### ISSUE TITLE
Windows 7 crash caused by showProgress value

### ISSUE THREAD

**Issue by fabnicol** [Rdatatable/data.table#1003]
Under Windows only (Linux runs fine) current github master code causes a crash on reading a csv table.

>library(data.table)
> fread("C:/Table.csv", header=TRUE, verbose=TRUE, skip="Matricule", showProgress=FALSE)
Error in fread("C:/Table.csv", header = TRUE, verbose = TRUE, skip = "Matricule",  : 
  showProgress must be 0 or 1, currently
> fread("C:/Table.csv", header=TRUE, verbose=TRUE, skip="Matricule", showProgress=TRUE)
Error in fread("C:/Table.csv", header = TRUE, verbose = TRUE, skip = "Matricule",  : 
  showProgress must be 0 or 1, currently

Changing value of the showProgress argument to 0 or 1 has no effect on the issue.
Omitting any arguments other than the table path has no effect either.

The coding issue seems to occur at line 428 of fread.c.

Below is a minimal base example and platform information.

Table.csv :

"Matricule","Name"
"0","A"
"1","B"

Platform is Windows 7 SP1, French locale, with Rtools 3.1.x fully installed and R.3.1.2 :
 
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

>locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

>attached base packages:
[1] compiler  stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
[1] data.table_1.9.5 gtools_3.4.1     assertthat_0.1   ggplot2_1.0.0    knitr_1.8        MASS_7.3-35     

>loaded via a namespace (and not attached):
 [1] chron_2.3-45     colorspace_1.2-4 digest_0.6.8     evaluate_0.5.5   formatR_1.0      grid_3.1.2       gtable_0.1.2     munsell_0.4.2   
 [9] plyr_1.8.1       proto_0.3-10     Rcpp_0.11.3      reshape2_1.4.1   scales_0.2.4     stringr_0.6.2    tools_3.1.2

**Comment by fabnicol** [comment]
The cause of the issue has been identified.

install_github(...) was called from a platform with proxy internet access. For some reason, the special customed Rtools install triggered by github code download did not work (and wasn't even launched) in this case. Proxy internet connexion/firewalls may well be the cause. Reinstalling on a fresh platform with appropriate internet connexion did fix the issue.

It is suggested to cleanly cause a crash of the install_github procedure in case that the customed Rtools did not install properly, as apparently prior Rtools installs (even fresh ones) may cause runtime issues.

**Comment by arunsrinivasan** [comment]
Thanks!
