### ISSUE TITLE
Support https directly in fread

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1005]
fread already supports http.  To support https, thanks to tip from Arun:  http://stackoverflow.com/questions/14441729/read-a-csv-from-github-into-r

**Comment by arunsrinivasan** [comment]
Committed a basic version here: e313fba41923e45611a9b9d4c1c87b55f2043b04

**Comment by arunsrinivasan** [comment]
Closing this for now. Will implement as we go.
