### ISSUE TITLE
Scoping of newly added columns

### ISSUE THREAD

**Issue by kykuo** [Rdatatable/data.table#1013]
Suppose I'm trying to add a couple columns where one depends on the other. It seems like I have two options:

```
data.table(iris)[
  , c("x", "y") := {
    x  <-  Sepal.Length * 2;
    y  <-  x^2;
    list(x, y)
    }][]
```

and

```
data.table(iris)[
  , x := Sepal.Length * 2][
    , y := x^2][]
```

I don't think either of these are elegant, and what I was hoping for is something like

```
data.table(iris)[
  ,`:=`(
    x = Sepal.Length *2,
    y = x^2)]
```

Which avoids curly braces, and adds the columns in the same bracket.

Is there a better way to do this, and, if not, why not?

**Comment by arunsrinivasan** [comment]
Some things that I've managed to recollect:

1. Suppose I want to do: `DT[, `:=`(x = x * 2, y = x^2)]` and I wanted `y = x^2` to the use the old `x`, I can't see a way to do it in a straightforward way.

2. Suppose I'd like to do: `DT[, `:=`(x = pmin(x,y), y = pmax(x,y))]` - this'd not give the result you'd want. This'd be a quite subtle bug, especially, to identify.

I think the current syntax solves these things straightforwardly while requiring `{}` for the operations you show. That is, we can do both.

However, if we update immediately, I don't see a straightforward way of accomplishing this without using temp variables.

**Comment by jangorecki** [comment]
Obviously you can always add columns in multiple steps, this may increase the readability of dependency between the columns:
```r
DT[, x:=x*2][, y:=x^2]
```
