### ISSUE TITLE
Make `setnames` to mimic `stats::setNames` when only one receiving only one names value

### ISSUE THREAD

**Issue by DavidArenburg** [Rdatatable/data.table#1028]
I often just want to renames all the names in my `data.table` object and I find inconvenient that I always need to enter the old names too. It seems that `names<-` and  `stats::setNames` are much easier to use in those cases. I wonder if it worth it mimic this behaviour when only the new names are entered, something like `setnames(DT, newnames)`. 

This is somewhat mimics the `xy.coords` behaviour which receives `x` and `y`, but if you only pass one variable, `x` becomes `y` and the `x` scale is generated by default using something like `seq_len(y)`

**Comment by arunsrinivasan** [comment]
From `?setnames`:

> `old` - When `new` is provided, character names or numeric positions of column names to change. **When `new` is not provided, the new column names, which must be the same length as the number of columns**. See examples.

**Comment by DavidArenburg** [comment]
Oh, OK, I should have tried it :)
