### ISSUE TITLE
.N returning NA instead of 0 when i is used

### ISSUE THREAD

**Issue by helix123** [Rdatatable/data.table#1034]
No sure whether this a bug report (or rather a check of documentation) or a feature request (for `.N` to differentiate between `nomatch=NA` and `nomatch=0`)

Not sure if this is related to #813.

```R
DT2 <- data.table(V1=c(1L,2L), V2=LETTERS[1:3], V3=LETTERS[1:6])

DT2[, .N, by=c("V2", "V3")]          # as expected
#    V2 V3 N
# 1:  A  A 1
# 2:  B  B 1
# 3:  C  C 1
# 4:  A  D 1
# 5:  B  E 1
# 6:  C  F 1

DT2[V1 == 2, .N, by=c("V2", "V3")]   # as expected
#    V2 V3 N
# 1:  B  B 1
# 2:  A  D 1
# 3:  C  F 1
```
At first I expected N to be all `0`s; but given i is evaluated first, the following makes sense to me.

```R
DT2[V1 == 3, .N, by=c("V2", "V3")] 
# Empty data.table (0 rows) of 3 cols: V2,V3,N

DT2[V1 == 3, .N, by=c("V2", "V3"), nomatch=NA] # as above; default
DT2[V1 == 3, .N, by=c("V2", "V3"), nomatch=0]   # as above
```

Does it make sense for `.N` to respect the nomatch and result in a different behaviour? For `nomatch=0`, I expected the following:

```R
DT2[V1 == 3, .N, by=c("V2", "V3"), nomatch=0] 
#    V2 V3 N
# 1:  B  B 0
# 2:  A  D 0
# 3:  C  F 0
```

`?data.table` says:

> When grouping by `i`, `.N` is the number of rows in `x` matched to, for each row of `i`, regardless of whether `nomatch` is `NA` or `0`.

Or maybe include that special case in the documentation or print a warning?

**Comment by helix123** [comment]
data.table_1.9.4 that is.

**Comment by jangorecki** [comment]
I assume it behaves as expected. Tested on 1.9.5 and have the same output.
- AFAIK the `nomatch` is designed to be used on join (when `i` is a data.table).
- `i` is designed to filter data.table before making aggregation by `by`, similarly as *SQL where* statement.

I not able to understand your expected output - why you expect 3 rows instead of 6, when there are 6 unique combinations of `V2, V3` so I cannot give you solution which would provide expected results.

**Comment by arunsrinivasan** [comment]
`DT[i, j, by]` takes the rows resulting from the expression in `i` and *then* computes `j` while grouped by `by`. Your condition `V1 == 3` already results in 0 rows.. Therefore there's nothing to do group by.

The `nomatch` argument is only valid for *binary search based subsets*. Now I think, it may be useful to have `nomatch = 0L` as the default to be consistent with vector scan results. Not sure though.

So if you do:

```R
setkey(DT2, V1)
DT2[.(3)] # will return NA because nomatch=NA by default
DT2[.(3), .N] # will return 1
```
In either case, I don't understand your output as to why all rows are returned when you've already subsetted the rows for `V1 == 3`.

I don't really see an issue here.
