### ISSUE TITLE
Docs: explain and document the i.col notation for joins

### ISSUE THREAD

**Issue by smartinsightsfromdata** [Rdatatable/data.table#1038]
I basically discovered the i.col notation by accident. I've even asked a question on so  about it (as I wasn't sure if it was kosher!). see [here](http://stackoverflow.com/questions/28431771/assigning-values-from-one-data-table-to-the-other-with-a-join?noredirect=1#comment45205951_28431771)

I haven't seen in either the FAQ, the intro or the cheat sheet.  I haven't finished yet the data camp course on data table but it wasn't in any part of the training I've done so far (incidentally, I would love to give you guys some feedback on the training, but I'm not sure where to do it).

Would it be possible to add examples of the i.col notation to the examples and (all the) docs please?

**Comment by arunsrinivasan** [comment]
Thanks. Will remember to document it in the vignettes.
On feedbacks, both Matt's and my email are available on our github pages - https://github.com/mattdowle and https://github.com/arunsrinivasan.

**Comment by arunsrinivasan** [comment]
Added to `?data.table`. Will close after adding to vignette.
