### ISSUE TITLE
Invalid .internal.selfref detected

### ISSUE THREAD

**Issue by tyner** [Rdatatable/data.table#1040]
From a fresh install off of github:

    library(data.table)
    data.table 1.9.5  For help type: ?data.table
    *** NB: by=.EACHI is now explicit. See README to restore previous behaviour.
    dt <- data.table(a = 1:10, b = 1:10)
    dt[["a"]] <- dt[["a"]] / dt[["b"]]
    dt[, ab := a * b]

gave:

    Warning message:
    In `[.data.table`(dt, , `:=`(ab, a * b)) :
      Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or been created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting. If this message doesn't help, please report to datatable-help so the root cause can be fixed.

Here is my:

    sessionInfo() 
    R version 3.0.2 (2013-09-25)
    Platform: x86_64-pc-linux-gnu (64-bit)
    
    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
     [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
     [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
     [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] data.table_1.9.5 devtools_1.7.0  
    
    loaded via a namespace (and not attached):
    [1] bitops_1.0-6   chron_2.3-45   httr_0.6.1     RCurl_1.95-4.5 stringr_0.6.2 
    [6] tcltk_3.0.2    tools_3.0.2

Note that though my R is somewhat antiquated, I have seen the same issue under version 3.1.2 (on another machine).

Regards,
B. Tyner

**Comment by arunsrinivasan** [comment]
The error message clearly explains what the issue is. The idiomatic way to do:

```R
dt[["a"]] <- dt[["a"]] / dt[["b"]]
```

is

```R
dt[, a := a/b]
```
Else the assignment destroys the over-allocation of data.tables. It has to be over-allocated again, therefore (hence the warning).

**Comment by tyner** [comment]
I realize it is non-idiomatic, but I thought data tables were supposed to be compatible with functions that only accept data frames (which `[[<-.data.frame` is, no?). The message said to avoid using structure(), key<-, names<- and attr<-, and I have dutifully not used any of these, and the message also said to report it to the list. If my understanding is deficient, please educate me.

Regards

**Comment by arunsrinivasan** [comment]
The issue is not compatibility, it is completely compatible. But as the error message mentions, R v< 3.1 copies the data on assignment using `<-`, which also for some reason resets the true length to 0 (meaning, over allocation is gone). We can't do anything about it, except ask you to upgrade to latest version, where this seems to not have come up so far.

**Comment by tyner** [comment]
Thanks for the clarification. I have seen the same exact issue under version 3.1.2. I can try under R-devel if this is advisable.

**Comment by arunsrinivasan** [comment]
I think if you try `dt$a <- ...` you won't get the message. Seems like `dt[[..]]` still seems to reset true length. And we can't really do anything about it, unfortunately.

**Comment by valentas-kurauskas** [comment]
Why is this closed? @arunsrinivasan  I don't completely understand why we can't do anything about it?

 I am getting this error on R version 3.3.2 and data.table_1.10.0. So at the very minimum, this part of warning is not relevant:

     "Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting."

But more importantly I thought that `dt[['a']] <- ...` was a nice way to set columns by name, which works both for data.frame and data.table. Is there any alternative?
