### ISSUE TITLE
[REQUEST] fread() from connection

### ISSUE THREAD

**Issue by sonyisos** [Rdatatable/data.table#1041]
We're moving all of our read.csv calls to use fread and we've got some read.csv that reads pretty big (~1-100 million rows) CSVs from sockets (we've got a c++ app that generates the data we need) but read.csvs poor performance is a huge hit.

Right now I'm using 
dt.list <- list()
iteration <- 0
while(..) {
  iteration <- iteration+1  
  data = readLines(my.socket, n=10000)
  dt.list[[iteration]] <- fread(paste(data, collapse="\n"), header=F)
}
dt <- rbindlist(dt.list)

But it looks like a really ugly and under-performing patch so is there any more elegant way to do it or can u add this feature?

Thanks!

**Comment by sonyisos** [comment]
Now that I understand a bit more I would request that it would work with any connection.
I understand it might not be possible because it's implemented in C where these R objects probably invalid objects that does nothing but just in case the R-C interface allows this kinda stuff I'm keeping this on.

**Comment by bph98** [comment]
I would love to see this as well.  Is this a duplicate with [#561](https://github.com/Rdatatable/data.table/issues/561)?

**Comment by arunsrinivasan** [comment]
Yes, dup of https://github.com/Rdatatable/data.table/issues/561.
