### ISSUE TITLE
data.table /devtools: data.table class detection for packages loaded with devtools::load_all()

### ISSUE THREAD

**Issue by stephlocke** [Rdatatable/data.table#1044]
I'm writing functions utilising `data.table` in a package and using `devtools` as part of my development workflow. `data.table` functions called within functions that get loaded via `devtools::load_all()` do not pick up the `data.table` class in the internal `data.table` class checks.

```
library(devtools)
create(path="repexample",rstudio = FALSE)
use_package("data.table",pkg="repexample")

# Create a function in folder repexample/R -----
# mydtcheck<-function(x){
#   x[,b:=2]
# }

load_all("repexample")

library(data.table)
exampledt<-data.table(a=1)
mydtcheck(exampledt)

#Error in `:=`(b, 2) : 
#  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once 
# only and in particular ways. See help(":=").
```

I've checked this on two different OS/ R instances (both using devtools_1.7.0, but have checked with 1.9.4 and 1.9.5 data.table versions)

**Comment by jangorecki** [comment]
I'm testing the example and as for now it seems the `use_package` does not add required `import(data.table)` to `NAMESPACE`. Will update if I find some more on that.

**Comment by arunsrinivasan** [comment]
@jangorecki thanks for tracking the issue. That is most likely the issue (from previous experiences on similar issues from SO).

**Comment by stephlocke** [comment]
Adding to the NAMESPACE resolves the issue - will have to check my package tomorrow for it. Ta both!

@arunsrinivasan - if it's alright, I'll put a wiki page on how to use data.table as a dependency. IIRC, there's things like if you use data.table inside new environments, you need some sort of whitelisting on the data.table side to minimise issues. May just help avoid mistakes like mine, build up some SEO to the wiki, and save some SO questions.

**Comment by arunsrinivasan** [comment]
@stephlocke, sounds great! Thanks.

**Comment by arunsrinivasan** [comment]
@stephlocke do I understand it right that the issue is resolved?
