### ISSUE TITLE
Inconsistent return type when selecting columns with option with=FALSE

### ISSUE THREAD

**Issue by kamicollo** [Rdatatable/data.table#1045]
Hi,

I have to admit I just started using the data.table package, so really sorry if this ticket is not to the point, but I found the below behavior quite strange. Let me also say in advance that I know how to solve it, yet I still believe the inconsistency should be considered a bug.

In particular, consider this data table:
```
DT <- data.table(a=1:3, b=4:6)
```

Simple column selection returns a list, i.e.:
```
class(DT[, a])
#returns "integer"
```
However, a column selection with a "dynamic" name returns a data table:

```
class(DT[, "a", with=F])
#returns "data.table data.frame"
```
The same applies if the column name is stored in a variable (which is the actual use case I ran into).

I know a solution for that, namely using list selection `DT[["a"]]`, but I would still think that data table's API would benefit from consistency here.

R version 3.1.2, data.table_1.9.4.

Cheers,
Aurimas

**Comment by DavidArenburg** [comment]
I agree with you because according to the documentation `DT[, "a", with = FALSE]` should be *similar to a `data.frame`*, whereas if we would do `setDF(DT); DT[, "a"]` we would get a vector instead of a `data.frame`...

**Comment by arunsrinivasan** [comment]
This has been discussed many times. `data.table` does not (and in all likeliness will not) have a `drop` argument. If you want to subset the `data.frame` way to return a vector, use `DT[["a"]]`.
