### ISSUE TITLE
[bug] [Question] minor typo in rbindlist documentation

### ISSUE THREAD

**Issue by micstr** [Rdatatable/data.table#1047]
In documentation for rbindlist, under the first line of Usage:

```
Makes one data.table from a list of many
Description
Same as do.call("rbind", l) on data.frames, but much faster. See DETAILS for more.
Usage
rbindlist(l, use.names=fill, fill=FALSE)
HASH rbind(..., use.names=TRUE, fill=FALSE)
```
 
I think use.names = **fill** should read use.names = **TRUE**?

I was not sure if I should classify this as Request or Bug hence the Question in Title.

using:
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
other attached packages:
[1] data.table_1.9.4

**Comment by ChristK** [comment]
I think this means that use.names is defined by the fill as default. So if fill = FALSE then use.names = FALSE, and if fill  = TRUE then use.names = TRUE if use.names not set differently by the user.

**Comment by arunsrinivasan** [comment]
@ChristK is right on. But glad you asked, @micstr.
