### ISSUE TITLE
Discrepancy between dt[var %in% c(val1, val2)] and dt[(var == val1) | (var == val2)]

### ISSUE THREAD

**Issue by MaxGhenis** [Rdatatable/data.table#1049]
Row-level subsetting using `%in%` returns incorrect results in a specific case, unfortunately not reproducible - it seems to be something wrong with the type of value in my data.table column. The data is also not shareable, otherwise I'd like to an .rd file. I'm on data.table 1.9.4.

Here's the set of results, where `dt$var` is the problem:

```r
dt[, .N, var]  # This works correctly
#    var     N
# 1:   GG13 33303
# 2:   GG14 39479
# 3:   GG15 48627
dt[var == "GG15", .N]  # 48019: different from 48627 above
dt[var %in% c("GG15"), .N]  # Also 48019
dt[(var == "GG14") | (var == "GG15"), .N]  # 88106 (=39479+48627, so this works correctly)
dt[var %in% c("GG14", "GG15"), .N]  # 12943: This fails severely - should be 88106
# Creating a new variable unbreaks it
dt[, var2 := var]
dt[var2 %in% c("GG14", "GG15"), .N]  # 88106: correct
# No dup column names
length(names(dt)) == length(unique(names(dt)))  # TRUE
```

Once identified, wasn't a big problem, but it went under the radar and created problems.

**Comment by arunsrinivasan** [comment]
Please try always with the latest development version (currently 1.9.5) before filing.

If you're able to reproduce it in 1.9.5, please file an issue again (or reopen this one), with a minimal example. Thanks.

**Comment by MaxGhenis** [comment]
Has any error like this been reported in the past? I'm in an organization where we're limited to CRAN, wondering how careful we have to be until 1.9.6 is pushed. Thanks.

**Comment by DavidArenburg** [comment]
Try using ````r
%chin%
`````
instead until v 1.9.6 will be released
