### ISSUE TITLE
by = list(round(x1, 2), ...) renames columns

### ISSUE THREAD

**Issue by pimentel** [Rdatatable/data.table#1051]
This issue came up at the [dplyr repo](https://github.com/hadley/dplyr/issues/883#issuecomment-75350617). The basic idea is that when a column name has a space in it, `data.table` renames the column:

```{r}
set.seed(42)
test.data <-
  data.frame(
    x1 = rnorm(100),
    x2 = rnorm(100),
    y = rnorm(100) )
a_dt <- data.table(test.data)
a_dt[, c("round(x1, 0)", "round(x2, 0)") := list(round(x1, 0), round(x2, 0))]
head(a_dt[,list(mean = mean(y)), by = list(round(x1, 0), round(x2, 0))])
```

With output:
```{r}
   round round         mean
1:     1     1 -0.286135195
2:    -1     1 -0.031488885
3:     0    -1 -0.003694665
4:     1     2  2.059539242
5:     0     0 -0.243933772
6:     2     0  0.387569383
```

is this expected behavior?

Thanks a bunch,

Harold

**Comment by jangorecki** [comment]
It did not rename column but apply `round` functions again on the `x1` and `x2`. If you want to group by `round(x1, 0)` column instead of the function call results use the following:
```r
head(a_dt[,list(mean = mean(y)), by = list(`round(x1, 0)`, `round(x2, 0)`)])
```

**Comment by pimentel** [comment]
Fantastic! Thanks!
