### ISSUE TITLE
Columns selected with DT$COL or DT[["COL"]] stay linked to data table

### ISSUE THREAD

**Issue by ahardjasa** [Rdatatable/data.table#1052]
I'm not sure if this is intentional, but it seemed like unexpected behaviour to me. If a data table column referenced with $ or [[ is used elsewhere, when the original data table is keyed by that column, the column is reordered wherever else it is used. This does not happen if the column is selected with the DT[, COL] syntax, although str(DT$COL) and str(DT[, COL]) look identical. Example below. I'm using data.table version 1.9.4.

```R
dt <- data.table(ID = c("ID_1_Cat", "ID_2_Cat", "ID_1_Dog", "ID_2_Dog"), val = factor(c("Cat", "Cat", "Dog", "Dog")))
mat1 <- sapply(levels(dt$val), function(x) as.numeric(dt$val == x))
rownames(mat1) <- dt[, ID]
mat1 #cat is cat, dog is dog

mat2 <- sapply(levels(dt$val), function(x) as.numeric(dt$val == x))
rownames(mat2) <- dt$ID
mat2 #cat is cat, dog is dog

setkey(dt, ID)
mat1 #cat is cat, dog is dog
mat2 #ID_1_Dog is cat, ID_2_Cat is dog??

**Comment by arunsrinivasan** [comment]
In `data.table` all `set*` operations and `:=` operation modifies the object by reference. Have a look at the *Reference semantics* vignette linked [here](https://github.com/Rdatatable/data.table/issues/944), especially section 3 - `:=` and `copy()`.
