### ISSUE TITLE
Table doesn't initially print after setting column using := inside a function

### ISSUE THREAD

**Issue by abielr** [Rdatatable/data.table#1054]
Using the development version of data.table, downloaded on Feb 26, 2015, I find that a `data.table` created inside a function and then modified using the `:=` notation doesn't print anything to the screen initially, unless `print()` is called explicitly. However, _after_ the first attempt to show the return value, everything works as expected. The code below demonstrates the issue (R 3.1.1 64-bit on Windows 7, replicated both inside RStudio and R GUI).
```r
testfunc <- function() {
  dat <- data.table(x1=1:10)
  dat[, x1 := 1]
  dat
}

x <- testfunc()
x # Doesn't print anything to the screen, although print(x) would have worked
x # Second time works
    x1
 1:  1
 2:  1
 3:  1
 4:  1
 5:  1
 6:  1
 7:  1
 8:  1
 9:  1
10:  1
```

**Comment by arunsrinivasan** [comment]
Please have a look at the `README.md` file, point (1) under *Bug fixes*.
