### ISSUE TITLE
[request] shift {data.table}: variable name generation (give.names) using variable name (x) to avoid V1 when not using .SD

### ISSUE THREAD

**Issue by JulianBo** [Rdatatable/data.table#1056]
Inside the new shift function (many thanks, by the way), give.names=TRUE uses the variable names when using .SD. However, it does not uses variable names when putting them directly to x. Instead standard variable names V1,... are used (note the difference in the below example). 

As it is pointed out in the help-file: `"give.names.	
default is FALSE which returns an unnamed list. When TRUE, names are automatically generated corresponding to type and n. "` (But not x!)

Could a feature be added that names are generated corresponding to  x as well, when not using .SD?
  
    DT = data.table(year=2010:2014, v1=runif(5), v2=1:5, v3=letters[1:5])
    DT[, shift(.SD, 1:2, NA, "lead", TRUE), .SDcols=2]
    #     v1_lead_1    v1_lead_2
    # 1: 0.82729735 0.54176449
    DT[, shift(v1, 1:2, NA, "lead", TRUE)   ]
    #      V1_lead_1  V1_lead_2
    #1: 0.82729735 0.54176449

**Comment by arunsrinivasan** [comment]
Yes, that'd be nice to have. Just committed. Thanks!
