### ISSUE TITLE
[request] recursion

### ISSUE THREAD

**Issue by davids99us** [Rdatatable/data.table#1057]
```R
recursive<-function(D) {
  print(nrow(D))
  if (nrow(D)<3) return(D)
  D[,group:=cut(test,2)]
  D[,recursive(.SD),by=group]
}
T=data.table(test=rnorm(10))
recursive(T)

> source('~/R 2/Anomaly/examples/ex5.R')
[1] 10
[1] 8
# Error in `[.data.table`(D, , `:=`(group, cut(test, 2))) : 
#   .SD is locked. Using := in .SD's j is reserved for possible future use; a tortuously flexible way 
# to modify by group. Use := in j directly to modify by group by reference.
```
Great package.  It is super solid and has changed the way I program in a week.  Shouldn't it support recursion though?  Thanks

**Comment by arunsrinivasan** [comment]
I'm not sure what you're trying to do here, but it's not recursion that's the problem, but that you're tying to modify `.SD` by reference (using `:=`). Change `recursive(.SD)` to `recursive(copy(.SD))` and your function should run without this error.

**Comment by davids99us** [comment]
Thanks Arun.
