### ISSUE TITLE
Auto-indexing prevents lazy comparison of dates

### ISSUE THREAD

**Issue by stephlocke** [Rdatatable/data.table#1058]
Not that I condone such lazy behaviour but v1.9.5's auto-indexing has an impact on cases where date columns get compared to a string hoding a date. 

My boss has been caught out by this and I have slapped his wrist though about being lazy and not doing it with an `as.Date()`! If it's a "Won't fix" could it be emphasised in the docs that it's a potentially breaking change. 

```
blah<-data.table(a=Sys.Date())
blah[a=="2015-03-02"]

options(datatable.auto.index=FALSE)
blah<-data.table(a=Sys.Date())
blah[a=="2015-03-02"]
```

**Comment by arunsrinivasan** [comment]
Have you tried this on the latest commits of v1.9.5? What's the output you get between the two?

**Comment by stephlocke** [comment]
Amazing how much progress you make in just a couple of days! I last downloaded sometime week. Cheers - fixed now
