### ISSUE TITLE
Auto index matches wrong index (because of partial match)

### ISSUE THREAD

**Issue by colinfang** [Rdatatable/data.table#1061]
data.table 1.94 (I haven't checked for 1.95)
```{r}
> a <- data.table(x=rep(c('a', 'b','c'), 4), x2=rep(1:2, 6))
> a
    x x2
 1: a  1
 2: b  2
 3: c  1
 4: a  2
 5: b  1
 6: c  2
 7: a  1
 8: b  2
 9: c  1
10: a  2
11: b  1
12: c  2
> a[x2==1, verbose=T]
creating new index 'x2'
   x x2
1: a  1
2: c  1
3: b  1
4: a  1
5: c  1
6: b  1
> a[x=='a', verbose=T] # Here, it matches x to x2.
using existing index 'x'
Starting bmerge ...done in 0.001 secs
   x x2
1: a  1
> key2(a)
[1] "x2"
```

Pretty obvious bug. I guess internally the column name is matched against the existing index list using `[[` or `$` partial matching, which causes the issue here.

**Comment by arunsrinivasan** [comment]
This is fixed in 1.9.5

**Comment by colinfang** [comment]
good to see it is already fixed. I posted here because I cannot find the corresponding mention of such bug in the release note for 1.9.5.

**Comment by arunsrinivasan** [comment]
The entire list of bugs under (6) in 1.9.5 corresponds to all auto indexing bugs that have been fixed.
