### ISSUE TITLE
[Question] Generically normalized data operation

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1064]
I wrote a helper which can be useful in case if data model requires the generically normalized structure in [EAV](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model).
On the following dataset:
```r
#           time product measure_name measure_value
#  1: 2015-03-04       4        gross     127.20171
#  2: 2015-03-03       1        gross      94.12162
#  3: 2015-03-02       2        gross     144.55868
#  4: 2015-03-01       3        gross     100.80579
#  5: 2015-02-28       5        gross      89.53581
#  6: 2015-03-04       4          tax       0.20000
#  7: 2015-03-03       1          tax       0.40000
#  8: 2015-03-02       2          tax       0.10000
#  9: 2015-03-01       3          tax       0.20000
# 10: 2015-02-28       5          tax       0.40000
```
Perform calculation between the *gross* and *tax* measures to calculate *net* value:
```r
#           time product measure_name measure_value
#  1: 2015-02-28       5        gross      89.53581
#  2: 2015-02-28       5          tax       0.40000
#  3: 2015-02-28       5          net      53.72149
#  4: 2015-03-01       3        gross     100.80579
#  5: 2015-03-01       3          tax       0.20000
#  6: 2015-03-01       3          net      80.64463
#  7: 2015-03-02       2        gross     144.55868
#  8: 2015-03-02       2          tax       0.10000
#  9: 2015-03-02       2          net     130.10281
# 10: 2015-03-03       1        gross      94.12162
# 11: 2015-03-03       1          tax       0.40000
# 12: 2015-03-03       1          net      56.47297
# 13: 2015-03-04       4        gross     127.20171
# 14: 2015-03-04       4          tax       0.20000
# 15: 2015-03-04       4          net     101.76137
```

My function which done that works fine, but I'm thinking of releasing it in *dwtools*, or if you find it interesting also in *dt*.
Maybe you can give some hint how to make it more generic and to use most of melt/dcast features, but also to make it proof for the future changes in data.table code.

Full example below:
```r
library(magrittr)
library(data.table)
normDTj <- function(x, j, id.vars, variable.name, measure.vars, fun.aggregate){
    stopifnot(is.data.table(x))
    x[,lapply(.SD,fun.aggregate),c(id.vars,variable.name),.SDcols=measure.vars] %>%
        dcast(formula=as.formula(paste(paste(id.vars,collapse=' + '),paste(variable.name,collapse=' + '),sep=' ~ ')),fun.aggregate=fun.aggregate,value.var=measure.vars) %>%
        `[`(j = eval(j), by = eval(id.vars)) %>%
        melt(id.vars=id.vars, variable.name=variable.name, value.name=measure.vars) %>%
        setkeyv(cols=c(id.vars,variable.name)) %>% # sort
        `[`() # print
}
set.seed(38)
# regular tabular structure
dt <- data.table(time=structure(16498:16494,class="Date"),product=sample(1:10,5,FALSE),gross=rnorm(5,100,40),tax=sample(1:4,5,TRUE)/10)
# generically normalization of data
dt <- melt(dt, id=1:2, variable = "measure_name", value = "measure_value")
# calculate new measures on generically normalized data
normDTj(dt, j = quote(net:=gross*(1-tax)), id=c('time','product'), variable='measure_name', measure='measure_value', fun=sum)
```
Looking forward for any feedback, not only Matt and Arun :)

PS. I know I could do below and rbind it to `dt` but it seems to be less generic and more error prone
```r
dt[,.(measure_name = 'net', measure_value = measure_value[measure_name=='gross']*(1-measure_value[measure_name=='tax'])),.(time,product)]
```

**edit**: I've made it a little better for standard use cases, all the arguments are guessed from the `key(x)` and I've add `shift.vars` which allows to use `shift` function in `j` arg. Till the end of week I should have it available in [dwtools](https://github.com/jangorecki/dwtools).

**Comment by arunsrinivasan** [comment]
Nice! This seems quite specific for `data.table` though.

Keeping the data in wide format makes more sense to me here. It avoids all the hassle and unnecessary grouping.

i.e., if your data were available in this format already:

```R
dt.c = dcast(dt, time + product ~ measure_name, value.var="measure_value")
#          time product     gross tax
# 1: 2015-02-28       5  89.53581 0.4
# 2: 2015-03-01       3 100.80579 0.2
# 3: 2015-03-02       2 144.55868 0.1
# 4: 2015-03-03       1  94.12162 0.4
# 5: 2015-03-04       4 127.20171 0.2
```

Then all you need to do is:
```R
dt.c[, net := gross * (1-tax)]
#          time product     gross tax       net
# 1: 2015-02-28       5  89.53581 0.4  53.72149
# 2: 2015-03-01       3 100.80579 0.2  80.64463
# 3: 2015-03-02       2 144.55868 0.1 130.10281
# 4: 2015-03-03       1  94.12162 0.4  56.47297
# 5: 2015-03-04       4 127.20171 0.2 101.76137
```
PS: I find `dcast` automatically sorting the data by formula LHS quite annoying.

**Comment by jangorecki** [comment]
Of course keeping data in the regular wide format table is the easiest and conceptually best way, but there are cases where data model requires long format, as mentioned [Entity–attribute–value model](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model). It allows to add columns (in that particular case a *net* measure) without altering the model, but with just inserting rows. It might not be in-line with the data.table concept where it is *cheaper* to add a column than row but when working with databases it can be handy.
One of the downsides of EAV (and other higher normalization forms) is the cost transforming data to wide format, data.table can address costs quite effectively :)
Once I release it in dwtools I will close that issue.

**Comment by arunsrinivasan** [comment]
I guess that depends on whether the database you're working with are column-based or row-based, isn't it? Besides, since you're working *in-memory* and using data.tables, I don't see a strong point. If you'd want to work with database, then you can melt and write to it?

However, I'm not aware of the model, and other operations you'd perform with it. So, please feel free to disregard my take.

**Comment by jangorecki** [comment]
Not particularly.
Row/column wise storage in databases is kind of lowest level infrastructure which will organize the data internally. It is vendor designed.
Data model, like EAV or the most popular 3NF, is higher level, user designed way of storing data in db (can be both rows or column oriented db, but rows is the common one), which has to enhance the ability to insert data, query data, capture changes in the data, etc. It is heavily dependent on the business requirements.
I've commit it to dwtools. It is now much more user-friendly cause it is taking most of parameters from the key:
```r
devtools::install_github("jangorecki/dwtools")
# basic product EAV
dt <- data.table(product=c(1,1,2,2,3,3),
                 attribute=rep(c('amount_in_pack','price'),3),
                 value=c(24,115,5,200,8,20.5),
                 key=c('product','attribute'))
dt
eav(dt, quote(price_of_pack := price * amount_in_pack))
```
more examples on [?eav](https://raw.githubusercontent.com/jangorecki/dwtools/master/tests/example-eav.R).
