### ISSUE TITLE
Unexpected duplications in data.table after filtering depending on classes

### ISSUE THREAD

**Issue by holgerman** [Rdatatable/data.table#1071]
Hi,

first, thanks very much for data.table, which is incredbibly helpful in my work.
I encountered an unexpected behaviour in 1.9.4 
In this example, my aim was to filter a data.table. Depending on classes, this sometimes resulted in duplications of rows:

require(data.table)
`## Loading required package: data.table`
##unexpected behaviour with duplication a and dt1$da are both numeric
a = c(1,1,2)
str(a)
`##  num [1:3] 1 1 2`
dt1 = data.table(da = c(1,1,3), db = letters[1:3])
dt1
`##    da db`
`## 1:  1  a`
`## 2:  1  b`
`## 3:  3  c`
dt1[da %in% a] ##duplicated
`##    da db`
`## 1:  1  a`
`## 2:  1  b`
`## 3:  1  a`
`## 4:  1  b`
##unexpected behaviour with duplication a and dt1$da are both integer

a = as.integer(c(1,1,2))
str(a)
`##  int [1:3] 1 1 2`
dt1 = data.table(da = as.integer(c(1,1,3)), db = letters[1:3])
dt1
`##    da db`
`## 1:  1  a`
`## 2:  1  b`
`## 3:  3  c`
dt1[da %in% a] ##duplicated
`##    da db`
`## 1:  1  a`
`## 2:  1  b`
`## 3:  1  a`
`## 4:  1  b`
##expected behaviour without duplication if a and dt1$da are different classes
a = as.integer(c(1,1,2))
str(a)
`##  int [1:3] 1 1 2`
dt1 = data.table(da = c(1,1,3), db = letters[1:3])
dt1
`##    da db`
`## 1:  1  a`
`## 2:  1  b`
`## 3:  3  c`
dt1[da %in% a] ##non duplicated
`##    da db`
`## 1:  1  a`
`## 2:  1  b`
##expected behaviour without duplication if a and dt1$da are different classes (vice versa)
a = c(1,1,2)
str(a)
`##  num [1:3] 1 1 2`
dt1 = data.table(da = c(1L,1L,3L), db = letters[1:3])
dt1
`##    da db`
`## 1:  1  a`
`## 2:  1  b`
`## 3:  3  c`
dt1[da %in% a] ##non duplicated
`##    da db`
`## 1:  1  a`
`## 2:  1  b`
sessionInfo()

`## R version 3.1.2 (2014-10-31)`
`## Platform: x86_64-w64-mingw32/x64 (64-bit)`
`## `
`## locale:`
`## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   `
`## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   `
`## [5] LC_TIME=German_Germany.1252    `
`## `
`## attached base packages:`
`## [1] stats     graphics  grDevices utils     datasets  methods   base     `
`## `
`## other attached packages:`
`## [1] data.table_1.9.4`
`## `
`## loaded via a namespace (and not attached):`
`##  [1] chron_2.3-45    digest_0.6.8    evaluate_0.5.5  formatR_1.0`    
`##  [5] htmltools_0.2.6 knitr_1.9       plyr_1.8.1      Rcpp_0.11.4    `
`##  [9] reshape2_1.4.1  rmarkdown_0.5.1 stringr_0.6.2   tools_3.1.2`

**Comment by arunsrinivasan** [comment]
Thanks. This is due to a bug in the new feature *auto indexing* in `v1.9.4` that has since then been fixed in the current development version, `1.9.5`. Either upgrade to devel version by following [these instructions](https://github.com/Rdatatable/data.table/wiki/Installation) or disable *auto indexing* by doing `options(datatable.auto.index=FALSE)`, and then try your code.

Please read the `README.md` file for latest news and bug fixes. Also please read the `Contributions.md` instructions and [github flavoured markdown](https://help.github.com/articles/github-flavored-markdown/) for future reports..

**Comment by holgerman** [comment]
@Arun OK, thanks for the quick reply!
