### ISSUE TITLE
fread fails with double quotes at the beginning of a field

### ISSUE THREAD

**Issue by daroczig** [Rdatatable/data.table#1077]
The CRAN (1.9.4) version of `data.table` silently ignores this issue and returns and empty object:

```r
fread('2,3\n""foo,bar')
## Empty data.table (0 rows) of 1 col: "foo,bar
````

The development version (32975cd4a8ea89a80486bf5f65111831d7d460b2) fails with an error:

```r
fread('2,3\n""foo,bar')
## Error in fread("2,3\n\"\"foo,bar") : 
##   Field 1 on line 2 starts with quote (") but then has a problem. It can contain balanced unescaped quoted subregions but if it does it can't contain embedded \n as well. Check for unbalanced unescaped quotes: ""foo,bar
```

I'm aware of the fact that this "CSV" is not well formed, but that's what I get :( Is there a way to sepcify something like `quote=''`?

**Comment by arunsrinivasan** [comment]
Thanks for the report. `quote = ""` is implemented. Either use that, or wrap your file with `""` around character columns so that `quote = "\""` can then read it properly. See `?fread` quote argument.

**Comment by daroczig** [comment]
Awesome, thank you very much, @arunsrinivasan & keep up the food work :100:

**Comment by arunsrinivasan** [comment]
👍🏽 thanks. Please write back if something's not right.

Arun

**Comment by arunsrinivasan** [comment]
Removed quote argument with a better fix (slightly more robust) for quotes. Please upgrade and test.

**Comment by daroczig** [comment]
Thanks! For the record, related commit: 9cb1f60be5bdb37c203c18d41b4bd2b7d73a7021
