### ISSUE TITLE
setDT method for tbl_df class

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1078]
Output of many function in dplyr pkg is a `tbl_df` class objects. It is not handled correctly by `setDT` which works on regular df and lists very well. See below:
```r
packageVersion("dplyr")
# [1] ‘0.4.1’
packageVersion("data.table")
# [1] ‘1.9.5’
library(dplyr) # latest CRAN
library(data.table) # latest dev

df <- data.frame(a = rnorm(1000), b = sample(1:5,1000,TRUE))
class(df)
# [1] "data.frame"
df2 <- as.tbl(df)
class(df2)
# [1] "tbl_df"     "tbl"        "data.frame"
setDT(df2)
class(df2)
# [1] "tbl_df"     "tbl"        "data.table" "data.frame"
```
Would be great to have `setDT` works on `tbl_df` and possibly also `tbl` classes.
Currently such object is not usable without using first `setDT(as.data.frame(df2))[]`.

**Edit**
Or easier/faster operating directly on class attribute: `setattr(df,"class",c("data.table","data.frame"))`

**Comment by arunsrinivasan** [comment]
#1128 also seems related. Possible fix is as follows:

* If an object is already a `data.table` with additional classes, we retain in any and all operations possible (current behaviour as such need not be modified).

* If an object is converted from another object to `data.table`, then we simply *do not* retain classes.
