### ISSUE TITLE
fread input random lines.  Sampling

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1084]
Hello.
It would be great if data.table's function fread (or other import functions) were able to read random rows from a file, I think this is also called "sampling" lines (nonconsecutive rows). 

As far as I know it can only read a single contiguous range.

There could be two options:
- The user could pass it a vector of numbers specifying the lines to be read.
- Or, the easiest way, just leave fread to read the rows he wants, for example using uniform random number generator to choose them.

Reading a file in this way would allow the user to have a quick glimpse of very big files.

**Comment by mgahan** [comment]
The `shuf` command already allows for this.

`fread("shuf -n 5 iris.csv")`

**Comment by RanaivosonHerimanitra** [comment]
+1

**Comment by skanskan** [comment]
@mgahan
I get this error:
 'shuf' is not recognized as an internal or external command,

Maybe that's only available on linux. Isn't it?

**Comment by mgahan** [comment]
Good point @skanskan. I am not sure how to do this on Windows.

**Comment by skanskan** [comment]
That's why I think it could be implemented directly on fread, I think it shouldn't be difficult.

**Comment by MichaelChirico** [comment]
This is basically #583 in disguise.
