### ISSUE TITLE
LHS of parsed formula did not result in character vector

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#1085]
I'm using the latest dev version of data.table.

A simple `dcast.data.table` example produces the following error, breaking my previously working code.

Create a simple `data.table`:

```r
p <- data.table(x=c("a","a","b","b"), y=c("m","n","n","m"), z=c(1,2,3,4))
```

Use `reshape2::dcast` to transform

```rconsole
> reshape2::dcast(p, x ~ y, value.var = "z", fun.aggregate = mean)
  x m n
1 a 1 2
2 b 4 3
```

But with `data.table::dcast.data.table` an error occurs

```rconsole
> dcast.data.table(p, x ~ y, value.var = "z", fun.aggregate = mean)
Error in dcast.data.table(p, x ~ y, value.var = "z", fun.aggregate = mean) : 
  LHS of parsed formula did not result in character vector, possibly invalid formula
```

I'm not sure why it happens.

My session info:

```rconsole
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.5

loaded via a namespace (and not attached):
[1] chron_2.3-45 tools_3.1.3 
```

**Comment by arunsrinivasan** [comment]
Thanks, but I'm unable to reproduce it on 1.9.5 (commit 1793) (tested on R v3.1.2 and v3.1.3).

**Comment by renkun-ken** [comment]
I install from commit 4db0c4356c and the problem is gone.

**Comment by arunsrinivasan** [comment]
Thanks. Note that you don't have to load `reshape2` to use `melt` / `dcast` anymore. And you don't have to spell out `dcast.data.table` anymore, just `dcast()` is sufficient. If you have to load `reshape2`, load it before `data.table` (this is also documented in `?dcast.data.table`).
