### ISSUE TITLE
prettier print of data.table

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1091]
A FR for mainly character processing just right before the print.
When DT is already filtered to non more than 100 rows (default print nrow).
There might be character processing, like:
a) detect and handle `\n`
b) trunc character after `x` nchars
```r
library(data.table)

dt <- data.table(a = 1:3, b = c("asda\nzxcz","asdas","CREATE TABLE ASD AS\nSELECT *\nFROM DUAL"))
dt # current
#    a                                        b
# 1: 1                               asda\nzxcz
# 2: 2                                    asdas
# 3: 3 CREATE TABLE ASD AS\nSELECT *\nFROM DUAL

options("datatable.print.word.wrap"=TRUE)
dt # handle \n
#    a                     b
# 1: 1                asda ¬
# 2: 2                 asdas
# 3: 3 CREATE TABLE ASD AS ¬

options("datatable.print.word.wrap"=FALSE,
        "datatable.print.trunc.char"=5L) # default value: 252
dt # handle long characters
#    a        b
# 1: 1 asda\...
# 2: 2    asdas
# 3: 3 CREAT...
```
Of course it would be only a print, the data.table returned would contains all the data.

**Comment by arunsrinivasan** [comment]
@jangorecki like this very much.. do you think you can issue a PR? Else, I'll take a look at it.

**Comment by arunsrinivasan** [comment]
What'd also be nice to somehow some the column type while printing as well.. I've had this on my mind for a while. Instead of doing `str()` or `sapply(DT, class)`..

**Comment by arunsrinivasan** [comment]
Have to:
- [ ] add test, and 
- [ ] assign `NULL` to global options in onLoad.R.
