### ISSUE TITLE
fread fails to read entire file and does *not* throw warning nor error

### ISSUE THREAD

**Issue by rsaporta** [Rdatatable/data.table#1095]
sample data available here: http://www.state.nj.us/transportation/refdata/accident/2013/Monmouth2013Accidents.zip

Offending line (767 in linked file) has the following value: `""A"" ST` 

Compare to read.table: 
```r
f <- "Monmouth2013Accidents.txt"
ans1 <- fread(f)
ans2 <- as.data.table(read.table(f, header=FALSE, sep=",", comment.char="", quote="", stringsAsFactors=FALSE))
    
dim(ans1)
# [1] "766 rows X 47 cols"
dim(ans2)
# [1] "20,700 rows X 47 cols"`
```

possibly related to #1077.

**Comment by arunsrinivasan** [comment]
I get this with v1.9.5:

```R
# Error in fread(f) : 
#   Field 48 on line 767 starts with quote (") but then has a problem. It can contain balanced unescaped quoted subregions 
# but if it does it can't contain embedded \n as well. Check for unbalanced unescaped quotes: 
# ""A"" ST                           , ,                         ,  ,25,25,        ,        ,
# N,                                                                                ,614  
```

**Comment by rsaporta** [comment]
great!   Why the restriction on `\n` if only an ending character?   
Any concern with the difference with `read.table()` ?

**Comment by arunsrinivasan** [comment]
Thanks for the report. `quote = ""` is implemented. Either use that, or wrap your file with `""` around character columns so that `quote = "\""` can then read it properly. See `?fread` quote argument.

**Comment by arunsrinivasan** [comment]
Removed quote argument with a better fix (slightly more robust) for quotes. Please upgrade and test.
