### ISSUE TITLE
Error when merging on a column with large numeric values

### ISSUE THREAD

**Issue by ryankelly-uiuc** [Rdatatable/data.table#1096]
Unless I'm missing something merge.data.table is failing on my data table that has very large (~1e14) numeric values in the "by" column. The values are integers but they are too big to be integer class. Here's an example:

    DT1 <- data.table(a=letters[1:3], x=c(1:3+1e1))
    DT2 <- data.table(b=letters[24:26], x=c(1:3+1e1))

    merge(DT1,DT2, by='x')

    # Result is fine:
    #     x
    # 1: 11
    # 2: 12
    # 3: 13

    # Now make the by column a very large number
    DT1[, x := x+1e15]
    DT2[, x := x+1e15]

    merge(DT1,DT2, by='x')
      # Allow-cartesian error (despite no duplicates in i)

    merge(DT1,DT2, by='x', allow.cartesian=T)
    # Weird result:
    #        x a b
    # 1: 1e+15 a x
    # 2: 1e+15 a y
    # 3: 1e+15 a z
    # 4: 1e+15 b x
    # 5: 1e+15 b y
    # 6: 1e+15 b z
    # 7: 1e+15 c x
    # 8: 1e+15 c y
    # 9: 1e+15 c z

    # workaround is coerce to character
    DT1[, x := as.character(x)]
    DT2[, x := as.character(x)]

    merge(DT1,DT2, by='x')
    # Result is fine
    #                   x a b
    # 1: 1000000000000011 a x
    # 2: 1000000000000012 b y
    # 3: 1000000000000013 c z

**Comment by arunsrinivasan** [comment]
Either use `bit64::integer64` or do `setNumericRounding(0L)` before to `merge`. We recommend converting large numerics (that are actually integers) to `integer64` format by using `as.integer64()` from the `bit64` package to avoid unexpected behaviour due to limitations in floating point representation. See `?setNumericRounding` and the examples for further info.

**Comment by ryankelly-uiuc** [comment]
Wow, it took me longer to install `integer64` and re-run the merge than it did for you to solve my bug... Amazing. Thanks.

**Comment by arunsrinivasan** [comment]
Glad it helped. I've already noted this point down (to be documented as a separate vignette) in #944.
