### ISSUE TITLE
"Invalid .internal.selfref" warning when applying := after tidyr::spread

### ISSUE THREAD

**Issue by MaxGhenis** [Rdatatable/data.table#1100]
Not sure if this is a bug with `data.table` (on v1.9.4) or `tidyr` (on v0.2.0) but here's an example of the behavior:

```
mtcars.dt.spread <- spread(data.table(mtcars), cyl, mpg)  # Returns a data.table
mtcars.dt.spread[, hp.gear := hp + gear]
```

yields this warning:
```
Warning message:                                                                                                                                                                     
 In `[.data.table`(mtcars.dt.spread, , `:=`(hp.gear, hp + gear)) :                                                                                                                    
   Invalid .internal.selfref detected and fixed by taking a copy of the whole table so that := can add this new column by reference. At an earlier point, this data.table has been co\
 pied by R (or been created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax i\
 nstead to avoid copying: ?set, ?setnames and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>\
 v3.0.2 if that is biting. If this message doesn't help, please report to datatable-help so the root cause can be fixed.
```

I'm running R 3.1.1. The result is still as expected, so this is just an unexplained warning. Also, subsequent `:=` calls on the object don't produce the warning; it's only after the first call following `spread`.

**Comment by arunsrinivasan** [comment]
FWIW, there's a much faster (and memory efficient) version of `dcast` implemented in `data.table`, which also can cast on multiple `value.var`s. Not sure why you need `spread`.

`spread` uses `reshape2::dcast`, which creates a data.frame, and just replaces the class to that of input at the very end. So there's no overallocation happening. We can't do anything about it. If you want to stick to it, you can probably wrap your call to `spread()` with `setDT()`, which'll *shallow copy*, *over-allocate*, and *assign that result back*.

**Comment by MaxGhenis** [comment]
Ah good to know, thanks. Are there any plans to build a version of `spread` in `data.table`? Hadley is pushing the `tidyr` framework over `reshape2`, and I've seen them used more recently. I also find `spread` less confusing than `dcast` for sharing code.

**Comment by arunsrinivasan** [comment]
Sorry, no. You should stick to `tidyr` then. I've summarised briefly some of the reasons in [this post](http://r.789695.n4.nabble.com/data-frame-data-driven-column-selections-that-vary-by-row-tp4705260p4705414.html) just moments ago.
