### ISSUE TITLE
[, := ] assigns to diffent/unrelated DT objects

### ISSUE THREAD

**Issue by helix123** [Rdatatable/data.table#1101]
x <- data.table(V1=1:6, V2=7:12)
a <- x
b <- x 

a[, V1 := 10]

a # as expected column V1 is 10 for all rows
b # column V1 is also 10 for all rows - not expected
x # column V1 is also 10 for all rows - not expected

packageVersion("data.table")
[1] ‘1.9.4’

**Comment by arunsrinivasan** [comment]
Please read the `Reference semantics` [HTML vignette](https://github.com/Rdatatable/data.table/wiki/Getting-started), and also `?\`:=\`` and `?copy`. Assignment by reference is a feature.

**Comment by helix123** [comment]
Thank for the quick replay! Was not aware of that/where of the fact that update by reference "spans <-". Maybe a hint/add for the documentation (html vignette): once subsetting is used, := does not affect other variables (as it is deep copied?)
