### ISSUE TITLE
all.equal.data.table - ignore.row.order and ignore.col.order arguments

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1106]
FR for `all.equal.data.table` to handle *ignore col order* and *ignore row order*. Creating issue to reference by # id in the tests.
I will submit PR for that soon.

**Comment by arunsrinivasan** [comment]
@jangorecki I don't understand what this means.. Could you please provide an example?

**Comment by jangorecki** [comment]
this issue is just a placeholder for #id which I've put into tests.Rraw in PR.
PR contains all the examples in the tests.Rraw - this is the same I've mentioned in my recent email to you :)

**Comment by arunsrinivasan** [comment]
Right. Took a small break. Not sure if I'll work next week either. What's the use for `ignore.row.order`? I can understand the use for `ignore.col.order` especially in data.table, as grouping operations return those columns first.

**Comment by jangorecki** [comment]
`ignore.row.order` can be utilized when:
- comparing results of groupings which automatically sorts the data to the groupings which do not sort the data
- comparing data fetch from database or any other source which stores data unordered.
- comparing data after `rbind`-ing them in random order.
- surely some other cases where the order of data doesn't matter but the data equality does matter.

**Comment by jangorecki** [comment]
some new use case for that feature:

- compare result from data.frame merge to data.table join - if they are equal

related SO: http://stackoverflow.com/a/29709406/2490497
To check if datasets are equal I would need to do following: `setDT, setcolroder, setkey`.
All those covered by two additional arguments to in my PR.

**Comment by jangorecki** [comment]
I believe this needs to be handled on the C side.
Cpp solution for exact issue is in dplyr's commit `dbfeb0f9a8bce88b57d441a1ba9bbc33e3e8336f`.

AFAIK it require data.table to be able to exit binary merge on first match. See pseudo code below, `which` arg of course doesn't accept character input, and I'm not advocating it should accept, I just use it to present concept:
```r
target[!current, which = "any"] || current[!target, which = "any"]
# or
target[current, which = "none"] || current[target, which = "none"]
```
`setdiff_` does not play well with duplicates, both directions return 0 rows, while datasets are not equal.
```r
library(data.table)
DT1 <- data.table(a = c(1:4,1:2), b = letters[c(1:4,1:2)])
DT2 <- data.table(a = c(1:4,3:4), b = letters[c(1:4,3:4)])
data.table:::setdiff_(DT1, DT2) # 0 rows
data.table:::setdiff_(DT2, DT1) # 0 rows
```
Slow alternative solutions available in recent commit in that PR.
