### ISSUE TITLE
[Question] How to make a system command in fread() pass CRAN Windows checks?

### ISSUE THREAD

**Issue by rmscriven** [Rdatatable/data.table#1110]
Hi guys.  I'm wondering if you can give me a push in the right direction.  My package, `retrosheet`, fails Windows CRAN checks for r-release and r-oldrel, but passes the Windows r-devel check. Here are the check results.

http://cran.r-project.org/web/checks/check_results_retrosheet.html

The culprit line is on line 59 of 

https://github.com/rmscriven/retrosheet/blob/master/R/getPartialGamelog.R

Specifically, CRAN reports the following,

    Syntax error: end of file unexpected (expecting ")")
    Warning: running command 'sh.exe -c (grep '20120825' GL2012.TXT) > D:\temp\RtmpC8Rfyr\file16485edb70d9' had status 2
    Warning in shell(paste("(", input, ") > ", tt, sep = "")) :
     '(grep '20120825' GL2012.TXT) > D:\temp\RtmpC8Rfyr\file16485edb70d9' execution failed with error code 2
    Error in fread(command, header = FALSE, select = sel) :
     File not found: D:\temp\RtmpC8Rfyr\file16485edb70d9
    Calls: getPartialGamelog -> fread
    Execution halted

I'm hoping you might be able to give me a few pointers on how to get the function to pass all Windows checks, as I am having trouble going about it.

Cheers.

**Comment by jangorecki** [comment]
Did 1.0.0 version of your package pass cran check OK for those versions?
You are using shell commands like `grep` which I believe is heavy OS dependent.

Can't help you much but I recommend to setup travis-ci, it helps quite a lot. Recently it gets native support for R which makes it much simpler (example [logR/.travis.yml](https://github.com/jangorecki/logR/blob/master/.travis.yml)).

Also you can link a line in file directly by adding `#L59` to url: [getPartialGamelog.R#L59](https://github.com/rmscriven/retrosheet/blob/master/R/getPartialGamelog.R#L59)

**Comment by rmscriven** [comment]
After thinking about this, there will probably be more to this function in the long-run.  So for now I've decided to take the safe route and not use a system command in `fread()`.  

@jangorecki  - thanks for the tips, I'll definitely have a look at travis-ci.

Closing this issue.

**Comment by arunsrinivasan** [comment]
Thanks for the report. I've tested this with R versions 3.0.3, 3.1.1 and 3.1.3, with data.table versions 1.9.2, 1.9.4 and 1.9.5 on windows 8.1, with corresponding Rtools versions.. Not able to reproduce at all. 

I'll keep it open because the issue seems to be in `fread`.

**Comment by rmscriven** [comment]
Thanks Arun. I wrote this temporary workaround for `out`.  

    out <- if(is.null(date)) {

        fread(fname, select = sel, header = FALSE)

    } else if(is.character(date)) {

        ## get the first column only - this is the 'Date' column
        sc <- scan(fname, sep = ",", flush = TRUE, what = "", quote = "\"", quiet = TRUE)

        ## find rows of matched dates
        if(!length(wh <- which(sc == date))) {
            stop("invalid 'date' given")
        }

        ## read the file - selecting specified date and columns
        suppressWarnings(fread(fname, select = sel, header = FALSE,
            skip = min(wh)-1L, nrows = diff(range(wh))))

    }

    ## set the names
    setnames(out, retrosheetFields$gamelog[sel])

    ## return the table
    out
}

Obviously there are other checks that have to happen now, which I omitted.  Unfortunately this is **a lot** slower than using the `grep` command.

**Comment by Monty9** [comment]
Hi there,
I have experienced the same error with fread. Unable to figure out what needs to be done. 
```Error in fread(input = "JournalHomeGrid.txt", sep = "auto", header = T) : 
  File is empty: C:\Users\monty9l\AppData\Local\Temp\RtmpKIX5gp\file335c1948555a
In addition: Warning messages:
1: running command 'C:\Windows\system32\cmd.exe /c (JournalHomeGrid.txt) > C:\Users\vgadepal\AppData\Local\Temp\RtmpKIX5gp\file335c1948555a' had status 1 
2: In shell(paste("(", input, ") > ", tt, sep = "")) :
  '(JournalHomeGrid.txt) > C:\Users\vgadepal\AppData\Local\Temp\RtmpKIX5gp\file335c194```

Please let me know how to pass this error.

**Comment by arunsrinivasan** [comment]
Can't reproduce.
