### ISSUE TITLE
crash fread, linux debian, R 3.1.3, RStudio 0.98.1091

### ISSUE THREAD

**Issue by maxbre** [Rdatatable/data.table#1119]
crash within Rstudio (not reproducible) and also from command line ( here follows)
## 

> fread("x_test.txt")

 **\* caught segfault ***
address 0x7f724a13f000, cause 'invalid permissions'

Traceback:
 1: fread("x_test.txt")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
aborting ...
#### 

my configuration:
Linux max-debian 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
RStudio Version 0.98.1091
R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"

**Comment by jangorecki** [comment]
Try to use verbose and log output to file so it could bring some more info. Also the file itself would be useful, without such data it can be hard to even look at it. Some might first guess... error message `invalid permissions` seems to be related not directly to R but to OS/file system issue, you might want to check that too.

**Comment by maxbre** [comment]
thank you for the support

I've been testing that under different machines with different OS/file 
systems and finally I've got an informative message

Error in fread(paste0(testpath, "X_test.txt")) :

   Expected sep (' ') but new line, EOF (or other non printing character) ends field 651 on line 33 when detecting types:.... here omitted output for brevity

so I think I can confirm now it is just a problem in the input file 
probably because there are uneven number of spaces in some fields

in fact no probs with "read.table": is there any possible workaround in 
order to use fread with such a file (quite big! 30 Mb)

regards

max

Il 16/04/2015 22:53, Jan Gorecki ha scritto:
