### ISSUE TITLE
"Unable to find 5 lines with expected number of columns" warning when freading 16 lines

### ISSUE THREAD

**Issue by richierocks** [Rdatatable/data.table#1124]
When calling `fread` on a file with exactly 16 lines, I get the warning `"Unable to find 5 lines with expected number of columns (+   last)"`.

To reproduce:

```{r}
library(data.table)
n <- 16
d <- data.table(
  x = 1:n,
  y = letters[1:n]
)

lines <- c(
  paste(colnames(d), collapse = ","), 
  paste(d$x, d$y, sep = ",")
)
(lines <- paste(lines, collapse = "\n"))
## [1] "x,y\n1,a\n2,b\n3,c\n4,d\n5,e\n6,f\n7,g\n8,h\n9,i\n10,j\n11,k\n12,l\n13,m\n14,n\n15,o\n16,p"
fread(lines)
```

If you change `n` to 15 or 17, the warning does not occur.

**Comment by skatastic** [comment]
Here's a real world example of this bug at play.  

fread("https://www.misoenergy.org/Library/Repository/Market%20Reports/20150531_da_pbc.csv",skip=4)

**Comment by sanmai-NL** [comment]
I also suffered this bug today.

**Comment by pseemakurthi** [comment]
I encountered the same bug using 1.9.7 freadversion

**Comment by jangorecki** [comment]
@pseemakurthi did you try latest development version? optionally provide output of `read.dcf(system.file("DESCRIPTION", package="data.table"), c("Packaged","Built"))`

**Comment by arunsrinivasan** [comment]
It is not a bug, but a warning. And this has been fixed in the devel version. Please try it and post a new issue if you still get the warning.
