### ISSUE TITLE
Getting strange behavior with := NULL

### ISSUE THREAD

**Issue by heshca** [Rdatatable/data.table#1125]
I have a data.table ```x``` that looks like the following:

```
A     B      C      D      E      F
1     4      7      9      8      6
2     4      4      3      6      6
3     7      6      4      5      6 
4     3      4      5      9      2 
5     3      4      5      6      7
```

I then run the code:

```
y <- x
y <- y[,c("B","C","F") := NULL]
```

And then I go back and check ```x``` and it has also lost columns "B","C" and "F".

**Comment by DavidArenburg** [comment]
This is a known `data.table` behavior and apparently "status-by-design". Do `y <- copy(x)` in order to avoid this behavior.

**Comment by heshca** [comment]
Thanks

**Comment by DavidArenburg** [comment]
Take a look [here](http://stackoverflow.com/questions/15913417/why-does-data-table-update-namesdt-by-reference-even-if-i-assign-to-another-v/15913648#15913648)
