### ISSUE TITLE
Package loading order leads to inconsistency with `bit64`

### ISSUE THREAD

**Issue by jean-robert** [Rdatatable/data.table#1129]
The order in which `bit64` and `data.table` are loaded leads to different behaviors. Using `R 3.0.1`, `data.table 1.9.4`, I have the following

```
require(bit64)
require(data.table)

dt <- data.table(timestamp=c(as.integer64(1427097940517),
  as.integer64(1427097943773),
  as.integer64(1427151599999)),
 value=1:3)

dt[, list(value=last(value)), by=timestamp]

#       timestamp value
#1: 1427097940517     1
#2: 1427097943773     2
#3: 1427151599999     3
```

which is the expected behavior, but if I load `data.table` before `bit64`, I get : 
```
require(data.table)
require(bit64)

dt <- data.table(timestamp=c(as.integer64(1427097940517),
  as.integer64(1427097943773),
  as.integer64(1427151599999)),
 value=1:3)

dt[, list(value=last(value)), by=timestamp]

#       timestamp value
#1: 1427097940517     2
#2: 1427151599999     3
```

which is not correct. I'm trying to investigate what is wrong, but I thought I would share in case someone wants to have a look.

**Comment by arunsrinivasan** [comment]
Thanks, but not reproducible in 1.9.5.

**Comment by jean-robert** [comment]
Seems to be fine also with a more recent version of R. I'll update accordingly, thanks.
