### ISSUE TITLE
%in% returns repeated rows

### ISSUE THREAD

**Issue by vttrifonov** [Rdatatable/data.table#1131]
The %in% operator has an unexpected behavior (see below). I am pretty sure this did not exist before (code which used to work, stopped working, because of this) but I cannot pinpoint the exact time when this happened.

-- example code begins here

library(data.table)

#data.table 1.9.4  For help type: ?data.table
#*** NB: by=.EACHI is now explicit. See README to restore previous behaviour.

sessionInfo()

#R version 3.1.0 (2014-04-10)
#Platform: x86_64-unknown-linux-gnu (64-bit)
#
#locale:
#[1] C
#
#attached base packages:
#[1] stats     graphics  grDevices utils     datasets  methods   base     
#
#other attached packages:
#[1] data.table_1.9.4
#
#loaded via a namespace (and not attached):
#[1] Rcpp_0.11.2   chron_2.3-45  plyr_1.8.1    reshape2_1.4  stringr_0.6.2

packageVersion("data.table")
#[1] '1.9.4'

data.table(a=c(1, 2, 3))[a %in% c(1, 1, 2, 1),]
#a
#1: 1
#2: 1
#3: 2
#4: 1

#expected to see
#a
#1: 1
#2: 2

**Comment by arunsrinivasan** [comment]
Fixed in 1.9.5 (one of the auto indexing bugs).
