### ISSUE TITLE
data.table when keyed to large number, both mis-sorts and changes data values

### ISSUE THREAD

**Issue by swright393** [Rdatatable/data.table#1137]
My data rows happend to already have large numeric identifiers.  When I keyed to this column, I got very strange behavior: subsetting by this index occasionally returned more rows than the key properly matched, AND it changed the reported key_value in the displayed output.  

Example:

sampleDT<-data.table(index=c(810000415444, 810000415447,510000515151), textindex=c("810000415444-txt","810000415447-txt","510000515151-txt")) #3-row data.frame
setkey(sample_DT,index)
sample_DT

#                      index        textindex
# 1: 510000515151   510000515151-txt
# 2: 810000415444   810000415444-txt
# 3: 810000415447   810000415447-txt

sample_DT[.(810000415444)] #Should only return row 1, but returns two rows--AND has changed the value in the index column for row 2 to end in "4"...?(txt_index and index no longer match)

#                      index        textindex
# 1: 810000415444 810000415444-txt
# 2: 810000415444 810000415447-txt

sampleDT[index==810000415444]#Still inappropriately returns two columns, BUT does not change the index column value.  Unsurprisingly, #sampleDT[index==810000415444, ] also returns the same.

sample_DT[sample_DT$index==810000415444]#Using this more data.frame method returns the proper row

#                index       text_index
#1: 810000415444 810000415444_txt

sample_DT[sample_DT$index==810000415444] #Using this more data.frame method returns the proper (single) row
sample_DT[sample_DT$index==810000415447] #As does this. 
 

Version: data.table 1.9.4,  
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
Occurs when data.table is only package loaded.

**Comment by swright393** [comment]
P.S.  Sorry about the formatting.   I should add that it is only specific numbers that generate this problem (and it is reproducible): for example, if I have 26,000 index numbers of this size, the first 2180 run just fine.  Also,  changing the mode to character fixes it completely, as expected.

**Comment by arunsrinivasan** [comment]
It'd be nice if you could re-format the post after reading [github flavoured markdown](https://help.github.com/articles/github-flavored-markdown/). Even better with [How to file a bug report?t](https://github.com/Rdatatable/data.table/wiki/How-to-file-a-bug-report).

Your issue is most definitely identical to #1096. Please try out the answer there..

**Comment by swright393** [comment]
Thanks.  Did all those, but as new to github (and don’t use markdown) still failed.  Sorry I missed 1096, didn’t catch it on the first serach.

 

Can close and/or delete the post, since it is a duplicate.
