### ISSUE TITLE
Strange behaviour in list of class which inherit from data.table

### ISSUE THREAD

**Issue by zezongo** [Rdatatable/data.table#1138]
Hello everyone,

this is my first post so please be kind :)
I am currently building a package, and i decided to use S4 for my class definition and method. One of my class, called "experiment", as slots containing some other classes inheriting from data.table. Here the definition of the class :

setClassUnion("POSIXctORNULL", c("POSIXct", "NULL"))
setClassUnion("plantORNULL", c("plant", "NULL"))
setClassUnion("environmentEPPNORNULL", c("environmentEPPN", "NULL"))
setClassUnion("finalORNULL", c("final", "NULL"))
setClassUnion("leafNumberORNULL", c("leafNumber", "NULL"))
setClass("experiment",
         slots=c(info="character",environment="environmentEPPNORNULL",plant="plantORNULL",leafNumber="leafNumberORNULL",final="finalORNULL",sowing="POSIXctORNULL",name="character"),
         ,validity=function(object) (any(grepl("[Ss]owing",object@info)==1))
)

and for exemple one of the inheriting class : 

setClass("plant",
         validity=function(object) ( all.equal(sapply(object,class),list(date=c("POSIXct","POSIXt"),genotype="factor",replicate="factor",estimatedLeafArea..LA.="numeric",estimatedBiomass..B.="numeric",projectedShootArea="numeric"
                                            ,keep.estimatedLeafArea..LA.="logical",keep.estimatedBiomass..B.="logical",keep.projectedShootArea="logical"
                                            ,valid.estimatedLeafArea..LA.="logical",valid.estimatedBiomass..B.="logical",valid.projectedShootArea="logical"
                                            ,model.estimatedLeafArea..LA.="numeric",model.estimatedBiomass..B.="numeric",model.projectedShootArea="numeric",
                                            accept="logical"))),
        
         contains="data.table"
)

As we may work with collection of experiments (meaning a list only composed of experiments), i wanted to define a binary operator allowing to access, and return, all the slots of the given name amongst the experiments : 

setGeneric("%@%",function(object,...) 
  standardGeneric("%@%")  
)

setMethod("%@%", "list",
          function(object,sl) ({
            aux<-as.character(substitute(sl))     
            if (identical(.inter(lapply(object,class)),"experiment")) {
              res<-lapply(object,function(e) slot(e,aux))
              return(res)
            }else warning("Not a list of experiments")
            
          })       
)

.inter<-function(...){
  #browser()
  objects<-list(...)
  if (length(objects)==1 & is.list(objects[[1]])) objects<-objects[[1]]
  aux<-objects[[1]]
  for (i in 2:length(objects)){
    aux<-intersect(aux,objects[[i]])
  }
  aux
}

This method works just fine while i put a slot different from a class having data.table : 

> object%@%name
[[1]]
[1] "Adelaide"

[[2]]
[1] "Szeged"

[[3]]
[1] "Julich"

> object%@%sowing
[[1]]
[1] "2014-01-10 CET"

[[2]]
[1] "2014-10-22 CEST"

[[3]]
[1] "2013-09-25 08:00:00 CEST"

but (plant is a class inheriting from data.table): 

> object%@%plant
[[1]]
Error in if (n > 0) c(NA_integer_, -n) else integer() : 
  argument is of length zero

i then browsered some alternative code : 

function(object,sl) ({
              browser()
              aux<-as.character(substitute(sl))     
              if (identical(.inter(lapply(object,class)),"experiment")) {
                  res<-vector("list",length(object))
                  for (i in 1:length(res)){
                      res[[i]]<-slot(object[[i]],aux)
                  }
                  return(res)
              }else warning("Not a list of experiments")
              
          })

and here is the weird thing ; i can access each element of 'res' individualy : 

res[[1]]
Object of class "plant"
                     date genotype replicate estimatedLeafArea..LA. estimatedBiomass..B. projectedShootArea keep.estimatedLeafArea..LA.
   1: 2014-01-26 10:39:09     A347         1                    101                    8              62905                        TRUE
   2: 2014-01-27 11:54:41     A347         1                    115                    9              71752                        TRUE
   3: 2014-01-28 10:39:15     A347         1                    131                   10              81727                        TRUE
   4: 2014-01-29 12:19:40     A347         1                    166                   13             103159                        TRUE
   5: 2014-01-30 12:52:54     A347         1                    185                   14             115069                        TRUE
  ---                                                                                                                                  
2182: 2014-02-12 06:02:34       W9        10                   1466                  113             912102                        TRUE
2183: 2014-02-14 10:18:03       W9        10                   1595                  123             992428                        TRUE
2184: 2014-02-14 15:56:29       W9        10                   1631                  126            1015092                        TRUE
2185: 2014-02-17 14:38:59       W9        10                   1987                  154            1236758                        TRUE
2186: 2014-02-18 11:26:11       W9        10                   2114                  164            1315522                        TRUE
      keep.estimatedBiomass..B. keep.projectedShootArea valid.estimatedLeafArea..LA. valid.estimatedBiomass..B. valid.projectedShootArea
   1:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
   2:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
   3:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
   4:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
   5:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
  ---                                                                                                                                   
2182:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
2183:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
2184:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
2185:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
2186:                      TRUE                    TRUE                         TRUE                       TRUE                     TRUE
      model.estimatedLeafArea..LA. model.estimatedBiomass..B. model.projectedShootArea accept
   1:                            0                          0                        0   TRUE
   2:                            0                          0                        0   TRUE
   3:                            0                          0                        0   TRUE
   4:                            0                          0                        0   TRUE
   5:                            0                          0                        0   TRUE
  ---                                                                                        
2182:                            0                          0                        0   TRUE
2183:                            0                          0                        0   TRUE
2184:                            0                          0                        0   TRUE
2185:                            0                          0                        0   TRUE
2186:                            0                          0                        0   TRUE

but i can't call 'res' as a whole...

althought, by casting the output of the slot as a data.frame, it works normaly (i did it on the specific slots) ...

Thanks for reading until the end, i expect i have been clear enough.

**Comment by jangorecki** [comment]
Re-format you post using [github-flavored-markdown](https://help.github.com/articles/github-flavored-markdown/) and follow [How-to-file-a-bug-report](https://github.com/Rdatatable/data.table/wiki/How-to-file-a-bug-report).
At the moment... I think you see how your post looks like.

**Comment by zezongo** [comment]
Thank you for these links, i will reformat and close (if possible) this thread.

**Comment by zezongo** [comment]
By reformating the post and trying to put a reproductible exemple, i finaly pointed out that it was my mistake : i just did not define the print method for my class, which was causing the bug.
