### ISSUE TITLE
Scope of .N in i

### ISSUE THREAD

**Issue by claytontstanley** [Rdatatable/data.table#1145]
I noticed that `.N` was made available in i recently, so I started using the feature. However, I got into trouble when trying to use `.N` in nested data tables. Here's an example:

```r
require(data.table)
tbl = data.table(1:5)
tbl[1:.N]
#    V1
# 1:  1
# 2:  2
# 3:  3
# 4:  4
# 5:  5

tbl[, head(.SD, n=2)[1:.N]]
#    V1
# 1:  1
# 2:  2
# 3: NA
# 4: NA
# 5: NA

tbl[, head(.SD, n=2)[, 1:.N]]
# [1] 1 2
```

I was expecting `.N` in both `i` and `j` to bind to the most local `data.table` environment. In this case, the nested table, so `.N=2`.

I brought this issue up with Arun. He looked at the code and found that `.N` was locked to the top-level `data.table`. He thought this would be a good issue to bring to the community for discussion.

-Clayton

**Comment by eantonya** [comment]
Seems "obvious" to me that it should be equal to 2 in your second expression, instead of 5, so I'd vote yay for the change.

**Comment by jangorecki** [comment]
+1 for change

**Comment by franknarf1** [comment]
+1

**Comment by renkun-ken** [comment]
+1

**Comment by arunsrinivasan** [comment]
Thanks @claytonstanley for catching this. Will fix.

**Comment by rsaporta** [comment]
I like the change as well, but just to be sure all bases are covered, what about when toplevel `.N` is desired?  (example that comes to mind might be when there is a `by` clause used in conjunction)

**Comment by franknarf1** [comment]
@rsaporta It's just a scalar, so I'd manually make a copy if needed: `DT[,{g.N=.N;....SD...},by=g]`
