### ISSUE TITLE
unique argument for CJ

### ISSUE THREAD

**Issue by eantonya** [Rdatatable/data.table#1148]
Since `CJ` is almost always used in combination with `unique`, I think it would make sense to add a `unique` argument to it, so that one can just write unique once:

```R
CJ(unique(colA), unique(colB), unique(colC)) -> CJ(colA, colB, colC, unique = TRUE)
```

The default of `unique` should be specified via options, and imo should be set to `TRUE` after a few release iterations.

**Comment by jangorecki** [comment]
Your suggestion to `CJ` in #814 looks interesting. Why don't you push suggested code together with handling this one. Even if it won't be mature PR it will be at least good reference/base to work with.

**Comment by arunsrinivasan** [comment]
That's just confusing. Too many things to remember. Until this is fixed, I think the default value for rounding should be `1` instead of `2`, so that millisecond resolutions are taken care of.

**Comment by jangorecki** [comment]
@arunsrinivasan wrong issue ;) btw. I agree on default `1`.
