### ISSUE TITLE
Varying behavior in print based on value of `i`

### ISSUE THREAD

**Issue by rsaporta** [Rdatatable/data.table#1150]
When assigning `:=`, output is given if `i` has no matches, whereas output is suppressed if `i` does have a match. 

  eg: 

    set.seed(1)
    DT <- data.table(A=1:3, Val=rnorm(3))
    DT[ A < 3, Val := 0]  # Some rows matched, no output printed
    DT[ A > 3, Val := 0]  # Zero rows matched, output was printed
    #     A       Val
    #  1: 1  0.000000
    #  2: 2  0.000000
    #  3: 3 -0.835629

related to #1122 

----

It is worth noting that this could be useful when working interactively.  EG, if the user is expecting to modify the DT and output is issued it serves as an indirect/subtle `warning` that there was no change to the table. 

This being said, if we desire that behavior perhaps we should insert a check and proper warning.

**Comment by franknarf1** [comment]
Related, regarding similar warnings for failure of `:=` to make changes: https://github.com/Rdatatable/data.table/issues/354

**Comment by mattdowle** [comment]
Already fixed. Item 2 on the v1.9.5 bug fix list. Checked tests were added to tests/autoprint.R in https://github.com/Rdatatable/data.table/commit/84766f40b099fd40f472d78e39643b910577d046
> 2 `DT[FALSE,LHS:=RHS]` no longer prints either, [#887](https://github.com/Rdatatable/data.table/issues/887). Thanks to Jureiss for reporting.
