### ISSUE TITLE
dcast.data.table different from reshape2::dcast when formula is of the form `. ~ col`

### ISSUE THREAD

**Issue by rsaporta** [Rdatatable/data.table#1152]
Different behavior between `dcast.data.table` and `reshape2::dcast`  when formula is of the form `. ~ col`

See SO  [Transposing a data.table with reshape2:::dcast](http://stackoverflow.com/q/30305843/1492421)

    library(data.table)
    library(reshape2)
    DT <- data.table(STORE = LETTERS[1:6]
                    , VOLUME = c(343.87205, 599.78335, 1665.90895, 712.0343, 465.6489, 622.5189)
                    )

    reshape2::dcast(DT, . ~ STORE, value.var = "VOLUME")
    #   .       A       B       C       D       E       F
    # 1 . 343.872 599.783 1665.91 712.034 465.649 622.519

    dcast.data.table(DT, . ~ STORE, value.var = "VOLUME")
    # Error in dcast.data.table(DT, . ~ STORE, value.var = "VOLUME") :
    #   LHS of formula evaluates to 'character(0)', invalid formula.

Thanks to SO user @mkemp6 for pointing this out

**Comment by DavidArenburg** [comment]
This has been fixed long time ago in the devel version.

**Comment by rsaporta** [comment]
Thanks Dave, my mistake.  I should have checked before filing the issue.  Going ahead and removing this.

**Comment by DavidArenburg** [comment]
How can I remove this :P
