### ISSUE TITLE
Subset DT[col=='val'] is empty after renaming values with DT[col=='val',col:='newval'] and then calling DT[col=='newval'].

### ISSUE THREAD

**Issue by saladspices** [Rdatatable/data.table#1156]
---
Subset empty after renaming values.
---

When renaming specific values in a column using := and subsequently subsetting the whole data.table based on that value, an empty data.table is returned. See the quick example code below.

```{r}
# Reproducible example
library(data.table) #assuming version 1.9.4 is installed
dat <- data.table(Subject=1:10,Condition=c(rep('horse',5),rep('cat',5)))
````
Let's only look at the rows where subjects where in the 'horse' condition:  
```{r}
dat[Condition=='horse']
```
That works. Now I don't want to call it 'horse' but 'Pony' (in reality this might be because of some errors in file naming)
```{r}
dat[Condition=='horse',Condition:='Pony']
dat[Condition=='Pony']
```
Somehow I get an empty data.table now.  
<br><br>
This behavior seems to be new in version 1.9.4 since it does not appear in version 1.9.2  
```{r}
remove.packages('data.table')
require(devtools)
install_version("data.table", version = "1.9.2", repos = "http://cran.us.r-project.org")
##
library(data.table) #assuming version 1.9.4 is installed
dat <- data.table(Subject=1:10,Condition=c(rep('horse',5),rep('cat',5)))
dat[Condition=='horse',Condition:='Pony']
dat[Condition=='Pony']
```

I consider this a serious bug, as this might lead to wrong conclusion as soon as it's packed somewhere in a loop or the like.  
Imagine, for instance, renaming condition 2 of a total of 6 conditions, because you want to analyze it together with condition 1. In subsequent analyses you could easily miss that you're actually still only analyzing condition 1 and your conclusions might be completely wrong.

**Comment by jangorecki** [comment]
Try 1.9.5. Seems to be fixed already?
```r
dat[Condition=='Pony']
#    Subject Condition
# 1:       1      Pony
# 2:       2      Pony
# 3:       3      Pony
# 4:       4      Pony
# 5:       5      Pony
```

**Comment by saladspices** [comment]
My bad! I didn't see the 1.9.5 before. That indeed solves the problem - thank you!
