### ISSUE TITLE
Inconsistent state between printing and querying

### ISSUE THREAD

**Issue by claytontstanley** [Rdatatable/data.table#1165]
What is going on here? data.table 1.9.4 via CRAN.

> tbl = data.table(rep('a', 101), c(rep('y', 100), 'x'))
> tbl[V2 == 'x', V2 := 'b']
> tbl[V2 == 'y', V2 := '']
> tbl[V2 == 'b']
Empty data.table (0 rows) of 2 cols: V1,V2
> tbl
     V1 V2
  1:  a   
  2:  a   
  3:  a   
  4:  a   
  5:  a   
 ---      
 97:  a   
 98:  a   
 99:  a   
100:  a   
101:  a  b
>

**Comment by franknarf1** [comment]
Use parentheses. `tbl[(V2 == 'b')]`. I think this may be a bug/behavior they want to fix. You might consider the mailing list for this sort of question, by the way; links are under Notices/Discussion here: https://github.com/Rdatatable/data.table/wiki/Getting-started

**Comment by arunsrinivasan** [comment]
It is most likely auto indexing bug.. Which has been fixed in devel version long back. Could you verify please? It is always essential to check on latest commits before filing, in general..

**Comment by claytontstanley** [comment]
Verified. The bug was already fixed. Everything works fine in the current development version. I'll roll with using the development version from here out, until 1.9.6 is released on CRAN.

Sorry for the false alarm.
