### ISSUE TITLE
Type mismatch with rbind and empty data.table throws an error

### ISSUE THREAD

**Issue by tseaward** [Rdatatable/data.table#1173]
The two data.tables below have a `date` column with different types. Should `data.table` throw an error when using `rbind` given that `a` is empty?

```
require(data.table)
# Loading required package: data.table
# data.table 1.9.5  For help type: ?data.table
# *** NB: by=.EACHI is now explicit. See README to restore previous behaviour.

a <- data.table(date = character(), value = numeric())
a
# Empty data.table (0 rows) of 2 cols: date,value

b <- data.table(date = Sys.Date(), value = 1)
b
# date value
# 1: 2015-06-08     1

rbind(a, b)
# Error in rbindlist(l, use.names, fill, idcol) : 
#   Class attributes at column 1 of input list at position 2 does not match with column 1 of input list at position 1. Coercion of objects of class 'factor' alone is handled internally by rbind/rbindlist at the moment.

sessionInfo()
# R version 3.2.0 (2015-04-16)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 7 x64 (build 7601) Service Pack 1
# 
# locale:
#   [1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252   
# [3] LC_MONETARY=English_South Africa.1252 LC_NUMERIC=C                         
# [5] LC_TIME=English_South Africa.1252    
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
#   [1] data.table_1.9.5 RODBC_1.3-11    
# 
# loaded via a namespace (and not attached):
#   [1] tools_3.2.0  chron_2.3-45
```

As an example this happens frequently when using `RODBC::sqlQuery`. When the result of the query is empty, date columns are of type `character` and are not coerced to `Date` (as there is not data to try and infer the class.)

**Comment by jangorecki** [comment]
It should thrown error IMO. This is a gap in RODBC package that it silently converts data types. I would advise to wrap `RODBC::sqlQuery` or `rbindlist` into own handler function. Silent data conversion is quite bad habit. In my code I would expect the case you describe to throw error.

**Comment by arunsrinivasan** [comment]
`rbindlist` skips on empty tables. So perhaps this could be automatically skipped. Not sure yet. Will take a look, thank you (marking as FR for now).

**Comment by arunsrinivasan** [comment]
The current behaviour is right, and it should throw error even on empty tables. You'll have to fix your data.table before to bind.
