### ISSUE TITLE
object 'CisReallyReal' not found and object 'CanyNA' not found

### ISSUE THREAD

**Issue by helix123** [Rdatatable/data.table#1178]
With data.table  1.9.5    2015-06-14 Github (Rdatatable/data.table@e22190a) I get:

    set.seed(45L)
    DT <- data.table(V1=c(1L,2L),
                 V2=LETTERS[1:3],
                 V3=round(rnorm(4),4),
                 V4=1:12)

    DT[V1==1, ]
    ## Error in isReallyReal(RHS) : object 'CisReallyReal' not found
    DT[V2=="A", ]
    ## Error in any_na(as_list(RHS)) : object 'CanyNA' not found

**Comment by DavidArenburg** [comment]
Close **all** your R sessions and reinstall again. I can't reproduce this, so it seems that you just didn't install it properly.

**Comment by DavidArenburg** [comment]
Close your R sessions and try reinstalling again as I can't reproduce this.

**Comment by arunsrinivasan** [comment]
I second @DavidArenburg's suggestion. Use `remove.packages()` to remove the package, and reinstall. That seems to have resolved things in the past.

**Comment by helix123** [comment]
Ok, removed and now on data.table * 1.9.5    2015-06-15 Github (Rdatatable/data.table@e22190a): no more errors. Thanks!
