### ISSUE TITLE
How to convert H2O Frame into data.table?

### ISSUE THREAD

**Issue by geponce** [Rdatatable/data.table#1184]
Hi, 

I have been trying to convert results from H2O predict method object into data.table without luck. Below a screenshots with some errors  that I got:
![image](https://cloud.githubusercontent.com/assets/5420072/8239164/f92c0818-15ae-11e5-8f6c-686b2bbbc197.png)

As you can see, dt.pred <- data.table(predicted=dt.predictions[,1])  seems to work, but then when I try to see the content I get the invalid type/length error... 

Actually, the as.data.frame also didn't work, check it out: 

![image](https://cloud.githubusercontent.com/assets/5420072/8239218/44645b82-15af-11e5-83e0-bd4487def5ea.png)

It also didn't show an error on the command execution time, just when you try to explore the content of the data frame is when you get the error.  In this case some java server output showed up... 

``` R
#Example taken from ML benchmarking by Szilard Pafka : https://github.com/szilard/benchm-ml
library(h2o)
library(data.table)

urlfile<-'https://raw.githubusercontent.com/geponce/R/master/train-1m.csv' 
urlfile2<-'https://raw.githubusercontent.com/geponce/R/master/test.csv'

h2oServer <- h2o.init(max_mem_size="32g", nthreads=-1)

dx_train <- as.h2o(h2oServer, read.csv(urlfile))
dx_test <- as.h2o(h2oServer, read.csv(urlfile2))

for (k in c("Month","DayofMonth","DayOfWeek")) {
  dx_train[[k]] <- as.factor(dx_train[[k]])
  dx_test[[k]] <- as.factor(dx_test[[k]])
}

dx_train
summary(dx_train)

Xnames <- names(dx_train)[which(names(dx_train)!="dep_delayed_15min")]

system.time({
  md <- h2o.randomForest(x = Xnames, y = "dep_delayed_15min", data = dx_train, ntree = 500, type="BigData")
})

system.time({
dt.predict <- h2o.predict(md, dx_test[,1])
})


dt.predictions <- data.table(prediction = dt.predict[,1])
dt.predictions
```

Best,
Guillermo

**Comment by MichaelChirico** [comment]
@geponce I'm not familiar enough with `h2o` to figure this out myself, but your sample code is an error for me:

    dx_train <- as.h2o(h2oServer, read.csv(urlfile))

Returns error

> `is.character(key) && length(key) == 1L && !is.na(key)` is not `TRUE`

PS why would you use `read.csv`? (perhaps this was written before `fread` could accept a URL connection... `as.h2o(h2oServer, fread(urlfile))` works just as well)

**Comment by geponce** [comment]
@MichaelChirico I don't recall if 'fread' was already available at that time... Anyway, were you able to see the content of dt.predictions in the last line without errors?

Maybe newer versions of h2o or data.table already deal with this issue...

Thanks,
Guillermo

**Comment by jangorecki** [comment]
@geponce It works fine on latest CRAN h2o and data.table. Also you should use `as.data.table` not `data.table`. Please check on latest versions, re-open if issue still persist.
