### ISSUE TITLE
test.data.table() error when bit64 isn't installed

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1186]
Running test id 1449     Test 1449 Error in fread("quoted_multiline.csv") : 
  (converted from warning) Some columns have been read as type 'integer64' but package bit64 isn't loaded. Those columns will display as strange looking floating point data. There is no need to reload the data. Just require(bit64) to obtain the integer64 print method and print the data again.
Error in eval(expr, envir, enclos) : 
  1 error out of 4166 (lastID=1525 ...

**Comment by arunsrinivasan** [comment]
Fixed already in commit https://github.com/Rdatatable/data.table/commit/06a435c8a325e8e4be471ae7d48d7f13fa1a877c
