### ISSUE TITLE
External pointer NULL of load(DT.Rdata)?

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1189]
Silence warning message mentioned in #944.

**Comment by jangorecki** [comment]
It is already in recent FAQ in *Warning messages* section. Not sure why @arunsrinivasan assigned Matt two days ago. Re-open if there is still something to do about that.

**Comment by arunsrinivasan** [comment]
Because he wants to *silence* the warning..

**Comment by arunsrinivasan** [comment]
If we are doing this, then we should catch if the input is not a symbol (and selfrefok is FALSE), and if so, error and ask user to run `alloc.col` first..

**Comment by MichaelChirico** [comment]
Context is lost here. Needs a fresh issue if it's still relevant.
