### ISSUE TITLE
3 tests fail under valgrind

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1194]
> Running test id 648     Test 648 expected TRUE but observed:
> any(is.na(ans1$V1)) && !any(is.nan(ans1$V1)) 
[1] FALSE
Running test id 1495     ==31666== Warning: set address range perms: large range [0x5f456040, 0x7323c728) (undefined)
==31666== Warning: set address range perms: large range [0x7323d040, 0x87023728) (undefined)
Running test id 1509     ==31666== Warning: set address range perms: large range [0x87024040, 0x9ae0a728) (undefined)
==31666== Warning: set address range perms: large range [0x3a056040, 0x4de3c728) (undefined)
Running test id 1101     Test 1101 ran without errors but failed check that x equals y:
> x = as.data.frame(dcast(DT, time ~ variable, fun = mean)) 
   time    weight
1     0  41.06000
2     2  49.22000
3     4  59.95918
4     6  74.30612
5     8  91.24490
6    10 107.83673
7    12 129.24490
8    14 143.81250
9    16 168.08511
10   18 190.19149
11   20 209.71739
12   21 218.68889
> y = dcast(as.data.frame(DT), time ~ variable, fun = mean) 
   time    weight
1     0  41.06000
2     2  49.22000
3     4  59.95918
4     6  74.30612
5     8  91.24490
6    10 107.83673
7    12 129.24490
8    14 143.81250
9    16 168.08511
10   18 190.19149
11   20 209.71739
12   21 218.68889
Running test id 1142     ==31666== Warning: set address range perms: large range [0x7323d028, 0x87023740) (noaccess)
==31666== Warning: set address range perms: large range [0x5f456028, 0x7323c740) (noaccess)
==31666== Warning: set address range perms: large range [0x87024028, 0x9ae0a740) (noaccess)
==31666== Warning: set address range perms: large range [0x3a056028, 0x4de3c740) (noaccess)
Running test id 1262     Test 1262 ran without errors but failed check that x equals y:
> x = length(unique(c(1.23456789012346, 1.23456789012346, 1.23456789012346,      1.23456789012346))) 
[1] 3
> y = 2L 
[1] 2
Running test id 1440     Tests 1441-1444 not run. If required install the 'fr_FR.utf8' locale.
Error in eval(expr, envir, enclos) : 
  3 errors out of 4247 (lastID=1526.2, endian=little, sizeof(long double)==16) in inst/tests/tests.Rraw on Mon Jun 22 19:02:32 2015. Search tests.Rraw for test numbers: 648, 1101, 1262.
>

**Comment by arunsrinivasan** [comment]
As mentioned under commit c14de41360e I don't think there are any more valgrind issues (or at least they aren't real issues, rather due to valgrind's limitation, I think).

**Comment by mattdowle** [comment]
Agreed.
