### ISSUE TITLE
Error on 64bit Machine

### ISSUE THREAD

**Issue by gchlapinski** [Rdatatable/data.table#1198]
Hi,
I get an error using this simple code on 64 bit machine. This code works on 32 bit machine.

Sorry for the format of this issue.

Wpisz 'demo()' aby zobaczyć demo, 'help()' aby uzyskać pomoc on-line, lub
'help.start()' aby uzyskać pomoc w przeglądarce HTML.
Wpisz 'q()' aby wyjść z R.

> library(data.table)
data.table 1.9.4  For help type: ?data.table
*** NB: by=.EACHI is now explicit. See README to restore previous behaviour.
Warning message:
pakiet ‘data.table’ został zbudowany w wersji R 3.2.1 
> tables()
No objects of class data.table exist in .GlobalEnv
> X <- data.table(x=1:5)
> tables()
Error in paste("%", nchar(m[1, "NROW"]), "s", sep = "") : 
  4 argumenty przekazano do '.Internal(nchar)' który wymaga 3
> setkey(X,x)
Error in setkeyv(x, cols, verbose = verbose, physical = physical) : 
  4 argumenty przekazano do '.Internal(nchar)' który wymaga 3
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 x64 (build 9200)

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.4

loaded via a namespace (and not attached):
[1] magrittr_1.5   plyr_1.8.3     tools_3.2.0    reshape2_1.4.1 Rcpp_0.11.6    stringi_0.5-2  stringr_1.0.0  chron_2.3-46

**Comment by gchlapinski** [comment]
Upgrade to version 3.2.1 has solved the problem.

**Comment by mattdowle** [comment]
Thanks for update. I suspect that R 3.2.1 didn't actually fix it and it might happen again.  If so, upgrade to data.table 1.9.5 from GitHub is more likely to fix it.

**Comment by gchlapinski** [comment]
It wasn't problem of 64bit machine. It was because I have installed data.table package on R-3.2.0 which was built under R-3.2.1. In this way I get errors using just tables() function. 
I suppose that error is connected with a new feature of R-3.2.1 about nchar function.
