### ISSUE TITLE
RStudio hangs when producing grouped plots with data.table

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#1203]
When I run the following code in RStudio release preview 0.99.447 and latest dev data.table under R 3.2.1 in Win8.1 x64

```r
library(data.table)
x <- data.table(id = 1:10000, x = rnorm(10000), g = sample(letters[1:4], 10000, TRUE))
par(mfrow=c(2,2))
x[, plot(x), by = g]
```

RStudio finishes the evaluation quickly but the internal state seems to hang and never execute more code. I run exactly the same code in R terminal and it works perfectly.

I'm not sure if the problem is in RStudio or data.table.

I also post the question at https://support.rstudio.com/hc/communities/public/questions/204285068-RStudio-hangs-when-producing-grouped-plots-with-data-table.

**Comment by arunsrinivasan** [comment]
@renkun-ken I can't reproduce it by running R from terminal. Could you please confirm?

**Comment by renkun-ken** [comment]
@arunsrinivasan I've mentioned that the same code works in R terminal but not in RStudio.

**Comment by arunsrinivasan** [comment]
Oops.. missed that. I'm not sure why you're not sure then :-).

**Comment by renkun-ken** [comment]
It should be 99.99% something wrong with RStudio so I post a issue there :) Hope some minor change could fix this.

**Comment by jangorecki** [comment]
I've checked how it works on Ubuntu 14.04 and 0.99.441
```r
library(data.table)
x <- data.table(id = 1:10000, x = rnorm(10000), g = sample(letters[1:4], 10000, TRUE))
par(mfrow=c(2,2))
x[, plot(x), by = g]
# Empty data.table (0 rows) of 1 col: g
# Error: 'x' and 'y' lengths differ in plot.xy()
# Error: 'x' and 'y' lengths differ in plot.xy()

library(data.table)
x <- data.table(id = 1:10000, x = rnorm(10000), g = sample(letters[1:4], 10000, TRUE))
par(mfrow=c(2,2))
x[, {plot(x)}, by = g]
# Empty data.table (0 rows) of 1 col: g

library(data.table)
x <- data.table(id = 1:10000, x = rnorm(10000), g = sample(letters[1:4], 10000, TRUE))
par(mfrow=c(2,2))
x[, {plot(x); Sys.sleep(0.001)}, by = g]
# Empty data.table (0 rows) of 1 col: g
### 1/4 of the plot

library(data.table)
x <- data.table(id = 1:10000, x = rnorm(10000), g = sample(letters[1:4], 10000, TRUE))
par(mfrow=c(2,2))
x[, {plot(x); NULL}, by = g]
# Empty data.table (0 rows) of 1 col: g
```
`Sys.sleep` seems to have an impact but still it plots only 1/4 plot. None of above code hangs the RStudio/R sessions.

**Comment by jmcphers** [comment]
Hello from RStudio -- we've looked into this and believe it to be a bug on our end (so this issue can probably be closed on yours). It specifically concerns some code specific to the Windows x64 R session process, so it won't be visible on Linux, nor on Windows x32.

**Comment by arunsrinivasan** [comment]
@jmcphers thanks.
