### ISSUE TITLE
Add argument sep to 'dcast' 

### ISSUE THREAD

**Issue by dbetebenner** [Rdatatable/data.table#1210]
Currently, ```dcast``` creates variable names separated by an underscore ```_```   Is it possible to add an additional argument ```sep``` to ```dcast``` analogous to the argument for ```reshape``` that allows a user specific character for the variable name separator

**Comment by arunsrinivasan** [comment]
Absolutely. Could be useful. Will see if I can get it for 1.9.6 already.
