### ISSUE TITLE
margins in dcast.data.table doesn't do anything

### ISSUE THREAD

**Issue by nepse** [Rdatatable/data.table#1214]
In regard to the [question](http://stackoverflow.com/questions/31297284/how-to-cast-multiple-columns-and-values-of-a-data-table/31298794#31298794) posted on SO, I found that `margins` argument in `dcast.data.table` (development version) doesn't produce anything, while running the same code with `dcast` (vs 1.9.4) as seen in two answers for the question above, gives the output. Following is the sample data and code: 

`DT <- data.table(Id = c(1, 1, 1, 1, 10, 100, 100, 101, 101, 101), 
                 Date = as.Date(c("1997-01-01", "1997-01-02", "1997-01-03", "1997-01-04", 
                                  "1997-01-02", "1997-01-02", "1997-01-04", "1997-01-03", 
                                  "1997-01-04", "1997-01-04"))
                 group = c(1,1,1,1,1,2,2,2,2,2),
                 Price.1 = c(29, 25, 14, 26, 30, 16, 13, 62, 12,  6), 
                 Price.2 = c(4, 5, 6, 6, 8, 2, 3, 5, 7, 8))`

**development version**
`kk <- melt.data.table(DT,id.vars=c("Id","Date","group"),
           measure.vars = c("Price.1","Price.2"),
           value.name = "Price")`
`dcast.data.table(kk, Id + variable + group ~ Date, value.var = "Price", fun = sum,margins="Date")`

The use of `margins` doesn't do anything here. 

**1.9.4**
`library(reshape2)`
`kk <- melt(DT,id.vars=c("Id","Date","group"),
                    measure.vars = c("Price.1","Price.2"),
                    value.name = "Price")`
`dcast(kk, Id + variable + group ~ Date, value.var = "Price", fun = sum,margins="Date")`

The use of `margins` generates additional column here. 

I am not sure whether this is a bug or not.

**Comment by arunsrinivasan** [comment]
?dcast mentions that this feature is not yet implemented. I won't be having time to do this anytime soon. It rarely comes up.

**Comment by nepse** [comment]
Thanks @arunsrinivasan.

**Comment by arunsrinivasan** [comment]
duplicate of https://github.com/Rdatatable/data.table/issues/531
