### ISSUE TITLE
update by reference on rolling join

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1217]
Rolling joins seems to not work when mixing with `:=` on rolling join as expected.

```r
library(data.table)
dt1 <- data.table(date = as.Date("2015-06-28")+c(0L,3L,5L,7L),
                  key="date")
dt2 <- data.table(date = as.Date("2015-06-30")+c(0:1,4L),
                  val = letters[7:9],
                  key="date")
dt2[dt1]
#          date val
# 1: 2015-06-28  NA
# 2: 2015-07-01   h
# 3: 2015-07-03  NA
# 4: 2015-07-05  NA
dt2[dt1, roll=TRUE]
#          date val
# 1: 2015-06-28  NA
# 2: 2015-07-01   h
# 3: 2015-07-03   h
# 4: 2015-07-05   i
copy(dt1)[dt2, val := i.val][]
#          date val
# 1: 2015-06-28  NA
# 2: 2015-07-01   h
# 3: 2015-07-03  NA
# 4: 2015-07-05  NA
```

Assuming above code I would expect the below lookup column by reference on rolling join works similarly.  
It now produces:
```r
copy(dt1)[dt2, val := i.val, roll=TRUE][]
#          date val
# 1: 2015-06-28   g
# 2: 2015-07-01   h
# 3: 2015-07-03   i
# 4: 2015-07-05  NA
```

While I would expect:

```r
#          date val
# 1: 2015-06-28  NA
# 2: 2015-07-01   h
# 3: 2015-07-03   h
# 4: 2015-07-05   i
```

**Comment by arunsrinivasan** [comment]
The code 

```r
dt2[dt1, roll = TRUE]
```
does this. For each value of `dt1$date`, find the matching row indices on `dt2$date`. 

1. If it matches, extract all columns of `dt2` corresponding to those matching rows, along with all columns of `dt1`. E.g., `dt1$date[2] = "2015-07-01"` matches with `dt2$date[2] = "2015-07-01"` (use `which = TRUE` to find matching indices).

2. If `dt1$date` doesn't match, and falls in a gap, instead extract the columns of `dt2` from the previous row instead (roll last observation forward). E.g., `dt1$date[3] = "2015-07-03"` falls in between `dt2$date[2] = "2015-07-01"` and `dt2$date[3] = "2015-07-04"`. So we roll the last row index forward (= 2).

Whereas the code

```r
dt1[dt2, val := i.val, roll = TRUE]
```
finds matching rows in `dt1$date` for each row in `dt2$date` instead (the other way around). I'll leave you to work out the same logic here.. Again using `which = TRUE` helps understanding. 

Essentially`dt1[dt2]` and `dt2[dt1]` aren't usually the same. Feel free to ask if it doesn't still clarify. But I think there's no issue here.

**Comment by jangorecki** [comment]
Thanks for detailed description. My code `dt2[dt1, roll=TRUE]` gives expected output, but it is not adding column by reference, right? so if `dt2` has 100 columns and I'm interested into one of them I should use `:=` and pick the column, but because of `:=` in `j` the dataset `x` needs to be swapped with `i`. Also `which` doesn't help on `:=`, and using it without `:=` will not reflect required use case.
I'm stuck and cannot achieve expected output, I will use SO for that.

**Comment by arunsrinivasan** [comment]
I suppose you're looking for this...?

```r
dt1[, val := dt2[dt1, val, roll = TRUE]][]
```

**Comment by jangorecki** [comment]
yes, thanks! ehh I didn't think about nesting join this way.

**Comment by jangorecki** [comment]
I believe the query I was asking `dt1[dt2, val := i.val, roll=TRUE]` and my expected results would be more consistent with current data.table argument is cases of:

- data.table to `i`
- `:=` in `j` expression

Where the `x` is modified in place with value taken from `i` dataset. It should not depends on if `roll` argument is provided or not.

**Comment by jangorecki** [comment]
an example use: http://stackoverflow.com/a/35486386/2490497 (to update if and when changed)

**Comment by jangorecki** [comment]
Another question that find current behaviour not intuitive https://stackoverflow.com/questions/54501800/identify-the-difference-between-rows-in-data-table-and-create-new-column-saying
