### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ladida771** [Rdatatable/data.table#1219]
# The following example returns unexpected output
require(data.table)
DT=data.table(ric=c('A','B','C'),ric_d=c(3,3,1))
DT[ric_d==DT[,max(ric_d)],ric_d:=4]
DT[ric=='C',]

# Expecting:
#   ric ric_d
# 1:   C     1
# Getting:
# Empty data.table (0 rows) of 2 cols: ric,ric_d

# The above example returns very different and expected output if column 'ric' is renamed to 'vic'
require(data.table)
DT=data.table(vic=c('A','B','C'),ric_d=c(3,3,1))
DT[ric_d==DT[,max(ric_d)],ric_d:=4]
DT[vic=='C',]

# Session info:
#R version 3.2.1 (2015-06-18)
#Platform: x86_64-w64-mingw32/x64 (64-bit)
#Running under: Windows 8 x64 (build 9200)

#locale:
#[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
#[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

#attached base packages:
#[1] stats     graphics  grDevices utils     datasets  methods   base     

#other attached packages:
#[1] data.table_1.9.4

#loaded via a namespace (and not attached):
#[1] magrittr_1.5   plyr_1.8.3     tools_3.2.1    reshape2_1.4.1 Rcpp_0.11.6    stringi_0.5-5  stringr_1.0.0  chron_2.3-47

**Comment by franknarf1** [comment]
I see your expected output with version 1.9.5. If you don't want to or cannot upgrade, try putting parentheses around it, like `DT[(ric=='C')]` Also, the comma is not needed.

Here are the bug reporting guidelines (including testing on the latest version), for reference: https://github.com/Rdatatable/data.table/wiki/How-to-file-a-bug-report

**Comment by arunsrinivasan** [comment]
I've no idea what this report is about, but thanks @franknarf1 for the help.
