### ISSUE TITLE
uniqueN could supports list input

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1224]
And not just lists but any type which is not supported by `uniqueN` could simply redirects to `length(unique(.))`.
```r
library(data.table)
d1 <- data.table(a = 1:4, l = list(list(letters[1:2]),list(Sys.time()),list(1:10),list(letters[1:2])))
d1[,length(unique(l))]
# [1] 3
d1[,uniqueN(l)]
#Error in uniqueN(l) : 
#  x must be an atomic vector or data.frames/data.tables
```
Looks pretty easy to do, I will try to make PR for that.

**Comment by arunsrinivasan** [comment]
@jangorecki this seems to do something different. 

```r
dt = data.table(x=c(1,1,2,3), y=c(2,2,3,4))
nrow(unique(dt)) # [1] 3

length(unique(as.list(dt))) # [1] 2
```

It seems to not check row-wise, rather if any element of list is identical to another.

**Comment by jangorecki** [comment]
I used `uniqueN` / `length(unique(` on single column while you did it on both columns. To make it more clear I simplified the example data:
```r
library(data.table)
d1 <- data.table(l = list(list(letters[1:2]),list(Sys.time()),list(1:10),list(letters[1:2])))
d1[,length(unique(l))]
d1[,uniqueN(l)]
```

**Comment by arunsrinivasan** [comment]
Okay. I guess the idea here is that a *list* is a *vector* as well.. that's fine.
Could you make sure it'd work on multiple columns as well? For example:

```r
d1 <- data.table(a = c(1:3,1), l = list(list(letters[1:2]),list(Sys.time()),list(1:10),list(letters[1:2])))
nrow(unique(as.data.frame(d1))) # [1] 3
```

We'd want that to work, if someone did:

```r
d1[, uniqueN(.SD)] 
```

This wouldn't work at the moment. Adding a check as to whether any column is of `list` type might be quite expensive when one performs a grouping operation (checking type for each group). And this is quite a rare case.. Hm.

**Comment by arunsrinivasan** [comment]
Maybe for single column case we can already use the fix you've provided, and take care of `.SD` / `data.table` cases later. Will merge asap. Thanks @jangorecki.

**Comment by jangorecki** [comment]
This should not affect `.SD` as the check is `if (!is.atomic(x) && !is.data.frame(x)) return(length(unique(x)))`.
```r
data.table(a = list(1:2,4))[,is.data.frame(.SD)]
# [1] TRUE
```
I will update doc, readme, and squash soon.

**Comment by arunsrinivasan** [comment]
This fix returns wrong result for `list(1:2, 3:4)`. `length(unique())` should only be dispatched for list of lists.. not list of atomics.

**Comment by jangorecki** [comment]
@arunsrinivasan I'm not sure if I follow. You are saying the list should be handled same as data.table? I don't think it is a proper behavior for list. I can create `uniqueN` generic so it can be flexible.

**Comment by arunsrinivasan** [comment]
Nope. I'm comfortable with `uniqueN` not supporting `list-of-lists`. It was not the original purpose. But it needs to do what `forder()` does for list of atomics (using `mget()` in `j` argument would not work as intended otherwise).

**Comment by jangorecki** [comment]
I will quote from source code, it is quite on point.
```r
# simple straightforward helper function to get the number 
# of groups in a vector or data.table. Here by data.table, 
# we really mean `.SD` - used in a grouping operation
```

**Comment by arunsrinivasan** [comment]
That was done before your update to lists. It just wasn't updated. What's your point?

**Comment by arunsrinivasan** [comment]
Will revisit later if the issue of lists come up. I'll revert this functionality to atomics / data.frames for now.

**Comment by jangorecki** [comment]
@arunsrinivasan yes, just doing it now.

**Comment by MichaelChirico** [comment]
A use case for this is in the syntax:

`DT[ , uniqueN(.(var1, var2)), by = var3]`

Could be handled with `.SDcols = c("var1", "var2")` or with `uniqueN(setDT(var1, var2))`.

The latter in particular pokes at: `uniqueN` should work at least for `data.table`-like `list`s.

I was also confused by the documentation, which has:

    uniqueN(x, by=if (is.list(x)) seq_along(x) else NULL, na.rm=FALSE)

I was surprised to see a test for `is.list(x)` in the official usage of `uniqueN`, but `x` can't be a _list_ list (though it's made clear in the Arguments section that this isn't handled).
