### ISSUE TITLE
Potentially strange behaviour of .N

### ISSUE THREAD

**Issue by cguill95** [Rdatatable/data.table#1230]
Hello,

First, thank you again for the data table package it is awesome !!! (I will keep saying this everytime I post   here :))

Now getting straight to the point: I recently experienced what I think is a strange behaviour with the symbol `.N`
Having read the FAQ, my understanding was that `.N` could be used (in a very simplistic way I agree) to get the last row of a data table like this `DT[.N]`
But if we look at the following script:

````r
require(data.table)
DT1 <- data.table(COL1=1:3)
DT2 <- data.table(COL2=4:5)
# Case 1: 
DT2[, DT1[, .N]]
# [1] 3
# Case 2: 
DT2[, DT1[.N, COL1]]
# [1] 2
````
We see that `.N` is evaluated within the frame of `DT1` for Case 1 and within the frame of `DT2` for Case 2.

Question: Is the second behaviour the expected one ?

Thanks in advance

**Comment by arunsrinivasan** [comment]
Please check with `1.9.5` always before posting. I've also edited your code for easy copy/paste (including the code to load the package).

**Comment by cguill95** [comment]
Sorry for the spamming, I will do that next time.

THanks

**Comment by arunsrinivasan** [comment]
@cguill95, no worries :+1: . 

Thanks for letting us know that you find data.table useful. It definitely motivates us.
