### ISSUE TITLE
`mult="none"` option in `[.data.table`

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1233]
Sometimes, when there are multiple matches in a merge, I prefer to just drop those matches entirely as a curb against mismatching (e.g., there are multiple matches when I expected there to be only 1).

As a workaround, I find myself doing something like `dt_1[dt_2[,if (.N==1) .SD,by=key],...]`, but this can be slow if there are many `key`s and `dt_2` is large; better, it seems, would be to just discard the `.N>1` cases via `mult` in `[.data.table`.

**Comment by jangorecki** [comment]
somehow related to #940 - I did propose to raise error using `nomatch` arg there.

**Comment by MichaelChirico** [comment]
@jangorecki yes, very much in the same vein as that thread--basically generalizing the possible returns for `mult`. Would also be fine to see something like `mult=5`.

**Comment by arunsrinivasan** [comment]
Closed as duplicated of new issue #1260.
