### ISSUE TITLE
Opened file ok, obtained its size on disk (0.0MB), but couldn't memory map it. 

### ISSUE THREAD

**Issue by cptdime** [Rdatatable/data.table#1238]
I'm getting the following error while trying to "fread" in a 23GB file or a 45GB file.  The machine has 64GB with swap turned OFF.  I am able to read various size files up to 7.1GB with fread (this isn't exact, it's just the largest file I read before I skip to a 23GB file).  Shouldn't it be able to be memory mapped?  How much overhead is involved with fread?  Also, note: the file is clearly not 0.0MB on disk.

Opened file ok, obtained its size on disk (0.0MB), but couldn't memory map it. This is a 64bit machine so this is surprising. Please report to datatable-
help

**Comment by jangorecki** [comment]
Thanks for the report but without the info mentioned in [How to file a bug report](https://github.com/Rdatatable/data.table/wiki/How-to-file-a-bug-report) the issue can be hard to debug.

**Comment by cptdime** [comment]
My apologies.  I stumbled on the answer.  Although I have 64G of RAM, I just realized /etc/security/limits.conf was limiting me to 8GB.  

Not sure why it says 0.0MB on disk, however.

**Comment by arunsrinivasan** [comment]
Thanks for the report. I'm guessing you're able to read the file now though.. not sure. But hard to do much without being able to reproduce.
