### ISSUE TITLE
GGally's ggpairs internal conflict

### ISSUE THREAD

**Issue by ProfFancyPants** [Rdatatable/data.table#1241]
I am not sure if this is a problem with ggpairs or with data.table, but it was my impression that anything that worked with a data.frame should work with a data.table as well. Unfortunately, I suspect the GGally package probably uses some silly non-standard evaluation to plot its graphs, and that combined with general ggplot silliness causes data.tables to crash R. Here is an example:
 
library(GGally)
df <- data.frame(var1 = rnorm(400, 10,1), var2 = rnorm(400,10,1),var2 = rnorm(400,10,1))
ggpairs(data = df, params = c(binwidth = 1), verbose = TRUE)
dt <- data.table(var1 = rnorm(400, 10,1), var2 = rnorm(400,10,1),var2 = rnorm(400,10,1))
ggpairs(data = dt, params = c(binwidth = 1), verbose = TRUE)

**Comment by frenchja** [comment]
The problem appears to be with [`ggally_cor`](https://github.com/ggobi/ggally/blob/150077ce9b49133059b93b0c276938a19745c0b7/R/gg-plots.r#L181-L190).  `xCol` for that specific cor plot gets set to `"var2.1"`, which of course doesn't exist in the data.table.  So when `complete.cases` is called on the data.table subset with a nonexistent column, it breaks.  Why this *does* work with a data.frame, I can't say.

It's also interesting that when debugging, there are duplicated column names in the internal `data` object:
```r
colnames(data)
[1] "var1" "var2" "var2"
```

**Comment by frenchja** [comment]
Unique names, of course, solves the problem:

```r
dt <- data.table(var1 = rnorm(400, 10,1), var2 = rnorm(400,10,1),var2 = rnorm(400,10,1))
setnames(dt, make.names(names(dt), unique = TRUE))
ggpairs(data = dt, params = c(binwidth = 1), verbose = TRUE)
```

**Comment by ProfFancyPants** [comment]
I implemented a fixed colnames function to mask the original. 

colnames <- function(x, do.NULL = TRUE, prefix = "col", envir = parent.frame()) {
  x <- substitute(x)
  for (i in seq_along(x)) {
    if (!identical(as.character(x[[i]]), "")) {
      if (is.data.table(eval(substitute_q(x[[i]], env = envir)))) {
        sub_list <- list(detected_DT = x[[i]])
        eval(substitute({detected_DT <- setDF(copy(detected_DT))}, sub_list))
      }
    }
  }
  x <- eval(x, environment())
  if (is.data.frame(x) && do.NULL) 
    return(names(x))
  dn <- dimnames(x)
  if (!is.null(dn[[2L]])) 
    dn[[2L]]
  else {
    nc <- NCOL(x)
    if (do.NULL) 
      NULL
    else if (nc > 0L) 
      paste0(prefix, seq_len(nc))
    else character()
  }
}

I don't know how solid the fix is, but I haven't seen any problems yet. It just cycles through the expression and does a temporary setDF where needed, then evaluates the original expression.

**Comment by arunsrinivasan** [comment]
I think `ggpairs()` should handle duplicate names (either by creating unique names with a warning or returning an error and informing the user to provide unique names).

The same case can happen with `data.frame` as well when `check.names = FALSE`

```r
require(GGally)
df <- data.frame(var1 = rnorm(400, 10,1), var2 = rnorm(400,10,1),var2 = rnorm(400,10,1), check.names=FALSE)
ggpairs(data = df, params = c(binwidth = 1), verbose = TRUE)
# Plot # 1
# [1] "trying left axis"
# Plot # 2
# Error in `[.data.frame`(data, , c(xCol, yCol)) : 
#   undefined columns selected
```
