### ISSUE TITLE
Bug: `.GRP` should create column named `GRP`, not `.GRP` (a la `.I`, `.N`)

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1243]
That `.GRP` returns a variable named `.GRP` by default is causing some errors.

Consider:

    data.table(id=rep(1:3,each=5),yr=rep(rep(1:3,3),rep(c(2,1,2),3)))[,.GRP,by=.(id,yr)][,!.GRP%in%range(.GRP),by=id]

(Basically, trying to eliminate the first and last `yr` of observation from each `id`)

This is an error: `cannot change value of locked binding for '.GRP'`. I can think of a number of workarounds, but it seems the simpler solution is to simply change the naming behavior.

I imagine this is the same reason why `.I` and `.N` return columns named `I` and `N` by default.

**Comment by eantonya** [comment]
I haven't thought this through very carefully, but I assume whatever argument applies to `.GRP` also applies to `.BY`.

**Comment by jangorecki** [comment]
Not sure but maybe it is only a matter of adjusting regex in two lines of `[.data.table`:
`jvnames = gsub("^[.]([NI])$","\\1",as.character(jsub))` in [data.table.R#L896](https://github.com/Rdatatable/data.table/blob/2d2a480cd6b061de1637b1e59addb58b181328bd/R/data.table.R#L896)
`jvnames[jj-1L] = gsub("^[.]([NI])$","\\1",deparse(jsubl[[jj]]))` in [data.table.R#L907](https://github.com/Rdatatable/data.table/blob/2d2a480cd6b061de1637b1e59addb58b181328bd/R/data.table.R#L907)

**Comment by MichaelChirico** [comment]
@jangorecki  perhaps [these lines](https://github.com/Rdatatable/data.table/blob/master/R/data.table.R#L1418-L1421) as well

**Comment by arunsrinivasan** [comment]
@MichaelChirico no, just the ones Jan's pointed. Would be great to wrap this up..

**Comment by MichaelChirico** [comment]
@arunsrinivasan gonna take care of it now. Is there anything that needs to be changed in the tests / manual for this?
