### ISSUE TITLE
Inconsistent assignment behavior

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#1247]
The following behavior seems inconsistent:

```rconsole
> p <- data.table(a=1:10)
> x <- 0
> p[, { cat(x, ",", a, "\n"); x <<- a; NULL}, by = a]
0 , 1 
2 , 2  # why not 1 , 2 ?
3 , 3 
4 , 4 
5 , 5 
6 , 6 
7 , 7 
8 , 8 
9 , 9 
10 , 10 
Empty data.table (0 rows) of 1 col: a
```

which gives different output from `for`

```rsoncole
> x <- 0
> for (m in p$a) { cat(x, ",", m, "\n"); x <<- m; }
0 , 1 
1 , 2 
2 , 3 
3 , 4 
4 , 5 
5 , 6 
6 , 7 
7 , 8 
8 , 9 
9 , 10 
```

I'm using latest dev of data.table. My session info:

```
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.5

loaded via a namespace (and not attached):
[1] tools_3.2.1  chron_2.3-47
```

**Comment by shrektan** [comment]
@renkun-ken I guess the reason of this happening is because in the data.table environment, the `x` is assigned by reference, which means, when you do `x<<-m`, you mean `x` is `m`.

so, what you can do is like this:

```r
p <- data.table(a=1:10)
x <- 0
p[, { cat(x, ",", a, "\n"); x <<- a + 0; NULL}, by = a]
```

or 

```r
p <- data.table(a=1:10)
x <- 0
p[, { cat(x, ",", a, "\n"); x <<- copy(a); NULL}, by = a]
```

**Comment by franknarf1** [comment]
Another fairly direct demonstration would be:

    DT <- data.table(a=1:3)
    x = 0
    DT[,{print(identical(x,a)); x <<- a; NULL},by=a]
    # FALSE TRUE TRUE

My guess is that there is no good reason to be using `<<-`, nor a good idea to assume that it behaves a certain way inside various functions that abstract loops (data.table, *apply, group_by, etc.).

**Comment by renkun-ken** [comment]
@shrektan I think you are right. `<<-` in `j` performs reference assignment. The following code show this explicitly:

```rconsole
> x <- 0
> p[, { x <<- a; NULL }]
NULL
> x
 [1]  1  2  3  4  5  6  7  8  9 10
> p[a <= 5, a := 0]
> x
 [1]  0  0  0  0  0  6  7  8  9 10
```

@franknarf1, indeed, this is more like an experiment on how things work than a practical way of use :)

**Comment by eantonya** [comment]
FYI this is regular R behavior and has little to do with `data.table`. Assignment in R is by reference, and only when the object is modified in a way that R can detect, is the reference counter updated and a new object created.

**Comment by shrektan** [comment]
Get it. This is new to me. 


发自网易邮箱大师
在2015年07月29日 23:33，eduard 写道:

FYI this is regular R behavior and has little to do with data.table. Assignment in R is by reference, and only when the object is modified in a way that R can detect, is the reference counter updated and a new object created.

**Comment by renkun-ken** [comment]
Thanks for your explanation. Copy-on-modify mechanism is apparent in most cases; in this case, it looks more indirect but actually is more explicit.
