### ISSUE TITLE
Revise example(data.table)

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1250]
Important not least because these days 3rd party sites repeat this page; e.g.
http://www.inside-r.org/packages/cran/data.table/docs/as.data.table
http://www.rdocumentation.org/packages/data.table/functions/data.table

This issue concerns the Examples section of ?data.table, run by user with example(data.table).

Should use `.()` consistently rather than `list()`.
Introduce the power of j earlier rather than comparing to data.frame first,  e.g. : 

"anonymous lambda" in j ... no need for a function.   "do" anything
DT[, {tmp<-mean(colA);  colB-tmp}, by=.(month(date), region)]

doesn't need to return any data at all ...
pdf("new.pdf")
DT[, plot(colB,colA), by=...]
dev.off()

Example using .N, .GRP, .SD
.N = "number of rows in this group".  There is no example here using it at the moment.
.SD = "this group's Subset of Data".  That text should appear in the examples section.

DT[, .SD[someCol == max(someCol)], by=...]  # subquery by group

apply over subset of columns, by group :
DT[, lapply(.SD, mean), by=..., .SDcols=100:150]

On a big data.table, DT,  try :
DT[ someCol == 42 ]     # build, store and use index, automatically
then repeat it straight away :
DT[ someCol == 42 ]     # uses index stored by line above.  Instant.
DT[ someCol %in% c(42,45,84) ]   # instant
key(DT)  # primary index (if any)
key2(DT)  # secondary indexes (if any)

Link to the DataCamp course here in ?data.table.

After nicer examples above come first,  replace : 
  DT[,v]    # v column (as vector)
with :
  DT[,V1]    # the column named "V1" as a vector, no quotes needed (unlike data.frame)
  DT[,.(V1)]  # the column named "V1" as a data.table.  There is no 'drop' in data.table.
  DT[, myCols, with=FALSE]  # the columns in variable myCols, as a data.table
  DT[[col]]    # easier and fastest way to lookup a single column by name or number, as a vector

**Comment by mattdowle** [comment]
Add in examples that as long as j returns a list, that's fine;  returns meaning last item of j={ ... }. Each j can evaluate to a varying number of rows, ok.  Maybe example where one 1 group has 1 row and head(.SD, 3) therefore returns just one 1 row for that group.

**Comment by arunsrinivasan** [comment]
Incorporated missing cases in https://github.com/Rdatatable/data.table/commit/da7ba2908f901af555b6915d9667b5138935fa7a
