### ISSUE TITLE
Strange behavior for filtering in data.table with NA values

### ISSUE THREAD

**Issue by sergiizaskaleta** [Rdatatable/data.table#1252]
Reported from [this](http://stackoverflow.com/questions/31873514) SO question:
I've stumbled upon weird data table `i` behavior that returns a row with `NA`s where I would expect an empty data table. See:  

```r
a = data.table(a = 1, d = NA) 
a[!is.na(a) & d == "3"] 
#     a  d
# 1: NA NA
```
I would expect an empty data table as a result here.
Compare to:

```r
a = data.table(a = c(1,2), d = c(NA,3))
a[!is.na(a) & d == "3"] 
#    a d
# 1: 2 3
```
This one does not produce an extra row with `NA` values, though.

```r
> sessionInfo()
# R version 2.15.2 (2012-10-26)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# 
# locale:
# [1] LC_COLLATE=English_United Kingdom.1252 
# [2] LC_CTYPE=English_United Kingdom.1252
# 
# [3] LC_MONETARY=English_United Kingdom.1252
# [4] LC_NUMERIC=C
# 
# [5] LC_TIME=English_United Kingdom.1252
# 
# attached base packages:
# [1] stats graphics grDevices utils datasets methods base
```

**Comment by sergiizaskaleta** [comment]
R version 2.15.2 (2012-10-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by mattdowle** [comment]
Many thanks.
The link to SO post doesn't seem to work - could you correct it please.
Did you really mean to include `!is.na(a)` i.e. on a column which has no NA?
i.e. instead of :
```r 
a = data.table(a = c(1,2), d = c(NA,3))
a[!is.na(a) & d == "3"]
```
this seems sufficient to demonstrate : 
```r
a = data.table(a = c(1,2), d = c(NA,3))
a[d == 3]
```
Indeed seems like there could be a bug here with 1-row data.table's containing one NA.

**Comment by sergiizaskaleta** [comment]
This actually was used in a piece of code that worked per subsets of a data.table, and in some rare subset case there could be such a scenario.

**Comment by arunsrinivasan** [comment]
Quite tightly linked to https://github.com/Rdatatable/data.table/issues/857 IMO. Would push this to `1.9.8`..

**Comment by arunsrinivasan** [comment]
Fixed with this commit: https://github.com/Rdatatable/data.table/commit/353cf8af56db5e604fc4b366acc2e9b61d35da47

Marked the wrong issue name while committing.

**Comment by mattdowle** [comment]
Causing package treemap to fail. Investigating.

**Comment by alexdthomas** [comment]
Just stumbled on this issue.  Using @mattdowle's example 

```
a = data.table(a = c(1,2), d = c(NA,3))
a[a==1&!d==3, ]
#Empty data.table (0 rows) of 2 cols: a,d
a[a==1&d!=3, ]
#Empty data.table (0 rows) of 2 cols: a,d
a[a==1&is.na(d), ]
#   a  d
# 1: 1 NA
```

I would expect the last result with the first two indexes, is this a new bug or have I always used `data.table` incorrectly?  

```
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.11.8

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1   
```

**Comment by st-pasha** [comment]
@alexdthomas The problem here is that NA doesn't compare equal, nor unequal, to any other value:
```
> a[, .(d, d==3, d!=3, d==NA, d==d)]
    d   V2    V3 V4   V5
1: NA   NA    NA NA   NA
2:  3 TRUE FALSE NA TRUE
```
This is the same convention as used in base R too:
```
> a$d == 3
[1]   NA TRUE
> a$d != 3
[1]    NA FALSE
```

**Comment by alexdthomas** [comment]
@st-pasha Thanks!  Well, that's embarrassing.  Apparently have 9 years of using R I either never really understood this or totally forgot about it.  For anyone else who stumbles on this I found a very helpful StackOverflow Q&A on how to correctly perform the selection I was trying to do. https://stackoverflow.com/questions/16221742/subsetting-a-data-table-using-some-non-na-excludes-na-too
