### ISSUE TITLE
Possible bug when using cast() in Mac machine

### ISSUE THREAD

**Issue by feifeifeihuang** [Rdatatable/data.table#1254]
First, I'd like to express my appreciation to the development of data.table. It's tremendously useful and powerful. One of the best thing ever happened. 

I'd like to report an issue though when my colleague and I were working with data.table. We noticed that the column name of data.table will change if you use that column as value in cast() function. data frame don't have this behavior, and this only happens in Mac. Windows works fine. Example is as following.

My laptop: MacBook Pro, 2.5 GHz Intel Core i7. 16GB 1600 MHz DDR3 memory. OS X Yosemite 10.10.4.

Thank you very much.

> T_dt <- data.table('a' = 1:5, 'b' = c('x', 'y', 'z', 'w','v'), 'c' = c(1991, 1992, 1993, 1994, 1995), 'd' = 20:24)
> T_dt
   a b    c  d
1: 1 x 1991 20
2: 2 y 1992 21
3: 3 z 1993 22
4: 4 w 1994 23
5: 5 v 1995 24
> pp = cast(data=T_dt, a ~ b, value="c", fill=0, add.missing=TRUE)
> T_dt
   a b value  d    ########### Note that column 'c' become 'value' ###########
1: 1 x  1991 20 
2: 2 y  1992 21
3: 3 z  1993 22
4: 4 w  1994 23
5: 5 v  1995 24
> 
> 
> T_df <- data.frame('a' = 1:5, 'b' = c('x', 'y', 'z', 'w','v'), 'c' = c(1991, 1992, 1993, 1994, 1995), 'd' = 20:24)
> T_df
  a b    c  d      ########### Note that column 'c' stay the same ###########
1 1 x 1991 20
2 2 y 1992 21
3 3 z 1993 22
4 4 w 1994 23
5 5 v 1995 24
> pp = cast(data=T_df, a ~ b, value="c", fill=0, add.missing=TRUE)
> T_df
  a b    c  d
1 1 x 1991 20
2 2 y 1992 21
3 3 z 1993 22
4 4 w 1994 23
5 5 v 1995 24

**Comment by arunsrinivasan** [comment]
Please make sure the issue is reproducible on devel version. Can't reproduce on `v1.9.5`.
