### ISSUE TITLE
[Request] allow `on=` to work with both character vectors and lists

### ISSUE THREAD

**Issue by dselivanov** [Rdatatable/data.table#1257]
From #1130 [comments](https://github.com/Rdatatable/data.table/issues/1130#issuecomment-124471872).
It would be nice if `on=` will accept both character vectors and lists as arguments.
```r
DT1[DT2,  on = list(...) ]
# or 
DT1[DT2,  on = .(...) ]
# or 
DT1[DT2,  on = c(...) ]
```

**Comment by arunsrinivasan** [comment]
Thanks @dselivanov.

**Comment by jangorecki** [comment]
According to linked comments, particularly mentioned *join on expression*, the following issue is related [joins on arbitrary functions #625](https://github.com/Rdatatable/data.table/issues/625).
