### ISSUE TITLE
Two dimensional column selector gives different result than data.frame's selector

### ISSUE THREAD

**Issue by JohnMount** [Rdatatable/data.table#1259]
I noticed data.table's two dimensional selector [,] doesn't pick columns the same way data.frame's does, even though the object claims to be both a data.frame and data.table.   Example below:

```r
require(data.table)
data.frame(x=7)[, "x"]
## [1] 7
data.table::rbindlist(list(data.frame(x=7)))[, "x"]
## [1] "x"  # what?
data.frame(data.table::rbindlist(list(data.frame(x=7))))[, "x"]
## [1] 7
class(data.table::rbindlist(list(data.frame(x=7))))
## [1] "data.table" "data.frame"
```

**Comment by ChristK** [comment]
I would recommend you to have a look at the faq (http://datatable.r-forge.r-project.org/datatable-faq.pdf). Your question is answered in paragraph 1.1

**Comment by arunsrinivasan** [comment]
Also the *"Introduction to data.table" vignette from the [Getting started](https://github.com/Rdatatable/data.table/wiki/Getting-started) page explains the reason/idea behind it under `Basics -> g)`. FAQ 2.17 should be helpful to get an idea of other minor differences.

Once you get familiar with the data.table syntax, you'll find yourself using much less of the data.frame syntax (as you can do much more in the `j` argument of a data.table). It's just a matter of getting used to.
