### ISSUE TITLE
Strongly-typed columns in data.table vs R not a strongly-typed language

### ISSUE THREAD

**Issue by alexWhitworth** [Rdatatable/data.table#1263]
Here's a recent error:

 Error in `[.data.table`(dat, , func(.SD), by= group]`,  : 
  Column 21 of result for group 291 is type 'integer' but expecting type 'double'. Column types must be consistent for each group. 

see [this question](http://stackoverflow.com/questions/31819208/data-table-syntax-for-split-apply-combine-ala-plyr) on SO for a similar function to func().

The original dataset comes from a RDBMS accessed via library(RODBC). For purposes of memory in the RDBMS, numeric columns are stored as integers where appropriate. As defined in func(), I set one of the values in the dataset to a numeric value. By default, R stores this as a double

    x <- 51
    is.double(x) # true
    is.integer(x) # false

However, the RDBMS data has this numeric stored as an int, hence the error. 

I was able to track down all locations in my code where this caused a problem and solve it. But I don't think this **should be** a problem in `data.table`. **R** is not **strongly-typed**. So having `data.table` be strongly typed seems problematic. At the minimum, there should be some intelligent logic in `rbindlist()` -- what I'm using here -- to attempt these types of conversions before exiting and returning this type of error.

**Comment by arunsrinivasan** [comment]
Always provide a minimal reproducible example.

We expect the type of operation performed within the group to be identical (both for efficiency and avoiding surprises). This case mostly happens with functions like `median()` whose return type depends on the length and type of input vector. An easy fix is to wrap it with `as.numeric()`.
