### ISSUE TITLE
Direct use of merge.data.table() does work per documentation

### ISSUE THREAD

**Issue by nkurz** [Rdatatable/data.table#1266]
I'm not sure if the export behavior or the documentation is at fault, but 1.9.4 and 1.9.5 do not currently match the documentation.

?merge.data.table
>  You don't need to use the full name of the method although you may if you wish; 
>  i.e., merge(DT1,DT2)  is idiomatic R but you can bypass method dispatch by going
>  direct if you wish: merge.data.table(DT1,DT2)."

DT1 = data.table(i=seq(10), v=rnorm(10), key="i")
DT2 = data.table(i=seq(10), v=rnorm(10), key="i")
dispatch = merge(DT1, DT2)  # works as expected
direct = merge.data.table(DT1, DT2) # does not work
> Error: could not find function "merge.data.table"

**Comment by jangorecki** [comment]
Looks like already solved by this commit: https://github.com/Rdatatable/data.table/commit/44b1e006af81afa517a4a297d5f6f1519b34484e#diff-14dac9bac3964e94af535d2f87bf2af8
confirm and close

**Comment by nkurz** [comment]
Thanks, that commit does in fact change the documentation so that direct usage is no longer suggested.   The error is still the same, but since it is not documented to work presumably this is no longer a bug.  Closing.
