### ISSUE TITLE
[fread] broken functionality in 1.9.6

### ISSUE THREAD

**Issue by ziyadsaeed** [Rdatatable/data.table#1267]
fread from v1.9.4 gives correct results but fread from dev 1.9.5 doesn't.
For eg

create a test.csv file 

``` R
cat("V1, V2, V3
1,2,3
V4, V5, V6, V7
4,5,6,7
8,9,10,11",
    file = "test.csv"
)
```

Notice there are different number of columns
fread from 1.9.4

``` R
fread("test.csv", nrows = 1, header = TRUE, skip = 0)
V1 V2 V3
1:  1  2  3
```

This is what I want

But in fread from v1.9.5

``` R
     fread("test.csv", nrows = 1, header = TRUE, skip = 0)
    V4 V5 V6 V7
    1:  4  5  6  7
    Warning messages:
    1: In fread("test.csv", nrows = 1, header = TRUE, skip = 0) :
     Starting data input on line 3 and discarded previous non-empty line: 1,2,3
    2: In fread("test.csv", nrows = 1, header = TRUE, skip = 0) :
    Stopped reading at empty line 5 but text exists afterwards (discarded): 8,9,10,11
```

Not the expected result.

**Comment by ziyadsaeed** [comment]
Minimum reproducible code is now added.

**Comment by ziyadsaeed** [comment]
This bug has now been released in v1.9.6.

**Comment by jangorecki** [comment]
@ziyadsaeed you can self-close resolved issue

**Comment by ziyadsaeed** [comment]
it isn't resolved. I'm mentioning that this bug was not fixed in the dev version and now the release version 1.9.6 has this bug.

**Comment by arunsrinivasan** [comment]
The default behaviour is right as it is. I'd expect `skip=0` explicitly to work as you intend however.

**Comment by ziyadsaeed** [comment]
what is the workaround to ask fread to just read the first line

**Comment by everdark** [comment]
in 1.9.6 (and 1.9.7 to this point of time) `nrows` no longer forces `fread` to just read those rows.
this makes me frustrated on small files with only the last line having less columns.

`fread("1,2,3\n1,2", nrows=1)` wont work and there seems to be no work-around...
i'd like to achieve reading the entire file except for the unbalanced last line.

and this only happens in small files:

```r
for ( i in 100:1) { 
  lines <- paste0(paste(rep("1,2,3", i), collapse='\n'), "\n1,2")
  fread(lines, nrows=i)
}
```

the above code stopped at i =4, which means the somewhat "undocumented" type checking behavior forces a parsing of at least 5 lines, regardless of the actual number of lines in the given file.

the impact of such feature is that whenever we are `fread`ing a bunch of files with a special treatment of last line (as we already know that the last line and only the last line may be unbalanced in column numbers but we still want to read it separately after `fread`ing the entire file except the last line), and there are files smaller than 6 lines with the last line unbalanced, we need a workaround. (i.e., to not use `fread` in these circumstances)

it will be appreciated that if we can optionally disable such type-checking behavior, or the argument `nrows` is actually not doing what it looks like to do: read only the first `nrows` lines. :)
