### ISSUE TITLE
.BY and list/copy issue 

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1270]
```r
DT = data.table(x=1:2, y=5:6)
DT[, .BY, by=x]$.BY
# [[1]]
# [1] 2

# [[2]]
# [1] 2
```

The first list element should be `1`.

**Comment by jangorecki** [comment]
@arunsrinivasan for R 2.15.0 this issue is still present

**Comment by arunsrinivasan** [comment]
Now that we'll move to R v3.0.0, this is not relevant anymore, @jangorecki ?

**Comment by jangorecki** [comment]
Issue is still present on 3.0.0.
```sh
docker run --rm -it jangorecki/r-3.0.0
```
```r
install.packages("data.table", type = "source", repos = "http://Rdatatable.github.io/data.table")
library(data.table)
DT = data.table(x=1:2, y=5:6)
DT[, .BY, by=x]$BY
#[[1]]
#[1] 2
#
#[[2]]
#[1] 2
```

**Comment by arunsrinivasan** [comment]
I think it's better to bump dependency to 3.1, or wait it out for this issue until we bump it. This is a relatively rare usage, and fixing this requires some tinkering (which'll only go away when we bump R version dependency). 

There's already some code in there for R v3.1+ / previous versions. My suggestion therefore would be to depend on 3.1+.
