### ISSUE TITLE
inconsistency of duplicated columns in j, by, .SD

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1273]
The results of both queries should be the same as `.SD` substitutes the `.(...)`.
```r
library(data.table)
dt <- data.table(a=rep(1:2,2),b=1:4)
dt[, .(a), a]
#    a a
# 1: 1 1
# 2: 2 2
dt[, .SD, a, .SDcols="a"]
#    a a
# 1: 1 1
# 2: 1 1
# 3: 2 2
# 4: 2 2
```
related to https://github.com/Rdatatable/data.table/issues/1269#issuecomment-131194411

**Comment by eantonya** [comment]
I don't understand what's inconsistent about this, looks good to me.

**Comment by jangorecki** [comment]
@eantonya updated first post

**Comment by eantonya** [comment]
I disagree, I think it's doing exactly the right thing and this is just a misunderstanding of what grouping is and what `.SD` is. This has come up before in slightly different form too.

In the first expression, once you group by `a` and then ask what is the value of `a` in that group - it's a single value.

In the second expression, you group by `a`, and then ask what is the subset of the data that corresponds to that group - and that's the entire column `a`.

**Comment by arunsrinivasan** [comment]
Agree with @eantonya. This has come before on the mailing list IIRC.

**Comment by jangorecki** [comment]
@eantonya this sounds quite reasonable, looks like I'm still dt newbie :)
