### ISSUE TITLE
Efficient implementation for accessing rows of any/all of previous groups

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1278]
This has come quite a few times on SO. My initial guess is that the internal implementation of allocating `.SD` using the longest group won't hold here.. it'll require a bit more thought and time to get it done efficiently. But I think this'll be terribly useful for _a lot_ of applications.

Here's one [SO post](http://stackoverflow.com/q/32034003/559784).

**Comment by MichaelChirico** [comment]
In the meantime we have a lot of improvements to rolling algorithms thanks to Jan. Not clear what else would be done here and this FR is a bit non-specific; closing in favor of more specific issues that may be opened in the future.
