### ISSUE TITLE
unique and duplicated methods should replace 'by=' with 'cols='

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1283]
Every other function - `setkey`, `setorder`, `na.omit`, `frank` etc.. has a `cols` argument, while `unique` and `duplicated` seem to have `by` argument..

**Comment by DavidArenburg** [comment]
I was thinking about this too, but this could brake some existing code.

**Comment by jangorecki** [comment]
@DavidArenburg It can be done quite safely, for example:
For `1.9.6` keep current behaviour, keep `by` and add `cols`, add a warning when using `by` that `by` will be removed from `1.9.8`. Also we can use `packageStartupMessage` to list the function and args which behaviour was changed.

**Comment by DavidArenburg** [comment]
Or we can just keep them both while `col` will be the idiomatic behavior and `by` will still work but will  return a warning that this was deprecated

**Comment by arunsrinivasan** [comment]
All other functions should've `by` argument instead of `cols` instead.

**Comment by jangorecki** [comment]
I would say it is not that much important to have those names unified. Especially when it doesn't fit well in all cases. The more important is backward compatibility, thus I would close this issue.
