### ISSUE TITLE
unique and duplicated's default value for 'by='

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1284]
I am not particularly happy with the current option of `unique/duplicated` having `by = key(x)` as the default, especially because there's no message or warning as to which columns are being used  to compute unique values on.

Now that `on=` argument is also in place, and we are entertaining the idea of having to set keys less, maybe it's right time to lift this default value so that it's similar to base R? i.e., with `cols = seq_along(x)` - see #1283.

**Comment by franknarf1** [comment]
I agree.

(I'm guessing a "question" issue is soliciting opinions..? I've no opinion on the `by`->`cols` issue; I like `by`, but could live with `cols`.)

**Comment by arunsrinivasan** [comment]
Meant it to be `internals`, sorry about that.

**Comment by MichaelChirico** [comment]
I agree--I rarely use the default value for `by` in my current usage--even if `x` is keyed, more often I do something equivalent to `by=key(x)[1:2]`, i.e., only using a subset of the assigned keys.

**Comment by jangorecki** [comment]
that would also refer to `uniqueN`

**Comment by cderv** [comment]
Help documentation for these functions seems not to have changed. It still says that `by = key(x)` is used by default. I think we should update the documentation as it is not verry clear right now. 

I discovered this reading through the NEWS for all changes in 1.9.8.
