### ISSUE TITLE
Slow [, colname] extraction in comparison to $colname

### ISSUE THREAD

**Issue by abossenbroek** [Rdatatable/data.table#1288]
I compared in rbenchmark column extraction speed between `[, colname]` and `$colname` with the following code,

    iris_dt <- as.data.table(iris)
    rbenchmark::benchmark(iris_dt$Sepal.Width, replications = 100000)
    #                            test replications elapsed relative user.self sys.self user.child sys.child
    # 1 iris_dt$Sepal.Width       100000    1.06        1      1.07        0         NA        NA
    rbenchmark::benchmark(iris_dt[,Sepal.Width], replications = 100000)
    #                    test replications elapsed relative user.self sys.self user.child sys.child
    #1 iris_dt[, Sepal.Width]       100000   32.36        1     31.68        0         NA        NA

My session info,

    sessionInfo()
    # R version 3.2.0 (2015-04-16)
    # Platform: x86_64-w64-mingw32/x64 (64-bit)
    # Running under: Windows 7 x64 (build 7601) Service Pack 1
    # 
    # locale:
    # [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    # [5] LC_TIME=English_United States.1252    
    # 
    # attached base packages:
    # [1] stats     graphics  grDevices utils     datasets  methods   base     
    # 
    # other attached packages:
    # [1] data.table_1.9.5 rbenchmark_1.0.0 stringr_1.0.0    vimcom_1.2-6    
    # 
    # loaded via a namespace (and not attached):
    # [1] magrittr_1.5  tools_3.2.0   stringi_0.4-1 chron_2.3-45 

I would expect the performance to be either similar or `[, colname]` to be faster.

**Comment by arunsrinivasan** [comment]
Yes. `[.data.table` does a lot and comes with an overhead. For repetitive operations on columns of data.table, we recommend `[[` as `DT[['x']]`, or as you show `$`. 

This may get better when we modularise `[.data.table`, but may not be as efficient as `[[ / $`. Also, I think `[.data.table` returns a copy (which'll improve when `shallow()` is exported).
