### ISSUE TITLE
Better support for encoding

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1293]
One way to provide better Encoding support is to provide an argument while creating/converting a data.table. That is,

```r
data.table(..., encoding = c("unknown", "UTF-8", "Latin-1"))
as.data.table(..., encoding = c("unknown", "UTF-8", "Latin-1"))
setDT(..., encoding = c("unknown", "UTF-8", "Latin-1"))
```

Since we convert the `i` argument of joins to data.tables, even scenarios of vectors/lists are handled. This should drastically reduce the occurrence of encoding warnings.

**Comment by izahn** [comment]
It would be good to improve the situation with respect to merging on columns with marked encodings. The current warning message is leading to nonsense like http://stackoverflow.com/q/33482308/189946

**Comment by shrektan** [comment]
+1

发自我的 iPhone
