### ISSUE TITLE
Documentation for `patterns`?

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1294]
Saw @arunsrinivasan's great vignette on reshaping in `data.table` and the internally implemented `patterns` function was mentioned; I spent a while searching around for how exactly it works before finally confirming it's accepting `regex` [here](https://github.com/Rdatatable/data.table/blob/c9cb39564db79ccd6d2af250bb21131185e5a37c/vignettes/datatable-reshape.Rmd).

`?patterns` and `??patterns` turn up nothing; I guess it would be good to add a snippet about what exactly `patterns` is doing under `?melt` (or under `?patterns` if this syntax is acceptable to other `data.table` functions).

**Comment by jangorecki** [comment]
It was discussed here https://github.com/Rdatatable/data.table/issues/944#issuecomment-114783448
maybe we can merge this issue to #944 by putting a task on the to do list.
