### ISSUE TITLE
DT[i, mult="first"] and DT[i, mult="last"] does not work when i is an expression

### ISSUE THREAD

**Issue by nkurz** [Rdatatable/data.table#1295]
The ?data.table documentation says: "When multiple rows in 'x' match to the row in 'i', 'mult' controls which are returned: 'all' (default), 'first' or 'last'."  So I assumed that DT[x==1, mult="first"] would return the first row where x==1.  But instead, there is no difference between mult="first", mult="last", and mult="all". All rows are always returned.   It's only when joining with another data.table that they work as they appear to be documented.  Is this a bug?  Or just imprecise documentation?  Or am I missing something obvious about how and when the 'mult' option is supposed to work?

```R
library(data.table)
# data.table 1.9.5

?data.table
# mult
# When multiple rows in x match to the row in i, mult controls which
# are returned: "all" (default), "first" or "last"

DT = data.table(x=c(0,1),y=1:10,key="x")
DT
#     x  y
#  1: 0  1
#  2: 0  3
#  3: 0  5
#  4: 0  7
#  5: 0  9
#  6: 1  2
#  7: 1  4
#  8: 1  6
#  9: 1  8
# 10: 1 10

X = data.table(x=1)
X
#    x
# 1: 1

DT[X,mult="all"]
#    x  y
# 1: 1  2
# 2: 1  4
# 3: 1  6
# 4: 1  8
# 5: 1 10

DT[X,mult="first"]
#    x y
# 1: 1 2

DT[X,mult="last"]
#    x  y
# 1: 1 10

DT[x==1,mult="all"]
#    x  y
# 1: 1  2
# 2: 1  4
# 3: 1  6
# 4: 1  8
# 5: 1 10

DT[x==1,mult="first"]
#    x  y
# 1: 1  2
# 2: 1  4
# 3: 1  6
# 4: 1  8
# 5: 1 10

DT[x==1,mult="last"]
#    x  y
# 1: 1  2
# 2: 1  4
# 3: 1  6
# 4: 1  8
# 5: 1 10
```

**Comment by arunsrinivasan** [comment]
`mult=` is only valid when `i` argument is a *list*/*data.frame*/*data.table*.
