### ISSUE TITLE
Ways to return a list of values instead of a data.table in `by` operations

### ISSUE THREAD

**Issue by vspinu** [Rdatatable/data.table#1297]
What is the idiomatic way to avoid rbinding in grouped operation?

Something like

```
dt[, I(sum(b)), by = a]
$`1`
[1] 9

$`2`
[1] 12
```

**Comment by DavidArenburg** [comment]
Can you provide `dt` too please?

**Comment by vspinu** [comment]
Sorry, didn't cut properly:

```
dt <- data.table(a = rep.int(1:2, 3), b = 1:6, key = "a")
```

**Comment by arunsrinivasan** [comment]
There isn't (at least, not designed to). You'll have to do it yourself.

```r
# Either:
ans = dt[, sum(by), by=a]
setattr(as.list(ans$V1), 'names', ans$a)[]

# or
lapply(split(dt$b, dt$a), sum)
```

**Comment by vspinu** [comment]
First case will not work for heterogeneous case which is the main point.

Essentially I would like to have the ability to do `plyr::dlply` with data table. This pattern comes along all the time.  Would you consider a feature request?   

It can be a call of the form `df[, I(expr)]`. Should be straitforward to implement, isn't it?

**Comment by franknarf1** [comment]
You have not clarified what a heterogeneous case would look like, but a list column might be the answer:

    > str(dt[, .(list(ifelse(a %% 2, sum(b), "NAH"))), by = a])
    Classes ‘data.table’ and 'data.frame':  2 obs. of  2 variables:
     $ a : int  1 2
     $ V1:List of 2
      ..$ : int 9
      ..$ : chr "NAH"
     - attr(*, "sorted")= chr "a"
     - attr(*, ".internal.selfref")=<externalptr>

**Comment by vspinu** [comment]
> but a list column might be the answer:

Yes. That's the answer indeed. By "heterogenuous" I meant the output of different length or class per each group: 

```
dt[, .(list(rep.int(1, sample(1:10, 1)))), by = a]
   a    V1
1: 1 1,1,1
2: 2     1
```
Thanks.
