### ISSUE TITLE
Speed up fread reading top n rows

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1300]
It need not map the whole file, if only the first 5 rows are needed, for example.
Caused confusion here:  http://stackoverflow.com/questions/32263566/comparing-speed-of-fread-vs-read-table-for-reading-the-first-1m-rows

**Comment by MichaelChirico** [comment]
@mattdowle this was covered by your recent commits (e.g. [this](https://github.com/Rdatatable/data.table/commit/9fadbcdfb7109b5d15adce07f826c9b58a86d2cf)), no?

**Comment by st-pasha** [comment]
We currently hold that the entire file should be sampled (for the purpose of type detection), even if only a handful of rows are requested.

**Comment by MichaelChirico** [comment]
@st-pasha i've come across files where I've wanted to throttle the input because i know for sure that the type detection will be thrown off by using certain rows... something to keep in mind
