### ISSUE TITLE
rbindlist supports for non-atomic columns

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1302]
The same way that `rbindlist` makes `c()`-like process on the atomic columns (column _"a"_ in below example) it would be nice to have non-atomic columns (column _"z"_ in below example) combined using `list()`-like process.

``` r
library(data.table)
l = list(
    list(a=1, z=list()),
    list(a=2, z=list("m"))
)
rbindlist(l)
# Error in rbindlist(l) : 
#   Column 2 of item 1 is length 0, inconsistent with first column of that item which is length 1. rbind/rbindlist doesn't recycle as it already expects each item to be a uniform list, data.frame or data.table

# expected
str(data.table(a=c(1,2), z=list(list(),list("m"))))
# Classes ‘data.table’ and 'data.frame':    2 obs. of  2 variables:
#  $ a: num  1 2
#  $ z:List of 2
#   ..$ : list()
#   ..$ :List of 1
#   .. ..$ : chr "m"
#  - attr(*, ".internal.selfref")=<externalptr> 
```

It appears currently it can handle list but not in a generic manner:

``` r
# this works - but *z* losses list class in each row
l = list(
    list(a=1, z=list("z")),
    list(a=2, z=list(c("a","b")))
)
str(rbindlist(l))
# Classes ‘data.table’ and 'data.frame':    2 obs. of  2 variables:
#  $ a: num  1 2
#  $ z:List of 2
#   ..$ : chr "z"
#   ..$ : chr  "a" "b"
#  - attr(*, ".internal.selfref")=<externalptr> 

# this not works
l = list(
    list(a=1, z=list("z",1)),
    list(a=2, z=list(c("a","b")))
)
str(rbindlist(l))
# Error in rbindlist(l) : 
#   Column 2 of item 1 is length 2, inconsistent with first column of that item which is length 1. rbind/rbindlist doesn't recycle as it already expects each item to be a uniform list, data.frame or data.table

# expected
str(data.table(a=c(1,2), z=list(list("z",1),list(c("a","b")))))
# Classes ‘data.table’ and 'data.frame':    2 obs. of  2 variables:
#  $ a: num  1 2
#  $ z:List of 2
#   ..$ :List of 2
#   .. ..$ : chr "z"
#   .. ..$ : num 1
#   ..$ :List of 1
#   .. ..$ : chr  "a" "b"
#  - attr(*, ".internal.selfref")=<externalptr> 
```

it could handle any non-atomic types, not just lists.

**Comment by dselivanov** [comment]
Does somebody work on this? Very useful feature. If not, I can try to have a look.

**Comment by arunsrinivasan** [comment]
Had a brief look. Seemed easy enough to fix, but some other issue popped up, and dint have time to pursue. Would be great if you could have a look. If needed, I can create a branch with my changes..

I also would like `rbindlist()` to work with *all* atomic columns... (there's already some work for this in `transpose()`, but it needs name matching. Some other time maybe.

**Comment by tcash21** [comment]
This would be really helpful, in the meantime, any workarounds people have used such as `flatten`?

**Comment by jangorecki** [comment]
@arunsrinivasan @dselivanov If any you has some commits towards this change, it may good if you link your branches here, so eventually others could pick it up. Unless you are working on it, then feel free to assign issue to yourself.

**Comment by 0xorial** [comment]
Can anyone post a workaround at least?

**Comment by MichaelChirico** [comment]
Here's a pretty junky workaround:

```
library(data.table)
l = list(
    data.table(a=c(1, 2), z=list(list(), list())),
    data.table(a=2, z=list("m"))
)

lengths = sapply(l, nrow)
DT = data.table(ID = seq_len(sum(lengths)))
grps = cumsum(c(0, lengths))

for (i in 1:length(l)) {
  idx = grps[i + 0:1] + 1:0
  li = l[[i]]
  DT[idx[1]:idx[2], (names(li)) := li]
}
```

**Comment by mattdowle** [comment]
PR #3455 fixes the original error at the top of this issue via #1871 which applies to `list` too (just NULL fill instead of NA).
The other examples look correct though. I added them all as tests in f9f21a2e4acf2f26f05087079ee34204d82c2c20.
