### ISSUE TITLE
Problem with skip in fread

### ISSUE THREAD

**Issue by MattWoods** [Rdatatable/data.table#1306]
Hi,
skip in fread doesn't function as described in the documentation.  The documentation says "skip>=0 means ignore autostart and take line skip +1 as the first data row." 
setting skip =0 makes line 1 the first row.
setting skip =1 also makes line 1 the first row, giving the same answer as skip =0.
setting skip =n with n>1 makes line n the first row, not line n+1.

**Comment by arunsrinivasan** [comment]
Please read the [Support](https://github.com/Rdatatable/data.table/wiki/Support) page and edit your post, and re-open if your examples tested on current devel reproduce the issue on your minimal example.

**Comment by MattWoods** [comment]
#### using current devel:

fread('"C1","C2"\n"1","2"\n"3","4"\n"5","6"',skip =1)

#     1 2
# 1: 3 4
# 2: 5 6

#### but when I unquote the numeric entries, the result is now 3x2:

fread('"C1","C2"\n1,2\n3,4\n5,6',skip =1)

#    V1 V2
# 1:  1  2
# 2:  3  4
# 3:  5  6

#### and in this case skip =1 and skip = 0 produce the same data rows, but change the column names:

fread('"C1","C2"\n1,2\n3,4\n5,6',skip =0)

#   C1 C2
# 1:  1  2
# 2:  3  4
# 3:  5  6

#### skip =2 takes line 2 as the first data row, not line 3
fread('"C1","C2"\n1,2\n3,4\n5,6',skip =2)

#    V1 V2
# 1:  3  4
# 2:  5  6
