### ISSUE TITLE
Autocomplete breaks when j is used

### ISSUE THREAD

**Issue by salmasian** [Rdatatable/data.table#1309]
This issue is with regard to the autocomplete feature in RStudio when using data tables. If you think I should report it to RStudio instead, please advise but I assume data.table developers should become aware of it too.

#### Working example

```R
library(hflights)
library(data.table)
DT <- as.data.table(hflights)
DT[UniqueCarrier == "AA"]
DT[
```

If I press CTRL+SPACE after opening the bracket, it correctly suggest to me column names from DT. 

#### Broken example

```R
library(hflights)
library(data.table)
DT <- as.data.table(hflights)
DT[UniqueCarrier == "AA", mean(AirTime, na.rm = T)]
DT[
```

Here pressing CTRL+SPACE will cause abnormal behavior: autocompletes adds `DT` again, resulting in `DT[DT`

#### Version info
R 3.2.2 stable, data.table 1.9.4 stable, RStudio 0.99.482 stable on Mac

**Comment by arunsrinivasan** [comment]
Thanks, but I don't see how it is a data table issue.

**Comment by jangorecki** [comment]
May be worth to ping @kevinushey as he was previously working on it.

**Comment by kevinushey** [comment]
Thanks, I'll file a bug in RStudio to handle this (RStudio is not inferring the completion context correctly)

**Comment by salmasian** [comment]
Thank you for the quick response! And for being proactive about submitting the bug to RStudio. I am sure your bug report will be more accurate and to the point that what I would write.
