### ISSUE TITLE
invisible with hist does not suppress output

### ISSUE THREAD

**Issue by trinker** [Rdatatable/data.table#1313]
I am using version 1.9.5 of data table and read in the FAQ:

> 2.18 I’m using j for its side effect only, but I’m still getting data returned. How do I stop that?
> In this case j can be wrapped with `invisible()`; e.g., `DT[,invisible(hist(colB)),by=colA]`

But using the code below the output is still printed and I get the warning that I on't quiet understand seen at the end of the post.
```r
library(data.table)
DT <- data.table(colA=rep(1:5,each=3), colB=floor(runif(15)*10))
DT[,invisible(hist(colB)),by=colA]
```

```
Warning message:
In `[.data.table`(DT, , invisible(hist(colB)), by = colA) :
  Column 2 of result for group 1 is length 5 but the longest column in this result is 6. Recycled leaving remainder of 1 items. This warning is once only for the first group with this issue.
```

**Comment by franknarf1** [comment]
`invisible` suppresses printing, but you're still seeing the *return value*. If you don't want this, use `DT[, {hist(colB); NULL},by=colA]`... though because you're doing this by group, you will only see the final histogram, so I don't see the point.

**Comment by trinker** [comment]
@franknarf1 Thanks  More of a curiosity not practical.  I saw the example in the FAQ and was curious.

**Comment by franknarf1** [comment]
Oh, maybe there's more to it, then...? I just looked at your code and skipped over the part about it being in the FAQ.
