### ISSUE TITLE
proper handling negative numeric values in `i` ?

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1317]
Related SO comment: http://stackoverflow.com/questions/32467007/subset-data-table-when-condition-is-exactly-met#comment52814568_32467007
`i` arg not handled properly, see below code.
Of course the `i = a<-1.3` is incorrect usage because it is assignment operator, it should be `i = a<(-1.3)`, the results are returned for incorrect usage anyway.
Looks like `i` argument numeric with decimal places is truncated to integer row id - same as data.frame.
It seems not to be a auto.index issues as it behave the same when it is turned off. More surprisingly it is behave the same for data.frame - so maybe issue can be closed because *work as designed in R*.
```r
library(data.table)
dt = data.table(a=c(-1.5,-1.2))
options("datatable.auto.index"=TRUE)
dt[a<-1.3]
#       a
# 1: -1.5
dt[-1.3]
#       a
# 1: -1.2
options("datatable.auto.index"=FALSE)
dt[a<-1.3]
#       a
# 1: -1.5
dt[-1.3]
#       a
# 1: -1.2

df = as.data.frame(dt)
df[df$a<-1.3,"a",drop=FALSE]
#      a
# 1 -1.5
df = as.data.frame(dt) # recreate due to assignment in above line
df[-1.3,"a",drop=FALSE]
#      a
# 2 -1.2
```
Please share what expected output you would see here as correct, not in terms vs. data.frame, but in general.

**Comment by eantonya** [comment]
I'm not following - is there a question here? Numeric arguments get converted to integer for indexing, by design, in both `data.frame` and `data.table`. `dt[a<-1.3]` is equivalent to `dt[1]` and `dt[-1.3]` to `dt[-1]`, which is why you get those results.

**Comment by franknarf1** [comment]
Yeah, I agree that this is expected behavior. I don't know what alternative we could use.

**Comment by arunsrinivasan** [comment]
IIUC this isn't specific data.table issue.

```r
a=5
a<-10 # a < 10 ?
a # [1] 10
```

**Comment by jangorecki** [comment]
OK, you all are right. It just may be sometimes confusing as in linked SO, anyway consistency with data.frame is a value here.
