### ISSUE TITLE
Feature Request: Extension of `use.names` functionalities for `rbind*` to define equivalence classes

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1333]
It would be great to be able to extend the syntax in `use.names` to allow something similar to that used for `on`.

```
DT1 <- data.table(id1=1:5, var=5:1)
DT2 <- data.table(id=6:10, var=10:6)

#if I know that 'id' is the same as `id1`, it'd be nice to do:
rbind(DT1, DT2, id = c(id1="id"))
```

This came about in the first place for me because `DT1` and `DT2` were both read in from Excel; it would be nice to avoid `setnames` which tends to clutter code.

This is a simple example and I'm not sure how I would generalize it, e.g., when there are many `data.table`s being `rbind`ed, how could we specify an "equivalence class" so that, e.g., all columns in the set `c("id", "id1", "id4")` are considered identical?

**Comment by jangorecki** [comment]
It may be better(?) to put that into `rbindlist` as `rbind` could be more R-base-ish. Wrapping `...` into `list()` to use `rbindlist` should not be a big deal.

**Comment by arunsrinivasan** [comment]
I don't think this can be generalised well enough (as you already mention).

**Comment by MichaelChirico** [comment]
@arunsrinivasan what's wrong with @jangorecki 's suggestion: use a named list to define equivalence classes? I see two possibilities (not sure how either would look on the coding side):

Use unnamed list, each list item defines an equivalence class; the first element of each item becomes the name of the column in the output:

    rbind(DT1, DT2, DT3, equiv = list(c("id", "id1", "id4"), c("var1", "var.1")))

Named list, name of each element becomes the name in the output:

    rbind(DT1, DT2, DT3, equiv = list(id = c("id1", "id4"), var1 = "var.1")
    # - or -
    rbind(DT1, DT2, DT3, equiv = list(id = c("id", "id1", "id4"), var1 = c("var1", "var.1")))

**Comment by arunsrinivasan** [comment]
We've `rbindlist()` ignoring names by default already. These are rare scenarios and it makes code hard to maintain by implementing every fringe case.
