### ISSUE TITLE
Suppression of printing on := assignments fails when within a logical statement?

### ISSUE THREAD

**Issue by TARehman** [Rdatatable/data.table#1335]
I am using `data.table` 1.9.4 and I am having some confusion about the invisible return of DT after using `:=` to make assignments. I believe the behavior I am seeing is unintended, so I am raising this as a bug - but if I am wrong I can take it over to SO instead.

I am in a situation where I need to check what columns were created in my data table against a list of expected columns. If an expected column is not found, then I need to create it and fill it with zero. I do this with a simple conditional logic check that looks to see if there are any missing names, and then fills them in if they are absent.

When the creation of the columns is put into the conditional logic statement, DT does not return invisibly; however, if the conditional logic is removed, DT is invisible. Based on my reading of the FAQ (specifically 2.21 and 2.22), that seems like it should not occur.

Here is an example that reproduces the issue.

    > library(data.table)
    data.table 1.9.4  For help type: ?data.table
    *** NB: by=.EACHI is now explicit. See README to restore previous behaviour.
    > DT <- data.table(A = c(1,2,3,4,5),
    +                  B = c(3,2,1,4,5),
    +                  D = c(4,5,6,7,8))
    > 
    > names.expected <- c("A","B","C","D","E")
    > names.found <- names(DT)
    > names.missing <- names.expected[!(names.expected %in% names.found)]
    > if(length(names.missing) > 0) {DT[,names.missing := 0,with = FALSE]}
       A B D C E
    1: 1 3 4 0 0
    2: 2 2 5 0 0
    3: 3 1 6 0 0
    4: 4 4 7 0 0
    5: 5 5 8 0 0
    > 
    > DT <- data.table(A = c(1,2,3,4,5),
    +                  B = c(3,2,1,4,5),
    +                  D = c(4,5,6,7,8))
    > 
    > names.expected <- c("A","B","C","D","E")
    > names.found <- names(DT)
    > names.missing <- names.expected[!(names.expected %in% names.found)]
    > DT[,names.missing := 0,with = FALSE]
    >

This problem reproduces both while running the code interactively (through an R session in RStudio Server) and on the command-line in Linux (the DT contents are printed to STDOUT).

**Comment by arunsrinivasan** [comment]
Please read [this](https://github.com/Rdatatable/data.table/wiki/Support). If you reproduce it on current devel, then feel free to reopen.

**Comment by TARehman** [comment]
Confirming this is resolved in 1.9.5. Apologies for raising the issue prematurely.
