### ISSUE TITLE
`as.Date`/`as.IDate` converts to the day before within by statement

### ISSUE THREAD

**Issue by DavidArenburg** [Rdatatable/data.table#1337]
So consider the following data set from [this SO](http://stackoverflow.com/questions/32523808/using-adply-in-data-table)

```r
dt <- data.table(start=c("2012-07-13 23:45:00", "2012-07-14 15:30:00", 
                       "2012-07-14 23:57:00"), 
                 end=c("2012-07-14 00:02:00", "2012-07-14 15:35:00", 
                     "2012-07-15 00:05:00"), id=c(1,2,1),cat=c("a","b","a"))
dt[, `:=`(start = as.POSIXct(start), end = as.POSIXct(end), indx = .I)]
```

And I would like to calculate duration from `start` to `end`  by row. I'm doing something like 

```r
dt[, seq(start, end - 1L, by = "mins"), by = .(indx, id, cat)
   ][, .N, by = .(Date = as.IDate(V1), id, cat)]
#          Date id cat  N
# 1: 2012-07-13  1   a 17
# 2: 2012-07-14  2   b  5
# 3: 2012-07-14  1   a  8
```

But the output is incorrect, it should be 

```r
dt[, seq(start, end - 1L, by = "mins"), by = .(indx, id, cat)
   ][, .N, by = .(Date = substr(V1, 1L, 10L), id, cat)]
#          Date id cat  N
# 1: 2012-07-13  1   a 15
# 2: 2012-07-14  1   a  5
# 3: 2012-07-14  2   b  5
# 4: 2012-07-15  1   a  5
```

It seems like all the dates before 1 am are being converted to the day before within the `by` statement, but this isn't a problem in `as.Date` or `as.IDate` themselves

```r
as.IDate("2012-07-15 00:05:00")
## [1] "2012-07-15"
as.Date("2012-07-14 00:02:00")
## [1] "2012-07-14"
```

I'm wondering if this a bug or am I missing something obvious here, as I'm surprised no one noticed this before.

**Comment by franknarf1** [comment]
Using David's example:

    x = dt[, seq(start, end - 1L, by = "mins"), by = .(indx, id, cat)]$V1
    
						  x          D         ID
	 1: 2012-07-13 23:45:00 2012-07-14 2012-07-14
	 2: 2012-07-13 23:46:00 2012-07-14 2012-07-14
	 3: 2012-07-13 23:47:00 2012-07-14 2012-07-14
	 4: 2012-07-13 23:48:00 2012-07-14 2012-07-14
	 5: 2012-07-13 23:49:00 2012-07-14 2012-07-14
	 6: 2012-07-13 23:50:00 2012-07-14 2012-07-14
	 7: 2012-07-13 23:51:00 2012-07-14 2012-07-14
	 8: 2012-07-13 23:52:00 2012-07-14 2012-07-14
	 9: 2012-07-13 23:53:00 2012-07-14 2012-07-14
	10: 2012-07-13 23:54:00 2012-07-14 2012-07-14
	11: 2012-07-13 23:55:00 2012-07-14 2012-07-14
	12: 2012-07-13 23:56:00 2012-07-14 2012-07-14
	13: 2012-07-13 23:57:00 2012-07-14 2012-07-14
	14: 2012-07-13 23:58:00 2012-07-14 2012-07-14
	15: 2012-07-13 23:59:00 2012-07-14 2012-07-14
	16: 2012-07-14 00:00:00 2012-07-14 2012-07-14
	17: 2012-07-14 00:01:00 2012-07-14 2012-07-14
	18: 2012-07-14 15:30:00 2012-07-14 2012-07-14
	19: 2012-07-14 15:31:00 2012-07-14 2012-07-14
	20: 2012-07-14 15:32:00 2012-07-14 2012-07-14
	21: 2012-07-14 15:33:00 2012-07-14 2012-07-14
	22: 2012-07-14 15:34:00 2012-07-14 2012-07-14
	23: 2012-07-14 23:57:00 2012-07-15 2012-07-15
	24: 2012-07-14 23:58:00 2012-07-15 2012-07-15
	25: 2012-07-14 23:59:00 2012-07-15 2012-07-15
	26: 2012-07-15 00:00:00 2012-07-15 2012-07-15
	27: 2012-07-15 00:01:00 2012-07-15 2012-07-15
	28: 2012-07-15 00:02:00 2012-07-15 2012-07-15
	29: 2012-07-15 00:03:00 2012-07-15 2012-07-15
	30: 2012-07-15 00:04:00 2012-07-15 2012-07-15
						  x          D         ID

I see that Date and IDate are both converting from POSIXct in the same (strange) way. Maybe this has something to do with a time zone secreted deep within the POSIXct?

**Comment by DavidArenburg** [comment]
As mentioned by @franknarf1 it not `data.table` related
