### ISSUE TITLE
`check.names` argument for `setDT`

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1338]
Given how simple implementing `check.names` seems to be, seems like `setDT` could go for the same argument.

Would allow my answer to [this](http://stackoverflow.com/questions/27866185/dealing-with-ambiguous-column-names-in-data-table/31493399#31493399) question to be done by reference, and in general would be key for when `fread` is not an option for bringing in outside data.

**Comment by arunsrinivasan** [comment]
@MichaelChirico agreed. PR? Matt's working on pushing to CRAN at the moment. If you can get this done soon, we can get it on v1.9.6 :-).

**Comment by MichaelChirico** [comment]
@arunsrinivasan ooh exciting. I'm hoping to get it done at some point today.
