### ISSUE TITLE
RStudio's auto formatting messes up the update operator

### ISSUE THREAD

**Issue by salmasian** [Rdatatable/data.table#1342]
I realize this might be perceived as an RStudio bug but since it specifically affects the := operator used by data.table, and I am not sure if RStudio's formatting is made aware of this operator by data.table or not, I am reporting it here. If you think it needs to be reported to RStudio instead, please close this issue and report there (or have me do it).

Take this code example:

    test <- function(DT, b) {
      DT[, Fkey := sth]
    }

If you select it all and use the Reformat Code feature of Rstudio, it chnages `Fkey := sth` to `Fkey: = sth` which results in syntax error.

**Comment by shrektan** [comment]
Yes this is something that I’ve been aware of for a long time.
Personally I think it’s an issue related to Rstudio.

**Comment by jangorecki** [comment]
@salmasian yes please report to RStudio. It is always good to check potential data.table just in R console.

**Comment by arunsrinivasan** [comment]
Agree with @jangorecki
