### ISSUE TITLE
last() no longer dispatches if data.table::last masks xts::last

### ISSUE THREAD

**Issue by joshuaulrich** [Rdatatable/data.table#1347]
```r
library(xts)
library(data.table)
last(.xts(1:3,1:3))
# [1] 3
# but should be (was in 1.9.4):
#                     [,1]
# 1969-12-31 18:00:03    3
```

It looks like the change in [e011351](https://github.com/joshuaulrich/data.table/commit/e0113510b92fe7b31bd24c176e8d51a8234e495f) is the cause, and it seems like it's just an error in the if statement (`||` should be `&&`).

But changing the `||` to `&&` will cause `xts::last.default` to be used any time xts is on the search path, and `xts::last.default` is slower than `data.table::last` for vectors, lists, data.frame, or data.table.  I think a better solution would have been to replace the call to `stop` with a call to `tail(x, ...)`.  Thoughts?

**Comment by arunsrinivasan** [comment]
Joshua, yes that seems like a better fix to me too.

**Comment by joshuaulrich** [comment]
Would you like me to submit a PR?

**Comment by arunsrinivasan** [comment]
If you can, sure :-). Else I / @jangorecki (?) can take care of it.

**Comment by jangorecki** [comment]
Maybe something like this at the beginning of `data.table::last`
```r
if (inherits(x, "xts") && "package:xts" %in% search())
    xts::last(x, ...)
```

**Comment by arunsrinivasan** [comment]
@jangorecki Joshua has already provided the fix (to use `tail()`).

**Comment by arunsrinivasan** [comment]
Fixed now @joshuaulrich, please verify.

**Comment by joshuaulrich** [comment]
@arunsrinivasan, that's essentially what I had in my commits, so it looks good to me!  You were able to get to the unit test before I was... I got "distracted" by my job. :)  Thanks!

**Comment by arunsrinivasan** [comment]
sorry, dint see your commits... 

:+1:
