### ISSUE TITLE
compilation error on AIX

### ISSUE THREAD

**Issue by vinhdizzo** [Rdatatable/data.table#1351]
Hi,

Trying to install data.table on R 3.2.2 on AIX, and am getting the following error.  Any suggestions would be greatly appreciated.

```{r}
> install.packages("data.table", repo = "http://cran.stat.ucla.edu")
trying URL 'http://cran.stat.ucla.edu/src/contrib/data.table_1.9.4.tar.gz'
Content type 'application/x-tar' length 949746 bytes (927 KB)
==================================================
downloaded 927 KB

* installing *source* package 'data.table' ...
** package 'data.table' successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/sas/outmva/opt/lib/R/include -DNDEBUG  -I/usr/local/include  -mno-fp-in-toc    -g -O2  -c assign.c -o assign.o
gcc -std=gnu99 -I/sas/outmva/opt/lib/R/include -DNDEBUG  -I/usr/local/include  -mno-fp-in-toc    -g -O2  -c bmerge.c -o bmerge.o
bmerge.c:25:17: error: 'nearest' redeclared as different kind of symbol
 static Rboolean nearest=FALSE, enc_warn=TRUE;
                 ^
In file included from /sas/outmva/opt/lib/R/include/R.h:31:0,
                 from data.table.h:1,
                 from bmerge.c:1:
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/4.8.3/include-fixed/math.h:1383:21: note: previous declaration of 'nearest' was here
 extern     double   nearest(double);
                     ^
bmerge.c:109:21: error: 'class' redeclared as different kind of symbol
 static SEXP ic, xc, class;
                     ^
In file included from /sas/outmva/opt/lib/R/include/R.h:31:0,
                 from data.table.h:1,
                 from bmerge.c:1:
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/4.8.3/include-fixed/math.h:1398:21: note: previous declaration of 'class' was here
 extern     int      class();
                     ^
/sas/outmva/opt/lib/R/etc/Makeconf:134: recipe for target 'bmerge.o' failed
make: *** [bmerge.o] Error 1
ERROR: compilation failed for package 'data.table'
* removing '/sas/outmva/opt/lib/R/library/data.table'

The downloaded source packages are in
        '/tmp/Rtmpf3o7ma/downloaded_packages'
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("data.table", repo = "http://cran.stat.ucla.edu") :
  installation of package 'data.table' had non-zero exit status
```

**Comment by mattdowle** [comment]
I see you're PowerPC.  Please try again with v1.9.6 which has just been released to CRAN this weekend.  It passed PowerPC under QEMU emulation.  Having said that, I haven't seen these errors about class() or nearest() before so I suspect v1.9.6 will not fix it.  A google search for "IBM AIX previous declaration of 'nearest'" throws up other packages having similar issues.  If you could investigate those threads and let us know what we need to do that'd be great if possible.  (We have no IBM AIX machine to test.)

**Comment by vinhdizzo** [comment]
Thanks for the prompt response Matt.

Tried 1.9.6 and the errors persist.  Googled the "IBM AIX previous declaration", and both [this](https://github.com/nagios-plugins/nagios-plugins/issues/40) and [this](https://sourceware.org/bugzilla/show_bug.cgi?id=13558) points to the ordering of the include statement.  Don't know what the proper ordering should be...maybe it's more apparent to you.  Thanks.

**Comment by mattdowle** [comment]
Thanks - useful.  Had a quick look but can't see what to change.  The symbol `nearest` occurs in bmerge.c only and is declared as a `static Rboolean`,  so I don't see how this could conflict with math.h. 
You're using "-std=gnu99" so why would math.h on your platform contain `extern nearest` when it doesn't on other platforms. Doesn't GNU99 say what is and isn't in the .h files?
If you could raise this on an AIX support list somewhere for us please and find someone who might know, that would be great.   Thanks.

**Comment by vinhdizzo** [comment]
Sorry, this is going beyond my comfort zone (not really familiar with this).

Both threads mention "before the system header files" in their fixes.  Is there a way to include 'R.h' before 'math.h'?

**Comment by mattdowle** [comment]
The string 'math.h' doesn't occur anywhere in data.table source so I don't see how.
Don't you have any AIX support channels open to you?

**Comment by mattdowle** [comment]
I suppose we could change the C symbol names from 'nearest' and 'class' to something else.
But such an effort/guess grates. You paid for IBM hardware and support so they should be helping, or at least responding.

**Comment by vinhdizzo** [comment]
Hey Matt,

The decision to have this AIX box was made years ago before I arrived here in my current employment, and there really isn't much support from our IT because they themselves aren't that familiar with UNIX/Linux.  In terms of support from IBM, I'm not even going to attempt it because it would involve too much red tape, requiring approvals and worst yet, may require $.  Not much of an appetite around here just to satisfy my requirements for getting things to work in R.

I don't even think IBM would be much help here because I'm not even using the compilers provided by them (again, too much hassle).  I was able to get get the GNU compilers to work on AIX thanks Michael Perlz who maintains [this](http://www.perzl.org/aix/) wonderful site.  I preferred to use the GNU compilers because at least the same compilers are used in other distros, hence better support from others.

I'll reach out to that maintainer to see if he's seen this error before in his experience dealing with AIX.  If he doesn't have a clue, then I really think my luck stops there.  I would then very much appreciate you changing those symbol names.  Thanks again.

**Comment by mattdowle** [comment]
Thanks for the further info and background.  Understood.  I've changed the symbol names.  To try it, please :  
> git clone https://github.com/Rdatatable/data.table.git
or
> wget https://github.com/Rdatatable/data.table/archive/master.zip
then
> R CMD build --no-build-vignettes data.table
> R CMD check data.table_1.9.7.tar.gz
> R CMD INSTALL data.table_1.9.7.tar.gz
> R
> test.data.table()

**Comment by vinhdizzo** [comment]
Thank you so much Matt for the fix.  It installs on AIX now.

If I do hear back from Michael Perlz (maintainter of many compiled packages for AIX), I'll post here so you know as well.  Thanks again.

**Comment by vinhdizzo** [comment]
I was just trying to install a different package (geosphere) and ran into some issues with TRUE or FALSE.  Did a search on it and found [this](http://r.789695.n4.nabble.com/unable-to-compile-mgcv-td925523.html) thread, and undef'ing TRUE and FALSE made the packages compiled. I just tried "#undef class" and "#undef nearest" on top of bmerge.c in the previous data.table version, but no go.  However, I don't think "#undef" is valid for these.  Is there a proper way to do this?  If so, I could try it out.  Thanks!

**Comment by mattdowle** [comment]
Thanks for the confirm.  Glad resolved.
I had a look at that thread but sorry I don't know.  If those are gcc headers then perhaps speak to those folk and maybe create a patch or a local copy of the headers without those defines.

**Comment by vinhdizzo** [comment]
Regarding that geosphere, I just manually modified the source (undef'ing) and compiled successfully.

I was just curious as to whether I could manually "#undef nearest" and "#undef class" (or something similar) at the beginning of bmerge.c to see if it works.  If it did, then in the future when I run into this AIX issue I would manually modify the source myself without having to bother the package maintainer as this clearly is an AIX problem.

Was just getting your thoughts if there was an analogous way to 'undef' the 'class' and 'nearest' in your package, that's all.

Thanks again.

**Comment by mattdowle** [comment]
That doesn't seem right to me.  If those are gcc headers then perhaps speak to those folk and maybe create a patch or a local copy of the headers without those defines.   i.e. find the .h in your system and simply remove the offending #define's,   taking a backup first of course.  Then you don't need to do anything for each package.

**Comment by vinhdizzo** [comment]
Hey Matt,

I mentioned this issue on the gcc-help mailing list and was given [this](https://gcc.gnu.org/ml/gcc-help/2015-09/msg00128.html) response.  Does it make sense?  Just an FYI.  Thanks again!

**Comment by aixtools** [comment]
re: the comments from gcc-help - I also package a gcc compiler for AIX (and have a test version with fortran in it I am using to test R for AIX).

The issue with "class" is many many lines on AIX, however, the name "nearest" is easiest to display:
root@x072:[/data/prj/cran/modules]grep nearest /usr/include/*
/usr/include/decContext.h:    DEC_ROUND_HALF_EVEN,           /* 0.5 rounds to nearest even      */
/usr/include/float.h: *      RN = Round toward nearest (default)
/usr/include/math.h:extern     double   nearest();
/usr/include/math.h:extern     double   nearest(double);
/usr/include/math.h:/* This is the nearest number to the cube root of MAXDOUBLE that   */
root@x072:[/data/prj/cran/modules]

"nearest()" seems to be claimed by IEEE math functions - so I am surprised that gcc would not be having namespace collision as well.

re: class - I would expect that to be a reserved in many languages, so I am not too surprised.

For brevity, I am not including the grep with class as "string to find".

I shall apply the patch, and I hope you soon update data.table_1.9.6.tar

Michael aka aixtools

**Comment by aixtools** [comment]
p.s. as I am very new to R - trying this for a friend, I do not understand who to use either the clone git instructions, or the master.zip file (with, although similar, is much smaller than the 1.9.6.tar file I am trying to install).

The instructions I had received were merely - get the file, ungzip it and then, in R
install.packages("./data.table_1.9.6.tar",repos=NULL,type="source")

My apologies for being so "simple-minded".

**Comment by jangorecki** [comment]
@aixtools You can install 1.9.6 from source directly from CRAN by
```r
install.packages("data.table", type="source")
```

**Comment by aixtools** [comment]
Thanks.
my friend I was helping prepped a tar file for, and it packaged without an issue.
On to Rcpp ...
