### ISSUE TITLE
warning message fread , bumped column

### ISSUE THREAD

**Issue by Monty9** [Rdatatable/data.table#1358]
Hi arun,
The `fread()` used to work fine until 2 days back. Suddenly, I started to see this warning.

```R
Warning messages:
1: In fread("JournalHomeGrid.txt", verbose = T) :
```
  Bumped column 7 to type character on data row 74, field contains 'Not Available'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.

**Comment by arunsrinivasan** [comment]
Read the warning. Check your file. And please, please read [this](https://github.com/Rdatatable/data.table/wiki/Support) *completely*. Then post back if you've an issue.

**Comment by Monty9** [comment]
Sorry, that was lame. Thank you for response. I fixed it.
