### ISSUE TITLE
accessing rows via a factor column throws error

### ISSUE THREAD

**Issue by mplatzer** [Rdatatable/data.table#1361]
this used to work in data.table v1.9.4 but now throws an error in v1.9.6:
```
dt <- data.table(i=1:10, f=as.factor(1:10))
dt[f==3]
```
the thrown error is: `Error in bmerge(i, x, leftcols, rightcols, io <- FALSE, xo, roll = 0,  : 
  x.'f' is a factor column being joined to i.'V1' which is type 'double'. Factor columns must join to factor or character columns.`

the error can be avoided by adding additional conditions, e.g. `dt[f==3 & TRUE]` or by comparing to characters (as indicated by the error itself): `dt[f=="3"]`. not sure, whether this is a bug or a feature, but I though it's worthwhile reporting.

**Comment by helix123** [comment]
Just found something. I had working code with the previous CRAN release, so something must have been changed.
````
seed(1)
DT <- data.table(V1=factor(c(1,2)),
                 V2=LETTERS[1:3],
                 V4=1:12)


# does not work
DT[V1 == 1, ]

# does work
DT[V1 == factor(1), ]

**Comment by caneff** [comment]
Running into this too. This seems to be very similar to isssue #957 but with factors instead of characters.

**Comment by caneff** [comment]
The problem seems to be that on line 471 of data.table.R, you check

``` mode(x[[isub2]]) != mode(RHS)```

However, both factors and integers have mode "numeric", so it skips this part and moves on to the standard auto-indexing, where bmerge chokes. I'm not sure what the right substitution is for line 471 but that is where the fix should go.

**Comment by caneff** [comment]
Ping? This is breaking our existing code so we are stuck with 1.9.4 until this gets fixed.

**Comment by helix123** [comment]
Here http://stackoverflow.com/questions/32934400/gather-multiple-times-at-once someone mentions in the comments that this problem can be circumvented by turning of auto indexing in v1.9.6.
