### ISSUE TITLE
Some minor suggestions for IDateTime documentation

### ISSUE THREAD

**Issue by Henrik-P** [Rdatatable/data.table#1364]
1.
Current:
`round(x, digits = c("weeks", "months", "quarters","years"), ...)`

Suggestion:
`round(x, digits = c("weeks", "months", "quarters", "years"), ...)`

2.
Current:
"number of seconds in the day"

Suggestion:
"number of seconds of the day"
(Compare e.g. `%j` Day _of_ year)

3.
Current:
"generic template, but to make converting easier, the second arguement"

Suggestion:
"generic template. But [or "However, "] to make conversion easier, the second argument 

4.
Current:
codeyday

Suggestion:
`yday`

5.
Current:
`key = "a,idate,itime")`

Suggestion:
`key = "a, idate, itime")`

6.
Current:
`IDateTime(chron("12/31/98","10:45:00")`

Suggestion:
`IDateTime(chron("12/31/98", "10:45:00")`

**Comment by arunsrinivasan** [comment]
Suggestion 5 won't work as this form requires no spaces in between. A PR would be great for all other suggestions.
