### ISSUE TITLE
Data.table not longer works with dplyr mutate function

### ISSUE THREAD

**Issue by dbuijs** [Rdatatable/data.table#1366]
The `dplyr` mutate function doesn't seem to work with data.table anymore and my best guess is the update of data.table to v1.9.6. 

See https://github.com/hadley/dplyr/issues/1431

**Comment by eantonya** [comment]
And this is a `data.table` issue because...?

**Comment by kaybenleroll** [comment]
I have noticed that sometime data.table objects don't print out to the screen the first time you try to use them after they are created. Could it be related to that?

Not sure if this phenomenon is an unintended side-effect or something of the new features.

**Comment by raubreywhite** [comment]
That's not new, it happened with me with 1.9.4

**Comment by eantonya** [comment]
I have noticed that too - hasn't bothered me enough to come up with a reproducible example, but if someone can come up with one that's not obscured by other packages, that'd be very useful.

**Comment by dbuijs** [comment]
You're right, it's a display issue. The object is still there, it just doesn't print the summary when you call it from the console. 

See the example in the referenced issue. 

Thanks
