### ISSUE TITLE
fread autostart problem in version 1.9.6

### ISSUE THREAD

**Issue by martinguerrero89** [Rdatatable/data.table#1371]
Hello, great package you have here! congratulations for all the hard work
lets go to the problem
I got a df with the first 37 lines with comments, when using fread from the previous (1.9.4) version of data.table i set the autostart argument to 40 and the function worked perfectly, now with the new version of data.table (1.9.6) with the same script i get the comment lines and i cannot work around this issue. If i skip these lines everything works fine but i do not always have 37 lines of comments

Here it goes a brief example...
https://github.com/martinguerrero89/example1/blob/master/example1.txt

> readLines("example1.txt", 40)
>  [1] "#ID ="  
>  [2] "#Name ="  
>  [3] "#AddressA_ID ="  
>  [4] "#AlleleA_ProbeSeq ="  
>  [5] "#AddressB_ID = "  
>  [6] "#AlleleB_ProbeSeq = "  
>  [7] "#Infinium_Design_Type = "  
>  [8] "#Next_Base ="  
>  [9] "#Color_Channel ="  
> [10] "#Forward_Sequence ="  
> [11] "#Genome_Build ="  
> [12] "#CHR = \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"  
> [13] "#MAPINFO = "  
> [14] "#SourceSeq = \t\t\t\t\t\t\t\t\t\t\t\t"  
> [15] "#Chromosome_36 ="  
> [16] "#Coordinate_36 ="  
> [17] "#Strand = "  
> [18] "#Probe_SNPs = "  
> [19] "#Probe_SNPs_10 = "  
> [20] "#Random_Loci ="  
> [21] "#Methyl27_Loci = "  
> [22] "#UCSC_RefGene_Name = \t\t\t\t\t\t\t\t\t\t\t\t\t"  
> [23] "#UCSC_RefGene_Accession ="  
> [24] "#UCSC_RefGene_Group = "  
> [25] "#UCSC_CpG_Islands_Name ="  
> [26] "#Relation_to_UCSC_CpG_Island ="  
> [27] "#Phantom = "  
> [28] "#DMR ="  
> [29] "#Enhancer ="  
> [30] "#HMM_Island ="  
> [31] "#Regulatory_Feature_Name ="  
> [32] "#Regulatory_Feature_Group ="  
> [33] "#DHS = "  
> [34] "#RANGE_START ="  
> [35] "#RANGE_END = "  
> [36] "#RANGE_GB ="  
> [37] "#SPOT_ID ="  
> [38] "ID\tName\tAddressA_ID\tAlleleA_ProbeSeq\tAddressB_ID\tAlleleB_ProbeSeq\tInfinium_Design_Type\tNext_Base\tColor_Channel\tForward_Sequence\tGenome_Build\tCHR\tMAPINFO\tSourceSeq\tChromosome_36\tCoordinate_36\tStrand\tProbe_SNPs\tProbe_SNPs_10\tRandom_Loci\tMethyl27_Loci\tUCSC_RefGene_Name\tUCSC_RefGene_Accession\tUCSC_RefGene_Group\tUCSC_CpG_Islands_Name\tRelation_to_UCSC_CpG_Island\tPhantom\tDMR\tEnhancer\tHMM_Island\tRegulatory_Feature_Name\tRegulatory_Feature_Group\tDHS\tRANGE_START\tRANGE_END\tRANGE_GB\tSPOT_ID"  
> [39] "cg00035864\tcg00035864\t31729416\tAAAACACTAACAATCTTATCCACATAAACCCTTAAATTTATCTCAAATTC\t\t\tII\t\t\tAATCCAAAGATGATGGAGGAGTGCCCGCTCATGATGTGAAGTACCTGCTCAGCTGGAAAC[CG]AATTTGAGATAAATTCAAGGGTCTATGTGGACAAGACTGCTAGTGTCTCTCTCTGGATTG\t37\tY\t8553009\tAGACACTAGCAGTCTTGTCCACATAGACCCTTGAATTTATCTCAAATTCG\tY\t8613009\tF\t\t\t\t\tTTTY18\tNR_001550\tTSS1500\t\t\t\t\t\t\t\t\t\t8553009\t8553132\tNC_000024.9\t"  
> [40] "cg00050873\tcg00050873\t32735311\tACAAAAAAACAACACACAACTATAATAATTTTTAAAATAAATAAACCCCA\t31717405\tACGAAAAAACAACGCACAACTATAATAATTTTTAAAATAAATAAACCCCG\tI\tA\tRed\tTATCTCTGTCTGGCGAGGAGGCAACGCACAACTGTGGTGGTTTTTGGAGTGGGTGGACCC[CG]GCCAAGACGGCCTGGGCTGACCAGAGACGGGAGGCAGAAAAAGTGGGCAGGTGGTTGCAG\t37\tY\t9363356\tCGGGGTCCACCCACTCCAAAAACCACCACAGTTGTGCGTTGCCTCCTCGC\tY\t9973356\tR\t\t\t\t\tTSPY4;FAM197Y2\tNM_001164471;NR_001553\tBody;TSS1500\tchrY:9363680-9363943\tN_Shore\t\t\t\tY:9973136-9976273\t\t\t\t9363356\t9363479\tNC_000024.9\t"

WITH VERSION 1.9.4 (the one that works):

> example1= fread("example1.txt", nrows=1, autostart=40,verbose=TRUE)
> Input contains no \n. Taking this to be a filename to open
> File opened, filesize is 0.000010 GB.
> Memory mapping ... ok
> Detected eol as \r\n (CRLF) in that order, the Windows standard.
> Using line 40 to detect sep (the last non blank line in the first 'autostart') ... sep='\t'
> Found 37 columns
> First row with 37 fields occurs on line 38 (either column names or first row of data)
> All the fields on line 38 are character fields. Treating as the column names.
> Count of eol after first data row: 23
> Subtracted 1 for last eol and any trailing empty lines, leaving 22 data rows
> nrow limited to nrows passed in (1)
> Type codes (   first 5 rows): 4414004004141441000004440000000001140
> Type codes: 4414004004141441000004440000000001140 (after applying colClasses and integer64)
> Type codes: 4414004004141441000004440000000001140 (after applying drop or select (if supplied)
> Allocating 37 column slots (37 - 0 dropped)
>    0.000s (  0%) Memory map (rerun may be quicker)
>    0.000s (  0%) sep and header detection
>    0.000s (  0%) Count rows (wc -l)
>    0.000s (  0%) Column type detection (first, middle and last 5 rows)
>    0.000s (  0%) Allocation of 1x37 result (xMB) in RAM
>    0.000s (  0%) Reading data
>    0.000s (  0%) Allocation for type bumps (if any), including gc time if triggered
>    0.000s (  0%) Coercing data already read in type bumps (if any)
>    0.000s (  0%) Changing na.strings to NA
>    0.001s        Total
> 
> example1
>            ID       Name AddressA_ID                                   AlleleA_ProbeSeq AddressB_ID AlleleB_ProbeSeq
> 1: cg00035864 cg00035864    31729416 AAAACACTAACAATCTTATCCACATAAACCCTTAAATTTATCTCAAATTC          NA               NA
>    Infinium_Design_Type Next_Base Color_Channel
> 1:                   II        NA            NA
>                                                                                                                Forward_Sequence
> 1: AATCCAAAGATGATGGAGGAGTGCCCGCTCATGATGTGAAGTACCTGCTCAGCTGGAAAC[CG]AATTTGAGATAAATTCAAGGGTCTATGTGGACAAGACTGCTAGTGTCTCTCTCTGGATTG
>    Genome_Build CHR MAPINFO                                          SourceSeq Chromosome_36 Coordinate_36 Strand
> 1:           37   Y 8553009 AGACACTAGCAGTCTTGTCCACATAGACCCTTGAATTTATCTCAAATTCG             Y       8613009  FALSE
>    Probe_SNPs Probe_SNPs_10 Random_Loci Methyl27_Loci UCSC_RefGene_Name UCSC_RefGene_Accession UCSC_RefGene_Group
> 1:         NA            NA          NA            NA            TTTY18              NR_001550            TSS1500
>    UCSC_CpG_Islands_Name Relation_to_UCSC_CpG_Island Phantom DMR Enhancer HMM_Island Regulatory_Feature_Name
> 1:                    NA                          NA      NA  NA       NA         NA                      NA
>    Regulatory_Feature_Group DHS RANGE_START RANGE_END    RANGE_GB SPOT_ID
> 1:                       NA  NA     8553009   8553132 NC_000024.9      NA

EXACTLY THE SAME BUT IN VERSION 1.9.6:

> example1= fread("example1.txt", nrows=1, autostart=40,verbose=TRUE)
> Input contains no \n. Taking this to be a filename to open
> File opened, filesize is 0.000010 GB.
> Memory mapping ... ok
> Detected eol as \r\n (CRLF) in that order, the Windows standard.
> Positioned on line 40 after skip or autostart
> This line is the autostart and not blank so searching up for the last non-blank ... line 1
> Detecting sep ... ' '
> Detected 2 columns. Longest stretch was from line 1 to line 11
> Starting data input on line 1 (either column names or first row of data). First 10 characters: #ID =
> All the fields on line 1 are character fields. Treating as the column names.
> nrow set to nrows passed in (1)
> Type codes (   first 5 rows): 44
> Type codes: 44 (after applying colClasses and integer64)
> Type codes: 44 (after applying drop or select (if supplied)
> Allocating 2 column slots (2 - 0 dropped)
> Read 1 rows. Exactly what was estimated and allocated up front
>    0.000s (  0%) Memory map (rerun may be quicker)
>    0.000s (  0%) sep and header detection
>    0.000s (  0%) Count rows (wc -l)
>    0.000s (  0%) Column type detection (first, middle and last 5 rows)
>    0.000s (  0%) Allocation of 1x2 result (xMB) in RAM
>    0.000s (  0%) Reading data
>    0.000s (  0%) Allocation for type bumps (if any), including gc time if triggered
>    0.000s (  0%) Coercing data already read in type bumps (if any)
>    0.000s (  0%) Changing na.strings to NA
>    0.001s        Total
> example1
>      #ID =
> 1: #Name =
> 
> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8 x64 (build 9200)
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
> [5] LC_TIME=English_United States.1252  
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base  
> Other attached packages:
> [1] data.table_1.9.4
> loaded via a namespace (and not attached):
> [1] magrittr_1.5   plyr_1.8.3     tools_3.2.2    reshape2_1.4.1 Rcpp_0.12.1    stringi_0.5-5  stringr_1.0.0 
> [8] chron_2.3-47

**Comment by rBatt** [comment]
I might be experiencing something related: I wasn't having a problem reading in a .csv with comments in 1.9.4, but I get the following error in 1.9.6:  
```
Error in fread(...) : 
  Expecting 16 cols, but line 129 contains text after processing all cols. It is very likely that this is due to one or more fields having embedded sep=',' and/or (unescaped) '\n' characters within unbalanced unescaped quotes. fread cannot handle such ambiguous cases and those lines may not have been read in as expected. Please read the section on quotes in ?fread.
```

The entries in these .csv's are often a mess. There are single and double quotes all over (and much other punctuation). Is this a separate problem that I need to find a solution for, or is this a temporary problem that will likely be fixed.

What other information should I provide?

**Comment by arunsrinivasan** [comment]
@rBatt Try again with `quote = ""`. If the problem persists, please add a new issue with a link to (sample of) file where the problem can be reproduced.

**Comment by rBatt** [comment]
@arunsrinivasan Thanks Arun, will do. I reinstalled 1.9.4 to get me through the days work. I'll switch back, test, and share soon.

**Comment by rBatt** [comment]
@arunsrinivasan I'm having problems still.

https://github.com/mpinsky/OceanAdapt/tree/testFread/testFread

The script in there is just a 1 liner, copy-pasting what I get in the console print out (error message, and then my `sessionInfo()`).

The .csv is the header of one of the files I am struggling with. There are a couple.

**Comment by rBatt** [comment]
@arunsrinivasan I've tried doing `quote=""` and I get the same error. That link is to a minimal reproducible example.

It seems like everywhere I look the go-to suggestion is "if fread doesn't work anymore, use quote="" "

It worked fine in 1.9.4. The only reason I'm so bothered is that my packages keep getting auto-updated through indirect means, so I have to continually uninstall and install_version. Plus, there have been lots of enhancements I'm missing out on!!

This is a real stumbling block for me. Any advice appreciated. Thanks

**Comment by arunsrinivasan** [comment]
@rBatt looking into this one.. In the meanwhile, you can do:

```r
fread("my_file.txt", skip="\nID")
```

It'll start from the first occurrence of that string..

**Comment by rBatt** [comment]
Thanks. I also just realized that I don't get an error with the example I linked with 1.9.6, only 1.9.7. However, I have other examples that don't work with 1.9.6 that I could try to share if needed.

Hard to know for sure if files will always have same header, so the `skip` approach is a bit tedious. But thanks. Right now just using 1.9.4, which seems to work great!

**Comment by rBatt** [comment]
Let me know if there's any progress, and I can try it out

**Comment by martinguerrero89** [comment]
Thanks @rBatt  the "skip" aproach works fine for me!
I don't know why recently when using version 1.9.4 of data.table R crashes but afortunatley with version 1.9.6 and the skip solution everything is working fine
Thanks!

**Comment by st-pasha** [comment]
The file is read correctly in the latest version
