### ISSUE TITLE
'datatable.prettyprint.char' wrapper

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1374]
FR: I use it a lot while developing.

``` r
ppc = function(trunc.char) options(datatable.prettyprint.char=trunc.char)
```

Do you think it's worth to merge such simple wrapper? just function name to revise

**Comment by arunsrinivasan** [comment]
How about exposing as additional argument to `print.data.table()`? `prettyprint.char = NULL` being the default..

**Comment by jangorecki** [comment]
already covered by #1523
