### ISSUE TITLE
[Request] names for tstrsplit results

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#1379]
[On SO](http://stackoverflow.com/a/32979049/1191259), I found myself doing...

    trial = c("9-5", "7-5", "13-3", "17-6")
    wdays = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
    setDT(tstrsplit(trial, "-", type.convert=TRUE))[, 
      paste0(wdays[V2 + 1], " ", V1, ":00")
    ]

It would be nice if I could instead do

    with( tstrsplit(trial, "-", type.convert=TRUE, list.names=TRUE), 
      paste0(wdays[V2 + 1], " ", V1, ":00")
    )

so `V1`, `V2`, etc are the names in the result.

The `list.names` arg could be extended to specify other naming rules as well.

**Comment by DavidArenburg** [comment]
I'm wondering if a syntax such `setDT(df)[, ":="(tstrsplit(x, ",", names = TRUE))]` should be allowed too since now this is a named list? This will both save the effort of finding out apriory how many column we supposed to get after the split and shorten the syntax
