### ISSUE TITLE
Allow get() sugar on LHS of := 

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1381]
For consistency with RHS.   Retain `(col) :=` shortcut too. 
See here : 
http://stackoverflow.com/a/33000778/403310

**Comment by arunsrinivasan** [comment]
I'm not sure about this. `get(char)` is supposed to extract the values associated with the variable.

**Comment by jangorecki** [comment]
agree with Arun on that, @mattdowle can we close it?

**Comment by MichaelChirico** [comment]
agreed it's confusing. `(col)` does just fine; we should just make sure there's reference to this style in getting started or FAQs
