### ISSUE TITLE
Run `value=` passed to set() within scope of DT.

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1382]
Overhead concerns may come into this, though.
http://stackoverflow.com/a/33000778/403310

**Comment by jangorecki** [comment]
That would mean we would change API of `set` from current standard evaluation to NSE. I would avoid this. NSE brings new set of problems. Eventually new arg could be added explicitly for NSE input.

**Comment by MichaelChirico** [comment]
I suppose we could get away with just doing `with(x[i], value)`, but this would immediately bring the `[` overhead to `set`.

**Comment by jangorecki** [comment]
voting for close, and keep `set` interface simple. Iit is now just:
```
function (x, i = NULL, j, value) 
{
    .Call(Cassign, x, i, j, NULL, value)
    invisible(x)
}
```

**Comment by MichaelChirico** [comment]
agree, I don't think we should support this. closing for now
