### ISSUE TITLE
[Request] Special symbol .SDdots for use in j

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#1399]
Suppose we want to collapse some columns with NAs by taking the minimum:

    DT[, do.call(pmin, c(.SD, list(na.rm = TRUE)))]

is kind of clunky. It would be nice if we could do

    DT[, pmin(.SDdots, na.rm = TRUE)]

where `.SDdots` acts like `...` in a function definition. 

I don't know if this request is compatible with data.table internals or has much broader application (... only `pmax` and `DT[, CJ(.SDdots, unique=TRUE)]` come to mind), so feel free to shoot it down with little to no explanation.

**Comment by arunsrinivasan** [comment]
It'd be best to revisit this if it pops up frequently.
