### ISSUE TITLE
shift conflict

### ISSUE THREAD

**Issue by sheffien** [Rdatatable/data.table#1401]
Hi, 

The new `shift` function conflicts in name with a similar function in the GenomicRanges package, which is giving me headaches and breaking some of my old code. I use both package extensively. 

Just wanted to point this out -- is there any way to rename or localize the data.table::shift function to avoid such conflicts?

Thanks.

**Comment by ChristK** [comment]
Load data.table package before the GenomicRanges package. So the shift() will default to the GenomicRanges function and data.table::shift() to the data.table shift function.

**Comment by sheffien** [comment]
Yes of course, but isn't there a better way to do this by registering the classes for the function or something?

**Comment by ChristK** [comment]
I'm not familiar with the GenomicRanges package. If the GenomicRanges::shift() is designed to operate on objects of specific class then maybe. Data.table:shift() though is designed to operate on a wide range of classes so the solution you suggest might get complicated and break workflow of other users. Maybe others more familiar with data.table internals can give a better answer.

**Comment by arunsrinivasan** [comment]
This is really an R issue. I don't know how to localise the function or register classes to avoid this issue. There are many functions from many packages that clash with each other. We try to avoid it, but in this case, I don't think there's a way around.

**Comment by jangorecki** [comment]
You can wrap `shift <- GenomicRanges::shift` after loading `data.table`.
If you want to localize `data.table::shift` you can do this by wrapping your code in a package and using `importFrom(data.table, fun1, fun2)` and not listing `shift`.

**Comment by sheffien** [comment]
So, maybe I'm wrong then, but I thought this was the point of [`setMethod`](https://stat.ethz.ch/R-manual/R-patched/library/methods/html/setMethod.html) -- does this answer your question, Arun?

For example, both IRanges and GenomicRanges define `shift` methods, but they each seem to restrict it to certain classes, so there is no conflict when you load them both. See 
[GenomicRanges shift](https://github.com/Bioconductor-mirror/GenomicRanges/blob/master/R/intra-range-methods.R), and [IRanges shift](https://github.com/hcorrada/IRanges/blob/master/R/intra-range-methods.R)

It just seems like for a function with a name as generic as 'shift' it might be a nice thing to do to try to avoid conflicts like this...

**Comment by mbacou** [comment]
Note that `data.table::shift` also conflicts with `raster::shift`. In my packages I get a warning:

```
Warning message:
replacing previous import ‘data.table::shift’ by ‘raster::shift’ when loading ‘hcapi3’ 
```

**Comment by jangorecki** [comment]
since R 3.3.0 there is a little better way to handle that, `import` function in NAMESPACE file gets `except` argument, so you should be able to import data.table package without `shift` function.
[manual](https://cran.r-project.org/doc/manuals/R-exts.html#Specifying-imports-and-exports)

**Comment by mbacou** [comment]
Great, thanks! I'd been wondering what the correct approach was.

**Comment by nsheff** [comment]
Actually, isn't  the correct approach for a shift function to specify the object classes it operates on?
