### ISSUE TITLE
Drop Null Values from `j` list elements

### ISSUE THREAD

**Issue by jdthorpe** [Rdatatable/data.table#1406]
A convenient idiom for selection columns in a data.frame takes advantage of the fact
that null values are dropped from vector concatenation:

```
DF = data.frame(a = 1:3,b = letters[1:3],c = LETTERS[1:3])
someCondition <- FALSE

# use `if(someCondition)` to conditionally include column 'c'
DF[,c('a','b',if(someCondition)'c')] 
:>   a b
:> 1 1 a
:> 2 2 b
:> 3 3 c
```

which does not work with data.table's b/c NULL values are not dropped 
from lists the same way they are dropped from concatenation:

```
DT = as.data.table(DF)
DT[,.(a,b,if(someCondition)c)]
:> Error in setnames(jval, jvnames) : 
:>   Can't assign 3 names to a 2 column data.table
```

I've defined a function called `..` which is a work around: 

```
.. <- function(...){
    x = list(...)
    x= x[!sapply(x,is.null)]
    x
}
DT[,..(a,b,if(someCondition)c)]
:>    V1 V2
:> 1:  1  a
:> 2:  2  b
:> 3:  3  c
```

but it seeks kind of kludgy to have to include my own function to accomplish an operation that is so common.  It would be convenient if `NULL` values were dropped from lists supplied to the `j` argument of `[.data.table`

**Comment by jangorecki** [comment]
This has been resolved somewhere between 2015 and 2019
```r
DT = as.data.table(DF)
DT[,.(a,b,if(someCondition)c)]
#   a b
#1: 1 a
#2: 2 b
#3: 3 c
```
