### ISSUE TITLE
S4 objects in cells

### ISSUE THREAD

**Issue by Cat1796** [Rdatatable/data.table#1407]
It is my understanding that data.table supports S4 objects in cells (as opposed to data.frame). Unfortunately there seems to be an issue with the implementation of the assignment. Here some code:
```R

require(data.table)
#create a bogus class for demonstration purposes
useless4 <- setClass(
 
  "useless4",
  
  # Define the slots
  slots = c(
    x = "numeric",
    y = "numeric"
  ),
  
  # Set the default values for the slots
  prototype=list(
    x = 0.0,
    y = 0.0
  )
)
#create vectors
id<-c(1:3)
many_useless <- lapply(rep("useless4",3),new)
#turn them into a data.table
DT<- data.table(id,many_useless )
#so far so good, S4 objects are in cells and can be accessed
print(DT[1,many_useless])
#assignments that work
DT[1,id:=5]
#create another instance of useless4 and actually pass some data
notsouseless <- useless4(x=4,y=5)
#my problem
DT[1,many_useless:=notsouseless]
```
This yields the following error:
```R
Error in `[.data.table`(DT, 1, `:=`(many_useless, notsouseless)) : 
  RHS of assignment is not NULL, not an an atomic vector (see ?is.atomic) and not a list column. 
```
Am I missing something? Is this a known limitation? How would one otherwise work with S4 in cells if one cannot assign (post initial creation).

EDIT: here is the only work around I have found (not efficient). Use a temporary list and assign the entire column at once
```R

mylist<-DT[,many_useless]
mylist[[1]]<-notsouseless
DT[,many_useless:=mylist]
```

**Comment by jangorecki** [comment]
List in RHS of `:=` is reduced by one, S4 must be wrapped in a list, so twice in that case.
Use the following:
```r
DT[1,many_useless:=list(list(notsouseless))]
```
Feel free to reopen if something is not clear.
