### ISSUE TITLE
[Request] progress bar for by

### ISSUE THREAD

**Issue by zachmayer** [Rdatatable/data.table#1409]
I think we should always know how many groups there are.  I've got a computation where I am applying a function by keyed groups in a `data.table`, and it takes a loooooog time.  It'd be nice to have a progress bar for by operations so I could track the function's progress through groups in the data.table.

For example, if I split my data into a list of data.tables, I could use [pbapply::pblapply](https://github.com/cran/pbapply/blob/master/R/pblapply.R) to track it's progress through each group (but I'd much rather use a single data.table and by!).

**Comment by zachmayer** [comment]
e.g.
```{R}
library(data.table)
x <- data.table(iris, key='Species')
x[,list(m=mean(Sepal.Width)),by='Species'] # progress bar here goes 0%, 33%, 66%, 100%
```

**Comment by MichaelChirico** [comment]
I imagine this is easiest to implement as another thing printed out by `verbose = TRUE`, no?

**Comment by arunsrinivasan** [comment]
@MichaelChirico makes sense..

**Comment by zachmayer** [comment]
Yes, that makes sense

**Comment by jucor** [comment]
I would love to have this, as I'm using data.table on a very large dataset with 7 M rows and 1.6M keys.

**Comment by jangorecki** [comment]
@zachmayer you can do your progress bar any way you want (with new lines or without), as answered in [this SO](http://stackoverflow.com/questions/38129223/progress-bar-in-data-table-aggregate-action). Please close the issue it works for you.

**Comment by zachmayer** [comment]
That's perfect!  For future reference, here is the solution I'm using:
```{R}
library(data.table)
dt = data.table(a=1:4, b=c("a","b"))
grpn = uniqueN(dt$b)
pb <- txtProgressBar(min = 0, max = grpn, style = 3)
dt[, {setTxtProgressBar(pb, .GRP); Sys.sleep(0.5); sum(a)}, b]
close(pb)
```

**Comment by jflycn** [comment]
To use @zachmayer 's method with ":=":

```
library(data.table)
dt = data.table(a=1:4, b=c("a","b"))
grpn = uniqueN(dt$b)
pb <- txtProgressBar(min = 0, max = grpn, style = 3)
dt[, x:={setTxtProgressBar(pb, .GRP); Sys.sleep(0.5);sum(a);},  b]
close(pb)
dt
```
