### ISSUE TITLE
make ITime accept NA

### ISSUE THREAD

**Issue by httassadar** [Rdatatable/data.table#1410]
> packageVersion("data.table")
[1] ‘1.9.6’

> as.ITime(NA)
Error in if (any(neg)) res[neg] = paste("-", res[neg], sep = "") : 
  missing value where TRUE/FALSE needed
> as.IDate(NA)
[1] NA

This causes trouble at key lookup and joining.

> DT = data.table(timestamp = "2010-01-01 00:00:00")
> DT
             timestamp
1: 2010-01-01 00:00:00
> DT[, c("date", "time") := IDateTime(as.POSIXct(timestamp))]
> DT
             timestamp       date     time
1: 2010-01-01 00:00:00 2010-01-01 00:00:00
> setkey(DT, date)
> DT[.(as.IDate("2010-01-01"))]
             timestamp       date     time
1: 2010-01-01 00:00:00 2010-01-01 00:00:00
> DT[.(as.IDate("2010-01-02"))]
Error in if (any(neg)) res[neg] = paste("-", res[neg], sep = "") : 
  missing value where TRUE/FALSE needed

**Comment by arunsrinivasan** [comment]
Fixed in devel `v1.9.7`. From [README](https://github.com/Rdatatable/data.table/blob/master/README.md

> as.ITime(NA) works as intended, #1354. Thanks @geneorama.
