### ISSUE TITLE
Create Jupyter notebook based vignettes

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1411]
This pandas tutorial is cool: https://github.com/jvns/pandas-cookbook

Would be great to have something like that for `data.table`.

**Comment by MichaelChirico** [comment]
I'm taking a stab at this. Any parameters for format? If not I've got somewhat of an idea of something to do

**Comment by MichaelChirico** [comment]
Here's a first pass at a chapter on `fread`:

https://github.com/MichaelChirico/data.table/blob/jupyter/vignettes/jupyter/Reading%20Data.ipynb

Feedback appreciated. @jangorecki feel free to chime in as well.

**Comment by jangorecki** [comment]
I haven't got a chance to work with notebooks, so cannot comment on it's structure.
Looking at it via https://try.jupyter.org/
- chunk2 - why not use `file.path` also for 3 files instead of `paste`?
```r
here <- file.path(getwd(), "baseballdatabank-master", "core")
fsep <- .Platform$file.sep

pitching_file <- paste(where, "Pitching.csv", sep=fsep)
batting_file  <- paste(where, "Batting.csv",  sep=fsep)
fielding_file <- paste(where, "Fielding.csv", sep=fsep)
```
- chunk3 - increase width of code block if possible, to be closer to console look and feel

**Comment by MichaelChirico** [comment]
Seems like RStudio is expanding to handle its own Notebook format:

https://blog.rstudio.org/2016/10/05/r-notebooks/

Perhaps worth just focusing on that instead of an IPython notebook?

**Comment by MichaelChirico** [comment]
https://twitter.com/michael_chirico/status/1097104415629074433

Poll results about how much the community wants alternative formats not particularly compelling... seems some people want other formats, but didn't manage to get any reasons why it's worth the effort... will leave this open for now

**Comment by jangorecki** [comment]
Such vignettes couldn't be vignette technically but just loose documents in `inst/doc` directory. Rmd format is pretty good for now, it is kind of standard, and I think is more lightweight than jupyter, at least for use. Closing for now, we can reopen if there will be reasons good enough.
