### ISSUE TITLE
setclass() function?

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1412]
Do we need a `setclass()` function similar to `setnames()`? Filing as issue due to this (now stale) PR https://github.com/Rdatatable/data.table/pull/844

**Comment by jangorecki** [comment]
There is not much interest in this FR over the last 5 years. I am closing it for now, as changing class like this is not that common operation for ordinary R users. And for those extraordinary users can easily use `setattr`.
