### ISSUE TITLE
move changelog from README.md to NEWS

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1420]
`NEWS` file is standard CRAN-friedly solution for providing changelog of the package. At the moment README file is huge and in practice it is README and NEWS.
If I would design this change I would simply cut and paste the changelog part of README.md and put into NEWS (eventually NEWS.md), and a link to it in a README.
README then could be high level description + links to other resources.
README might include the breaking changes in the current dev version so anyone can clearly see most critical info without digging through long list of fixes.

- [x] migrate changelog from README.md to NEWS.md
- [ ] update url in `data.table.Rd`
- [ ] add NEWS reference to access locally? something like `file.show(system.file("NEWS.md", package="data.table"))` to `data.table.Rd` or readme

**Comment by arunsrinivasan** [comment]
Yes, Matt and I discussed this briefly sometime ago, and we intend to do that.

**Comment by jangorecki** [comment]
According to info from [devtools update post](http://blog.rstudio.org/2016/02/02/devtools-1-10-0/) CRAN supports NEWS.md already, so the markdown format looks like a best way to go.

An off-topic comment regarding linked post, quoting:

> install_github() is now lazy and won't reinstall if the currently installed version is the same as the one on github. Local installs now add git and github metadata, if available.

Above may result into issue reports for fixes already made in 1.9.7, but still reproducible on older 1.9.7. Just letting you know this may hit the issue list someday so better to be aware.

**Comment by arunsrinivasan** [comment]
Seems like `force = TRUE` should do the trick. Will have to update wiki.

**Comment by jangorecki** [comment]
@mattdowle why not just NEWS.md instead of ReleaseNotes.md ? it will fit into standard R packages structure.
