### ISSUE TITLE
Use existing index even when auto index is disabled

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1422]
If you have `auto.index=TRUE` your code will always create index when filtering in `i` for supported cases but many times the dataset is just temporary processing data which will be gone after exit of function. In those cases there is not point to create index. On the other hand I have dataset where I've manually set indexes and those I would like to use (via `==` or `%in%`).  
Currently `datatable.auto.index` option seems to affect both cases so cannot be turned on.
```r
library(data.table)
options("datatable.auto.index"=TRUE)
options("datatable.verbose"=TRUE)
d = data.table(k=1)
set2key(d, k)
forder took 0.004 sec
d[k==1]
# Using existing index 'k'
# Starting bmerge ...done in 0 secs
#    k
# 1: 1
options("datatable.auto.index"=FALSE)
d = data.table(k=1)
set2key(d, k)
# forder took 0 sec
d[k==1]
#    k
# 1: 1
```

**Comment by cooldome** [comment]
Upvoting the request, I also had use cases were wanted to manually maintain secondary keys and not to really on automatic secondary keys construction.  Unfortunately, `options("datatable.auto.index"=FALSE)` disables a use of already available secondary keys.

**Comment by jangorecki** [comment]
Added to 1.9.8 milestone as it will be useful to have when presenting difference of use of index vs not using index. So allows to avoid helper functions like the one `with_index` I've used in [Scaling data.table using index](https://jangorecki.github.io/blog/2015-11-23/data.table-index.html). Now have have index used on joins so it is good to be able to present that feature nicely.

**Comment by jangorecki** [comment]
Updated vignette can be viewed [here](http://jangorecki.gitlab.io/data.table/library/data.table/doc/datatable-secondary-indices-and-auto-indexing.html).
