### ISSUE TITLE
[Request] Expose .SD in i

### ISSUE THREAD

**Issue by claytontstanley** [Rdatatable/data.table#1424]
So if I have the right mental model here, I think that .SD in i (if it were available) will always be equivalent to using the variable name of the table instead. However, I tried using .SD in i and was surprised that it doesn't work. Maybe it's just me, but I'm starting to find it a bit of a code smell when I have to reuse the variable name for the table within the table itself, as data.table seems to be all about not requiring that (e.g., how all column names are exposed to the environment within `[`). 

Here's a code example:

> cTbl = data.table(ID=c(1,1,1,2,2,2,3,3,3), val=c(1,2,3,4,5,6,7,8,9))
> cTbl[ID %in% cTbl[, .N, ID][sample(.N, 2), ID]]
   ID val
1:  2   4
2:  2   5
3:  2   6
4:  1   1
5:  1   2
6:  1   3

> cTbl[ID %in% .SD[, .N, ID][sample(.N, 2), ID]]
Empty data.table (0 rows) of 2 cols: ID,val

> cTbl[.N, val, ID]
   ID val
1:  3   9
> 

So .N is available in i, and to use that with a by the user should already understand that .i is filtered prior to the by operation. .SD in i would be an extension to that same model, unless I'm missing something. However, this would mean that the meaning of .SD depends on the position when a by is present (if in i it is used prior to the by, if in j used with the by), so maybe this is an all-around bad idea because of that. That said, .N has the same issue, and it's available in both i and j.

Also, thinking about this a bit more, it wouldn't be useful just for shorthand. If many chaining operations were done prior, .SD would have no named equivalent at that point, so exposing .SD in i would allow the user to reference the entire current table to do some needed operation in i, which cannot be done currently (unless you push the whole operation to j which requires .SD[... .SD[...]] syntax I think, which looks more complicated to me).

Thoughts?
-Clayton

**Comment by franknarf1** [comment]
I see what you're saying about having to retype the table name, but code smell is very subjective. To me, big one-liners built in `i` are noxious; and I instead do unclever but transparent things like:

    my_IDs = cTbl[, if (mean(val) > 4) 1, by=ID]$ID
    cTbl[.(my_IDs), on="ID"]

`.N` in `i` is nice to have, but easily confusing. For example, your

    cTbl[ID %in% cTbl[, .N, ID][sample(.N, 2), ID]]
    # is the same as
    cTbl[ID %in% cTbl[, 1, ID][sample(.N, 2), ID]]
    # or just
    cTbl[ID %in% sample(unique(ID),2)]

The `.N` you make in the `cTbl[, .N, ID]` is not actually used in the next step, where it takes on the name `N` (without a dot). Or maybe I'm misunderstanding... I do find its use confusing.

**Comment by claytontstanley** [comment]
Yeah the example could have been better, and your last version is a much cleaner way to write this which avoids the issue of .SD in i for this problem. However, I'm still curious in general your thoughts of exposing .SD in i in the same way that .N is exposed that way.

**Comment by arunsrinivasan** [comment]
No, there are no plans for this. You'll just have to use `dt`. Besides, for operations like: `dt[x == 5, val := Y[.SD, val]]` for example, we need `.SD` to refer to the outer frame. 

The use case here isn't compelling enough, and I've not seen cases where `.SD` needs to be in `i`, yet.
