### ISSUE TITLE
FR for `fread`: if `select` is used, `colClasses` need only correspond to the columns in `select`

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1426]
I never filed a FR for a [question I raised a year ago on SO](http://stackoverflow.com/questions/25691637/using-colclasses-and-select-arguments-of-fread-simultaneously).

The current canon for using `select` and `colClasses` simultaneously is (IMO) unwieldy.

Consider:

```
#file to read
ffile <- paste0(paste(paste0("V", 1:20), collapse = ","),
              "\na,b,c,d,e,1,2,3,4,5,1.1,1.2,1.3,1.4,1.5,",
              "TRUE,FALSE,TRUE,FALSE,TRUE")

#columns to take
sel <- c(2, 10, 13:15, 20)
#types of all columns
tps <- rep(c("character", "integer",
           "numeric", "logical"),
         rep(5, 4))
```

Here's the best I could come up with as a programmatic way to use `fread`:

```
DT <- fread(ffile, select = paste0("V", sel),
            colClasses =
              sapply(unique(tps[sel]),
                     function(x) paste0("V", sel[which(tps[sel] == x)])))
```

(gross; could be spelled out explicitly as the following, but this is generally unsatisfying:)

```
DT <- fread(ffile, select = paste0("V", sel),
            colClasses =
              list(character = "V1", integer = "V10",
                   numeric = c("V13","V14","V15"),
                   logical = c("V20")))
```

To me it would make much more sense to be able to simply write:

```
DT <- fread(ffile, select = paste0("V", sel), colClasses = tps[sel])
```

But this currently produces the error:

> Error in `fread(ffile, select = paste0("V", sel), colClasses = tps[sel])` : 
>   `colClasses` is unnamed and length 6 but there are 20 columns. See `?data.table` for `colClasses` usage.

Parsimonious, and as far as I can tell unambiguous. Any reason why this wouldn't work?

**Comment by MichaelChirico** [comment]
What about just reversing the order of dealing with `select` vs. `colClasses` -- switch [Lines #1141 - 1157](https://github.com/Rdatatable/data.table/blob/master/src/fread.c#L1141-L1157) with [Lines #1059 - 1112](https://github.com/Rdatatable/data.table/blob/master/src/fread.c#L1059-L1112), and reset `ncol` to `length(select)` within the `select` condition?

**Comment by dselivanov** [comment]
+1 for this, also annoying me. Will try to check.

**Comment by arunsrinivasan** [comment]
Quite a few issues marked for v1.9.8 already. Can't take a look anytime soon. Glad if you could look into this. Thanks.

**Comment by renkun-ken** [comment]
Really need this.
