### ISSUE TITLE
uniqueN is not handling NULL value

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1429]
Latest 1.9.7:
```r
library(data.table)
uniqueN(NULL)
# Error in forderv(x, by = by, retGrp = TRUE) : 
#    First column being ordered is type 'NULL', not yet supported
```

**Comment by arunsrinivasan** [comment]
There's a bug when `uniqueN()` is used along with a `list()` at the moment.. it results in `length(unique(.))` which would return the wrong result.

**Comment by arunsrinivasan** [comment]
This bug is as a result of #1224, not this one.
