### ISSUE TITLE
Fuzzy join `FJ()` for unstructured search

### ISSUE THREAD

**Issue by danielkrizian** [Rdatatable/data.table#1431]
Imagine full-text, unstructured search powered `data.table`. Here is the teaser, which I believe would quickly become a [popular](http://stackoverflow.com/questions/24589775/fuzzy-search-box-widget-with-shiny-in-r) feature.  Users often search on-the-fly reference/master tables containing text data such as names, using google-like queries.

Similar, but not quite the same use cases:
#636 - similar idea, but requires regex-like query syntax, as opposed to simpler google-like query syntax
#625

``` r
library(data.table)

# our reference database that we want to search in
dt = data.table(Name=rownames(mtcars))
setkey(dt, Name)

# note the two Toyotas
tail(dt) 
#>                Name
#> 1: Pontiac Firebird
#> 2:    Porsche 914-2
#> 3:   Toyota Corolla
#> 4:    Toyota Corona
#> 5:          Valiant
#> 6:       Volvo 142E

# exact join
search_string = "Toyota Corolla"
dt[J(Name=search_string)]
#>              Name
#> 1: Toyota Corolla

# exact join doesn't quite work on partial strings
search_string = "Corolla"
dt[J(Name=search_string)]
#>       Name
#> 1: Corolla

# feature like (F)uzzy (J)oin would be extremely cool, facilitating unstructured lookups:
search_string = "Toyota"
dt[FJ(Name=search_string)] # obviously error
#> Error in eval(expr, envir, enclos): could not find function "FJ"

# ideal output something like this, sorted by best string distance (e.g. `adist` function)
#>              Name  Distance
#> 1:  Toyota Corona         7
#> 2: Toyota Corolla         8
```

**Comment by arunsrinivasan** [comment]
Yes, I've been quite interested in implementing fast/vectorised pattern searching for data tables for a while... Not sure when we'll get to it though :-).

**Comment by danielkrizian** [comment]
Hi, here is one simplified implementation I've been playing with, using `FJ(x,y)` syntax similar to `CJ(...)`. More convenient would probably be `DT[FJ(...)]`

``` r
library(stringdist); library(data.table)

options(fuzzy_match.weight=c(d = 1, i = 0.7, s = 1, t = 1))

# find fuzzy equivalents of x in table satisfying minimum similarity thresholds. Similarity is expressed relative to string length.
fuzzy <- function(x, table, 
                        thres = 0.8,
                        method = c("osa", "lv", "dl", "hamming", "lcs", "qgram", "cosine", "jaccard", "jw", "soundex"), 
                        useBytes = FALSE,
                        weight = c(d = 1, i = 1, s = 1, t = 1), 
                        maxDist = Inf, q = 1, p = 0,
                        ncores = 1, cluster = NULL) {
  
    mat = stringdist::stringdistmatrix(tolower(table), tolower(x), method=method[1], weight=weight)
    mat = 1 - mat / matrix(rep(nchar(x), times=nrow(mat)), ncol=ncol(mat), byrow=T)
    best = max.col(t(mat), ties.method = "first")
    if(is.numeric(thres)) {
      sim = mat[(1:ncol(mat)-1)*nrow(mat)+ best] # similarity scores
      best[sim<thres] <- NA
    }
    table[best]
}

REF = data.table(Name=rownames(mtcars), key="Name")
tail(REF)
#>                Name
#> 1: Pontiac Firebird
#> 2:    Porsche 914-2
#> 3:   Toyota Corolla
#> 4:    Toyota Corona
#> 5:          Valiant
#> 6:       Volvo 142E

ugly = c("Toyotta Corola", "T-Corona", "Pontiac F.", "Volvo 145") # this is unclean data that we want to search & match,

DT = data.table(Name=ugly, val=1:length(ugly),key="Name")
DT
#>              Name val
#> 1:     Pontiac F.   3
#> 2:       T-Corona   2
#> 3: Toyotta Corola   1
#> 4:      Volvo 145   4

FJ <- function(x, y, thres) {
  fcol = fuzzy(x[[key(x)]], y[[key(y)]], weight=getOption("fuzzy_match.weight"), thres=thres)
  x[, eval(key(x)):=fcol]
  return(x)
}

found = FJ(DT, REF, thres=.8)
found
#>              Name val
#> 1:             NA   3
#> 2:             NA   2
#> 3: Toyota Corolla   1
#> 4:     Volvo 142E   4

found = FJ(DT, REF, thres=.2)
found
#>                Name val
#> 1: Pontiac Firebird   3
#> 2:    Toyota Corona   2
#> 3:   Toyota Corolla   1
#> 4:       Volvo 142E   4
```

**Comment by arunsrinivasan** [comment]
@danielkrizian looks great! Have added it to v2.0.0 milestone. Thanks!

**Comment by jangorecki** [comment]
@danielkrizian is it much different than https://github.com/dgrtwo/fuzzyjoin package? Looks like it could be used for that but it has heavy dependencies.

**Comment by danielkrizian** [comment]
@jangorecki  [dgrtwo/fuzzyjoin](https://github.com/dgrtwo/fuzzyjoin) is a very nice find, more general. Seems like new package (first commit March 2016). Syntax native to `data.table` would help: i.e. terseness of [J()](http://stackoverflow.com/questions/22001945/how-is-j-function-implemented-in-data-table), leveraging existing `data.table` arguments like `on` ([`fuzzyjoin::stringdist_join` for example uses `by`](https://github.com/dgrtwo/fuzzyjoin/blob/master/R/stringdist_join.R#L10)]

**Comment by jangorecki** [comment]
@danielkrizian I'm not sure if I would like it even as suggested dependency. It has dependencies with the chain of other deps. What is really needed is a function that evaluates to expected logical vector - so the core feature seems to be dependent on `stringdist`, maybe also `stringr`/`stringi`, am I correct?

**Comment by danielkrizian** [comment]
There is just `stringdist` dependency (if `data.table` implements only maximum similarity match). Unless you want also _regex_ matching - but that is additional feature (which can still be made dependent only on `base::grepl`, not `stringr/stringi` at all.). 

It really helps to break the task down and implement _"maximum similarity given minimum threshold"_ match first, later generalize `FJ(..., type=c("stringdist", "regex", "numeric_difference", "custom"))` for example. In fact, numeric similarity vs string similarity mode could be auto-detected based on join column class. 

Also, considering whether to talk about distance measure and looking for minimum match given max threshold, or talking about similarity measure as reciprocal of distance (`~1/dist`) and looking for maximum match given min threshold. Another consideration is absolute similarity vs normalized similarity - scaled/normalized relative to the length of the target (i.e. string length, or distance from zero for numeric).

**Comment by franknarf1** [comment]
Re regex matching, I think the [OP in this SO q](http://stackoverflow.com/questions/42208119/aggregate-if-string-contains-specific-text-in-r) would benefit from it:

    library(data.table)
    DT = data.table(name = c('bike+ride','shoe+store','ride','mountian%20bike','ride+along'), 
      count = c(2,5,8,7,6))
    patt = c("ride", "bike")

The goal is to sum `count` for rows matching each `patt`:

    # current workaround
    mDT = data.table(patt)[, .(w = grep(patt, DT$name)), by=patt]
    DT[mDT$w, sum(count), by=.(patt = mDT$patt)]

    # desired syntax
    DT[.(patt = patt), on=.(name %like% patt), sum(count), by=.EACHI]

**Comment by waynelapierre** [comment]
Any progress? This seems a super useful feature.

**Comment by tdhock** [comment]
why not just use regex for partial text matching? `dt[grep("Toyota", Name)]`

**Comment by MichaelChirico** [comment]
> why not just use regex for partial text matching? `dt[grep("Toyota", Name)]`

here's a fresh applied example:

https://jcarroll.xyz/2024/03/15/fuzzy-grouping.html

regex is not suited for this problem. even string distance is pretty limited in what it can accomplish IMO.

Honestly I think this is out of scope for data.table. Not sure there's anything specific about data.table internals that suggests we're well-positioned to offer a good solution here. The most powerful solutions will do things like embeddings+clustering that are well beyond our scope.
