### ISSUE TITLE
showProgress is not type integer but type 'logical'

### ISSUE THREAD

**Issue by richierocks** [Rdatatable/data.table#1436]
With the latest `data.table` `1.9.7`, the `datatable.showProgress` global option is set to one, which `fread` then complains about.

To reproduce:

```{r}
library(data.table)
getOption("datatable.showProgress")
## [1] 1
fread("x\n1\n")
## Error in fread("x\n1\n") : 
##   showProgress is not type integer but type 'logical'. Please report.
```

**Comment by arunsrinivasan** [comment]
Can't reproduce on Mac and Linux (Ubuntu). I frankly don't understand the reason for this error...

**Comment by franknarf1** [comment]
No repro on Win 7 either.

**Comment by richierocks** [comment]
I've tried on two other machines using a variety of versions of R and data.table, and I can't reproduce this elsewhere either.  If you are happy to leave this open for a few more days, I'll dig around on my work machine that caused the problem next week.

**Comment by arunsrinivasan** [comment]
:+1:

**Comment by richierocks** [comment]
On the problem machine it works with the CRAN version, and today's devel version, so I'm putting it down to a possible temporary bad build, or other unexplained weirdness.
