### ISSUE TITLE
Optimize DT[,...:=lapply(.SD,...)] to for(...)set(...)

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1441]
So the user doesn't need to know to use `for(...)set(...)` to reduce memory usage, detailed here:
http://stackoverflow.com/a/33000778/403310

Also for combining with `by=` i.e. optimize `DT[,...:=lapply(.SD,...), by=...]` which is harder to achieve with manual `for(...)set(...)`. 

Optimizing `:=lapply` could solve the symbol repetition issue too raised in the question linked above.

**Comment by mattdowle** [comment]
Also see here:  http://stackoverflow.com/questions/32940580/convert-some-column-classes-in-data-table/32942319?noredirect=1#comment55531299_32942319

**Comment by jangorecki** [comment]
this is a duplicate of #4225, isn't it? @MichaelChirico

**Comment by MichaelChirico** [comment]
yes i'd say so. nice to see some SO references in this one
