### ISSUE TITLE
Rename set2key to setindex?

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1442]
As suggested here : 
https://twitter.com/mark_danese/status/669325773103169536

(Obviously previous name would be kept and very slowly deprecated).

**Comment by franknarf1** [comment]
Yeah, I agree. I think it would be more intuitive, matching the name of the attribute (which everyone sees in `str(DT)` and puzzles over).

**Comment by jangorecki** [comment]
There is no issue with having two names for same function, if we don't use `set2key` in the docs it can be conceptually deprecated, but we can still support both names cheaply by `f1 <- f2 <- function(...) ...` as long as we not introduce breaking changes.
On the other hand changing name of a function can help to make breaking changes for index, not sure what exactly they could be now.
I wonder if storing indexes in separate environment wouldn't help to process them, and maybe for performance too? If so this could be one of such changes.
```r
idx.env = new.env()
...
setattr(dt, "index", idx.env)
```
@franknarf1 data.table does not have own `str` method, which can help on that, or for example hide some attributes like `attr(*, ".internal.selfref")=<externalptr> `.

**Comment by cooldome** [comment]
Shouldn't it be addindex/removeindex of some sort. You would certainly want to add a new index without affecting already created ones

**Comment by arunsrinivasan** [comment]
I like `set2key`. But I don't mind `setindex`. But isn't the idea that the user doesn't need to know about these functions, as all optimisations will (eventually) happen under the hood?

The change, if need be, is straightforward. Moving it to v2.0.0 until a decision is made.

**Comment by jangorecki** [comment]
Secondary keys are basically indexes, they don't affect real data, you can have as many as you want. Name `setindex` is appropriate. Latest `all.equal.data.table` if checking attributes can eventually report *has no index* ([test.data.table.R#L213](https://github.com/Rdatatable/data.table/blob/e72af027270871c4e34ae23eb59892028187c711/R/test.data.table.R#L213)). *Index* is somehow cleaner than *secondary keys* and it precisely reflects the actual state.

@cooldome no, secondary indexes does not resorts the data, it is a limitation of data.table *key* but not secondary keys.

**Comment by arunsrinivasan** [comment]
Oops, just noticed you'd assigned this to yourself, @jangorecki...

**Comment by MichaelChirico** [comment]
Are we keeping `key2`? Maybe `index` or `indices` instead?

**Comment by jangorecki** [comment]
`index` is a generic method in `zoo` package, if it is possible to use it as data.table method without importing zoo, then it would be the best. Alternatively we can use `indices` - which additionally express there can be multiple objects returned, unlike `key`. On the other we already masking `xts::last` so masking `zoo::index` wouldn't be as bad, as if it was a base R function. We can have `index` generic + `index.data.table`, so other `zoo` related classes would be correctly dispatched.

**Comment by arunsrinivasan** [comment]
nice catch @MichaelChirico. indices makes perfect sense.

**Comment by MichaelChirico** [comment]
Also `get2key`, unless that's vestigal
