### ISSUE TITLE
when 'select' argument is provided, columns should be returned in the order provided to that argument 

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1445]
```r
require(data.table) # devel
fread("a,c,b\n1,2,3", select=c("b", "c"))
#    c b
# 1: 2 3
```

I'd have expected the columns to be in the order provided to `select`. Just ran across this bug today.

**Comment by MichaelChirico** [comment]
Any reason to care about the column order? I've noticed this but never particularly minded. Usually the order I specify them in is meaningless.

**Comment by arunsrinivasan** [comment]
@MichaelChirico perhaps because the reason I ran into this issue is due to recently implemented `col.names` argument. You can't use `col.names` argument together with `select` if you can't be sure of the order of columns in the result.

```r
fread(my_file, select=c("b", "c"), col.names = c("B", "C"))
```
names the columns wrongly in this case.. and so one has to do:

```r
cols = c("b", "c")
dt = fread(my_file, select=cols)
setcolorder(dt, cols)
setnames(dt, cols, c("B", "C"))
```

**Comment by MichaelChirico** [comment]
@arunsrinivasan duly noted, I had missed the `col.names` update. Very useful.

**Comment by mattdowle** [comment]
Agreed.  And fread should error if the column requested isn't present.

```R
> fread("a,c,b\n1,2,3", select=c("b", "foo"))
   b
1: 3 
# TODO:  Error: column name "foo" passed to 'select=' not found in data
```
