### ISSUE TITLE
data.table() should ignore/warning on `stringsAsFactors` argument

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1446]
It would avoid the case to create `stringsAsFactors` recycled to length of other arguments. Like this: http://stackoverflow.com/q/33947148/2490497
Better consistency with data.frame.
Should be pretty simple and safe.

**Comment by arunsrinivasan** [comment]
I think it'd be better to implement it. The code is there in `as_factor()` function within `fread.R`.. in case you'd like to have a look at it. We just need to pull it out and use the same logic in `fread()` here..

**Comment by arunsrinivasan** [comment]
Thanks, but I've implemented it similar to `fread()` now.
