### ISSUE TITLE
fread should read columns of Date/POSIXct types directly

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1450]

**Comment by statquant** [comment]
May be use fasttime to read POSIXct/Date quickly like [here](http://stackoverflow.com/questions/35247063/is-there-a-fast-parser-for-date/35247222?noredirect=1#comment58209017_35247222)

**Comment by MichaelChirico** [comment]
@statquant thus relating this to #587

**Comment by MichaelChirico** [comment]
Closed by https://github.com/Rdatatable/data.table/pull/2545 ?

**Comment by jangorecki** [comment]
@MichaelChirico agree we can close this one, @arunsrinivasan please re-open if needed, ideally providing a use case, so it can be added to unit tests.
