### ISSUE TITLE
Faster internal date/datetime implementation (with ns resolution..)

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1451]
Marking this as an issue for next release (following email conv. with Matt).

**Comment by statquant** [comment]
++ that, spoke with @mattdowle many times a IDateTime (date+time) class with ns resolution stored as int64 would be life changing

**Comment by MichaelChirico** [comment]
related: #1906

**Comment by jangorecki** [comment]
`nanotime` is really nice package, and actively maintained, made by @eddelbuettel and @lsilvest 
https://github.com/eddelbuettel/nanotime/
I think it make sense to not duplicate that much work. We are already taking care to ensure nanotime works well inside data.table by having it in our unit tests.
