### ISSUE TITLE
Extend auto indexing to multiple columns

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1453]
(and eventually to any type of logical operation). This would be very efficient as the number of condition increases (as binary search reduces the search space with every condition).

**Comment by franknarf1** [comment]
This came up on SO: http://stackoverflow.com/q/35438190/1191259 Might want to post an answer there when this is implemented.

**Comment by jangorecki** [comment]
without binary search it could be done now, if using under the hood with `Reduce` over `x[i = ..., which = TRUE]` many queries with indexes and combined.

**Comment by arunsrinivasan** [comment]
Moving this to next release (should be straightforward after non-equijoins are done (hopefully)).

**Comment by MarkusBonsch** [comment]
My PR #2494 addresses the optimized subsetting on multiple columns with & connection like DT[a==1 & b == 2]. Additionally, support for the %chin% operator was introduced. However, <, <=, >, >= are not yet supported. Neither are queries that are connected by | like DT[a==2 | b==3].

**Comment by jangorecki** [comment]
I am not sure if we should keep this issue open. Auto index has been extended to work on multiple columns by @MarkusBonsch PR. The OR operator is not yet there, but as per initial comment

> as binary search reduces the search space with every condition

It was not really asking for `|` but for `&`.

Unless there is an idea to address other stuff, I would close the issue, it is quite broadly defined and biggest part of it has been already addressed. If we want to keep it open, it is best to list precisely what is to be done, so it will be clear what is left.
