### ISSUE TITLE
uniqueN needs na.rm argument

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1455]

**Comment by jaapwalhout** [comment]
See [this question & answer on StackOverflow](http://stackoverflow.com/a/34007315/2204410) on StackOverflow for an example

**Comment by arunsrinivasan** [comment]
Hm, how to handle NAs when multiple columns are provided (`uniqueN` in data.table is not limited to vectors alone)..

**Comment by MichaelChirico** [comment]
`complete.cases`?
