### ISSUE TITLE
[Request] Filter by group criteria

### ISSUE THREAD

**Issue by red-swan** [Rdatatable/data.table#1456]
`DT[ .N > 60, by = groupingID]`
to quickly filter out any groups where you don't have 60 observations or
`DT[ min(Date) > "1989-11-09" , by = groupingID]`
to filter out a group that started before the Berlin Wall fell

I'm new to github and don't know how this all works. Forgive me if this is not proper protocol. Thank you.

**Comment by franknarf1** [comment]
I think this is roughly the same as https://github.com/Rdatatable/data.table/issues/788

**Comment by red-swan** [comment]
If this is something that you've decided you'd like to implement, I'd love to help. I'm new to collaborating, though, so I would need help to be helpful.

**Comment by arunsrinivasan** [comment]
Yes, it's a dup. There's already a way to do it.. `DT[, .SD[.N > 60], by=ID]`. It just needs to be optimised better.. which I'll work on later for this release.

PS: of course we'd be happy to receive PRs. There are quite a few issues for you to choose from :-).
