### ISSUE TITLE
shift type argument could be more intuitive

### ISSUE THREAD

**Issue by markdanese** [Rdatatable/data.table#1458]
for a function named shift, which operates on a column, I think it makes more sense to talk about shifting the column "up" or "down" by a certain number of rows.  The current words "lag" and "lead" don't easily communicate what is going on.  In other words, I don't think most people talk about lagging and leading by rows.  But I do think they say "shift column x up/down 1 row".  Hence, I might allow either "lag" or "down" and "lead" or "up" for the type argument.  Or, just a simple clarification in the documentation would help.  Apologies if I am missing something in the terminology.  Feel free to close.

**Comment by arunsrinivasan** [comment]
lead and lag are fairly standard terms. One just needs to get used to it.

**Comment by jangorecki** [comment]
@markdanese lag and lead are also terms used in the SQL analytics functions for the same purpose, so at least for people from db background it is quite intuitive.
