### ISSUE TITLE
Function to make columns w/ same names in 2 data.tables have matching classes 

### ISSUE THREAD

**Issue by rBatt** [Rdatatable/data.table#1460]
Beyond the succinct description in the title, [this question on SO](http://stackoverflow.com/q/34091811/2343633) explains it best.

[This answer](http://stackoverflow.com/a/34093064/2343633), along with my comment, offer an inelegant approach for `data.table`. @arunsrinivasan made a comment on that question.

I could provide a lot of examples for where I need this/ why, if it'd help understand use-cases. 

something like `match_class(dt1, dt2, by=intersect(names(dt1),names(dt2))` would be great (where the classes of `dt2` are match to those of `dt1`, so the order matters). 

Even better would be warnings printed if the conversion isn't likely to be back compatible. Like if in `dt1` there is a column formed from `colA = c("01","02")`, and in `dt2` there is a column along the lines of `colB = c(1L, 2L)`, then converting back might produce different results where a user might intend for a match. I've seen `fread()` print out warning along these lines before, I believe.

**Comment by rBatt** [comment]
Turns out that there were some complications in this question. See the answer to my own question, and related links. Possible R bug that lead to difficulty (but unclear; [here for related question](http://stackoverflow.com/questions/34093056/asx-double-and-as-doublex-are-inconsistent), [here for possible bug](https://stat.ethz.ch/pipermail/r-devel/2015-December/072079.html). The responses, perhaps surprisingly, seems consistent with the impression that the behavior is less-than-intuitive.

<shrug> Might be useful to keep in mind if creating matching classes is a feature that's desirable.

**Comment by jangorecki** [comment]
I would say it is not related to data.table. You have two list, and want to coerce elements of those lists to match the class for matching names of those lists. This can be well applied on data.tables as well, agree. I think such a data cleaning routine is beyond the scope of data.table. SO serves a good resource here, but I am not really finding good reasons to have such routine in data.table. In any case we can re-open this issue if there will be really demand for it.

**Comment by MichaelChirico** [comment]
I'll add that if `tidyverse` has such function (I don't know offhand), you might try checking the [`tidyfast`](https://github.com/TysonStanley/tidyfast) package which seeks to offer `data.table` backend to `tidyr` data cleaning-type functions. Even if there's no `tidyverse` equivalent, I think there is a better fit anyway.
