### ISSUE TITLE
rblindlist error?

### ISSUE THREAD

**Issue by rBatt** [Rdatatable/data.table#1467]
```
Error in .Call("Crbindlist", l, use.names, fill) : 
  "Crbindlist" not resolved from current namespace (data.table)
```

Running data.table 1.9.6 

I got the error when simply trying to print a data.table, not while creating it (even running `str(dt)` showed reasonable content). Subsequent function that tried to use `dt` did fail though, with similar error message.

I uninstalled, installed v 1.9.4, and the error was gone.

I haven't tried 1.9.7, and I haven't tried to isolate the error and make a minimal example. If this isn't a duplicate issue and it's an unresolved bug, I can post back with much more information.

Sorry for such a minimal tip-off. Once I got it working again I tied my system up with the work I was trying to do. But just let me know and I'll definitely report back with all the useful goodies :)

Thanks/ sorry

**Comment by MichaelChirico** [comment]
Were you able to reproduce the error after starting a new R session, before installing 1.9.4?

I've gotten similar odd errors that resolved upon restarting R. Haven't isolated a specific trigger, though.

**Comment by rBatt** [comment]
Frankly, I haven't tried to reproduce it yet. But sitting in 1.9.4 all week. And at this point, I can barely remember where it happened to me :( I'm not going to be upgrading to a higher version until #1371 gets fixed, because I need fread to work :(

**Comment by jangorecki** [comment]
@rBatt Can you post a reproducible example using any data.table version?

**Comment by rsaporta** [comment]
I had the same issue, but was unable to isolate it too deeply. 
Quitting out my R Session and starting from a fresh, clean session resolved the issue. 

It only occurred when printing out more than 100 rows of data, on any data.table, regardless of content. Even a simple  `DT <- data.table(A=1:1000, B='hello')`  had the same issue.
`DT[1:100]` would print fine  (as would, any arbitrary 100 lines, ie `DT[201:300]`)
But `DT[1:101]` would throw the error shown in the OP

Once I started the new session, I was no longer able to reproduce it.

**Comment by arunsrinivasan** [comment]
When you come across it next time, without restarting the session use `debugonce(data.table:::print.data.table)` and try to isolate the issue..

Until then, I'm not sure if we can do anything about this.

**Comment by rsaporta** [comment]
Just hit the error again

    Error in .Call("Crbindlist", l, use.names, fill) :
      "Crbindlist" not resolved from current namespace (data.table)

    R> traceback()
    6: rbindlist(l, use.names, fill, idcol)
    5: data.table::.rbind.data.table(...) at <text>#1
    4: rbind(deparse.level, ...)
    3: rbind(head(x, topn), tail(x, topn))
    2: print.data.table(x)
    1: function (x, ...)
       UseMethod("print")(x)

Then in rbindlist(), it's right in the first line
`debug: ans = .Call("Crbindlist", l, use.names, fill)`

**Comment by damienchallet** [comment]
Hi,

I hit this problem only when I use RStudio (0.99.887), but not in an R session started from a terminal.

R 3.2.3.

When I try to rbind an empty data.table with a one-line data.table, I get

> source('~/work/rstatistics/bug_data.table.R')
Error in .Call("Crbindlist", l, use.names, fill) : 
  "Crbindlist" not resolved from current namespace (data.table)

Enter a frame number, or 0 to exit   

1: source("~/work/rstatistics/bug_data.table.R")
2: withVisible(eval(ei, envir))
3: eval(ei, envir)
4: eval(expr, envir, enclos)
5: bug_data.table.R#26: rbind(aucs, myaucs)
6: rbind(deparse.level, ...)
7: <text>#1: data.table::.rbind.data.table(...)
8: rbindlist(l, use.names, fill, idcol)

This happens after loading a 15Mb file. Source code+ file available on request.

**Comment by arunsrinivasan** [comment]
Pushed a fix. Please write back if it's still not fixed.

**Comment by lkettle** [comment]
I am not sure if this is correct procedure to add to this topic.  I get this error trying to make a treemap in R.

Here is my code and error.
![r problem](https://user-images.githubusercontent.com/14791604/33160022-014191d6-cfe7-11e7-9095-6f7ba782c465.png)

**Comment by lkettle** [comment]
The boxplot is the previous plot.  I am trying to match the colors in my treemap so all my plots have same colors for each group.

**Comment by lkettle** [comment]
I tried command
debugonce(data.table:::print.data.table)
in the console but nothing happens

**Comment by lkettle** [comment]
never mind, I stopped and started and it worked!

**Comment by jangorecki** [comment]
@lkettle no, it is not correct procedure. Please read [Support](https://github.com/Rdatatable/data.table/wiki/Support) before posting on data.table next time. You can try to contact maintainer of the package that you are using - treemap.
