### ISSUE TITLE
Warning suggestion for setattr 

### ISSUE THREAD

**Issue by ladida771** [Rdatatable/data.table#1468]
We need a warning for setattr function when it uses a "bit" package version within data.table. I happened to accidentaly load "bit" package after "data.table" and all of my scripts started crashing. It took a while to figure out the problem and I bet many users will run into such a problem in the future. Less experiences users will not be able to identify the cause of such a bug.

**Comment by arunsrinivasan** [comment]
When you load the package, there should've been a message that the [data.table] function has been masked. There's nothing much we can do about this, other than to recommend being specific using `data.table::setattr()` in your script/package.

**Comment by jangorecki** [comment]
Some comments from me.
The best practice is to organize your script into package, then you can import particular functions from specific packages using `importFrom` in `NAMESPACE` file. Organizing script into package is also useful for versioning, documentation, unit testing, etc. You can include arbitrary data in `inst` subdirectory, for example *crontab* job definition, or deployment scripts. This is definitely way to go.
Also the messages about the functions being masked by other package goes to `stderr` which should help/alert on such cases to spot them.
