### ISSUE TITLE
Unintuitive output from a rolling join

### ISSUE THREAD

**Issue by DavidArenburg** [Rdatatable/data.table#1469]
When performing a rolling join by different column names, it seems like the first column name is selected by default regardless where the values are coming from. This is very confusing to me. Is this by design? (sorry flying tonight in didn't have time to test on the GH version too)

``` r
library(data.table) # V 1.9.6+
set.seed(123)
DT <- data.table(X = 1:3)
DT2 <- data.table(Y = 3:5, Z = sample(3))
DT[DT2, on = c(X = "Y"), roll = -Inf]
#    X Z <~~~ The column name is X but values are from Y
#1: 3 1
#2: 4 2
#3: 5 3
```

**Comment by ben519** [comment]
This.  I couldn't agree more.  I constantly work around this issue.

**Comment by jangorecki** [comment]
This issue is already covered in the linked one, it is also well explained there.
Current recommendation below. It is unlikely to be changed any time soon, feel free to post your proposal into linked issue.
```r
DT[DT2, .(Y, Z), on = c(X = "Y"), roll = -Inf]
# when column names are overlapping
DT[DT2, .(Y=i.Y, Z=i.Z), on = c(X = "Y"), roll = -Inf]
# now also 'x.' prefix should work the same as 'i.' before
```
