### ISSUE TITLE
display ITime correctly in View(myDT)

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#1472]
I use `View()` to browse large-ish datasets that don't fit nicely in the console, but am in trouble when ITime is involved:

    myDT = data.table(x = as.ITime("10:00:01"))

    myDT       # shows "10:00:01"
    View(myDT) # shows integer 36001 instead of "10:00:01"

I'm not sure if this qualifies as a FR or a bug. Looking at the code for `View()`, I think the real culprit is this C function used in the final line `invisible(.External2(C_dataviewer, x, title))` and I guess it's likely that nothing can be done about it on data.table's end. Too bad `View` is not a generic.

**Comment by jangorecki** [comment]
Put a session info. For me on Ubuntu 14.04 and R 3.2.3 `View(myDT)` invokes external window having expected value `10:00:01`.

**Comment by franknarf1** [comment]
Thanks, Jan! Apparently, I needed R 3.2.3 (having used 3.2.2)
