### ISSUE TITLE
Feature Request: pass columns to function ``merge`` 

### ISSUE THREAD

**Issue by ptoche** [Rdatatable/data.table#1475]
```
# make a data.table
set.seed(1)
dt <- data.table(id = 1:5, x1 = 1:5, x2 = 5:1, x3 = round(runif(5, 1, 5), 0), key = "id")
```

I can merge with quoted column names:

```
merge(dt, dt, by = c("x1", "x2"))
##       id x1 x2 x3
##1:  1  1  5  2
##2:  2  2  4  2
##3:  3  3  3  3
##4:  4  4  2  5
##5:  5  5  1  2
```

(silly example that was!) but not directly with a vector of columns:

```
merge(dt, dt, by = c(x1, x2))
##Error in merge.data.table(dt, dt, by = c(x1, x2)) : object 'x1' not found
```

The function `subset` accepts both `c(x1, x2)` and `c("x1", "x2")` so why not `merge` ?

**Comment by jangorecki** [comment]
data.table aims to keep reasonable and still convenient consistency with base R functions. Proposed extension would break current `merge.data.table` consistency with `merge.data.frame` without adding additional optional argument to define a scope - as you may have `x1` and `x2` variables defined in parent scope.

**Comment by ptoche** [comment]
Thanks jangorecki. Would you mind showing an example of "where merge is done using variables having overlapping names to columns" to help me understand the problem. Thanks!

**Comment by jangorecki** [comment]
```r
library(data.table)
set.seed(1)
dt = data.table(id = 1:5, x1 = 1:5, x2 = 5:1, x3 = round(runif(5, 1, 5), 0), key = "id")
x1 = "id"
x2 = "x3"
merge(dt, dt, by = c("x1", "x2"))[]
merge(dt, dt, by = c(x1, x2))[]
merge(dt, dt, by = c("x1", "x2"))==merge(dt, dt, by = c(x1, x2))
```

**Comment by ptoche** [comment]
I see, thanks. Yes that's messy.  Couldn't ``merge`` be made to check if the object is a ``data.frame`` or ``data.table`` and act accordingly or would that cause too much confusion to users? In any case, thanks for your reply: I understand now why ``data.table`` functions are inconsistent wrt to quote/unquote.

**Comment by MichaelChirico** [comment]
Same here as on #1474 that the two options seem to be

1) add `with` argument

2) parse `list`s as within the `data.table`'s scope and anything else as in parent scope.

**Comment by jangorecki** [comment]
Closing from the same reasons as described in https://github.com/Rdatatable/data.table/issues/1474#issuecomment-609405378
We don't really need new interface for something that works good and address users needs.
