### ISSUE TITLE
`:=` broken inside functions for data.table loaded from disk that was saved from a list

### ISSUE THREAD

**Issue by jsams** [Rdatatable/data.table#1478]
I THINK this is a minimal working example, but there may be elements that are not required here. I'm pretty sure loading from disk is required for the malfunction though.

 When I create a data.table that was returned by a function that returns a list of objects, and save that data.table to disk, and then load it, and assign a value to it by reference inside another function, that assignment fails. That sounds confusing, but I think a minimal working example works best. But once I assign by reference to the DT, then assignment by reference within other functions works. Here's a minimal working example showing all of this. I'm running data.table 1.9.6 and R 3.2.2 on 64 bit Linux both kubuntu 15.10 and ubuntu 14.04.

```R
gen_broken = function() {
    DT = data.table(x=1:10, y=21:30)
    return(list(DT=DT))
}

broken_ref = function(dt, newvar) {
    dt[, newvar := 31:40, with=F]
}

tmp = tempfile()
DT_list = gen_broken()
DT = DT_list$DT
save(DT, file=tmp)

rm(DT_list, DT)

load(tmp)
class(DT) # 'data.table', 'data.frame'
# address of DT and DT2 are not the same, but should be
# 'z' is not added to DT
DT2 = broken_ref(DT, 'z')
'z' %in% colnames(DT) # FALSE
'z' %in% colnames(DT2) # TRUE
address(DT) == address(DT2) # FALSE
# has nothing to do with assignment
broken_ref(DT, 'z2')
'z2' %in% colnames(DT) # FALSE

# BUT!!
newvar = 'z3'
DT[, newvar := 41:40, with=F]
'z3' %in% colnames(DT) # TRUE

# AND NOW IT WORKS!!
DT3 = broken_ref(DT, 'z4')
'z4' %in% colnames(DT) # TRUE!
address(DT3) == address(DT) # TRUE

```

**Comment by jangorecki** [comment]
This is known behavior, you can read Arun's reply on [SO](http://stackoverflow.com/a/28090267/2490497).

**Comment by arunsrinivasan** [comment]
Thanks for the report. Jan's link is spot on. After loading from disk, use `setDT()` or `alloc.col()`. Clayton has already filed #1017 following that SO post.
