### ISSUE TITLE
data.table sort/filter/aggregate/reshape with htmlwidget

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1480]
FR for htmlwidget that unlocks data.table performance directly from html/js. A [htmlwidget](http://www.htmlwidgets.org/) would consume data.table back-end.
There is a portable package [rpivotTable](https://cran.r-project.org/web/packages/rpivotTable/) htmlwidget, it has a lot more feature, but it is a javascript side processing, and it is slow.
Not only shiny apps would use it, but potentially any web app, or even an ad-hoc browsing aggregates/pivot views.
I don't have enough javascript skills to dev that FR currently.

**Comment by arunsrinivasan** [comment]
I don't know how this is doable. And this is beyond the scope of data.table package.
