### ISSUE TITLE
FR: `expand.grid.data.table`

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1486]
Sometimes it's nice to use `expand.grid`, but it unfortunately returns a `data.frame`, so

    data.table(a = sample(100), b = sample(100))[ , expand.grid(a, b)]

Returns a `data.frame` with too many rows to print.

Shouldn't `data.table` have its own method for doing this that returns a `data.table` directly?

**Comment by franknarf1** [comment]
`CJ(a = sample(100), b = sample(100))`?

**Comment by MichaelChirico** [comment]
@franknarf1 nice, never thought to use `CJ` as a standalone.
