### ISSUE TITLE
More improvements to %between%

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1489]
There are a few other improvements in line for `between`, but a very simple one is increasing the flexibility of `incbounds` to allow values `"upper"` (case: `x > lower & x <= upper`) and `"lower"` (case: `x >= lower & x < upper`).

(edit: just noticed in the comment in [between.R](https://github.com/Rdatatable/data.table/blob/master/R/between.R) that there's a clunky suggested workaround -- `# If we want non inclusive bounds with %between%, just +1 to the left, and -1 to the right (assuming integers)` -- of course this doesn't work if `x` is continuous)

I also think it's more natural for `between` to take a vector as a second argument (so we can pass stuff of the form `between(x, range(y), FALSE)`, but this would break existing code. Perhaps different infixes for different defaults? `%bw%` is default, `%bwx%` is `incbounds = FALSE` (e**x**clusive), `%bwu%` is `incbounds = "upper"`, and `%bwl%` is `incbounds == "lower"`.

Also, the documentation doesn't make clear that the default for `between` is to set `incbounds = TRUE` (though this should be clear through the example, it makes sense to write it out as well). It also doesn't include an example usage of `%between%` in the Usage section.

Proposed update:

```
between <- function(x, lower, upper, incbounds = TRUE)
{
  if(isTRUE(incbounds)) x >= lower & x <= upper
  elseif (incbounds == FALSE) x > lower & x < upper
  elseif (incbounds == "upper") x > lower & x <= upper
  elseif (incbounds == "lower") x >= lower & x < upper
  else stop("Valid arguments for incbounds are TRUE, FALSE, "upper", and "lower")
}
```

Or a mite more efficiently:

```
between <- function(x, lower, upper, incbounds = TRUE)
{
  if (!incbounds %in% list(TRUE, FALSE, "upper", "lower")) stop('Valid arguments for incbounds are TRUE, FALSE, "upper", and "lower"')
  (if ((inct <- incbounds == TRUE) | incbounds == "lower") `>=` else `>`)(x, lower) &
    (if (inct | incbounds == "upper") `<=` else `<`)(x, upper)
}
```

**Comment by arunsrinivasan** [comment]
This seems unnecessary. I'll for one never remember all these aliases. `between()` seems to cover most common 2 cases (>= & <=, > & <).

**Comment by MichaelChirico** [comment]
@arunsrinivasan yea, I've been meaning to revise this PR as I've soured on all the suggested infixes myself (currently out of the country).

I still think `incbounds` would benefit from the suggested expansion (and I perceive the cost as minimal), no?

**Comment by MichaelChirico** [comment]
Closing until further notice.
