### ISSUE TITLE
do.call(rbind, datatablelist ) does not work when list contains data.table element named "fill"

### ISSUE THREAD

**Issue by abharti5** [Rdatatable/data.table#1491]
mydata is list of data.tables. if one of the elements is fill, do.call(rbind,mydata) reports an error.

> mydata = list( order=as.data.table(list(a=1,b=2)) , fill=as.data.table(list(a=1,b=2)))

> do.call(rbind,mydata)
Error in rbindlist(l, use.names, fill, idcol) : 
  fill should be TRUE or FALSE

Here is the version info:
> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-pc-linux-gnu (64-bit)
[1] data.table_1.9.6

**Comment by MichaelChirico** [comment]
This is not a `data.table` problem, but an R problem, as far as I can tell.

`fill` is an argument to `rbindlist`, so your `data.table` is being sent as an argument to that.

I can't see a way around this besides 1) not using `do.call` or 2) renaming your `data.table` (`fill_dt`, perhaps?).

**Comment by abharti5** [comment]
Thanks Michael.  I thought this could be data.table issue, as If I replace the data.table with data.frame, do.call gives the expected answer.  I get it now. Thanks for the clarification. I will use rbindlist instead which works.
