### ISSUE TITLE
[Request] head.data.table print columns fit to screen width

### ISSUE THREAD

**Issue by nverno** [Rdatatable/data.table#1497]
Would it be useful for head.data.table to have an option to print only the head of columns that fit the screen width, and summarise the rest?  I was imagining something like the printed output from the head of a `tbl_df` in dplyr.  I think it is nice for tables with many columns.

**Comment by MichaelChirico** [comment]
@nverno could you add an example from `dplyr` that exemplifies what you have in mind?

**Comment by arunsrinivasan** [comment]
@MichaelChirico it only prints a few columns and displays the others as *variables not shown*. I'm not entirely sure how it's helpful.. but shouldn't hurt to add an argument...

```r
require(data.table)
dt = setDT(lapply(1:100, function(x) 1:3))
dt
dplyr::tbl_dt(dt)
```
