### ISSUE TITLE
Error when subsetting  itime columns on  equal ("==")

### ISSUE THREAD

**Issue by dougedmunds** [Rdatatable/data.table#1501]
data.table dt contains an ITime column.  It will subset on <, >, <=, >=, and !=, but it generates an error on ==

    > str(dt)
    Classes ‘data.table’ and 'data.frame':	35697 obs. of  5 variables:
     $ Time : chr  "2016/01/13 00:01:31" "2016/01/13 00:01:58" "2016/01/13 00:02:20" "2016/01/13 00:02:20" ...
     $ Close: num  4.79 4.79 4.79 4.79 4.79 ...
     $ Vol  : num  1 1 2 1 1 1 1 1 1 1 ...
     $ idate: IDate, format: "2016-01-13" "2016-01-13" "2016-01-13" ...
     $ itime:Class 'ITime'  int [1:35697] 91 118 140 140 140 147 147 147 147 195 ...
     - attr(*, ".internal.selfref")=<externalptr> 
     - attr(*, "sorted")= chr "itime"

For example, subsetting on ">=" works fine:

    > dt[itime >= as.ITime("23:50:00"),itime]
    [1] "23:50:37" "23:57:39" "23:57:39" "23:57:39" "23:57:39" "23:57:39" "23:57:39" "23:57:39"
    [9] "23:57:39" "23:57:39" "23:57:39" "23:57:39" "23:57:39" "23:57:39" "23:57:39" "23:59:10"
    [17] "23:59:10" "23:59:10" "23:59:10" "23:59:10"

Error generated with  ==

    > dt[itime == as.ITime("23:50:00"),itime]
    Error in alloc.col(x) : 
      Internal error: length of names (0) is not length of dt (1)

**Comment by arunsrinivasan** [comment]
data.table version and reproducible example please.

**Comment by dougedmunds** [comment]
Please close this issue.  If/when I encounter it again, I will
document it. Thank you.
