### ISSUE TITLE
data.table devel snapshots as drat repository in gh-pages

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1505]
I would like to have an easier way to install devel version of data.table.
I have no problem with installing at all, but in some cases it would be useful.
I have data.table devel snapshots in my fork of data.table and it works perfectly fine, but when publishing a blog post I would prefer to use devel data.table provided by Rdatatable, not jangorecki.
I need devel cause I want to benchmark some of the features added in devel, like `dt[, .SD[val], grp]`.

Full recipe for creating drat data.table with devel snapshot as source package, starting in data.table git dir, and requires `drat` package installed to create repo.
```sh
git checkout master # ensure you are on master
git status # ensure no uncommitted changes and latest commit should already pass the CI tests
cd ..
R CMD build data.table --no-build-vignettes --no-manual
cd data.table
git checkout --orphan gh-pages
git rm -rf .
rm '.gitignore'
cd ..
Rscript -e 'drat::insertPackage("data.table_1.9.7.tar.gz","data.table")'
cd data.table
git status
git add src
git status
git commit -m 'latest devel snapshot'
git push origin gh-pages
```
and a way to use it
```r
# installing development snapshot having all deps already
install.packages("data.table", repos = "https://rdatatable.github.io/data.table")

# installing development snapshot and all deps
install.packages("data.table", repos = paste0("https://", c("rdatatable.github.io/data.table", "cran.rstudio.com")))

# another ways
options(repos = c(getOption("repos"), "https://rdatatable.github.io/data.table"))
install.packages("data.table")
# or update all pkgs including data.table
update.packages()
```

**Comment by jangorecki** [comment]
Not yet resolved. [Build](https://travis-ci.org/Rdatatable/data.table/builds/112172795) failed to push to `gh-pages` due to
```
deploy.sh: line 18: GH_TOKEN: unbound variable
```
Most likely related to organization account as it was working on user account.

**Comment by MichaelChirico** [comment]
@jangorecki  very cool, thanks. Should we update the [how to install](https://github.com/Rdatatable/data.table/wiki/Installation) yet?

**Comment by jangorecki** [comment]
@MichaelChirico soon, I want to make better README.md in gh-pages branch. Any feedback on current setup welcome.

**Comment by jangorecki** [comment]
@MichaelChirico already done.

Just for the record if anyone would like to reproduce travis+drat on own (non-Rdatatable) account, the following needs to be adjusted:
- `.travis.yml`
  - generate own GH token, encrypt according to drat + travis vignette, put to `secure` env
  - change account name in `test $TRAVIS_REPO_SLUG == "Rdatatable/data.table"`
  - remove `test $TRAVIS_PULL_REQUEST == "false"` to try also on PR
  - adjust `test $TRAVIS_BRANCH == "master"` as you probably don't want to change your master to keep sync with upstream master
- `deploy.sh`
  - change account name in `git remote add upstream "https://$GH_TOKEN@github.com/Rdatatable/data.table.git"`

**Comment by MichaelChirico** [comment]
@jangorecki just came across an issue potentially related to this.

Trying to use `data.table` in a Shiny app, but I'm getting the error referenced here:

https://github.com/rstudio/shinyapps/issues/194

IIUC we need to add a `"Repository: "` line to the `DESCRIPTION` file to fix this.

PS your name should be on the `"Author: "` line by now!

**Comment by jangorecki** [comment]
@MichaelChirico isn't that issue related to shiny/shinyapps/packart? I don't see `Repository` mentioned in [r-release/R-exts](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) or [r-devel/R-exts](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html).
