### ISSUE TITLE
Test 1105 system call failed: Cannot allocate memory

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1506]
I'm trying to setup CI for data.table on gitlab, it is currently failing on the test 1105. I use Ubuntu 14 image. Is this error in some way essential for that test? if not I could tryCatch just this one error and suppress in tests.
```
 Running ‘tests.R’ [127s/131s]
 ERROR
Running the tests in ‘tests/tests.R’ failed.
Last 13 lines of output:
  
      colsplit, melt, recast
  
  Don't know how to automatically pick scale for object of type ITime. Defaulting to continuous
  Don't know how to automatically pick scale for object of type ITime. Defaulting to continuous
  Test 1105 Error in system(paste("(", input, ") > ", tt, sep = "")) : 
    (converted from warning) system call failed: Cannot allocate memory
  Tests 1441-1444 not run. If required install the 'fr_FR.utf8' locale.
  
  Error in eval(expr, envir, enclos) : 
    1 error out of 4544 (lastID=1590.3, endian=little, sizeof(long double)==16) in inst/tests/tests.Rraw on Sun Jan 24 01:47:10 2016. Search tests.Rraw for test number 1105.
  Calls: test.data.table -> sys.source -> eval -> eval
  Execution halted
```
[test 1105](https://github.com/Rdatatable/data.table/blob/c2c8387f51593765bfff3b78e0c757f63e2eab18/inst/tests/tests.Rraw#L3356):
```r
x1 <- data.table(a = c(1:5), b = c(1:5))
f <- tempfile()
write.csv(x1, f, row.names = FALSE)
if (.Platform$OS.type == "unix") {
    test(1105, x1[a != 3], fread(paste('grep -v 3 ', f, sep="")))
}
```
[build](https://gitlab.com/jangorecki/data.table/builds/603078)

**Comment by jangorecki** [comment]
This hits me on local machine so it is not really gitlab related. In my case I had some other apps open. Just to clarify, this tests reads 4 rows data.table, what can be problem is lack of memory for `grep` command to start.

**Comment by mattdowle** [comment]
@jangorecki  I don't see how it's anything to do with these tests.  Earlier tests or whatever have gobbled the ram -- the problem is earlier. Causing there not be enough ram for even these tiny tests. Whether these tests run or not is nothing to do with it, iiuc.
