### ISSUE TITLE
Secondary key causes wrong results

### ISSUE THREAD

**Issue by aushev** [Rdatatable/data.table#1507]
(originally [asked at SO](http://stackoverflow.com/questions/34983209/problems-with-secondary-key-of-data-table))
```
myDT <- data.table(ID=c('A','B','B'), val=c('check','check','a')) ; 
myDT[val == "check"] ; 
myDT[, val := ifelse(.N>1, '2', '1'), by = ID] ; 
#    ID val
# 1:  A   1
# 2:  B   2
# 3:  B   2
myDT[val=='2']
#    ID val
# 1:  B   2
```
`val=='2'` is expected to give records 2 and 3 but only record 2 is found. Removing secondary key restores normal behavior:
```
set2key(myDT, NULL)
myDT[val=='2']
#    ID val
# 1:  B   2
# 2:  B   2
```

**Comment by arunsrinivasan** [comment]
Thanks, buy dup of #1479. If not, please write back.
