### ISSUE TITLE
assigning new columns in data.table prints the data.table when the lme4 package is loaded

### ISSUE THREAD

**Issue by ashinm** [Rdatatable/data.table#1509]
When I try to assign a new column in an existing data.table it prints the entire data.table if 'lme4' package is loaded. Here are my sessionInfo and the steps I tried

> library('data.table')
data.table 1.9.7  For help type ?data.table or https://github.com/Rdatatable/data.table/wiki
The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.7

loaded via a namespace (and not attached):
[1] chron_2.3-45

> a = data.table(1)
> a[,v := 2] #does not print anything

> library(lme4)
Loading required package: Matrix

Attaching package: ‘Matrix’

The following objects are masked from ‘package:base’:

    crossprod, tcrossprod

Loading required package: Rcpp
> a[,v := 2] # prints the data.table
   V1 v
1:  1 2

**Comment by jangorecki** [comment]
duplicated of #1277

**Comment by ashinm** [comment]
Thanks Jan.
