### ISSUE TITLE
Cannot use i.field and by= in same data.table expression

### ISSUE THREAD

**Issue by sz-cgt** [Rdatatable/data.table#1519]
The following two expressions fail when `by=` is used

    DT1[DT2,sum(v1*w1),by=k1]    # fails complaining about being unable to find w1
    DT1[DT2,sum(v1*i.w1),by=k1]  # also fails with the same error

This works 

    DT1[DT2][,sum(v1*w1),by=k1]  # works

but I'm not clear on the effect of very large tables on memory using this method.

See http://stackoverflow.com/questions/35193626/cannot-use-i-field-and-by-in-same-data-table-expression for details

**Comment by arunsrinivasan** [comment]
dup of https://github.com/Rdatatable/data.table/issues/733
