### ISSUE TITLE
A few improvements to between.Rd

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1521]
- [ ] Need to uncomment `%`.
 - [ ] Need to mention the default value of `incbounds` is `TRUE` for the `x %between% y` infix usage.
 - [ ] Clarifying valid `x` `class`es (since `between` doesn't work with, e.g., `complex` or `factor` vectors)

**Comment by MichaelChirico** [comment]
Hey @arunsrinivasan I think you got the number wrong on this latest commit. This issue doesn't have to do with `NA`s in `i`....

**Comment by arunsrinivasan** [comment]
Yes.. it's #1252. Made a note there..
