### ISSUE TITLE
Plot series inside data.table call when grouping

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1524]
Not sure if it is a bug...
Please follow output from below code chunks.

This seems to be perfectly doable for a basic case like this:
```r
library(data.table)
dt = data.table(x = rep(1:4,2), y = c(1:4,2:5), grp = c(rep("a",4),rep("b",4)))
plot(x=NA, y=NA, xlim=range(dt$x), ylim=range(dt$y), xlab="x", ylab="y")
dt[, lines(x = x, y = y, col = .GRP+1L), .(grp)]
```

But doesn't work for a little more complex data, still the same structure:
```r
dt = data.table(
    x = c(44138L, 44138L, 44137L, 44138L, 105465L, 105464L, 105464L, 105464L, 135865L, 135866L, 135865L, 135865L, 172875L, 172876L, 172875L, 172876L, 223145L, 223144L, 223144L, 223145L),
    y = c(0.00446385, 0.004606568, 0.004254985, 0.004632678, 0.01447159, 0.01379085, 0.01400047, 0.01407437, 0.01037709, 0.01443538, 0.007433852, 0.01499026, 0.0204805, 0.02010754, 0.02207507, 0.0192663, 0.01804157, 0.03229697, 0.01821333, 0.01634321),
    grp = c("rnode13", "rnode12", "rnode14", "rnode11", "rnode11", "rnode14", "rnode12", "rnode13", "rnode12", "rnode11", "rnode13", "rnode14", "rnode13", "rnode12", "rnode14", "rnode11", "rnode11", "rnode14", "rnode13", "rnode12")
)
plot(x=NA, y=NA, xlim=range(dt$x), ylim=range(dt$y), xlab="x", ylab="y")
dt[, lines(x = x, y = y, col = .GRP+1L), .(grp)]
```

While the `lapply` workaround plot series well:
```r
plot(x=NA, y=NA, xlim=range(dt$x), ylim=range(dt$y), xlab="x", ylab="y")
gg = unique(dt$grp)
lapply(seq_along(gg), function(i) dt[grp==gg[i], lines(x = x, y = y, col = i+1L)])
```
Ubuntu + R 3.2.3 + 1.9.7.

**Comment by MichaelChirico** [comment]
@jangorecki strange, something going on with devices.

I get the correct plot if I put the output to a device, e.g.

```
dt = data.table(
    x = c(44138L, 44138L, 44137L, 44138L, 105465L, 105464L, 105464L, 105464L, 135865L, 135866L, 135865L, 135865L, 172875L, 172876L, 172875L, 172876L, 223145L, 223144L, 223144L, 223145L),
    y = c(0.00446385, 0.004606568, 0.004254985, 0.004632678, 0.01447159, 0.01379085, 0.01400047, 0.01407437, 0.01037709, 0.01443538, 0.007433852, 0.01499026, 0.0204805, 0.02010754, 0.02207507, 0.0192663, 0.01804157, 0.03229697, 0.01821333, 0.01634321),
    grp = c("rnode13", "rnode12", "rnode14", "rnode11", "rnode11", "rnode14", "rnode12", "rnode13", "rnode12", "rnode11", "rnode13", "rnode14", "rnode13", "rnode12", "rnode14", "rnode11", "rnode11", "rnode14", "rnode13", "rnode12")
)

pdf("~/Desktop/test.pdf")
plot(x=NA, y=NA, xlim=range(dt$x), ylim=range(dt$y), xlab="x", ylab="y")
dt[, lines(x = x, y = y, col = .GRP+1L), .(grp)]
dev.off()
```

Not sure what's causing the issue, gonna explore a little more and report back.

**Comment by arunsrinivasan** [comment]
Perhaps you're using RStudio? Reminds me of [this SO post](http://stackoverflow.com/a/27509129/559784)..

I've no issues with R in terminal.

**Comment by arunsrinivasan** [comment]
Ping @Kevinushey. In case you've some thoughts..

**Comment by jangorecki** [comment]
@arunsrinivasan yeah, non reproducible in R console.

**Comment by kevinushey** [comment]
Thanks for the heads up. It seems like RStudio needs to do something to ensure that data references (ie, in `data.table`s case, to `.SD`) are retained; does that sound correct?

**Comment by arunsrinivasan** [comment]
Very likely. Check out the SO link to see if that sheds more light.

**Comment by MichaelChirico** [comment]
Came up again [here](http://stackoverflow.com/questions/36413514/strange-error-plotting-by-group).

I also posted an issue on [RStudio support](https://support.rstudio.com/hc/en-us/signin?return_to=https%3A%2F%2Fsupport.rstudio.com%2Fhc%2Fen-us%2Fcommunity%2Fposts%2F208778048-RStudioGD-has-some-bug-when-used-within-j-of-data-table-also-dplyr-)

**Comment by MichaelChirico** [comment]
This came up again:

```
DT <- 
  structure(list(Gender = c("Female", "Female", "Female", "Female", "Female", "Female", 
                            "Female", "Female", "Female", "Male", "Male", "Male"), 
                 height = c(5.33, 5.33, 5.5, 5.08, 5.42, 
                            5.75, 5.02, 5.17, 5.58, 6.17, 6, 6.17), 
                 hairlength = c(15L, 14L, 14L, 14L, 16L, 18L,
                                    20L, 14L, 16L, 2L, 4L, 2L)), 
            row.names = c(NA, -12L), class = c("data.table", "data.frame"), 
            .Names = c("Gender", "height", "hairlength"))

DT[ , plot(NULL, xlim = range(hairlength, na.rm = TRUE),
                 ylim = range(height, na.rm = TRUE),
                 xlab = "Hair Length", ylab = "Height")]
DT[ , points(hairlength, height, col = .GRP), by = Gender]
```

Gives in RStudio

![screenshot from 2016-08-30 18 30 22](https://cloud.githubusercontent.com/assets/7606389/18109538/e6d5d190-6edf-11e6-8789-64f912acdd98.png)

But from the command line or from saving with `png`, we get the expected output:

![test2](https://cloud.githubusercontent.com/assets/7606389/18109571/1f798028-6ee0-11e6-9787-3739a77b9aeb.png)

(still no movement over on the RStudio issue... leaving this issue closed, just documenting more examples of the bug)

**Comment by arunsrinivasan** [comment]
Perhaps add a FAQ entry and then close?

**Comment by MichaelChirico** [comment]
it's already closed. just adding this for my reference if/when rstudio
fixes it.

FAQ entry makes sense.

also should update my SO Q "plotting by group in data.table"
