### ISSUE TITLE
High precision addition is not associative?

### ISSUE THREAD

**Issue by jeffkeller87** [Rdatatable/data.table#1527]
This possible bug had me up all night!
I attached an environment ([myEnv.zip](https://github.com/Rdatatable/data.table/files/122182/myEnv.zip)) with three variables and a one-row data.table with two variables.

The following calculations produce different results when the only difference is the order of terms:

    myDT[, v1 := X*A + Y*B + Z]
    myDT[, v2 := Z + X*A + Y*B]
    myDT[, identical(v1, v2)] # is FALSE

Differences are small, but I was expecting v1 and v2 to be identical.

**Comment by arunsrinivasan** [comment]
This seems to be a case of floating point limitations.. and nothing to do with data.table at a first glance. You'd get the same without data tables as well. 

```r
ans1 = with(myDT, X*A + Y*B + Z)
ans2 = with(myDT, Z + X*A + Y*B)
identical(ans1, ans2)
all.equal(ans1, ans2) # should be TRUE
```

[This article might be of use](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) (if you've not already come across it.
