### ISSUE TITLE
data.table  does not matrix values columns

### ISSUE THREAD

**Issue by ajosep6** [Rdatatable/data.table#1535]
Hi there,

data.table does not seem to allow the columns to be matrices, unlike data.frame. Having the columns as matrices can very useful especially when dealing with splines (or any other basis vectors) in a regression context. The example below elucidates my point. data.table simply truncates the matrix taking the first 2 elements, instead of storing the whole matrix like in a data.frame.

Let me know if this is fixable
 
>DF = data.frame(a = c(1,1))
>mat = matrix(c(1,2,3,4), nrow = 2)
>DF$matcol = mat
>str(DF)
 'data.frame':	2 obs. of  2 variables:
  $ a  : num  1 1
  $ mat: num [1:2, 1:2] 1 2 3 4

>DT = data.table(a = c(1,1))
>DT[, matcol := mat]
 Warning messages:
 1: In `[.data.table`(DT, , `:=`(matcol, mat)) :
  2 column matrix RHS of := will be treated as one vector
 2: In `[.data.table`(DT, , `:=`(matcol, mat)) :
   Supplied 4 items to be assigned to 2 items of column 'matcol' (2 unused)
> str(DT)
 Classes ‘data.table’ and 'data.frame':	2 obs. of  2 variables:
  $ a     : num  1 1
  $ matcol: num  1 2
  - attr(*, ".internal.selfref")=<externalptr>

**Comment by shrektan** [comment]
I think you need to split the matrix to two list first.

**Comment by mrdwab** [comment]
@ajosep6 , Can you describe a use case for this? You've mentioned "Having the columns as matrices can very useful especially when dealing with splines (or any other basis vectors) in a regression context". If you can show what you're trying to achieve, there might be a better "data.table" way.

A list as a column can make sense since the list items may be of different lengths (non-rectangular), but I don't see why you wouldn't just be able to use the output from `cbind(DT, mat)` in conjunction with `.SD`. 

The other alternative if you need row-wise vectors would be to split the matrix into a list, perhaps with something like this: `DT[, matlist := as.list(lapply(1:nrow(mat), function(x) mat[x, ]))][]`. It's not the same as your matrix as a column approach, but without a clearer example of what you're trying to solve, I'm not sure which approach would be a better suggestion.

**Comment by ajosep6** [comment]
Here's an example that hopefully makes things clear. The data.frame DF below contains two elements : A column vector y, and a matrix mat. If you do head(DF) the columns of of the matrix appear as mat.1, mat.2, ...., mat.10. However, if you want to fit a linear model of y versus all the columns of mat you just need to do lm(y ~ mat) instead of the more complicated lm(y ~ mat.1 + mat.2 + ... + mat.10). Let me know what you think.

> mat = matrix(rnorm(100*10), nrow = 100)
> y = rnorm(100, 1)
> DF = data.frame(y = y)
> DF$mat = mat
> head(DF)
          y        mat.1        mat.2        mat.3        mat.4        mat.5
1 1.2143509 -0.881349131  1.074246761  0.499579090 -1.047490374  0.032519248
2 1.0966679 -0.023563327 -0.172730434  0.005178194 -0.170606182 -0.835357989
3 0.5776981  1.114187132 -0.657022928  1.164421208  0.622387254 -0.705441201
4 1.8128953  0.302934443  0.338816687 -0.889763326 -0.095762380 -0.198618402
5 0.6448786  0.372460571 -1.065882287  1.795278612  1.789820786  0.402635932
6 1.2384363  0.005024471 -0.574642775  1.880154165  0.203888166  0.578237148
         mat.6        mat.7        mat.8        mat.9       mat.10
1 -0.532747665  0.249793841 -0.100084674 -0.502407701 -1.260064868
2  1.117022353  2.149332544 -0.336424803 -0.137276419  0.211477540
3  0.767845627 -2.122699087  1.081228706  0.204697436 -0.619255297
4 -0.055607393  0.790521184  0.727712085 -1.230266726  1.764792422
5 -2.072085207 -1.820700399  1.228984904 -0.064375031 -0.508499922
6 -0.314053186  0.573876017  1.730942162 -1.652396564 -0.556324115
> lm(y ~ mat)

Call:
lm(formula = y ~ mat)

Coefficients:
(Intercept)         mat1         mat2         mat3         mat4         mat5  
   0.984234    -0.092668    -0.166295     0.086720     0.120805    -0.016052  
       mat6         mat7         mat8         mat9        mat10  
   0.009384     0.041582    -0.004408    -0.027783     0.217170

**Comment by jangorecki** [comment]
I think you could try to format your comments better.
Use triple backtick `` ` `` for code blocks open and close.
Also make the output of R session to start with comment character `#` for full copy-paste reproducibility to limit number of misconceptions.

**Comment by mrdwab** [comment]
@ajosep6 I don't see how a matrix column is a big advantage here. You should be making a better use of the formula in `lm` instead:

```r
set.seed(1)
mat <- matrix(rnorm(100*10), nrow = 100)
y <- rnorm(100, 1)
DF <- data.frame(y = y)
DF$mat <- mat
x1 <- lm(y ~ mat, data = DF)

DT <- data.table(y)
DT <- cbind(DT, mat)
x2 <- lm(y ~ ., data = DT)

x1
# Call:
# lm(formula = y ~ mat, data = DF)
# 
# Coefficients:
# (Intercept)         mat1         mat2         mat3         mat4  
#    1.008444    -0.169751    -0.125989    -0.019528     0.007749  
#        mat5         mat6         mat7         mat8         mat9  
#    0.040811    -0.036582     0.019733     0.055781    -0.120640  
#       mat10  
#    0.060751  

x2
# Call:
# lm(formula = y ~ ., data = DT)
# 
# Coefficients:
# (Intercept)           V1           V2           V3           V4  
#    1.008444    -0.169751    -0.125989    -0.019528     0.007749  
#          V5           V6           V7           V8           V9  
#    0.040811    -0.036582     0.019733     0.055781    -0.120640  
#         V10  
#    0.060751  
```

**Comment by arunsrinivasan** [comment]
`LHS := RHS` form requires `RHS` to be a *list of values* and `LHS` to be a character vector of column names. You'll have to wrap the matrix with `as.data.table()`, and provide all the column names on `LHS`. See the Reference Semantics vignette for usage.
