### ISSUE TITLE
 Error in chmatch("data.frame", tt) :    Internal error: savetl_init checks failed (0 100 0x7fe2cb52d5d0 0x7fe2cb511010).

### ISSUE THREAD

**Issue by LoesClephas** [Rdatatable/data.table#1537]
Quite anoying. Suddenly get this error. Any ideas how to solve?

**Comment by LoesClephas** [comment]
Easy example: 

> foutentabel <- data.table()
> foutentabel <- foutentabel[,list(Bestand="",Fout="")]
Error in mult %chin% c("first", "last", "all") : 
  Internal error: savetl_init checks failed (0 100 0x7fe2cb52d5d0 0x7fe2cb511010). Please report to datatable-help.

**Comment by MichaelChirico** [comment]
That line produces no error for me (latest devel version). What version are you working on? If you're on devel, and have R up to date, please post `sessionInfo()`.

**Comment by LoesClephas** [comment]
version 1.9.2. Latest version.

2016-02-18 16:55 GMT+01:00 Michael Chirico <notifications@github.com>:

> That line produces no error for me (latest devel version). What version
> are you working on? If you're on devel, and have R up to date, please post
> sessionInfo().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rdatatable/data.table/issues/1537#issuecomment-185788189>
> .
>



-- 
___________________________
ir. Loes Clephas
Vreelandgroep Organisatie-adviseurs

T: 035-5423922
M: 06-83440388
E: clephas@vreelandgroep.nl

Soestdijkseweg Zuid 224
3721 AJ  Bilthoven
Postbus 116
3720 AC Bilthoven
KvK-nr 320 86 880

<https://www.youtube.com/watch?v=bjzVSoZvA7I>
______________________________

**Comment by MichaelChirico** [comment]
I'm on 1.9.7, and the latest CRAN version is 1.9.6. Do you have the ability to update?

**Comment by LoesClephas** [comment]
I have the same problem with 1.9.6. Running on an IOs system btw

2016-02-18 16:59 GMT+01:00 Michael Chirico <notifications@github.com>:

> I'm on 1.9.7, and the latest CRAN version is 1.9.6. Do you have the
> ability to update?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rdatatable/data.table/issues/1537#issuecomment-185790307>
> .
>



-- 
___________________________
ir. Loes Clephas
Vreelandgroep Organisatie-adviseurs

T: 035-5423922
M: 06-83440388
E: clephas@vreelandgroep.nl

Soestdijkseweg Zuid 224
3721 AJ  Bilthoven
Postbus 116
3720 AC Bilthoven
KvK-nr 320 86 880

<https://www.youtube.com/watch?v=bjzVSoZvA7I>
______________________________

**Comment by arunsrinivasan** [comment]
I am not able to reproduce either (tested on El Capitan 10.11.3, Windows 10 and Ubuntu Linux 14.04 LTS). 

Please try removing your current installation using `remove.packages("data.table")` and then try running the code again after reinstalling.
