### ISSUE TITLE
Error in bmerge.c on dcast() due to missing support of long vectors.

### ISSUE THREAD

**Issue by Vinschni** [Rdatatable/data.table#1541]
Using dcast on a big data.table (400 Million rows) and 3 columns causes following error, which in my eyes is systematic:
<img width="416" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/340731/13250951/7a25e64e-da2d-11e5-87ef-e3402a76ca17.PNG">

**Comment by arunsrinivasan** [comment]
It seems like your data results in creating more than 2 billion rows in the process of converting to wide form. It's hard to do much without a reproducible example. Please read [Support](https://github.com/Rdatatable/data.table/wiki/Support).
