### ISSUE TITLE
setnames on data.frames

### ISSUE THREAD

**Issue by jrounds** [Rdatatable/data.table#1542]
I could this as an expected side effect of data.table, but perhaps one that is not very "R" like and thus dangerous.

```
library(data.table)
l = list()
l$df = data.frame(x=1, y=2)
df2 = l$df
setnames(df2, "x", "whatwhat")
> l;
$df
  whatwhat y
1        1 2
```

Basically using just data.frames with setnames will change by reference the colnames in the data.frame you would entirely expect to have copied in R.  I am sure the authors of the package understand better than I the way that promises evaluate, but it was a bug inducing gotcha.  I thought I would be safe because it wasn't an actual data.table that was assigned prior to calling setnames.

Please close if you have to file this under an unfortunate side effect of how data.table efficiently setnames without copying.

**Comment by arunsrinivasan** [comment]
It's intended behaviour. See the first paragraph in `?setnames`.

**Comment by jangorecki** [comment]
@jrounds if you want to set names with copy use `colnames<-` from the base R.

**Comment by jrounds** [comment]
I wanted colnames(DF)[colnames(DF) == "x"] = "y"  but setnames was
syntactic sugar, and the fact that I was chasing syntactic sugar for a
data.frame without really thinking about data.tables  induced me to fall
alseep.  It caught me off guard when it had the side-effect of changing the
colnames on data.frame inside of a list argument to a function call because
I wasn't thinking "data.table".  Problem solved by copy() though (there is
enough operations inside of the function to justify the copy anyway).
Thanks for considering it. Have a nice day!
