### ISSUE TITLE
Extra 'i' in column names with function returning multiple columns

### ISSUE THREAD

**Issue by yvanrichard** [Rdatatable/data.table#1545]
I am trying to return several statistics for each of several columns in a simple way. I found a way that is a bit convoluted, but the end result is not what I am expecting, with a weird 'i' being introduced in the column names. I suppose this is a bug.

``` r
## Data example
dt <- data.table(x = rep(letters[1:10], each = 10),
                y1 = rep(1:100, 10),
                y2 = 10*rep(1:100, 10),
                y3 = 100*rep(1:100, 10))

## Function returning the mean, minimum and maximum
summfun <- function(x) {
    z <- list(mean = mean(x),
             min = min(x),
             max = max(x))
    names(z) <- paste0(tail(as.character(substitute(x)), 1), '.', names(z))
    return(z)
}
```

That works well with one variable, as ``dt[, summfun(y1), x]`` returns
```
    x y1.mean y1.min y1.max
 1: a     5.5      1     10
 2: b    15.5     11     20
 3: c    25.5     21     30
 4: d    35.5     31     40
 5: e    45.5     41     50
 6: f    55.5     51     60
 7: g    65.5     61     70
 8: h    75.5     71     80
 9: i    85.5     81     90
10: j    95.5     91    100
```

The result needs to be un-listed then re-listed when using several variables:

``` r
## Apply the function on y1 and y2 for each x
dt[, as.list(unlist(lapply(.SD, summfun))), x, .SDcols=c('y1','y2')]
```
It returns that, which is close to what I am expecting but with extra 'i's in the column names:
```
    x y1.i.mean y1.i.min y1.i.max y2.i.mean y2.i.min y2.i.max
 1: a       5.5        1       10        55       10      100
 2: b      15.5       11       20       155      110      200
 3: c      25.5       21       30       255      210      300
 4: d      35.5       31       40       355      310      400
 5: e      45.5       41       50       455      410      500
 6: f      55.5       51       60       555      510      600
 7: g      65.5       61       70       655      610      700
 8: h      75.5       71       80       755      710      800
 9: i      85.5       81       90       855      810      900
10: j      95.5       91      100       955      910     1000
```

I can't explain why these 'i's are introduced. I suppose it's a bug.
But maybe there's a better way of doing this summarising, without having to normalise the data?

Note: I am using data.table version 1.9.6 on R 3.2.3 and Ubuntu 14.04

**Comment by jangorecki** [comment]
This is caused by `substitute` and `lapply`, try below:
```r
lapply(list(a=1,b=2), summfun)
```
`substitute` has very strict use cases, nesting in `lapply` isn't one of them.

**Comment by yvanrichard** [comment]
I'm realising that the code wasn't exactly what I had. Trying to be clear, I simplified too much. I just edited the substitute line in the question.
But thank you, your example is enlightening.  I admit my experience with substitute is rather limited and I could feel that was pretty flimsy. 
Any idea on a better way?

**Comment by jangorecki** [comment]
I think it may be better to take that to stackoverflow instead, you can get a range of answers and pick the one which suits you bests.
In general I would:
- provide name explicitly, in worst case as separate character argument
- avoid `as.list(unlist(` in favour of `dcast`
- build `j` unevaluated expression with a helper function and `eval` at once like `j = eval(build.j(c("y1","y2")))`

**Comment by yvanrichard** [comment]
Indeed, this doesn't seem to be a data.table issue. I'm closing it.
Thank you for your suggestions, though. I am bit disappointed that there isn't a quick concise way. It would be nice if data.table had a method to produce several columns from a single column, similar to my failed attempt...
