### ISSUE TITLE
Bug: get and .SDcols don't mix

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1548]
Curious error:

```
DT <- data.table(A = LETTERS[1:10], B = 11:20)

#as expected
DT[ , get("A")]
DT[ , .SD, .SDcols = "A"]
DT[ , lapply(.SD, identity), .SDcols = "A"]

#but error
DT[ , lapply(names(.SD), get), .SDcols = "A"]
```

> Error in `FUN(X[[i]], ...)` : object `A` not found

Also this is unexpected (shouldn't it just be `"A"`)?:

```
DT[ , print(names(.SD)), .SDcols = "A"]
# [1] "A"
# [1] "A"
```

**Comment by franknarf1** [comment]
The error is not an .SDcols thing, but rather a get+lapply thing as seen by trying `DT[ , lapply(names(.SD), get)] # same error`. `get` needs the right environment:

```
DT[ , lapply(names(.SD), get, env=as.environment(.SD))]
```

But yeah, the second thing is weird. And here's a case where it fails to filter:

```
DT[ , lapply(names(.SD), get, env=as.environment(.SD)), .SDcols="A"]
# shows A and B both
```

(Trying out the \`\`\` thing you mentioned. Handy.)

**Comment by MichaelChirico** [comment]
@franknarf1 gotcha. Strange that `DT[ , lapply("A", function(x) get(x))]` works, though...

**Comment by MichaelChirico** [comment]
The "duplication" of `"A"` is (1) from the `print` (2) `print` of the return value. so nothing odd there.

Frank points out exactly the issue -- we hack `get` in `j` to get the right `env` but here it's not able to do it automatically (I guess since it's nested in `lapply`?), which we can fix by (1) supplying `envir` or (better yet) (2) just using `mget` which is also hacked.
