### ISSUE TITLE
migrate vignettes from Rnw to Rmarkdown

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1551]
- [x] ~~`datatable-intro.Rnw`~~
- [ ] `datatable-faq.Rnw`
  - [ ] include current [github FAQ](https://github.com/Rdatatable/data.table/wiki/FAQ) into vignette

**Comment by arunsrinivasan** [comment]
The `intro` Rnw vignette is already consolidated to Rmd spread across multiple vignettes. 
The FAQ vignette needs to go as a wiki or Rmd (still deciding this internally).

But this issue merged with #944 perhaps to keep it all in one place?

**Comment by MichaelChirico** [comment]
Got it, happy to have made progress towards wherever this ends up.

**Comment by arunsrinivasan** [comment]
@jangorecki to begin with, we can create a vignette and put it on the wiki (and refer to the wiki on SO). We can decide which one is better to keep as we go along.

**Comment by jangorecki** [comment]
@arunsrinivasan lets keep the separate issue just for that - of item on my TO DO list depends on getting rid of Rnw.
What about introduction vignette? Do we keep it? We could drop in favour of your newer vignettes (as discussed somewhere). If we would keep it then it may need some update for recent features.

**Comment by MichaelChirico** [comment]
How about having this intro vignette redubbed as the "Quickstart Guide"?

The other intro vignette is chapter one of the main vignette series, which will eventually be thorough; this could serve as a get-in, get-out vignette for the impatient.

**Comment by arunsrinivasan** [comment]
FAQ needs some content updates / deletion.. Will review them asap.
