### ISSUE TITLE
FR: update / improvement of value.var guessing

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1564]
Please see #1563 for a bit more context.

Basically, the current usage of guessing done by `value.var` strikes me as obsolete:

```
set.seed(1034)
DT <- data.table(id = sample(LETTERS[1:4], 10000, TRUE),
                 v1 = rnorm(10000),
                 v2 = rnorm(10000))

dcast(DT[ , lapply(.SD, quantile, c(.025, .975)), by = id, .SDcols = paste0("v", 1:2)],
      id ~ c("low", "high")[rowid(id)], value.var = paste0("v", 1:2))
```

I have to write `paste0("v", 1:2)` over and over; might it not be better for `value.var` to guess _all_ the columns that are not included in `formula`? The current approach strikes me as a vestige of the days when `value.var` was restricted to accepting one column.

**Comment by arunsrinivasan** [comment]
The default functionality has to be consistent with `reshape2::dcast`.
