### ISSUE TITLE
readRDS subtly changes behavior of `data.table`

### ISSUE THREAD

**Issue by kbrevoort** [Rdatatable/data.table#1567]
Saving a `data.table` using `saveRDS()` appears to alter the functionality of the `data.table`.  Here is a reproducible example (that I have tested on Linux and OSX) in which two data.tables, one created and one read from a file using `readRDS()` are treated differently by the function `f`.  

```
library(data.table)

# Two data.tables:  One created, one read from file
dt <- data.table(a = c(1, 2, 3), b = c(4, 5, 6))
saveRDS(dt, "junk.rds")
dt2 <- readRDS("junk.rds")

# Define a function that adds a new column
f <- function(x) x[, z := a + b]
f(dt)
f(dt2)

# The column is added to dt as expected
print(dt)
#    a b z
# 1: 1 4 5
# 2: 2 5 7
# 3: 3 6 9

# But not to dt2
print(dt2)
#    a b
# 1: 1 4
# 2: 2 5
# 3: 3 6
```
I've found I can work around this by replacing `dt2 <- readRDS('junk.rds')` with `dt2 <- data.table(readRDS('junk.rds'))`, but that's slower.

**Comment by jangorecki** [comment]
This is known behavior, see [FAQ: Reading data.table from RDS or RData file](https://github.com/Rdatatable/data.table/wiki/FAQ#loading-from-rds)

**Comment by kbrevoort** [comment]
Thanks, I missed that (I was searching for "readRDS" instead of just "RDS").
