### ISSUE TITLE
Expand setkey/setkeyv to accept comma-separated key, like data.table

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1577]
From `?setDT` about `key`:

> Character vector of one or more column names which is passed to `setkeyv`. It may be a single comma separated string such as `key="x,y,z"`, or a vector of names such as `key=c("x","y","z")`.

However, functionality for accepting the former type of argument hasn't been specified:

```
DF <- data.frame(a = rep(1:3, each = 2), b = rep(1:2, 3))
setDT(DF, key = "b,a")
```

> Error in `setkeyv(x, key)` : some columns are not in the `data.table`: `b,a`

That's because `setkeyv` isn't built to handle this type of argument.

For consistency, best to make the things `key` arguments can accept consistent

**Comment by arunsrinivasan** [comment]
3. That statement is taken from definition for `key` argument from `?data.table`. And the logic is in `data.table()`. We need to extract that as a separate internal function and use that everywhere so that `key="x,y,z"` works.

**Comment by MichaelChirico** [comment]
@arunsrinivasan OK. For now, for #890, I'm going to write as if `key="x,y,z"` doesn't work, until this issue is filled.

**Comment by arunsrinivasan** [comment]
Um.. I think it's better not to mention that instead of saying it doesn't work.

**Comment by MichaelChirico** [comment]
@arunsrinivasan indeed that's what I meant.

**Comment by MichaelChirico** [comment]
@arunsrinivasan noting from the logic in `data.table` this comment:

> key = strsplit(key,split=",")[[1L]]
> # eg key="A,B"; a syntax only useful in key argument to data.table(), really.

Seems to me the syntax is also useful elsewhere, no?

**Comment by arunsrinivasan** [comment]
Not necessary for setkey/setkeyv

**Comment by DavidArenburg** [comment]
@arunsrinivasan Why isn't that necessary? It seem like very inconsistent behavior to me. Is there anything wrong with having this especially if the fix is so minor?
