### ISSUE TITLE
macros for full set of `[.data.table` arguments

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1579]
Currently there is a *macro* feature that allows to pass quoted language objects to `[.data.table` argument, and evaluate them with simple `eval()`.
```r
library(data.table)
dt = data.table(a=1:4, b=1:2)
qi = quote(a %in% 1:3)
qj = quote(.(n = .N, total.a = sum(a)))
qby = quote(b)
dt[eval(qi), eval(qj), eval(qby)]
#   qby n total.a
#1:   1 2       4
#2:   2 1       2
```
This is awesome feature but it is limited to single argument.

The macro could be extended to handle all the arguments that `[.data.table` can get.
Above example could looks like:
```r
my1 = as.macro(a %in% 1:3, .(n = .N, total.a = sum(a)), b)
dt[~my1]
#   b n total.a
#1: 1 2       4
#2: 2 1       2
```
I've made a draft of it, it could be improved to not call `[` again, but just replace arguments in current scope. It is nice because it can be used for chaining.
Code can be found in https://github.com/Rdatatable/data.table/compare/master...jangorecki:macros
More examples of usage can be found in [macros.R](https://github.com/Rdatatable/data.table/blob/71777d69a02af859ab628f4740d5bd980a0d44fc/R/macros.R#L8) file in *testing* code block.
I would like to hear what you think about such feature.

**Comment by DavidArenburg** [comment]
This looks very nice, though I can't think of a practical use for it.

**Comment by jangorecki** [comment]
Pretty the same as using current *macros* of quoted expression and `eval(.)`, so mostly to not repeat same expressions. Additionally it can result into cleaner code for bigger data.table queries.

**Comment by MichaelChirico** [comment]
@jangorecki I think this could go for some more examples of usage.

It looks great... but I'm with David that it I don't see myself using it. But perhaps you have something in mind that would ease my own coding experience.

Personally, I almost never use `eval`; when I do, I almost exclusively use it in `j`.

On the implementation side, I noticed you didn't name `keyby`, is this just a style difference? Struck me as odd to leave an argument blank.

**Comment by jangorecki** [comment]
If you are not using current macros it is reasonable you probably wouldn't use this proposal.
There are multiple examples in linked file, not sure if you've seen them.

Regarding keyby, any argument, including keyby, can be matched by position, and I often use that fact.

A side effect of such macros can be boost in ability to prepare inputs for `[.data.table` call, something like:
```r
lst = list(j = quote(sum(v2)),
           by = "v1")
class(lst) = "macro"
dt[~lst]
```

**Comment by jangorecki** [comment]
Macros could optionally collect technical measures about the query execution allowing easier code profiling.

**Comment by arunsrinivasan** [comment]
Sorry, I don't see a (strong) use case for this.

**Comment by jangorecki** [comment]
OK, just found an interesting package which could easily populate macros from web browser https://github.com/timelyportfolio/listviewer giving ability to query data.table from browser.
