### ISSUE TITLE
Show progress in Shiny

### ISSUE THREAD

**Issue by nuno-agostinho** [Rdatatable/data.table#1585]
Is it possible to redirect the output of fread to a Shiny progress bar? If not, I'd welcome this feature.

**Comment by jangorecki** [comment]
Did you try `capture.output`? I think it could catches all print but once fread is finished, so not really useful, but worth to try.

**Comment by jangorecki** [comment]
Closing due to no reply for almost a year, feel free to re-open with updated info.
