### ISSUE TITLE
Column names from `fread` with whitespaces

### ISSUE THREAD

**Issue by cronacronis** [Rdatatable/data.table#1587]
In [`fread.c` todo](https://github.com/Rdatatable/data.table/blob/master/src/fread.c#L33), there is a following issue:
`Jim Holtman requested column names be stipped of whitespace. On datatable-help 22 Jan 2014.` it refers to the [message](http://comments.gmane.org/gmane.comp.lang.r.datatable/2326).
I beleive it can be solved easily with something like that, should user expect trailing.
```
TrimLeadingAndTrailing <- function (x) gsub("^(\\s|\\\ufeff)+|\\s+$", "", x)
setnames(dt_, names(dt_), TrimLeadingAndTrailing(names(dt_)))
```

**Comment by MichaelChirico** [comment]
If I'm not mistaken the goal is to do this in C for speed.

**Comment by arunsrinivasan** [comment]
```r
require(data.table)
names(fread('    a  ,  b,c   \n1,2,3\n4,5,6'))
# [1] "a" "b" "c"

names(fread('    a  ,  b,c   \n1,2,3\n4,5,6', strip.white=FALSE))
# [1] "a  "  "b"    "c   "
```
