### ISSUE TITLE
Bug: select in fread causing a stack imbalance

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1593]
Something's up with `select` in `fread`.

```
fl <- "a,b,c\n1,2,3\n4,5,6\n7,8,9"

x <- fread(fl, select = "b")
```
> Warning: stack imbalance in '<-', 2 then 3

On the other hand, either of the following work:

```
x <- fread(fl)

fread(fl, select = "b")
#    b
# 1: 2
# 2: 5
# 3: 8
```

Confirmed that this _doesn't_ cause an issue on 1.9.6. I guess this is related to the [#1445 fix](https://github.com/Rdatatable/data.table/commit/99efe898d6e8a42c73f37f6cc5c3bbb7825cfea5) (especially since I assume this bug comes from C). [Other possible culprit](https://github.com/Rdatatable/data.table/commit/57dbdce71539d9c4c3476fb9f3e9ace933e4cf3e).

This likely made it past `test.data.table()` since there are no tests that actually _assign_ the output of `fread` when using `select` (relevant tests: `1071`-`3`, `1618`).

**Comment by arunsrinivasan** [comment]
Thanks, already noticed that. Just pushed a fix.
