### ISSUE TITLE
Bug: Unable to count by list columns

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1597]
Perhaps this is intentional, but it seems to me a more natural solution to [this](http://stackoverflow.com/questions/36072187/r-item-combinations-group-of-3/) question on SO would be:

```
shoppinglists[ , if (.N>=3) 
  .(triplet = combn(items, 3, simplify=FALSE)), 
  by=consumer][ , .N, by=triplet][order(-N)]
```

But if we try and use the `list` column in `by` we get an error:

> Error in`` `[.data.table`(shoppinglists[, if (.N >= 3) list(triplet = combn(items,`: 
>   The items in the`by`or`keyby`list are length`(3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3)`. Each must be same length as rows in`x`or number of rows returned by`i` (18).

As cryptic as this error is, I think `by` is having trouble identifying unique lists (perhaps this is by design).

Is there no way to do use a `list` column in `by`?

**Comment by franknarf1** [comment]
Yeah, pretty sure it's not supported. You cannot join on list columns either.

**Comment by MichaelChirico** [comment]
I understand support may be difficult / not worthwhile (comparing and indexing lists must be much more time-consuming than comparing vectors)... worth having out there as a FR though!

**Comment by MichaelChirico** [comment]
I'm not sure count-by-list is quite properly defined since list comparison is undefined in R:

```
list(1) == list(1)
```

> Error in list(1) == list(1) : 
  comparison of these types is not implemented

Probably what is intended is to [`unnest`](https://github.com/Rdatatable/data.table/issues/2146) and then count. To close this, we can add a more helpful error message.

**Comment by jangorecki** [comment]
I think we can safely close this issue, as ordering of list column is undefined operation.

**Comment by MichaelChirico** [comment]
for the record, it's possible to `GROUP BY` non-atomic columns (e.g. Presto SQL does this).

_ordering_ is not defined but _distinctness_ can be defined (e.g. `unique.list`) -- IINM they use a hash operation to group.

That said, it would require a pretty big upheaval of our backend (?i think? from sort-then-group to sometimes-sort/sometimes-hash) to accommodate this use case & there doesn't appear to be much demand. So happy to leave closed

**Comment by jan-glx** [comment]
As a (potentially slow) workaround one can hash the elements of the list column, use the hash in `by`/`keyby` and `listcolumn[1]` in `j`:
```
as.data.table(shoppinglists)[ , if (.N>=3) 
    .(triplet = combn(items, 3, simplify=FALSE)), 
    by=consumer][ , .(.N, triplet=triplet[1]), by=.(triplet_hash=sapply(triplet, digest::digest))][order(-N)]
```
