### ISSUE TITLE
Bug in fread?

### ISSUE THREAD

**Issue by jeffwong-nflx** [Rdatatable/data.table#1599]
If I have a text file that looks like

col1
0x0
0x0

fread will interpret this as the number 0. I think this is because fread thinks it is a number in hexadecimal.

If I have col1
0x0
0x0
10x10

fread correctly interprets it as a string

**Comment by franknarf1** [comment]
`fread("col1\n0x0\n0x0", colClasses="string")` works for me.

**Comment by jangorecki** [comment]
@jeffwong-nflx please provide reproducible example

**Comment by arunsrinivasan** [comment]
`read.table` does the same:

```r
read.table(text="col1\n0x0\n0xAE", header=TRUE)
#   col1
# 1    0
# 2  174

data.table::fread("col1\n0x0\n0xAE")
#    col1
# 1:    0
# 2:  174
```
