### ISSUE TITLE
fread changing values

### ISSUE THREAD

**Issue by jvondollen** [Rdatatable/data.table#1600]
When reading in a dataset, I've come across the famous warning message about "bumping" columns to type character. In some cases, this results in the values in the column getting converted to something else.  An example is reading in a tab delimited txt file such as:

| Run | label |
| --- | ----- |
| 2 | T |
| 3 | T |
| 4 | T |
| 5 | T |
| 6 | T |
| 7 | T |
| 9 | T |
| 10 | T |
| 1 | C |
| 8 | C |
| 11 | T |
| 12 | T |
| 13 | T |
| 14 | T |
| 15 | T |
| 16 | T |
| 17 | T |
| 18 | T |
| 20 | T |
| 21 | T |
| 22 | T |
| 23 | T |
| 25 | T |
| 19 | C |
| 24 | C |
| 32 | C |
| 26 | T |
| 27 | T |
| 28 | T |
| 29 | T |
| 30 | T |
| 31 | T |
| 33 | T |
| 34 | T |
| 35 | T |
| 36 | T |
| 37 | T |
| 38 | T |
| 39 | T |

The warning pops up and says that column two has been bumped to type character. When we look at the resulting data.table object read in, the first portion of the column has been changed from T's to numeric 1's instead:

|  | Run | label |
| --- | --- | ----|
| 1: | 2 | 1 |
| 2: | 3 | 1 |
| 3: | 4 | 1 |
| 4: | 5 | 1 |
| 5: | 6 | 1 |
| 6: | 7 | 1 |
| 7: | 9 | 1 |
| 8: | 10 | 1 |
| 9: | 1 | C |
| 10: | 8 | C |
| 11: | 11 | T |
| 12: | 12 | T |
| 13: | 13 | T |
| 14: | 14 | T |
| 15: | 15 | T |
| 16: | 16 | T |
| 17: | 17 | T |
| 18: | 18 | T |
| 19: | 20 | T |
| 20: | 21 | T |
| 21: | 22 | T |
| 22: | 23 | T |
| 23: | 25 | T |
| 24: | 19 | C |
| 25: | 24 | C |
| 26: | 32 | C |
| 27: | 26 | T |
| 28: | 27 | T |
| 29: | 28 | T |
| 30: | 29 | T |
| 31: | 30 | T |
| 32: | 31 | T |
| 33: | 33 | T |
| 34: | 34 | T |
| 35: | 35 | T |
| 36: | 36 | T |
| 37: | 37 | T |
| 38: | 38 | T |
| 39: | 39 | T |

I get these warnings all the time for different datasets, and I'm scared to think about what data has been changed by using fread. 

R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)
data.table Version 1.9.6

**Comment by jangorecki** [comment]
would be better not to have nicely formatted tables but the script to populate them

**Comment by arunsrinivasan** [comment]
+1 @jangorecki. MRE please. Could you also retest on v1.9.7 (this devel)? Thanks.
Please reopen once you've edited with a MRE.

**Comment by jvondollen** [comment]
What is MRE?

**Comment by jangorecki** [comment]
@jvondollen minimal reproducible example - highest voted stackoverflow question on R tag explains it well: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by jvondollen** [comment]
edited initial submission to have R code
