### ISSUE TITLE
Wrong output of 'melt', additional rows

### ISSUE THREAD

**Issue by rohlfs** [Rdatatable/data.table#1605]
I have a data.table with 89 columns. I insert an id-variable, to create a "stack"

umsatz.roh[, id:= .I ]

Then I use melt, to create a stack:

dim(melt(head(umsatz.roh,2), id.vars="id"))
[1] 178   3

This was wrong, because there are two additional, wrong lines:
... 
175:  1     originalCreditorName                  
176:  2     originalCreditorName                  
177:  1                       NA                  
178:  2                       NA                  
     id                 variable             value

With the 'melt' from the library 'reshape2', I got the right result:

> dim(melt(as.data.frame(head(umsatz.roh,2)), id.vars="id"))
[1] 176   3

**Comment by franknarf1** [comment]
Please make a reproducible example. You claim that the melted data table has three columns but show lines with, apparently, only two, so our odds of guessing your problem with what you've given are slim.

**Comment by arunsrinivasan** [comment]
Please provide a minimal reproducible example.
