### ISSUE TITLE
back propagating column into parent data.table object

### ISSUE THREAD

**Issue by jg44** [Rdatatable/data.table#1607]
### Just some behaviour that seems very odd to me.  Thought I'd report...

> test<-data.table(a=1:3, b=5:3)
> test
   a b
1: 1 5
2: 2 4
3: 3 3
> tmp<-test
> tmp[, c:=a+b]

### This makes perfect sense
> t2
   a b c
1: 1 5 6
2: 2 4 6
3: 3 3 6

### However the fact that the c column is created in 'test' seems very odd to me.  Is this intended behaviour?  If so, how would one avoid back propagating changes into parent data.table objects?
> test
   a b c
1: 1 5 6
2: 2 4 6
3: 3 3 6

Jeff

**Comment by ChristK** [comment]
The quick answer is use `tmp = copy(test)` but please have a look here: [https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-reference-semantics.html](url)

**Comment by jangorecki** [comment]
This was asked many times on SO. Make `<-` operator to force copy data.table will be inefficient. `copy()` is easy and cheap solution for that. ChristK's url appears to be broken, here valid one: [Reference semantics vignette](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-reference-semantics.html).
