### ISSUE TITLE
Printing issue when data.table returned from function

### ISSUE THREAD

**Issue by daynefiler** [Rdatatable/data.table#1611]
test1 <- function() data.table(a = 1)

test2 <- function() {
  dat <- data.table(a = 1)
  dat[ , b := 2]
  dat
}

When altering a data.table with `:=` before returning the data.table, the returned object does not print. I would have expected this behavior to be  consistent.  

I am still using 1.9.6 -- I apologize if this has already been fixed in the current development version.

**Comment by daynefiler** [comment]
Interestingly, if you create an object from `test2` it still takes two iterations to get the object to print:

dat <- test2()
dat ## does not print
dat ## does print

**Comment by MichaelChirico** [comment]
This is well-documented behavior, see FAQ 2.23 `vignette("datatable-faq")`

**Comment by daynefiler** [comment]
I realized that and close the issue. Thanks.
