### ISSUE TITLE
Confusing error on factor column

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1621]
Caused by [this](http://stackoverflow.com/q/36389601/3576984) SO question.

```
DT <- 
  structure(list(game = c(1L, 1L, 2L, 2L, 3L, 3L),
                 team = 
                   structure(c(6L, 1L, 2L, 3L, 4L, 5L), 
                             .Label = 
                               c("aston villa", "chelsea", "fulham", 
                                 "leicester", "man city", "newcastle"), 
                                  class = "factor"),
                 score = c(3L, 2L, 1L, 1L, 28L, 0L)),
            .Names = c("game", "team", "score"), 
            row.names = c(NA, -6L),
            class = c("data.table", "data.frame"))
```

Target is to aggregate games to winners, and return `NA` for ties, leading naturally to:

```
DT[ , if (diff(score) == 0) NA else team[which.max(score)], by = game]
```

Which gives error:

> Error in``[.data.table`(DT, , if (diff(score) == 0) NA else team[which.max(score)],`  : 
>   Column 1 of result for group 2 is type `logical` but expecting type `integer`. Column types must be consistent for each group.

This is of course because `team` is stored as a `factor`, i.e., named `integer`.

It seems like one or both of the following should happen:

1) `data.table` should flexibly fix `NA` to `NA_integer_` automatically

2) The error should correctly identify that a `factor` is why it's expecting an `integer`

(another case where having `class = TRUE` by default on print would have been helpful)

**Comment by franknarf1** [comment]
> 1) data.table should flexibly fix `NA` to `NA_integer_` automatically

Even if the NA comes before the first non-NA? 

    DT1 = DT[c(3:4, 1:2, 5:6)]
    DT1[, if (diff(score) == 0) NA_integer_ else team[which.max(score)], by = game]
    #    game V1
    # 1:    2 NA
    # 2:    1  6
    # 3:    3  4

The fix is 

    DT1[, if (diff(score) == 0) team[NA_integer_] else team[which.max(score)], by = game]

since `as(NA, "factor")` does not work. Personally, I think NA classes are just an R quirk that the user has to be responsible for handling.

**Comment by MichaelChirico** [comment]
In retrospect, agree with @franknarf1.
