### ISSUE TITLE
[Documentation] Use of the `on=` argument for joins

### ISSUE THREAD

**Issue by stephlocke** [Rdatatable/data.table#1623]
The `on=` argument for data.table has minimal documentation at present, and does not feature in FAQs. It is, of course, a rather hard to search for the term. 

I'd like to see the following:
1) A wiki page on all things JOIN in data.table
2) An entry in the FAQ about different join methods
3) More illustrative examples in the documentation about the features and limitations of `on=`

**Comment by stephlocke** [comment]
Started on the wiki content. Started at `setkey()` as it seemed a bit weird to jump to `on=` without coverage of keys and JOINs first.
https://github.com/Rdatatable/data.table/wiki/Keys

**Comment by jangorecki** [comment]
R has great infrastructure for keeping docs. I would advocate to put such doc as a part of the package, so in vignettes or new Rd manuals. I'm quite OK on keeping GH related docs (support/contribution/installation/etc.) as GH wiki and strictly project related stuff within the project scope. So I would move *fread* wiki to vignettes too at some point.
BTW. AFAIK Arun is working on joins vignettes, so probably he handled `on` argument there.

**Comment by stephlocke** [comment]
Agreed - vignettes would be fantastic. 

@arunsrinivasan, I'm happy to port content over via PR?

**Comment by arunsrinivasan** [comment]
I think you've not seen https://github.com/Rdatatable/data.table/commit/f55d35b04c6781e592f533d515c50c50db6f2b65 and https://github.com/Rdatatable/data.table/commit/a2cb83a03dbc21badbb54f5e976cb0eacc358f3e ?

Also, recently added [Secondary indices and Auto indexing](https://github.com/Rdatatable/data.table/wiki/Getting-started) explains the rationale for `on=` argument along with examples.

The next vignette joins will also focus on `on=`, but I'm in the process of wrapping up non-equi joins. So most likely, it'll happen after that.

In essence, on your points:

1. Join vignette will be added (and I think it's better than Wiki).
2. Makes sense. Adding FAQ explaining just the rationale behind `on=` argument would be great!
3. See links above.

@jangorecki on `fread`, moving it to vignettes is the plan, yes.

**Comment by arunsrinivasan** [comment]
Noted point 2 in #944.

**Comment by arunsrinivasan** [comment]
On keys, there's an entire vignette dedicated to it.. why the wiki? Is it addressing something different?
