### ISSUE TITLE
Bug: by and RStudioGD don't play nice together

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1624]
From what Arun has learned, it seems like this is an RStudio issue more than a `data.table` issue, but I'm leaving it here since it has come up a few times for `data.table` users.

Here are two SO questions which appear to be driven by the same bug: [1](http://stackoverflow.com/q/36413514/3576984), [2](http://stackoverflow.com/q/27505794/3576984)

An example demonstrating the issue (from the first link above):

```
library(data.table)
set.seed(23)
Example <- data.table('group' = rep(c('a', 'b'), each = 5), 'value' = runif(10))
layout(1:2)
par('mai' = rep(.5, 4))
#Note that both the top and bottom plot use the same data
Example[, plot(value, ylim = c(0, 1)), by = group]
```

As Arun pointed out, it seems there's an issue specifically with RStudio's `RStudioGD` device which is the source of both issues.

[Cross-posted at RStudio support](https://support.rstudio.com/hc/en-us/community/posts/208778048-RStudioGD-has-some-bug-when-used-within-j-of-data-table-also-dplyr-)

**Comment by jangorecki** [comment]
isn't that duplicate of #1524 ?

**Comment by MichaelChirico** [comment]
Indeed it is! I even contributed to that issue... whoops...
