### ISSUE TITLE
fread incorrectly skips header on this file

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1625]
fread("http://www.nzta.govt.nz/resources/crash-analysis-system-data/docs/crash-data-2014.csv") :
  Starting data input on line 2 and discarding line 1 because it has too few or too many items to be column names or data: "TLA NAME","CRASH ROAD","CRASH DIST","CRASH DIRN","INTSN","SIDE ROAD","CRASH ID","CRASH DATE","CRASH DOW","CRASH TIME","MVMT","VEHICLES","CAUSES","OBJECTS STRUCK","ROAD CURVE","ROAD WET","LIGHT","WTHRa","JUNC TYPE","TRAF CTRL","ROAD MARK","SPD LIM","CRASH FATAL CNT","CRASH SEV CNT","CRASH MIN CNT","PERS AGE1","PERS AGE2","EASTING","NORTHING"

From : http://stackoverflow.com/questions/28100868/download-file-inserts-an-extra-cr-after-each-crlf

**Comment by arunsrinivasan** [comment]
Try it again with `fill = TRUE`. Perhaps that should be added to the warning message.
