### ISSUE TITLE
Big table is not sorted according to specified key

### ISSUE THREAD

**Issue by AmitaiPerlstein** [Rdatatable/data.table#1631]
Warning message:
In setkeyv(x, cols, verbose = verbose, physical = physical) :
Already keyed by this key but had invalid row order, key rebuilt. If you didn't go under the hood please let datatable-help know so the root cause can be fixed.

**Comment by DavidArenburg** [comment]
I would include a reproducible example if I were you

**Comment by arunsrinivasan** [comment]
Please provide a minimal reproducible example. Either reopen by editing this post or feel free to create a new one.
