### ISSUE TITLE
handling i which is a factor

### ISSUE THREAD

**Issue by aushev** [Rdatatable/data.table#1632]
It happens quite often to me that column which I passed as `i`, turns out to be a factor. Current behavior [is to throw an error](https://github.com/Rdatatable/data.table/blob/master/R/data.table.R#L705): "_i has not evaluated to logical, integer or double_", so I have to manually convert it to the same class as the `key` of the target table.
1. One option would be just to add this conversion to `"[.data.table"` function code. I guess there are some reasons against as it have not been done yet, would be glad to hear it.
2. When it happened first time, it took me some time to figure out what was the problem. It would be helpful to make error message more informative, just add `class(i)` at the end of message in `stop()` call.

**Comment by MichaelChirico** [comment]
Related to #1621 -- seems we'd do well to give better errors when `factor`s are involved

**Comment by aushev** [comment]
well, for me, it's not the same situation there - it is not processing of `i`...

**Comment by jangorecki** [comment]
Are you converting to integer or character (factor levels)?
I think both types (integer and character) could be expected in such case, so it may be better to keep conversion on the user side. Any reason why not to convert factors into character in the first place, if you are going to use them as character?

**Comment by aushev** [comment]
I am converting it to the same class as the `key` of the data.table I am calling - usually it's character. It just happens that the table where I take `i` from has it as a factor (usually just because it was created this way, but sometimes I explicitly want it to be factor, for other operations). OK, I take the point of suggesting user to make conversion - but still believe that it would not hurt to add this info to error message (show specific message if `is.factor(i)`, or generally add `class(i)` to that message).

**Comment by jangorecki** [comment]
Agree, we need to add check for is.factor, current error is little bit confusing.
```r
setkey(data.table(a=factor("a")))[factor("a")]
#Error in `[.data.table`(setkey(data.table(a = factor("a"))), factor("a")) : 
#  i has evaluated to type integer. Expecting logical, integer or double.
```

**Comment by mattdowle** [comment]
This was unfortunate. The workaround was in fact to just wrap factor `f` with `.()`; i.e `DT[.(f)]` so that a join would be invoked.
#5120 means that that workaround is no longer needed and `DT[f]` just works.
