### ISSUE TITLE
fread doesn't check colClasses to be valid type

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1634]
```
> sapply(fread("A,B\n1,2",colClasses="numeric"),class)   # ok
        A         B 
"numeric" "numeric" 
> sapply(fread("A,B\n1,2",colClasses="integer"),class)    # ok
        A         B 
"integer" "integer" 
> sapply(fread("A,B\n1,2",colClasses="string"),class)      # type "string" works?
          A           B 
"character" "character" 
> sapply(fread("A,B\n1,2",colClasses="c"),class)             
          A           B 
"character" "character" 
> sapply(fread("A,B\n1,2",colClasses="foo"),class)      # should be error that foo isn't valid type?
          A           B 
"character" "character" 
> 

```

**Comment by MichaelChirico** [comment]
maybe just produce a warning for all of the above?

**Comment by jangorecki** [comment]
how exactly we want to define *valid type*?

**Comment by mattdowle** [comment]
@jangorecki  Looking at Hugh's PR #2545 made me realize the answer to your question.  Just as `read.csv`,  `"foo"` is a valid type to use in `colClasses=` if `as.foo.character()` or `as.foo.default()` exists. Otherwise, standard R error that `as.foo` method does not exist.

**Comment by MichaelChirico** [comment]
Whether `as.*` exists will be dependent on the local user's setup. I suppose this is a desired behavior -- users expecting coercion to `foo` class with methods defined in `bar` library can be trusted to handle loading `bar` themselves before running `fread`. From a glance at #2545, the backup (to use default interpretation, typically `character`) with a warning is probably ideal behavior.
