### ISSUE TITLE
Memory leak in data.table

### ISSUE THREAD

**Issue by adamryczkowski** [Rdatatable/data.table#1637]
Run this code:

```
library(data.table)
db<-data.table(V0=sample(c(TRUE,FALSE), 2e6, TRUE))
for (i in 1:200)
{
  db[,paste0('V',i):=sample(c(TRUE,FALSE), 2e6, TRUE),with=FALSE]
}
v<-db[,v:=paste0(as.integer(.SD),collapse=''),by=1:2e6]
rm(list=ls(all=TRUE))
gc()
```
The memory does not get reclaimed.

**Comment by franknarf1** [comment]
The step after your loop (creating v) gives me this error:

> Error in `[.data.table`(db, , `:=`(v, paste0(as.integer(.SD), collapse = "")),  : 
> column or expression 202 of 'by' or 'keyby' is type NULL. Do not quote column names. Usage: DT[,sum(colC),by=list(colA,month(colB))]

Are you using the devel version of the package? (To be honest, I have no idea why that error is triggered, since `db[202, paste0(as.integer(.SD),collapse='')]` works...)

**Comment by arunsrinivasan** [comment]
Seems to work fine for me. What version? What OS?

**Comment by franknarf1** [comment]
Not sure if you're asking me, but... As far as the error I saw goes, I think it is because `by=n:m` treats n and m as column numbers currently. E.g., `data.table(a=1,b=2,c=3)[, "bah", by=2:3]`. I'm on 1.9.7, but it may be out of date (can't update atm); win 7, r 3.2.3.

**Comment by arunsrinivasan** [comment]
@franknarf1 nope, to the op.

**Comment by jangorecki** [comment]
Code works fine for me without error.
@adamryczkowski are you aware of https://stackoverflow.com/questions/14580233/why-does-gc-not-free-memory ?

**Comment by adamryczkowski** [comment]
Thank you for so quick response. I use 64bit Ubuntu Linux. session.info:

R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pl_PL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.6

loaded via a namespace (and not attached):
[1] chron_2.3-47

**Comment by adamryczkowski** [comment]
@jangorecki 

Maybe this is the case, and there is nothing to worry about. I'll try to see if I hit out of memory problem, but not today.

I will also try to replicate the error on development version of data.table.

**Comment by jangorecki** [comment]
@adamryczkowski OK, re-open then if needed.
