### ISSUE TITLE
fread does not properly close file connection on error-induced exit

### ISSUE THREAD

**Issue by bahanonu** [Rdatatable/data.table#1638]
Didn't see this particular bug noted in Issues after searching for a bit, so posting here.

When `fread` encounters an error, such as a row with an incorrect number of columns, it does not properly close the connection to the file it was attempting to read. This causes problems for any other functions that try to manipulate said file later. It is unclear if this is as simple as adding `on.exit()` somewhere in the code such that it always closes the current file connection when `fread` exits.

See below for example code to reproduce the error and `sessionInfo()` output.
#### original error

Below is an example output when there is a column with an incorrect number of columns. This leads to that file being 'locked'.

``` R
Error in fread(fileToRead, sep = ",", header = TRUE) : 
  Expecting 4 cols, but line 13041 contains text after processing all cols. [...]
```
#### code to reproduce error

Below is a minimal reproducible example to cause the error to occur and the file to become locked.

``` R
packagesFileList = c("data.table")
lapply(packagesFileList,FUN=function(file){if(!require(file,character.only = TRUE)){install.packages(file,dep=TRUE)}})

testFilename = "test.csv"
sink(testFilename)
cat("header1,header2,header3\n")
cat("1,2,3\n")
cat("1,2,3\n")
cat("1,2,3\n")
sink()
fread(testFilename,sep=",",header=TRUE)

# opens fine
sink(testFilename)
cat("header1,header2,header3\n")
cat("1,2,3\n")
cat("1,2,3,4\n")
cat("1,2,3\n")
sink()
fread(testFilename,sep=",",header=TRUE)

# produces an error since connection to file isn't closed
sink(testFilename)
```

The last command should produce the below, demonstrating that fread hasn't properly closed the file connection.

``` R
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'test.csv': Invalid argument
```
#### sessionInfo() output

``` R
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.6

loaded via a namespace (and not attached):
[1] chron_2.3-47
```

**Comment by MichaelChirico** [comment]
for now, try `fill = TRUE` to get around that error in the development version.

**Comment by st-pasha** [comment]
The file is now closed properly in all cases.
