### ISSUE TITLE
fread dec argument compatibility within shinyapps.io

### ISSUE THREAD

**Issue by rchiche** [Rdatatable/data.table#1644]
Assigning the fread dec argument to anything else than "." crashes when a shiny app is run on shinyapps.io.

I think this is due to the system default that cannot be changed on shinyapps.io servers.

Is there any way to avoid that crash, other than forcing all numerical columns to be read as characters and converting them afterwards?

Just to precise my question, fread works fine on my own computer, using data.table 1.9.7.
The only issue I have is when I try to modify the dec argument when lauching a shiny app from shinyapps.io.

**Comment by jangorecki** [comment]
You should provides more details.
Are you able to reproduce it using 1.9.7?

**Comment by rchiche** [comment]
@jangorecki : Thank you for your reply. I understand the reproductibility issue.

If you are using shinyapps.io, do you know how to check the data.table version is used in an app?

**Comment by jangorecki** [comment]
`packageVersion("data.table")`

**Comment by rchiche** [comment]
I am indeed using data.table 1.9.7, which is the version that is pushed to shinyapps when I upload my application.

**Comment by jangorecki** [comment]
Hard to track further, reproducible example, if possible, would help. Otherwise you can try to compare locales. Try to output `sessionInfo()` in your app, `verbatimTextOutput` component is good for that.

**Comment by rchiche** [comment]
Ok thanks.
Here is an app I just designed to test opening a small CSV file in 2 versions: comma and dot decimals (attached).
[dot_sep.txt](https://github.com/Rdatatable/data.table/files/215401/dot_sep.txt)
[comma_sep.txt](https://github.com/Rdatatable/data.table/files/215400/comma_sep.txt)

Result: https://apiagpc.shinyapps.io/test_datatable/


Code is:

`# ui.R`
`shinyUI(fluidPage(`
`  titlePanel("Test"),`
`  htmlOutput("text1")`
`))`

`# server.R`
`library(data.table)`

`shinyServer(function(input, output) {`
  
`  try(data_comma <- fread("comma_sep.csv", dec=",", sep=";"), silent=T)`
`  try(data_dot <- fread("dot_sep.csv", dec=".", sep=","), silent=T)`
  
`  output$text1 <- renderUI({`
`    HTML(paste0("File with comma: ", exists("data_comma"), "<br/>",`
`                                    "File with dot: ", exists("data_dot")))`
`  })`
`}`
`)`

PS : sorry if the code is hard to read, I'm new on github and am not sure how to format it correctly...

**Comment by jangorecki** [comment]
For formatting on github use triple backticks as start of the code block, and another triple backtick as end of code block. Add `sessionInfo()` to your app so we can see what really drivers the application.

**Comment by rchiche** [comment]
Sorry, I am actually using data.table 1.9.6, but your line of code runs into a "non-zero return code". I'm not really sure of what to do.

The above link is updated to output the sessionInfo.

Thanks a lot for your help!

**Comment by jangorecki** [comment]
If you are on windows you may need to install additional Rtools which allows to build package from source, read more on [Intallation](https://github.com/Rdatatable/data.table/wiki/Installation) wiki.

**Comment by arunsrinivasan** [comment]
Sorry if I appear to be dim here, but why is this an issue with `fread`?

**Comment by jangorecki** [comment]
@rchiche Arun is right on that. This doesn't seem to be fread issue but more shinyapps.io configuration, better then to look for support there than guessing here.
