### ISSUE TITLE
error compile in windows 64bit

### ISSUE THREAD

**Issue by pfv07** [Rdatatable/data.table#1645]
When a try to install the development version, I have the next error:

 * installing *source* package 'data.table' ...
** libs
gcc -m64 -I"C:/R/R-32~1.3/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c assign.c -o assign.o
assign.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include "data.table.h"
 ^
make: *** [assign.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/R/R-32~1.3/etc/x64/Makeconf" -f "C:/R/R-32~1.3/share/make/winshlib.mk" SHLIB="data.table.dll" WIN=64 TCLBIN=64 OBJECTS="assign.o bmerge.o chmatch.o dogroups.o fastmean.o fcast.o fmelt.o forder.o frank.o fread.o fwrite.o gsumm.o ijoin.o init.o quickselect.o rbindlist.o reorder.o shift.o transpose.o uniqlist.o vecseq.o wrappers.o"' had status 2
ERROR: compilation failed for package 'data.table'
* removing 'C:/R/R-3.2.3/library/data.table'
* restoring previous 'C:/R/R-3.2.3/library/data.table'

I want to know if you have a time estimated to 64bit disponiblility.
Tks.

**Comment by arunsrinivasan** [comment]
Did you follow the instructions [here](https://github.com/Rdatatable/data.table/wiki/Installation)? That is, do you've Rtools installed?

**Comment by pfv07** [comment]
I have installed Rtools and this work ok for another compilation packages. In the log say:
"sorry, unimplemented: 64-bit mode not compiled in #include "data.table.h" ^ make: *** [assign.o]"
It's from package ?? or error of the compliler ..
In Linux it's ok.
tks.

**Comment by arunsrinivasan** [comment]
Please post the entire compilation output.

**Comment by jangorecki** [comment]
Exact command which indicates the builds can also be useful. Precisely the parameters useed `R CMD ...`. And `sessionInfo()` from R.

**Comment by pfv07** [comment]
I solved it, I'm using Rtools33 but uninstall it and install Rtools32 and work.!!!
tks
