### ISSUE TITLE
as.data.table not handling nested data.frame with lists properly

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1646]
I'm trying to convert the data from JSON into a `data.table`, and it failed to do so properly, I think because of the nest list.

Here's an example:

```
DF <- structure(list(
  DF1 = structure(list(
    V1 = list(1:2, 3:4), V2 = 5:6), .Names = c("V1","V2"),
    class = "data.frame", row.names = c(NA, 2L)),
  DF2 = structure(list(
    V3 = 7:8, V4 = 9:10), .Names = c("V3","V4"),
    class = "data.frame", row.names = c(NA, 2L)), 
  V5 = 11:12), .Names = c("DF1", "DF2", "V5"), 
  class = "data.frame", row.names = c(NA, 2L))

as.data.table(DF)
```

> Error in `FUN(X[[i]], ...)` : 
>   Invalid column: it has dimensions. Can't format it. If it's the result of `data.table(table())`, use `as.data.table(table())` instead.

The error is from `print.data.table`, since we can assign `DT <- as.data.table(DF)` with no problem.

Perhaps `as.data.table` should un-nest the list?

**Comment by franknarf1** [comment]
Not sure what you expect/want the result to look like, but `as.data.table(as.list(DF))` doesn't throw an error, at least.

**Comment by MichaelChirico** [comment]
Maybe it's unreasonable, but expected output is:

    DT <- data.table(V1 = 1:2, V2 = 3:4, V3 = 7:8, V4 = 9:10, V5 = 11:12)

**Comment by MichaelChirico** [comment]
`print.data.table()` no longer chokes on the output, which looks reasonable (full unnesting should be handled by user):

```
   DF1.V1 DF1.V2 DF2.V3 DF2.V4    V5
   <list>  <int>  <int>  <int> <int>
1:    1,2      5      7      9    11
2:    3,4      6      8     10    12
```

**Comment by MichaelChirico** [comment]
Re-opening: we should add a regression test to be sure. Ideally we'd bisect to find when it's fixed but it's hard to compile such an old version of data.table now.
