### ISSUE TITLE
Inaccurate sum of integer64 returned using by clause

### ISSUE THREAD

**Issue by mlandry22-h2o** [Rdatatable/data.table#1647]
Attached is a data.table with an integer64 column. Data.table returns the correct sum when the by clause is not used. However, when the by clause is used, the result is incorrect. The sum returned is interestingly the sum of the results except the final row.

Related scripts:

```
> setnames(DT,c("key","value"))
> DT
               key   value
1: 7355 1100047023 -168067
2: 7355 1100047023  168067
3: 7355 1100047023  141091
4: 7355 1100047023 -141091
> DT[,sum(value)]
integer64
[1] 0
> DT[,sum(value),by=key]
               key      V1
1: 7355 1100047023 -141091
> save(DT,file="integer64_sum_with_group_example.Rdata")
```

[integer64_sum_with_group_example.zip](https://github.com/Rdatatable/data.table/files/217990/integer64_sum_with_group_example.zip)

**Comment by mattdowle** [comment]
Yep confirmed.  GForce needs to be `integer64` aware.  Thanks for reporting!

**Comment by stanmart** [comment]
Would it be possible to disable GForce if an integer64 column is detected until there is a proper fix? It is dangerous that `data.table` returns an incorrect result without failing or warning.

**Comment by pertplu** [comment]
This came up as a SO question at https://stackoverflow.com/questions/53051166/integer64-class-in-r-data-table-sum-and-by

**Comment by franknarf1** [comment]
@moman822 Fyi, you see those results because gsum uses the core data (that you can see with `unclass(z$int64)`), which contains some NaNs.

```
> z[, v := replace(int64, is.nan(unclass(int64)), NA)]
> z
    group int64  v
 1:     A    10 10
 2:     A    -2 NA
 3:     A    20 20
 4:     A    -7 NA
 5:     B     5  5
 6:     B    -8 NA
 7:     B    -2 NA
 8:     B    -1 NA
 9:     B    -3 NA
10:     B     0  0
```

To avoid using gsum till this is supported, besides what akrun pointed out, you can wrap in parentheses:

```
z[, (sum(int64, na.rm = TRUE)), by=group]
z[, (sum(int64, na.rm = FALSE)), by=group]
```

**Comment by moman822** [comment]
@franknarf1

That makes sense to me for when `na.rm=TRUE`, but not for when `na.rm=FALSE`.

**Comment by franknarf1** [comment]
@moman822 The same idea applies:

```
library(integer64) # no need for data.table to see it
x = as.integer64(c(10,-2,20,-7))
structure(sum(unclass(x)), class="integer64")
# integer64
# [1] -2
```

We could take it to StackOverflow if it's still unclear (eg [this chat room](https://chat.stackoverflow.com/rooms/25312/r-public)) since the package maintainers here on github seem to understand the problem already (from the second comment).
