### ISSUE TITLE
fread ignore escaped double quotes in conjunction with separator

### ISSUE THREAD

**Issue by rohlfs** [Rdatatable/data.table#1651]
When trying to read apache's htacces-file with the very fast 'fread', sometimes there are errors:

> fread("error.apache.htaccess")
> Fehler in fread("error.apache.htaccess") : 
> _  Expecting 5 cols, but line 7 contains text after processing all cols. It is very likely that this is due to one or more fields having embedded sep=' ' and/or (unescaped) '\n' characters within unbalanced unescaped quotes. fread cannot handle such ambiguous cases and those lines may not have been read in as expected. Please read the section on quotes in ?fread._

Reason: If there was a double quote, directly followed by the separator (whitespace), the escaping
backslash were ignored:   "abc\" def"
freads interprete it as a quoting mark of the column. Erroneous in my opinion.

[error.apache.htaccess.txt](https://github.com/Rdatatable/data.table/files/222145/error.apache.htaccess.txt)

**Comment by st-pasha** [comment]
The example file works with latest data.table version
