### ISSUE TITLE
Error Display in Vignettes

### ISSUE THREAD

**Issue by XD-DENG** [Rdatatable/data.table#1653]
When I was reading the Vignettes on CRAN (https://cran.r-project.org/web/packages/data.table/vignettes/datatable-keys-fast-subset.html), I found something seeming not well put, as below
<img width="442" alt="screen shot 2016-04-17 at 3 28 21 pm" src="https://cloud.githubusercontent.com/assets/11539188/14585741/331f9704-04b2-11e6-8876-ec5aadb178de.png">

The speedup factor is not apprearring. I checked the raw Rmd file, it is as below,
<img width="409" alt="screen shot 2016-04-17 at 3 28 07 pm" src="https://cloud.githubusercontent.com/assets/11539188/14585723/7dffb872-04b1-11e6-8db7-9735fa98f823.png">
<img width="382" alt="screen shot 2016-04-17 at 3 28 14 pm" src="https://cloud.githubusercontent.com/assets/11539188/14585724/7e022f58-04b1-11e6-9a13-142c9eb7dc31.png">

So the reason should be that the t2[3] is 0, then t1[3]/t2[3] is a invalid value, which caused the disapprearance of the speedup factor.

I'm thinking if it's necessary to use **microbenchmark** package to do more accurate benchmarking. If you find it necessary, I would be more than happy to submit a PR regarding it.

**Comment by arunsrinivasan** [comment]
Thanks! Will fix.

**Comment by XD-DENG** [comment]
Sure. But maybe have a smaller threshold, say 1e-8, rather than 0.001? 

If we use 0.001, quite likely the speedup factor will be underestimated.

**Comment by arunsrinivasan** [comment]
Sure!
