### ISSUE TITLE
[Request] allow aggregations in LHS of dcast formula

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#1655]
Found [this question on SO](http://stackoverflow.com/q/31956104/1191259): The goal is to collapse the data to the level of US states, taking means of continuous columns ("density" and "income") and dcasting counts of a categorical column ("tree_type"):

    set.seed(1)
    tree_type <- c("pine", "birch", "maple", "palm")
    DT <- data.table(location = sample(state.abb[1:5], 20, replace = TRUE), 
               tree_type = sample(tree_type, 20, replace = TRUE),
               density = runif(20, min = 24, max = 365), 
               income = runif(20, min = 37000, max = 62000))

    # desired output (using the best current syntax I could think of)
    dcast(DT[, c(lapply(.SD, mean), list(tree_type = tree_type)), by=location, .SDcols=!"tree_type"],
      location + ... ~ tree_type, fill = 0L)

    # proposed syntax
    dcast(DT, location + lapply(..., mean) ~ tree_type, fill = 0L)
    # or at least
    dcast(DT, location + mean(density) + mean(income) ~ tree_type, fill = 0L)

**Comment by arunsrinivasan** [comment]
Seems not *that* common / convincing really. It doesn't seem easy to understand from the syntax what exactly is happening too. I'd split your current syntax version into 2 lines.

**Comment by franknarf1** [comment]
Yeah, looking at it a day later, I agree.
