### ISSUE TITLE
Documentation: ?wday should mention the reference day

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1658]
The man page for `?wday` needs to mention the reference day (Sunday) and expected output (1 through 7), especially since it is in conflict with `?POSIXlt`:

    wday(as.Date("2016-04-18"))
    # [1] 2 
    as.POSIXlt("2016-04-18")$wday
    # [1] 1

A perfectly fine design choice, but this needs to be mentioned.

**Comment by arunsrinivasan** [comment]
Sure, do you mind issuing a PR?

**Comment by MichaelChirico** [comment]
planning on it :)
