### ISSUE TITLE
`chmatch` validate `nomatch` argument

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1672]
Docs states that `nomatch` is coerced to integer.
When providing integer of length 0L it should warn/error/handle other way.  Currently output is not really useful.
```r
library(data.table)
chmatch(c("a","b"), c("a","c"), nomatch = integer())
#[1]        1 45133224
```

**Comment by MichaelChirico** [comment]
what does `base::match` do? `chmatch` should mirror that
