### ISSUE TITLE
wrong link in support on wiki

### ISSUE THREAD

**Issue by floswald** [Rdatatable/data.table#1677]
hi,
when i click on the FAQ link, the wiki editor opens for me. where is the FAQ pdf?

**Comment by MichaelChirico** [comment]
What FAQ link?

**Comment by franknarf1** [comment]
[This FAQ link](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-faq.html) works. It's number 6 on [Getting started](https://github.com/Rdatatable/data.table/wiki/Getting-started).

I'm not sure what FAQ link you're looking at, but maybe you could edit it to the right one?

**Comment by floswald** [comment]
this link doesn't.

data.table FAQ
<https://github.com/Rdatatable/data.table/wiki/vignettes/datatable-faq.pdf>

it was on the support page. I grabbed yours and put it there.

**Comment by jangorecki** [comment]
@floswald thanks for updating support page.
