### ISSUE TITLE
Darwin: unknown operand

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1687]
Hello.

When I install data.table, with 
install_github("Rdatatable/data.table")

Apparently it's installed properly but I get this error:

> uname: not found
> [: Darwin: unknown operand

**Comment by arunsrinivasan** [comment]
What's your OS, R version etc.? What happens if you install using the instructions provided [here](https://github.com/Rdatatable/data.table/wiki/Installation)? Have you tried `remove.packages("data.table")` and reinstalling it?

**Comment by arunsrinivasan** [comment]
Please write back with your R version / session Info / OS etc. if you still have issues.

**Comment by skanskan** [comment]
Hello.  
I've removed the package 

> sessionInfo()
> R version 3.2.4 (2016-03-16)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] RevoUtilsMath_3.2.4
> 
> loaded via a namespace (and not attached):
> [1] tools_3.2.4


And installed again:

> > install.packages("data.table", type = "source", repos = "https://Rdatatable.github.io/data.table")
> trying URL 'https://Rdatatable.github.io/data.table/src/contrib/data.table_1.9.7.tar.gz'
> Content type 'application/octet-stream' length 2721547 bytes (2.6 MB)
> downloaded 2.6 MB
> 
> * installing *source* package 'data.table' ...
> ** libs
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c assign.c -o assign.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c bmerge.c -o bmerge.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c chmatch.c -o chmatch.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c dogroups.c -o dogroups.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c fastmean.c -o fastmean.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c fcast.c -o fcast.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c fmelt.c -o fmelt.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c forder.c -o forder.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c frank.c -o frank.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c fread.c -o fread.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c fwrite.c -o fwrite.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c gsumm.c -o gsumm.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c ijoin.c -o ijoin.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c init.c -o init.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c openmp-utils.c -o openmp-utils.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c quickselect.c -o quickselect.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c rbindlist.c -o rbindlist.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c reorder.c -o reorder.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c shift.c -o shift.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c subset.c -o subset.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c transpose.c -o transpose.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c uniqlist.c -o uniqlist.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c vecseq.c -o vecseq.o
> gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/include" -DNDEBUG     -I"c:/applications/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c wrappers.c -o wrappers.o
> gcc -m64 -shared -s -static-libgcc -o data.table.dll tmp.def assign.o bmerge.o chmatch.o dogroups.o fastmean.o fcast.o fmelt.o forder.o frank.o fread.o fwrite.o gsumm.o ijoin.o init.o openmp-utils.o quickselect.o rbindlist.o reorder.o shift.o subset.o transpose.o uniqlist.o vecseq.o wrappers.o -fopenmp -Lc:/applications/extsoft/lib/x64 -Lc:/applications/extsoft/lib -LC:/PROGRA~1/MIE74D~1/MRO/R-32~1.4/bin/x64 -lR
> mv data.table.dll datatable.dll
> if [ `uname -s` = 'Darwin' ]; then install_name_tool -id datatable.dll datatable.dll; fi
> uname: not found
> [: Darwin: unknown operand
> installing to C:/Program Files/Microsoft/MRO/R-3.2.4/library/data.table/libs/x64
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> * DONE (data.table)
> 
> The downloaded source packages are in
> 	‘c:\temp\Rtmp4ChOjv\downloaded_packages’
> 

It seems to work but I was wondering about that strange warning about Darwin.

**Comment by arunsrinivasan** [comment]
The line `if [ \`uname -s\` = 'Darwin' ]; ...` was added because of #1144. We should be able to check and ignore if the OS is Windows. Will look into it. Thanks.

**Comment by skanskan** [comment]
Thanks
