### ISSUE TITLE
Columns of `i` not available when grouping a key field

### ISSUE THREAD

**Issue by jdthorpe** [Rdatatable/data.table#1688]
When the `by` field is the same as the key field, the columns of `i` are not available in `j`.

	A = data.table(Id = 1:20)
	B = data.table(Id = 1:10, z = rnorm(10))
	setkey(A,Id)
	setkey(B,Id)
	A[B,z,by=Id] # groupign by the key field
	#> Error in `[.data.table`(A, B, .(z), by = Id) : object 'z' not found

Using this pattern probably counts as an EBCAK, so the behavior is fine, but the error message is unuseful.  A better error message such as "columns of i are not available when 'by' is a key field" would save a lot of headaches.

**Comment by arunsrinivasan** [comment]
Duplicate of #733.

**Comment by eantonya** [comment]
Related: http://stackoverflow.com/questions/37285184/data-table-group-by-non-id-column-in-joined-table
