### ISSUE TITLE
Add ties.method="last" to frank

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1689]
base R's rank method has gained this new method in recent R version.

**Comment by abudis** [comment]
Bumping this. The documentation of frank says that all of the base rank's ties.method values are supported. So, either change the doc or add the possibility of using last as an accepted value.

**Comment by abudis** [comment]
Thanks guys for supporting and for the prompt response! :D

**Comment by MichaelChirico** [comment]
you're welcome!

this was actually a case of, when I first saw your bump I thought it was going to be trivial to add (just the opposite of `"first"`, how hard can it be?)

by the time I realized it was a bit more involved I was already committed to solving the puzzle! enjoy

**Comment by abudis** [comment]
Glad you had some fun too!
