### ISSUE TITLE
Weird bug: keeps trying to delete a column

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1690]
I've run into some strange bug where suddenly my `data.table` keeps trying to delete a column.
I keep getting the "Adding new column... then assigning NULL (deleting it)" warning, in statements that a) don't use `:=` at all and b) don't use the `data.table` in question at all. I mean it really keeps trying. Some statements give me in excess of 50 warning messages, e.g.

I haven't been able to pin down exactly what's going on...

Here are all the lines in my file that use the offending `data.table` (`attendance`)

(sorry for the massive data dump... still working on figuring out what the offending line(s) is(are)...)

```
#DATA SETUP
GHstub <- paste0("https://raw.githubusercontent.com/",
                 "MichaelChirico/iesRTutorial/in_progress/data/")
attendance <- 
  fread(paste0(GHstub,"School%20Profiles%20Teacher%20Attendance%202013-2014.TXT"))
salaries <- fread(paste0(GHstub, "employee_information.csv"))
setnames(salaries, tolower(names(salaries)))

teachers <-
  salaries[title_description == "TEACHER,FULL TIME" & 
             pay_rate_type == "SALARIED"]
schools <- unique(teachers, by = "home_organization")
```
```
attendance
print(attendance, class = TRUE)
class(attendance)
str(attendance)
is.list(attendance)
attendance$SCH_TEACHER_ATTEND
attendance[ , summary(SCH_TEACHER_ATTEND)]
attendance[SCH_TEACHER_ATTEND < 90]
attendance[SCH_TEACHER_ATTEND > 97]
attendance
attendance[ , attendance_proportion := SCH_TEACHER_ATTEND / 100]
attendance[ , attendance_relative := SCH_TEACHER_ATTEND / SDP_TEACHER_ATTEND]
attendance[]
attendance[schools, school_name :=
             home_organization_description, 
           on = c(ULCS_NO = "home_organization")]
attendance
attendance[ , school_name := NULL][]
attendance[unique(teachers, by = "home_organization"),
           school_name := i.home_organization_description,
           on = c(ULCS_NO = "home_organization")][]
attendance[ , school_name := NULL]
attendance[teachers, 
           school_name := unique(home_organization_description),
           on = c(ULCS_NO = "home_organization"), by = .EACHI][]
attendance[ , school_name := NULL]
attendance[teachers,
           school_name := home_organization_description[1],
           on = c(ULCS_NO = "home_organization"), by = .EACHI][]
attendance[is.na(school_name)]
attendance[school_name == NA]
attendance[salaries, 
           school_name := unique(home_organization_description),
           on = c(ULCS_NO = "home_organization"), by = .EACHI]
attendance[is.na(school_name)]
attendance[SCH_TEACHER_ATTEND < 90 | 
             SCH_TEACHER_ATTEND > 97
           ][order(-SCH_TEACHER_ATTEND), 
             .(ULCS_NO, school_name, SCH_TEACHER_ATTEND)]
```

The warning says it's trying to assign & delete `school_name`.

Doesn't seem to be replicating here...

**Comment by jangorecki** [comment]
You can put urls into `fread` call to make it reproducible. My guess is that some of the join did not create new column because of no match during join. This behaviour changed in 1.9.7 so now column should be always created.

**Comment by MichaelChirico** [comment]
@jangorecki one of the files is zipped up unfortunately, should I add that anyway?

And this problem is happening after a fresh install to the latest commit.

**Comment by arunsrinivasan** [comment]
Can't reproduce it either. I know it can be hard.. but not much to go on here :-(.

**Comment by MichaelChirico** [comment]
I know. what's more strange is:

in context this is a .rmd file, HTML output.

when I knit the output, I don't see any of the warnings.

Only when I "run chunks" in r studio does this arise.

I'll keep an eye out for more specifics...

**Comment by MichaelChirico** [comment]
Hmm, couldn't reproduce this anymore when I just tried to find the issue again.

Perhaps those facing this just need to update.

Running the following `data.table` development version:

> data.table 1.9.7 IN DEVELOPMENT built 2016-08-01 11:42:30 UTC; travis

Running the following version of RStudio:

> Version 0.99.878 – © 2009-2016 RStudio, Inc.; Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) RStudio Safari/538.1 Qt/5.4.0
