### ISSUE TITLE
[Request] C API documentation ?

### ISSUE THREAD

**Issue by eddelbuettel** [Rdatatable/data.table#1694]
I am contemplating creating data.table objects from Rcpp.  We had some luck with (exported) bindings from xts some of which we wrapped up in the RcppXts package ([GitHub](https://github.com/eddelbuettel/rcppxts), [CRAN](https://cran.rstudio.com/web/packages/RcppXts/index.html)) which provides some guidance as to how to do this in compiled code.

Could something similar be started here?  Creating data.frame objects in C++ is not easy---we mostly just stick things in a list and call the R function `as.data.frame()` on it.  I guess I could always call `setDT()` after that.  But are there any C level functions here we could export, one by one, or dozen by the dozen?   Happy to help...

**Comment by arunsrinivasan** [comment]
Great! I've made an attempt at implementing `data.table()` completely in C, #1415. But at the time, I had some issues with getting it to work with `do.call()` and `cbind()` IIRC. For now, `setDT()` would be the way to go.

But this is an incentive for me to give it another go :-).

**Comment by mattdowle** [comment]
Sounds good.  Looking at `setDT()` at R level it seems quite general purpose.  Maybe a new C level function to turn a list of same-length vectors into a data.table is what you'd need Dirk?  e.g. no recycling.

**Comment by eddelbuettel** [comment]
Thanks for picking up the thread, gentlemen.  

There are really two distinct issues:
-- ornaments for a SEXP so that when the user receives it in R it is a data.table (easy, call `setDT()` via `Rcpp::Function()`)
-- adding some callable interface for the _C_ level to get some of the nice data.table magic without having to got to R (hard(er), not sure how much is feasible)

Longer term point two would be _really_ appealing.  Not sure if it feasible.

**Comment by eddelbuettel** [comment]
Any news?  Working on something where this would be nice to have...

**Comment by mattdowle** [comment]
No news from my side. Happy to give information or pointers to whoever wants to do it.  I don't know what you mean by "nice data.table magic" or "really appealing".  It's too unclear to me as to what is being asked for here, currently.  Maybe someone else understands or can create some examples to illustrate.

**Comment by eddelbuettel** [comment]
Will fill in a handful of lines of R code I'd rather do at the level once back at work tomorrow.

**Comment by eddelbuettel** [comment]
How do I do

```r
seDT(d)
d[ , `:=`(a = 2*b +c,  d = log(e))]
```

at the C level?

**Comment by eddelbuettel** [comment]
I think I just got a regression.  We uses to be able to create a data.frame in C++ (via Rcpp) and then set its `class` attribute to `data.table` and all was good.   See eg [this Rcpp Gallery post for an example](http://gallery.rcpp.org/articles/creating-integer64-and-nanotime-vectors/) -- scroll down for `getDT()`.

When I do this now, and I also tried executing `setDT` from the C++ level, I get

> Warning message:
In `[.data.table`(dat, , `:=`(pt, as.POSIXct(ts, tz = "America/Chicago"))) :
  Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or been created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting. If this message doesn't help, please report to data.table issue tracker so the root cause can be fixed.

Is there a chance to avoid this?  And how about a C API to create a data.table?

(I can file a new issue if you prefer.)

**Comment by MichaelChirico** [comment]
confirming that you're testing against the latest development version?

**Comment by eddelbuettel** [comment]
Scratch this for now.  It hit me at work, but there are more moving pieces.  

I just tried the Gallery example at home, where it still works.  This may be something else, it may be the `nanotime` object and its timezone.  Ball in my court.

That said, this ticket is still needed :)

**Comment by MichaelChirico** [comment]
@eddelbuettel any update?

**Comment by eddelbuettel** [comment]
@MichaelChirico I'd love to use some documentation, but I don't think I am the one who can write it.

**Comment by MichaelChirico** [comment]
was referring to if you're still having trouble creating DT from C/C++ level for Rcpp

**Comment by eddelbuettel** [comment]
I have not tried, but I had been thinking about it. Current paradigm is assemble `data.frame` via Rcpp, convert once back.  Should be able to do better.  Has not been a bottleneck though.

**Comment by jangorecki** [comment]
@eddelbuettel so maybe we can just port `setDT` to C?

**Comment by eddelbuettel** [comment]
Maybe. I may have looked into that, or calling it from C, and got nowhere.

**Comment by jangorecki** [comment]
First interface to our C routines has been added by @lsilvest in #4084.
Documentation has been also added as a part of this PR.
I think it address your request for C API documentation, please see [?cdatatable](https://rdatatable.gitlab.io/data.table/library/data.table/html/cdt.html).
At present moment we only exported single C routine, `CsubsetDT`. I can imaging you were interested in a much more routines available from C. Could we have such request in a separate issue?

**Comment by eddelbuettel** [comment]
(Just for the record it makes only limited little sense to close this and _at the same time_ ask me to open a clone of it.  But [`?cdatatable](https://rdatatable.gitlab.io/data.table/library/data.table/html/cdt.html)  is a very good start and I already thanked @lsilvest for it in another venue...)

**Comment by jangorecki** [comment]
I understand that closing one to create another one may look superfluous, but this issue is already a long read. To save time for newcomers, rather than changing title of this one, it make sense to start new one.

**Comment by jangorecki** [comment]
Linking an example of linking C code between package: https://github.com/Accio/demo-linking-native
Actually one of many, as well explained by Dirk on mailing list.
If WRE will get a demo package explaining that, then I think it is work to mention that in our docs.
