### ISSUE TITLE
[Request] Piping into Rbindlist with a data.table, not automatically assigning "l = ."

### ISSUE THREAD

**Issue by bahuber** [Rdatatable/data.table#1697]
I do a decent amount of work where I need to add margins and totals into the data.table I'm working with. I've found that to use rbindlist to bring in these totals I have to approach it from a few different methods:

    example.dt %>%
    rbind( . ,
    rbindlist(list(.[margin.calc1], .[margin.calc2], .[margin.calc3], use.names = T, fill = F),
    use.names = T, fill = F)

or wrapping it into an anonymous function

    example.dt %>%
    (function(x){
    return(rbindlist(list(x, x[margin.calc1], x[margin.calc2], x[margin.calc3], use.names = T, fill = F))
    })

I think it might make more sense to have rbindlist not assign ". to l" when piped, which would reduce a small, but not insignificant amount of typing. I think it would still make sense for the function, which is taking list inputs and returning a data.table.

**Comment by MichaelChirico** [comment]
Could you add an example table with expected output? I'm not sure I get your meaning, particularly about "assign '. to I'"

**Comment by jangorecki** [comment]
I don't really understand why you decided to report non-reproducible code. In such a specific case, I would expect to have non-piping version, and expected piping version. So it would be clear what you expect, and how the data looks like.
If you are looking to add totals and subtotals to your data, be aware there is a PR [#1667](https://github.com/Rdatatable/data.table/pull/1667/files) waiting to be reviewed. It is fully functional, and should fit your use case.

**Comment by bahuber** [comment]
Apologies, this is my first time attempting to contribute to a project on GitHub. Please see examples below:
@jangorecki I'll check out that PR.

```R
test <- data.table(
  var1 = rep(letters[1:5], 2),
  var2 = rep(letters[6:7], 5),
  var3 = rep(letters[11:15], 2),
  values = 1:10
)


#Doesn't work, but is what is what I would guess the setup for use in this case would look like.

test %>%
  rbindlist(
    l = list( . ,
              .[,list(values = sum(values)),
                by = c('var1', 'var2')][,var3 := "Total"],
              
              .[,list(values = sum(values)),
                by = c('var2', 'var3')][,var1 := "Total"],
              
              .[,list(values = sum(values)), 
                by = c('var1', 'var3')][,var2 := "Total"]),
    use.names = T, fill = F
  )

# Error in rbindlist(., l = list(., .[, list(values = sum(values)), by = c("var1",  : 
# idcol must be a logical or character vector of length 1. If logical and 'TRUE' the 
# id column will automatically named '.id'. Else the column will be named with the 
# character value provided in 'idcol'.

#Works, but forces workaround
test %>%
  rbind(
    . ,
    rbindlist(
    l = list(.[,list(values = sum(values)),
                by = c('var1', 'var2')][,var3 := "Total"],
              
              .[,list(values = sum(values)),
                by = c('var2', 'var3')][,var1 := "Total"],
              
              .[,list(values = sum(values)), 
                by = c('var1', 'var3')][,var2 := "Total"]),
    use.names = T, fill = F
  ),
  use.names = T, fill = F
  )

#Works, but forces workaround
test %>%
  (function(x){
    return(rbindlist(
      l = list( x ,
                x[,list(values = sum(values)),
                  by = c('var1', 'var2')][,var3 := "Total"],
                
                x[,list(values = sum(values)),
                  by = c('var2', 'var3')][,var1 := "Total"],
                
                x[,list(values = sum(values)), 
                  by = c('var1', 'var3')][,var2 := "Total"]),
      use.names = T, fill = F
    ))
  })
'
```

**Comment by jangorecki** [comment]
@bahuber it can be simplified to
```r
f = function(l) {
    stopifnot(is.list(l), !is.data.frame(l))
    toString(unlist(lapply(l, class)))
}
test %>% f(l = list(., .))
#Error in f(., l = list(., .)) : unused argument (.)
```
Looks more like a feature request to magrittr.

If you really want piping you can have it much nicer with single wrapper:
```r
f = function(x) {
    rbindlist(
        l= list( x ,
                 x[,list(values = sum(values)),
                   by = c('var1', 'var2')][,var3 := "Total"],
                 x[,list(values = sum(values)),
                   by = c('var2', 'var3')][,var1 := "Total"],
                 x[,list(values = sum(values)), 
                   by = c('var1', 'var3')][,var2 := "Total"]),
        use.names = T, fill = F, idcol = F
    )
}
test %>% f %>% tail(3)
#   var1  var2 var3 values
#1:    c Total    m     11
#2:    d Total    n     13
#3:    e Total    o     15
```

**Comment by bahuber** [comment]
Thanks for your help, I think if I were to make the suggestion after thinking about it a bit longer, I would have posed something like this:

```R
rbindlist <- function (..., use.names = fill, fill = FALSE, idcol = NULL) {
  
  l <- list(...)

#...
}
```

For the rbindlist function, but I could see how that would at least be problematic from a backwards compatibility perspective, if not other ways.

**Comment by jangorecki** [comment]
If you mean first argument `...` instead of `l` then you may want to use `rbind` instead, also documented in `?rbindlist`.
