### ISSUE TITLE
Add CSVY support for fread() and fwrite()

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1701]
The [rio](https://github.com/leeper/rio) already [allows](https://github.com/leeper/rio/blob/e1365beec61ed79ebdf2e911f4b0375b5a1e48e8/R/import_methods.R#L160) reading of [csvy](http://csvy.org/) formats by relying on the helper package (same author) [csvy](https://github.com/leeper/csvy/blob/master/R/read_csvy.R#L17-L88). It'd be great to leverage its features to read/write.

**Comment by MichaelChirico** [comment]
Just documenting how the `.csvy` reader of `rio` works:

 1. `rio` encounters a `.csvy` file and dispatches to [`.import.rio_csvy`](https://github.com/leeper/rio/blob/master/R/import_methods.R#L158-L161)
 2. `.import.rio_csvy` calls [`read_csvy`](https://github.com/leeper/csvy/blob/master/R/read_csvy.R#L17-L88) from the [`csvy` package](https://github.com/leeper/csvy).
 3. `read_csvy` uses `readLines` to digest the file, then uses `grep` to identify the YAML header.
 4. [`yaml.load`](https://github.com/viking/r-yaml/blob/master/R/yaml.load.R) from the [`yaml` package](https://github.com/viking/r-yaml) is called to convert the YAML content string to a `list` of component parts. This is already implemented in C so is presumably efficient.
 5. `read_csv` then applies `paste(., collapse = '\n')` to the non-YAML portion of the file and can read it with `fread`.
 6. Content of YAML header is applied to the output.

Major inefficiencies are:

 - Using `readLines` to digest the whole file (slow)
 - `paste`ing the file back into a format for `fread` to tackle only after stripping out the YAML part
 - Some parts of the YAML header are intended to assist `fread`, but the YAML data is not fed into `fread`.

My proposed solution (if we decide to tackle this):

 1. Stream lines of the file until the end of the YAML header is reached (or until an out-of-format line is reached -> `stop`). I'm not sure the most efficient way to pass files line-by-line in R, or if we'll have to implement that ourselves in C. Keep track of the # of lines fed.
 2. Add `yaml` package to `Suggests` and rely on that to parse the YAML info
 3. Extract any info relevant to `fread` itself (especially/most importantly `colClasses`; I'll have to read the `csvy` standard to see how open-ended the rest is)
 4. `fread` the remainder of the file, using `skip` to jump past the YAML section, and including relevant info from the YAML.

**Comment by HughParsonage** [comment]
> I'm not sure the most efficient way to pass files line-by-line in R

`fread(file, sep = NULL)` (in dev) ?

Also `readLines` is likely to be much faster in R 3.5.0, possibly as fast as `fread` or `readr::read_lines`.

**Comment by MichaelChirico** [comment]
@HughParsonage that still leaves the issue of reading the file twice. The idea of streaming lines is to examine the file line-by-line and only read in, say, 10-20 lines of YAML metadata using `readLines` (or `fread`, or whatever) before parsing that and deploying `fread` on (presumably) the bulk of the file which follows the header

**Comment by MichaelChirico** [comment]
Progress here:

https://github.com/Rdatatable/data.table/tree/csvy_support

Merging with potentially user-supplied `colClasses` is a pain; giving up for the night

**Comment by jangorecki** [comment]
I would avoid extra dependency, even in suggests, and use some helper function to extract fields from yaml header. Similar way as we would process DESCRIPTION file. Fwrite should be able to write csvy header the way that fread can read it.

**Comment by MichaelChirico** [comment]
as yaml can be arbitrarily nested I didn't see a need to reinvent the wheel.

especially as it seems at the moment to be a rather limited use case -- happy to revisit if this format takes off.

**Comment by MichaelChirico** [comment]
`fwrite` support not done yet... will file separately
