### ISSUE TITLE
Extend forder support to 'complex' type.

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1703]

**Comment by MichaelChirico** [comment]
How do you sort a two-dimensional object? By modulus?

**Comment by arunsrinivasan** [comment]
Same way base R does it. From `?order`:

> Complex values are sorted first by the real part, then the imaginary part.

**Comment by MichaelChirico** [comment]
strange to me to say `0 + 300000000000i < 1 + i`, but as long as it's base-consistent.
