### ISSUE TITLE
library(data.table) fails if "Packaged" field is not present in DESCRIPTION

### ISSUE THREAD

**Issue by restonslacker** [Rdatatable/data.table#1706]
Recently, R seems to no longer add the "Packaged" field to DESCRIPTION when building from source. This prevents an end-user from loading the dev version because of the "staleness" check in `onAttach()`. However, "Built" is in there (at least on the systems I tested this against).  I will submit a that  PR attempts to capture that and use it as a substitute.  If that fails, it returns since this check is purely informational.

**Comment by jangorecki** [comment]
Looks like we don't have to `try()` as `read.dcf` has an argument `fields`. Check below
```r
read.dcf(system.file("DESCRIPTION", package="data.table"), fields="Packaged")
read.dcf(system.file("DESCRIPTION", package="data.table"), fields="notexistingfield")
# or even
read.dcf(system.file("DESCRIPTION", package="data.table"), fields=c("Packaged","notexistingfield"))
```
Then we can handle that with `is.na`.

**Comment by restonslacker** [comment]
there is a new commit that removes the call to `try()`

**Comment by arunsrinivasan** [comment]
Just ran into this as well. Thanks for the PR @restonslacker. Merged.
