### ISSUE TITLE
shift should accept negative n

### ISSUE THREAD

**Issue by eantonya** [Rdatatable/data.table#1708]
I think using "type = lag/lead" is a lot of unnecessary typing, and using a negative shift would be much simpler and more intuitive. It would also allow for more nifty multiple shifts going from lead to lag by typing e.g. `shift(vec, -5:5)`.

The "type" argument can still stay and negative shift would simply reverse the meaning of "type".

`n = 0` should also be accepted and simply return the original vector.

**Comment by MichaelChirico** [comment]
Could make moving-average windowing very simple

**Comment by arunsrinivasan** [comment]
Agreed that this looks much better. At the time, I added `type=` with more types in mind. Particularly `cyclic` shift. But that doesn't seem to come up much (on SO). Perhaps `type=` could be removed altogether.

**Comment by eantonya** [comment]
Having a cyclic shift would be interesting, and that would also benefit from having negative `n`'s. I agree though that it doesn't come up much - I can't think of any real life use cases right now.

**Comment by MichaelChirico** [comment]
could you elaborate what you guys have in mind with `cyclic` shift?

**Comment by franknarf1** [comment]
@MichaelChirico I think they just mean that the unused values are shifted around to "fill", like

    cyc_shift = function(x, n) c(tail(x,-n), head(x,n))

    cyc_shift(LETTERS[1:5], -2) # DEABC lag  by 2
    cyc_shift(LETTERS[1:5], 2)  # CDEAB lead by 2

**Comment by arunsrinivasan** [comment]
Michael, google for `circshift` function in Matlab.

**Comment by MichaelChirico** [comment]
Would still love to have this -- so many times I want to facilitate moving averages like `sapply(-2:2, shift, x = V1)`

**Comment by jangorecki** [comment]
Is there agreement on `-` exact mapping to `type`?
Default `type` is `"lag"`, so it make sense to treat negative `n` as `type="lead"`, while @franknarf1 example of `cyc_shift` propose the opposite.
So `n=-2` would be translated to `n=2` and `type` `"lead"` or `"lag"`?

**Comment by DavidArenburg** [comment]
I think that having negative `n` translated to `lead` would be very confusing to quite about everyone. This will bring issue/questions on SO and a lot of fuss in general IMO.

**Comment by jangorecki** [comment]
It will be more consistent to current code, as described above.
Also more conceptually when you compare output of `lag` and `lead` you can observe than `lag` adds extra elements in from of vector, while `lead` removes them. And that somehow maps to `lag -> +` and `lead -> -`.
No matter what we will decide it will be backward compatible anyway.

**Comment by DavidArenburg** [comment]
Yeah, I guess you are right if we want to keep this backward compatible. I was thinking it could be a good thing to deprecate `type` altogether, but that will break too much code.

**Comment by jangorecki** [comment]
We can just map it change `n` argument, so we don't need to support type in C api. Also mention in docs to not use `type`. Then after few years should be safe to add warning and after another few to error.

**Comment by jaapwalhout** [comment]
I'm not sure if it would be confusing. Maybe at first, but people will get used to it. As @eantonya said: *The "type" argument can still stay and negative shift would simply reverse the meaning of "type".*. Which could facilitate a transition period.

`stats::lag` also accepts negative values to get a lead, so why couldn't `shift`? `shift(vec, -5:5)` is a lot easier than `sapply(-5:5, shift, x = vec)`. Furthermore, using `sapply` in those use cases possibly introduces extra overhead. 

@jangorecki  I would use negative values to get a lead, which makes it consistent with `stats::lag`.

**Comment by MichaelChirico** [comment]
i think because it's ambiguous it makes sense to keep so that code can be more readable. `shift(x, 1, type = 'lead')` in anyone's code can instantly be understood, I think.

Unless we want to go the `NAMESPACE`-heavy route & add alias functions `lead` and `lag`.

That said, I think most of the use cases involving mixed indices are of the form `-n:n` for which `type` is irrelevant

**Comment by jangorecki** [comment]
I don't see anything in name `shift`, good thing is that it is not masking other functions, thus better to keep that instead of `lag`. Eventually `flag` for _fast-lag_, but `shift` is pretty fine. Lets put it into 1.12.0.

**Comment by franknarf1** [comment]
> Default type is "lag", so it make sense to treat negative n as type="lead", while @franknarf1 example of cyc_shift propose the opposite.

That looks like a typo on my part; sorry for the confusion.
