### ISSUE TITLE
colA:colB syntax should also work on LHS of LHS := RHS

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1710]
``` r
require(data.table)
dt = data.table(x=c(2,2,2,1,1,1), a=1, b=2, c=3)

dt[, lapply(.SD, sum), by=x, .SDcols=a:c]
#    x a b c
#1: 2 3 6 9
#2: 1 3 6 9
```

This way of specifying `start:end` also works with `by=`. It'd be great to get this to work on `LHS`.

**Comment by eantonya** [comment]
Related - also allow `list`/`.` syntax on LHS: `dt[, .(a, b, c) := as.list(1:3)]`.

**Comment by franknarf1** [comment]
Also, the `!cols` syntax, I think. Just ran into that here: http://stackoverflow.com/a/42301797/ where I can use `.SDcols = !k` but have to use `setdiff(names(res), k)  :=`

**Comment by MichaelChirico** [comment]
I think we can just use `names(.SD)` on the LHS now, seems easier than introducing more NSE complications in `j`:

```r
dt[, names(.SD) := lapply(.SD, sum), by=x, .SDcols=a:c]
dt
#        x     a     b     c
#    <num> <num> <num> <num>
# 1:     2     3     6     9
# 2:     2     3     6     9
# 3:     2     3     6     9
# 4:     1     3     6     9
# 5:     1     3     6     9
# 6:     1     3     6     9
```
