### ISSUE TITLE
Try to understand why `mget()` doesn't work here? 

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1712]
``` r
require(data.table)
dt = data.table(x=c(1,1,2,2,2), y=1, z=2)
vv = 6

dt[, get("vv")] # works fine

# ?!?!?
dt[, mget("vv")]
# Error: value for ‘vv’ not found
```

Is this a bug? Haven't had time to look into it yet.

**Comment by MichaelChirico** [comment]
Yea something's pretty messed up...

I get `SDenv$.SDall` to be:

```
#    x y z x.x x.y x.z
# 1: 1 1 2   1   1   2
# 2: 1 1 2   1   1   2
# 3: 2 1 2   2   1   2
# 4: 2 1 2   2   1   2
# 5: 2 1 2   2   1   2
```

No way it should be calculating all that!

**Comment by DavidArenburg** [comment]
This is simply because `get` has `inherits = TRUE` as default while `mget` has `inherits = FALSE` as default. Hence both `dt[, mget("vv", inherits = TRUE)]` and `dt[, mget("vv", envir = as.environment(1))]` work, eh?

**Comment by MichaelChirico** [comment]
That handles that... curious that they have different defaults, any guesses why? Nothing in the dox.

**Comment by arunsrinivasan** [comment]
@DavidArenburg great! Thanks.

**Comment by DavidArenburg** [comment]
NP, @arunsrinivasan. But why do you think it's a bug? It has nothing to do with `data.table` and this a documented behavior in base R

**Comment by arunsrinivasan** [comment]
Actually, it has everything to do with data.table. `mget()` for data.table should be consistent with what one expects within the frame of a data.table, however inconsistent base R is between `get()` and `mget()`.

**Comment by MichaelChirico** [comment]
So you plan to overload `mget` within `data.table`? Or silently add `inherits = TRUE` when detecting `mget` in `jsub`?

Neither seem ideal to me...

**Comment by arunsrinivasan** [comment]
`inherits=TRUE`.

**Comment by MichaelChirico** [comment]
I think it'd be pretty complicated in general to handle this. Tried a simple approach of treating `mget` like `strptime` and defining `SDenv$mget`:

```
  SDenv$mget = function(...) {
    if ('inherits' %chin% names(list(...))) mget(...) else mget(..., inherits = TRUE)
  }
```

But this doesn't work as hoped. Unless there's something simple I'm missing I'd say we abandon this

**Comment by jangorecki** [comment]
I agree with Michael that it does seems to complicated to handle that. We already know that `inherits` was responsible for a difference in question. I would advise to use a more general substitution #4304 rather than lookup up symbols in frames via get/mget. Please re-open if you do not agree.
