### ISSUE TITLE
Think about how to bring melt/dcast functionality on to `[]` syntax...

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1714]

**Comment by MichaelChirico** [comment]
FWIW I already do this all the time, with `.SD`:

`dcast(DT, formula, ...)`

becomes

`DT[ , dcast(.SD, formula, ...)]`

If it's possible, `DT[ , dcast(formula, ...)]` seems natural as well...

**Comment by MichaelChirico** [comment]
Closing this pending something more specific about what's needed here.
