### ISSUE TITLE
Warning: Already keyed by this key but had invalid row order, key rebuilt.

### ISSUE THREAD

**Issue by Christoph999** [Rdatatable/data.table#1720]
I got the following warning message:
1: In setkeyv(x, cols, verbose = verbose, physical = physical) :
  Already keyed by this key but had invalid row order, key rebuilt. If you didn't go under the hood please let datatable-help know so the root cause can be fixed.

What is wrong? Is it critical?

**Comment by jangorecki** [comment]
are you able to reproduce it?

**Comment by Christoph999** [comment]
I ran the simulation and it appeared again. In my code a function is called frequently which does the following:

tmp <- data.table::data.table(newdata)
  data <- rbindlist(list(data, tmp))
  data <- routes[order(pars)] # pars are four parameters, each listed separatedly.
  data.table::setattr(data, "sorted", c("pars"))
  data.table::setkey(data, pars)

Just let me know, if you need further information.

**Comment by franknarf1** [comment]
You should use `setattr(data, "sorted", pars)` not `setattr(data, "sorted", c("pars"))`

**Comment by Christoph999** [comment]
This is how I did it: data.table::setattr(data, "sorted", c("lat1", "lng1", "lat2", "lng2")).

**Comment by jangorecki** [comment]
any reason why you are setting `sorted` attribute manually instead of using `setkey` or `setkeyv`?

**Comment by Christoph999** [comment]
No. This was the version I made running. Any suggestions for improvements are highly appreciated. 
Is this related to the warning?

**Comment by jangorecki** [comment]
Yes, warning is related to setting order manually. Use `setkey` or `setkeyv`, it will set `sorted` attribute for you. Also you don't need to access `sorted` attribute manually as there is `key` function for that. You can close the issue if your issue is solved.

**Comment by Christoph999** [comment]
Thus, the following 3 lines should be enough:
tmp <- data.table::data.table(newdata)
data <- rbindlist(list(data, tmp))
data.table::setkey(data, pars)
And data is ordered = sorted?

**Comment by franknarf1** [comment]
Well, it is sorted unless pars has floating point columns with differences in their latter bits, as complained loudly about here: https://github.com/Rdatatable/data.table/issues/1642

**Comment by jangorecki** [comment]
Yes, that should be enough. If you sort high precision *double* columns you may want to add `setNumericRounding(0)` command.

**Comment by Christoph999** [comment]
I ran the code twice using my privious version and the version below (No rounding). No errors appeared, so it seems to be fine. I would be great, if somebody could state, whether you would expect the following code to work fine (Appart from issue #1642):

tmp <- data.table::data.table(newdata)
data <- rbindlist(list(data, tmp))
setNumericRounding(0)
data.table::setkey(data, pars)

I run this script in a function each time "newdata" is added!
If this is the way you should use data.table, you can close the issue. Thank you for your help.

**Comment by franknarf1** [comment]
@Christoph999 As noted in the linked issue, setNumericRounding of zero might have bad side effects when joining on the float col:

    library(data.table)
    setNumericRounding(0)
    DT = data.table(a = c(.3, .1 + .2), key="a")
    DT[.(.3), .N] # 1 row, "should" be 2

So if you're doing this inside a function, you probably want to `setNumericRounding(2)` (the default value) after sorting/keying the table.

**Comment by Christoph999** [comment]
Ok. Thank you for making that clear:-)

**Comment by Christoph999** [comment]
Ok. Thank you for making that clear:-)

**Comment by arunsrinivasan** [comment]
Please do *NOT* set the `sorted` attribute by yourself, unless you are 100% sure if the table is sorted. It is best to avoid such hacks. `setkey()` checks for orderedness at first and returns the table as such if it is already ordered (which is admittedly O(n) op but better to be safe).

**Comment by Christoph999** [comment]
@arunsrinivasan: To be honest, I was quite unsure about what is actually really needed and when it is needed. Did I miss that in the documentation? Assume I have a program looking like

library(data.table)
data <- data.table::data.table(lat1 = numeric(0), ...)
data.table::setkey(routes, lat1, lng1, lat2, lng2)

**for loop starts here...**
data.table::setkey(data, pars) **# needed again?**
tmp <- data.table::data.table(newdata)
data <- rbindlist(list(data, tmp))
data.table::setkey(data, pars) **# needed again?**

I think I am still not sure about what changing by reference is, although I tried to get through this: http://stackoverflow.com/questions/10225098/understanding-exactly-when-a-data-table-is-a-reference-to-vs-a-copy-of-another

**Comment by jangorecki** [comment]
Intent of your program is a mystery at the moment. Pseudo code isn't very helpful. Why do you sort data in each iteration of loop? Any problem in rbinding all your datasets and then sort them once? Numeric rounding does not have much affect on performance, if you have an example where it makes 10x difference please provide reproducible code. You don't have to change the numeric rounding if you are not sorting on *double* data types, this is a consequence of using floating point data type (discussed in issue linked by Frank). Also be aware there are vignettes listed in [Getting started](https://github.com/Rdatatable/data.table/wiki/Getting-started) page which may address your concerns. If you find something not clear there, you can always suggest an improvement.

**Comment by Christoph999** [comment]
@jangorecki: Here are some explanations to the crucial parts:
We simulate processes in the field of logistics. There, we calculate routes with osrm which is slow and therefore store the routes found somewhere for fast access (See also the post [here](http://stackoverflow.com/questions/37026669/r-fast-hash-search-in-lists-environment) ). 

Thus, we initialise our simulation in a first run (empty list)
    data <- data.table::data.table(par1 = numeric(0), ...)
    data.table::setkey(data, pars)
We now use `setkey` because we want the list sorted for very fast access (binary search).

Then we step through "traveling history" which contains about 2e5 routes. 
At some point we have calculated "all" routes and the remaining task is to just find the route in the list. 
However, if we hit an unknown route, we calculate it and add it to our "database":
      data.table::setkey(data, pars)
      tmp <- data.table::data.table(newdata)
      data <- rbindlist(list(data, tmp))
      data.table::setkey(data, pars) 
If the data = routes are not sorted, the code is incredibly slow. This is the reason why we want to sort every time.

I read the vignette, but was not sure when, where and how often I should place `setkey`. (I am still quite new to R...). As said: **If I don't use binary search, a run takes 15 h instead of 15 minutes.**

I highly appreciate your suppport!!! :-)

**Comment by jangorecki** [comment]
That gives some more insight to your case, but be aware the better place for such higher level logic inquiries could be stackoverflow using `data.table` tag. If you utilize the key inside every iteration in a loop then it make sense to set the key there. Be aware there are also secondary keys available (indices) which doesn't require to physically sort the data.

**Comment by arunsrinivasan** [comment]
I agree with @jangorecki (that this is more appropriate Q for SO). 

Read the SO post: [what-is-the-purpose-of-setting-a-key-in-data-table](http://stackoverflow.com/a/20057411/559784). Also please read the new [Secondary Indices](https://github.com/Rdatatable/data.table/wiki/Getting-started) vignette as well which highlights the advantages of using them instead of keying data.tables, and when keying is useful.
