### ISSUE TITLE
:= should as.POSIXct when RHS is POSIXlt

### ISSUE THREAD

**Issue by linzhp** [Rdatatable/data.table#1724]
I am able to add a POSIXct column to a data.frame, but not data.table.

``` R
data <- read.table(header=TRUE, text='
 id weight
  1     20
  2     27
  3     24
')
dates <- c(strptime('160523-1600', '%y%m%d-%H%M'),strptime('160523-1600', '%y%m%d-%H%M'),strptime('160523-1600', '%y%m%d-%H%M'))
dt <- data.table(data)
# This works well
data$dates <- dates
# This results in an error
dt$dates <- dates
```

The error message I get is:

> Warning message:
> In `[<-.data.table`(x, j = name, value = value) :
>   Supplied 11 items to be assigned to 3 items of column 'dates' (8 unused)

And the `dates` field is not properly assigned to `dt`.

**Comment by franknarf1** [comment]
I think the recommended way is

    dt[, dates := as.POSIXct(dates)]

I think data.table doesn't like POSIXlt cols, judging by `dt[, .(dates)]` giving

> Error in setDT(jval) : 
> Column 1 is of POSIXlt type. Please convert it to POSIXct using as.POSIXct and run setDT again. We do not recommend use of POSIXlt at all because it uses 40 bytes to store one date.

**Comment by arunsrinivasan** [comment]
I could have sworn that I fixed `dt[, date := dates]` to automatically convert to `POSIXct` and issue a warning..

**Comment by linzhp** [comment]
I am using version 1.9.6, and `dt[, date := dates]` still gives me an error. Was the fix made after 1.9.6?

**Comment by arunsrinivasan** [comment]
What I meant was `dt[, date := dates]` doesn't seem to be working as intended.

**Comment by pseemakurthi** [comment]
Date col is being converted as a number when writing the file to disc using fwrite()
I'm not sure if someone already reported the abovee bug
