### ISSUE TITLE
fwrite crashes RStudio when na argument is passed

### ISSUE THREAD

**Issue by contefranz** [Rdatatable/data.table#1725]
I am using R v. 3.3.0 and RStudio 0.99.1197. The session crashes when the argument `na` is passed to `fwrite()`. Here is the minimal:

```{r}
dt = data.table( a = 1:10, b = letters[ 1:10 ] )

# working with message:
# Your platform/environment has not detected OpenMP support. 
# fwrite() will still work, but slower in single threaded mode.
fwrite( dt, '~/Desktop/test.csv' )

# NOT WORKING 
fwrite( dt, '~/Desktop/test.csv', na = NA )
```

Is there anyone who's experiencing this? 
Thanks in advance

**Comment by arunsrinivasan** [comment]
The argument needs to be a string. `na = "NA"` works. We need to make sure to convert to string before calling the C-function.
