### ISSUE TITLE
Use alloc.col in setDT() even if setlfrefok > 0

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1731]
Fix for http://stackoverflow.com/q/37667922/559784

Not sure if that'll fix this issue though. IIUC the problem is that the argument to `[.data.table` is not a symbol and therefore assignment back to parent frame wouldn't be happening.

**Comment by MichaelChirico** [comment]
OP here was doing bad things, doesn't seem to have been a common issue in the meantime. Closing.
