### ISSUE TITLE
Row operations in data.table using `by = .I`

### ISSUE THREAD

**Issue by rafapereirabr** [Rdatatable/data.table#1732]
I was exploring alternatives of [how to do row operations in `data.table`](http://stackoverflow.com/questions/37667335/row-operations-in-data-table-using-by-i) and I think I've found a bug.

These three lines of code should return the same result. However, the result of `by = .I` seems return a wrong result.

`dt[, sdd := sum(.SD[, 2:4, with=FALSE]), by = 1:NROW(dt) ]`
`dt[, rowpos := .I][ ,  sdd := sd(.SD[, -1, with=FALSE]), by = rowpos ]`
`dt[ ,  sdd := sd(.SD[, -1, with=FALSE]), by = .I ]`

sample data:
`dt <- data.table(V0 =LETTERS[c(1,1,2,2,3)],
                 V1=1:5,
                 V2=3:7,
                 V3=5:1)`

**Comment by eantonya** [comment]
Alternatively, `by = .I` should give an error, though it would be nice to have it work with an `i-expression` present.

Similar issue with using `.N` in `by` (again smth one might naively try - `dt[, ..., by = 1:.N]`).

**Comment by leoluyi** [comment]
Why not just add feature "rowwise" by using `by = .I`, which sounds intuitive.

#1063

**Comment by rafapereirabr** [comment]
Hi @leoluyi , 

the behaviour of `by = .I` is equivalent to `by = NULL` . Have a look at this SO discussion [https://stackoverflow.com/questions/37667335/row-operations-in-data-table-using-by-i](https://stackoverflow.com/questions/37667335/row-operations-in-data-table-using-by-i)

**Comment by rafapereirabr** [comment]
Thank you all. This is extremely helpful ! I may have found a small bug though. `by = .I` seems to work with `sum()` operation but it throws and error with a `sd()` operation.  See the reprex below.

```
library(data.table)

dt <- data.table(V0 =LETTERS[c(1,1,2,2,3)],
                 V1=1:5,
                 V2=3:7,
                 V3=5:1)

# it works with sum operation
dt[ ,  ssum := sum(.SD[, -1, with=FALSE]), by = .I ] 
dt
>    V0 V1 V2 V3 ssum
> 1:  A  1  3  5   55
> 2:  A  2  4  4   55
> 3:  B  3  5  3   55
> 4:  B  4  6  2   55
> 5:  C  5  7  1   55

# id does NOT work with standard deviation operation
dt[ ,  sdd := sd(.SD[, -1, with=FALSE]), by = .I ] 

> Error in is.data.frame(x) : 
>   'list' object cannot be coerced to type 'double'
```

**Comment by ben-schwen** [comment]
@rafapereirabr 

Both work for me on `dev.version`.

``` r
library(data.table)

dt = data.table(V0 =LETTERS[c(1,1,2,2,3)], V1=1:5, V2=3:7, V3=5:1)

dt[,  sum(.SD[, -1, with=FALSE]), by = .I]
#>        I    V1
#>    <int> <int>
#> 1:     1     9
#> 2:     2    10
#> 3:     3    11
#> 4:     4    12
#> 5:     5    13
dt[,  sd(.SD[, -1, with=FALSE]), by = .I]
#>        I       V1
#>    <int>    <num>
#> 1:     1 2.000000
#> 2:     2 1.154701
#> 3:     3 1.154701
#> 4:     4 2.000000
#> 5:     5 3.055050
```

What's your output for `sessionInfo()` ?
