### ISSUE TITLE
Can't assign NA for a factor

### ISSUE THREAD

**Issue by Zus** [Rdatatable/data.table#1740]
When trying to assign NA to a specfic items in a factor, an error is thrown, which does not happen in base DF.

```r
require(data.table)
DT <- data.table(x = 1:5,y = factor(c("","a","b","a", "")), z = 5:9)
DT[y==""]
DT[y=="", y := NA] # throws an error, interpreted as logical
DT[y=="",y] <- NA # throws an error
```

R 3.3.0 DT 1.96

**Comment by jangorecki** [comment]
It works if you provide a factor type value on RHS of `:=`:
```r
DT[y=="", y := as.factor(NA)]
```
But I agree to make sense to catch that automatically.

**Comment by arunsrinivasan** [comment]
It was expecting an integer (`NA_integer_`). But the coercion is handled on logical types as well.
