### ISSUE TITLE
maxgap and minoverlap from foverlpas function

### ISSUE THREAD

**Issue by Chudar-Arivu** [Rdatatable/data.table#1741]
Hi,

The maxgap and minovelap parametres infoverlaps function didnt seem to be implemented in data.table 1.9.6. Is there an updated version of data.table already out or should we have wait for updates. I really want to make use of maxgap option in foverlaps function.

Kindly guide me

**Comment by jangorecki** [comment]
Hi, it wasn't yet implemented, you can subscribe to issue #528 to be up to date on that feature.
