### ISSUE TITLE
Inequality for strings

### ISSUE THREAD

**Issue by ladida771** [Rdatatable/data.table#1742]
DT <- data.table(title=c('A','B','C'))
DT <- DT[3,title:=NA]
DT <- DT[title!='A',]

Intuitively expecting:
   title
1:     B
2:    NA

Getting:
   title
1:     B

**Comment by CJBarry** [comment]
It is because `NA != "A"` is `NA`.  For a vector:

`v <- LETTERS[1:3]
v[c(F, T, NA)]`

gives: `[1] "B"  NA`.  Data table subsetting seems to treat `NA`s like `FALSE`.  With a vector or a data frame, an `NA` in a logical subsetting vector always returns `NA` (e.g. try with `setDF(DT)` and try again).

**Comment by franknarf1** [comment]
First, don't use an arrow to assign the result after modifying by reference (in your second line). You'll probably need to read [the vignettes](https://github.com/Rdatatable/data.table/wiki/Getting-started) before you can use the package productively.

I asked a similar question when I started with data.table and got good answers: http://stackoverflow.com/questions/16221742/subsetting-a-data-table-using-some-non-na-excludes-na-too In his answer, Matt mentioned something about making a FR to include NA in the results for a query like this, but it looks like it hasn't been changed. I'm fine with the current behavior now.

**Comment by ladida771** [comment]
A link shared by franknarf1 fully explains the problem. Yet, most would probably agree that there is some inconsistency in the syntax which is very dangerous for a non-power user.

**Comment by arunsrinivasan** [comment]
Not having NA is a more common scenario and avoids having to type `& !is.na(.)` every time. Subsets therefore don't return NA rows by default. This is a design choice. If you'd like to return NA rows as well, then:

```r
DT <- DT[title != "A" | is.na(title)]
```
should do it. This behaviour is similar to `subset()` in base R.
