### ISSUE TITLE
Strange problem involving data.table, profvis() and mclapply()

### ISSUE THREAD

**Issue by costis-t** [Rdatatable/data.table#1745]
**Briefly:** 
There seems to be something wrong with `.internal.selfref` of a loaded with `readRDS()` data.table when I try to use `mclapply()` inside `profvis()`, but I am not sure which one of the 3 involved packages has the problem.

Even with a data.table of 8 rows, this functions takes forever (I must kill R):
```R
it.stalls <- function() {
 unique.x <- unique(DT$a)
 profvis({
 assign.me <- setNames(mclapply(unique.x, function(uniquex) {
            DT[a == uniquex]
            subset.DT <- DT[a == uniquex]
            print(paste0(uniquex, ' - ', nrow(subset.DT))) 
            paste0(uniquex, ' - ', nrow(subset.DT))
   }, mc.cores = 4), unique.x)
 })
}
```
Inside `profvis()`, `lapply()` (instead of mclapply()) works fine, but not `mclapply()`.
When I do comment out `profvis()`, both `mclapply()`/`lapply()` work fine. 

**How to reproduce?**
This is the difficult part.
`~/dataset.rds` is very large, so to make readable `dput()` output I subset it. 
```R
library(profvis)
library(data.table)
library(parallel)
DT <- readRDS('~/dataset.rds')
alloc.col(DT) # I do not know if this is good practice, is it? with or without it, the  problem persists...
DT <- DT[a <= 10002 & Day <= 1][, .(a, Day)][c(1:4, 438:441)]
nrow(DT)
# [1] 8
saveRDS(DT, '~/savedDT.rds')
```
`dput(DT)` shows:
```R
structure(list(a = c(10000L, 10000L, 10000L, 10000L, 10002L, 
10002L, 10002L, 10002L), Day = c(1, 1, 1, 1, 1, 1, 1, 1)), .Names = c("a", 
"Day"), class = c("data.table", "data.frame"), row.names = c(NA, 
-8L), .internal.selfref = <pointer: 0x1625c68>)
```
When I run:
```R
it.stalls() # it.stalls!
```
it takes forever and only one core works at 100%.

At this point, if instead of calling `it.stalls()`,  I open a new R session , I can normally run:
```R
library(profvis)
library(data.table)
library(parallel)
DT <- readRDS('~/savedDT.rds')
dput(DT)
structure(list(a = c(10000L, 10000L, 10000L, 10000L, 10002L, 
10002L, 10002L, 10002L), Day = c(1, 1, 1, 1, 1, 1, 1, 1)), .Names = c("a", 
"Day"), class = c("data.table", "data.frame"), row.names = c(NA, 
-8L), .internal.selfref = <pointer: (nil)>)
it.stalls() # does not stall anymore!
```
If I remain in the previous session and I load the small `~/savedDT.rds`, *before* I run `it.stalls()`, then the two `dput()` outputs seem identical (in the old and the new session I see `.internal.selfref = <pointer: (nil)>`. Nevertheless, I still encounter problem in the old session!

Last, `attributes(DT)$.internal.selfref <- NULL`, does not seem to help...

```R
sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] data.table_1.9.6 profvis_0.3.2   

loaded via a namespace (and not attached):
[1] htmlwidgets_0.6 magrittr_1.5    tools_3.3.0     htmltools_0.3.5
[5] Rcpp_0.12.5     stringi_1.0-1   stringr_1.0.0   digest_0.6.9   
[9] chron_2.3-47
```

**Comment by jangorecki** [comment]
Thanks for the report. I was able to nail it down to. It isn't related to loading from disk, and also is not related to profiling code. It seems to be related only to parallel processing.
```r
library(data.table)
library(parallel)
x <- data.table(a=1:2, b=1:4)
f <- function(mc.cores = 4, threads = 4) {
    setthreads(threads)
    mclapply(unique(x$a), function(ua) {
        x[a == ua, sum(b), a]
    }, mc.cores = mc.cores)
}
f(1, 1) # ok
f(4, 1) # ok
f(1, 4) # ok
f(4, 4) # stuck
```

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
```

**Comment by mgahan** [comment]
Good catch @jangorecki and @costis-t . This issue was causing me lots of problems, but this setting the threads fixed it for me.

**Comment by fruce-ki** [comment]
I've been catching up with the documentation and news and I found out there is a setDTthreads() function, so that makes my life a lot easier than I anticipated.
I also saw mention that DT automatically switches to single threaded operation inside mclapply calls? Does that mean I don't have to make any modification to my code at all? What is the recommended practice?

Thank you!
