### ISSUE TITLE
Error when using large numerics

### ISSUE THREAD

**Issue by amwill04** [Rdatatable/data.table#1747]
Given a data frame and converting to `data.table` with `as.data.table()`

```
df <- structure(list(A = c(10000000007624, 10000000007619, 10000000007745, 
10000000007624, 10000000007767, 10000000007729, 10000000007705, 
10000000007711, 10000000007784, 10000000007745, 10000000007624, 
10000000007762, 10000000007762, 10000000007631, 10000000007762, 
10000000007619, 10000000007628, 10000000007705, 10000000007762, 
10000000007624, 10000000007745, 10000000007706, 10000000007767, 
10000000007777, 10000000007624, 10000000007745, 10000000007624, 
10000000007777, 10000000007771, 10000000007631, 10000000007624, 
10000000007640, 10000000007642, 10000000007708, 10000000007711, 
10000000007745, 10000000007767, 10000000007655, 10000000007722, 
10000000007745, 10000000007762, 10000000007771, 10000000007617
), B = c(4060697L, 7683673L, 7699192L, 1322422L, 7754939L, 7448486L, 
2188027L, 1061376L, 2095950L, 7793530L, 2095950L, 6447861L, 2188027L, 
7448451L, 7428427L, 7516354L, 7067801L, 2095950L, 6740142L, 405911L, 
4057215L, 1061345L, 7754945L, 7501748L, 2188027L, 7780980L, 6651988L, 
6649330L, 6655118L, 6556367L, 6463510L, 2347462L, 7675114L, 6556361L, 
1061345L, 7224099L, 6463515L, 2188027L, 6463515L, 7311234L, 7764971L, 
7224099L, 2347479L), C = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 
3L, 3L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 25L, 2L, 1L, 2L, 
1L, 1L, 1L)), .Names = c("A", "B", "C"), row.names = c(NA, -43L
), class = "data.frame")

library(data.table)

df <- as.data.table(df)
```

I am trying to cast from long-to-wide using `dcast.data.table()` function with the following

```
output <- dcast.data.table(df, A ~ B, value.var = "C",
                           fun.aggregate = sum, fill = NA)
```

Column `A` consists of large numeric values with a total of 20 unique values in this example, However the output produced by the above example only produces a `data.table` with 2 rows when I am expecting a 20 by 36 data frame. This issue does not occur when using `dcast()`.

Question as been raised on [SO](http://stackoverflow.com/questions/37941867/error-with-large-numerics-in-dcast-data-table) and was asked to test the development version of `data.table`.

Error occurs on both that and `CRAN` release version.

Other system info is the following:

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.7

loaded via a namespace (and not attached):
[1] tools_3.3.0
```

**Comment by jangorecki** [comment]
You can achieve what you expect by setting `setNumericRounding(0)` before dcast. I tried your dcast call with reshape2 but it gives error `Error in vapply(indices, fun, .default) : values must be type 'logical',
 but FUN(X[[3]]) result is type 'integer'`. Also if you are using big integer we recommend to use `bit64` package instead of double type. Otherwise you can end up with platform specific behavior of your code. I don't think it make sense to change dcast to not use rounding for double data type, as it is a grouping step in the process, and grouping of double type should use rounding. Feel free to re-open in case of doubts.
