### ISSUE TITLE
patterns only looks in the global environment for variables

### ISSUE THREAD

**Issue by kendonB** [Rdatatable/data.table#1749]
Using a previously defined variable inside ``patterns`` fails when done inside a user-written function.

```r
require(data.table)
DT <- data.table(
  i_1 = c(1:5, NA), 
  i_2 = c(NA,6,7,8,9,10), 
  f_1 = factor(sample(c(letters[1:3], NA), 6, TRUE)), 
  f_2 = factor(c("z", "a", "x", "c", "x", "x"), ordered=TRUE), 
  c_1 = sample(c(letters[1:3], NA), 6, TRUE), 
  d_1 = as.Date(c(1:3,NA,4:5), origin="2013-09-01"), 
  d_2 = as.Date(6:1, origin="2012-01-01"))
# add a couple of list cols
DT[, l_1 := DT[, list(c=list(rep(i_1, sample(5,1)))), by = i_1]$c]
DT[, l_2 := DT[, list(c=list(rep(c_1, sample(5,1)))), by = i_1]$c]

# NEW FEATURE: measure.vars can be a list
# melt "f_1,f_2" and "d_1,d_2" simultaneously, retain 'factor' attribute
# convenient way using internal function patterns()
tmp <- function(dt){
  patt <- c("^f_", "^d_")
  melt(dt, id=1:2, measure=patterns(patt), value.factor=TRUE)
}
tmp(DT)
# Error in unlist(list(...), use.names = FALSE) : object 'patt' not found 
```

**Comment by jangorecki** [comment]
@kendonB Did you read [`?data.table::patterns`](http://jangorecki.gitlab.io/data.table/library/data.table/html/patterns.html)?

**Comment by franknarf1** [comment]
@jangorecki Even knowing what's written there, I think what they're asking for is a reasonable FR. (Not sure if you meant something else by posting that link.)

The feature is for convenience, but is not yet convenient to use programmatically. Looking at `melt`, I guess this would just require tweaking the environment of the `eval(measure.sub)` call somehow... or just not `eval` it at all? 

As a workaround, the OP could recreate the behavior of `patterns`:

    tmp <- function(dt){
        patt <- c("^f_", "^d_")
        melt(dt, id=1:2, measure=lapply(patt, grep, names(dt)), value.factor=TRUE)
    } 
    tmp(DT)
