### ISSUE TITLE
subsetting problem

### ISSUE THREAD

**Issue by joemliang** [Rdatatable/data.table#1750]
data.table seems to have problem doing subsetting. 

~~~~
> atable = data.table(a=c(978073763135, 978073763138, 978073763136))
> atable[a == 978073763135]
              a
1: 978073763135
2: 978073763138
3: 978073763136
> 978073763135 == 978073763136
[1] FALSE
> 978073763135 == 978073763138
[1] FALSE
~~~~

**Comment by jangorecki** [comment]
You are subsetting on big integer storing them as floating point data type. Doing so you can end up with platform specific code. We recommend to use `bit64` data type in such case. If you still want use floating point type you can set `setNumericRounding(0)`.
