### ISSUE TITLE
NOT select in data.table `j` expression

### ISSUE THREAD

**Issue by ywhuofu** [Rdatatable/data.table#1759]
I wonder if there is a simple way to accomplish the following in `j` express instead of through `.SDcols`?
```
x = data.table(A=1:10, B=11:20, C=21:30)
x[, .SD, .SDcols=-'A']
```

**Comment by franknarf1** [comment]
You mean `x[, !"A", with=FALSE]` or `x[, -"A", with=FALSE]`?

**Comment by ywhuofu** [comment]
@franknarf1 Thanks !
