### ISSUE TITLE
CsubsetDT could remove indices

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1762]
`CsubsetDT` could remove indices the same way as it removes key when doing subset. Two methods `na.omit` and `unique` are currently removing indices after making call to `CsubsetDT`. IMO better to have that in the same place where subset is actually produced.

**Comment by jangorecki** [comment]
AFAIU this has been solved by [commit 20d ago](https://github.com/Rdatatable/data.table/blame/05c512253e265dcc05f66cf5cdf25a440d10d8d0/src/subset.c#L284). @mattdowle please confirm and close

**Comment by mattdowle** [comment]
@jangorecki Yes exactly.
