### ISSUE TITLE
week() does not return actual calendar week

### ISSUE THREAD

**Issue by STATWORX** [Rdatatable/data.table#1765]
Hi,

the week() function does not return the actual calendar week (what I think most users expect).
Please fix or rename function since a lot of users are expecting a different result.

Thank you!

Example:

```
### Packages
library(data.table)
library(lubridate)

### Thursday, 7th january 2016, calendar week 1
my_date <- as.Date("2016-01-07", format = "%Y-%m-%d")

### Week from data.table
data.table::week(my_date)
> 2 # not what most people would expect

### Week from lubridate
lubridate::isoweek(my_date)
> 1 # as expected
```

**Comment by MichaelChirico** [comment]
please include the output -- I'm not at a machine so I can't tell what you see/expect.

For now, please see the relevant code and I particular the preceding comment section:

https://github.com/Rdatatable/data.table/blob/master/R/IDateTime.R

**Comment by MichaelChirico** [comment]
see also #1658 which i imagine is related

**Comment by STATWORX** [comment]
Updated the example. Actually, the week() produces this: "Weeks is the number of complete seven day periods that have occured between the date and January 1st, plus one..."(see http://stackoverflow.com/questions/27116645/r-week-function-returns-unexpected-values). I think that this is an unexpected return that a lot of users are not aware of.

**Comment by DavidArenburg** [comment]
According to you, what will most users expect for `"2016-01-08"`? Both `lubridate` and `data.table` will return `2`, while according to [this](http://whatweekisit.org/) for instance, first week is until `2016-01-10`. Did you actually looked at the source code of `data.table::week(my_date)` and `lubridate::week(my_date)`? They are almost identical with a small change (which was implied by @MichaelChirico already) simple base R code which you could easily understand exactly what it's doing.

**Comment by STATWORX** [comment]
OK, you're right. `lubridate:week()` and `data.table::week()` are almost identical. Just checked the source code. Issue updated. We're using the `lubridate:isoweek()` function now for the actual calendar week.

**Comment by arunsrinivasan** [comment]
Thanks @STATWORX for filing the issue. Perhaps we'll need an isoweek as well. Good to know.

**Comment by arunsrinivasan** [comment]
@MichaelChirico do you think you've some time to look up into `isoweek`?

**Comment by MichaelChirico** [comment]
sure, why not =D
