### ISSUE TITLE
implement `diffid`

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1767]
This sort of Q comes up frequently on SO.

Given `dt` as shown below:

``` r
require(data.table)
dt = data.table(x=c(1,2,3,4,2,6,10,3,4,5,6), y=1:11)
#      x  y
#  1:  1  1
#  2:  2  2
#  3:  3  3
#  4:  4  4
#  5:  2  5
#  6:  6  6
#  7: 10  7
#  8:  3  8
#  9:  4  9
# 10:  5 10
# 11:  6 11
```

get `sum(y)` by generating a unique group for those values that are consecutive and are in increasing order.

i.e., `1,2,3,4 -> 1`, `2,6,10` -> 2, `3,4,5,6` -> 3.

The result should be:

```
data.table(diffid=c(1:3), sumy=c(10L, 18L, 38L))
#    diffid sumy
#1:      1   10
#2:      2   18
#3:      3   38
```

This should also work a) within multiple identifier cols, and b) under a fixed duration of difference within consecutive values.

**Comment by cronacronis** [comment]
Is it what you are looking for?
```
fn_splitter <- function(vec_)
{
	ids_splits <-  c(1, (which(diff(vec_) < 0) + 1))
	num_groups <-  length(ids_splits)
	group_marker <- numeric(length(vec_))
	group_marker[ids_splits] <- 1
	factor(cumsum(group_marker))
}

IncreasingSplit = function(vec_) {
	split(vec_, fn_splitter(vec_))
}

> IncreasingSplit(c(1, 2, 3, 4, 2, 6, 10, 3, 4, 5, 6))
$`1`
[1] 1 2 3 4

$`2`
[1]  2  6 10

$`3`
[1] 3 4 5 6

> fn_splitter(c(1, 2, 3, 4, 2, 6, 10, 3, 4, 5, 6))
 [1] 1 1 1 1 2 2 2 3 3 3 3
Levels: 1 2 3
```

**Comment by arunsrinivasan** [comment]
Update these on SO:

http://stackoverflow.com/q/38464551/559784

**Comment by MichaelChirico** [comment]
Not much appetite for this, not sure it needs a dedicated implementation. Workaround is to use `shift()`:

```r
dt[, sum(y), by=.(diffid = cumsum((x-shift(x, fill=x[1]))<0))]
   diffid    V1
    <int> <int>
1:      0    10
2:      1    18
3:      2    38
```

I think that's good enough unless this is some widely-known operation I've not come across in my own work.
