### ISSUE TITLE
FR: colClasses could accept a data.frame/table

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1773]
This is related to #1701 in that it's about simplifying the process of tracking data types in data input/output.

As I see it, one convenient way of exporting then importing data at different stages of a project goes like this:

```
#Module 1
fwrite(DT, "out.csv")

fwrite(as.data.table(sapply(DT, class), keep.rownames = TRUE), "out_types.csv")
```

Followed by:

```
#Module 2
fread("out.csv", colClasses = fread("out_types.csv"))
```

I think implementation just consists of recognizing `data.table`/`data.frame` input and then treating it as `list`s are currently handled.

**Comment by arunsrinivasan** [comment]
I think this is better handled with CSVY format.

**Comment by arunsrinivasan** [comment]
As mentioned before, better handled with #1701.
