### ISSUE TITLE
Table mangling and loss of assignment by reference caused by unique() with JIT compiling on

### ISSUE THREAD

**Issue by fabnicol** [Rdatatable/data.table#1775]
I'm confronted with an obscure, hardly replicable table-mangling issue that might be hard to identify let alone solve.

I created and processed a data.table with no signs of an issue whatsoever until it became apparent that this table was not modifiable by reference using `:=` or ``:=``(...). Paradoxically, a simple copy of it still behaves normally and  can be modified by reference as is normal.

I have trouble replicating the issue with minimal examples.  It is not an accidental one-off, many such bases have been produced with the same code. I join the full base and a commented R script to test the issue as minimally as possible in [this](https://github.com/fabnicol/test.git) test repository. Just run the test.R script under a recent version of R and the current git code of data.table.

The issue should be related with "last-sector mangling" as is shown by this snapshot of a binary diff between the original base (right) and its shallow copy using data.table::copy() on the left. The latter adds about a sector of hex padding at the end of the table, which seems to have been mangled in the original base.

I acknowledge that this post may not comply with replication standards yet I consider the issue serious enough to at least mention it
![bcompare](https://cloud.githubusercontent.com/assets/1889579/16932640/f0781c26-4d47-11e6-9848-7d9d120adb02.png)
.

**Comment by jangorecki** [comment]
Hello, are you aware of [Reading data.table from RDS or RData file](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-faq.html#reading-data.table-from-rds-or-rdata-file)?

**Comment by fabnicol** [comment]
Yes, the issue is not related to RData file reading. I provide the RData file in the github repo for convenience here. In actual code there is no binary loading at all : the tables are fread from csv.

**Comment by franknarf1** [comment]
@fabnicol Did you read the link? Using `setDT(Bulletins.avan3)` before calling `f` solved it for me. That's what I usually do, even though the link recommends `alloc.col`.

**Comment by fabnicol** [comment]
@franknarf1 : Thanks, your undocumented suggestion as to `setDT()` helped me out find a minimal  text-based example. See new test file test2.R in repo indicated above.

Unfortunately, the test ran this way (with the apparent bug as indicated in comments of test2.R) for a certain memory status of my R session. After a clean restart of the session things went back to normal (for a time) and test2.R ran OK. 

The interplay of data.table::unique and global assignment might be involved.

Interestingly `setDT()` set things right even in my probably memory-corrupted environment. I keep the advice as a good practice. Including this in the docs would be appropriate.

**Comment by franknarf1** [comment]
Interesting tests there. I do not see the same thing as you, though (using the devel version, as documented in [Links number 4 in the support page](https://github.com/Rdatatable/data.table/wiki/Support)). After the first `g(A)`, I do see column `Y` showing.

Generally, one of the core features of the package is modifying objects by reference, so if you want to play with the references for some reason, it's probably best to get a sense for the typical usage in R and data.table (which avoid `<<-`... not sure if you knew that already).

**Comment by fabnicol** [comment]
@franknarf1
The devel version was built and used in above tests as indicated by link 4. The issue did not appears with libs built with devel code a few weeks older. I'll try to determine which commit set the issue on.

**Comment by fabnicol** [comment]
Done.

Issue is very recent and was directly caused by commit cda73b (jangorecki) on July 1st, more specifically by modifications to duplicated.R
For the priori commit 41e7a7 and commits before, the issue consistently disappears.  
As hypothesized in my above comment, there seems to be an issue with the gain in memory efficiency expected by the second part of the output of `git diff  41e2a7  cda73b`. The new version of unique.data.table closing #1760 is apparently less robust than the release one. Is it really harmless to remove indexes after `unique`?     

####  Methodology   
I cloned the master branch, and restarted R sessions after each source code rebuild. Commit responsible for issue was reached by dichotomy in the git-log list of recent commits.
All user libs recompiled freshly. Issue is not hardware-dependent (tested on a PC and a laptop), nor gcc-dependent (tested with versions 4.9.3, 5.4.0 and current 7.0.0 gcc builds) yes only tested on linux platforms.

#### Part of the diff that introduced the issue    
index b8359f3..215dbdf 100644
--- a/R/duplicated.R
+++ b/R/duplicated.R
@@ -28,7 +28,8 @@ duplicated.data.table <- function(x, incomparables=FALSE, fromLast=FALSE, by=key
 unique.data.table <- function(x, incomparables=FALSE, fromLast=FALSE, by=key(x), ...) {
     if (!cedta()) return(NextMethod("unique"))
     dups <- duplicated.data.table(x, incomparables, fromLast, by, ...)
-    .Call(CsubsetDT, x, which_(dups, FALSE), seq_len(ncol(x))) # more memory efficient version of which(!dups)
+    ans <- .Call(CsubsetDT, x, which_(dups, FALSE), seq_len(ncol(x))) # more memory efficient version of which(!dups)
+    if (nrow(x) != nrow(ans)) setindexv(ans, NULL)[] else ans #1760
     # i.e. x[!dups] but avoids [.data.table overhead when unique() is loop'd
     # TO DO: allow logical to be passed through to C level, and allow cols=NULL to mean all, for further speed gain.
     #        See news for v1.9.3 for link to benchmark use-case on datatable-help.

**Comment by jangorecki** [comment]
> Is it really harmless to remove indexes after `unique`? 

I would say it is harmful to not remove it. When you have a subset of original data your index isn't valid any more. It just keeps the row order. AFAIR separate issue discuss possibility to automatically recalculate index on subset, but even if implemented it won't be active by default.
Do you have any code to reproduce discussed issue?

**Comment by fabnicol** [comment]
I could possibly send you chunks of real code but to do that I need private transmission on confidential terms (this is job code).

**Comment by jangorecki** [comment]
Ideally it should be example isolated and simplified enough, so it won't need a chunk of *read code*. Not just for confidentiality but also for the convenience of getting support. If you have a simple and reproducible example that you want to provide confidentially you can drop me R file on email, for end-to-end encrypted email use `jangorecki` at `protonmail.ch`.

**Comment by fabnicol** [comment]
@jangorecki 
I finally found a minimal test. Please update above repository and run `minimal_test.R` *line by line* under RStudio, or if not using it replace `.rs.restartR()` by any other way of restarting R (and wait a few seconds for the clean session to start).   
It is necessary to always start a clean session as the bug has persisting effects that may be misleading.   
The bottom line is : there is somewhere an issue with data.table and the compiler library as soon as JIT levels 1 and above are set, once the new version of `data.table::unique()`  is on, and only with global assignment (compare the output of `g()` and `h()`).   
See the data.table warnings that were stifled by my prior verbosity coding and now shed light on the issue (for this run `g()` at JIT levels 1 and above)   
This warning also explains why the `setDT()` method is a good workaround (see comment by franknarf1 above and corresponding test).  

` Warning message:
     In `[.data.table`(Base, , `:=`(Y, 1)) :
     Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or been created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting. If this message doesn't help, please report to datatable-help so the root cause can be fixed.`

**Comment by jangorecki** [comment]
```r
.rs.restartR()
#Error: could not find function ".rs.restartR"
```
I would appreciate if you can reproduce it starting with base R by actually restarting session (if that is desired behavior). Just to double check source of that issue.

**Comment by fabnicol** [comment]
There is no restart function in base R. The alternative is to use q () instead and source again test3.R on a fresh session. Then call the test function with an incremented integral argument between 1 and 3.

**Comment by fabnicol** [comment]
The above comment is now implemented in repository by file `minimal_test_base.R`. Please git-pull and run file *line by line*.
Restarting is there to avoid memory corruption side-effects. Once the bug has bitten, it has persisting effects for newly created tables which otherwise would be fine. Cleaning the environment is the only way to neatly isolate the bug from other factors.

**Comment by jangorecki** [comment]
I'm able to reproduce the warning, but the whole process seems to be dependent on `compiler` package. Could you isolate data.table issue from it? I tried the following with multiple restarts but it seems to be working as expected. It looks like `compiler` makes an unexpected side effect here.
```r
library(data.table)
B <- data.table(V = c("a", "b"), W = c("d", "e"))                            
f <- function(Base)    Base[ , Y := 1]
g <- function() {
    cat("B addr:", address(B), "\n")
    Case1 <<-  unique(B, by = NULL)
    cat("Case1 addr:", address(Case1), "\n")
    cat("f(Case1) addr:", address(f(Case1)), "\n")
    print(Case1)
}
g()
```
Generally I would avoid `<<-` operator.

**Comment by fabnicol** [comment]
Exactly what I commented above.
There is no issue at all when `enableJIT` is set at level 0, which amounts to deactivating the `compiler` package as in your above test.
Once byte-compilation is enabled at level 1 and above, the bug reappears and you should now be in a position to confirm this.  
On `<<-` :  
Admittedly bad style yet correct base-R syntax. Style is not syntax.   
Note that while global assignment with `<<-` may be bad style when overused (as in the minimal test for convenience) it may come in handy in more complex cases.   
On the `compiler` library:    
Please note that `compiler` has been part of any base R distribution for some time now and that this package is extensively used.   Should the data.table team chose not to support it, this choice, which is yours to make, should be carefully documented somewhere IMHO.

**Comment by jangorecki** [comment]
I'm not saying anything about lack of support for it, rather just trying to narrow the issue, which appears to be package integration related. Unfortunately I'm not able to provide more info on that currently as I never used `compiler` package

**Comment by fabnicol** [comment]
Clearly the issue revolves around the way `compiler` inlines `.Call` (see paper [here](http://homepage.divms.uiowa.edu/~luke/R/compiler/compiler.pdf), page 59.
When `.Call` is repeated instead of its `ans` replacement in devel code (R/duplicated.R at around l.30, function `unique.data.table`), the issue disappears in the 'else' case. Obviously undesirable performance-wise.    
This points to an arcane cause related to the R/C interface and its interplay with byte compiling. Possibly there might be a way to freeze `.Call` and protect it from inlining by the compiler. I tried a few ways (putting it in a closure; in a list; fiddling with non-namespace-exported `setkeyv`) to no avail so I'll have to give up on this. Note there is a mention of "protection from inlining" in the paper definition of JIT level 1 :

> Functions in the base packages found through a namespace that are not shadowed by
function arguments or visible local assignments may be inlined  

This may be a clue to a solution: find a way to shadow the `ans <-` assignment by making it "visible" (but how?)

Good luck.

**Comment by jangorecki** [comment]
Did the following change solve your issue? It splits `unique` from `<<-`.
```r
  g <- function() {
    
    tmp <-  unique(B, by = NULL)    
    f(tmp)
    Case1 <<- tmp
    cat("g : using global assignment for Case1\n")  
    print(Case1)
    
  }
```

**Comment by fabnicol** [comment]
It does work.  
It is more of a hackey way out than a solution, though.

**Comment by jangorecki** [comment]
@fabnicol If you create those objects in advance in expected frame (or higher) you won't get those notes. That can be done by `Case1=NULL` or `utils::globalVariables`. These notes are pretty well discussed in relation to package development, where they appear the most often. I will leave that issue open as exact source of that issue wasn't identified.

**Comment by fabnicol** [comment]
@jangorecki 
FYI There is another more convincing way out as follows:
    `assign(Case1, unique(B, by = NULL), envir = parent.frame())`
in your above quoted code or in new file test4.R in updated repo.
test4.4 also tests for a more general solution that does not break existing code using `alloc.col`  (see end of file)
This solution is implemented in current data.table code in file patch.diff added to repo. Use:
` git apply patch.diff` 
if the R directory of current source code.
This issue is reminiscent of issues fixed by @arunsrinivasan in commit 9e8a71653efa

**Comment by fabnicol** [comment]
Update as of Dec 8, 2016

The bug at issus was not fixed with the release of 'stable' version 1.10.

As a result, all code using global assignments as shown above is broken if compiler is set to enableJIT values above 0. I'm losing about 20 % of execution  time doing so.

Currently I have deactivated JIT compiling pending a code review to try and eliminate the globals.

**Comment by fabnicol** [comment]
Bug seems to have disappeared with current devel version (1.10.5 built today, Linux OS, R version 3.3.2).
I haven't tried yet to pinpoint the code delta that may have fixed the bug yet as the minimal tests provided by my above github test [repository ](https://github.com/fabnicol/test.git) are now OK, this issue can now be considered closed.

**Comment by fabnicol** [comment]
Bug still currently there (version 1.10.5, R version 3.3.2).

**Comment by fabnicol** [comment]
Hastily closed. Bug still currently there (version 1.10.5, R version 3.3.2).

**Comment by fabnicol** [comment]
Bug was very likely caused not by data.table code but by internal R issues with the compiler library.
data.table issue no longer shows up starting with R 3.4 even at the afore-mentioned cd73b commit.
This may be linked to a revision in JIT byte-compiling in R 3.4 (default is now enableJIT(3)).
Issue closed.

**Comment by MichaelChirico** [comment]
if the issue is true R version-dependent, please leave this open -- IIRC
current stated dependency is R 3.0, which would mean this is still a  bug
for some users.
