### ISSUE TITLE
Warning message when deleting columns

### ISSUE THREAD

**Issue by httassadar** [Rdatatable/data.table#1781]
I get some warning messages when deleting columns. This behaviour is somewhat random and I can't  consistently reproduce it. The result is correct though.
`

> xx = data.table(a = 3, b=2, c = 3)
> setnames(xx, c('aa','bb','cc'))
> xx[, bb:=NULL]
> xx[, cc:=NULL]

**Warning messages:
1: In `[.data.table`(xx, , `:=`(bb, NULL)) :
  Adding new column 'bb' then assigning NULL (deleting it).
2: In `[.data.table`(xx, , `:=`(bb, NULL)) :
  Adding new column 'bb' then assigning NULL (deleting it).
3: In `[.data.table`(xx, , `:=`(bb, NULL)) :
  Adding new column 'bb' then assigning NULL (deleting it).**
`

> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252  
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C  
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.3.3  ggplot2_2.1.0    data.table_1.9.6

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      digest_0.6.8     chron_2.3-47     grid_3.2.2       plyr_1.8.3  
 [6] gtable_0.1.2     magrittr_1.5     scales_0.3.0     stringi_0.5-5    tools_3.2.2  
[11] stringr_1.0.0    munsell_0.4.2    compiler_3.2.2   colorspace_1.2-6 memoise_0.2.1

**Comment by arunsrinivasan** [comment]
I remember a couple of users experiencing the same issue at the UseR'16 tutorial. But it was while working with RStudio. IIRC it couldn't be replicated with R on a terminal. 

Could you confirm if this is the same scenario in your case as well?

**Comment by httassadar** [comment]
Yes, I'm using RStudio

**Comment by arunsrinivasan** [comment]
Thanks. I meant if you could work with R terminal and try to reproduce the issue. It seems extremely hard to reproduce the issue, and affects only a handful. So quite hard to debug from my side. I can't think of a reason why this'd be a data.table issue. 

If you couldn't replicate it from an R-session on a terminal (cygwin perhaps?), or using R-GUI, then that'd confirm it.

**Comment by MichaelChirico** [comment]
I guess this is the same issue as #1690. Couldn't nail down the issue there either...

Perhaps it's relevant that I was using `data.table` within a `knitr` document there? Is that perhaps the case for you as well @httassadar?

**Comment by arunsrinivasan** [comment]
Tagging @kevinushey (assuming this is only happening in RStudio). Although I'm not sure what can be done without being able to reproduce it consistently.

**Comment by arunsrinivasan** [comment]
This is the code that Sadie Gill (participant at UseR'16 tutorial) tried:

```r
> library(data.table)
# data.table 1.9.6  For help type ?data.table or https://github.com/Rdatatable/data.table/wiki
# The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
set.seed(1)
DT = data.table(
  id = sample(LETTERS, 200, replace = TRUE),
  v = sample(10, 200, replace = TRUE)
)
DT[, mean2 := mean(v), by = id][] #empty bracket to print DT
#      id v    mean2
#   1:  G 3 4.625000
#   2:  J 3 5.125000
#   3:  O 6 5.666667
#   4:  X 3 4.750000
#   5:  F 2 5.250000
# ---              
# 196:  P 4 4.666667
# 197:  C 7 5.375000
# 198:  V 4 3.500000
# 199:  I 4 5.200000
# 200:  U 2 5.600000
DT[, `:=` (mean = mean(v), sd= sd(v)), by = id]
DT
#      id v    mean2     mean       sd
#   1:  G 3 4.625000 4.625000 2.825269
#   2:  J 3 5.125000 5.125000 3.907411
#   3:  O 6 5.666667 5.666667 3.829708
#   4:  X 3 4.750000 4.750000 1.669046
#   5:  F 2 5.250000 5.250000 3.575712
# ---                                
# 196:  P 4 4.666667 4.666667 2.783882
# 197:  C 7 5.375000 5.375000 2.615203
# 198:  V 4 3.500000 3.500000 1.760682
# 199:  I 4 5.200000 5.200000 2.859681
# 200:  U 2 5.600000 5.600000 2.674987
DT[]
#      id v    mean2     mean       sd
#   1:  G 3 4.625000 4.625000 2.825269
#   2:  J 3 5.125000 5.125000 3.907411
#   3:  O 6 5.666667 5.666667 3.829708
#   4:  X 3 4.750000 4.750000 1.669046
#   5:  F 2 5.250000 5.250000 3.575712
#  ---                                
# 196:  P 4 4.666667 4.666667 2.783882
# 197:  C 7 5.375000 5.375000 2.615203
# 198:  V 4 3.500000 3.500000 1.760682
# 199:  I 4 5.200000 5.200000 2.859681
# 200:  U 2 5.600000 5.600000 2.674987
DT[]
#      id v    mean2     mean       sd
#   1:  G 3 4.625000 4.625000 2.825269
#   2:  J 3 5.125000 5.125000 3.907411
#   3:  O 6 5.666667 5.666667 3.829708
#   4:  X 3 4.750000 4.750000 1.669046
#   5:  F 2 5.250000 5.250000 3.575712
#  ---                                
# 196:  P 4 4.666667 4.666667 2.783882
# 197:  C 7 5.375000 5.375000 2.615203
# 198:  V 4 3.500000 3.500000 1.760682
# 199:  I 4 5.200000 5.200000 2.859681
# 200:  U 2 5.600000 5.600000 2.674987
setkey(DT, id)
key(DT)
# [1] "id"
DT[id == "B"]
#    id v mean2 mean      sd
# 1:  B 8   3.4  3.4 3.04959
# 2:  B 5   3.4  3.4 3.04959
# 3:  B 2   3.4  3.4 3.04959
# 4:  B 1   3.4  3.4 3.04959
# 5:  B 1   3.4  3.4 3.04959
DT[c("A","B")]
#    id v mean2 mean        sd
# 1:  A 3  4.25 4.25 0.9574271
# 2:  A 5  4.25 4.25 0.9574271
# 3:  A 5  4.25 4.25 0.9574271
# 4:  A 4  4.25 4.25 0.9574271
# 5:  B 8  3.40 3.40 3.0495901
# 6:  B 5  3.40 3.40 3.0495901
# 7:  B 2  3.40 3.40 3.0495901
# 8:  B 1  3.40 3.40 3.0495901
# 9:  B 1  3.40 3.40 3.0495901
x = data.table(c("B", "G", "H"), top = c(2,4,3))
DT[]
#      id  v mean2 mean        sd
#   1:  A  3  4.25 4.25 0.9574271
#   2:  A  5  4.25 4.25 0.9574271
#   3:  A  5  4.25 4.25 0.9574271
#   4:  A  4  4.25 4.25 0.9574271
#   5:  B  8  3.40 3.40 3.0495901
#  ---                           
# 196:  Z 10  6.00 6.00 2.9154759
# 197:  Z  5  6.00 6.00 2.9154759
# 198:  Z  2  6.00 6.00 2.9154759
# 199:  Z  7  6.00 6.00 2.9154759
# 200:  Z  6  6.00 6.00 2.9154759
setkey(DT, id, v)
DT[.("A")]
#    id v mean2 mean        sd
# 1:  A 3  4.25 4.25 0.9574271
# 2:  A 4  4.25 4.25 0.9574271
# 3:  A 5  4.25 4.25 0.9574271
# 4:  A 5  4.25 4.25 0.9574271
DT[]
#      id  v mean2 mean        sd
#   1:  A  3  4.25 4.25 0.9574271
#   2:  A  4  4.25 4.25 0.9574271
#   3:  A  5  4.25 4.25 0.9574271
#   4:  A  5  4.25 4.25 0.9574271
#   5:  B  1  3.40 3.40 3.0495901
# ---                           
# 196:  Z  2  6.00 6.00 2.9154759
# 197:  Z  5  6.00 6.00 2.9154759
# 198:  Z  6  6.00 6.00 2.9154759
# 199:  Z  7  6.00 6.00 2.9154759
# 200:  Z 10  6.00 6.00 2.9154759
DT[, 3:5 := NULL] # remove multiple columns
DT[]
#      id  v
#   1:  A  3
#   2:  A  4
#   3:  A  5
#   4:  A  5
#   5:  B  1
#  ---      
# 196:  Z  2
# 197:  Z  5
# 198:  Z  6
# 199:  Z  7
# 200:  Z 10
setkey(DT, id)
DT[id == "B"]
#    id v
# 1:  B 1
# 2:  B 1
# 3:  B 2
# 4:  B 5
# 5:  B 8
x = data.table(c("B", "G", "H"), top = c(2,4,3))
DT[]
#      id  v
#   1:  A  3
#   2:  A  4
#   3:  A  5
#   4:  A  5
#   5:  B  1
#  ---      
# 196:  Z  2
# 197:  Z  5
# 198:  Z  6
# 199:  Z  7
# 200:  Z 10
x
#    V1 top
# 1:  B   2
# 2:  G   4
# 3:  H   3
DT[, `=:` (mean = mean(v), max = max(v)), by = id]
# Error in `[.data.table`(DT, , `=:`(mean = mean(v), max = max(v)), by = id) : 
#   could not find function "=:"
DT[, `:=` (mean = mean(v), max = max(v)), by = id]
DT
#      id  v mean max
#   1:  A  3 4.25   5
#   2:  A  4 4.25   5
#   3:  A  5 4.25   5
#   4:  A  5 4.25   5
#   5:  B  1 3.40   8
#  ---               
# 196:  Z  2 6.00  10
# 197:  Z  5 6.00  10
# 198:  Z  6 6.00  10
# 199:  Z  7 6.00  10
# 200:  Z 10 6.00  10
DT[, 3:4 := NULL] # remove multiple columns
DT
# Warning messages:
# 1: In `[.data.table`(DT, , `:=`(nmean, NULL)) :
#   Adding new column 'nmean' then assigning NULL (deleting it).
# 2: In `[.data.table`(DT, , `:=`(nmean, NULL)) :
#   Adding new column 'nmean' then assigning NULL (deleting it).
# 3: In `[.data.table`(DT, , `:=`(nmean, NULL)) :
#   Adding new column 'nmean' then assigning NULL (deleting it).
DT
#      id  v
#   1:  A  3
#   2:  A  4
#   3:  A  5
#   4:  A  5
#   5:  B  1
#  ---      
# 196:  Z  2
# 197:  Z  5
# 198:  Z  6
# 199:  Z  7
# 200:  Z 10
```

**Comment by kevinushey** [comment]
Without a consistently reproducible example, there's not much we can do on the RStudio side either, unfortunately.

**Comment by MichaelChirico** [comment]
mine comes from fully public code & data -- just that it's 1000s of lines long. I'll make a note to see if I can't narrow things down a bit...

**Comment by MichaelChirico** [comment]
code here in case someone else wants to take a crack

https://github.com/MichaelChirico/iesRTutorial/blob/master/iesrtutorial.Rmd

**Comment by httassadar** [comment]
@MichaelChirico I'm not using knitr actually.
@arunsrinivasan Yes, it's likely RStudio issue. I'm not able to reproduce the warning message once in RGui.

**Comment by MichaelChirico** [comment]
@arunsrinivasan that code gives me no error;
@httassadar my own code that was causing issues no longer is. Perhaps whatever the error was has been phased out?

Can you still get the error within RStudio on the latest `data.table` development version and RStudio >= 0.99.878?

**Comment by MichaelChirico** [comment]
I haven't seen this warning in quite some time, and apparently it hasn't come up for others, either, so assuming the issue was squashed (perhaps inadvertently) somewhere along the way... closing

**Comment by maxgold** [comment]
I am still getting this issue when using data.table. Has anyone been able to find a fix?
