### ISSUE TITLE
setDT in master branch version fails when run under R 3.3.1

### ISSUE THREAD

**Issue by sz-cgt** [Rdatatable/data.table#1782]
Pulled the latest version from github today so I could use the fwrite function.  Works fine under R 3.2.5.  Fails under 3.3.1

    data.table 1.9.7 IN DEVELOPMENT built 2016-07-26 19:07:44 UTC
    For help type ?data.table or https://github.com/Rdatatable/data.table/wiki
    The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
    > xx = data.frame(x=1:3, y=rnorm(3))
    > setDT(xx)
    Error in dim.data.table(x) : object 'Cdim' not found
    > R.version.string
    [1] "R version 3.3.1 (2016-06-21)"

**Comment by jangorecki** [comment]
I cannot reproduce error on R 3.3.1 with Ubuntu. Can you provide more details? `sessionInfo()`

**Comment by sz-cgt** [comment]
Here you go.

data.table 1.9.7 IN DEVELOPMENT built 2016-07-26 19:07:44 UTC
For help type ?data.table or https://github.com/Rdatatable/data.table/wiki
The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
> xx data.frame(x = 1:3, y= rnorm(3))
Error: unexpected symbol in "xx data.frame"
> xx = data.frame(x = 1:3, y= rnorm(3))
> setDT(xx)
Error in dim.data.table(x) : object 'Cdim' not found
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringi_1.1.1    magrittr_1.5     data.table_1.9.7

loaded via a namespace (and not attached):
[1] tools_3.3.1

**Comment by arunsrinivasan** [comment]
Could you try uninstalling your current installation (using `remove.packages()`) and reinstalling again?

**Comment by sz-cgt** [comment]
That fixed it.  Thanks!
