### ISSUE TITLE
zero length .SDcols

### ISSUE THREAD

**Issue by ggrothendieck** [Rdatatable/data.table#1789]
It would be nice if .SDcols could be zero length.   In #1786 we discussed this code which works but a special case had to be made for the situation where there were no numeric columns.  

```
iris.dt <- as.data.table(iris)
nums <- which(sapply(iris.dt, is.numeric))
if (length(nums)) iris.dt[, (nums) := .SD/rowMeans(.SD), .SDcols = nums]
```

It would be nice if .SDcols could allow the specification of no columns so that this would work even in the case that iris has no numeric columns.  

```
iris.dt <- as.data.table(iris)
nums <- which(sapply(iris.dt, is.numeric))
iris.dt[, (nums) := .SD/rowMeans(.SD), .SDcols = nums]
```

(Incidentally it would also be nice if nums could be logical so that we could have `nums <- sapply(iris.dt, is.numeric)` .  That works in .SDcols= but not on the LHS of := .)

**Comment by jangorecki** [comment]
Slightly related to #1269

**Comment by HughParsonage** [comment]
As a note, there is a (very mild) inconsistency between zero-length character and zero-length integer `.SDcols`

```r
DT <- data.table(x = 1, y = 2, z = 3)
DT[, .SD, .SDcols = integer(0)]
# Error in `[.data.table`(DT, , .SD, .SDcols = integer(0)) : 
#  .SDcols is numeric but has both +ve and -ve indices
DT[, .SD, .SDcols = character(0)]
# Null data.table (0 rows and 0 cols)
```

In my view the `character(0)` response is correct, or at the very least the error message in `integer(0)` is incorrect.
