### ISSUE TITLE
Auto indexing when not necessary

### ISSUE THREAD

**Issue by snoram** [Rdatatable/data.table#1791]
See Q on SO
[http://stackoverflow.com/q/38726950/4552295](http://stackoverflow.com/q/38726950/4552295)

**Comment by jangorecki** [comment]
duplicate https://github.com/Rdatatable/data.table/issues/1264

**Comment by arunsrinivasan** [comment]
Oh yes.. I asked OP to add an issue.. dint realise I filed one already...
