### ISSUE TITLE
frank() with order = ... failing

### ISSUE THREAD

**Issue by sz-cgt** [Rdatatable/data.table#1794]
Given

```r
require(data.table)
set.seed(1L)
dt <- data.table(a = c('a', 'b'), b = 1:4, c = 'yesy', d = runif(20, 1, 10), e = 'noy', f  = runif(20, 1, 10))
```

the following all work (and produce identical results)

    dt[,frank(.SD, f, d), by = .(a, b)]
    dt[,frank(.SD, cols = c('f', 'd')), by = .(a, b)]
    dt[,frank(.SD), by = .(a, b), .SDcols = c(6, 4)]

However, attempting to explicitly declare an order causes all three statements to throw an error:

    Error in validate(cols, x) :
      cols value(s) [NA] not present (or out of range) in x

    dt[,frank(.SD, f, d, order = -1L), by = .(a, b)]  #fails
    dt[,frank(.SD, cols = c('f', 'd', order = -1L)), by = .(a, b)]  #fails
    dt[,frank(.SD, order = -1L), by = .(a, b), .SDcols = c(6, 4)]  #fails

This happens regardless of whether `order =` is given a a single value of a vector with length matching the number of columns

Explicitly flagging each column works as expected but I was trying to avoid the extra typing (my actual use case has more columns than the example above).

System details in case it matters:

data.table 1.9.7 IN DEVELOPMENT built 2016-07-26 22:00:54 UTC
For help type ?data.table or https://github.com/Rdatatable/data.table/wiki
The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringi_1.1.1    magrittr_1.5     data.table_1.9.7

loaded via a namespace (and not attached):
[1] tools_3.3.1

**Comment by MichaelChirico** [comment]
please add a `set.seed` and output

**Comment by jangorecki** [comment]
there is no `cols` argument in `frank` function, you probably wanted `frankv`

**Comment by arunsrinivasan** [comment]
It has no `order` argument either. As @jangorecki  suggested, use `frankv` which is the "SE" version.. `frank` is useful in interactive scenarios, for example: `frank(dt, -x, y)` (note that the ordering is provided directly).

**Comment by sz-cgt** [comment]
close #1794
