### ISSUE TITLE
adding a column with ":=" and strptime() doesn't work

### ISSUE THREAD

**Issue by gd-aovchinnikov** [Rdatatable/data.table#1802]
New column is incorrectly created in case when existing column (character) is converted to POSIXlt with strptime() function, see the example below.

`library(data.table)`
`mdt<-data.table(id=1:3, d=c("06:02:36", "06:02:48", "07:03:12"))`
`mdt[,dt:=strptime(d, "%H:%M:%S")]`

> Warning message:
> In `[.data.table`(mdt, , `:=`(dt, strptime(d, "%H:%M:%S"))) :
>   Supplied 11 items to be assigned to 3 items of column 'dt' (8 unused)

This warning above is the first indication of the problem. Expected behavior is that three values in existing 'd' column are converted into three values in the new 'dt' column.
The output shows that values in 'dt' column were created from parts of the entire 'd' column, e.g.  mdt[1,dt] consists of 'seconds' component of entire 'd' column.

`print(mdt)`

>    id        d       dt
> 1:  1 06:02:36 36,48,12
> 2:  2 06:02:48    2,2,3
> 3:  3 07:03:12    6,6,7

`sessionInfo()`

> R version 3.3.0 (2016-05-03)
> Platform: x86_64-apple-darwin14.5.0 (64-bit)
> Running under: OS X 10.12 (unknown)
> 
> locale:
> [1] C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] data.table_1.9.6
> 
> loaded via a namespace (and not attached):
> [1] tools_3.3.0  chron_2.3-47
>

**Comment by franknarf1** [comment]
Read [the support page](https://github.com/Rdatatable/data.table/wiki/Support). You should be posting a bug report only if you see it on the latest development version. 

For what it's worth, the warning I see is:

> Warning message:
> In strptime(d, "%H:%M:%S") :
>   POSIXlt column type detected and converted to POSIXct. We do not recommend use of POSIXlt at all because it uses 40 bytes to store one date.

Also, the result seems to be fine:

       id        d                  dt
    1:  1 06:02:36 2016-08-05 06:02:36
    2:  2 06:02:48 2016-08-05 06:02:48
    3:  3 07:03:12 2016-08-05 07:03:12

**Comment by gd-aovchinnikov** [comment]
It works in the dev. version for me as well, thanks. I apologise for submitting the known issue.

Btw,  the [installation instruction for the dev. version](https://github.com/Rdatatable/data.table/wiki/Installation) are a bit outdated for Mac OS. The command `brew install clang-omp` doesn't work since clang-omp was retired and moved to the [boneyard](https://github.com/Homebrew/homebrew-boneyard) repository. So the working command looks like `brew install homebrew/boneyard/clang-omp`

**Comment by franknarf1** [comment]
Cool. Glad it worked. I'm sure the devs would appreciate an edit to correct the instructions (it's a wiki, so there's an edit button in the top right).
