### ISSUE TITLE
data.table file reading issue

### ISSUE THREAD

**Issue by FunData7** [Rdatatable/data.table#1805]
Running 'fread' command and getting the erros:

> fn1 <- fread(input.path,"filename.csv", header=T,sep='\t')

Error in fread(input.path, "filename.csv", header = T,  :
  Opened file ok, obtained its size on disk (0.0MB), but couldn't memory map it. This is a 64bit machine so this is surprising. Please report to datatable-help.

Can you help with that? Any ideas would be helpful!

**Comment by MichaelChirico** [comment]
We won't be able to help without knowing what `input.path` is...

**Comment by arunsrinivasan** [comment]
The first argument needs to be the file name. Please read `?fread` and have a look at the examples.
