### ISSUE TITLE
fread() has problems with some forms of balanced quotes

### ISSUE THREAD

**Issue by solquist** [Rdatatable/data.table#1809]
Here is a simplified example of quote processing issue I ran into today. If the quotes are balanced, but are such that the logic kicks in for a quoted field, fread() does not process the file correctly. In the example below it fails to read. If the quote usage patterns are the same, it will succeed, but with two fields instead of four (e.g. if the second row of data in the example below were '"Another" string').

```
libarary(data.table)

#
# Data:
# 
#        V1            V2    v3   v4
# "This" is a test    100   "A"  TRUE
# Another string       90   "B"  FALSE
#

# When pattern isn't consistent, read fails due to a row with too few fields
tmp <- fread('V1, V2, V3, V4\n"This" is a test, 100, "A", TRUE\nAnother string, 90, "B", FALSE\n')
```
Output:
```
Error in fread("V1, V2, V3, V4\n\"This\" is a test, 100, \"A\", TRUE\nAnother string, 90, \"B\", FALSE\n") : 
  Expected sep (',') but new line, EOF (or other non printing character) ends field 1 when detecting types (   first): "This" is a test, 100, "A", TRUE
```
One possible suggestion to get the best of both worlds seems to be to do without quotes first -- if the number of fields matches with the header read or consensus with the other data, you are good, and if not, invoke the quote matching logic.

**Comment by solquist** [comment]
A nice features request that would help here as well is to have fread also support the "quotes" option. Then in the case you have a well formed delimited file, you could just use quotes="" like you would in read.delim() to just ignore the quotes. I would be happy to file this as a separate feature request if that seems useful.

**Comment by arunsrinivasan** [comment]
Fixed in v1.9.7.

**Comment by MichaelChirico** [comment]
@solquist see here for instructions on how to get 1.9.7

https://github.com/Rdatatable/data.table/wiki/Installation

**Comment by solquist** [comment]
Thanks for the info.
