### ISSUE TITLE
FR: in dcast, with multiple value.var and a single fun.agg, don't put the fun in the col names

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#1810]
An example from SO: http://stackoverflow.com/a/38923405/

    require(data.table)
    data = data.table(
        var1 = c("a","b","c","b","d","e","f"),
        var2 = c("aa","bb","cc","dd","ee","ee","ff"),
        subtype = c("1","2","2","2","1","1","2"),
        type = c("A","A","A","A","B","B","B")
    )
    f = function(v) paste0(unique(v), collapse = "|")
    dcast(data, type ~ subtype, value.var = c("var1", "var2"), fun = f)

    #    type var1_f_1 var1_f_2 var2_f_1 var2_f_2
    # 1:    A        a      b|c       aa bb|cc|dd
    # 2:    B      d|e        f       ee       ff

The `_f_` is somewhat redundant in the new column names. Worse, using an anonymous function, we'd see `_function_`. It would be preferable to just have names like `var1_1`, etc.

**Comment by arunsrinivasan** [comment]
Could you please add `require(data.table)` to the code as well? It'd be even easier to copy/paste. Thanks. I've edited it in.
