### ISSUE TITLE
"object 'Cwritefile' not found" error when calling fwrite

### ISSUE THREAD

**Issue by richierocks** [Rdatatable/data.table#1811]
To reproduce:

```{r}
library(data.table)
fwrite(cars, "cars.csv")
## Error in fwrite(cars, "cars.csv") : object 'Cwritefile' not found
```

`Cwritefile` doesn't seem to have been registered when the package was loaded.

```{r}
dll <- system.file("libs/x64/datatable.dll", package = "data.table")
rr <- getDLLRegisteredRoutines(dll)
"Cwritefile" %in% names(rr$.Call) # FALSE
```

I'm running today's development version of `data.table`, and a recent version of R-devel 3.4.0 under Windows 10.

**Comment by arunsrinivasan** [comment]
Uninstalling data.table from a fresh session and reinstalling should fix this. Please write back if it doesn't.
