### ISSUE TITLE
Replace clang-omp with llvm in Mac Installation Instructions

### ISSUE THREAD

**Issue by botanize** [Rdatatable/data.table#1817]
With clang-omp moved to the brew boneyard the recommended replacement is the llvm package which contains clang.

The following steps worked for me:
`brew update && brew install llvm`

~/.R/Makevars
```
CC=/usr/local/opt/llvm/bin/clang -fopenmp
CXX=/usr/local/opt/llvm/bin/clang++ -fopenmp
CFLAGS=-O3 -mtune=native
CXXFLAGS=-O3 -mtune=native
LDFLAGS=-L/usr/local/opt/llvm/lib
CPPFLAGS=-I/usr/local/opt/llvm/include
```

**Comment by arunsrinivasan** [comment]
Thanks. Feel free to edit the wiki page by yourself the next time.
