### ISSUE TITLE
`setDT` Fails to Detect Locked Objects In Corner Case

### ISSUE THREAD

**Issue by brodieG** [Rdatatable/data.table#1827]
Warning, running the following code will modify objects in locked namespaces:

```
mtcars2 <- mtcars
setDT(mtcars2)
mtcars                         # this is now a data.table
```

Obviously this happens because `mtcars` is never copied since `mtcars2` is not touched.  This bypasses the `setDT` [safety check](https://github.com/Rdatatable/data.table/blob/master/R/data.table.R#L2627) because the name `mtcars2` is defined in `.RGlobalEnv` and is not locked, even though the associated SEXP is still the one in `package:datasets`.

This actual issue came up in the following example:

```
library(magrittr)
mtcars %>% setDT
```

Where magrittr "copies" `mtcars` to `.`, but since `.` isn't modified, it still points to the original `mtcars` SEXP.

**Comment by arunsrinivasan** [comment]
Unfortunately locked binding allows an object to be modified by reference. `setDT` checks if an environment is locked, and if so errors. But `mtcars2` isn't. I don't think there's anything we can do about this.

**Comment by brodieG** [comment]
You could check whether `NAMED() == 2` and refuse to apply `setDT`, with a warning on how to circumvent, and possibly an argument in `setDT(force=TRUE)`  to override.  Not a huge deal in my books though.

**Comment by arunsrinivasan** [comment]
Brodie, those won't work since all data.frames have `NAMED()` = 2 upon creation.

**Comment by brodieG** [comment]
Didn't realize that.  Do you want me to close this or just leave it here as `wontfix` for reference?

**Comment by arunsrinivasan** [comment]
It's better to have it open, since it's still an issue. I labelled it just for easier searching.
