### ISSUE TITLE
duplicate warning in 1.9.7 - how to switch this off

### ISSUE THREAD

**Issue by carbonmetrics** [Rdatatable/data.table#1841]
I am using data.table 1.9.7.
when I run `df[!duplicated(df), ] `in a function I get this message:

`Default value of duplicated.data.table method's 'by' argument will be changed to seq_along(x) (from key(x)) from the next release to be consistent with the default behaviour of base::unique.data.frame.
`

How do I switch this off? I have tried `suppressMessages` and checked that the `verbose` option in data.table is off. In the duplicated documentation I can't find what data.table wants me to do now.

**Comment by jangorecki** [comment]
Provide `by=key(df)` argument to `duplicated` call, you can also remove key from `df` - but because you do join here then adding `on="oldkeycols"` would be required. This messages is here to prevent from silently breaking the code on update to 1.9.8.

**Comment by arunsrinivasan** [comment]
Will improve message, and probably add a global option. Thanks.

**Comment by mattdowle** [comment]
As @arunsrinivasan suggested have now added a global option and moved the message to the startup banner.  See commits to close #1284.  Thanks for highlighting it @carbonmetrics.
