### ISSUE TITLE
FR: Add warning "Supplied 0 items to be assigned to group ..."

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#1843]
Example:

```r
library(data.table)
DT = data.table(a = c(1,1,1,2), b = 1:4)
DT[, x := b[b > 1], by=a]
# Warning message:
# In `[.data.table`(DT, , `:=`(x, b[b > 1]), by = a) :
#   Supplied 2 items to be assigned to group 1 of size 3 in column 'x' (recycled leaving remainder of 1 # items).

DT = data.table(a = c(1,1,1,2), b = 1:4)
DT[, x := b[b > 3], by=a]
# no warning
```

Example in the wild: http://stackoverflow.com/a/39360845/

Possibly related to #681

**Comment by MichaelChirico** [comment]
has the potential to return 1000s of warnings, or else one really long
warning, no?

**Comment by franknarf1** [comment]
@MichaelChirico Yeah, one per `by` group, which is the same as the other warning. By the way, with 50+ warnings, printing is suppressed:

    DT = data.table(id = rep(1:100, each=4), b = 1:4); DT[, x := b[b > 1], by=id]
    # There were 50 or more warnings (use warnings() to see the first 50)

**Comment by arunsrinivasan** [comment]
What's the reason for a warning here? The warning in previous case is due to recycling leaving a remainder (which is probably unlikely).

**Comment by franknarf1** [comment]
@arunsrinivasan I was thinking: to catch mistakes like the example I gave and the one akrun made in the link. The user mistakenly thinks that they've passed the correct number of rows (1, .N or something recyclable), but instead passed zero. 

But now that I think about it, this would also warn when doing `DT[, y := if (max(b) > 3) "A", by=a]`, which would be annoying / undesirable, so maybe it is a bad idea. Feel free to close it.

**Comment by arunsrinivasan** [comment]
Yes, I think the current behaviour is fine.
