### ISSUE TITLE
unwanted vectorization in using function in j

### ISSUE THREAD

**Issue by dracodoc** [Rdatatable/data.table#1848]
I'm using a function for sub assignment, which is not vectorized. However `data.table` seemed to be vectorizng it and had errors:
```
DT <- data.table(letters[1:5], 1:5)
DT2 <- data.table(letters[1:5], 11:15)
fun <- function(index) {
  r <- DT2[V1 == index, V2]
  return(r+10)
}
DT[V2 <3, V3 := fun(V1)]
```

    Error in `[.data.table`(DT2, V1 == index, V2) : 
      RHS of == is length 2 which is not 1 or nrow (5). For robustness, 
    no recycling is allowed (other than of length 1 RHS). 
    Consider %in% instead. 

The `fun` here may seem meaningless or can be replaced with a merge. But it is just a simplified version to show the error. The function is intended to only take one parameter from current row, but `data.table` seemed to provided the whole column to the function, while it is not vectorized by design.

**Comment by MichaelChirico** [comment]
doesn't seem like a problem with data.table to me...

**Comment by dracodoc** [comment]
@MichaelChirico , compare this:

```
# this worked
DT[, V3 := fun(V1)]
# this has errors
DT[V2 <3, V3 := fun(V1)]
## Error in `[.data.table`(DT2, V1 == index, V2) : 
##  RHS of == is length 2 which is not 1 or nrow (5). For robustness, no recycling is allowed (other than of length 1 RHS). Consider %in% instead. 
```

I think the problem happened when i is taking a subset, but data.table is only expecting either 1 or nrow in j.

**Comment by MichaelChirico** [comment]
that works by construction.

it's still vectorized -- you're still passing the whole column, but it's
row-by row identical to itself.

try DT[ , V3 := fun(V1 + c(1, rep(0, .N - 1)))]

**Comment by jangorecki** [comment]
The following use case you wrote is invalid, according to your use of `[` inside `fun` I would add the following input check to prevent invalid usage.
```
fun <- function(index) {
  stopifnot(is.character(index), length(index) <= 1)
  r <- DT2[V1 == index, V2]
  return(r+10)
}
```
It is not clear what you want to achieve, maybe Michael already solved your problem with his single call to DT, not sure. If it didn't I think the best place would be to move problem to SO, including a little more background, of course keeping it simple. Many of us read SO too.

**Comment by dracodoc** [comment]
What I want is just subassignment a subset rows with column by a function. Without the subset in i, the assignment with function works. @MichaelChirico 's code showed that the function call is vectorized, this is known since the error message hinted that that line took a vector as input. 

I later found out the error in this example can be solved using `%in%` instead of `==` inside the function, just as the error message hinted. However my actual usage have multiple places using column value, and I cannot let them take vector value.

I found wrapping my fun with `Vectorize` seemed solve the problem.

**Comment by dracodoc** [comment]
I think `data.table` can handle the unvectorized function for simple column assignment, but with subassignment it doesn't work with unvectorized function. Wrapping with `Vectorize` is a simple solution, though I'm wondering if the subassignment can be improved to remove this requirement.
