### ISSUE TITLE
setDTthreads + mclapply hang for larger tables

### ISSUE THREAD

**Issue by mgahan** [Rdatatable/data.table#1849]
`setDTthreads` seems to have an issue with nested parallism for large files but not small files. Here is an example:

## test.R 

```
#!/usr/bin/env r
# test.R

library(data.table)
library(parallel)
setDTthreads(1)

test_func_small <- function(x) {
	setDTthreads(1)
	test <- data.table(A=1:100, B=1:100)
	fwrite(test, paste0("testSmall",x,".csv"))
	return(NULL)
}

test_func_big <- function(x) {
	setDTthreads(1)
	test <- data.table(A=1:1e5, B=1:e5)
	fwrite(test, paste0("testBig",x,".csv"))
	return(NULL)
}

smallOutput <- mclapply(1:20, test_func_small)
bigOutput <- mclapply(1:20, test_func_big)
```

This issue seems to have occurred in the transition from `setthreads` to `setDTthreads`.

Here is my output when I run:

`nohup r test.R &`

## nohup.out

The nested parallelism works for the small files but errors out for the big files. Any possible ideas for a temporary fix? This same code seemed to work before with `setthreads`. 

```
Warning message:
In mclapply(1:20, test_func_big) :
  all scheduled cores encountered errors in user code
```

## Session Info

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS
```

**Comment by arunsrinivasan** [comment]
Please test again. Seems like Matt has fixed it.

**Comment by mgahan** [comment]
This still seems to be giving me the same error. It is possible it is on my side.

```
Warning message:
In mclapply(1:20, test_func_big) :
  all scheduled cores encountered errors in user code
```

Using this version of `data.table`:

```
> library(data.table)
data.table 1.9.7 IN DEVELOPMENT built 2016-09-24 08:43:00 UTC; travis
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Please type: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes and live news: http://r-datatable.com
```

**Comment by mgahan** [comment]
Should this issue be closed?

**Comment by mattdowle** [comment]
@mgahan Do you still have the problem with calling `fwrite` from `parallel::mclapply`?  I think this was fixed a year ago.  Could you try again with 1.10.4-2 on CRAN?  It might have been that you didn't quite catch the update in dev a year ago.   If you still have the problem,  yes,  please reopen.

**Comment by mgahan** [comment]
I just tested this using a fresh Docker: rocker/rbase:latest (3.4.2) with `data.table_1.10.4-2`. Everything looks good! No errors. Thanks @mattdowle!
