### ISSUE TITLE
Fwrite fails when writing integer64

### ISSUE THREAD

**Issue by rodonn** [Rdatatable/data.table#1850]
```
require(data.table)
require(bit64)

test = data.table(a = c(as.integer64("250025208939"), 1, 2, 3),
                  b = rnorm(4))


fwrite(test, "~/test.csv")
```

The resulting file has the following contents

```
a,b
).-).0-*(+,))+(E-312,1.04402420706055
).-).0-*(+,))+(E-324,0.817949584061257
).-).0-*(+,))+(E-324,-0.0471162845556441
).-).0-*(+,))+(E-323,-0.484982585999501
```

It's easy enough to work around the problem by converting any integer64 columns to strings before calling fwrite, but it would probably good to warn if integer64 is not supported.

**Comment by MichaelChirico** [comment]
This is already mentioned in #1664; hopefully will be handled by 1.9.8

**Comment by jangorecki** [comment]
This was solved by recent commit by Matt.
Your code now produce following csv:
```
cat ~/test.csv
#a,b
#250025208939,-1.51047609506293
#1,1.07577126001336
#2,0.153891060144299
#3,0.627545978511813
```
