### ISSUE TITLE
fread very slow

### ISSUE THREAD

**Issue by lmanchon** [Rdatatable/data.table#1851]
--Hi,
just to inform you that i have tested fread with multiple (~980) input files, 12M each, 
and it takes too much time,
whereas in version 1.9.6 fread was very speed.

my code:
go <- Sys.time()
library(data.table)
filenames <- Sys.glob("*.txt")
nb=length(filenames)  #nb=976
colsToKeep <- c(2)
ldf=NULL
ldf = lapply(filenames, function(x) {
      dat = fread(x, header=FALSE, sep="\t", select=colsToKeep)
      names(dat) = c(sub('.txt','',x))
      return(dat)
})
library(dplyr)
df = bind_cols(ldf)

thank you --

**Comment by MichaelChirico** [comment]
this is useless without more information

**Comment by lmanchon** [comment]
number of files: ls *.txt | wc -l
976
Each file (12M) has 2 columns and 675530 lines

with data.table_1.9.7:
go <- Sys.time()
library(data.table)
filenames <- Sys.glob("*.txt")
nb=length(filenames)
colsToKeep <- c(2)
ldf=NULL
ldf = lapply(filenames, function(x) {
      dat = fread(x, header=FALSE, sep="\t", select=colsToKeep)
      names(dat) = c(sub('.txt','',x))
      return(dat)
})
print(Sys.time()-go)
Time difference of 7.699174 mins

with data.table_1.9.6:
go <- Sys.time()
library(data.table)
filenames <- Sys.glob("*.txt")
nb=length(filenames)
colsToKeep <- c(2)
ldf=NULL
ldf = lapply(filenames, function(x) {
      dat = fread(x, header=FALSE, sep="\t", select=colsToKeep)
      names(dat) = c(sub('.txt','',x))
      return(dat)
})
print(Sys.time()-go)
Time difference of 6.817499 mins

~1 min less, you are right maybe this is not significant.

**Comment by MichaelChirico** [comment]
Can you gist one of the files? Perhaps a spoofed/anonymized version if it's private

**Comment by lmanchon** [comment]
i have zipped 2 input files: 3.6M
[input.zip](https://github.com/Rdatatable/data.table/files/488204/input.zip)

remove the zip asap you get it.

**Comment by MichaelChirico** [comment]
have it

**Comment by MichaelChirico** [comment]
I don't experience any appreciable slowdown:

From 1.9.6

```
system.time(fread("SRR934267.txt", sep = "\t", select = 2L))
#    user  system elapsed 
#   0.032   0.000   0.033 
 
system.time(rbindlist(lapply(setNames(
  nm = list.files(pattern = "\\.txt")),
  fread, sep = "\t", select = 2L),
  idcol = TRUE))
#    user  system elapsed 
#   0.176   0.000   0.177 
```

From 1.9.7 (built just now)

```
system.time(fread("SRR934267.txt", sep = "\t", select = 2L))
#    user  system elapsed 
#   0.032   0.004   0.035 

system.time(rbindlist(lapply(setNames(
  nm = list.files(pattern = "\\.txt")),
  fread, sep = "\t", select = 2L),
  idcol = TRUE))
#    user  system elapsed 
#   0.128   0.004   0.132 
```

**Comment by lmanchon** [comment]
yes, it's not significant, i think i can update my code to speed up the construction of the data.frame.
is the fread function coded in data.table use the C 'read' function (from lib unistd.h) ?

**Comment by lmanchon** [comment]
R version 3.2.1 compiled with intel/15.0.3.187
OS: Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Comment by jangorecki** [comment]
@lmanchon Provide reproducible code in single chunk. Ensure that you measure only time of `fread` and not other function calls, use `proc.time` instead of `system.time`. If problem still occurs then please reopen.
