### ISSUE TITLE
Print a data.table built in a function

### ISSUE THREAD

**Issue by Jean-Romain** [Rdatatable/data.table#1854]
Maybe this issue is related to #1852 . When a `data.table` is built in a function and some processes are done by reference the display of the output fail (display nothing).

Here a toy example

```r
foo = function(x, y, z)
{
  dt = data.table(x, y, z)
  dt[, `:=`(t = x + z, u = y + z)]
  return(dt)
}

library(data.table)

x = runif(5) ; y = runif(5) ; z = runif(5)

foo(x, y, z)
# Nothing displayed

ret = foo(x, y, z)
ret
# Nothing displayed

print(ret)
# Works
```

- **Package** : data.table 1.9.6
- **R** :  3.3.1
- **OS** : Linux Mint 17 and 18

**Comment by MichaelChirico** [comment]
Put `return(dt[])` in `foo`

**Comment by Jean-Romain** [comment]
It works. Is there a document that explain why (I'm curious).

**Comment by MichaelChirico** [comment]
See [FAQ 2.23](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-faq.html#why-do-i-have-to-type-dt-sometimes-twice-after-using-to-print-the-result-to-console)
