### ISSUE TITLE
[Request] rollapply written in data.table

### ISSUE THREAD

**Issue by ghost** [Rdatatable/data.table#1855]
My apologies if this has already been brought up but do you plan on ever writing a rollapply function for data.table?

I know that you can use xts::rollapply function inside of data.table, however, xts::rollapply is still slow. I get the feeling that if a data.table::rollapply function was written utilizing data.table's radix sorting, it could be much faster than anything that is available right now. Without it, people just keep building c++ libraries to perform quick rolling time-series calcs...

**Comment by jangorecki** [comment]
rollapply even when developed in data.table might not be as fast as custom built c++ code. Just because it is not possible to effectively optimize arbitrary R function.
closing as duplicate of #2778
