### ISSUE TITLE
Unexpected Behavior With %between% Operator

### ISSUE THREAD

**Issue by peterlittlejohn** [Rdatatable/data.table#1860]
Hello,

I'm running
R 3.2.3 on x86_64-redhat-linux-gnu
and
data.table 1.9.7 IN DEVELOPMENT built 2016-09-29 11:37:39 UTC; travis

I came across the following behavior, which I would deem erroneous.

`d <- data.table(a=1:10)`

Example 1: output is incorrect
`d[a%between%1:2*2] ## it's sloppy, but should work`

Example 2: output is incorrect
`d[a%between%(1:2)*2]`
   a
1: 2
2: 2

Example 3: output is correct
`d[a%between%((1:2)*2)]`
   a
1: 2
2: 3
3: 4

**Comment by MichaelChirico** [comment]
This is not a `data.table` problem. This is how R's order of operations works with infix operators.

See [`?Syntax`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Syntax.html). Compare:

```
c(2,4) %in% 1:2*2
# [1] 2 0
c(2,4) %in% (1:2)*2
# [1] 2 0
c(2,4) %in% (1:2*2)
# [1] TRUE TRUE
```
