### ISSUE TITLE
strange behavior (functions not recognizing key)

### ISSUE THREAD

**Issue by jfrostad** [Rdatatable/data.table#1861]
Hi,

I am encountering some strange behavior when running data.table 1.9.7 on R version 3.2.4 using my institution's unix cluster. This behavior just began today without update to my version of R or data.table, though I have tried removing and reinstalling 1.9.7 from github, to no avail.

The issue is that functions that I understood to automatically use the key do not seem to be recognizing the key. For example:

** to demonstrate clean session of R and clean install of data.table 1.9.7 **
 jfrostad@cn406:R

R version 3.2.4 Revised (2016-03-16 r70336) -- "Very Secure Dishes"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> remove.packages("data.table")                         # First remove the current version
Removing package from ‘/snfs2/HOME/jfrostad/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
> install.packages("data.table", type = "source",
+     repos = "http://Rdatatable.github.io/data.table") # Then install devel version
Installing package into ‘/snfs2/HOME/jfrostad/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://Rdatatable.github.io/data.table/src/contrib/data.table_1.9.7.tar.gz'
Content type 'application/octet-stream' length 2746374 bytes (2.6 MB)
==================================================
downloaded 2.6 MB

* installing *source* package ‘data.table’ ...
** libs
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c assign.c -o assign.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c between.c -o between.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c bmerge.c -o bmerge.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c chmatch.c -o chmatch.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c dogroups.c -o dogroups.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c fastmean.c -o fastmean.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c fcast.c -o fcast.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c fmelt.c -o fmelt.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c forder.c -o forder.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c frank.c -o frank.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c fread.c -o fread.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c fsort.c -o fsort.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c fwrite.c -o fwrite.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c gsumm.c -o gsumm.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c ijoin.c -o ijoin.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c init.c -o init.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c inrange.c -o inrange.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c openmp-utils.c -o openmp-utils.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c quickselect.c -o quickselect.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c rbindlist.c -o rbindlist.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c reorder.c -o reorder.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c shift.c -o shift.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c subset.c -o subset.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c transpose.c -o transpose.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c uniqlist.c -o uniqlist.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c vecseq.c -o vecseq.o
gcc -std=gnu99 -I/share/local/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -g -O2  -c wrappers.c -o wrappers.o
gcc -std=gnu99 -shared -L/share/local/R-3.2.4/lib64/R/lib -L/usr/local/lib64 -o data.table.so assign.o between.o bmerge.o chmatch.o dogroups.o fastmean.o fcast.o fmelt.o forder.o frank.o fread.o fsort.o fwrite.o gsumm.o ijoin.o init.o inrange.o openmp-utils.o quickselect.o rbindlist.o reorder.o shift.o subset.o transpose.o uniqlist.o vecseq.o wrappers.o -fopenmp -L/share/local/R-3.2.4/lib64/R/lib -lR
mv data.table.so datatable.so
if [ "" != "Windows_NT" ] && [ `uname -s` = 'Darwin' ]; then install_name_tool -id datatable.so datatable.so; fi
installing to /snfs2/HOME/jfrostad/R/x86_64-pc-linux-gnu-library/3.2/data.table/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (data.table)

The downloaded source packages are in
        ‘/tmp/RtmpV4nR4Y/downloaded_packages’
> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.8 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] tools_3.2.4
> require(data.table)
Loading required package: data.table
data.table 1.9.7 IN DEVELOPMENT built 2016-09-29 11:37:39 UTC; travis
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Please type: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes and live news: http://r-datatable.com

**to demonstrate issue using the unique() function and the example in the help file**

> DT <- data.table(A = rep(1:3, each=4), B = rep(1:4, each=3), C = rep(1:2, 6), key = "A,B")
> duplicated(DT)
 [1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
> unique(DT)
    A B C
 1: 1 1 1
 2: 1 1 2
 3: 1 2 2
 4: 2 2 1
 5: 2 2 2
 6: 2 3 1
 7: 2 3 2
 8: 3 3 1
 9: 3 4 2
10: 3 4 1
> uniqueN(DT)
[1] 10
> unique(DT, by=c('A','B'))
   A B C
1: 1 1 1
2: 1 2 2
3: 2 2 1
4: 2 3 1
5: 3 3 1
6: 3 4 2
> uniqueN(DT, by=c('A','B'))
[1] 6
> key(DT)
[1] "A" "B"
> uniqueN(DT, by=key(DT))
[1] 6
> unique(DT, by=key(DT))
   A B C
1: 1 1 1
2: 1 2 2
3: 2 2 1
4: 2 3 1
5: 3 3 1
6: 3 4 2

**end example**

I am unable to replicate this behavior on my Windows PC running 1.9.7 as well.

Thoughts on a solution?

**Comment by franknarf1** [comment]
Item 1 in [the news](https://github.com/Rdatatable/data.table/blob/master/NEWS.md) for 1.9.7 (the current devel version) explains that the key is no longer used by default for these functions.

**Comment by jfrostad** [comment]
I see! Well that definitely explains it, sorry for not reading the documentation! I still don't understand why I am not experiencing this behavior on my Windows machine (also running 1.9.7)?

> DT <- data.table(A = rep(1:3, each=4), B = rep(1:4, each=3), C = rep(1:2, 6), key = "A,B")
> duplicated(DT)
 [1] FALSE  TRUE  TRUE FALSE
 [5] FALSE  TRUE FALSE  TRUE
 [9] FALSE FALSE  TRUE  TRUE
> unique(DT)
   A B C
1: 1 1 1
2: 1 2 2
3: 2 2 1
4: 2 3 1
5: 3 3 1
6: 3 4 2
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] grid      parallel  stats    
[4] graphics  grDevices utils    
[7] datasets  methods   base     

other attached packages:
 [1] plyr_1.8.3        
 [2] dplyr_0.4.3       
 [3] gridExtra_2.0.0   
 [4] ggthemes_3.0.2    
 [5] RColorBrewer_1.1-2
 [6] stringr_1.0.0     
 [7] RMySQL_0.10.7     
 [8] DBI_0.3.1         
 [9] magrittr_1.5      
[10] ggplot2_2.0.0     
[11] data.table_1.9.7  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2     
 [2] assertthat_0.1  
 [3] digest_0.6.8    
 [4] R6_2.1.1        
 [5] gtable_0.1.2    
 [6] pacman_0.3.0    
 [7] scales_0.3.0    
 [8] stringi_1.0-1   
 [9] reshape2_1.4.1  
[10] labeling_0.3    
[11] tools_3.2.3     
[12] munsell_0.4.2   
[13] colorspace_1.2-6
>

**Comment by arunsrinivasan** [comment]
It is very likely that they are both different commits. Please try to update by following the install instructions under wiki.

Feel free to reach open if you are still reproduce the issue after updating.
