### ISSUE TITLE
Add shift support for lists columns

### ISSUE THREAD

**Issue by statquant** [Rdatatable/data.table#1862]
From tests (and reading vignette) my understanding is that `shift` does not work for lists columns (nor does base::diff).
Would that be possible to add support ?

Example: a data.table of lm objects, and we want to call predict.lm with the previous lm object

**Comment by franknarf1** [comment]
See  #1595

**Comment by statquant** [comment]
Brilliant !

**Comment by franknarf1** [comment]
Closing it is fine, I bet.
