### ISSUE TITLE
use and save intermediate results in `:=` expression, feature request

### ISSUE THREAD

**Issue by GeraldCNelson** [Rdatatable/data.table#1865]
I'd like to use intermediate results like this where the x vector is first calculated and then used to generate the y vector, and both are kept (i.e., x is not an intermediate calculation
```
DT[, `:=` (
x = 1 + 2,
y = x + 3)
]
```

**Comment by MichaelChirico** [comment]
like

```
DT[ , `:=`(x = x <- 1 + 2,
          y = x + 3)]
```

?

**Comment by franknarf1** [comment]
@jangorecki I'm wondering in what sense this is not reproducible..?

To me, it looks like a dupe of #659

**Comment by jangorecki** [comment]
@franknarf1 To reflect issue quality on that matter ;)

**Comment by GeraldCNelson** [comment]
There are several ways to achieve the results I'm looking for. I just thought that the structure I proposed in my feature request was the simplest way. Just turns out that it doesn't work in the current version of data.table (which by the way, is awesome. I don't suppose we could replace data frames...).

**Comment by MichaelChirico** [comment]
@GeraldCNelson as pointed out by @franknarf1, keep an eye out for #659, as it does indeed seem to cover what you're after.

**Comment by GeraldCNelson** [comment]
@MichaelChirico, it does. Looks like a speed issue is why it hasn't been implemented.
