### ISSUE TITLE
fread give errorness warning (read-error)

### ISSUE THREAD

**Issue by rohlfs** [Rdatatable/data.table#1866]
fread("multi.txt")

Warnmeldung:
In fread("multi.txt") :
  Unable to find 5 lines with expected number of columns (+   last)

When trying standard-tool "read.table", there was no error:
read.delim("multi.csv")
[multi.txt](https://github.com/Rdatatable/data.table/files/512321/multi.txt)

**Comment by MichaelChirico** [comment]
are you allowed to share the data file?

**Comment by rohlfs** [comment]
yes, it's mine. I can't see any issue against sharing.

**Comment by MichaelChirico** [comment]
`fread` works fine for me. Please provide `sessionInfo()` if you still are having trouble.

```
fread("multi.txt")
#        remoteAccountNumber id_Person
#  1:                3662603         1
#  2: DE08500800000091331501        61
#  3:             4084300300        61
#  4: DE02662400020115507600        61
#  5: DE61514206000013259097        69
#  6: DE63430609678034667600        82
#  7: DE74100100100226265106        99
#  8: DE75100205000003287301       191
#  9: DE47641500200000155467       195
# 10: DE86501108006161604670       219
# 11: DE11590100660166262660       234
# 12: DE93590100660722928664       234
# 13: DE46613700240063460001       241
# 14: DE54478400807989625996       273
# 15: DE31740201000108604985       301
# 16: DE38640500000000024055       199
```

**Comment by rohlfs** [comment]
The Problem still exists. I check it under two differen OS- and R-Versions:

> sessionInfo()
((1))
R version 3.2.2 (2015-08-14)
Platform: amd64-portbld-freebsd10.1 (64-bit)

((2))
R version 3.3.1 (2016-06-21)
Platform: amd64-portbld-freebsd10.2 (64-bit)


10.1-RELEASE-p24 FreeBSD 10.1-RELEASE-p24 #0: Mon Nov  2 12:17:28 UTC 2015     
Platform: amd64-portbld-freebsd10.2 (64-bit)

10.2-RELEASE-p18 FreeBSD 10.2-RELEASE-p18 #0: Sat May 28 08:53:43 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64



locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.6

loaded via a namespace (and not attached):
[1] chron_2.3-43
j

**Comment by arunsrinivasan** [comment]
Please check against development version before filing issues. See wiki for installation instructions.

Feel free to r open if you qr  able to r produce in v 1.9.7, devel.
