### ISSUE TITLE
merge error on date columns -- unmatched rows returned as ~0 instead of NA

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1874]
I'm trying to merge-and-define using two `data.table`s on a `Date` column. Some of the entries aren't matched, so the rows should be defined as `NA`; instead they're returned as ~0:

```
library(data.table)
library(quantmod)
getSymbols("CPIAUCNS", src = "FRED")
cpi = as.data.table(CPIAUCNS)

DT = data.table(date = structure(c(17014, 17045), class = "Date"),
                price = c(1.11, 3.92))

DT[cpi, rel := price / i.CPIAUCNS, on = c(date = "index")][]
#          date price           rel
# 1: 2016-08-01  1.11  4.608620e-03
# 2: 2016-09-01  3.92 2.121996e-314
```

The first row was matched, and `rel` is defined properly.

The second row _shouldn't_ have been matched (the CPI data, as of this writing, ends at August 2016).

However, the row is returning something near 0.

---

Converting to `integer` doesn't solve the problem:

```
DT[ , date_i := as.integer(date)]
cpi[ , date_i := as.integer(index)]

DT[cpi, rel_i := price / i.CPIAUCNS, on = "date_i"][]
#          date price           rel date_i         rel_i
# 1: 2016-08-01  1.11  4.608620e-03  17014  4.608620e-03
# 2: 2016-09-01  3.92 2.121996e-314  17045 2.302377e-316
```

The ~0 number has changed, not sure why.

**Comment by franknarf1** [comment]
That's weird. I guess it's a bug, but stumbled into a few workarounds:

    DT[, rel := NULL ]
    DT[cpi, rel := price / i.CPIAUCNS, on = c(date = "index"), by=.EACHI][]

I guess grouping like that might be inefficient, though. Alternately...

    DT[, rel := NULL ]
    DT[, rel := cpi[DT, on = c(index = "date"), price/CPIAUCNS]]

That seems like the best way, among the workarounds. Finally...

    DT[, rel := NULL ]
    DT[cpi, rel := price / i.CPIAUCNS, on = c(date = "index"), nomatch=0][]

which does the right thing but claims to be ignoring `nomatch`, with warning

> Warning message:
> In `` `[.data.table`(DT, cpi, `:=`(rel, price/i.CPIAUCNS), on = c(date = "index"),``  :
>   nomatch isn't relevant together with :=, ignoring nomatch

By the way, I tested these after converting to IDate. I don't know if there's some good reason to use integers instead.

**Comment by mattdowle** [comment]
Odd indeed.  Especially that it was missed by tests.  Thanks, will take a look ...

**Comment by mattdowle** [comment]
Thanks for spotting and reporting that one @MichaelChirico.  Please reinstall from dev and it should work again.  Missing test added.

**Comment by MichaelChirico** [comment]
thanks Matt! indeed strange that this is the first time this issue came up! there may have been s change in code elsewhere at some point? anyway thanks again!
