### ISSUE TITLE
[Request] ``setTbl`` function 

### ISSUE THREAD

**Issue by kendonB** [Rdatatable/data.table#1877]
My use case is passing a `tbl_df` to a function, which converts it to a `data.table` for some data heavy work, then outputs a `tbl_df`. The input object in `.GlobalEnv` is then converted to a `data.table`.

I can use `setDF` to reset the input object in `.GlobalEnv` back to a `data.frame`, but I'd like to be able to set it back to a `tbl_df`.

Thanks! Let me know if you'd like an MRE.

**Comment by MichaelChirico** [comment]
seems reasonable to me! why don't you take a gander at how setDF works --
should be easy to extend it to return something with `tbl_df` class as
well. If so, feel free to file a pull request!

**Comment by jangorecki** [comment]
I'm not aware how those classes differentiate, but better than single `tbl_df` is to give ability to set also others, potentially useful, classes like: `data_frame`, `tibble`, `tribble`. And that seems to be overlapping with #1412

**Comment by MichaelChirico** [comment]
good point jan. agree piecemeal solutions will quickly get out of hand;
this seems like a perfect use case for showcasing the utility of setclass.

**Comment by kendonB** [comment]
Thanks everyone; for now, I'll use:

`setattr(x, "class", c("tbl", "tbl_df", "data.frame"))`

for setting the class back to a standard tibble. In case people land here,

`setattr(x, "class", c("tbl_dt", "tbl", "data.table", "data.frame"))`

should work for setting a ``tbl_dt``.

**Comment by MichaelChirico** [comment]
I think `setattr()` is the right approach, maybe `setclass()` if that's added eventually, but that's a separate discussion. Closing here.
