### ISSUE TITLE
patterns in .SDcols

### ISSUE THREAD

**Issue by eantonya** [Rdatatable/data.table#1878]
I thought I've seen this FR before, but couldn't find it.

Would be nice if we could specify column names using regex expressions in `.SDcols`. Currently one has to do something like `.SDcols = grep("mypattern", names(myDT))`, which you can't chain on, and is pretty fragile.

Perhaps the `patterns` function from `melt` can be reused here, making the syntax `.SDcols = patterns("mypattern")`.

**Comment by ksavin** [comment]
I'd like to add, that `patterns` would be super useful in `j` as well.

It is often needed to select columns with `grep` and the only way is to refer it via `names()`, e.g.
`veryLongDataTableName[, grep('lag', names(veryLongDataTableName), with = FALSE]` 

or to remove multiple columns, e.g. 
`dt[, (grep('lag', names(dt)) := NULL]`

or to make new column names:
`dt[, paste0(grep('^test', names(dt), value = TRUE), '_sqrt') := lapply(.SD, sqrt), .SDcols = grep('^test', names(dt), value = TRUE)]`

These would be much shorter with `patterns` available in j as well:
`veryLongDataTableName[, patterns('lag'), with = FALSE]` 
`dt[, patterns('lag') := NULL]`
`dt[, paste0(patterns('^test'), '_sqrt') := lapply(.SD, sqrt), .SDcols = patterns('^test')]`

Alternatively, it would be handy to have a special symbol for column names, selected in `.SDcols`, e.g. `.NM`

**Comment by MichaelChirico** [comment]
names(.SD) should suffice...

**Comment by ksavin** [comment]
Forgot I am in fact using `names(.SD)` for these cases :)
Still, way cleaner and shorter with patterns.

**Comment by MichaelChirico** [comment]
I do regularly things like `grep(pattern, names(.SD))` (and maybe add `value = TRUE`)... Maybe I'm just used to this setup.

**Comment by mbacou** [comment]
Another one I tend to use is `.SDcols=names(.SD) %like% "mypattern"`, a little ugly. Upvoting this FR as well.

**Comment by hannes101** [comment]
Just as a reference to a SO question.
https://stackoverflow.com/questions/42999949/select-data-table-columns-with-grep-like-partial-matching

**Comment by franknarf1** [comment]
SO q to update: https://stackoverflow.com/questions/47535845/perform-operations-on-data-table-columns-based-on-regex?noredirect=1

**Comment by HughParsonage** [comment]
I wrote [`select_grep`](https://github.com/HughParsonage/hutils/blob/master/R/select_grep.R) in package [hutils ](https://cran.r-project.org/package=hutils)before realizing this was an outstanding issue:

``` r
library(hutils)
library(data.table)
dt <- data.table(x1 = 1, x2 = 2, y = 0)
select_grep(dt, "x")
#>    x1 x2
#> 1:  1  2
    select_grep(dt, "x", .and = "y")
#>    x1 x2 y
#> 1:  1  2 0
    select_grep(dt, "x", .and = "y", .but.not = "x2")
#>    x1 y
#> 1:  1 0
```

Created on 2018-05-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
