### ISSUE TITLE
alias for patterns

### ISSUE THREAD

**Issue by eantonya** [Rdatatable/data.table#1879]
The regular expressions I use with `patterns` are quite often shorter than the word "patterns", and I find it distracting from code, as well as cumbersome to type.

I understand some people might prefer the verboseness of it, but can we also please add some shorthand alias for it?

Common ways to express it in other languages that could be reused here as well are `r("my_regex")` or `~("my_regex")`.

**Comment by MichaelChirico** [comment]
considering, in its actual implementation, patterns is _not_ a function,
this should be pretty easy to accommodate

**Comment by eantonya** [comment]
I just realized that `~("a", "b")` does not form a valid R expression, so I guess that's out (on the other hand `~"a" || "b"` is a valid expression with funky extension possibilities, but maybe that's too much - I'd be perfectly happy with `r("a", "b")`).

**Comment by MichaelChirico** [comment]
I'd rather not introduce any more shorthand that harms readability & is hard to research. pseudo-function `patterns()` is already enough rule-bending IMO.
