### ISSUE TITLE
fread Expected sep (',') but new line

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1882]
Hello.

I've upgraded to the latest development version and when I use fread to read a large csv file 
fread("name.csv", encoding="UTF-8",stringsAsFactors=F, integer64 = "character", na.strings=c("", "NA"))

I get this error:

> Error in fread("unzip -c limpio.zip", encoding = "UTF-8", stringsAsFactors = F,  : 
>   Expected sep (',') but new line, EOF (or other non printing character) ends field 0 when detecting types from point 10: 

The same file can be read without problem in older versions.
The file is properly formated.  I can't upload it because it's very large and contains private data.

**Comment by skanskan** [comment]
I've seen than fwrite sometimes writes files ending with a new empty line, and sometimes writes the last line without creating that new empty line.
If the last element is a missing data, and the file is very long it causes problems when opening it with fread.
You need to edit the file with an external editor en delete the last carriage return.

**Comment by skanskan** [comment]
The problem persists:
I fread a big data.table with many NAs.
I do any operation on it (such as substitutions or remove a column)
I fwrite it as a csv file.
For some reason sometimes fwrite adds an empty line at the end.
If I try to fread it again it produces an error.
I need to delete it manually and save the file back.



I cannot provide a reproducible example because muy dataset is very big.

**Comment by MichaelChirico** [comment]
As a workaround, consider feeding your file through a command line tool instead of manually deleting the bogus line:

http://stackoverflow.com/questions/4881930/bash-remove-the-last-line-from-a-file

**Comment by alexfun** [comment]
I tried `fread("sed -i '$ d' foo.txt")` but that gave me a 

`File is empty: C:\...\Local\Temp\...\file12072506f6356`

 error. Running 

`sed '$ d' foo.txt > foo_new.txt`

 in the command line gives a new file that can be read by fread. My sed version supports -i.

**Comment by skanskan** [comment]
Hello.

I was trying to generate a reproducible error easy to share and I've found the problem is not related to fread nor data.table but unzip.exe when used in this way:
`fread("unzip -c original.zip",...)`
I guess it's a very old executable and doesn't work well with large files or maybe it doesn't work well together with data.table.
It also causes problems cutting the last lines:
https://github.com/Rdatatable/data.table/issues/2003

I'm sorry for the confusion.

fread works well, you can close the issue.

**Comment by MichaelChirico** [comment]
@skanskan you can close the issue yourself...
