### ISSUE TITLE
Question regarding `inrange` 

### ISSUE THREAD

**Issue by DavidArenburg** [Rdatatable/data.table#1884]
Consider this example

```r
dt <- data.table(Test = c(200, 205), Min = c(100, 120), Max = c(200, 205))
dt[,Test %inrange% c(Min, Max)]
## [1] FALSE FALSE
```
Why am I getting `FALSE` for both? If I do just 

```r
200 %inrange% c(120, 205)
## [1] TRUE
``` 

I'm getting the desired output. Isn't `inrange` suppose to, and I quote `?inrange`:

> inrange checks whether each value in x is in between any of the intervals provided in lower,upper.

**Comment by franknarf1** [comment]
Maybe you need a list? `dt[,Test %inrange% .(Min, Max)] # TRUE TRUE`

**Comment by DavidArenburg** [comment]
Yeah you are right. Thanks
