### ISSUE TITLE
feature request : transpose(keep.rownames = T)?

### ISSUE THREAD

**Issue by ghost** [Rdatatable/data.table#1886]
transposing up to now required this:

```
dt = data.table(x=1:5, y=6:10)
t(dt) %>% data.table(keep.rownames = T)
```

, so the `transform` function has potential to cut this short. 
It has however no `keep.rownames = T` argument (or something similar), so the variable names disappear:

```
transpose(dt)
#    V1 V2 V3 V4 V5
#1:  1  2  3  4  5
#2:  6  7  8  9 10
```

what I hoped to see was something like this:

```
#    rn  V1 V2 V3 V4 V5
#1:  x  1  2  3  4  5
#2:  y  6  7  8  9 10
```

**Comment by skanskan** [comment]
This should be easy to implement and an important addition.

**Comment by MichaelChirico** [comment]
could you elaborate with sample input & output?

lists don't really have a "row names" attribute...

**Comment by skanskan** [comment]
Imagine you have a data.table with several columns, such as this toy example.
dt = data.table(A=1:5, B=c(NA,3,3,NA,NA), C=c(NA,NA,9,8,7))

and you want to calculate several things to summarize the different variables.
nas <- t(dt[,lapply(.SD,function(x) sum(is.na(x)))])
sums  <- t(dt[,lapply(.SD,function(x) sum(x,na.rm = T))])
data.table(nas=nas,sums=sums)

Something similar to this:
t(apply(dt,2,function(x) rbind(sum(x,na.rm = T),sum(is.na(x)))))
 
But I having a result with colnames and rownames:
    nas   sums
A   15    0
B    6    3
C   24    2

**Comment by carbonmetrics** [comment]
if the example input & output in the original feature request is not clear enough let me know and I will edit. 

I agree that a list does not have row.names. The function is also intended for data.frames and data.tables however. When you transpose these objects, their variable names would become row.names, in which the `transpose` function does not foresee. Hence the need for the verbose `as.data.table(t(dt), keep.rownames = T)`.

**Comment by MichaelChirico** [comment]
This could have been useful in this [SO](http://stackoverflow.com/a/42937657/3576984) post -- instead of needing the helper function `coefsplit` to break apart the named result of `coef(...)`, we could do `transpose(as.list(coef(...)), keep.rownames = TRUE)`
