### ISSUE TITLE
Unable to find 5 lines with expected number of columns" warning when freading 16 lines #1124

### ISSUE THREAD

**Issue by Fpadt** [Rdatatable/data.table#1887]
Hi, 

seems to me that issue #1124 is back again. It appears only with 16 lines [1124](https://github.com/Rdatatable/data.table/issues/1124)
(or is my software not up to date?) I am running data.table 1.9.6

to reproduce 
`fread("https://www.misoenergy.org/Library/Repository/Market%20Reports/20150531_da_pbc.csv",skip=4)`

`read.dcf(system.file("DESCRIPTION", package="data.table"), c("Packaged","Built"))`
     Packaged                              Built  
[1,] "2015-09-19 04:47:43.628 UTC; mdowle" "R 3.2.2; x86_64-w64-mingw32; 2015-10-15 03:10:44 UTC; windows"

`R.version`
               _  
platform       x86_64-w64-mingw32  
arch           x86_64  
os             mingw32  
system         x86_64, mingw32  
status  
major          3  
minor          3.1  
year           2016  
month          06  
day            21  
svn rev        70800  
language       R  
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by franknarf1** [comment]
Yeah, it's expected that you test on the devel version before reporting a potential bug: https://github.com/Rdatatable/data.table/wiki/Support

**Comment by jangorecki** [comment]
if you can build R pkgs from source, this should work
```r
install.packages("data.table", type="source", repos="http://Rdatatable.github.io/data.table")
```

**Comment by Fpadt** [comment]
currently not able to build, will try on Ubuntu later this week. 
For me not a big problem as I could add a record which made the issue disappear.
Shall I close this issue?

**Comment by jangorecki** [comment]
@Fpadt I tried on current CRAN version and Mac and it reads file properly, feel free to reopen if issue is still reproducible for you.
