### ISSUE TITLE
fread noticeably slower in windows than linux

### ISSUE THREAD

**Issue by mahyarkargar** [Rdatatable/data.table#1888]
Hi,

I recently had to change my OS from Linux Mint 18 to Windows 10. I noticed fread is much slower in Win 10. I installed Win on the identical SSD. My machine has 64G RAM and 500G SSD.
`library(data.table);
rm(list=ls());
DT <- fread("data.csv")`

> DT <- fread("data.csv")
> Read 98504 rows and 135 (of 135) columns from 0.137 GB file in 00:00:22

The same data set took almost half as long to read in Linux. Please let me know if there is anything I can do.

here is my session info:

> R version 3.3.1 (2016-06-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] data.table_1.9.7    RevoUtilsMath_8.0.3
> 
> loaded via a namespace (and not attached):
> [1] RevoUtils_10.0.1 tools_3.3.1

**Comment by jangorecki** [comment]
Looks like you've made the wrong choice ;)
You could additionally:
1. try again on just plain R with data.table without RevoUtils* loaded
2. provide output of fread when done with `verbose=TRUE`
3. provide reproducible example so we can confirm and eventually debug the issue

**Comment by mahyarkargar** [comment]
Unfortunately didn't have a choice on the OS! I would pick Linux over Windows any day!
I ran this example on plain R.
`library(data.table)
rm(list=ls())

n=1e6
DT = data.table( a=sample(1:1000,n,replace=TRUE),
                 b=sample(1:1000,n,replace=TRUE),
                 c=rnorm(n),
                 d=sample(c("foo","bar","baz","qux","quux"),n,replace=TRUE),
                 e=rnorm(n),
                 f=sample(1:1000,n,replace=TRUE) )
DT[2,b:=NA_integer_]
DT[4,c:=NA_real_]
DT[3,d:=NA_character_]
DT[5,d:=""]
DT[2,e:=+Inf]
DT[3,e:=-Inf]
fwrite(DT,"test.csv")
DT <- fread("test.csv",verbose = TRUE)
system.time(DT <- fread("test.csv"))  `

here is the output

> > DT <- fread("test.csv",verbose = TRUE)
> Input contains no \n. Taking this to be a filename to open
> File opened, filesize is 0.049545 GB.
> Memory mapping ... ok
> Detected eol as \r\n (CRLF) in that order, the Windows standard.
> Positioned on line 1 after skip or autostart
> This line is the autostart and not blank so searching up for the last non-blank ... line 1
> Detecting sep ... ','
> Detected 6 columns. Longest stretch was from line 1 to line 30
> Starting data input on line 1 (either column names or first row of data). First 10 characters: a,b,c,d,e,
> All the fields on line 1 are character fields. Treating as the column names.
> Count of eol: 1000001 (including 1 at the end)
> Count of sep: 5000000
> nrow = MIN( nsep [5000000] / (ncol [6] -1), neol [1000001] - endblanks [1] ) = 1000000
> Type codes (point  0): 113431
> Type codes (point  1): 113431
> Type codes (point  2): 113431
> Type codes (point  3): 113431
> Type codes (point  4): 113431
> Type codes (point  5): 113431
> Type codes (point  6): 113431
> Type codes (point  7): 113431
> Type codes (point  8): 113431
> Type codes (point  9): 113431
> Type codes (point 10): 113431
> Type codes: 113431 (after applying colClasses and integer64)
> Type codes: 113431 (after applying drop or select (if supplied)
> Allocating 6 column slots (6 - 0 dropped)
> Read 1000000 rows and 6 (of 6) columns from 0.050 GB file in 00:00:05
> Read 1000000 rows. Exactly what was estimated and allocated up front
>    0.001s (  0%) Memory map (rerun may be quicker)
>    0.000s (  0%) sep and header detection
>    0.154s (  3%) Count rows (wc -l)
>    0.009s (  0%) Column type detection (first, middle and last 5 rows)
>    0.067s (  2%) Allocation of 1000000x6 result (xMB) in RAM
>    4.170s ( 95%) Reading data
>    0.000s (  0%) Allocation for type bumps (if any), including gc time if triggered
>    0.000s (  0%) Coercing data already read in type bumps (if any)
>    0.002s (  0%) Changing na.strings to NA
>    4.403s        Total
> > system.time(DT <- fread("test.csv"))
> Read 1000000 rows and 6 (of 6) columns from 0.050 GB file in 00:00:05
>    user  system elapsed 
>    4.09    0.01    4.09 

My sessioninfo() again
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.7

loaded via a namespace (and not attached):
[1] tools_3.3.1
```

**Comment by mattdowle** [comment]
Sorry it took so long to get to this one.  Found and fixed the Windows-only problem here.
Could you test again please and confirm?  I borrowed a Windows 8.1 laptop and it looks fixed my end.
data.table 1.10.5 IN DEVELOPMENT built 2017-04-15 11:11:18 UTC; appveyor
install.packages("https://ci.appveyor.com/api/buildjobs/1txx94ruv769jc42/artifacts/data.table_1.10.5.zip", repos=NULL)
Thanks, Matt

**Comment by mahyarkargar** [comment]
appreciate the response Matt. that resolved the issue.
best
mahyar

**Comment by mattdowle** [comment]
Great.  Thanks for testing.
