### ISSUE TITLE
Automatic reference to columns in the selected data.table with set()

### ISSUE THREAD

**Issue by hannes101** [Rdatatable/data.table#1893]
I came across an issue, that in the case of set combined with which() in the i clause one needs to explicitly call the data.table and the column name and not just the column name. Isn't the latter not kind of an expected behavior? At least for me it would be more natural to just use the following, since in the first argument the data.table actually is defined already and therefore all selections should only be in reference to that data.table, or?
`set(dt1, i = which(OilWellID == 3), j = "Invest.Period", value = 756)`
Instead it's necessary to explicitly add the call like this:
`set(dt , i = which(dt[["Abandon.Period"]] == 2270L), j = 2L, value = 1L)`

Is it possible to implement the first option as well or is it just not possible?

For a reproducible examples, please see:
https://stackoverflow.com/questions/40304286/setting-a-value-in-a-data-table-with-set-debugging
data.table version is 1.9.6 
R 3.3.0
Thanks for data.table!

**Comment by franknarf1** [comment]
Please post your reproducible example here. Visiting SO, I see you apparently claiming that this works, but it does not, for the simple reason that `OilWellID` does not exist in global scope:

    library(data.table)
    dt1 <- structure(list(OilWellID = 1:5, Invest.Period = c(1L, 1L, 1L, 1L, 1L))
            , .Names = c("OilWellID", "Invest.Period"), class = c("data.table", "data.frame"), row.names = c(NA, -5L))


    set(dt1, i = which(OilWellID == 3), j = "Invest.Period", value = 756)

**Comment by hannes101** [comment]
Ok, this was an error on my side, since OilWellID was in my environment, but that's not really the issue. What I mean is that the following does not work:

```
library(data.table)
  dt <- structure(list(Abandon.Period = c(8135L, 1961L, 18307L, 4353L, 2270L, 7905L, 2600L, 2406L, 2286L, 2464L)
                 , Activity.Flag = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L))
              , .Names = c("Abandon.Period", "Activity.Flag"), row.names = c(NA, -10L), class = c("data.table", "data.frame"))

 set(dt
, i = which(Abandon.Period == 2270L)
, j = 2L
, value = 1111L
)
```
To me it seems a bit odd, that you have to add the additional call to the data.table in `i` `like this:
` set(dt , i = which(dt[["Abandon.Period"]] == 2270L), j = 2L, value = 1L)`
I just would like to know why that's the case.

**Comment by franknarf1** [comment]
@hannes101 I think it's just that `DT[...]` conveniently allows you to refer to column names directly in `...`, while `set` has an interface like a typical R function (well, almost every function except `subset`, `with` and `within`). The interface is clunkier, but I guess it's expected that it is only be needed in rare circumstances. I manage to do almost everything in `DT[...]`. In this case, I guess you know you can write

    dt[ Abandon.Period == 2270L, Activity.Flag := 1111L  ]

**Comment by hannes101** [comment]
Thanks, yeah I know that but am mostly trying to use set(), since it's way faster. Why I perhaps also expected it to work like this was, that in the case of `j` it's perfectly fine to directly use the column name. But perhaps that's because of the different implementation of rows and columns in data.table.

**Comment by MichaelChirico** [comment]
It is implemented differently.

You could try with(dt, set(dt, i = which(Abandon.Period == 2270L), j = 2L,
value = 1L))

**Comment by jangorecki** [comment]
I don't think we should be putting `with` functionality into `set` function, and making it NSE.
Although it annoys me also from time to time, but the proper way is to rewrite `[` to C and to avoid current overhead. Closing for now.
