### ISSUE TITLE
Getting githubio version offline?

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1896]
I'd like to install the latest successful `data.table` build offline (so I don't have access to the `install.packages` approach)... is there a way to do so?

**Comment by jangorecki** [comment]
`install.packages` works for local archives too, just mirror repo from `gh-pages`.
```
git clone --branch gh-pages https://github.com/Rdatatable/data.table.git
Rscript -e 'install.packages("data.table", repos=file.path("file:",normalizePath("data.table")))'
```

**Comment by MichaelChirico** [comment]
but I'm offline so I can't git clone either... but this is in the right
direction. should be able to git clone on a different machine then flash
drive.

**Comment by jangorecki** [comment]
If you have source on disk, you can do everything offline.
```
R CMD build data.table
R CMD check $(ls -1t data.table_*.tar.gz | head -n 1)
mkdir -p cran/src/contrib
mv $(ls -1t data.table_*.tar.gz | head -n 1) cran/src/contrib/.
Rscript -e 'tools::write_PACKAGES(contrib.url("cran"))'
```
then install from it
```
Rscript -e 'install.packages("data.table", repos=file.path("file:",normalizePath("cran")))'
```

**Comment by MichaelChirico** [comment]
Yes, exactly. My question was mainly about how to get the source onto disk, since I didn't know where online I could find the repository.

This should work. Thanks!
