### ISSUE TITLE
Break out rbindlist into new package?

### ISSUE THREAD

**Issue by sckott** [Rdatatable/data.table#1897]
Would it be possible to pull rbindlist out into a new package?  `data.table` isn't too heavy to install, but the lighter the better. A task I almost always do in every package I make is to bind lists into a data.frame. `rbindlist` is very fast for this. But I rarely use the other `data.table` functions in my packages. I am guessing the answer is "no", but thought worth asking

**Comment by MichaelChirico** [comment]
I guess that's part of the aim of Ananda's `splitstackshape`. But it does have `data.table` as a dependency:

https://github.com/mrdwab/splitstackshape

**Comment by sckott** [comment]
@MichaelChirico  thanks for the link, will have a look

**Comment by jangorecki** [comment]
data.table cannot get lighter already, it doesn't depend or import any R package that isn't shipped with base R. Taking out `rbindlist` wouldn't make it lighter as it still would need to compile C language code. You can always use pre-data.table base R solution `do.call("rbind", l)`. I don't think you will find anything lighter and faster than data.table.

**Comment by sckott** [comment]
i'm not asking to make `data.table` lighter, but to have a package with just `rbindlist`. I could use `rbind`, but it doesn't fill when there's mismatch in named elements AFAIK

**Comment by mattdowle** [comment]
In your packages you can import just what you'd like and not the rest with
   `importFrom(data.table, rbindlist)`
More info is in [R-exts 1.5.1](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Specifying-imports-and-exports)
Will that be ok?

**Comment by MichaelChirico** [comment]
will that also export the associated source code?

**Comment by sckott** [comment]
@mattdowle right, I already do that, but of course the whole package needs to be installed still.

Thanks for your replies. Sounds like it's not something of interest, which is very understandable
