### ISSUE TITLE
frank broken?

### ISSUE THREAD

**Issue by colinr23** [Rdatatable/data.table#1901]
moved working code to new machine, frank not found when data.table installed from CRAN. When installed from github, does not work?

> x = c(4, 1, 4, NA, 1, NA, 4)
> frank(x)
Error in dim.data.table(x) : object 'Cdim' not found

**Comment by MichaelChirico** [comment]
I can't reproduce. Both current GH & CRAN versions run as expected

**Comment by colinr23** [comment]
removed it, updated install from cran, now working. Weird... but yep, now working.

**Comment by colinr23** [comment]
![screen shot 2016-11-05 at 1 24 43 pm](https://cloud.githubusercontent.com/assets/1821803/20033341/6de53a5e-a35b-11e6-82ae-ff7ad90eb5d4.png)

**Comment by MichaelChirico** [comment]
current CRAN version is 1.9.6. You must be installing from a poorly-maintained mirror?

**Comment by colinr23** [comment]
could be.. was using whatever the default is in R-studio, i presume through geo-location
