### ISSUE TITLE
ITime could use integer64 for accurate pico second support

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1906]
```
10^12 * 60*60*24 < 2^63     # pico
10^15 * 60*60*24 > 2^64     # femto
```

It could use either integer or integer64.  The typeof() could determine accuracy.  Or maybe a new type I64Time.

**Comment by MichaelChirico** [comment]
I prefer `I64Time` or `ITime64`. Automatically doing it for `ITime` means doubling the storage space automatically _or_ adding a (to me, clunky) new argument in all the `ITime` methods about storage, or else keeping one of those dreaded `options` that might be edited from any environment.

**Comment by jangorecki** [comment]
Is there really a need for pico seconds resolution? nanotime packages provides nano seconds resolution which seems to be high enough IMO.

**Comment by jangorecki** [comment]
Pico time resolution doesn't seems to be demanded feature. I think there is no need to duplicate what nanotime does. It is quite lightweight so it shouldn't be an issue to include it if needed.
