### ISSUE TITLE
warning about invalid .internal.selfref detected on a data.tabe in a list

### ISSUE THREAD

**Issue by maverickg** [Rdatatable/data.table#1908]
Not sure this is a bug, but I am not expecting this warning.  The following is how to replicate:
```r
library(data.table)
dt <- data.table(x=rexp(100),y=rep(LETTERS[1:10], 10))
dtL <- split(dt, by = "y")
dtL[[1]][, x2 := -x]
Warning message:
In `[.data.table`(dtL[[1]], , `:=`(x2, -x)) :
  Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table 
so that := can add this new column by reference. At an earlier point, this data.table 
has been copied by R (or been created manually using structure() or similar). 
Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy 
the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames
 and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 
and DT2 (R's list() used to copy named objects); please upgrade to 
R>v3.0.2 if that is biting. If this message doesn't help, please report 
to datatable-help so the root cause can be fixed.
```

By the way, I am using R 3.3.1 and the most recent data.table by following here https://github.com/Rdatatable/data.table/wiki/Installation

**Comment by MichaelChirico** [comment]
have you searched at all?

the trouble of data.tables in lists is well-reported. there are I think
several outstanding issues. see here for a start

http://stackoverflow.com/q/17133522/3576984

**Comment by maverickg** [comment]
no, but the warning does not make sense as I am using a function (that is, `split`) provided by data.table to generate the list. And this warning does not provide any help on how to fix it.

**Comment by jangorecki** [comment]
@maverickg thanks for reporting, it is now fixed. If all tests will pass it should published in [our repository](https://github.com/Rdatatable/data.table/tree/gh-pages), should be around 10-15minutes.

**Comment by maverickg** [comment]
that is fast!  cool! @jangorecki thanks a lot.

**Comment by parisagavanji** [comment]
Hi
I got the same warning when I was trying package "simPop" in R. Could anyone help me?
I wanted to install data.table package but I could not.

**Comment by jangorecki** [comment]
@parisagavanji please create new issue and provide minimal reproducible example, using latest data.table version.
