### ISSUE TITLE
error installing development version

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1917]
I've tried to install the latest development version, with R 3.3.1.

> install.packages("data.table", type = "source",
>                  repos = "http://Rdatatable.github.io/data.table")

and I get this error

> Warning: newline within quoted string at bootMer.Rd:174
> Error in parse_Rd("c:/temp/RtmpUdSp7X/devtools1f705556b92/lme4-lme4-54f5cab/man/bootMer.Rd",  : 
>   Unexpected end of input (in " quoted string opened at bootMer.Rd:198:23)
> ERROR: installing Rd objects failed for package 'lme4'

**Comment by jangorecki** [comment]
@skanskan could you try `utils::install.packages("data.table", type = "source",
repos = "http://Rdatatable.github.io/data.table")` ?

**Comment by skanskan** [comment]
Yes, I do have Rtools 3.4.
And now it works, I don't know why, maybe it was using an install.package from a different package.

Thanks
