### ISSUE TITLE
v1.9.6 

### ISSUE THREAD

**Issue by Arsova** [Rdatatable/data.table#1922]
> data <- fread(filepath,
+             stringsAsFactors=FALSE, verbose=T, col.names = col.names,
+             showProgress = T)

Input contains no \n. Taking this to be a filename to open
File opened, filesize is 5.898778 GB.
Memory mapping ... ok
Detected eol as \n only (no \r afterwards), the UNIX and Mac standard.
Positioned on line 1 after skip or autostart
This line is the autostart and not blank so searching up for the last non-blank ... line 1
Detecting sep ... '\t'
Detected 22 columns. Longest stretch was from line 1 to line 30
Starting data input on line 1 (either column names or first row of data). First 10 characters: 104066	1	T
Some fields on line 1 are not type character (or are empty). Treating as a data row and using default column names.
Count of eol: 18509489 (including 1 at the end)
Count of sep: 388699255
nrow = MIN( nsep [388699255] / ncol [22] -1, neol [18509489] - nblank [1] ) = 18509488
Type codes (   first 5 rows): 1144244444444444441114
Type codes (+ middle 5 rows): 1144244444444444441114
Type codes (+   last 5 rows): 1144244444444444441114
Type codes: 1144244444444444441114 (after applying colClasses and integer64)
Type codes: 1144244444444444441114 (after applying drop or select (if supplied)
Allocating 22 column slots (22 - 0 dropped)
Read 31.9% of 18509488 rowsBumping column 19 from INT to INT64 on data row 5921832, field contains 'General'
Bumping column 19 from INT64 to REAL on data row 5921832, field contains 'General'
Bumping column 19 from REAL to STR on data row 5921832, field contains 'General'
Error in fread(filepath, stringsAsFactors = FALSE, verbose = T, col.names = col.names,  : 
  Expecting 22 cols, but line 5921832 contains text after processing all cols. It is very likely that this is due to one or more fields having embedded sep='	' and/or (unescaped) '\n' characters within unbalanced unescaped quotes. fread cannot handle such ambiguous cases and those lines may not have been read in as expected. Please read the section on quotes in ?fread.
In addition: Warning message:
In fread(filepath, stringsAsFactors = FALSE, verbose = T, col.names = col.names,  :
  Bumped column 19 to type character on data row 5921832, field contains 'General'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.

**Comment by MichaelChirico** [comment]
please try installing the development version.

**Comment by Arsova** [comment]
When I try to use the development version I have those errors: 
> install.packages("data.table", type = "source",
+                  repos = "http://Rdatatable.github.io/data.table")
trying URL 'http://Rdatatable.github.io/data.table/src/contrib/data.table_1.9.7.tar.gz'
Content type 'application/octet-stream' length 2832330 bytes (2.7 MB)
downloaded 2.7 MB

* installing *source* package 'data.table' ...
** libs

*** arch - i386
Warnung: Ausfьhrung von Kommando 'make -f "Makevars" -f "C:/Users/KRISTI~1.ARS/DOCUME~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/Users/KRISTI~1.ARS/DOCUME~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB="data.table.dll" OBJECTS="assign.o between.o bmerge.o chmatch.o dogroups.o fastmean.o fcast.o fmelt.o forder.o frank.o fread.o fsort.o fwrite.o gsumm.o ijoin.o init.o inrange.o openmp-utils.o quickselect.o rbindlist.o reorder.o shift.o subset.o transpose.o uniqlist.o vecseq.o wrappers.o"' ergab Status 127
ERROR: compilation failed for package 'data.table'
* removing 'C:/Users/kristina.arsova/Documents/R/R-3.3.2/library/data.table'
Warning in install.packages :
  running command '"C:/Users/KRISTI~1.ARS/DOCUME~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\kristina.arsova\Documents\R\R-3.3.2\library" C:\Users\KRISTI~1.ARS\AppData\Local\Temp\4\RtmpkngZ0s/downloaded_packages/data.table_1.9.7.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘data.table’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\kristina.arsova\AppData\Local\Temp\4\RtmpkngZ0s\downloaded_packages’
> library(data.table)
Error in library(data.table) : es gibt kein Paket namens ‘data.table’

**Comment by MichaelChirico** [comment]
Have you installed `RTools`? Follow full instructions [here](https://github.com/Rdatatable/data.table/wiki/Installation)

**Comment by Arsova** [comment]
It still got the same error after installing RTools and development version.
