### ISSUE TITLE
fread/fwrite by connection instead of file.path (for zip files)

### ISSUE THREAD

**Issue by TuSKan** [Rdatatable/data.table#1924]
Is it possible to use fwrite in a connection instead of file.path to write zip files ?

**Comment by TuSKan** [comment]
Sorry! Just saw that is in milestone 1.9.8.

**Comment by mattdowle** [comment]
Package [rio](https://github.com/leeper/rio) already does this very nicely in one step.  It uses `fread` already, and `fwrite` in its next release to CRAN (available now from GitHub).
```R
rio::export(DF,"DF.csv.zip")`
rio::import("DF.csv.zip")
```
I've filed an issue [here](https://github.com/leeper/rio/issues/139) to make that more prominent in its README as it's very nice and there's therefore no need to reimplement this in data.table.
If I've misunderstood, please do reopen.
