### ISSUE TITLE
fwrite breaks can't appropriately deal with string starting with double qoutes

### ISSUE THREAD

**Issue by amatsuo** [Rdatatable/data.table#1925]
`fwrite` output leaves one double-quote without escaping for a string starting with a double quote. This would make an output unreadable. 

Here is an example:
```
test.data <- data.frame(x = c("\"hello", "world"), y = 1:2 )
fwrite(test.data, '~/Desktop/temp.csv')
```
and the output csv file looks like this:
```
x,y
"hello,1
world,2
```

**Comment by MichaelChirico** [comment]
I don't think it's unreadable:

```
fread('x,y
"hello,1
world,2')
#         x y
# 1: "hello 1
# 2:  world 2
```
