### ISSUE TITLE
Update Documentation of `duplicated`

### ISSUE THREAD

**Issue by my-R-help** [Rdatatable/data.table#1931]
In `?duplicated.data.table`, in the "Arguments" section, `by=` is still explained using the old defaults from v1.9.6, i.e. `key(x)`. But starting from v1.9.8 it should be mentioned that it defaults to all columns.

**Comment by my-R-help** [comment]
There are also other references to the keyed columns elsewhere in the documentation of these functions (not only in the "Arguments" section).

**Comment by jangorecki** [comment]
@my-R-help thanks for reporting
