### ISSUE TITLE
Revise FAQ 1.1

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#1936]

**Comment by franknarf1** [comment]
Isn't the quote/eval question (formerly 1.6) still necessary...? It is certainly frequently asked., e.g., twice today: 
- http://stackoverflow.com/questions/42368065/what-is-the-preferred-way-to-programmatically-define-multiple-new-data-table-col 
- http://stackoverflow.com/questions/42376032/how-to-work-with-data-table-in-r-using-column-names-as-variables-e-g-for-funct

I'm looking at this part of the diff: https://github.com/Rdatatable/data.table/commit/0575dcc0856066be43601bf12176d1d866274553#diff-fe7a7c5366ca703107d9365ef6f78884L68
