### ISSUE TITLE
Unable to use data.table's duplicated function

### ISSUE THREAD

**Issue by neomantic** [Rdatatable/data.table#1940]
This issue is very similar to a previous issue that was [closed](
https://github.com/Rdatatable/data.table/issues/1526)

We have upgraded from R 3.3.1 to 3.3.2.  We are using data.table 1.9.8.  After upgrade, a call of `duplicated` on a data.table object is not being dispatched to data.table generic's `duplicated' function. The call to` duplicated` has not changed, but the results are different.  

Concretely, we are doing the following.  Assume that `DataTableWithDuplications` has a column, `DuplicateColumn` with duplicated values represented as chars, dumb opaque values.

``` R
setkey(DataTableWithDuplications, DuplicateColumn)
Duplicates <- duplicated(DataTableWithDuplications)
```
Per the documentation, it should return a logical vector with `TRUE` and `FALSE` values indicating duplicate rows. Prior to upgrade this vector was populated with both values.  After upgrade, the vector is populated with only `FALSE` values. 

The following code, though, returns the correct results

``` R
Duplicates <- duplicated(DataTableWithDuplications, by = "DuplicateColumn")
```
The `by` should be unnecessary and besides, it's not a param of data.table's `duplicated()` function.

**Comment by MichaelChirico** [comment]
IIUC this is covered by the [first item on the changelog for 1.9.6 vs. 1.9.8](https://github.com/Rdatatable/data.table/blob/master/NEWS.md):

> By default all columns are now used by `unique()`, `duplicated()` and `uniqueN()` `data.table` methods, #1284 and #1841. To restore old behaviour: `options(datatable.old.unique.by.key=TRUE)`. In 1 year this option to restore the old default will be deprecated with warning. In 2 years the option will be removed. Please explicity pass `by=key(DT)` for clarity. Only code that relies on the default is affected. 266 CRAN and Bioconductor packages using data.table were checked before release. 9 needed to change and were notified. Any lines of code without test coverage will have been missed by these checks. Any packages not on CRAN or Bioconductor were not checked.

The default value of `by` for `duplicated` has changed.

And `by` is indeed a parameter for `duplicated.data.table`, see `?duplicated.data.table`.

**Comment by neomantic** [comment]
To split-hairs, "The call to `duplicated ` has not change" is indeed correct; is is correct because I didn't change my call to `duplicated`.  What has changed is the return value of `duplicated` between 1.9.6 and 1.9.8.  I didn't expect the return value of a call to change on what I interpreted as a patch release from 6 to 8.

I'll be more careful next time, and read the change logs a little more closely.  Thank you for your help and advice.

**Comment by jangorecki** [comment]
@neomantic most important changes are always listed on top of changelog, be sure to look there on each upgrade. Additionally be aware you can participate in discussions about API changes here in github issues.

**Comment by mattdowle** [comment]
@neomantic Good point about 6 to 8 conveying patch-only.  Yes I should have bumped to 1.10.0 - apologies.  Can't correct it now but next release will be 1.10.0 then with a note about this.
Closing this issue then.
