### ISSUE TITLE
error in fread (showProgress is not type integer but type 'logical'. Please report.)

### ISSUE THREAD

**Issue by demydd** [Rdatatable/data.table#1944]
I have used **fread** to read data. But the error has arisen:  

>showProgress is not type integer but type 'logical'. Please report. 

Here is the reproducible script:

    library(data.table)
    x <- "sgsddsfsfsf"
    write.csv2(x,"check.csv", row.names=FALSE)
    fread("check.csv", stringsAsFactor=FALSE)

**Comment by MichaelChirico** [comment]
Try restarting R and running again. I can't reproduce your example:

```
library(data.table)
x <- "sgsddsfsfsf"
write.csv2(x,"check.csv", row.names=FALSE)
fread("check.csv", stringsAsFactor=FALSE)
#              x
# 1: sgsddsfsfsf
```

Can you give `sessionInfo()` if the problem still arises?

**Comment by demydd** [comment]
Detail see [here](http://stackoverflow.com/questions/40890999/error-in-fread-showprogress-is-not-type-integer-but-type-logical-please-repo.

The poblem still is still here.

**Comment by mattdowle** [comment]
Looks like I'm to blame - sorry. I changed the type of the showProgress global option to logical for fwrite : eb9f7efb075aea7584b147e586120cbedc56ee0e

There was a strange problem in the past almost identical : https://github.com/Rdatatable/data.table/issues/1111

With fresh eyes I don't see why showProgress wasn't type logical in the first place throughout.  Will fix.

In the meantime, passing `showProgress=1L` or `0L` to `fread()` should work.   It's strange it only causes a problem on Windows.
