### ISSUE TITLE
min/max fails on ordered factors when using by

### ISSUE THREAD

**Issue by mcieslik-mctp** [Rdatatable/data.table#1947]
It seems as this is a regression in the latest version (data.table_1.9.8), as it worked before 

```
library(data.table)
test <- data.table(V1=factor(rep(c("a","b"), 10), levels=c("a", "b"), ordered=TRUE), 
V2=rep(c("c","d", "e", "f"), 5))
test[,min(V1)]           # (1)
test[,min(V1),by=V2]     # (2)
```

(1) correctly works but (2) returns an error:
`Error in gmin(V1) : min is not meaningful for factors.`

**Comment by mattdowle** [comment]
(1) dispatches to base R.  (2) dispatched to GForce grouping.
GForce was changed here (a1b1c083ab9e12d9dcb49b05d7053592f0409ae2) but I don't see any notes in NEWS or any tests added. 

R's `min` treats ordered factors and non-ordered factors differently, as you nicely showed.

```
R --vanilla
> x = factor(letters)
> min(x)
Error in Summary.factor(1:26, na.rm = FALSE) : 
  ‘min’ not meaningful for factors
> x = factor(letters, ordered=TRUE)
> min(x)
[1] a
26 Levels: a < b < c < d < e < f < g < h < i < j < k < l < m < n < o < ... < z
```

Yes I guess we should be in line with base R in this regard.  Thanks for highlighting.

**Comment by mbacou** [comment]
Is there a status update about data.table's support for summarizing ordered factors? Won't be implemented? Thx.

**Comment by franknarf1** [comment]
SO q to update: https://stackoverflow.com/questions/50916153/in-r-data-table-max-works-on-an-ordered-factor-and-fails-when-grouped

**Comment by mbacou** [comment]
Excellent thanks! Was surprised to see that feature work well in e.g. PostgreSQL and not in data.table. Glad that was an easy fix.

**Comment by MichaelChirico** [comment]
if I would venture a guess it's only survived so long because ordered
factors are almost criminally underused as a data type (myself included) :)
