### ISSUE TITLE
[question]dcast with multiple `value.var` : order between `measure.vars` and `value.var`

### ISSUE THREAD

**Issue by thierrygosselin** [Rdatatable/data.table#1951]
[question]dcast with multiple `value.var` : order between `measure.vars` and `value.var`

Right now using dcast with multiple `value.var` creates a new data.table where columns are made:
`value.var`[sep]`measure.vars` which for me makes no sense to have the value.var first in the column header. 

**Question:**
Is there a way to change the order from : `value.var`[sep]`measure.vars` to  `measure.vars`[sep]`value.var` ?

Cheers
Thierry

**Comment by MichaelChirico** [comment]
Why doesn't it make sense to have `value.var` first? I personally prefer this way.

**Comment by thierrygosselin** [comment]
The logic behind my comment:
* my brain is wired to read left to right, but I understand it's not universal ;)
* there is a certain hierarchy: first the `group` then the `value`
* there is usually less group then value.

I'll give you an example in genomics:

* data frame with 4 columns: `INDIVIDUALS, LOCUS, REF_COUNT, ALT_COUNT`.
* each `INDIVIDUALS` as 30K `LOCUS`.
* each `LOCUS as 2 alleles (diploid animal) : the reference (REF) and the alternate (ALT).
* the columns `REF_COUNT` and `ALT_COUNT` are counts of REF and ALT alleles.
* for a particular analysis that doesn't like tidy data frame, I need INDIVIDUALS in rows and all the locus in columns. With the alleles counts as values.
* So we have 60K + 1 columns:`INDIVIDUALS` and then `LOCUS1.REF, LOCUS1.ALT, LOCUS2.REF, LOCUS2.ALT, ...` 

However, currently how dcast is implemented we get `ALT.LOCUS1, ALT.LOCUS2, ALT.LOCUS3...REF.LOCUS1, REF.LOCUS2, REF.LOCUS3`, etc. I don't like that. 

Is it possible possible to use a formula to decide how we want our `value.var` to bind ?

**currently:**
```
genomic.wide <- data.table::dcast.data.table(data = genomic.,
formula = POP_ID + INDIVIDUALS ~ MARKERS,
        value.var = c("REF_COUNT", "ALT_COUNT"),
        sep = "."
)
```

**wish:**
```
genomic.wide <- data.table::dcast.data.table(data = genomic.,
formula = POP_ID + INDIVIDUALS ~ MARKERS + c("REF_COUNT", "ALT_COUNT"),
        value.var = c("REF_COUNT", "ALT_COUNT"),
        sep = "."
)
```

?

If not, then I have to melt before casting in one step :(
Cheers
Thierry

**Comment by franknarf1** [comment]
It's not just group and value, but also function that goes into the resulting col names. I think eventually it would be nice to have some sort of customizable regex to determine how the names are constructed, mentioned before in #1821 , but I'd guess it's a tall order. And there's also the issue of what order the cols are shown in...

One idea, if you prefer this non-default formatting and routinely face the case where it applies, consider making a wrapper for dcast that has a step like `sub("(.*)[.](.*)", "\\2.\\1", "ALT.LOCUS1")` on the names.
