### ISSUE TITLE
Bug in `options(datatable.WhenJisSymbolThenCallingScope = T)`

### ISSUE THREAD

**Issue by my-R-help** [Rdatatable/data.table#1952]
When setting `options(datatable.WhenJisSymbolThenCallingScope = T)`, it fails to protect special symbols in `j`. For example: 

    options(datatable.WhenJisSymbolThenCallingScope = T)
    DT <- data.table(a = c(1, 1, 2))
    DT[, .N, by = a]

This gives a `Null data.table (0 rows and 0 cols)`, while it should in fact produce the group counts.

**Comment by mattdowle** [comment]
Ah yes. Thank you. Will fix.
