### ISSUE TITLE
suggest alternative in "avoid POSIXlt" warning

### ISSUE THREAD

**Issue by jan-glx** [Rdatatable/data.table#1957]
When intermediate `POSIXlt` values are created in `j`, `data.table` warns about a convertion to `POSIXct`:
````
dt <-fread("start.date start.time end.date end.time
2012-07-13   15:01:32 2012-07-13 15:02:42
2012-07-05   18:26:31 2012-07-05 18:27:19 
2012-07-14   20:23:21 2012-07-14 20:24:11")

dt[,as.numeric(difftime(strptime(paste(start.date, start.time), "%Y-%m-%d %H:%M:%S"),
                        strptime(paste(  end.date,   end.time), "%Y-%m-%d %H:%M:%S")))]
#[1] -70 -48 -50
#Warning messages:
#1: In strptime(paste(start.date, start.time), "%Y-%m-%d %H:%M:%S") :
#POSIXlt column type detected and converted to POSIXct. We do not recommend use of POSIXlt at all
#because it uses 40 bytes to store one date.
#2: In strptime(paste(end.date, end.time), "%Y-%m-%d %H:%M:%S") :
#POSIXlt column type detected and converted to POSIXct. We do not recommend use of POSIXlt at all
#because it uses 40 bytes to store one date.
````
It would be nice if a suitable alternative was suggested instead. 
Such as `as.POSIXct(., format=.)`:
```
dt[,as.numeric(difftime(as.POSIXct(paste(start.date, start.time), format="%Y-%m-%d %H:%M:%S"),
                        as.POSIXct(paste(  end.date,   end.time), format="%Y-%m-%d %H:%M:%S")))]
#[1] -70 -48 -50
```

In this particular case the warning might not be necessarily at all.

_I hope this was not already asked for in any of the many other date/time related issues._

**Comment by jan-glx** [comment]
Hm. Maybe I was just too much confused because my column was in fact numeric and not `POSIXlt` but I had my troubles finding `as.POSIXct(., format=.)` (admittedly mainly because it is not listed on `?strptime`, nor `?as.POSIXct`!) Anyway, `getAnywhere("as.POSIXct.default")` reveals `return(as.POSIXct(as.POSIXlt(x, tz, ...), tz, ...))` so I could just as well have used `strptime`. So the warning seems of no use in this case and would have been less of a hassle if it straightly suggested a way around.  How would I know that `as.POSIXct` has a format argument if it wasn't for google? Note that using `as.POSIXct(strptime(` produces the very same warning.

**Comment by MichaelChirico** [comment]
It's deep buried in the dense documentation of `?as.POSIXct`, but it's techincally covered by the paragraphs about `as.POSIX*`. I agree it seems like an oversight that the dox don't have any `as.POSIXct(x, format = .)` examples in there.

That said, there's nothing wrong with Googling things.

**Comment by CodeGiggler** [comment]
Warning message:
In data.table(strptime(Health$Visit.date, "%Y-%m-%d")) :
  POSIXlt column type detected and converted to POSIXct. We do not recommend use of POSIXlt at all because it uses 40 bytes to store one date.
> Health$Visit.date<-data.table(strptime(Health$Visit.date, '%Y-%m-%d'))
Warning message:
In data.table(strptime(Health$Visit.date, "%Y-%m-%d")) :
  POSIXlt column type detected and converted to POSIXct. We do not recommend use of POSIXlt at all because it uses 40 bytes to store one date.
>
