### ISSUE TITLE
fread: Error: isLOGICAL(showProgress) is not TRUE

### ISSUE THREAD

**Issue by masterofsleep** [Rdatatable/data.table#1964]
I just updated data.table to 1.10.0. When i tried to read data with fread, I got the following error

```
> fread("dat.csv")
Error: isLOGICAL(showProgress) is not TRUE
```

It can only be solved when I manually add the argument `showProgress = T`
Platform: Windows 7

**Comment by franknarf1** [comment]
Probably related to https://github.com/Rdatatable/data.table/commit/eb45306fb5702538b3f7af13f4d743cdc3ecd50f

**Comment by masterofsleep** [comment]
@franknarf1 , you are absolutely right. I am wondering if anybody else is having this problem.

**Comment by mattdowle** [comment]
What does `getOption("datatable.showProgress")` return for you?  Have you set that option in a `.Rprofile` anywhere?   Please try again with `R --vanilla` which disables the loading of any profile scripts, to double check.  When you look at `args(fread)` you can see that the `showProgress` argument comes from `getOption("datatable.showProgress")`.

Or, you did restart R after upgrading, didn't you?  In a fresh session?  If you merely upgrade in a single session without reloading the package in a new session, it won't refresh those options. So the option's value from the previous version will still be in memory.

**Comment by masterofsleep** [comment]
Hi @mattdowle , Thank you SO much for your detailed explanation. 
I no longer have this error now. I not get `TRUE` from `getOption("datatable.showProgress")` but last week when I had the error I got `1` instead of `TRUE`. I did restart R after upgrading but I did not restart my laptop. Maybe the solution is just to restart the OS.

**Comment by jangorecki** [comment]
@masterofsleep usually it is enough to install package in a clean R session, not having other sessions running at the same time as they may be using data.table dll. Glad you solve it, I will close the issue then.
