### ISSUE TITLE
Automatic column names when using shift in a data.table - give.names = TRUE

### ISSUE THREAD

**Issue by hannes101** [Rdatatable/data.table#1971]
As a follow up on my SO question [1] I would like to ask if it would be possible to achieve the "desired" result directly, namely to give the column created with shift() a more meaningful name than "V1".
In case shift() returns a list it's named according to the value of n and the type. In this particular type it would seem kind of logical to me.
Thanks anyway for data.table!

[1] https://stackoverflow.com/questions/41279773/no-automatic-column-names-with-shift-in-a-data-table-give-names-true

**Comment by jangorecki** [comment]
`give.names` works only for list output, we cannot name a vector, unless we wrap it into list. I submitted patch to clarify that in documentation.
