### ISSUE TITLE
.SD sometimes doesn't work?

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1977]
For this simple data.table:
`temp <- data.table(P=c(1,1,1,NA,NA,NA), S=c(1,2,NA,1,2,NA))`

I can get the whole table and a new column saying if the column S is a NA.

`temp[, .(P,S,is.na(S))]`

But if I want to get it without explicitly naming every column

`temp[, .(.SD,is.na(S))]`
it doesn't work,

> Error in setnames(jval, jvnames) : 
>   Can't assign 2 names to a 3 column data.table

Is it a bug?

the following does work.
`temp[, cbind(.SD,is.na(S))]`
but I don't know what's the suggested way to do it

**Comment by MichaelChirico** [comment]
Try

    temp[, c(.SD, list(is.na(S)))]

**Comment by jangorecki** [comment]
@skanskan solution provided by Michael is the proper way. You can always use `copy(temp)[, newcol := is.na(S)]` if you don't want to update your original dataset.
