### ISSUE TITLE
Documentation: more explicit that j can be logical (when with=FALSE)

### ISSUE THREAD

**Issue by Henrik-P** [Rdatatable/data.table#1978]
I stumbled over one of the highly informative error messages in `data.table`:

>   When with=FALSE, j-argument should be of type **logical**/character/integer indicating the columns to select.

However, the fact that `j` can be of type `logical` is not explicitly described in `?data.table`.

From `with`:

> When `with=FALSE` `j` is a character vector of column names, a numeric vector of column positions to select or of the form `startcol:endcol`

From `j`:

> When `with=FALSE`, `j` can only be a vector of column names or positions to select

**Comment by franknarf1** [comment]
Fyi, if you're writing new code and using version 1.9.8+, you might as well skip the `with=FALSE` bit:

    library(data.table)
    DT = data.table(a = 4, b = 5)
    DT[, 2]
    DT[, 2, with=FALSE] # same

**Comment by MichaelChirico** [comment]
Funnily, I don't see the fact that `j` can be `logical` in the documentation for `[.data.frame` either...
