### ISSUE TITLE
A data.table with a column named (lower case) 'x' prevents RStudio View() sort and filter from working

### ISSUE THREAD

**Issue by slin30** [Rdatatable/data.table#1980]
Not sure if this is an RStudio or data.table (or a combination thereof) issue, but I've reproduced it across two similar systems. Basically, when a `data.table` with a column named `x` (lower-case) is present, as the only or as one of any number of columns, trying to use sort and/or filter functionality in the RStudio viewer (via `View()`) unexpectedly:

* **When sorting:** filters the entire view to only the first record
* **When using the table-level search (filter) functionality via the upper right-hand box:** only highlights relevant results in `x`, without actually filtering the view
    * returns `No matching records found` if additional column(s) are present in a `data.table` with a column named `x`, when quick filtering on a (valid) value in the additional column(s)-- assuming the value one queries for is not also a value within column `x`
* **When using column-level filtering:** returns `No matching records found`, with the exception below:
    * seems to work if filtering on a factor level, if and only if one actually clicks on the drop-down list of
available values, although a subsequent sort action again returns only the first record in the current view

Note that for examples below, all works if column `x` is renamed to pretty much anything else, e.g. `X`. 

Also, `data.frame`s work as expected with a column named `x`. Whether created manually, or via `as.data.frame()` or `setDF()`. 

```{r}
library(data.table) # 1.10.0
# Run in RStudio 1.0.44

# Examples ----------------------------------------------------------------
# The simplest case
dt1 <- data.table(x = 1:5L) # does not seem to matter if integer, numeric, chr

# Make a factor column to demonstrate filter behavior (in View() gui)
set.seed(1)
dt2 <- data.table(g = factor(sample(LETTERS[1:2], 5, replace = TRUE)), 
                  x = 1:5L)


# Sort and filter behavior in View() gui ----------------------------------
View(dt1)
# looks like this in the gui (no issues with initial view):
#     x
# 1:  1
# 2:  2
# 3:  3
# 4:  4
# 5:  5
#
# But when you try to sort within the view, looks like this in the gui:
#     x
# 1:  1

# dt2 behaves similarly if you sort (on any column), although if you first filter on
# 'g', it seems to work (until you sort, that is)
View(dt2) # also no issues with initial view
#    g x
# 1: A 1
# 2: A 2
# 3: B 3
# 4: B 4
# 5: A 5
#
# When you try to filter on e.g. level "B" within the View() gui, without trying to sort, the
# behavior is as expected:
#    g x
# 1: B 3
# 2: B 4
# Note that you must actually click on the available levels within 'g' when trying to filter; 
# typing a value in a column (any column) gives "No matching records found"
#
# But if you first try to sort (on any column), or subsequently try to sort (after 
# filtering on 'g'),you again end up with only the first row of the current view. 
# That is, if you first filtered on level "B" and then sort:
#    g x
# 1: B 3
#
# ... but if you first sorted:
#    g x
# 1: A 1

# Quick search behavior in View() gui -------------------------------------
# Using the quick (table-level) search will highlight relevant result(s), without filtering the literal view:
View(dt1)
# ... then type '4' in the quick search, and you get something like this:
#     x
# 1:  1
# 2:  2
# 3:  3
# 4:  4 <- this is highlighted
# 5:  5

# However, with the second example, if you try to quick search (column-level) on a 
# value in e.g. column 'g', you end up with no results:
View(dt2)
# ... then type "B" in the quick search, and you see:
#    g x
# No matching records found
#
# Although you still get the highlight (only) behavior if you e.g. search on a value in 'x', via 
# table-level quick search:
#    g x
# 1: A 1
# 2: A 2
# 3: B 3
# 4: B 4 <- this is highlighted
# 5: A 5
```

sessionInfo()
```{r}
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.0

loaded via a namespace (and not attached):
[1] tools_3.3.2
```

**Comment by franknarf1** [comment]
Yup, I see the same on RStudio 1.0.44, R 3.2.5, data.table 1.10.1. To me, it seems to clearly be an RStudio issue. They wrote their own version of View, and the base one (utils::View) still behaves as expected.

Fyi, [support instructions](https://github.com/Rdatatable/data.table/wiki/Support) suggest running on the latest github version of the package.

**Comment by slin30** [comment]
@franknarf1 : Noted for next time re: testing with latest dev version. Thanks for the reminder and confirmation. Am happy to submit bug report to RStudio and close out here if this is confirmed to definitely be an RStudio issue.

**Comment by xhdong-umd** [comment]
I didn't see an issue report in RStudio support, so I [submitted one there](https://support.rstudio.com/hc/en-us/community/posts/115005671127-View-on-data-table-have-bug-on-sorting).

**Comment by kevinushey** [comment]
This does indeed appear to be an RStudio-specific issue -- thanks for letting us know, and feel free to close this issue on the `data.table` side if preferred.

**Comment by arunsrinivasan** [comment]
Thanks @kevinushey for following up. Will close. Thanks @xhdong-umd, @slin30 and @franknarf1 as well.
