### ISSUE TITLE
Anything changed in the way we assign values to a data.table?

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1981]
I'm using data.table 1.10.1

I'm trying to perform some simple substitutions.
`my <- data.table(A=c(1,2,NA), B=c(NA,NA,7),C=c(NA,NA,0))`
`my[is.na(.SD)]`
produces an error
> Empty data.table (0 rows) of 3 cols: A,B,C
> Warning message:
> In is.na(.SD) : is.na() applied to non-(list or vector) of type 'NULL'
> 

I need to write
`my[,is.na(.SD)]`
instead.
Anything changed in the way we read values or assign them to a data.table?
I think I could do it with the first method in previous versions.

And if I want to replace all NA with zeroes.
`my[,is.na(.SD)] <- 0`

> Error in `[<-.data.table`(`*tmp*`, , is.na(.SD), value = 0) : 
>   j must be vector of column name or positions
> In addition: Warning message:
> In is.na(.SD) : is.na() applied to non-(list or vector) of type 'NULL'

`my[is.na(.SD)] <- 0`
> Warning message:
> In is.na(.SD) : is.na() applied to non-(list or vector) of type 'NULL'
but it's supposed to work:
https://stackoverflow.com/questions/20535505/replacing-all-missing-values-in-r-data-table-with-a-value

`my[,is.na(.SD) := 0]`
> Error in `[.data.table`(my, , `:=`(is.na(my), NA)) : 
 > LHS of := isn't column names ('character') or positions ('integer' or 'numeric')

**Comment by franknarf1** [comment]
`.SD` is not available in `i`.

**Comment by skanskan** [comment]
Then how do you get the same result than 
`for (jj in 1:ncol(my)) set(my, i = which(is.na(my[[jj]])), j = jj, v = 0)`
or
`for (jj in 1:ncol(my)) set(my, i = which(my[[jj]]==0), j = jj, v = NA)`
with the "classic" brackets syntax?

**Comment by MichaelChirico** [comment]
Confirming this didn't work in 1.9.6, nor 1.9.4, as Frank said.

I believe the error you're getting is because `.SD` is defined by default within `data.table` as `NULL` to satisfy a CRAN check

**Comment by franknarf1** [comment]
@skanskan Sorry, I don't understand the question; I think you should use a for loop, actually. `DT[...]` works with one set of rows at a time, while your substitution needs a different set of rows depending on the column, so I don't think a single `DT[...]` call can do the trick.

**Comment by skanskan** [comment]
see the penultimate answer here:
https://stackoverflow.com/questions/7235657/fastest-way-to-replace-nas-in-a-large-data-table
Is it supposed to work?

**Comment by franknarf1** [comment]
@skanskan It *does* work. Notice that they're using `dt` instead of `.SD` there. The post author is wrong about it being efficient, though, I guess.

**Comment by skanskan** [comment]
Then this works:
`my[is.na(my)] <- 0`
or
`my <- my[,lapply(.SD,function(xx) ifelse(is.na(xx), 0, xx) )]`

but this doesn't
`my[,lapply(.SD,function(xx) ifelse(is.na(xx), xx:= 0, xx) )]`

**Comment by franknarf1** [comment]
I'm not sure if you're still asking a question or not. If so, it might make sense to close this issue and ask on SO or [the chat room there](http://chat.stackoverflow.com/rooms/25312/r-public), since this issue tracker sends emails to a bunch of folks each time someone posts.

**Comment by skanskan** [comment]
Then this works:
`my[is.na(my)] <- 0`
or
`my <- my[,lapply(.SD,function(xx) ifelse(is.na(xx), 0, xx) )]`

but how do you get it done by reference with ":="?

OK, close the thread.

**Comment by MichaelChirico** [comment]
@skanskan what's wrong with [Matt's own answer](http://stackoverflow.com/a/7249454/3576984) on that question? AFAIC that's canon on replacing `NA` in `data.table`.

**Comment by skanskan** [comment]
Nothing is wrong.  Anyway three solutions use other libraries or a loop with set().

The only solution using  **:=** is really complex:

f_dowle = function(dt) {     
  na.replace = function(v,value=0) { v[is.na(v)] = value; v }
  for (i in names(dt))
    eval(parse(text=paste("dt[,",i,":=na.replace(",i,")]")))
}

**Comment by MichaelChirico** [comment]
@skanskan  no reason to be married to using `:=` -- at core, both `set` and `:=` call the C function [`assign`](https://github.com/Rdatatable/data.table/blob/master/src/assign.c#L278). `set` is faster because `:=` requires the overhead of calling `[.data.table`.

If you're really obsessed with using `:=`:

    DT[ , (names(DT)) := lapply(.SD, function(x) {x[is.na(x)] <- v; x})]

Where `v` is your replacement of choice.

**Comment by skanskan** [comment]
OK, thanks.
The reason sometimes I'm looking for := solutions is because some of my scripts need to be read by other people that aren't R experts nor programmer and it's better if I don't use new syntax (such as set()). They already make an effort using R and sometimes data.table.

**Comment by MichaelChirico** [comment]
@skanskan understood. Personally, in cases like that, I leave a comment by the obscure code snippet referring to documentation. In this case, I might leave a clarifying comment referring to the SO post:

    #see this SO post:
    #  http://stackoverflow.com/questions/7235657/fastest-way-to-replace-nas-in-a-large-data-table/7249454

**Comment by arunsrinivasan** [comment]
Please close issues if you've got an answer. This Q is much more suitable for SO as well.
