### ISSUE TITLE
Exporting dataframe

### ISSUE THREAD

**Issue by msgoussi** [Rdatatable/data.table#1984]
Is there a way of using fwrite to export a big dataframe (4GB) to a zip file. 

thank

**Comment by MichaelChirico** [comment]
fwrite(DF) should work without conversion.

If not, fwrite(setDT(DF)) will.

**Comment by MichaelChirico** [comment]
please read ?fwrite:

https://jangorecki.gitlab.io/data.table/library/data.table/html/fwrite.html

**Comment by msgoussi** [comment]
Dear Michael,
As you may know if I use rio::export(DF,"DF.csv.zip"), I will get compressed DF.csv in zip format, so the file size will very small.
I am wondering if data.table::fwrite can do the same.
Thanks

**Comment by MichaelChirico** [comment]
If file size is a concern, you may consider `feather` or simply using another utility to zip the output, e.g., `?zip`

**Comment by msgoussi** [comment]
I used rio:: export to save a dataframe in csv file compressed as zip file. Thanks

**Comment by mattdowle** [comment]
rio looks very nice. It doesn't make sense for data.table to reimplement that nice interface.  rio already uses `fread`, so now that `fwrite` is on CRAN, perhaps rio can switch from `write.csv` to `fwrite`.

And indeed it already does in development! Thanks to @leeper.

https://github.com/leeper/rio/issues/90
https://github.com/leeper/rio/issues/136

**Comment by leeper** [comment]
Indeed. rio uses `fwrite()` in the dev version. Just waiting for a few final updates before a CRAN release.
