### ISSUE TITLE
data.table class changed ?

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1990]
Hello.

Say I have a data.table
`DT <- data.table(A=c(NA,NA,NA,NA), B=c(NA,NA,NA,7),C=c(NA,NA,4,8),D=c(NA,2,5,9), E=c(1,3,6,0))`

If I execute this
DT2 <- DT[,is.na(.SD)]

I would expect to get a data.table with TRUEs and FALSEs
but I have a matrix instead.
And if my original data.table is big I get a "Large matrix".

Is it a bug or is the expected behavior?
How can I get a data.table? (I mean without converting it later?

I'm working with data.table 1.10.1 and R 3.3.2

**Comment by franknarf1** [comment]
I think it's expected. Try

    class(is.na(as.data.frame(DT))) # matrix

and maybe check out the Value section of `?is.na`.

**Comment by skanskan** [comment]
I expected to get a data.table because I was executing everything inside the brackets, though I guess I need to do

DT2 <- DT[,lapply(.SD,is.na)]

**Comment by MichaelChirico** [comment]
Yes, that's correct.

`[]` will only give you a `data.table` if the result inside `j` is a `list`.

But as Frank points out, `is.na` returns a `matrix`.

If you really like how `is.na(.SD)` looks, you could do `DT[ , as.data.table(is.na(.SD))]`. My instincts tell me the `lapply` approach is faster, anyway.

**Comment by arunsrinivasan** [comment]
It is better to ask such Q on SO first.
