### ISSUE TITLE
[Request] Add note to ?setorder that character ordering sorts case, then alphabetically

### ISSUE THREAD

**Issue by HughParsonage** [Rdatatable/data.table#1996]
I noticed that `setorder` is case-sensitive in a different way to `base::order`

```r
DT <- data.table(x = c("a", "A", "B", "b"), y = 1:4)
DF <- as.data.frame(DT)

# ordered by case, then alphabetically and capital letters occur before lower-case letters
DT[order(x)]
#    x y
# 1: A 2
# 2: B 3
# 3: a 1
# 4: b 4

# in alphabetical order first, then case-sensitively (and lower-case first)
DF[order(DF$x), ]
#   x y
# 3 a 1
# 1 A 2
# 4 b 4
# 2 B 3
```

If this is intended behaviour, I believe it should be added to the documentation for `?setorder`.

**Comment by MichaelChirico** [comment]
I believe this is documented, though perhaps it could be done so more elegantly/obviously:

> `data.table` always reorders in C-locale. To sort by session locale, use `x[base::order(.)]` instead.

**Comment by HughParsonage** [comment]
FWIW, I saw that in the documentation (before raising this issue) but didn't realize it had that effect.
