### ISSUE TITLE
Syntax of "value" in  set(x, i = , j, value), further documentation.

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1997]
Hello

There is some information about how to use the _set_ command.
In all the examples I've seen the value is a single value.
For example
`for (jj in 1:10) set(my, i = which(my[[jj]]=="10/14/1982"), j = jj, v = NA) `

How can I use something more complex instead of that NA?
For example, I want the value depends on the value of another column.
```
DT <- data.table(A=c(1,2,3,NA,1, NA), B=c(NA, 2,3,NA, NA,1))    
set(DT, i = which(is.na(DT[[1]])), j = 1L, v = is.na(DT[[2]])) 
```
that gives an error.

If I try 
`set(exa, i = which(is.na(exa[[1]])), j = 1L, v = as.numeric(is.na(exa[[2]]))) `
it says:
> Supplied 6 items to be assigned to 2 items of column 'A' (4 unused)

I know I can do it with two lines
```
set(DT, i = which(is.na(DT[[1]]) & is.na(DT[[2]])), j = 1L, v = 1) 
set(DT, i = which(is.na(DT[[1]]) & !is.na(DT[[2]])), j = 1L, v = 0) 
```
But this implies using more code, and many times is not possible to do it like that.

**Comment by MichaelChirico** [comment]
Per the documentation:

> `value` : A list of replacement values to assign by reference to `x[i, j]`.

So `value` should be the same length as `i`, or recycling rules will apply.

Your case is really better suited for using `:=` assignment:

```
DT[is.na(A), A := B][]
#     A  B
# 1:  1 NA
# 2:  2  2
# 3:  3  3
# 4: NA NA
# 5:  1 NA
# 6:  1  1
```

**Comment by arunsrinivasan** [comment]
Please close issues if you've got your issue answered (which seems to be the case here). Searching on SO would provide more complex use cases. Please make sure you've exhausted other possibilities before filing issues.
