### ISSUE TITLE
fread: Error: isLOGICAL(showProgress) is not TRUE

### ISSUE THREAD

**Issue by TomKellyGenetics** [Rdatatable/data.table#1998]
An `fread` command in scripts that used to work now returns:

`Error: isLOGICAL(showProgress) is not TRUE`

Similar issue to https://github.com/Rdatatable/data.table/issues/1964 so I suspect the 1.10.0 update is also behind this but also occurring on a red hat linux server.

`getOption("datatable.showProgress")` returns `1` not `TRUE` or `FALSE`

Updating on CRAN or the dev version 1.10.1 on github (with devtools) does not fix the error. As a workaround `options(datatable.showProgress=T)` restores `fread` functionality.

**Comment by MichaelChirico** [comment]
@TomKellyGenetics are you still experiencing this error with the latest CRAN/dev versions?

**Comment by TomKellyGenetics** [comment]
@MichaelChirico Thanks for following up on this. The workaround is still in the scripts that I'm using for the workflow in this project. I don't think it's necessary anymore though. I'm not getting this error without changing the `options` now.

I'm running data.table 1.10.4 in R 3.3.1.
