### ISSUE TITLE
Quoting column names consistency

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1999]
Hello.

When we select column names by name we don't use quotes 
`DT[,myname]`
but if we do it with SDcols we need to quote them:
`DT[,.SD, .SDcols="myname"]`
otherwise we get an error.
Is that the intended way to achieve it?

**Comment by MichaelChirico** [comment]
See #1474

**Comment by arunsrinivasan** [comment]
There's no reason why we can't do `.SDcols = .(col1, col2)`.. this was done for `by` because it allows expressions to be evaluated there, and therefore has a higher purpose, e.g., `by=.(col1, col2=col3-5)`. 

But still, it can be used to just provide column names, I guess, for interactive scenarios.

**Comment by jangorecki** [comment]
As noted by Arun in `by` argument it has actually some value added. Using it in `.SDcols` would not add much, other than reducing number of `"` signs required: `c("a","b")` vs `.(a, b)`. In my opinion this reasoning is not good enough to introduce extra complexity related to NSE processing. I elaborated more on that in https://github.com/Rdatatable/data.table/pull/4304#issuecomment-611109219. Voting for close.

**Comment by MichaelChirico** [comment]
I agree; going ahead to close.

The use case I had in mind for allowing this initially would have been on-the-fly columns like:

```
DT[ , .SDcols = .(v = v+1), j = .(s = foo(v))]
```

But this is trivially easy to implement without needing NSE in `.SDcols`:

```
DT[ , {
  v = v + 1
  .(s = foo(v))
}]
```

And as noted, there is overhead to allowing NSE in more places -- thus the cost outweighs the benefit.
