### ISSUE TITLE
Shiny Reactivity Fails with data.table

### ISSUE THREAD

**Issue by sergeganakou** [Rdatatable/data.table#2001]
In my shiny code when I use reactive function with a data.table it's doesn't work but it's work with a data.frame . Please somebody can help me to solve this problem.

**Comment by sergeganakou** [comment]
`tableau = reactive({
    
    if (is.null(input$fichier)) 
      return(NULL)
   
    fread(input$fichier$datapath, stringsAsFactors=TRUE, quote=input$quote)
    
  })
  
  
  
  
  
  

  
  type = function(data){ 
    tab = c()
    for ( i in 1:length(data)){
      tab1 = class(data[,get(names(data)[i])])
      tab = c(tab,tab1)
    }
    return(tab)
  }
  
  
  output$var_namequant = renderUI({
    
    quant = names(tableau())[which( type(tableau()) == "numeric" |  type(tableau()) == "integer")]
    if (is.null(input$fichier) | length(quant) == 0) {}
    else {
      selectInput("var_namequant1", label = "Choisir la(les) variable(s) a transformer en qualitative(s):", choices = names(tableau())[which( type(tableau()) == "numeric" |  type(tableau()) == "integer")], multiple = TRUE)
    }
    
  })
  
  output$var_namequal = renderUI({
    
    qual = names(tableau())[which( type(tableau()) == "character" |  type(tableau()) == "factor")]
    if (is.null(input$fichier) | length(qual) == 0) {}
    else {
      selectInput("var_namequal1", label = "Choisir la(les) variable(s) a transformer en quantitative(s):", choices = names(tableau())[which( type(tableau()) == "character" |  type(tableau()) == "factor")], multiple = TRUE)
    }
    
  })
  
  
  
  tableau1 = reactive({ 
    if (is.null(input$fichier)) {return(NULL)}
    else{
      if ( length(input$var_namequant1) == 0 & length(input$var_namequal1) == 0 & is.null(input$fichier) == "FALSE" ){
        donnee = tableau()
        return(donnee)
      }else{
        if ( length(input$var_namequant1) > 0 & length(input$var_namequal1) == 0 ){
          donnee = tableau()
          translate_to_factors = input$var_namequant1
          for (i in 1:length(translate_to_factors)){
            e = substitute(X := as.factor(as.character(X)), list(X = as.symbol(translate_to_factors[i])))
            donnee[ , eval(e)]
          }
          return(donnee)
        }else{
          if ( length(input$var_namequal1) > 0 & length(input$var_namequant1) ==0 ){
            donnee = tableau()
            translate_to_values = input$var_namequal1
            for (i in 1:length(translate_to_values)){
              e = substitute(X := as.numeric(as.character(X)), list(X = as.symbol(translate_to_values[i])))
              donnee[ , eval(e)]
            }
            return(donnee)
          }else{
            if ( length(input$var_namequant1) > 0 & length(input$var_namequal1) > 0 ){
              donnee = tableau()
              
              translate_to_factors = input$var_namequant1
              for (i in 1:length(translate_to_factors)){
                e = substitute(X := as.factor(as.character(X)), list(X = as.symbol(translate_to_factors[i])))
                donnee[ , eval(e)]
              }
              
              translate_to_values = input$var_namequal1
              for (i in 1:length(translate_to_values)){
                e = substitute(X := as.numeric(as.character(X)), list(X = as.symbol(translate_to_values[i])))
                donnee[ , eval(e)]
              }
              return(donnee)
            }else{}
          }
        }
        
      }
    }
  })`

**Comment by sergeganakou** [comment]
`tableau = reactive({
    
    if (is.null(input$fichier)) 
      return(NULL)
   
    fread(input$fichier$datapath, stringsAsFactors=TRUE, quote=input$quote)
    #
    
  })
  
  
  
  
  
  
  
  #Variables quantitatives et Variables qualitatives
  
  
  type = function(data){ #fonction qui retourne le type des variables d'un dataframe
    tab = c()
    for ( i in 1:length(data)){
      tab1 = class(data[,get(names(data)[i])])
      tab = c(tab,tab1)
    }
    return(tab)
  }
  
  
  output$var_namequant = renderUI({
    
    quant = names(tableau())[which( type(tableau()) == "numeric" |  type(tableau()) == "integer")]
    if (is.null(input$fichier) | length(quant) == 0) {}
    else {
      selectInput("var_namequant1", label = "Choisir la(les) variable(s) a transformer en qualitative(s):", choices = names(tableau())[which( type(tableau()) == "numeric" |  type(tableau()) == "integer")], multiple = TRUE)
    }
    
  })
  
  output$var_namequal = renderUI({
    
    qual = names(tableau())[which( type(tableau()) == "character" |  type(tableau()) == "factor")]
    if (is.null(input$fichier) | length(qual) == 0) {}
    else {
      selectInput("var_namequal1", label = "Choisir la(les) variable(s) a transformer en quantitative(s):", choices = names(tableau())[which( type(tableau()) == "character" |  type(tableau()) == "factor")], multiple = TRUE)
    }
    
  })
  
  
  output$var_typequant = renderText({
    if (is.null(input$fichier) | length(input$var_namequant1) == 0) {}
    else{
      if (length(input$var_namequant1) == 1){print("La variable selectionnee ci dessus a ete transformee en qualitative")}
      else{print(paste("Les",length(input$var_namequant1),"variables selectionnees ci dessus ont ete transformees en qualitative"))}
    }
  })
  
  output$var_typequal = renderText({
    if (is.null(input$fichier) | length(input$var_namequal1) == 0) {}
    else{
      if (length(input$var_namequal1) == 1){print("La variable selectionnee ci dessus a ete transformee en quantitative")}
      else{print(paste("Les",length(input$var_namequal1),"variables selectionnees ci dessus ont ete transformees en quantitative"))}
    }
  })
  
  
  
  tableau1 = reactive({ #ici on cree tableau1 pour pouvoir transformer les variables en variables qualitatives ou quantitatives (base de donnee initial modifiee)
    if (is.null(input$fichier)) {return(NULL)}
    else{
      if ( length(input$var_namequant1) == 0 & length(input$var_namequal1) == 0 & is.null(input$fichier) == "FALSE" ){
        donnee = tableau()
        return(donnee)
      }else{
        if ( length(input$var_namequant1) > 0 & length(input$var_namequal1) == 0 ){
          donnee = tableau()
          translate_to_factors = input$var_namequant1
          for (i in 1:length(translate_to_factors)){
            e = substitute(X := as.factor(as.character(X)), list(X = as.symbol(translate_to_factors[i])))
            donnee[ , eval(e)]
          }
          return(donnee)
        }else{
          if ( length(input$var_namequal1) > 0 & length(input$var_namequant1) ==0 ){
            donnee = tableau()
            translate_to_values = input$var_namequal1
            for (i in 1:length(translate_to_values)){
              e = substitute(X := as.numeric(as.character(X)), list(X = as.symbol(translate_to_values[i])))
              donnee[ , eval(e)]
            }
            return(donnee)
          }else{
            if ( length(input$var_namequant1) > 0 & length(input$var_namequal1) > 0 ){
              donnee = tableau()
              
              translate_to_factors = input$var_namequant1
              for (i in 1:length(translate_to_factors)){
                e = substitute(X := as.factor(as.character(X)), list(X = as.symbol(translate_to_factors[i])))
                donnee[ , eval(e)]
              }
              
              translate_to_values = input$var_namequal1
              for (i in 1:length(translate_to_values)){
                e = substitute(X := as.numeric(as.character(X)), list(X = as.symbol(translate_to_values[i])))
                donnee[ , eval(e)]
              }
              return(donnee)
            }else{}
          }
        }
        
      }
    }
  })`

**Comment by sergeganakou** [comment]
`tableau = reactive({
    
    if (is.null(input$fichier)) 
      return(NULL)
   
    fread(input$fichier$datapath, stringsAsFactors=TRUE, quote=input$quote)
    #
    
  })
  
  
  
  
  
  
  
  #Variables quantitatives et Variables qualitatives
  
  
  type = function(data){ #fonction qui retourne le type des variables d'un dataframe
    tab = c()
    for ( i in 1:length(data)){
      tab1 = class(data[,get(names(data)[i])])
      tab = c(tab,tab1)
    }
    return(tab)
  }
  
  
  output$var_namequant = renderUI({
    
    quant = names(tableau())[which( type(tableau()) == "numeric" |  type(tableau()) == "integer")]
    if (is.null(input$fichier) | length(quant) == 0) {}
    else {
      selectInput("var_namequant1", label = "Choisir la(les) variable(s) a transformer en qualitative(s):", choices = names(tableau())[which( type(tableau()) == "numeric" |  type(tableau()) == "integer")], multiple = TRUE)
    }
    
  })
  
  output$var_namequal = renderUI({
    
    qual = names(tableau())[which( type(tableau()) == "character" |  type(tableau()) == "factor")]
    if (is.null(input$fichier) | length(qual) == 0) {}
    else {
      selectInput("var_namequal1", label = "Choisir la(les) variable(s) a transformer en quantitative(s):", choices = names(tableau())[which( type(tableau()) == "character" |  type(tableau()) == "factor")], multiple = TRUE)
    }
    
  })
  
  
  output$var_typequant = renderText({
    if (is.null(input$fichier) | length(input$var_namequant1) == 0) {}
    else{
      if (length(input$var_namequant1) == 1){print("La variable selectionnee ci dessus a ete transformee en qualitative")}
      else{print(paste("Les",length(input$var_namequant1),"variables selectionnees ci dessus ont ete transformees en qualitative"))}
    }
  })
  
  output$var_typequal = renderText({
    if (is.null(input$fichier) | length(input$var_namequal1) == 0) {}
    else{
      if (length(input$var_namequal1) == 1){print("La variable selectionnee ci dessus a ete transformee en quantitative")}
      else{print(paste("Les",length(input$var_namequal1),"variables selectionnees ci dessus ont ete transformees en quantitative"))}
    }
  })
  
  
  
  tableau1 = reactive({ #ici on cree tableau1 pour pouvoir transformer les variables en variables qualitatives ou quantitatives (base de donnee initial modifiee)
    if (is.null(input$fichier)) {return(NULL)}
    else{
      if ( length(input$var_namequant1) == 0 & length(input$var_namequal1) == 0 & is.null(input$fichier) == "FALSE" ){
        donnee = tableau()
        return(donnee)
      }else{
        if ( length(input$var_namequant1) > 0 & length(input$var_namequal1) == 0 ){
          donnee = tableau()
          translate_to_factors = input$var_namequant1
          for (i in 1:length(translate_to_factors)){
            e = substitute(X := as.factor(as.character(X)), list(X = as.symbol(translate_to_factors[i])))
            donnee[ , eval(e)]
          }
          return(donnee)
        }else{
          if ( length(input$var_namequal1) > 0 & length(input$var_namequant1) ==0 ){
            donnee = tableau()
            translate_to_values = input$var_namequal1
            for (i in 1:length(translate_to_values)){
              e = substitute(X := as.numeric(as.character(X)), list(X = as.symbol(translate_to_values[i])))
              donnee[ , eval(e)]
            }
            return(donnee)
          }else{
            if ( length(input$var_namequant1) > 0 & length(input$var_namequal1) > 0 ){
              donnee = tableau()
              
              translate_to_factors = input$var_namequant1
              for (i in 1:length(translate_to_factors)){
                e = substitute(X := as.factor(as.character(X)), list(X = as.symbol(translate_to_factors[i])))
                donnee[ , eval(e)]
              }
              
              translate_to_values = input$var_namequal1
              for (i in 1:length(translate_to_values)){
                e = substitute(X := as.numeric(as.character(X)), list(X = as.symbol(translate_to_values[i])))
                donnee[ , eval(e)]
              }
              return(donnee)
            }else{}
          }
        }
        
      }
    }
  })`

**Comment by sergeganakou** [comment]
`  test`

**Comment by sergeganakou** [comment]
` tableau = reactive({
    
    if (is.null(input$fichier)) 
      return(NULL)
   
    fread(input$fichier$datapath, stringsAsFactors=TRUE, quote=input$quote)
    #
    
  })
  
  
  
  
  
  
  
  #Variables quantitatives et Variables qualitatives
  
  
  type = function(data){ #fonction qui retourne le type des variables d'un dataframe
    tab = c()
    for ( i in 1:length(data)){
      tab1 = class(data[,get(names(data)[i])])
      tab = c(tab,tab1)
    }
    return(tab)
  }
  
  
  output$var_namequant = renderUI({
    
    quant = names(tableau())[which( type(tableau()) == "numeric" |  type(tableau()) == "integer")]
    if (is.null(input$fichier) | length(quant) == 0) {}
    else {
      selectInput("var_namequant1", label = "Choisir la(les) variable(s) a transformer en qualitative(s):", choices = names(tableau())[which( type(tableau()) == "numeric" |  type(tableau()) == "integer")], multiple = TRUE)
    }
    
  })
  
  output$var_namequal = renderUI({
    
    qual = names(tableau())[which( type(tableau()) == "character" |  type(tableau()) == "factor")]
    if (is.null(input$fichier) | length(qual) == 0) {}
    else {
      selectInput("var_namequal1", label = "Choisir la(les) variable(s) a transformer en quantitative(s):", choices = names(tableau())[which( type(tableau()) == "character" |  type(tableau()) == "factor")], multiple = TRUE)
    }
    
  })
  
  
  output$var_typequant = renderText({
    if (is.null(input$fichier) | length(input$var_namequant1) == 0) {}
    else{
      if (length(input$var_namequant1) == 1){print("La variable selectionnee ci dessus a ete transformee en qualitative")}
      else{print(paste("Les",length(input$var_namequant1),"variables selectionnees ci dessus ont ete transformees en qualitative"))}
    }
  })
  
  output$var_typequal = renderText({
    if (is.null(input$fichier) | length(input$var_namequal1) == 0) {}
    else{
      if (length(input$var_namequal1) == 1){print("La variable selectionnee ci dessus a ete transformee en quantitative")}
      else{print(paste("Les",length(input$var_namequal1),"variables selectionnees ci dessus ont ete transformees en quantitative"))}
    }
  })
  
  
  
  tableau1 = reactive({ #ici on cree tableau1 pour pouvoir transformer les variables en variables qualitatives ou quantitatives (base de donnee initial modifiee)
    if (is.null(input$fichier)) {return(NULL)}
    else{
      if ( length(input$var_namequant1) == 0 & length(input$var_namequal1) == 0 & is.null(input$fichier) == "FALSE" ){
        donnee = tableau()
        return(donnee)
      }else{
        if ( length(input$var_namequant1) > 0 & length(input$var_namequal1) == 0 ){
          donnee = tableau()
          translate_to_factors = input$var_namequant1
          for (i in 1:length(translate_to_factors)){
            e = substitute(X := as.factor(as.character(X)), list(X = as.symbol(translate_to_factors[i])))
            donnee[ , eval(e)]
          }
          return(donnee)
        }else{
          if ( length(input$var_namequal1) > 0 & length(input$var_namequant1) ==0 ){
            donnee = tableau()
            translate_to_values = input$var_namequal1
            for (i in 1:length(translate_to_values)){
              e = substitute(X := as.numeric(as.character(X)), list(X = as.symbol(translate_to_values[i])))
              donnee[ , eval(e)]
            }
            return(donnee)
          }else{
            if ( length(input$var_namequant1) > 0 & length(input$var_namequal1) > 0 ){
              donnee = tableau()
              
              translate_to_factors = input$var_namequant1
              for (i in 1:length(translate_to_factors)){
                e = substitute(X := as.factor(as.character(X)), list(X = as.symbol(translate_to_factors[i])))
                donnee[ , eval(e)]
              }
              
              translate_to_values = input$var_namequal1
              for (i in 1:length(translate_to_values)){
                e = substitute(X := as.numeric(as.character(X)), list(X = as.symbol(translate_to_values[i])))
                donnee[ , eval(e)]
              }
              return(donnee)
            }else{}
          }
        }
        
      }
    }
  }) `

**Comment by sergeganakou** [comment]
`tableau = reactive({
    
    if (is.null(input$fichier)) 
      return(NULL)
   
    fread(input$fichier$datapath, stringsAsFactors=TRUE, quote=input$quote)
 
  })
  `

**Comment by raubreywhite** [comment]
I have the same problem.

These examples all use this framework: http://rmarkdown.rstudio.com/flexdashboard/

So you need to rename "failingFlexdashboard.txt" to "failingFlexdashboard.Rmd" and then you can run it (the same with "workingFlexdashboard.txt" -> "workingFlexdashboard.Rmd").

I've also attached the log from my shiny server that gives the error. Basically, Shiny seems to be trying to treat it as a data.frame, not a data.table, so it can't find the variable to stratify on.

[failingFlexdashboard.txt](https://github.com/Rdatatable/data.table/files/983407/failingFlexdashboard.txt)
[workingFlexdashboard.txt](https://github.com/Rdatatable/data.table/files/983406/workingFlexdashboard.txt)
[test_error-docker-20170508-120846-37265 (linux's conflicted copy 2017-05-08) (linux's conflicted copy 2017-05-08) copy.txt](https://github.com/Rdatatable/data.table/files/983412/test_error-docker-20170508-120846-37265.linux.s.conflicted.copy.2017-05-08.linux.s.conflicted.copy.2017-05-08.copy.txt)

**Comment by raubreywhite** [comment]
Another reproducible example listed here:

https://github.com/rstudio/shiny/issues/1696
