### ISSUE TITLE
%in% operator with list column

### ISSUE THREAD

**Issue by magerton** [Rdatatable/data.table#2004]
I have been hoping to use the %in% operator to see whether the elements in one column are members of the element vectors in a list column, but the behavior of this operator doesn't seem to be consistent. I can't tell what the %in% operator is comparing.

```R
dt = data.table(a=c(1, 2, 3, 4), b=list(1:3, 1, 1:3, 4))
dt[, c:= a %in% b]
dt[, d:= a %in% b[[1]] ]
dt
```
Returns
```
   a     b     c     d
1: 1 1,2,3  TRUE  TRUE
2: 2     1 FALSE  TRUE
3: 3 1,2,3 FALSE  TRUE
4: 4     4  TRUE FALSE
```
Using data.table v 1.10.0 and R version 3.3.1 (2016-06-21)

**Comment by skanskan** [comment]
b[[1]] is an integer vector 1,2,3, then it seems right.
1 contains 1
2 contains 2
3 contains 3
4 doesn't contain 1,2 nor 3
then d is right.

c is also right, it doesn't compare the same things.

**Comment by magerton** [comment]
Thanks for the response, @skanskan . I think I am confused because I was expecting a row-wise comparison in d, but perhaps that's not how data.table behaves. And I suppose that column c is looking at whether the each element of a is also an element of b, so c(2) is not in list(c(1,2,3), c(1), c(4)).

**Comment by skanskan** [comment]
I'm not an expert anyway.

**Comment by jangorecki** [comment]
@magerton @skanskan is right here, you probably want something like
```r
dt[, d:= mapply(function(x, y) x %in% y, a, b) ]
```
feel free to re-open if it is not what you expect.

**Comment by magerton** [comment]
Thanks @jangorecki. Yes, that looks like just what I was expecting.
