### ISSUE TITLE
 !require("data.table",quietly=FALSE,warn.conflicts=FALSE) print many messages

### ISSUE THREAD

**Issue by tarrade** [Rdatatable/data.table#2005]
Hi everybody,

I have just a naive question. Why do I see a bunch of messages when the package is already installed with the require() function ?

```
> !require("data.table",quietly=TRUE,warn.conflicts=FALSE)
data.table 1.10.0
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com
[1] FALSE
Warning message:
Paket ‘data.table’ wurde unter R Version 3.2.5 erstellt 
```

`> library(data.table)`

 Why do I see all these info while I am using  

> quietly=TRUE

I am using  "R version 3.2.3 (2015-12-10)" and data.table 1.10.0

Thanks
Cheers
Fabien

**Comment by franknarf1** [comment]
I think those messages come from [onload.R](https://github.com/Rdatatable/data.table/blob/master/R/onLoad.R) and can be suppressed using [this answer from SO](http://stackoverflow.com/a/8681811/).

**Comment by tarrade** [comment]
Hi @franknarf1,

ah, I was using it for install.packages and didn't know it will work with require.
Perfect, it does what I want.

Thanks
Cheers
Fabien
