### ISSUE TITLE
Set column by reference with date type

### ISSUE THREAD

**Issue by moman822** [Rdatatable/data.table#2010]
It seems that the issue outlined in [this SO post](http://stackoverflow.com/questions/15996692/cannot-assign-columns-as-date-by-reference-in-data-table), and resolved later via Github, persists when using an `ifelse` statement on the RHS of the assignment operator.

An example:

```
dt <- data.table(DateColumn = as.Date("2010-10-10"))

dt[, SecondDate := DateColumn+1]

dt[, ThirdDate := ifelse(is.na(SecondDate), SecondDate, DateColumn)]
```
Setting `SecondDate` works, but setting `ThirdDate` converts to numeric.

**Comment by MichaelChirico** [comment]
This is a `base` problem -- `ifelse` strips attributes:

```
DateColumn = as.Date("2010-10-10")
SecondDate = DateColumn+1
ifelse(is.na(SecondDate), SecondDate, DateColumn)
# [1] 14892
```

However, newly introduced `fifelse` doesn't do so -- try it out!

```
DateColumn = as.Date("2010-10-10")
SecondDate = DateColumn+1
fifelse(is.na(SecondDate), SecondDate, DateColumn)
# [1] "2010-10-10"
```
