### ISSUE TITLE
Doing setkey(DT,key) then unique(DT) no longer removes duplicates

### ISSUE THREAD

**Issue by abhivr** [Rdatatable/data.table#2014]
Doing setkey(DT,key) then unique(DT) no longer removes duplicates by key. 

I am using working unique(DT, by="key") as work around.

**Comment by franknarf1** [comment]
You might want to have a look at the "potentially breaking changes" part of the changelog when upgrading. This one is [from 1.9.8](https://github.com/Rdatatable/data.table/blob/master/NEWS.md#potentially-breaking-changes).

**Comment by MichaelChirico** [comment]
the default value of by has changed since 1.9.8. see NEWS.md
