### ISSUE TITLE
question about reading a large character array

### ISSUE THREAD

**Issue by wangj26** [Rdatatable/data.table#2015]
Hi,

When using the fread to read my large file (around 100 million rows and 2 columns, all character), I found at the first time, it took around 270 seconds. But if I read this file again or read another large file (the same size), it only took around 30 seconds. The following is the screen shot for my two run.
<img width="877" alt="screen shot 2017-02-02 at 10 34 27 pm" src="https://cloud.githubusercontent.com/assets/25493765/22596574/bedda748-e9f1-11e6-98bd-1256f3c82412.png">

How can I make the first time read as fast as the second time?

Thanks,

**Comment by MichaelChirico** [comment]
this is documented & expected behavior, see `?fread`

**Comment by MichaelChirico** [comment]
This is documented in the manual

**Comment by wangj26** [comment]
Is it possible to make the first run faster? There is nine times slower for the first time run.

**Comment by MichaelChirico** [comment]
I would rather think of it as being 9 times faster on the second run.

**Comment by wangj26** [comment]
My code is running in the web server. When the users run this code each time, the server will open a fresh R. Thus, every time the users need to wait 270 seconds to get the data. 

Is it any way that I can initialize the cache of R? If I can set a very big cache (e.g. 8GB) for R and then it should be very fast to read the file.

**Comment by MichaelChirico** [comment]
I think this sort of Q is better suited for SO, I believe

**Comment by mattdowle** [comment]
If you run the `fread` with `verbose=TRUE` you'll see it reporting that the column types are character.  (I heard from you in direct email which is how I know.)

Each and every unique string in your file will add that string to R's global character cache.  That cache will grow to accommodate all the unique strings.  Adding a new character strings is more expensive than finding that that particular string has been seen before and is aleady in the cache.

> My code is running in the web server. When the users run this code each time, the server will open a fresh R. Thus, every time the users need to wait 270 seconds to get the data.

Must you open a fresh R sessions each time?  Can you keep the same R session alive which has seen those strings before?  You can `rm()` all variables in the `.GlobalEnv` after each user finishes their query.   Or use R in client server mode like I showed in a video and slides from 2009 at the very bottom [here](https://github.com/Rdatatable/data.table/wiki/Presentations).

**Comment by mattdowle** [comment]
I'd also be very interested in how fast pandas read_csv is for you on this file. Python folk tell us it is better at handling strings and faster at hashing.  Please do let us know.
