### ISSUE TITLE
question about fread

### ISSUE THREAD

**Issue by wangj26** [Rdatatable/data.table#2017]
Hi,

I have a big file in the server (around 1.4Gb) and want to read this file from the client side. Using fread to read this file took a very long time to download the file first and then loaded the file to the R. It totally took 1305.329 seconds to finish the read.

I then tried to directly use read.csv to read the file from server. It took 1251.877 seconds to finish the read. 

My question is whether there is some ways that can make the download part faster in the fread.

Thanks,

**Comment by jangorecki** [comment]
@wangj26 Hi, download part in fread function is outsourced to external code, either base R or `curl` package. There is not much that can be done here. It can get eventually faster when fread will support connection. Keep in mind you can use shell commands inside `fread` call, so you can speed up the download part using OS tools. Closing as not related to fread, if you have suggestions how current download part could be improved feel free to reopen.
