### ISSUE TITLE
R data.table fast subset matching

### ISSUE THREAD

**Issue by sjain777** [Rdatatable/data.table#2018]
Hi, is there a fast way to compare two columns row-wise, whether column A is a subset of column B, where A and B contain a comma-separated list of character strings. I have example code below but that is extremely slow (takes hours) over a table of thousands of rows.  This is an example of making predictions on Test data from an Association Rules model (_arules::apriori_). There is no 
"predict" method for this particular model in the package, and computing the predictions using other methods in the package is slow over 1000's of rows. 
Hence, I am trying to use **data.table** and its features for speed and memory efficiency for doing the computation. I have done timing tests and based on that, the following step is the blocker in processing time as the number of rows increases. 

`pred <- rulesDT[, matchcol := subsetmatch(LHS, items)][matchcol == 1][, .(Predictable, Probability)]`

If you could point me to a better way of doing the computation below, that would be very much appreciated. Thanks! PS: The version is 1.9.6 for data.table used in the example below (in R 64-bit, on Windows).

#### Load libraries
`if(! "arules" %in% installed.packages()) install.packages("arules", depend = TRUE)`
`if(! "data.table" %in% installed.packages()) install.packages("data.table", depend = TRUE)`
`if(! "rje" %in% installed.packages()) install.packages("rje", depend = TRUE)`
`library(arules)`
`# for method: subsetmatch`
`library(rje)`                
`library(data.table)`

#### Get input data
`data(Groceries)`

#### Define a set of outcomes to build Association Rules models
`Predictables <- c("soda", "vinegar", "coffee", "butter")`

#### Define Train and Test data
`TrainAR <- Groceries[1:5000]`
`TestAR <- Groceries[5001:length(Groceries)]`

#### Build Association Rules models over all outcomes
`aprioriModel <- lapply(Predictables, function(x) apriori(TrainAR, parameter = list(supp=0.001, minlen = 2, maxlen=5, conf = 0.5, target = "rules"), appearance = list(rhs = x, default="lhs")))`

#### First, define methods makeRulesDataTable, rec, scoreARModel

```
makeRulesDataTable <- function(x) { 
  if(length(x) > 0) {
    data.table(LHS = LIST(x@lhs), Predictable = unlist(LIST(x@rhs)), Probability = as(x, "data.frame")$confidence)
  }  else data.table(NULL)
}
```

```
rec <- function(x, indata, rulesDT) {
  if(dim(rulesDT)[1] > 0) {
    rulesDT[, items := rep(LIST(indata[x]), nrow(rulesDT))];	
    pred <- rulesDT[, matchcol := subsetmatch(LHS, items)][matchcol == 1][, .(Predictable, Probability)];
    if(dim(pred)[1] > 0) {		
      pred <- pred[, list(Probability = max(Probability), RowId = x), by = Predictable]
    } else pred <- data.table(NULL)
    rulesDT[, items := NULL];
  } else pred <- data.table(NULL);
  pred
}
```

```
scoreARModel <- function(x, RowIdVec, TestAR) {
  rulesExtract <- makeRulesDataTable(x);
  pred <- lapply(RowIdVec, rec, indata = TestAR, rulesDT = rulesExtract);
  pred <- rbindlist(pred);
}
```

#### Next, make predictions on Test data
`#RowIdVec <- 1:4835 # corresponds to total number of Rows in TestAR`
`TestAR2 <- TestAR[1:5]    # choose a subset for demonstration`
`RowIdVec <- 1:5`
`tscoretestdata <- system.time(predAR <- rbindlist(lapply(aprioriModel, scoreARModel, RowIdVec, TestAR2)) )`       
`tscoretestdata[[3]][1]`
`#[1] 5.71 `

`TestAR2 <- TestAR[1:15]`
`RowIdVec <- 1:15`
`tscoretestdata <- system.time(predAR <- rbindlist(lapply(aprioriModel, scoreARModel, RowIdVec, TestAR2)) )`       
`tscoretestdata[[3]][1]`
`#[1] 17.56`
`# Going to larger number of rows increases processing times.`

**Comment by franknarf1** [comment]
Please edit to indent your code so it formats more readably on github. Also consider making an example that doesn't require installing two extra packages (or is it three? I cannot find Groceries).  This is a good place to start: https://github.com/Rdatatable/data.table/wiki/Support

**Comment by sjain777** [comment]
Hi, Thanks for your feedback. I have updated the code so the indentation is better. Regarding the Groceries dataset, that's found when loading library(arules). My example is based on this dataset and to demonstrate the real problem (subset-matching a comma-separated list of values via data.table) I needed to use the additional packages (arules, rje). Thanks!

**Comment by arunsrinivasan** [comment]
This sort of Q is more suitable on SO first. Also please use minimal data, minimal code, and minimal packages to explain your point.

Short answer: No, there's no method in data.table to search efficiently between two list of character vectors. You will have to use packages designed for that. If you want to file a potential FR, please re-file a minimal example.
