### ISSUE TITLE
rbindlist segfault

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#2019]
[Commit 2706](https://github.com/Rdatatable/data.table/commit/2f136404619af1a16c05516c7eaa870e193e3bc5) segfaults `rbindlist` when used with `idcol` argument.

```r
require(data.table)
dt <- setDT(lapply(1:11, function(x) sample(letters, 1e4L, TRUE)))

ll <- lapply(1:3000, function(x) {
  if (runif(1) > 0.5) data.table() else dt[sample(1000L)]
})

# works fine
for (i in 1:50) {
  ans1 <- rbindlist(ll)
}

# segfaults
for (i in 1:50) {
  ans2 <- rbindlist(ll, idcol="id")
}
```

The current CRAN version segfaults. Narrowed it down to commit 2706.

**Comment by mllg** [comment]
Here is an example which is easier to reproduce:
```r
require(data.table)
x <- list(list(a = 1), list(), list(a = 2))
rbindlist(x, idcol = "id")
```
This is fixed with #2077, but I'm not sure where to put the test.
