### ISSUE TITLE
Bug in merging with `on=`

### ISSUE THREAD

**Issue by my-R-help** [Rdatatable/data.table#2021]
Maybe I misunderstand the documentation, but the following doesn't work: 

    X <- data.table(a = 1:3, b = letters[1:3])
    Y <- data.table(p = 2:4, o = LETTERS[1:3])
    X[Y, on = c(x = "a", y = "p")]

I get the following error both in the development version as well as the CRAN version (1.10.4): 

    Error in `[.data.table`(X, Y, on = c(x = "a", y = "p")) : 
      Column(s) [x,y] not found in x

**Comment by franknarf1** [comment]
Yeah, the syntax is `x[i, on=c(xcol = "icol", xcol2 = "icol2")]`.

**Comment by my-R-help** [comment]
Following your reply, the code below still gives the same error message: 

    X[Y, on = c(xcol = "a", xcol2 = "p")]

I also tried `X[Y, on = c(xcol = "a", ycol = "p")]` with the same result. 

I think I'm using the syntax in my original post correctly, according to `?data.table`.

**Comment by ChristK** [comment]
You are still misinterpreting the syntax. `xcol` is a column name in `x` and `"icol"` is a quoted column name in `i`
Try this with your example
`X[Y, on = c(a = "p")]`

**Comment by my-R-help** [comment]
I see, many thanks for clarifying. 

In my opinion, the documentation in `?data.table` could be expanded a bit to avoid these kinds of misunderstandings. For example, the second bullet point under `on:` might better read like this: 

As a _named_ character vector, e.g., `X[Y, on=c(x="a", y="b")]`, where `x` and `y` are column names in `X` and `"a"` and `"b"` refer to column names in `Y`.

**Comment by jameslamb** [comment]
Could this issue be closed? When I run `?data.table::data.table` on version 1.12.0, I see this text which basically has the same information as what @my-R-help recommended

![image](https://user-images.githubusercontent.com/7608904/62750567-40c9c780-ba26-11e9-9859-4b38e8d8130f.png)

**Comment by jangorecki** [comment]
thanks @jameslamb for letting us know
