### ISSUE TITLE
Using Package

### ISSUE THREAD

**Issue by msgoussi** [Rdatatable/data.table#2024]
Dear Sir, 
I have a big csv file (almost 7GB) has more than 13 million cells.
I would like to use data.table since it is an extension to data.frame
I am wondering how I can use the package to read the file (either csv or zip format) and how to write via data.table to save locally, and how view part of the data in R.
Thanks

**Comment by MichaelChirico** [comment]
https://github.com/Rdatatable/data.table/wiki/Getting-started

**Comment by franknarf1** [comment]
Also look at https://github.com/Rdatatable/data.table/wiki/Support . This issue tracker is not really a good place to request a tutorial.

**Comment by arunsrinivasan** [comment]
You'll have to learn to use the package by going through the vignettes linked above.
