### ISSUE TITLE
fread stringsAsFactors=0.2

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2025]
For character columns, if  `uniqueN(column)/nrow < 0.2` then make the column a factor.  Generalizing current binary argument to a scale between FALSE (0.0) and TRUE (1.0).
Request came up for onwards model build which switches based on character / factor type.
No change to default FALSE.

**Comment by MichaelChirico** [comment]
the closing PR is a bit large, @HughParsonage can you confirm this issue was closed at the R level? I seem to recall it was...

**Comment by HughParsonage** [comment]
Yes: https://github.com/Rdatatable/data.table/blob/be6c1fc66a411211c4ca944702c1cab7739445f3/R/fread.R#L322
