### ISSUE TITLE
setnames renames what I want and, unfortunately, more things

### ISSUE THREAD

**Issue by pachamaltese** [Rdatatable/data.table#2027]
Hi

I was using this

`setnames(hs_imports_2, c("exports_val"), c("exports_val_fob"))`

But that is renaming  column in `hs_imports` *and* `hs_imports_2` :(

A bug maybe? I have R 3.2 for Ubuntu and data.table 1.10.4

**Comment by cderv** [comment]
How do you create hs_imports ? 
If you did not make a hard copy with `copy` but use classic assignment <-, modifying the one update the other too. 
It is not a bug and it is by design. You could find explanations in the vignettes you can find in the wiki.

**Comment by pachamaltese** [comment]
I did use `assign(...)`

**Comment by arunsrinivasan** [comment]
`assign` does not create a (deep) copy as well. For the future, use `data.table::address` to check that the addresses are non-identical to ensure you're not updating an object that another object points to as well..
