### ISSUE TITLE
Non-consistent merge results with CHARSXP and segfault

### ISSUE THREAD

**Issue by kislenok-roman** [Rdatatable/data.table#2028]
I've used data.table for a lot of join operations when some day I've got this with 1.9.8:
> simpleError in bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch, mult, ops, nqgrp, nqmaxgrp, verbose = verbose): 'translateCharUTF8' must be called on a CHARSXP

Ok. I've tried to solve this problem with update. But with 1.10.4 (latest from CRAN) more often I got the `CHARSXP` and sometimes even this:
> *** caught segfault ***
> address 0x430bed708, cause 'memory not mapped'"
> 
> Traceback:"
>  1: bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch,
>     mult, ops, nqgrp, nqmaxgrp, verbose = verbose)
>  2: `[.data.table`(y, x, nomatch = if (all.x) NA else 0, on = by,
>     allow.cartesian = allow.cartesian)
>  3: y[x, nomatch = if (all.x) NA else 0, on = by, allow.cartesian = allow.cartesian]
>  4: merge.data.table(x = dic, y = dic[, list(has_child = 1), list(fullname = path)],
>     by = \"fullname\", all.x = TRUE, allow.cartesian = TRUE)
>  5: merge(x = dic, y = dic[, list(has_child = 1), list(fullname = path)],
>     by = \"fullname\", all.x = TRUE, allow.cartesian = TRUE)
>  6: processLog(dt)
> aborting ...

I've tried to reproduce the problem and I have a code and data that cause error.
I've tried it on:
* 1.9.8 (the server: wrong result in 1-2 out of 60);
* 1.10.0 (my machine before update: wrong result in 1-2 out of 60);
* 1.10.4 (my machine after update: wrong result in 6-35 out of 60, or CHARSXP or even segfault if you are lucky).

All tested only on Linux. Expected result for 3 tests: "1" as all key values in `r1` are in `r2` (`r2` build from several `r1`'s)
The code and output for 1.10.4:
```
sessionInfo()
# R version 3.2.3 (2015-12-10)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Ubuntu 16.04.1 LTS
# 
# locale:
#  [1] LC_CTYPE=ru_RU.UTF-8       LC_NUMERIC=C               LC_TIME=ru_RU.UTF-8        LC_COLLATE=ru_RU.UTF-8    
#  [5] LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=ru_RU.UTF-8    LC_PAPER=ru_RU.UTF-8       LC_NAME=C                 
#  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=ru_RU.UTF-8  LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] data.table_1.10.4
# 
# loaded via a namespace (and not attached):
# [1] tools_3.2.3
r1 <- readRDS("res.RData")
r2 <- readRDS("dic.RData")
setkey(r1, "path", "name")
setkey(r2, "path", "name")
print(r1[, .N, list(Encoding(path), Encoding(name))])
#     Encoding Encoding.1      N
# 1:  unknown    unknown 964538
print(r2[, .N, list(Encoding(path), Encoding(name))])
#    Encoding Encoding.1       N
# 1:  unknown    unknown 5555527
print("Please note that both `name` and `path` are in Russian")
# [1] "Please note that both `name` and `path` are in Russian"
all <- 20
success1 <- 0
success2 <- 0
success3 <- 0
for (i in 1:all) {
  success1 <- success1 + (r2[r1][is.na(id), .N] == 0)
  success2 <- success2 + (r2[r1][is.na(id), .N] == 0)
  success3 <- success3 + (r2[r1][is.na(id), .N] == 0)
}
print(success1 / all)
# [1] 0.95
print(success2 / all)
# [1] 0.90
print(success3 / all)
# [1] 0.85
```
Obviously not even close to 1
or (sorry, it's partly in Russian) you can get this during `for`:
>  Ошибка в bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch,  :
>  'translateCharUTF8' должен быть вызван на CHARSXP 
> 7. bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch, 
>    mult, ops, nqgrp, nqmaxgrp, verbose = verbose) 
> 6. `[.data.table`(r2, r1) at .active-rstudio-document#24
> 5. r2[r1] at .active-rstudio-document#24
> 4. eval(expr, envir, enclos) 
> 3. eval(ei, envir) 
> 2. withVisible(eval(ei, envir)) 
> 1. source("~/.active-rstudio-document", echo = TRUE) 

And strange thing - it's "always" (the times I've checked) different rows that did not match. 
Files are big so I've uploaded them to DropBox: "dic.RData" (https://www.dropbox.com/s/loj3j3oseg26wn1/dic.RData?dl=0) and "res.RData" (https://www.dropbox.com/s/q3m3xkwd3q11gde/res.RData?dl=0)

**Comment by adamaltmejd** [comment]
I'm experiencing something similar using data.table_1.10.5:

```
Error in forderv(x, by = rightcols) :
  'translateCharUTF8' must be called on a CHARSXP
Calls: source ... withVisible -> eval -> eval -> [ -> [.data.table -> forderv
```

Downgrading to the latest version on CRAN (1.10.4.3) solves the problems with translateCharUTF8 but then i get segfaults instead when trying to do a non-equi join on the data. Really hard to debug, don't even know what kind of encoding issue I'm dealing with.

**Comment by adamaltmejd** [comment]
Here is my traceback of the segfault:

```
 *** caught segfault ***
address 0x405fa0144, cause 'memory not mapped'

Traceback:
 1: bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch,     mult, ops, nqgrp, nqmaxgrp, verbose = verbose)
 2: `[.data.table`(poang, d, sum(credits_done), on = list(id, HsKod,     LProg, year >= admission_year), by = .EACHI)
 3: poang[d, sum(credits_done), on = list(id, HsKod, LProg, year >=     admission_year),by = .EACHI]
 4: eval(jsub, SDenv, parent.frame())
 5: eval(jsub, SDenv, parent.frame())
 6: `[.data.table`(d, , `:=`(credits_accumulated, poang[d, sum(credits_done),     on = .(id, HsKod, LProg, year >= admission_year), by = .EACHI]$V1))
 7: d[, `:=`(credits_accumulated, poang[d, sum(credits_done), on = .(id,     HsKod, LProg, year >= admission_year), by = .EACHI]$V1)]
```

**Comment by valentas-kurauskas** [comment]
I encountered only the second error (segfault), which I believe actually was an out of memory problem.

**Comment by jangorecki** [comment]
@valentas-kurauskas are you able to provide reproducible example?

**Comment by valentas-kurauskas** [comment]
@jangorecki no, sorry, that was with linux ulimit set and a pretty large amount of memory and complex code.

**Comment by MichaelChirico** [comment]
No reliable reproducible example to check if it's still affecting master.

Please re-open if you experience this and can provide a repro.
