### ISSUE TITLE
as.ITime(character(0)) fails

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#2032]
```r
require(data.table)
as.ITime(character(0))
# Error in substring(paste("0", hh, sep = ""), nchar(paste(hh))) : 
#   invalid substring arguments
```

The issue is very likely in `format.ITime`. I think the behaviour should be similar to `as.Date()`, `as.IDate()` and `as.POSIXct()`.

**Comment by MichaelChirico** [comment]
x = as.ITime(character(0))

is OK.

so it's `print(x)` causing the issue.
