### ISSUE TITLE
web version of FAQ doesn't match local copy (missing TOC, item numbering)

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2033]
The copy linked from [Getting Started](https://github.com/Rdatatable/data.table/wiki/Getting-started) doesn't include the latest answers regarding `DT[, "col"]` (FAQ 1.1 and others), while my local copy does.

**Comment by m0nhawk** [comment]
I have updated the [Getting Started](https://github.com/Rdatatable/data.table/wiki/Getting-started) with the most up-to date links on CRAN.

**Comment by MichaelChirico** [comment]
closing, seems fixed to me (right @franknarf1?)

**Comment by franknarf1** [comment]
@MichaelChirico I find it useful to refer to question numbers within the faq (as I did in the OP), but the link @m0nhawk found to CRAN does not display these (while the older link did). Fyi, that's why I didn't just change the link myself or close this earlier. Fine to have it closed if the faq itself is in for a big overhaul (as you have in mind in #2664 ).

**Comment by MichaelChirico** [comment]
@franknarf1 indeed... it's mentioned in the first paragraphs that the display seems messed up. I'll re-open, editing top post to clarify what's missing and add reference in #2664.

**Comment by MichaelChirico** [comment]
`vignette("datatable-faq")`, the [CRAN page](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html), and our [website render](https://rdatatable.gitlab.io/data.table/articles/datatable-faq.html) all look the same to me now. Closing.
