### ISSUE TITLE
Expected sep (',') but new line or EOF ends field 14 on line 675816

### ISSUE THREAD

**Issue by zheguzai100** [Rdatatable/data.table#2037]
`Read 24.4% of 2338118 rows
Error in data.table::fread("./train/bill_detail_train.txt", header = FALSE,  : 
  Expected sep (',') but new line or EOF ends field 14 on line 675816 when reading data: 2699,5911634067,6,20.659179,20.665913,21.069883,21.068517,18.765930,0,0.000000,0.000000,0.000000(0.000000,20.376736,0
In addition: Warning message:
In data.table::fread("./train/bill_detail_train.txt", header = FALSE,  :
  Bumped column 12 to type character on data row 675816, field contains '0.000000(0.000000'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses a sample of 1,000 rows (100 rows at 10 points) so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE`

**Actually, info of line 675816 is** 
`2699,5911634067,6,20.659179,20.665913,21.069883,21.068517,18.765930,0,0.000000,0.000000,0.000000,0.000000,20.376736,0`

**Comment by jangorecki** [comment]
@zheguzai100 
> If reporting to datatable-help, please rerun and include the output from verbose=TRUE

**Comment by st-pasha** [comment]
Not enough information to understand the problem
