### ISSUE TITLE
Compiling ignores Makevars options  -mtune=native -march=native 

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#2038]
Hello.

When I install data.table in Windows 10 using 

> install.packages("data.table", type = "source", repos = "http://Rdatatable.github.io/data.table")

it does so showing message lines such as:

> c:/Rtools/mingw_64/bin/gcc -m64 -I"C:/PROGRA1/MIE74D1/MRO-331.1/include" -DNDEBUG     -I"C:/swarm/workspace/External-R-3.3.1/vendor/extsoft/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mtune=core2 -c assign.c -o assign.o

Ignoring my Makevars options

> -mtune=native -march=native 

I guess it doesn't use my Makevars at all because it has its own configuration.

Where can I change it?
I would like to compile data.table optimized for my architecture, Intel Core i7-4790K Haswell-DT.

I have even tried with

> install.packages("data.table", type = "source", repos = "http://Rdatatable.github.io/data.table", configure.args = "CXXFLAGS+=  -mtune=native -march=native -Wno-unused-variable -Wno-unused-function")

but it doesn't work either.

**Comment by arunsrinivasan** [comment]
See how to add `CFLAGS` and `CXXFLAGS` to your `~/.R/Makevars` as shown under [Installation](https://github.com/Rdatatable/data.table/wiki/Installation).

Write back if that doesn't solve.
