### ISSUE TITLE
Sorting a logical column generates an error with ASAN LeakSanitizer

### ISSUE THREAD

**Issue by MarcusKlik** [Rdatatable/data.table#2039]
While compiling the `fst` package using ASAN and UBSAN sanitizer support, I noticed that `data.table`'s method `setkey` introduces a memory leak when sorting a logical column.

```r
x <- data.table(A = 1:2)
setkey(x, A)  # no problem here

x <- data.table(A = c(1.2, 2.4))
setkey(x, A)  # no problem here

x <- data.table(A = LETTERS[1:2])
setkey(x, A)  # no problem here

x <- data.table(A = factor(LETTERS[1:2]))
setkey(x, A)  # no problem here

x <- data.table(A = c(TRUE, FALSE))
setkey(x, A)  # memory leak
```

The actual LeakSanitizer error for the example above:

```
=================================================================
==6127==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 192 byte(s) in 1 object(s) allocated from:
    #0 0x4cb988  (/usr/local/lib/R/bin/exec/R+0x4cb988)
    #1 0x7f1758383688  (/usr/lib/x86_64-linux-gnu/libgomp.so.1+0x9688)

SUMMARY: AddressSanitizer: 192 byte(s) leaked in 1 allocation(s).
```

It's a very small leak obviously but I though you might wanted to know!

**Comment by MichaelChirico** [comment]
Hi @MarcusKlik, I just tried running this on the `RD` binary of `rocker/r-devel-san` Docker image: https://github.com/rocker-org/r-devel-san/blob/master/Dockerfile and didn't get any memory leak issue, can you confirm the memory leak seems to have been fixed?

**Comment by MarcusKlik** [comment]
Hi @MichaelChirico, thanks for reporting back on this one, yes, I can confirm the error is gone!
