### ISSUE TITLE
data table object requires casting or debugger access for successful return from function

### ISSUE THREAD

**Issue by freeberz** [Rdatatable/data.table#2042]
A simple function consistently fails to return a data table object _unless_  either: a) the object is cast using as.data.table(); or b) the object is first accessed within the debugger. The following code reproduces the bug. A test data table, dt, is included below. The function **must be invoked from the REPL** in order to reproduce the bug. 

```
#-------------------------------------------------- 
bug.func <- function(dt=data.table(), bug.on=TRUE) {
#-------------------------------------------------- 
  
  # Initialise new data table
  dt.new <- copy(dt) 
  dt.new[,`:=` (cum.np=cumsum(np), cum.nq=cumsum(n-np), cum.n= cumsum(n))]
  
  # Return new data table
  if (bug.on) {
    return(dt.new)
  } else {
    return(as.data.table(dt.new))
  }
}

# Create test table 
dt <- data.table(np=c(1:5), n=c(1:5))

# Invocation (must be made from REPL to reproduce). This returns nothing (not even a NULL) at the REPL
bug.func(dt, bug.on=TRUE)
# ... while this returns a data table
bug.func(dt, bug.on=FALSE)
```
Here is the output from sessionInfo():

R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4

loaded via a namespace (and not attached):
[1] tools_3.3.2
>

**Comment by jangorecki** [comment]
@freeberz please ensure that your `bug.on=TRUE` call is not returning data.table invisibly. It works fine on my Mac machine. Please re-open if it didn't work for you.
```
bug.func(dt, bug.on=TRUE)[]
```
For details about the need of `[]` see FAQ.
