### ISSUE TITLE
Error: cannot allocate vector of size

### ISSUE THREAD

**Issue by msgoussi** [Rdatatable/data.table#2043]
I have a data.table "x" with (772867 by 460), and I would like to use data.table::melt
nums<-sapply(x,is.numeric)
data.table::melt(x,id.vars=names(x)[nums==F],
                      measure.vars=names(x)[nums==T])
I get the following error.
Error: cannot allocate vector of size 2.6 Gb

OS is windows 7 (x64) and I am using R 3.3.2 x86_64-w64-mingw32
PC RAM is 15.6 GB.
Can you please advise.

**Comment by jangorecki** [comment]
@msgoussi Please provide reproducible example, ensure that amount of numeric fields is similar to your original data. Also knowing data.table version will help.

**Comment by arunsrinivasan** [comment]
Please (re)read [SUPPORT](https://github.com/Rdatatable/data.table/wiki/Support) page and file again with all necessary info.

**Comment by Ic3fr0g** [comment]
#1540
