### ISSUE TITLE
fread version 1.10.4 Error: isLOGICAL(showProgress) is not TRUE

### ISSUE THREAD

**Issue by bmreilly** [Rdatatable/data.table#2048]
I recently updated to version 1.10.4, and since the update whenever I use fread() I get an error: 

```
fread(f)
Error: isLOGICAL(showProgress) is not TRUE
```

Unless I specify `showProgress=FALSE`

Is this intentional or is this an issue?

**Comment by jangorecki** [comment]
duplicate of #1998
