### ISSUE TITLE
Ask for a new feature of supporting fread from clipboard

### ISSUE THREAD

**Issue by bioinformatist** [Rdatatable/data.table#2056]
Dear,
Currently `data.table::fread` seems cannot support read data from clipboard (like a section dragged in MS Excel). I get the answer on *stackoverflow* that we can wrap it ourselves but it will be more convenient if data.table make it:

```R
freadClip <- function(...) {
  X <- tempfile()
  writeLines(readLines("clipboard"), X)
  fread(X, ...)
}
```

From: [http://stackoverflow.com/a/19786996](http://stackoverflow.com/a/19786996)

Thanks.

**Comment by jangorecki** [comment]
Duplicate of #1292
