### ISSUE TITLE
no more speedup for radix sort in datatable-intro?

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#2058]
The datatable-intro vignette mentions that order is internally optimized, but the speedup is only 1x. I think this is because recent versions of R are now using your sorting code. Is that correct? Anyway, you should probably update that vignette, since a speedup of 1x is nothing to write home about...

**Comment by jangorecki** [comment]
resolved in https://github.com/Rdatatable/data.table/commit/27dedc1ff3964a6df4ddf41e25e1368c0166ed4f

**Comment by jangorecki** [comment]
Actually recent improvements to `order` has not been ported to base R, and they might not be ported at all because they depend on openmp, so then speed up could be presented again. Or better is just to link to decent _order_ benchmark online, ideally continuously updated.
