### ISSUE TITLE
define multiple aggregation functions outside of dcast and refer to them inside of dcast

### ISSUE THREAD

**Issue by smidelius** [Rdatatable/data.table#2064]
I want to define multiple aggregation functions in custom number/order outside of dcast and then pass it to dcast fun parameter.

I try to achieve something like that:
```

dt <-  data.table(x=sample(5,20,TRUE), y=sample(2,20,TRUE), 
                z=sample(letters[1:2], 20,TRUE), d1 = runif(20), d2=1L)

functions <- list(sum,mean)

dcast(dt, x + y ~ z, fun=functions, value.var="d1") 

```

But I get the error message: 

> Error in eval(expr, envir, enclos) : could not find function "functions"

**Comment by franknarf1** [comment]
Related to this [SO question](http://stackoverflow.com/q/42846181/1191259) and issue #1369.

**Comment by arunsrinivasan** [comment]
dup of https://github.com/Rdatatable/data.table/issues/1369
