### ISSUE TITLE
Error from fread failing to read column correctly

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2067]
I guess this is related to the recent drop of mid-read bumping.

Not sure if the logic can be improved to have handled this file correctly:

```
tmp = tempfile()
tdir = tempdir()
download.file('https://nces.ed.gov/ccd/data/zip/ag071b_txt.zip', tmp)
unzip(tmp, exdir = tdir)
unlink(tmp)

ff = list.files(tdir, pattern = 'txt', full.names = TRUE)

fread(ff)
```
> Column 5 ('PHONE07') was guessed at type 'integer64' but row 7629 contains `<<M>>`.
Error in fread(ff) : 
 
> The guessed column type was insufficient for 51 values in 1 columns. The first in each column was printed to the console. Use colClasses to set these column classes manually.

The easiest fix is to just set `colClasses = 'character'`, which is obviously not ideal/efficient. A more tailored approach would set `colClasses = list(character = 'PHONE07')`, but that doesn't work in my case since (as is the same data pipeline I'm working with as in #2066) this is just one of a series of files I'm reading, and the other files error when they don't contain `PHONE07` (it would be nice to get a warning instead of an error for the other files?).

I also don't think the error message is telling the truth -- I think the error message is predicated on having used `verbose = TRUE`. So I guess it should be updated.

**Comment by st-pasha** [comment]
Trying this test case, it appears to work correctly in the latest version. Closing as "not reproducible"
