### ISSUE TITLE
[BUG] fread error on particular csv in latest development build

### ISSUE THREAD

**Issue by yaakovfeldman** [Rdatatable/data.table#2070]
I have several large csv files. Using the latest development build (windows binary from AppVeyor), fread fails on one of them with error:

`Error in fread("myfile.csv") : 
  A row outside the large sample was i) either too short and fill=FALSE ii) too long or iii) a jump batch didn't end properly. This message will be made specific before release to CRAN.`

This is after the commit 'fread parallel' https://github.com/Rdatatable/data.table/commit/0b3cd65381656330b66c5670c2c044f76e2ac03f

The previous commit and earlier still work fine, so something must have changed in this commit.

The csv has 89205 observations of 9 variables. Unfortunately, it is sensitive. What can I try to help make a reproducible example?

EDIT: anonymised csv in comment below

**Comment by MichaelChirico** [comment]
is it possible to replace all of the sensitive fields with ### or some
other anonymizer?

**Comment by yaakovfeldman** [comment]
I now have a reproducible example! (Anonymising didn't work earlier)
[csv.zip](https://github.com/Rdatatable/data.table/files/858334/csv.zip)

I get the error above with
`fread(myfile.csv)`

**Comment by mattdowle** [comment]
Reproduced - thanks.

**Comment by mattdowle** [comment]
Many thanks for providing this file.  Works for me now.  Please open a new issue if you find anything else.
