### ISSUE TITLE
Failed subsetting on character UTF8 column

### ISSUE THREAD

**Issue by ghost** [Rdatatable/data.table#2074]
Data table DT has a character column NAZWA encoded in UTF8 and approx. 7.5 million rows with 370 unique values. The following code is meant to recode NAZWA into integer column KOD:

kod <- setkey(DT, NAZWA)[, .(NAZWA = unique(NAZWA))][, KOD := .I]
DT[kod, KOD := i.KOD, on = .(NAZWA)]
DT[, .N, by = is.na(KOD)]

The last command returned the following:

   is.na       N
1: FALSE 7146718
2:  TRUE  332407

Apparently, lots of rows were left without a code. However, when DT$NAZWA contains unique values only, all are assigned a proper code. What’s wrong about it?

**Comment by MichaelChirico** [comment]
Why not just `DT[ , KOD := .GRP, by = NAZWA]`? Anyway, this seems like a question for StackOverflow.

**Comment by Monacopedia** [comment]
Thank you, my point, however, was about subsetting and the above re-coding was just a case to prove my concern. It looks to me that there is a problem of scale with subsetting on UTF8 column.

**Comment by jangorecki** [comment]
No reproducible example, user deleted his account sometime within last 3 years so we will probably not get any code.
