### ISSUE TITLE
Fread unable to distinguish separators

### ISSUE THREAD

**Issue by DatBreh** [Rdatatable/data.table#2075]
Expect to get a dataset with 3 columns.
R code i'm using is `Answers <- fread(input = 'data/stackoverflow.txt', stringsAsFactors = FALSE)`
with R package 'data.table' v1.10.5 in development from GitHub.

the line which caused trouble is: "1","Pr/ "d/s". "a", n) ","B"

`Error in fread(input = "data/stackoverflow.txt", stringsAsFactors = FALSE) : 
  Line 3 starting <<"1","Pr/ ">> has more than the expected 3 fields. Separator 3 occurs at position 26 which is character 6 of the last field: << n) ","B">>. Consider setting 'comment.char=' if there is a trailing comment to be ignored.`

Please find attached txt file.

[stackoverflow.txt](https://github.com/Rdatatable/data.table/files/863585/stackoverflow.txt)

**Comment by st-pasha** [comment]
This is an example of a file with improperly quoted fields. Normally if a field contains internal quotation marks, they should either be doubled (CSV standard) or escaped. When the quotation marks are left as-is, then it becomes impossible to unambiguously parse them. *Usually* `fread` does a good job handling these improperly quoted fields regardless. However your example is unusual: it looks to fread as 4 fields `"1"`, `"Pr/ "d/s". "a"`, `n) "`, and `"B"`. This is why the error is produced.
