### ISSUE TITLE
Cannot find all.equal in data.table namespace

### ISSUE THREAD

**Issue by zwep** [Rdatatable/data.table#2076]
The title says the most...

I want to compare to data.tables using all.equal. However, I can only use the base version.

Tried to use data.table::all.equal, but then I get the error that this function is not in the namespace.
I am using data.table version 1.10 and R version 3.2.3

The documentation online and calling help(all.equal) does show that there is an all.equal function in data.table... hence my confusion.

I need the all.equal of data.table because I need the line ignore.row.order = TRUE, which is not available in the base version

**Comment by MichaelChirico** [comment]
you'll need to provide a reproducible example.

please try restarting R and reinstalling data.table if the problem persists.

**Comment by zwep** [comment]
dt1 <- data.table(A = letters[1:10], X = 1:10, key = "A")
dt2 <- data.table(A = letters[5:14], Y = 1:10, key = "A")
x <- setkeyv(copy(dt1), NULL)
y <- dt1[sample(nrow(dt1))]
all.equal(x, y)
all.equal(x, y, ignore.row.order = TRUE)

**Comment by jangorecki** [comment]
`all.equal` is S3 method so you should look for `all.equal.data.table`.
