### ISSUE TITLE
fread() deals with quoted zero-prefixed colum different from read.csv()

### ISSUE THREAD

**Issue by chenwq** [Rdatatable/data.table#2078]
I have a csv file such as "'0001',a\n'0002',b\n'0003',c", for fread(), the first column will be character but for read.csv() the 1st column will be numeric type. Hope there be an argument to control this issue.

**Comment by MichaelChirico** [comment]
It does?

```
read.csv(text = "'0001',a\n'0002',b\n'0003',c", header = FALSE)
#       V1 V2
# 1 '0001'  a
# 2 '0002'  b
# 3 '0003'  c
```

And from `?fread`/`colClasses`:

> A character vector of classes (named or unnamed), as `read.csv`. Or a named list of vectors of column names or numbers, see examples. `colClasses` in `fread` is intended for rare overrides, not for routine use. `fread` will only promote a column to a higher type if `colClasses` requests it. **It won't downgrade a column to a lower type since `NA`s would result. You have to coerce such columns afterwards yourself, if you really require data loss.**

**Comment by st-pasha** [comment]
```
fread("'0001',a\n'0002',b\n'0003',c", header = FALSE, quote='\'')
#    V1 V2
# 1:  1  a
# 2:  2  b
# 3:  3  c
```
