### ISSUE TITLE
Data table ":=" assignment used in functions prevents the output to the console

### ISSUE THREAD

**Issue by statespace** [Rdatatable/data.table#2093]
Here's working example:
```
test <- function(vec){
    x <- data.table(vec)
    return(x)
}
```
Returns (as expected):
```
> test(c(1,2,3))
   vec
1:   1
2:   2
3:   3
```
Here's what happens when adding ":=":
```
test <- function(vec){
    x <- data.table(vec)
    x[,vec2:=vec*2]
    return(x)
}
```
Returns nothing:
```
> test(c(1,2,3))
> 
```
However, it properly creates object with content when assigned. But what's very odd is that new data object does not return the table to the console when called for the first time after the assignment. 
```
> test <- function(vec){
+     x <- data.table(vec)
+     x[,vec2:=vec*2]
+     return(x)
+ }
> test(c(1,2,3)) ### no output 
> a <- test(c(1,2,3)) 
> a ### no output
> a ### on second call it creates output to console as expected
   vec vec2
1:   1    2
2:   2    4
3:   3    6

```

**Comment by MichaelChirico** [comment]
please read the faq

**Comment by statespace** [comment]
Could you please add a pointer to the FAQ you are referring to?

**Comment by MichaelChirico** [comment]
please try googling

https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-faq.html

**Comment by statespace** [comment]
Thanks a lot, sometimes keywords for search of very specific issues are not obvious... 
Anyways, this issue should be closed.

**Comment by MichaelChirico** [comment]
just click the "close issue" button
