### ISSUE TITLE
Join using on not working when specifying column names

### ISSUE THREAD

**Issue by jrowen** [Rdatatable/data.table#2094]
This example doesn't appear to work.
```
X = data.table(A=LETTERS[1:10], value1=1:10)
Y = data.table(B=LETTERS[1:10], value2=11:20)
X[Y, on=c(x="A", y="B")]
```
But the `data.table` help for `on` appears to say that it should work: "As a named character vector, e.g., X[Y, on=c(x="a", y="b")]. This is useful when column names to join by are different between the two tables."

From what I can see [in the code](https://github.com/Rdatatable/data.table/blob/c4cb116ce48141a4bd9660035c787b2c5c05a450/R/data.table.R#L660), it appears that the `on` names are not used when checking is columns are present.

**Comment by franknarf1** [comment]
The lower-case x and y are meaningful there. They should be column names in X. Similarly, a and b should be column names in Y.

The line you found in the code shows the cols of X being selected. Try `names(c(x="A", y="B"))` if you're not familiar with that function already. Similarly, the leftcols line soon after shows cols of Y being selected...

**Comment by jrowen** [comment]
Thanks for the quick response.  With this additional info, I've confirmed that everything works.  I was getting confused by the fact that the lowercase names matched the table names, so my only suggestion might be to clarify the help text a bit more (the second and third lines of your comment are really helpful).
