### ISSUE TITLE
fread needs 'nThread' argument similar to fwrite

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#2101]
now that it reads in parallel so that we don't need to `setDTthreads()`, `fread()`, and `setDTthreads()` back again.

**Comment by mattdowle** [comment]
Done. Thanks.

**Comment by cemalley** [comment]
Was nThreads taken out? I can't use it as a option and it's not in docs.

**Comment by jangorecki** [comment]
@cemalley no it wasn't. What version you use? I see it in documentation: https://rdatatable.gitlab.io/data.table/library/data.table/html/fread.html

**Comment by MichaelChirico** [comment]
It's still in the code of course: `https://github.com/Rdatatable/data.table/blob/master/R/fread.R#L2`

**Comment by cemalley** [comment]
@jangorecki @MichaelChirico Hi all, I do see it in your code for fread, but not in documentation viewed from RStudio. I'm using data.table 1.10.4-3. nThread gives "Error: unused argument." I can still use multithreading with setDTthreads before running fread. Thank you for developing fread by the way, it is blazing fast even single threaded.

Here is my session info...

`> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4-3

loaded via a namespace (and not attached):
[1] compiler_3.4.3  Matrix_1.2-12   tools_3.4.3     yaml_2.1.18    
[5] grid_3.4.3      lattice_0.20-35`

**Comment by jangorecki** [comment]
@cemalley update to recent devel and re-open if still doesn't work for you.

**Comment by MichaelChirico** [comment]
@cemalley  thanks, the `sessionInfo()` helps. You can see [here](https://cran.r-project.org/web/packages/data.table/data.table.pdf) or in `?fread` on your installed version that `nThread` is _not_ a valid argument in `1.10.4-3`.

If you want this argument, update to the current development version following instructions here:

https://github.com/Rdatatable/data.table/wiki/Installation
