### ISSUE TITLE
auto index keeped in .SD

### ISSUE THREAD

**Issue by arcosdium** [Rdatatable/data.table#2102]
I noticed that an auto index of the whole data.table is keep in the .SD table. Under  certain circumstandes, this leads to wrong results.  Here is a minimal example (data.table Version 1.10.4, R Version 3.3.1)

```
temp<-data.table(a=c(1,2,1,2),b=c(1,2,3,2))
temp[a%in%c(1),b:=1]

temp
#   a b
#1: 1 1
#2: 2 2
#3: 1 1
#4: 2 2

test <- function(tab){
  tab <- copy(tab)
  str(tab)
  print(tab[a==2])
  tab[a==2]
}

temp[, test(.SD), by = c("b")]
```

The result is

```
Classes ‘data.table’ and 'data.frame':	2 obs. of  1 variable:
 $ a: num  1 1
 - attr(*, ".internal.selfref")=<externalptr> 
 - attr(*, "index")= atomic  
  ..- attr(*, "__a")= int  1 3 2 4
Empty data.table (0 rows) of 1 col: a
Classes ‘data.table’ and 'data.frame':	2 obs. of  1 variable:
 $ a: num  2 2
 - attr(*, ".internal.selfref")=<externalptr> 
 - attr(*, "index")= atomic  
  ..- attr(*, "__a")= int  1 3 2 4
   a
1: 2
   b a
1: 2 2
```

Thus one of the rows of the second .SD data.table ( `$ a: num  2 2`) got lost in the selection `tab[a==2]`. The line `tab <- copy(tab)` seems necessary to produce the error.
Turning auto indexing off with `options(datatable.auto.index=FALSE)`  and runing the same code again yields the correct result:

```
Classes ‘data.table’ and 'data.frame':	2 obs. of  1 variable:
 $ a: num  1 1
 - attr(*, ".internal.selfref")=<externalptr> 
Empty data.table (0 rows) of 1 col: a
Classes ‘data.table’ and 'data.frame':	2 obs. of  1 variable:
 $ a: num  2 2
 - attr(*, ".internal.selfref")=<externalptr> 
   a
1: 2
2: 2
   b a
1: 2 2
2: 2 2
```

**Comment by franknarf1** [comment]
Another workaround is to take a shallow copy:

```
f = function(d) data.table:::shallow(d)[a==2]
temp[, f(.SD), by=b]

   b a
1: 2 2
2: 2 2
````

I'm not sure why that works, since the index is still there:

```
temp[, attr(attr(data.table:::shallow(.SD), "index"), "__a"), by=b]

   b V1
1: 1  1
2: 1  3
3: 1  2
4: 1  4
5: 2  1
6: 2  3
7: 2  2
8: 2  4
```

**Comment by MarkusBonsch** [comment]
@arcosdium Somehow, the bug is fixed in the current development version. I am not sure, why, but still, fixed is fixed and I close the issue for now.
