### ISSUE TITLE
OpenMP compilation problems on Windows

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2103]
I saw this when I tried to install the devel version today:

> fread.c: In function 'readfile':
> fread.c:1301:32: error: expected end of line before 'read'
> fread.c:1302:21: error: invalid operator for '#pragma omp atomic' before '=' token

The [line](https://github.com/Rdatatable/data.table/blob/79a961e1e9d19910dffe89146fde407a5119b996/src/fread.c#L1301) is

            #pragma omp atomic read    

My setup is 

> R version 3.2.5 (2016-04-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

...with Rtools version 3.3.0.1959 (containing gcc 4.6.3). 

I don't know anything about C or compilation, but a google search suggests this is from the compiler not playing nice with OpenMP syntax.

**Comment by mattdowle** [comment]
Great thanks - good to know.
The Rtools page (https://cran.r-project.org/bin/windows/Rtools/) contains "Support for the gcc 4.6.3 toolchain has been dropped."
Can you upgrade to current release of Rtools v3.4 please?

**Comment by mattdowle** [comment]
gcc 4.6 supported OpenMP 3.0 IIUC and that's quite old now.  Although, I can't find a date.  Looking through OpenMP history I can't see when 'atomic read' was introduced.  But I have gcc 5.4 from Ubuntu 16.04 and that supports OpenMP 4.0.  So there's a good chance current Rtools34.exe should work.

**Comment by franknarf1** [comment]
@mattdowle Thanks. Yep, upgrading to rtools 3.4 did it (along with upgrading to R 3.3.3, since rtools 3.4 doesn't cover R 3.2.5).

**Comment by MichaelChirico** [comment]
Does that mean we have to bump the R Version on `DEPENDS`?

**Comment by mattdowle** [comment]
Good point.  I don't believe so, but it's definitely worth checking.

Could someone on Windows find out please?  The  Windows .zip that AppVeyor makes is available [here](https://github.com/Rdatatable/data.table/wiki/Installation#windows-binaries).  That's built with latest R and latest Rtools.exe.  That should be the same as Frank made himself.  That needs to be installed into R 3.0.0 (the current stated dependency) and then run `test.data.table()`.   I do that when releasing to CRAN on Linux ([here](https://github.com/Rdatatable/data.table/blob/master/CRAN_Release.cmd#L89)) but never before for Windows.  Typically many of the Suggests packages are not available that far back (their dependency is later) so I just do `test.data.table()` and not full 'R CMD check`.

**Comment by jangorecki** [comment]
Just to address unanswered question. We don't need to upgrade R version depends if we mean Rtools, those are different tools. Dependencies relation between R and Rtools is not in scope of data.table package.
