### ISSUE TITLE
fread coerces floating number into character

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#2104]
Hello.

I don't know if this is an error.

I've extracted a small part of my dataset and saved it as a csv file with just 2 columns and 30000 rows.

Yo can uncompress it and read it with 

`temp  <- fread("check.csv", integer64 = "character") `

I get this warning message:

> In fread("check.csv", integer64 = "character") :
>   Bumped column 2 to type character on data row 10827, field contains '1.8'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; ...
> 

from rows 1 to 10826 the column contains integers and missings.
The row 10827 contain a floating number  1.8   but fread doesn't coerces the column to be numeric but instead coerces it to be character.
I think it shouldn't be like that.

I'm using the latest data.table development version.

I need to use the option because some columns in the big dataset contain long ID numbers.

[check.zip](https://github.com/Rdatatable/data.table/files/900388/check.zip)

**Comment by st-pasha** [comment]
Appears to be fixed in the latest version.
