### ISSUE TITLE
[Doc request] ?rbindlist shouldn't refer to rbind.data.table, which doesn't exist

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2113]
The doc says

> `rbind.data.table` gained a `fill` argument to fill missing columns with `NA` in `v1.9.2`, which allowed for `rbind(...)` binding unequal number of columns.

But there is no `rbind.data.table`. Maybe this instead:

> `rbind(...)` gained a `fill` argument to fill missing columns with `NA` in `v1.9.2`, which allowed for binding unequal number of columns.

I guess this part of the docs will go away in a few version anyway (since it's just explaining history), so no big deal. I did find it confusing, though.

**Comment by nicholaelaw** [comment]
Perhaps, there actually was a `rbind` method for `data.table` in v1.9.2? Like you said, it's history.
