### ISSUE TITLE
Problems with text indexing

### ISSUE THREAD

**Issue by JBreidaks** [Rdatatable/data.table#2114]
I have vector with characters:
y <- c('B','Ā','Č','D','Ē','E')

When I sort using order for vector
y2 <- y[order(y)]
y2

[1] "Ā" "B" "Č" "D" "E" "Ē"
y2 <- data.table(y = y2)

If I make vector as data.table and sort with setkeyv then can not get the same result as y2.

test2 <- data.table(y)
setkeyv(test2, "y")
test2

identical(y2, test2)

Maybe can give some solution for this situation?

**Comment by MichaelChirico** [comment]
I believe this is due to C ordering:

```
sapply(c('B','Ā','Č','D','Ē','E'), utf8ToInt)
#   B   Ā   Č   D   Ē   E 
#  66 256 268  68 274  69 
```

whereas `y[order(y)]` is using locale sorting, C sorting will be according to `utf8ToInt` IINM.

Will add a note to the `setkey` documentation about this.
