### ISSUE TITLE
[FR] `intervalid` could be useful

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#2115]
or `rangeid`...

I see questions that benefit from non-equi joins, but the join seems forced in some cases (due to lack of a function that groups intervals together to generate `ids`). For example, http://stackoverflow.com/q/43106465/559784

@franknarf1's answer is nice.. but it would be much easier to do something like

```r
d[, v := .N, by=intervalid(id, x >= x+30, x <= x+40)][N > 0L]
```

perhaps.. Right now, we can already use `%inrange% (shown below), but I don't see an efficient practical use in most scenarios..

```r
d[, x %inrange% list(x-40, x-30), by=id]
```

since `%inrange%` gets slow with more groups for obvious reasons. With `intervalid`, the logic can be moved to `by` which can be useful for cases like these. 

Just like `rowid` and `rleid` it can be used outside of `[ ...]` as well.

**Comment by arunsrinivasan** [comment]
Here's another: http://stackoverflow.com/a/42836636/559784

**Comment by franknarf1** [comment]
Other `by=` arguments have to have a length of `.N`, the number of rows of `DT[i]`. Would this be different? Seems like it would have to be, since intervals can overlap, etc.

**Comment by arunsrinivasan** [comment]
True. Not sure how/if it can be handled.. just registering the issue for now.
