### ISSUE TITLE
[Request] Print by group

### ISSUE THREAD

**Issue by chochkov** [Rdatatable/data.table#2117]
One of the features I love about data.table is the flexible printing. However, I've been missing the option, for the `data.table.print` to respect a `by=` parameter and to split the output according to the provided grouping.

Here's an example of the requested syntax and output.

    > DT <- data.table(group = seq(1:2), date=rep(as.IDate(paste0('2016-02-0', 1:10)), 100))
    > DT
          group       date
      1:     1 2016-02-01
      2:     2 2016-02-02
      3:     1 2016-02-03
      4:     2 2016-02-04
      5:     1 2016-02-05
      ---
    996:     2 2016-02-06
    997:     1 2016-02-07
    998:     2 2016-02-08
    999:     1 2016-02-09
    1000:     2 2016-02-01
    > print(DT, by=group) # Expected syntax and output:
          group       date
      1:     1 2016-02-01
      2:     1 2016-02-03
      3:     1 2016-02-05
      4:     1 2016-02-07
      5:     1 2016-02-09
      ---
      496:   1 2016-02-09
      497:   1 2016-02-09
      498:   1 2016-02-09
      499:   1 2016-02-09
      500:   1 2016-02-09
      -----
      1:     2 2016-02-02
      2:     2 2016-02-04
      3:     2 2016-02-06
      4:     2 2016-02-08
      5:     2 2016-02-01
      ---
      496:   2 2016-02-09
      497:   2 2016-02-09
      498:   2 2016-02-09
      499:   2 2016-02-09
      500:   2 2016-02-01

**Comment by MichaelChirico** [comment]
there's an outstanding issue about printing options, including one about
grouping, please add this there

**Comment by MichaelChirico** [comment]
for now, it looks like you'd be happy with print(split(DT, by = 'group'))

On Apr 18, 2017 7:51 AM, "Michael Chirico" <michaelchirico4@gmail.com>
wrote:

there's an outstanding issue about printing options, including one about
grouping, please add this there

**Comment by yasen-polyanski** [comment]
I assume this is the one you mean - https://github.com/Rdatatable/data.table/issues/1523 and in fact what I mean is mentioned there already, so I'd close this issue.

**Comment by chochkov** [comment]
I assume this is the one you mean - #1523 and in fact what I mean is mentioned there already, so I'd close this issue.
