### ISSUE TITLE
Latest fread version crashes

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#2139]
Till some days ago I was using
`my <- fread("7z e -y -bso0 -so mydata.7z", stringsAsFactors=F, na.strings=c("", "NA"), colClasses=list(character=1:775))
`
To read data from a compressed file. It worked well.

Today I've upgraded data.table to the latest development version and the same command makes R crash most of the time.

And sometimes works saying
`Read 224320 rows x 775 columns from 0.330GB file in 00:05.748 wall clock time (can be slowed down by any other open apps even if seemingly idle)
`
If I don't use the option `colClasses=list(character=1:775)`  then it works well.
And the message is
```
Reread 224320 rows x 23 columns in 00:00.498
though it reads the 775 columns indeed.
```

I've installed the version in cran and it works again well.

I can't upload my data because it's too big.
I couldn't reproduce the problem with a smaller toy dataset.

**Comment by ProfFancyPants** [comment]
I was having this issue yesterday. I just updated data.table with Matt's latest two commits and it fixed the error for me.

**Comment by skanskan** [comment]
I'll try.
Anyway.

I'm using this method to install it:
install.packages("data.table", type = "source",  repos = "http://Rdatatable.github.io/data.table")

How could I install the version from 3 weeks ago instead?

**Comment by skanskan** [comment]
`my <- fread("mydata.csv", stringsAsFactors=F, na.strings=c("", "NA"), colClasses=list(character=1:775))`

Still crashes for me.
And produces this warning 
`stack imbalance in '$', 28 then 26.`

**Comment by jangorecki** [comment]
@skanskan try `git checkout`, `R CMD build`, `R CMD INSTALL`. Possibly devtools can have some helper for that.

**Comment by st-pasha** [comment]
@skanskan It says "Reread 224320 rows x 23 columns" because it needs to **re**-read only 23 columns out of 775.
Could you check whether the issue still remains with the latest dev version of data.table? If yes, then please provide the output of fread command with `verbose=TRUE` (otherwise there is not enough information to understand the problem).

**Comment by skanskan** [comment]
I'm sorry for the delay.
It seems to be working properly now.

Sometimes I get this strange warning:
```
Warning message:
In if (nh > 1L) tryCatchOne(tryCatchList(expr, names[-nh], parentenv,  :
  closing unused connection 3 ()
```
I hope it's not important.
