### ISSUE TITLE
Merging Issue

### ISSUE THREAD

**Issue by msgoussi** [Rdatatable/data.table#2143]
Dear Mr.
I downloaded data (x) from website and I would like to uniform the countries by y.
After melting and merging I realized that one of the names is repeated.
Please advise.
[New folder.zip](https://github.com/Rdatatable/data.table/files/980764/New.folder.zip)

**Comment by arunsrinivasan** [comment]
Have you read the [support](https://github.com/Rdatatable/data.table/wiki/Support) page? Have you gone through the [vignettes](https://github.com/Rdatatable/data.table/wiki/Getting-started)? Have you read the help file for the functions you're looking for? 

Please ask on StackOverflow or the data.table mailing list with a minimal reproducible example and a clear explanation of your expected result.

As it stands, there's not much that can be done.
