### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by RonRichman** [Rdatatable/data.table#2144]
Can we please add a blog to inform the data.table community of new features and updates? There are so many good things happening that deserve to be getting more airtime and I think a blog would be a good way of disseminating this information.

**Comment by franknarf1** [comment]
Periodically looking at [presentations](https://github.com/Rdatatable/data.table/wiki/Presentations) and the [NEWS](https://github.com/Rdatatable/data.table/blob/master/NEWS.md) is one way to follow it, fyi.

**Comment by RonRichman** [comment]
Agree that is a way. But it is sub-optimal IMHO since you have to actively seek out the information whereas one can hook up a blog to an RSS feed.

**Comment by arunsrinivasan** [comment]
It's a good idea, but that requires *a lot* more time, which is quite hard with full time jobs.

**Comment by jangorecki** [comment]
We have now [stay-up-to-date](https://rdatatable.gitlab.io/data.table/#stay-up-to-date) section on our homepage. No blog there, but I don't think we really need one. IMO NEWS file is detailed enough.
