### ISSUE TITLE
Describe "dot dot prefix" in help text, FAQ and vignette

### ISSUE THREAD

**Issue by Henrik-P** [Rdatatable/data.table#2145]
In [New Features for 1.10.2](https://github.com/Rdatatable/data.table/blob/master/NEWS.md#changes-in-v1102--on-cran-31-jan-2017) the `..` prefix is introduced. However, it is not mentioned in `?data.table`. 

Furthermore, if you do a mistake in your subsetting, as examplified e.g. in [this nice answer](http://stackoverflow.com/questions/41051890/r-data-table-1-10-0-why-does-a-named-column-index-value-not-work-while-a-int/41052245#41052245), an informative error message is generated:

> Error in `[.data.table`(DT, , myCols) : 
>   j (the 2nd argument inside [...]) is a single symbol but column name 'myCols' is not found. Perhaps you intended DT[,..myCols] or DT[,myCols,with=FALSE]. This difference to data.frame is deliberate and explained in FAQ 1.1. 

From the error message one could easily get the impression that `..` is explained in FAQ 1.1. But it's not. 

In the release notes it says that `..` "is experimental", so perhaps this omission is intentional? Still, I think this feature deserves to be described in the help text and FAQ (and in the vignette), possibly with an "experimental" reservation.

**Comment by aryoda** [comment]
See also SO question https://stackoverflow.com/q/45380628/4468078 (Why does “..” work to pass column names in a character vector variable?)

**Comment by mattdowle** [comment]
And it's now FAQ 1.5 anyway too, not 1.1.  Will add this to PR #4408.
