### ISSUE TITLE
[Request] Allow rbindlist(L, idcol = v) for any vector v of matching length

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2159]
I have a list of tables (read from disk) that I want to stack with rbindlist, assigning an id column:

```
library(data.table)
DT = data.table(f_id = 2:3, tab = list(
    data.table(g = 1:2, v = (1:2)*10),
    data.table(g = 3:4, v = (3:4)*10)
))

tabDT = DT[, rbindlist(setNames(tab, f_id), idcol = "f_id")][, f_id := as.integer(f_id) ][]
```

Because my id column is not a character, I need to type it four (!) times and manually coerce it back to the correct class. There are other ways to handle it, but all the ones I can think of are quite clunky, like...

```
tabDT = DT[, rbindlist(tab, idcol = TRUE)][, `:=`(f_id = DT$f_id[.id], .id = NULL)][]
```

So I'd like syntax like this instead:

```
DT[, rbindlist(tab, idcol = f_id, idcol.name = "f_id")]
# or
DT[, rbindlist(tab, idcol = list(f_id = f_id))]
# or
DT[, rbindlist(tab, idcol = f_id)]
# with the name automatically inferred in the last case
```

**Comment by MichaelChirico** [comment]
Agree with this. I swore I had already put up this FR in fact!

**Comment by arunsrinivasan** [comment]
This'd be better implemented with a separate function like `unwrap()`, for example. I remember having an implementation somewhere.. will have to check old local branches..

**Comment by arunsrinivasan** [comment]
Marking this as a dup of https://github.com/Rdatatable/data.table/issues/2146. If you feel strongly that `rbindlist` is the way to go, feel free to reopen and give your thoughts.

**Comment by franknarf1** [comment]
That sounds good. I could get used to a `unnest(DT[, c("f_id", "tab")], id = "f_id")` idiom or whatever. (I'm not familiar with unnest syntax and always keep a single column for an ID.)
