### ISSUE TITLE
fread completely broken: arguments mismatched in C call

### ISSUE THREAD

**Issue by HughParsonage** [Rdatatable/data.table#2166]
In commit 97af8bae6d9e7456069c7d9ec915c55cd0ba35dc it appears that `fread`'s arguments have been misaligned in the C Call:

```r
library(data.table)
fwrite(data.table(x = 1:10), "temp.csv")
fread("temp.csv")
Error in fread("temp.csv") : 
  'integer64' must be a single character string
```

The offending line appears to be:

```
+    warnings2errors = getOption("warn") >= 2
      ans = .Call(CfreadR,input,sep,dec,quote,header,nrows,skip,na.strings,strip.white,blank.lines.skip,
 -                        fill,showProgress,nThread,verbose,select,drop,colClasses,integer64,encoding)
 +                        fill,showProgress,nThread,verbose,warnings2errors,select,drop,colClasses,integer64,encoding)
```

Indeed, 

```r
 fread("temp.csv", colClasses = "integer64")
Error in fread("temp.csv", colClasses = "integer64") : 
  encoding='integer64' invalid. Must be 'unknown', 'Latin-1' or 'UTF-8'
```

and 

```r
fread("temp.csv", colClasses = "integer64", integer64 = "unknown")
Error in fread("temp.csv", colClasses = "integer64", integer64 = "unknown") : 
  Column number 0 (select[1]) is out of range [1,ncol=1]
```

etc.

**Comment by mattdowle** [comment]
I can't reproduce in dev and `fread` is passing lots of tests on Linux and Windows in clean environments.
Are you on Windows and is it possible that an old .dll is hanging around?  Try purging data.table and reinstalling after a Windows reboot.
Or possibly `getOption("datatable.integer64")` has been set incorrectly in `.Rprofle` or similar?  To rule that out, try with `R --vanilla`.

**Comment by HughParsonage** [comment]
You're right. I apologize. I overlooked a background R process on another user.
