### ISSUE TITLE
fread does not close UTF-8 input file with byte order mark on Linux

### ISSUE THREAD

**Issue by akersting** [Rdatatable/data.table#2168]
To reproduce the issue first create a UTF-8 file with BOM:
`echo -ne '\xEF\xBB\xBF' > test_utf8.csv && echo "hello,world" | iconv -t UTF-8 >> test_utf8.csv`

Now start an interactive R session and read the file using fread:
`data.table::fread("test_utf8.csv")`

After the successful read, in another terminal and without closing the R session run
`lsof -p XXX | grep test_utf8`
where XXX is the PID of the R process, which shows
`R       90895 askers  mem    REG 202,145       15 10879439 /home/askers/test_utf8.csv`

For me this does not happen for ASCII files or for UTF-8 files without BOM.

I've noticed this issue when reading dozens of large zipped files one at a time, first unzipping them to a temporary directory, then reading those temporary files using fread and then deleting them. After a while I would run out of space on my /tmp partition because the space of the deleted files was not released due to them still being opened by fread / the R process. `df` would report the partition as completely full while `du` would show it as nearly empty.

**Comment by akersting** [comment]
I forgot: my data.table version is 1.10.4.

**Comment by MichaelChirico** [comment]
please test on development, I know there was a recent commit addressing BOM (though I'm not sure it covers this case)

**Comment by akersting** [comment]
The issue indeed seems to be fixed on develop, probably by #2084.
