### ISSUE TITLE
Performance of unique applied to j question

### ISSUE THREAD

**Issue by scottstanfield** [Rdatatable/data.table#2184]
I've been curious about the performance of `unique` over a vector or tuple over J or over the return of the datatable when J is returned as a vector. 

With this simple, contrived example, the delta in performance time is over 10x. I *prefer* the syntax with `unique()` inside J, but it's clearly slower. Am I missing a concept here? For now I'll keep it outside, but just curious as to why.

![image](https://cloud.githubusercontent.com/assets/280700/26755055/a6345668-483a-11e7-9774-5cb751f40fb0.png)

```
library(data.table)
library(microbenchmark)

dt <- data.table(a=round(runif(1000)*1000, 0))
t <- microbenchmark(
  inside  = length(dt[, unique(a)]),
  outside = length(unique(dt$a)),
  times = 100
)
print(t)
```

**Comment by scottstanfield** [comment]
Ok, I tried this on a non-trivial sized data.table, and using `unique` wrapped around J is *faster*. 

Details: 3M rows x 456 columns (about 2GB in-memory). Used `setkey` around a 3-column tuple consisting of a two ints and a factor...

The same benchmark above on the count of unique tuples is μ=30 on "inside" and μ=50 "outside". 

So basically, data.table continues to kick ass.

At this point, just curious what the idiomatic way should be. I'm going with "inside" for now.

**Comment by franknarf1** [comment]
The idiomatic way is `uniqueN`, though it's currently not faster, as noted in https://github.com/Rdatatable/data.table/issues/1120 

```
library(data.table)
library(microbenchmark)

dt <- data.table(a=round(runif(1000)*1000, 0))
t <- microbenchmark(
  inside  = length(dt[, unique(a)]),
  outside = length(unique(dt$a)),
  uN      = uniqueN(dt$a),
  uN2     = uniqueN(dt, by="a"),
  times = 10
)
print(t)

Unit: microseconds
    expr     min      lq     mean   median      uq     max neval
  inside 190.837 195.491 205.8552 203.8690 208.834 243.898    10
 outside  34.754  38.167  43.6286  39.0985  48.717  66.095    10
      uN  52.442  55.545  64.6986  60.6645  67.957 102.711    10
     uN2  46.545  51.200  56.8168  56.7860  59.268  76.645    10
```

**Comment by scottstanfield** [comment]
Ah: I realize I've mixed two operations here. The first being `unique`, which can be applied to a vector or list. The second being `length`. 

I can see that the special case of finding the length of a unique vector, then `uniqueN()` should be used. Cool.
