### ISSUE TITLE
dt[, uniqueN(col)] does not warn when `col` is evaluated outside of dt's frame

### ISSUE THREAD

**Issue by mbacou** [Rdatatable/data.table#2186]
Hi, the very simple code below returns `20` without warning. This is potentially very error-prone, when the user would normally expect a column named `v` in `dt`, but that column is accidentally missing. Not sure if this is intended. Thx!

Tested with data.table 1.10.4.

```r
v <- 1:20
dt <- data.table(a=1:10, b=1:10)
dt[, uniqueN(v)]
# [1] 20
```

**Comment by MichaelChirico** [comment]
I don't think this is anything particular to uniqueN, or even data.table
for that matter -- standard R behavior of ascending call scope to find
variables, no?

**Comment by mbacou** [comment]
Yes and no, `data.frame` would throw an error obviously. Generally, it seems to me that evaluation in ascending scope in `j`'s element is very prone to user errors. Somehow I feel like forcing the user to make an explicit call to an out-of-scope object would be safer (e.g. maybe using something like `..(v)`.

**Comment by MichaelChirico** [comment]
maybe... OTOH there's no error/warning in

x = 5
f = function(y) x+5
f(0)

How/why should that differ for a [] call? the default behavior of setting
with=TRUE is well documented in introductory vignettes... and personally I
rely on occasionally referring to up-the-scope variables intentionally for
clean code (essentially referring to "global" variables). would be strange
to get a warning in such cases.

**Comment by franknarf1** [comment]
I think the proposed `inherits = FALSE` would cover this https://github.com/Rdatatable/data.table/issues/633 and agree it would be nice to have.

**Comment by mbacou** [comment]
I agree here, `inherits = FALSE` should be default behavior, with an explicit `..(col1, col2)` notation possibly allowed.

**Comment by arunsrinivasan** [comment]
As @franknarf1 pointed out, it's a nice feature to have, and is a dup of #633.
