### ISSUE TITLE
Wrong source link

### ISSUE THREAD

**Issue by akhst7** [Rdatatable/data.table#2190]
Hi, 

Could you update the source link in the Installation page ? 

`http://Rdatatable.github.io/data.table` 

Thanks.

**Comment by MichaelChirico** [comment]
It's not clear what link you're referring to. a quick glance shows indeed
the correct link is cited on the installation page.

Anyway, the installation page is a wiki. Please feel free to update it
yourself.

**Comment by akhst7** [comment]
By clicking the following link to the repor src page I listed in the new issue,  I get a 404, file not found error.  

install.packages("data.table", type = "source",
    repos = "http://Rdatatable.github.io/data.table")

**Comment by MichaelChirico** [comment]
it's not a website you can visit. are you getting the error when running
the install.packages command as instructed?

**Comment by akhst7** [comment]
Actually, It worked third time for some reasons.  It was probably the typo somewhere I did not realize. 


Thanks.
