### ISSUE TITLE
[Request] join on=.(sign(v) = v_sign)

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2203]
I have a table with a lot of distinct values in a set of variables (`g` and `v` below). I have some rules for mapping these to a smaller number of values, encapsulated in the `mDT` table below:

```
library(data.table)
DT = data.table(id = 1:5, g = "gah", v = c(-4, NA, 3, 1, 1))
#    id   g  v
# 1:  1 gah -4
# 2:  2 gah NA
# 3:  3 gah  3
# 4:  4 gah  1
# 5:  5 gah  1

mDT = data.table(g= "gah", v_sign = c(-1, NA, 1), x = LETTERS[1:3])
#      g v_sign x
# 1: gah     -1 A
# 2: gah     NA B
# 3: gah      1 C
```

The idea is to assign rows based on `g` and `sign(v)` in `DT`. In principle, I could write all values of `v` in `mDT` and do an equi-join, but then I would not be able to browse `mDT` and be sure it's doing what I want. Instead, I would like to join directly on `mDT$v_sign`.

```
# desired syntax
DT[mDT, on=.(g, v %signmatch% v_sign), x := i.x ]
# or
DT[mDT, on=.(g, sign(v) = v_sign), x := i.x ]

# workaround
mDT[, vm := c(-Inf, NA, 0)]
DT[, x := mDT[DT, on=.(g, vm = v), roll=TRUE, x.x ]][]

#    id cat  v x
# 1:  1 gah -4 A
# 2:  2 gah NA B
# 3:  3 gah  3 C
# 4:  4 gah  1 C
# 5:  5 gah  1 C
```

My workaround shown above is fine for my current case, but if more than one such var were involved, I wouldn't be able to use `roll` for all of them.

I realize this is probably a very niche concern, but it seems doable in principle. In my real use-case, I have four messy string variables instead of just `g`, for 2300 rows in `mDT` when using `sign(v)` or 7400 if I instead use distinct values of `v`.

**Comment by MichaelChirico** [comment]
@franknarf1  is this subsumed by #1639?

**Comment by franknarf1** [comment]
@MichaelChirico I think so, thanks
