### ISSUE TITLE
[Doc request] add quote/eval/substitute guidance back to FAQ

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2209]
Elevating [my comment](https://github.com/Rdatatable/data.table/issues/1936#issuecomment-281465037) to a request. I just saw this brought up [on SO again today](https://stackoverflow.com/questions/44632867/passing-columns-in-a-variable-dynamically-when-aggregating-in-data-table) and it seems to come up frequently.

Here is [the old version](https://github.com/Rdatatable/data.table/blob/c682d7e55dcc4b430d69a4e68b5cbbeb44889734/vignettes/datatable-faq.Rmd), for reference:

> 1.6 OK, but I don't know the expressions in advance. How do I programatically pass them in?
> 
> To create expressions use the `quote()` function. We refer to these as `quote()`-ed expressions to
> save confusion with the double quotes used to create a character vector such as `c("x")`. The simplest `quote()`-ed expression is just one column name:
> 
> ```{r}
> DT = data.table(x = 1:3)
> q = quote(x)
> 
> #return a vector
> DT[ , eval(q)]
> 
> q = quote(list(x))
> 
> #return a one-column 'data.table'
> DT[ , eval(q)]
> ```
> 
> Since these are _expressions_, we are not restricted to column names only:
> 
> ```{r}
> q = quote(mean(x))
> DT[ , eval(q)]  # identical to 'DT[ , mean(x)]'
> 
> DT = data.table(x = 1:3, y = 4:6, z = 7:9)
> q = quote(list(x, sd(y), mean(y*z)))
> DT[ , eval(q)]  # identical to 'DT[ , list(x, sd(y), mean(y*z))]'
> ```
> 
> However, if it's just simply a vector of column names you need, it may be simpler to pass a character vector to `j` and use `with = FALSE`.
> 
> To pass an expression into your own function, one idiom is as follows:
> 
> ```{r}
> DT = as.data.table(iris)
> setkey(DT, Species)
> myfunction = function(dt, expr) {
>     e = substitute(expr)
>     dt[ , eval(e), by = Species]
> }
> myfunction(DT, sum(Sepal.Width))
> ```
> 
> `quote()` and `eval()` are like macros in other languages. Instead of `j = myfunction()` (which won't work without laboriously passing in all the arguments) it's `j = eval(mymacro)`. This can be more efficient than a function call, and convenient. When `data.table` sees `j = eval(mymacro)` it knows to find `mymacro` in calling scope so as not to be tripped up if a column name happens to be called `mymacro`, too.
> 
> For example, let's make sure that exactly the same `j` is run for a set of different grouping criteria :
> 
> ```{r}
> DT = as.data.table(iris)
> whatToRun = quote( .(AvgWidth = mean(Sepal.Width),
>                      MaxLength = max(Sepal.Length)) )
> DT[, eval(whatToRun), by = Species]
> DT[, eval(whatToRun), by = .(FirstLetter = substring(Species, 1, 1))]
> DT[, eval(whatToRun), by = .(Petal.Width = round(Petal.Width, 0))]
> ```

If I can figure out how to make a PR, I might try to tackle this. It looks to me like just the first part (that mentions column names and `with = FALSE`) needs updating. Elsewhere in the FAQ, `..var` could also be added.

**Comment by Henrik-P** [comment]
Regarding the last sentence in this issue, please see also [[Documentation] Describe "dot dot prefix" in help text, FAQ and vignette](https://github.com/Rdatatable/data.table/issues/2145)

**Comment by jangorecki** [comment]
I think this issue will be well covered by #4247, closing as duplicate
