### ISSUE TITLE
Bug? Named logical vectors don't select rows as expected

### ISSUE THREAD

**Issue by skranz** [Rdatatable/data.table#2210]
I just found a bug in one of my packages that arises because data.table does not select rows, with a named logical vector as I had expected. See this example:

```r
> library(data.table)
> dt = data.table(x=1,y=2)
> 
> # unexpected behavior: named logical vector does not select the first row
> named.ind = c("myind"=TRUE)
> named.ind
myind 
 TRUE 
> dt[named.ind,]
Empty data.table (0 rows) of 2 cols: x,y
> 
> # an unnamed logical vector works as expected
> unnamed.ind = c(TRUE)
> unnamed.ind
[1] TRUE
> dt[unnamed.ind,]
   x y
1: 1 2

> # named logicals works with data.frames as expected
> df = as.data.frame(dt)
> df[named.ind,]
  x y
1 1 2
```
Maybe that is a feature of data.table, which I just overlooked. Then sorry for opening up this issue. But since I never encountered the issue before, I thought maybe that is a bug that sneaked into a new data.table version. I am using version 1.10.4 of data.table.

**Comment by jangorecki** [comment]
duplicated of #2152
