### ISSUE TITLE
fread on particular file crashes R

### ISSUE THREAD

**Issue by cnoelke** [Rdatatable/data.table#2228]
Looks very similar to #2167, I have a file that crashes R if read with fread. Very similar files do not have this problem. read.csv works fine with this file.

The file is a csv (renamed to .txt to upload).

df <- read.csv("session_aborted_fatal_error.txt", header=F) 
dt <- fread("session_aborted_fatal_error.txt", header=F, verbose = TRUE)

Thanks!

[session_aborted_fatal_error.txt](https://github.com/Rdatatable/data.table/files/1112755/session_aborted_fatal_error.txt)

![image](https://user-images.githubusercontent.com/29780821/27698804-2c34774e-5cc6-11e7-9260-0a2e528bb71f.png)

**Comment by MichaelChirico** [comment]
please run this from the command line to get a tad more feedback about how R crashed

**Comment by cnoelke** [comment]
Sorry, is this better:

![image](https://user-images.githubusercontent.com/29780821/27699211-87e1d0d6-5cc7-11e7-8374-f961cbfb8e4d.png)

**Comment by MichaelChirico** [comment]
no, this:

```
library(data.table)
# data.table 1.10.5 IN DEVELOPMENT built 2017-06-07 23:18:40 UTC; travis
#   The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
#   Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
#   Release notes, videos and slides: http://r-datatable.com
fread('~/Downloads/session_aborted_fatal_error.txt')

#  *** caught bus error ***
# address 0x7f8e627ee000, cause 'non-existent physical address'

# Traceback:
#  1: fread("~/Downloads/session_aborted_fatal_error.txt")
```

**Comment by cnoelke** [comment]
Sorry, not sure what you mean. I'm running this on Windows RStudio. I can run the script from the Windows command line, but the output is identical to what RStudio produces.

![image](https://user-images.githubusercontent.com/29780821/27700199-d8d1bdbe-5cca-11e7-9192-ed4c245b064d.png)

Thanks!

**Comment by st-pasha** [comment]
This looks like an instance of #2194
A fix already exists, waiting to be merged.

**Comment by mattdowle** [comment]
Many thanks @cnoelke.  Your file now added to the test suite.

**Comment by brankokovac** [comment]
I have the same problem with loading one particular file with fread().

Here is the error file: [session_aborted_fatal_error.txt](https://github.com/Rdatatable/data.table/files/1333139/session_aborted_fatal_error.txt)

**Comment by e-nascimento** [comment]
Hello,

It has been awhile since this closed, but I am facing the same issue on R version 4.1.0 (2021-05-18)
I could isolate the issue.

# RStudio crashes if you try to read row 183131
DT <- fread(file = "file.csv", sep = ";", fill = T, verbose = T, nrows = 183130)

[file.zip](https://github.com/Rdatatable/data.table/files/6640252/file.zip)

**Comment by jangorecki** [comment]
If it is not the same file then I think it make sense to file a new issue
