### ISSUE TITLE
fread object 'CfreadR' not found

### ISSUE THREAD

**Issue by SamoPP** [Rdatatable/data.table#2237]
> library(data.table)
data.table 1.10.5 IN DEVELOPMENT built 2017-07-01 10:01:24 UTC
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com
> 
> fread("D:/DataExport/SPY.txt")
Error in fread("D:/DataExport/SPY.txt") : object 'CfreadR' not found
> 
> head(read.csv("D:/DataExport/SPY.txt"))
        Date   Open   High    Low  Close  Volume OI     Aux1 Aux2     oc      ov MemberOfSPX MemberOfRUI MemberOfRUT MemberOfRUA
1 1993-01-29 44.000 44.000 43.750 44.000 1003200  0 44078100    0 44.000 1003200           0           0           0           0
2 1993-02-01 44.000 44.250 44.000 44.250  480500  0 21262100    0 44.250  480500           0           0           0           0
3 1993-02-02 44.250 44.375 44.125 44.375  201300  0  8926400    0 44.375  201300           0           0           0           0
4 1993-02-03 44.375 44.875 44.375 44.750  529400  0 23723700    0 44.750  529400           0           0           0           0
5 1993-02-04 45.000 45.125 44.875 45.000  531500  0 23917500    0 45.000  531500           0           0           0           0
6 1993-02-05 45.000 45.000 44.750 45.000  492100  0 22129100    0 45.000  492100           0           0           0           0
  MemberOfRMC MemberOfRUMIC MemberOfOEX MemberOfMID MemberOfSML MemberOfSP1500 MemberOfDJI MemberOfNDX OrdinaryDividends SpecialDividends
1           0             0           0           0           0              0           0           0                 0                0
2           0             0           0           0           0              0           0           0                 0                0
3           0             0           0           0           0              0           0           0                 0                0
4           0             0           0           0           0              0           0           0                 0                0
5           0             0           0           0           0              0           0           0                 0                0
6           0             0           0           0           0              0           0           0                 0                0
  TotalDividends
1             NA
2             NA
3             NA
4             NA
5             NA
6             NA
> 
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.5

loaded via a namespace (and not attached):
[1] tools_3.3.3

**Comment by m-dz** [comment]
Have encountered the same error with:
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
data.table_1.10.5

**Comment by mattdowle** [comment]
This is very likely an installation problem on Windows.  We see similar quite regularly on Windows, but never on Linux or Mac.

Please run `test.data.table()`.   That will probably fail too and confirms that data.table is not installed properly.

Please reboot Windows to release all it's locks it holds on .dlls and similar.  Then reinstall data.table and try again.

**Comment by mattdowle** [comment]
@SamoPP Could you confirm please.
@m-dz Could you confirm please.

**Comment by mattdowle** [comment]
Assumed installation issue on Windows.  Closed as no response.
Significant improvements made to Windows instructions here: https://github.com/Rdatatable/data.table/wiki/Installation#windows
