### ISSUE TITLE
fread is inconsistent in treating quoted fields

### ISSUE THREAD

**Issue by st-pasha** [Rdatatable/data.table#2259]
Currently **Quote Rule 0** says 
> Fields may be quoted, any quote inside the field is doubled.

However what I believe it should be saying is
> A field may or may not be quoted. If there are any separators, quotation marks, or newlines inside the field, then it *must* be quoted. Inside a quoted field all quotations marks are doubled.

The difference here is that currently a field such as `hello "world"` is admissible under QR0, whereas I believe that it shouldn't. Instead, if there are any quotation marks inside the field, then such field *must* be quoted, and all quotes inside doubled: `"hello ""world"""`, as dictated by the CSV standard.

**Comment by pliptor** [comment]
I wonder if that's the reason I don't get consistent results compared with the base package. Attached is
a sample csv file to reproduce the result.

``
> a <- read.csv("test.csv", as.is=T)
> a
      Desc Type
1     ABBA    1
2 z  ddd w    2
> library(data.table)
data.table 1.10.4
> b <- fread("test.csv")
> b
         Desc Type
1:     A"BB"A    1
2: z  "ddd" w    2
> a$Desc==b$Desc
[1] FALSE FALSE
``
[test.txt](https://github.com/Rdatatable/data.table/files/1219999/test.txt)
