### ISSUE TITLE
Add `ezknitr` to cedta.pkgEvalsUserCode

### ISSUE THREAD

**Issue by mattmills49** [Rdatatable/data.table#2266]
[ezknitr](https://cran.r-project.org/web/packages/ezknitr/index.html) is a package that helps with using `knitr`'s `knit` and `spin` functions that I use frequently in combination with `ProjectTemplate` project directories. When using the `data.table` package in my scripts I received the "cedta decided 'ezknitr' wasn't data.table aware" message when attempting to spin the script with the `datatable.verbose` option set to TRUE. I was able to fix this by running the `assignInNamespace("cedta.pkgEvalsUserCode", c(data.table:::cedta.pkgEvalsUserCode,"ezknitr"), "data.table")` command but was wondering if `ezknitr` could be added to the default packages to be excluded in the [cedta.R](https://github.com/Rdatatable/data.table/blob/master/R/cedta.R) file? If not then that's fine, at least I know how to avoid this error in the future.

**Comment by mattdowle** [comment]
Many thanks.  Yes will add.
Related: https://stackoverflow.com/a/13131555/403310

**Comment by cderv** [comment]
@mattdowle, you could find some answers in this [blogpost](http://deanattali.com/blog/ezknitr-package/)
