### ISSUE TITLE
Modifications to one table appears into another.

### ISSUE THREAD

**Issue by EdvinasD** [Rdatatable/data.table#2271]
Hello,

I think I encountered a bug, or at least behavior which I didn't expect. If I create a`data.table` called `dat` and then create `dat2` based on the `dat` and modify it, modifications also appear in the original `dat`.

>library(data.table)
data.table 1.10.4

> dat <- data.table(data.frame(x=c(1,2,1,3,4),y=c(1,2,1,3,4)))
> dat2 <- dat
> dat2[,c("y"):=rep(5,5)]
> dat
   x y
1: 1 5
2: 2 5
3: 1 5
4: 3 5
5: 4 5
> dat2
   x y
1: 1 5
2: 2 5
3: 1 5
4: 3 5
5: 4 5

assigning like this, fixes problem 
>dat2 <- data.table(dat)

And my session info:
R version 3.3.2 (2016-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4

loaded via a namespace (and not attached):
[1] tools_3.3.2
Thank You. 

Best,
Edvinas

**Comment by MichaelChirico** [comment]
this is well documented behavior. search for "copy reference data.table"
and read the beginner's vignette, wiki, and FAQ.

**Comment by Henrik-P** [comment]
See e.g. [Reference semantics](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-reference-semantics.html), part **3) := and copy()**

Relevant SO Q&A: [Understanding exactly when a data.table is a reference to (vs a copy of) another data.table](https://stackoverflow.com/questions/10225098/understanding-exactly-when-a-data-table-is-a-reference-to-vs-a-copy-of-another).

**Comment by EdvinasD** [comment]
Thank you a lot, now I get :)
