### ISSUE TITLE
How to contribute to fix 9218868437227407266?

### ISSUE THREAD

**Issue by pachamaltese** [Rdatatable/data.table#2274]
Hi 

I read fixing 9218868437227407266 vs NA "bug" needs extensive C coding not to break performance.

How can I help? I'm using data.table(v.1.10.4) and the problem persists as in older versions.

**Comment by MichaelChirico** [comment]
First, be sure to check the bug still exists in development. See the installation page:

https://github.com/Rdatatable/data.table/wiki/Installation

Assuming the issue still exists, search the issue tracker to find the bug report that already exists (IIRC it's been reported already)

Finally, hack away, being sure to follow the contribution guidelines & file a pull request:

**Comment by jangorecki** [comment]
@pachamaltese could you provide reproducible example?
