### ISSUE TITLE
cheat sheets with latest features / commands

### ISSUE THREAD

**Issue by sdaza** [Rdatatable/data.table#2286]
Hello, 
It's hard for me to track of the great changes / new features data.table keep adding. Is there exists a sheet summarizing new (all) data.table features (e.g. %like%, .. ) I can look at?

**Comment by franknarf1** [comment]
The [front page](https://github.com/Rdatatable/data.table/wiki) has a bulleted list; there is a somewhat outdated cheat sheet on the [getting started page](https://github.com/Rdatatable/data.table/wiki/Getting-started); but for the latest, you'll want to follow [the release notes](https://github.com/Rdatatable/data.table/blob/master/NEWS.md).

For a full list of features and functions, type...

```
help(package = "data.table")
```

**Comment by sdaza** [comment]
Yes, I review the release notes. I am just thinking on an easier and more systematic way to get the new features.

**Comment by MichaelChirico** [comment]
It's hard to imagine an easier/more systematic approach than following https://github.com/Rdatatable/data.table/blob/master/NEWS.md

You can also try and follow the maintainers on Twitter but that's not systematic (I try and post for major features but am not too consistent):

https://twitter.com/michael_chirico
https://twitter.com/MattDowle
https://twitter.com/rdatatable
