### ISSUE TITLE
Problem with empty data.table in set()

### ISSUE THREAD

**Issue by nicholaelaw** [Rdatatable/data.table#2294]
Hi there, I've encountered a problem to which I have found no answers on the web. Perhaps I'm doing it wrong?

I have a master record of say, payments. I have to derive some historical data from it by looping through a  set of date ranges. So for some `i`, I'm using the following code to calculate the statistics and storing it in a  predefined `data.table`:

```r
data.table::set(
  result, i, 1L:10L, 
  value = temp[
    date %between% this_day,
    .(stat1 = something, stat2 = something, ...)
  ]
```

Problem is, sometimes `temp[date %between% this_day, ...]` would return an empty `data.table`, and then `set` would complain about RHS being of 0 length and not `NULL`. And the loop breaks down.

I know no easy and cheap way to check this condition, short of calling `temp[date %between% this_day, .N]` before `set`. So I would prefer that when there is no match, the statement `temp[date %between% this_day, ...]` would simply return a data.table with a single row where every column is zero. Or NA. Or anything other than empty.

Am I doing it wrong? Is there a way to handle the empty data.table situation in `set`? I've since found a workaround by doing

```r
value = as.list(temp[
  date %between% this_day,
  c(stat1 = something, stat2 = something, ...)
])
```

But is it the intended way?

**Comment by jangorecki** [comment]
You can use `j = if (.N > 0) ... else ...`. Also "empty data.table" is not equal to "0-row data.table" which I believe you had in mind. Generally this type of questions should goes into SO or mailing lists, not github issue. Please re-open if you think there is issue/bug/gap for new feature.

**Comment by nicholaelaw** [comment]
Well I used 'empty data.table' only because the error message used it: '... empty data.table (0 rows): ...' .

I will go ask around on SO then.

**Comment by jangorecki** [comment]
@nicholaelaw you are right, empty is ambiguous here. Just look for examples of `if (.N > 0) ... else ...`.
