### ISSUE TITLE
[Question] Is Rtools installation on Windows deprecated?

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2304]
I noticed that there are now only instructions for binaries on [the wiki page](https://github.com/Rdatatable/data.table/wiki/Installation). The binary way is very nice to have, but it still seems to work fine via the Rtools route. Will it continue to work and is there a reason I should switch from using Rtools for this? 

(Sorry if it's a dumb question.)

**Comment by jangorecki** [comment]
Rtools route will always work as it is the way that R packages meant to be compiled on windows. If we would stop supporting it our package wouldn't build on R windows platforms.
