### ISSUE TITLE
accessing .SD via data.table::.SD gives NULL

### ISSUE THREAD

**Issue by spennihana** [Rdatatable/data.table#2306]
I wasn't able to find an answer to this via searching SO/issues, so I'll just ask:

Is this legal way of accessing .SD:

```
someFun <- function(dt) {
  stopifnot(!is.null(dt))
  5
}

r <- data.table::data.table(iris)
r[ , someFun(data.table::.SD)    # Not OK
   , by=.(Sepal.Length)
 ]

# Error: !is.null(dt) is not TRUE

r[ , someFun(.SD)     # OK
   , by=.(Sepal.Length)
 ]
``` 

In `someFun`, the arg `dt` is NULL. Not a huge pain since I can do an explicit package import, but curious never-the-less.

edit: fixed up example

**Comment by MichaelChirico** [comment]
no, it's not a legal way of accessing .SD. the object is created within the
[] call; it's not an exported object.

**Comment by spennihana** [comment]
Thanks for your response; it's still bothersome that there's no way of telling data.table to get the groups without explicitly importing the package.

At first I was confused by what you meant by "not exported" (https://github.com/Rdatatable/data.table/blob/master/NAMESPACE#L27), but I see that you mean it's built on-the-fly.

I want to import and use data.table in this way, without explicitly setting it in my DESCRIPTION:depends. Any trick here?

**Comment by MichaelChirico** [comment]
why not just import it? using data.table without importing the C code is
bound to end poorly.

**Comment by spennihana** [comment]
when developing a package id like to access via the package namespace. Among other things it avoids noisy startup messages that I don't want to appear.

**Comment by jangorecki** [comment]
@spennihana did you tried just `.SD`? You have to put to imports/depends every package that you use by `::`, you don't have to import its functions or attach to search path. Unless you escape that function call with something like `requireNamespace`, then Suggests is enough.

**Comment by spennihana** [comment]
Tried bare `.SD` too, no luck.

It is desirable for all packages to be in Imports. I do not want them in Depends.

Yes, this R package is following a strict style of `<pkg>::<fn>`. But then I came across the current issue. I could look at `requireNamespace` to special-case data.table as a way of muting the startup messages; but it's unfortunate that this needs special handling...

**Comment by spennihana** [comment]
Actually, I got a hint on how to handle this from Matt via: https://github.com/Rdatatable/data.table/issues/850

I will set these to NULL just before usage.

Thanks!

**Comment by f2ostie** [comment]
I'm having the same issue. Could somebody elaborate on the solution?

I imported `data.table` in the `DESCRIPTION`:
```
Imports:
  data.table (>= 1.10.0),
	RODBC (>= 1.3.0)
```
but
```
  r <- data.table::data.table(iris)
  r[ , print(.SD), by=.(Sepal.Length)]
```
just prints` NULL`.

Tried setting `.SD` to `NULL` before function to no avail.
```
 r <- data.table::data.table(iris)
.SD <- NULL
r[ , print(.SD), by=.(Sepal.Length)]
```
Can anybody fix my example? (Tried `data.table::.SD` but gave same result)

**Comment by HughParsonage** [comment]
Have you imported `data.table` to your package's NAMESPACE?

**Comment by f2ostie** [comment]
I have done that now and it indeed works, thanks!

**Comment by MichaelChirico** [comment]
@f2ostie  see also the new vignette:

https://github.com/Rdatatable/data.table/blob/master/vignettes/datatable-importing.Rmd

**Comment by jangorecki** [comment]
html version: https://rdatatable.gitlab.io/data.table/library/data.table/doc/datatable-importing.html
