### ISSUE TITLE
Aggregate function giving incorrect results using indexing

### ISSUE THREAD

**Issue by Balter85** [Rdatatable/data.table#2309]
Hi,  I don't usually post on github and I'm just learning data.table through the vingettes.  Great package.  But I found something I believe to be a bug.  Forgive me if this has already been brought up or I'm doing something wrong.

Using the flights dataset from the vingette:
`flights[origin == 'LGA' & dest == 'TPA', mean(arr_delay), by = month]`
    month         V1
 1:     1 21.9570552
 2:     2 11.3742331
 3:     3  3.0373832
 4:     4 -0.1095238
 5:     5  6.8539326
 6:     6  4.7650273
 7:     7 19.1884817
 8:     8 -1.8556701
 9:     9 -3.7546012
10:    10 -8.5906736

As expected.  But doing the same thing uses indexes does not return the correct results for the month column.

`flights[.('LGA','TPA'), mean(arr_delay), on = c('origin','dest'),by = month]`
    month         V1
 1:     1 21.9570552
 2:     1 11.3742331
 3:     1  3.0373832
 4:     1 -0.1095238
 5:     1  6.8539326
 6:     1  4.7650273
 7:     1 19.1884817
 8:     1 -1.8556701
 9:     1 -3.7546012
10:     1 -8.5906736

Thanks.

**Comment by Balter85** [comment]
Saw this issue was previously noted.

**Comment by MichaelChirico** [comment]
Hey @Balter85, could you cite the related issue you found? Others may end up here for one reason or another and not know where to turn. Thanks!

**Comment by Balter85** [comment]
Sure.

https://github.com/Rdatatable/data.table/issues/1943
