### ISSUE TITLE
[Question] Warning : Invalid .internal.selfref

### ISSUE THREAD

**Issue by FingerDrill** [Rdatatable/data.table#2310]
I used code to add a new column.
I can't give you reproducible data(kaggle competition), but it is very simple code.

```
trans  <- fread(paste0(data_path, "train_2016_v2.csv"))
setkey(trans, parcelid)
trans <- trans %>% 
  rename(id_parcel = parcelid,
         date_transaction = transactiondate)
trans[, date_transaction := as.Date(date_transaction)]
trans[, logerror_abs := abs(logerror)]
```

This makes an warning in last line :
> Warning message:
> In `[.data.table`(trans, , `:=`(logerror_abs, abs(logerror))) :
>   Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or been created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting. If this message doesn't help, please report to datatable-help so the root cause can be fixed. 
> 

I know other function to do same thing like 
`trans <- trans %>% mutate(logerror_abs = abs(logerror))`
But I'm trying to use data.table for it's fast speed but this warning makes me unhappy.

What's wrong?

**Comment by FingerDrill** [comment]
OK, I know that 'rename' function with dplyr makes this warning.
It seems to be happened by key, names, attr functions copying DT.
If I'm wrong, comment pls.

**Comment by jangorecki** [comment]
@FingerDrill I don't know about `rename` behaviour but you can do something like this:
```r
trans <- fread(paste0(data_path, "train_2016_v2.csv"))
setnames(trans, c("transactiondate","parcelid"), c("date_transaction","id_parcel"))
setkey(trans, id_parcel)
```
Your code will still be very verbose. If you want to have compact code you can set key using `keyby = .(id_parcel = parcelid)` and rename column in `j` the same way.

**Comment by franknarf1** [comment]
> OK, I know that 'rename' function with dplyr makes this warning.
> It seems to be happened by key, names, attr functions copying DT.
> If I'm wrong, comment pls.

Regarding `rename`, try it with dtplyr (the package that is designed to support data.table with dplyr) and if it doesn't work, maybe file an issue/request with hadley: https://github.com/hadley/dtplyr

Fwiw, I think it's better to stick to one syntax or the other. Also, `fread` has a `key=` option.
