### ISSUE TITLE
dot list alias doesn't work with `between`

### ISSUE THREAD

**Issue by Henrik-P** [Rdatatable/data.table#2315]
From `?between`:
    
    X = data.table(a = 1:5, b = 6:10, c = c(5:1)) 
    X[c %between% list(a, b)]

`list` can't be replaced by `.( )` here: 
    
    X[c %between% .(a, b)]
    # Error in .(a, b) : could not find function "."

**Comment by MichaelChirico** [comment]
I think . is only interpreted in the j clause, and when it's the only thing
in i... you're right that this probably deserves explication in a help
page, perhaps we should add an Rd for ?"."

**Comment by franknarf1** [comment]
@MichaelChirico Of course, it's available in the `i`, `on` and `by` clauses as well. I kind of expect it to work throughout `i` and `j`, no matter the form of the expression, anyways. I have a somewhat related SO post https://stackoverflow.com/questions/41228076/using-data-tables-shortcut-in-quoted-expressions

**Comment by MichaelChirico** [comment]
speaking off the cuff here, you're more correct. and i agree it'd be nice
to have everywhere

**Comment by Henrik-P** [comment]
Yes, the help text may possibly be clearer on the use of `.( )`. Currently, it is explicitly described in `j` ("The expression `.()` is a shorthand alias to `list()`"), but it appears in `i`, `on` and `by` as well. Given that it seems to work "everywhere", I just gave it a try in `i` with `between`.

**Comment by Henrik-P** [comment]
Just to provide a small background if considering an update of the help text and/or usage of `.()`

Currently, `.( )` is (more or less) explicitly described in:

- Explicit in the **Arguments** section of `j`:
>"The expression `.()` is a shorthand alias to `list()`")
- Slightly less explicit in the **Arguments** section of `by`: 
>a `list()` of expressions of column names: e.g., `DT[, .(sa=sum(a)), by=.(x=x>0, y)]`
- Slightly less explicit in the **Arguments** section of `on`: 
>also possible to use `.() syntax as X[Y, on=.(a, b)]`
- First `j` **Examples**
>`DT[, .(v)]`  # same as above, `.()` is a shorthand alias to `list()`
- Quite far down among the `i` **Examples**
> `kDT[.("a")]`    # same, `.()` is an alias for `list()`

Some thoughts:
1. Given the frequent use of `.()` in `i`, and to make the help text more consistent, I think `.()` could be mentioned explicitly also in the **Arguments** section of `i`.  
2. In the `i` **Examples**, it would be better to describe `.( )` when it first occurs (`DT[.("a"), on="x"]`).
3. Either describe exceptions to when `.()` works (like e.g. my `between` and in Frank's SO post) or, as Frank wrote, make it work throughout `i` and `j`.
