### ISSUE TITLE
non-english variable name error

### ISSUE THREAD

**Issue by jeonghyunwoo** [Rdatatable/data.table#2320]
In case of Korean variable name, errors ocurr.
   example: 
       df[ , .(wltv = weighted.mean(현재ltv , w=대출잔액), by=시도] 
      error message: 
        Error in weighted.mean(현재ltv, w = 대출잔액) : 
             object '현재ltv' not found

But, this is not consistent.
   example:
       df[ , .(현재ltv, 대출잔액, 시도)][ , .(wltv = weighted.mean(현재ltv , w=대출잔액), by=시도] 
   if I use subset and chainning, it does work! I can't understand why.

**Comment by MichaelChirico** [comment]
could you make a reproducible example? thanks

**Comment by jangorecki** [comment]
@jeonghyunwoo if you are able to provide the reproducible please do, we will re-open the issue. Closing as it is now more than 2.5 year that we are waiting for it.
