### ISSUE TITLE
frank

### ISSUE THREAD

**Issue by cguill95** [Rdatatable/data.table#2328]
Hi,

Maybe this is not a real issue and the wanted behavior but I just wanted to draw your attention to the inconsistent behavior between the `rank` function and the `frank` function in the way they deal with capital letters.

`> frank(c("Da", "DA", "DB"))
[1] 3 1 2
> rank(c("Da", "DA", "DB"))
[1] 1 2 3`

**Comment by franknarf1** [comment]
It's probably related to this in `?setorder`

> data.table always reorders in C-locale. To sort by session locale, use `x[base::order(.)]` instead.

However, I don't see a similar note in `?frank`.
