### ISSUE TITLE
FR: if CJ is passed data.table arguments, do a blocked cross-join

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2343]
I have a case where I don't want the outer product of _all rows_ of some input, but rather the outer product of all _blocks of rows_ of the input. It seems natural that `CJ` should be able to handle constructing this:

```
DT1 = data.table(x1 = c(1, 2), x2 = c(3, 4))
DT2 = data.table(y1 = c(5, 6, 7))
```

Desired output:
```
CJ(DT1, DT2)
#    x1 x2 y1
# 1:  1  3  5
# 2:  2  4  5
# 3:  1  3  6
# 4:  2  4  6
# 5:  1  3  7
# 6:  2  4  7
```

Hopefully it's sufficiently clear from this.

A hack is to do something like:

```
idxDT = CJ(seq_len(nrow(DT1)), seq_len(nrow(DT2)))
idxDT[ , cbind(DT1[V1], DT2[V2])]
#    x1 x2 y1
# 1:  1  3  5
# 2:  1  3  6
# 3:  1  3  7
# 4:  2  4  5
# 5:  2  4  6
# 6:  2  4  7
```

The order isn't particularly natural here, but doesn't matter in my application. Worse is that it's clunky and not easily extensible to having several more `data.table`s of input.

Most natural in current functionality (wrong) is `CJ(DT1$x1, DT1$x2, DT2$y1)`, but this has too many rows and must be pared back.

**Comment by st-pasha** [comment]
How about this:
```
> DT2[, (DT1), by=y1]
   y1 V1 V2
1:  5  1  3
2:  5  2  4
3:  6  1  3
4:  6  2  4
5:  7  1  3
6:  7  2  4
```

**Comment by franknarf1** [comment]
> I have a case where I don't want the outer product of all rows of some input, but rather the outer product of all blocks of rows of the input.

I don't see the distinction here. There are two rows in one table; three in the other; and the Cartesian product in the result (regarding rows as tuples and tables as sets of tuples), unless you just mean the row order.

> Worse is that it's clunky and not easily extensible to having several more data.tables of input.

With `Reduce`...

```
CJDT = function(...) 
  Reduce(function(DT1, DT2) cbind(DT1, DT2[rep(1:.N, each=nrow(DT1))]), list(...))
```

Not sure if that's what you're after. I'm not crazy about the row ordering, so I'd probably do `cbind(DT1[rep(1:.N, each=nrow(DT2))], DT2)` instead, fwiw.

**Comment by MichaelChirico** [comment]
Indeed I think #1717 covers this. Closing.
