### ISSUE TITLE
Fread 'sep' must be a single character

### ISSUE THREAD

**Issue by sabrikaragonen** [Rdatatable/data.table#2361]
We're using double pipe "||" as seperator in csv files. It makes our data transfer process more robust.
However, when I try to use fread with these files, I get the error in the title.  
Is it possible to change that behaviour in fread? It should accept double characters as seperator, too.

**Comment by st-pasha** [comment]
Duplicate of #2011

**Comment by mattdowle** [comment]
Yep, closing at duplicate. Thanks @st-pasha.  Keeping the earlier one open.
