### ISSUE TITLE
Fix test() function so that it can distinguish NA from NaN

### ISSUE THREAD

**Issue by st-pasha** [Rdatatable/data.table#2365]
The following simple test currently passes, whereas it should not
```
require(data.table)
data.table:::test(11111, as.numeric(NA), NaN)
```

**Comment by mattdowle** [comment]
I know this was my suggestion to change `test()`, but thinking about it, have now just added `identical()` into the test() calls in this rare case (PR #2363) where we care about `NaN`/`NA` differences.  Changing `test()` to no longer use `all.equal()` (which considers `NA` and `NaN` equal) will be too much work for little benefit.  Passing `identical()` to `test()` when we need that, should be fine.
