### ISSUE TITLE
fread mangles long integers? eg 17603012411165

### ISSUE THREAD

**Issue by seanv507** [Rdatatable/data.table#2375]
[test.txt](https://github.com/Rdatatable/data.table/files/1321340/test.txt)

test
17603012411165

> fread('data/test.csv')
            test
1: 8.697044e-311

data.table version 1.10.4 on ubuntu

**Comment by MichaelChirico** [comment]
I believe this was handled recently, please try installing the development version (or possibly simply following the warning message and installing `bit64`):

```
fread('https://github.com/Rdatatable/data.table/files/1321340/test.txt')
             test
1: 17603012411165
```

**Comment by mattdowle** [comment]
Yes, full explanation here:  https://stackoverflow.com/a/46012612/403310
