### ISSUE TITLE
one column being needed both in grouping and in j

### ISSUE THREAD

**Issue by ieiwk** [Rdatatable/data.table#2379]
Dear,

data.table is cool. I am learning using it.

Here is a situiation I found no quick solution:
there is one column for which I want to use its sub-string in _by_, while in _j_ I want to access its other parts.

Please help. Thanks a lot!

**Comment by MichaelChirico** [comment]
look into .BY. please use the issue tracker for package bugs/feature
requests instead of tutorial help -- stackoverflow will be happy to help as
well as much faster.

cheers!!

**Comment by ieiwk** [comment]
Thanks! But .BY is only the sub-string I used to group, while in _j_ I need to access parts other than that sub-string...

**Comment by ieiwk** [comment]
Also for the issue tracker, am I using it already and correctly?

**Comment by renkun-ken** [comment]
Duplicate of #1427

**Comment by ieiwk** [comment]
OK, now I have figured it out. I can use _.I_ in _j_.
