### ISSUE TITLE
Failed to read 1 row file

### ISSUE THREAD

**Issue by Victsz** [Rdatatable/data.table#2380]
The file contains 1 data line with no header in UTF-8.

Error in fread("x.214") : 
  Internal error: ch>eof when detecting eol

I tried to append empty line by CR LF or LF but made no difference.

My sample data,

![image](https://user-images.githubusercontent.com/8154646/30780127-72405bfe-a136-11e7-8dd8-a4fa9dd8a9e7.png)

R version 3.3.2 64bit

packageVersion("data.table")
[1] ‘1.10.0’
>

**Comment by MichaelChirico** [comment]
please update to the latest development version as there's been a lot of
work on fread recently. do report back if the issue remains.

**Comment by Victsz** [comment]
Still not working
data.table_1.10.4.zip
from https://cran.r-project.org/web/packages/data.table/
@MichaelChirico

**Comment by st-pasha** [comment]
Could you attach the file please?

**Comment by Victsz** [comment]
Sure @st-pasha 
[x.214.txt](https://github.com/Rdatatable/data.table/files/1328636/x.214.txt)

**Comment by st-pasha** [comment]
Hmm, I'm getting with the latest version of datatable the following result:
```
> fread("~/Downloads/x.214.txt")
Empty data.table (0 rows) of 3 cols: "HedgeReplace,RBs_LC-F-H-125,RBs_LC-F-SH-127
```
which seems to be about right. Same result both on MacOS and on Ubuntu Linux.

Which error message are you getting, and could you please post your `sessionInfo()` ?

**Comment by Victsz** [comment]
` fread("~/Downloads/x.214.txt")
Error in fread("~/Downloads/x.214.txt") : 
  Internal error: ch>eof when detecting eol`
`
 sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4

loaded via a namespace (and not attached):
[1] rtvs_1.0.0.0`

**Comment by Victsz** [comment]
is data.table_1.10.4 the latest ?

**Comment by MichaelChirico** [comment]
no, 1.10.5. read here:

https://github.com/Rdatatable/data.table/wiki/Installation

**Comment by Victsz** [comment]
Cool! problem solved. Thanks @MichaelChirico  @st-pasha
