### ISSUE TITLE
[fread][bug] fread with explicit select=NULL

### ISSUE THREAD

**Issue by dselivanov** [Rdatatable/data.table#2381]
There is inconsistency in `select`argument in` fread()`. Default value is `select = NULL`, but logic inside is to [check missing value](https://github.com/Rdatatable/data.table/blob/master/R/fread.R#L111) with `missing(select)`.
So when user specifies `select = NULL` explicitly, `fread` throws error:
```r
fread("a,c,b\n1,2,3", select=NULL)
#Error in setcolorder(ans, reorder) : 
#  neworder is length 0 but x has 3 columns.
```

My guess is that `fread` should check it with `is.null()`

**Comment by MichaelChirico** [comment]
good catch!

**Comment by rudazhan** [comment]
:+1:  I was just about to report the same issue recently caught in my read function.

**Comment by rudazhan** [comment]
This issue has been reported earlier this year in #2007

**Comment by dselivanov** [comment]
Ok, closing. Really small issue, we need to get rid of it. I will send PR.
