### ISSUE TITLE
unexpected subsetting results

### ISSUE THREAD

**Issue by kodonnell** [Rdatatable/data.table#2396]
The following doesn't seem intuitive, and also contradicts normal data frame subsetting

```r
> dt <- data.table(a=1:2, b=c('a', 'b'))
> dt
   a b
1: 1 a
2: 2 b
> setkey(dt, a, b)
> dt[a == 1 & b == 'b'] # this behave as expected
Empty data.table (0 rows) of 2 cols: a,b
> dt[.(1, 'b')] # this doesn't (even though it's meant to?), and 'corrupts' my data
   a b
1: 1 b
```

Why don't the last two agree? Specifically, why is subsetting introducing data that doesn't exist? (Violating data integrity in such a way is pretty serious ....). If this is intended behaviour, I'm worried that it's non-intuitive, and an easily made mistake - and doesn't seem to be documented anywhere I can find. Even if it exists, the point is still that I, as a not infallible but still somewhat experienced (non-data.table) R user didn't see this, and my data was being 'corrupted' etc.

Questions:
- is this a bug or expected behaviour?
- if the latter, how to avoid these (very serious and easily made) accidents being made by inexperienced data.table users (like myself)? Warnings? What do we lose if we change the behaviour to act as 'expected'?

Note: I've had a look but couldn't find an equivalent issue, so hopefully this isn't a duplicate.

**Comment by franknarf1** [comment]
It is expected behavior, for a join `x[i]`, you will see each row of `i` even if it is unmatched in `x` by default. To omit unmatched rows of `i`...

```
dt[.(1, 'b'), nomatch=0]
```

**Comment by kodonnell** [comment]
Great, thanks @franknarf1 . Should we default to `nomatch=0`, as this a) matches default `data.frame` behaviour, and b) is much safer given the above.

**Comment by MichaelChirico** [comment]
See #857 and comment there. To me, this is just _how `[` works_... You're using `i` to look up rows in `x`.

For now, you can use `merge` if you want more explicit control over what to do with unmatched rows (`all.x`/`all.y`/`all` arguments). See also here: https://stackoverflow.com/questions/1299871/how-to-join-merge-data-frames-inner-outer-left-right

**Comment by franknarf1** [comment]
@kodonnell The analogy of a join `x[i]` where `i` is another table is to `X[Y]` where both are matrices -- it's not subsetting by a logical condition but rather lookup by an index, so in that sense `nomatch=NA` makes intuitive sense. 

It's just that `x[i]` is overloaded for use with logical conditions, joins and row numbers. Each has different rules for the results, but the differences are useful once you're used to them.

**Comment by kodonnell** [comment]
Thanks both - I'm not familiar enough with `data.table` to understand what you mean by *just how `[` works* or *intuitive sense*. To me, if something doesn't exist in the data (and hence the 'index', since it's only ordering the data here?), then nothing should be returned - and I suspect that's what most non-data.table users would expect. @MichaelChirico, this appears to be the case in #857, where others expect `nomatch=0L` to be the default (it appears that was going to happen but hasn't??).

@franknarf1 if the behaviour was 

```
> dt[.(1, 'b')]
   a b
1: 1 NA
```

then `nomatch=NA` might make sense to me (though `NULL` fills would be more correct than `NA`). As it is, I still don't see why it's returning data that doesn't exist, or how this could be useful. Even in the above case, I'd still argue that `nomatch=0L` was a better default.

**Comment by franknarf1** [comment]
@kodonnell To clarify, this is what I meant by matrix indexing:

```
X = matrix(LETTERS[1:4], 2)
Y = cbind(c(1,2), c(1,2))
X[Y]
# [1] "A" "D"
```

or with vectors...

```
v = LETTERS[1:4]
w = c(2, 5)
v[w]
# [1] "B" NA
```

so the unmatched index returns an `NA`. 

The matrix-index analogy is mentioned at the top of the docs:

> It is inspired by `A[B]` syntax in R where `A` is a matrix and `B` is a 2-column matrix. 

----

Looking again, I agree the docs should be clearer. They say...

> When the binary operator `==` alone is used, an *equi join* is performed. 

as well as 

> If `i` is a data.table, [...] It allows for both equi- and the newly implemented non-equi joins.

But actually these two ways to get an equi-join behave differently with respect to `nomatch=`, and that could be made clearer.

**Comment by kodonnell** [comment]
Thanks @franknarf1 - but I'm still not sure how this applies here, as *incorrect data* is returned, not `NA`. I.e. asking for the fifth element of a four element (as per your last example) vector is undefined, hence returning `NA`. As discussed before, I'm unclear why `1 b` is returned not `1 NA` (even though I'd still prefer the default to return nothing). It seems like you'd also expect the latter (i.e. *the unmatched index returns an `NA`.*) - if not, can you explain?

**Comment by franknarf1** [comment]
@kodonnell You are using a multicolumn index, in this case with two columns. Every row and every column of the index shows up in the results when `nomatch=NA`. If you want unmatched rows dropped, `nomatch=0` will do that. No index .(1, NA) was passed, but rather .(1, "b"), so that's what you see.

Another example:

```
library(data.table)
DT1 = data.table(x = 1, y = 2, z = 3)
DT1[.(c(1,1),c(3,99)), on=.(x,z)]

   x  y  z
1: 1  2  3
2: 1 NA 99
```

The x and z values are taken from the index and each gets at least one row in the result even if unmatched, which is what the `nomatch=NA` default means.

If you're interested in more examples, I have [some notes](http://franknarf1.github.io/r-tutorial/_book/tables.html#dt-joins) and sometime soon, the package developers hope to have a vignette on joins, I think.

**Comment by kodonnell** [comment]
Ah, I see - it's not returning corrupt data per se, it's returning no data, plus my search term. (Hence why `nomatch=0` is correct.)

Back to the other question - do you think we should default to `nomatch=0`? (Or `NULL` as per #857, which makes more sense.) As per #857, this seems to be desired by others, and I still maintain that it's probably what most people expect to happen most of the time, and that it's very easy to make a mistake like the above which has the effect of corrupting outputs (in a way that is hard to detect). If you want to include other `nomatch` types, then it can be assumed you know what you're doing, and you know all the intricacies of the above - but this is probably beyond most common R users, who, if they're like me, expect data.table kind of be like data.frames just a lot faster (which is how I recall it usually being described/marketed).

Also, great notes, thanks. Will read in detail later.

**Comment by franknarf1** [comment]
@kodonnell Np. I can't think of a strong reason to prefer one `nomatch=` default vs the other, since when it matters, I usually (i) want `nomatch=0` or (ii) do `by=.EACHI` which essentially keeps all `i` rows. I guess my existing code wouldn't break if it switched, but I'm not sure.

Even if that is changed, you'll find other differences vs your `DT[x == 1 & y == 2]` style subsetting, which is apparently closest to a "semi join" (... I am not very conversant in SQL terms):

* [Hadley's 2013 SO question on it](https://stackoverflow.com/questions/18969420/perform-a-semi-join-with-data-table) and a related suggestion: #915
* My similar suggestion years later (before I realized it was the same issue): #2158 

There may be other differences between joins and your intuitiion for them. Generally, it's probably best to learn to think of data.table's default joins as distinct from vanilla subsetting.

**Comment by kodonnell** [comment]
Good links @franknarf1  - yes, 'semi-join' is what I'm looking for. However, as a user I don't want to think of joins, I just want to think of subetting. Based off https://cran.r-project.org/web/packages/data.table/vignettes/datatable-keys-fast-subset.html, I was under the impression `DT[x == 1 & y == 2]` and `setkey(DT, x, y); DT[.(1, 2)]` were equivalent (for subsetting). This is clearly not the case unless one specifies `nomatch=0` ... maybe this should be made clearer, and the fact that 'subsetting' is actually joining etc. Or just change it so that 'subsetting' behaves as expected, though that's probably not trivial.

At the least we can avoid my particular issue (and possibly others) in the subsetting case by defaulting to `nomatch = 0` etc. Alternatively, we could add warnings in when these sorts of subsetting operations occur. Or have no default `nomatch`, to force people to be aware of the potential sources of error.

**Comment by MichaelChirico** [comment]
Agree to close. Hope we have clarified things @kodonnell. `x[i]` is a _RIGHT JOIN_ by default (in SQL speak).

That means there's always (at least) one row corresponding to every row in `i`. Have also tagged this issue as reference in RFV (request for vignette 😛) at #944.

**Comment by jangorecki** [comment]
Yes, this is pretty obvious when you look at basic R subsetting.
```r
x = c(a=1,b=2)
i = c("b","c")
x[i]
#   b <NA> 
#   2   NA 
```
