### ISSUE TITLE
For consistency, should subsetting with a logical vector, DT[logic, .(a)] give the same results as DT[, .(a[logic])]?

### ISSUE THREAD

**Issue by alexfun** [Rdatatable/data.table#2416]
Compare:

```
DT <-
    data.table(a = c(1, NA, 3))
logic <- c(T, NA, T)

tmp_dt[logic, .(a)]
# a
# 1: 1
# 2: 3
tmp_dt[, .(a[logic])]
# V1
# 1:  1
# 2: NA
# 3:  3
```
This seems to be strange to me due to the inconsistency. Note I don't have a problem with passing a logical vector to the "I" component of a data table, as explained by Arun here: https://stackoverflow.com/a/16222108/

**Comment by franknarf1** [comment]
Similarly,

```
DT[a == 1]
#    a
# 1: 1
data.frame(DT)[ DT$a == 1, , drop = FALSE]
    a
1   1
NA NA
```

Personally, I prefer it this way. Getting NA rows back when subsetting is not meaningful for my purposes.

If anything, I guess I'd like an option to throw an error when `is.logical(i) && anyNA(i)`.

**Comment by jangorecki** [comment]
Explained in FAQ: https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html#SmallerDiffs
