### ISSUE TITLE
add a banner to the issues page pointing to the contributing guidelines

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2417]
Just noticed this repository has a nice banner at the top of the issues page pointing out the contribution guidelines:

https://github.com/baztian/jaydebeapi/issues

I've noticed an uptick in "issues" that are better suited for SO questions, perhaps adding such a banner could help redirect this traffic.

**Comment by mattdowle** [comment]
Good idea.  I had a look in the project settings but couldn't see the option for that.  I asked GitHub support how to do it.

Btw, surprised to find you're not a member of the project!  I just added you.  That was long overdue.  You are properly listed in DESCRIPTION,  but in dev and not yet on CRAN.  Those CRAN patches were manual and minimal, so that field on CRAN will be corrected when 1.10.6 finally gets to CRAN!

**Comment by MichaelChirico** [comment]
@mattdowle Oh, cool, thanks, I'm honored!

**Comment by MichaelChirico** [comment]
Also seeing basically a clone over on `bootstrap`; the first line looks standard, the second customizable (wherever this functionality lives):

https://github.com/twbs/bootstrap/issues

**Comment by mattdowle** [comment]
GitHub support replied :

> Are you referring to the banner asking "Want to submit an issue to baztian/jaydebeapi?" ? If so, then I see that banner on the Rdatatable/data.table page as well -- see attached screenshot. 
<img width="1109" alt="screen shot 2017-10-15 at 08 43 17" src="https://user-images.githubusercontent.com/2779998/31599038-84a175a0-b205-11e7-81db-17a03ca2e06b.png">

> That's a GitHub thing, not something project owners can control, and the reason you don't see it on Rdatatable/data.table is that you're someone who already contributed to the repository. The banner is shown only to first time contributors (to help them get started).

> However, the message is tweaked based on some things. For example, the message will have a link to the contributing guide if you have one defined in your repository (which you do).

**Comment by mattdowle** [comment]
I had another look in project settings and there is a template for issues possible.  Seems like a new GitHub feature.  So I made a first attempt and added one. It's a new file in root.
First problem is that when the user presses "new issue" they have to realize to click over to preview tab to see the links in the template decently.  If we keep the template, maybe "Click preview tab just above!" could be added at the top.
Second problem is that we now have 3 places :  issue template, Contributing and Support with some duplication of information across them.
