### ISSUE TITLE
on = col_name (i.e., unquoted) should work for consistency with by = col_name

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2433]
We finally have `on = .(col_name)` syntax working, so I was caught off guard when I tried `on = col_name` and encountered "not found" error.

Any reason not to use the same scoping rules as in `by` for `on`?

**Comment by jangorecki** [comment]
As long as we don't support on-the-fly calls inside `on` there is no reason to align `on` to `by`. I would rather prefer to workaround the new, broader interface for joining.
