### ISSUE TITLE
noreturn option to data.table 

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2442]
Since `data.table` captures `list` objects in `j` and tries to read them as columns, sometimes we get pesky errors. This happens in particular when trying to `boxplot` something in `j`:

```
set.seed(10349)
DT = data.table(f = factor(sample(5, 100, TRUE)), v = rnorm(100))
DT[ , boxplot(v ~ f)]
```
> Error in setnames(jval, jvnames) : Can't assign 6 names to a 14 column data.table

There's an easy workaround: just make `j = {boxplot(v ~ f); NULL}` to prevent the `boxplot` from being returned.

My issue with this is it's a bit hacky, which may be a distraction in presentations, e.g., `rmarkdown` versions of output.

I don't think it's possible for `DT[ , boxplot(v~f)]` to work, but something like `DT[ , boxplot(v ~ f), noreturn = TRUE]` might be easier on the eyes? Thoughts?

**Comment by franknarf1** [comment]
Or maybe return, with values...

* TRUE for current behavior
* FALSE for returning NULL (invisibly?)
* “asis” for returning j without attempting to translate to columns

**Comment by HughParsonage** [comment]
FWIW, I would use `magrittr`, even if this feature were implemented in `data.table`. Considering how well `data.table` plays with `magrittr`, it would be rare to have one without the other.

```r
library(magrittr)
DT %$%
  boxplot(v ~ f)
```

**Comment by MichaelChirico** [comment]
thanks Hugh, cool suggestion, never saw that pipe before. *adds to toolkit*

FWIW I think I'll stick with using [] in most cases, as in most cases the
plot is the second or third element of a [][][] chain, so to me it feels
more natural to keep the chain going

**Comment by renkun-ken** [comment]
What about using `as.null()` like

```r
DT[ , as.null(boxplot(v ~ f))]
```

**Comment by jangorecki** [comment]
eventually
```r
DT[, I(boxplot(v ~ f))] -> nul
```
IMO no need an extra argument just for such narrow functionality. Feel free to re-open if there will be some new idea to address that.
