### ISSUE TITLE
shiny issue

### ISSUE THREAD

**Issue by vikram-rawat** [Rdatatable/data.table#2443]
I am just seeking help with a small question.

## **WHY**

`DT()[,somecolname] `doesn't work in shiny context where DT() is a reactive data.table.
but
`DT[,somecolname]` works on console.

is there anything that is different. I just want to know is there any conceptual gap between normal data.table and using it in shiny. because I want to write big queries this is just a subset of it.

This is the entire project it is nothing but manipulating an excel file. just take a look and you would understand what do I mean. the file that I am working on is inside as well. I don't know if this is perticular to this app.

[AbhilashGST.zip](https://github.com/Rdatatable/data.table/files/1414235/AbhilashGST.zip)

**Comment by vikram-rawat** [comment]
It is solved

**Comment by MichaelChirico** [comment]
please elaborate for any future users with a similar issue

**Comment by SteveBronder** [comment]
@vikram-rawat what was the resolution to this?

**Comment by vikram-rawat** [comment]
Somehow

SetDT function wasn't working on read_excel. It was like

Read_excel(some file) %>% setDT()

This doesn't convert the data frame into data table.

So it wasn,t a data table when I called it even though it should have been.

Then I created 2 different statement

Like

File <- Read_excel(some file)
SetDT(file)
