### ISSUE TITLE
fwrite not retaining group permission enabled by setfacl

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#2445]
`fwrite` does not retain group permission of a directory enabled by `setfacl`, as <https://unix.stackexchange.com/a/115632/165008> suggests. By contrast, both `touch` in terminal and `writeLines()` in R correctly retain that group permission.

Steps to reproduces (under Ubuntu 16.04.3):

```sh
cd ~
mkdir test
chmod g+s,o-rwx test
setfacl -Rdm g::rw test
touch test/touch.txt
Rscript -e "writeLines('hello','test/writeLines.txt')"
Rscript -e "write.csv(mtcars,'test/write.csv.csv')"
Rscript -e "data.table::fwrite(mtcars,'test/fwrite.csv')"
ls -lh test
```

On my machine, it shows the following:

```
total 44K
-rw-r----- 1 renkun renkun 1.3K Oct 26 13:29 fwrite.csv
-rw-rw---- 1 renkun renkun    0 Oct 26 13:28 touch.txt
-rw-rw---- 1 renkun renkun 1.8K Oct 26 13:29 write.csv.csv
-rw-rw---- 1 renkun renkun    6 Oct 26 13:29 writeLines.txt
```

This indicates that `fwrite` does not retain group permission enabled by `setfacl` while `touch`, `write.csv` and `writeLines` do.

It looks like something has to be done to https://github.com/Rdatatable/data.table/blob/5f1581303051108a61fda8020142fc5730105ec2/src/fwrite.c#L656 to fix this.

**Comment by mattdowle** [comment]
Great report, thanks.   It works for me in dev though.  Bug fix 2 in [NEWS](https://github.com/Rdatatable/data.table/blob/master/NEWS.md) from 1.10.5 is : 

> 2. `fwrite()` creates a file with permissions that now play correctly with Sys.umask(), #2049. Thanks to @gnguy for reporting.

That fix already changed that line fwrite.c and I looks like it fixed your example too.   Please reopen if 1.10.5 doesn't fix it for you.

**Comment by renkun-ken** [comment]
Great to know it's fixed. Thanks!
