### ISSUE TITLE
Unable to load package data.table 1.10.4-3

### ISSUE THREAD

**Issue by arfesta** [Rdatatable/data.table#2448]
`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)
library(data.table)

Error : .onLoad failed in loadNamespace() for 'data.table', details:
  call: fun(libname, pkgname)
  error: (converted from warning) Option 'datatable.old.bywithoutby' has been removed as warned for 2 years. It is now ignored. Please use by=.EACHI instead and stop using this option.
Error: package or namespace load failed for ‘data.table’

`#` `Output of sessionInfo()`
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.0

**Comment by mattdowle** [comment]
This seems like intended behaviour.
```
error: (converted from warning) Option 'datatable.old.bywithoutby' has been removed as warned for 2 years. It is now ignored. Please use by=.EACHI instead and stop using this option.
```
What that's telling you is that somewhere either in your `.Rprofile` or in your code/package is a line that is setting that option.  But that option has been removed, and is now ignored.  It has been warning you for 2 years and you didn't do anything.  It has been removed now and you must remove that line in your code that is setting that option.

Please reopen if I've misunderstood.

**Comment by mattdowle** [comment]
From news file for v1.9.8 on CRAN Nov 2016 :  

> 36  The option datatable.old.bywithoutby to restore the old default has been removed. As warned 2 years ago in release notes and explicitly warned about for 1 year when used. Search down this file for the text ‘bywithoutby’ to see previous notes on this topic.

That's when the warning started and there hasn't been any change since then.  It's still a warning.  I'm not sure why it's being covered to error for you.  If you have set `options(warn=2)`, it would do.  Or if you are running `data.table:::test.data.table()` directly without doing `library(data.table)`, perhaps.

It was intended to be a warning and not an error.  In a year it might be changed to error.

**Comment by arfesta** [comment]
Ahh, sorry about that. I forgot I had set the options(warn=2). I changed that and it loads/works. I hadn't seen the error before because I hadn't used it with warn=2.

Thank you!

**Comment by mattdowle** [comment]
@arfesta  Ok great.  Please remove the use of that option though as it will eventually (in 1 year) be changed to error and then the package really will refuse to load.  You should have seen the warning before.  It's important to address and tackle all warnings.
