### ISSUE TITLE
DT[,mget(colNames)] vs DT[,colNames,with=FALSE]

### ISSUE THREAD

**Issue by statquant** [Rdatatable/data.table#2466]
Hello, 

1. is there a difference between `DT[,mget(colNames)]` vs `DT[,colNames,with=FALSE]`
2. should one be preferred ?

As a FR could we get something like `dtget`  that would enable us to get/rename at once

```
DT=data.table(x=1:3,y=1:3,z=1:3)
DT[,dtget(c(X='x','z',Y='y'))] # essentially mget + setnames but much easier to use in chaining
   X z Y 
1: 1 1 1
2: 2 2 2
3: 3 3 3
```

**Comment by MichaelChirico** [comment]
In chaining, I'm not sure how useful `setnames` is compared to just naming the output:

```
DT[, .(X='x', z, Y='y')]
```

As to `mget` vs `with=FALSE`, in principle there shouldn't be a difference between the two in terms of output, I don't know about performance. I'd say `.SDcols` is most preferred in more complicated scenarios.

Feel free to re-open if that leaves you unsatisfied.
