### ISSUE TITLE
Checking LENGTH(allocVector(INTSXP,2)) [231477936] is 2 ... failed. Please forward this message to maintainer('data.table').

### ISSUE THREAD

**Issue by rgpearce** [Rdatatable/data.table#2469]
I have continued to get this loading error for the last couple of weeks while installing a package in R-devel. This has already been mentioned [`here`](https://github.com/Rdatatable/data.table/issues/2353) and [`here`](https://github.com/leeper/rio/pull/164), but it is not clear if this is a problem with data.table or r-devel.

**Comment by mattdowle** [comment]
Please include the output of `sessionInfo()` so we can see which version of R-devel you are using (its date and revision number) and which version of data.table (dev as of when, or which CRAN version).
I tried locally with dev data.table 1.10.5 and R-devel as follows and it passed ok  : 
```
R Under development (unstable) (2017-10-10 r73525)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.04
```
I updated to latest R-devel and it still seems fine
```
R Under development (unstable) (2017-11-08 r73690)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.04
```
Are you running a version of R-devel as of 2 weeks ago, perhaps?  The comments in the linked questions seems to suggest there was a problem in R-devel around then which was resolved.  So you have to update your version of R-devel.

Also, I uploaded latest dev 1.10.5 to win-builder and it passed latest R-devel there ok on Windows.

And, CRAN version 1.10.4-3 is passing fine on latest R-devel according to [here](https://cran.r-project.org/web/checks/check_results_data.table.html).

The error you're seeing is the result of some checks that run on loading the package.  For the LENGTH() of that vector not to be 2 is a very serious fundamental error and seems very likely to have been a fleeting bug in R-devel that was resolved quickly.

Please paste the output from `sessionInfo()`.

**Comment by mattdowle** [comment]
Closing to move on.  We must have `sessionInfo()` up front please as the Issue template asks for.  Otherwise we waste time asking you for it and guessing.
