### ISSUE TITLE
is it possible to ignore error and coninue reading from file

### ISSUE THREAD

**Issue by huashan** [Rdatatable/data.table#2496]
I am trying to read from several huge files which may contain `embedded null strings` in some lines. `fread()` always stops with message "Jump %d did not finish counting rows exactly where jump %d found its first good line start".

Since I have some many files to read and I don't care to lose some broken lines of data, is it possible to let `fread()` just ignore the error and continue reading?

**Comment by MichaelChirico** [comment]
please include information about your version of data.table. if you haven't
installed the most recent development version, please do so -- fread has
undergone substantial improvements and this concern may be moot.

**Comment by huashan** [comment]
@MichaelChirico 

The data.table version is 1.10.5 release, with the above message "Jump %d did not finish counting rows exactly where jump %d found its first good line start".

I also tried earlier versions of data.table, from 1.9.7 to 1.10.4, all report error message with "embedded null string".

**Comment by huashan** [comment]
@MichaelChirico 

FYI, for version 1.10.5, if I set `quote=""` in `fread()` causes R crashes.

**Comment by jangorecki** [comment]
please provide reproducible example
