### ISSUE TITLE
problems on bigdata importinng.

### ISSUE THREAD

**Issue by amjiuzi** [Rdatatable/data.table#2508]
hi, @mattdowle
i have a big dataset ( txt, 8Gb, dim(dataset) == 300,000 rows x 900,000 columns)
col1 is ID, others are all numeric, not sparse.
i wonder if 'fread' is sufficient for this? 
had you token such a test like this? how about your time cost?

if sufficient, any smart params should i set ?

looking forward to your reply

**Comment by MichaelChirico** [comment]
1) Have you tried reading the file?
2) Do you have sufficient RAM?

I see no reason in principle why `fread` would fail in this case on a machine equipped to do so.

I'm going to close this; feel free to re-open if you've tried reading and find some bug you think requires fixing.
