### ISSUE TITLE
data.table's grouping function does not work when called inside a source code in an original package.

### ISSUE THREAD

**Issue by YTs63** [Rdatatable/data.table#2528]
When I packaging a source code including data.table[x, FUN, by=] grouping method, the grouping didn't work, although the same code works when I run directly on Rstudio's console.

The source code I wrote is below.
test.r
```
test1 <- function(){
	library(data.table)

	data.dt <- data.table(x=rep(c("a", "b", "c"), each=3), y=c(1,3,6), z=1:9)
	print(data.dt)
	cnt <- data.dt[, .N, by=x]
	print(cnt)
}
```

The output in my environment in the two cases are below.
1. Ran the source code directly on console
->Works correctly.
```
> data.dt <- data.table(x=rep(c("a", "b", "c"), each=3), y=c(1,3,6), z=1:9)
> print(data.dt)
   x y z
1: a 1 1
2: a 3 2
3: a 6 3
4: b 1 4
5: b 3 5
6: b 6 6
7: c 1 7
8: c 3 8
9: c 6 9
> cnt <- data.dt[, .N, by=x]
> print(cnt)
   x N
1: a 3
2: b 3
3: c 3
```

2.Load package which includes test.r and run the function test1()
->Doesn't work.
```
> library(TestPackage)
> test1()
   x y z
1: a 1 1
2: a 3 2
3: a 6 3
4: b 1 4
5: b 3 5
6: b 6 6
7: c 1 7
8: c 3 8
9: c 6 9
Null data.table (0 rows and 0 cols)
NULL
```
TestPackage is the original package I created which includes only test.r script.

It seems that the data.dt[, .N, by=x] does not return any result.
Does anyone know the cause of this case?
Thanks.

**Comment by MichaelChirico** [comment]
please read the new vignette about using data.table in your own package, created with this pull request:

https://github.com/Rdatatable/data.table/pull/2501

**Comment by jangorecki** [comment]
The case is that you are incorrectly using dependency in your package. You should not load dependencies using `library` call. If you want to develop quality package you should read the manual [Writing R extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html). If you just want to make it work you can check new vignette [importing data.table](https://rdatatable.gitlab.io/data.table/library/data.table/doc/datatable-importing.html). Closing issue, if you have any issues after following vignette feel free to reopen.

**Comment by YTs63** [comment]
Thanks for the solutions!
I've solved the problem.
