### ISSUE TITLE
Multi-threaded group by

### ISSUE THREAD

**Issue by xiaodaigh** [Rdatatable/data.table#2533]
I wonder if it's technically possible to do multi-threaded group-by? I tested some multi-threading group by in Julia using a divide and conquer algorithm and I can make sum-by faster. So if data.table has multi-threaded group-by then things should speed up even more

**Comment by MichaelChirico** [comment]
I thought this was implemented already, but apparently not:

```
library(data.table)

NN = 1e8
set.seed(304093)
DT = data.table(grp = sample(8, NN, TRUE),
                V = rnorm(NN), key = 'grp')
(default_threads = getDTthreads())
# [1] 8

system.time(DT[ , mean(V), keyby = grp])
#    user  system elapsed 
#   0.786   0.126   0.916 

setDTthreads(1)

system.time(DT[ , mean(V), keyby = grp])
#    user  system elapsed 
#   0.792   0.105   0.898 

setDTthreads(default_threads)
```

**Comment by jangorecki** [comment]
```
> library(data.table)
data.table 1.11.6  Latest news: r-datatable.com
> 
> NN = 1e9
> set.seed(304093)
> # poisson returns integer, 1 billion rows
> #   really pushed the limit of my local RAM
> DT = data.table(grp = sample(8L, NN, TRUE),
+                 V = rpois(NN, 10), key = 'grp')

> (default_threads = getDTthreads())
[1] 32
> 
> system.time(DT[ , mean(V), keyby = grp])
   user  system elapsed 
  6.098   1.007   7.115 
> 
> setDTthreads(1)
> 
> system.time(DT[ , mean(V), keyby = grp])
   user  system elapsed 
  5.674   1.067   6.748 
```
@MichaelChirico could you retry on your machine to see if you still experience slowdown? Second call can eventually be a little bit faster due to caching (so my timings above are close to equal). Grouping is not parallelized but we still need to track slowdown in cases you presented. Recent improvements to gfunctions might have fixed that.

**Comment by MichaelChirico** [comment]
Hmm I got

```
Error: vector memory exhausted (limit reached?)
```

**Comment by mattdowle** [comment]
Please can we have a new policy that when posting timings or benchmarks,. verbose=TRUE should be set and the output included in the issue.  The verbose output includes some timings of some operations and it really helps to see it up front.

**Comment by jangorecki** [comment]
resolved.

40 cores
```
   user  system elapsed 
 61.953   8.605   4.418 
```
1 core
```
   user  system elapsed 
 10.825   4.427  15.253 
```
