### ISSUE TITLE
Warn when user writes DT[.SD, on=]

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2534]
Currently, if `i = .SD` is an invalid referent (... not sure how to describe this case), we get a null data.table back without comment:

```
library(data.table)
# data.table 1.10.5 IN DEVELOPMENT built 2017-12-08 20:14:33 UTC; travis
# sessionInfo() starts like...
# R version 3.3.3 (2017-03-06)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 7 x64 (build 7601) Service Pack 1

DT = data.table(a = 1)
DT[.SD, on=.(yo, wassup) + gibberish / wazoo, verbose = TRUE ]
# Null data.table (0 rows and 0 cols)
```

Maybe a warning or verbose message could be given in this case. I got here by writing...

```
# pseudocode
DT2[, DT[.SD, on=.(a,b), x.z]]
```

and then copy-pasting the inner `j` part to my console while trying to explore the query/call results.

----

I also saw a null data.table returned with... 

```
DT[.GRP, on=.(yo, wassup) + gibberish / wazoo, verbose = TRUE]
# Null data.table (0 rows and 0 cols)
DT[.I, on=.(yo, wassup) + gibberish / wazoo, verbose = TRUE]
# Null data.table (0 rows and 0 cols)
```

... for these other symbols that are not defined in `i`. These are less likely user mistakes, but maybe the messaging here could also be improved.

**Comment by MichaelChirico** [comment]
Hmm I think addressing this would require blocking `.SD` from being used in `i`, unless we specifically look for `isub == quote(.SD) && is.null(eval(isub))`?

**Comment by franknarf1** [comment]
Thanks @MichaelChirico Reading this again, I guess I prefer doing nothing over blocking .SD there (since it's very useful for update joins). I guess my user error in the OP is a special case of the misuse of special symbols outside of expected scope, which is probably pretty rare and might call for a more general fix (if any). Eg,

```
> .N + 1L
```

The 3-year-old issue hasn't had any indication that anyone else ran into the same issue, so I'll go ahead and close. Sorry for the hassle.
