### ISSUE TITLE
fread unnecessary warning

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#2539]
```r
require(data.table) # devel 25-12-2017
fread("ex.txt")
#                  id            name val
# 1: 9002019291929192 Robert Whitaker 200
# 2: 9200129401349301   "Elisa Waters 190

# Warning message:
# In fread("ex2.txt") :
#   Found the last consistent line but text exists afterwards. Consider fill=TRUE and/or 
# blank.lines.skip=TRUE. First 200 characters of discarded line: <<END-OF-DATA>>

fread("ex.txt", nrow=2L)
#                  id            name val
# 1: 9002019291929192 Robert Whitaker 200
# 2: 9200129401349301   "Elisa Waters 190

# Warning message:
# In fread("ex2.txt") :
#   Found the last consistent line but text exists afterwards. Consider fill=TRUE and/or 
# blank.lines.skip=TRUE. First 200 characters of discarded line: <<END-OF-DATA>>
```

If I already choose to read the first 3 lines, I don't think a warning is warranted. Click [**here**](https://github.com/Rdatatable/data.table/files/1586062/ex.txt) to download `ex.txt`.

**Comment by mattdowle** [comment]
Thanks, fully agreed.  Fixed recently in dev and I just checked it looks right now.  Existing new tests cover it. Please reopen if anything amiss.
```
> more("~/Downloads/ex.txt")
id,"name",val
9002019291929192,"Robert Whitaker", 200
9200129401349301 ,"Elisa Waters,190  


END-OF-DATA
METADATA
attr:value
date:"2018-01-01"
data:"cash payment"
> 
> fread("~/Downloads/ex.txt", nrow=2)
                 id            name val
1: 9002019291929192 Robert Whitaker 200
2: 9200129401349301   "Elisa Waters 190
Warning message:
In fread("~/Downloads/ex.txt", nrow = 2) :
  Found and resolved improper quoting. First healed line 3: <<9200129401349301 ,"Elisa Waters,190  >>
> fread("~/Downloads/ex.txt", nrow=1)
                 id            name val
1: 9002019291929192 Robert Whitaker 200
```

If I edit the `ex.txt` to add a quote to properly close that field on line 3 then :  
```
> more("~/Downloads/ex.txt")
id,"name",val
9002019291929192,"Robert Whitaker", 200
9200129401349301 ,"Elisa Waters",190  


END-OF-DATA
METADATA
attr:value
date:"2018-01-01"
data:"cash payment"
>
> fread("~/Downloads/ex.txt", nrow=1)
                 id            name val
1: 9002019291929192 Robert Whitaker 200
> fread("~/Downloads/ex.txt", nrow=2)
                 id            name val
1: 9002019291929192 Robert Whitaker 200
2: 9200129401349301    Elisa Waters 190
> fread("~/Downloads/ex.txt", nrow=3)
                 id            name val
1: 9002019291929192 Robert Whitaker 200
2: 9200129401349301    Elisa Waters 190
Warning message:
In fread("~/Downloads/ex.txt", nrow = 3) :
  Stopped early on line 4. Expected 3 fields but found 0. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<END-OF-DATA>>
> fread("~/Downloads/ex.txt")
                 id            name val
1: 9002019291929192 Robert Whitaker 200
2: 9200129401349301    Elisa Waters 190
Warning message:
In fread("~/Downloads/ex.txt") :
  Stopped early on line 4. Expected 3 fields but found 0. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<END-OF-DATA>>
>

**Comment by nitinahuja** [comment]
This file also gives this error - however if I download the zip file first, fread reads the file fine.
`dt <- data.table::fread("http://www.fueleconomy.gov/feg/epadata/vehicles.csv.zip", fill = TRUE)`
Fails with
`trying URL 'http://www.fueleconomy.gov/feg/epadata/vehicles.csv.zip'
Content type 'application/x-zip-compressed' length 1506286 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

Stopped early on line 2. Expected 1 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<>>`

Opening the same file after downloading and unzipping the file works fine
`dt <- data.table::fread("~/Downloads/vehicles.csv")`
This works

**Comment by jangorecki** [comment]
@nitinahuja This issue in which you are reporting your problem does not seem to be related to your problem. Please avoid bloating different issue with your problem, you can always create new issue. Be sure to follow guidance how to do it. Reading compressed files from remote location, this has been added very recently and as of now is not available in CRAN's data.table version. Read NEWS file for more details.

**Comment by nitinahuja** [comment]
> @nitinahuja This issue in which you are reporting your problem does not seem to be related to your problem. Please avoid bloating different issue with your problem, you can always create new issue. Be sure to follow guidance how to do it. Reading compressed files from remote location, this has been added very recently and as of now is not available in CRAN's data.table version. Read NEWS file for more details.

Thanks - just noticed the news section with this information. Will try with this version.
