### ISSUE TITLE
dt[x] versus dt[unique(c(x))].  What could go wrong?

### ISSUE THREAD

**Issue by jrounds** [Rdatatable/data.table#2541]
Long time user of data.table.  Love your package.  I can recall when I first started using it the "gotcha" bugs would roll in at a surprising pace, so much so, that I would occasionally warn people. Those days have passed.

Fast forward 4 years and I have to say it has been a long while since I ran into a bug in my code due to inappropriately using data.table, but I ran into one today.  Which was basically like so:

dt0 = data.table(x=as.factor(c("a","b", "b")))
x = grep("b", dt0$x)
dt0[unique(c(x))]
dt0[x]

The first results in:
   x
1: a
2: b
I did it thinking I would have the second:
   x
1: b
2: b

I assume this difference is due to the way lazy evaluation is handled?  The first results in x being a column of dt0 and the second uses x in the calling scope.  Dirty.

**Comment by jrounds** [comment]
It is worth noting:
> setDF(dt0)
> 	dt0[unique(c(x)), ]
[1] b b
Levels: a b
> 	dt0[x,]
[1] b b
Levels: a b
> 	setDT(dt0)
> 	dt0[unique(c(x)), ]
   x
1: a
2: b
> 	dt0[x,]
   x
1: b
2: b

I assume the lazy evaluation is a feature.

**Comment by MichaelChirico** [comment]
It's not lazy evaluation, but rather `data.table`'s `with = TRUE` behavior:

```
setDF(dt0)
with(dt0, dt0[unique(c(x)), ])
# [1] a b
# Levels: a b
```

What I'm surprised by is that `c` forces the `factor` into its `integer` representation -- the following fails like I'd expect:

```
dt0[unique(x)]
```

you can force `with = FALSE`-like behavior like so:

```
dt0[unique(.GlobalEnv$x)]
#    x
# 1: b
# 2: b
```

and of course, always be wary of namespace bloat!

going to close this as known behavior pending further feedback. thanks!

**Comment by jrounds** [comment]
Thanks for the detailed response I will start using with = FALSE appropriately.
