### ISSUE TITLE
Need an easier way to fread a list of files of inconsistent number of fields

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#2549]
Suppose a list of csv files with the same header.

Each file is written in the following format:

```csv
1,name1,0.0,1.0
2,name2,0.5,1.5
```

It is easy to read all the files into memory with desired columns selected and classes specified:

```r
files <- list.files("~/data", "\\.csv$", full.names = TRUE)
data <- lapply(files, fread, col.names = c("id", "name", "col1", "col2"), colClasses = c("integer", "character", "numeric", "numeric"))
data <- rbindlist(data)
```

However, if one day the csv format breaks due to some reason, e.g. a new column is added to record the exact local time that record is created, then the csv files that are created later becomes:

```csv
1,name1,0.5,1.5,20180103093025
2,name2,1.5,2.5,20180103093027
```

Then the format breaks from the file with the new column. The reading code no longer works. To avoid rewriting all the csv files in history to apply the new format, the reading code must be adjusted to detect which format is used when each file is read.

I'm wondering if there's an easier way to force reading out specified columns with specified classes. If the column is not present in the file, then fill with missing values of that class. If more columns are present in the file, then they are dropped if not included in the specified columns.

**Comment by MichaelChirico** [comment]
fill = TRUE?

On Jan 3, 2018 9:34 PM, "Kun Ren" <notifications@github.com> wrote:

Suppose a list of csv files with the same header.

Each file is written in the following format:

1,name1,0.0,1.0
2,name2,0.5,1.5

It is easy to read all the files into memory with desired columns selected
and classes specified:

files <- list.files("~/data", "\\.csv$", full.names = TRUE)data <-
lapply(files, fread, col.names = c("id", "name", "col1", "col2"),
colClasses = c("integer", "character", "numeric", "numeric"))data <-
rbindlist(data)

However, if one day the csv format breaks due to some reason, e.g. a new
column is added to record the exact local time that record is created, then
the csv files that are created later becomes:

1,name1,0.5,1.5,20180103093025
2,name2,1.5,2.5,20180103093027

Then the format breaks from the file with the new column. The reading code
no longer works. To avoid rewriting all the csv files in history to apply
the new format, the reading code must be adjusted to detect which format is
used when each file is read.

I'm wondering if there's an easier way to force reading out specified
columns with specified classes. If the column is not present in the file,
then fill with missing values of that class. If more columns are present in
the file, then they are dropped if not included in the specified columns.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rdatatable/data.table/issues/2549>, or mute the thread

**Comment by HughParsonage** [comment]
Instead of specifying the `colClasses` by column number, you can specify it by name

```r
data <- lapply(files, fread, col.names = c("id", "name", "col1", "col2"),
               colClasses = c(integer = "id", character = "name", numeric = c("col1", "col2"))

```

The above should work even if an extra column is added. Then you can use `rbindlist(data, use.names = TRUE, fill = TRUE)` as Michael suggested.

**Comment by renkun-ken** [comment]
In my case, the header is left to the reader to specify and is saved to a separate file, therefore all csv files are of no header at the top, just as demonstrated in my first post.

For the first type of format:

```csv
1,name1,0.0,1.0
2,name2,0.5,1.5
```

I can use the following code to read:

```r
fread(file, col.names = c("id", "name", "col1", "col2"), colClasses = c("integer", "character", "numeric", "numeric"))
```

But for the second type of format, the code does not work even with 'fill=TRUE' added:

```csv
1,name1,0.5,1.5,20180103093025
2,name2,1.5,2.5,20180103093027
```

```r
fread(file, col.names = c("id", "name", "col1", "col2"), colClasses = c("integer", "character", "numeric", "numeric"))
```

```
Error in fread(file, col.names = c("id", "name", "col1", "col2"),  : 
  colClasses is unnamed and length 4 but there are 5 columns. See ?data.table for colClasses usage.
```

To force reading 5 columns from the first format, the following also ends up with an error:

```r
fread(file, col.names = c("id", "name", "col1", "col2", "localtime"), colClasses = c("integer", "character", "numeric", "numeric", "character"))
```

```
Error in fread(file, col.names = cols,  : 
  colClasses is unnamed and length 5 but there are 4 columns. See ?data.table for colClasses usage.
```

The problem seems to come from the combination of csv of no header and specifying `col.names` and `colClasses` at the same time. I'm not sure if there's an easier way to do this?

**Comment by renkun-ken** [comment]
The simpler question is: Is there a way to specify `col.names` and `colClasses` or some other arguments to `fread` both formats of no header with one call, either dropping the last column if present or forcing the last column if not present?

**Comment by MichaelChirico** [comment]
did you catch Hugh's suggestion? I think that's what you want?

**Comment by renkun-ken** [comment]
It works with csv that has a header inside. 

```r
csv1 <- "1,name1,0.0,1.0\n2,name2,0.5,1.5"
csv2 <- "1,name1,0.5,1.5,20180103093025\n2,name2,1.5,2.5,20180103093027"
```

The following code can read `csv1`:

```r
fread(csv1, col.names = c("id", "name", "col1", "col2"), colClasses = list(integer = 1, character = 2, numeric = c(3, 4)))
```

but cannot read `csv2`

```r
> fread(csv2, col.names = c("id", "name", "col1", "col2"), colClasses = list(integer = 1, character = 2, numeric = c(3, 4)))
Error in setnames(ans, col.names) : 
  Can't assign 4 names to a 5 column data.table
```

@HughParsonage's suggestion works perfectly when there's header at top of file. But in my case, I can't specify `col.names` and `colClasses` to work with both formats.

**Comment by st-pasha** [comment]
There could be a new optional parameter `columns` that accepts a callback function; the callback function will be invoked by fread and passed the lists of column names and their types; the function then computes and returns new lists of column names and types. I believe this approach would resolve more than 1 feature request at once.

**Comment by HughParsonage** [comment]
If you know that the only columns you need will be the first four, you could just use `select = 1:4`

``` r
library(data.table)
csv1 <- "1,name1,0.0,1.0\n2,name2,0.5,1.5"
csv2 <- "1,name1,0.5,1.5,20180103093025\n2,name2,1.5,2.5,20180103093027"
fread(csv1, col.names = c("id", "name", "col1", "col2"), colClasses = list(integer = 1, 
  character = 2, numeric = c(3, 4)), select = 1:4)
#>    id  name col1 col2
#> 1:  1 name1  0.0  1.0
#> 2:  2 name2  0.5  1.5
fread(csv2, col.names = c("id", "name", "col1", "col2"), colClasses = list(integer = 1, 
  character = 2, numeric = c(3, 4)), select = 1:4)
#>    id  name col1 col2
#> 1:  1 name1  0.5  1.5
#> 2:  2 name2  1.5  2.5
```

**Comment by HughParsonage** [comment]
I don't think it's possible currently. Does `rbindlist(fill = TRUE)` solve the underlying problem. I can't see a use case for adding an empty column otherwise?

**Comment by renkun-ken** [comment]
`rbindlist(fill = TRUE)` solves the problem when each file is read with proper parameters, i.e. `csv1` is read with the first 4 columns and `csv2` is read with the first 5 columns, and then a list of `data.table`s with different number of columns can be put together with the missing column in `csv1` forced to appear. However, correctly reading each file needs to detect which format it is in the first place. That's exactly the problem this issue is addressed.

**Comment by franknarf1** [comment]
Seems like something best handled by a wrapper (read first row, count fields, use if/else to read the rest of the file based on # fields)? Or more cleanly, use a table to specify the rules:

```
library(data.table)
csvs = c(
  "1,name1,0.0,1.0\n2,name2,0.5,1.5",
  "1,name1,0.5,1.5,20180103093025\n2,name2,1.5,2.5,20180103093027"
) 

rulesDT = data.table(
  ncol = 4:5, 
  col.names = list(
    c("id", "name", "col1", "col2"), 
    c("id", "name", "col1", "col2", "localtime")
  ), 
  colClasses = list(
    c("integer", "character", "numeric", "numeric"),
    c("integer", "character", "numeric", "numeric", "character")
  )
)
setkey(rulesDT, ncol)

readfun = function(s, r = rulesDT){
  nc = length(fread(s, nrow = 1))
  r[.(nc), do.call(fread, c(list(s), lapply(.SD, unlist, recursive = FALSE))), 
    .SDcols = setdiff(names(r), key(r))]
}

(res <- lapply(csvs, readfun))
```

which gives

```
[[1]]
   id  name col1 col2
1:  1 name1  0.0  1.0
2:  2 name2  0.5  1.5

[[2]]
   id  name col1 col2      localtime
1:  1 name1  0.5  1.5 20180103093025
2:  2 name2  1.5  2.5 20180103093027

Warning message:
In require_bit64() :
  Some columns are type 'integer64' but package bit64 is not installed. Those columns will print as strange looking floating point data. There is no need to reload the data. Simply install.packages('bit64') to obtain the integer64 print method and print the data again.
```

You can `rbindlist` the result if that's the next step.

The case of extra trailing columns doesn't seem so general that fread should handle it directly. I might have a pair of file formats with proper headers "B,C,D,E" and "A,B,C,D,E" where the additional column comes at the start, for example.

**Comment by renkun-ken** [comment]
Thanks @franknarf1. That's how I handle this currently, `fread(file, nrows = 0)` and count the number of columns to determine which format to apply.
