### ISSUE TITLE
[Request] Could you tag each version in Git?

### ISSUE THREAD

**Issue by twang2218** [Rdatatable/data.table#2550]
There is no git tag in this repo, so it's hard for us to check the source code of certain version of this project, and it's also hard to find out that which version introduced certain functions or lines.

Could you tag each version and push the tags to GitHub? Thank you.

**Comment by HughParsonage** [comment]
Thanks for the request. I think it's reasonable.

In the meantime, you might find the CRAN GitHub mirror useful. It includes every version of `data.table` on CRAN. Indeed, it might be more useful as the only commits are those synchronized with submissions.

https://github.com/cran/data.table

e.g. In which version was a particular function introduced? Answer:

https://github.com/cran/data.table/blame/master/NAMESPACE

**Comment by jangorecki** [comment]
done: https://github.com/Rdatatable/data.table/tags

**Comment by twang2218** [comment]
Great, thank you.
