### ISSUE TITLE
multithreaded fwrite writes result nThread times

### ISSUE THREAD

**Issue by wookietreiber** [Rdatatable/data.table#2553]
## TL;DR

```r
fwrite(table, file = "foo.csv", nThread = 1)
fwrite(table, file = "bar.csv", nThread = 32)
```

```console
$ ls -1hs foo.csv bar.csv
7.2G bar.csv
228M foo.csv
```

7.2G is the same size as 228M x 32. It appears that fwrite writes the output once per thread.

## Description

I have written a small script to convert rds to csv:

```r
#!/usr/bin/env r

suppressMessages(library(docopt))
suppressMessages(library(data.table))

doc <- "usage: rds2csv [-t THREADS] RDS CSV
RDS                     input rds file
CSV                     output csv file
-t --threads THREADS    amount of threads to use [default: 1]
"

opt <- docopt(doc)

threads <- as.integer(opt$threads)

table <- readRDS(opt$RDS)

fwrite(table, file = opt$CSV, nThread = threads)
```

I had an example csv file and converted that to rds to test the script:

```console
$ ls -1hs example.*
228M example.csv
 91M example.rds
```

I ran the script twice:

```console
$ rds2csv       example.rds foo.csv
$ rds2csv -t 32 example.rds bar.csv
```

Then, I luckily happen to have checked the file sizes before giving this to my users:

```console
$ ls -1hs example.* foo.csv bar.csv
7.2G bar.csv
228M example.csv
 91M example.rds
228M foo.csv
```

Quick calculation regarding the file sizes:

```console
$ bc <<< '(7.2 * 2^30) / (228 * 2^20)'
32
```

FYI: The header appears only once (`year_2015` occurs only in header):

```console
$ grep -c year_2015 example.csv
1
$ grep -c year_2015 bar.csv
1
```

## My Environment

```console
$ cat /etc/centos-release
CentOS release 6.9 (Final)

$ R

R version 3.4.2 (2017-09-28) -- "Short Summer"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(data.table)
data.table 1.10.4.2
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /gpfs0/global/local/lapack/gcc/3.6.1-1/lib/libblas.so.3.6.1
LAPACK: /gpfs0/global/local/lapack/gcc/3.6.1-1/lib/liblapack.so.3.6.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] data.table_1.10.4-2

loaded via a namespace (and not attached):
[1] compiler_3.4.2
```

**Comment by wookietreiber** [comment]
## Further Tests 1

I have just tested this with `data.table 1.10.4.3` on the same system, which yields the same bug.

**Comment by wookietreiber** [comment]
## Further Tests 2

I have just tested this locally on my machine (not on our HPC cluster), which is an up-to-date Arch Linux:

```console
$ uname -r
4.14.11-1-ARCH

$ R

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(data.table)
data.table 1.10.4.3
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas_sandybridgep-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C
 [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8
 [7] LC_PAPER=en_US.utf8       LC_NAME=C
 [9] LC_ADDRESS=C              LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] data.table_1.10.4-3

loaded via a namespace (and not attached):
[1] compiler_3.4.3
```

My machine has only 8 CPU cores:

```console
$ rds2csv      example.rds foo.csv
$ rds2csv -t 8 example.rds bar.csv
```

Here it works as expected:

```console
$ ls -1hs foo.csv bar.csv
228M bar.csv
228M foo.csv
```

---

Possible impactful differences:

- OS kernel (unlikely)
- glibc
- R 3.4.2 vs R 3.4.3

**Comment by wookietreiber** [comment]
FYI: On the CentOS cluster `fwrite` shows:

```
Written 9.2% of 731759 rows in 2 secs using 32 threads. anyBufferGrown=no; maxBuffUsed=45%. Finished in 19 secs.
```

... counting up. This didn't show on my machine nor when run single-threaded, I don't know if that means anything.

**Comment by HughParsonage** [comment]
Are you able to share `table`? 

When you covert `rds` to `csv` do you run `alloc.col` as recommended by the FAQ?

**Comment by wookietreiber** [comment]
How do I *share a table*? What FAQ are you talking about? I'm using the script as written above in the description.

**Comment by HughParsonage** [comment]
Are you able to provide us with a means to load `table` ourselves (like a link to the `rds` filke)? So we can reproduce the problem. 

By the FAQ, I meant the [FAQ vignette](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html). In particular:

> ## Reading data.table from RDS or RData file
> `*.RDS` and `*.RData` are file types which can store in-memory R objects on disk efficiently. However, storing data.table into the binary file loses its column over-allocation. This isn't a big deal – your data.table will be copied in memory on the next by reference operation and throw a warning. Therefore it is recommended to call `alloc.col()` on each data.table loaded with `readRDS()` or `load()` calls.

**Comment by MichaelChirico** [comment]
If you're free to share the data publicly, try a [gist](https://gist.github.com/). If it's private data, try and exclude the irrelevant features of your data set and create a fake data set that mimics your data, but can be shared publicly; then put _that_ in a gist. The latter is a bit of an art, but the process of distilling your issue can also shed light/further details on what, exactly, is going wrong.

**Comment by mattdowle** [comment]
In short @wookietreiber what people are saying is they can't reproduce it. So all eyes on there being a problem with the `table` object you are writing.  This isn't your problem.  But the problem is likely something to do with `table`, like how it's being created.  I don't think `alloc.col()` should be needed.  That's only recommended to oil the cogs later when update-by-reference is used on a `DT` loaded from rds.

In other words,  there does seem to be a bug but we don't know where it is.

I tried to make a reproducible example like this, but it works for me : 

```
DT = data.table(A=1:1e7, B=1:1e7)
saveRDS(DT, file="/tmp/DT.rds")
```
```
DT = readRDS("/tmp/DT.rds")
fwrite(DT, "/tmp/DT1.csv", nThread=1)
fwrite(DT, "/tmp/DT4.csv", nThread=4)
```
```
-rw-r--r-- 1 mdowle mdowle  41M Jan 15 18:20 DT.rds
-rw-r--r-- 1 mdowle mdowle 151M Jan 15 18:21 DT1.csv
-rw-r--r-- 1 mdowle mdowle 151M Jan 15 18:22 DT4.csv
```

Are you able to look inside the too-big file and work out how it has gotten so big?  It is really that the output has been repeated,  or have certain strings been written out very big or garbled?  Are you able to give us the output of `str(table)` to tell us the column types and first few values.  Then we might be able to guess further.

I've never seen anything like the problem you're reporting.  If it was simply that it writes the file as many times as there threads used, then we would have had many more reports that we have as it would fail all the time.  It's pointing towards something unique about your data.

**Comment by jangorecki** [comment]
No feedback for a year, and no reproducible example. Please post reproducible example, then we re-open issue.
