### ISSUE TITLE
Sub-setting rows using is.na 

### ISSUE THREAD

**Issue by 123saga** [Rdatatable/data.table#2554]
- I was trying to subset my data based on a column if it is a null or not.

- Syntax that I am using:
`DT[is.na(col1),col2]`

- The filtering condition is not working, I still see all the rows in my output.

**Comment by MichaelChirico** [comment]
please provide a reproducible example, without that it just sounds like you've made a coding mistake. please try starting on StackOverflow. closing barring said example.
