### ISSUE TITLE
joins with type coercion: 1.5 == 1 is TRUE

### ISSUE THREAD

**Issue by MarkusBonsch** [Rdatatable/data.table#2592]
Maybe this is a known issue, but to me it came as a very bad surprise.
During a join, if `i` is coerced to integer to match `x`'s column type, 1.5 is joined to 1:
```
library(data.table)
dt1 <- data.table(x = 1L, y = 1)
dt2 <- data.table(x = 1.5, z = 2)
dt1[dt2, on = "x", verbose = TRUE]
# Calculated ad hoc index in 0 secs
# Coercing double column i.'x' to integer to match type of x.'x'. Please avoid coercion for efficiency.
# Starting bmerge ...done in 0 secs
#     x y z
# 1: 1 1 2
# 1: 1 1 2

merge(dt2, dt1, by = "x")
#    x y z
# 1: 1 1 2
```
The reason is the blind coercion to integer of dt2$x during `bmerge`. 
We should adopt the base R loic of `merge.data.frame` where the join columns get coerced to the 'highest' involved type (https://github.com/wch/r-source/blob/e690b0d6998dfbc360f0fa14492eb8648df20949/src/main/unique.c) Lines 902ff:
```
    /* Coerce to a common type; type == NILSXP is ok here.
     * Note that above we coerce factors and "POSIXlt", only to character.
     * Hence, coerce to character or to `higher' type
     * (given that we have "Vector" or NULL) */
    if(TYPEOF(x) >= STRSXP || TYPEOF(table) >= STRSXP) type = STRSXP;
    else type = TYPEOF(x) < TYPEOF(table) ? TYPEOF(table) : TYPEOF(x);
    PROTECT(x	  = coerceVector(x,	type)); nprot++;
PROTECT(table = coerceVector(table, type)); nprot++;
```

**Comment by mattdowle** [comment]
Good spot and agree.  With the caveat that it should only coerce to double if `isReallyReal()`. Otherwise, coerce the not-really-real double to int (which is the more common case in mind). Both with warning rather than just verbose.

**Comment by MarkusBonsch** [comment]
I have done a bit more extensive testing on joins with non-matching types. The table below lists the findings and my proposed change of behaviour. The proposwed changes are in line wth the proposal by @mattdowle .Code for examples can be found at the end of the post.

|type of x column|type of i column|behaviour|recommended behaviour| comment|
|---|---|---|---|---|
|integer|numeric|bug: coercion to integer so that 1.5 joins to 1| If the column in i isReallyReal, coercion to numeric with warning. If the column in i is not reallyReal, coercion to integer with warning| see example in code below|
|numeric|integer|coercion to numeric| don't change, add warning||
|integer/numeric|character|throws error|don't change||
|character|integer/numeric|throws error|don't change||
|integer|factor|bug: joins so that integer 1 joins to the first level of the factor.| Throw error| see examples|
|factor|integer|throws error|don't change||
|numeric|factor|throws error|don't change||
|factor|numeric|throws error|don't change||
|integer|logical|Same behaviour as merge.data.frame: coercion to integer so that 1 joins to TRUE, 0 to FALSE, but 2 to nothing.|don't change, add warning|see examples.|
|logical|integer|throws error| make it similar to x.int == i.bool: coercion to integer; add warning|Behaviour should always be symmetric, i.e. bool==int should behave the same way as int==bool imho.|


Here is the code to highlight the problematic cases:
```
library(data.table)
library(magrittr)
dt <- data.table(int = 1L:10L, 
                 num = (1:10) + 0.5,
                 char = as.character(1:10),
                 bool = as.logical(0:9),
                 fact = factor(letters[1:10]))
                 

## integer numeric problem
dt[dt, on = "int==num", nomatch = 0L] 
## should be empty but is:
#    int  num char  bool fact i.int i.char i.bool i.fact
#1:   1  1.5    1 FALSE    a     1      1  FALSE      a
#2:   2  2.5    2  TRUE    b     2      2   TRUE      b
#3:   3  3.5    3  TRUE    c     3      3   TRUE      c
#4:   4  4.5    4  TRUE    d     4      4   TRUE      d
#5:   5  5.5    5  TRUE    e     5      5   TRUE      e
#6:   6  6.5    6  TRUE    f     6      6   TRUE      f
#7:   7  7.5    7  TRUE    g     7      7   TRUE      g
#8:   8  8.5    8  TRUE    h     8      8   TRUE      h
#9:   9  9.5    9  TRUE    i     9      9   TRUE      i
#10:  10 10.5   10  TRUE    j    10     10   TRUE      j

## the other way round, it works fine
dt[dt, on = "num==int", nomatch = 0L] 
# Empty data.table (0 rows) of 9 cols: int,num,char,bool,fact,i.num...

## integer - factor problem
dt[dt, on = "int==fact", nomatch = 0L] 
## very questionable output: is 1 =="a" really TRUE? And is "a" an integer?
#    int  num char  bool fact i.int i.num i.char i.bool
#1:   a  1.5    1 FALSE    a     1   1.5      1  FALSE
#2:   b  2.5    2  TRUE    b     2   2.5      2   TRUE
#3:   c  3.5    3  TRUE    c     3   3.5      3   TRUE
#4:   d  4.5    4  TRUE    d     4   4.5      4   TRUE
#5:   e  5.5    5  TRUE    e     5   5.5      5   TRUE
#6:   f  6.5    6  TRUE    f     6   6.5      6   TRUE
#7:   g  7.5    7  TRUE    g     7   7.5      7   TRUE
#8:   h  8.5    8  TRUE    h     8   8.5      8   TRUE
#9:   i  9.5    9  TRUE    i     9   9.5      9   TRUE
#10:   j 10.5   10  TRUE    j    10  10.5     10   TRUE

## merge.data.frame looks more reasonable
merge(data.frame(dt), data.frame(dt), by.x = "fact", by.y = "int")
# <0 rows> (or 0-length row.names)

## The other way round, it correctly throws an error
dt[dt, on = "fact==int", nomatch = 0L] 

## integer - bool problem
dt[dt, on = "int==bool", nomatch = 0L]
## correct output, because base merge.data.frame gives same result.
#   int num char  bool fact i.int i.num i.char i.fact
#1:   1 1.5    1 FALSE    a     2   2.5      2      b
#2:   1 1.5    1 FALSE    a     3   3.5      3      c
#3:   1 1.5    1 FALSE    a     4   4.5      4      d
#4:   1 1.5    1 FALSE    a     5   5.5      5      e
#5:   1 1.5    1 FALSE    a     6   6.5      6      f
#6:   1 1.5    1 FALSE    a     7   7.5      7      g
#7:   1 1.5    1 FALSE    a     8   8.5      8      h
#8:   1 1.5    1 FALSE    a     9   9.5      9      i
#9:   1 1.5    1 FALSE    a    10  10.5     10      j

## merge.data.frame does the same thing
merge(data.frame(dt), data.frame(dt), by.x = "int", by.y = "bool")
#   int num.x char.x  bool fact.x int num.y char.y fact.y
#1   1   1.5      1 FALSE      a   2   2.5      2      b
#2   1   1.5      1 FALSE      a   3   3.5      3      c
#3   1   1.5      1 FALSE      a   4   4.5      4      d
#4   1   1.5      1 FALSE      a   5   5.5      5      e
#5   1   1.5      1 FALSE      a   6   6.5      6      f
#6   1   1.5      1 FALSE      a   7   7.5      7      g
#7   1   1.5      1 FALSE      a   8   8.5      8      h
#8   1   1.5      1 FALSE      a   9   9.5      9      i
#9   1   1.5      1 FALSE      a  10  10.5     10      j

## but base R behaviour is a bit confusing here, I find.
1:10 == TRUE
#  [1]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
as.logical(1:10) == TRUE
#  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
```

**Comment by MarkusBonsch** [comment]
I have updated the table with type conversions in the last post to reflect all combinations.

**Comment by Fablepongiste** [comment]
If type is NA in dt2 and let say character in dt1 (or any other type really for dt1), should the merge not failed and still work , assuming NA in dt2 is of type of dt1 ? 

Sometimes do not know you are getting NA, and there is no reason that column with type NA is of type logical if not NA ?

**Comment by Fablepongiste** [comment]
Is that supposed to fail ? 

```
merge(dt1, dt2, by = intersect(names(dt1), names(dt2)), all = TRUE, sort = FALSE)
dt1 <- data.table("a" = 1, b = "test")
 dt2 <- data.table("a" = 2, b = NA)
Error in bmerge(i, x, leftcols, rightcols, xo, roll, rollends, nomatch,  : 
  typeof x.b (logical) != typeof i.b (character)
```

**Comment by jangorecki** [comment]
@Fablepongiste Thanks for reporting.
Definitely NA should be coerced to NA_character_ transparently to user.
Lets add to that also special case of both fields being NAs of different type
```r
dt1 <- data.table("a" = 1, b = NA_character_)
dt2 <- data.table("a" = 2, b = NA)
merge(dt1, dt2, by = intersect(names(dt1), names(dt2)), all = TRUE, sort = FALSE)
```

**Comment by Fablepongiste** [comment]
@jangorecki Do you expect this fix to be released soon at least in develop branch ? 
Have seen issue #2734 but seems not updated from long time ?

**Comment by jangorecki** [comment]
@Fablepongiste cannot promise but we are trying to clear out PR queue, so it will be definitely on our list

**Comment by MarkusBonsch** [comment]
Interesting case @Fablepongiste. We will have to check, whether PR #2734 covers that and amend if not. Unfortunately, the PR is very old, so merging will be painful and I have very limited time at the moment. I will nonetheless try to see after it in the next weeks.

**Comment by mattdowle** [comment]
I managed to take a look. #2734 now covers all-NA coercion. Thanks @Fablepongiste for raising.
