### ISSUE TITLE
[REQUEST] Print only first/last few columns

### ISSUE THREAD

**Issue by vlulla** [Rdatatable/data.table#2608]
I regularly use fread to read csv files which have hundreds of columns.  For cursory exploration I just print the name of the variable to see what it contains and it will print all the columns!  This makes it difficult to glance wide data.  Census bureau demographic files are an example of wide data format that I commonly use.

Is it possible to modify the print.data.table function to show only first/last few columns instead of all the columns?  data.table already does this for rows where only the first/last few (controlled by options variables) rows are shown with the intermediate rows represented as ---.  But there is nothing analogous for columns.  A tibble gets around this problem by printing the dimensions of the tibble first and then printing only the first 10 rows with a few columns and then listing just the column names.  Julia language does this even better, but primarily for matrices.  Try randn(150,150) in a julia repl to see what I mean.

Additionally, is it possible to list the dimension of data.table just like tibbles?  If this suggestion appears too unfavorable (I too am not convinced that this works best for data.table) the column number might be listed as a suffix to the column datatype which is controlled by the datatable.print.class option variable.

**Comment by franknarf1** [comment]
You might want to have a look at @MichaelChirico 's list of possible improvements, https://github.com/Rdatatable/data.table/issues/1523 . Part of this might fall under his number 11.

**Comment by vlulla** [comment]
Yes!  And it appears that it was discussed in https://github.com/Rdatatable/data.table/issues/1497 too but there doesn't seem to be any consensus yet about how to do this.  Thank you for pointing out Michael's possible improvements list.

**Comment by mattdowle** [comment]
Implemented by #4074 which closes the earlier #1497.
Please check it out in dev before release.
