### ISSUE TITLE
fread colClasses support for POSIXct

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2610]
Currently fread colClasses does not support conversion to POSIXct:
```r
str(data.table::fread("c1,c2\n2018-01-31 03:16:57,b", colClasses=c(c1="POSIXct")))
#Classes 'data.table' and 'data.frame':	1 obs. of  2 variables:
# $ c1: chr "2018-01-31 03:16:57"
# $ c2: chr "b"
# - attr(*, ".internal.selfref")=<externalptr> 
```
related to #1450
once solved update: https://stackoverflow.com/questions/41903259/data-table-colclasses-conversion-to-posixct

**Comment by MichaelChirico** [comment]
Haven't quite closed the SO question since it refers to `as.POSIXct` being slow on huge data... Related to #587 then?

**Comment by mattdowle** [comment]
Yes: #1450 outstanding.
