### ISSUE TITLE
R-devel change to as.list.Date

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2616]
From CRAN:

This is because now
R> as.list.Date
function (x, ...)
lapply(unclass(x), .Date)
for performance reasons, which no longer preserves the whole class
vector.  Hence in your
  test(1562.1, as.list(d), lapply(as.list(as.Date(d)), as.IDate))
with d an IDate, as.list now gives a Date object.
The simplest fix would be adding something like
  as.list.IDate <- function(x) lapply(unclass(x), as.IDate)
to data.table.

----

Matt replied : 

I don't think this is a good change in R-devel, though. as.list() should not drop class information. I can't see this mentioned in R-devel NEWS (https://cran.r-project.org/doc/manuals/r-devel/NEWS.html).  Is the change discussed somewhere?

----

This is why PRs are now failing tests against R-devel.  For now I'll disable test 1562.1 in dev and revisit before release.

**Comment by HughParsonage** [comment]
Perhaps this mail thread?
https://stat.ethz.ch/pipermail/r-devel/2018-February/075504.html

**Comment by mattdowle** [comment]
Thanks for that thread link.  Yes, likely related I guess.
It's now reverted in R-devel so in a few days I'll turn back on the test and this issue goes away.
