### ISSUE TITLE
R-devel change to sequence vectors

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2619]
From CRAN:

> r74244 commits changes to generate compact arithmetic sequences
> (e.g. 1:n) via the ALTREP framework. This breaks one of your tests in
> data.table that assumes things about these vectors that are no longer
> true.

This sounds like a very welcome change that data.table will need to accommodate and pass R-devel before next release to CRAN.

GitHub PRs will start failing due to this as soon as R-devel daily snapshot updates.

**Comment by MichaelChirico** [comment]
yes, very welcome! R is sorely missing a companion to Python 3's `xrange` iterators

**Comment by HughParsonage** [comment]
Any clue as to what that test might be?

**Comment by mattdowle** [comment]
It seems as though we are already passing R-devel which now has compact sequences in place, with no changes needed.  That's because the compact sequences get expanding upon first touch,  otherwise legacy code using R's C API would break.  Packages like data.table will have to start using the new C API functions for compact vectors, in order to keep them compact.  This info is thanks to Luke Tierney.

The particular test that broke is 1373 which tested the contents of .Internal(inspect()).  I'll turn it back on with the new understanding to close this issue.

If anybody wants to see the new compact vectors,  Rdevel's `.Internal(inspect())` now displays a `(compact)` label for them.
