### ISSUE TITLE
`:=` gives error within package

### ISSUE THREAD

**Issue by desk165** [Rdatatable/data.table#2622]
Data table is giving me this error when executing a function which uses its syntax:

`#` error in `:=`(model_1_num = model_1_num * model_1_calib, model_2_num = model_2_num *  : 
  Check that is.data.table(DT) == TRUE. Otherwise,

DT here is a data table (I tried explicitly setting this before the line giving the error).
However I don't get this error unless I'm calling the function from a package which I've built (which has data.table as an explicit dependency).  Defining the function in the global environment and running it works fine. 

I can work round this by not using data table's format, but we're trying to get everyone to use it!

`#` `example`
  
 errorFunction = function(foo){
  LiftDataTable <- data.table (model_1_num = 1:2, model_1_calib  = 1:2,
 model_2_num= 1:2, model_2_calib = 1:2)
  LiftDataTable[,':='(model_1_num = model_1_num * model_1_calib ,
                      model_2_num = model_2_num * model_2_calib)]
 return ("bar")
}

`#` `Output of sessionInfo()`
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               
 date     2018-02-12                  

Packages -----------------------------------------------------------------------------------------------------------------------------------
 package       * version    date       source        
 acepack         1.4.1      2016-10-29 CRAN (R 3.4.3)
 assertthat      0.2.0      2017-04-11 CRAN (R 3.4.3)
 backports       1.1.2      2017-12-13 CRAN (R 3.4.3)
 base          * 3.4.1      2017-06-30 local         
 base64enc       0.1-3      2015-07-28 CRAN (R 3.4.1)
 bindr           0.1        2016-11-13 CRAN (R 3.4.3)
 bindrcpp        0.2        2017-06-17 CRAN (R 3.4.3)
 checkmate       1.8.5      2017-10-24 CRAN (R 3.4.3)
 Ckmeans.1d.dp   4.2.1      2017-07-09 CRAN (R 3.4.3)
 cluster         2.0.6      2017-03-10 CRAN (R 3.4.1)
 colorspace      1.3-2      2016-12-14 CRAN (R 3.4.3)
 compiler        3.4.1      2017-06-30 local         
 data.table    * 1.10.4-3   2017-10-27 CRAN (R 3.4.3) ...

**Comment by HughParsonage** [comment]
Have you imported data.table in your package’s NAMESPACE?

**Comment by desk165** [comment]
Importing data.table explicitly for the function concerned does indeed fix this.  Thanks
