### ISSUE TITLE
R Error in as.character.factor(X[[i]], ...) : malformed factor

### ISSUE THREAD

**Issue by BartoszMU** [Rdatatable/data.table#2642]
Error in as.character.factor(X[[i]], ...) : malformed factor

Error code in R "Error in as.character.factor(X[[i]], ...) : malformed factor"

I have weekly repeated measures at multiple sites. This is the code I ran.

"mod1 <- gls(LogTSS ~ Urban+WWTP+Qs, correlation = corAR1(form = ~ Date | Site), na.action=na.omit)"

Date is formated as 11/19/2017 All the other variables are numeric

**Comment by jangorecki** [comment]
I don't see how this error is related to data.table. Closing due to lack of information. Feel free to reopen providing more details, be sure to read Support page before reopening issue.
