### ISSUE TITLE
Unclear what data types are accepted by `foverlaps()` 

### ISSUE THREAD

**Issue by sritchie73** [Rdatatable/data.table#2646]
Related to Issue #2645 

The documentation for foverlaps() states in the Details: 

> The storage.mode of the interval columns must be either double or integer. It therefore works with bit64::integer64 type as well.

However, you are able to run `foverlaps()` with intervals encoded as the Date class:

```
# Try with dates
df <- as.Date(paste0("2018-01-0", 1:9), format="%Y-%m-%d")
X <- data.table(id=1, start=df[1], end=df[4])
Y <- data.table(id=2, start=df[2], end=df[5])
setkey(X, start, end)
setkey(Y, start, end)
foverlaps(X, Y)
```
```
   id      start        end i.id    i.start      i.end
1:  2 2018-01-02 2018-01-05    1 2018-01-01 2018-01-04
```

The documentation needs updating to make it clear which data types are accepted.

**Comment by franknarf1** [comment]
The docs are accurate, though..?

```
> storage.mode(as.Date(paste0("2018-01-0", 1:9), format="%Y-%m-%d"))
[1] "double"
```

**Comment by sritchie73** [comment]
Aha, I didn't realise dates were stored as doubles internally.

**Comment by MichaelChirico** [comment]
yes, this is not separate from/is duplicate of #2645. that issue indeed must needs be addressed.
