### ISSUE TITLE
Allow column type changes when the as.* call comes at the end of a pipe chain

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2651]
From here: https://stackoverflow.com/a/49061816/3576984

I used highly functional code for the desired outcome; for such cases I think the `magrittr` syntax increases readability substantially. I would have written the answer as:

```
library(magrittr)
DT[ , c := gsub('[][]', '', c) %>% 
      strsplit(',', fixed = TRUE) %>%
      lapply(as.integer) %>% as.list]
```

But this still fails on column type mismatch despite explicit use of `as.list`. The version where we force `as.list` to the top of the call list looks odd:

```
DT[ , c := as.list(
  gsub('[][]', '', c) %>% 
    strsplit(',', fixed = TRUE) %>%
    lapply(as.integer)
)]
```

And the pure R version is quite unreadable:

```
DT[ , c := as.list(lapply(
  strsplit(gsub('[][]', '', c), ',', fixed = TRUE),
  as.integer))]
```

**Comment by franknarf1** [comment]
This works fine and seems to be what your code is meant to achieve (create a list column, right?):

```
library(data.table)
library(magrittr)
DT = data.table(a = 1, b = 2, c = '[1, 2, 3, 4]', d = 4)
DT[ , c := gsub('[][]', '', c) %>% 
      strsplit(',', fixed = TRUE) %>%
      lapply(as.integer) %>% list]
```

List columns need to be wrapped in `list()`. Your code is like `DT[, c := list(1,2,3,4)]` but it should be `DT[, c := list(list(c(1,2,3,4)))]`..? I see no coercion warning, while your code gives both a coercion warning and a length warning. `lapply` returns a list so `as.list` doesn't do anything extra.

Running Windows with...

```
data.table 1.10.5 IN DEVELOPMENT built 2018-03-01 18:25:07 UTC; travis
R version 3.3.3 (2017-03-06) -- "Another Canoe"
```

**Comment by MichaelChirico** [comment]
In the interim, my original approach now works:

```r
library(magrittr)
DT = data.table(a = 1, b = 2, c = '[1, 2, 3, 4]', d = 4)
DT[verbose=TRUE, ,
    c := gsub('[][]', '', c) %>% 
      strsplit(',', fixed = TRUE) %>%
      lapply(as.integer) %>%
      as.list()]
# Detected that j uses these columns: [c]
# Assigning to all 1 rows
# RHS_list_of_columns == false
# RHS for item 1 has been duplicated because NAMED==2 MAYBE_SHARED==1, but then is being plonked. length(values)==1; length(cols)==1)
```

In any case, the native pipe (`|>`) eliminates the issue by solving this at the parser level -- write the pipeline approach, parser converts it to the non-piped approach.

Closing with a new regression test.
