### ISSUE TITLE
Error on joining empty data.tables in R-devel on windows ("type must be LANGSXP at this point")

### ISSUE THREAD

**Issue by mllg** [Rdatatable/data.table#2658]
First of all, sorry that I cannot provide more detailed information about this issue - I do not have a windows box to reproduce + investigate myself. Although I'm aware that there are known problems with the current CRAN release of data.table and ALTREPs, I specifically wanted to bring this to your attention because I think that this one is easily overlooked as it only affects the combination of r-devel+win.

As you can see on the CRAN check summary for my package batchtools (<https://cran.r-project.org/web/checks/check_results_batchtools.html>), only r-devel on windows seems to be affected.
The same issue was also addressed on SO (<https://stackoverflow.com/questions/48266055/why-r-cmd-check-failed-with-weird-error-in-winbuilder-type-must-be-langsxp-at?rq=1>). 

I can confirm that avoiding empty joins seems to circumvent the issue on the winbuilder service where I then get past the first join attempt.

**Comment by mattdowle** [comment]
That's really useful - thanks!
I'm making attempts to solve in PR #2665 
It seems to pass r-devel on 64-bit Windows, though.  Just not r-devel on 32bit Windows.
Can you confirm for completeness that you're on 32bit Windows (or at least,  the 32bit build of R, which you might be running on 64bit Windows).
I see the same error on win-builder and AppVeyor, consistently.

**Comment by mllg** [comment]
> Can you confirm for completeness that you're on 32bit Windows? Or at least, the 32bit build of R, which you might be running on 64bit Windows.

Yes, was on WB with R i386. No issues with x86_64.

> I see the same error on win-builder and AppVeyor, consistently.

 :+1:
