### ISSUE TITLE
fread unable to detect all columns if starts with few columns in first line

### ISSUE THREAD

**Issue by boralprophecy** [Rdatatable/data.table#2669]
A csv file can contain either 4 columns or 6 columns in each row.

If the first row has 6 columns, fread is reading the data properly.

If first row has 4 columns and later rows have more than 4 columns, fread is not able to read the data.

Able to do this with read.table() and count.fields() - but with fread it is failing.

**Read properly**

```
no_col = max( count.fields( 'df.csv', sep = ',') )
data = read.csv( 'df.csv', fill=T, col.names=1:no_col )
```
**Failing in fread**

![image](https://user-images.githubusercontent.com/22155714/37251358-b2b7aec6-2534-11e8-9477-0e0e13d6a8b3.png)

**Data**

[df.zip](https://github.com/Rdatatable/data.table/files/1800151/df.zip)

**Comment by etienne-s** [comment]
Have you tried with the latest development version? It works for me:

```r
fread("df.csv", header = FALSE, fill = TRUE)
#                               V1                        V2            V3          V4      V5       V6
#      1: 2018-03-07T07:40:00.410Z raw/vac/00:1E:C0:3F:6A:BD 1520426400409   12.727085      NA       NA
#      2: 2018-03-07T07:40:00.949Z raw/vac/00:1E:C0:3F:6A:BD 1520426400949   12.728709      NA       NA
#      3: 2018-03-07T07:40:01.422Z raw/vac/00:1E:C0:3F:6A:BD 1520426401421   12.727085      NA       NA
#      4: 2018-03-07T07:40:01.962Z raw/vac/00:1E:C0:3F:6A:BD 1520426401962   12.727085      NA       NA
#      5: 2018-03-07T07:40:02.981Z raw/vac/00:1E:C0:3F:6A:BD 1520426402434   12.728709      NA       NA
#     ---                                                                                              
# 111478: 2018-03-07T07:49:59.953Z  raw/mg/24:71:89:E8:78:84 1520426999952    0.000000 0.00000 0.000000
# 111479: 2018-03-07T07:49:59.953Z  raw/gy/24:71:89:E8:78:84 1520426999952    0.000000 0.00000 0.000000
# 111480: 2018-03-07T07:49:59.953Z  raw/ac/24:71:89:E8:78:84 1520426999952   -0.050293 0.04541 1.220947
# 111481: 2018-03-07T07:49:59.953Z  raw/mg/24:71:89:E8:78:84 1520426999952    0.000000 0.00000 0.000000
# 111482: 2018-03-07T07:49:59.953Z  raw/bp/24:71:89:E8:78:84 1520426999953 1009.760010      NA       NA
```

**Comment by HughParsonage** [comment]
Hi @boralprophecy it seems to be working in the development version (meaning that the bug you've reported has since been fixed but the fix has not yet been released). If you've installed the latest development version and still encounter the problem, please reopen but include `sessionInfo()` and set `verbose = TRUE` in `fread` in your reply.
