### ISSUE TITLE
fill for DT[i, :=]

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2676]
```R
> DT = data.table(A=LETTERS[1:5])
> DT[ A %in% c("C","E"), val:=42][]
        A   val
   <char> <num>
1:      A    NA
2:      B    NA
3:      C    42
4:      D    NA
5:      E    42

> DT[ A %in% c("C","E"), val:=42, fill=0][]       # current behaviour
Error in `[.data.table`(DT, A %in% c("C", "E"), `:=`(val, 42), fill = 0) : 
  unused argument (fill = 0)

> DT[ A %in% c("C","E"), val:=42, fill=0][]       # desired behaviour
        A   val
   <char> <num>
1:      A     0
2:      B     0
3:      C    42
4:      D     0
5:      E    42
```

**Comment by franknarf1** [comment]
I guess you will want to generalize to accepting a named list, similar to what dplyr/tidyr has in its many functions' `fill=` args (none of their names comes to mind...). 

Example from SO with `i` and multiple columns in `:=`: https://stackoverflow.com/a/49283432/

**Comment by arunsrinivasan** [comment]
Couldn't we use the already existing `nomatch` argument here? It'd help make `nomatch` to be not specific to *joins*. Just a thought ...

**Comment by jangorecki** [comment]
excatly, #857

**Comment by MarkusBonsch** [comment]
Concerning @arunsrinivasan's proposal: this might interfere with the new optimized subsetting implementation, where subsets in i are redirected to joins and nomatch is set to 0L, assuming that `nomatch` has no significance outside joins and can be altered automatically. While this can be changed, it should be considered when implementing nomatch for non-join operations.

**Comment by jangorecki** [comment]
Closing as duplicate. `nomatch` arg is exactly about that.
