### ISSUE TITLE
Efficient update data.table to latest devel

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2681]
Skip downloading package if your git commit is latest one. This is already done in db-benchmarks: https://github.com/h2oai/db-benchmark/blob/0922840dd7bc768aa11f937128bd066fc1246986/helpers.R#L97-L118
It is very useful for scheduling data.table updates or updating from within a workflow.

**Comment by mattdowle** [comment]
But `git pull` does this already doesn't it?  

```
mdowle@MattsMac:~/GitHub/data.table$ git pull
Already up-to-date.
```

**Comment by jangorecki** [comment]
Updating pkg from R, not from git. This requires #2680 to be merged so we can access commit information in PACKAGES and DESCRIPTION files.
