### ISSUE TITLE
setindexv could accept list of characters to create multiple indices

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2695]
It could be internally optimized for speed but for now it will be enough to run in loop.
API to create index on `a` field and second index on `a, b` fields:
```r
setindexv(DT, list("a",c("a","b"))
```

**Comment by MichaelChirico** [comment]
I'm just about done writing this.... but I'm thinking, is this really any more convenient than `sapply(list('a', c('a', 'b')), setindexv, x = DT)`?

**Comment by jangorecki** [comment]
Single DT should be returned from setindexv, not matter if we set one index or many. A little more convenient :) and we are going to use same API in fread already. It would be awkward if user will learn setting up index on fread and then would be surprised it is not working with setindexv.

**Comment by MichaelChirico** [comment]
I see. so will revert to loop as well. thanks
