### ISSUE TITLE
Test 1546 generates a warning on my machine, but not on the Travis / AppVeyor

### ISSUE THREAD

**Issue by sritchie73** [Rdatatable/data.table#2718]
On my machine (OSX, R 3.4.2) test 1546 in tests.Rraw generates the following warning message:

```
Running test id 1546      Test 1546 produced 1 warnings but expected 0 
Expected: 
Observed: Coerced 'integer' RHS to 'character' to match the column's type. Either change 
the target column ['cats'] to 'integer' first (by creating a new 'integer' vector length 
15 (nrows of entire table) and assign that; i.e. 'replace' column), or coerce RHS to 
'character' (e.g. 1L, NA_[real|integer]_, as.*, etc) to make your intent clear and for 
speed. Or, set the column type correctly up front when you create the table and stick 
to it, please.
```

The test itself runs the following:

```
df1 = df2 = data.frame(cats = rep(c('', ' ',  'meow'), 5))
df2[grep("^[ ]*$", df2$cats), "cats"] = NA_integer_
test(1546, set(df1, grep("^[ ]*$", df1$cats), 1L, NA_integer_), df2)
```

This warning is not generated in integration tests when submitting PRs. 

This is a minor annoyance, but I'm wondering whats different about my setup thats causing this warning.

**Comment by MarkusBonsch** [comment]
Well, if that is comforting you: almost always when I run `test.data.table()` locally, I get errors on some tests that I didn't touch (lately, it is some fread stuff 18xx). I have no idea why, but you are not the only victim, altough 1546 runs fine in my case

**Comment by jangorecki** [comment]
Did you try R --vanilla? you can also try setting TZ=UTC and C locale

**Comment by sritchie73** [comment]
I hadn't thought of that - the test passes in `R --vanilla`.  The culprit turned out to be `options(stringsAsFactors = FALSE)`.

**Comment by MichaelChirico** [comment]
@sritchie73 actually that's a good catch... I guess tests could be robust to an error like that pretty easily. I'll file a PR quickly...
