### ISSUE TITLE
fread parse standard data.table print output

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2720]
I would find it convenient to just copy-paste data.table as printed to output.
```r
      ID  time nTest
 1: 1650 6.714    91
 2: 1652 6.376    91
 3: 1648 6.338    91
 4: 1509 5.446     1
 5: 1779 4.541    13
 6: 1646 4.060    91
 7: 1644 3.572    91
 8: 1642 3.416    91
 9: 1437 2.261   528
10: 1151 1.828     2
```
This text copy-pasted from output could be just put in `fread("[ctrl+v]")`. Something like checking `1:` in first col. Makes easier to get some small data.table copy-pasted from Rout log.

**Comment by MichaelChirico** [comment]
How sophisticated do you want it to be?

An extremely rinky-dink version is:

```
fread_rout = function(x) {
  x = strsplit(x, '\n', fixed = TRUE)[[1L]]
  x = sub('^[ \t]+', '', sub('[ \t]+$', '', x))
  x = grep('---', x, fixed = TRUE, invert = TRUE, value = TRUE)
  coln = strsplit(x[1L], '\\s+')[[1L]]
  x = transpose(strsplit(x[-1L], '\\s+'))[-1L]
  setDT(x)
  setnames(x, coln)
  x[ , (coln) := lapply(.SD, function(x) {
    num = suppressWarnings(as.numeric(x))
    if (any(is.na(num[x != 'NA']))) return(x)
    return(num)
  })]
  x[]
}
```

It won't be able to handle anything weird (embedded commas, etc). But I guess that's not the use case here.

**Comment by MichaelChirico** [comment]
we could just add this into the `text` argument's functionality perhaps?

**Comment by jangorecki** [comment]
I would close this issue, because the idea was not that smart, printing formats depends on my factors. It is easy to do function like this for the most common examples, but difficult to make it work more widely, potentially bringing many reports about something being not well parsed.
