### ISSUE TITLE
move GenomicRanges to integration tests

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2726]
Currently installing suggested dependency GenomicRanges requires in total 11 packages to be installed, including one 17MB package. To keep testing process tiny we need to handle foverlaps tests without GenomicRanges.
Related: https://github.com/Rdatatable/data.table/issues/2740

**Comment by mattdowle** [comment]
Maybe the data output from the (correct and passing, of course) tests can be saved to .Rdata files and stored in inst/tests.  Then the tests could compare to those known results directly without needing to ask GenomicRanges to recalculate them every time.  However, I don't know how many files there would be and what their total size would be.  There is a reasonable 5MB limit of the tar.gz on CRAN and we're currently at 3.1MB.

**Comment by jangorecki** [comment]
Just to clarify, GenomicRanges was removed from dependencies and its results are stored as static object in `inst/tests/test1372.Rdata` file, so we can run all required tests inside main CI without actually needing GenomicRanges anymore.
