### ISSUE TITLE
Raise warning or error when selecting duplicated columns in j

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#2728]
In seems that selecting duplicated columns from a data.table is almost always a mistake, as demonstrated in the following example:

```r
library(data.table)
dt <- data.table(x = 1:10, y = 10:1)
p1 <- dt[, .(x, y, x)]
p1
```

When the selector `.(x, y, x)` is short, it is easy to notice duplicated columns. But if tens of columns are selected in this way, it would not be easy to do so until an error occurs when the table is merged with other tables:

```r
merge(p1, data.table(x = 1:10, z = rnorm(10)))
```

```
Error in merge.data.table(p1, data.table(x = 1:10, z = rnorm(10))) : 
  x has some duplicated column name(s): x. Please remove or rename the duplicate(s) and try again.
```

I'm not sure if there's a particular reason not to raise an warning or error in `dt[, .(x, y, x)]` in the first place.

**Comment by MichaelChirico** [comment]
there are some legitimate use cases for selecting duplicate columns. I've
done this when creating an output table, for example, one where the header
has two rows (gender and ethnicity, for example).

so, since it gets caught downstream if unintended, I think no harm no foul,
right?

maybe add a verbose message

**Comment by jangorecki** [comment]
Selecting duplicated columns is totally redundant unless you are formatting table for output, then it is perfectly valid use case. So no warnings should be raised in such case.

**Comment by jangorecki** [comment]
I am going to close this one. Feel free to put your comment here, we can eventually reopen issue if there will be more demand for that. As for printing verbose message to console, if doing so we then need to provide a switch to disable that, not forcing user to wrap into `capture.output` if they don't want to see that.
