### ISSUE TITLE
Codecov result posts immediately in PR, before test suite runs

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2731]
Has anyone else noticed that and been similarly confused?
I raised it in more detail in the codecov project :  https://github.com/codecov/support/issues/493

**Comment by mattdowle** [comment]
That test in PR #2721 actually made no difference to the code cov stats there.   But the auto comment was again updated immediately as soon as the push happened; i.e. before the test suite even ran.

**Comment by mattdowle** [comment]
Oh, wait. The code cov results did change after all in that PR as a result of the irrelevant whitespace-only commit.
**Before :** 
![screenshot from 2018-04-09 17-43-19](https://user-images.githubusercontent.com/2779998/38530797-65175834-3c21-11e8-9c23-a5240e52afb4.png)
 **After :**
![screenshot from 2018-04-09 18-09-18](https://user-images.githubusercontent.com/2779998/38530814-819b69dc-3c21-11e8-9a2c-5bd2a4a2c5ef.png)

**Comment by sritchie73** [comment]
I had a similar issue after commit 5b3cd83 in PR #2702 which addressed your request to fix the code coverage for data.table.R. The Codecov report didn't update until the subsequent commit 8b9a920 which didn't touch the test suite.

**Comment by MichaelChirico** [comment]
I haven't noticed this lately? Close? @mattdowle

**Comment by mattdowle** [comment]
Yep - seems to have been fixed. Good call.
