### ISSUE TITLE
Reduce memory usage of test.data.table

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2739]
We have been discussing with Matt offline and he suggested to call gc() in test() to measure memory usage.
![memtest](https://user-images.githubusercontent.com/3627377/38656244-e3a445e2-3e36-11e8-93aa-e814f412f48d.png)
Attached graph shows there are 3 tests which uses significantly more memory than others. If possible we should reduce memory use of those.

**Comment by mattdowle** [comment]
Very nice!  In addition to making the test suite run more robustly in cloud (AppVeyor) and on CRAN, the same technique will be useful in the benchmarks to measure space as well as time.
