### ISSUE TITLE
Remove branch CI and keep just pr CI

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2743]
When PR is checked, there are 4 jobs (2 AppVeyor for /branch and /pr,  and 2 for Travis for /branch and /push).
Branch means the branch is tested, I assume.  It might be possible that the branch is behind master which is why this might be useful.
/pr and /push means master is tested as if PR were merged into master, right?

I've never really seen branch result different to pr/push result, though.  But we have to wait for both to run which doubles the time to see if a PR passes after a push.

When non-project members do PR from a fork in their repo, I noticed (iirc) the PR just does pr/push check and not branch. Which makes sense because there is no branch in the data.table project in that case.  And that works fine and great.

@jangorecki If that's all correct, could we remove the CI for branch?  Keeping 2 out of the 4 CI jobs for /pr (AppVeyor) and /push (Travis) .  And if so, how is that change made?

**Comment by HughParsonage** [comment]
I know I shouldn't but occasionally if I don't have access to a computer where I can easily build the package, I'll use Travis-CI on branch to test something for myself before opening a pull-request. Is it just waiting for the queue to clear that's the problem?

**Comment by jangorecki** [comment]
@HughParsonage so according to new settings only appveyor build will kicks in. If you want to check Linux then you can eventually check our gitlab mirror which runs multiple Linux jobs, but you will usually need to wait few minutes for pulling new branches from github to gitlab. https://gitlab.com/Rdatatable/data.table/pipelines

**Comment by mattdowle** [comment]
@HughParsonage  Thanks for explaining that.  I haven't been using branches in that way but maybe I should a bit more.  Yes : it probably affects me more than others as I find myself waiting for CI tests to complete quite a bit.  If the queue has built up it can take a while to start.  Not a huge deal, but twice as fast (25mins down to 12mins) would come in handy on busy days, especially to see coverage results sooner.

**Comment by mattdowle** [comment]
@jangorecki  So far so good. PRs are running 2 instead of 4 jobs and it's better.

One follow up: the last commit to master (https://github.com/Rdatatable/data.table/commit/34f90fb07e3a65e3536f6f3a55993473c407b8d8) was me changing CRAN_Release.cmd only, so I didn't create a PR for it. Looks like coverage is now missing for master though, causing PR #2755 not to show coverage. At least, according to the PR #2755 code cov comment : 
![image](https://user-images.githubusercontent.com/2779998/38887894-e917c2d2-422e-11e8-90d1-8de006a77e3d.png)

Is there a way to ensure Travis (and therefore codecov stats) always runs for every commit to master, not just every merge?
