### ISSUE TITLE
When using data.table style "==" I got nothing, but I can get the result using data.frame style "==".

### ISSUE THREAD

**Issue by wasmetqall** [Rdatatable/data.table#2759]
I have a `data.table` `info_exp` using `fread`  read from a csv file.

```
info_exp=fread("data.csv")
info_exp[NAME=="王鑫"]
```
 (`王鑫` is a string of Chinese I want to find)
I got:
 `Empty data.table (0 rows) of 19 cols`
(Some of the columns work while others not)
However 
`info_exp[info_exp$NAME=="王鑫"]` got the result I want.

```
info_exp_xls=readxl::read_xls("data.xls")
info_exp_xls=data.table(info_exp_xls)
info_exp_xls[NAME=="王鑫"]
```
also gives me the ruslt I want.

**Comment by MichaelChirico** [comment]
please provide `sessionInfo()`. there was a recent bugfix regarding encoding; please try your code again from the latest development version if you haven't already.

**Comment by wasmetqall** [comment]
@MichaelChirico 
It works when I upgrade the version of data.table. THANKS A LOT!

**Comment by MichaelChirico** [comment]
All thanks I believe go to @shrektan
