### ISSUE TITLE
Setting LC_ALL=C makes 1590.4 and 1590.5 fail

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2771]
Tests 1590.4 and 1590.5 are failing in case of setting locale to C.
My current configuration:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4
```
Locale:
```r
Sys.getlocale()
#[1] "LC_CTYPE=en_IN;LC_NUMERIC=C;LC_TIME=en_IN;LC_COLLATE=en_IN;LC_MONETARY=en_IN;LC_MESSAGES=en_IN;LC_PAPER=en_IN;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_IN;LC_IDENTIFICATION=C"
```
Pass R CMD check fine.
But when I create `~/.Renviron` file:
```
LC_ALL=C
```
So my locale is now:
```r
Sys.getlocale()
#[1] "C"
```
Then 1590.4 and 1590.5 are failing.
Behavior is same on recent devel and 1.10.4.

**Comment by MichaelChirico** [comment]
glancing at this a bit.

i guess we should either set the seed or just hard-code a random ordering, no?

`sample(c(x,xx), 10, TRUE)`

**Comment by jangorecki** [comment]
@MichaelChirico hard coding would only hide the problem, not solve it, isn't it? `set.seed` make sense whenever we use `sample` but I don't think it will solve the problem.

**Comment by MichaelChirico** [comment]
yes you're right, that comment was more of an observation about an ancillary problem. I lost time to get further than that...

whatever the solution is, there's a (small) chance the vector will be in order by accident, so hard coding guarantees against that spurious success, at least
