### ISSUE TITLE
fsort segfault when vector contains NA

### ISSUE THREAD

**Issue by MarkusBonsch** [Rdatatable/data.table#2772]
On my machine, a simple fsort of a vector with NAs crashes R (not always but sometimes. There is definitely a problem with memory allocation / access on C level:
```
library(data.table)
x <- c(1, NA)
fsort(x, na.last = FALSE)
# crashes R

**Comment by mattdowle** [comment]
Agreed. Negatives are caught, but not NAs.
The top of `?fsort` does state "Experimental" and it was never mentioned in NEWS for that reason.
But it should be finished off, properly tested and made robust.
Given that it's a crash, I've added to 1.10.6 with gracefully stopping on NA.  Will implement in a future release.

**Comment by MarkusBonsch** [comment]
OK, so I'll implement the graceful stopping on NA and include it in the tests for the time being.

**Comment by mattdowle** [comment]
Oj I see. Yes redirecting to `forderv` would be better. Great.
