### ISSUE TITLE
Problem with set and parallel - Fixed

### ISSUE THREAD

**Issue by bkmontgom** [Rdatatable/data.table#2775]
This is similar to #755 or #2482, but I thought it was worth posting because the connection with parallel processing was new.
I learned that clusterExport() of a data.table strips the over-allocation, and will therefore throw an error when set() is used to create new columns.
This can be overcome by using setDT() within the parallel threads.
```
library('data.table')
library('parallel')

a <- data.table(x = 1:3, y = letters[1:3])

cl <- makeCluster(2)
invisible(clusterEvalQ(cl, library(data.table)))
clusterExport(cl, varlist = 'a')

# b <- lapply(1:2, function(d) set(a, j = 'z', value = d))  # works, but z's are both 2
# b <- parLapply(cl, 1:2, function(d) set(a, j = 'z', value = d))  # error - like #755 or #2482
b <- parLapply(cl, 1:2, function(d) set(setDT(a), j = 'z', value = d))  # fixed
# b <- parLapply(cl, 1:2, function(d) a[, z := d])  # also fine
b

stopCluster(cl)
```

**Comment by jangorecki** [comment]
I think we can close it. There is not much we can do. It is similar to what users have to do after using `readRDS`. Thanks for providing solution.
