### ISSUE TITLE
Add clang-tidy to CI

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2781]
As suggested by @michaelquinn32 here: https://github.com/Rdatatable/data.table/pull/2738#issuecomment-380888101

**Comment by jangorecki** [comment]
https://clang.llvm.org/extra/clang-tidy/

This could be added on top of our current clang test job: https://github.com/Rdatatable/data.table/blob/685d51d3dd0deab81c1f6e4a392a89134307fbfb/.gitlab-ci.yml#L179-L183

**Comment by MichaelChirico** [comment]
https://github.com/Rdatatable/data.table/pull/4859

Is another PR fixing an issue identified by `clang-tidy`, as evidence that we could use CI to prevent backsliding on this type of thing.
