### ISSUE TITLE
Output of na.omit changed

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2784]
Reported here, thanks @mgahan:  https://github.com/Rdatatable/data.table/commit/1fd38629ec81af80c2ff57e475ff2e7f2c55f844#commitcomment-27966734
Need to run before and after and see what changed.

**Comment by GregorDeCillia** [comment]
The changes in `na.omit` make it so, that `invert = TRUE` doesn't work if every row contains one missing value. 

Previously, the whole table was returned in this scenario. Now, the result is empty

```
d <- read.table(text = 
'
NA   2     3
1    NA    3
1    2     NA
')

setDT(d)
na.omit(d)
#> Empty data.table (0 rows) of 3 cols: V1,V2,V3
na.omit(d, invert = TRUE)
#> Empty data.table (0 rows) of 3 cols: V1,V2,V3
```
