### ISSUE TITLE
Integer arithmetic can speed up date/time functions on objects in UTC seconds

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2791]
As implemented on the [`fast_hour`](https://github.com/Rdatatable/data.table/tree/fast_hour) branch.

If someone knows a way to retrieve a timezone's offset without resorting to `as.POSIXlt`, we can make this approach fully* flexible as well.

*Well, not _fully_ flexible... there's always weird cases like [this](http://www.nas.gov.sg/blogs/archivistpick/time-zone-adjustment/).

Perhaps we can offer a `use_exact` argument (`TRUE` by default?) which will induce `as.POSIXlt` to do all the edge-case handling.

**Comment by jangorecki** [comment]
Code in `fast_hour` branch is good enough to merge.

**Comment by MichaelChirico** [comment]
I'll have to pull & push. later on
