### ISSUE TITLE
Warning: dependency 'data.table' is not available

### ISSUE THREAD

**Issue by IndrajeetPatil** [Rdatatable/data.table#2794]
One of the packages that my package relies on imports `data.table` and for a few days now my `AppVeyor` build has been failing (https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot) with the same error: 
```Warning: dependency 'data.table' is not available```

I also checked CRAN results for `data.table` (https://cran.r-project.org/web/checks/check_results_data.table.html) and it shows that there are some errors on Windows machines with the new release. Is that the reason why `AppVeyor` is throwing this error?

![image](https://user-images.githubusercontent.com/11330453/39191666-6f6a9a82-47a5-11e8-8b2f-daf05d0e9f7b.png)

**Comment by HughParsonage** [comment]
Yes, that is the reason: we hope to have a release on CRAN (and thus working on appveyor) some time in the next fortnight.

Apologies for the inconvenience.

**Comment by jangorecki** [comment]
@IndrajeetPatil If you are able to modify repositories from which your CI is sourcing dependencies you can just put `https://rdatatable.github.io/data.table` next to your CRAN repo url.
