### ISSUE TITLE
Cannot install data.table under R 3.5.0

### ISSUE THREAD

**Issue by plarson2** [Rdatatable/data.table#2797]
I recently updated to R 3.5.0 and can now no longer install data.table. 

What should I do?

install.packages("C:/Users/owner/Downloads/data.table_1.10.4-3.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/owner/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'data.table' ...
**  パッケージ 'data.table' の解凍および MD5 サムの検証に成功しました 
** libs

*** arch - i386
 system(cmd) で警告がありました:  'make' not found
ERROR: compilation failed for package 'data.table'
* removing 'C:/Users/owner/Documents/R/win-library/3.5/data.table'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/Users/owner/Downloads/data.table_1.10.4-3.tar.gz’ had non-zero exit status

**Comment by jangorecki** [comment]
I had seamless installation of recent data.table and R 3.5.0 built from source. CRAN check logs are not that relevant here because they run 1.10.4-3, so any issues present there might have been resolved already. Are you still have issue installing data.table from sources having Rtools for 3.5.0 installed? You might need to install recent Rtools.

**Comment by plarson2** [comment]
It appears that Rtools is not available for R 3.5.0

> install.packages("Rtools")
Installing package into ‘C:/Users/owner/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Rtools’ is not available (for R version 3.5.0)

**Comment by plarson2** [comment]
Thanks. I installed the latest Rtools but nothing has changed. I still cannot install data.table.

**Comment by facorread** [comment]
Same experience here. That is why I downgraded.

**Comment by plarson2** [comment]
Hopefully it will get resolved soon.

**Comment by pierrot07** [comment]
same problem, just solved now!
1/ download and install **Rtools 3.5.0**; don't forget to check the modify **PATH** option
2/ in R type **install.packages("data.table")**
3/ you get the message: ..._Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘data.table’_
4/ then a small window opens, asking you if you want to **install from source**: click YES
5/ data table is installed from source ..._data.table_1.10.4-3.tar.gz_

now you can load Rcmdr and it works
I hope it will work with you!!!!

**Comment by JoeFernando** [comment]
Had the same problem. I'm on a Windows 10 machine. This is how I solved it:
* uninstall rtools via "Add/Remove Programs"
* remove devtools from your library - remove.packages("data.table")
* Go to environmental variables and remove all rtools paths (see point 5 in link https://www.biostat.wisc.edu/~kbroman/Rintro/Rwinpack.html) / you need to remove from both "user variables" and "System variables" - I had rtools path in both.
* download the latest rtools and install
* In the installation selection menu check the "PATH" - super important
* once done, go back to environmental variables and check if you can see rtools
* then in r remove.packages("data.table")
* library(devtools)
* install_github("Rdatatable/data.table", build_vignettes=FALSE)
You should be good to go.....

**Comment by jangorecki** [comment]
@JoeFernando if you are building from source you don't need to use `devtools::install_github`, use
```r
install.packages("data.table", repos="https://Rdatatable.github.io/data.table")
```
instead. If you use `install_github` you always install latest master, when you use our repo you install latest master that passed R CMD check. Unless you are developing data.table the latter should be preferred.

**Comment by mattdowle** [comment]
But @jangorecki these are Windows users.  Please give up on installing from source.  Go straight to asking them to click the AppVeyor compiled and tested binary, like I did here : 

https://stackoverflow.com/a/50031325/403310

I linked to the tweet there, and included the graphic.  See the comments to the answer: Windows users who have upgraded to R 3.5 need to click the R_VERSION=r_devel one and not the the R_VERSION=r_release one.  Until AppVeyor updates to R 3.5, and then it won't matter which one they click.

**Comment by jangorecki** [comment]
@mattdowle I was not aware that R-devel binaries will work on R 3.5. Good to know

**Comment by HughParsonage** [comment]
They 'work' but emit a warning that they were built under a different version, so will fail R CMD check for example.

**Comment by plarson2** [comment]
@JoeFernando THANK YOU. Works!

**Comment by jangorecki** [comment]
1.10.0 binaries are available from CRAN already.

**Comment by aadler** [comment]
Some of us on Windows still prefer to build from source to take advantage of machine-specific optimizations.
