### ISSUE TITLE
Travis error installing devtools due to R 3.5

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2801]
Last master check [here](https://travis-ci.org/Rdatatable/data.table/jobs/372150832#L2095) fails with : 
```
Error: package ‘devtools’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Execution halted
```

@jimhester aware and fixed yesterday already (thanks!) : 
https://github.com/travis-ci/travis-build/commit/b78ea1c1fdd62ebb9f3dafaf710a8575f690a0e7
So I'm not sure why we're seeing a fail today. Is each commit to Travis-build master immediately used by R packages on GitHub using Travis (I thought so)? Or maybe the attempted fix doesn't quite work, needs time to update cache, or we need to change something in our travis.yml (e.g. should we remove `cache: packages`, and then put it back to force the update of the cache perhaps)?

For now, I'll proceed to merge PRs with Travis on GitHub in error status. AppVeyor is passing and enough to proceed.

**Comment by mattdowle** [comment]
Lucky me! Workaround worked.

**Comment by elcega** [comment]
Hi, 

I am having the same issue as initially posted.

Could you explain in a bit more detail what did you do to re-install or make data.table work on R 3.5?

Thanks,

Elena

**Comment by jangorecki** [comment]
@elcega all Matt did is explained in git history, see 3deeb3849e2bc8037b0c7dbdd2d73c2035ada6ee
