### ISSUE TITLE
Can't use / install / update data.table after moving to R 3.5

### ISSUE THREAD

**Issue by dl7631** [Rdatatable/data.table#2817]
Never had problems with data.table before (I am on Windows).
After migrating to R 3.5.0, I can't use it / install it.

![image](https://user-images.githubusercontent.com/28024034/39486054-dbf2beac-4d48-11e8-8bba-0e7d10880954.png)
![image](https://user-images.githubusercontent.com/28024034/39486091-fb55a96c-4d48-11e8-9ba5-c390914d99a2.png)

Advice?

**Comment by mattdowle** [comment]
Sorry about this. Please see the notice at the top of our homepage.
https://github.com/Rdatatable/data.table/wiki

**Comment by dl7631** [comment]
Thank you! Will switch back to R 3.4.4 in the meantime.

**Comment by dl7631** [comment]
I have Rtools. So, how do I install data.table vai RTools?

**Comment by MichaelChirico** [comment]
hopefully my Q&A here is instructive:

https://stackoverflow.com/questions/33179156/installing-a-package-offline-from-github

**Comment by jangorecki** [comment]
@dl7631 FYI data.table 1.11.0 windows binaries are already on cran.
installing devel data.table (no technically always "latest", but "latest" that passed basic CI builds and checks) with Rtools is as easy as:
```
install.packages("data.table", type = "source", repos = "https://Rdatatable.github.io/data.table")
```
Be sure to have Rtools properly configured to be found on `PATH`.
