### ISSUE TITLE
Error: SETLENGTH() cannot be applied to an ALTVEC object.

### ISSUE THREAD

**Issue by HughParsonage** [Rdatatable/data.table#2820]
On Linux I get an error in a package which imports `data.table` for R-dev only:

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

```r
out <- data.table(tex_group = c(0L, 1L, 1L))
out[, z1 := .GRP, by = "tex_group"]
#> Error in `[.data.table`(out, , `:=`(z1, .GRP), by = "tex_group") : 
#>   SETLENGTH() cannot be applied to an ALTVEC object.
#> Calls: [ -> [.data.table
#> Execution halted
```

```
$ Rscript -e 'sessionInfo()'
R Under development (unstable) (2018-05-02 r74679)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS
Matrix products: default
BLAS: /home/travis/R-bin/lib/R/lib/libRblas.so
LAPACK: /home/travis/R-bin/lib/R/lib/libRlapack.so
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base  
```

Likely culprit? https://github.com/wch/r-source/commit/e0b847422074173f06f13eea8560d897afd26e52

**Comment by mattdowle** [comment]
Yes exactly: that commit made to R-devel yesterday. CRAN maintainers let me know too. Luke made that change at the same time as data.table was accepted on CRAN so we made it on just in time. Will need to liaise with Luke.
Expected 1.11.2 to need to be on CRAN soon anyway.

**Comment by mattdowle** [comment]
All PRs will fail now because of this due to all PRs testing against latest nightly R-devel snapshot.  One option is to turn off r-devel testing on AppVeyor for now.  Let's see in a few days, depending on how hard it turns out to be.

**Comment by HughParsonage** [comment]
@mattdowle Sorry for the sloppy copy paste. Fixed now. Here's the travis build failure: https://travis-ci.org/HughParsonage/r-dev-vs-release/jobs/373807347

**Comment by HughParsonage** [comment]
I suspect it's `.GRP` rather than `c(0L, 1L, 1L)` that's affected.

**Comment by Polkas** [comment]
Hi,
I have the same problem - https://github.com/Polkas/miceFast.
Moreover this package has the same problem https://cran.r-project.org/web/checks/check_results_sstModel.html - find from Google.

The worst is that I could not reproduce it - remote error. 
My package passed R-devel Windows, travis Ubuntu and a local Windows but it has one WARNING on Debian - automatic R checks.

* using R Under development (unstable) (2018-05-03 r74693)
* using platform: x86_64-pc-linux-gnu (64-bit)
....
....
* checking re-building of vignette outputs ... [3s/3s] WARNING
Error in re-building vignettes:
  ...
Quitting from lines 98-118 (miceFast-intro.Rmd) 
Error: processing vignette ‘miceFast-intro.Rmd’ failed with diagnostics:
SETLENGTH() cannot be applied to an ALTVEC object.
Execution halted

Code:

```r
data = cbind(as.matrix(airquality[,-5]),intercept=1,index=1:nrow(airquality),
             # a numeric vector - positive values 
             weights = round(rgamma(nrow(airquality),3,3),1),
             # as.numeric is needed only for miceFast - see on next pages
             groups = airquality[,5])
data_DT = data.table(data)

# simple mean imputation - intercept at position 6
data_DT[,Ozone_imp:=fill_NA(x=as.matrix(.SD), 
                           model="lm_pred",
                           posit_y=1,
                           posit_x=c(6),w=.SD[['weights']]),by=.(groups)] %>% 
# avg of 10 multiple imputations - last posit_x equal to 9 not 10 
# because the groups variable is not included in .SD
  .[,Solar_R_imp:=fill_NA_N(as.matrix(.SD),
                           model="lm_bayes",
                           posit_y=2,
                           posit_x=c(3,4,5,6,9),w=.SD[['weights']],times=10),by=.(groups)]

data_DT[which(is.na(data_DT[,1]))[1],]
```

Thanks

**Comment by HughParsonage** [comment]
Great! I know it's more work for you, but could I request that you re-release to CRAN asap? This issue will prevent all packages that import data.table (including 4 of mine :D) from being updated. (Unless you know there are likely to be future commits to R-dev that might cause failures.)

**Comment by mattdowle** [comment]
@HughParsonage  For completeness of issue log, done:  v1.11.2 is now on CRAN.  I believe they are accepting updates and new submissions.  Let me know if not.
