### ISSUE TITLE
FR: warn/error when updating and i has duplicates

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2837]
```
DT = data.table(a = 1:5)
DT[c(1, 1, 2), a := 3:5][]
#    a
# 1: 4
# 2: 5
# 3: 3
# 4: 4
# 5: 5
```

It seems the final element to be assigned (here 4 corresponds to the second instance of 1 in `i`). Not clear what the right behavior is in this case; my guess is most often it's a user mistake, hence a warning. But also possibly an error since "correct" behavior is ambiguous.

**Comment by MichaelChirico** [comment]
not possible to use a hash table to say "seen"/"not seen" at each element?

what about an option to green light the speed hit?

also in the case of a keyed subset, the cost is trivial

**Comment by franknarf1** [comment]
Somewhat related: the same problem during a join https://github.com/Rdatatable/data.table/issues/2022

Fwiw, I find that I use both joins and Michael's approach, since often

```
# from the OP
mDT = data.table(row = c(1,1,2), new = 3:5)
DT[mDT$row, a := mDT$new]
```

is more expedient than adding a row-number column...

```
# adding a column and doing a join
mDT = data.table(row = c(1,1,2), new = 3:5)
DT[, row := .I]
DT[mDT, on=.(row), a := i.new]
```

so my code is vulnerable to both idioms until/unless I add a dupe check, `anyDuplicated(mDT, by=on_cols)` or something.

**Comment by jangorecki** [comment]
if we want to add so many checks we should also collect more attributes. We already keep info if object is sorted, we can also put info if any is NA, or if there are duplicates. So at least we can reduce overhead related to extra checks.

**Comment by MichaelChirico** [comment]
Related: #2879. Agree with Pasha that potential speed hit should be the primary consideration re: whether to implement this. At a minimum, we should make sure there's a quick blurb in `?data.table` highlighting the existing behavior.
