### ISSUE TITLE
printing of POSIXct should (could?) include tz info if it's there

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2842]
```
DT = data.table(
  t1 = as.POSIXct('2018-05-01 12:34:56', tz = 'UTC'),
  t2 = as.POSIXct('2018-05-01 12:34:56', tz = 'Asia/Singapore')
)
DT
#                     t1                  t2
# 1: 2018-05-01 12:34:56 2018-05-01 12:34:56
DT$t1
# [1] "2018-05-01 12:34:56 UTC"
DT$t2
# [1] "2018-05-01 12:34:56 +08"
```

The printed output makes `t1` and `t2` seem identical, but they're not.

The same problem applies to `data.frame`s, to be fair:

```
setDF(copy(DT))[]
#                    t1                  t2
# 1 2018-05-01 12:34:56 2018-05-01 12:34:56
```

Probably timezone printing should be on by default due to the above, but at least there should be an option.

**Comment by jangorecki** [comment]
default format probably best something like +00:00, less dependent on timezone dictionaries in OSes
