### ISSUE TITLE
zero-length ITime doesn't like substr

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2852]
I'm formatting an ITime for printing out to CSV like HH:MM (truncating/throwing away seconds, mentioned in #1979). Since that's not a built-in option for fwrite, I set up the workaround of using `substr`, but it fails if my table has zero rows:

```
library(data.table)
x = as.ITime("01:00")[0L]
invisible(substr(x, 1, 5))
# Error in substring(paste("0", hh, sep = ""), nchar(paste(hh))) : 
#   invalid substring arguments
```

I'm not sure if that can be fixed or is worth fixing, but figured I'd post just in case. I wrapped in `invisible` since apparently last time (#2032) it was related to printing to console.

I'll just switch to `sprintf("%02d:%02d", hour(x), minute(x))` for now.

**Comment by MichaelChirico** [comment]
`format(x, '%H:%M')`?

**Comment by MichaelChirico** [comment]
Anyway your code doesn't error for me?

**Comment by franknarf1** [comment]
Thanks for checking, Michael. Going to close for now since I cannot test on devel from here and seems it's no-repro. 

(I still see it here on 1.10.4-3 on r 3.3.3, where the `format(x, '%H:%M')` way gives the same error for whatever reason.)
