### ISSUE TITLE
as.IDate ignores origin

### ISSUE THREAD

**Issue by DavidArenburg** [Rdatatable/data.table#2880]
Searched for this in the issues but couldn't find it. It seem like `as.IDate` ignores `origin`
```r
library(data.table) #v1.11.2
as.IDate(1000, origin = "1930-01-01")
## [1] "1972-09-27"
as.Date(1000, origin = "1930-01-01")
## [1] "1932-09-27"
```

**Comment by DavidArenburg** [comment]
I've took a look in the source code and I don't see any attention to `origin` in `as.IDate.numeric`. I think we could make a small change using something like

```r
as.IDate.numeric <- function(x, origin = "1970-01-01", ...) as.IDate(origin, ...) + x
as.IDate(1000)
## [1] "1972-09-27"
as.IDate(1000, origin = "1930-01-01")
## [1] "1932-09-27"
```

This also won't brake compatibility with the old behavior

**Comment by tdeenes** [comment]
Found the same bug today. @DavidArenburg , have you considered submitting a PR for this?
