### ISSUE TITLE
index on key column is ignored

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2883]
For consistency it should produce 0 length index attribute.
```r
library(data.table)
dt <- setDT(copy(iris))
setkeyv(dt, "Sepal.Length")
setindexv(dt, "Sepal.Length")
indices(dt)
#NULL
attr(dt, "index", TRUE)
#NULL
setkeyv(dt, NULL)
setindexv(dt, "Sepal.Length")
indices(dt)
#[1] "Sepal.Length"
attr(dt, "index", TRUE)
#integer(0)
#attr(,"__Sepal.Length")
#integer(0)
```

**Comment by MichaelChirico** [comment]
I don't fully follow why this is "for consistency"?

**Comment by jangorecki** [comment]
if you don't have just an attribute `sorted` you can create index, if you have it is silently ignored. It is still same column in same order. It doesn't cost any time or memory.

**Comment by MichaelChirico** [comment]
nvm, i see why it's for consistency now. 👍 

```
DT = data.table(ID1 = rep(1:2, each = 3), ID2 = rep(1:3, 2), key = 'ID1')
setindex(DT, ID1, ID2)
attributes(attr(DT, 'index'))
# $`__ID1__ID2`
# integer(0)

# vs 
setindex(DT, ID1)
attributes(attr(DT, 'index'))
# $`__ID1__ID2`
# integer(0)
```

**Comment by mattdowle** [comment]
It doesn't feel right, on first glance, to create some redundancy in the attributes. Could be wrong though.
Could `setkey` and `setindex` issue a warning when an existing key or index already covered the requested columns and therefore no change was made? Isn't that the root cause of the issue?

**Comment by jangorecki** [comment]
I don't think we should raise a warning, just because creating index can happens so easily.
Consider user script that is creating index, but just before creating index user did query data to just view few rows of it, so index has been automatically created. Then he continue his script and got warning, which will only raise confusion. If operation yields to expected outcome, to have an index on a column, we don't have to raise warning. There is no ordering twice or any performance lose when attempting to create index on same fields multiple times. IMO it is very safe to just silently finish call, as it is now. What is the problem now, that creating index might not actually create index, and behavior depends only on `sorted` attribute. Making this behavior consistent makes using indices more friendly for programmatic use, as there is no need to handle "exceptions" like `if(identical(key(x), ...)) ... else ...`.
