### ISSUE TITLE
Default colorder with setcolorder based off keys and indices

### ISSUE THREAD

**Issue by jsams** [Rdatatable/data.table#2895]
I'm proposing to have `setcolorder(x)` set the columns in the order specified by the keys, then remaining index columns, then the rest of the columns. I have a fork with the change already. Not sure if it would be welcome though. It makes for a nice mindless but sensible ordering to the data.

```R
DT = data.table(a = 1:3, b = 2:4, c = 3:5)
setkey(DT, c)
setindex(DT, b)
all.equal(names(setcolorder(DT)),  c("c", "b", "a"))
```

Forked branch available here https://github.com/Rdatatable/data.table/compare/master...jsams:colorder_keys

Happy to make a PR if this is something that would be welcome (and sorry for the tracker spam the past few hours). Tried setting up the tests and such, but really, I have no idea what's going on with the testing framework here to be honest.

**Comment by jangorecki** [comment]
What about multiple multi-column indices? there are not tests covering that.
If you ask how to use `test` function in `tests.Rraw` it looks like you use it correctly. If you ask about setting up test in general then use the standard R way, `R CMD build .` followed by `R CMD check data.table_1.11.3.tar.gz`.

**Comment by MichaelChirico** [comment]
Be sure also to read the [Contributing](https://github.com/Rdatatable/data.table/wiki/Contributing) page, which has some details about how to use `test`, let us know if there's some unclear points still (and, it being a wiki, feel free to edit if there's anything unclear)

**Comment by jsams** [comment]
Thanks for the pointers! Figured out how to run the tests. More tests added, a bug uncovered/fixed, and news item added. LMK if you think this is worthy of a PR and i'll make it.

**Comment by MichaelChirico** [comment]
I don't see any harm in filing a PR, especially since it seems yours is ready. Certainly the surest way to move the conversation along. 👍  thanks in advance!
