### ISSUE TITLE
Sometimes returns data.table, sometimes returns list

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2924]
I have a feeling I won't be able to make a reproducible version of this, so I'll start with a simple copy paste:

```
lookups[ , gh_address := 
           .(lapply(matches_address, function(ii) unique(ref[ii, geohash])))]
```

This code somehow results in some rows having class `data.table`, but others having class `list` (if I'm not mistaken, it should always be `list`):

```
lookups[ , .(gh_address)]
#         gh_address
#    1:       <list>
#    2: <data.table>
#    3:       <list>
#    4:       <list>
#    5:       <list>
#   ---             
# 1722: <data.table>
# 1723: <data.table>
# 1724:       <list>
# 1725:       <list>
# 1726:       <list>
```

FWIW `ref` is another `data.table`. I think part of the issue is that this code failed to turn `ref$geohash` into a `character` vector (it's still a `list` after this operation, even though all elements are length-1):

```
ref = ref[lengths(geohash) == 1L]
ref[ , geohash := sapply(geohash, `[`)]
```
I couldn't reproduce this on a toy data-set; it may be worth filing as its own issue.

**Comment by jangorecki** [comment]
please re-check on recent devel as there were some changes made how RHS list is interpretted

**Comment by MichaelChirico** [comment]
Can't remember where this example came from so I'm closing
