### ISSUE TITLE
fread fails to read a tsv file sucessfully read by read.table with fill=TRUE

### ISSUE THREAD

**Issue by dolevrahat** [Rdatatable/data.table#2928]
Hello

I have come across the following behaviour of fread:

`ann_file<-'/home/dolevr/Documents/variation_pipeline_v12/outputs/30383_index24_GGTAGC_L001-L002_R1_001.annotated.tsv'

 ann_df<-fread(ann_file)
`
Which gives the following warning:

`Warning message:
In fread(ann_file) :
  Stopped early on line 830. Expected 39 fields but found 41. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<1	1895058	C	C/A	A	Het	58.77	5	2	3	rs72894763	130																													>>`

Adding `fill=TRUE `did not alter the result. `comment.char` does not appear as an argument of fread in the documentaion and when try to follow the advice regarding ` comment.char` I get the predictable
`unused argument (comment.char = ".")` error.

Further, when I try reading the file with read.table:
 `ann_df<-read.table(ann_file,sep='\t',fill=TRUE)` All lines are read successfully.

```

sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Linux Mint 18.3

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] optparse_1.4.4    data.table_1.11.4 snow_0.4-2       

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4    getopt_1.20.2 

```

**Comment by MichaelChirico** [comment]
Hi @dolevrahat, thanks for the report. Without the file itself there may not be much we can do... if you're not able to share the file publicly but are willing to share it with Matt, please e-mail him and we can proceed from there...

At a minimum, please include the output of `fread` with `verbose = TRUE`... Feel free to re-open if you're still experiencing issues and you've done one of the above :)
