### ISSUE TITLE
Output full numeric precision for floating point numbers

### ISSUE THREAD

**Issue by traversc** [Rdatatable/data.table#2929]
This is a question/feature request, as I don't think it exists as an option.  

Example: 
```
x <- -75.1637420654296875
fwrite(data.table(a = x), file="/tmp/x.txt")
xi <- fread("/tmp/x.txt")$a

identical(x, xi)
 # FALSE
x-xi
# 1.421085e-14
```

`x` is an exact floating point value (that is, fully representable by IEEE standards) according to: https://www.h-schmidt.net/FloatConverter/IEEE754.html

I would like to write and read that value to its full precision.  

Thank you

**Comment by MichaelChirico** [comment]
have you seen this Q&A?

https://stackoverflow.com/q/3978266/3576984

**Comment by MichaelChirico** [comment]
Since here, we match the output of write.csv for floating point numbers:

https://github.com/Rdatatable/data.table/commit/6c1ed96d45df7e8b9d261a1d59a7be9789177326

**Comment by traversc** [comment]
Thanks for the links Michael.  Would it be possible in the future include an option to write full precision, or otherwise to include a format specifier e.g. "%10.5f" as in `numpy.savetxt`?

**Comment by MichaelChirico** [comment]
actually there's #2020 as well. an option may be helpful.

**Comment by MichaelChirico** [comment]
I guess this is subsumed by #2020. Test version is at #3716 if you'd like to have a go. Please follow up in #2020/#3716 or feel free to re-open if you think there's anything left uncovered here... thanks!
