### ISSUE TITLE
Reorder and/or nest list returned by shift

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2932]
I've got a week-level `data.table` like:

```
set.seed(02394)
DT = data.table(
  income = rnorm(10)**2,
  hours = rnorm(10)**2
)
```

I'd like to count the rolling 3-week average wage (total income in 4 weeks / total hours in 4 weeks), for which the clear candidate to start with is:

```
DT[ , shift(.(income, hours), 0:2)]
#             V1         V2        V3           V4           V5           V6
#  1: 1.33820392         NA        NA 1.2377758767           NA           NA
#  2: 3.97688720 1.33820392        NA 0.4012312060 1.2377758767           NA
#  3: 1.14375274 3.97688720 1.3382039 2.3425237847 0.4012312060 1.2377758767
#  4: 1.83867033 1.14375274 3.9768872 2.5081968996 2.3425237847 0.4012312060
#  5: 1.86013992 1.83867033 1.1437527 0.0103398837 2.5081968996 2.3425237847
#  6: 0.46078651 1.86013992 1.8386703 0.0006115426 0.0103398837 2.5081968996
#  7: 3.70388940 0.46078651 1.8601399 0.0713339318 0.0006115426 0.0103398837
#  8: 0.62650574 3.70388940 0.4607865 0.0427792309 0.0713339318 0.0006115426
#  9: 0.07577299 0.62650574 3.7038894 2.6584709238 0.0427792309 0.0713339318
# 10: 1.07718661 0.07577299 0.6265057 0.1220792874 2.6584709238 0.0427792309
```

Isn't this output format a bit unintuitive? I would have expected either (1) a length-2 list where each element is a length-3 list or (2) a length-3 list where each element is a length-2 list.

This could easily be `unlist, recursive = FALSE`'d to get the above output format (perhaps even as an argument to shift).

Why this is strange is that with this output format, I've got to do arithmetic gymnastics to get my desired output:

```
DT[ , rolling_avg_wage :={
  v = shift(.(income, hours), 0:2)
  Reduce(`+`, v[1:3])/Reduce(`+`, v[4:6])
}][]
#         income        hours rolling_avg_wage
#  1: 1.33820392 1.2377758767               NA
#  2: 3.97688720 0.4012312060               NA
#  3: 1.14375274 2.3425237847        1.6222011
#  4: 1.83867033 2.5081968996        1.3250903
#  5: 1.86013992 0.0103398837        0.9961947
#  6: 0.46078651 0.0006115426        1.6511917
#  7: 3.70388940 0.0713339318       73.2185649
#  8: 0.62650574 0.0427792309       41.7624228
#  9: 0.07577299 2.6584709238        1.5891919
# 10: 1.07718661 0.1220792874        0.6302719
```

(e.g. `DT[5L, rolling_avg_wage]` is (1.86+1.84+1.14)/(.01+2.51+2.34) ~ .996)

I think it a bit more natural for this code to read as:

```
DT[ , rolling_avg_wage :={
  v = shift(.(income, hours), 0:2)
  # first element is as v[1:3] above
  Reduce(`+`, v[[1L]])/Reduce(`+`, v[[2L]])
}][]
```

Alternatively, it would be helpful for the output to be named predictably, so that we could use (e.g.) `grep` to select the list elements as appropriate, e.g.

```
names(v) == c('income_0', 'income_1', 'income_2', 'hours_0', 'hours_1', 'hours_2')
```

(also hopefully this particularly use case is made obsolete by Jan's work on https://github.com/Rdatatable/data.table/tree/roll)

**Comment by jangorecki** [comment]
> Isn't this output format a bit unintuitive? I would have expected either (1) a length-2 list where each element is a length-3 list or (2) a length-3 list where each element is a length-2 list.

then it wouldn't play well with `:=` to add shifted columns to existing data.table

> This could easily be `unlist, recursive = FALSE`'d to get the above output format (perhaps even as an argument to shift).

argument to shift seems to be best to achieve what you need. Similarly there is `flatten` argument in `split` method which indicates if results should be nested lists of just single list (when split by multiple columns).

As of now what seems to be best way deal with it is to call `shift` twice, it is very fast so should not give much performance penalty.

**Comment by franknarf1** [comment]
Not sure if you'll like this syntax any better, but there's ...

```
DT[, res := setDT(lapply(.SD, function(x) Reduce(`+`, shift(x, 0:2))))[, income/hours], .SDcols = c("income", "hours")]
```

or make a helper function:

```
flat_shiftDT = function(d, ...) setDT(lapply(.SD, function(x) Reduce(`+`, shift(x, ...))))

DT[, res := flat_shiftDT(.SD, 0:2)[, income/hours], .SDcols = c("income", "hours")]
```

**Comment by MichaelChirico** [comment]
Any reason we couldn't build the list element names like we do for `dcast`? `grep`ing would be an acceptable solution, I reckon

**Comment by jangorecki** [comment]
Rolling sum is better to do using frollsum these days.
Regarding shift option to return nested list, we could provide an argument to control that, same as `split(..., flatten=TRUE)` - https://rdatatable.gitlab.io/data.table/library/data.table/html/split.html

**Comment by jangorecki** [comment]
> Alternatively, it would be helpful for the output to be named predictably, so that we could use (e.g.) grep to select the list elements as appropriate, e.g.

This is actually now possible using `give.names=TRUE` and providing named list on input. Therefore problem described by Michael can be more easily addressed, possibly closing this issue.

**Comment by MichaelChirico** [comment]
`give.names=` is indeed a huge help & at least offers a programmatic way to deal with issue that's readable / doesn't require looking up `?shift` every time.

OTOH I think there are still two places we could make this friendlier:

 - Auto-name list input for `give.names`:

    ```r
    names(DT[ , shift(.(income, hours), 0:2, give.names=TRUE)])
    # [1] "V1_lag_0" "V1_lag_1" "V1_lag_2" "V2_lag_0" "V2_lag_1" "V2_lag_2"
    ```

    Could be auto-named to `.(income = income, hours = hours)` like we do elsewhere in `j`
 - `flatten=` does seem useful still, it allows a more consistent input->output mapping that's more flexible.

Filing those both as follow-ups given the time elapsed from this first issue & interim improvements to `shift()`/rolling calculations generally.

**Comment by MichaelChirico** [comment]
Closing with pointers to #6035 and #6036
