### ISSUE TITLE
Behaviour of rollends when performing rolling join

### ISSUE THREAD

**Issue by hpschrei** [Rdatatable/data.table#2933]
I tried to do a rolling join in the data.table package in R close to the example below. I understand that setting rollends to c(FALSE, FALSE) indicates that values falling before the first value or after the last value for a group should not be rolled.

However, it is unclear to me why the last value itself is not being included in the output of the example below, that is, why does 2018-05-31 have a value of NA instead of 1.5 in the example below. I understand that the value of 2018-06-30 is NA, as the last value should not be rolled forward.

Is the below desired behavior of rollends? I would have expected the last value to not be rolled forward but still included in the rolling join.

### Minimal reproducible example

`tableB <- data.table(DT = c("2018-01-31", "2018-02-28", "2018-03-30", "2018-04-30", "2018-05-31", "2018-06-30"))`
`tableA <- data.table(DT = c("2018-02-23", "2018-05-09"),
                 value = c(0.5, 1.5))`
`tableB[, DT := as.Date(DT)]`
`tableA[, DT := as.Date(DT)]`
`setkey(tableA, DT)`
`setkey(tableB, DT)`
`tableA[, .SD[tableB, roll = Inf, on = "DT", rollends = c(FALSE, FALSE)]]`

`#            DT value`
`# 1: 2018-01-31    NA`
`# 2: 2018-02-28   0.5`
`# 3: 2018-03-30   0.5`
`# 4: 2018-04-30   0.5`
`# 5: 2018-05-31    NA`
`# 6: 2018-06-30    NA`

### Output of sessionInfo()

R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.7.4   RollingWindow_0.2 devtools_1.13.5   xlsx_0.5.7        xlsxjars_0.6.1    openxlsx_4.0.17   stringr_1.3.0    
[8] data.table_1.11.2 RJDBC_0.2-7.1     rJava_0.9-9       DBI_1.0.0        

loaded via a namespace (and not attached):
[1] Rcpp_0.12.17   digest_0.6.15  withr_2.1.2    R6_2.2.2       git2r_0.21.0   magrittr_1.5   httr_1.3.1     stringi_1.1.7  curl_3.2      
[10] tools_3.5.0    compiler_3.5.0 memoise_1.1.0 

[https://stackoverflow.com/questions/50681804/r-data-table-rolling-join-when-rollends-false-false](https://stackoverflow.com/questions/50681804/r-data-table-rolling-join-when-rollends-false-false)

**Comment by MarkusBonsch** [comment]
After a bit of testing and reading the `?data.table` man page on rollends, I think that your understanding of `rollends` is not correct, allthough your understanding seems very natural.
My understanding is:
If `rollends[2]=FALSE`, the help says that the last value (in x or tableA respectively) is not being rolled forward. This is exactly what happens in your case. You are attempting a 'last observation carried forward' ('LOCF' on the manpage) for which the default rollends is `(FALSE,TRUE)`. 

So I think everything is fine, just put `(FALSE,TRUE)`. By the way, I don't know why you are doing your join so complicated in `.SD`:
```
tableA[tableB, roll = Inf, on = "DT", rollends = c(FALSE,TRUE)]
```

I am closing as solved. Feel free to reopen if your question is not answered.
Cheers,
Markus

**Comment by MichaelChirico** [comment]
@markus maybe take a stab at clarifying the man page since you've already racked your brain on it? and/or adding the example here
