### ISSUE TITLE
`forder` not faster than `base::order`?

### ISSUE THREAD

**Issue by eliocamp** [Rdatatable/data.table#2966]
I was reading the [Introduction to data.table](https://cloud.r-project.org/web/packages/data.table/vignettes/datatable-intro.html) documentation and found this part:

![image](https://user-images.githubusercontent.com/8617595/42287981-49da19a6-7f8f-11e8-8c51-9df72b6f3a21.png)

It seems like for some reason, `base::order` is getting the same performance as `data.table::forder`.

**Comment by jaapwalhout** [comment]
That's not strange since `base::order` is the same as `data.table::order` since R 3.3.0.

[See here](https://cran.r-project.org/doc/manuals/r-release/NEWS.html) (and search the page for "Matt Dowle and Arun Srinivasan")

**Comment by MichaelChirico** [comment]
Nevertheless, we should probably update that Intro page -- claiming a speedup of `1x` is rather effete.

**Comment by MichaelChirico** [comment]
@mattdowle noticing this in the FAQ as well, maybe I don't understand but doesn't this contradict #1880?

> * All we did was to change `by` to `keyby`. This automatically orders the result by the grouping variables in increasing order. Note that `keyby()` is applied after performing the operation, i.e., on the computed result.

**Comment by jangorecki** [comment]
Keyby is made first, then original order is adjusted so docs should be updated to reflect this.
