### ISSUE TITLE
fsetequal treatment of dupes inconsistent with base

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2968]
I mean:

```
library(data.table)
DT1 = data.table(x = "yeehaw")
DT2 = DT1[c(1,1)]

fsetequal(DT1, DT2) # FALSE
setequal(DT1$x, DT2$x) # TRUE
```

(Testing on an old version of data.table, but figured I'd file since I didn't see any issues filed on it and still see [the same code up](https://github.com/Rdatatable/data.table/blob/98010eab877f4c894c96d737ff51ade64a41dd38/R/setops.R#L108), missing calls to unique/funique.) EDIT: Just upgraded and am seeing the same behavior.

**Comment by sritchie73** [comment]
I think you're right - `fsetequal()` should test whether the set of rows is equal, without regard for order or duplicates.

**Comment by sritchie73** [comment]
Just noting that `setequal()` in bases has the same problem with `data.frames`:

```
df1 <- data.frame(id=c(1, 1, 2, 3, 4))
df2 <- unique(df1)

setequal(df1, df2) # FALSE
setequal(dt1$id, df2$id) # TRUE
```

@jangorecki just noticed you've self assigned this. I've just created a new branch with plans to add the `all` argument to `fsetequals` so that `all = FALSE` ignores duplicate rows.  Do you want me to delete the branch and leave for you to resolve instead?

**Comment by franknarf1** [comment]
(I guess you know but...) `setequal` in base behaves that way not because it counts dupe rows, but because it regards columns as the elements of the set instead of rows. So `setequal(transpose(df1), transpose(df2))` is true.

It also does other wonky/undesirable stuff when not working with vanilla vectors: 

```
setequal(
  data.frame(x = 1:2, y = 3:4), 
  data.frame(w = factor(3:4, levels=1:4), z = as.character(1:2))
)
# TRUE
setequal(
  list(x = 1:2), 
  list(z = as.character(1:2))
)
# FALSE
```

**Comment by sritchie73** [comment]
Oh right, because a `data.frame` is just a `list` of columns, so its treating each column as an element in a set...

**Comment by jangorecki** [comment]
@sritchie73 go ahead, I was not planning to look at this anytime soon.
