### ISSUE TITLE
.internal.selfref warning update?

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2969]
Currently this is the `.internal.selfref` error message:

> Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or been created manually using structure() or similar). **Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table**. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. **Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting**. If this message doesn't help, please report to data.table issue tracker so the root cause can be fixed.

1. Is it still true that `key<-`, etc can incidentally induce copies in base R?
2. Should we still be referring to a version gap in R that precedes the stated R dependency?

**Comment by jangorecki** [comment]
2. definitely not

**Comment by MichaelChirico** [comment]
experience with #2970 suggests `attr<-` can still (again, oddly) create copies.

so, I'll just axe that sentence & close this.
