### ISSUE TITLE
deprecate J?

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2978]
From `?J`

> `J` : the same result as calling list. `J` is a direct alias for `list` but results in clearer more readable code.

I'm not sure if anyone is actually using this? Personally I never did, I was only using `.` since a long time back. (`.` of course being another "direct alias for `list`").

This is also noted further down in the examples:

```
DT[J("b")]      # returns the 2nd row
DT[.("b")]      # same. Style of package plyr.
```

**Comment by st-pasha** [comment]
I thought J stands for Genius...

**Comment by DavidArenburg** [comment]
I think there is no reason to deprecate it. The fact that you never used it doesn't mean other people didn't use it too. I think it can break a lot of code. For example the word2vec package uses it in [it's vignettes](http://text2vec.org/vectorization.html) and probably in the source code too

**Comment by MichaelChirico** [comment]
@DavidArenburg thanks, the point of this issue/thread wasn't to definitely start the process of depreciation, but to probe for interest. I'm aware others have different coding styles, but I hadn't even seen `J` show up "in the wild" in others' code in some time. The examples your provide are quite valuable.

**Comment by st-pasha** [comment]
From the perspective of a casual data.table user, the problem with this code:
```
  res = res[ , .(token = list(filter_pos(lemma, upos, pos_keep, pos_remove))), keyby = doc_id]
  res = res[J(id), token]
```
is that it **looks** like `J` is some unknown (to them) function of data.table. And it makes this code harder to understand than it could have been.

----
Of course, @DavidArenburg 's point is valid too: the symbol is used in practice, and deprecating would probably break lots of code without good reason.
However what we could do is *weak deprecation* instead:
* The functionality of `J` remains exactly as-is, no changes.
* If, and only if, there is an option in data.table to warn about non-idiomatic or scheduled-for-deprecation usage, then `J` may emit a warning. However this would be an opt-in from the user.
* Symbol `J` should no longer be used in any vignette / documentation / source code. The only mention in documentation can say something like `J: deprecated, exactly the same as . `.
* If we find SO question or answer that uses "J", edit it and replace with "."
* If we find a GitHub repository that uses "J", open a PR to replace it with "."

**Comment by MichaelChirico** [comment]
I think the path for deprecation would be clear, but David's usage examples are poignant (especially, David has been long-time `data.table` user who continues to use `J`). And `?J` points right to the correct help page, which already states clearly:

> `x[data.table(id)]` is the same as `x[J(id)]` but the latter is more readable. Identical alternatives are `x[list(id)]` and `x[.(id)]`.

So the path for a new/casual user from "what's this new thing `J`?" to "oh, it's just `.`, especially handy in cases when the _join_ aspect of `i` should be emphasized" is pretty straightforward.
