### ISSUE TITLE
Cannot aggregate when data.table is embedded within a function calls

### ISSUE THREAD

**Issue by rmcgehee** [Rdatatable/data.table#2991]
Here's a snippit of code that makes a data table and correctly aggregates it by pasting the "code" column together by the "id" column.
```
test <- as.data.table(data.frame(id=c(1, 1, 2), code=c("A","B","C")))
test[,list(text=paste(code, collapse="|")), by=id]

   id text
1:  1  A|B
2:  2    C
```

However, if I embed those two lines within a function AND submit the function to the R buffer using C-c C-f in ESS/emacs (and not just copy and paste it into my R session), and then run the function, I get an error ("object 'code' not found"). I'm unfortunately not able to reproduce this in a simple example without using whatever magic ESS/emacs uses to copy a function to the buffer. I can reproduce this without ESS in my large package (which is how I know this in not an ESS bug), but could not easily figure out how to share a simple reproducible example without ESS.

```
## Copy this to a scratch file and then load it into your current R session with C-c C-f in ESS/emacs
testfun <- function() {
        test <- as.data.table(data.frame(id=c(1, 1, 2), code=c("A","B","C")))
        test[,list(text=paste(code, collapse="|")), by=id]
}
testfun()
Error in paste(code, collapse = "|") : object 'code' not found
```

Apologies for the bad bug report (in the sense that it requires something beyond data.table), but perhaps someone who also uses ESS/Emacs can reproduce this and/or comment on it

I'm using data.table v1.11.4 on R 3.5.0 on Linux.

**Comment by MichaelChirico** [comment]
Almost certainly, this is a `cedta()` issue -- it looks like `[.data.frame` is being dispatched.

That said, I tried to reproduce this and failed with current data.table -- I used `C-c C-c` to run the two lines and it ran.

I also ran `C-f` while highlighting inside `testfun` to load it and then `C-j` to run the `testfun()` line to the same effect.

If you're able to reproduce again, please try `debug(data.table:::cedta)` to see what result it's giving before opening a new issue.
