### ISSUE TITLE
Error in subsetting the dataset using data.table.

### ISSUE THREAD

**Issue by rkahir712** [Rdatatable/data.table#2993]
I am trying to execute the following code.
```R
dataset_load <- fread("test.csv") 
dataset_load
win<-21
h<-5
win_hour <- win*24
for(i in 0:(n_hours-1)) {
   # subsetting dataset
  dt1<-dataset_load[, ((i*h)+1):((i+win_hour)*h), with = F]
  dt1
  datas <- data.matrix(dt1)
}
```
 I am getting following error. No. of column in Dataset are 4:
```
Error in `[.data.table`(dataset_load, , ((i * h) + 1):((i + win_hour) *  : 
  Item 5 of j is 5 which is outside the column number range [1,ncol=4]
```
Kindly do needful.

**Comment by st-pasha** [comment]
Seems like you're using a column selector, but you meant to select the rows? Try
```
dataset_load[((i*h)+1):((i+win_hour)*h), ]
```

**Comment by rkahir712** [comment]
It's not working. is there any other method to subset the dataset.?

**Comment by jangorecki** [comment]
It seems that best place for asking this types of questions is Stackoverflow. Please post question there, and ensure your example code is reproducible to get better response. Also use `data.table` tag when asking question.
