### ISSUE TITLE
Internal error in subset.c: column 2 is an ALTREP vector

### ISSUE THREAD

**Issue by fzesch** [Rdatatable/data.table#2997]
I encountered the error message  *"Internal error in subset.c: column 2 is an ALTREP vector. Please see NEWS item 2 in v1.11.4 and report this as a bug."* So I report this here. 

The error occurs with two data.tables in memory, none of them keyed. The error occurs while grouping in the second data.table with `B[, .SD[1,], mergeKey]`, after similar columns have been created in both data.tables

# Reproducible example

```
library(data.table)
B <- CJ(i2 = letters, orig = runif(50))
B[, orig := as.character(orig)]
B[, mergeKey := as.character(orig)]
B[, .SD[1L], by = mergeKey]


# Error in `[.data.table`(B, , .SD[1L], mergeKey) : 
# Internal error in subset.c: column 2 is an ALTREP vector. 
# Please see NEWS item 2 in v1.11.4 and report this as a bug.

```

# Output of sessionInfo()

> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
> [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] data.table_1.11.4
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.5.1 tools_3.5.1    yaml_2.1.19   
>
> RStudio version 1.1.453

If you need more information, I will be glad to help. Thanks for your work!

**Comment by DavidArenburg** [comment]
Was able to repro on R 3.5.1 + latest dev data.table version (v1.11.5)

**Comment by jangorecki** [comment]
I believe it was solved by recent rework of many C functions, I am not able to reproduce it. Please re-open if issue still persist.

**Comment by tiagomaie** [comment]
Problem still persists with R 3.6.0 and data.table v1.12.2

**Comment by jangorecki** [comment]
@tiagomaie could please post your console output and session info? I am not able to reproduce on 1.12.2 and recent devel also, using R 3.6.1.

**Comment by tiagomaie** [comment]
Well this is awkward... In the meantime, I re-installed both of these and I can't reproduce it anymore. I was able to reproduce the exact console output from OP except with R 3.6.1 and data.table 1.12.2.
