### ISSUE TITLE
can not read csv file

### ISSUE THREAD

**Issue by msgoussi** [Rdatatable/data.table#3000]
I download a file from the following link 
https://we.tl/Pmiuh7rfaj
then I extract it to TradeMatrixExport.csv (4 GB)
I tried to use data.table to read the header of the table, 
```R
cleanvalue <- c("" , "-", "_", "..", "...", "--", "***", "*", "n/a", "n.a.", "#VALUE!", "0", "Inf", "-Inf","NAN")
dataset <- data.table::fread("TradeMatrixExport.csv", 
                               nrows = 0, header = TRUE, 
                               skip = 0L, check.names = TRUE, fill = FALSE,
                               na.strings = cleanvalue,
                               encoding = "Latin-1")
```
It failed an RStudio is crashing.

Would you please advise.

**Comment by MichaelChirico** [comment]
Can you share the `TradeMatrixExport.csv` file directly?

Also please provide your `sessionInfo()` as well as the command line output (run `R` from your command line and evalute this code again; the command line tends to give better session crash info than RStudio IME)

**Comment by st-pasha** [comment]
@msgoussi It appears that your file contains a 1 row x 1,424,869,727 columns dataset. This is a bit too much. `fread` is designed to work for datasets having possibly billions of rows, but a reasonable number of columns; not the other way around. Trying to read a dataset with this many columns leads to memory exhaustion, and the system eventually kills the process.

There is no easy solution. It might be possible to add an option to force `fread` to ingest the data in a transposed mode -- but even that is non-trivial, and I don't recall anybody else asking for it...

**Comment by jangorecki** [comment]
@msgoussi what was the tool used to produce such data extract?

**Comment by msgoussi** [comment]
The data was sent by UNCTAD, it is trade data among countries in the World.
I will ask them to extract in a different way.

**Comment by msgoussi** [comment]
@st-pasha 
May i know which tool you used to find out the content of the file (1 row x 1,424,869,727 columns).
Thanks

**Comment by MichaelChirico** [comment]
how about

https://stackoverflow.com/questions/8629330/unix-count-of-columns-in-file

**Comment by jangorecki** [comment]
`wc -l data.csv` is easiest way IMO.
Is there any reason which justify using such format for this extract?
I think we can close it for now.

**Comment by st-pasha** [comment]
@msgoussi I used `fread` with `verbose=TRUE`. Before it dies it shows in the log that it found that many fields with `sep='\t'` but only 1 line.
