### ISSUE TITLE
fwrite unit tests fail when run in clean env

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3003]
when only data.table was installed on clean R, at the current moment cannot reproduce locally but issue [still occurs](https://gitlab.com/Rdatatable/data.table/pipelines).
```
Running the tests in ‘tests/main.R’ failed.
Last 13 lines of output:
  Running /builds/Rdatatable/data.table/bus/test-r-release-vanilla/data.table.Rcheck/data.table/tests/tests.Rraw 
  
  **** Suggested package bit64 is not installed. Tests using it will be skipped.
  
  
  **** Suggested package xts is not installed. Tests using it will be skipped.
  
  
  **** Suggested package nanotime is not installed. Tests using it will be skipped.
  
  
  Running test id 1.1      Error in if (ncol(x) == 0L && file != "") { : 
    missing value where TRUE/FALSE needed
  Calls: test.data.table -> sys.source -> eval -> eval -> test -> fwrite
  Execution halted
```
issue introduced by https://github.com/Rdatatable/data.table/commit/c0f8647a65a718da47b7f0b615d31e0a7791ffd6

I don't see any reason why this fails only for clean R session. FYI @MichaelChirico

**Comment by MichaelChirico** [comment]
do we know whether it's `ncol(x)` or `file` that's coming up `missing`?

**Comment by jangorecki** [comment]
no, but it happens also on another build where dependencies were present: https://gitlab.com/Rdatatable/data.table/-/jobs/92535046
in theory `x` can be list, then `ncol(x)` will return `NULL`, but it should not be that random.

**Comment by mattdowle** [comment]
PR looks good -- true breakage in dev, nice find. Merged.
`test()` does call `fwrite()` in one place, `if (memtest)` and a `list()` is passed to `fwrite()` there. So maybe the PR does fix this issue for that reason.

**Comment by mattdowle** [comment]
I didn't close this one.  I left it open for Jan to confirm.
I guess that GitHub accepts the word "resolve #<num>" which Jan wrote in the PR description as a synonym for "closes #<num>".

**Comment by jangorecki** [comment]
Good spot about `test` function and `memtest` branch.
`NCOL` resolved the problem.
