### ISSUE TITLE
Optimization wrong result with column names that are expressions

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3020]
Edge case reported by @DavidArenburg in [this comment](https://github.com/Rdatatable/data.table/pull/2494#issuecomment-396533079) on a merged PR.

Creating open issue so as not to forget to follow up.

If folk have a set of expressions they compute and they put the expression itself as the column name, then I can see how it arises.

**Comment by DavidArenburg** [comment]
The author of the post opened and issue on this too: #2931

**Comment by mattdowle** [comment]
Thanks. Closing as dup of #2931.
