### ISSUE TITLE
Print method for subclass makes `:=` return visible output

### ISSUE THREAD

**Issue by eliocamp** [Rdatatable/data.table#3029]
I'm extending `data.table` class and I'm having a problem. When defining a custom print method operations with `:=` print the object instead of returning it invisibly. 

``` r
library(data.table)

dt <- data.table(x = 1)

dt[, y := 1]  # No output. Correct!

setattr(dt, "class", c("someclass", class(dt)))

dt[, y := 1] # still no output. Yey!

print.someclass <- function(x, ...) {
  NextMethod("print")
  # maybe other things
}

dt[, y := 1]   # there's output, Noooo!
```

(The output doesn't seem to appear when reprexed, but it's there in interactive mode, please test)

I don't know what I'm doing wrong and I cannot find much documentation on this.

**Comment by MichaelChirico** [comment]
@mattdowle I don't quite get what all is meant to be covered [here](https://github.com/Rdatatable/data.table/blob/master/R/print.data.table.R#L28-L29):

```
length(SYS) > 3L && is.symbol(thisSYS <- SYS[[length(SYS)-3L]][[1L]]) &&
          as.character(thisSYS) %chin% mimicsAutoPrint
```

First thing that comes to mind is to look for `NextMethod` in `SYS` in addition to the `mimicsAutoPrint`... Or is there some way for downstream users to expand `mimicsAutoPrint` (on their own? Through the Issues tracker?)

**Comment by nikosbosse** [comment]
We're seeing a similar issue in our R [scoringutils](https://github.com/epiforecasts/scoringutils/). Is there any solution or steps we could take? Thank you!

**Comment by ben-schwen** [comment]
> First thing that comes to mind is to look for `NextMethod` in `SYS` in addition to the `mimicsAutoPrint`... Or is there some way for downstream users to expand `mimicsAutoPrint` (on their own? Through the Issues tracker?)

I don't think that expanding `mimicsAutoPrint` with a curated list for every custom printing is suitable in the long run. Looking for `NextMethod` on second to last position in addition with `length(class(dt))` seems like a viable approach to me

**Comment by MichaelChirico** [comment]
> Looking for NextMethod on second to last position in addition with length(class(dt)) seems like a viable approach to me

Still feels pretty clunky to me -- does that distinguish explicit `print(dt)` on a class extension?

It looks like the key to detecting the autoprint is this esoteric first entry in the call stack:

```r
sys.calls()
# [[1]]
# (function (x, ...) 
# UseMethod("print"))(x)
# ...rest of stack...
```

That's just the `print()` generic being invoked in a `substitute()`-y way:

```r
substitute(f(x), list(f = print))
# (function (x, ...) 
# UseMethod("print"))(x)

identical(sys.calls()[[1]][[1]], print)
# [1] TRUE
```

That `identical()` condition looks pretty good to me as a test of "auto-printed in interactive session" -- in particular explicit `print()` does _not_ pass that, as `sys.calls()` looks like so in that case:

```r
sys.calls()
# [[1]]
# print(dt)

# [[2]]
# print.data.table(dt)
```

Another idea is to add an argument to `print.data.table()` like `suppressPrint=FALSE` that downstreams could run to force print suppression, sent along through `NextMethod()`.

**Comment by MichaelChirico** [comment]
Hmm, is it considered intentional behavior that

```r
print(as.data.table(mtcars)[,y:=2])
```

Does not print anything? I would guess no?

**Comment by eliocamp** [comment]
`print(as.data.table(mtcars)[,y:=2])` is equivalent to `as.data.table(mtcars)[,y:=2]`, since results are printed implicitly in the console, right? Since the expected behaviour is for `:=` to suppress printing, then, yeah, it is intended.
