### ISSUE TITLE
Error in `fintersect` if the first data table contains a column called "y"

### ISSUE THREAD

**Issue by mnazarov** [Rdatatable/data.table#3034]
``` r
library(data.table)
dtA <- data.table(y = 1)
dtB <- data.table(y = 2)
fintersect(dtA, dtB)
#> Error in funique(y): is.data.table(x) is not TRUE
```
The issue is in:
https://github.com/Rdatatable/data.table/blob/659657a991d10b4ee844c8cc43bb6bb20a735a6c/R/setops.R#L70

I guess the solution could be to substitute `funique(y)` with something like
`funique(get("y", envir = parent.frame(3)))`.

**Comment by jangorecki** [comment]
Thank you for reporting, will fix for coming release.

**Comment by MichaelChirico** [comment]
good catch!
