### ISSUE TITLE
Does tryCatch of #2887 add to call overhead?

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3037]
Follow up on comment here : https://github.com/Rdatatable/data.table/pull/2891#issuecomment-419275989

**Comment by MichaelChirico** [comment]
Looks like the answer is yes; here's timings of the following script:

```
cd ~/github/data.table
Rscript -e "remove.packages('data.table')"

# CRAN
Rscript -e "install.packages('data.table', repos = 'https://cloud.r-project.org'); library(data.table); system.time(test.data.table())"

# just before typo checker
git checkout 7cf4f89db5c43a400833c691cff421c1ae269c19 .
R CMD build .
R CMD INSTALL .
Rscript -e "library(data.table); system.time(test.data.table())"

# current master
git reset --hard origin/master
R CMD build .
R CMD INSTALL .
Rscript -e "library(data.table); system.time(test.data.table())"
```

```
Timing stopped at: 54.3 5.34 40.5
Timing stopped at: 53.98 5.394 40.85
Timing stopped at: 55.97 5.739 42.23
```

So about a 3% speed hit. Re-running now to establish consistency of that...

**Comment by MichaelChirico** [comment]
Running a non-representative benchmark it looks like `tryCatch` _per se_ is not very expensive

**Comment by jangorecki** [comment]
Closing as resolved, as per results posted y @MichaelChirico

**Comment by mattdowle** [comment]
That test shows that tryCatch is small relative to a meaty task (runif(1e5)).
But I asked about call-overhead.  Which means for a very small task that might be called in a loop, is the overhead significant.
```
> x = 1L
> microbenchmark(
    TC   = for (i in 1:10000) tryCatch(x==2L, error=identity),
    noTC = for (i in 1:10000) x==2L)
Unit: milliseconds
 expr       min        lq     mean    median        uq      max neval
   TC 42.965566 45.990841 46.43713 46.221042 46.564809 61.63837   100
 noTC  1.070726  1.188889  1.49864  1.245389  1.426172 19.56793   100
> 
```

**Comment by MichaelChirico** [comment]
So, let's trigger the spell-check branch based on an option (spell-check by default)?

High-repetition tasks can turn off the spell-checker

Question is whether to decide such an option for the spell checker specifically, or whether to devise a broader "streamlined-`[`"-type option... which relates this to #852

**Comment by jangorecki** [comment]
@MichaelChirico We do raise this error in our code, so instead of handling it with tryCatch we can just use grep before raising the error, no?

**Comment by MichaelChirico** [comment]
without typo checking:

```
time Rscript -e "library(data.table); replicate(50, test.data.table())"
real	37m57.953s
user	62m17.104s
sys	5m27.150s
```

with:

```
time Rscript -e "library(data.table); replicate(50, test.data.table())"
real	37m22.124s
user	61m52.443s
sys	5m17.260s
```

So, I'm really not seeing any evidence that this check is a significant source of overhead.

I think my comment from above holds:

> let's trigger the spell-check branch based on an option

Say, `datatable.spellchecker`. `TRUE` by default since it seems like the impact is low in usual usage (as proxied by the `test.data.table()` suite).

Users who know they'll be running repetitive, safe commands can shut this down for that extra edge of speed. 

FWIW, I count 7 usages of `tryCatch` in our code, one of which in `cedta` which IIUC is run every time `[.data.table` is.
