### ISSUE TITLE
using get on a variable column breaks when variable is already a column name

### ISSUE THREAD

**Issue by nolanp2** [Rdatatable/data.table#3052]
I've seen get suggested as a standard way of referring to column names via a variable. In the event that the variable matches a column name in the dt, this seems to cause issues. Here's a simple example without any issues: 

```
dt <- data.table(a = 1:10,b = 1:10)

col1 = names(dt)[1]
col2 = names(dt)[2]

dt[,newcol:=get(col1)/get(col2)]

```

Now I make a slight change to dt, setting the first column name to match the variable col1:
```
dt <- data.table(col1 = 1:10,b = 1:10)

col1 = names(dt)[1]
col2 = names(dt)[2]

dt[,newcol:=get(col1)/get(col2)]
```
returns error: 

> Error in get(col1) : invalid first argument

**Comment by franknarf1** [comment]
Are you wanting or expecting different behavior? Currently, you can do..

```
dt[,newcol:=get(..col1)/get(..col2)]
```

with the `..` prefix meaning "up one level". It's a recent feature (from the last year) and part of a broader ongoing discussion https://github.com/Rdatatable/data.table/issues/2655#issuecomment-370535846

**Comment by nolanp2** [comment]
That names feature is bizarre, good to know. 

As for the issue raised, it seems to me it makes get() a potentially dangerous way of referencing variables. get(var) on its own is often suggested on stackoverflow as a solution, but could easily result in a situation where a function breaks when a DT with the variable name in its colnames is passed in. Your alternative using get(..var) is safer, but I've never seen it mentioned. Maybe some documentation around the safest wayd of handling these situations would save people some pain in the future?

**Comment by jangorecki** [comment]
@nolanp2 There is another way using base R feature called *computing on the language*. Personally I actually prefer this method, as you use feature of a language you coding in.
```
library(data.table)
dt <- data.table(col1 = 1:10,b = 1:10)
col1 = names(dt)[1]
col2 = names(dt)[2]
qj = as.call(list(
  as.name(":="),
  as.name("newcol"),
  call("/",
       as.name(col1),
       as.name(col2))
))
print(qj) # qj stands for quoted `j` argument, lets print it to see expression you build
#`:=`(newcol, col1/b)
dt[,eval(qj)]
```
Worth to mention it is quite exceptional feature of R language, you can read more about it in official R language manual in [Computing on the language](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Computing-on-the-language) chapter.

**Comment by MichaelChirico** [comment]
Basically `data.table` evaluation means that when `col1` is found as a column name, that _column_ (not its name) is passed to `get`, which doesn't know what to do when passed a vector of values.

In addition to Jan's & Frank's recommendations, you should also be able to use `.SDcols`:

```
dt[ , newcol := .SD[[1L]]/.SD[[2L]], .SDcols = c(col1, col2)]
```

Depends on what makes the most sense to you.
