### ISSUE TITLE
One note on CRAN about package size on Solaris

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3058]
One note on CRAN.
![image](https://user-images.githubusercontent.com/2779998/45855587-b725e400-bd05-11e8-9179-c0545134d212.png)

I guess the binary is slightly larger on Solaris for some reason and has just tipped it over 5MB limit to 5.1MB.   The datatable.so for me locally is 430KB.  Looks like it's twice that (1.1MB) on Solaris since that's the only file that `libs/` contains.  Or it's possible that `libs/` on Solaris contains another file.

Therefore, focussing on `tests` :
```
$ cd ~/GitHub/data.table/inst/tests
$ du -h * | sort -h
... snip ...
108K    issue_2157_sampling_reached_eof_early.txt
140K    allchar.csv
180K    winallquoted.csv
284K    grr.csv
664K    tests.Rraw
```

We can't reduce `tests.Rraw` (12,257 lines of tests) but it may be possible to reduce the next 4 largest data files, potentially saving up to 108+140+180+284 = 712K.

**Comment by mattdowle** [comment]
CRAN has replied
> I think you should not worry about this part.
I take this as meaning don't spend any time on it now (not even for next release) and we'll look again in future when it becomes a problem on more instances then.

**Comment by mattdowle** [comment]
For completeness, I looked at the 4 largest test data files above, briefly. They are non-trivial to reduce in size.  They need to be large enough to trigger fread sampling and are related to jump points / handovers.  The risk in reducing their size would be no longer testing the desired edge cases.

**Comment by MichaelChirico** [comment]
more like merging?

idea being to end up with one large file that covers all the edge case grounds intended by the four files we have now....

taking a glance I guess the logic of `allchar.csv` could be merged in another file? and possibly the same with the `issue_2157` file?

will be a time sink but maybe worth considering if we eventually are asked to shrink...
