### ISSUE TITLE
Be more outspoken on distinction between `week` and `isoweek` functions

### ISSUE THREAD

**Issue by ugroempi** [Rdatatable/data.table#3065]
Proposal: Add a small paragraph to the value section of the `IDateTime` documentation, saying something like: While function `week` returns the number of completed or fractional 7-day periods in the year, function `isodate` returns the week number in ISO... format." (I'm not familiar enough with the ISO conventions to create a proper proposal for ... .)

Explanation: I understand that function `week` attempts to provide the number of weeks within the current year (full or started already; with the bug mentioned in the open issue #2611), while function `isoweek` provides the week number according to a particular ISO convention (and might receive a method argument, if someone wants to implement different conventions).
Thus, for example, `week` should always return `1` for January 1 to January 7 and 53 for December 31st, while the outcome of `isoweek` depends on the circumstances and might, e.g., be 52 or 53 for January 1st or 1 for December 31st (which is why there should also be an `isoyear` function like in **lubridate**). 
A na&iuml;ve user might use function `week` for calculating the week number, being unaware of function `isoweek`. The documentation should actively prevent this confusion.

Best, Ulrike

P.S.: In my view, a name for function `week` which is more safe against this confusion would by `yweek`, i.e., week of year.

**Comment by franknarf1** [comment]
I like the idea of `yweek` if the "January first == first day of first week" behavior is kept somewhere. Then you could also have `ywday` for day number within those weeks; `isowday` etc.

From the discussion in your linked issue, I don't think the behavior of `week` is pinned down yet.  Maybe just keep the function with that name around with an argument `type=` that causes an error when left blank (to address your concern about user confusion here)? With that could go `weekdays.IDate` (which returns "Sunday", "Monday", etc depending on locale) which would also have a `type=` arg.

To reduce bugs from having to type `type=` values everywhere, maybe a global option could be set in `datatable.weektype`
