### ISSUE TITLE
data.table won't open/install

### ISSUE THREAD

**Issue by GKJonathan** [Rdatatable/data.table#3066]
Using R 3.5.1, tried to download "Car" package but I am getting error that "data.table" package will not download, see error code below:

Error: package or namespace load failed for ‘car’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘data.table’

However, when I try to download data.table, it does not appear in my library. Can anyone please advise? I am on Mac OS X - 10.13.4

**Comment by mattdowle** [comment]
Binaries are not yet available for MacOS for data.table 1.11.6 released a week ago.  Somewhere on your screen or in a file will be a message asking you something like "source is later than binary, do you wish to install from source".  And if you do that you'll need to follow our compilation instructions for MacOS : https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac

You can contact cran@r-project.org perhaps and there is a special interest mailing list for mac you could try.

But it's not a data.table problem per se.  The CRAN Mac machine is just very slow (a week or more).

Current status is always here :  https://cran.r-project.org/web/checks/check_results_data.table.html

![image](https://user-images.githubusercontent.com/2779998/45983240-b3010b80-c010-11e8-927e-9ba7c79b66ad.png)
