### ISSUE TITLE
tstrsplit error - unused arguments in transpose

### ISSUE THREAD

**Issue by arnematzen** [Rdatatable/data.table#3086]
Using data.table 1.11.6, I managed to generate the error below:

![image](https://user-images.githubusercontent.com/5829589/46256982-a4a06d00-c4b2-11e8-9092-ffe9fef828d8.png)

What strikes me, however, is that according to the signature of 'tstrsplit' the argument 'fill' has a default value, and thus when calling 'transpose' there should be no unused arguments?

![image](https://user-images.githubusercontent.com/5829589/46257102-63a95800-c4b4-11e8-958e-e585c219acfc.png)

Can any shed light on, what is the root-cause or what I'm perhaps interpreting wrong?

Thanks,
Kind regards,
Rene

**Comment by MichaelChirico** [comment]
Have you recently upgraded `data.table`? Can you share your `sessionInfo()`? In the meantime, please try a complete re-install of `data.table` (including closing all active R sessions); see the [Installation](https://github.com/Rdatatable/data.table/wiki/Installation) wiki

**Comment by arnematzen** [comment]
Yes - the setup is as follows: I use data.table on a Databricks cluster, which essentially means that every time I (re-)start the cluster I re-install data.table (1.11.6) from GitHub. However, I use devtools' install_github (which differs from the Installation guidelines on linux) to install the package, should that make a difference? 

The cluster comes with version 1.10.4.3 as default and uses the R version:

![image](https://user-images.githubusercontent.com/5829589/46257285-6d808a80-c4b7-11e8-83ed-5b9b49ec46fe.png)

**Comment by arnematzen** [comment]
Here comes the sessionInfo()

![image](https://user-images.githubusercontent.com/5829589/46257351-66a64780-c4b8-11e8-8719-995e42fa1181.png)

**Comment by arnematzen** [comment]
![image](https://user-images.githubusercontent.com/5829589/46257358-8473ac80-c4b8-11e8-8f55-13ea5bb31a80.png)

**Comment by MichaelChirico** [comment]
I'm confused, you say you install the latest dev but your installation shows an older version?

**Comment by arnematzen** [comment]
This is the default version of Databricks.

I use the following command: devtools::install_github(repo="Rdatatable/data.table") in order to obtain

![image](https://user-images.githubusercontent.com/5829589/46257417-8a1dc200-c4b9-11e8-8178-eaeaa8077292.png)

**Comment by arnematzen** [comment]
Have you experienced this error on previous versions of data.table?

**Comment by HughParsonage** [comment]
It's good that you've reported an issue, but you've ignored the contribution guidelines. Please edit your issue so that it contains a reproducible example and do not post screenshots. Be aware that the maintainers need to process all issues and their time is limited.

**Comment by MichaelChirico** [comment]
https://github.com/Rdatatable/data.table/blame/c54e7e7424541955d4f81caa7dc95d675a5d3a75/R/transpose.R

that code appears to be the same as 4 years ago.

please try debugonce to see if you can't figure out what might be amiss

**Comment by arnematzen** [comment]
strange - I'll try that and next time I will comply with the contribution guidelines.

thanks for your quick response
