### ISSUE TITLE
Working with out-of-memory data

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#3101]
I really like the performance of data.table, however it seems to only work with in-memory data. I was wondering how I can work with out-of-memory data.

**Comment by jangorecki** [comment]
As of now it is not possible, you can work around by chunking your data or partition your data across multiple machines with [big.data.table](https://github.com/jangorecki/big.data.table). We do plan to support out-of-memory feature, to stay up to date with that feature you can subscribe to https://github.com/Rdatatable/data.table/issues/1336
