### ISSUE TITLE
Respect `nomatch = 0L` for integer i

### ISSUE THREAD

**Issue by mllg** [Rdatatable/data.table#3109]
Currently `nomatch` seems to be ignored if `i` in `dt[i, j, nomatch = 0L]` is integer. Values of `i` which are out of bounds or `NA` result in rows filled with `NA`:
```r
dt = data.table(x = 1:10)
dt[c(1L, 11L, NA_integer_), x, nomatch = 0L]
> 1 NA NA
```
I see no reason to not support `nomatch = 0L` for integer `i`.

Also note that the current handling of negative integer `i` seems to be inconsistent with not-joins:
```r
# mixing negation/not-join with nomatch
dt[-1L, nomatch = 0L] # works, nomatch ignored
dt[!list(1L), on = "x", nomatch = 0L] # exception

# negation/not-join with out-of-bounds values
dt[-11L] # warning
dt[!list(11), on = "x"] # no warning
```

**Comment by franknarf1** [comment]
For the second part, the inconsistent behavior is good, right? 

I generally don't want a warning when part of an anti-join matches nothing, but do want it when I pass a row number outside of range. There are other safeguards on row numbers that don't have join analogies too (eg, `dt[c(-1,1)]` errors).

**Comment by mllg** [comment]
> I generally don't want a warning when part of an anti-join matches nothing, but do want it when I pass a row number outside of range.

Well, I'm not sure about it. Base R also does not give a warning:
```r
x = 1:10
x[-11L] # no warning, works fine
x[c(-1L,1L) # also an exception
```

**Comment by jangorecki** [comment]
please use `nomatch=NULL` from now on
