### ISSUE TITLE
.SD in expression with j? 

### ISSUE THREAD

**Issue by sritchie73** [Rdatatable/data.table#3115]
While waiting for PR #3093 , I'm looking for a way to return all columns in the result of a join while at the same time returning columns that are not part of `.SD`. E.g. I'd like to do something like this:

```
# Return the non-equi join columns from both sides of the join, 
# as well as all other columns that result from the join
DT_left[DT_right, on = .(key_left > key_right), 
             j = .(x.key_left, i.key_right, .SD)]
```

This doesn't work - you can't access `.SD` within an expression in `j`. Obviously I could write out all the columns I want in `j` manually, but that becomes impractical very quickly for even a small number of columns.

Another scenario where this would be useful is computing new columns in the result of a join, e.g.:

```
# Where A is a column in X, B is a column in Y.
X[Y, on = .(id), j = .(.SD, new_col = A * B)] 
```

Is there a way of doing this that I'm not aware of?

**Comment by MichaelChirico** [comment]
Agree this is a drawback... for now I either write out all the columns or try my luck with `mget(names(DT_left))` or `mget(paste0('x.', names(DT_left)))`

**Comment by Henrik-P** [comment]
Is this somewhat related to my SO question [Use `j` to select the join column of `x` and all its non-join columns](https://stackoverflow.com/questions/42329157/use-j-to-select-the-join-column-of-x-and-all-its-non-join-columns)?

**Comment by sritchie73** [comment]
Thanks @Henrik-P  that is the same issue. If you haven't looked at the PR #3093 above, we're planning on changing the behaviour of non-equi joins so that the non-equi join key columns from both data.tables are returned.  

The solutions at the moment to achieve this result are:

  - Do the join twice
  - Use `foverlaps()`
  - Use `mget` in various ways
  - (Not suggested yet, but my current approach) Create copies of the non-equi join key columns to use in the on argument

**Comment by sritchie73** [comment]
Can anyone comment if it would be sane to extend `.SD` so that it can be used inside `j=.()` ?

**Comment by st-pasha** [comment]
@sritchie73 This is perfectly sane. In fact, Python datatable has a similar feature request: https://github.com/h2oai/datatable/issues/1317

**Comment by jangorecki** [comment]
I am against using
```r
j = .(x.key_left, i.key_right, .SD)
```
we should ask user to use this instead
```r
j = c(.(x.key_left, i.key_right), .SD)
```
@sritchie73 could you add reproducible example in the issue?

**Comment by jangorecki** [comment]
There is now alternative approach. As question lacks reproducible example I will provide a dry example only:
```r
DT_left[DT_right, on = .(key_left > key_right), 
             j = .SDxx,
             env = list(
               .SDxx = as.list(
                 c("x.key_left", "i.key_right", names(DT_left))
               )
             )]
```

**Comment by MichaelChirico** [comment]
I am closing as I think this is covered by the above. See also #5020 and #935.
