### ISSUE TITLE
Missing presentation on Presentation Wiki page

### ISSUE THREAD

**Issue by nbenn** [Rdatatable/data.table#3131]
@mattdowle On the presentation page of the wiki it says you did a talk on "ALTREP from a data.table perspective" in Sept. Is it possible for you to link/upload the slides? I'm interested.

**Comment by mattdowle** [comment]
Thanks @nbenn. I didn't use any slides so there's nothing I can upload or link there really. I just talked ad-lib and showed code on screen. There was no recording. I do have a photo of the room though so you can get a sense of it. I just upload that to the page.
