### ISSUE TITLE
Incorrect result from funion(DT1, DT2, all=TRUE)

### ISSUE THREAD

**Issue by st-pasha** [Rdatatable/data.table#3133]
R data.table implements several set operators: `funion`, `fintersect`, `fsetdiff` and `fsetequal`. Each of these has an option to treat input data frames as **multi-sets** instead of regular sets, by passing the argument `all = TRUE`.

Unfortunately, `funion` uses incorrect formula to compute its results: for an element `x` with multiplicities `nA` and `nB` it produces an output with multiplicity `nA+nB` instead of the expected multiplicity `max(nA, nB)` (see [Multiset](https://en.wikipedia.org/wiki/Multiset)).

Due to this problem, the following invariant does not hold: `funion(A,B,all=F) == funion(A,B,all=T)` for data.tables `A` and `B` containing only unique elements.

Note that producing multiplicity of `nA+nB` is exactly equivalent to r-binding two data.tables, which is already available in a dedicated function.

**Comment by jangorecki** [comment]
Could you provide minimal reproducible example?

**Comment by mrdwab** [comment]
I keep trying not to, but just as I kept wondering who Frank was when `frank()` was introduced, whenever I use `funion()` I keep reading it as "fun-ion" and think of onions.

I know this isn't going to help resolve the bug at all.... ;-)

**Comment by st-pasha** [comment]
Any example would do. For example
```
> DT = data.table(A=1)
> funion(DT, DT, all=T)
       A
   <num>
1:     1
2:     1
```
Expected result: `all.equal(funion(DT, DT, all=T), DT)`.

**Comment by jangorecki** [comment]
I updated documentation that we aim for SQL way of handling that rather than wikipedia.
http://sqlfiddle.com
```sql
CREATE TABLE t1 (a double precision);
INSERT INTO t1 VALUES (1);
CREATE TABLE t2 AS SELECT * FROM t1;
```
```sql
SELECT * FROM t1 UNION ALL SELECT * FROM t2;
```

**Comment by st-pasha** [comment]
This is not "wikipedia way", this is mathematics way, the set theory. 

I'm sure we can say that these are not really set function, but "SQL set-like functions". Which are equivalent to mathematical set functions in all cases except for UNION ALL, which instead behaves exactly like `rbind()`.

But I feel this is just sweeping the bug under the rug.

**Comment by jangorecki** [comment]
The fact is that no one question SQL behavior. Everyone uses it in SQL industry, and the wikipedia way is pretty uncommon. Maybe it is not that useful for operations on data, maybe there is a mistake on wikipedia, maybe mistake in SQL just kept for backward compatibility, don't know. I believe there are good reasons behind it. Best would be to go though postgresql mailing list and find related topic discussed there.

**Comment by st-pasha** [comment]
UNION ALL in SQL does not claim to be a set operation. They needed some way to rbind results, and they decided to call it "union all". Everyone's happy. Only when juxtaposed with INTERSECT ALL and EXCEPT ALL that this discrepancy from math becomes pronounced.

On the other hand, the multiset operations are probably so rare that almost nobody uses them anyway. Which is why this issue has gone unnoticed for such a long time. I only discovered this problem because I was reading the docs for `funion`, and noticed that the math in the docs was incorrect. At first I thought it was a documentation issue, but then it turned out it was the implemented behavior too.

So this just looks like a very low importance issue, not worth spending the effort to fix.

**Comment by jangorecki** [comment]
Actually when I was developing ETL pipelines those set operators having `ALL` were used multiple times a day, and not just me but the whole team of ETL developers. This is how you track using SQL if `TRUNCATE & LOAD`/`INSERT`/`UPSERT` from table to another table is properly developed in ETL tool. It may sound trivial but when you have time variant fields in your tables then it is not trivial. AFAIU DAI will use truncate and load every time so that wouldn't be useful there anyway.

**Comment by st-pasha** [comment]
I don't have much experience with PostgreSQL, I guess it would be worthwhile to peruse their docs.
On the other hand, INTERSECT ALL &el. are not available in SQL Server, Oracle SQL or MySQL, which is why I assumed they were rarely useful. But from what you're saying, it seems that people do find them handy when they are available.

In the absence of Union, this operator can be calculated as 
```
X∪Y = (X\Y) + (Y\X) + (X∩Y)
```
which gives multiplicity function `max(nX-nY, 0) + max(nY-nX, 0) + min(nX, nY) = max(nX, nY)` as desired.
