### ISSUE TITLE
[Documentation] list/.() can be omitted in j on single column/expression

### ISSUE THREAD

**Issue by Henrik-P** [Rdatatable/data.table#3145]
From the vignette [Introduction to data.table](https://cloud.r-project.org/web/packages/data.table/vignettes/datatable-intro.html):

>As long as `j`-expression returns a `list`, each element of the list will be converted to a column in the resulting `data.table`. 

>When there’s only one column or expression to refer to in `j` and `by`, we can drop the `.()` notation. This is purely for convenience. 

In `?data.table`, the first sentence appears in the **Arguments** section on `j`. However, the second piece of information does not appear here. Furthermore, in **Details**, the drop of `.()` is only explicitly described for `by`: "`.()` can be omitted in `by` on single expression for convenience"

I suggest that the part "When there’s only one column or expression to refer to in `j` [...], we can drop the `.()` notation. This is purely for convenience." is added also to the help text in **Arguments** section about `j`.

**Comment by sritchie73** [comment]
Note however that without `.()` or `list()` the result is returned as a vector rather than a 1-column data.table

**Comment by Henrik-P** [comment]
Indeed! I should have been clearer on the background of my thoughts. Consider the two examples in the **Details** section of `?data.table`:

    X[, .(sum(a)), by=c]        # get sum(a) grouped by 'c'.
    X[, sum(a), by=c]           # same as above, .() can be omitted in by on single expression for convenience

I interpreted the "`.()` can be omitted in `by` on single expression" wrongly, as referring to wrapping **`by`** in `.()` or not. At the same time, we see that the difference between the two lines of code is in fact that `.()` has been omitted in **`j`** (not `by`...). A typo? Anyway, this made me start looking for a reference in `?data.table`, similar to the one in the vignette.

In the help text, the description of how variables and expressions can be specified in both `j`, `by` and `on` is very nice and thorough. Furthermore, it is mentioned explicitly (as you also note) in several places that when _not_ wrapping `j` in `list`, the result is a _vector_. This contrasts with the examples where `j` is not wrapped `list` which returns a `data.table`, namely together with `by`, examples without further explanation. This behavior is perhaps too obvious - how else should the result be returned we may think? Still, I believe it's better to be explicit in the help text. Given the thorough treatment of all other possible ways to specify `j` (and `on` and `by`), I think the "`j`-without-`list`-together-with-`by`" deserves a few more words, at least for consistency.

And apologize for _me_ not being more explicit in my first post.

Cheers

**Comment by MichaelChirico** [comment]
@henrik-p do let us know if the change looks good. thanks for filing!
