### ISSUE TITLE
[R-Forge #1018] Using "by" parameter in [.data.table results in "unused argument error"

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#315]
Submitted by: Christian Hudon; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1018&group_id=240&atid=975)

I'm going through the data.table introduction PDF file. When I try the following command: "DT[,sum(v), by=x]" I get an error instead of a sum of the "v" values grouped by "x":

Error in getOption("datatable.verbose", FALSE) : 
  unused argument(s) (FALSE)
Calls: [ -> [.data.table -> getOption

And indeed trying "getOption("datatable.verbose", FALSE)" results in the same error:
Error in getOption("datatable.verbose", FALSE) : 
  unused argument(s) (FALSE)

I'm running R 2.9.2 with data.table 1.4.1.

**Comment by bellowswang** [comment]
Hey I have the same issue. Did you solve the problem?

**Comment by MichaelChirico** [comment]
@bellowswang please share your `sessionInfo()` and a reproducible example if you can
