### ISSUE TITLE
print.data.table should honour na.print

### ISSUE THREAD

**Issue by HughParsonage** [Rdatatable/data.table#3152]
In `?print.default`:

> `na.print`	
> a character string which is used to indicate NA values in printed output, or NULL (see ‘Details’).

This works for base R data frames, but not for `data.table`s.

``` r
print(data.frame(x = c(NA, "a", "b")),
      na.print = ".")
#>   x
#> 1 .
#> 2 a
#> 3 b

library(data.table)
print(data.table(x = c(NA, "a", "b")), 
      na.print = ".")
#>       x
#> 1: <NA>
#> 2:    a
#> 3:    b
```

I think it would be worthwhile to offer the default `na.print` as an option, unless the current behaviour is intended.

<sup>Created on 2018-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by joshhwuu** [comment]
thinking of giving this a try - am I wrong to assume that I can just add a new parameter to `print.data.table`, some type checking, adding the parameter to `print.default` calls, some tests, and making an update to the corresponding documentation? I'm assuming the calls to `print.default` within `print.data.table` can handle `na.print` correctly.

**Comment by MichaelChirico** [comment]
That's the right approach. Start from how the `print.data.frame` method handles the argument, and work back to the right way to adapt it for `print.data.table`.

Assigning you for now, but feel free to unassign.

**Comment by joshhwuu** [comment]
Looking at `print.data.frame`, `na.print` is passed to calls to `print.default` by the `...` operator. Do you think this approach is appropriate for `print.data.table` as well, or is it better to just add in the `na.print` argument to keep things simple, (not allowing extraneous arguments) I assume there's a reason why we don't pass `...` to `print.default` calls already.
