### ISSUE TITLE
Should 0-column data.tables preserve the number of rows?

### ISSUE THREAD

**Issue by sritchie73** [Rdatatable/data.table#3155]
Related to #3149 .

I noticed the following discrepancy between data.frames and data.tables:

```
> mtcars[,0]
data frame with 0 columns and 32 rows
> DT <- as.data.table(mtcars)
> DT[,0]
Null data.table (0 rows and 0 cols)
```

Should a Null data.table preserve the number of rows like data frames do?

**Comment by MichaelChirico** [comment]
I swear there's a related issue lying around somewhere...

**Comment by MichaelChirico** [comment]
I guess this one? #2422 

also pinging @jangorecki and #3149

**Comment by jangorecki** [comment]
IMO it should not. In columnar storage row is a child of column. Without column no rows exists. This make sense for multidimensional structures like matrix/array but not data.frames.

**Comment by sritchie73** [comment]
Happy for you to close this then - I figured there was a sane reason for this but wanted to make sure this got cross checked with Issue #3149 and its proposed solution in PR #3154
