### ISSUE TITLE
Confusing default in merge documentation for all.x and all.y

### ISSUE THREAD

**Issue by hannes101** [Rdatatable/data.table#3157]
I don't know if this is on purpose, but the Usage section in the help file for merge[data.table} includes the following:
```
    ## S3 method for class 'data.table'
merge(x, y, by = NULL, by.x = NULL, by.y = NULL, all = FALSE,
all.x = all, all.y = all, sort = TRUE, suffixes = c(".x", ".y"), no.dups = TRUE,
allow.cartesian=getOption("datatable.allow.cartesian"),  # default FALSE
...)
```
As you can see ```all.x``` and ```all.y``` are presented with the default value of all, although both of these are logical options, which either need to be TRUE or FALSE. To me it would be easier to just enter the default values, which also would make it easier to get the necessary data type for the option, by just looking at the command there. Of course further down the options are explained correctly, but it confused me a little.

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)
?data.table::merge

`#` `Output of sessionInfo()`
I think all other infos are not necessary: data.table_1.11.8

**Comment by MichaelChirico** [comment]
This is the same as other `merge` methods, e.g. `base`:

```
## S3 method for class 'data.frame'
merge(x, y, by = intersect(names(x), names(y)),
      by.x = by, by.y = by, all = FALSE, all.x = all, all.y = all,
      sort = TRUE, suffixes = c(".x",".y"), no.dups = TRUE,
      incomparables = NULL, ...)f
```

and `SparkR`:

```
## S4 method for signature 'SparkDataFrame,SparkDataFrame'
merge(x, y,
  by = intersect(names(x), names(y)), by.x = by, by.y = by,
  all = FALSE, all.x = all, all.y = all, sort = TRUE,
  suffixes = c("_x", "_y"), ...)
```

**Comment by hannes101** [comment]
Ok, then I guess it's a matter of taste, I just found it confusing to have option values there, which are actually not possible to use.

**Comment by jangorecki** [comment]
> As you can see all.x and all.y are presented with the default value of all, although both of these are logical options, which either need to be TRUE or FALSE. To me it would be easier to just enter the default values, which also would make it easier to get the necessary data type for the option, by just looking at the command there.

That would change the logic, now by changing `all` you can control `all.x` and `all.y` argument. If that would be hardcoded logical value you could not.
