### ISSUE TITLE
IDateTime could optionally track different time zones for different rows

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3160]
simple `base` R time objects (`POSIXct`) are ill-suited to handling regional datasets (`tzone` attribute is atomic); similarly, `POSIXlt` objects are overly broad (_every_ component is a vector).

What's really needed is a structure that's just a little bit more general than that offered by `IDateTime` at the moment:

```
idate itime tz
17861 32415  1
17861 32415  2
```

Where I'm suppressing the `print` methods for each column to show the simple integer structure of each column.

`idate` and `itime` are as before, but the objects (optionally? `NA` by default?) gain a `tz` column stored as a `factor` whose labels name different `OlsonNames()` time zones, e.g.

```
tz = factor(c('Asia/Singapore', 'Asia/Jakarta'))
```

Related methods would then handle printing/formatting/etc appropriately accounting for the `tz` column.

Related: #2402, #1451

**Comment by MichaelChirico** [comment]
So far I've been doing things `by = tz`; "producing a report" is exactly the sort of functionality I have in mind, but also, filtering rows based on local time (`x[hour_local == 9L]`, e.g.).

Functionality I have in in mind handles this logic internally to be less of a fuss. I'll add `Low` label since it's a nice-to-have.

**Comment by mattdowle** [comment]
If there are mixed timezones in an input dataset, it's best practice to convert everything to consistent UTC up front. Leaving them mixed in the same column is going to lead to bugs really quickly, slow it down even if it works, and at best result in a new class that can't be passed to other packages.
If the use case is really to do something like `x[hour_local == 9L]` then a column can be added for that using plain `integer`, or `ITime` or similar.  In other words users don't have to use `POSIXct`. I most often prefer two columns anyway: date and time separately. That way grouping by date/month/day-of-week need only touch the smaller 4 byte date column,  rolling joins are a bit easier to find first and last record by day and don't join to the last row of the previous day (penultimate column, date, must match). Most often in time series we're doing time deltas within the day, not across days.
I'm just trying to say there other better ways to represent varying local time zone data, if that is really needed, than attempting to incorporate a vector-timezone into POSIXct. Those ways are already possible without needing to add anything into data.table.
If you agree, can we close this issue?

**Comment by MichaelChirico** [comment]
I agree that it's a bit niche and hard to maintain. I do think it's quite useful e.g. for building regression models, but I guess the main potential advantage -- skipping over `POSIXlt` conversion on a huge dataset -- wouldn't really be brought by the proposed change, at least without substantial effort & underlying code.

It's worth mentioning that both [PostgreSQL](https://www.postgresql.org/docs/9.1/datatype-datetime.html) and [Presto](https://prestodb.io/docs/current/functions/datetime.html) support the `TIMESTAMP WITH TIMEZONE` column type, which can have timestamps vary by row, which I think provides good evidence of its utility. I believe the implementation is similar to R, where the core storage type is related to UTC, and the time zone really only comes into play for formatting & extractions.

I'll close this with a note that it would be useful for a different add-on package to support such a thing.
