### ISSUE TITLE
Schrodinger's cols in setorderv (internally several !length(cols) behaviors)

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3169]
[These two](https://github.com/Rdatatable/data.table/blob/master/R/setkey.R#L318-L323) lines suggest different behavior for what to do with

```
DT = data.table(a = 1:3)
setorderv(DT, character(0L))
```

Obviously the first branch is hit first and simply `return`s the input. But the other branch suggests the behavior should be more like `setkey` and use _all_ columns. 

The first branch's behavior is consistent with `setorder` where `setorder(DT)` would just return `DT` unaltered.

Perhaps what's intended is for the latter branch to handle `missing(cols)` and the former branch to handle `!length(cols)`?

**Comment by jangorecki** [comment]
I generally prefer to not error on zero length input. When you have metadata driven app it is then less `if(!length(.))` branching. I would go with `colnames(x)` for missing (ideally as default value of an arg), and unaltered for `character(0)`.
