### ISSUE TITLE
names(DT) returns values by reference so setnames() overwrites saved column names

### ISSUE THREAD

**Issue by sz-cgt** [Rdatatable/data.table#3187]
Here's a simple example.  While the data.table `set*()` functions all work by reference, it violates standard R semantics and the Principal of Least Surprise when other functions behave the same way.

``` r
library(data.table)
dt <- data.table(a = 1, b = 2, c = 3)
oldNames <- 
  names(dt)
print(oldNames)
#> [1] "a" "b" "c"
pryr::address(oldNames)
#> [1] "0x1fbe6340"
newNames <- 
  paste0(oldNames, "_1")
print(newNames)
#> [1] "a_1" "b_1" "c_1"
pryr::address(newNames)
#> [1] "0x1ffba948"
print(oldNames)
#> [1] "a" "b" "c"
setnames(dt, old = oldNames, new = newNames)
print(oldNames)
#> [1] "a_1" "b_1" "c_1"
pryr::address(oldNames)
#> [1] "0x1fbe6340"
print(newNames)
#> [1] "a_1" "b_1" "c_1"
pryr::address(newNames)
#> [1] "0x1ffba948"
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 16299)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
#> [3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
#> [5] LC_TIME=English_Australia.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] data.table_1.11.8
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.1   pryr_0.1.4       backports_1.1.2  magrittr_1.5    
#>  [5] rprojroot_1.3-2  tools_3.5.1      htmltools_0.3.6  yaml_2.2.0      
#>  [9] Rcpp_1.0.0       codetools_0.2-15 stringi_1.2.4    rmarkdown_1.10  
#> [13] knitr_1.20       stringr_1.3.1    digest_0.6.18    evaluate_0.12
```

<sup>Created on 2018-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ocschwar** [comment]
Hi, all. I have some pretty long data processing pipelines to maintain, which make extensive use of data.table and retain variables long term, and so this issue is disocncerting. I've had to look extensively through my codebase to make sure nothing I ran was tripping up on this issue. 

Is the idea to just leave data.table to use column names by reference and therefore mutable in this way?

**Comment by Atrebas** [comment]
This is the expected behaviour. See #3316 for @mattdowle's answer.

**Comment by mattdowle** [comment]
Yes this is deliberate behavior of `:=` all `set*` functions including `setnames()`.  Updating by reference is supposed to be different to standard R.  Note you can only do that if you use the special `:=` and `set*` functions.
You don't have to use `setnames()`. You could use `names(DT)[]<-` which is the standard R syntax and has the standard copying semantic. That will copy the column names vector if a symbol is pointing to the column from an earlier assign.  Some people have many thousands of columns and might be updating column names in a loop where the copying (even of just column names) can start to bite.
However, it's more about adding new columns to the end than it is about changing existing column names.  The column names vector is over-allocated just like the vector of column pointers. When adding a new column the next spare slot is populated to point to the new column, and the spare slot of the column names is pointed to the new column name.  It's much more common to add (and remove) columns than it is to change existing column names.  In terms of updating the (over-allocated) column name vector by reference, the ops of adding, removing and updating are similar.
