### ISSUE TITLE
Navigation in documentation pages

### ISSUE THREAD

**Issue by Gayyam** [Rdatatable/data.table#3200]
Thank you for this great package!

I was going through the docs [here](https://github.com/Rdatatable/data.table/wiki/Getting-started), which are helpful.

Is there a way to navigate to the next page in the documentation series without having to click the back button? i.e. a next section / previous section button at the bottom of those pages would be great.

**Comment by jangorecki** [comment]
AFAIK not possible, as long as we have it on github wiki.

**Comment by MichaelChirico** [comment]
@Gayyam  thanks for reaching out. This would require some sort of "ordering" to the documentation, which there's not. For an ordered introduction to the package, try the vignettes and the wiki:

https://github.com/Rdatatable/data.table/wiki/Getting-started
