### ISSUE TITLE
Release checks

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3211]
Hi @renkun-ken.
Could you run latest data.table dev through your systems please.
There are some significant internal code changes that it would be good to run past your checks early.
Please check that more cores are being used more of the time, and whether your test suite total time is any faster or not.
Thanks!!
Matt

**Comment by renkun-ken** [comment]
I notice that significant changes are made recently so I keep up with those on a daily basis. So far the system runs perfectly with 4c9a1f0.

I'll test against the latest commit very soon.

**Comment by mattdowle** [comment]
Thanks @renkun-ken!  
We could maybe have a look at fork again. See past problems here : 
https://github.com/Rdatatable/data.table/blob/master/src/openmp-utils.c#L73
Are you on Linux/Mac/WIndows?  ( I didn't think Windows had fork, but somebody told me recently that it does.)

**Comment by renkun-ken** [comment]
I'm on Linux.

I test a small part of system against 0daefad2dcba8dd15f907969eab60a58b7f28ef1 and the computing time reduced 30%. I'll do a more thorough test soon.

I filed #2885 on auto-restore multi-threading after fork. fst adopts this behavior for quite a while and it works for me perfectly so far.

**Comment by renkun-ken** [comment]
Latest commit 0daefad2dcba8dd15f907969eab60a58b7f28ef1 is broken here. I'll take a closer look and file an issue about it soon.

**Comment by renkun-ken** [comment]
The problem lies on a assumed behavior that `dt[TRUE]` always creates a shallow copy of `dt` so that adding columns to the shallow copy does not influence the original data.table. See #3214.

**Comment by mattdowle** [comment]
Thanks @renkun-ken.  Now fixed in #3213 and merged.

**Comment by mattdowle** [comment]
@renkun-ken Many thanks for this invaluable testing!!
#3216 fixed, and #2885 (restore multi threading after fork) done too.
Please rerun whenever convenient.

**Comment by renkun-ken** [comment]
A full run with 76d4a622e0ee3c5ed8e3ecf693026bf0ed7f4fe3 is in progress...

**Comment by renkun-ken** [comment]
Just found another issue which seems to be breaking change. The updated subsetting seems to under-allocate. See #3228.

**Comment by renkun-ken** [comment]
Except empty `.SDcols` now produces an error (which I think is by design in recent changes?), as #3229 has just been merged, no other issues are found so far.

**Comment by mattdowle** [comment]
Thanks again for the quick turnaround!

Looks like that failed in 1.11.8 too but with a better message.  Will make the error message same as before, but still an error, right?

```R
> dt <- data.table(x = rnorm(10), y = rnorm(10))
> cols <- intersect(c("p", "q"), names(dt))

v1.11.8
======
> dt[, x := rowSums(.SD), .SDcols = cols]
Error in `[.data.table`(dt, , `:=`(x, rowSums(.SD)), .SDcols = cols) : 
  RHS of assignment to existing column 'x' is zero length but not NULL. If you intend to
delete the column use NULL. Otherwise, the RHS must have length > 0; e.g., NA_integer_.
If you are trying to change the column type to be an empty list column then, as with all
column type changes, provide a full length RHS vector such as vector('list',nrow(DT));
i.e., 'plonk' in the new column.

dev error not intended
======
> dt[, x := rowSums(.SD), .SDcols = cols]
Error in `[.data.table`(dt, , `:=`(x, rowSums(.SD)), .SDcols = cols) : 
  Empty .SDcols is not yet supported.

**Comment by renkun-ken** [comment]
Sorry, I just noticed that there might be a bug in 1.11.8 on empty `.SDcols` that I happended to take advantage of unintentionally.

The following code works with 1.11.8:

```r
library(data.table)

dt <- data.table(x = rnorm(10), y = rnorm(10))
gs <- list(a = c("x", "y", "z"), b = c("p", "q"))

for (g in names(gs)) {
  dt[, (g) := rowSums(.SD), .SDcols = intersect(colnames(dt), gs[[g]])]
}
```

But if the `for`-loop is run again, the `RHS ...` error occurs.

I think I should change my code here.

**Comment by mattdowle** [comment]
@renkun-ken  With that PR just merged, it should be back to 1.11.8 behavior w.r.t. empty `.SDcols`.  Please rerun and hopefully this resolves everything? Huge thanks again.

**Comment by renkun-ken** [comment]
Another issue: #3245.

**Comment by mattdowle** [comment]
@renkun-ken  Thanks again, fixed. Please rerun.

**Comment by renkun-ken** [comment]
A full run with f73e7b0 works perfectly.

**Comment by renkun-ken** [comment]
Looks like all issues for milestone 1.12.0 are closed. It's time to initiate a full run.

**Comment by mattdowle** [comment]
- [ ] CRAN_Release (e.g. UBSAN, ASAN and rchk)
- [ ] CI Pipeline
- [ ] win-builder 3*OK
- [ ] final rerun latast revdeps refreshed (748) running now
- [ ] Kun Ren final go-first

**Comment by renkun-ken** [comment]
@mattdowle Everything works perfectly.

**Comment by jangorecki** [comment]
web browsers often cache website so might not show new version on cran, the following can be helpful:

Rscript -e 'data.table::fread("https://cran.r-project.org/web/packages/data.table/index.html", sep=NULL, header=FALSE)[24]'

**Comment by mattdowle** [comment]
In some ways I think the most significant item of this release is note 1. The bug report to r-core is open with no progress. It's potentially really serious and could have affected a lot of packages for a long time, silently.
Like I did with OpenMP for Mac (which worked) the new check and long message is intended to draw attention to it. It asks folk affected to add a comment to the R-core bug report.
If there's any movement on that, I'll be delighted.
We need to gather more _very precise_ and _reproducible_ evidence in the day or so after it hits CRAN and _before_ the Windows binary is made available on CRAN. I believe the most severe problem is only in that short window so we need to gather good evidence right then and there to move the needle in the minds of R-core.

**Comment by jangorecki** [comment]
Be sure to tweet after cran release will be rolled out so we can get feedback from windows users on that. @mattdowle

**Comment by jangorecki** [comment]
1.12.0 is on CRAN.
Windows users please try to install from CRAN having data.table attached in another R session to verify the mechanism mentioned above to prevent version mismatch. As described in #3282 you might see `CdllVersion not found` type error. You of course needs Rtools installed so R will attempt to build Windows binaries from source because windows binaries are published on CRAN with delay. Also see @mattdowle comment above for details.
