### ISSUE TITLE
shift better naming for negative n

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3223]
as discussed in inline comments to https://github.com/Rdatatable/data.table/pull/3166
now when `shift` accepts negative integers we can get column names like `V1_lag_-1` / `V1_lead_-1`, they look awkward.
- [x] My suggestion is to use `V1_shift_1` / `V1_shift_-1` instead. This cannot be made without breaking change to current behavior, unless we introduce new type, just `type="shift"`. Not much changes to code, and users who prefer to use only new interface (positive to lag, negative for lead) could switch to `type="shift"`. Good to have it for 1.12.0 as we are releasing negative n feature there.

- [x] Additionally on docker tests we are getting - fixed in 76d4a622e0ee3c5ed8e3ecf693026bf0ed7f4fe3 - issue was that `match.arg` was using shell dependent quoting
```
Test 1963.8 didn't produce the correct error :
Expected: should be one of "lag" 
Observed: 'arg' should be one of “lag”, “lead” 
```
those are environments striped out from many R stuff that is by default active, like methods package.
```r
test(1963.8, shift(DT$x, type = 'some_other_type'),
     error = 'should be one of "lag"')
```

- [x] fix invalid test 1963.4,, atomic vectors should not be named

**Comment by st-pasha** [comment]
The problem with a name such as `V1_lag_-1` is that it cannot be used as a variable: `DT[:, V1_lag_-1]` will not work. Backticks may be used as a workaround, but they may not work everywhere, may not be widely known, and are more cumbersome.

What can be done is to automatically replace `lag` <=> `lead` upon getting a negative `n`. This way the produced names will be `V1_lag_1` and `V1_lead_1` respectively.

**Comment by MichaelChirico** [comment]
I agree w pasha here. the awkward part of the naming is exactly the -1
part, so proposed solution continues to be awkward IMO

**Comment by jangorecki** [comment]
Backticks is not a workaround but standard way to deal with column names like this. From the programmatic point of view it is much better to deal with backticks than condition on your input to shift() to operate its results later on.

**Comment by mattdowle** [comment]
Everyone can be satisfied here. In 32eee2b9921fa06287e0c060c685f7fb00519e5f I kept new `type="shift"` and flipped the lead/lag in the names too.  That way users can use whichever they prefer.
NEWS item now reads : 
> `shift()` now interprets negative values of `n` to mean the opposite `type=`, [#1708](https://github.com/Rdatatable/data.table/issues/1708). When `give.names=TRUE` the result is named using a positive `n` with the appropriate `type`. Alternatively, a new `type="shift"` names the result using a signed `n` and constant type.
    `shift(x, n=-5:5, give.names=TRUE)                =>  "_lead_5" ... "_lag_5"`
    `shift(x, n=-5:5, type="shift", give.names=TRUE)  =>  "_shift_-5" ... "_shift_5"`
