### ISSUE TITLE
Under-allocation of truelength after subsetting

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#3228]
The allocation behavior seems to be changed. The `truelength()` is largely reduced after any subsetting. Massive adding columns to the under-allocated data.table in other environment would fail to apply to the original object.

```r
library(data.table)

dt <- data.table(id = 1:1000)
dt[, x := rnorm(.N)]
truelength(dt)
#> [1] 1025

dt1 <- dt[x > 0]
truelength(dt1)
#> [1] 66
```

**Comment by mattdowle** [comment]
Thanks. I see the issue. `CsubsetDT` does the over-allocation inside it at C level. It needs the `alloc.col` option passing down from R level.  Will do.
