### ISSUE TITLE
revdep results

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3233]
Not bad: just 21 out of 586 CRAN revdeps to investigate. Most of the Bioconductor ones are usual suspects: they don't tend to fix warnings on Bioconductor and are usually unrelated to data.table.  Still need to be investigated though.

```
Installed data.table to be tested against: 1.11.9 
CRAN:
 ERROR   :  17 : antaresRead batchtools behavr damr DeclareDesign ggetho maditr popEpi PROSPER rENA rtsdata scopr sdcMicro sleepr timeseriesdb toxboot zeitgebr 
 WARNING :   4 : assertable ctsem SpaDES.core tidytext 
 NOTE    : 183 
 OK      : 382 
 TOTAL   : 586 / 586 
 
BIOC:
 ERROR   :  12 : CAGEr facopy GenVisR ImmuneSpaceR LowMACA LymphoSeq MAST phantasus RGMQL scater TIN TitanCNA 
 WARNING :  18 : bsseq CONFESS CRISPRseek crossmeta eQTL GenoGAM iCNV IrisSpatialFeatures methylPipe minfi MinimumDistance paxtoolsr RiboProfiling rTANDEM S4Vectors SISPA TFutils Uniquorn 
 NOTE    :  87 
 OK      :  18 
 TOTAL   : 135 / 135 
 
TOTAL          : 721 
```

[fail.log](https://github.com/Rdatatable/data.table/files/2692452/fail.log)

**Comment by mattdowle** [comment]
To include on CRAN upload message that communication with downstream maintainers has happened in advance : 
- [ ] behavr   https://github.com/rethomics/behavr/pull/40

**Comment by mattdowle** [comment]
Current status after full rerun : 
```
Installed data.table to be tested against: 1.11.9 
CRAN:
 ERROR   :   2 : DeclareDesign worrms 
 WARNING :   0 :  
 NOTE    : 191 
 OK      : 403 
 TOTAL   : 596 / 596 
 
BIOC:
 ERROR   :   6 : GenVisR ImmuneSpaceR LymphoSeq MAST QuartPAC scater 
 WARNING :  18 : bsseq CONFESS CRISPRseek crossmeta eQTL GenoGAM iCNV IrisSpatialFeatures methylPipe minfi MinimumDistance paxtoolsr RiboProfiling rTANDEM S4Vectors SISPA TitanCNA Uniquorn 
 NOTE    :  91 
 OK      :  19 
 TOTAL   : 134 / 134 
 
TOTAL          : 730
```

**Comment by mattdowle** [comment]
I needed to update repo of Bioconductor from 3.7 to 3.8.  Thanks to several Bioconductor maintainers for taking a look and letting me know.

**Comment by mattdowle** [comment]
After updating to Bioc 3.8 and rerunning, email to 26 Bioc maintainers on 8th Jan 2018 : 

---

Dear maintainer of Bioconductor package,

Please could you fix the error or warning status in the log attached, or let me know how I can fix it locally. Your package uses data.table in some way. Since your package is already in error/warning status with the released version of data.table (1.11.8), it makes it much harder for me to test the impact each data.table update has.

There are no errors or warnings for the 598 packages on CRAN that use data.table :
```
CRAN:
 ERROR   :   0 :  
 WARNING :   0 :  
 NOTE    : 192 
 OK      : 406 
 TOTAL   : 598 / 598 
 ```
There are 26 Bioc packages that use data.table that have error or warning. I don't think these are related to data.table but these make it much harder to spot errors or warnings that data.table has caused when it is updated.
I'm using Bioc 3.8 and session info is at the top of the attached log.
```
BIOC:
 ERROR   :   2 : GENESIS ImmuneSpaceR 
 WARNING :  24 : CEMiTool CONFESS crossmeta dada2 ELMER eQTL flowWorkspace GenoGAM GOTHiC
                 iCNV MAST methylPipe MinimumDistance netSmooth OUTRIDER RiboProfiling
                 rTANDEM S4Vectors SCnorm SISPA TENxBrainData TitanCNA Ularcirc Uniquorn 
 NOTE    : 102 
 OK      :  24 
 TOTAL   : 152 / 152 
 ```
Thanks, Matt

---
[fail.log](https://github.com/Rdatatable/data.table/files/2738700/fail.log)

**Comment by mattdowle** [comment]
Testing 1.11.9 and looking for diff in status.

- [ ] rerun ok for 7 due to resource/internet issues: BiocParallel, MAGeCKFlute, SWATH2stats, GSALightning, RegParallel, TCGAbiolinksGUI, RCAS

- [ ] geneXtendeR

**Comment by mattdowle** [comment]
checkmate 1.9.0 update today is broken by data.table

**Comment by mattdowle** [comment]
One revdep fail so far (still running) due to #3273. Was worth delaying release to fix those bad bugs. Good to have been formal and rerun all revdeps.

- [ ] damr  `Can't use NULL in colClasses when select or drop is used as well.`

**Comment by jangorecki** [comment]
`GitHub API rate limit exceeded` might be client side issue. I am recently getting this when using devtools install_github and I had to wait up to one hour. It seems that gh reduced limit of API calls when not using gh token auth.
