### ISSUE TITLE
slow execution of command

### ISSUE THREAD

**Issue by gabrielwong1991** [Rdatatable/data.table#3247]
Hi I run into this problem very often.

Basically after I fread a csv file (about 300mb only), do some basic data manipulations (like looking for some data, changing values, creating new columns etc...) and let R studio idle for say 2 minutes, then executing a new command the program would take about 30 seconds to show result (e.g. Viewing the data.table). 

Meanwhile when I look at task manager, the CPU usage is constantly working at 30% and could see the ram usage fluctuating. It appears like the computer is sorting out the memory....

The problem is similar to this one:
https://community.rstudio.com/t/r-studio-ram-cpu-usage-spikes-every-time-i-save-script/12783/7

So I follow in the link to try finding which code causes the lag, i ran

Rprof("rstudio-trace.Rprof")

Rprof(NULL)

summaryRprof("rstudio-trace.Rprof")

It appears that dotryCatch, tryCatch occupied the time most ~44seconds.

I have 32GB of ram and after some data manupulation, the ram usage is just 1Gb. 

Anything I could provide to help identify the issue?

**Comment by gabrielwong1991** [comment]
[rstudio-trace.Rprof.txt](https://github.com/Rdatatable/data.table/files/2710628/rstudio-trace.Rprof.txt)

Here is the output from rstudio-trace.Rprof. As you can see data.table, tryCatch, took the longest time to run. What basically happened here?

**Comment by MichaelChirico** [comment]
can you reproduce this running from the terminal (especially R --vanilla)?

if not, I'd say this is probably an RStudio problem

**Comment by gabrielwong1991** [comment]
Hi Michael thanks for your reply I will try in Rgui now

**Comment by gabrielwong1991** [comment]
I don't get any problem with Rgui. - Smooth as butter. So I would guess this is the problem with the connection between R and R-studio then?

**Comment by franknarf1** [comment]
@gabrielwong1991 You mentioned Viewing; and RStudio has its own View function, so maybe that's part of the issue? Anyway, if it's not data.table-specific, this might not be the best place to continue debugging.

**Comment by gabrielwong1991** [comment]
Viewing the data as in typing the object name not View(object). 

I agreed closing this thread as I already posted in Rstudio community.

Thanks.

**Comment by jangorecki** [comment]
It might eventually be related to https://github.com/Rdatatable/data.table/issues/3037 which uses tryCatch which could be avoided.
