### ISSUE TITLE
Remove #define USE_RINTERNALS

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3301]
With ALTREP in R 3.5+ it's no longer true that defining USE_RINTERNALS before including Rinternals.h makes REAL(), INTEGER() etc into macros.   That's why I did it originally and it's no longer true, so there's no point in doing it anymore. It was good advice because it was a lot faster. The new advice with R 3.5+ is to not use the R API inside loops.
See also: https://github.com/Rdatatable/data.table/issues/2866#issuecomment-389643625 and https://github.com/Rdatatable/data.table/issues/3188#issuecomment-444757748

Section 5.14 of R-exts manual contains : 

> If efficiency is essential, the internal versions of the accessors can be obtained by defining ‘USE_RINTERNALS’ before including Rinternals.h. If you find it necessary to do so, please do test that your code compiles without ‘USE_RINTERNALS’ defined, as this provides a stricter test that the accessors have been used correctly. Also be prepared to adjust your code should R internals change. 
> The accessor functions, and other functions in the R API, are also subject to change to support the ‘ALTREP’ project (https://svn.r-project.org/R/branches/ALTREP/ALTREP.html). Code that does not define ‘USE_RINTERNALS’ should not be affected by these changes, but code that does define ‘USE_RINTERNALS’ may need to be adjusted.

I've tried turning off USE_RINTERNALS and data.table compiles and passes all tests with latest versions of R because DATAPTR is exposed in the R API. But still we're not supposed to use it. Not passing R 3.1.0 until DATAPTR is removed (~72~ 22 calls) : 
- [x] assign.c (#3610 #4095; v1.12.8)
- [x] bmerge.c (#3610; v1.12.4)
- [x] dogroups.c (#3610 #4164; v1.12.10)
- [x] fmelt.c (#3350; v1.12.2)
- [x] freadR.c [#4164; v1.12.10]
- [x] fwriteR.c [#4164; v1.12.10]
- [x] gsumm.c (#3350; v1.12.2)
- [x] quickselect.c (#3377; v1.12.2)
- [x] rbindlist.c (#3350 #3455; v1.12.2)
- [x] reorder.c (#4164; v1.12.10)
- [x] shift.c (#3348; v1.12.2)
- [x] uniqlist.c (#3350; v1.12.2)

**Comment by jangorecki** [comment]
Code from `quickselect.c` is not being used anywhere, I suggest to remove that file. It is being compiles on each installation, unnecessarily. If we will remove it nicely in separate commit, in separate PR, it will be easy to find it later on if needed.

**Comment by mattdowle** [comment]
@jangorecki  `dquickselect` and `iquickselect` in quickselect.c are being used in gsumm.c.  But the single use of DATAPTR in it is commented out, so that part can be removed.
