### ISSUE TITLE
Record `DT[, lapply(.SD, anyNA)]` as an attribute 

### ISSUE THREAD

**Issue by HughParsonage** [Rdatatable/data.table#3323]
I've been writing a few basic functions to operate on atomic vectors. Things like `if_else` and `range`. One thing that sticks with me is that handling missing values forms a considerable part of both the code base and the run time performance. So much so that for some functions I even allow an argument `nas_absent = TRUE|FALSE` so that if I *know* the vector has no missing values I can take a shortcut. 

I propose data.table provide an attribute that, on request, records `anyNA` for each column.

We could use this attribute internally too: most gforce functions should be able to harness this for considerable improvement run time performance. 

Related: https://github.com/Rdatatable/data.table/issues/3161

(I believe an issue was raised to record this and other information during `fread`, which would be sensible.)

**Comment by MichaelChirico** [comment]
Duplicate (subset) of #2879?

**Comment by HughParsonage** [comment]
Ah yes! I searched for 'information', 'anyNA', and 'missing', but it looks like the battleships were on other squares...

**Comment by MichaelChirico** [comment]
I had to remember Jan posted the issue, and search by author
