### ISSUE TITLE
macOS / OSX builds in GLCI

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3326]
We already have linux and windows builds in CI. While linux covers most of all macOS potential issue, there exists some that are macOS specific, as the one reported in https://github.com/Rdatatable/data.table/issues/3300#issuecomment-458032675.
It would be then valuable to have macOS runners.
Whenever there will be some macOS machine we could put our runner into, please @abal5 let us know. It would run only master branch so the overall load made by the runner would be pretty low. C compiles fast, and our tests, while there are many of them, they are quite compact. Linux builds takes from 6min to 15min, depending on the config.

**Comment by abal5** [comment]
we have mr-0xb11 to use

**Comment by jangorecki** [comment]
Thanks to @MarcusKlik we now have macOSX builds running on Travis. Still it would be good to include them in our GitLab pipelines so OSX binaries can be published together with Windows binaries in same repository.

**Comment by ben-schwen** [comment]
We could use the already available beta runner for macos if we apply for the Gitlab open source program.

**Comment by jangorecki** [comment]
It is very good idea, please GI ahead! This way we can provide binaries if devel version also for Mac users.

**Comment by ben-schwen** [comment]
Done by #6389
