### ISSUE TITLE
NEWS file

### ISSUE THREAD

**Issue by ggrothendieck** [Rdatatable/data.table#3336]
The NEWS file does not appear in 

 https://CRAN.R-project.org/package=data.table

or in `help(package = data.table)` .

**Comment by mattdowle** [comment]
Hi Gabor.
NEWS is there next to README.  Do you see something different?

![image](https://user-images.githubusercontent.com/2779998/52016568-bfebab00-2499-11e9-83bc-d02b4697a1a6.png)

**Comment by ggrothendieck** [comment]
You are right about the CRAN site but if you do this you will see the NEWS for zoo in your browser:

```
help(package = zoo)
```

That is this appears:

```
S3 Infrastructure for Regular and Irregular Time Series (Z's Ordered Observations) 
 
Documentation for package ‘zoo’ version 1.8-4
DESCRIPTION file.
User guides, package vignettes and other documentation.
Code demos. Use demo() to run them.
Package NEWS.   <------------------------------------------------------
```

**Comment by MichaelChirico** [comment]
@ggrothendieck confirming... i don't see anything on `?help` though that suggests how that `help(package = data.table)` page is compiled though, any idea?

**Comment by ggrothendieck** [comment]
You have to pre-process the NEWS file first.  If I do this:

```
cd data.table
pandoc NEWS.md -o NEWS -t plain
cd ..
R CMD INSTALL data.table
```
then the help does appear as shown below:

```
Extension of `data.frame` 
 
Documentation for package ‘data.table’ version 1.12.0
DESCRIPTION file.
User guides, package vignettes and other documentation.
Package NEWS. <------------------------------------------------------------
```
