### ISSUE TITLE
rbind/rbindlist failing on empty input when source is NULL list

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3343]
```
DT1 = list(a = NULL)
DT2 = list(a = NULL)
setDT(DT1)
setDT(DT2)

rbind(A = DT1, B = DT2, idcol = 'id')
```

> Error in rbindlist(l, use.names, fill, idcol) : 
>  attempt to set an attribute on NULL

It's because `class(DT1$a)` is `NULL`. I'm not sure what attribute is being set.

Or maybe this is a problem with `setDT`?

Fix for me now is to correct my upstream inputs for the empty cases, but this error seems wrong.

**Comment by jangorecki** [comment]
This doesn't seems to be proper DT in the first place, `setDT(DT1<-list(a=list(NULL)))`. AFAIR we don't allow a column to be NULL.

**Comment by MichaelChirico** [comment]
Jan I think you're right. Solved my issue by fixing upstream laziness.

I was trying to create an empty schema data.table for edge cases like 

```
DT_empty = data.table(a = numeric(), b = integer())
```

But was trying to get away without having to specify the column types in my 0-row edge case and allow `rbindlist` to just squash them away when it sees the right number of columns + names. `setDT(sapply(col_names, function() NULL))` was the most concise route but led to this error.

Agree my approach is not recommended, but something should be fixed here, I think... certainly the error message is confusing.

**Comment by jangorecki** [comment]
related #2305
