### ISSUE TITLE
The foverlaps() function seems produce an incorrect answer (data.table 1.12.0)

### ISSUE THREAD

**Issue by lux5** [Rdatatable/data.table#3349]
Hi,

The `foverlaps()` function seems produce an incorrect answer - the detailed description of the issue and sample codes/data were posted by me in [here](https://stackoverflow.com/questions/54247663/overlap-join-cut-by-data-tablefoverlaps-function-when-assigning-flood-event-id).

Could anyone have a look and give a try on the posted sample codes? Many thanks!

BTW, I am using data.table 1.12.0 running on R version 3.5.2 (2018-12-20).

**Comment by arunsrinivasan** [comment]
I can't access the dropbox link you provided in your SO post. Are you sure it's functional?

**Comment by arunsrinivasan** [comment]
Nevermind, the link works fine. Found the issue and just patched. Will test and push.

**Comment by lux5** [comment]
Thank you for the fix arunsrinivasan.

data.table always makes my work a lot of easier.
I am looking forward to the updated version ;)
