### ISSUE TITLE
platform independent timing in C

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3358]
Timing C code is a platform independent way is a tricky process. If we could incorporate some helper function for that, then we would be able to collect more detailed timings, including timings from parallel regions. Those could be reported back to user, if `verbose` was used, giving some more detailed insight.

**Comment by st-pasha** [comment]
would [omp_get_wtime()](https://gcc.gnu.org/onlinedocs/libgomp/omp_005fget_005fwtime.html) help?

**Comment by jangorecki** [comment]
Thanks @st-pasha, applied in #3341.
