### ISSUE TITLE
Semantically invalid name not recognized when passed to keyby

### ISSUE THREAD

**Issue by HughParsonage** [Rdatatable/data.table#3378]
Reprex:

``` r
library(data.table)
DT <- data.table(x = 1:5, y = letters[1:5])
setnames(DT, "x", "x y")
DT[, y := "j", keyby = "x y"]
#> Warning in `[.data.table`(DT, , `:=`(y, "j"), keyby = "x y"): := keyby not straightforward character column names or list() of column names, treating as a by:`x y`
```

<sup>Created on 2019-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It should work as it does with `by`.

**Comment by MichaelChirico** [comment]
Hugh what monstrous column names are you concocting over there

**Comment by HughParsonage** [comment]
You don't want to know.

But in all seriousness, for things like printable tables and plots you don't want `.` or `_` in your names. And it's safer to use the displayed name rather than using a placeholder and replacing it.
