### ISSUE TITLE
#3281 appears to cause as.IDate to update by reference

### ISSUE THREAD

**Issue by HughParsonage** [Rdatatable/data.table#3385]
#3281 

Old behaviour

```r
x <- 500L
as.IDate(x)
#> [1] "1971-05-16"
x
#> 500
```

New behaviour:

```r
x <- 500L
as.IDate(x)
#> [1] "1971-05-16"
x
#> [1] "1971-05-16"  # oops
```

I think this should be reverted.

**Comment by MichaelChirico** [comment]
Something slipped through the cracks...

**Comment by HughParsonage** [comment]
Looking at the PR, you were rightly concerned about `structure`, but I think `attr()<-` is plenty quick. I suspect Matt avoided it back in the day when it made deep copies, but R has since become a lot smarter about this stuff.

**Comment by MichaelChirico** [comment]
problem here is `as.integer` is not guaranteed to produce a copy, to wit, if the input is an integer it just returns (no copy). Can just force that.
