### ISSUE TITLE
Fix or remove usages of sample() in tests

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3430]
Noted [here](https://twitter.com/groundwalkergmb/status/1100190052125237248)

> Major #rstats #reproducibility PSA - Narrow but significant bias issue in sample() (id'ed by @kellieotto + P Stark) fixed in r-devel. Be aware set.seed + sample code ***will give different results*** than in previous R versions by default. Credit D Murdoch + @LukeTierney4

Paper about bias in `sample()`:

https://arxiv.org/pdf/1809.06520.pdf

It stands to reason we should expect `r-devel` tests to start crashing any day now:

```
$ grep sample inst/tests/tests.Rraw | wc -l 
305
$ grep sample inst/tests/* | wc -l
335
```

To the extent possible, most of these tests should be replaced by a hard-coded version...

**Comment by jangorecki** [comment]
Or we can safely use RNGkind function, no?

**Comment by MichaelChirico** [comment]
Unless I'm missing something, no:

```
sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2  
```

```
formals(RNGkind)
$kind
NULL

$normal.kind
NULL
```

I think `sample` argument is being added to accommodate the change, it hasn't been around since 3.1.0 e.g.

**Comment by MichaelChirico** [comment]
Unless we can just replicate what's done here:

https://github.com/wch/r-source/commit/e4acfd1f240a42b3fc1474a4d97017114e4eb053

**Comment by jangorecki** [comment]
lets close it as dup of #3431
