### ISSUE TITLE
problems using .SD and with = F 

### ISSUE THREAD

**Issue by Ravin515** [Rdatatable/data.table#3466]
I'm working with selecting all of the double vector by `sapply` function in j. **When I use DT name, it works**:
`mtcars[, sapply(mtcars, is.double), with = F] %>% head()`

However, **it doesn't work with .SD**, which output a emtpy DT:
`mtcars[, sapply(.SD, is.double), with = F] %>% head()`

I tried to test some mutation of this pattern, finally, I find that `with = F` can not be used with .SD.
So, my question is this problem is a special designation for data.table or a bug?
It will be solved just like  just like `.SD` with `:=`?

**Comment by franknarf1** [comment]
From the docs:

> By default `with=TRUE` and `j` is evaluated within the frame of `x`

I believe `.SD` is only defined in that context and is otherwise NULL. Unfortunately, I don't think there's a way to avoid typing the table's name a second time inside `DT[...]` but one extension for that is requested in https://github.com/Rdatatable/data.table/issues/1786

**Comment by MichaelChirico** [comment]
also

```
mtcars[ , lapply(.SD, function(x) if (is.double(x)) x else NULL)]
```

**Comment by MichaelChirico** [comment]
Just read Frank's reference, I think this is a dupe, please re-open if you think not

**Comment by Ravin515** [comment]
Thank you for all !
