### ISSUE TITLE
Bug: Setting a column of a dt inside a listcolumn of a dt fails

### ISSUE THREAD

**Issue by jakob-r** [Rdatatable/data.table#3474]
Setting a column of a data table inside a listcolumn of a data tabke fails if the outer data.table has only one row:
```r
inner = data.table(a = 1:3, b = 1:3)
outer = data.table(aa = 1, ab = list(inner))
outer$ab[[1]]$b = 3L
```
```
Warning message:
In `[<-.data.table`(x, j = name, value = value) :
  Supplied 2 items to be assigned to 1 items of column 'ab' (1 unused)
```
```r
outer$ab
```
```
[[1]]
 [1]  1  2  3
```

However the following works as expected:
```r
outer$ab[[1]][, b := 3L]
outer$ab
```
```
[[1]]
       a     b
   <int> <int>
1:     1     3
2:     2     3
3:     3     3
```

Note that this bug only seems to occur if the outer data.table has just one row.

**Comment by jangorecki** [comment]
Thanks for reporting, note that behaviour of your code slightly changed in development version, but issue is still valid. If you are not reporting on recent devel it is always useful to include `sessionInfo()` output.
