### ISSUE TITLE
rename alloc.col to set.alloc.col

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3475]
for consistency

**Comment by MichaelChirico** [comment]
If we're going to change, I wouldn't use `set.alloc.col` which sounds odd.

`set_allocated_columns` or the like would be more expressive & help get at what it's doing

**Comment by shrektan** [comment]
A little off-topic, but I really wish one day there's a way to auto set `alloc.col()` to the `data.table` objects from RDS files...
