### ISSUE TITLE
`-`(Date, IDate) throws a warning and wrong output

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3490]
```
as.Date(Sys.Date()) - as.IDate(Sys.Date())
# [1] "1970-01-01"
```
> Warning message:
Incompatible methods ("-.Date", "-.IDate") for "-" 

Output should be `0` `difftime` object

**Comment by MichaelChirico** [comment]
Relevant thread:

http://r.789695.n4.nabble.com/quot-Incompatible-methods-quot-for-overloaded-operator-td4633362.html

**Comment by MichaelChirico** [comment]
Maybe we should `wontfix` this?

**Comment by jangorecki** [comment]
@MichaelChirico agree, we can think about it if it will come back.
