### ISSUE TITLE
froll 9999.025 test failure on non-x86 systems

### ISSUE THREAD

**Issue by QuLogic** [Rdatatable/data.table#3491]
The latest data.table 1.12.2 fails on [ppc64le](https://koji.fedoraproject.org/koji/taskinfo?taskID=34042967), [aarch64](https://koji.fedoraproject.org/koji/taskinfo?taskID=34042969), and [s390x](https://koji.fedoraproject.org/koji/taskinfo?taskID=34042973), which did not occur in 1.12.0.

The error is:
```
Running the tests in 'tests/froll.R' failed.
Last 13 lines of output:
        ID   time nTest
   1: 9999 10.952   586
   2:    2  0.000     0
   3:    3  0.000     0
   4:    4  0.000     0
   5:    5  0.000     0
   6:    6  0.000     0
   7:    7  0.000     0
   8:    8  0.000     0
   9:    9  0.000     0
  10:   10  0.000     0
  
  Error in test.data.table(script = "froll.Rraw") : 
    1 error out of 586 in 15.7s elapsed (11.3s cpu) on Mon Apr  8 03:00:23 2019. [endian==little, sizeof(long double)==16, sizeof(pointer)==8, TZ=NA, locale='C', l10n_info()='MBCS=FALSE; UTF-8=FALSE; Latin-1=FALSE', getDTthreads()='omp_get_num_procs()==4; R_DATATABLE_NUM_PROCS_PERCENT=="" (default 50); R_DATATABLE_NUM_THREADS==""; omp_get_thread_limit()==2147483647; omp_get_max_threads()==4; OMP_THREAD_LIMIT==""; OMP_NUM_THREADS==""; data.table is using 2 threads. This is set on startup, and by setDTthreads(). See ?setDTthreads.; RestoreAfterFork==true']. Search tests/froll.Rraw for test number 9999.025.
```

# Minimal reproducible example
```bash
$ _R_CHECK_FORCE_SUGGESTS_=0 R CMD check data.table
```
(xts and nanotime are not packaged yet, so I need to skip the Suggests check.)

# Output of `sessionInfo()`
I cannot get this directly as it's on a builder.

# PS.
> By continuing to file this new issue / feature request, I confirm I have :
> 6. used tags under the labels menu on the right of this page, not text prefixes in the title.

This is not possible for non-contributors.

**Comment by QuLogic** [comment]
> # Output of `sessionInfo()`
> 
> I cannot get this directly as it's on a builder.

The closest I can get is the output from a local build:
```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 31 (Rawhide)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3
```
(but obviously the platform will be different.)

**Comment by jangorecki** [comment]
Thanks for reporting. Could you please check `.Machine$sizeof.longdouble` on those platforms?
Also if possible could you edit `inst/tests/froll.Rraw` from:
```r
test(9999.025, errs[["froll_fast"]]>errs[["froll_exact"]])
```
to use `==` instead of `>`,
to:
```r
test(9999.025, errs[["froll_fast"]]==errs[["froll_exact"]])
```
and see if it will pass?

**Comment by QuLogic** [comment]
For igraph, I patch in some `if (Sys.info()["machine"] %in% c("aarch64", "ppc64", "ppc64le", "s390x")) {` (or whatever arch is appropriate for the test.) This is based on [their existing test arch checks](https://github.com/igraph/rigraph/blob/675946d0d30a3e29b3562a76d25a52faf2332240/tests/testthat/test_layout.kk.R#L11).

**Comment by QuLogic** [comment]
Also, this test seems to be asserting that the fast algorithm is less exact than the exact algorithm. But is that actually required (or can it be `>=`)?

**Comment by jangorecki** [comment]
@QuLogic I doubt it will be equal, thus `>=` will not help

**Comment by QuLogic** [comment]
> Regarding `>=`, I doubt it will be equal, thus `>=` will not help.

But since it fails with `>`, then it must be equal, less (impossible due to `abs`), or perhaps `NaN`; I suppose I could try and check for this last case.

**Comment by jangorecki** [comment]
@QuLogic why impossible?  `sum(abs(1)) < sum(abs(2))`

**Comment by QuLogic** [comment]
Yes, that's true for arbitrary numbers, but I'm assuming from 9999.024 that `errs[["froll_exact"]]==0` (which did not have a `sizeof.longdouble` check in 1.12.2 and did not fail above), so the 9999.025 check is `errs[["froll_fast"]] > errs[["froll_exact"]]` -> `errs[["froll_fast"]] > 0` -> `sum(abs(ans3-ans1)) > 0`. It is for _that_ comparison that I'm saying it cannot be less, as `abs` cannot be less than 0 (unless complex, but I don't think the random data is.)

**Comment by jangorecki** [comment]
Thanks for clarification, still we cannot assume 024 will successfully pass, if we would like to then the test should be wrapped into `if` to test if 024 actually was successful. Also 024 has now escape for `sizeof.longdouble!=16` so might not be tested at all.
