### ISSUE TITLE
How to eliminate comment lines from csv using `fread` function in R?

### ISSUE THREAD

**Issue by bhavneetattri1995** [Rdatatable/data.table#3493]
I trying to read a CSV file which has some comment lines(start with #) along with data rows. [fread](https://www.rdocumentation.org/packages/data.table/versions/1.12.0/topics/fread) function is used to read this CSV file.

`config <- fread("Configuration.csv")`

![CSV  File](https://user-images.githubusercontent.com/42670674/55705966-a61c9600-59fd-11e9-9b97-6f095e769b2d.png)

In this file number of lines are not fixed they might be changed. How to read the CSV without these comment lines.

#### Thanks in Advance!!!

**Comment by MichaelChirico** [comment]
this is an outstanding feature request:

https://github.com/Rdatatable/data.table/issues/856

Please refer to there for some helpful tricks for getting around this now.

If you're still stuck, please raise the issue on StackOverflow for further help :)
