### ISSUE TITLE
 data.table::dcast.data.table documentation suggestion

### ISSUE THREAD

**Issue by thierrygosselin** [Rdatatable/data.table#3497]
`data.table::dcast.data.table` seems to automatically transform my _character_ `value.var` into  _factors_. I've spent 10 min searching the documentation of the function and closely related function `data.table::melt.data.table `. The later one as a really nice argument that by default is `value.factor = FALSE`. I would like to have the same thing for `data.table::dcast.data.table`.

I did search the **issues**, but theirs 736 open ones... it's a bit overwhelming so no worries if you don't have time answering this one... I'll close it in a couple of days. I have a plan B.

**Comment by shrektan** [comment]
I agree `factors` is the last thing that I want to have by default....

**Comment by jangorecki** [comment]
So lets keep that open as feature request. @thierrygosselin for future please provide minimal example.

**Comment by arunsrinivasan** [comment]
Please provide a minimal example of the issue.

**Comment by arunsrinivasan** [comment]
Please reopen if you manage to provide a minimal example.
