### ISSUE TITLE
Help text of J and CJ

### ISSUE THREAD

**Issue by Henrik-P** [Rdatatable/data.table#3511]
Some suggestions for the `J` and `CJ` help page:

-----

**Header**
Creates A Join Data Table -> Creates a join `data.table`

-----

**Usage**
`# DT[J(\dots)]`
Why is the `J` example commented away?

-----

`DT[J(\dots)]` -> `DT[J(...)]`
`DT[\dots]` -> `DT[...]`
`DT[SJ(\dots)]` -> `DT[SJ(...)]`

I assume it's the `#` which messes with the rendering of `\dots`

-----

**Arguments**
**sorted** Should the input be sorted (ascending order)?

I think it should be described that `sorted` is not "only" about sorting, but also whether keys are set. Now the key part is only mentioned in the first `CJ` example. Perhaps borrow the wording in **Value** of `SJ`:

>Should `setkey()` be called on all the columns in the order they were passed to `CJ`?

And similar for "If `FALSE`, the input order is retained":

>If `FALSE`, the result is unkeyed and input order is retained

------

**Value**

(S)orted (J)oin -> **S**orted **J**oin
(C)ross (J)oin -> **C**ross **J**oin

It looks a bit cluttered with the parentheses. I suggest a bold first letter instead. This also makes it consistent with the style used in the help text of `.SD`.

Again, I think it should be mentioned that the result of `CJ` is keyed (see above).

-----

**Examples**

`DT = data.table(A=5:1,B=letters[5:1])` -> `DT <- data.table(A = 5:1, B = letters[5:1])`
`setkey(DT,B) # re-orders` -> `setkey(DT, B) # reorders`

Insert spaces for readability (here and in other places), no dash in reorder.

`DT[.("b")]      # same. Style of package plyr.`

The dot alias for `list` now feels like an integral part of `data.table`, so no need to refer to another package, especially not the semi-deprecated `plyr` package. If anything, refer to relevant `data.table` docs on `.( )`.

**Comment by MichaelChirico** [comment]
LGTM, please file a PR! Thanks

**Comment by Henrik-P** [comment]
Thanks for your feedback Michael. I will be computer-free for some time now, so please don't anticipate a PR very soon.
