### ISSUE TITLE
between changed behaviour from NA bounds 'unknown' to 'missing'

### ISSUE THREAD

**Issue by cguill95** [Rdatatable/data.table#3522]
Dear all,

I have discovered recently the change introduced in version 1.12.0 regarding `between` and how `NA` are now treated.

Given this change may break routines relying on the previous behavior, I was wondering whether in the future a parameter could be introduced so that `NA` are not treated as missing values but as `NA` (i.e. would return the same as `x >= lower & x <= upper`).

Thank you very much

Best,
Cyrille

**Comment by jangorecki** [comment]
@cguill95 thanks for reporting this regression, for future please try to always include reproducible example.
```r
install.packages("data.table")
library(data.table)
between(1:5, 2L, NA, incbounds=TRUE)
#[1] FALSE  TRUE  TRUE  TRUE  TRUE
```
```r
install.packages("https://cran.r-project.org/src/contrib/Archive/data.table/data.table_1.11.8.tar.gz")
library(data.table)
between(1:5, 2L, NA, incbounds=TRUE)
#[1] FALSE    NA    NA    NA    NA
```
