### ISSUE TITLE
[fread] When reading column with only digits (0-9), if any of the values starts with 0, the column should be coerced into character vector.

### ISSUE THREAD

**Issue by artidata** [Rdatatable/data.table#3527]
When dealing with digits only characters, fread automatically coerce them into integers.
```
> fread(text="V1,V2\n12,123")
   V1  V2
1: 12 123
```
Such feature is good as it will conserve the amount of memory required. 

However, variables such as zip codes and phone number may have digit values that starts with 0. 
Currently, the default will also coerced them into integer, 
```
> fread(text="V1,V2\n012,123")
   V1  V2
1: 12 123
```
As a result leading 0s are deleted and users have to manually add the leading 0s. Hence, I would like to suggest that fread should coerce back to character and retain the zeros.
My desired output will be:
```
> fread(text="V1,V2\n012,123")
   V1  V2
1: 012 123
```
Let me know whether this can be a viable feature.

**Comment by artidata** [comment]
Note that, I know that the you can specify it in parameter colClasses to prevent the removal of leading 0s. I just thought that it will be a good default.

**Comment by jangorecki** [comment]
https://github.com/Rdatatable/data.table/issues/2999
