### ISSUE TITLE
Completely axe reshape2 from code

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3549]
As mentioned in #3542, [`reshape2` is dead since a year ago](https://github.com/hadley/reshape).

We removed it from suggests but still have some snippets like:

```
    ns = tryCatch(getNamespace("reshape2"), error=function(e)
         stop("The dcast generic in data.table has been passed a ",class(data)[1L]," (not a data.table) but the reshape2 package is not installed to process this type. Please either install reshape2 and try again, or pass a data.table to dcast instead."))
    ns$dcast(data, formula, fun.aggregate = fun.aggregate, ..., margins = margins,
             subset = subset, fill = fill, value.var = value.var)
```

I don't think it makes sense to support such functionality anymore.

Question is, are we safe to just get rid of it right away, or do we need to lifecycle it out?

**Comment by jangorecki** [comment]
According to comment (probably very old one) in `melt`
```
    # if data is not data.table and reshape2 is installed, this won't dispatch to reshape2's method;
    # CRAN package edarf and others fail without the else branch
```

Question is, should we create generic methods for `dcast` and `melt`?

**Comment by MichaelChirico** [comment]
I thought we already have such generics?

**Comment by MichaelChirico** [comment]
lines 98-108 of NAMESPACE?

**Comment by MichaelChirico** [comment]
> By default, if any of the columns to be melted are of type `factor`, it'll be coerced to `character` type. This is to be compatible with `reshape2`'s `melt.data.frame`.

Now that we're taking ownership of `dcast`/`melt`, do we want to continue this backward-compatibility?

Of course we'd have to go through a deprecation cycle, but ultimately do we agree with this behavior?

**Comment by lionel-** [comment]
FWIW reshape2 is not dead nor deprecated, it is only "retired". This means that development has stopped but it continues to be maintained on CRAN and will continue to work for the foreseeable future.

**Comment by hadley** [comment]
You can see our lifecycle definitions at https://www.tidyverse.org/lifecycle/#retired.
