### ISSUE TITLE
CJ can handle list() input if sorted=FALSE but fails confusingly

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3597]
```
CJ(1:2, list(1:3, 1))
```

> Error in forderv(y, retGrp = TRUE) : 
  Column 2 is length 1 which differs from length of column 1 (3)

```
CJ_old(1:2, list(1:3, 1), sorted = FALSE)
   V1    V2
1:  1 1,2,3
2:  1     1
3:  2 1,2,3
4:  2     1
```

The logic for building the `CJ` output from `list` input is the same, but `sorted` has to be `FALSE` because there's no ordering of lists.

We can either `stop` here or force `sorted = FALSE`... either way the current behavior is confusing.

**Comment by jangorecki** [comment]
I don't think we need to support list. There was idea to make it generic so there can be data.table method... https://github.com/Rdatatable/data.table/issues/1717#issuecomment-355499952

**Comment by MichaelChirico** [comment]
we don't need to support it, but it's also extremely easy to build in the current logic as well as that in #3596.
