### ISSUE TITLE
Full column plonk in join results in type coercion

### ISSUE THREAD

**Issue by Gayyam** [Rdatatable/data.table#3642]
I am attempting to use joins as a means to bypass an expensive conversion from Julian dates to character to R dates. When I try to update the existing integer Julian date with the new Date column, I get a type mismatch warning even though this is a full column plonk. Thus, I have to use an extra step after the join to convert back to dates.

Consider the following - 

```
library(data.table)
set.seed(1)
n <- 1e8
JDate <- 2019001L:2019365L
dailyData <- data.table(
  Date = sample(JDate, size = n, replace = TRUE), 
  value = runif(n)
)
julianDT <- data.table(JDate)
julianDT[, Date := as.Date(as.character(JDate), format = '%Y%j')]
# Slow operation I intend to avoid
system.time(
  dailyData[, newDate := as.Date(as.character(Date), format = '%Y%j')]
)
# Approximately 13 times faster on my machine, but results in a warning
system.time(dailyData[julianDT, on = c(Date = 'JDate'), Date := i.Date])
# Warning message:
# In `[.data.table`(dailyData, julianDT, on = c(Date = "JDate"), `:=`(Date,  :
#  Coerced double RHS to integer to match the type of the target column (column 1 named  'Date'). The RHS values contain no fractions so would be more efficiently created as integer.  Consider using R's 'L' postfix (typeof(0L) vs typeof(0)) to create constants as integer and avoid  this warning. Wrapping the RHS with as.integer() will avoid this warning too but it's better if  possible to create the RHS as integer in the first place so that the cost of the coercion can be  avoided.
dailyData[, Date := as.Date(Date, origin = '1970-01-01')]
dailyData[, all(Date == newDate)]
# [1] TRUE
```

So, my question is: is this avoidable?

<details><summary>sessionInfo()</summary>

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252    LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                         LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.3

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    yaml_2.2.0    
```

**Comment by franknarf1** [comment]
Re "is this avoidable?" you can do 

```
system.time(dailyData[, Date := julianDT[.SD, on = .(JDate = Date), x.Date]])
```

I think a plonk only occurs when there is no i argument, so it is guaranteed that all rows are being modified. Fwiw, I never find a need for the x[i, v := i.v] form.

**Comment by Gayyam** [comment]
Thanks Frank. Yes, that works. 

However, in my subjective opinion, that requires needless typing. What would be the pros and cons of making `x[i, v := i.v]` "just work"?

**Comment by franknarf1** [comment]
Np. My guess about the cons:

- You would need to confirm that x's rows are a subset of those associated with i, which could be computationally costly. 
- The consequences for v being plonked or not would depend on complicated conditions not resulting from the syntax of the call but instead the comparison of rows. This means that you wouldn't know what was going to happen until after running it.

I noted some of the pros of the way with more typing on SO, fwiw: https://stackoverflow.com/a/54313203

**Comment by Gayyam** [comment]
Thanks Frank. Makes sense.

**Comment by MichaelChirico** [comment]
Related: #2925, #2818

**Comment by MichaelChirico** [comment]
You can also save more typing by using `as.IDate` since `origin = '1970-01-01` by default ;-)

```
dailyData[, Date := as.IDate(Date)]
```

You could also use `.Date`:

```
dailyData[, Date := .Date(Date)]
```

But seeing as how you have a massive table, I'd use `IDate` anyway unless you really need fractional dates
