### ISSUE TITLE
setkey() affects the behaviour of head()

### ISSUE THREAD

**Issue by hadley** [Rdatatable/data.table#3643]
I found this surprising:

``` r
library(data.table)

dt <- data.table(x = runif(5), y = 5:1)
head(dt, 1)
#>          x y
#> 1: 0.88266 5

setkey(dt, y)
head(dt, 1)
#>            x y
#> 1: 0.9731627 1
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by MichaelChirico** [comment]
it's late and I must be missing something... what's surprising?

setkey sorts in place? could you print DT and/or include a seed? and/or say the expected output

**Comment by hadley** [comment]
I would expect `head(dt, 1)` to return the first row of `dt`.

**Comment by hadley** [comment]
Oh it _sorts in place_.

**Comment by MichaelChirico** [comment]
yes, all `set` functions operate in-place and I believe they all return the modified object for chaining
