### ISSUE TITLE
rbindlist raises malformed factor

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3662]
recent devel
```r
rbindlist(list(data.table(a=as.factor(1:2), b=as.factor(2:3)),
          list(a=as.factor(3L), b=as.factor(4:5))))
#Error in as.character.factor(x) : malformed factor
```
error could be improved

on 1.12.2 it segfaults

**Comment by MichaelChirico** [comment]
Actually this still segfaults for me:

```
library(data.table)
# data.table 1.12.3 IN DEVELOPMENT built 2019-07-07 12:06:15 UTC using 4 threads (see ?getDTthreads).  Latest news: r-datatable.com
rbindlist(list(data.table(a=as.factor(1:2), b=as.factor(2:3)), list(a=as.factor(3L), b=as.factor(4:5))))
```

```
 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: rbindlist(list(data.table(a = as.factor(1:2), b = as.factor(2:3)),     list(a = as.factor(3L), b = as.factor(4:5))))
```

**Comment by MichaelChirico** [comment]
The segfault is caused here:

https://github.com/Rdatatable/data.table/blob/0ba914488fbd21cf1c66006de4bdac29818e34cc/src/rbindlist.c#L444-L453

I don't 100% follow the logic of what's going on here, but I believe the `break` is meant to break out of a different loop than it's breaking (or there's meant to be two `break`s).

If I change the `memcopy` section to also `break`, we still get the `malformed factor` error, but no segfault:

```
if (nohop) {
  memcpy(targetd+ansloc, INTEGER(thisCol), thisnrow*SIZEOF(thisCol));
  break; // <- new break
}
```

**Comment by mattdowle** [comment]
Recycling is missing in that section. Needed to recycle the length-1 `as.factor(3L)` in this example. Will add the mask trick.
