### ISSUE TITLE
character column of x no longer available as ii in x[ y[ii] ]

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#3669]
I used code like this for a long time:

```
# example
library(data.table)
# data.table 1.12.3 IN DEVELOPMENT built 2019-06-19 19:02:40 UTC; travis using 4 threads (see ?getDTthreads).  Latest news: r-datatable.com
iDT = data.table(key = "i_id",
    i_id = c("A", "B", "C", "D"), 
    g = state.name[c(1,1,2, 3)], 
    e_date = as.IDate(c("2019-01-20", "2019-01-20", "2019-01-01", "2019-01-01")),
    e_time = as.ITime(c("14:00", "20:00", "20:00", "20:00"))
)
set.seed(1)
vDT = data.table(i_id = unique(iDT$i_id))[, .(v = runif(5,0,10), p = sample(c(5,5,10,10,10))), by=i_id]

# old code that now errors due to bare i_id in the i= clause
vDT[c("B", "C", "A"), on=.(i_id), .N, by=.EACHI][iDT[i_id, order(e_date, e_time)]]

# longer/clearer version of the same
tmp = vDT[c("B", "C", "A"), on=.(i_id), .N, by=.EACHI]
tmp[iDT[i_id, order(e_date, e_time)]]
```

but the last line now yields 

> Error in `[.data.table`(iDT, i_id, forder(x, e_date, e_time)) : 
  i_id is not found in calling scope but it is a column of type character. If you wish to select rows where that column contains TRUE, or perhaps that column contains row numbers of itself to select, try DT[(col)], DT[DT$col], or DT[col==TRUE] is particularly clear and is optimized. When the first argument inside DT[...] is a single symbol (e.g. DT[var]), data.table looks for var in calling scope.

Contrary to the error message, `i_id` is in calling scope from `tmp`, right? Here's working code illustrating expected behavior:

```
tmp[iDT[tmp$i_id, order(e_date, e_time)]]
#    i_id N
# 1:    C 5
# 2:    A 5
# 3:    B 5
```

My code was confusing (took me a minute to figure out what I was trying to do before I could start debugging) so I don't mind if the idiom I used no longer works. I'm just bringing it up in case the scoping is intended to work there.

**Comment by MichaelChirico** [comment]
The advice of the error message works though right?

```
vDT[c("B", "C", "A"), on=.(i_id), .N, by=.EACHI][iDT[(i_id), order(e_date, e_time)]]
#    i_id  N
# 1:    A  5
# 2: <NA> NA
# 3:    B  5
# 4:    C  5
```

**Comment by franknarf1** [comment]
@MichaelChirico Thanks, yes, that works. I was just reporting since it used to work without needing to be wrapped in parentheses. If no one else minds the change in behavior and no rev deps are impacted either, maybe the issue could be closed.

Side note: I ran into a seg fault when messing around with the example, below. Please let me know if I should open a new issue. 

```
library(data.table)
# data.table 1.12.3 IN DEVELOPMENT built 2019-09-02 09:13:56 UTC; root using 4 threads (see ?getDTthreads).  Latest news: r-datatable.com
iDT = data.table(key = "i_id",
    i_id = c("A", "B", "C", "D"), 
    g = state.name[c(1,1,2, 3)], 
    e_date = as.IDate(c("2019-01-20", "2019-01-20", "2019-01-01", "2019-01-01")),
    e_time = as.ITime(c("14:00", "20:00", "20:00", "20:00"))
)
set.seed(1)
vDT = data.table(i_id = unique(iDT$i_id))[, .(v = runif(5,0,10), p = sample(c(5,5,10,10,10))), by=i_id]

tmp = vDT[c("B", "C", "A"), on=.(i_id), .N, by=.EACHI]
tmp[iDT[.(.SD$i_id), order(e_date, e_time)]]
```

**Comment by MichaelChirico** [comment]
I wouldn't close as it is a regression. If we're going to break something we need to report it.

That code didn't segfault for me, please report in a new issue if it's still failing from dev master

**Comment by mattdowle** [comment]
@MichaelChirico on https://github.com/Rdatatable/data.table/issues/3669#issuecomment-527196024, wrapping with paren like that returns a result by using the character column to join to itself (rather than the variable in calling scope which should work) but then the result is different (the NA is not desired).
