### ISSUE TITLE
What about data.table powered by GPU along with CPU?

### ISSUE THREAD

**Issue by AdrianAntico** [Rdatatable/data.table#3670]
This is similar to closed issue #2877 without the remote part asked previously. The response mentioned on #2877 is that there wouldn't be a large audience that would take advantage of GPU along with not knowing fully which functions would benefit mostly from this. Is it still the case that you don't believe there would be enough adopters and if yes, what estimate of adoption potential would be required to gain support? I'd imagine the data.table folks would do a better job at making this optimal which is why I'm asking. In terms of which functions / tasks would benefit the most, I'd imagine it's the functions / tasks that currently benefit more from parallel execution than others. I imagine you could identify the break-even for CPU vs. GPU in a large enough number of cases to auto-apply GPU when advantageous.

**Comment by MichaelChirico** [comment]
I don't really understand what it would take to go about fulfilling this issue, so I asked LLM:

https://g.co/gemini/share/686b2d81ff3e

(please chime in if this looks wildly off-base) It looks like a pretty substantial undertaking -- I think the library is not in good shape for this level of extensibility. I am open to outside contributions here (ideally first on some small section of the codebase to get an idea of what it will look like in practice), but not likely to be taken up by current maintainer core in the near future.

Closing as out-of-scope pending a community commitment to implement+maintain this.

**Comment by travis-leith** [comment]
This seems relevant: https://github.com/dmlc/xgboost/issues/11263
