### ISSUE TITLE
feature request : rolling functions

### ISSUE THREAD

**Issue by randomgambit** [Rdatatable/data.table#3674]
Hello the dream team. 

Unless I am mistaken, I was not able to find some clear, concise, fast ways to perform rolling computations on a data.table. Is this something you plan to do?

In the tidyverse, there is a pretty efficient package right now `tsibble`. Maybe this could be useful for data.table?

What do you think?
Thanks!

**Comment by jaapwalhout** [comment]
Development on rolling functions started already some time ago; see #2778 

([found via a simple search for "roll" in the open isuues](https://github.com/Rdatatable/data.table/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+roll))

**Comment by randomgambit** [comment]
thank @jaapwalhout . that would be awesome and enough for me to justify a full move from messyverse to DT. Keep up the good work!
