### ISSUE TITLE
Master list: Feature completion for complex-valued columns

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3690]
As a follow-up to #1444 and #3689, I think it's useful to keep a list of all the features missing for users who want to do work involving complex-valued columns `z`:

 - [x] 1. Sorting by `z` (#1703); by extension `frank(z)`, `rowid(z)`, `dcast`, `setkey`, `uniqueN`
 - [x] 2. Grouping `by` z
 - [x] 3. `z` I/O (`fread` (without `colClasses`) & `fwrite`; overlap with #2247)
 - [x] 4. `CJ(z)`
 - [x] 5. Assign `z` `by` group
 - [x] 6. `GForce` on `z`
 - [ ] 7. ~Joins on `z`~    wait until a user requests it with justification (that part of bmerge.c is complex) 
 - [x] 8. `coalesce(z)`
 - [x] 9. `shift(z)`
 - [x] 10. `unique(z)`
- [x] 11. `:=` #3639

v1.12.4 NEWS contains : 

![image](https://user-images.githubusercontent.com/2779998/61567164-771db380-aa33-11e9-90bf-5c6064544c6f.png)

---
# Examples

```
DT = data.table(a = 1:5, z = 6:10 + (5:1)*1i)
```

### 1. 

```
DT[order(z)]
```

> Error in forderv(ans, cols, sort = TRUE, retGrp = FALSE, order = if (decreasing) -order else order,  : 
  Column 1 of by= (1) is type 'complex', not yet supported. Please use the by= argument to specify columns with types that are supported. See NEWS item in v1.12.2 for more information.

### 2. 

```
DT[ , .N, by = z]
```

> Error in `[.data.table`(DT, , .N, by = z) : 
  column or expression 1 of 'by' or 'keyby' is type complex. Do not quote column names. Usage: DT[,sum(colC),by=list(colA,month(colB))]

### 3. 

```
fwrite(DT)
```

> Error in fwrite(DT) : 
  Column 2's type is 'complex' - not yet implemented in fwrite.

```
fread('a\n1+i')
#         a
#    <char>
# 1:    1+i
```

### 4. 

```
DT[CJ(a, z)]
```

> Error: Column 1 of by= (1) is type 'complex', not yet supported. Please use the by= argument to specify columns with types that are supported. See NEWS item in v1.12.2 for more information.

Coming from `forderv` so first this is a repeat of 1

```
DT[CJ(a, z, sorted = FALSE)]
```

> Error: Type 'complex' not supported by CJ.

### 5. 

```
DT[ , total := base::sum(z), by = .(a %% 2)]
```

> DT[ , total := base::sum(z), by = .(a %% 2)]
Error in `[.data.table`(DT, , `:=`(total_rad, base::sum(z)), by = .(a%%2)) : 
  Internal error: writeNA passed a vector of type 'complex'

### 6.

```
DT[ , sum(z), by = .(a %% 2)]
```

> Error in gsum(z) : 
  Type 'complex' not supported by GForce sum (gsum). Either add the prefix base::sum(.) or turn off GForce optimization using options(datatable.optimize=1)

### 7.

```
DT[DT, on = 'z']
```

> Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  : 
  x.z is type complex which is not supported by data.table join

### 8.

```
DT[ , coalesce(`is.na<-`(z, 1), 0+0i)]
```

> Error in coalesce(`is.na<-`(z, 1), 0 + (0+0i)) : 
  Unsupported type: complex

### 9. 

```
DT[ , shift(z)]
```

> Error in shift(z) : Unsupported type 'complex'

**Comment by MichaelChirico** [comment]
I think we could get away with hacking sorting immediately by morphing `order(z)` into `order(Re(z), Im(z))`; is there any immediacy to doing this, or is worth wait until going through and doing it properly in C on the `CPLXSXP`?

**Comment by MichaelChirico** [comment]
I don't really know where to start on `fread`... but Hugh's `colTypes` generalization already works:

```
class(fread('a\n0+1i', colClasses = c(a='complex'))[[1]])
# [1] "complex"
```

I'd say this is good enough unless there is some specific demand to speed this up. At a glance it would take significant effort to teach `fread` to detect & read `complex` values automatically.

**Comment by mattdowle** [comment]
Fantastic!  Can this be closed now @MichaelChirico ?

**Comment by MichaelChirico** [comment]
I'd say so! maybe just open a follow-up issue for complex joins? or we
could leave something in the NEWS asking if there's any real use case for
it while also suggesting Re=Re & Im=Im as a workaround?

**Comment by mattdowle** [comment]
Great. I edited the revised news item into the main comment at the top of this issue. It asks for a use case. Is that ok?  I'd prefer not to create a new issue for join-on-complex until someone asks for it.

**Comment by MichaelChirico** [comment]
Yes that's perfect. Thanks for all your help getting the rest of this issue over the finish line!
