### ISSUE TITLE
Fix compilation with OpenMP on latest macOS Xcode without headers in /usr/include

### ISSUE THREAD

**Issue by fox34** [Rdatatable/data.table#3698]
When installing according to the docs on macOS 10.14.5, compilation with OpenMP support fails on newer macOS/Xcode versions.

Latest versions of Xcode do not provide the mentioned package macOS_SDK_headers_for_macOS_10.14.pkg any more, as documented in the [Xcode 10 release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes).

As such, /usr/include does not exist and cannot be created. Thus, the compilation always fails with the error _stdio.h file not found_.

Modifying the last line of Makevars from the recommended

`CPPFLAGS=-I/usr/local/opt/gettext/include -I$(LLVM_LOC)/include`

to

`CPPFLAGS=-I/usr/local/opt/gettext/include -I$(LLVM_LOC)/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include`

solved the issue for me.
However, a lot of warnings and notes about nullability were issued during compilation, but I do not know whether this is associated with my fix or not.

**Comment by mattdowle** [comment]
Many thanks. I've added this with a link back to this issue, to https://github.com/Rdatatable/data.table/wiki/Installation.
