### ISSUE TITLE
Remove setrev function

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3704]
As pointed out in a comment on #3688:

Trying to do coverage and came across this function: setrev

I don't see it used anywhere and it's not exported... shall we delete it? Otherwise we should file an issue to have it exported.

`grep` to show it's unused:

```
grep -r "setrev" . | grep -v "Rproj" | grep -v "tests/tests" | grep -v "Binary"
./R/setkey.R:setrev = function(x) .Call(Csetrev, x)
./src/init.c:SEXP setrev();
./src/init.c:{"Csetrev", (DL_FUNC) &setrev, -1},
./src/reorder.c:SEXP setrev(SEXP x) {
```

**Comment by franknarf1** [comment]
Fyi, original commit: https://github.com/Rdatatable/data.table/commit/97750a509d53d6c99f88512474de54bcbbba3d21
