### ISSUE TITLE
nafill / setnafill could work on list columns

### ISSUE THREAD

**Issue by statquant** [Rdatatable/data.table#3707]
Hello, this is a FR given the function is still in dev and clearly states the types of inputs it works on
The function `setnafill` does not work on list columns
```
x = c(1:5, 1:5)                                                        
dt = data.table(v1=x, v2=shift(x)/2, v3=shift(x, -1L)/2)               
dt = dt[,.(v2=list((v2))),v1]                                          
dt[v1==3, v2:=NA]                                                      
setnafill(dt, "nocb")                                                  
Error in setnafill(dt, "nocb") :                                         
  'x' argument must be numeric type, or list/data.table of numeric types 
```
I think it would be a nice addition

**Comment by jangorecki** [comment]
In your example we can see that row 1 has NA in a first element in `v2` column, and row 3 has NA in first (and only) element in `v2` column.
```
> str(dt)
Classes ‘data.table’ and 'data.frame':	5 obs. of  2 variables:
 $ v1: int  1 2 3 4 5
 $ v2:List of 5
  ..$ : num  NA 2.5
  ..$ : num  0.5 0.5
  ..$ : logi NA
  ..$ : num  1.5 1.5
  ..$ : num  2 2
```
It is not obvious how NAs in a list should be handled. There is no such a thing like NA list (`NA_list_` would technically be needed), so I am not really convinced by your feature request.
Could you provide a non-minimal use case where you will find that useful, that might help.

**Comment by statquant** [comment]
Hello, 
I think this feature is about consistency, I see no reason why you would not want to fill NA values in case of list columns **if** you allow list columns to have mixted types.
You say there is no such thing as NA_list_ but in this case wouldn't NULL act as NA_list_ ?
When you do the following that's what you're getting.

x = c(1:5, 1:5)                                                        
dt = data.table(v1=x, v2=shift(x)/2, v3=shift(x, -1L)/2)               
dt = dt[,.(v2=list((v2))),v1]                                           
dtr = data.table(v1 = 1:6)                                   
str(merge(dtr, dt, by = "v1", all.x = T))                    
> Classes ‘data.table’ and 'data.frame':  6 obs. of  2 variables:
> $ v1: int  1 2 3 4 5 6                                        
> $ v2:List of 6                                                
>  ..$ : num  NA 2.5                                            
>  ..$ : num  0.5 0.5                                           
>  ..$ : num  1 1                                               
>  ..$ : num  1.5 1.5                                           
>  ..$ : num  2 2                                               
>  ..$ : NULL                                                   
> - attr(*, ".internal.selfref")=<externalptr>                  
> - attr(*, "sorted")= chr "v1"                                 

It seems like a bad idea to allow mixed type in a list column, how would you unnest mixed types ?
Maybe I should close this FR and open another one asking to forbid mixed types ?

**Comment by statquant** [comment]
Hello, 
I think this feature is about consistency, I see no reason why you would not want to fill NA values in case of list columns **if** you allow list columns to have mixted types.
You say there is no such thing as NA_list_ but in this case wouldn't NULL act as NA_list_ ?
When you do the following that's what you're getting.

x = c(1:5, 1:5)                                                        
dt = data.table(v1=x, v2=shift(x)/2, v3=shift(x, -1L)/2)               
dt = dt[,.(v2=list((v2))),v1]                                           
dtr = data.table(v1 = 1:6)                                   
str(merge(dtr, dt, by = "v1", all.x = T))                    
> Classes ‘data.table’ and 'data.frame':  6 obs. of  2 variables:
> $ v1: int  1 2 3 4 5 6                                        
> $ v2:List of 6                                                
>  ..$ : num  NA 2.5                                            
>  ..$ : num  0.5 0.5                                           
>  ..$ : num  1 1                                               
>  ..$ : num  1.5 1.5                                           
>  ..$ : num  2 2                                               
>  ..$ : NULL                                                   
> - attr(*, ".internal.selfref")=<externalptr>                  
> - attr(*, "sorted")= chr "v1"                                 

It seems like a bad idea to allow mixed type in a list column, how would you unnest mixed types ?
Maybe I should close this FR and open another one asking to forbid mixed types ?

**Comment by franknarf1** [comment]
> It seems like a bad idea to allow mixed type in a list column, how would you unnest mixed types ?
Maybe I should close this FR and open another one asking to forbid mixed types ?

You mean to only have atomic vectors? That would eliminate all of my use cases for list columns (storing estimation results, nested data.tables, etc; see broom and purrr packages for examples).

> You say there is no such thing as NA_list_ but in this case wouldn't NULL act as NA_list_ ?

I think that's right (eg, you also get it from `list()[NA_integer_]`), but that won't help in your original example (where there are no NULL elements), right? So at least to me, the use case is still unclear.

**Comment by statquant** [comment]
> You mean to only have atomic vectors? That would eliminate all of my use cases for list columns (storing estimation results, nested data.tables, etc; see broom and purrr packages for examples).

Yes you're right, there is no need to be restrictive here, if the column is a list of list of the same type then it works and can be unnested if it does not then an error. Actually that's how it works in kdb too.
