### ISSUE TITLE
Somewhat surprising result of rbindlist on nested list input

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3713]
```
l = list(list(list(1, 2)))
rbindlist(l)
#    V1
# 1:  1
# 2:  2
```

I expected this to give

```
data.table(V1 = list(list(1, 2)))
```

Relatedly surprised that both of the following return the same 2-row table:

```
as.data.table(l[[1L]])

data.table(V1 = list(1, 2))
```

---

For context, I am receiving data from [Presto's REST API](https://github.com/prestodb/presto/wiki/HTTP-Protocol). It comes back as JSON and I ingest it with `httr::content()` which converts it to a nested list.

For normal (non-recursive) data types, the return object of an `n`-row, `p`-column query is a length-`n` list with `all(lengths(l)) == p`, e.g.:

```
presto_get(conn, "values(1, 'a'), (2, 'b')")
```

Gives JSON

```
{
  "id": "...",
  "infoUri": "...",
  "columns": [
    {
      "name": "_col0",
      "type": "integer",
      "typeSignature": {
        "rawType": "integer",
        "typeArguments": [],
        "literalArguments": [],
        "arguments": []
      }
    },
    {
      "name": "_col1",
      "type": "varchar(1)",
      "typeSignature": {
        "rawType": "varchar",
        "typeArguments": [],
        "literalArguments": [],
        "arguments": [
          {
            "kind": "LONG_LITERAL",
            "value": 1
          }
        ]
      }
    }
  ],
  "data": [
    [
      1,
      "a"
    ],
    [
      2,
      "b"
    ]
  ],
  "stats": {...},
  "cpuTime": 0,
  "bytesReadFromSource": 0
}
```

After running `httr::content(obj)$data` we have:

```
list(list(1L, "a"), list(2L, "b"))
# l[[1]] <-- first row
# l[[1]][[1]] <- first row, first column
# l[[1]][[2]] <- first row, second column
# l[[2]] <- second row
# l[[2]][[1]] <- second row, first column
# l[[2]][[1]] <- second row, second column
```

That's all well and good. And in fact `rbindlist` works as expected:

```
rbindlist(list(list(1L, "a"), list(2L, "b")))
#    V1 V2
# 1:  1  a
# 2:  2  b
```

However, things get complicated when we try and apply this to a more complicated data type:

```
presto_get(con, 'select array[1, 2]')
```

condensed JSON version:

```
{
 ...
  "columns": [
    {
      "name": "_col0",
      "type": "array(integer)",
      "typeSignature": {
        "rawType": "array",
        "typeArguments": [
          {
            "rawType": "integer",
            "typeArguments": [],
            "literalArguments": [],
            "arguments": []
          }
        ],
        "literalArguments": [],
        "arguments": [
          {
            "kind": "TYPE_SIGNATURE",
            "value": {
              "rawType": "integer",
              "typeArguments": [],
              "literalArguments": [],
              "arguments": []
            }
          }
        ]
      }
    }
  ],
  "data": [
    [
      [
        1,
        2
      ]
    ]
  ],
 ...
}
```

And `httr::get()$data`:

```
list(list(list(1L, 2L))) # as above
```

But the data structure is similar to the normal case:

```
l[[1]] # <- first row
# [[1]]
# [[1]][[1]]
# [1] 1
# 
# [[1]][[2]]
# [1] 2
l[[1]][[1]] # <- first row, first column
# [[1]]
# [1] 1
# 
# [[2]]
# [1] 2
```

`length(l) == 1` and `all(lengths(l) == 1)`, so IMO this looks like a 1x1 `data.table` whose sole element is `list(1, 2)`. 

The nestedness makes things a bit confusing, so maybe I'm missing something.

**Comment by franknarf1** [comment]
> The nestedness makes things a bit confusing, so maybe I'm missing something.

>         l[[1]] # <- first row

That is not the first row, but rather the first object to be rbinded, right? It might be a row or it might be a table. If you specify a column as `list(1,2)` it is interpreted as a length-2 list column with elements 1, 2, as you saw with

>         data.table(V1 = list(1, 2))

or with `setDT(l[[1]])[]`. If you add one more `list`, then it will be a length-1 list column with element list(1,2):

```
DT = data.table( v = list(list(1,2)) ) # or change outer data.table() to list()
L = list(DT)
rbindlist(L)
```

**Comment by MichaelChirico** [comment]
Indeed it's pretty straightforward in my function to add `if (is.list(l)) list(l) else l` which works fine. Closing this as that works for me, feel free to re-open.
