### ISSUE TITLE
cerrection needed in FAQ section 2.17 item 3

### ISSUE THREAD

**Issue by JackieMium** [Rdatatable/data.table#3717]
In FAQ section 2.17 item 3 (line 375 in [datatable-faq.Rmd](https://github.com/Rdatatable/data.table/blob/5ca3366cdbae22e2534dc816e200265a6ec0bcfc/vignettes/datatable-faq.Rmd#L375) ) it says:

 > `DT[[3]] == DF[3] == DF[[3]]`

But should this be `DT[[3]] == DF[, 3] == DF[[3]]`? Both `DT[[3]]` and `DF[[3]]` returns 3rd column as a vector, while `DF[3]` returns 3rd column as a one-clolumn `df`, what we need here is `DF[, 3]` for a vecor.

**Comment by MichaelChirico** [comment]
yes that's correct... would you mind filing a pull request? might be able to get away with doing this one from the web UI FWIW
