### ISSUE TITLE
generation of descriptive statistics

### ISSUE THREAD

**Issue by BryanHutchinsonBH** [Rdatatable/data.table#3719]
This my first post in Git Hub so please bear with me, it looks like a long learning curve. I first naively contacted Matt Dowle and he very patiently suggested that I post here to get others' opinions.

My feature request is to include a function that computes descriptive statistics by groups for a measure variable. In making my point I have used the desc_staby function found in the ggpubr package which allows me to generate the sort of output I envisage. It is basically this which I would like to see optimised/extended within data.table.  I have not been presumptuous to put install ggpubr in my listing.

I hope to show in a few of examples that, coupled with data.table filtering, a good deal of related and flexible output and analysis can be produced in tabular and graphical format with minimum effort.

As an end user I would find it much easier to focus on particular aspects and thereby help have a better workflow, at least initially.

The data I have used is "flights14.csv", hardly minimised, but it at least has the benefit of being well known to data.table.

```{r}
library(ggplot2)
library(ggpubr)
library(data.table)

input <- if (file.exists("flights14.csv")) {
  "flights14.csv"
} else {
  "https://raw.githubusercontent.com/Rdatatable/data.table/master/vignettes/flights14.csv"
}

flights <- fread(input)
options(digits=3)
```

Example 1  allows me to get the stats for any month by changing the filter. It is also of course easy to change origin to carrier if I were to focus on airline performance rather than airport and/or change the measurement valiable.

```{r}
# Example 1

desc_statby(
  flights[month==8L & origin%in%c("EWR","JFK","LGA")],
  measure.var="arr_delay",ci=0.95,
  grps=c("month","origin"))

```

For Example 2 I have extended the above to include a day== filter and "day" in grps. I can now get stats for any day in any month.

```{r}
# Example 2

desc_statby(
  flights[month==3L & day==1L & origin%in%c("EWR","JFK","LGA")],
  measure.var="arr_delay",ci=0.95,
  grps=c("month","day","origin"))[,c(1:8,11)]
```

For example 3 I have simply pasted Example 2 into a ggplot, deleted the day== filter and used "day" as the x= aesthetic. Because a descriptives table is generated I can also change the y= aesthetic to mean, median, min, max etc. where appropriate.

```{r}
# Example 3

ggplot(desc_statby(
  flights[month==3L & origin%in%c("LGA","EWR","JFK")],
  measure.var="arr_delay",ci=0.95,
  grps=c("month","day","origin")),
  aes(x=day, y=length, colour=origin))+
  geom_line(size=1)+
  scale_x_continuous(breaks=seq(1,31,2))+
  theme_bw()
```

For Example 4 I have pasted Example 2 into a ggplot, added "hour" to grps (line 4) and used hour as the x= aesthetic. I can now generate graphs for any day in any month. I can also still change the y= aesthetic to any of the other descriptives, such as "mean" etc., where appropriate.

```{r}
# Example 4

ggplot(desc_statby(
  flights[month==3L & day==2L & origin%in%c("LGA","EWR","JFK")],
  measure.var="arr_delay",ci=0.95,
  grps=c("month","day","hour","origin")),
  aes(x=hour, y=median, colour=origin))+
  geom_line(size=1)+
  scale_x_continuous(breaks=seq(0,24,2))+
  theme_bw()
```

**Comment by moodymudskipper** [comment]
@BryanHutchinsonBH here would be a way to do it: 

``` r
summary_stats <- function(var, ci) {
  # connvert integer to double
  var <- as.numeric(var)
  list(
    length = length(var),
    min = min(var),
    max = max(var),
    median = median(var)
    #etc, more calls using ci or other parameters if relevant
  )
}

flights[month==8L & origin %in% c("EWR","JFK","LGA"), 
        summary_stats(arr_delay),
        by = c("month","origin")]
#>    month origin length min max median
#> 1:     8    JFK   8986 -73 727     -5
#> 2:     8    LGA   9031 -57 833     -6
#> 3:     8    EWR   9433 -70 964     -7
```

**Comment by Bryan-Hutchinson** [comment]
Thanks for this Antoine.  As you probably guessed I am rather new to this. I will be a bit more circumspect in future - best f look for the future.

Bryan

**Comment by moodymudskipper** [comment]
This is not so obvious Bryan, have fun learning on your journey!

**Comment by jangorecki** [comment]
@BryanHutchinsonBH is there anything pending about this issue or we can close it?

**Comment by Bryan-Hutchinson** [comment]
Jan please close this issue.

Regards
Bryan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
