### ISSUE TITLE
data.table(double(0), 1) returns a zero-row table

### ISSUE THREAD

**Issue by shrektan** [Rdatatable/data.table#3727]
One of pattern of using data.table is to return a data.table at the end of a function, like:

```r
data.table(
  A = xxx,
  B = yyy,
  Z = zzz,
)
```

I often need to include some constant columns, like the datetime, the id, etc. Most of time it returns what I want except when all other inputs are zero length vector. For example:

``` r
data.table::data.table(
  a = double(),
  b = 1
)
#> Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names
#> = check.names): Item 1 has 0 rows but longest item has 1; filled with NA
#>     a b
#> 1: NA 1
```

So I have to explicitly use `rep()` everytime in order to ensure it returns the desired result. 

``` r
a <- double()
n <- length(a)
data.table::data.table(
  a = a,
  b = rep(a, n)
)
#> Empty data.table (0 rows and 2 cols): a,b
```

It's verbose, inconvenient and often being forgotten in the first place because in my mind, the length 1 column should always be recycled... so it's actually a little bit inconsistent, IMO:

```r
### gets a data.table with row 2
data.table::data.table(
  a = double(2),
  b = 1
)
### gets a data.table with row 3
data.table::data.table(
  a = double(3),
  b = 1
)
### Should get a zero-row data.table but gets a 1-row table with a warning
data.table::data.table(
  a = double(0),
  b = 1
)
```

while tibble gets what I expect:

``` r
tibble::tibble(
  a = double(0),
  b = 1
)
#> # A tibble: 0 x 2
#> # ... with 2 variables: a <dbl>, b <dbl>
```

**Comment by MichaelChirico** [comment]
Related: #2662 and #759

**Comment by shrektan** [comment]
This is very annoying IMO. Another case is in querying with `J()`. In the below example, I expect a zero vector return...

``` r
dt <- data.table::data.table(CODE = c('a', 'b'), DATE = 1:2, VALUE = c(1.3, 1.5),
                             key = c('CODE', 'DATE'))
dt[J('a', 1), VALUE]
#> [1] 1.3
dt[J(character(), 1), VALUE]
#> Warning in as.data.table.list(i): Item 1 has 0 rows but longest item has 1;
#> filled with NA
#> [1] NA
```

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Since we've already provided a warning here, why not just return a zero row value? I may be wrong but I can't imagine a use case that needs to recycle the zero-length vector. Again, only the scalar value is supposed to be recycled.

If there's no clear objection, I'm going to file a PR.

**Comment by jangorecki** [comment]
@shrektan I like your initial report here, it make sense. Looking forward for PR. As for your recent comment, isn't it a different piece of code to be altered to make this join working? If so then two separate PR could be better.

**Comment by shrektan** [comment]
I think it's the cause is the same. 

If `J(character(), 1)` returns a zero-row table, `dt[J(character(), 1), VALUE]` should return a zero-length result.

 I haven't looked into `J`'s implementation yet. If it's quite different, I will separate the PR. Thanks for reminding this.

**Comment by MichaelChirico** [comment]
Note that `J` is commented out on its help page:

```
# DT[J(...)]                          # J() only for use inside DT[...]
```

actually, `J` is another example of NSE-only function in `data.table`. It's simply converted to `list` internally:

```
grep "J" R/data.table.R -n
103:  # J alias for list as well in i, just if the first symbol
```

**Comment by shrektan** [comment]
Just to update another example that I was bite in the real code. 


``` r
library(data.table)
tbl <- data.table(A = 1:3, B = letters[1:3])
tbl1 <- tbl[A > 3L, .(ITEM = 'A>3', A, B)]
tbl1
#> Empty data.table (0 rows and 3 cols): ITEM,A,B
tbl2 <- tbl[A > 3][, .(ITEM = 'A>3', A, B)]
#> Warning in as.data.table.list(jval, .named = NULL): Item 2 has 0 rows but
#> longest item has 1; filled with NA
#> Warning in as.data.table.list(jval, .named = NULL): Item 3 has 0 rows but
#> longest item has 1; filled with NA
tbl2
#>    ITEM  A    B
#> 1:  A>3 NA <NA>
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ecoRoland2** [comment]
@johnroxton 

You could replace `as.numeric(NA)` with `NA_real_`.

However, this reads a bit like an [xy problem](https://xyproblem.info/). You should try to avoid populating data.table columns with data later on.

**Comment by johnroxton** [comment]
Thanks for the answer and mentioning it might not be a good idea. So what I actually do is that I have a vector of strings and do several checks on them, e.g. whether there are non-ASCII chars in them, or whether they contain numbers, or whether they follow a specific pattern. So I first create a results data.table with the first column being the actual strings and subsequent columns coding the results, which can be numeric, logical or character. I thought it would be best to have the columns initialised first, but I could of course also append them to the data.table one after the other when the values have been calculated. Would this be better?

**Comment by MichaelChirico** [comment]
If pre-allocating columns I would change `numeric()` (implicitly: `numeric(0)`) to `numeric(N)`.

If you actually want to populate "missing", `rep(NA_real_, N)` looks fine to me, but also just `data.table(ID = 1:3, value = NA_real_)` will do the `rep()` for you.

**Comment by TysonStanley** [comment]
Given `data.table` already over allocates columns, I'm curious if pre-allocating would be advantageous at all

**Comment by ecoRoland2** [comment]
Probably not unless the user does some row-wise operation. They might do something in a loop that lets them hit the truelength several times and in that case they should use `setalloccol` or reconsider the whole approach. But I think you are right, pre-allocation isn't needed in the specific case discussed.

@johnroxton As long as you append with `:=` or `set` you shouldn't need to pre-allocate.

**Comment by johnroxton** [comment]
Thanks to all for your comments and advice!

**Comment by MichaelChirico** [comment]
> Given data.table already over allocates columns, I'm curious if pre-allocating would be advantageous at all

Not sure if this is what you meant, but data.table over-allocates column _pointers_, not full columns. I'd have to think more carefully about if that still means there's a performance benefit to allocating columns up front or not.

Regardless, pre-allocating can also help make the code more readable: Here's the intended schema of the output table, now the following steps will "fill it up", vs. trying to understand from reading what the end schema of the table is as it accumulates columns in messy following code.
