### ISSUE TITLE
[R-Forge #2591] format.data.table should know about embedded formulas

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#374]
Submitted by: Matt Dowle; Assigned to: Arun ; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2591&group_id=240&atid=978)

Suggested by Mike Crowe :

DT = data.table(F = c(X~Y, X~Y+Z))
DT
DT[, Fstr := sapply(F, format)]
DT

It's getting caught here in format.data.table because formulae are not atomic :

if (is.atomic(x))
     paste(c(head(x, 6), if (length(x) > 6) ""), collapse = ",")
else
     paste("<", class(x)[1L], ">", sep = "")

**Comment by MichaelChirico** [comment]
@arunsrinivasan Working on #1523 and this came up... I can't seem to reproduce a `data.table` that doesn't force a `formula` to `list` -- the example provided here now does so, for example:

```
DT = data.table(F = c(X~Y, X~Y+Z))
sapply(DT, class)
#      F 
# "list" 
```

I'm wondering if this is no longer possible (wondering if I need to account for the possibility that a column could be stored as `formula` in matching `class` to an abbreviation for pretty printing)

**Comment by arunsrinivasan** [comment]
`c(X ~ Y, X ~ Y + Z)` would already return a list. `is.call(X ~ Y)` returns `TRUE`. It's not possible to have then without it being a list column. 

If a column is of type `list`, does all the element of the list having the same class (perhaps C code here so as to not create a vector of length = `nrow(x)`)? If so, if they have a class attribute, set column type to that class, e.g., "formula", "data.table" etc.. if not, then just "list" as the class type should be sufficient...

How about doing so?
