### ISSUE TITLE
make 'CsubsetDT' callable from C in other packages

### ISSUE THREAD

**Issue by lsilvest** [Rdatatable/data.table#3751]
I'm writing a package ([lsilvest/dtts.utils](https://github.com/lsilvest/dtts.utils)) that has functions that subset `data.table`.

These functions provide time series functionality to a `data.table` that has as first column a `nanotime` type ([eddelbuettel/nanotime](https://github.com/eddelbuettel/nanotime)) and will allow pretty cool subsettings on intervals, alignment to a grid, etc.

For this I need efficient subsetting at C level and I wouldn't need to duplicate C code if `CsubsetDT` were exported. It's a one liner to export it (`R_RegisterCCallable("data.table", "CsubsetDT", (DL_FUNC) &subsetDT);`) and I have committed it in a fork that could be pulled (7c84115).

Any chance this would be possible?

**Comment by jangorecki** [comment]
Recent idea in #3736 seems very related, but it is still R interface.
If you are planning to call it from C mainly then it make sense to go even deeper, as you propose.

**Comment by lsilvest** [comment]
Indeed my use cases for calling `CsubsetDT` are within loops at C level that construct a new `data.table`, but I could construct an index at C level and then the solution in #3736 would be satisfactory, even if not always optimal and a bit less flexible.

**Comment by jangorecki** [comment]
@lsilvest would you mind filling PR to address your request?
