### ISSUE TITLE
Issue in X[Y,,.EACHI] when Y contains integer64

### ISSUE THREAD

**Issue by statquant** [Rdatatable/data.table#3779]
I was performing a left join with a right table with integer64 and it failed.
I might be misunderstanding .EACHI but I would expct the following to work, and it does when Y$y is not integer64

```
X = data.table(x=1:3)                          
Y = data.table(x=1:2, y=as.integer64(c(10,20)))
X[Y, `:=`(y = i.y), on = "x", by = .EACHI]     
Error in `[.data.table`(X, Y, `:=`(y = i.y), on = "x", by = .EACHI) :                          
  Internal error: memrecycle source is integer64 but target is real and not integer64; target should be type integer64
```

**Comment by statquant** [comment]
Fixed in data.table_1.12.9

**Comment by jangorecki** [comment]
@statquant Glad to hear it fixed but we should not be closing issue without having unit test for that, to ensure that there will be no regression in future. Any idea if we added unit tests to cover this issue? If so it is still good to mention the issue in NEWS file
