### ISSUE TITLE
setnames could break out early if identical(old,new)

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3783]
Am writing a function that works like

```
if (length(idx <- grep('^_', names(x)))) setnames(x, idx, gsub('^_', '', names(x)[idx])
```

It would be cleaner to just write

```
setnames(x, gsub('^_', '', names(x)))
```

And (in the `!length` case) let `setnames` realize `old` and `new` are the same & return early for efficiency.

**Comment by MichaelChirico** [comment]
Actually it already does this in the `missing(new)` case

https://github.com/Rdatatable/data.table/blob/a8e926a48a87cd669ffe2ee310a73173be652f2b/R/data.table.R#L2447-L2451

Will file a fix for `!missing(new)`

**Comment by HughParsonage** [comment]
> It would be cleaner to just write
> 
> ```
> setnames(x, gsub('^_', '', names(x)))
> ```

I believe this would work already, no? If the pattern in `gsub` is not matched the replacement is not attempted.

**Comment by mattdowle** [comment]
This case is a nice one. Have been looking at it and @HughParsonage seems right to me: that case (where the pattern is not matched to any column name) does not overwrite the names redundantly. Even where only a few column names are matched, it only updates those. The `setnames(DT, new)` form seems fine and no improvement possible.  It's just `setnames(DT, old, new)` that the PR improves.
