### ISSUE TITLE
Cannot use froll function in data.table

### ISSUE THREAD

**Issue by vukhanh1202** [Rdatatable/data.table#3787]
Hi everyone, I'm trying to implement other rolling function in data.table, however, it seems that right now data.table supports only the frollmean. I would like to create other rolling function in data.table. How can I do? Thank you in advance.

When I type getAnywhere(froll) -> R returns:
function (fun, x, n, fill = NA, algo = c("fast", "exact"), align = c("right", 
    "left", "center"), na.rm = FALSE, hasNA = NA, adaptive = FALSE, 
    verbose = getOption("datatable.verbose")) 
{
    stopifnot(!missing(fun), is.character(fun), length(fun) == 
        1L, !is.na(fun))
    algo = match.arg(algo)
    align = match.arg(align)
    ans = .Call(CfrollfunR, fun, x, n, fill, algo, align, na.rm, 
        hasNA, adaptive, verbose)
    ans
}

I can see the Fun (which is similar as the fun in rollapplyr of xts package ), but I cannot use this one to create other function.

**Comment by jangorecki** [comment]
Just read manual (type `?froll` R) and #2778 which defines scope for rolling functions. You are welcome to contribute rest of (not yet implemented) rolling functions but it requires knowledge of C coding. Before proceeding please consult in #2778.
