### ISSUE TITLE
coalesce() can't handle NaN

### ISSUE THREAD

**Issue by shrektan** [Rdatatable/data.table#3790]
Currently, NaN is treated as if a non-NA value but I expect it's the same as NA_real_, because `is.na(NaN)` returns `TRUE`.

``` r
library(data.table)
coalesce(NaN, 1)
#> [1] NaN
is.na(NaN)
#> [1] TRUE
```

<sup>Created on 2019-08-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jangorecki** [comment]
should be a matter of changing `ISNA` to `ISNAN` in https://github.com/Rdatatable/data.table/blob/d95910733167684b05ce253dcb4da801bde54f56/src/coalesce.c#L99-L118

**Comment by MichaelChirico** [comment]
I think that because `is.na(NaN)` default should be to consider it as NA. Both `dplyr` and `hutils` do so.

In the future, if requested, we could add an option, but I think we should do this for now.

**Comment by MichaelChirico** [comment]
(PS we're already doing this for complex input: `coalesce(NaN + NaN*1i, 1 + 1i)` -> `1+1i`
