### ISSUE TITLE
cleanup root dir

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3793]
once pkgdown PR will be merged we can do small cleaning of root dir
- [ ] `png`, `svg` could go into `.graphics`/`.logo` dir
- [ ] `Dockerfile.in`, `ci.R,` `deploy.sh`, `publish.R` could go into `.ci` dir
- [ ] `cc.R`, `revdep.R`, `CRAN_Release.cmd` could go into `.dev` dir
- [ ] add `.Rprofile` file sourcing `.dev/cc.R` so anyone who starts R session in git clone project root dir will be well equipped
- [ ] rename `appveyor.yml` to `.appveyor.yml` for consistency to other CI services
- [ ] add README.md to `.ci` and `.dev`

**Comment by MichaelChirico** [comment]
Yes! Let's also add a `README` to `.ci` and `.dev` directory with a quick primer on the files. They're quite generally useful (I got a lot of mileage out of `CRAN_Release.cmd` in trying to debug my SAN/valgrind issues in `geohashTools` recently), would be nice to document them a bit.

**Comment by jangorecki** [comment]
AFAIU logo.png needs to stay in root dir for now due to https://github.com/r-lib/pkgdown/issues/1148
