### ISSUE TITLE
Add an alias for functional version of `:=`

### ISSUE THREAD

**Issue by eliocamp** [Rdatatable/data.table#3795]
Right now when adding multiple columns to a data.table one of the options is to do:

```r
dt[, `:=`(col1 = stuff, col2 = moar_stuff)]
```

I think that this syntax can be a bit confusing (too many equals) but mainly is hard to write. To get the grave accent, on my keyboard I have to press AltGr + } and then space. It's kind of annoying. 

So my modest proposal is to just have an alias for `:=()` that is just a run-off-the-mill common name with no special characters. Maybe (ab)using the `set()` function? It would end up something like this:

```r
dt[, set(col1 = stuff, col2 = moar_stuff)]
```

I think it not only reads better, but it's also 87% easier to type.

**Comment by MichaelChirico** [comment]
Relatedly it would also help solve this issue:

https://github.com/Rdatatable/data.table/issues/1543#issuecomment-483134996

(I suggested the name `list_set` there but the idea is the same)

I think the issue is there's a reason why `:=` is not defined as a proper function (limiting the API so prevent its being used outside `[`)... not sure how challenging it is to build out the NSE hacks to work for a new function in addition to `:=`.

> on my keyboard I have to press AltGr + } and then space. It's kind of annoying.

Sounds very much so! Are you working in RStudio? There must be a way to define some add-in keyboard shortcuts...

**Comment by jangorecki** [comment]
I would prefer to avoid name collision, even if not evaluated. Maybe `setj`?

**Comment by eliocamp** [comment]
> As for the named list in :=, isn't it better to just handle ":="(list(col1=col1, col2=col2))?

Yes, I guess ultimately it's the same change. 

`setj()` could work, but the "j" there is kind of esoteric and I don't know how many users (specially beginners) appreciate that they are using an argument named "j".

**Comment by jangorecki** [comment]
> `setj()` could work, but the "j" there is kind of esoteric and I don't know how many users (specially beginners) appreciate that they are using an argument named "j". 

Once they will figure that out, looking at `?"["` for example, they will appreciate. These really basics things that anyone who wants to "know R" should learn at some point.

----

My suggestion to address this issue is an alias `setj` which will be substituted for `:=` in `[.data.table`.

**Comment by eliocamp** [comment]
I don't know if many users will ever look at `?"["` (I now I never have 😜️). Still, I generally like more descriptive arguments. "j" is basically meaningless --merely a convention from algebra notation-- whereas "column" actually describes what's going on. 
How abut `setcol()`?

**Comment by tdeenes** [comment]
I think most (if not all) set* functions take a data.table as input (e.g., setkey, setorder, setcolorder). The most natural syntax to me would be:
```r
DT[, .(col1 := new_value, col2 := something)]
```
This way no new symbol is introduced; we simply allow for mixing the already well-known `.()` (~the result consists of multiple columns) and `:=` (~do the assignment in place) symbols.

**Comment by eliocamp** [comment]
In my opinion, that would be more confusing because then the behaviour of `.()` would not be consistent. Sometimes it would create a new data.table and others it would modify by reference. It could further come into problems if someone where to write `DT[, .(col1 := new_value, col2 = something)]` and the functional version would still be needed for the `":="(list(col1=col1, col2=col2))` case. 

I do think its a good point that `set*` functions take a data.table as argument, though. :thinking:

**Comment by jangorecki** [comment]
`setattr` works for other types

**Comment by eliocamp** [comment]
Yeah, but I think the point is that `set` functions modify (by reference) the object in the `x` argument. In this case `set` would be modifying the data.table in which it is called. It's a small departure from the other functions' behaviour, maybe.

**Comment by dracodoc** [comment]
Maybe simply use a different word other than `set`? How about `let`?

**Comment by eliocamp** [comment]
That's fine by me. Is not bad.

**Comment by moodymudskipper** [comment]
As far as I can tell it's only about changing `== ":="` to `%in% c(":=", "let")` in the code.

I wrote [this evil hack](https://www.reddit.com/r/rstats/comments/dprgkw/create_an_alias_for_in_datatable/) for a reddit user that wanted this feature : 

```
set_colon_equal_alias <- function(alias){
  requireNamespace("data.table")
  temp <- data.table:::`[.data.table`
  body(temp)[-1] <- parse(text = gsub(
    '== ":="',
    paste("%in%", deparse(c(":=", alias))) ,
    body(temp)[-1],
    fixed = TRUE))
  assignInNamespace("[.data.table", temp, "data.table")
  invisible()
}

library(data.table)
dt <- data.table(x = c(1,2,3), y = c(4,5,6))
set_colon_equal_alias("let")

dt[, let(double_x = x * 2, x_plus_y = x + y)][]
#>    x y double_x x_plus_y
#> 1: 1 4        2        5
#> 2: 2 5        4        7
#> 3: 3 6        6        9
```

**Comment by s-fleck** [comment]
Might I suggest `"mut()"` for mutating a mutable object?

**Comment by mattdowle** [comment]
> To get the grave accent, on my keyboard I have to press AltGr + } and then space. It's kind of annoying.

Btw, just for completeness, both single quote and double quote also work; i.e. `DT[, ':='(...)]` and `DT[, ":="(...)]`. It doesn't have to be backtick; i.e. grave. Not saying an alias isn't still better. Will merge PR. Just saying for completeness it doesn't have to be backtick.
