### ISSUE TITLE
working with out-of-memory data 

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#3821]
I was wondering if the data.table developers have considered adding out-of-memory data functionality. If there is such a plan, is there any timeline for that?

**Comment by MichaelChirico** [comment]
See #3526 #1336 #1828 #1721 #3104 #583 #561 

One distinction is out-of-memory-but-local and distributed-out-of-memory. Distributed out-of-memory is probably never going to happen, except if we eventually provide a front end to Spark.

Very much a help-wanted issue :)
