### ISSUE TITLE
optimise coalesce to fcoalesce

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3830]
follow up of #3827

**Comment by MichaelChirico** [comment]
As I understand, we already saw the `revdep` impact of the provisional approach from #3800, so no need to bother with this until next release & we can start phasing it in then, right?

**Comment by jangorecki** [comment]
We could eventually drop this idea because of the differences in `coalesce` implementation described by Matt in https://github.com/Rdatatable/data.table/issues/3754#issuecomment-528571184
Unless `BBmisc::coalesce` would change its default behaviour, it seems to be more tricky. We will need to detect if BBmisc is on a search path. FYI @berndbischl

**Comment by jangorecki** [comment]
As commented, this doesn't seems to be good idea because of different implementations of `coalesce`. Best to just let people know they can use `fcoalesce` to have most standard and fastest implementation. Closing.
