### ISSUE TITLE
All warnings should be avoidable

### ISSUE THREAD

**Issue by HughParsonage** [Rdatatable/data.table#3848]
Generalization of (fixed) #3796.

Warnings are useful when they highlight that something has happened that the user might not expect. However, they lose their utility if the highlight something that the user *does* expect (or has accepted). In addition, we cannot anticipate every input -- some warnings with some inputs may be spurious. Warnings which cannot be turned off might lead to them being ignored, or lead to workarounds that introduce bugs.

For this reason, while warnings should occur by default, they should either explain how to avoid them, or the function that produces them should provide an option to turn off each particular warning.

**Comment by jangorecki** [comment]
I agree with your comment. The only problem that issue was referring to is fixed already, so theoretically we should close that. If anyone will find such a warnings please link here and re-open.
