### ISSUE TITLE
datatable filter

### ISSUE THREAD

**Issue by olivierroy1** [Rdatatable/data.table#3856]
for quantitative variables could it be possible to have filter in logarithmic scale or  something more robust to really big values
In my dataset i have a lot of 0 many numbers in the middle and one really big 

0,0,0,0, 10000, 20000, (many values in between) 50000, 800000000

It's really hard to drag let's say to gather values between 4000 and 45000 (apart if you enter the numbers by hand, but sometimes you don't really know your dataset so it's hard to set these values by hand

**Comment by MichaelChirico** [comment]
Sorry, I don't follow. Could you please build a more fleshed out example & use case?
