### ISSUE TITLE
first on empty DT should return empty DT

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#3858]
```r
dt = data.table(a=1,b=2)[0,]
first(dt)
#       a     b
#1:    NA    NA
head(dt, 1)
#Empty data.table (0 rows and 2 cols): a,b
```

**Comment by st-pasha** [comment]
I was recently struggling with a similar question in `datatable`, regarding applying reduce operators to a 0-row Frame. Conceptually there could be 2 approaches for grouping such a frame:
- it creates 1 group of 0 rows;
- it creates 0 groups of any rows.

Curious to hear your reasoning as to which of them is better.

**Comment by jangorecki** [comment]
Definitely 0 groups of any rows. 1 group of 0 rows make sense for a grand total summary where we apply reduce function without any actual grouping. Related subject are [grouping sets: rollup, cube](https://rdatatable.gitlab.io/data.table/library/data.table/html/groupingsets.html)
```r
d = data.table(grp=character(), val=numeric())
d = data.table(grp="a", val=1)
groupingsets(d, by="grp", sets=list(character()), j=.(sum=sum(val), mean=mean(val), len=length(val)))
#      grp   sum  mean   len
#   <char> <num> <num> <int>
#1:   <NA>     0   NaN     0
d = data.table(grp="a", val=1)
groupingsets(d, by="grp", sets=list(character()), j=.(sum=sum(val), mean=mean(val), len=length(val)))
#      grp   sum  mean   len
#   <char> <num> <num> <int>
#1:   <NA>     1     1     1
```

**Comment by jangorecki** [comment]
@st-pasha generally the same as we would run it outside of data.table
```
> A=numeric()
> list(head(A,1L), sum(A), min(A))
[[1]]
numeric(0)

[[2]]
[1] 0

[[3]]
[1] Inf

Warning message:
In min(A) : no non-missing arguments to min; returning Inf
```

**Comment by jangorecki** [comment]
there is no `first`/`last` in base R. So first/last needs to wrap either to
- `head(x, n=1)` and `tail(x, n=1)` or
- `x[1]` and `x[max(length(x), 1)]` (yes, extra complexity needed here)

latter will always expand to a 1 element vector.
xts which implements first/last long time seems to be affected by same inconsistency: https://github.com/joshuaulrich/xts/issues/309
