### ISSUE TITLE
No error when using missing by in a function

### ISSUE THREAD

**Issue by ColinFay** [Rdatatable/data.table#3861]
This follows a question I asked [on Twitter](https://twitter.com/_ColinFay/status/1172112266378063873) regarding the behavior of 

``` r
library(data.table)
iris_dt <- as.data.table(iris)
plop <- function(dt, kk){
  dt[, .(n = .N), kk ]
}

plop(iris_dt)
     n
1: 150

plop(iris_dt, "Species")
      Species  n
1:     setosa 50
2: versicolor 50
3:  virginica 50
```

As far as I have understood, `kk` enters unevaluated into `[.data.table`, and as it's tested for missingness there, everything works fine even if `kk` is missing from the function.

In other words, I would have expected it to behave as what it would have done in the .GlobalEnv

``` r
> iris_dt[, .(n = .N), kk ]
Error in eval(bysub, parent.frame(), parent.frame()) : 
  object 'kk' not found
```

I think the expected behaviour here would be to throw an error, as `kk` is missing from the function call. Jan [here](https://twitter.com/Jan30294383/status/1172121779655127040) suggested me to open an issue about this behaviour so here I am. 

Colin  

PS: I know I can prevent this from testing missingness and / or try to `force(kk)`. I just wanted to share what seemed like an unexpected behaviour to me.

**Comment by jangorecki** [comment]
Looking at (1) wrote by @MichaelChirico I don't think we need to deal with that in some special way.

**Comment by jangorecki** [comment]
Long time no new ideas for tackle this R-specific problem. Closing. Will re-open if there will be something to address in data.table about that.
