### ISSUE TITLE
Fail on win-builder for R 3.5.3

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3865]
Passes OK on R 3.6.1

But fails with this on R 3.5.3 :
```
Running test id 1658.07      Test 1658.07 produced 1 warnings but expected 0
  Expected: 
  Observed: partial argument match of 'along' to 'along.with'
  
  Running test id 1658.08      
  Running test id 1658.09      Test 1658.09 produced 1 warnings but expected 0
  Expected: 
  Observed: partial argument match of 'along' to 'along.with'
  ```

**Comment by mattdowle** [comment]
@MichaelChirico I don't think you should have flagged @mmaechler on this. We need to save his time for when we really need it.
> there were also 50+ warnings from actually running in console

Can you add more color on this please? I don't see those and they aren't shown on win-builder output. Just 2 tests failed. If there are many more warnings than 2, why didn't more than 2 tests fail? `test()` fails if a warning occurs which is not expected. Did the 50+ warnings occur outside all `test()` calls (in preparing data for each tests) and only within `test()` in 2 cases?

**Comment by MichaelChirico** [comment]
yes that's my take on what happened. ran tests & got those errors and was prompted to run warnings() to see more. my experience w test.data.table() is that happens for issues on code outside test() calls.

have run the tests again on the PR branch and confirmed no more issues anyway
