### ISSUE TITLE
git history disappeared after move

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3889]
`.dev\` CRAN_Release.cmd, cc.R and revdep.R have lost their history after the move. @jangorecki did you use `git mv`?  It now just looks as though you created them from scratch with 1 contributor.

**Comment by jangorecki** [comment]
AFAIR it was `git mv`, we could try to rewind that. It is the same for files in `.github` directory. I generally use `git mv`, some time I might forget that but definitely not in all those cases.
I found related: https://stackoverflow.com/questions/31304441/i-moved-all-my-project-files-with-git-mv-but-i-have-lost-all-my-history-why

**Comment by jangorecki** [comment]
yes, history is there, maybe it is just a github issue
```
> git log --follow .dev/cc.R | head -17
commit b0577108354d1b2c5e98d2ee44131fff9fb38661
Author: Jan Gorecki <jangorecki@users.noreply.github.com>
Date:   Tue Sep 17 02:41:54 2019 +0200

    cleanup rootdir (#3884)

commit 5cb4f349fce0c1331c70e518ca6006bf5232f219
Author: Matt Dowle <mattjdowle@gmail.com>
Date:   Thu Sep 12 15:47:16 2019 -0700

    Fixed LTO warnings (#3864)

commit 4ee9264597061b6b18c9348520a4a84e14d83437
Author: Michael Chirico <michael.chirico@grabtaxi.com>
Date:   Wed Aug 28 13:19:26 2019 -0700

    unlock shallow copy of .SD when needed in joins in j (#3774)
```

**Comment by jangorecki** [comment]
OK, this is described here https://stackoverflow.com/questions/5646174/how-to-make-github-follow-directory-history-after-renames

**Comment by jangorecki** [comment]
we can use gitlab to see history, it works as expected: https://gitlab.com/Rdatatable/data.table/commits/master/.dev/cc.R
https://gitlab.com/Rdatatable/data.table/commits/master/.dev/CRAN_Release.cmd
feel free to open if you think there is anything we can do about that
