### ISSUE TITLE
NA as a factor level malformed by rbindlist

### ISSUE THREAD

**Issue by sindribaldur** [Rdatatable/data.table#3915]
```
data.table(V1 = factor(as.character(c(NA, 1:100, NA)), exclude = NULL))
# Error in as.character.factor(x) : malformed factor
data.table(V1 = factor(as.character(c(NA, 1:3, NA)), exclude = NULL))
#      V1
# 1: <NA>
# 2:    1
# 3:    2
# 4:    3
# 5: <NA>
```

Is this the expected behaviour? 

Another example here: https://stackoverflow.com/q/58103098/4552295

I'm getting this result with `data.table_1.12.2` and `R version 3.6.1`.

**Comment by jangorecki** [comment]
Same in devel. Thanks for reporting.
bug in print method, happens only for < 100 rows because of head&tail print format.
