### ISSUE TITLE
Try to use .. more in SO answers/documentation

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3916]
Inspired by this tweet+replies:

https://twitter.com/zentree/status/1177075147078918144

Still not a ton of awareness on .. usage in j

SO answers using `with=F` (wide net), via [SO query](https://data.stackexchange.com/stackoverflow/query/1115628/usage-of-withfalse-in-data-table-answers) & download CSV & replace `"`->``

Types of answers which can't be updated:

 I. Using the output of a function to name columns, like `[ , key(x), with=FALSE]` or `[ , foo(x), with=FALSE]`
II. Would be fixed by #2988 

- [x] https://stackoverflow.com/a/8377352
- [x] https://stackoverflow.com/a/8382486
- [x] https://stackoverflow.com/a/9202485
- [x] https://stackoverflow.com/a/9236768
- [x] https://stackoverflow.com/a/9269634
- [x] https://stackoverflow.com/a/9864666 
- [ ] https://stackoverflow.com/a/10088611 * pinged Matt to address an (very old) answer which doesn't run anymore
- [ ] https://stackoverflow.com/a/10466482 * Type I
- [x] https://stackoverflow.com/a/10756341
- [x] https://stackoverflow.com/a/10757820
- [x] https://stackoverflow.com/a/11265843
- [x] https://stackoverflow.com/a/11308946
- [x] https://stackoverflow.com/a/11941009
- [x] https://stackoverflow.com/a/12758229
- [x] https://stackoverflow.com/a/13130487
- [x] https://stackoverflow.com/a/13223642
- [x] https://stackoverflow.com/a/13383995
- [x] https://stackoverflow.com/a/13577501
- [x] https://stackoverflow.com/a/13635514
- [x] https://stackoverflow.com/a/13648975
- [x] https://stackoverflow.com/a/13755775
- [x] https://stackoverflow.com/a/13756786
- [x] https://stackoverflow.com/a/13760740
- [x] https://stackoverflow.com/a/13811401
- [x] https://stackoverflow.com/a/13822033
- [x] https://stackoverflow.com/a/13969805
- [ ] https://stackoverflow.com/a/14144194 * Type I
- [x] https://stackoverflow.com/a/14697838
- [x] https://stackoverflow.com/a/14937323
- [x] https://stackoverflow.com/a/15008164
- [x] https://stackoverflow.com/a/15017231
- [x] https://stackoverflow.com/a/15464770
- [ ] https://stackoverflow.com/a/15600672 * Type I
- [x] https://stackoverflow.com/a/15637223
- [ ] https://stackoverflow.com/a/15776186 * Type I
- [x] https://stackoverflow.com/a/15779078
- [x] https://stackoverflow.com/a/15784604
- [x] https://stackoverflow.com/a/15791747
- [x] https://stackoverflow.com/a/16037068
- [x] https://stackoverflow.com/a/16037329
- [x] https://stackoverflow.com/a/16048817
- [x] https://stackoverflow.com/a/16092334
- [x] https://stackoverflow.com/a/16136018
- [ ] https://stackoverflow.com/a/16154253 * Type I uses paste0 in by-.SD, not sure why not working
- [ ] https://stackoverflow.com/a/16189337 * Type II
- [x] https://stackoverflow.com/a/16362100
- [x] https://stackoverflow.com/a/16471747
- [ ] https://stackoverflow.com/a/16473380 * pending #3943
- [x] https://stackoverflow.com/a/16473460
- [x] https://stackoverflow.com/a/16660201
- [x] https://stackoverflow.com/a/16667624
- [ ] https://stackoverflow.com/a/16758299 * Type I; answer could probably also just use .SDcols
- [x] https://stackoverflow.com/a/16772809
- [x] https://stackoverflow.com/a/16847122
- [x] https://stackoverflow.com/a/16865506
- [x] https://stackoverflow.com/a/16936714
- [x] https://stackoverflow.com/a/17126247
- [x] https://stackoverflow.com/a/17126522
- [x] https://stackoverflow.com/a/17420436
- [x] https://stackoverflow.com/a/17476975
- [ ] https://stackoverflow.com/a/17581336 * Type I
- [ ] https://stackoverflow.com/a/17731293 * Type I
- [x] https://stackoverflow.com/a/18919776
- [x] https://stackoverflow.com/a/18970074
- [ ] https://stackoverflow.com/a/18970106 * Type I
- [x] https://stackoverflow.com/a/18970767
- [x] https://stackoverflow.com/a/19171032
- [x] https://stackoverflow.com/a/19256122
- [x] https://stackoverflow.com/a/19327132
- [x] https://stackoverflow.com/a/19454986
- [x] https://stackoverflow.com/a/19576563
- [x] https://stackoverflow.com/a/19794527
- [x] https://stackoverflow.com/a/19811795
- [x] https://stackoverflow.com/a/20645697
- [x] https://stackoverflow.com/a/23056431
- [x] https://stackoverflow.com/a/24148520
- [x] https://stackoverflow.com/a/27019323
- [x] https://stackoverflow.com/a/31197365
- [x] https://stackoverflow.com/a/33000778
- [x] https://stackoverflow.com/a/35351306
- [ ] https://stackoverflow.com/a/45688853 * Type I
- [ ] https://stackoverflow.com/a/19816256 * Type I
- [ ] https://stackoverflow.com/a/19829314 * Type I
- [x] https://stackoverflow.com/a/19850535
- [x] https://stackoverflow.com/a/20077670
- [x] https://stackoverflow.com/a/20077701
- [ ] https://stackoverflow.com/a/20202885 * Type I
- [ ] https://stackoverflow.com/a/20221789 * Type I
- [x] https://stackoverflow.com/a/20230968
- [x] https://stackoverflow.com/a/20383282
- [x] https://stackoverflow.com/a/20914724
- [x] https://stackoverflow.com/a/21024386
- [x] https://stackoverflow.com/a/21025209
- [x] https://stackoverflow.com/a/21055199
- [x] https://stackoverflow.com/a/21167790
- [x] https://stackoverflow.com/a/21170460
- [x] https://stackoverflow.com/a/21432165
- [x] https://stackoverflow.com/a/21466433
- [x] https://stackoverflow.com/a/21466500
- [x] https://stackoverflow.com/a/21564290
- [x] https://stackoverflow.com/a/21652125
- [x] https://stackoverflow.com/a/21689442
- [x] https://stackoverflow.com/a/21690524
- [ ] https://stackoverflow.com/a/21754425 *Type I ish -- can't do ..letters[1:2] (yet?)
- [x] https://stackoverflow.com/a/21859095
- [x] https://stackoverflow.com/a/21893708
- [x] https://stackoverflow.com/a/21952332
- [x] https://stackoverflow.com/a/22119386
- [x] https://stackoverflow.com/a/22273967
- [x] https://stackoverflow.com/a/22316329
- [ ] https://stackoverflow.com/a/22530042 *Type I ish -- c(1, j+1, j-1)
- [x] https://stackoverflow.com/a/22565582
- [x] https://stackoverflow.com/a/22694260
- [x] https://stackoverflow.com/a/22845261
- [x] https://stackoverflow.com/a/23092028
- [x] https://stackoverflow.com/a/23092675
- [x] https://stackoverflow.com/a/23222213
- [x] https://stackoverflow.com/a/23377047
- [x] https://stackoverflow.com/a/23412356
- [x] https://stackoverflow.com/a/23441619
- [x] https://stackoverflow.com/a/23474197
- [x] https://stackoverflow.com/a/23482568
- [x] https://stackoverflow.com/a/23503183
- [x] https://stackoverflow.com/a/23547459
- [ ] https://stackoverflow.com/a/23959184 *Type i: cols[i]
- [x] https://stackoverflow.com/a/23959381
- [x] https://stackoverflow.com/a/24112579
- [x] https://stackoverflow.com/a/24188193
- [ ] https://stackoverflow.com/a/24275304 * Type I
- [x] https://stackoverflow.com/a/24295335
- [x] https://stackoverflow.com/a/24626588
- [x] https://stackoverflow.com/a/24937370
- [ ] https://stackoverflow.com/a/24987717 * Type I ish? x[ , ncol(x), with=FALSE]
- [x] https://stackoverflow.com/a/25000184
- [x] https://stackoverflow.com/a/25041985
- [ ] https://stackoverflow.com/a/25067387 * messy answer... would take some time
- [ ] https://stackoverflow.com/a/25130696 * Type I
- [x] https://stackoverflow.com/a/25174446
- [x] https://stackoverflow.com/a/25212302
- [x] https://stackoverflow.com/a/25264214
- [x] https://stackoverflow.com/a/25535728
- [x] https://stackoverflow.com/a/25944409
- [x] https://stackoverflow.com/a/25956337
- [x] https://stackoverflow.com/a/25962445
- [x] https://stackoverflow.com/a/25997471
- [x] https://stackoverflow.com/a/26084175
- [ ] https://stackoverflow.com/a/26608058 * Type I : keys[i]
- [x] https://stackoverflow.com/a/26717541
- [x] https://stackoverflow.com/a/26826804
- [x] https://stackoverflow.com/a/26828713
- [x] https://stackoverflow.com/a/26845958
- [x] https://stackoverflow.com/a/26959633
- [x] https://stackoverflow.com/a/27053529
- [x] https://stackoverflow.com/a/27100150
- [x] https://stackoverflow.com/a/27373063
- [ ] https://stackoverflow.com/a/27543546 * Type I: nm2[[j]]
- [x] https://stackoverflow.com/a/27560478
- [x] https://stackoverflow.com/a/27609994
- [x] https://stackoverflow.com/a/27713565
- [x] https://stackoverflow.com/a/27747859
- [x] https://stackoverflow.com/a/27785774
- [x] https://stackoverflow.com/a/28094737
- [x] https://stackoverflow.com/a/27721110
- [x] https://stackoverflow.com/a/28097897
- [x] https://stackoverflow.com/a/28141784
- [x] https://stackoverflow.com/a/28279445
- [x] https://stackoverflow.com/a/28279539
- [ ] https://stackoverflow.com/a/28287977 * Type I ? A bit complicated, maybe more benefit from multi-`.SD`
- [x] https://stackoverflow.com/a/28406013
- [x] https://stackoverflow.com/a/28432327
- [x] https://stackoverflow.com/a/28621700
- [x] https://stackoverflow.com/a/28708907
- [x] https://stackoverflow.com/a/28723779
- [x] https://stackoverflow.com/a/28859038
- [x] https://stackoverflow.com/a/28917393
- [x] https://stackoverflow.com/a/28998173
- [x] https://stackoverflow.com/a/29080471
- [x] https://stackoverflow.com/a/29087565
- [x] https://stackoverflow.com/a/29087636
- [x] https://stackoverflow.com/a/29099309
- [x] https://stackoverflow.com/a/29240806
- [x] https://stackoverflow.com/a/29337291
- [x] https://stackoverflow.com/a/29354862
- [x] https://stackoverflow.com/a/29435524
- [ ] https://stackoverflow.com/a/29475974 * Type I -- `key()`
- [x] https://stackoverflow.com/a/29771788
- [ ] https://stackoverflow.com/a/29812120 * Type I -- colSums(DT) 
- [ ] https://stackoverflow.com/a/29871677 * Type I -- colnames(x)[1]
- [x] https://stackoverflow.com/a/30037828
- [x] https://stackoverflow.com/a/30067087
- [x] https://stackoverflow.com/a/30076577
- [x] https://stackoverflow.com/a/30175666
- [x] https://stackoverflow.com/a/30190276
- [x] https://stackoverflow.com/a/30216226
- [x] https://stackoverflow.com/a/30222105
- [x] https://stackoverflow.com/a/30242194
- [ ] https://stackoverflow.com/a/30283651 *
- [x] https://stackoverflow.com/a/30404223
- [x] https://stackoverflow.com/a/30449534
- [x] https://stackoverflow.com/a/30485610
- [x] https://stackoverflow.com/a/30497283
- [x] https://stackoverflow.com/a/30716831
- [x] https://stackoverflow.com/a/30757380
- [x] https://stackoverflow.com/a/30775844
- [x] https://stackoverflow.com/a/30843820
- [ ] https://stackoverflow.com/a/30855633 * 
- [x] https://stackoverflow.com/a/30971563
- [x] https://stackoverflow.com/a/31053207
- [x] https://stackoverflow.com/a/31058062
- [x] https://stackoverflow.com/a/31146132
- [x] https://stackoverflow.com/a/31230507
- [x] https://stackoverflow.com/a/31271966
- [ ] https://stackoverflow.com/a/31325518 * 
- [x] https://stackoverflow.com/a/31431080
- [x] https://stackoverflow.com/a/31433892
- [ ] https://stackoverflow.com/a/31506367 *
- [ ] https://stackoverflow.com/a/31592365 *
- [x] https://stackoverflow.com/a/31594165
- [x] https://stackoverflow.com/a/31600070
- [x] https://stackoverflow.com/a/31709153
- [x] https://stackoverflow.com/a/31994409
- [ ] https://stackoverflow.com/a/32092228 *
- [x] https://stackoverflow.com/a/32101691
- [x] https://stackoverflow.com/a/32146977
- [x] https://stackoverflow.com/a/32184318
- [x] https://stackoverflow.com/a/32244033
- [x] https://stackoverflow.com/a/32263828
- [ ] https://stackoverflow.com/a/32284002 *
- [x] https://stackoverflow.com/a/32301104
- [x] https://stackoverflow.com/a/32308699
- [x] https://stackoverflow.com/a/32358386
- [x] https://stackoverflow.com/a/32412564
- [x] https://stackoverflow.com/a/32599013
- [ ] https://stackoverflow.com/a/32611984 *
- [x] https://stackoverflow.com/a/32674242
- [x] https://stackoverflow.com/a/32720887
- [x] https://stackoverflow.com/a/33246418
- [x] https://stackoverflow.com/a/33301945
- [x] https://stackoverflow.com/a/33310211
- [x] https://stackoverflow.com/a/33365918
- [x] https://stackoverflow.com/a/33374076
- [x] https://stackoverflow.com/a/33483578
- [x] https://stackoverflow.com/a/33596543
- [x] https://stackoverflow.com/a/34193143
- [x] https://stackoverflow.com/a/34436718
- [x] https://stackoverflow.com/a/41259424
- [x] https://stackoverflow.com/a/33608542
- [x] https://stackoverflow.com/a/33659271
- [x] https://stackoverflow.com/a/33667064
- [ ] https://stackoverflow.com/a/33753341 * Type I
- [x] https://stackoverflow.com/a/33764808
- [x] https://stackoverflow.com/a/33781475
- [ ] https://stackoverflow.com/a/33795503 * Type I
- [ ] https://stackoverflow.com/a/33798033 * 
- [x] https://stackoverflow.com/a/34012931
- [x] https://stackoverflow.com/a/34092649
- [ ] https://stackoverflow.com/a/34185207 *
- [x] https://stackoverflow.com/a/34190507
- [ ] https://stackoverflow.com/a/34373116
- [ ] https://stackoverflow.com/a/34503665
- [ ] https://stackoverflow.com/a/34220956
- [ ] https://stackoverflow.com/a/34578863
- [ ] https://stackoverflow.com/a/34666130
- [ ] https://stackoverflow.com/a/34750693
- [ ] https://stackoverflow.com/a/34799050
- [ ] https://stackoverflow.com/a/34872333
- [ ] https://stackoverflow.com/a/34943272
- [ ] https://stackoverflow.com/a/35170148
- [ ] https://stackoverflow.com/a/35331837
- [ ] https://stackoverflow.com/a/35419279
- [ ] https://stackoverflow.com/a/35544997
- [ ] https://stackoverflow.com/a/35582563
- [ ] https://stackoverflow.com/a/35614344
- [ ] https://stackoverflow.com/a/35621947
- [ ] https://stackoverflow.com/a/35668272
- [ ] https://stackoverflow.com/a/35693634
- [ ] https://stackoverflow.com/a/35764275
- [ ] https://stackoverflow.com/a/35785990
- [ ] https://stackoverflow.com/a/35792287
- [ ] https://stackoverflow.com/a/35945512
- [ ] https://stackoverflow.com/a/36133703
- [ ] https://stackoverflow.com/a/36305801
- [ ] https://stackoverflow.com/a/36339465
- [ ] https://stackoverflow.com/a/36347707
- [ ] https://stackoverflow.com/a/36456334
- [ ] https://stackoverflow.com/a/36488380
- [ ] https://stackoverflow.com/a/36509061
- [ ] https://stackoverflow.com/a/36872769
- [ ] https://stackoverflow.com/a/37119312
- [ ] https://stackoverflow.com/a/37197226
- [ ] https://stackoverflow.com/a/37198059
- [ ] https://stackoverflow.com/a/37210528
- [ ] https://stackoverflow.com/a/37210546
- [ ] https://stackoverflow.com/a/37339193
- [ ] https://stackoverflow.com/a/37542534
- [ ] https://stackoverflow.com/a/37542835
- [ ] https://stackoverflow.com/a/37567861
- [ ] https://stackoverflow.com/a/37568489
- [ ] https://stackoverflow.com/a/37655412
- [ ] https://stackoverflow.com/a/37666742
- [ ] https://stackoverflow.com/a/37667288
- [ ] https://stackoverflow.com/a/37696966
- [ ] https://stackoverflow.com/a/37696967
- [ ] https://stackoverflow.com/a/37796841
- [ ] https://stackoverflow.com/a/37965602
- [ ] https://stackoverflow.com/a/37974623
- [ ] https://stackoverflow.com/a/38023429
- [ ] https://stackoverflow.com/a/38109271
- [ ] https://stackoverflow.com/a/38203559
- [ ] https://stackoverflow.com/a/38273499
- [ ] https://stackoverflow.com/a/38290038
- [ ] https://stackoverflow.com/a/38296983
- [ ] https://stackoverflow.com/a/38470997
- [ ] https://stackoverflow.com/a/38521778
- [ ] https://stackoverflow.com/a/38649497
- [ ] https://stackoverflow.com/a/38859443
- [ ] https://stackoverflow.com/a/38887204
- [ ] https://stackoverflow.com/a/38920734
- [ ] https://stackoverflow.com/a/38948462
- [ ] https://stackoverflow.com/a/39211972
- [ ] https://stackoverflow.com/a/39242241
- [ ] https://stackoverflow.com/a/39321486
- [ ] https://stackoverflow.com/a/39367909
- [ ] https://stackoverflow.com/a/39436766
- [ ] https://stackoverflow.com/a/39712153
- [ ] https://stackoverflow.com/a/39789740
- [ ] https://stackoverflow.com/a/39923539
- [ ] https://stackoverflow.com/a/40173749
- [ ] https://stackoverflow.com/a/40283104
- [ ] https://stackoverflow.com/a/40315567
- [ ] https://stackoverflow.com/a/40375483
- [ ] https://stackoverflow.com/a/40394519
- [ ] https://stackoverflow.com/a/40571095
- [ ] https://stackoverflow.com/a/40594921
- [ ] https://stackoverflow.com/a/40771563
- [ ] https://stackoverflow.com/a/41166612
- [ ] https://stackoverflow.com/a/41343980
- [ ] https://stackoverflow.com/a/41769783
- [ ] https://stackoverflow.com/a/41775535
- [ ] https://stackoverflow.com/a/41779145
- [ ] https://stackoverflow.com/a/41781264
- [ ] https://stackoverflow.com/a/41969871
- [ ] https://stackoverflow.com/a/42020650
- [ ] https://stackoverflow.com/a/42296777
- [ ] https://stackoverflow.com/a/42311568
- [ ] https://stackoverflow.com/a/42790513
- [ ] https://stackoverflow.com/a/42824615
- [ ] https://stackoverflow.com/a/42860349
- [ ] https://stackoverflow.com/a/43000219
- [ ] https://stackoverflow.com/a/43362229
- [ ] https://stackoverflow.com/a/43746237
- [ ] https://stackoverflow.com/a/44013800
- [ ] https://stackoverflow.com/a/44131730
- [ ] https://stackoverflow.com/a/44141837
- [ ] https://stackoverflow.com/a/44201616
- [ ] https://stackoverflow.com/a/44295877
- [ ] https://stackoverflow.com/a/44343384
- [ ] https://stackoverflow.com/a/44478990
- [ ] https://stackoverflow.com/a/44512677
- [ ] https://stackoverflow.com/a/44570429
- [ ] https://stackoverflow.com/a/44570872
- [ ] https://stackoverflow.com/a/44927901
- [ ] https://stackoverflow.com/a/45219301
- [ ] https://stackoverflow.com/a/45474075
- [ ] https://stackoverflow.com/a/46007823
- [ ] https://stackoverflow.com/a/46570017
- [ ] https://stackoverflow.com/a/46576396
- [ ] https://stackoverflow.com/a/47177132
- [ ] https://stackoverflow.com/a/47320778
- [ ] https://stackoverflow.com/a/47458106
- [ ] https://stackoverflow.com/a/47553180
- [ ] https://stackoverflow.com/a/47652353
- [ ] https://stackoverflow.com/a/47658575
- [ ] https://stackoverflow.com/a/47941529
- [ ] https://stackoverflow.com/a/48241599
- [ ] https://stackoverflow.com/a/48253812
- [ ] https://stackoverflow.com/a/48254523
- [ ] https://stackoverflow.com/a/48254822
- [ ] https://stackoverflow.com/a/48342886
- [ ] https://stackoverflow.com/a/48412406
- [ ] https://stackoverflow.com/a/48570044
- [ ] https://stackoverflow.com/a/48596271
- [ ] https://stackoverflow.com/a/48673401
- [ ] https://stackoverflow.com/a/48802554
- [ ] https://stackoverflow.com/a/48880529
- [ ] https://stackoverflow.com/a/49254757
- [ ] https://stackoverflow.com/a/49533037
- [ ] https://stackoverflow.com/a/49567106
- [ ] https://stackoverflow.com/a/49652644
- [ ] https://stackoverflow.com/a/50027752
- [ ] https://stackoverflow.com/a/50034368
- [ ] https://stackoverflow.com/a/50101304
- [ ] https://stackoverflow.com/a/50256677
- [ ] https://stackoverflow.com/a/50382374
- [ ] https://stackoverflow.com/a/50605260
- [ ] https://stackoverflow.com/a/50799129
- [ ] https://stackoverflow.com/a/50819933
- [ ] https://stackoverflow.com/a/51026271
- [ ] https://stackoverflow.com/a/51402826
- [ ] https://stackoverflow.com/a/52008992
- [ ] https://stackoverflow.com/a/52436661
- [ ] https://stackoverflow.com/a/52822577
- [ ] https://stackoverflow.com/a/52909535
- [ ] https://stackoverflow.com/a/53087012
- [ ] https://stackoverflow.com/a/53154421
- [ ] https://stackoverflow.com/a/53748031
- [ ] https://stackoverflow.com/a/53830681
- [ ] https://stackoverflow.com/a/55495855
- [ ] https://stackoverflow.com/a/55728691
- [ ] https://stackoverflow.com/a/55733044
- [ ] https://stackoverflow.com/a/55788088
- [ ] https://stackoverflow.com/a/55836462
- [ ] https://stackoverflow.com/a/55881201
- [ ] https://stackoverflow.com/a/56262238
- [ ] https://stackoverflow.com/a/56367493
- [ ] https://stackoverflow.com/a/56581308
- [ ] https://stackoverflow.com/a/57067533
- [ ] https://stackoverflow.com/a/57167967
- [ ] https://stackoverflow.com/a/57407959
- [ ] https://stackoverflow.com/a/57596025
- [ ] https://stackoverflow.com/a/57662386
- [ ] https://stackoverflow.com/a/57700421
- [ ] https://stackoverflow.com/a/57711983
- [ ] https://stackoverflow.com/a/57941310
- [ ] https://stackoverflow.com/a/57983021
- [ ] https://stackoverflow.com/a/58017639

But also should try and look through intro docs and make sure it's salient enough

**Comment by jangorecki** [comment]
or eventually new `env` arg instead.

**Comment by MichaelChirico** [comment]
Not worth pursuing further IMO. Can revisit if we do eventually deprecate `with=`, though it looks unlikely at the moment.
