### ISSUE TITLE
Improve 'DT$' item in Usage section

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3947]
Regarding this item on the homepage in the Usage section : 

> * no need to prefix columns with DT$

The way I worded this originally in 2006 in the Description (tweeted here https://twitter.com/MattDowle/status/720872742933831680) was to give a nod to `subset()` and `with()`. I was trying to get across that `DT[...]` builds in `subset()` and `with()` behavior.  More like: we like `subset()` and `with()` so much that we built them in and made it automatic.  Not so much that `DT$` is bad and that we fixed a bad thing (which might be how the bullet comes across currently), or that this can't be done in base R.  I'm pleased I mentioned `subset()` and `with()` originally so I'd prefer to retain that. On the other hand, people reading this page might not know what `subset()` and `with()` do, so mentioning them might not help them understand.

**Comment by jangorecki** [comment]
agree, explaining similarity to subset and with was big part of my intro workshop
