### ISSUE TITLE
Makevar

### ISSUE THREAD

**Issue by to0be0cool** [Rdatatable/data.table#3958]
I am ROOKIE, I am not programming, I AM A USER
PLEASE HELP ME! 
I am trying to install this data.table on a MAC, following the Wiki page and please I know my questions is stupid, but what is Makevars file? How can I create one? I have spend 3 hours trying to understand, please help me, all I want is to analyse my data :'(((((

**Comment by shrektan** [comment]
You’re welcome. Hope you can find data.table useful. And what I can tell you is, I really love it! Hope you will feel the same!

**Comment by to0be0cool** [comment]
I don't even know what data.table is doing, I suppose it arranges the things in a table.. I am just using the script written by others. I am just a simple chemist with absolutely no ambitions to become a data analyst. but I am thankful to the people who like data analysis, and more thankful to the people who will to help fellow scientists from other fields :)
