### ISSUE TITLE
First print fails on DT operation updated by reference and assigned

### ISSUE THREAD

**Issue by zeomal** [Rdatatable/data.table#3963]
Minimally reproducible example:

```
library(data.table)

iris_copy_1 <- setDT(copy(iris))

iris_copy_2 <- iris_copy_1[, .(.SD, ratio = Sepal.Length/Sepal.Width)][, ratio := 0]

iris_copy_2 # Printing to screen fails
iris_copy_2 # Printing to screen succeeds
```
The code above, by my understanding of `data.table`'s operations, should not fail the first time. Without assignment, of course, the output is not printed, but this behaviour should not be carried over here. I've noticed this under quite a few cases, with datasets of varying size, and on two different systems (Windows 10 and Windows 7, the former's session info attached). Output of sessionInfo() [here](https://pastebin.com/UFTJ5U7m).

**Comment by Henrik-P** [comment]
Please see [FAQ 2.23 Why do I have to type DT sometimes twice after using := to print the result to console?](https://cloud.r-project.org/web/packages/data.table/vignettes/datatable-faq.html)

**Comment by zeomal** [comment]
Oh, I missed that in the FAQ. I'd gone over this before back when my understanding of `data.table` was nascent. Thanks, and sorry for the repeat issue being brought up!
