### ISSUE TITLE
revdeps failed under R-devel

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3971]
Most likely related to #3968 

---

Dear maintainer,

package data.table_1.12.6.tar.gz has been auto-processed. The auto-check found problems when checking the first order strong reverse dependencies.
Please reply-all and explain: Is this expected or do you need to fix anything in your package? If expected, have all maintainers of affected packages been informed well in advance? Are there false positives in our results?

*** Changes to worse in reverse dependencies ***
Debian: <https://win-builder.r-project.org/incoming_pretest/data.table_1.12.6_20191015_082015/reverseDependencies/summary.txt>

Log dir: <https://win-builder.r-project.org/incoming_pretest/data.table_1.12.6_20191015_082015/>
The files will be removed after roughly 7 days.

Pretests:
Windows: <https://win-builder.r-project.org/incoming_pretest/data.table_1.12.6_20191015_082015/Windows/00check.log>
Debian: <https://win-builder.r-project.org/incoming_pretest/data.table_1.12.6_20191015_082015/Debian/00check.log>

Last published version on CRAN:

CRAN Web: <https://cran.r-project.org/package=data.table>

Best regards,
CRAN teams' auto-check service
Package check result: OK

Changes to worse in reverse depends:

Package: bigreadr
Check: tests
New result: ERROR
    Running ‘spelling.R’ [0s/0s]
    Running ‘testthat.R’ [2s/3s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > library(testthat)
    > library(bigreadr)
    >
    > test_check("bigreadr")
    ── 1. Failure: 'cbind_df' works (@test-bind.R#26)  ─────────────────────────────
    class(dt2) not identical to c("data.table", "data.frame").
    Lengths differ: 1 is not 2

    ── 2. Failure: 'cbind_df' works (@test-bind.R#27)  ─────────────────────────────
    `dt2` not identical to `dt`.
    Attributes: < Names: 2 string mismatches >
    Attributes: < Length mismatch: comparison on first 2 components >
    Attributes: < Component 1: Modes: character, externalptr >
    Attributes: < Component 1: target is character, current is externalptr >
    Attributes: < Component 2: Modes: numeric, character >
    Attributes: < Component 2: Lengths: 150, 2 >
    Attributes: < Component 2: target is numeric, current is character >

... snip; many package fails ....

---

From Matt :
This is not expected.  I had checked revdeps with R-release.  But there is a change in this release related to the rbind/cbind S3 dispatch change in R-devel recently that Kurt asked me to cater for, and a new switch on getRversion>="4.0.0" which is in NAMESPACE too.  I didn't check revdeps using R-devel as you do. I'll investigate tomorrow as it's 02:30 my time now.

---

From Uwe:
Thanks, I cancelled the submission for now.
Best,
Uwe

**Comment by mattdowle** [comment]
Smaller set than I feared : 
```
$ grep "^Package: " summary.txt | uniq
Package: bigreadr
Package: distr6
Package: DTSg [Old version: 0.1.3, New version: 0.2.0]
Package: eplusr
Package: mlr3
Package: mlr3db
Package: mlr3filters
Package: mlr3learners
Package: mlr3pipelines
Package: mlr3tuning
Package: paradox
Package: rAmCharts
Package: scorecard
Package: staRdom
Package: text2vec
```

**Comment by mattdowle** [comment]
distr6  --  same 'not a function' error on CRAN in just one flavor (debian-gcc). May have been fleeting in R-devel which is clearing now.

**Comment by mattdowle** [comment]
Matt to CRAN:
---
I have investigated all the fails, here: https://github.com/Rdatatable/data.table/issues/3971
They were all one issue: 'not a function ... in makeActiveBinding'.   This was a recent problem in R-devel it seems, unrelated to the data.table update, and appears to be clearing. I can see the same errors on CRAN in many cases.
Other than 3: bigreadr, scorecard and rAmCharts.  All 3 fail for correct reasons now in R-devel and will need an update. For example 2 of them call rbind.data.frame directly with fill=TRUE, and so that should be fixed.  I will submit PRs to those 3 maintainers,  cc'd.
Those 3 will only fail in R-devel though.  They will pass on CRAN on R-release. For that reason, and also because there is some urgency to the MacOS error and binary unavailability in R-release causing users issues,  can I be excused the notice period with those 3 maintainers please?  If so, please publish 1.12.6 to CRAN. I will start submitting PRs to those 3 maintainers tomorrow so they can update to pass checks on R-devel.  And it will be helpful if this data.table 1.12.6 is on CRAN first, before they update.
Best, Matt

**Comment by mattdowle** [comment]
Matt to CRAN:

---

Thanks Florian for updating bigreadr to 0.1.11 so quickly! But that change is not quite best. It's much simpler and I've submitted a PR for bigreadr:  https://github.com/privefl/bigreadr/pull/5

Uwe & Kurt,
I've added a check to data.table's .onLoad to ensure that data.table is reinstalled in R>4.0.0.  This won't make a difference to CRAN checks but I think it would be tidier to get into this release.
So I will submit another 1.12.6 later tonight once I've submitted PRs for scorecard and rAmCharts.
Best, Matt

**Comment by mattdowle** [comment]
@privefl
@ShichenXie 
@bthieurmel 
Many thanks for updating your packages on CRAN so quickly. CRAN's revdep autocheck service included your updates and tested them in latest R-devel with the updated data.table, and everything passed cleanly. data.table 1.12.6 has just been accepted on CRAN. Many thanks!

**Comment by privefl** [comment]
Many thanks to you for the great {data.table}!
