### ISSUE TITLE
turn off coverage on macos travis?

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#3980]
Looking at the macOS log on Travis, it looks to be running codecov and uploading to codecov.io.
https://travis-ci.org/Rdatatable/data.table/jobs/598969191
I'm not sure how that code coverage upload interacts with the upload from the Linux job.  I know that codecov increases the runtime quite a lot (quite understandably) so if we turned off coverage just in the macOS Travis job then maybe the macOS job would be significantly faster and we could leave macos travis turned on in dev after all.
Wasn't sure. So I raised an issue first.
Incidently, how do we get artifacts from Travis?  I wanted to check the output of the installation log on Travis (`00install.out`) but can't get to it; can't find anything similar to artifacts like there is on AppVeyor.

**Comment by jangorecki** [comment]
mac travis should not run codecov, it runs as
```sh
test $TRAVIS_OS_NAME == "linux" &&
    travis_wait Rscript -e 'library(covr); codecov()'
```

**Comment by jangorecki** [comment]
Looking at log you linked I see this step took 0.01s, so looks to be properly escaped.

**Comment by jangorecki** [comment]
I don't know about build artifacts from travis. We do pushlish tar.gz and PACKAGES file to gh-pages branch (only on success) in a very hackish way. It is nowhere close to getting 00install.out, which should be reachable even on failure.

**Comment by mattdowle** [comment]
Ahah. Thanks, @jangorecki. That explains why the drop-down arrow didn't do anything too. Great.
(Let's chase artifacts if it ever comes up again.)
