### ISSUE TITLE
Ability to explicitly pass index names in melt.data.table measure.vars argument

### ISSUE THREAD

**Issue by vspinu** [Rdatatable/data.table#4027]
Currently melt with multiple melting patterns works as expected only when data has a regular grid pattern. If some of the variables are missing the order of the output is scrambled.

For example:

```R
(dt <- data.table(id = 1, a.1 = 1, a.3 = 3, b.1 = 1, b.2 = 2, b.3 = 3))
##    id a.1 a.3 b.1 b.2 b.3
## 1:  1   1   3   1   2   3

melt.data.table(dt, "id" , measure.vars = list(a = 2:3, b = 4:6), variable.name = "ix")
##    id ix  a b
## 1:  1  1  1 1
## 2:  1  2  3 2
## 3:  1  3 NA 3
```

But what I really want is the ix of `a.3` to be 3,  not 2.

```R
##    id ix  a b
## 1:  1  1  1 1
## 2:  1  2 NA 2
## 3:  1  3  3 3
```

I was hoping that explicit index names in the measure.vars would be taken into account but they are currently not:

```R
melt.data.table(dt, "id" ,
                measure.vars = list(a = c("1" = 2, "3" = 3),
                                    b = c("4" = 4, "5" = 5, "6" = 6)),
                variable.name = "ix")
##    id ix  a b
## 1:  1  1  1 1
## 2:  1  2  3 2
## 3:  1  3 NA 3
```

I am fairly confident that this is related (or maybe even the same as #1739) but the example and discussion there is a bit cryptic.

Would you consider adding the ability to explicitly pass index names?

Thanks!

<details>

```
R Under development (unstable) (2019-08-06 r76924)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /home/vspinu/bin/R-latest/lib/libRblas.so
LAPACK: /home/vspinu/bin/R-latest/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=C              LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  utils     datasets  grDevices methods   base     

other attached packages:
[1] data.table_1.12.4

loaded via a namespace (and not attached):
[1] compiler_3.7.0
```

</details>

**Comment by Henrik-P** [comment]
I wonder if this may be related: [Properly handling the "variable" column after melting unbalanced wide data [feature request]](https://github.com/Rdatatable/data.table/issues/2575). Maybe also [Possibility to provide group labels in `variable` column when melting a list of columns simultaneously #Enhancement #melt](https://github.com/Rdatatable/data.table/issues/2551)?

**Comment by vspinu** [comment]
@Henrik-P, Indeed. Those seem related. I think in all these issues the solution might be to add an extractor regexp parameter which would extract the index  from the input names. 

In my case above it would be `melt(...., variable.extractor = ".*([0-9]+).*")` to get the digit index from the input variable names. Internally `melt.data.table` could do a simple `sub(variable.extractor, "\\1", vars)` to get the molten variable names.

**Comment by Henrik-P** [comment]
Just to connect to somewhat similar thoughts, see comments on [melt.data.table should offer `variable` to match on the name, rather than the number](https://github.com/Rdatatable/data.table/issues/3396): [here](https://github.com/Rdatatable/data.table/issues/3396#issuecomment-464455105) and [here](https://github.com/Rdatatable/data.table/issues/3396#issuecomment-479334432)

This is indeed a recurring topic ;)

**Comment by tdhock** [comment]
@vspinu and @Henrik-P I would argue that for this use case data table provides sufficient functionality already and such regex functionality is better left to dedicated extensions, such as nc::capture_melt_multiple https://github.com/tdhock/nc

**Comment by tdhock** [comment]
in regards to the suggestion from @vspinu about using named integer vectors in the measure.vars list, I would instead suggest to use NA:
```r
melt.data.table(dt, "id" , measure.vars = list(a = c(2, NA, 3), b = 4:6))
```

**Comment by tdhock** [comment]
by the way tidyr does this 
```r
> tidyr::pivot_longer(wide.input, -1, names_pattern = "(.).(.)", names_to=c(".value", "ix"))
# A tibble: 3 x 4
     id ix        a     b
  <dbl> <chr> <dbl> <dbl>
1     1 1         1     1
2     1 3         3     3
3     1 2        NA     2
```

**Comment by vspinu** [comment]
@tdhock I am not sure I understand what those NAs signify in your proposal, but regardless, I think it will not work if you don't know the pattern of "missing" columns in advance. In one case a.1 can be missing in another a.2 etc.

**Comment by tdhock** [comment]
hi @vspinu I tried to clarify my comment above, does that help?
If I understand you correctly, which input columns are missing may not be known in advance, but their input column names which are present should be named consistently right? In that case we can describe the consistent naming pattern with a regex, and it is possible/trivial to automatically identify which ones are missing (and that is what I do internally in nc::capture_melt_multiple).
For my purposes of implementing an efficient solution to this problem using nc functions on top of data table, either solution should suffice:
- either the named integer vectors of variable length suggested by @vspinu 
- or the un-named integer vectors of contant size which I suggested above
@jangorecki do you have any idea about which would be easier to implement given the current melt.data.table code? (I am not familiar with that code at all so I don't know which approach would e easier)
who wrote/maintains that code?

**Comment by jangorecki** [comment]
I am not very familiar of melt/dcast internals unfortunately so cannot help on that. I think @arunsrinivasan wrote the most of it, or at least there recent version of it.

**Comment by mrdwab** [comment]
In the [V2 version of `splitstackshape`](https://github.com/mrdwab/splitstackshape/tree/v2.0) (which I haven't worked on in a long time) I was working on a `reshape_long` wrapper around `melt`. It works, but it's a somewhat convoluted approach of adding empty columns to balance the data before it gets `melt`ed that I'm sure can be enhanced. It's slower than `melt` because I err on the side of caution and use `setDT(copy(input))` since the function potentially adds stuff the user wouldn't want in their original data.

Here's how it works with this example:

    library(data.table)
    library(splitstackshape)
    # This is 'splitstackshape' version 2.0.0.
    
    reshape_long(dt, c("a", "b"), variable.name = "ix")
    # All non-stub names being used as ids
    #    id ix  a b
    # 1:  1  1  1 1
    # 2:  1  2 NA 2
    # 3:  1  3  3 3

It also works with some of the other related issues, though additional care needs to be taken with the column names. 

For example, with issue #3396 the columns need to be renamed since [`all_names`](https://github.com/mrdwab/splitstackshape/blob/9d4183595c4989532e98325a8cb1878e7d7c5a15/R/splitstackshape_helper_functions.R#L50) hasn't been written in a way that a column name ending with `$` would be accepted. 

There, the approach might be something like:

    setnames(DT, gsub("$", "dollar", names(DT), fixed = TRUE))
    reshape_long(DT, c(Dollar = "dollar", Number = "No"), end_stub = TRUE)

Other examples, like @ggrothendieck's [example](https://github.com/Rdatatable/data.table/issues/4047#issuecomment-615209508) at issue #4047 don't have "stubs", so you need to add them in:

    setnames(input, grep("\\d$", names(input), value = TRUE), 
             sprintf("%s_score", grep("\\d$", names(input),  value = TRUE)))
    reshape_long(input, stubs = c("score", "sp"), end_stub = TRUE)[
      , na.omit(.SD), key = c("id", "school")]

**Comment by tdhock** [comment]
hi #4720 solves this issue. Its not merged into master yet but you can use it via
```r
remotes::install_github(c("Rdatatable/data.table@fix4027", "tdhock/nc@multiple-fill"))
#> Skipping install of 'data.table' from a github remote, the SHA1 (4c5810c2) has not changed since last install.
#>   Use `force = TRUE` to force installation
#> Skipping install of 'nc' from a github remote, the SHA1 (11b61f8e) has not changed since last install.
#>   Use `force = TRUE` to force installation
dt <- data.table::data.table(id = 1, a.1 = 1, a.3 = 3, b.1 = 1, b.2 = 2, b.3 = 3)
nc::capture_melt_multiple(dt, column="[a-z]", "[.]", ix="[0-9]", fill=TRUE)
#>    id ix  a b
#> 1:  1  1  1 1
#> 2:  1  2 NA 2
#> 3:  1  3  3 3
```

**Comment by jangorecki** [comment]
Waiting for merged PR with this. Issue should stay open till it is fixed in upstream branch, news item provided and ideally tests.

**Comment by tdhock** [comment]
whoops sorry, I was trying to be too helpful I guess!

**Comment by tdhock** [comment]
btw @vspinu can you share a link to a "real" data set which has missing variables?

**Comment by tdhock** [comment]
hi @vspinu here is some code which shows how to solve your original problem using the new melt functionality:
```r
remotes::install_github("Rdatatable/data.table@fix4027")
#> Skipping install of 'data.table' from a github remote, the SHA1 (4c5810c2) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(data.table)
dt <- data.table(id = 1, a.1 = 1, a.3 = 3, b.1 = 1, b.2 = 2, b.3 = 3)
melt(
  dt, variable.name="ix",
  measure.vars=list(a=c("a.1", NA, "a.3"), b=c("b.1", "b.2", "b.3")))
#>    id ix  a b
#> 1:  1  1  1 1
#> 2:  1  2 NA 2
#> 3:  1  3  3 3
```
(this melt call is what nc::capture_melt_multiple does internally after doing regex matching on column names)

**Comment by tdhock** [comment]
pure data.table solution using #4731 
```r
remotes::install_github("Rdatatable/data.table@melt-custom-variable")
#> Skipping install of 'data.table' from a github remote, the SHA1 (c02fa9e8) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(data.table)
dt <- data.table(id = 1, a.1 = 1, a.3 = 3, b.1 = 1, b.2 = 2, b.3 = 3)
melt(dt, measure.vars=measure(value.name, ix, sep="."))
#>    id ix  a b
#> 1:  1  1  1 1
#> 2:  1  3  3 3
#> 3:  1  2 NA 2
```
