### ISSUE TITLE
Odd parameter names of `setnames`

### ISSUE THREAD

**Issue by Kodiologist** [Rdatatable/data.table#4041]
If you call `setnames` with just a vector of new names, then it looks like `setnames(df, c("date", "place", "value"))`, which is fine. But if you name the argument supplying the new names, then the call looks like `setnames(old = c("date", "place", "value"), df)`, which is confusing because you're supplying new names, not old ones. Consider allowing `old` to be missing, so `new` can be set by name instead.

**Comment by MichaelChirico** [comment]
The goal of the current design is to allow both usages:

```
iris = data.table(iris)
setnames(iris, letters[1:6])
setnames(iris, letters[1:3], LETTERS[1:3])
```

Unfortunately unless I'm missing something (very possible), that by necessity means the second argument will be overloaded -- in the first case, it's the _new_ names; in the second case, it's the _old_ names. We chose `old` as the argument name for clarity in the latter use case.

If you have an alternative in mind, that would be great. Or, if you explain what's wrong for your use case with using implicit argument matching, that would also be helpful.

**Comment by Kodiologist** [comment]
You should be able keep the existing overloading with an approach like the following. Keep the order and names of parameters as they are, but put this near the top of the definition of `setnames`:

```
if (is.missing(old) && !is.missing(new)) {
    old = new
    new = NULL
}
```

This way, all existing code should work unaltered, and it will be possible to say `setnames(iris, new = LETTERS[1:6])`.

**Comment by MichaelChirico** [comment]
but that's not the same. it requires naming 'new' explicitly, which will
break a mountain of code.

**Comment by Kodiologist** [comment]
I don't follow. Since the parameter order stays the same, `setnames(iris, letters[1:6])` and `setnames(iris, letters[1:3], LETTERS[1:3])` will still do what they before. Since the parameter names stay the same, any calls that used names will still work, too. The only change should be to calls that weren't legal originally, such as `setnames(iris, new = LETTERS[1:6])`.

**Comment by MichaelChirico** [comment]
maybe it's best to file a PR since it seems like you have something in mind already for how it would work.
