### ISSUE TITLE
data.table  breaks xts first(), last() distpatching

### ISSUE THREAD

**Issue by ethanbsmith** [Rdatatable/data.table#4053]
upgrading to data.table 12.6 breaks existing xts first(), last() dispatching. Im not sure what the last working verison was, but the broke somewhere between 12.2 and 12.6. reverting to 12.2 restores expected behavior

```
library(quantmod)
r <- getSymbols("SPY", auto.assign=F)
> last(r)
           SPY.Open SPY.High SPY.Low SPY.Close SPY.Volume SPY.Adjusted
2019-11-15   311.02   311.84  310.26    311.79   62023600       311.79
> library(data.table)
> last(r)
[1] 311.79
```

**Comment by jangorecki** [comment]
I am pretty sure it is my fault, made in https://github.com/Rdatatable/data.table/pull/3859
I knew it might be breaking change thus asked for revdeps check, but it appears none of the revdeps was testing that. Thanks for reporting.

**Comment by joshuaulrich** [comment]
Thanks @jangorecki! Let me know if there's anything I can do in xts to help catch things like this in the future, and/or I can do anything to help our two packages play nicely together.

**Comment by jangorecki** [comment]
@joshuaulrich extra eyes on a fix PR would be helpful. Thanks

**Comment by joshuaulrich** [comment]
Hi Jan, I looked at the PR, and I don't have a good enough understanding of the underlying code to make useful comments.
