### ISSUE TITLE
melt converts the variable content to numbers (from its factor levels).

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#4056]
I was reading a data.table cheatsheet:
https://raw.githubusercontent.com/rstudio/cheatsheets/master/datatable.pdf

And I've found something that may be an error.

This works well:
```
DTLong  <- data.table(id=c("A","A","B","B"), y=c("x","z","x","z"), a=c(1,2,1,2), b=c(6,7,8,9))

   id y a b
1:  A x 1 6
2:  A z 2 7
3:  B x 1 8
4:  B z 2 9

DTwide <- dcast(DTLong, id ~ y,value.var = c("a", "b"))

   id a_x a_z b_x b_z
1:  A   1   2   6   7
2:  B   1   2   8   9
```
But this:
```
melt(DTwide, id.vars = c("id"), measure.vars = patterns("^a", "^b"), variable.name = "y", 
     value.name = c("a", "b"), variable.factor = F) 
```

Gives the result:
```
   id y a b
1:  A 1 1 6
2:  B 1 1 8
3:  A 2 2 7
4:  B 2 2 9
```

It should be instead:

```
   id y a b
1:  A x 1 6
2:  B x 1 8
3:  A z 2 7
4:  B z 2 9
```

I have tried with _variable.factor = F_  but then instead of factors I get characters of the numbers, still not the original letters.

**Comment by sindribaldur** [comment]
* Should be `dcast(DTLong,...` instead of `dcast(xsxs,...`.

* Why do you think your expected output is what *should* happen?

**Comment by skanskan** [comment]
It was a typo, I'm sorry.

Because it's the reverse process, I expect to get the original input.
Maybe it's not a "should" happen because it wasn't clear how the output was requested by the user (me).

In this simpler version (without patterns) works as expected.
```
DTLong  <- data.table(id=c("A","A","B","B"), y=c("x","z","x","z"), b=c(6,7,8,9))
DTwide <- dcast(DTLong, id ~ y,value.var = c( "b"))
melt(DTwide, id.vars = c("id"),  variable.name = "y",  value.name = c("b"), variable.factor = F)

   id y b
1:  A x 6
2:  B x 8
3:  A z 7
4:  B z 9
```

**Comment by MichaelChirico** [comment]
Is this the same as #2551?

Agree it should be fixed, I think `melt` could go for a bit of a makeover.

**Comment by tdhock** [comment]
hi here is a solution to the original post that uses the new function in nc package (which uses melt.data.table internally), 
```r
library(data.table)
DTLong  <- data.table(id=c("A","A","B","B"), y=c("x","z","x","z"), a=c(1,2,1,2), b=c(6,7,8,9))
(DTwide <- dcast(DTLong, id ~ y,value.var = c("a", "b")))
#>    id a_x a_z b_x b_z
#> 1:  A   1   2   6   7
#> 2:  B   1   2   8   9
nc::capture_melt_multiple(DTwide, column="[ab]", "_", y="[xz]")
#>    id y a b
#> 1:  A x 1 6
#> 2:  B x 1 8
#> 3:  A z 2 7
#> 4:  B z 2 9
```

**Comment by jangorecki** [comment]
If we decide that requested functionality is out of scope then agree we can close and suggest using another package. Otherwise we could have that functionality in DT thus issue should stay open.
I don't have any preferences on that so interested parties should provide a comment.

**Comment by tdhock** [comment]
here is a pure data.table solution using new feature in #4731 
```r
remotes::install_github("Rdatatable/data.table@melt-custom-variable")
#> Skipping install of 'data.table' from a github remote, the SHA1 (c02fa9e8) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(data.table)
DTLong  <- data.table(id=c("A","A","B","B"), y=c("x","z","x","z"), a=c(1,2,1,2), b=c(6,7,8,9))
DTwide <- dcast(DTLong, id ~ y,value.var = c("a", "b"))
melt(DTwide, measure.vars=measure(value.name, y))
#>    id y a b
#> 1:  A x 1 6
#> 2:  B x 1 8
#> 3:  A z 2 7
#> 4:  B z 2 9
```

**Comment by tdhock** [comment]
#4731 was recently merged into master so @skanskan if that works for you can you please close this issue?
