### ISSUE TITLE
R-devel switch to reference counting

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#4058]
From Luke and Kurt,

---

Hi Matt,

We're hopefully just a few weeks away from switching R-devel from
NAMED to reference counting. One of data.table's tests fails under
reference counting because the .Internal(inspect()) output is
different: it shows number of references as REF(n) instead o the NAMED
field value as NAM(n). Can you please look into adjusting your tests?

For now you can build with reference counting using a configure.site
file containing

CFLAGS="-O2 -g -Wall -pedantic -DSWITCH_TO_REFCNT"

Best,
Luke

---

Matt:
My debian-gcc check run will soon use -DSWITCH_TO_REFCNT and hence show
the error: so please fix as quickly as possible.
Best
-k

---

**Comment by jangorecki** [comment]
great news, finally!
