### ISSUE TITLE
Is there any docs I can find to understand when parallelism is used

### ISSUE THREAD

**Issue by statquant** [Rdatatable/data.table#4071]
Hello, this is a question as opposed to an issue, please kindly refer me to the proper channel if that was not the right one.
I am looking for documentation to understand exactly where data.table uses openMP parallelism, there are cases where I clearly see the parallelism kick in but in cases where I do long `by` operations it is clearly not.
Is there anything I can use ?

Regards

**Comment by MichaelChirico** [comment]
I guess we could/should add this to the `?openmp-utils` man page.

Extremely user-unfriendly answer in the meantime -- use `grep`: `grep -Elr "#pragma omp (?:for|parallel)" src`:

```
src/forder.c
src/coalesce.c
src/gsumm.c
src/froll.c
src/nafill.c
src/between.c
src/fsort.c
src/frolladaptive.c
src/cj.c
src/types.c
src/fread.c
src/frollR.c
src/reorder.c
src/fifelse.c
src/fwrite.c
src/subset.c
```
