### ISSUE TITLE
Add option to merge() to automatically remove columns with duplicated informations

### ISSUE THREAD

**Issue by YoannPa** [Rdatatable/data.table#4082]
Hi, 
so this is something I am wondering about since some time already, merge() function works fine on data.table objects, but one thing that I encounter often when I want to merge 2 tables, is that sometimes the 2 tables contains the same information in some columns (and columns do not have 
necessarily the same column names).
Would it be possible to add an option to the merge() function to let user the possibility to **automatically remove the columns with duplicated information in the final data.table**?
Something like:   
**merge(,.., rm.dup=TRUE)**

I checked on Stackoverflow and in other issues, I did not find any similar feature request.

Currently I do this task manually, first identifying columns with duplicated information, and then discarding them the data.table way.
If adding this option is not possible, any idea if this is already possible another way ?

**Comment by jangorecki** [comment]
I don't think it fits into merge function, I would rather keep that in a helper function. `merge` method just redirects to `DT1[DT2]` join. Why not look over columns in two data.tables using `all.equal`? `merge` do merge ignoring order of rows, so it is expensive (it actually orders `on` columns later on). Using `all.equal` after `merge` should be cheap because it doesn't need to check order. If you already asked SO question on that problem just drop the link here.

**Comment by YoannPa** [comment]
Okay I wasn't aware of that.
Then merge might not suit indeed.

> Why not loop over columns in two data.tables using all.equal? 

How would you do this looping over the 2 dataframes using all.equal ?

Currently I use duplicated() on the data.frame resulting from merge() (I would have enjoy a method able to point columns that will be duplicated in the resulting data.frame before merging, unfortunately I don't thing such thing is available, and that sounds complex to assess, since the 2 dataframes can have different number of rows for example, without merging dataframes in the first place...): 

`duplicated(t(DT))[ duplicated(t(DT)) == TRUE ] `
Then I simply extract names of duplicated columns and subset my DT the data.table way:
`DT[,-c(duplicated_names),with=FALSE]`

Doing it once is fine, but when you have several table to process going few times through the same process of removing the duplicated columns each time is annoying.

> If you already asked SO question on that problem just drop the link here.

I haven't post any question on SO yet. And I am not sure I will, since I would be happy to write a small function myself to allow the remove of duplicated columns after merging.

**Comment by jangorecki** [comment]
This question seems to fit bests to stackoverflow. Closing then.
