### ISSUE TITLE
set could allow empty input without warning

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4086]
```r
d = data.table(a=1, b=1)
dropcols = character()
set(d, NULL, dropcols, NULL)
#Warning message:
#In set(d, NULL, dropcols, NULL) :
#  length(LHS)==0; no columns to delete or assign RHS to.
```
I don't think we really need a warning here, it could work without the need for `if (length(dropcols)) set(...)`.

**Comment by jangorecki** [comment]
That would unfortunately also remove the warning from `d[, character() := NULL]`. Are we OK to remove the warning from here also? IMO make sense

**Comment by MichaelChirico** [comment]
Agree don't need to warn, verbose message would be fine
