### ISSUE TITLE
Compiler warning on platform: armv8l-unknown-linux-gnueabi (32-bit)

### ISSUE THREAD

**Issue by 2005m** [Rdatatable/data.table#4097]
`
gcc I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include -fopenmp -fpic  -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb  -c freadR.c -o freadR.o
In file included from fread.c:28:
./freadLookups.h:31:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-350L,
^
./freadLookups.h:32:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-349L,
^
./freadLookups.h:33:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-348L,
^
./freadLookups.h:34:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-347L,
^
./freadLookups.h:35:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-346L,
^
./freadLookups.h:36:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-345L,
^
./freadLookups.h:37:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-344L,
^
./freadLookups.h:38:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-343L,
^
./freadLookups.h:39:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-342L,
^
./freadLookups.h:40:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-341L,
^
./freadLookups.h:41:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-340L,
^
./freadLookups.h:42:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-339L,
^
./freadLookups.h:43:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-338L,
^
./freadLookups.h:44:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-337L,
^
./freadLookups.h:45:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-336L,
^
./freadLookups.h:46:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-335L,
^
./freadLookups.h:47:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-334L,
^
./freadLookups.h:48:1: warning: magnitude
      of floating-point constant too small
      for type 'long double'; minimum is
      4.9406564584124654E-324
      [-Wliteral-range]
1.0E-333L,
^
`

**Comment by MichaelChirico** [comment]
Maybe we can set/unset `DBL_MIN` to 1e-350 to define the `pow10lookup`? 

https://trac.openmodelica.org/OpenModelica/ticket/4713

**Comment by QuLogic** [comment]
This is somewhat-concidentally fixed by #4165.

**Comment by 2005m** [comment]
Yes I think you are right. I noticed it as well but I was not sure.
