### ISSUE TITLE
.SDcols with logical vector

### ISSUE THREAD

**Issue by Henrik-P** [Rdatatable/data.table#4115]
In `?data.table` about `.SDcols` argument:

>May be character column names or numeric positions. 

However, it seems like also a `logical` vector is possible, e.g.

    d <- data.table(x = 1, y = "a")
    d[ , .SD, .SDcols = sapply(d, is.numeric)]
    #    x
    # 1: 1

If selecting columns with a logical vector in `.SDcols` is intended to work, should this possibility be added to the help text?
 
Please also note two differences with `j` in this regard:

(1) Using a logical vector longer than the number of columns errors in `j`, but not in `.SDcols`

    d[ , c(TRUE, TRUE, TRUE)]
    # Error in `[.data.table`(d, , c(TRUE, TRUE, TRUE)) : 
    #  Item 3 of j is 3 which is outside the column number range [1,ncol=2]

    d[ , .SD, .SDcols = c(TRUE, TRUE, TRUE)]
    #    x y
    # 1: 1 a

(2) If a logical vector with length `k < ncol(x)` is passed to `j`, it will be filled to length `ncol(x)` with `FALSE`. In `.SDcols`, the logical vector is recycled.

    d[ , TRUE]
    #    x
    # 1: 1

    d[ , .SD, .SDcols = TRUE]
    #    x y
    # 1: 1 a

----

`data.table` 1.12.9 IN DEVELOPMENT built 2019-12-13 23:32:57 UTC

**Comment by jaapwalhout** [comment]
Related to #3950 and #3991 ?

**Comment by Henrik-P** [comment]
@jaapwalhout Thanks for spotting these posts. Indeed related. Cheers.

**Comment by ColeMiller1** [comment]
What is the preferred behavior for incomplete logical vectors in ```j``` or ```.SDcols```? My thought would be for it to error out.

**Comment by jangorecki** [comment]
It will error.

**Comment by jangorecki** [comment]
1.9.5 has a following new feature entry

>  15. `.SDcols` accepts logical vectors as well. If length is smaller than number of columns, the vector is recycled. Closes [#1060](https://github.com/Rdatatable/data.table/issues/1060). Thanks to @StefanFritsch.

So in theory someone could rely on that, but on the other hand, documentation does not seem to mention that .

**Comment by MichaelChirico** [comment]
I would be fine putting deprecation cycle on that at least. Generally we are moving away from such recycling

**Comment by jangorecki** [comment]
Yes, #4470 keep recycling but with warning
