### ISSUE TITLE
Error in documenation

### ISSUE THREAD

**Issue by KyleHaynes** [Rdatatable/data.table#4118]
In the following: https://github.com/Rdatatable/data.table/blob/master/man/print.data.table.Rd

In the details section a backslash is missing:

*By default, with an eye to the typically large number of observations in a **code{data.table}***

**Comment by MichaelChirico** [comment]
thanks! would you mind filling a PR?

**Comment by KyleHaynes** [comment]
Will do

**Comment by KyleHaynes** [comment]
And FWIW, I did quite a bit of checking for any others and this was the only one.
