### ISSUE TITLE
Filter Helper Functions

### ISSUE THREAD

**Issue by ColeMiller1** [Rdatatable/data.table#4133]
```dplyr``` has many helper functions for filtering including ```filter_at(.tbl, .vars, .vars_predicate, .preserve = FALSE)``` and ```top_n(x, n, wt)```. These functions are particularly helpful in combination with ```group_by()``` such as:
```
library(dplyr)
tib <- as_tibble(iris)
tib%>%
  group_by(Species)%>%
  top_n(3, Sepal.Length)
```
While optimizations have been made for ```data.table``` in ```.SD[]```, a helper function in the ```i``` could be 1) more performant and 2) allow update-by-reference in the ```j```. Additionally, since the ```dt[dt[, .I[1:3], by = fct]$V1]``` is typically faster than the ```.SD[]``` method, a helper function would allow us to better achieve that peak performance and be used in chaining operations instead of saving an intermediate ```data.table``` object.

On SO, these types of helper functions really help ```dplyr``` shine - I would really like assisting ```data.table``` but this is too extreme for a random PR. I have done enough work that non-exported ```top.n(n, wt, by)``` and ```filter.at(cols, logic, by, all.vars = TRUE)``` currently work with all tests checking out OK on my PC. As for performance:

top.n:
```
foo2 <- data.table(
  x = runif(n = 10^7),
  grp = sample(letters[1:5], 10^7, replace = T)
)

# A tibble: 3 x 13
  expression                                              min median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>                                            <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int>
1 foo2[top.n(-3L, x, grp)]                               1.7s  2.04s     0.503     298MB    0.805    10
2 foo2[foo2[, .I[frank(x) <= 3L], grp]$V1]              1.76s  2.04s     0.490     336MB    0.980    10
3 foo2[, .SD[frank(x, ties.method = "min") <= 3L], grp] 1.71s   1.9s     0.513     298MB    0.872    10
```
filter.at:
```
foo <- data.table(
  x = as.character(runif(n = 10^6)),
  y = as.character(runif(n = 10^6)),
  z = as.character(runif(n = 10^6))
)

# A tibble: 3 x 13
  expression                                              min median `itr/sec` mem_alloc `gc/sec` n_itr
  <bch:expr>                                            <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int>
1 foo[filter.at(c("x", "y", "z"), like(x, "123"))]      290ms  301ms      3.32     7.9MB    0.831     4
2 foo[like(x, "123")][like(y, "123")][like(z, "123")]   291ms  291ms      3.35    8.13MB    0         5
3 foo[like(x, "123") & like(y, "123") & like(z, "123")] 858ms  884ms      1.10    22.9MB    0         5
```
Notice ```filter.at()``` has a nice performance gain and would help in closing issues like [4105](https://github.com/Rdatatable/data.table/issues/4105) as the code includes optimizations.

Is this something that is wanted? If it is, I could start working on a PR that would also include filter.all, top.n.bottom, sample.n, subset.n, and slice.n. If it is not wanted, I completely understand. Thank you for all of your work.

**Comment by jangorecki** [comment]
It is much better to optimize head(n=2) etc rather than adding new functions. Don't know what is the body of filter.at fun but note the comments in #4105, solution proposed there is not appropriate because it can actually increase time.

**Comment by MichaelChirico** [comment]
see also https://github.com/Rdatatable/data.table/issues/3804

**Comment by ColeM1** [comment]
Both functions are highly NSE. The optimized ```filter.at()``` is largely:
```
ind = which(like(x[['x']], '123'))
for (col in c('y', 'z'){
  ind = ind[like(x[[col]], '123'))
}
```
All other functions substitute in to largely end up with ```[dt[, .I[...], by = ...]$V1```. Full functions:
```
#starting on line 341 within `[data.table`
    if (is.call(isub) && as.character(isub[[1]])[[1L]] %chin% c('top.n', 'filter.at')) {  #TO DO , 'filter.all', 'top.n.bottom', 'sample.n', 'subset.n', 'slice.n'
      l <- eval(isub)

      if (is.null(l$j)){
  
        #for optimizing dt[a & b & c]   - used only for filter.at
        eval(l[[1]])
        eval(l[[2]])

        #ind is a result of the eval steps
        isub = ind
      } else if (is.null(l$by)) {
        isub = do.call(`[.data.table`, l)
      } else {
        isub = do.call(`[.data.table`, l)$V1
      }
    }
##########

##new functions

top.n = function(n, wt, by) {
  
  l = as.list(match.call())
  
  if (missing(by)){
    l_args = vector('list', length = 2)
    names(l_args) = c('x', 'j')
  } else {
    l_args = vector('list', length = 3)
    names(l_args) = c('x', 'j', 'by')
    l_args[['by']] = l$by
  }
  
  l_args[['x']] = quote(x)
  if (n > 0) {
    l_args[['j']] = str2lang(paste0('.I[frank(', paste0('-', as.character(l[['wt']])), ', ties.method = "min") <= ',n, ']'))
  } else {
    l_args[['j']] = str2lang(paste0('.I[frank(', as.character(l[['wt']]), ', ties.method = "min") <= ',abs(n), ']'))
  }
  l_args
}

filter.at = function(cols, logic, by, all.vars = TRUE){

  l = as.list(match.call())
  # Predicates wtih rle and cumsum do not work
  # with chaining i.e. 
  # dt[rleid(x1) < 5 & rleid(x2)] does not always equal
  # dt[rleid(x1) < 5][rleid(x2) < 5]
  #
  # May want to make this an arg that defaults to FALSE.
  
  quickFilter = !grepl('rle|cumsum', deparse(l[['logic']]))

  # remove missing(by) after optimizing by  
  if (missing(by) && all.vars == T && quickFilter){
    if (missing(by)){
      
      #optimization. For logic of x == 5 and cols = c('a','b','c') the resut of this would be
      #
      # ind <- which(dt[['a']] == 5)
      # for(col in c('b','c')){
      #   ind <- ind[dt[['col']][ind] == 5]
      # }
      
      dt_quote_start = substitute(x[[cols]], list (cols = cols[1]))
      logic_eq_start = eval(substitute(substitute(ind <- which(eq), list(x = dt_quote_start)), list(eq = l[['logic']])))
      
      # dt_quote_loop = quote(x[[col]][ind])
      dt_quote_loop = quote(.Call(data.table:::CsubsetVector, x[[col]], ind))
      # logic_eq_loop = eval(substitute(substitute(for (col in cols){ind <- ind[eq]}, list(cols = cols[-1], x = dt_quote_loop)), list(eq = l[['logic']])))
      logic_eq_loop = eval(substitute(substitute(for (col in cols){ind <- .Call(data.table:::CsubsetVector, ind, which(eq))}, list(cols = cols[-1], x = dt_quote_loop)), list(eq = l[['logic']])))

      return(list(logic_eq_start, logic_eq_loop))
    } 
    else {
      
      # to do
      # optimize by
      
      # dt[,
      #     {
      #       ind <- which(logic(get(col[1])))
      #       for (col in cols[-1]){
      #         ind <- ind[logic(get(col[ind]))]
      #       }
      #       .I[ind]
      #     }
      #     ,by = by]
    }
  } else if (missing(by)){
    l_args = vector('list', length = 3)
    names(l_args) = c('x', 'j', '.SDcols')
  } else {
    l_args = vector('list', length = 4)
    names(l_args) = c('x', 'j', '.SDcols', 'by')
    l_args[['by']] = l$by
  }
  
  if (all.vars) {
    logic_symbol = '&'
  } else {
    logic_symbol = '|'
  }
  
  l_args[['x']] = quote(dt)
  l_args[['.SDcols']] = l[['cols']]
  l_args[['j']] = str2lang(paste0('Reduce("', logic_symbol, '", lapply(.SD, function(x) ', deparse(l[['logic']]), ' ))'))
  
  l_args
}

**Comment by jangorecki** [comment]
Your initial pseudo code chunk seems to be missing closing square bracket. AFAIU it will not address the problem because it can quite easily add an overhead (time and memory) when filters return large portions of data.

**Comment by ColeM1** [comment]
I made edits and will be more careful in the future. My apologies.

This issue is more related to consistency and syntactic sugar than pure performance. For users who want to do ```topn```, it would be great to allow it by group. Unfortunately, the current API does not lead to that:

```
library(data.table)
dt = as.data.table(iris)

dt[order(-Sepal.Length)[1:3]]

#unintended results
dt[order(-Sepal.Length)[1:3], by = Species] 

#largely correct results with column re-ordering
dt[order(-Sepal.Length), .SD[1:3], by = Species]

#largely correct with by reordered based on top group result but more performant
dt[dt[order(-Sepal.Length), .I[1:3], by = Species]$V1]

#proposed
dt[top.n(3, Sepal.Length)]                    ##evals dt[order(-Sepal.Length)[1:min(.N, 3)]]
dt[top.n(3, Sepal.Length, Species)]           ##evals dt[dt[order(-Sepal.Length), .I[1:min(.N, 3)], by = Species]$V1]
dt[top.n(3, Sepal.Length, Species, ties = T)] ##evals dt[dt[, .I[frank(-Sepal.Length, ties.method = 'min') <= 3], by = Species]$V1]
```
For filtering, I agree that for functions that return mostly *TRUE* results that there would be a performance penalty using a ```filter.at``` approach. Still, users are very interested in functional programming due to tidyverse documentation which makes ```dt[filter.at(cols, fx)]``` very attractive as opposed to ```dt[dt[, Reduce('&', lapply(.SD, fx)), .SDcols = cols]]``` or similarly ```dt[filter.at(cols, fx, fct)]``` versus ```dt[dt[, Reduce('&', lapply(.SD, fx)), .SDcols = cols, by = fct]$V1]```. 

In essence, these helper functions would help unite the ```i``` argument with the ```.SDcols``` and ```by``` arguments. My initial implementation of these result in good performance that tries to keep a consistent API. I would be happy to make a PR but again, I understand if this is too much and am content if the issue is closed.

**Comment by jangorecki** [comment]
Aim for consistency in data.table is consistency to base R. That is why we prefer head() rather than new topn() functions. Of course we can consider new helper functions, that is why best probably to fill PR and show how that would help in practice. Please don't invest to much time into it, just single use case well presenting usefulness of your proposal. And don't focus on performance now, but be ready to explain how would efficient implementation be made.

**Comment by sritchie73** [comment]
@ColeMiller1 perhaps more useful is to use/modify the [dtplyr](https://github.com/tidyverse/dtplyr) package?

**Comment by ColeMiller1** [comment]
@sritchie73 I will close as there is no interest in this from the community.
