### ISSUE TITLE
Using Reduce and lapply results in large memory usage spike

### ISSUE THREAD

**Issue by ColeM1** [Rdatatable/data.table#4145]
While working on #4139 , I looked into Hadley's [Subset by Group with data.table](https://stackoverflow.com/questions/16573995/subset-by-group-with-data-table) SO post. There was a massage spike in memory use from 0.3 MB to 16 MB When using ```Reduce('&', lapply(.SD, function(x) x == max(x)))``` as opposed to ```.I[g == max(g)]```. While not providing intended results, the memory use is 0.45 MB if I remove the ```Reduce``` which changes ```j``` from ```'lapply(.SD, function(x) x == max(x))'``` to ```'list(..FUN1(g))'``` according to verbose.

I understand more overhead with the additional calls to ```Reduce``` and ```lapply``` but I do not follow why memory use would see substantial increases. 

```
library(data.table)
set.seed(123L)
dt <- data.table(id = as.character(sample(300:1300, 21699, TRUE)),
                 g = sample(162, 21699, TRUE))

bench::mark(
  dt[dt[, .I[g == max(g)], by = id]$V1],
  dt[dt[, .I[Reduce('&', lapply(.SD, function (x) x == max(x)))], by = id, .SDcols = 'g']$V1],
  dt[, .SD[g == max(g)], by = id],
  dt[dt[, lapply(.SD, function (x) x == max(x)), by = id, .SDcols = 'g']$V1]
)

# A tibble: 3 x 13
  expression                                                                                      min  median `itr/sec` mem_alloc
  <bch:expr>                                                                                 <bch:tm> <bch:t>     <dbl> <bch:byt>
1 dt[dt[, .I[g == max(g)], by = id]$V1]                                                        9.21ms    10ms     96.7       0.23MB
2 dt[dt[, .I[Reduce("&", lapply(.SD, function(x) x == max(x)))], by = id, .SDcols = "g"]$V1]  47.38ms  55.6ms     18.0       16MB
3 dt[, .SD[g == max(g)], by = id]                                                            241.84ms 249.1ms      4.05    16.3MB
```
I also checked base without ```by``` - there was no increase in memory usage. 
```
g1 = list(dt[['g']])
bench::mark(
  g1[[1]] == max(g1[[1]]),
  lapply(g1, function(x) x == max(x))[[1]],
  Reduce('&', lapply(g1, function(x) x == max(x)))
)

# A tibble: 3 x 13
  expression                                          min median `itr/sec` mem_alloc `gc/sec`
  <bch:expr>                                       <bch:> <bch:>     <dbl> <bch:byt>    <dbl>
1 g1[[1]] == max(g1[[1]])                          60.6us   62us    14529.    84.8KB     18.2
2 lapply(g1, function(x) x == max(x))[[1]]         66.1us 67.5us    13675.    84.8KB     14.7
3 Reduce("&", lapply(g1, function(x) x == max(x))) 74.3us   76us    12765.    84.8KB     14.7
```

Output of sessionInfo()
<details>
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.9 dplyr_0.8.3      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        pillar_1.4.2      compiler_3.6.1    prettyunits_1.0.2 remotes_2.1.0    
 [6] tools_3.6.1       zeallot_0.1.0     testthat_2.2.1    digest_0.6.20     pkgbuild_1.0.5   
[11] pkgload_1.0.2     memoise_1.1.0     tibble_2.1.3      pkgconfig_2.0.2   rlang_0.4.0      
[16] bench_1.0.3       cli_1.1.0         rstudioapi_0.10   withr_2.1.2       vctrs_0.2.0      
[21] desc_1.2.0        fs_1.3.1          devtools_2.1.0    rprojroot_1.3-2   tidyselect_0.2.5 
[26] glue_1.3.1        R6_2.4.0          processx_3.4.1    fansi_0.4.0       profmem_0.5.0    
[31] sessioninfo_1.1.1 callr_3.4.0       purrr_0.3.2       magrittr_1.5      backports_1.1.4  
[36] ps_1.3.0          usethis_1.5.1     assertthat_0.2.1  utf8_1.1.4        crayon_1.3.4
</details>

**Comment by jangorecki** [comment]
`bench` package is using unreliable way of measuring memory. Please repeat your benchmark using reliable methods and post results.

**Comment by ColeM1** [comment]
I tried using ```Rprofmem``` and saw similar results - 16.8MB with ```Reduce(..., lapply(...))``` vs. 0.4 MB with ```lapply(...)```. The log with ```Reduce``` includes a lot of shallow copies.  

Also, please feel free to point me out to a preferred memory profiling tool - I'm not sure this way is ideal either.

```
library(data.table)
set.seed(123L)
dt <- data.table(id = as.character(sample(300:1300, 21699, TRUE)),
                 g = sample(162, 21699, TRUE))

#warmup - the first run of data.table seems to take extra memory
dt[, .I[Reduce('&', lapply(.SD, function (x) x == max(x)))], by = id, .SDcols = 'g']$V1

Rprofmem('noreduce.log')
dt[, .I[Reduce('&', lapply(.SD, function (x) x == max(x)))], by = id, .SDcols = 'g']$V1
Rprofmem(NULL)
noReduce <- readLines("noreduce.log")

Rprofmem('wReduce.log')
dt[, lapply(.SD, function (x) x == max(x)), by = id, .SDcols = 'g']$V1
Rprofmem(NULL)
wReduce = readLines("wReduce.log")

Rprofmem('onlyI.log')
dt[, .I[g == max(g)], by = id]$V1 
Rprofmem(NULL)
onlyI = readLines("onlyI.log")

sum(as.integer(sapply(strsplit(noReduce, ':'), `[`, 1)), na.rm = T)
##[1] 16719816
sum(as.integer(sapply(strsplit(wReduce, ':'), `[`, 1)), na.rm = T)
##[1] 423984
sum(as.integer(sapply(strsplit(onlyI, ':'), `[`, 1)), na.rm = T)
##[1] 205336
```

**Comment by ColeM1** [comment]
If it helps, without ```optimize = 0L```, the shallow copies always happen.
```
options(datatable.optimize = 0L)
Rprofmem('noReduce_noOptim.log')
dt[, lapply(.SD, function (x) x == max(x)), by = id, .SDcols = 'g']$V1
Rprofmem(NULL)
noReduce_noOptim = readLines("noReduce_noOptim.log")

options(datatable.optimize = 1L)
sum(as.integer(sapply(strsplit(noReduce, ':'), `[`, 1)), na.rm = T)
##[1] 427424
sum(as.integer(sapply(strsplit(noReduce_noOptim, ':'), `[`, 1)), na.rm = T)
##[1] 16939680

**Comment by jangorecki** [comment]
Rprofmem suffers from the same problem as bench package, see it's repository issues for problem description.

**Comment by ColeM1** [comment]
I do not follow. ```Rprofmem``` is from ```utils``` - I checked Henrik's github and could not find the problem. 

Still, there seem to be performance issues when using ```.SD``` and ```by``` together - especially as the number of columns increases. For 22,000 rows, 22 columns, and 1,228 IDs (similar to ```plyr::baseball```), it takes 1.8 seconds to do ```dt[, .SD[g == max(g)], by = id]``` versus 0.29 seconds for 2 columns. 

Still, I think this is expected behavior when optimizations cannot occur. See https://github.com/Rdatatable/data.table/blob/d52b0d8df6d854aac3c148ae46482a19e2c1ab08/R/data.table.R#L1507

This testing was on 1.12.8.

```
library(data.table)
set.seed(123L)
small_dt <- data.table(id = as.character(sample(1228, 21699, TRUE)),
                 g = sample(162, 21699, TRUE))

large_dt <- data.table(id = as.character(sample(1228, 21699, TRUE)),
                       g = sample(162, 21699, TRUE),
                       replicate(20, rep(1L, 21699)))

system.time(large_dt[, .SD[g == max(g)], by = id])
##   user  system elapsed 
##   1.11    0.94    1.80 
system.time(small_dt[, .SD[g == max(g)], by = id])
##   user  system elapsed 
##  0.29    0.03    0.28 
system.time(large_dt[large_dt[, .I[g == max(g)], by = id]$V1])
##   user  system elapsed 
##   0.03    0.00    0.02 


system.time(large_dt[, .SD[1L:2L], by = id])
##  user  system elapsed 
##   1.15    0.95    2.08 
system.time(large_dt[, head(.SD, 2), by = id])
##   user  system elapsed 
##   0.36    0.02    0.36 
system.time(small_dt[, .SD[1L:2L], by = id])
##   user  system elapsed 
##  0.28    0.06    0.35 
system.time(small_dt[, head(.SD, 2), by = id])
##   user  system elapsed 
##  0.05    0.00    0.06 
system.time(large_dt[large_dt[, .I[1L:2L], by = id]$V1])
##   user  system elapsed 
##   0.02    0.02    0.04 
```
