### ISSUE TITLE
"not in" operator `%!in%`

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4152]
FR to propose a not-in operator
```r
`%!in%` = function(x, y) !(x%in%y)
```
Motivation is to have a single call that we could optimise. Otherwise we have to investigate unevaluated expression tree more deeply (and in a much more complex way) to know when user is doing a not-in operation.
Pseudo code in R C api
```r
CAR(x %!in% 1:10)
#`%!in%`
CAR(! x %in% 1:10)
#`!`
```

**Comment by jangorecki** [comment]
Actually we still need to handle `!` because `!x%in%` was just one example, another example is `!x%like%y`. It is definitely not robust to ask users to rewrite their code from base R style to our functions so we can optimize them. And it turns out it was not that difficult to handle `!`. I will leave this issue open because there are upvotes, so it seems such helper function might be useful anyway.

**Comment by jaapwalhout** [comment]
Such a function is certainly useful! I would prefer to write it as `%nin%` though, which is easier to type (imho)

**Comment by legendre6891** [comment]
I would really welcome the addition of `%notin%`, even if unoptimized; it is quite handy to have.

**Comment by mczekanski1** [comment]
I've been working on this and I'm wondering if someone can explain something for me. How does this function call get evaluated?
`chmatch("a", c(), 5)`
It returns 5, but as far as I can tell it dispatches to `chmatchMain` and it should return a vector `allocVector(chin?LGLSXP:INTSXP, xlen)` of length 0 which is `logical(0)` but somehow it returns 5 from R. There's no reference to the `nomatch` parameter before it returns.
