### ISSUE TITLE
"patterns" warning in R check

### ISSUE THREAD

**Issue by ccshao** [Rdatatable/data.table#4171]
In data.table 1.12.8, I used `melt` with patterns  `melt(indata, id.vars = "XX", measure.vars = patterns("^T_"))`

In the R check, it reports warning:

> no visible global function definition for ‘patterns’

patterns could be seen from` ?patterns`, but `patterns` itself shows 

> Error: object 'patterns' not found

> 
> > sessionInfo()
> R version 3.6.2 (2019-12-12)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Linux Mint 19.2
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] data.table_1.12.8
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.6.2 tools_3.6.2   
> 
> 
>

**Comment by MichaelChirico** [comment]
`patterns` is not an exported function from `data.table`; we are using non-standard evaluation to do `melt`+`patterns` calls.

@jangorecki this isn't mentioned in the NSE symbols section of the importing vignette; also, by contrast with `:=`, `patterns` isn't exported as a dummy version. Shall we address this?
https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html

@ccshao for now, you can add this to your package:

```
patterns = function(...) NULL
```

And `R CMD check` should pass + `melt` still work as intended.

**Comment by ccshao** [comment]
Thanks for the quick help!
