### ISSUE TITLE
errors when installing on windows

### ISSUE THREAD

**Issue by LeoWelter** [Rdatatable/data.table#4175]
I'm experiencing an issue with installing 1.12.8 on Windows 10, R version 3.6.2
(Rtools installed)

**Error: package or namespace load failed for ‘data.table’:
 .onLoad failed in loadNamespace() for 'data.table', details:
  call: NULL
  error: invalid version specification ‘before 1.12.0’**

Any idea how to get this going?
I've also tried to install on my Linux installation which went flawless

> install.packages("data.table")
Installing package into ‘C:/Users/xxxxxxx/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/data.table_1.12.8.zip'
Content type 'application/zip' length 2277646 bytes (2.2 MB)
downloaded 2.2 MB

package ‘data.table’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\xxxxxxx\AppData\Local\Temp\RtmpmYutAn\downloaded_packages
> library(data.table)
Error: package or namespace load failed for ‘data.table’:
 .onLoad failed in loadNamespace() for 'data.table', details:
  call: NULL
  error: invalid version specification ‘before 1.12.0’

**Comment by jangorecki** [comment]
Could you try to restart your machine, one just single R session, ideally not any IDE, and retry installation? It is known issue on Windows that DLL are being blocked by another R process and cannot be updated.

**Comment by LeoWelter** [comment]
Thanks, I could solve the issue by installing and compiling with admin
rights



Op do 16 jan. 2020 om 14:09 schreef Jan Gorecki <notifications@github.com>
