### ISSUE TITLE
internal error when specifying .SDcols

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4231]
There is an issue in scope in which `.SDcols` is evaluated.
AFAIU there is no need to evaluate it in [`x`'s scope](https://github.com/Rdatatable/data.table/commit/b0ecc0e56850a543cef874106fcda11f7fafc6ac#diff-650e4a11ed4384f8e560a6ebfff4ff53R897), and that is likely caused an issue here.
```r
data.table(V1=-1L, V2=-2L, V3=-3L)[,.SD,.SDcols=-V2:-V1]
#Error in `[.data.table`(data.table(V1 = -1L, V2 = -2L, V3 = -3L), , .SD,  : 
#  Internal error: xcolAns does not pass checks: 1121
```
```r
as.data.table(as.list(1:2))[, .SD,.SDcols=(-1L)]
#Error in colnamesInt(x, cols, check_dups = FALSE) : 
#  argument specifying columns specify non existing column(s): cols[1]=-1
as.data.table(as.list(1:3))[, .SD,.SDcols=(-1L)]
#Error in `[.data.table`(as.data.table(as.list(1:3)), , .SD, .SDcols = (-1L)) : 
#  Internal error: xcolAns does not pass checks: 2211,2
```

**Comment by ColeMiller1** [comment]
For the first one, I think we should make users do ```-(V2:V1)``` - we probably could have special error handling to be helpful.

For the second one, I assume that if ```abs(number)``` is less than ```nrow(DT)```, we should return ```setdiff(seq_len(nrow(DT)), abs(number))``` Is that how you see it?

**Comment by jangorecki** [comment]
I think you mean `ncol` rather than `nrow`, yes it make sense
