### ISSUE TITLE
Vignette for programmatic data.table (eval, get, etc)

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4247]
Copying over a request for a vignette that touches on building programmatic data.table workflows:

https://twitter.com/El_Grund/status/1197189888334061570?s=20

we certainly mention this all the time in the issue tracker but I couldn't think of a comprehensive resource we offer (I know there is some stuff in the FAQ).

**Comment by ColeMiller1** [comment]
Somewhat related SO post:

https://stackoverflow.com/questions/60263274/should-i-use-mget-or-with-false-to-select-columns-of-a-data-table

**Comment by Plebejer** [comment]
Also related: https://stackoverflow.com/questions/60279756/r-data-table-how-to-pass-everything-possible-to-by-in-a-function

**Comment by Plebejer** [comment]
Here is a very rough idea on what could be included in this vignette:

### How can I pass arguments to ... in order to keep the interface identical to data.table directly
#### ... i ...
#### ... j ...
#### ... by/keyby ...

### How do create dynamic variable names in `j`?
#### By reference
#### anything else (such as aggregation)

**Comment by dracodoc** [comment]
This will be greatly helpful. Though I wish there will be more consistent syntax available first. Otherwise the vignette may just be too complex and user's options are still limited/not good enough.

**Comment by jangorecki** [comment]
@dracodoc note that there is PR for that, and vignette is here https://github.com/Rdatatable/data.table/blob/09e0499b55545ae15a83d4e9a0536b632f85a892/vignettes/datatable-programming.Rmd. You are welcome to provide feedback/review.

**Comment by dracodoc** [comment]
@jangorecki Thanks for the link! I read it briefly, it's more about the proposed new syntax with substitute2 and related usage. I was thinking the vignette would also include existing usage patterns (like `()` `..`) for completeness.

I was thinking to wait others to write on that, but if nobody has done it yet, I can try to summary what I learned, maybe as a draft to receive more comments and improvements.

**Comment by jangorecki** [comment]
In PR there is my comment about `..`.
