### ISSUE TITLE
grep on names(.SD) fails when with=FALSE

### ISSUE THREAD

**Issue by chinsoon12** [Rdatatable/data.table#4265]
I was using `grep` to subset columns from a file that I have read in. It seems like `grep` on `names(.SD)` is does not work when `with=FALSE`

MWE:

    data.table(A=1, B=2)[, grep("A", names(.SD), value=TRUE), with=FALSE]
    #Null data.table (0 rows and 0 cols)

Expecting:

    data.table(A=1, B=1)[, grep("A", c("A","B"), value=TRUE), with=FALSE]
    #   A
    #1: 1

I have searched for `grep with FALSE` in the issues and could not find any similar issue. And I could not install dev version in current env and test.

sessionInfo:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252    LC_MONETARY=English_Singapore.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Singapore.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.8

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1  
```

**Comment by ColeMiller1** [comment]
PR #4163 is somewhat related although it only works on the lhs of an ```:=``` assignment call. However, using ```patterns``` would make your MRE work:
```
data.table(A=1, B=2)[, .SD, .SDcols = patterns("A")]

       A
   <num>
1:     1
```
Does this address your use case or are there other times that ```names(.SD)``` would be helpful on the RHS of an evaluation?

**Comment by MichaelChirico** [comment]
when with=FALSE, j is evaluated in the parent frame; .SD is defined as NULL there. Cole thankfully pointed to the more canonical approach for grep column filtering with .SDcols=patterns.

could you let us know which documentation you consulted when exploring your issue? in that way we can try to improve self help for this issue going forward

**Comment by chinsoon12** [comment]
Thanks @ColeMiller1  and @MichaelChirico using .SDcols=patterns works great. 

I should have read the with argument carefully. 

If I remember there might be a few issues caused by a null .SD, maybe it might be good to warn when .SD is null as I can’t think of a use case where .SD is null. And I believe .SD was initialized to null to suppress a build warning?

**Comment by MichaelChirico** [comment]
@chinsoon12 thanks for filing the issue! You've been an active contributor to `[data.table]` tag on SO -- if you found a behavior confusing / unintuitive & couldn't solve your way out of it, most likely it means we need to improve documentation.

Now that I'm at a computer I can confirm:

```
grep('A', names(NULL), value = TRUE)
# character(0)
```

So `grep` has this strange edge case behavior.

`.SD` is exported as `NULL` -- you can try `library(data.table); .SD` or `data.table::.SD` to confirm. Yes this is to suppress the build warning as `R CMD check` looks over the code & sees us using `.SD` left & right but not ever writing `.SD =` so we "trick" it.

Beyond documentation, we might consider searching `j` for special symbols when `with=FALSE` & warning? But I would prefer to attack this as a documentation issue.

**Comment by ColeMiller1** [comment]
I always wonder if we should just add attributes to ```.SD``` itself. Then it wouldn't be so magical and we wouldn't have to rely on NSE to determine if ```names(.SD)``` was used. After ```sdvars``` is established we could assign names in the ```j``` eval

**Comment by chinsoon12** [comment]
@MichaelChirico, I agree that as long as base R functions can handle NULL (or anything that is assigned to .SD), it will cause some confusion when `with=FALSE` is used.

> if you found a behavior confusing / unintuitive & couldn't solve your way out of it, most likely it means we need to improve documentation.
Honestly, its all in `?data.table` under `with` and `.SDcols` arguments . To myself, its RTM. no excuses.

**Comment by jangorecki** [comment]
I agree that `with=FALSE` should disable any features like `.SD` and behaves like an data.frame api in `j`
