### ISSUE TITLE
Expressions in non-equi join

### ISSUE THREAD

**Issue by kdkavanagh** [Rdatatable/data.table#4283]
It would be great if non-equi join by statements accepted expressions rather than solely column names.  Would eliminate the need to create temporary columns manually ahead of the join.  E.g

```
#Join values in A which are a maximum of 5000 units of time before the observation in B
a[b, on=.(x.Timestamp < i.Timestamp, x.Timestamp+5000 > i.Timestamp)]
```

**Comment by MichaelChirico** [comment]
Thanks for the request! IINM that's https://github.com/Rdatatable/data.table/issues/1639

please feel free to add support on that main issue, or reopen this if I'm in error in assigning the duplicate label
