### ISSUE TITLE
Tests fail when using R compiled with Intel compiler

### ISSUE THREAD

**Issue by jackjackk** [Rdatatable/data.table#4312]
We are having issues when using `data.table` with R compiled with the Intel compiler. Indeed the tests fail when running `test.data.table`.
I reported the steps used for installation, the output from `test.data.table` and the output of `sessionInfo` in a [dedicated gist](https://gist.github.com/jackjackk/416b2370425f5d760f326c7f844c3fae). 

It might just be a matter of wrong compiler flags, but would need help to experiment in this direction.
In general, any help would be highly appreciated.

Thanks!

**Comment by jangorecki** [comment]
Thank you @jackjackk for reporting.
Could you please try on latest devel and see if it is still an issue? and if so try setting `R_DATATABLE_NUM_THREADS=1` env var to see if it makes any difference?

**Comment by jackjackk** [comment]
@jangorecki thanks a lot for following up. Please find a before/after report for the [old version vs latest master datatable version](https://gistpreview.github.io/?416b2370425f5d760f326c7f844c3fae/zold2new.html) and [18 threads vs 1 thread](https://gistpreview.github.io/?416b2370425f5d760f326c7f844c3fae/z18threads2onethread.html) output.
 There are several differences, also due to changes in the setup itself as we updated R to 4.0 (from R3.6) and Intel compiler to 20.1. Please let me know how I can further help in the debugging as it would be great for us to switch to Intel compiled version as soon as possible. Thanks again!

**Comment by jackjackk** [comment]
I've also realized that running multiple times does not give the same number of errors each time, but instead a number in the ~21-24 range.

**Comment by jackjackk** [comment]
Alright, with the support of our IT team we found what could be the culprit. Compiling the devel version with the following `.R/Makevars`:
```
SHLIB_OPENMP_CFLAGS = -qopenmp
CFLAGS=-g -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -Wall -pedantic -std=c++11 -mtune=native -pipe
```
leads to zero tests failed. Thanks again for following up!
