### ISSUE TITLE
The existence of key of DT[i,...] depending on the order of i

### ISSUE THREAD

**Issue by shrektan** [Rdatatable/data.table#4313]
Well, I absolutely understand that if `i` is not sorted, `key` attributes should be `NULL`. However, it sometimes surprises users. 

So I'm wondering: should we keep the `key` attributes even when `i` is sorted?

``` r
library(data.table)
tbl = data.table(KEY = c("A", "B"), VALUE = 100, key = "KEY")
key(tbl[J(c("A", "B"))])
#> [1] "KEY"
key(tbl[J(c("B", "A"))])
#> NULL
```

<sup>Created on 2020-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jangorecki** [comment]
I think it was added as a feature few years back.

**Comment by jangorecki** [comment]
Looking at #477 I would assume we will like to keep that. It doesn't hurt and adds quite a lot possibilities for later optimizations.
