### ISSUE TITLE
do.call + dump.frames performance issue

### ISSUE THREAD

**Issue by kdkavanagh** [Rdatatable/data.table#4319]
I've noticed that if I pass a data.table to a function via do.call, and inside that function I call dump.frames (e.g in the event of an error), the time to complete the dump is exponentially higher than calling the function direct (i.e not with do.call).  

I'm not sure if this is a data.table issue or a base R issue, but figured this is a good place to start.  Example:

```
require(data.table)
testFrame = data.table(
  a=stringi::stri_rand_strings(600000, 2, pattern = "[A-Za-z0-9]"),
  b=stringi::stri_rand_strings(600000, 17, pattern = "[A-Za-z0-9]"))

stopper=function(a) { if(!is.null(a)) dump.frames()}
start_time <- Sys.time()
stopper(testFrame)
end_time <- Sys.time()
print(end_time - start_time) #Time difference of 0.000575304 secs
if(!exists('last.dump')) {
  stop("Failed to generate normal dump")
}

start_time <- Sys.time()
do.call(stopper, list(testFrame))
end_time <- Sys.time()
print(end_time - start_time) 
#Time difference of 21.00366 secs.  This seems to increase in some proportion to the dimension of the table

```

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.5 (Maipo)

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.4.2
LAPACK: /usr/lib64/liblapack.so.3.4.2

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] bit64_0.9-7       bit_1.1-15.2      data.table_1.12.8

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    stringi_1.4.5
```

**Comment by kdkavanagh** [comment]
After realizing this also occurs with data.frames, I found some old posts from Hadley which indicate that do.call performs terribly with large arguments.  I resorted to assembling the call myself from the list of args -> string -> eval(parse()).  Not great, but much much faster now.

**Comment by jangorecki** [comment]
Yes, do.call has an overhead. I still advise to not use eval parse, but rather construct a call, using as.call, substitute, etc., then you can have the functionality of do.call but with no overhead it brings. It should be also faster than eval parse because there is no parsing step involved, altough it is still very tiny part of the timing.
So your code
```r
do.call(stopper, list(testFrame))
```
can be turned into
```r
qc = as.call(list(as.name("stopper"), as.name("testFrame")))
print(qc)
eval(qc)
```
