### ISSUE TITLE
fread segfaults due to colClasses arg named vector

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#4337]
This used to work until `1.12..2` but segfaults on all versions since then AFAICT.

```r
# Rv3.6.1 windows
require(data.table) # 1.12.8, 1.12.6 or 1.12.4
col_classes <- c("character", rep("integer", 2L), "character", "numeric", "integer", "numeric",
                         "integer", "integer", "character", "logical", "integer", "character", "integer",
                         "character", "character", "logical")
setattr(col_classes, "names", paste0("V", 1:17))
bla <- "98Y|12345|6789|foo|123.000|19|123.817|197|5|A| |1|B|10|LP12|ZZ01|LE10|LE12|01|C|\n"
fread(bla) # works fine
#     V1    V2   V3  V4  V5 V6      V7  V8 V9 V10 V11 V12 V13 V14  V15  V16  V17  V18 V19 V20 V21
# 1: 98Y 12345 6789 foo 123 19 123.817 197  5   A  NA   1   B  10 LP12 ZZ01 LE10 LE12   1   C  NA
fread(bla, colClasses=col_classes) # segfaults, should return entire table with col classes
                                                      # set correctly for first 17 cols
```

if `col_classes` was unnamed, things worked fine.

I can't test it on devel at the moment, but I don't see this issue handled in NEWS for 1.12.9 under BUG FIXES.

**Comment by jangorecki** [comment]
I am able to reproduce on the recent devel and linux

**Comment by arunsrinivasan** [comment]
Update: just to be clear, when column names are provided for col classes, irrespective of the number of columns, it should return all columns with classes for those columns provided to `colClasses` correctly. So, there should be no error here, as I state as to what the behaviour should be in the original post.  (Removed now. See history for old post if needed).

**Comment by arunsrinivasan** [comment]
More update. This doesn't seem to be a 'colClasses' issue.. It seems to be parsing a column as 'logical' type.

```r
fread(bla, select=17L, colClasses=c(V17="character")) # segfault
fread(bla, select=17L, colClasses=c(V17="logical")) # segfault
```

**Comment by OfekShilon** [comment]
Checking on the latest dev repo, the repro code doesn't segfault and gives an informative message:
```
Warning message:
In fread(bla, colClasses = col_classes) :
  Attempt to override column 17 of inherent type 'string' down to 'bool8' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.
```
So I think this can be closed.
