### ISSUE TITLE
Is using setDT on a temporary asking for trouble?

### ISSUE THREAD

**Issue by ggrothendieck** [Rdatatable/data.table#4344]
This seems to work but I was wondering if this is asking for trouble.  Could R garbage collect it not realizing it had been assigned?

```
library(data.table)
DT <- setDT(BOD + 1)
```

The actual application is that I am converting a zoo object to data.table:

```
library(data.table)
library(zoo)
z <- zoo(BOD)
DT <- setDT(fortify.zoo(z))
```

I realize that I could use `as.data.table` in place of `setDT` but the above is faster.

**Comment by shrektan** [comment]
No, it will not. R is smart enough to know that the temporary vector belongs to a variable and will not collect it in GC.

 So don't worry.

You can test it by call `gc()` explicitly~ Hope this erase your concern 😄
