### ISSUE TITLE
Recycle singletons for fwrite?

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4368]
Saw this:

https://twitter.com/ficaryl/status/1248286097861378048

```
setDT(DT)[, fwrite(.SD, paste0("user", unique(userid),".csv")), by = userid, .SDcols=names(DT) ]
```

was struck by `.SDcols=names(DT)`, IINM it's to force the `.BY` columns to be included in the output. This of course makes this unavailable on chained `data.table`s; the following would look relatively straightforward:

```
setDT(DT)[, fwrite(c(.BY, .SD), paste0("user", .BY$userid, ".csv")), by = userid]
```

(this works as `DT[ , c(.BY, .SD), by = userid]`)

But fails currently because `fwrite` won't recycle the singletons.

The workaround is to do the recycling manually:

```
DT[ , by = userid, {
  out = c(.BY, .SD)
  # or for (i in seq_along(.BY)) {...}
  out[[1L]] = rep(out[[1L]], .N)
  fwrite(out, ...)
}]
```

**Comment by jangorecki** [comment]
In short, you are asking for a list method for fwrite function?

**Comment by MichaelChirico** [comment]
`fwrite` already works on lists:

```
data.table::fwrite(list(1:10, 10:1))
```

what doesn't work is:

```
data.table::fwrite(list(1, 1:10))
```

**Comment by jangorecki** [comment]
Agree that would nicely simplifies the use case from twitter, but on the other hand might introduce confusion. I would rather change `unique(userid)` into `userid[1L]`.

> IINM it's to force the .BY columns to be included in the output. This of course makes this unavailable on chained data.tables

Solution proposed by you is not generic enough to address chaining gap here, it will address this case only.

The case above `c(.BY, .SD)` would be addressed by https://github.com/Rdatatable/data.table/issues/661 (if having `.BY` as data.table not only when `i` is a list).

We either should stay as is now, incorporate your suggestion, or provide a good replacement for `c` to handle recycling. Which naturally should be `cbind`.

**Comment by MichaelChirico** [comment]
> not generic enough to address chaining gap here

not sure I follow why, but anyway, agree `cbind` + `.BY`-as-`data.table` would be an equally nice solution.
