### ISSUE TITLE
Any plans for out-of-memory data formats?

### ISSUE THREAD

**Issue by hope-data-science** [Rdatatable/data.table#4384]
In many times, the memory of the computer might not be large enough, and for each computation we don't really have to read all the data into RAM to carry out the computation. Could we possibly parse a csv instead of reading it into a RAM. I've seen this design in [fst](https://github.com/fstpackage/fst), with a new class named `fst_table`, and modify it to be used in [tidyfst](https://hope-data-science.github.io/tidyfst/articles/example5_fst.html). I've tested the performance as well in another work (<https://hope-data-science.github.io/tidyft/articles/Introduction.html>).

Any plans to make it work for csv in data.table? I think this might be even more memory efficient and time saving with the powerful `fread` and `fwrite`.  

Thanks.

**Comment by MichaelChirico** [comment]
I think this is covered in https://github.com/Rdatatable/data.table/issues/1336 https://github.com/Rdatatable/data.table/issues/1721 and https://github.com/Rdatatable/data.table/issues/3104 ; please re-open if there's something novel not mentioned in those
