### ISSUE TITLE
'setDT(unclass(x))' creates a shallow copy

### ISSUE THREAD

**Issue by hongyuanjia** [Rdatatable/data.table#4392]
I know this is not a common use of `setDT`, but I learned this trick from https://github.com/Rdatatable/data.table/issues/3477#issuecomment-477310740. However, I encountered a wired behavior. Please see the example below.

Modifying columns in `x` will also change the same columns in `y`, which is desirable. But adding new columns in `x` will not adding the same columns in `y`, which confused me. So in this case, `y <- setDT(unclass(x)[cols])` seems to only keep `cols` "linked". And `y` is not just an alias of `x`.

Is this behavior by design? Thanks.

``` r
x <- data.table(a = 1L, b = "b")

y <- setDT(unclass(x)[c("a", "b")])

# change column "a" and add a new column "c"
set(x, 1L, c("a", "c"), list(2L, "c"))[]
#>    a b c
#> 1: 2 b c

# "a" in y get changed but "c" is not added
y
#>    a b
#> 1: 2 b

sessionInfo()
#> R version 3.6.2 (2019-12-12)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Arch Linux
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/libblas.so.3.9.0
#> LAPACK: /usr/lib/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] data.table_1.12.8 nvimcom_0.9-86   
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.6.2  magrittr_1.5    htmltools_0.4.0 tools_3.6.2    
#>  [5] yaml_2.2.0      Rcpp_1.0.4.6    stringi_1.4.6   rmarkdown_2.1  
#>  [9] highr_0.8       knitr_1.28      stringr_1.4.0   xfun_0.12      
#> [13] digest_0.6.25   rlang_0.4.5     evaluate_0.14
```

**Comment by jangorecki** [comment]
AFAIK it is by design. We use that fact internally in multiple places. It can be especially useful when you want to add new columns only, and not edit existing onces, then you want to make a shallow (not deep) copy of  your data. Internally we do `dt2 = data.table:::shallow(dt)[, new_col := ...]` for that, then we can independently add columns to dt2 and dt2, even having same name but different values, because those tables share only a subset of columns. Internal `shallow` function takes an argument to specify those columns.

**Comment by hongyuanjia** [comment]
Thanks for the explanation.
