### ISSUE TITLE
'mult' controls multiple matches in `i`, not `x`

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4394]
`mult` manual entry now states

> When `i` is a `list` (or `data.frame` or `data.table`) and _multiple_ rows in `x` match to the row in `i`, `mult` controls which are returned: `"all"` (default), `"first"` or `"last"`.

but it is actually the opposite

```r
data.table(a=1L)[data.table(a=c(1L,1L),b=1:2), on="a", mult="first"]
#   a b
#1: 1 1
#2: 1 2
data.table(a=c(1L,1L),b=1:2)[data.table(a=1L), on="a", mult="first"]
#   a b
#1: 1 1
```

**Comment by chinsoon12** [comment]
actually it seems correct to me. when there are multiple rows in x for each i, mult will control which row of x to be returned.

**Comment by jangorecki** [comment]
@chinsoon12 thanks for extra eyes on that. I seems to be doing to much of swapping x with i recently :)

**Comment by chinsoon12** [comment]
cheers! looking for to `forder` to return grouping and `env` for NSE

**Comment by jangorecki** [comment]
it was precisely a results of continuous swapping `x` and `i` in #4370 :)
