### ISSUE TITLE
which=NA inconsistent with ?data.table

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4411]
Was answering this question:

https://stackoverflow.com/q/61554066/3576984

and trying to mirror `base` behavior with `which`, i.e., for `which` to return `NA` elements of `i` as `NA`:

```
DT = data.table(
  A = c(NA, 3, 5, 0, 1, 2),
  B = c("foo", "foo", "foo", "bar", "bar", "bar")
)
DT[A  > 1, which=TRUE]
# [1] 2 3 6
```

whereas

```
DT[ , .I[A > 1]]
# [1] NA  2  3  6
```

We can use e.g. `na.omit` to mirror the `data.table` behavior like `.I[na.omit(A > 1)]` but doing the reverse seems awkward:

```
idx = DT[is.na(A) | A > 1, which = TRUE]
is.na(idx) <- is.na(DT[idx]$A)
idx
# [1] NA  2  3  6
```

I thought this in `?data.table` might be helpful:

> ### which

> `TRUE` returns the row numbers of `x` that `i` matches to. If `NA`, returns the row numbers of `i` that have no match in `x`. By default `FALSE` and the rows in `x` that match are returned.

Sort of reads like `DT[A > 1, which = NA]` should return `1L`, but it errors instead:

```
DT[A > 1, which = NA]
```

> Error in `if (which) return(if (is.null(irows)) seq_len(nrow(x)) else irows)` : 

> missing value where `TRUE`/`FALSE` needed

Should we change the documentation, or is this a bug?

**Comment by MichaelChirico** [comment]
Just found https://github.com/Rdatatable/data.table/issues/4303 again, will check if #4342 closes this as well, I'm not sure at a glance if it's a duplicate

**Comment by MichaelChirico** [comment]
#4342 does _not_ close this issue as of f9e21dd3e46fa193e43dca1edfd5920d8cb3d414

**Comment by jangorecki** [comment]
I don't think we should be handling that specially.
```r
DT[A  > 1, which=TRUE]
```
is subsetting a data.table, whereas
```
DT[ , .I[A > 1]]
# [1] NA  2  3  6
```
is subsetting an integer vector.
and this difference for subsetting data.table is covered in FAQ.

And the error you got from `which=NA` seems to be a bug...
