### ISSUE TITLE
Proposed dtplyr hex logo

### ISSUE THREAD

**Issue by hadley** [Rdatatable/data.table#4420]
We have been working on a hex logo for the dtplyr package:

![dtplyr_2020_05_01](https://user-images.githubusercontent.com/4196/80976395-07718d00-8de9-11ea-906c-03e9afd4f699.png)

I wanted to check if anyone in the data.table community had any concerns about the logo, given that it's obviously inspired by the data.table logo.

**Comment by mattdowle** [comment]
Thanks, Hadley. No concerns here: feel free.

**Comment by hadley** [comment]
Thanks!
