### ISSUE TITLE
Should grouping by a factor always return a row for every level of the factor (no dropping missing levels)?

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4421]
[was very surprised not to find an issue on this already, I must have searched wrong]

This question identifies a discrepancy between `base` (e.g. `tapply`) and `data.table` -- grouping `by` a factor in `data.table` will only return rows for the levels present in the data:

```
DT <- data.table(
    grp1 = c(1L, 1L, 1L, 3L), 
    grp2 = factor(c("A","B","A","B"), levels = c('A', 'B', 'C')), 
    v = c(1,2,3,4)
)
DT[ , mean(v), by = grp2]
#    grp2 V1
# 1:    A  2
# 2:    B  3
```

vs. `base`:

```
with(DT, tapply(v, grp2, mean))
#  A  B  C 
#  2  3 NA 
```

This further applies if levels are present in one group, but not another:

```
# DT[ , mean(v), by = .(grp1, grp2)]
#    grp1 grp2 V1
# 1:    1    A  2
# 2:    1    B  2
# 3:    3    B  4
```

vs `base`

```
with(DT, tapply(v, list(grp1, grp2), mean))
#    A B  C
# 1  2 2 NA
# 3 NA 4 NA
```

There's nothing about this in `?data.table`; I added `breaking-change` since some code likely relies on this behavior.

**Comment by jangorecki** [comment]
I prefer to keep current behavior, it is simply more useful

**Comment by Henrik-P** [comment]
I have also stumbled over this one... At that time, I ended up on this issue: [Grouping could include unused factor levels while computing j (like `tapply` does)](https://github.com/Rdatatable/data.table/issues/562)

**Comment by jangorecki** [comment]
I think we could close as a duplicate
