### ISSUE TITLE
why data.table does not use Rcpp?

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#4450]
Since most parts of data.table are written in C, why it does not use Rcpp to interface R? Does using Rcpp hurt its performance?

**Comment by philippechataignon** [comment]
data.table was here before Rcpp and C is a good language for data.table core. But I agree that some extensions are easily written with Rcpp. See https://github.com/philippechataignon/dtutils.

**Comment by jangorecki** [comment]
These are only my guesses, proper answer can be only provided by Matt who would be the only person to make decision about any change in that matter.

- Rcpp was not yet existing when data.table started to use C compiled code inside the package, back in 2008
- Rcpp is an extra dependency, and we avoid dependencies
- We(?) feel comfortable in C (personally me, much more comfortable than in C++)
- C is more portable

I will consider your question as answered, and close the issue. Matt, if will have something to add, can do it anytime later. Stale issues in our repository won't be locked, and can always be re-opened in future if needed.
