### ISSUE TITLE
as.data.table.data.frame keep.rownames & key

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4468]
This works fine:

```
as.data.table(mtcars, keep.rownames = TRUE, key = 'rn')
```

But it's a bit arcane to know that `rn` is going to be the rownames' name. More readable might be:

```
as.data.table(mtcars, keep.rownames = 'model', key = 'model'
```

But that's an error:

```
Error in setkeyv(ans, key) : some columns are not in the data.table: model
```

Haven't looked yet but it must be setkeyv is applied before the setnames.

Note that this approach already works for `setDT`:

```
setDT(DT, keep.rownames = 'model', key = 'model')
```

**Comment by moodymudskipper** [comment]
It might add confusion, but thinking out loud maybe `key = TRUE` could use the row names as a key by default, or the first column if no row names (the id column will usually be first). This way your first call could be abbreviated to `as.data.table(mtcars, key = TRUE)`

**Comment by MichaelChirico** [comment]
Hmm but when I read `as.data.table(mtcars, key=TRUE)`, actually I think of the answer being `setkey(as.data.tabel(mtcars))`; `setkey` keys on all columns by default.

**Comment by moodymudskipper** [comment]
Right, there could also be special values for `key` but that might be too much potential confusion to spare a few characters.
