### ISSUE TITLE
[R-Forge #733] Add split method which gives warning not to split

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#448]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=733&group_id=240&atid=978)

Proposed contents to warn users not to use split :

split.data.table = function(...){stop("Use 'by' argument instead of split() on data.table. See ?'[.data.table'")}

The reason is it copies the whole data.table to a split up format. That uses much more memory than 'by' which does each subset one by one.

**Comment by jangorecki** [comment]
Lets put that warning into ?split.data.table

**Comment by jangorecki** [comment]
closed with 5f7a435
