### ISSUE TITLE
Error with dec=',', sep = 'auto' but detected as ','

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4483]
Possibly related: #2750

```
fread('A,B,C\n1,+,4\n2,-,5\n3,-,6\n', dec=',', verbose=TRUE)
```

> Stopped early on line 2. Expected 3 fields but found 3. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<1,+,4>>

with `dec=','`, `+,4` reads as `+.4`.

But we've already detected `sep=','`... not sure the correct behavior for manually specified `dec=','`.

In any case the error message is strange "Expected 3 fields but found 3"

**Comment by st-pasha** [comment]
When `dec=','` and `sep=','`, we should not attempt to use the float parser at all, unless the field is quoted.

**Comment by MichaelChirico** [comment]
> rather insane...

Actually found a file on some Spanish government website for which that's the correct parsing 😂  but yes, indeed insane as a general thing.

This issue is slightly different. We already block `sep==dec`:

https://github.com/Rdatatable/data.table/blob/ff3e7d42bb4e4114c8b17fc4e74fc2a5bb4dbe45/src/fread.c#L1180

Here what happens is, since `sep` detection comes first, right now we aren't enforcing `sep != dec` when `sep` starts out as `'auto'` but ends up as `','`.

Maybe the best option is to change here:

https://github.com/Rdatatable/data.table/blob/ff3e7d42bb4e4114c8b17fc4e74fc2a5bb4dbe45/src/fread.c#L1455

to 

```
char seps[] = dec == ',' ? "|;\t " : ",|;\t ";
```

i.e. if user has manually specified `dec=','`, prevent `sep='auto'` from finding `sep=','`
