### ISSUE TITLE
Keyed join with empty data.table and roll='nearest' segfaults

### ISSUE THREAD

**Issue by tlapak** [Rdatatable/data.table#4499]
Somewhat related to #4060 in appearance but crashes on all versions of R. Different mechanism, similar appearance. Found this while working on amending #4272. I'll submit a fix soon (hopefully). Should I put it in with #4272 or submit a separate PR? These are all related in that they are triggered by passing zero length `icols/xcols` to `Cbmerge`. 

I'm not a hundred percent on what this _should_ do, but I'd suggest to have it behave the same way for all values of `roll`.

```R
DT = data.table(A="a", key="A")
DT[data.table(), roll = 'nearest']  # Will segfault
# Proposed return Value == DT[0]:
# Empty data.table (0 rows and 1 cols): A
```

**Comment by jangorecki** [comment]
It should raise error that there is no column to join to.
