### ISSUE TITLE
Will it be possible to have a consistent way to refer column name by variable?

### ISSUE THREAD

**Issue by dracodoc** [Rdatatable/data.table#4511]
I have been using data.table extensively for quite several years, and love the expression power and speed. The major hurdle that bumped me from time to time is to refer column name by variable, i.e. if I have a column name saved in a variable, how to refer it in data.table. I use this mainly to create a function to process 

- We used to have `with` but no longer using it. It also have its own limits (sometimes I would like to mix using column name directly and column names in variable.
- In `j` we can use `..col_name` but I didn't find a similar syntax for `i`. For example I may want to select a subset in i, update the column in j based on their original values. This is a common operation if we were using column name directly (`dt[x <3, x := x +1]`), but very hard to duplicate in a function with column name saved in variable.
`set` function doesn't seem to be able to handle this. `get` seemed cannot be used in certain cases, like `dt[get(col_name) < 3, col_name := str_c(get(col_name))]`

So far I have to use `dt[[col_name]]`, but it will become very awkward if I want to combine i, j or even grouping.

I knew this is probably is not a easy task, that's why there have been so many different workarounds and never a consistent solution. However I think I still need to ask, is it possible to have a consistent way to deal with this?

From syntax aspect, I think the way like `..` is limited because it cannot handle complex expression well. A delimiter that mark the variable boundary clearly will be much easier to deal with, like how glue package use expression in a string `"this is a string with {variable or expression}"`. So something like `{variable/expression}` will be easy to understand and use. Of course `{}` itself may not work, but something similar will be just fine.

**Comment by MichaelChirico** [comment]
Hi @dracodoc  have you seen #4304 and #2655?

**Comment by dracodoc** [comment]
@MichaelChirico , Thanks a lot for the link. I searched issues before posting, but didn't find these two. I'll read them and post there.
