### ISSUE TITLE
R_DATATABLE_NUM_THREADS env var alone ignored

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4514]
Shouldn't we default num_proc_percent to 100% when num_threads is provided?
```r
R_DATATABLE_NUM_THREADS=2 Rscript -e 'data.table::getDTthreads(T)'
#  omp_get_num_procs()            2
#  R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
#  R_DATATABLE_NUM_THREADS        2
#  omp_get_thread_limit()         2147483647
#  omp_get_max_threads()          2
#  OMP_THREAD_LIMIT               unset
#  OMP_NUM_THREADS                unset
#  RestoreAfterFork               true
#  data.table is using 1 threads. See ?setDTthreads.
#[1] 1
```
https://github.com/Rdatatable/data.table/blob/d3bd408ab3c2f46365b9e0d94a508d7874034d01/src/openmp-utils.c#L44

**Comment by MichaelChirico** [comment]
Hmm I think it's slightly different. Because actually `R_DATATABLE_NUM_THREADS` is too high:

```
ans = imin(ans, getIntEnv("R_DATATABLE_NUM_THREADS", INT_MAX));
```

the `min` here is `imax(ans*perc/100, 1)`, i.e. 1.

For me I have `omp_get_num_procs()=8` so your code runs as expected:

```
R_DATATABLE_NUM_THREADS=2 Rscript -e 'data.table::getDTthreads(T)'
#   omp_get_num_procs()            8
#   R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
#   R_DATATABLE_NUM_THREADS        2
#   omp_get_thread_limit()         2147483647
#   omp_get_max_threads()          8
#   OMP_THREAD_LIMIT               unset
#   OMP_NUM_THREADS                unset
#   RestoreAfterFork               true
#   data.table is using 2 threads. See ?setDTthreads.
# [1] 2
```

**Comment by MichaelChirico** [comment]
I guess your point is if `NUM_THREADS` is set and `NUM_PROCS_PERCENT` is not, `NUM_THREADS` the default of `NUM_PROCS_PERCENT` becomes 100...

**Comment by jangorecki** [comment]
try using 5

**Comment by jangorecki** [comment]
maybe that is actually good, so it is more flexible to cap threads to min of two provided. Then we just need to mention that in manual.

**Comment by mattdowle** [comment]
On the principle of the first-thought-best, let's go with Jan's first thought and change it. When you use setDTthreads() at the R prompt it works at you expect, so fixing the environment variable is just making its behaviour consistent with setDTthreads.
