### ISSUE TITLE
data.table-intro reference to coercion to factors out of date

### ISSUE THREAD

**Issue by romunov** [Rdatatable/data.table#4515]
Line stating conversion to factors as default for data.frames no longer holds (mentioned [here](https://github.com/Rdatatable/data.table/blob/master/vignettes/datatable-intro.Rmd#L91)). I'd be happy to make a PR that removes this.

**Comment by MichaelChirico** [comment]
That would be great, thanks! Keep in mind that, since we only depend on R 3.1.0, we can't guarantee every reader of the vignette would be on >= 4.0.0, so the wording should reflect that.
