### ISSUE TITLE
Question) setorder and setcolorder

### ISSUE THREAD

**Issue by matthewgson** [Rdatatable/data.table#4535]
`setorder` accepts variable names as arguments and `setorderv` accepts character vector as its arguments. 
I thought `setcolorder` function would behave similarly, but it rather accepts character vector as its argument. (and there is no `setcolorderv`) Is there a reason for this difference?

**Comment by jangorecki** [comment]
AFAIK there is no specific reason for that. Those functions (like generally all others in data.table) were appearing over the course of years (DT is already 14 years old). Inconsistencies in the interface like this are caused exactly by that. As long as we don't introduce breaking change, we should be fine about aligning those interfaces. I don't think it is a straightforward in `setcolorder` case. If you really need it, please provide an idea for backward compatible change, I will re-open issue then.
