### ISSUE TITLE
all.equal.data.table uses relative difference on POSIXct column (should be absolute)

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4543]
```
DT1 = data.table(t = .POSIXct(1590973200, tz='UTC'))
DT2 = data.table(t = .POSIXct(1590974413, tz='UTC'))
all.equal(DT1, DT2)
# [1] "Column 't': Mean relative difference: 7.624264e-07"
```

vs `base`:

```
DT1 = data.frame(t = .POSIXct(1590973200, tz='UTC'))
DT2 = data.frame(t = .POSIXct(1590974413, tz='UTC'))
all.equal(DT1, DT2)
# [1] "Component “t”: Mean absolute difference: 1213"
```

For `POSIXct` column, relative difference is meaningless since it's somewhat arbitrarily relative to the 0 time of UTC epoch.

**Comment by jangorecki** [comment]
I would expect it to fall back to a base R all.equal in such a simple comparison

**Comment by MichaelChirico** [comment]
found the culprit

```
cols.r = all.equal(unclass(x), unclass(y), tolerance = tolerance, 
          ..., check.attributes = check.attributes)
```

**Comment by MichaelChirico** [comment]
Introduced by @mattdowle here:

https://github.com/Rdatatable/data.table/commit/23bd1669f54f8026e7b10d3af150f7358248c4ec

Seems the goal was to break from `all.equal.data.frame` which considers `1L` different from `structure(1L, class='foo')` _even when `check.attributes=FALSE`_.

I agree with that, but I think we should still dispatch to `all.equal` methods if they're there...
