### ISSUE TITLE
Restoring row order of a data.table for use in side-effect free functions

### ISSUE THREAD

**Issue by myoung3** [Rdatatable/data.table#4575]
I've been recently writing several functions that use data.tables as arguments.  In general when writing functions like these, my preference is to not copy() the data.table inside the function body argument because these functions I'm writing are typically intended to deal with large datasets and I'd like to avoid unnecessary copying.  However, in cases where I need to set the key of the data.table internal to the function body, I'd like to ensure that the key is restored on exit of that function (either when the function returns a value or errors out). This is because I'd like these functions to be free of side-effects

Here is a working approach to deal with this problem:

```

#x is a data.table

savestate <- function(x){
  original_colnames <- copy(names(x))
  rowindex_colname <- "rowindex"
  while(rowindex_colname %in% names(x)) rowindex_colname <- paste0("i.",rowindex_colname)
  x[,eval(rowindex_colname):=1:.N]

  k <- key(x)
  list(key=k,rowindex_colname=rowindex_colname,original_colnames=original_colnames)
}



setstate <- function(x,state){

  required_columns <- c(state$original_colnames, state$rowindex_colname)
  stopifnot(all(required_columns %in% names(x)))

  setorderv(x,state$rowindex_colname)
  setattr(x, name="sorted",value=state$key)
  #explicitly remove index for clarity,
  #although this would happen anyway in the next line:
  x[, eval(state$rowindex_colname):=NULL]
  #remove all new columns:
  newcols <- setdiff(names(x),state$original_colnames)
  for(i in 1:length(newcols)){
    set(x,j=newcols[i],value=NULL)
  }
  invisible(x)
}

f1 <- function(x,newkeyv){
  stopifnot(is.data.table(x))
  state <- savestate(x)
  tryCatch(expr = {
    #do some code which may alter the key of x
    setkeyv(x,newkeyv)
    ##add a temporary column
    x[, temp:=NA]
    ##ooops but the function broke and now the key of x is altered
    c(1,2)%*%c(1,2,3) #generate an error
    out <- 3

  },
  error=function(e){
    setstate(x,state)
    stop(e)
  })

  setstate(x,state)
  out
}

x <- data.table(id=c(1,1,2,2,2),
                id2=c(5,4,3,2,1),
                value=c(9,2,4,2,8),
                row_n=c(1,2,3,4,5)
                )
setkey(x,id)
x_original <- copy(x)
f1(x,newkeyv="id2")
all.equal(x,x_original)

```

But there  are still some unappealing characteristics of this approach:

- First, due to the fact that the (state-specific) rowindex column gets removed when setstate is called, setstate() it can only ever be called once for a given state object. But deleting the index column is necessary to return the data.table to its original state (ie the state in which another column was added).
- Second, it creates a column in the data.table (rowindex) with all the implied complications of a column being added unexpectedly which could lead to conflicts with other column names.

The above issues could probably be solved by using indexing in C, but I'm not familiar enough with that code to provide a detailed solution.  I'm curious what other people think about the fundamental idea of these functions.

Some design considerations (obviously up for discussion):

savestate(x):
 - would return a small metadata object containing the key of x, columns of x, and a pointer to row order of x (all at at the time when savestate(x) was called)
 - savestate also modifies x invisibly in a way would subsequently allow the row order to be restored to what it was when savestate was called.

setstate(x,state)
- should restore not just the key of x, but also the original row order of x (i.e., this distinction is important because keys or the key could start as NULL)
- columns added since savestate was called are removed as in the above example (or this is an option)
- I guess columns should be put back in the order they were (not in the example above but this point follows from the rest)

setstate(x,state) would fail (return error) if:
- columns in the key definition stored in state are no longer in x or have been renamed
- any other (non-key) columns are missing or renamed that were present when savestate was called (or this is an option)

The intervalaverage function in a package I'm developing (https://github.com/kaufman-lab/intervalaverage) is the motivation for this discussion. I'm taking two data.tables, doing an foverlaps (which requires keying) internal to the function, then returning a new data.table that is an average of values in x over intervals in y.  I can use my solution above to deal with this problem, but in general I think it would be good if there were native data.table tools to facilitate writing true functions (ie free of side-effects) that still make use of data.table's efficient pass-by-reference semantics.

**Comment by jangorecki** [comment]
- Soon, once #4340 will be merge, not for 1.12.10 but probably next release, it will be easier to revert order. You will not need to create extra column but just `setorderv(DT, neworder = old_order_int_var)`
- I would simplify `rowindex_colname` and remove `while` loop. Take some technical name like `__mypkg_rowindex`, test if name exists in input, if it does then raise error asking to not use that particular name.
- avoid `setattr(x, name="sorted",value=state$key)`. It is risky, especially in the way you use it (between different function calls). `setkeyv` should be very fast for already sorted input, it detects that and skips the work it normally do. It may not be worth to take the risk for a very little overhead.
- when using `set` you can pass `j` argument as a vector, not need to loop and call it for each column separately.
- instead of `tryCatch` and error exception handling you can use `on.exit()`
- does `foverlaps` requires keyed data.tables? I see `by.x` and `by.y` arguments in [?foverlaps](https://rdatatable.gitlab.io/data.table/reference/foverlaps.html)

----

After having #2888, #4340, #4386, #3447 it would be pretty straightforward
```r
f = function(x, new.k) {
  old.k = key(x)
  setkeyv(x, new.k) # would retain existing key as index #2888
  old.o = forderv(x, by=old.k) # does not compute order but return it from existing index #4386
  on.exit(setkeyv(x, old.o))
  # do foverlaps or anything else
}
```

**Comment by MichaelChirico** [comment]
on the last point: #1355
