### ISSUE TITLE
complete a data.table on column combinations

### ISSUE THREAD

**Issue by mayer79** [Rdatatable/data.table#4583]
From time to time, I need to add/pad artificial rows for missing combinations of columns, i.e. patient/treatment combinations. This can be done by a combination of `dcast` followed by `melt` or, alternatively by `tidyr::complete`. 

Ideally, such functionality would be available directly in `data.table`.

Here is what I mean (example and naive implementation):

`#` [`Minimal reproducible example`]
```
# Naive implementation and example
complete_dt <- function(data, by, fill = list()) {
  grid <- as.data.table(expand.grid(data[, ..by]))
  full <- merge(grid, data, by = names(grid), all.x = TRUE)  
  repl_vars <- intersect(names(fill), names(full))
  
  for (v in repl_vars) {
    full[is.na(get(v)), (v) := fill[[v]]]
  }
  full
}

X <- as.data.table(
  cbind(
    x = c(1, 3, 4), 
    y = c("A", "B", "B"),
    z = 1:3
))

complete_dt(data = X, by = c("x", "y"))

# Output
   x y    z
1: 1 A    1
2: 1 B <NA>
3: 1 B <NA>
4: 3 A <NA>
5: 3 B    2
6: 3 B    2
7: 4 A <NA>
8: 4 B    3
9: 4 B    3

out <- complete_dt(data = X, by = c("x", "y"), fill = c(z = 0))
out

# Output
   x y z
1: 1 A 1
2: 1 B 0
3: 1 B 0
4: 3 A 0
5: 3 B 2
6: 3 B 2
7: 4 A 0
8: 4 B 3
9: 4 B 3
```

**Comment by MichaelChirico** [comment]
I believe you want `CJ` (see `?CJ`); `fill` can be accomplished with `setnafill` (see `?setnafill`).

**Comment by mayer79** [comment]
I think you are right, thanks for the great hint!

**Comment by Henrik-P** [comment]
@mayer79 You may find this post useful: [data.table equivalent of tidyr::complete()](https://stackoverflow.com/questions/43483497/data-table-equivalent-of-tidyrcomplete). Cheers.

**Comment by mayer79** [comment]
@Henrik-P : Very helpful, here the test:

```
library(data.table)
library(tidyr)

X <- as.data.table(
  cbind(
    x = c(1, 3, 4), 
    y = c("A", "B", "B"),
    z = 1:3
))

complete(X, x, y)

vars <- c("x","y")
X[do.call(CJ, c(mget(vars), unique = TRUE)), on = vars]
```
