### ISSUE TITLE
Question regarding fcase

### ISSUE THREAD

**Issue by statquant** [Rdatatable/data.table#4593]
Hello, I have a question regarding `fcase`, I understand that I can use it like 
```
x = c(1,2,3,4)
fcase(x > 2, pmin(x, 3), default = 10)
[1] 10 10  3  3
```

But most of the time what I really would like is a vector default 
```
x = c(1,2,3,4)
fcase(x > 2, pmin(x, 3), default = x)
[1] 10 10  3  4
```
the above does not work. 
I am thinking about things like 
`fcase(x > y, x*y, default = x/y)`

I guess I must be missing something here, maybe the intended use is not to do what I expect, can someone enlight me ?
Many thanks

**Comment by MichaelChirico** [comment]
Thanks for the issue, I believe it's the same as here:

https://github.com/Rdatatable/data.table/issues/4258

Please re-open if I missed something
