### ISSUE TITLE
Non-Equi Joins with by = .EACHI produce odd results for i columns in Rcpp

### ISSUE THREAD

**Issue by ColeMiller1** [Rdatatable/data.table#4599]
In relation to #4598 , I attempted to solve the issue with ```Rcpp```. Here is the basic operation that the OP of the other issue was performing:

``` r
library(data.table)
set.seed(123L)
uid <- 1L:3L
x <- CJ(id = uid, xstart = seq(1L, 20L, by = 7L))
x[, `:=`(xend = xstart + 6L,
         xend2 = xstart + 6L,
         xstart2 = xstart,
         value = rnorm(.N))]

y <- CJ(id = uid, ystart = seq(1L, 19L, by = 3L))
y[ , `:=`(yend = ystart + 9L,
          yend2 = ystart + 9L,
          ystart2 = ystart)]

out1 <- x[y,
          list(avg_value = weighted.mean(x=value,w=pmin(xend2,yend2)-pmax(xstart2,ystart2)+1L)),
          by=.EACHI,
          on=c("id","xend>=ystart","xstart<=yend"),
          nomatch=NULL]
```
While working the Rcpp function, the columns from ```y``` provided weird values when any elements outside of the first element was selected in Rcpp. The ```x``` columns were always correct. The Rcpp function is under the fold.

Here were my attempts and I have included one groupings odd ```y``` values - note that if we make a copy and chain together with the same ```by``` columns, we get the expected results. 
```r
x[y,
          list(avg_value = custom_fx(value, xstart2, xend2, ystart2, yend2)),
          by=.EACHI,
          on=c("id","xend>=ystart","xstart<=yend"),
          nomatch=NULL]

##Ends 
## xend[0] = 7; yend[i] = 10
##Starts 
## xstart[0] = 1; ystart[i] = 1
##Ends 
## xend[1] = 14; yend[i] = 442
##Starts 
## xstart[1] = 8; ystart[i] = 442

## Actual Result: -0.224673  ###### BAD!!!!!


## chaining it works
out3 <- x[y, 
          on=c("id","xend>=ystart","xstart<=yend"),
          nomatch=NULL,
          allow.cartesian = TRUE][, list(avg_value = custom_fx(value, xstart2, xend2, ystart2, yend2)),
                                  by = c("id","xend","xstart")]

##Ends 
## xend[0] = 7; yend[i] = 10
##Starts 
 ##xstart[0] = 1; ystart[i] = 1
##Ends 
## xend[1] = 14; yend[i] = 10
##Starts 
## xstart[1] = 8; ystart[i] = 1

## Actual Result: -0.461386 ### RIGHT!!!
```

I assume this is related on how memory is recycled - I believe there was a recent-ish discussion about spline function providing odd results (#4298). However, unlike that one (or the discussions in #507), ```copy``` does not correct the issue. 

<details>
  <summary>Rcpp Code</summary>
  
```c++
#include <Rcpp.h>
using namespace Rcpp;
  
// [[Rcpp::export]]
double custom_fx(NumericVector vals,
                        IntegerVector xstart,
                        IntegerVector xend,
                        IntegerVector ystart,
                        IntegerVector yend) {
    
    int n = vals.size();
    
    int wt_sum = 0;
    double val_sum = 0;

    for (int i = 0; i < n; i++) {
        int wt = 1;
        
        Rcout << "Ends \n xend[" << i << "] = " << xend[i] << "; yend[i] = " << yend[i] << "\n";
        int xtmp = xend[i]; int ytmp = yend[i];
        if (xtmp > ytmp) {
            wt += ytmp;
        } else {
            wt += xtmp;
        }
        
        Rcout << "Starts \n xstart[" << i << "] = " << xstart[i] << "; ystart[i] = " << ystart[i] << "\n";
        xtmp = xstart[i]; ytmp = ystart[i];
        if (xtmp > ytmp) {
            wt -= xtmp;
        } else {
            wt -= ytmp;
        }
        
        if (wt == 0) continue;
        val_sum += vals[i] * wt;
        wt_sum += wt;
    }    
    Rcout << "\n Actual Result: " << val_sum / wt_sum << "\n" ;
    return(val_sum / wt_sum);
}
```

</details>

**Comment by jangorecki** [comment]
Does nomatch=NA with skipping NA in j makes any difference?

**Comment by ColeMiller1** [comment]
Using nomatch = NA largely does not not help. The first time I ran it, the first two elements were correct but any group with a 3rd element was off. However, I cannot consistently get those results as now the 2nd element is also off. 

I also tried removing the ```by = .EACHI``` - the results look good when the grouping is removed. It seems like ```by = .EACHI``` makes ```CdoGroups``` believe that there should only be one result for each row of i.  

https://github.com/Rdatatable/data.table/blob/588e0725320eacc5d8fc296ee9da4967cee198af/src/dogroups.c#L128-L131

But the other surprising thing is that when I call a function in ```R``` to do the same thing, there are no issues.

```r
weighted.mean2 = function (val, xstart, xend, ystart, yend) {
  wts = ifelse(xend > yend, yend, xend) - ifelse(xstart > ystart, xstart, ystart)+1L
  return(sum(val * wts) / sum(wts))
}

## works fine
out7 <- x[y,
            list(avg_value = weighted.mean2(value, xstart2, xend2, ystart2, yend2)),
            by=.EACHI, on=c("id","xend>=ystart","xstart<=yend"),nomatch=NULL, verbose = TRUE]

**Comment by ColeMiller1** [comment]
User error on my part. The length of each group of ```.EACHI``` is 1. Therefore, it makes sense that only 1 row is allocated in ```.iSD``` in each grouping. I just could wrap my head around that.

The fix was to adjust the function to treat ```i``` columns as scalars. The regular R functions do that under the hood. For better or for worse, Rcpp seems very lax about throwing errors when subsetting outside of the vector length.

**Comment by ColeMiller1** [comment]
Rcpp is not lax about throwing errors outside of vector length. You can use either ```[``` or ```(``` on vectors. From [Section 8.2](https://teuder.github.io/rcpp4everyone_en/080_vector.html) is an important distinction:

>[] operator ignores out of bound access, while () operator throws an exception index_out_of_bounds.

So, ```[``` can be faster because it does not check the length. At the same time, user-error can cause issue with ```[``` like what I originally did.
