### ISSUE TITLE
Tests failing due to setting datatable.print.keys option

### ISSUE THREAD

**Issue by vlulla** [Rdatatable/data.table#4633]
I set the `options(datatable.print.keys=TRUE)` in my `.Rprofile`. This causes tests `1465.18` and `1872.09` to fail. Both of these  test failures can be prevented by _explicitly_ setting this option to `FALSE` before running these tests.

**Comment by OfekShilon** [comment]
Fixed by https://github.com/Rdatatable/data.table/commit/22b51c510a614e9095b7cd6de57cf87aae0d8914
