### ISSUE TITLE
fread segfault

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#4644]
I'm using the latest data.table release and the following code causes segfault:

```r
library(data.table)
md <- fread("~/data/20200724.sample.log.gz",
  col.names = c("localtime", "event", "exchange_id", "instrument_id", "exchange_time",
    "pre_close", "last_price", "volume", "turnover",
    "bid_price", "ask_price", "bid_volume", "ask_volume"
  ),
  colClasses = c(
    "character", "factor", "factor", "character", "character",
    "double", "double", "double", "double",
    "double", "double", "integer", "integer"
  )
)
```

```
 *** caught segfault ***
address 0x5c, cause 'memory not mapped'
```

The gzipped data is attached. 

[20200724.sample.log.gz](https://github.com/Rdatatable/data.table/files/4977827/20200724.sample.log.gz)

Both original file or gz causes segfault. If I only read some top rows (e.g. `nrows = 100`) it won't crash.

If I don't use `colClasses`, it won't cause segfault either.

**Comment by mattdowle** [comment]
Thanks. Confirmed.

**Comment by hongyuanjia** [comment]
Hi @mattdowle. May I ask is there any update on this thread? Most of [my CI](https://travis-ci.com/github/hongyuanjia/eplusr/jobs/365998732) failed due to this bug. I would like to know any workaround before I submit a new version to CRAN. Many thanks!

**Comment by mattdowle** [comment]
@hongyuanjia Sorry for the impact. Working on the valgrind issue now, then this segfault, then the [[ by group slow down, then will release. Hopefully end of week but no promises.  I'm not aware of a workaround in the meantime other than going back to v1.12.8.

**Comment by st-pasha** [comment]
MRE is
```
data.table:::fread("~/Downloads/20200724.sample.log.gz", colClasses=c(V13="integer"), verbose=TRUE)
```

**Comment by st-pasha** [comment]
or even this:
```
data.table:::fread("0.0\n", colClasses="integer")
```

**Comment by hongyuanjia** [comment]
@mattdowle Thanks for letting me know the timeline. Just take your time. I will keep track on this issue.
