### ISSUE TITLE
bit64 update on CRAN breaks data.table

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#4654]
No sooner have we started to pass tests on CRAN, are they broken again.
data.table updated to v1.13.0 on 24 July.  Then bit64 updated to 4.0.2 on 30th July.
I wrote to Kurt and Jens:
> Looked further and I suppose it's because CRAN policy states that the reverse dependencies are returned by `tools::package_dependencies(reverse = TRUE)`. The default for its `which=` does not include Suggests. data.table suggests bit64 which is why I assume data.table as a revdep of bit64 was not tested by bit64, nor CRAN's revdep testing upon submission of bit64. When I run revdep checks I set `which='all'` but that's not in CRAN policy to do so.  I think that's a failing of policy because Suggests are needed for packages to pass their tests; that's what the Suggests category is there for amongst other things.
Kurt - do you think CRAN policy could be updated to include Suggests in revdep testing?

**Comment by ColeMiller1** [comment]
@mattdowle there seem to be two issues that led to the break.

1. ```bit``` 4.0.0 included a new ```copy()``` function which masked ```data.table::copy``` and resulted in our test scripts to fail.
2. ```bit64``` 4.0.0 included a new ```all.equal.integer64``` method that is more accurate - specifically, it no longer provides incorrect results with respect to ```NA``` values. This fix uncovered two unit tests which had wrong expected results.

#4656 passes on our CI builds. Hopefully that will help get us back to passing.

**Comment by mattdowle** [comment]
@ColeMiller1  Thanks for investigating. I had correspondence on email with Jens too.  He's kindly suggested to renamed his copy, which would be better for users since data.table::copy is long standing.

---

Jens,

I've looked at the two tests you highlighted: 2127.26 and 2127.27.
They were passing before because in previous version of bit64 :

> all.equal( as.integer64(3), as.integer64(4) )
[1] TRUE
> all.equal( as.integer64(3), as.integer64(NA) )
[1] TRUE

That seems to be a bug that you've fixed in the new version. New version result :

> all.equal( as.integer64(3), as.integer64(4) )
[1] "Mean relative difference: 0.3333333"
> all.equal( as.integer64(3), as.integer64(NA) )
[1] "'is.NA' value mismatch: 1 in current 0 in target"

I'm surprised this is classified as a 'new feature' in bit64 v4.0.0.
All the NEWS file says is: NEW FEATURES

    o new method all.equal.integer64
      (contributed by Leonardo Silvestri)

But all.equal wasn't working before for integer64, and adding the missing method makes it work. A little more detail in the news item would be good please?

> @Matt can you confirm that? Do you want me to submit those changes?

Ok confirmed. If you can submit the renamed copy functions to CRAN, that is much appreciated. Then I will update these two tests in data.table and submit. As you say, they are incorrectly specified, not spotted before because all.equal wasn't working for integer64.

Best, Matt
