### ISSUE TITLE
Issue coercing data.frame to data.table via as.data.table when POSIXlt variables are present

### ISSUE THREAD

**Issue by Feakster** [Rdatatable/data.table#4684]
Hi,

I've recently noticed that the `as.data.table()` function has issues and inconsistencies in coercing `data.frame` objects to `data.table` objects.

Take the following toy example; a `list` containing two elements: `x` a `POSIXct` object of length 10, `y` a `POSIXlt` object of length 10:

```r
l <- list(
  x = as.POSIXct("2020-01-01") + 1:10,
  y = as.POSIXlt(as.POSIXct("2020-01-01") + 1:10)
)
```

Running the following produces a coercion warning (which seems to be the intended behaviour), and results in a `data.table` object containing two columns of class `POSIXct`:

```r
dt <- as.data.table(l)
```
```text
Warning message:
In as.data.table.list(l) :
  POSIXlt column type detected and converted to POSIXct. We do not recommend use of POSIXlt at all because it uses 40 bytes to store one date.
```
```r
dt
```
```text
                      x                   y
 1: 2020-01-01 00:00:01 2020-01-01 00:00:01
 2: 2020-01-01 00:00:02 2020-01-01 00:00:02
 3: 2020-01-01 00:00:03 2020-01-01 00:00:03
 4: 2020-01-01 00:00:04 2020-01-01 00:00:04
 5: 2020-01-01 00:00:05 2020-01-01 00:00:05
 6: 2020-01-01 00:00:06 2020-01-01 00:00:06
 7: 2020-01-01 00:00:07 2020-01-01 00:00:07
 8: 2020-01-01 00:00:08 2020-01-01 00:00:08
 9: 2020-01-01 00:00:09 2020-01-01 00:00:09
10: 2020-01-01 00:00:10 2020-01-01 00:00:10
```
```r
sapply(dt, class)
```
```text
     x         y        
[1,] "POSIXct" "POSIXct"
[2,] "POSIXt"  "POSIXt"
```

If you first coerce the `list` to a `data.frame` via `as.data.frame()`, no coercion warning is issued when using `as.data.table()` to coerce the `data.frame` to a `data.table`, despite the `POSIXlt` variable being coerced to `POSIXct`:

```r
dat <- as.data.frame(l)
dt <- as.data.table(dat)
dt
```
```text
                      x                   y
 1: 2020-01-01 00:00:01 2020-01-01 00:00:01
 2: 2020-01-01 00:00:02 2020-01-01 00:00:02
 3: 2020-01-01 00:00:03 2020-01-01 00:00:03
 4: 2020-01-01 00:00:04 2020-01-01 00:00:04
 5: 2020-01-01 00:00:05 2020-01-01 00:00:05
 6: 2020-01-01 00:00:06 2020-01-01 00:00:06
 7: 2020-01-01 00:00:07 2020-01-01 00:00:07
 8: 2020-01-01 00:00:08 2020-01-01 00:00:08
 9: 2020-01-01 00:00:09 2020-01-01 00:00:09
10: 2020-01-01 00:00:10 2020-01-01 00:00:10
```
```r
sapply(dt, class)
```
```text
     x         y        
[1,] "POSIXct" "POSIXct"
[2,] "POSIXt"  "POSIXt"
```

However, if you first coerce the `list` to a `data.frame` via the `list2DF()` function, the output of running `as.data.table()` on the resulting `data.frame` is malformed. Additionally, the `POSIXlt` variable is not coerced and `POSIXct`:

```r
dat <- list2DF(l)
dt <- as.data.table(dat)
dt
```
```text
                      x            y
 1: 2020-01-01 00:00:01 <POSIXlt[1]>
 2: 2020-01-01 00:00:02 <POSIXlt[1]>
 3: 2020-01-01 00:00:03 <POSIXlt[1]>
 4: 2020-01-01 00:00:04 <POSIXlt[1]>
 5: 2020-01-01 00:00:05 <POSIXlt[1]>
 6: 2020-01-01 00:00:06 <POSIXlt[1]>
 7: 2020-01-01 00:00:07 <POSIXlt[1]>
 8: 2020-01-01 00:00:08 <POSIXlt[1]>
 9: 2020-01-01 00:00:09 <POSIXlt[1]>
10: 2020-01-01 00:00:10 <POSIXlt[1]>
```
```r
sapply(dt, class)
```
```text
     x         y        
[1,] "POSIXct" "POSIXlt"
[2,] "POSIXt"  "POSIXt" 
```

Kind regards,

Ben

Output from `sessionInfo()`:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.10.so
LAPACK: /usr/lib/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.13.0

loaded via a namespace (and not attached):
 [1] bit_4.0.4       compiler_4.0.2  magrittr_1.5    ellipsis_0.3.1  tools_4.0.2     parallel_4.0.2  pillar_1.4.6   
 [8] rstudioapi_0.11 tibble_3.0.3    crayon_1.3.4    bit64_4.0.2     vctrs_0.3.2     lifecycle_0.2.0 pkgconfig_2.0.3
[15] rlang_0.4.7 
```

**Comment by eddelbuettel** [comment]
Your analysis is incorrect.  The resulting `data.table` is valid, it simply consists a so-called list column per your wishes and despite the warnings:

```r
R> l <- list(
+   x = as.POSIXct("2020-01-01") + 1:10,
+   y = as.POSIXlt(as.POSIXct("2020-01-01") + 1:10)
+ )
R> ldt <- as.data.table(list2DF(l))
R> ldt[,.(y)]
                      y
 1: 2020-01-01 00:00:01
 2: 2020-01-01 00:00:02
 3: 2020-01-01 00:00:03
 4: 2020-01-01 00:00:04
 5: 2020-01-01 00:00:05
 6: 2020-01-01 00:00:06
 7: 2020-01-01 00:00:07
 8: 2020-01-01 00:00:08
 9: 2020-01-01 00:00:09
10: 2020-01-01 00:00:10
Warning message:
In as.data.table.list(jval, .named = NULL) :
  POSIXlt column type detected and converted to POSIXct. We do not recommend use of POSIXlt at all 
 because it uses 40 bytes to store one date.
R> 
```

More importantly, see this

```r
R> ## but note
R> data.table( list2DF(l) )
Error in setDT(ans, key = key) : 
  Column 2 is of POSIXlt type. Please convert it to POSIXct using as.POSIXct and run setDT again. We do not recommend use of POSIXlt at all because it uses 40 bytes to store one date.
R> 
```

So the error, if any, is on the user side for insisting to storea POSIXt resolution timepoint (or, rather, a vector of them) as POSIXlt when POSIXct is both _equivalent_ and _more efficient_.

**Comment by Feakster** [comment]
I get this when running the following command on my last example:

```r
dt[1,2]
```
```text
dt[1,2]
Error in `[.data.table`(dt, 1, 2) : 
  Column 2 ['y'] is length 11 but column 1 is length 10; malformed data.table.
```

**Comment by Feakster** [comment]
Also, wouldn't it be better to always show the `POSIXlt` coercion warnings upon coercion, as opposed to upon coercion for lists and upon printing for data frames?

**Comment by eddelbuettel** [comment]
Please stop machine gunning the ticket and read up on _list columns_.  It still works once you realize the data type created _per your instructions_:

```r
R> ldt[, `:=`(d=as.IDate(y),t=as.ITime(as.POSIXct(y)))][]
                      x            y          d        t
 1: 2020-01-01 00:00:01 <POSIXlt[1]> 2020-01-01 00:00:01
 2: 2020-01-01 00:00:02 <POSIXlt[1]> 2020-01-01 00:00:02
 3: 2020-01-01 00:00:03 <POSIXlt[1]> 2020-01-01 00:00:03
 4: 2020-01-01 00:00:04 <POSIXlt[1]> 2020-01-01 00:00:04
 5: 2020-01-01 00:00:05 <POSIXlt[1]> 2020-01-01 00:00:05
 6: 2020-01-01 00:00:06 <POSIXlt[1]> 2020-01-01 00:00:06
 7: 2020-01-01 00:00:07 <POSIXlt[1]> 2020-01-01 00:00:07
 8: 2020-01-01 00:00:08 <POSIXlt[1]> 2020-01-01 00:00:08
 9: 2020-01-01 00:00:09 <POSIXlt[1]> 2020-01-01 00:00:09
10: 2020-01-01 00:00:10 <POSIXlt[1]> 2020-01-01 00:00:10
R> 
```

It short:
- it works
- it is unwieldy
- it warned you on one use with a very clear and well reasoned message
- it errors on another plausible with a direct `data.table(...)` construction

**Comment by Feakster** [comment]
But I wasn't "machine gunning" the ticket. I had posted two comments to your previous one & edited one of those to remove a typo? More of a bolt-action rifle to be honest.

So the issues lies in `list2DF()` producing an object that isn't equivalent to `as.data.frame.list()` when some list elements have an underlying `list` class, such as `POSIXlt`?

**Comment by eddelbuettel** [comment]
> coerces POSIXlt list elements to POSIXct

Which is the reasonable thing to do, and `data.table` urges you do to it but is not as bossy and does not do it behind your back.

**Comment by MichaelChirico** [comment]
Hi @eddelbuettel appreciate your help addressing the issue but please make efforts to be more patient & polite on the `data.table` issue tracker (you can use the Unwatch button to turn off notifications on specific issues) :smiley: 

@Feakster I see you've closed the issue so I take that to mean you are satisfied with the current behavior. As you saw some of the inconsistency appears to be coming from `base` behavior. I suppose we could make more efforts to block `POSIXlt` columns from emerging but our goal is to _strongly discourage_ using `POSIXlt` columns (for the reasons mentioned that they are [1] equivalent to `POSIXct` columns and [2] they use 5x as much storage, though admittedly `base` will often convert these columns to `POSIXlt` in the course of manipulating them), rather than to completely forbid them.

Happy to address any residual concerns
