### ISSUE TITLE
.NROW as a way to access the nrow after subsetting in `i` but before entering a subgroup

### ISSUE THREAD

**Issue by zerweck** [Rdatatable/data.table#4688]
I use data.table a lot to calculate absolute frequencies on the fly with, while also applying a subsetting flag in `i` in the same call.
```R
iris[Sepal.Width<3.7,.N,.(Species)]
```

If i want to change this to relative frequencies within the subset, I need to save the number of rows after filtering as denominator in another call, like this:
```R
nrow_after_filtering <- iris[Sepal.Width<3.7,.N]
iris[Sepal.Width<3.7,.(rel_freq=.N/nrow_after_filtering) ,.(Species)]
```

This gets old after a while when doing this a lot.
It would be great if a symbol `.NROW` similar to `.N` existed, returning the nrow of the data.table after applying `i`, but before going into the subgroup.

The name `.NROW` is probably bad since it would be unclear what the difference to `.N` is, maybe `.NI` or `.NFILT`?

**Comment by ben-schwen** [comment]
Your intended behaviour can simply be achieved by chaining
`iris[Sepal.Width<3.7, .N, .(Species)][, rel_freq := N/sum(N)][] `

**Comment by ColeMiller1** [comment]
Related: #1206 

I like the concept but I always think of @MichaelChirico's comment from the thread as I sometimes wonder if there are too many symbols already, some of which are only triggered via NSE. 

> Not sure when symbol overload kicks in...

Finally, here was my code golf. 

``` r
library(data.table)
as.data.table(iris)[Sepal.Width < 3.7,
                    {
                      N = .N
                      .SD[, .(rel_freq = .N / N), Species]
                    }
]
```

**Comment by zerweck** [comment]
> Related: #1206

As usual when I post something here, a better issue exists already :)

Also thanks to @ben-schwen for the chaining suggestion, I have used in the past but somehow forgot about it again.
