### ISSUE TITLE
Unable to install data.table on MacOS Version10.15.6

### ISSUE THREAD

**Issue by HarshitBagla** [Rdatatable/data.table#4699]
I have tried to follow instructions on https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac but still, I couldn't get it to work with CRAN. The error I am getting is the "installation of package ‘data.table’ had non-zero exit status." Can someone help me with this?

**Comment by jangorecki** [comment]
Error like this is the standard error that doesn't give us any clue what could be the problem.
Could you please provide exact console output when attempting to install data.table in fresh R console, not an IDE, together with your OS version and R session info.
Did you try to apply fixes from different related issues in our repo? Browsing `install` label will list many related ones.
