### ISSUE TITLE
as.data.table(function) and the uninformative error message

### ISSUE THREAD

**Issue by sindribaldur** [Rdatatable/data.table#4704]
```R
> as.data.table(sum)
Error: C stack usage  15923664 is too close to the limit
```

**Comment by ColeMiller1** [comment]
Thanks for the report. However, I cannot reproduce with data.table 1.13.0 / R 4.0.2 / Windows 10:

``` r
library(data.table)
as.data.table(sum)
#> Error in as.data.frame.default(x, ...): cannot coerce class '"function"' to a data.frame
```

Could you provide session info?

**Comment by sindribaldur** [comment]
Oops. Sorry! Can't reproduce either in a fresh session. The output is definitely real but I posted it too quickly without the context which I forgot by now.

**Comment by MichaelChirico** [comment]
please feel free to reopen if you can recreate the issue and provide
session info
