### ISSUE TITLE
stringsAsFactors=.2 is undocumented

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4706]
Follow-up to #2025 -- we mentioned the change in NEWS but nothing in `fread.Rd`

**Comment by markderry** [comment]
I have updated the documentation and I am wondering if the following is still required for a PR?
- A new test
- A news entry

**Comment by MichaelChirico** [comment]
no test, but you can add a NEWS entry and please cite yourself for the fix. thanks!

**Comment by mattdowle** [comment]
Closed by Mark's #4745. Thanks!
