### ISSUE TITLE
CI failure due to pkgdown installation failure

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4717]
Currently GL CI fails when attempting to produce artifacts (pkgdown website). It is because one of pkgdown dependencies is failing to be installed.
Reproducible
```sh
docker run -it registry.gitlab.com/jangorecki/dockerfiles/r-builder Rscript -e 'install.packages("systemfonts")'
```
error
```
------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: fontconfig/fontconfig.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘systemfonts’
* removing ‘/usr/local/lib/R/site-library/systemfonts’

The downloaded source packages are in
        ‘/tmp/RtmplIvXGb/downloaded_packages’
Warning message:
In install.packages("systemfonts") :
  installation of package ‘systemfonts’ had non-zero exit status
```
This is quite unfortunate because even we fix this one it is likely that similar issues will come back again in future due to the complexity of dependencies of pkgdown. What I think could make sense is to fix CRAN source to a specific date snapshot using MRAN, and keep using older pkgdown always.

**Comment by jangorecki** [comment]
explained in https://github.com/r-lib/pkgdown/issues/1115#issuecomment-699136153

**Comment by eddelbuettel** [comment]
@jangorecki That is actually a good example of where "BSPM" (with full underlying depends, ie using PPA where available) wins over "RSPM" without depends (as well as other manual aspects).  Of course it also a prime example of precisely that missing for other OSs: no PPAs for Windows or macOS.
