### ISSUE TITLE
Parallel execution of frollapply function

### ISSUE THREAD

**Issue by MislavSag** [Rdatatable/data.table#4726]
Is there simple approach to use `frollapply` fuctnion in parallel? My function inside `frollapply` takes 1s so if I can execute it inside `frollapply` in parrel I would have high performance improvement. Here is simple, non-parallel example:
```
library(data.table)
df <- as.data.table(cbind.data.frame(x=1:100))
my_fun <- function(x) {
  x <- log(x)
  Sys.sleep(1L)
  return(tail(x, 1))
}
roll_df <- frollapply(df, 90, function(x) {
  my_fun(x)})

```
Is there some `data.table` native way yo use parallel execution?

**Comment by jangorecki** [comment]
It is not possible to parallelize with OpenMP because it calls R C eval which is not thread safe. You can try fork- style parallelism like mclapply. Please do let us know if it was able to give you any speed up.

**Comment by MislavSag** [comment]
Maybe I can somehow divide `x` to n subsamples (that corresponds to a number of clusters) and than parallelize over subsamples (run `frollapply` over each subsample).

**Comment by MislavSag** [comment]
I successfully implemented parallel processing with the above approach. I divided the vector into samples and roll over them.

**Comment by jangorecki** [comment]
If it is an open source project you can link particular commit so anyone having similar problem can lookup potential solution. Thank you.

**Comment by MislavSag** [comment]
@jangorecki it is the simple wraper of frollapply:
```
frollapply_parallel <- function(y, n_cores = 4, roll_window = 600, FUN, fill = NA, align = 'right') {
  
  # divide vector to subvectors
  seq_index <- as.integer(seq(1, length(y), length.out = n_cores))
  
  # test if there are enough data in subsamples
  if ((roll_window - (seq_index[2] - seq_index[1])) > 0) {
    stop('Subsample length is lower than the rolling length. Decrease the rolling window or the number of cores.')
  }
  
  # generate subsamples
  subsample <- list()
  loop_index <- seq_along(seq_index)
  for (i in loop_index) {
    if (i == 1) {
      subsample[[i]] <- y[seq_index[i]:seq_index[i+1]]
    } else if (i == loop_index[length(loop_index)]) {
      next()
    } else {
      subsample[[i]] <- y[((seq_index[i]+1) - roll_window+1):seq_index[i+1]] 
    }
  }
  
  # apply rolling function on subsamples
  roll_par <- future_lapply(
    subsample, 
    FUN = function(x_subsample) {
      data.table::frollapply(
        x = x_subsample,
        n = roll_window,
        FUN = FUN,
        fill = fill,
        align = align
      )
    })
}
```
For contribution, I have to fork and make PR?

**Comment by jangorecki** [comment]
Thank you. As for contribution we would have to first consider that to be in scope of DT, and while it would add new dependencies, as is now, I don't think it could be merged.
If possible, could you also mention what were the gains of parallelizing here?
length of input, window width, number of cores, FUN body, and timings of frollapply and frollapply_parallel.
I am curious because in my uses cases parallelization like this was not utilizing cores that well.

**Comment by MislavSag** [comment]
The gains come if function inside `FUN` takes some time to execute (1 second in my case). In my case, using default `frollapply` on sample data took 18 minutes for all calculation. With 9 cores it took 3 minutes. With full data, it the deference would be much higher.

If `data.table` maintainers don't plan to add `future_lapply` to dependency, than there is no point of doing PR?

**Comment by jangorecki** [comment]
Unfortunately, package that provides that functions depends on another package, so chain of dependencies would be pretty big. Option is to optionally load its namespace via Suggests, but I would prefer to wait and observe more use cases that justify that. Your code provided above will be definitely useful here.

**Comment by jan-swissre** [comment]
@MislavSag `frollapply` is parallel now, it uses base R provided parallelism, low overhead, fork process. It does not work on Windows
