### ISSUE TITLE
More Elegant Merge by Range Solution

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#4736]
I have two tables, policies and claims:

```
policies<-data.table(policyNumber=c(123,123,124,125), 
                EFDT=as.Date(c("2012-1-1","2013-1-1","2013-1-1","2013-2-1")), 
                EXDT=as.Date(c("2013-1-1","2014-1-1","2014-1-1","2014-2-1")))

claims<-data.table(claimNumber=c(1,2,3,4), 
                   policyNumber=c(123,123,123,124),
                   lossDate=as.Date(c("2012-2-1","2012-8-15","2013-1-1","2013-10-31")),
                   claimAmount=c(10,20,20,15))
```

The policy table really contains policy-terms, since each row is uniquely identified by a policy number along with an effective date.

I want to merge the two tables in a way that associates claims with policy-terms. A claim is associated with a policy term if it has the same policy number and the lossDate of the claim falls within the effective date and expiration date of the policy term.

My data.table way of doing this is like below:

```
require(data.table) 
setDT(claims)[, lossDate2 := lossDate]
setkey(claims, policyNumber, lossDate, lossDate2)
foverlaps(policies, claims, by.x=c("policyNumber", "EFDT", " EXDT"))
```
but it looks verbose to me, are there more elegant ways to do this?

**Comment by jangorecki** [comment]
There are non-equi joins which should fit your scenario well. If performance is important you can check speed of both because they have own internals so their speed will be different for different scenarios.
Also for future it might be better to use stackoverflow for this kind of questions.
