### ISSUE TITLE
reset truelength after coerce to data.frame

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4754]
```r
library(data.table) # 1.13.1
dt = data.table(a=1, b=2)
df = data.frame(a=1, b=2)
truelength(dt)
#[1] 1026
truelength(df)
#[1] 0
truelength(as.data.frame(dt))
#[1] 1026 ## we want 0 here
setDF(dt)
truelength(dt)
#[1] 1026 ## we want 0 here
```

**Comment by mattdowle** [comment]
Just to be clear, why do we want 0 there; e.g. is there onward impact if it is left at 1026? Just trying to understand what was the motivation here. Maybe converting it back to DT again incorrectly thinks it's overallocated, or something like that. And if so, that could be a test.

**Comment by jangorecki** [comment]
I am not sure now what was the exact reason to file this issue. It may have been assumption that converting to data.frame should strip out any data.table related attributes, to make it as pure data.frame as possible.

**Comment by MichaelChirico** [comment]
This seems like something @OfekShilon would want to weigh in on :)

Ofek -- do you think we should bother resetting `truelength()` here? If not, we can abandon #5299.

**Comment by OfekShilon** [comment]
I think this can be safely abandoned. But I've parted ways with data.table ~2.5Y ago, don't think my opinion should carry any weight.
