### ISSUE TITLE
Inconsistent knitr printing

### ISSUE THREAD

**Issue by nbenn** [Rdatatable/data.table#4771]
The following inconsistency in knitr printing of `data.table` objects has been driving me mad. The simplest example I was able to reduce it to is as follows:

    ---
    output:
      github_document:
        html_preview: false
    ---
    
    ```{r setup}
    
    knitr::opts_chunk$set(
      collapse = TRUE,
      comment = "#>",
      out.width = "100%"
    )
    
    library(data.table)
    
    rename <- function(x) {
      x <- setnames(x, "b", "c")
      x
    }
    ```
    
    ```{r test0}
    dat <- data.table(a = 1:10, b = rnorm(10))
    rename(dat)
    ```
    
    ```{r test1}
    dat <- data.table(a = 1:10, b = rnorm(10))
    dat <- dat[, b := b + 1]
    
    rename(dat)
    ```
    
    ```{r test2}
    dat <- data.table(a = 1:10, b = rnorm(10))
    dat <- dat[, b := b + 1]
    
    rename(copy(dat))
    ```
    
    ```{r sess}
    sessionInfo()
    ```

If such an `.Rmd` file is compiled with `rmarkdown::render()`, the following `.md` results. Note that for chunks `test0` and `test2`, results are auto-printed, while for chunk `test1` this is not the case. To me there is no obvious reason why `test1` behaves differently. Can someone help me figuring out what is happening here?

    ``` r
    knitr::opts_chunk$set(
      collapse = TRUE,
      comment = "#>",
      out.width = "100%"
    )
    
    library(data.table)
    ```
    
        ## data.table 1.13.2 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com
    
    ``` r
    rename <- function(x) {
      x <- setnames(x, "b", "c")
      x
    }
    ```
    
    ``` r
    dat <- data.table(a = 1:10, b = rnorm(10))
    rename(dat)
    #>      a           c
    #>  1:  1 -0.41598280
    #>  2:  2 -0.82448725
    #>  3:  3 -0.43457416
    #>  4:  4 -0.09501297
    #>  5:  5 -0.79228629
    #>  6:  6 -2.15780357
    #>  7:  7 -0.88764300
    #>  8:  8  0.60382641
    #>  9:  9 -1.49974354
    #> 10: 10 -1.21045432
    ```
    
    ``` r
    dat <- data.table(a = 1:10, b = rnorm(10))
    dat <- dat[, b := b + 1]
    
    rename(dat)
    ```
    
    ``` r
    dat <- data.table(a = 1:10, b = rnorm(10))
    dat <- dat[, b := b + 1]
    
    rename(copy(dat))
    #>      a         c
    #>  1:  1 0.9484193
    #>  2:  2 0.9607713
    #>  3:  3 0.5125809
    #>  4:  4 0.8557314
    #>  5:  5 0.2514294
    #>  6:  6 0.2331115
    #>  7:  7 1.3812242
    #>  8:  8 2.6902517
    #>  9:  9 3.1345512
    #> 10: 10 0.6198159
    ```
    
    ``` r
    sessionInfo()
    #> R version 4.0.3 (2020-10-10)
    #> Platform: x86_64-apple-darwin17.0 (64-bit)
    #> Running under: macOS Catalina 10.15.6
    #> 
    #> Matrix products: default
    #> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
    #> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
    #> 
    #> locale:
    #> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    #> 
    #> attached base packages:
    #> [1] stats     graphics  grDevices utils     datasets  methods   base     
    #> 
    #> other attached packages:
    #> [1] data.table_1.13.2 assertthat_0.2.1  colorout_1.2-2    prettycode_1.1.0 
    #> [5] devtools_2.3.2    usethis_1.6.3    
    #> 
    #> loaded via a namespace (and not attached):
    #>  [1] Rcpp_1.0.5           knitr_1.30           magrittr_1.5        
    #>  [4] pkgload_1.1.0        prompt_1.0.0         R6_2.4.1            
    #>  [7] rlang_0.4.8          fansi_0.4.1          stringr_1.4.0       
    #> [10] tools_4.0.3          pkgbuild_1.1.0       xfun_0.17           
    #> [13] sessioninfo_1.1.1    cli_2.1.0            withr_2.3.0         
    #> [16] htmltools_0.4.0      ellipsis_0.3.1       remotes_2.2.0       
    #> [19] yaml_2.2.1           digest_0.6.25        rprojroot_1.3-2     
    #> [22] crayon_1.3.4         processx_3.4.4       callr_3.5.0         
    #> [25] fs_1.4.1             ps_1.4.0             clisymbols_1.2.0    
    #> [28] testthat_2.99.0.9000 evaluate_0.14        memoise_1.1.0       
    #> [31] glue_1.4.2           rmarkdown_2.4        stringi_1.5.3       
    #> [34] compiler_4.0.3       desc_1.2.0           backports_1.1.10    
    #> [37] prettyunits_1.1.1    memuse_4.1-0
    ```

**Comment by jangorecki** [comment]
Haven't gone into your particular problem but I would start by removing unnecessary assignment from `setnames` and `:=` calls.
```r
#x <- setnames(x, "b", "c")
setnames(x, "b", "c")

#dat <- dat[, b := b + 1]
dat[, b := b + 1]
```
`set*` functions and `:=` modifies table in-place, so assignment is not needed, and may be confusing to reader of code.

**Comment by nbenn** [comment]
@jangorecki Thanks for the feedback. I realize that defining `rename()` for example as

```r
rename <- function(x) {
  x <- setnames(x, "b", "c")
  x[]
}
```

would solve my issue. But please keep in mind, this is an artificial minimal reprex. I don't think a viable solution to this problem is making sure that every function that changes a `data.table` by-reference returns the object as `x[]`. This sounds like a lot of wasted functions calls to `[.data.table()` (and generally just feels like an ugly solution to me) just for the capability of triggering knitr auto-printing.

Interestingly, while

```r
#x <- setnames(x, "b", "c")
setnames(x, "b", "c")
```

does not change anything,

```r
#dat <- dat[, b := b + 1]
dat[, b := b + 1]
```

actually fixes the issue (in these artificial mini-examples). But while the assignments do seem to have an influence, I don't believe that this can be used to explain the issue away. For starters, as far as I am aware such assignments are at worst unnecessary. I don't think users are advised against their use for reasons other than aesthetic preferences (please correct me if I'm wrong). Also, to complicate matters more, I can produce additional examples which I find behave inconsistently:

```r
rename1 <- function(x) {
  x <- setnames(x, "b", "c")
  x
}

add_one1 <- function(x) {
  x <- x[, b := b + 1]
  x
}

rename2 <- function(x) {
  setnames(x, "b", "c")
}

add_one2 <- function(x) {
  x[, b := b + 1]
}
```

For the following chunks, only in `test5`, printing is triggered:

    ```{r test3}
    dat <- data.table(a = 1:10, b = rnorm(10))
    rename1(add_one1(dat))
    ```
    
    ```{r test4}
    dat <- data.table(a = 1:10, b = rnorm(10))
    dat <- add_one1(dat)
    
    rename1(dat)
    ```
    
    ```{r test5}
    dat <- data.table(a = 1:10, b = rnorm(10))
    add_one1(dat)
    rename1(dat)
    #>      a           c
    #>  1:  1  2.21368729
    #>  2:  2  1.13649214
    #>  3:  3  0.60559790
    #>  4:  4  1.12473323
    #>  5:  5 -0.12028355
    #>  6:  6  0.71150148
    #>  7:  7  0.75782028
    #>  8:  8  0.50369290
    #>  9:  9  0.55801836
    #> 10: 10 -0.03409446
    ```
    
    ```{r test6}
    dat <- data.table(a = 1:10, b = rnorm(10))
    rename2(add_one2(dat))
    ```
    
    ```{r test7}
    dat <- data.table(a = 1:10, b = rnorm(10))
    dat <- add_one2(dat)
    
    rename2(dat)
    ```
    
    ```{r test8}
    dat <- data.table(a = 1:10, b = rnorm(10))
    add_one2(dat)
    rename2(dat)
    ```

**Comment by shrektan** [comment]
The cause of this issue is the same as #4331 . 

Specifically speaking, the `[` operator in R is a primitive function and the visibility of the result is controlled by the C routines of R itself, which is forced to be visible. It means any top-level call on `[`, e.g., `DT[, A:=1]`, is inevitably trigger the  `print()` method. 

To avoid printing unexpectedly, data.table now always suppress the next printing after `DT[, j:=]`, by comparing the memory address of the object. It works in most cases but is far from perfect for now...


This is actually documented in the [FAQ (2.22 OK, thanks. What was so difficult about the result of `DT[i, col := value]` being returned invisibly?)](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html#ok-thanks.-what-was-so-difficult-about-the-result-of-dti-col-value-being-returned-invisibly) . 

I haven't found any way better than the current workaround yet but I'm investigating this...

**Comment by nbenn** [comment]
@shrektan Thanks for your input. If this is already tracked in another issue, I'm happy to close.
