### ISSUE TITLE
Segfault on call to fread with fill = TRUE

### ISSUE THREAD

**Issue by AndeolEvain** [Rdatatable/data.table#4774]
I have a file that systematically makes R process crash when calling the following code : 

```
dn1 <- data.table::fread("minimalEx.csv",
        sep = ",",
        quote = "\"",
        header = TRUE,
        fill = TRUE,
        stringsAsFactors = TRUE,
        integer64 = "numeric"
)
```

When trying to make a minimal example, I found that : 
_ There seem to be a minimal number of lines (around 100+) for this crash to happen. Below this threshold, I simply get an error.
_ It is linked to non-escaped quotes, here in that last line of the file
_ It only happens with argument fill = TRUE

Here is the file reduced to a minimal example : 
[minimalEx.zip](https://github.com/Rdatatable/data.table/files/5416791/minimalEx.zip)

This seems somwhat linked to the bug reported in # https://github.com/Rdatatable/data.table/issues/3509, but the conditions of reproduction are a bit different.

**Comment by jangorecki** [comment]
Thank you for reporting. For completeness would be good to have your session info as well.

**Comment by AndeolEvain** [comment]
I was on R 3.6.3 (on windows 10). Then reproduced the same issue on R 3.5.3. I updated the data.table package when trying to find the minimal case (not sure what was the version before), so I now have the version 1.12.8.
My collegues also reproduced the issue with R3.6.0, and on Mac with R3.5.3, so it doesn't seem too system-dependant.
