### ISSUE TITLE
Feature Request: `setcoltype` function for fast column coercion 

### ISSUE THREAD

**Issue by ChristopherEeles** [Rdatatable/data.table#4812]
I am currently using `data.table` to parse R objects into database tables for inclusion in a MySQL relational database.

I have found that the rate limiting operation in my scripts is actually coercing column types, and wondered if it would be feasible to implement a set* function for fast column type coercion?

For example when coercing from character to integer for primary key columns on a table with 100 million+ rows:

```
# map ids from other tables
setkeyv(sample, 'name')
setkeyv(compound_gene_response, 'sample_id')
compound_gene_response[sample, sample_id := i.id]

setkeyv(gene, 'name')
setkeyv(compound_gene_response, 'gene_id')
compound_gene_response[gene, gene_id := i.id]

compound_gene_response[, `:=`(sample_id=as.integer(sample_id),
    gene_id=as.integer(gene_id))]
```

The coercion takes > 5s to run and is the slowest part of the pipeline (with 8 DTthreads).

Thanks,
Christopher Eeles
Software Developer
Princess Margaret Cancer Research Centre

**Comment by ecoRoland2** [comment]
Please add some benchmarks. I suspect that most of the time is spend by `as.integer`. Then this would be a request for faster alternatives to R's type coercion functions.

**Comment by jangorecki** [comment]
agree, I don't think there is much to gain trying to re-implement R's `coerceVector`.

**Comment by MichaelChirico** [comment]
I guess your best bet is to parallelize over chunks of rows if you really
want a speed up. I don't think that is in scope for data.tabel TBH.

**Comment by jangorecki** [comment]
I doubt it will give speed up. `coerceVector` allocates so cannot be used in openmp parallel and other parallelism gives and overhead which is likely to be significant enough considering how simple operation is being parallelized. Closing. If you have some good idea about implementation that, please share them, we can always reopen this issue.
