### ISSUE TITLE
[R-Forge #5580] invisible functions become visible in the j-expression

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#482]
Submitted by: Eduard Antonyan; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5580&group_id=240&atid=975)

``` S
fn = function() {invisible(1:5)}

dt[, fn()]
# [1] 1 2 3 4 5
```

This is pretty annoying when using e.g. `boxplot`.

**Comment by MichaelChirico** [comment]
I think this may be identical to #1471. Just found this.

**Comment by MichaelChirico** [comment]
It's too bad R doesn't return something with an `"invisible"` attribute when it is the result of `invisible`. That would make this easy.

**Comment by mattdowle** [comment]
Linking to http://stackoverflow.com/a/36093766/403310 as well.  We could revisit FAQ 2.18 (the solution there didn't work for me when I just tested it) as well as 2.22 and over a year has passed since we last looked so another attempt may be due.

**Comment by MichaelChirico** [comment]
Hmm. Just noticed that `with(dt, fn())` _doesn't_ print the output. I guess this is related to the whole `.global$print` issue more than anything, then.

**Comment by arunsrinivasan** [comment]
No it is because R internally forces visibility on `[` unlike `with()`. [See FAQ 2.22](https://rawgit.com/wiki/Rdatatable/data.table/vignettes/datatable-faq.html#ok-thanks.-what-was-so-difficult-about-the-result-of-dti-col-value-being-returned-invisibly).

**Comment by jangorecki** [comment]
as per Arun comment, we cannot do much about R's `[` forcing visibility, solution is to wrap your data.table expression into `invisible`.
