### ISSUE TITLE
rbindlist Internal error: savetl_init checks failed

### ISSUE THREAD

**Issue by dbart79** [Rdatatable/data.table#4823]
Hi, thanks for this awesome package. 

I have a weird crash where data.table bugs out unrecoverably (requires R restart) in all versions 1.13.0 to 1.13.3. Here is the minimal example (nonsensical, the true data has more variation and is bigger) 

_library(data.table)
library(mltools)
data_instance <-data.table(x=rep(0.2972973,101),transfos=0)
buckets <- 12
data_instance[,bucket:=bin_data(transfos, bins=buckets, binType = "quantile")]_

Fehler in rbindlist(list(head(x, topn), tail(x, topn)), use.names = FALSE) : 
  STRING_PTR() can only be applied to a 'character', not a 'NULL'

And then whenever I call a data.table:

Fehler in rbindlist(list(head(x, topn), tail(x, topn)), use.names = FALSE) : 
  Internal error: savetl_init checks failed (0 100 0x00000135ab4382c0 0x00000135ab4a9670). please report to data.table issue tracker.

Until I restart

**Sessioninfo**:
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default
Sessioninfo
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mltools_0.3.5     data.table_1.13.3

loaded via a namespace (and not attached):
[1] compiler_4.0.3  Matrix_1.2-18   tools_4.0.3     yaml_2.2.1      grid_4.0.3      lattice_0.20-41

**Comment by MichaelChirico** [comment]
Sorry about that! I am not reproducing on Linux on current `master`, nor on the latest CRAN release.

**Comment by shrektan** [comment]
I think #4803 fixes this

**Comment by dbart79** [comment]
Yes, I justed it and it works, issue can be closed 👍 .

Thanks!
