### ISSUE TITLE
Why does dt[character(0L)] not error during tidyr call

### ISSUE THREAD

**Issue by ColeMiller1** [Rdatatable/data.table#4825]
While working on a fix for https://github.com/tidyverse/tidyr/issues/1066, I ran into code in which ```tidyr``` called ```df[cols]```. In the case that was failing, the call translated into ```dt[character(0L)]```. On 1.13.2 in a regular session, this errors because ```dt``` is not keyed. However, during the call within ```tidyr```, it actually returns a `null.data.table` somehow.

```
library(tidyr) ##pivot_wider modified to print information
library(data.table)

dt <- data.table(nms=letters[1:3],vals=1:3)
dt[character(0L)]
## Error in `[.data.table`(dt, character(0L)) : 
##   When i is a data.table (or character vector), the columns to join by must be specified using 'on=' argument (see ?data.table), ## by keying x (i.e. sorted, and, marked as sorted, see ?setkey), or by sharing column names between x and i (i.e., a natural join). ## Keyed joins might have further speed benefits on very large data due to x being sorted in RAM.

dt %>% pivot_wider(names_from=nms,values_from=vals)

##highly modified debugging information; I hope it's more readable this way.

str(data) ##data = dt
## Classes ‘data.table’ and 'data.frame':	3 obs. of  2 variables:
##  $ nms : chr  "a" "b" "c"
##  $ vals: int  1 2 3
##  - attr(*, ".internal.selfref")=<externalptr> 
## NULL

substitute(data[x], list(x = key_vars))
## data[character(0)]

data[key_vars]
## Null data.table (0 rows and 0 cols)

data[character(0L)]
## Null data.table (0 rows and 0 cols)

data[key_vars, verbose = TRUE]
## Empty data.table (0 rows and 2 cols): nms,vals
```
To emphasize, a regular session of `dt[character[0L]]` results in an error. After a few calls which do not change the `dt` object, the `data[character[0L]]` results in a _null.data.table_ whereas `data[character[0L], verbose = TRUE]` results in an empty data.table with the same columns as the original data.table.  

I looked at tidyr methods and I did not see anything specific to `data.table`. I am going to try to dig deeper but would appreciate any thoughts on what may cause this to occur.

**Comment by mgirlich** [comment]
This is because in `tidyr` the variable `datatable.aware = TRUE` is not set. If you set it, you get the error as you described above. See [the vignette](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html#data.table-in-imports-but-nothing-imported) for more information.

**Comment by ColeMiller1** [comment]
Thank you! I had it backwards - I assumed `[.data.table` would be the default and that those flags would revert to `[.data.frame`. I see my mistake now.
