### ISSUE TITLE
Allow duplicated() to show all duplicates

### ISSUE THREAD

**Issue by matthewgson** [Rdatatable/data.table#4828]
In order to browse all of duplicated rows by certain columns, I've been using 
`DT[duplicated(DT,by=c('col1','col2') | duplicated(DT, by=c('col1','col2'), fromLast=T)]` 
but I felt it's somewhat verbose.
Could an argument be implemented to this function to achieve above, like 
`DT[duplicated(DT, by=c('col1','col2'), all=T)]`?

**Comment by MichaelChirico** [comment]
See also #924, #1163

**Comment by jangorecki** [comment]
@matthewgson If any linked issue covers your requested use case please close this issue.

**Comment by matthewgson** [comment]
Glad to find that it was already requested.  #924 seems to subsume this issue - closing.
