### ISSUE TITLE
[R-Forge #5571] complicated by expression can hide column if .SD is present

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#484]
Submitted by: Eduard Antonyan; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5571&group_id=240&atid=975)

A bunch of specific things have to happen for this bug - when the `by` expression includes a column, that column disappears in the `j`-expression **if** `.SD` is also used in the `j`-expression:

```R
require(data.table)
dt = data.table(a = 1, b = 1)
dt[, data.table(a, .SD), by = cumsum(a)]
# Error in data.table(a, .SD) : object 'a' not found
```

Expressions that work:

```R
dt[, data.table(a, .SD), by = a]
dt[, data.table(b, .SD), by = cumsum(a)]
dt[, data.table(a, b), by = cumsum(a)]
```

**Comment by MichaelChirico** [comment]
Should be a lot easier to handle now that we've got `.SDall`, right?
