### ISSUE TITLE
options("datatable.WhenJisSymbolThenCallingScope") removed but still in FAQ?

### ISSUE THREAD

**Issue by markseeto** [Rdatatable/data.table#4858]
https://github.com/Rdatatable/data.table/blob/21eec50d7309adcaea1efbba973e31de10955bd4/NEWS.md says, under v1.10.2,

> `options('datatable.WhenJisSymbolThenCallingScope')` is now removed

but the FAQ (item 1.5) says

> In v1.9.8 released Nov 2016 there is an ability to turn on new behaviour: `options(datatable.WhenJisSymbolThenCallingScope=TRUE)`. It will then work as you expected, just like data.frame. If you are a new user of data.table, you should probably do this. You can place this command in your .Rprofile file so you don’t have to remember again.

I don't know if it's just been left in the FAQ by mistake, or if I'm misunderstanding something.

**Comment by MichaelChirico** [comment]
Sorry about that, and thanks for raising the issue. It is indeed there by mistake. The FAQ really does need an update & there's probably a few obsolete bits in there.

I've changed that part in #4862, please have a look & see if that's a better explanation for you.

Related: #2664 and #3275

**Comment by markseeto** [comment]
Thanks @MichaelChirico, yes that looks better.

**Comment by MichaelChirico** [comment]
Leaving this open until that PR would be merged
