### ISSUE TITLE
aggregate columns by condition

### ISSUE THREAD

**Issue by antoine4ucsd** [Rdatatable/data.table#4861]
Hello
I am trying to aggregate multiple columns given certain conditions...
I have one dataframe1 with columns 12:262 that contains species abundance (each column) for each sample (rows)
In another dataframe2, I have the phylum, genus, etc.. for each species (rows) .
I would like to aggregate all columns from dataframe1 whose species belong to the same phylum...
Does that make sense?

thank you+++

**Comment by jangorecki** [comment]
Hi @antoine4ucsd,
I think your may find answer to your question in `?data.table` manual and in introduction vignette. If you haven't read those yet then I recommend to do it.
Anyway if documentation does not give you the clear answer to your question, then it seems that it is best to post a question on stackoverflow, using `data.table` tag, where our community is much more responsive on helping with this kind of questions. Be sure to include reproducible example and expected output.

**Comment by antoine4ucsd** [comment]
thank you
