### ISSUE TITLE
[R-Forge #5413] fread() can no longer read files that are missing values in first row

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#487]
Submitted by: Garrett See; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5413&group_id=240&atid=975)

This is how it worked in Revision 1180

``` S
library(data.table)
tmpfile <- tempfile()
write.csv(data.table(x=NA_character_, y=1:2), tmpfile, row.names=FALSE, na="")
fread(tmpfile)
#     x y
#1: NA 1
#2: NA 2
```

However, `fread()` throws an error in newer versions of `data.table`

``` S
# install.packages("data.table", repos="http://cran.us.r-project.org")
library(data.table)
tmpfile <- tempfile()
write.csv(data.table(x=NA_character_, y=1:2), tmpfile, row.names=FALSE, na="")
fread(tmpfile)
# Error in fread(tmpfile) : 
#   Not positioned correctly after testing format of header row. ch=','
```

**Comment by kirillovde** [comment]
Looks like it's not working properly again. Try https://www.dropbox.com/s/fdtkolq19bg4xly/X_test.txt.zip?dl=0 as a test file.

`test.x <- fread(".X_test.txt")`

fread() in data.table 1.9.4 results in R session termination, while 1.9.5 throws an error `Not positioned correctly after testing format of header row. ch=' '`
