### ISSUE TITLE
How to find out where R copied a data.table

### ISSUE THREAD

**Issue by thothal** [Rdatatable/data.table#4875]
## Update

After some heavy debugging I could track the error down more clearly and will eb able to provide a reprex. Thus, I will cloise this issue and open a new one with a proper reprex.

### Context
In my rather complicated `shiny` app I am using a `data.table` in a reactive and change its values by reference from time to time (I am aware that the observers won't get notified about these changes out of the box, but in my use case that's ok). I also use `data.table` in a `list`   column of another `data.table`.

### My findings 

I have searched and found plenty of sites saying that `data.table` in a list may be the culprit (e.g. [this SO question](https://stackoverflow.com/questions/17133522/invalid-internal-selfref-in-data-table)). However, these entries seem to be rather old, and if I run the code from this example I cannot even reproduce the error. Hence, I assume these issues where fixed in the meanwhile.

### Issue
At some point in my app, however, I get the following warning from `data.table`:

>  Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or was created manually using structure() or similar). Avoid names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. If this message doesn't help, please report your use case to the data.table issue tracker so the root cause can be fixed or this message improved.

### What I tried so far
I am not using `names<-` nor `attr<-` knowingly in my app, but cannot vouch for that none of the library calls does so. So I am trying to hunt down where this copy takes place (could also be during adding the `data.table` into a reactive context) using `tracemem`.

### What I would need
However, I do not see any output. If I understand `tracemem` correctly, this means that the `data.table` (which is as said a `data.table` in a list column of another `data.table`) is not copied anywhere in my app. Thus, I am at my wit's end of where this error may come from, or what is the best tactic to track this warning down. Any advice on how to proceed?

### Session Info
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.13.2

loaded via a namespace (and not attached):
[1] compiler_3.6.3

```

**Comment by MichaelChirico** [comment]
@thothal glad to see it looks like you solved your issue; if you can offer any insights for future searchers' benefit that would be great.
