### ISSUE TITLE
list columns aren't copied when returned by dt[, col]

### ISSUE THREAD

**Issue by tlapak** [Rdatatable/data.table#4877]
I don't think that's intentional?

```R
dt = data.table(a=1:3, b=as.list(1:3))
dt
address(dt[, a]) == address(dt[, a])
#[1] FALSE

address(dt[, b]) == address(dt[, b])
#[1] TRUE
```

This means you can modify the returned list by reference later.

The offending code is https://github.com/Rdatatable/data.table/blob/3fce74daa440f9b8ef82446036375abcdd6c43b1/R/data.table.R#L1305-L1307
where the `if` condition is too broad. I need a little more time to write up a fix, but I hope I'll get to it soon. I don't really understand the S4 comment at the moment.

**Comment by MichaelChirico** [comment]
> This means you can modify the returned list by reference later.

It actually took me a minute to come up with how to do so. Here's what _doesn't_ work:

```r
l1 = dt[, b]
l2 = dt[, b]
l1[[1]] = 5 # no: outside `[` l1/l2 memory management are handled by R, copy-on-write

dt[, c := dt[, b]]
dt[1L, b := .(list(5))] # no, assign.c (?) makes a copy of dt[,b] when assigning to c --> unaffected
```

Here's a reprex of that modification-by-reference having a likely undesired effect:

```r
dt = data.table(a=1:3, b=as.list(1:3))
l = dt[, b]
l[[1]]
# [1] 1
dt[1L, b := .(list(6))]
l[[1]]
# [1] 6
```
