### ISSUE TITLE
fifelse wrong warning (max(x, na.rm = T) : no non-missing arguments to max; returning -Inf)

### ISSUE THREAD

**Issue by dmongin** [Rdatatable/data.table#4880]
I get a warning of `fifelse` wen it should not:

I found warning difference using `fifelse` from `data.table` library:

```r
    set.seed(123)
    df <- data.table(ID = rep(1:10,each = 2),x = sample(c(1,NA),20,replace = T))
    
    test1 <- df[,fifelse(any(!is.na(x)),max(x,na.rm = T),as.numeric(NA)),by = ID]
```

produces a warning:

>Warning messages
>1: In max(x, na.rm = T) : no non-missing arguments to max; returning -Inf
>2: In max(x, na.rm = T) : no non-missing arguments to max; returning -Inf

And it should not, because I filter the case where there is at leat one non NA `x` variable per group. And :

```r
 test2 <- df[,ifelse(any(!is.na(x)),max(x,na.rm = T),as.numeric(NA)),by = ID]
```

don't produce a warning, which is normal. And the two results are identical:    

```r
    identical(test1,test2)
    [1] TRUE
```

And there is no `-Inf` in the variable

Session:

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=French_Switzerland.1252  LC_CTYPE=French_Switzerland.1252    LC_MONETARY=French_Switzerland.1252
[4] LC_NUMERIC=C                        LC_TIME=French_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6         rstudioapi_0.11      magrittr_1.5         REDCapR_0.11.0.9001  hms_0.5.3           
 [6] modules_0.8.1        tidyselect_1.1.0     here_0.1             R6_2.4.1             rlang_0.4.8         
[11] dplyr_0.8.5          stringr_1.4.0        httr_1.4.1           tools_3.6.3          checkmate_2.0.0     
[16] data.table_1.12.8    lambda.r_1.2.4       futile.logger_1.4.3  ellipsis_0.3.0       assertthat_0.2.1    
[21] yaml_2.2.1           rprojroot_1.3-2      lifecycle_0.2.0      tibble_3.0.1         crayon_1.3.4        
[26] purrr_0.3.4          readr_1.3.1          formatR_1.7          vctrs_0.3.4          futile.options_1.0.1
[31] curl_4.3             glue_1.4.0           stringi_1.4.6        pillar_1.4.4         compiler_3.6.3      
[36] generics_0.0.2       backports_1.1.6      lubridate_1.7.8      pkgconfig_2.0.3     
```

**Comment by MichaelChirico** [comment]
will look into your issue more closely later but immediately -- this is a
use case for if/else and not ifelse. your logical condition is a scalar
(simple yes/no rather than a series of yeses+noes)

**Comment by jangorecki** [comment]
Michael comment is very correct. Moreover there are tools in R that let you debug your problem every further
```r
set.seed(123)
df <- data.table(ID = rep(1:10,each = 2),x = sample(c(1,NA),20,replace = T))
test1 <- df[,fifelse(any(!is.na(x)), {
  if (all(is.na(x))) browser()
  max(x,na.rm = T)
}, as.numeric(NA)),by = ID]
Browse[1]> .GRP
#[1] 4
Browse[1]> df[.BY, on=names(.BY)]
#   ID  x
#1:  4 NA
#2:  4 NA
```
Using browser you can see that `.GRP` has all NAs, and using .BY you can easily print only this group.

So according to your data, this operation should produce warning, same as base R do
```r
max(c(NA,NA), na.rm=T)
#[1] -Inf
#Warning message:
#In max(c(NA, NA), na.rm = T) :
#  no non-missing arguments to max; returning -Inf
```

For now I am closing, if you are able to present the issue, then please do, we will re-open.

**Comment by dmongin** [comment]
@jangorecki I understand your point, but I disagree: group 4 has all NAs, and so the true part of `fifelse` should not be evaluated, because the condition of `fifelse` is `any(!is.na(x))`. Furthermore, the warning indicates that it produces -Inf when there is no in the result. And it is inconsistent with the behavior of base `ifelse`.

I agree with Michael that it is  use case for simple `if`, but the behavior still looks suspicious to me

**Comment by jangorecki** [comment]
Your example could be simplified to
```r
fifelse(FALSE, max(NA, na.rm=T), NA_real_)
```
To make it work as you expect we would have to make its values evaluated lazily. I think we discussed this possibility and decided to force evaluation because laziness would needed to be implemented for every element in values as `ifelse` is designed to be used on vectors, scalar (as in your example) is just a special case.
If you want lazy evaluation of values then I would say the way to go is it use `fcase`. If you want lazy evaluation and you provide scalar logical, then of course `if` function.
