### ISSUE TITLE
Unexpected behaviour using special symbol .I with curly braces

### ISSUE THREAD

**Issue by avimallu** [Rdatatable/data.table#4904]
I am working on creating flags using complicated rules for a specific ask. I found using the curly braces courtesy of [NEWS item for 1.12.8](https://github.com/Rdatatable/data.table/blob/master/NEWS.md#datatable-v1128--09-dec-2019) to be very helpful, but I ran into what looks like unexpected behaviour for the `.I` symbol inside a `.SD`. Reproducible code and comments below.

```r
library(data.table)

DT = data.table(
  id = rep(letters[1:5], c(100, 80, 60, 40, 20)),
  ln = rep(rep(LETTERS[1:3], c(10, 20, 30)), 5),
  nm = rep(rep(seq(77, 82), c(5, 4, 3, 2, 1), 20))
)
```

The specific case that I wanted to highlight is:

```r
DT[id == "e"]
    id ln nm
 1:  e  C 77
 2:  e  C 78
 3:  e  C 79
 4:  e  C 80
 5:  e  C 81
 6:  e  C 82
 7:  e  C 77
 8:  e  C 78
 9:  e  C 79
10:  e  C 80
11:  e  C 81
12:  e  C 82
13:  e  C 77
14:  e  C 78
15:  e  C 79
16:  e  C 80
17:  e  C 81
18:  e  C 82
19:  e  C 77
20:  e  C 78
```

I wanted to identify all the records that followed the first appearance of the maximum value for column `nm` for each `id`. My initial approach was (the `if` clause is presented to show the discrepancy in expected value):

```r
DT[, {
  tot = .SD[, .I[which.max(nm)]];
  boo = .SD[.I > tot, .(.I, tot, .N, id)];
  if(id == "e") print(boo)},
  .(id)]
```
which gives
```r
     I tot  N id
 1:  1   6 20  e
 2:  2   6 20  e
 3:  3   6 20  e
 4:  4   6 20  e
 5:  5   6 20  e
 6:  6   6 20  e
 7:  7   6 20  e
 8:  8   6 20  e
 9:  9   6 20  e
10: 10   6 20  e
11: 11   6 20  e
12: 12   6 20  e
13: 13   6 20  e
14: 14   6 20  e
15: 15   6 20  e
16: 16   6 20  e
17: 17   6 20  e
18: 18   6 20  e
19: 19   6 20  e
20: 20   6 20  e
Empty data.table (0 rows and 1 cols): id
```
while I expected it to give:
```r
     I tot  N id
 1:  1   6 15  e
 2:  2   6 15  e
 3:  3   6 15  e
 4:  4   6 15  e
 5:  5   6 15  e
 6:  6   6 15  e
 7:  7   6 15  e
 8:  8   6 15  e
 9:  9   6 15  e
10: 10   6 15  e
11: 11   6 15  e
12: 12   6 15  e
13: 13   6 15  e
14: 14   6 15  e
15: 15   6 15  e
Empty data.table (0 rows and 1 cols): id
```
The expected output is obtained by modifying the code to be:
```r
DT[, {
  tot = .SD[, .I[which.max(nm)]];
  boo = .SD[seq(tot, .N, 1), .(.I, tot, .N, id)];
  if(id == "e") print(boo)},
  .(id)]
```

Is there anything that I am missing here? What I do not understand is why despite `tot` being 6 in both cases, why the number of rows is not filtered correctly in `.SD`? Is there a misunderstanding in my understanding of `.I`?

Note: I understand the more efficient way to do this would perhaps be:
```r
DT[, {
  boo = .SD[.I >= .I[which.max(nm)], .(.I, .N, id)];
  if(id == "e") print(boo)},
  .(id)]
```
but I think the code above is still unexpected behaviour, and hence am reporting.

**Comment by jangorecki** [comment]
.SD has own .I, isn't it? Did you took that into account in your code?

**Comment by avimallu** [comment]
I think I have - `.SD[.I >.I[which.max(ln)]]` and `.SD[seq(tot, .N, 1)]` work (with `tot` in the latter having been defined as `.SD[, .I[which.max(ln)]]`), but `.SD[.I > tot]` does not.

**Comment by MichaelChirico** [comment]
.I doesn't work in i IINM

**Comment by avimallu** [comment]
Got it. My bad - that is the first line in the help page. It'll be nice if the user can be warned about using it in `i` though, much like `:=` usage in `i` is given a friendly error, rather than allowing it to pass through without any warning.

**Comment by MichaelChirico** [comment]
Thanks for the feedback! I think eventually we do want to support `.I` in `i` (see #4695 and add a reaction there to add your support)
