### ISSUE TITLE
rlang interferes with dcast `...~metric` API

### ISSUE THREAD

**Issue by l-jaye** [Rdatatable/data.table#4913]
Hello! 

I am not sure if this is a Shiny issue, or a data.table issue, but a recent update to either package causes an error `Error in check_formula: '...' used in an incorrect context` when using `...` in a formula for dcast.data.table() inside a shiny app. Outside of the shiny app, no issue. Please see a reproducible example below:  

```
library(data.table)
library(shiny)

shinyApp(
  
  ui = fluidPage(
    actionButton("do.btn","Go!")
  ),
  
  server = function(input, output){
    
    observeEvent(input$do.btn, {
      
      metrics = c("col.x","col.y")
      dt = data.table(x = 1:10, y = "test", col.x = 3, col.y = 4)
      melt.dt = melt(dt, measure.vars = metrics, variable.name = "metric")
      dt = dcast(melt.dt, ... ~ metric, value.var = "value", fill = NA) # this throws error
      
    })
    
  }
)
```

**Comment by l-jaye** [comment]
Update: 

Replacing  `... ~ metric` with `as.formula("...~metric")` works:

```
library(data.table)
library(shiny)

shinyApp(
  
  ui = fluidPage(
    actionButton("do.btn","Go!")
  ),
  
  server = function(input, output){
    
    observeEvent(input$do.btn, {
      
      metrics = c("col.x","col.y")
      dt = data.table(x = 1:10, y = "test", col.x = 3, col.y = 4)
      melt.dt = melt(dt, measure.vars = metrics, variable.name = "metric")
      
      dt = dcast(melt.dt, as.formula("...~metric"), value.var = "value", fill = NA)
      print(dt)
      
    })
    
  }
)

```

**Comment by avimallu** [comment]
From the [linked issue](https://github.com/rstudio/shiny/issues/3303), it looks like this is not something that can be fixed on `data.table`'s end, correct? The comment indicates that it's an interaction between `rlang` and `data.table`.

**Comment by ColeMiller1** [comment]
I would leave it open in case we would want to provide a new API. Maybe `.SD ~ metric` which would not interfere with `rlang` - I know it took me awhile to remember that all variables was `...`.

As far as workarounds, quoting just the formula works. E.g.

``` r
dt = dcast(melt.dt, "...~metric", value.var = "value", fill = NA)
```

**Comment by lionel-** [comment]
This is a bug in rlang that we will fix on our side.

**Comment by MichaelChirico** [comment]
Thanks Lionel! Closing this side then.
