### ISSUE TITLE
can enable reading from a connection?

### ISSUE THREAD

**Issue by ieiwk** [Rdatatable/data.table#4921]
Hi,

I wonder if reading from a connection can be enabled.

Thanks.

**Comment by ben-schwen** [comment]
Thanks for the request! Duplicate of #561 

Please feel free to add support on that main issue, or reopen this if I'm in error in assigning the duplicate label

**Comment by ieiwk** [comment]
thanks for redirection!

**Comment by MichaelChirico** [comment]
Thanks Ben!
