### ISSUE TITLE
.EACHI and empty i for rowwise operations

### ISSUE THREAD

**Issue by vincentarelbundock** [Rdatatable/data.table#4922]
The "special symbols" section of the documentation says:

> Its usage is by=.EACHI (or keyby=.EACHI) which invokes grouping-by-each-row-of-i; see data.table's by argument for more details.

We can "twist" this feature into allowing us to run row-wise operations by (1) keying all columns, (2) doing a self-join, and (3) calling `by=.EACHI`. For example, to add a new column with row sums:

```r
library("data.table")

dat = data.table(a = 1:2, b = 3:4)

setkeyv(dat, colnames(dat))

dat[dat, .(c = sum(c(a, b))), by = .EACHI]
#>    a b c
#> 1: 1 3 4
#> 2: 2 4 6
```

It would be very convenient if we could skip the `setkeyv` and the self-join steps, and just leave `i` empty to operate on each row. This would produce the same result as above:

```r
dat = data.table(a = 1:2, b = 3:4)

dat[, .(c = sum(c(a, b))), by = .EACHI]
```

Does this make any sense?

**Comment by jangorecki** [comment]
There is idea to use `by=.I` instead, your request is interesting alternative, but I think I prefer `.I`, because `.EACHI` is confusing when `i` is missing. Alternatively `dat[i=TRUE, j=..., by=.EACHI]` makes little bit more sense to be.

**Comment by vincentarelbundock** [comment]
Thanks for your reply, and I apologize for missing the other issue. I agree that `.I` would make more sense.

Closing in favor of https://github.com/Rdatatable/data.table/issues/1732

**Comment by vincentarelbundock** [comment]
BTW, @jangorecki I see that you expressed skepticism about rowwise operations in the other thread. I agree that many patterns are probably best achieved by applying `melt` first, but I would argue that there are still many natural applications.

For example, I run a fair amount of simulations where I need to fit models with different parameters. Rowwise operations allow me to store parameters in different rows of a data.table, and run my operations in a very natural way, like this:

[PS: Forgot to thank you for your great work on `data.table`. I benefit from it every day!]

``` r
library(data.table)

params = CJ(
  y = c("hp", "mpg", "vs"),
  x = c("drat", "cyl", "gear"))

fit = function(x, y) {
  f = as.formula(paste(y, "~", x))
  mod = lm(f, mtcars)
  out = summary(mod)$coefficients
  out = data.frame(out)
  out$term = row.names(out)
  out
}

setkey(params, x, y)
params[params, fit(x, y), by = .EACHI]
#>        x   y     Estimate  Std..Error    t.value     Pr...t..        term
#>  1:  cyl  hp -51.05436157 24.98194431 -2.0436504 4.985522e-02 (Intercept)
#>  2:  cyl  hp  31.95828066  3.88380335  8.2286042 3.477861e-09         cyl
#>  3:  cyl mpg  37.88457649  2.07384361 18.2678078 8.369155e-18 (Intercept)
#>  4:  cyl mpg  -2.87579014  0.32240888 -8.9196988 6.112687e-10         cyl
#>  5:  cyl  vs   1.85335019  0.19398766  9.5539594 1.309758e-10 (Intercept)
#>  6:  cyl  vs  -0.22882427  0.03015818 -7.5874702 1.843018e-08         cyl
#>  7: drat  hp 353.65252616 76.04872959  4.6503410 6.242031e-05 (Intercept)
#>  8: drat  hp -57.54523275 20.92205020 -2.7504586 9.988772e-03        drat
#>  9: drat mpg  -7.52461844  5.47666257 -1.3739423 1.796391e-01 (Intercept)
#> 10: drat mpg   7.67823260  1.50670511  5.0960421 1.776240e-05        drat
#> 11: drat  vs  -1.05517953  0.56167858 -1.8786181 7.004519e-02 (Intercept)
#> 12: drat  vs   0.41502950  0.15452549  2.6858319 1.167553e-02        drat
#> 13: gear  hp 189.76296296 63.25908009  2.9997743 5.393025e-03 (Intercept)
#> 14: gear  hp -11.68148148 16.83172566 -0.6940157 4.930119e-01        gear
#> 15: gear mpg   5.62333333  4.91637913  1.1437957 2.617534e-01 (Intercept)
#> 16: gear mpg   3.92333333  1.30813070  2.9991906 5.400948e-03        gear
#> 17: gear  vs  -0.08148148  0.45868941 -0.1776398 8.601999e-01 (Intercept)
#> 18: gear  vs   0.14074074  0.12204626  1.1531753 2.579439e-01        gear
```
