### ISSUE TITLE
unused argument (.SEDcols

### ISSUE THREAD

**Issue by misterbensonh** [Rdatatable/data.table#4939]
i am working with R version 3.2.1 on OS X Yosemite (Version 10.10.4).

Read a CSV file using:

> train = read.csv("~/Downloads/train.csv", header = TRUE)
Then initialized a variable:

> cat_var <- names(train)[which(sapply(train, is.character))]
> cat_var <- c(cat_var, 'BedroomAbvGr', 'HalfBath', ' KitchenAbvGr','BsmtFullBath', 'BsmtHalfBath', 'MSSubClass')
Now I want to find the total null values in the cat_var columns, but getting the following error:

> colSums(sapply(train[,.SD, .SDcols=cat_var], is.na))
Error in `[.data.frame`(train, , .SD, .SDcols = cat_var) : 
  unused argument (.SDcols = cat_var)

**Comment by MichaelChirico** [comment]
from your error message+code, you're trying to use data.table syntax on a
data.frame returned by read.csv.

try switching read.csv to fread to return a data.table instead
