### ISSUE TITLE
unused argument error when using .SD with SEDcols

### ISSUE THREAD

**Issue by misterbensonh** [Rdatatable/data.table#4940]
data.table used to powerfully allow combinations of .SDcols and lapply(.SD, foo) within the j of dt[i,j,...]. Now it doesn't seem to. Has the proper syntax changed? Is the operation no longer supported? Any help would be greatly appreciated!

example below:

NewMedicationData.V <- fread(file ="E:/MedicationsWithDoses/MedsExtractWithDoseInfo_hourlyCompleted_update.csv",
sep=",", sep2="auto", dec=".", quote=""",
nrows=Inf, header="auto",
na.strings=getOption("datatable.na.strings","NA"),
stringsAsFactors=FALSE, verbose=getOption("datatable.verbose", TRUE),
drop=NULL, colClasses=NULL, check.names=FALSE, encoding="unknown",
strip.white=TRUE, fill=FALSE, blank.lines.skip=TRUE,
showProgress=getOption("datatable.showProgress", interactive()),
data.table=getOption("datatable.fread.datatable",TRUE)
,keepLeadingZeros = getOption("datatable.keepLeadingZeros", FALSE))

NewMedicationData.V[,.SD[max(durationUsageMonths,na.rm = T)], by = UserUUID,
.SEDcols = c('durationUsageYears', 'durationUsageMonths')]

Error in [.data.table(NewMedicationData.V, , .SD[max(durationUsageMonths, :
unused argument (.SEDcols = c("durationUsageYears", "durationUsageMonths"))

The same code works with a simulated sample
below. 
x <- rep(1 : 10, each = 4)
y = rep ( 5 : 14, each = 4)
z = rep(c("male", "female"), each = 20)

xy <- data.frame(x,y, z)
xy = setDT(xy)

xy[,.SD[which.max(x)], by = z, .SDcols = c("x","y")]

**Comment by ColeMiller1** [comment]
Thanks for getting into data.table! 

The error is caused by a typo. The argument is `.SDcols` as you used in the sample code that works. The argument is not `.SEDcols`. Anytime you see the error `unused argument error` it means that you are 1) passing too many arguments to a function or, as in this case, 2) passing a named argument that does not match the function arguments.

So this would be the correct call:
``` 
NewMedicationData.V[,.SD[max(durationUsageMonths,na.rm = T)], by = UserUUID, .SDcols = c('durationUsageYears', 'durationUsageMonths')]
```

**Comment by misterbensonh** [comment]
That's correct! Thank you so much!!
