### ISSUE TITLE
data table getting an index (by reference) after I filter/subset by rows (without doing anything by reference)

### ISSUE THREAD

**Issue by bnicenboim** [Rdatatable/data.table#4976]
Hi, I found a strange behavior of data table, it does look like a bug, and I can't find info about it. (I tried with the last version in CRAN and in development).

A data table without an index gets an index after filtering:

```
dt <- data.table(x=1:10, y=1:10)
indices(dt)
# NULL
dt[!y %in% c(1,2,3),]
indices(dt)
# [1] "y"
```

`#` `Output of sessionInfo()`

```
>  sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.1

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3   
```

**Comment by avimallu** [comment]
This is covered in the [Secondary indices and auto indexing](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-secondary-indices-and-auto-indexing.html) vignette and is mentioned as (emphasis mine):
> That is what auto indexing does. At the moment, it is only implemented for binary operators == and %in%. An index is **automatically created and saved as an attribute**. That is, unlike the on argument which computes the index on the fly each time (unless one already exists), a secondary index is created here.

**Comment by bnicenboim** [comment]
Ohh, sorry! i didn't know that! 

It was failing the unit tests of my package.
 I see that there is a
options(datatable.auto.index = FALSE)
I'll try to set that for my package.

Thanks, I'm closing it.

**Comment by MichaelChirico** [comment]
Hi Bruno, indeed you can set `options(datatable.auto.index=FALSE)` to prevent this, but this is not expected to be typical behavior -- could you elaborate on why you want to prevent auto-indexing? We think of it as the correct default in the vast majority of cases.

You said "It was failing the unit tests of my package", what does that mean exactly? Maybe we could offer you alternatives instead, e.g. `all.equal.data.table` has an `ignore.attributes` argument that will confirm two tables are equal without checking that they necessarily have the same indices.
