### ISSUE TITLE
Documentation for `i.` and `x.`

### ISSUE THREAD

**Issue by iago-pssjd** [Rdatatable/data.table#4977]
Recently I have found the use of symbols `i.` and `x.` in `data.table` (specifically, `i.to` here: https://stackoverflow.com/a/44592473/997979)

I was looking for documentation explaining them, but the only thing I've found in the vignettes was the line `# i.V1 has same type (character) as x.origin. No coercion needed.` in https://rdatatable.gitlab.io/data.table/articles/datatable-secondary-indices-and-auto-indexing.html

Is there some place where this syntax is explained?

Thank you!

**Comment by tlapak** [comment]
It is explained in `?data.table` in the `j` section, last two paragraphs.

**Comment by iago-pssjd** [comment]
I see. Thanks!

**Comment by iago-pssjd** [comment]
I closed the issue since it is explained, but a vignette with some examples would be very helpful.

**Comment by avimallu** [comment]
Track the vignette progress in #2181.

**Comment by MichaelChirico** [comment]
would it make sense for ?i. and ?x. to bed aliases for ?data.table?
