### ISSUE TITLE
measure() processes id.var in melt() if column name matches pattern

### ISSUE THREAD

**Issue by PavoDive** [Rdatatable/data.table#4991]
I posted this in issue #2575 (closed), and am reposting it here, as it most likely is a new issue of the `measure` function than the countinuation of the old issue.

Thank you all very much for `measure`. I find an unexpected behavior. With data from [this StackOverflow question](https://stackoverflow.com/questions/65937422/variable-values-in-data-tablemelt-with-patterns?noredirect=1#comment116595972_65937422) and `data.table` 1.14.1 I found this:

```
df1 <- structure(list(Material_code = 111:112, 
                      actual_202009 = c(30L, 19L), 
                      actual_202010 = c(44L, 70L), 
                      actual_202011 = c(24L, 93L), 
                      pred_202009 = c(25L, 23L), 
                      pred_202010 = c(52L, 68L), 
                      pred_202011 = c(27L, 100L)), 
                 class = c("data.table", "data.frame"), 
                 row.names = c(NA, -2L))
```

The following code produces **almost** the expected result:

```
> melt(df1, id.vars = 1, measure.vars= measure(value.name, date, sep = "_"))
   Material_code   date Material actual pred
1:           111   code      111     NA   NA
2:           112   code      112     NA   NA
3:           111 202009       NA     30   25
4:           112 202009       NA     19   23
5:           111 202010       NA     44   52
6:           112 202010       NA     70   68
7:           111 202011       NA     24   27
8:           112 202011       NA     93  100
```

with the weird rows with "code" in the `date` column. I expected `melt` to leave column 1 (`id.vars = 1`) untouched by `measure`, so that's why I say the result is not what I expected. **However**, if I change the name of the first column, then it produces the output I expected:

```
df2 <- copy(df1)[, setnames(.SD, 1, "Material.code")]
> melt(df2, id.vars = 1, measure.vars= measure(value.name, date, sep = "_"))
   Material.Code   date actual pred
1:           111 202009     30   25
2:           112 202009     19   23
3:           111 202010     44   52
4:           112 202010     70   68
5:           111 202011     24   27
6:           112 202011     93  100
```

**Comment by mattdowle** [comment]
@tdhock I had followed up on twitter [here](https://twitter.com/MattDowle/status/1391658157378781186) which gave rise to this one. Would you be able to take a look please? I can take a look if not. Just thought you might know.

**Comment by tdhock** [comment]
Hi I don't think this is a bug. In fact this is the documented behavior:
```
     sep: Separator to split ‘cols’ into groups. Columns that result in
          the maximum number of groups are considered measure
          variables.
```
So since Material_code splits with sep="_" into two groups (which is the max), it is considered a measure variable. 

For these data you should use the pattern arg instead of sep:
```r
> melt(df1, measure.vars= measure(value.name, date, pattern="(actual|pred)_(.*)"))
   Material_code   date actual pred
1:           111 202009     30   25
2:           112 202009     19   23
3:           111 202010     44   52
4:           112 202010     70   68
5:           111 202011     24   27
6:           112 202011     93  100
> 
```

**Comment by tdhock** [comment]
maybe a warning or message could be added when id.vars is used with measure() to avoid this kind of confusion?

**Comment by tdhock** [comment]
OP wrote "I expected melt to leave column 1 (id.vars = 1) untouched by measure" but actually it is valid to specify the same variable in id.vars and measure.vars. But we could warn in that case. @PavoDive would a warning like this be helpful?
Warning: some variables (1) specified as both id.vars and measure.vars, which is typically a mistake

**Comment by PavoDive** [comment]
Hi @tdhock , thanks for checking on this. I think such a warning will be helpful.

**Comment by avimallu** [comment]
Strictly speaking, the warning maybe shouldn't call it a mistake? `melt` documentation does state:

```Both id.vars and measure.vars can have the same column more than once and the same column can be both as id and measure variables.```

Maybe showing it specifically for the case of using the `measure` function may be more beneficial, as in that case it is likely that the common columns escaped the user's notice since it was not explicitly specified in the arguments?

**Comment by tdhock** [comment]
Well, since we also have documentation that it is OK to use the same variable in both measure.vars and id.vars, I would say that we do NOT need to add a warning here.
Otherwise if we add a warning I would suggest updating the documentation as well, something like 
Both id.vars and measure.vars can have the same column more than once and the same column can be both as id and measure variables (but a warning is given in this case because it is usually a mistake)

As for the idea to warn only when measure() function is used, that seems difficult to implement (measure function does not know what id.vars is).

**Comment by tdhock** [comment]
I propose to close this issue, without any new warnings, due to the reasons explained above. @PavoDive if that is ok with you please close?
