### ISSUE TITLE
Allowing the use of un-named list elements in `env` in `substitute2` and `[.data.table`

### ISSUE THREAD

**Issue by tonyfischetti** [Rdatatable/data.table#4995]
Currently, `substitute2` (and, by extension, `[.data.table`) disallows the use of un-named list elements in the `env` argument. However, I noticed that, for a lot of use cases, the two sides of the equals sign are the same. For example...

```
DT = as.data.table(iris)
tmp = "Species"
DT[, .N, tmp, env=list(tmp=tmp)]
```

`data.table()` already allows the use of "unnamed" columns by auto-naming them using `name_dots` in R/utils.R. An implementation (which I'm happy to furnish) can use use `name_dots` for this purpose, too.

This would allow the above to be written as simply as
```
DT = as.data.table(iris)
tmp = "Species"
DT[, .N, tmp, env=list(tmp)]
```

This, of course, wouldn't stop users from using named list elements, or even mixing them in the same `env`.

**Comment by jangorecki** [comment]
This unfortunately also requires to introduce NSE to `env` argument, to which I responded in https://github.com/Rdatatable/data.table/issues/4994#issuecomment-840590829. In this case there is way around, like creating and exporting `.()` mentioned in linked issue. Ultimately, to not introduce NSE to `env` and have this kind of functionality we would have to have for example `list2` function having NSE interface and use that instead of `list`.

**Comment by tonyfischetti** [comment]
I understand your hesitation to use NSE in `env`.

Perhaps there is another shorthand for list() that uses NSE that the user can choose to use to use in `env`? It couldn't be `.()` (for the reason outlined in  #4994). `L()`?
It could used `name_dots`. Might be useful in other places in the codebase, as well

**Comment by MichaelChirico** [comment]
I basically agree with Jan here. I understand the temptation to add nice NSE tricks wherever possible, but they do create a maintenance hassle. Adding metaprogramming to our new metaprogramming interface... starting to feel like a Hofstadterian kōan :smiley: 

The case when these shortcuts are most helpful is in interactive usage; `env` is really designed for structured work in packages, where being explicit is almost always the better choice. So I wouldn't use `L` or any other short-hand, and I wouldn't use `name_dots` either. `list()` is a core data structure for R; auto-naming a la `name_dots` mostly happens with interactive features (e.g. plots). Providing explicit names should be preferred.

**Comment by tonyfischetti** [comment]
I get it--thanks for the explanations. I'll close this issue and  #4994
