### ISSUE TITLE
Remove "no non-missing" warning for character min and max?

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#4999]
When looking at `gsumm.c` for recent PR, this warning struck me as unnecessary : 

```
> DT
        a     b
   <char> <int>
1:   <NA>     1
2:   <NA>     2
> DT[, min(a, na.rm=TRUE), by=b]
       b     V1
   <int> <char>
1:     1   <NA>
2:     2   <NA>
Warning message:
In gmin(a, na.rm = TRUE) :
  No non-missing values found in at least one group. Returning 'NA' for such groups to be consistent with base
```

Can we just remove the warning?  I can imagine that the warning is more annoying when it does occur, than being appreciated. A secondary motivation is that there is an extra loop through the result just to generate that warning, so that loop could be removed.

**Comment by jangorecki** [comment]
IMO definitely! If it is consistent to base R then we don't have to warn. This is what user should expect.

**Comment by mattdowle** [comment]
The PR didn't turn out the way I was planning: the warnings are gone, but it no longer returns `Inf`. I realize you agreed on the basis that the bahavior was the same as base so why warn. But then I realized the warning itself is generated in base too (that Inf is being returned). So with-warning is the part that is consistent with base too.
I just think the new behavior makes more sense! I'm sure everyone is surprised by the `Inf` and type change to numeric when they first experience it. Time to remove that user surprise. NA is the behavior I want myself when I'm doing data science.
