### ISSUE TITLE
measure not included in the NAMESPACE of data.table

### ISSUE THREAD

**Issue by lizimai** [Rdatatable/data.table#5002]
Hi I have installed the new dev version of data.table to use the new measure function. It works outside but when I incorporate it in a R package that I write it reports the `measure` function is not in `NAMESPACE` yet. Is it possible to add it in the `NAMESPACE` of the package? Thanks!

```Error: 'measure' is not an exported object from 'namespace:data.table' ```

**Comment by avimallu** [comment]
I may be mistaken here, but `measure` in its current state cannot work outside of a `data.table` environment. Its documentation indicates:
```
measure(..., sep, pattern, cols, multiple.keyword="value.name")
```
and has no reference to a `data.table` object, similar to `patterns`.

**Comment by MichaelChirico** [comment]
You're right @avimallu, but so far we've also exported those as "dead objects" to make it easier on package developers to get around these errors.

@lizimai can you clarify how you're using `measure` exactly? It is not intended do be used like `data.table::measure` -- you should write `measure(...)` and then `data.table` will interpret it correctly.

**Comment by lizimai** [comment]
I see... the problem was solved when I remove `data.table::` so I think that was the problem
