### ISSUE TITLE
use all threads by default

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#5008]
Why not make the data.table package use all threads by default?

**Comment by jangorecki** [comment]
@waynelapierre if you look through the issues you will probably find the reason.

**Comment by mattdowle** [comment]
But, @jangorecki, it might be hard to search for!  I tried a few google searches and I didn't come up with anything that returned the following.

See new feature 3 in v1.12.2 (Apr 2019) : 

![image](https://user-images.githubusercontent.com/2779998/118736190-2fb70880-b7ff-11eb-9c26-37a57fa2fc20.png)

So if you prefer to use all logical CPUs by default, on servers for example, just set environment variable `R_DATATABLE_NUM_PROCS_PERCENT` to 100%.  Depending on the task, you'll need to experiment what works best for your data and your machine.

**Comment by jangorecki** [comment]
@waynelapierre Please subscribe to https://github.com/h2oai/db-benchmark/issues/202 for more precise information about threads vs timing performance.
