### ISSUE TITLE
data.table license compatibility

### ISSUE THREAD

**Issue by PhilippeSantenoise** [Rdatatable/data.table#5012]
The exhibit B of the MPL license makes code incompatible with the secondary licenses. This issue has already discussed (https://github.com/Rdatatable/data.table/pull/2456#discussion_r168598384), but the response is not clear for me.
Several R packages with a secondary license (example: Ac3net, AF, ...) depend on the data.table R package and I cannot find any details on this part. 
Is a code with a secondary license (as GPL) still compatible with data.table license ?

**Comment by mattdowle** [comment]
Thank you for linking to the response there. Which part of the detailed response is not clear?

**Comment by PhilippeSantenoise** [comment]
Thank you for your quick reply.
All is clear now.
