### ISSUE TITLE
Rolling functions don't seem to work with lists

### ISSUE THREAD

**Issue by pnacht** [Rdatatable/data.table#5013]
The man page for the `froll*` family of functions describes the argument `x` as:

> vector, list, [...]

However, I can't seem to get the functions to work for lists:

``` r

packageVersion("data.table")
#> [1] ‘1.14.0’

data.table::frollsum(c(1, 2, 3), n = 2)
#> [1] NA  3  5
data.table::frollsum(list(1, 2, 3), n = 2)
#> [[1]]
#> [1] NA
#> 
#> [[2]]
#> [1] NA
#> 
#> [[3]]
#> [1] NA
```

<sup>Created on 2021-05-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The fact that the output is a list is expected, since that's the return type for any non-vector `x`. However, obviously the actual results are incorrect, seeing as they're all `NA`.

Interestingly, the rolling function doesn't seem to be applied at all in the case of lists: (note that "AAA" is never printed in that case):

``` r
data.table::frollapply(c(1, 2, 3), n = 2, FUN = function(x) {print("AAA"); 1})
#> [1] "AAA"
#> [1] "AAA"
#> [1] NA  1  1
data.table::frollapply(list(1, 2, 3), n = 2, FUN = function(x) {print("AAA"); 1})
#> [[1]]
#> [1] NA
#> 
#> [[2]]
#> [1] NA
#> 
#> [[3]]
#> [1] NA
```

**Comment by avimallu** [comment]
I *may* be wrong here, but I think the way they are designed to work is by applying the window *inside* each of the elements of the list, and not the list itself.

```r
> data.table::frollsum(list(c(1, 2, 3), c(4, 5, 6)), n = 2)
[[1]]
[1] NA  3  5

[[2]]
[1] NA  9 11
```

This behaviour is *probably* required to ensure that the operation for `data.table` or `data.frame` objects can be performed as intended i.e. by treating each element of the `data.table`/`data.frame` (which I think will be a list) as a column.

**Comment by jangorecki** [comment]
If you will keep reading this line of manual till the end it will get more clear

> vector, list, data.frame or data.table **of numeric or logical columns.**

bold text also applies to a list, where each element is considered a column.
So basically what @avimallu explained to you.

Your presented use case, a list of scalars, seems very unusual. If you would like to fill FR, then please do, providing expected results.

**Comment by pnacht** [comment]
I don't actually have this use-case. I was exploring another issue when I stumbled onto this behavior which surprised me given how I'd interpreted the man page.

That being said, I do think the definition of `x` could be made a bit clearer in this regard. I'd read the line to the end, but the use of the word "columns" seemed to make it clear that it was only with regards to data.frame/tables; I've personally never seen elements of a list described as columns.

I believe a definition like the one below would be clearer:

>x: vector, data.frame or data.table of numeric or logical elements or columns. May also be a list, in which case the rolling function is applied to each of its elements.
