### ISSUE TITLE
:= coercion when recycling with length=1

### ISSUE THREAD

**Issue by sindribaldur** [Rdatatable/data.table#5018]
A bug or should I have searched the documentation better?

```R
DT <- data.table(a = 1:2, b = c(0, 0))
DT[, b := '-'][]
# Warning messages:
# 1: In `[.data.table`(DT, , `:=`(b, "-")) :
#   Coercing 'character' RHS to 'double' to match the type of column 2 named 'b'.
# 2: In `[.data.table`(DT, , `:=`(b, "-")) : NAs introduced by coercion
#    a  b
# 1: 1 NA
# 2: 2 NA

DT <- data.table(a = 1:2, b = c(0, 0))
DT[, b := rep('-', .N)][]
#    a b
# 1: 1 -
# 2: 2 -
```

**Comment by avimallu** [comment]
You'll find this in the documentation for `:=`, quoted below (bolding mine):

> Unlike <- for data.frame, the (potentially large) LHS is not coerced to match the type of the (often small) RHS. **Instead the RHS is coerced to match the type of the LHS, if necessary**. Where this involves double precision values being coerced to an integer column, a warning is given (whether or not fractional data is truncated). The motivation for this is efficiency. It is best to get the column types correct up front and stick to them. **Changing a column type is possible but deliberately harder: provide a whole column as the RHS**. This RHS is then plonked into that column slot and we call this plonk syntax, or replace column syntax if you prefer. **By needing to construct a full length vector of a new type, you as the user are more aware of what is happening, and it is clearer to readers of your code that you really do intend to change the column type**.

**Comment by Henrik-P** [comment]
Related answer on SO where @mattdowle addresses both class and memory when a column is plonked: [Why is data.table casting column classes when I assign all columns by reference](https://stackoverflow.com/questions/18594017/why-is-data-table-casting-column-classes-when-i-assign-all-columns-by-reference)

**Comment by sindribaldur** [comment]
I clearly should have searched the documentation better.
