### ISSUE TITLE
add examples of `set` function in documentation

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5031]

**Comment by avimallu** [comment]
Hey Jan, isn't this already present as a "speed example" in docs?
```r
m = matrix(1, nrow = 2e6L, ncol = 100L)
DF = as.data.frame(m)
DT = as.data.table(m)

system.time(for (i in 1:1000) DF[i, 1] = i)
# 15.856 seconds
system.time(for (i in 1:1000) DT[i, V1 := i])
# 0.279 seconds  (57 times faster)
system.time(for (i in 1:1000) set(DT, i, 1L, i))
# 0.002 seconds  (7930 times faster, overhead of [.data.table is avoided)
```

**Comment by jangorecki** [comment]
Not enough, there should be usage of assignment to multiple columns multiple values. As asked in https://stackoverflow.com/q/67761660/2490497

**Comment by ColeMiller1** [comment]
Loosely related:

https://stackoverflow.com/q/67689765/11355066

Basically, the example is trying to use `set` to aggregate by group which isn’t a great use case for `set`. I do not think any additional documentation is needed based on this SO.
