### ISSUE TITLE
big-sur-arm64 binary

### ISSUE THREAD

**Issue by adamaltmejd** [Rdatatable/data.table#5033]
Have `https://Rdatatable.gitlab.io/data.table` set as a repo in `getOption("repos")` but `renv` produces the following warning at startup, guessing because the url 404s:

```
1: could not retrieve available packages for url 'https://Rdatatable.gitlab.io/data.table/bin/macosx/big-sur-arm64/contrib/4.1'
```

**Comment by jangorecki** [comment]
I don't know what is renv, please define your problem with the use of base R.

**Comment by jangorecki** [comment]
We don't produce binaries for Mac, not just big sure but any version of Mac. As of current moment.

**Comment by adamaltmejd** [comment]
Strange, maybe this started with an update of renv that coincided with me moving over from homebrew R 4.1 to the mac binary. Renv is here: `https://rstudio.github.io/renv/articles/renv.html`, and on startup I get that message. But maybe its got nothing to do with data.table, thanks!

**Comment by adamaltmejd** [comment]
Did not notice before but the warning message actually shows up when `install.packages()` is run too if `getOption("repos")` contains `"https://Rdatatable.gitlab.io/data.table"`

**Comment by jangorecki** [comment]
This will be addressed in https://github.com/Rdatatable/data.table/issues/3326

**Comment by adamaltmejd** [comment]
Still receiving the same warning. Should one not set the url in `option("repos")` on Mac anymore?

```
> install.packages("data.table")
Installing package into ‘/Users/adam/.R/packages’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://Rdatatable.gitlab.io/data.table/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'https://Rdatatable.gitlab.io/data.table/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'
```

**Comment by jangorecki** [comment]
You are attempting to install Mac binaries, try sources instead, "type" argument to install.packages

**Comment by adamaltmejd** [comment]
Sure, I know. My problem here is i guess mainly with renv which cannot access and retrieve the list of packages available at the data.table repository making it issue a warning at every startup. Don't know how repositories are structured but couldn't it be that you are missing some file indicating that a data.table binary is not available?

**Comment by jangorecki** [comment]
I think it may be issue with renv that assumes binaries are present.

**Comment by adamaltmejd** [comment]
Yeah. Filed an issue yesterday: https://github.com/rstudio/renv/issues/979

**Comment by adamaltmejd** [comment]
See https://github.com/rstudio/renv/issues/979#issuecomment-1097028040

Seems warning shows up in base R too because of missing PACKAGES file.
