### ISSUE TITLE
travis CI upgrade

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5036]
Seems that travis CI will be shut down on 15 June.
It may be good to move our travis CI to github actions, still keeping it as minimal as possible, to have fast feedback. Proper CI is working fine in GitLab CI.

**Comment by eddelbuettel** [comment]
As I understand it ravis-ci.org shuts down, yet travis-ci.com continues.  However one quickly runs out of credits there -- so moving to GitHub Actions is a good idea.  And I am :100: per cent with you on preferring minimal setups there.  The same vendor lock-in may ter happen there so I personally prefer to stay away from involved GitHub Actions 'recipes' and just use the same `run.sh` from my [r-ci](https://eddelbuettel.github.io/r-ci/) that works everywhere (Azure, Travis, GitHub and likely GitLab too) with its focus on quick and simple Linux tests using CRAN binaries for Ubuntu via Michael's PPA and Inaki's bspm package.

**Comment by tlapak** [comment]
Did the shutdown of travis CI take out our Codecov integration?
