### ISSUE TITLE
[R-Forge #2660] Improve fread na.strings handling

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#504]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2660&group_id=240&atid=975)

As raised [here](http://stackoverflow.com/questions/15784138/bad-interpretation-of-data-using-fread) and [here](http://stackoverflow.com/questions/22331552/read-in-certain-numbers-as-na-in-r-with-data-tablefread) on SO.

**Comment by arunsrinivasan** [comment]
:bump:

**Comment by PeterDee** [comment]
I was going to post this on SO but I found this issue so I'll instead provide a screenshot for the fread vs. read.table results - it's the main reason I've put off learning to use data.table. It's a pretty common data format with a few missing values in numeric columns. I wonder if people have been making sure to check their column classes after using fread: 
![fread_bug](https://cloud.githubusercontent.com/assets/8597866/8355827/f32acc56-1b94-11e5-8037-84018443d7db.png)

**Comment by dselivanov** [comment]
@arunsrinivasan, @mattdowle today I had a look into this.  
Seems `Strto*()` functions family from [fread.c](https://github.com/Rdatatable/data.table/blob/master/src/fread.c) should care about `na.strings` parameter. As of now the only one case is handled - `"NA"` strings. And the way this case  handled is not very agile. 
```c
if (lch==start && lch<eof-1 && *lch++=='N' && *lch++=='A' && (lch==eof || *lch==sep || *lch==eol)) {
        ch = lch;
        u.d = NA_REAL;
        return(TRUE);
    }
```
If you agree that this is work for these functions (not just post-processing at the end `readfile()` function ) , I have ideas how to fix this.

**Comment by arunsrinivasan** [comment]
Thanks again for the excellent fix @dselivanov. Opened another issue, #1314, for `na.strings="-999"` like cases.
