### ISSUE TITLE
[R-Forge #2611] := shouldn't print in knitr

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#505]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2611&group_id=240&atid=975)

As raised on SO [here](http://stackoverflow.com/questions/15267018/knitr-gets-tricked-by-data-table-assignment)

**Comment by rubenarslan** [comment]
In conjunction with using dplyr on a data.table, this still happens. Presumably the error can also occur when other classes remove `data.table` from being the pole position class.

Here's a reproducible Rmd file:

	`:=` prints in conjunction with dplyr, because dplyr adds all kind of classes to data.tables

	```{r}
	library(dplyr); library(data.table)
	mtcars = data.table(mtcars)

	grouped = mtcars %>% group_by(cyl)
	grouped[, mpg := 2]
	class(grouped)

	class(grouped) = c("data.table", "grouped_dt", "tbl_dt", "tbl", "data.frame") // reorder classes
	grouped[, mpg := 2]

	grouped = mtcars %>% group_by(cyl) %>% data.table()
	grouped[, mpg := 2]
	class(grouped)
	```

This is with data.table_1.9.5, dplyr_0.4.1 and knitr_1.9.
