### ISSUE TITLE
fread seg fault

### ISSUE THREAD

**Issue by ethanbsmith** [Rdatatable/data.table#5062]
`fread` caused r to crash. i suspect the input is malformed, as adding `quote = ""` works as expected
this was very difficult to track down because of the seg fault instead of an error.  fread is great and not looking for any changes here. if the error could be trapped and reported, might save someone some hair ;)

i dont control the input file, but have attached it for testing/repro

[nasdaqtraded.txt](https://github.com/Rdatatable/data.table/files/6754827/nasdaqtraded.txt)

`fread("nasdaqtraded.txt", sep = "|", fill = TRUE) #seg faults`
`fread("nasdaqtraded.txt", sep = "|", quote = "") #works as expected`

**Comment by MichaelChirico** [comment]
Can you confirm this still fails on the current dev version of data.table? we recently fixed an fread segfault.

If it's still failing on current master, please also include the output of verbose=TRUE leading up the segfault.

**Comment by tlapak** [comment]
I just tested it. It's fixed on dev.

**Comment by MichaelChirico** [comment]
#4774 #5041 are the duplicated issues, for posterity

**Comment by ethanbsmith** [comment]
ty! you folks are awesome
