### ISSUE TITLE
Message when loading through R notebooks: "Registered S3 method overwritten by 'data.table':"

### ISSUE THREAD

**Issue by wlandau** [Rdatatable/data.table#5103]

**Comment by wlandau** [comment]
Sorry for posting an issue without content initially. I accidentally hit the wrong keystroke.

When I load `data.table` through the R console, I see the usual messages about threads etc. But when I start a new session and load it through the [R Markdown notebook interface](https://bookdown.org/yihui/rmarkdown/notebook.html) in the RStudio IDE:

    ---
    title: "R Notebook"
    output:
      html_document:
        df_print: paged
    ---

    ```{r}
    library(dtplyr)
    ```

I also see:

```r
Show in New Window
Registered S3 method overwritten by 'data.table':
  method           from
  print.data.table   
```

This message also appears if I restart R and load a package that imports `data.table` functions, such as `dtplyr` or `targets`.

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

Please see above.

`#` `Output of sessionInfo()`

```r
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.0

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0    knitr_1.33     xfun_0.24     
```

**Comment by eddelbuettel** [comment]
Is this not the same as a) using one many ways in knitr to suppress console output and/or b) doing what I do most of the time, wrapping `suppressMessages(...)` around one or more `library(calls)`.  

I was able to confirm that I did get the message (as you state) when not wrapped, but no longer see it once I wrap:

![image](https://user-images.githubusercontent.com/673121/130167171-d5670815-98e2-4d9f-9d05-fab1cb412bd7.png)

**Comment by TimTaylor** [comment]
I think this might be an RStudio issue (see https://github.com/rstudio/rstudio/issues/9692). If you turn off diagnostics does that stop the problem? If it does would you mind giving a plus one on that issue and linking this.

**Comment by wlandau** [comment]
@TimTaylor, the message persists after I uncheck everything in global options -> code -> diagnostics. Likewise after I uncheck everything in global options -> code -> completion. But I went ahead and dropped a comment and thumbs up in that RStudio issue.

@eddelbuettel, the message does not bother me as a user, but it pops up for everyone using `targets` because of the dependency on `data.table`. I am starting to repeat myself when `targets` users ask me about it.

**Comment by eddelbuettel** [comment]
@wlandau  There is nothing (AFAIK) that 'team data.table' can do for you here.  That is base R, end of story. 

You recommend the following which shadows how other people load `dplyr` where R also (rightly !!) yells at them for duplicated symbols:

![image](https://user-images.githubusercontent.com/673121/130284766-ca7fc189-f6ad-4e78-b89d-6d987f9c87ae.png)

**Comment by TimTaylor** [comment]
@eddelbuettel I think you are right that this is not for 'team data.table' but it is not what base R is doing that is the issue rather it is something Rstudio is doing .... to clarify if you take @wlandau's example Rmd and replace the call with `library(data.table)` you will get the same message which is somewhat cyclic:
```
Registered S3 method overwritten by 'data.table':
  method           from
  print.data.table 
```
@wlandau you can stop it happening by setting `Chunk Output in Console`  - 
![Screenshot from 2021-08-20 21-10-49](https://user-images.githubusercontent.com/43499035/130288433-8876d00f-03cb-4c01-8839-6a6c316f06f1.png)

**Comment by wlandau** [comment]
Closing since this turned out to not be a `data.table` issue. Thanks for the input.

**Comment by eddelbuettel** [comment]
@TimTaylor I said so myself in https://github.com/Rdatatable/data.table/issues/5103#issuecomment-902371906 (see 2nd par).

**Comment by TimTaylor** [comment]
@eddelbuettel - we may have crossed wires but at least there is one less issue open. Perhaps semantics but I still think it is due to RStudio (but certainly could be wrong) as they override some s3 methods; see https://github.com/rstudio/rstudio/blob/edbc775214e1a46edd145ca6d37e14e2cded86e6/src/cpp/session/modules/NotebookData.R and  https://github.com/rstudio/rstudio/pull/2762/files

**Comment by eddelbuettel** [comment]
@TimTaylor If you go back and read what I wrote then you may agree that it boils down to a) me saying you can suppress library loading noise by wrapping in `suppressMessages()`, and b) me saying you can suppress library noise by add adding `warn.conflicts=FALSE` (as well as c) telling knitr to be quiet, which is yet another layer).  Neither has anything to with RStudio.   (They may be at fault for tickling noise relative to `dtplyr`; that is outside of my realm as I d) mostly run R outside of RStudio and e) do not use that package all that much, and hence f) almost surely not inside RStudio.)

I.e. 'a page full of noise' on the left with plain `library()` calls, two quiet lines on the right.

![image](https://user-images.githubusercontent.com/673121/130296814-f5bf5aeb-1d35-4c9f-8a3f-18d3d634670a.png)

I chimed in here in an attempt to be helpful to Will when nobody had yet answered his question. It was not my intend to upset or confuse you.  If I have done so, my bad.  Base R still works as instrumented when used as designed.  That's really all I was trying to reaffirm.   Peace out, and one issue down as you say.

**Comment by TimTaylor** [comment]
@eddelbuettel  Zero upset or confusion caused - we are just looking at the issue differently. Enjoy the weekend.
