### ISSUE TITLE
[R-Forge #5024] Cleanup help text for "key" in "?[.data.table"

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#511]
Submitted by: Ricardo Saporta; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5024&group_id=240&atid=5356)

Let's consider rewording the help text for key in  ?"[.data.table"

Specifically, (1) the dual-meaning of "x" (2) the last sentence as a whole could use elaboration. 

Currently reads: 

key: 
Character vector of one or more column names which is passed to setkey. It may be a single comma separated string such as key="x,y,z", or a vector of names such as key=c("x","y","z"). If specified in [.data.table, will change the key of x..

**Comment by MichaelChirico** [comment]
I suppose this can be closed? Since `key` is not an argument to `[.data.table`. And the last sentence is no longer in `?data.table`...

**Comment by arunsrinivasan** [comment]
Right, this doesn't need fixing anymore..
