### ISSUE TITLE
fread(text=) breaks down when text has length 1

### ISSUE THREAD

**Issue by michaelhallquist** [Rdatatable/data.table#5121]
I am using the `data.table::fread` command to parse a character vector that is the output of a system() call. It works very well, but breaks down strangely when the command only returns one row (i.e., when the character vector has length 1). Given that I use the `text=` argument, I don't know why I would get a complaint about a file not being found.

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

```
bad <- "JobID|help|test"
data.table::fread(text=bad)

good <- c("JobID|help|test", "123|okay|tested")
data.table::fread(text=good)
```

`#` `Output of sessionInfo()`

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.5.2

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.0

loaded via a namespace (and not attached):
[1] compiler_4.1.1 tools_4.1.1 
```

**Comment by avimallu** [comment]
Can you try using the latest devel? It works on my system, fixed by [this pull request](https://github.com/Rdatatable/data.table/pull/4703). Of course, the output may not be what you expect:

```
> bad <- "JobID|help|test"
> data.table::fread(text=bad)
Empty data.table (0 rows and 3 cols): JobID,help,test
> 
> good <- c("JobID|help|test", "123|okay|tested")
> data.table::fread(text=good)
   JobID help   test
1:   123 okay tested
```

but that can be easily fixed if you do

```
> data.table::fread(text=bad, header = FALSE)
      V1   V2   V3
1: JobID help test
```

**Comment by michaelhallquist** [comment]
Thanks for the follow-up! The latest dev version of the package works as expected (A zero-row data.table is what I had hoped for in this case). I will close this since the PR you mentioned was already merged into the master branch.
