### ISSUE TITLE
omp.h before Rincludes.h

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5122]
Received from Prof Brian Ripley today :

Subject: Packages including omp.h after Rincludes.h

That is

AMORE BNN BRISC OpenMPController RFCCA RFpredInterval RLT
RandomFields RandomFieldsUtils RandomForestsGLS RhpcBLASctl RxODE
STB TMB brnn coop data.table excursions float glinternet glmmTMB
gmGeostats graphscan hashr hutilscpp influenceR iq kit likeLTD
mRMRe magick meanShiftR meanr mnlogit poismf poppr praznik rFerns
randomForestSRC rasterKernelEstimates rehh simputation spBayes
spNNGP stringdist sylcount unfoldr

Compilation logs can be seen at
https://www.stats.ox.ac.uk/pub/bdr/clang13/ but beware these may only
show the first error.

The imminent clang 13.0.0 has an omp.h including
```
/* OpenMP 5.1 */
#if defined(_OPENMP) && _OPENMP >= 201811
  #pragma omp begin declare variant match(device={kind(host)})
  static inline int omp_is_initial_device(void) { return 1; }
  #pragma omp end declare variant
  #pragma omp begin declare variant match(device={kind(nohost)})
  static inline int omp_is_initial_device(void) { return 0; }
  #pragma omp end declare variant
#endif
```

whose use of match causes a compilation error if included after
Rinternals.h.  'Writing R Extensions' presents various workarounds, the
main one being the strong advice to include system headers before R headers.

Please correct before 2021-09-21 to safely retain your package on CRAN.

**Comment by MichaelChirico** [comment]
I guess it's release time then? unless we plan to just patch this in quickly

**Comment by mattdowle** [comment]
yep, release time

**Comment by mattdowle** [comment]
Thanks to Prof Ripley he provided a patch :  

---
I have attached the patch I used to get data.table to install with
clang-13.  Hope it helps.

If I had compiled code as complicated as yours I would consider using
R_NO_REMAP and adding Rf_ prefixes in the code.

[data.table.patch.txt](https://github.com/Rdatatable/data.table/files/7214364/data.table.patch.txt)

**Comment by mattdowle** [comment]
Thanks to Prof Ripley : 

---

This is still open for

AMORE BNN OpenMPController RandomFields RandomFieldsUtils data.table
graphscan influenceR likeLTD mnlogit spBayes unfoldr

This is a final reminder: the archival process will start on Sep 25.

**Comment by mattdowle** [comment]
Owing to the deadline, [v1.14.2](https://github.com/Rdatatable/data.table/milestone/24?closed=1) is now on CRAN which is a minimal patch of v1.14.0. The change to `as.character.hexmode()` in R-devel 6 days ago was caught that day (thanks to GLCI) and fix included before submitting 5 days ago.
