### ISSUE TITLE
revdep getDTeval affected

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5127]
Same as #5125

On line 138 of getDTeval it does : 
```
names(the.result) <- gsub(pattern = "`", replacement = "", x = names(the.result))
```
which drops the key and causes : 

```
> test_check("getDTeval")
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-getDteval.R:68:2): create a new column ────────────────────────
getDTeval(...) not equal to formulaic::snack.dat[, `:=`(age_decades, floor(get(age.name)/10))].
Datasets has different number of (non-excluded) attributes: target 2, current 3

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 4 ]
Error: Test failures
Execution halted
```

**Comment by tdhock** [comment]
git bisect says that this error started happening after merging https://github.com/Rdatatable/data.table/pull/5084

**Comment by mattdowle** [comment]
Thanks for doing the bisect, but did you see #5133 linked above which mentions that?

**Comment by tdhock** [comment]
I didn't, thanks for the info, glad to see there is a fix in the works!

**Comment by mattdowle** [comment]
I remember struggling with it. Hopefully fresh eyes will help.

**Comment by MichaelChirico** [comment]
This still reproduces on current `master` + CRAN `getDTeval`, and _not_ on CRAN data.table (1.14.10).

**Comment by MichaelChirico** [comment]
Minimized example (I didn't see a truly minimal example yet across the various issues & open PR)

```r
DT <- data.table(a = 1)
setindex(DT, a)
names(DT) <- "b"
"index" %in% names(attributes(DT))
# on CRAN
# [1] TRUE
# on master
# [1] FALSE
```

**Comment by tdhock** [comment]
I believe we should keep this open until the revdep fixes this.
I could contact them and ask for a fix, but I do not really understand the issue very well. Can some one who knows https://github.com/Rdatatable/data.table/pull/5849 better please explain how the revdep should fix?

**Comment by MichaelChirico** [comment]
Filed downstream: https://github.com/MB4511/getDTeval/pull/1

**Comment by MichaelChirico** [comment]
Now fixed+verified:

![image](https://github.com/Rdatatable/data.table/assets/7606389/c8ee8afd-246a-4490-8357-0c6a9148324d)
