### ISSUE TITLE
using cc() in current devel

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5131]
After removing .Rprofile file from project root dir, in current devel version, my dev workflow doesn't work anymore.
```
cd data.table
R
cc()
#Error in cc() : could not find function "cc"
```
how do you currently use `cc()`?  a global .Rprofile or something else?
sourcing `.dev/cc.R` doesn't seem to work as well
```
source(".dev/cc.R")
cc()
#Error in setwd(file.path(path, "src")) : cannot change working directory
```

**Comment by ben-schwen** [comment]
Sourcing `.dev/cc.r` works for me. I set the `PROJ_PATH` variable directly in my `.Renviron` file.

**Comment by mattdowle** [comment]
We had two .Rprofiles. Now we just have one in .dev. My link looks like this:

```
ls -l ~/.Rprofile 
/home/mdowle/.Rprofile -> /home/mdowle/GitHub/data.table/.dev/.Rprofile
```
That `.Rprofile` sets `PROJ_PATH` before sourcing `./dev/cc.R`.

**Comment by jangorecki** [comment]
Thanks, sounds good

**Comment by jangorecki** [comment]
Just for future reference, mine
```
cat ~/git/data.table/.Rprofile
Sys.setenv(PROJ_PATH="~/git/data.table")
source(".dev/cc.R")
```
