### ISSUE TITLE
argument to which is not logical

### ISSUE THREAD

**Issue by mcol** [Rdatatable/data.table#5135]
I've just come across this odd behaviour while attempting to remove columns containing only NAs from a data.table:

```
library(data.table)
dt <- data.table(iris)[, Petal.Length := NA]

dt[, which(sapply(.SD, function(z) all(is.na(z))))]            # works as expected
# Petal.Length
#            3

dt[, which(sapply(.SD, function(z) all(is.na(z)))) := NULL]    # error
# Error in which(sapply(.SD, function(z) all(is.na(z)))) :
#   argument to 'which' is not logical
```

There is probably a better way of achieving that, but in any case the error message is extremely puzzling!

`#` `Output of sessionInfo()`
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] data.table_1.14.0

loaded via a namespace (and not attached):
[1] compiler_3.6.3

**Comment by MichaelChirico** [comment]
.SD is not available on the LHS of :=

use `dt` instead

**Comment by mcol** [comment]
Would it be possible to mention that in the error message? As is it doesn't give any clue that that is the problem.

**Comment by MichaelChirico** [comment]
I'm afraid not. what's happening is that .SD is NULL until we populate it like normal. I suspect that it would be roughly equivalent effort to make .SD work on the LHS as it would be to give a helpful error in that case.

FWIW there is an open PR for fixing the referenced issue, so hopefully it can be fixed soon enough.
