### ISSUE TITLE
[R-Forge #2302] Add mnel's merge join syntax to FAQ (with timings)

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#515]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2302&group_id=240&atid=5356)

Highlighted in comments here :
http://stackoverflow.com/a/12773976/403310

**Comment by jangorecki** [comment]
This isssue is precisely about documenting full outer join using `[.data.table` join. Rather than adding it to FAQ, it is better to just document it in join vignette #2181. Will note it there, and close this issue as duplicate then.
