### ISSUE TITLE
Package 'data.table' is not available (for R version 3.1.1)

### ISSUE THREAD

**Issue by yinianwuyu** [Rdatatable/data.table#5171]
Package 'data.table' is not available (for R version 3.1.1)
when i tried to install 'data.table' in R (version 3.1.1) . 

But from the manual, it said 'Depends >= 3.1.0', 
can someone give some advice to install 'data.table' in R version 3.1.1?
Appreciation to your help!

**Comment by MichaelChirico** [comment]
this might be #5122 ... @mattdowle did we get archived from cran? 😬

**Comment by mattdowle** [comment]
We haven't been archived.
@yinianwuyu does any other package work?  I tried briefly in R 3.1.0 and no package works. Do you also see a 'unable to access index for repository' warning? What OS are you? You were asked to provide sessionInfo() when filing the issue. The OS makes a big difference as to binary vs source.

**Comment by mattdowle** [comment]
Removing the `s` from the `https` in the repo makes it work for me in R 3.1
```
options(repos="http://cloud.r-project.org")
install.packages("data.table")
```
If that works for you, please follow up with CRAN maintainers as it doesn't seem related to data.table.

R's message "Package 'data.table' is not available (for R version 3.1.1)" is often misleading in my experience in that it's rarely due to the version of R. Just ignore the parenthetic and think 'something is wrong'.

**Comment by jangorecki** [comment]
It is important to know if you are installing from binaries or sources. Anyway older R version were not well handling https, so as Matt suggested, just use http instead. If you want to use https then you should be able by installing curl in your OS (not R package) and use download.method option in R.

**Comment by mattdowle** [comment]
Please reopen if you still have problems and think it's specific to data.table.
R 3.1.1 is 7 years old now and as Jan said, R's package installation code has improved in that time.

**Comment by yinianwuyu** [comment]
Hi Matt, 
the sessionInfor as the following: 
>   sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.1.1

when i used
>   options(repos="http://cloud.r-project.org")
> install.packages("data.table")
it gave me the error message: 
Warning: unable to access index for repository http://cloud.r-project.org/bin/windows/contrib/3.1

   package ‘data.table’ is available as a source package but not as a binary

Warning message:
package ‘data.table’ is not available (for R version 3.1.1) 

Thank you very much for your answers!

**Comment by jangorecki** [comment]
@yinianwuyu did you try installing from sources? only if that fails then it may be something for our team to fix. Binaries is provided (or not) by CRAN, we just distribute sources. It is not surprising that binaries for very old versions of R are no longer being online. Try installing from package sources. You need Rtools installed, you can find it here: https://cran.r-project.org/bin/windows/Rtools/history.html

**Comment by mattdowle** [comment]
@yinianwuyu I did ask you "does any other package work? I tried briefly in R 3.1.0 and no package works." but you didn't answer that part.
Thanks for your output confirming that you also do see `Warning: unable to access index for repository http://cloud.r-project.org/bin/windows/contrib/3.1` which indicates not even being able to access the repository at all.
So I pasted `http://cloud.r-project.org/bin/windows/contrib/3.1` into my browser and it is "not found".
So then I removed the 3.1 at the end and found that `http://cloud.r-project.org/bin/windows/contrib/` is found and displays : 
![image](https://user-images.githubusercontent.com/2779998/134687114-6859ea04-d577-459d-ba70-fe71f774e523.png)
You can see that the entire 3.1 directory is not there, but 3.2 is.
However, that is not enough to think that 3.2 would be fine. You have to keep digging and exploring. For example, there's a Readme there. Always click the readme just in case. On this occasion it happens to be revealing : 
![image](https://user-images.githubusercontent.com/2779998/134687498-5d5ecff2-1ee0-4b35-8e7e-1c955efcccb5.png)

So you would have this problem with any package. You're just going to continue having problems with such an old version of R where you'll end up re-compiling all packages, or other problems if use very old versions of binary packages from the archive.

I'll say it more clearly : you must upgrade R.   7 year old R on WIndows is no longer supported by CRAN.

**Comment by MichaelChirico** [comment]
IMO this is a pretty good mark in favor of us bumping to a 3.2.0 dependency

**Comment by jangorecki** [comment]
OK but if there are no other good reasons for that. Every power user will manage to compile package on old R, old Rtools are easily available. So bumping version without good reason will only cause power users to have to edit DESCRIPTION file to change "3.2" to "3.1" so they can keep latest DT on their old production system upgraded. I repeat what I said already multiple times. I had job interview in UK in biggest cloud provider in the world, at the time of DT 1.9.8. They gave me problem to solve and machine with so old R that latest DT I was able to install was 1.8.8 (no rbindlist even). And this was the top company. From other non R software environment, I know that upgrading production environment is so risky subject that many times it is not made at all, as long as the system is working, no matter how many years ago support for a version has finished. I seen easily 10+ years systems after support.

**Comment by MichaelChirico** [comment]
Point well taken, however, such systems will also likely be using an old version of `data.table`. At some point, it's only reasonable to expect users updating to latest `data.table` to also update R...

**Comment by jangorecki** [comment]
Main difference of those upgrades is that for updating data.table you don't need sudo but to update R you need it.
