### ISSUE TITLE
r-oldrel-windows-ix86+x86_64 vignette error

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5181]
This WARN has just started today on CRAN with 1.14.2. But 1.14.2 is an utterly minimal patch of 1.14.0 so I doubt it's related to 1.14.2 per se. My guess is that r-oldrel checks run when the package is published on CRAN, but don't run again thereafter. So I'm thinking that something else is different on r-oldrel between the last publish date and now. The version of r-oldrel may well have changed in that time, for example. We have been seeing several fails on CRAN's windows recently due to packages not being available (like knitr) unrelated to data.table; those tend to get fixed by CRAN within a week or so.  But this one (`attempt to use zero-length variable name`) seems like it could be a data.table problem, perhaps under R 4.0.5.

```
using R version 4.0.5 (2021-03-31)
using platform: x86_64-w64-mingw32 (64-bit)
using session charset: ISO8859-1
checking for file 'data.table/DESCRIPTION' ... OK
this is package 'data.table' version '1.14.2'
checking package namespace information ... OK
checking package dependencies ... OK
checking if this is a source package ... OK
checking if there is a namespace ... OK
checking for hidden files and directories ... OK
checking for portable file names ... OK
checking whether package 'data.table' can be installed ... OK
checking installed package size ... OK
checking package directory ... OK
checking 'build' directory ... OK
checking DESCRIPTION meta-information ... OK
checking top-level files ... OK
checking for left-over files ... OK
checking index information ... OK
checking package subdirectories ... OK
checking R files for non-ASCII characters ... OK
checking R files for syntax errors ... OK
loading checks for arch 'i386'
checking whether the package can be loaded ... OK
checking whether the package can be loaded with stated dependencies ... OK
checking whether the package can be unloaded cleanly ... OK
checking whether the namespace can be loaded with stated dependencies ... OK
checking whether the namespace can be unloaded cleanly ... OK
checking loading without being on the library search path ... OK
checking use of S3 registration ... OK
loading checks for arch 'x64'
checking whether the package can be loaded ... OK
checking whether the package can be loaded with stated dependencies ... OK
checking whether the package can be unloaded cleanly ... OK
checking whether the namespace can be loaded with stated dependencies ... OK
checking whether the namespace can be unloaded cleanly ... OK
checking loading without being on the library search path ... OK
checking use of S3 registration ... OK
checking dependencies in R code ... OK
checking S3 generic/method consistency ... OK
checking replacement functions ... OK
checking foreign function calls ... OK
checking R code for possible problems ... [25s] OK
checking Rd files ... OK
checking Rd metadata ... OK
checking Rd cross-references ... OK
checking for missing documentation entries ... OK
checking for code/documentation mismatches ... OK
checking Rd \usage sections ... OK
checking Rd contents ... OK
checking for unstated dependencies in examples ... OK
checking line endings in shell scripts ... OK
checking line endings in C/C++/Fortran sources/headers ... OK
checking line endings in Makefiles ... OK
checking compilation flags in Makevars ... OK
checking for GNU extensions in Makefiles ... OK
checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
checking use of PKG_*FLAGS in Makefiles ... OK
checking pragmas in C/C++ headers and code ... OK
checking compiled code ... OK
checking installed files from 'inst/doc' ... OK
checking files in 'vignettes' ... OK
checking examples ...
running examples for arch 'i386' ... [7s] OK
running examples for arch 'x64' ... [8s] OK
checking for unstated dependencies in 'tests' ... OK
checking tests ...
running tests for arch 'i386' ... [199s] OK
  Running 'autoprint.R' [0s]
  Comparing 'autoprint.Rout' to 'autoprint.Rout.save' ... OK
  Running 'froll.R' [24s]
  Running 'knitr.R' [1s]
  Comparing 'knitr.Rout' to 'knitr.Rout.save' ... OK
  Running 'main.R' [172s]
  Running 'nafill.R' [2s]
  Running 'other.R' [0s]
  Running 'types.R' [0s]
running tests for arch 'x64' ... [222s] OK
  Running 'autoprint.R' [0s]
  Comparing 'autoprint.Rout' to 'autoprint.Rout.save' ... OK
  Running 'froll.R' [23s]
  Running 'knitr.R' [1s]
  Comparing 'knitr.Rout' to 'knitr.Rout.save' ... OK
  Running 'main.R' [195s]
  Running 'nafill.R' [2s]
  Running 'other.R' [0s]
  Running 'types.R' [0s]
checking for unstated dependencies in vignettes ... OK
checking package vignettes in 'inst/doc' ... OK
checking re-building of vignette outputs ... [41s] WARNING
Error(s) in re-building vignettes:
--- re-building 'datatable-benchmarking.Rmd' using rmarkdown
--- finished re-building 'datatable-benchmarking.Rmd'

--- re-building 'datatable-faq.Rmd' using rmarkdown
--- finished re-building 'datatable-faq.Rmd'

--- re-building 'datatable-importing.Rmd' using rmarkdown
--- finished re-building 'datatable-importing.Rmd'

--- re-building 'datatable-intro.Rmd' using rmarkdown
Loading required package: data.table
--- finished re-building 'datatable-intro.Rmd'

--- re-building 'datatable-keys-fast-subset.Rmd' using rmarkdown
Loading required package: data.table
--- finished re-building 'datatable-keys-fast-subset.Rmd'

--- re-building 'datatable-reference-semantics.Rmd' using rmarkdown
Loading required package: data.table
Quitting from lines 135-154 (datatable-reference-semantics.Rmd)
Error: processing vignette 'datatable-reference-semantics.Rmd' failed with diagnostics:
attempt to use zero-length variable name
--- failed re-building 'datatable-reference-semantics.Rmd'

--- re-building 'datatable-reshape.Rmd' using rmarkdown
Loading required package: data.table
--- finished re-building 'datatable-reshape.Rmd'

--- re-building 'datatable-sd-usage.Rmd' using rmarkdown
Loading required package: data.table
--- finished re-building 'datatable-sd-usage.Rmd'

--- re-building 'datatable-secondary-indices-and-auto-indexing.Rmd' using rmarkdown
Loading required package: data.table
--- finished re-building 'datatable-secondary-indices-and-auto-indexing.Rmd'

SUMMARY: processing the following file failed:
  'datatable-reference-semantics.Rmd'

Error: Vignette re-building failed.
Execution halted
checking PDF version of manual ... OK
DONE
Status: 1 WARNING
```

**Comment by MichaelChirico** [comment]
By luck I think I just found our bug -- it's a `knitr` update that just landed. I expect it'll cascade to the other flavors soon if that's the case:

https://github.com/yihui/knitr/blob/master/NEWS.md#major-changes

**Comment by mattdowle** [comment]
@MichaelChirico awesome, well spotted! I was actually scratching my head over why the last GLCI run failed on test-rel-lin and test-rel-win (with `Error: object 'Species' not found` in datatable-programming.Rmd ) but test-rel-cran-lin and test-rel-vanilla-lin passed fine. The `knitr` update might explain that too then.

The `knitr` update appears to be very odd, @yihui :

1. "attempt to use zero-length variable name" is deemed by @yihui as an acceptable error message (as it's documented in news) for the indents on ``` being inconsistent. If it was impossible to give a better error message than that, then the news item could have stated "sorry for the unhelpful error message but there's no known way to do better".

2. the `knitr` update breaks `data.table`. How was that ever published on CRAN without contacting data.table? CRAN runs revdep checks and the maintainer has to reply to CRAN to confirm that broken revdeps have been given adequate notice. I wonder, maybe revdep checks skip vignettes, but that would be very disappointing if nobody realized that, as the very point of `knitr` is for vignettes.

I've updated to knitr 1.35 released today and I now see the same error we see on GLCI, which is not the same as the one on CRAN. So it seems we have a 2nd problem caused by the knitr update, but it's in a different vignette and just in dev (maybe that vignette changed in dev) ...

**Comment by mattdowle** [comment]
This is strange: locally I see output below. I haven't applied your PR yet to fix the problem in `datatable-reference-semantics.Rmd`, so I was expecting to see that vignette fail, then I would apply your PR, confirm it's fixed, merge and move on. But that sematics.Rmd vignette passes OK. Instead it fails on `datatable-reference-semantics.Rmd` like it does on GLCI.

```
* checking running R code from vignettes ...
  ‘datatable-benchmarking.Rmd’ using ‘UTF-8’... OK
  ‘datatable-faq.Rmd’ using ‘UTF-8’... OK
  ‘datatable-importing.Rmd’ using ‘UTF-8’... OK
  ‘datatable-intro.Rmd’ using ‘UTF-8’... OK
  ‘datatable-keys-fast-subset.Rmd’ using ‘UTF-8’... OK
  ‘datatable-programming.Rmd’ using ‘UTF-8’... failed
  ‘datatable-reference-semantics.Rmd’ using ‘UTF-8’... OK
  ‘datatable-reshape.Rmd’ using ‘UTF-8’... OK
  ‘datatable-sd-usage.Rmd’ using ‘UTF-8’... OK
  ‘datatable-secondary-indices-and-auto-indexing.Rmd’ using ‘UTF-8’... OK
 ERROR
Errors in running code in vignettes:
when running code in ‘datatable-programming.Rmd’
  ...

> my_subset = function(data, col, val) {
+     subset(data, col == val)
+ }

> my_subset(iris, Species, "setosa")

  When sourcing ‘datatable-programming.R’:
Error: object 'Species' not found
Execution halted

* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR
```

**Comment by yihui** [comment]
> Instead it fails on `datatable-programming.Rmd`

This issue has been fixed in the dev version of **knitr**.

> If it was impossible to give a better error message than that, then the news item could have stated "sorry for the unhelpful error message but there's no known way to do better".

I wouldn't say "there's no known way" but it's indeed a tricky issue to me. Please give me a little more time to think about possible improvements.

> the `knitr` update breaks `data.table`. How was that ever published on CRAN without contacting data.table?

As I just explained in email, CRAN only requires revdep checks for hard reverse dependencies. In the case of data.table, it only Suggests knitr, so it was not checked. Had it been checked, I would have contacted you for sure...

**Comment by mattdowle** [comment]
Thanks @yihui. I replied to CRAN and you to say that, because the purpose of knitr is to build vignettes, you should check revdep vignettes (i.e. include reverse suggests). Otherwise, you've barely checked anything.

CRAN policy states :

>  If possible, check reverse strong dependencies, reverse suggests and the recursive strong dependencies of these (by tools::package_dependencies(reverse = TRUE, which = "most", recursive = "strong")).

Must we have a debate where we ask CRAN policy to add a sentence there: "But if the very point of your package is to be a soft depend, i.e. to be 'suggest'ed, then of course you should do this (i.e. include reverse suggests). Otherwise you aren't checking anything."

It takes me overnight (< 8 hours) to check 1,100 revdeps of data.table on my laptop, including their vignettes.  So, a guesstimate would be 2 days of runtime for you to check your 6,000 reverse suggests. On a laptop. You're at RStudio and have resources so couldn't you use a server with more cores, or use a spot instance?  Even on a 2nd laptop, given the importance of knitr, surely you can handle 2 days of runtime, running on a server, or something, somehow. 2 days of runtime is surely 'possible' for RStudio to handle.  1 month of runtime is understood to be 'not possible'. But just 2 days? That's possible.

As you may know, CRAN have become very strict, and I've seen packages taken off CRAN if they didn't clear errors or warnings within just 2 weeks. Which may now apply to data.table being in WARN status. I was recently given 3 weeks notice to comply with clang13 (barely even released) and was given a hard deadline of 25 Sep otherwise data.table would have been removed from CRAN, for example.

CRAN policy says : 

> If an update will change the package’s API and hence affect packages depending on it, it is expected that you will contact the maintainers of affected packages and suggest changes, and give them time (at least 2 weeks, ideally more) to prepare updates before submitting your updated package. Do mention in the submission email which packages are affected and that their maintainers have been informed. In order to derive the reverse dependencies of a package including the addresses of maintainers who have to be notified upon changes, the function reverse_dependencies_with_maintainers is available from the developer website.

But you're saying that doesn't include reverse suggests, so you don't do it. But I say the very point of knitr is to be suggested, as above.

**Comment by yihui** [comment]
No, I don't intend to debate. It was all my fault. Your points make perfect sense! Lessons learned, and I will try to do better next time. Thank you! BTW, I have just submitted a new version of knitr to CRAN, and also explained the situation to them (that it was my fault). Hopefully this problem will be resolved in the next day or two, and I think it's unlikely for data.table to be removed due to this problem.

**Comment by mattdowle** [comment]
@yihui Ok many thanks. I remember that this problem (knitr impact to reverse suggests not caught) has happened before, which I feel I should mention, so as to explain why on the 2nd time I became much more forthright.

**Comment by yihui** [comment]
I do appreciate you being forthright and I deserve the blame!
