### ISSUE TITLE
is.unsorted error on GLCI dev-win

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5198]
Seems related to https://github.com/wch/r-source/commit/e749e78ec0e66365297e12e7e6726de85355d99e in R-devel on Sep 28th. I `grep`'d all our source and we don't call `.Internal` on `is.unsorted`; those 2 tests just use regular `base::is.unsorted` at R level. The error isn't occurring on CRAN. So let's leave it a week to see what comes up (e.g. maybe it's been fixed in R-devel already) before spending time on it too early. Since an argument was added to the C functions, maybe a mismatch between R.dll and R code on Windows R CI is in play.

```
* using R Under development (unstable) (2021-10-04 r81003)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using options '--no-manual --ignore-vignettes'
* checking for file 'data.table/DESCRIPTION' ... OK
* this is package 'data.table' version '1.14.3'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'data.table' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... NOTE
Note: information on .o files for x64 is not available
File 'C:/GitLab-Runner/builds/Rdatatable/data.table/bus/test-dev-win/data.table.Rcheck/data.table/libs/x64/data_table.dll':
  Found '_exit', possibly from '_exit' (C)
  Found 'abort', possibly from 'abort' (C), 'runtime' (Fortran)
  Found 'exit', possibly from 'exit' (C), 'stop' (Fortran)
  Found 'printf', possibly from 'printf' (C)
Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs. The detected symbols are linked into the code but
might come from libraries and not actually be called.
See 'Writing portable packages' in the 'Writing R Extensions' manual.
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... SKIPPED
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'autoprint.R'
  Comparing 'autoprint.Rout' to 'autoprint.Rout.save' ... OK
  Running 'froll.R'
  Running 'knitr.R'
  Comparing 'knitr.Rout' to 'knitr.Rout.save' ... OK
  Running 'main.R'
  Running 'nafill.R'
  Running 'other.R'
  Running 'programming.R' ERROR
Running the tests in 'tests/main.R' failed.
Last 13 lines of output:
    OMP_NUM_THREADS                unset
    RestoreAfterFork               true
    data.table is using 1 threads with throttle==1024. See ?setDTthreads.
  test.data.table() running: C:/GitLab-Runner/builds/Rdatatable/data.table/bus/test-dev-win/data.table.Rcheck/data.table/tests/tests.Rraw
  Test 1760 not run because this session either has no OpenMP or has been limited to one thread (e.g. under UBSAN and ASAN)
  Test 1774.1 produced 1 errors but expected 0
  Expected: 
  Observed: 2 arguments passed to .Internal(is.unsorted) which requires 3
  Test 1774.11 produced 1 errors but expected 0
  Expected: 
  Observed: 2 arguments passed to .Internal(is.unsorted) which requires 3
  
  Tue Oct 05 18:18:00 2021  endian==little, sizeof(long double)==16, longdouble.digits==64, sizeof(pointer)==8, TZ=='UTC', Sys.timezone()=='UTC', Sys.getlocale()=='LC_COLLATE=C;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252', l10n_info()=='MBCS=FALSE; UTF-8=FALSE; Latin-1=TRUE; codepage=1252; system.codepage=1252', getDTthreads()=='OpenMP version (_OPENMP)==201511; omp_get_num_procs()==2; R_DATATABLE_NUM_PROCS_PERCENT==unset (default 50); R_DATATABLE_NUM_THREADS==unset; R_DATATABLE_THROTTLE==unset (default 1024); omp_get_thread_limit()==2147483647; omp_get_max_threads()==2; OMP_THREAD_LIMIT==unset; OMP_NUM_THREADS==unset; RestoreAfterFork==true; data.table is using 1 threads with throttle==1024. See ?setDTthreads.', zlibVersion()==1.2.11 ZLIB_VERSION==1.2.11
  Error: 2 error(s) out of 10512. Search tests/tests.Rraw for test number(s) 1774.1, 1774.11
  Execution halted
* DONE
```

**Comment by mattdowle** [comment]
Now the same problem is happening on GLCI rel-win.
https://gitlab.com/Rdatatable/data.table/-/jobs/1840155050
Likely because R-devel has been released now as R 4.1.2.
However, the GLCI log also shows a download error:
```
ERROR: Downloading artifacts from coordinator... error couldn't execute GET against https://gitlab.com/api/v4/jobs/1840155024/artifacts?direct_download=true: Get https://storage.googleapis.com/gitlab-gprd-artifacts/b0/a4/b0a4138c4fbd165ae5b27b493c3472ed9aab1a358cdd2aa2ed465fe58c062208/2021_12_01/1840155024/1992723977/artifacts.zip?GoogleAccessId=gitlab-object-storage-prd@gitlab-production.iam.gserviceaccount.com&Signature=ZIymlMu1vJSqB3iBGs9H4mpRYljMw%2F087%2B81KcrZpAzbjW9S5ecQu0btaCVn%0AgZkF6EQuoLNsKb7z7GAae%2FhYC14ylizIoiFbu7ChsvQI93zloenACq3Wuwdt%0A1Tj2r5XfKKIq9o2%2F3%2BPcnsjHkr1Fsqhr4Jkl88wvhpn5BgnoIZWi2HcMMwA2%0AwGJc10%2BpYHj%2FKmE%2BZBlB508YAYBumDOvlLz%2BIHLtNMNexX239oRDwq%2Fkitjn%0AWATrAGTn5%2BvGBXlqZPm5HOP5Gybl41%2F0KsBUd1K84ao9%2Bvpel2BqId53JtSX%0AOKUWuTJhXHruZkdIqhABeIb7qORSqmFl%2Bp3eE4y5Ng%3D%3D&Expires=1638398785: x509: certificate signed by unknown authority  id=1840155024 token=Z1extixf
```
and it seems to be using R 4.1.0 (2021-05-18) which is 2 releases ago; i.e. it didn't update to R-4.1.1 (2021-08-10) either it seems. Maybe if the certificate problem were fixed, it could update. But I don't know how to update the certificates, or why that is a step that needs to exist.
AppVeyor is running fine; i.e. testing every PR on every commit using R 4.1.2 on Windows automatically and we didn't need to do anything.
Given that GLCI is blocked currently and not reaching publish step, and that AppVeyor covers it, I'll turn off rel-win

**Comment by jangorecki** [comment]
Yes, this job produces binaries to be published in R repo.
I think we only need to update links here https://github.com/Rdatatable/data.table/blob/b28b496ee487b6bf21c559bf0867223dd59f03e1/.gitlab-ci.yml#L98
I recall raising that to R-devel and Jeroen Ooms (he was working around win builds) to provide urls that will alias to r-rel and r-oldrel, but I haven't heard that to be addressed.

**Comment by mattdowle** [comment]
I attempted to use the stable link mentioned on https://cloud.r-project.org/bin/windows/base/ :

![image](https://user-images.githubusercontent.com/2779998/144496908-16436715-b16d-4014-88e5-0230c1ff120f.png)

i.e. I tried that in ef4d24c.  But that appears to result in `Start-Process : This command cannot be run due to the error: The file or directory is corrupted and unreadable.` : 

![image](https://user-images.githubusercontent.com/2779998/144496709-7aa7b812-528f-41a4-8301-08f136d62016.png)

> Keep the ./old/ for r-rel as well because on the new release they move the file from ./ to ./old/ and url doesn't work anymore.

I appreciate the intent here to keep the GLCI pipeline working when a new version of R is released, but I'd prefer it to break so that we know the link needs to be updated rather than it continuing to use an older version of R without us knowing as it has been doing it seems. That's why I'm now going to try https://cloud.r-project.org/bin/windows/base/R-4.1.2-win.exe (i.e. without `/old`) which is expected to work. Well, in terms of grabbing the latest R-release anyway: the error `WARNING: Failed to load system CertPool: crypto/x509: system root pool is not available on Windows` occurs earlier in the log and I suspect that will still need to be solved. As they are warnings maybe the script will complete. Maybe @jangorecki you know what those warnings might be about and point me in the right direction to investigate.

@jeroen The link https://cloud.r-project.org/bin/windows/base/release.html does work for me in my browser (Chrome) in that it does automatically redirect to https://cloud.r-project.org/bin/windows/base/R-4.1.2-win.exe and Chrome starts to download that .exe no problem. However, when I passed that to curl.exe, I got the error above, maybe because it is an auto-forward or something like that. There is a link for R-devel `https://cloud.r-project.org/bin/windows/base/R-devel-win.exe` which we use here and works and downloads the latest R-devel-win.exe as that updates every day. So in the same way, would it be possible for you to provide a link `https://cloud.r-project.org/bin/windows/base/R-release-win.exe` instead of (or as well as) the auto-forward `.html` link https://cloud.r-project.org/bin/windows/base/release.html? Or maybe you can see a different better way forward. I'm not sure you're the right person, but I thought I'd start with you because Jan mentioned you. Thanks.

**Comment by mattdowle** [comment]
That worked, the is.unsorted 3 vs 2 argument mismatch has gone away, and GLCI is passing now. Hence closing.
The `Failed to load system CertPool` warnings are still there, but started new issue #5278 for that.

**Comment by jangorecki** [comment]
I checked now and looks like CRAN does provide r-release version inside /old dir as well, resolving problem of broken link after r version upgrade.
