### ISSUE TITLE
[R-Forge #1061] Expand documentation on self joins

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#521]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1061&group_id=240&atid=5356)

Add worked example and timing difference between SJ and J as mentioned here :
http://r.789695.n4.nabble.com/Data-table-syntax-tp2527407p2530508.html

**Comment by jangorecki** [comment]
Problem describe in that email can be now (and for quite few years already) be solved using rolling join. At the time of the question, 2010, it wasn't probably in data.table yet.
Recent dev:
```r
library(data.table)
N=1e7
dt=data.table(i=sample(1:(N/10), N, TRUE), t=sample(letters, N, TRUE), v=rnorm(N), key=c("i","t"))
system.time(dt[SJ(i, "a")])
#   user  system elapsed 
#   1.14    0.28    1.46 
system.time(dt[J(i, "a")])
#   user  system elapsed 
#   1.16    0.23    1.40
```
If you have any clear picture what precisely do in this issue feel free to reopen.
