### ISSUE TITLE
Improve "Aggregate function missing, defaulting to 'length'" message

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#5217]
My guess is that most often, this happens by mistake, in which case a new/inexperienced user's response is likely along the lines of "aggregation? what aggregation?".

The culprit is here:

https://github.com/Rdatatable/data.table/blob/c6f6dd80b7ad565d9a78221fbe32ea0c5e0bf547/R/fcast.R#L156-L162

Almost certainly we can use that `forderv` output to provide a bit more context for diagnosing the issue.

**Comment by akshat-max** [comment]
Hey I am newbie to open source if this issue is open I would love to work on it can you please assign me and provide some resources what I need to do?

**Comment by MichaelChirico** [comment]
Hi @akshat-max sorry for the long delay. Just assigned you.

The goal is to improve the user experience of the message encountered in this scenario:

```
DT = data.table(grp1 = rep(1:2, 4), grp2 = rep(rep(1:2, 2), 2), val = 1:8)

dcast(DT, grp1 ~ grp2, value.var="val")
```

throws `message()`:

```
Aggregate function missing, defaulting to 'length'
```

with output:

```
Key: <grp1>
    grp1     1     2
   <int> <int> <int>
1:     1     4     0
2:     2     0     4
```

What's happened is that rows are not uniquely identified by combinations of `grp1` and `grp2`, i.e., `anyDuplicated(DT, by = c("grp1", "grp2")) != 0L`.

The message should provide some more helpful information to the user in case this message is unexpected (which is likely in the case that `fun.aggregate` is missing). 

You can try running `debugonce(data.table:::dcast.data.table)` before running `dcast(DT, grp1 ~ grp2, value.var="val")` to see the code that generates the message.

**Comment by MichaelChirico** [comment]
Thanks @Nj221102! I would say no. Per the issue description, my main concern with the existing message is that it's often encountered by mistake when running `dcast(DT, x ~ y)` where `(x, y)` don't uniquely identify rows within `DT` (see example above). Beginner users might not even know that `fun.aggregate=` is an option, nor how to use it.

So a much better message would give some detail about which group(s) was(were) duplicate (to help debug, if that was not intended), and point to `?dcast` for further details about `fun.aggregate=`. And we should ensure some pithy examples in `?dcast` explain this aspect of `fun.aggregate=` as well.

**Comment by Nj221102** [comment]
<img width="898" alt="Screenshot 2024-03-05 at 1 44 17 AM" src="https://github.com/Rdatatable/data.table/assets/151559388/d9d5946e-5531-41af-aa88-058209639687">

Hi @MichaelChirico This is the warning i have come up with, if you think there can be further changes to improve this plz suggest and if not i will make the PR.

"When combinations of rows and columns aren't unique, it means that certain combinations repeat in the data table, pointing to more than one value. However, we need a single representative value for each combination. This can be achieved using an aggregation function, which merges multiple values into one as required by the user. Functions like mean or sum can be used for this purpose.

If no aggregation function is explicitly specified, the length of values (i.e., the number of different values associated with each combination) is used as the unique value. If you want to customize this behavior, you can input your desired aggregation function to manipulate the values accordingly.

For more information, you can type `?dcast` in the terminal."

**Comment by MichaelChirico** [comment]
looks like a great start! please feel free to open a PR and we can iterate from there.

**Comment by tdhock** [comment]
I agree with Michael, "a much better message would give some detail about which group(s) was(were) duplicate (to help debug, if that was not intended)"
in your example it would be helpful if you could add something like:
The columns=values with more than one resulting row are: grp1=1,grp2=1 and grp1=2,grp2=2

**Comment by Nj221102** [comment]
> I agree with Michael, "a much better message would give some detail about which group(s) was(were) duplicate (to help debug, if that was not intended)" in your example it would be helpful if you could add something like: The columns=values with more than one resulting row are: grp1=1,grp2=1 and grp1=2,grp2=2

well i have made the draft PR and I am going to work on adding this feature as well :)
