### ISSUE TITLE
Does data.table have a release schedule or estimated date of next CRAN version?

### ISSUE THREAD

**Issue by JoshOBrien** [Rdatatable/data.table#5219]
I'm asking because I've put together  a PR for the **sf** package that will produce pretty printing of simple feature geometry columns in data.tables. It relies, though, on the new `format_list_item` generic, introduced in the development version, v1.14.3, so I'll wait until v1.14.4 to submit that.

Is there somewhere I can look to see an estimate of when the next version will be submitted to CRAN?

**Comment by avimallu** [comment]
[This ](https://github.com/Rdatatable/data.table/pull/5201#issuecomment-939331602) might help.

**Comment by JoshOBrien** [comment]
@avimallu Thanks! That is helpful.
