### ISSUE TITLE
Incorrect date + time writing via fwrite (.: 00Z) ISO

### ISSUE THREAD

**Issue by avraam-inside** [Rdatatable/data.table#5238]
Hey!

```r
data.table::fwrite(
  x    = data.table::as.data.table(
          anytime::anytime(1678296152.99999952316284179688)), 
  file = here::here('test.csv'))
```

If we transfer the following code with a digit to a normal date + time + milliseconds, and then write it to a file, then we get an incorrect record: `2023-03-08T17:22:32.:00Z`

Why does fwrite round like this? The problem is that I then need to transfer this record format to another system, and its developers are sure that such a record does not meet any standards (like me) and do not want to change their parsers for this.

On my side, I, of course, did rounding, but I would like to get the correct record right away, not `.:00Z`

**Comment by tlapak** [comment]
Looks like this is an unhandled edge case in the rounding of microseconds to six digits. The correct output should be either `2023-03-08T17:22:33Z` or `2023-03-08T17:22:32.000000Z` although `fwrite` currently uses the former when microseconds round down to 0.
