### ISSUE TITLE
`rbindlist` fails for an empty `by` object

### ISSUE THREAD

**Issue by OfekShilon** [Rdatatable/data.table#5258]
Example:
```
df       <- data.frame(a=seq(10), b=rep(1:2, 5))
df.empty <- subset(df, a>10)
byy       <- by(data=df,       INDICES=df$b, FUN=function(x) x[1,])
byy.empty <- by(data=df.empty, INDICES=df.empty$b, FUN=function(x) x[1,])

class(byy)       # "by"
class(byy.empty) # "by"

is.list(byy)        # TRUE
is.list(byy.empty)  # FALSE - might qualify as an R bug

rbind(byy)        # succeeds
rbind(byy.empty)  # succeeds

rbindlist(byy)        # succeeds
rbindlist(byy.empty)  # fails:  "Input is by but should be a plain list of items to be stacked"
```

The direct reason is [this line](https://github.com/Rdatatable/data.table/blame/f8556cbd99e09b0a6117300597dbe38ab03ee3bd/R/data.table.R#L2547) in rbindlist.  

Regardless of `is.list`'s weird behavior, `rbind` succeeds for this case so we hope `rbindlist` can too.

Tested on R3.4.0 and  R4.0.5

**Comment by ben-schwen** [comment]
I guess you could fix your example by changing to `by(, simplify=FALSE)` if that's an option.

There is also a documented difference between `rbindlist` and `rbind` where `rbindlist` demands a list as the first argument (which is also in its name) and `rbind` accepts vectors and matrices and also coerces other suitable objects.

**Comment by OfekShilon** [comment]
> I guess you could fix your example by changing to `by(, simplify=FALSE)` if that's an option.

Thanks. I already worked around it in a different manner, just thought I'd report it.

> 
> The behavior of `is.list(byy.empty)` is explainable because the underlying object is not a `list` but an atomic vector of length 0 and type `logical` which can be seen by `str(byy.empty)` or if we really want to look deep `.Internal(inspect(byy.empty))`.
> 
> ```r
> str(byy.empty)
> # 'by' logi[0 (1d)] 
> # - attr(*, "dimnames")=List of 1
> #  ..$ df.empty$b: NULL
> # - attr(*, "call")= language by.data.frame(data = df.empty, INDICES = df.empty$b, FUN = function(x) x[1, ])
> 
> .Internal(inspect(byy.empty))
> # @562347ad23c0 10 LGLSXP g0c0 [OBJ,MARK,REF(4),ATT] (len=0, tl=0)
> # trimmed ATTRIB here
> ```

I'd say any questions about the class of an object (whether directly via `class` or indirectly via `is.**`) should not have the answers depend on the specific contents of the object, eg whether it's empty. Peeking inside the implementation might be a step in debugging this behavior, not quite an explanation for it.

> There is also a documented difference between `rbindlist` and `rbind` where `rbindlist` demands a list as the first argument (which is also in its name) and `rbind` accepts vectors and matrices and also coerces other suitable objects.

I'll try to take it up with the R guys then.

**Comment by ben-schwen** [comment]
> I'd say any questions about the class of an object (whether directly via class or indirectly via is.**) should not have the answers depend on the specific contents of the object, eg whether it's empty. 

And you can totally achieve this with `by( , simplify=FALSE)` as also mentioned in the docs of `?by` which ensures that the resulting object is a list and not converted to something different.

Keeping in mind that many people from different fields who are not trained computer scientists use `R`, I'm quite convinced that R-core won't change the behavior of `sapply`, `tapply` and friends, by e.g., setting `simplify=FALSE` as default but you can always try.

**Comment by OfekShilon** [comment]
@ben-schwen  - you're right, thanks!   Shall I close the issue?
