### ISSUE TITLE
[R-Forge #5679] more advanced combining of j-expression results

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#526]
Submitted by: Eduard Antonyan; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5679&group_id=240&atid=978)

Currently j-expression results are rbind'd together, ignoring any column names and failing if number of columns don't match.

A suggestion is to add an extra argument to [.data.table that would indicate how to combine the results. Some additional combine options are - have use.names/fill-like options as in rbind, leave it as a plain list (i.e. don't combine to a data.table).

SO thread about, see comments in: http://stackoverflow.com/a/16695110/817778

**Comment by MichaelChirico** [comment]
Doesn't seem like much follow-up demand for this. Original SO question should be handled by addition of `split.data.table` method as pointed out by @jangorecki in comments there.

Close this?

**Comment by jangorecki** [comment]
Split is very inefficient as it only wraps on `[` call, but it doesn't seems to come up often. If there is a need, we can always re-open.
