### ISSUE TITLE
Inconsistency in data.frame and tibble join on x

### ISSUE THREAD

**Issue by avimallu** [Rdatatable/data.table#5260]
In the current development version of `data.table`, installed via

```r
install.packages("data.table", repos = "https://Rdatatable.gitlab.io/data.table")
```

The following command works:

```r
> library(data.table)
> library(tibble)
> DT = data.table(x = 1:3, y = letters[1:3])
> TBL = tibble(y = letters[1:3], b = 5:7)
> DT[TBL, on = "y"]
   x y b
1: 1 a 5
2: 2 b 6
3: 3 c 7
```

But in the current version on CRAN (1.14.2) at the time of writing this report, it does not, and throws the error:

```r
> library(data.table)
> library(tibble)
> DT = data.table(x = 1:3, y = letters[1:3])
> TBL = tibble(y = letters[1:3], b = 5:7)
> DT[TBL, on = "y"]
Error in `[.data.table`(DT, TBL, on = "y") : 
  logical error. i is not a data.table, but 'on' argument is provided.
```

Which is confusing, because the code below works in both versions:

```r
DT[as.data.frame(TBL), on = "y"]
```

I cannot find any news bullet that will account for the difference in behaviour between the two versions (save for item 28 under bug fixed, but that has to do with the way `dplyr` treats `data.table`s and not the other way around). I want to highlight this inconsistency because while my code was working on my system, it stopped working on someone else's who was on the CRAN version.

**Comment by MichaelChirico** [comment]
if you want to practice some git skills, you could try to use `git bisect` to identify when it was fixed:

https://www.metaltoad.com/blog/beginners-guide-git-bisect-process-elimination

https://git-scm.com/docs/git-bisect

**Comment by avimallu** [comment]
I just learn `git bisect` so many years later, but as I was about to test this issue out, I realized that the code I wrote is working now. Closing.
