### ISSUE TITLE
as.xts.data.table is limited to numeric data types, but this is not an xts limitation

### ISSUE THREAD

**Issue by ethanbsmith** [Rdatatable/data.table#5268]
`xts` allows columns to have any type, as long as the columns are all the same type (as its really a matrix under the hood)

for example, you can have character columns:
`xts(x = cbind(letters, LETTERS), order.by = Sys.Date() + (1:26))`

logicals:
`xts(x = c(T,F), order.by = Sys.Date() + (1:2))`

`as.xts.data.table` currently only allows conversion for numeric columns. it should follow the same rules as `xts` and support any type

**Comment by ethanbsmith** [comment]
i was going to work on a pr to essentially just do:
`xts::xts(as.matrix(x), order.by = if ("IDate" %chin% class(x[[1L]])) as.Date(x[[1L]]) else x[[1L]])`
which i think is the proper way to handle the conversion. However, this will be a breaking change.  Any thoughts or suggestions?

**Comment by ben-schwen** [comment]
Best option imho would be to establish type counts via `table(vapply_1c(x[,-1L], mode))` and filter for the most occurring type. Maybe even establish some kind of tie-breaker with `numeric` > ...

**Comment by ethanbsmith** [comment]
wont mode based column filtering still be a potential breaking change? shouldn't the caller should really be responsible for subsetting which columns to include

using `to.matrix` has a reliable, standard , expected outcome. it turns this function into handling just handling the index conversion between a data column and an attribute, which is a good piece of functionality

one option would be to add a `numerics.only` argument that would default to `TRUE` for backward compatibility, The default could be changed/removed on a later version

**Comment by ethanbsmith** [comment]
There is also a significant performance gain to using `data.table` awesome `as.matrix` implementation. some benchmarks on a ~20 million row OHLCV data table:

```R
> z
               index        Open        High         Low       Close   Volume
       1: 1962-01-02   0.4226460   0.4226460   0.4153361   0.4153361   704396
       2: 1962-01-03   0.4215661   0.4298728   0.4215661   0.4236428  1420820
       3: 1962-01-04   0.4236428   0.4309527   0.4194894   0.4194894  1822013
       4: 1962-01-05   0.4194894   0.4215661   0.3997194   0.4111827  1760777
       5: 1962-01-08   0.4111827   0.4184926   0.4060325   0.4121795   947213
      ---                                                                    
19911740: 2021-11-15 227.3700000 233.9400000 226.9200000 233.0900000 21921856
19911741: 2021-11-16 232.9400000 232.9500000 225.5100000 225.8000000 10120193
19911742: 2021-11-17 229.5400000 231.3200000 224.2000000 226.6200000 10750940
19911743: 2021-11-18 230.3000000 231.5000000 224.9510000 227.2500000 10983711
19911744: 2021-11-19 225.0700000 225.3300000 213.2300000 214.1300000 20844074
```

```R
> microbenchmark(as.xts(setDF(z[,-1L]), order.by = z[[1L]]),
+                xts(setDF(z[,-1L]), order.by = z[[1L]]),
+                xts(as.matrix(z[,-1L]), order.by = z[[1L]]), times = 5)
Unit: seconds
                                         expr       min        lq      mean    median        uq      max neval
  as.xts(setDF(z[, -1L]), order.by = z[[1L]]) 12.374819 16.449329 17.465670 16.517783 18.019016 23.96741     5
     xts(setDF(z[, -1L]), order.by = z[[1L]]) 11.876490 14.277099 17.339480 19.085982 19.989391 21.46844     5
 xts(as.matrix(z[, -1L]), order.by = z[[1L]])  4.237925  4.315352  6.064066  4.817026  5.817695 11.13233     5
```

**Comment by ethanbsmith** [comment]
to disambiguate the issues, this is what i see:

1. handling mixed type tables. here i think `as.matrix` is the best option as it provides a standard, deterministic result
2. handling backward compatibility. here i think a new parameter that optimizes a common use case is best
3. where should the conversion to a matrix be done? here i think the optimized dt `as.matrix` is best
