### ISSUE TITLE
WARNING: Failed to load system CertPool: crypto/x509: system root pool is not available on Windows

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5278]
From GLCI rel-win: https://gitlab.com/Rdatatable/data.table/-/jobs/1844394128

![image](https://user-images.githubusercontent.com/2779998/144511108-dddd25a4-57ba-4e8b-b68f-d8064747378d.png)

@jangorecki rel-win looks to be passing now but these warnings are still there. Any idea? I searched and found some issues online, but I'm not sure what to do after reading them.
https://stackoverflow.com/questions/41840307/warning-about-system-root-certificate-pool-crypto-x509
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/3035

**Comment by jangorecki** [comment]
These warnings AFAIR were there from the very beginning.
From reading gitlab issue you linked is looks to be known issue. There is even a 4 weeks old PR aiming to address it. I am pretty sure we can ignore it, and warning should disappear once gitlab will address this issue.

**Comment by mattdowle** [comment]
Thanks. Latest run is now error status and blocking GLCI pipeline. I don't see the difference though why it failed with exit status 1 this time. Do you?  https://gitlab.com/Rdatatable/data.table/-/jobs/1844743635

**Comment by mattdowle** [comment]
I tried rerunning it, i.e. pressing retry button when logged in to GitLab UI, and it passed. Disconcerting but at least it works again and the GLCI pipeline is complete.
So indeed it seems like we can ignore these particular warning/errors. I see they appear in the dev-win and old-win logs too.
