### ISSUE TITLE
`update.packages` goes further than CRAN?

### ISSUE THREAD

**Issue by OfekShilon** [Rdatatable/data.table#5281]
As of Dec 4, 2021, `update.packages(oldPkgs="data.table")` brings in data.table v1.14.3, which news.md still lists as 'in development':

>![image](https://user-images.githubusercontent.com/73080/144757779-feecf711-6970-41b8-b4dd-dbb9ad901c82.png)

The version listed officially in CRAN is 1.14.2:

>![image](https://user-images.githubusercontent.com/73080/144757825-a0368178-39ca-439d-bd67-cf01427da53b.png)

And the last tagged version is 1.14.0:
>![image](https://user-images.githubusercontent.com/73080/144757891-38920bc9-2de6-460a-959d-b73119a45a62.png)

Is there a versioning policy?  Can I get `update.packages` to use the last _stable_ version?
Is the diff between the version publicly shown on CRAN and the one brought in by `update.packages` somehow intentional?

**Comment by avimallu** [comment]
I don't seem to get the development version when I run that command on a fresh session:

```r
> update.packages(oldPkgs="data.table")
> library(data.table)
data.table 1.14.2 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com
Warning message:
package ‘data.table’ was built under R version 4.1.2
```

This is my system:

```r
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.2

loaded via a namespace (and not attached):
[1] compiler_4.1.1 tools_4.1.1
```

**Comment by ben-schwen** [comment]
`update.packages` only performs an install if the version on CRAN is newer than your locale version. To force the installation of the last stable version one could `install.packages` but that  has the downside that it will always run.

I guess we could add a boolean argument `stable` or `CRAN` to `update.dev.pkg` if that's the desired feature.

**Comment by jangorecki** [comment]
Check your repos option. You may have set a DT devel repo there, then update.packages automatically resolves from that repo.

**Comment by OfekShilon** [comment]
@jangorecki  
```r
> getOption("repos")
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE
```
I'll try to reproduce the exact upgrade sequence on some clean machine and post here.

**Comment by jangorecki** [comment]
I will close it for now. We can reopen issue when it will be possible to reproduce it.
