### ISSUE TITLE
Tests fail when run with some non-default options

### ISSUE THREAD

**Issue by OfekShilon** [Rdatatable/data.table#5285]
```
options(warn=2)
test.data.table()
```
Would result in multiple failures. Also:
```
options(digits=17)
test.data.table()
```
Probably best to add to `oldOptions` in `test.data.table`:
```
...
 warn = 1,
 digits = 7
```

`#` `Output of sessionInfo()`
R 4.0.5, data.table 1.14.3

**Comment by ben-schwen** [comment]
Similar to #4936 and #4633
