### ISSUE TITLE
[R-Forge #5610] fread: handle multiple whitespace as delimiter

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#529]
Submitted by: Matthew Forrest; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5610&group_id=240&atid=978)

This has come up in forums a couple of times.  Basically it would be fantastic to be able to use sep="" in fread to use multiple whitespaces as the separator analogously to how it works in read.table.  Sometimes one cannot get away from data files which have multiple spaces as column separators to make it easy for humans to read, but not so much for fread!

I know it is on Matt Dowle's radar since this stackoverflow post (which also has a handy workaround)

http://stackoverflow.com/questions/22229109/r-data-table-fread-command-how-to-read-large-files-with-irregular-separators

but I thought I would formalise it into a feature request here.  Also, thanks for data.table, it is great!

**Comment by arunsrinivasan** [comment]
Fixed in devel. Please upgrade and test.

**Comment by skanskan** [comment]
Hello.
What about handling mixed separators as if they where just one?
for example sometimes the file has tabs and spaces.

**Comment by sariya** [comment]
>for example sometimes the file has tabs and spaces.

Is there a way this could be achieved in data.table? `data.table_1.13.0` and `R4.0` 
thanks
