### ISSUE TITLE
GLCI dev-win magrittr error

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5294]
Currently seeing the following error which is blocked GLCI deployment.

https://gitlab.com/Rdatatable/data.table/-/jobs/1893814876

```
$ Rscript.exe -e "source('.ci/ci.R'); install.packages(dcf.dependencies('DESCRIPTION', which='most'), quiet=TRUE)"
  There are binary versions available but the source versions are later:
        binary source needs_compilation
glue     1.5.0  1.5.1              TRUE
stringi  1.7.5  1.7.6              TRUE
digest  0.6.28 0.6.29              TRUE
also installing the dependencies 'glue', 'magrittr', 'stringi', 'digest', 'base64enc', 'rlang', 'fastmap', 'R.oo', 'R.methodsS3', 'RcppCCTZ', 'Rcpp', 'RcppDate', 'evaluate', 'highr', 'stringr', 'xfun', 'htmltools', 'jsonlite', 'tinytex', 'jquerylib', 'mime'
package 'magrittr' successfully unpacked and MD5 sums checked
Error in unpackPkgZip(foundpkgs[okp, 2L], foundpkgs[okp, 1L], lib, libs_only,  : 
  package 'magrittr' not installed because it is not built for UCRT
Calls: install.packages -> .install.winbinary -> unpackPkgZip
Execution halted
```

On the pipelines page I pressed the 'Clear runner caches' at the top the page, and reran this job, without luck.

@jangorecki Any ideas on how to go about fixing this please?  I'm really looking for pointers, commands, and instructions so that other people can proceed to investigate.

**Comment by jangorecki** [comment]
Seems to be related to changes in win dev for uctr. Changing line to build dependencies from source rather than binaries could help. Or eventually waiting, as I believe it affects more packages, so possibly can be fixed later on in dev.

**Comment by ben-schwen** [comment]
Seems related to https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/

**Comment by jangorecki** [comment]
Thanks Ben for pointing that out. I think what may be sufficient then is to change a toolchain to Rtools42. By change I may to change it only for win devel, and not all win builds. Use of multiple Rtools can be looked up in this commit https://github.com/Rdatatable/data.table/commit/73204cde7d16f9421ae7482a47d3b422fcc8216b#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7
It has been removed then because we didn't need older Rtools anymore, so now we need it again.

**Comment by mattdowle** [comment]
Thanks all. I'm looking at that line and trying to change it to Rtools42 : 
```
.test-install-rtools-win: &install-rtools-win
  - curl.exe -s -o ../rtools.exe https://cloud.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe; Start-Process -FilePath ..\rtools.exe -ArgumentList "/VERYSILENT /DIR=C:\rtools40" -NoNewWindow -Wait
```

I hunted through the articles and links to try to find what to change `rtools40-x86_64.exe` to exactly to get Rtools42. [https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/](https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/) contains one link to Rtools42 which is [https://www.r-project.org/nosvn/winutf8/ucrt3/web/rtools.html](https://www.r-project.org/nosvn/winutf8/ucrt3/web/rtools.html). That in turn contains a link labelled "Rtools42 installer" to [https://www.r-project.org/nosvn/winutf8/ucrt3/rtools42-RTVER.exe](https://www.r-project.org/nosvn/winutf8/ucrt3/rtools42-RTVER.exe) which returns "Object not found". Looking at the index for that directory : 

![image](https://user-images.githubusercontent.com/2779998/146823366-8752b8b3-e372-4c37-be95-3f786cd7eb40.png)

So I'm thinking `rtools42-4911-4926.exe` might work; i.e. with the version numbers in the name. But that doesn't seem right in that we'd have to change the link every time to get the latest version.

Why this CI job needs `magrittr` anyway seems to be the root cause.  I'm guessing it comes form the `knitr`/`rmarkdown` dependency chain. But the `dev-win` job has `--no-manual --ignore-vignettes` which looks good and correct so `knitr`/`rmarkdown` aren't needed for this job. Having tests run that need the other suggests `bit64 (≥ 4.0.0), bit (≥ 4.0.4), curl, R.utils, xts, nanotime, zoo (≥ 1.8-1), yaml` looks good and correct.

So I'm thinking to modify `dcf.dependencies('DESCRIPTION', which='most')` so that we can exclude `knitr` and `rmarkdown` from that for this dev-win job that doesn't need `knitr` or `rmarkdown`. A new parameter to `dcf.dependencies` called `exclude` for example, so that the exclusions are visible in the `gitlab-ci.yml` script. That should speed up this job and make it less likely to have problems by excluding the large dependency trail that `knitr`/`rmarkdown` pulls in. If that works, this `magrittr` problem should just go away without needing to spend any more time on Rtools42.  Have I misunderstood anything @jangorecki?

**Comment by mattdowle** [comment]
The `00install.out` for dev-win now fails with : 
```
* installing *source* package 'data.table' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
gcc  -I"C:/R/include" -DNDEBUG     -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -fexceptions  -c assign.c -o assign.o
sh: line 1: gcc: command not found
make: *** [C:/R/etc/x64/Makeconf:252: assign.o] Error 127
ERROR: compilation failed for package 'data.table'
* removing 'C:/GitLab-Runner/builds/Rdatatable/data.table/bus/test-dev-win/data.table.Rcheck/data.table'
```

Which is odd because I didn't point it to rtools42 at all, afaik. It's as though https://cloud.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe has been pointed to rtools42 in the meantime.

**Comment by mattdowle** [comment]
That worked so will move on.
