### ISSUE TITLE
fread(cmd = xxx) error with paths or filenames that contain a closing parenthesis "(" (on Windows)

### ISSUE THREAD

**Issue by MagicHead99** [Rdatatable/data.table#5302]
We have a file in the working directory called "res).csv". The troublesome closing parenthesis can be anywhere in the path of the file. This fails as well:  "//share/dir_(test)/a.csv"

fread("res).csv") ==> OK

CMD = "head -n 2 res).csv"
fread(cmd = CMD) ==> KO

I believe the issue comes from this part of the fread() code:

```
  if (!is.null(cmd)) {
    (if (.Platform$OS.type == "unix") 
      system
    else shell)(**paste0("(", cmd, ") > "**, tmpFile <- tempfile(tmpdir = tmpdir)))
    file = tmpFile
    on.exit(unlink(tmpFile), add = TRUE)
  }
```
The cmd is wrapped in parentheses before being sent to tmpFile. Unfortunately, the way it's managed, there is no way to escape the parentheses in the path or filename  of the CMD (to my knowledge).

**Comment by MichaelChirico** [comment]
Thanks for filing!

Minimal reprex:

```
fwrite(mtcars, tmp <- tempfile(pattern = ")"))
fread(cmd = paste("head -n 2", tmp))
# sh: 1: Syntax error: word unexpected
# Error: File '/tmp/RtmpTsqlX6/file661d174d39e0' does not exist or is non-readable. getwd()=='/home/michael/github/data.table'
```

**Comment by MichaelChirico** [comment]
Hmm I see, actually the fix is on your end. Use `shQuote` when you construct CMD:

```
CMD = paste("head -n 2", shQuote('res).csv'))
fread(cmd = CMD)
```

Use `shQuote('res).csv', "cmd")` if on Windows.

In my minimal example:

```
fwrite(mtcars, tmp <- tempfile(pattern = ")"))
fread(cmd = paste("head -n 2", shQuote(tmp)))
#      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#    <int> <int> <int> <int> <num> <num> <num> <int> <int> <int> <int>
# 1:    21     6   160   110   3.9  2.62 16.46     0     1     4     4
```

**Comment by MagicHead99** [comment]
This is very useful. Thanks a lot @MichaelChirico
