### ISSUE TITLE
roll regression

### ISSUE THREAD

**Issue by shenqixue** [Rdatatable/data.table#5314]
I want to do roll regression in data.table. For now, there are only frollsum and frollmean, which just accept one variable. Could you add something like roll_lm, roll_correlation, etc?

**Comment by MichaelChirico** [comment]
dupe of #4075

**Comment by jangorecki** [comment]
This can be achieved using `by.column=FALSE` https://github.com/Rdatatable/data.table/issues/4887 but it obviously will not be super fast.

**Comment by waynelapierre** [comment]
Any progress on rolling regression?

**Comment by jangorecki** [comment]
@waynelapierre let's keep the discussion about the functionality in the issue linked by Michael above.
