### ISSUE TITLE
Strange errors with .N and .() functions

### ISSUE THREAD

**Issue by aaelony-catasys** [Rdatatable/data.table#5317]
I am seeing peculiar behavior where `.N` no longer works correctly.  
I have tried to re-install data.table, but somehow the below strangeness keeps occuring:

```
> head(iris)
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa
> iris[, .N, by = "Species"]
Error in `[.data.frame`(iris, , .N, by = "Species") : 
  unused argument (by = "Species")


> iris[, .(cnt = .N, sum= sum(Sepal.Length)), by = "Species"]
Error in `[.data.frame`(iris, , .(cnt = .N, sum = sum(Sepal.Length)),  : 
  unused argument (by = "Species")

> iris[, .(cnt = .N, sum= sum(Sepal.Length))]
Error in .(cnt = .N, sum = sum(Sepal.Length)) : 
  could not find function "."


```

```
> packageVersion("data.table")
[1] ‘1.14.3’

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.3

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0   

```

Unfortunately, I am tied to this version of R on a prod machine. However, `data.table` has worked fine on this machine before.

Any insight on how to resolve this issue is welcome.

**Comment by dcaseykc** [comment]
Have you confirmed `iris` is a `data.table` (e.g. `class(data.table)`)?

**Comment by aaelony-catasys** [comment]
Thank-you, that was the issue (somehow carried over in my actual issue and in the iris data meant to illustrate the problem). Resolved.

**Comment by MichaelChirico** [comment]
a lesson in reading the error message verrry carefully -- note it is mentioning [.data.frame

that's usually a dead giveaway that the object is not a data.table

**Comment by aaelony-catasys** [comment]
Exactly right!  In my case though, it _had_ been a data.table that I nested within a data.table (to keep track of things within a data.table), and I forgot that I stored the data.table object within a list to store it within the data.table's row.  

No excuses, 100% my bad, but that wrangle in my headspace caused me adequate grief.   Thanks for your quick reply.
