### ISSUE TITLE
Groupingsets id order as the order of the sets

### ISSUE THREAD

**Issue by SamuelAllain** [Rdatatable/data.table#5323]
I wish the id were in the same order as the list of sets provided, so that I could easily give explicit names for each grouping.
Example with the grouping column and the grouping column I wish.

```
library(data.table)

n <- 1e4
d <- data.table(grp1 = sample(c("A", "B"), n, T),
                grp2 = sample(c("C", "D"), n, T),
                value = runif(n))
res <- groupingsets(d, sets = list(character(), "grp1", "grp2", c("grp1", "grp2")),
             by = c("grp1", "grp2"),
             j = mean(value),
             id = T)
res[, better_grouping := rleid(grouping)]
res
```

grouping | grp1 | grp2 | V1 | better_grouping
-- | -- | -- | -- | --
3 |   |   | 0.495586431312328 | 1
1 | B |   | 0.500010336070719 | 2
1 | A |   | 0.491132341371961 | 2
2 |   | D | 0.497149279533043 | 3
2 |   | C | 0.493995196342902 | 3
0 | B | D | 0.500908536961613 | 4
0 | A | C | 0.488859396055944 | 4
0 | A | D | 0.493364601509291 | 4
0 | B | C | 0.499095876515268 | 4

What do you think ? Is there any advantage of the current grouping column I am overlooking ? Thanks !

**Comment by jangorecki** [comment]
Hi, thanks for feedback. Advantage is being aligned to postgres implementation which is de facto a standard.

**Comment by jangorecki** [comment]
If you look at the code of the function you can see there is not much magic there. Loop over group by calls, rbindlist and extra id. It is not that difficult to hand craft those groupings yourself if they are fixed.

**Comment by SamuelAllain** [comment]
Thank you for the answer @jangorecki. Indeed because the order of the result is the same as the `sets` argument (and not the same as the `grouping` column), I reached my goal quite easily. This is the way I gave explicit names to my groupings, in case someone else had the same problem  :

```
library(data.table)

n <- 1e4
d <- data.table(grp1 = sample(c("A", "B"), n, T),
                grp2 = sample(c("C", "D"), n, T),
                value = runif(n))
sets1 <- list(character(), "grp1", "grp2", c("grp1", "grp2"))
res <- groupingsets(d, sets = sets1,
                    by = c("grp1", "grp2"),
                    j = mean(value),
                    id = T)

sets1_lib <- sapply(sets1, paste, collapse = "-")
res[, explicit_name := sets1_lib[rleid(grouping)]]
res
```


grouping | grp1 | grp2 | V1 | explicit_name
-- | -- | -- | -- | --
3 |   |   | 0.493262678802176 |  
1 | A |   | 0.48919647801607 | grp1
1 | B |   | 0.497337020130397 | grp1
2 |   | C | 0.495135565390374 | grp2
2 |   | D | 0.491314127748673 | grp2
0 | A | C | 0.490341457415416 | grp1-grp2
0 | B | C | 0.500011218714589 | grp1-grp2
0 | B | D | 0.494596698273552 | grp1-grp2
0 | A | D | 0.487987052364583 | grp1-grp2
