### ISSUE TITLE
Bug - data table join doesnt work

### ISSUE THREAD

**Issue by vk111** [Rdatatable/data.table#5324]
Unfortunately I cannot create any reproducible example

The issue is:

dt1 - 100 cols, 50000 rows
dt2 - 2 cols (character): a, b

dt1[dt2, a := i.a, on=.(c = b)] - it doesnt work, c - character column

I have found out that it works only when I run 
dt1 = dt1[, 1:length(colnames(dt1))] 
before join

#1 doesnt work
dt1[dt2, a := i.a, on=.(c = b)] 

#2 works
dt1 = dt1[, 1:length(colnames(dt1))] 
dt1[dt2, a := i.a, on=.(c = b)]

It happens not always - I just found one place in my code where it behaves like this
I dont know what can I add just if you have any guesses please let me know

Thanks

data.table_1.10.4-3

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.0                         
year           2017                        
month          04                          
day            21                          
svn rev        72570                       
language       R                           
version.string R version 3.4.0 (2017-04-21)

**Comment by OfekShilon** [comment]
Perhaps you can save and attach the offending dt's?

**Comment by ben-schwen** [comment]
First thing to try would be to update `data.table` to `1.14.3` since `1.10.4` is already 4 years old.

**Comment by MichaelChirico** [comment]
@vk111 as mentioned your version of data.table is quite old. We are happy to try and help if you can reproduce your issue on the current version of data.table. It will be much easier to provide help if you can provide a reproducible example. Please re-open at your discretion.
