### ISSUE TITLE
`fread` ignores integer argument for `nrow`

### ISSUE THREAD

**Issue by MEO265** [Rdatatable/data.table#5328]
A function call of the form `data.table::fread(file = file_path, nrow = 0L)` results in the entire file being read. In my opinion, the behavior should be the same as when the call is `data.table::fread(file = file_path, nrow = 0)`, since specifying the length as an integer is not uncommon.

**Comment by ben-schwen** [comment]
Seems like a duplicate to #4686 which is already fixed by #4694.

Please feel free to reopen this if I'm in error in assigning the duplicate label.

**Comment by MEO265** [comment]
![dt_bug](https://user-images.githubusercontent.com/99362508/153291790-897e3afa-77bb-4130-b281-76afc47a1597.png)
I may be wrong, but the PR you mentioned should have been processed in the version, but the bug still occurs.

**Comment by ben-schwen** [comment]
Nope, it's included in 1.14.3.
1.14.2 was merely a fix to not be archived on CRAN.

**Comment by MEO265** [comment]
> Nope, it's included in 1.14.3. 1.14.2 was merely a fix to not be archived on CRAN.

OK, thanks for your quick reply
