### ISSUE TITLE
[R-Forge #5400] parentheses use with `:=` should extend to more than one column name

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#533]
Submitted by: Eduard Antonyan; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5400&group_id=240&atid=978)

Currently one can do the following easily:

dt = data.table(a = 1:4)
colname = 'blah'

dt[, (colname) := 4:1]

However trying the above with the explicit `:=` function, as one would to modify several columns at once, will promptly result in an error:

dt[, `:=`((colname) = 4:1)]
#Error: unexpected '=' in "dt[, `:=`((colname) ="

The only current way of achieving this (aside from doing it one column at a time, which may or may not be possible, depending on what else is happening in the expression) I'm aware of is to construct the expression by hand and eval(parse it, and that's pretty ugly.

**Comment by arunsrinivasan** [comment]
This makes very little to no sense to me. How's this different from asking the same for `DT[, .((varx) = mean(x), (vary) = mean(y), by = .]` ?

**Comment by jangorecki** [comment]
@arunsrinivasan totally agree, this should be closed too.

**Comment by arunsrinivasan** [comment]
I still don't follow this one (and Matt doesn't as well from R-Forge link) and there seems to have been no follow ups. Use the `LHS := `RHS` form.
