### ISSUE TITLE
Set the number of threads in a package that depends on data.table

### ISSUE THREAD

**Issue by variani** [Rdatatable/data.table#5333]
Hello,

I develop an R package, e.g., `mypkg`, that depends on `data.table`, and I need to configure `data.table` to always use 1 thread in its operations, e.g., `fread`. What is the best was to accomplish this?

(1) My initial (naive) idea was to manually replace `fread()` by `fread(nThread = 1)`. But I also import other functions like `setkey`, and I'm not sure how many threads is used there.

(2) Looking at documentation of`setDTthreads`, it is stated that this is not a regular R option.

>It needs to be at C level so it is not a regular R option using [options()](https://rdrr.io/r/base/options.html)

Will it work if I put `setDTthreads(1)` line inside `.onLoad` function for my package?

My question is more about package development based on `data.table`, although it is related to a previously reported issue #1727.

Imagine my package `mypkg` has a function `myfun` that calls `data.table::fread` inside it. Note that there is no parallelization implemented in `myfun`, but `data.table::fread` uses 50% threads by default. Then I run a pipeline (e.g., snakemake)  in a multi-core machine (e.g., 48 cores), where each call of `myfun` is performed using 1 core. Since I don't configure `fread` to use only one core, the pipeline execution hangs (the reading operation by `fread` is too intensive; my data tables are relatively large, 10M rows). 

Thank you.

Best,
Andrey

**Comment by MichaelChirico** [comment]
you might try:

```
old <- setDTthreads(1)
on.exit(setDTthreads(old))
```

inside of `myfun`.

the risk with `.onLoad` is that other packages might adjust it.

**Comment by variani** [comment]
Hi Michael,

Your solution makes sense, thank you.

I would prefer to set the number of cores for `data.table` globally using the `options` mechanism within my package `mypkg`, but it seems it is not something that data.table can do. Perhaps, it is not common for other R packages.

Imagine I have multiple functions `myfun1`, `myfun2`, etc., and I need to apply `setDTthreads` inside every function. Additionally, I need to track whether any function in `mypkg` is based on `data.table`. Having a way to set the number of cores globally within `mypkg` looks cleaner to me.

Anyway, `data.table` is so powerful that I can live with the solution you suggested. Thank you for all your work on `data.table`!

**Comment by MichaelChirico** [comment]
You can definitely try setting the option in .onLoad (and conversely in .onUnload), with the caveat that any other code can later edit the # of threads without warning.

the same caveat applies to R's options() mechanism.

my approach is more tedious but AFAIK the only way to be totally safe

**Comment by variani** [comment]
Now I get your point that options() mechanism is not safe. I actually checked it, and obviously the number of cores can be easily rewritten. Thank you again.
