### ISSUE TITLE
Shift give.names=T does not name vector correctly

### ISSUE THREAD

**Issue by brian-loo** [Rdatatable/data.table#5349]
Shift no longer seems to label its output correctly.

## data.table 1.11.8 
> a = rnorm(10)
> names(a) =1:10
> shift(a,1,give.names=T)
   1_lag_1    2_lag_1    3_lag_1    4_lag_1    5_lag_1    6_lag_1    7_lag_1    8_lag_1    9_lag_1   10_lag_1
        NA -0.9827276 -0.8808175 -0.2446042  0.3919162 -2.9444352 -0.5435765  0.7315477 -0.6268370 -1.3413065

##data.table 1.14.2 
>  a = rnorm(10)
>  names(a) =1:10
>  shift(a,1,give.names=T)
 [1]         NA -1.5210371  0.4854557 -0.6147250  0.4174157  1.2376715
 [7] -0.9258354  0.1849812  1.5688538  1.9255935

**Comment by avimallu** [comment]
I quickly checked the NEWS section, and it looks like there was no mention of a change in `shift` that would alter this behaviour from 1.11.8. However, I do want to point out that it was never intended to work with atomic input (assuming that the documentation wasn't altered at some point):

> default is `FALSE` which returns an unnamed list. When `TRUE`, names are automatically generated corresponding to `type` and `n`. **If answer is an atomic vector, then the argument is ignored**.

**Comment by MichaelChirico** [comment]
See #1971. Looks like @jangorecki added that bit to the documentation in 91390e238c220111f2a349c873fd3e15a4619946. I guess it stopped working around 1.12.0 or 1.12.2 (3+ years ago).

**Comment by avimallu** [comment]
Follow up comment: the behaviour changed in https://github.com/Rdatatable/data.table/commit/6e60d7bc61b822113a255dc38ce06aa74d8a26c0:

```
  if (give.names) {
```
was changed to
```
  if (give.names && is.list(ans)) {
```

**Comment by MichaelChirico** [comment]
Looking again, I don't think we should support what used to work. How `give.names` is working in your example is quite different from how it's working for the intended use case of list input:

```
shift(list(a, a), give.names=TRUE)
# $V1_lag_1
#  [1]          NA  0.30254969  0.70778122 -1.25874202 -0.01945092  0.55619249
#  [7]  0.22146262 -0.10797979 -1.97651554  0.06095637

# $V2_lag_1
#  [1]          NA  0.30254969  0.70778122 -1.25874202 -0.01945092  0.55619249
#  [7]  0.22146262 -0.10797979 -1.97651554  0.06095637
```
