### ISSUE TITLE
[R-Forge #5381] gsum could accept a list of columns and add them all, like base::sum

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#535]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5381&group_id=240&atid=978)

Such as reported here for a list of one column :

https://r-forge.r-project.org/tracker/?func=detail&group_id=240&aid=5380&atid=975

It could sum up across list, like base::sum does.  That can be useful when applying by row,  but by row is always going to much slower than by column.

The error message currently redirects to DT[,lapply(.SD,sum),by=,.SDcols=] which is more likely what the user wants.

Or gsum could just do if (length 1 vecscp) x= VECTOR_ELT(x,0) first.  However, user's motivation was probably by row across a set of columns;  one-column was likely just a minimal example.

**Comment by jangorecki** [comment]
It doesn't seem to be valid anymore
```r
base::sum(list(1, 2))
#Error in base::sum(list(1, 2), list(2, 3)) : 
#  invalid 'type' (list) of argument
```
