### ISSUE TITLE
"total" label in cube/rollup/groupingsets

### ISSUE THREAD

**Issue by markseeto** [Rdatatable/data.table#5351]
Thanks for the data.table package.

I often find that after using cube/rollup/groupingsets, I want to fill in the NAs in the "total" rows. It would be nice if this could be done as part of the call to cube/rollup/groupingsets.

Example:

```
DT <- CJ(State = c("s1", "s2", "s3"),
         Group = c("g1", "g2"))[rep(1:6, c(2, 4, 3, 0, 1, 3))]

Counts <- cube(DT, .N, by = c("State", "Group"))

Counts
#     State Group  N
#  1:    s1    g1  2
#  2:    s1    g2  4
#  3:    s2    g1  3
#  4:    s3    g1  1
#  5:    s3    g2  3
#  6:    s1  <NA>  6
#  7:    s2  <NA>  3
#  8:    s3  <NA>  4
#  9:  <NA>    g1  6
# 10:  <NA>    g2  7
# 11:  <NA>  <NA> 13

# Fill in the NAs
for (v in c("State", "Group")) {
  Counts[is.na(get(v)), (v) := "Total"]
}

Counts[]
#     State Group  N
#  1:    s1    g1  2
#  2:    s1    g2  4
#  3:    s2    g1  3
#  4:    s3    g1  1
#  5:    s3    g2  3
#  6:    s1 Total  6
#  7:    s2 Total  3
#  8:    s3 Total  4
#  9: Total    g1  6
# 10: Total    g2  7
# 11: Total Total 13

# Maybe this could be done as part of the call to cube(), e.g.:
cube(DT, .N, by = c("State", "Group"), total.label = "Total")

# And it could allow different labels for different variables:
cube(DT, .N, by = c("State", "Group"),
     total.label = list(State = "National", Group = "Total"))


sessionInfo()

# R version 4.1.2 (2021-11-01)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19044)

# Matrix products: default

# locale:
# [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252
# [3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C
# [5] LC_TIME=English_Australia.1252

# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base

# other attached packages:
# [1] data.table_1.14.2

# loaded via a namespace (and not attached):
# [1] compiler_4.1.2
```
Thanks for considering.

**Comment by clerousset** [comment]
I have the same type of issues at work. One should keep in mind that for column classes different from `character` (e.g. for variables like dates or generations), it will coerce the entire column in `character` though

**Comment by BriceNocenti** [comment]
I have the same problem in worse : for me the NA results mixes with the true NAs on the grouping variables and it’s a mess to detect which is which (I don’t want to turn them as character "NA" before because it’s too long). 

@clerousset could something like `factor("Total")` preserve the type of factor columns (and hence the levels order) ?

**Comment by jangorecki** [comment]
Same way as NAs mixes with true NAs, the word "Total" mixes with true "Total" string in the data.
Having NA as default label has big plus that it works for all types of columns.

Ultimate way to deal with mixing aggregated rows with data rows is to use `id=TRUE` argument.
```r
Counts <- cube(DT, .N, by = c("State", "Group"), id=TRUE)
Counts
#    grouping  State  Group     N
#       <int> <char> <char> <int>
# 1:        0     s1     g1     2
# 2:        0     s1     g2     4
# 3:        0     s2     g1     3
# 4:        0     s3     g1     1
# 5:        0     s3     g2     3
# 6:        1     s1   <NA>     6
# 7:        1     s2   <NA>     3
# 8:        1     s3   <NA>     4
# 9:        2   <NA>     g1     6
#10:        2   <NA>     g2     7
#11:        3   <NA>   <NA>    13
```

----

Also, you may want to change
```r
for (v in c("State", "Group")) {
  Counts[is.na(get(v)), (v) := "Total"]
}
```
into more robust
```r
for (v in c("State", "Group")) {
  Counts[is.na(v), v := "Total", env=list(v=v)]
}
```

**Comment by markseeto** [comment]
@jangorecki Thanks for looking at this, and thanks for your detailed reply and suggestions about using `id=TRUE` and `env`.

I would like to attempt to implement the `total.label` list solution. I have very little experience contributing to packages and making pull requests, but I'm keen to give it a try. I've had a quick look at groupingsets.R and should be able to at least make an attempt.

**Comment by jangorecki** [comment]
@markseeto please look below at API and behavior proposed. `cat` just prints to desired query to be called, and then `copy(ans)[...]` gives expected output.
If we all agree on it then we can proceed to making change in your PR.
What is left is to decide what types should be supported, for me what must be supported is character, integer and factor, as those are meaningful to group by. Ideally we could support all types that are supported in `by` argument in `[`.
```r
library(data.table)

d = data.table(id1=c("a","b"), id2=c(1L,2L), v1=c(5,10))
ans = cube(d, .N, by = c("id1","id2"))

cat('cube(d, .N, by = c("id1","id2"), labels=-1L)\n')
copy(ans)[is.na(id2), id2:=-1L][]
cat('cube(d, .N, by = c("id1","id2"), labels="total")\n')
copy(ans)[is.na(id1), id1:="total"][]
cat('cube(d, .N, by = c("id1","id2"), labels=list("total", -1L))\n')
copy(ans)[is.na(id1), id1:="total"][is.na(id2), id2:=-1L][]
cat('cube(d, .N, by = c("id1","id2"), labels=list(id2=-1L, id1="total"))\n')
copy(ans)[is.na(id1), id1:="total"][is.na(id2), id2:=-1L][]
cat('cube(d, .N, by = c("id1","id2"), labels=list(integer=-1L, character="total"))\n')
copy(ans)[is.na(id1), id1:="total"][is.na(id2), id2:=-1L][]

## support for NA groups which are not totals

d = data.table(id1=c("a",NA), id2=c(1L,NA), v1=c(5,10))
ans = cube(d, .N, by = c("id1","id2"))

cat('cube(d, .N, by = c("id1","id2"), labels=list("total", -1L))\n')
copy(ans)[3:4, id2:=-1L][5:6, id1:="total"][7L,c("id1","id2"):=list("total",-1L)][]
```

**Comment by markseeto** [comment]
@jangorecki Thanks for looking at this and thanks for providing the examples. I've already made changes to the functions based on our discussion in the PR, but I haven't committed them yet. The modified functions are consistent with your examples, except that they currently don't support an unnamed list [`label=list("total", -1L)`] and they don't support a list with names being the classes/types [`list(integer=-1L, character="total")`]. I used argument name `label` instead of `labels` because `labels` is a base function.

Your examples are shown below, with `cube.data.table.new` being the modified function. It at least supports `label` for character, factor, integer, Date, IDate, and numeric variables. It probably supports other types but I haven't checked this thoroughly. The examples are followed by some questions.
```
library(data.table)

d = data.table(id1=c("a","b"), id2=c(1L,2L), v1=c(5,10))
ans = cube(d, .N, by = c("id1","id2"))

cat('cube(d, .N, by = c("id1","id2"), labels=-1L)\n')
copy(ans)[is.na(id2), id2:=-1L][]
#     id1 id2 N
# 1:    a   1 1
# 2:    b   2 1
# 3:    a  -1 1
# 4:    b  -1 1
# 5: <NA>   1 1
# 6: <NA>   2 1
# 7: <NA>  -1 2

cube.data.table.new(d, .N, by = c("id1","id2"), label=-1L)
#     id1 id2 N
# 1:    a   1 1
# 2:    b   2 1
# 3:    a  -1 1
# 4:    b  -1 1
# 5: <NA>   1 1
# 6: <NA>   2 1
# 7: <NA>  -1 2
# Warning message:
# When 'label' is a scalar, it is only used for variables having the same class as the label, so it was not used for the following variables, even though they have 'total' rows in the output: [id1]

cat('cube(d, .N, by = c("id1","id2"), labels="total")\n')
copy(ans)[is.na(id1), id1:="total"][]
#      id1 id2 N
# 1:     a   1 1
# 2:     b   2 1
# 3:     a  NA 1
# 4:     b  NA 1
# 5: total   1 1
# 6: total   2 1
# 7: total  NA 2

cube.data.table.new(d, .N, by = c("id1","id2"), label="total")
#      id1 id2 N
# 1:     a   1 1
# 2:     b   2 1
# 3:     a  NA 1
# 4:     b  NA 1
# 5: total   1 1
# 6: total   2 1
# 7: total  NA 2
# Warning message:
# When 'label' is a scalar, it is only used for variables having the same class as the label, so it was not used for the following variables, even though they have 'total' rows in the output: [id2]

cat('cube(d, .N, by = c("id1","id2"), labels=list("total", -1L))\n')
copy(ans)[is.na(id1), id1:="total"][is.na(id2), id2:=-1L][]
#      id1 id2 N
# 1:     a   1 1
# 2:     b   2 1
# 3:     a  -1 1
# 4:     b  -1 1
# 5: total   1 1
# 6: total   2 1
# 7: total  -1 2

cube.data.table.new(d, .N, by = c("id1","id2"), label=list("total", -1L))
# Error: Argument 'label', if not NULL, must be a scalar or a named list of scalars.

cat('cube(d, .N, by = c("id1","id2"), labels=list(id2=-1L, id1="total"))\n')
copy(ans)[is.na(id1), id1:="total"][is.na(id2), id2:=-1L][]
#      id1 id2 N
# 1:     a   1 1
# 2:     b   2 1
# 3:     a  -1 1
# 4:     b  -1 1
# 5: total   1 1
# 6: total   2 1
# 7: total  -1 2

cube.data.table.new(d, .N, by = c("id1","id2"), label=list(id2=-1L, id1="total"))
#      id1 id2 N
# 1:     a   1 1
# 2:     b   2 1
# 3:     a  -1 1
# 4:     b  -1 1
# 5: total   1 1
# 6: total   2 1
# 7: total  -1 2

cat('cube(d, .N, by = c("id1","id2"), labels=list(integer=-1L, character="total"))\n')
copy(ans)[is.na(id1), id1:="total"][is.na(id2), id2:=-1L][]
#      id1 id2 N
# 1:     a   1 1
# 2:     b   2 1
# 3:     a  -1 1
# 4:     b  -1 1
# 5: total   1 1
# 6: total   2 1
# 7: total  -1 2

cube.data.table.new(d, .N, by = c("id1","id2"), label=list(integer=-1L, character="total"))
# Error: When argument 'label' is a list, all element names must be in 'by' too. Element names in 'label' but not present in 'by': [integer, character]

## support for NA groups which are not totals

d = data.table(id1=c("a",NA), id2=c(1L,NA), v1=c(5,10))

ans = cube(d, .N, by = c("id1","id2"))
ans

cat('cube(d, .N, by = c("id1","id2"), labels=list("total", -1L))\n')
copy(ans)[3:4, id2:=-1L][5:6, id1:="total"][7L,c("id1","id2"):=list("total",-1L)][]
#      id1 id2 N
# 1:     a   1 1
# 2:  <NA>  NA 1
# 3:     a  -1 1
# 4:  <NA>  -1 1
# 5: total   1 1
# 6: total  NA 1
# 7: total  -1 2

cube.data.table.new(d, .N, by = c("id1","id2"), label=list("total", -1L))
# Error: Argument 'label', if not NULL, must be a scalar or a named list of scalars.

cube.data.table.new(d, .N, by = c("id1","id2"), label=list(id1="total", id2=-1L))
#      id1 id2 N
# 1:     a   1 1
# 2:  <NA>  NA 1
# 3:     a  -1 1
# 4:  <NA>  -1 1
# 5: total   1 1
# 6: total  NA 1
# 7: total  -1 2

# Examples with numeric and date grouping variables

d2 = data.table(id1=c(1.1, 1.2), id2=as.Date(c("2023-01-01", "2023-01-02")), v1=c(5,10))

cube.data.table.new(d2, .N, by = c("id1","id2"), label=list(id1=999, id2=as.Date("3000-01-01")))
#      id1        id2 N
# 1:   1.1 2023-01-01 1
# 2:   1.2 2023-01-02 1
# 3:   1.1 3000-01-01 1
# 4:   1.2 3000-01-01 1
# 5: 999.0 2023-01-01 1
# 6: 999.0 2023-01-02 1
# 7: 999.0 3000-01-01 2

cube.data.table.new(d2, .N, by = c("id1","id2"), label = as.Date("3000-01-01"))
#    id1        id2 N
# 1: 1.1 2023-01-01 1
# 2: 1.2 2023-01-02 1
# 3: 1.1 3000-01-01 1
# 4: 1.2 3000-01-01 1
# 5:  NA 2023-01-01 1
# 6:  NA 2023-01-02 1
# 7:  NA 3000-01-01 2
# Warning message:
# When 'label' is a scalar, it is only used for variables having the same class as the label, so it was not used for the following variables, even though they have 'total' rows in the output: [id1]

# The example below shows that the class check is strict - numeric/integer is a mismatch, and Date/IDate is a mismatch.

cube.data.table.new(d2, .N, by = c("id1","id2"), label=list(id1=999L, id2=as.IDate("3000-01-01")))
# Error: When argument 'label' is a list, the class of each element must match the class of the corresponding column of 'x'. Class mismatch for: [id1 (label:integer; x:numeric), id2 (label:IDate,Date; x:Date)]
```

Questions/comments:
1. Do you think the warning `When 'label' is a scalar, it is only used for variables having the same class as the label, so it was not used for the following variables, even though they have 'total' rows in the output: [id1]` is useful, or should it be removed?
2. For checking consistency between `label` and `x`, I compared classes (`class()`) rather than types (`typeof()`). Do you agree with this approach? The reason I did it that way was because `typeof(factor("a"))` is integer and `typeof(as.Date("2023-01-01"))` is double, so using `typeof()` wouldn't distinguish between factor and integer, and wouldn't distinguish between numeric and date, which I think would cause problems.
3.  I can try implementing `label=list("total", -1L)`, but I wonder if this option is necessary if we're allowing `label=list(integer=-1L, character="total")`. I'm assuming that `label=list("total", -1L)` means "total" applies to all character variables and -1L applies to all integer variables, but if not, please let me know.
4. For `label=list(integer=-1L, character="total")`, if we're using classes rather than types, we have the difficulty that the class can have length greater than 1, e.g. `c("IDate", "Date")`. Would you just want the list element name to be the first element of the class, e.g. `label=list(integer=-1L, IDate=as.IDate("3000-01-01"))`? This could cause problems if there are different classes that have the same first element. Or should we consider classes to be the same if they have the same first element? If we only use the first element of the class here, then I guess we should only use the first element when checking that `label` is consistent with `x` (currently the whole class vector is compared).
5. For `label=list(integer=-1L, character="total")`, a minor difficulty is that `x` could have columns called "integer" and "character", but this should be easy to handle with an error or warning.

**Comment by jangorecki** [comment]
1. It is useful to provide actionable warnings, so users know how to address it. In this case I would just not raise any warning but document this behavior well. Users should not expect any other behavior in such case.

2. Sounds good, just remember that class() can return length > 1 so comparison needs to use identical() rather than ==.

I will answer next points soon
