### ISSUE TITLE
fread: Return only column names and types (not the data.table)?

### ISSUE THREAD

**Issue by tconwell** [Rdatatable/data.table#5355]
fread says it uses a sample of 10,000 rows to determine the types for each column. Is there a way to return the column names and types without reading in the data? If not, can it be added?

**Comment by avimallu** [comment]
You can try

```
DT = fread(file_location, nrow=0)
sapply(DT, class) |> as.data.table(keep.rownames = TRUE)
```

**Comment by tconwell** [comment]
@avimallu Thanks for the reply, however this doesn't return the correct types. When nrows = 0, it assigns unknown/logical to every column and doesn't run the 10,000 row sample. nrows = 1 also does not run the sample.

**Comment by ben-schwen** [comment]
IIUC you are asking for the possibility that the types are determined by reading the sample but not reading the entire file?

**Comment by tconwell** [comment]
@ben-schwen In the details of the fread documentation, it says 

> A sample of 10,000 rows is used for a very good estimate of column types. 100 contiguous rows are read from 100 equally spaced points throughout the file including the beginning, middle and the very end. This results in a better guess when a column changes type later in the file (e.g. blank at the beginning/only populated near the end, or 001 at the start but 0A0 later on). This very good type guess enables a single allocation of the correct type up front once for speed, memory efficiency and convenience of avoiding the need to set colClasses after an error.

I'm asking for the possibility to return just the type allocation from the sample and immediately exit the function. I don't want any of the csv/file data, just to infer the types that might be present in the file.

**Comment by ben-schwen** [comment]
Perfect, thanks for the clarification, just wanted to make sure we are talking about the same thing.

**Comment by tdeenes** [comment]
Related (more general) request to return a broader set of metadata which is created internally by `fread`: https://github.com/Rdatatable/data.table/issues/4233

**Comment by ben-schwen** [comment]
Duplicate to #4686/#4029
