### ISSUE TITLE
warning when compiling fread on master on windows rtools42

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#5374]
```r
> remotes::install_github("Rdatatable/data.table@e9a323de01a17af70d5316016606fa8d35b25023")
...
gcc  -I"c:/PROGRA~1/R/R-42~1.0/include" -DNDEBUG     -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fread.c -o fread.o
In file included from fread.h:3,
                 from fread.c:27:
dt_stdio.h:25: warning: "__USE_MINGW_ANSI_STDIO" redefined
   25 |   #define __USE_MINGW_ANSI_STDIO 1
      | 
In file included from c:\rtools42\x86_64-w64-mingw32.static.posix\include\corecrt.h:10,
                 from c:\rtools42\x86_64-w64-mingw32.static.posix\include\crtdefs.h:10,
                 from c:\rtools42\x86_64-w64-mingw32.static.posix\include\time.h:9,
                 from c:\rtools42\x86_64-w64-mingw32.static.posix\include\sys\time.h:10,
                 from fread.c:8:
c:\rtools42\x86_64-w64-mingw32.static.posix\include\_mingw.h:435: note: this is the location of the previous definition
  435 | #define __USE_MINGW_ANSI_STDIO 0      /* was not defined so it should be 0 */
      | 
```

**Comment by tdhock** [comment]
It is possible to see this warning if you look on the GLCI log https://gitlab.com/Rdatatable/data.table/-/jobs/2212133398#L169 but it would be easy to miss (build is still green/pass). @jangorecki maybe it is worth considering changing the GLCI logic to return a red/fail build when there are compilation warnings, so that they would be more easily identified and fixed?

**Comment by jangorecki** [comment]
We already have this logic for the most strict job: https://github.com/Rdatatable/data.table/blob/e9a323de01a17af70d5316016606fa8d35b25023/.gitlab-ci.yml#L167
We could add it for windows as well. As long as there won't be many false positives then it should be ok.

**Comment by jangorecki** [comment]
@tdhock by any chance if you are on windows, could you provide powershell equivalent of
```sh
(! grep "warning:" data.table.Rcheck/00install.out) 
```
?
note that we do have `grep.exe` from /c/Rtools43/bin. Maybe it is as simple as adding `.exe` but I don't have where to try out

**Comment by ben-schwen** [comment]
> @tdhock by any chance if you are on windows, could you provide powershell equivalent of
> 
> ```shell
> (! grep "warning:" data.table.Rcheck/00install.out) 
> ```
> 
> ? note that we do have `grep.exe` from /c/Rtools43/bin. Maybe it is as simple as adding `.exe` but I don't have where to try out

That should be `(-not (Get-Content "data.table.Rcheck\00install.out" | Select-String "warning:"))`

`-not (c:\Rtools43\bin\grep "warning:" data.table.Rcheck\00install.out)` should also work
