### ISSUE TITLE
error message for comparison could be improved

### ISSUE THREAD

**Issue by mcol** [Rdatatable/data.table#5407]
The behaviour is correct, but the error message could be improved by reporting the comparison operator ">" instead of 6.

```r
dt <- data.table(iris)
dt[date > 0 & Species == "Virginica", .N]
# Error: comparison (6) is possible only for atomic and list types
```

`#` `Output of sessionInfo()`
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.2

loaded via a namespace (and not attached):
 [1] compiler_4.1.0

**Comment by MichaelChirico** [comment]
This is a base R problem -- don't think there's anything data.table should do here:

```r
with(iris, date > 0 & Species == "Virginica")
# Error in date > 0 : 
#   comparison (6) is possible only for atomic and list types
```

Please report to r-devel/Bugzilla

**Comment by MichaelChirico** [comment]
Actually, I found a fix in R pretty easily, so I filed myself:

https://bugs.r-project.org/show_bug.cgi?id=18375

**Comment by MichaelChirico** [comment]
Nice! already merged to r-devel. Thanks for raising! it has bugged me a few times before but you finally gave me the nudge to go chase it down!

https://github.com/r-devel/r-svn/commit/3a55efbf8741822cc67fab9fb188548cf0e7710f
