### ISSUE TITLE
Performance issue with chained assignment

### ISSUE THREAD

**Issue by markfairbanks** [Rdatatable/data.table#5408]
After using `as.character()` in assignment the next chained assignment is unexpectedly slow. I couldn't find any other functions that this occurred with.

``` r
library(data.table)

df <- data.table(x = round(runif(1e6), 4))

bench::mark(
  single = copy(df)[, x := as.character(x)][],
  chained = copy(df)[, x := as.character(x)][, x := x][],
  check = FALSE, iterations = 30
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 single        750µs   1.33ms    636.      9.48MB   273.  
#> 2 chained       416ms 490.03ms      2.00   22.97MB     2.42
```

**Comment by tlapak** [comment]
String conversions are expensive, therefore R delays them where possible in case the result isn't actually needed. The initial `as.character` call only produces what's known as an ALTREP object which in this case is essentially just a pointer to the original and a note to do the conversion next time the object is touched. Simply printing it is enough to trigger this conversion and data.table also forces the expansion any time you touch such an ALTREP column. This is what happens in the second example. If you replace that call with `copy(df)[, x := as.character(x)][, x]` you get the same effect. (The empty angle brackets do nothing btw.) So what you're observing is simply R taking some liberties with when it actually does what you asked.

**Comment by markfairbanks** [comment]
Gotcha - thanks for the explanation.
