### ISSUE TITLE
[R-Forge #5260] basic operations like row-subsets on data.table could be faster

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#542]
Submitted by: Arun ; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5260&group_id=240&atid=978)

One example is shown here:

http://stackoverflow.com/questions/21033196/how-to-access-data-table-rows-by-index

It should be possible to figure out that 'i' is the only argument inside and speed-up this operation?

In general, `[.data.table` needs quite a bit of tweaking/tidying up. This is a reminder to up the priority on this.

**Comment by MichaelChirico** [comment]
Is this not subsumed by #852?

**Comment by jangorecki** [comment]
This must have been resolved as DT is always faster than DF currently
```
> system.time(for (i in 1:1000) DT[i,])
   user  system elapsed 
  1.106   0.033   0.304 
> system.time(for (i in 1:1000) DF[i,])
   user  system elapsed 
  0.585   0.000   0.586 
> system.time(DT[seq(len=nrow(m)),])
   user  system elapsed 
  0.024   0.000   0.008 
> system.time(DF[seq(len=nrow(m)),])
   user  system elapsed 
  0.044   0.000   0.044 
```

**Comment by ColeMiller1** [comment]
@jangorecki how is the elapsed time less than the user time for ```DT[i, ]``` timings? I thought this typically meant parallelism was possible but in the case of ```subsetDT``` with 1 row, I do not see how the workers can be faster than single-thread. Maybe if we used OpenMP for the column loop but right now the implementation is on the vector subset. Perhaps the implementation was different last year...

**Comment by jangorecki** [comment]
I checked on `subsetDT1` branch to have more up-to-date timings, default 20 threads (50%). Looks fine.
```
> library(data.table)
data.table 1.12.9 IN DEVELOPMENT built 2020-06-13 21:38:35 UTC; jan using 20 threads (see ?getDTthreads).  Latest news: r-datatable.com
> m = matrix(1L, nrow=100000, ncol=100)
> 
> DF = as.data.frame(m)
> DT = as.data.table(m)
> system.time(for (i in 1:1000) DT[i,])
   user  system elapsed 
  0.251   0.010   0.262 
> system.time(for (i in 1:1000) DF[i,])
   user  system elapsed 
   0.56    0.00    0.56 
> system.time(DT[seq(len=nrow(m)),])
   user  system elapsed 
  0.100   0.109   0.014 
> system.time(DF[seq(len=nrow(m)),])
   user  system elapsed 
  0.064   0.024   0.088 
```
