### ISSUE TITLE
Fread precision issue with multiple threads

### ISSUE THREAD

**Issue by aquasync** [Rdatatable/data.table#5433]
The problem is that occasionally some floating-point values are parsed by fread to slightly different values, despite an identical representation in the underlying text file (causing eg ranking etc to then differ). Further playing around shows that this is affected by the number of threads used.

I've not been able to put together a minimal repro yet - the file in question is too large (2G csv) and contains some proprietary data. There are two rows which contain exactly "...,-0.071943,..." for a given field. If I read with 1 thread they remain the same value:

```
fread('test.csv', nThread=1)[date == 20040130 & id %in% c('QVKR6L-R', 'T67DJN-R'), sprintf('%.18f', factor1)]
# [1] "-0.071943000000000007" "-0.071943000000000007"
```

And with the default:

```
fread('test.csv')[date == 20040130 & id %in% c('QVKR6L-R', 'T67DJN-R'), sprintf('%.18f', factor1)]
# [1] "-0.071942999999999993" "-0.071943000000000007"
```

If I try and isolate a smaller file with eg just that date, the issue goes away, but that may be because it is not using multiple threads, or they've ended up getting processed in the same block by chance. Any ideas why the float parsing would be affected by the use of threaded reads?

**Comment by tlapak** [comment]
Thanks for reporting. If you are using the latest dev version, this is a duplicate of #5406 and #5346. 

Just to make sure, are you using this on Windows or Mac? And could you try to build the latest dev version with the latest rtools42 and R 4.2.1 and try again? That combination seems to have fixed the issue for me.

**Comment by aquasync** [comment]
Ah ok thanks, #5346 indeed looks like the same thing. Yes I'm on windows, but not on the dev version of data.table - I'm on 1.14.2. I'll try and update data.table to the latest dev version, but I'm currently stuck on R 4.0.5 because I'm using the MKL libs from Microsoft R Open.

**Comment by aquasync** [comment]
Updating just data.table to latest dev version fixed that particular case, but ended up with another where "0.066434" parsed as different floats. I'll have to try and update R to 4.2 then.

**Comment by aquasync** [comment]
Thanks @tlapak, can confirm that the issue goes away if I move to R 4.2 and use the dev version of data.table.

**Comment by tlapak** [comment]
Thank you very much for going to the trouble of updating your system and confirming that that fixes the issue. 

There is an issue with data.table that got fixed in dev, which is why you saw the change in affected floats. That it fully disappears after updating R confirms to me that there's a separate issue caused by the build tools.
