### ISSUE TITLE
Merge using `:=` does not produce a deterministic result

### ISSUE THREAD

**Issue by MEO265** [Rdatatable/data.table#5434]
Unfortunately I was not able to create a reproducible minimal example. Even if I save the workspace in the line before the bug in my code and later load it again and run `x[y, B := i.B, on = "A"]` "by hand", the error is not reproducible.
Nevertheless, I would like to share my problem with you and try to describe it as best as possible in the following, because unfortunately I cannot share the original code and data.

```R
# Create two data.table (data types as in the original code)
# In the original, x has about 70,000,000 rows and y 200,000,000
x <- data.table::data.table(A = letters[sample.int(26, replace = TRUE, size = 200)], C = runif(200))
y <- data.table::data.table(A = letters, B = sample.int(8,replace = TRUE, size = 26))
x[y, B := i.B, on = "A"]
```
Normally there should now be no `NA` in column `B` in data.table `x`, but in my code there are occasional `NA`s that are in different positions from run to run. But sometimes the error doesn't appear at all. 
The code should be absolutely deterministic. And if I save the workspace before this line in two runs and compare them (as enviroments) using `identical`, it gives `TRUE`. The error could be reproduced with the original code on several computers.

My suspicion is that it has to do with the memory management of `:=`

```R
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] testthat_3.1.0    fs_1.5.0          utilR_0.0.6       shinyjs_2.0.0     shiny_1.7.1       loggit_2.1.1      minpack.lm_1.2-1 
 [8] openxlsx_4.2.5    readxl_1.3.1      haven_2.4.3       lubridate_1.8.0   data.table_1.14.2

loaded via a namespace (and not attached):
 [1] zip_2.2.0        Rcpp_1.0.7       cellranger_1.1.0 pillar_1.6.4     compiler_4.1.2   later_1.3.0      forcats_0.5.1   
 [8] tools_4.1.2      digest_0.6.28    lifecycle_1.0.1  tibble_3.1.5     pkgconfig_2.0.3  rlang_0.4.12     fastmap_1.1.0   
[15] generics_0.1.1   vctrs_0.3.8      hms_1.1.1        R6_2.5.1         fansi_0.5.0      magrittr_2.0.1   promises_1.2.0.1
[22] ellipsis_0.3.2   htmltools_0.5.2  mime_0.12        xtable_1.8-4     httpuv_1.6.3     utf8_1.2.2       stringi_1.7.5   
[29] crayon_1.4.2
```

**Comment by tlapak** [comment]
Unfortunately, this isn't a whole lot to go on. 

I see that you have a number of Excel related package loaded. Are you reading the data from an Excel file and have you made sure the data is loaded the same way each time? Have you inspected the affected rows? If you can, run the script again and set `verbose = True` in the offending line and post the output here. Maybe there's something in there. Finally, two more things to try: Turn off multi threading by calling `setDTthreads(1)` and update your system to the latest versions of R and the dev version of data.table.

**Comment by MEO265** [comment]
> Unfortunately, this isn't a whole lot to go on.
> 
> I see that you have a number of Excel related package loaded. Are you reading the data from an Excel file and have you made sure the data is loaded the same way each time? Have you inspected the affected rows? If you can, run the script again and set `verbose = True` in the offending line and post the output here. Maybe there's something in there. Finally, two more things to try: Turn off multi threading by calling `setDTthreads(1)` and update your system to the latest versions of R and the dev version of data.table.

The data used in this situation does not come from an Excel file and is guaranteed to always be identical. I run the code single core as soon as possible and then report back with the output.

**Comment by MEO265** [comment]
> Unfortunately, this isn't a whole lot to go on.
> 
> I see that you have a number of Excel related package loaded. Are you reading the data from an Excel file and have you made sure the data is loaded the same way each time? Have you inspected the affected rows? If you can, run the script again and set `verbose = True` in the offending line and post the output here. Maybe there's something in there. Finally, two more things to try: Turn off multi threading by calling `setDTthreads(1)` and update your system to the latest versions of R and the dev version of data.table.


The problem also occurs with `setDTthreads(1)`. During further testing, I also noticed that I had to expand the minimal example by one column in each DT:

```R
x <- data.table::data.table(A = letters[sample.int(26, replace = TRUE, size = 200)], C = runif(200))
x <- x[, .(SCEN = 1:2), by = x]
y <- data.table::data.table(SCEN = c(rep(1L, 26), rep(2L,26)), A = rep(letters, 2), B = sample.int(8,replace = TRUE, size = 52))
x[y, B := i.B, on = .(SCEN, A)]
```

The output of the original (in a smaller version) then looks like this, regardless of whether an error is produced or not:
```
i.SCEN has same type (integer) as x.SCEN. No coercion needed.
i.A has same type (character) as x.A. No coercion needed.
forder.c received 7985000 rows and 10 columns
Calculated ad hoc index in 0.380s elapsed (0.350s cpu) 
Starting bmerge ...
forder.c received 6410000 rows and 3 columns
bmerge done in 22.2s elapsed (22.1s cpu) 
Constructing irows for '!byjoin || nqbyjoin' ... 0.020s elapsed (0.020s cpu) 
Detected that j uses these columns: i.B 
Assigning to 7985000 row subset of 7985000 rows
RHS_list_of_columns == false
```


I don't know if this is relevant, but the table `y` is created by `melt.data.table(y, id.vars = "SCEN", variable.name = "A", value.name = "B", variable.factor = FALSE)`. I don't think it's relevant though, as it's always the same when comparing different runs.

**Comment by jangorecki** [comment]
For reproducible example please use set.seed so we can compare output of each session.

**Comment by hdn012** [comment]
Can you check `uniqueN(y, "A")` and `uniqueN(y, c("A", "B"))` in your actual data to see if they are different?  
If they are different, I suspect the issue is with your usage of this syntax `x[y, B := i.B, on = "A"]`. In term of the resulting data.table, the syntax is not equivalent to `merge` or `y[x, on = "A"]` if multiple rows in `y` match a row in `x`. In that case, the syntax should be use with care because changing row order in `y` will result in different join result.

**Comment by MEO265** [comment]
> For reproducible example please use set.seed so we can compare output of each session.

Any seed can be used because in the original data the column with the numerics is deterministic, it was just the easiest way to generate an example, although it doesn't reproduce the error. Will keep it in mind for future examples though.

**Comment by MEO265** [comment]
> Can you check `uniqueN(y, "A")` and `uniqueN(y, c("A", "B"))` in your actual data to see if they are different? If they are different, I suspect the issue is with your usage of this syntax `x[y, B := i.B, on = "A"]`. In term of the resulting data.table, the syntax is not equivalent to `merge` or `y[x, on = "A"]` if multiple rows in `y` match a row in `x`. In that case, the syntax should be use with care because changing row order in `y` will result in different join result.

The number of different elements is identical and uniqueN confirms this, thanks for the suggestion anyway.

I'll see if I can later put online an original data set that has undergone a bijective replacement of the same data type.

**Comment by jangorecki** [comment]
Let's reopen when there will something that we can do about it.
