### ISSUE TITLE
Incorrect results from gsum/gmean

### ISSUE THREAD

**Issue by ecanesc** [Rdatatable/data.table#5454]
I see incorrect results for gsum and gmean for data.table compiled with full optimization using the Intel OneAPI compiler. This may be an issue for Intel, but it is similar to previous bugs such as https://stackoverflow.com/questions/71983259/data-table-average-by-group-provide-different-results-when-using-mean-and-sum.

Test case:
> library(data.table)
> set.seed(1)
> test.data<-data.table(cat=rep(c('a','b'),each=10),val=runif(20))
> test.data
       cat        val
    <char>      <num>
 1:      a 0.26550866
 2:      a 0.37212390
 3:      a 0.57285336
 4:      a 0.90820779
 5:      a 0.20168193
 6:      a 0.89838968
 7:      a 0.94467527
 8:      a 0.66079779
 9:      a 0.62911404
10:      a 0.06178627
11:      b 0.20597457
12:      b 0.17655675
13:      b 0.68702285
14:      b 0.38410372
15:      b 0.76984142
16:      b 0.49769924
17:      b 0.71761851
18:      b 0.99190609
19:      b 0.38003518
20:      b 0.77744522
       cat        val
> test.data[,mean(val),by=cat]
      cat        V1
   <char>     <num>
1:      a 0.3530419
2:      b 0.2827711

This result is incorrect, the correct result is
> options(datatable.optimize=1)
> test.data[,mean(val),by=cat]
      cat        V1
   <char>     <num>
1:      a 0.5515139
2:      b 0.5588204

> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS:   /home/local-rhel7/apps/R-4.2.0/intel-21.4/lib64/R/bin/exec/R
LAPACK: /home/local-rhel7/apps/R-4.2.0/intel-21.4/lib64/R/modules/lapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] data.table_1.14.2

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0    tcltk_4.2.0

Here is a sample of how the package was built:
icc -std=gnu11 -I"/usr/local/apps/R-4.2.0/intel-21.4/lib64/R/include" -DNDEBUG   -I/usr/local/include  -fopenmp  -fpic  -O3 -fp-model precise  -c gsumm.c -o gsumm.o

The workaround is to reduce the optimization level to -O1, I did this by setting in ~/.R/Makevars:
CFLAGS = -O1 -fp-model precise

It can also be resolved by wrapping val in as.numeric(), but this puts too much burden on the R user.

**Comment by jangorecki** [comment]
DT optimization levels has nothing to do with a compiler, they work already on compiled code. It clearly looks like a compiler bug, optimizations should not change the results IMO.

**Comment by ben-schwen** [comment]
Since you are using `data.table_1.14.2`, please try to update to dev version with `data.table::update.dev.pkg()` and see if the issue still occurs.

**Comment by ecanesc** [comment]
The compiler bug is still present when using data.table 1.14.3. It is not always so well-behaved, sometimes the result is garbage:

> set.seed(1)
> test.data<-data.table(cat=rep(c('a','b'),each=10),val=runif(20))
>  test.data[,mean(val),by=cat]
      cat        V1
   <char>     <num>
1:      a       NaN
2:      b 0.2827711
>  test.data[,mean(val),by=cat]
      cat            V1
   <char>         <num>
1:      a  1.688735e+86
2:      b -3.510855e+58
>  test.data[,mean(val),by=cat]
      cat             V1
   <char>          <num>
1:      a -1.734145e+241
2:      b -1.756618e+278

Again, avoiding optimization gets the correct result:

> options(datatable.optimize=1)
>  test.data[,mean(val),by=cat]
      cat        V1
   <char>     <num>
1:      a 0.5515139
2:      b 0.5588204

By the way, the documentation under "Installation" at https://github.com/Rdatatable/data.table/ is incorrect, it says to install the development package using

> data.table::update_dev_pkg()
Error: 'update_dev_pkg' is not an exported object from 'namespace:data.table'

but the correct syntax is as @ben-schwen said:

> data.table::update.dev.pkg()

**Comment by jangorecki** [comment]
Function name has been change in 1.14.3

**Comment by jangorecki** [comment]
You may try to reach out your compiler support as well.

**Comment by ecanesc** [comment]
I did open a compiler issue after my last post. This issue belongs with them, so I will close this one.
