### ISSUE TITLE
Add .bgz file decompression to data.table::fread() (compatible with .gz)

### ISSUE THREAD

**Issue by TMRHarrison** [Rdatatable/data.table#5461]
Currently, .bgz files are read as plain text, which fails due to invalid characters. [.bgz files are compatible with gunzip](http://www.htslib.org/doc/bgzip.html), and have the same data header (0x1F 0x8B). renaming *.bgz files to *.gz files allows them to be decompressed normally.

Adding .bgz to the list of files that can be decompressed by data.table::fread shouldn't require anything other than R.utils. I think adding `".bgz"` to the vector in this line:

https://github.com/Rdatatable/data.table/blob/c4a2085e35689a108d67dacb2f8261e4964d7e12/R/fread.R#L121

And checking for `w<=2` on this line

https://github.com/Rdatatable/data.table/blob/c4a2085e35689a108d67dacb2f8261e4964d7e12/R/fread.R#L124

Would allow fread to decompress .bgz files automatically. However, I haven't tested this.

**Comment by MichaelChirico** [comment]
Do you have any .bgz files you could share for testing?

**Comment by MichaelChirico** [comment]
Adding a key insight from the [`bgzip` man page](https://www.htslib.org/doc/bgzip.html) (it's hinted in OP's post):

> Bgzip compresses files in a similar manner to, and compatible with, gzip(1).

i.e., any tool that can read `gz` files should also be able to read `bgz` files. _generating_ `bgz` files would be another story, but we don't do that in `fread()`.
