### ISSUE TITLE
[R-Forge #5096] speed up get(colname)

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#550]
Submitted by: Eduard Antonyan; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5096&group_id=240&atid=978)

I think "get" with a single argument - get(colname) - is equivalent to eval(as.name(colname)), but the latter does not trigger construction of all columns. This can be addressed in the construct/deconstruct cycle where user's "get"'s can be replaced by appropriate eval's.

jan's edit: low priority as it can be easily achieved with `as.name`.

**Comment by jangorecki** [comment]
IMO no reason to go more deep into optimisations of `get` because of complexity it imposes. Related issue #4314. #4304 seems to be a way to address that.
