### ISSUE TITLE
Switch to pkgdown Bootstrap 5 template?

### ISSUE THREAD

**Issue by eitsupi** [Rdatatable/data.table#5503]
The switch to bs5 will allow for search within the site, which will be very useful for users.
https://www.tidyverse.org/blog/2021/12/pkgdown-2-0-0/#bootstrap-5

Since you are currently using pkgdown 2 with CI, switching to bs5 should be very easy.
(Of course I could create a PR if you are OK)

**Comment by jangorecki** [comment]
Yes, please fill PR.

**Comment by eitsupi** [comment]
It appears to change in appearance as follows.

Current website
![image](https://user-images.githubusercontent.com/50911393/198862454-96c0b113-bc95-44bd-8b91-f9f69e5e0cc3.png)

Switch to BS5 (my local view)
![image](https://user-images.githubusercontent.com/50911393/198862458-a2efb085-3917-4e63-a4bb-549f3347e023.png)
