### ISSUE TITLE
[R-Forge #5066] data.table( ) should check for columns named `V1`,etc.

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#551]
Submitted by: Ricardo Saporta; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5066&group_id=240&atid=978)

Example of duplicate column names: 

```R
data.table("Z", data.table(1:3, "a"))
#    V1 V1 V2
# 1:  Z  1  a
# 2:  Z  2  a
# 3:  Z  3  a
```

If `data.table()` is working with columns that are already named, it should check if any are named `V1`, `V2`, etc. so as to not create unnecessary duplicate column names.

**Comment by MichaelChirico** [comment]
This is closed by `check.names`, correct?

```
> data.table("Z", data.table(1:3, "a"), check.names = TRUE)
   V1 V1.1 V2
1:  Z    1  a
2:  Z    2  a
3:  Z    3  a
```

Unless we think it should somehow name the columns `V1` through `V3`, but that seems like a tall order and unnecessary.

**Comment by arunsrinivasan** [comment]
I can't tell when `check.names` argument was added to `data.table()` function. But it makes total sense.
