### ISSUE TITLE
add some consistency checks of new tables() quick sizing approach

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#5525]
> Yes good idea. With a caveat that if R-devel change object.size slightly it could break our test. Maybe find what object.size says now and match that but use that figure instead of the call. Then put the test that actually calls object.size somewhere off CRAN like maybe other.Rraw (by stretching how we think of other to include base). Or, just put it in other.Rraw only. But coverage, ok that's why in tests.Rraw too then.

_Originally posted by @mattdowle in https://github.com/Rdatatable/data.table/pull/5524#discussion_r1020853792_

**Comment by mattdowle** [comment]
and this issue can serve as a reminder to review all the changes to `tables()` and comments in #5224 and its follow-ups. I wouldn't normally make changes to master like this but I was working in the move_ram_tests branch for #5220 whose nature is resolving tipping points in rss to reveal the next test ID. I figured it was better to at least commit changes to tables() separately than do them in that branch.  I expect some changes to tables() before release once #5220 is merged.

**Comment by MichaelChirico** [comment]
I forget the context on this & am not particularly motivated to address it. We can revisit if there's a user request / the need arises again.
