### ISSUE TITLE
Re-cover dropped coverage in #5520

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5527]
The coverage comment says 0.76% reduced so I'm not sure why it passed. Need to get #5520 onto CRAN (plus the fix for R-devel) because it takes several weeks for CRAN Windows to update.

![image](https://user-images.githubusercontent.com/2779998/201901830-844c1cc9-10c5-4327-9a57-8739203be12c.png)

![image](https://user-images.githubusercontent.com/2779998/201901996-3d382c28-f437-4d24-add6-bd1f6eb09ff6.png)

**Comment by MichaelChirico** [comment]
Hmm we don't have the coverage reports for this PR specifically anymore. Closing this in favor of just generally improving coverage as we go along.
