### ISSUE TITLE
revdep new warnings because new exports yearmon, yearqtr, %notin%

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#5534]
revdep iemisc does both `import(zoo)` and `import(data.table)` in NAMESPACE, which causes R CMD check to give a warning with new data.table from github master, since we are now exporting yearmon, yearqtr (and zoo exports those two names as well).
I filed an issue to request that iemisc submit an update to CRAN https://gitlab.com/iembry/iemisc/-/issues/3 and a new version on CRAN has fixed this as of 13 Feb 2023.

**Comment by tdhock** [comment]
revdep CSMES has the exact same issue, but I don't see it on github/etc, so I will email the maintainer to ask for a fix.

**Comment by tdhock** [comment]
revdep PsychWordVec has similar issue
```
* checking whether package 'PsychWordVec' can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import 'data.table::%notin%' by 'bruceR::%notin%' when loading 'PsychWordVec'
```
I will ask for an update via https://github.com/psychbruce/PsychWordVec/issues

**Comment by tdhock** [comment]
revdep SWMPr has exact same issue with zoo import. I will ask for an updae via https://github.com/fawda123/SWMPr/issues

**Comment by tdhock** [comment]
seems like there are several other definitions of `%notin%`
```
* checking whether package 'TeXCheckR' can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import 'data.table::%notin%' by 'hutils::%notin%' when loading 'TeXCheckR'
```
I will ask for an update via https://github.com/HughParsonage/TeXCheckR/issues

**Comment by tdhock** [comment]
same zoo issue, will ask for update via https://github.com/Carm1r/fruclimadapt/issues

**Comment by tdhock** [comment]
same hutils notin conflict, will ask for update via https://github.com/HughParsonage/fy/issues

**Comment by tdhock** [comment]
revdep tbma has same zoo issue, I will ask for an update either via https://github.com/BurakhanS/tbma (looks inactive) or email.

**Comment by jangorecki** [comment]
I think it could be even better if we change the name to %nin%, less changes in general...

**Comment by tdhock** [comment]
revdeps TeXCheckR and tbma have been given plenty of advance warning, so this issue should not block new DT CRAN submission.

**Comment by MichaelChirico** [comment]
> revdep tbma has same zoo issue, I have asked for an update via [BurakhanS/tbma#1](https://github.com/BurakhanS/tbma/issues/1)

Also filed https://github.com/BurakhanS/tbma/pull/2

**Comment by MichaelChirico** [comment]
> seems like there are several other definitions of `%notin%`
> 
> ```
> * checking whether package 'TeXCheckR' can be installed ... WARNING
> Found the following significant warnings:
>   Warning: replacing previous import 'data.table::%notin%' by 'hutils::%notin%' when loading 'TeXCheckR'
> ```
> 
> I have asked for an update via [HughParsonage/TeXCheckR#82](https://github.com/HughParsonage/TeXCheckR/issues/82)

This is already fixed in the dev version:

https://github.com/HughParsonage/TeXCheckR/commit/09826878215cf56bc24a7e273084bfda3954a73b

https://github.com/HughParsonage/TeXCheckR/blob/09826878215cf56bc24a7e273084bfda3954a73b/NAMESPACE#L40

**Comment by MichaelChirico** [comment]
@tdhock do we leave this issue open now? We have done everything we can for the two remaining revdeps, they just need to accept our change (tbma) and push to CRAN (tbma + TeXCheckR).

**Comment by jangorecki** [comment]
assuming maintainers were notified long time ago, and they did, I think we can close them, putting on 1.15.0 milestone
