### ISSUE TITLE
revdep shapr new test failures due to warnings

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#5544]
revdep shapr has the following new test failures if data.table from github master is installed:
```
* checking tests ...
  Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  `shapr(train_df_used_numeric, l_numeric[[i]])` produced warnings.
  -- Failure ('test-a-shapley.R:87'): Testing data input to shapr in shapley.R ---
  `shapr(train_df_used_numeric, l_numeric[[i]])` produced warnings.
  -- Failure ('test-a-shapley.R:92'): Testing data input to shapr in shapley.R ---
  `shapr(train_df_used_factor, l_factor[[i]])` produced warnings.
  -- Failure ('test-a-shapley.R:92'): Testing data input to shapr in shapley.R ---
  `shapr(train_df_used_factor, l_factor[[i]])` produced warnings.
  -- Failure ('test-a-shapley.R:92'): Testing data input to shapr in shapley.R ---
  `shapr(train_df_used_factor, l_factor[[i]])` produced warnings.
  -- Failure ('test-a-shapley.R:92'): Testing data input to shapr in shapley.R ---
  `shapr(train_df_used_factor, l_factor[[i]])` produced warnings.
  
  [ FAIL 7 | WARN 45 | SKIP 0 | PASS 637 ]
  Error: Test failures
  Execution halted
```
git bisect says this started happening after merging https://github.com/Rdatatable/data.table/pull/5233
@ben-schwen can you please have a look since you were the author of that PR?

**Comment by MichaelChirico** [comment]
Same warning as #5532, this time because of the `nomatch=` argument being passed to `merge.data.table`.

Here's the invocation in question:

https://github.com/NorskRegnesentral/shapr/blob/3f4f61e90056839baec90c301015bc730d7cd8bd/R/models.R#L467

Should we add `nomatch=` to the signature of `merge.data.table`?

**Comment by jangorecki** [comment]
IMO should be kept baseR-ish, and the only reasonable way to add nomatch there is to catch it and raise warning. merge.data.table is suboptimal in the sense that it calls [ join. Coming mergelist will be even better substitute for merge.data.table.

**Comment by tdhock** [comment]
I would also suggest to keep merge as simple as possible (do not add nomatch argument), instead fix this issue by asking revdep maintainer to use [ instead of merge if he needs to specify nomatch arg.

**Comment by tdhock** [comment]
this is now fixed on CRAN.
