### ISSUE TITLE
When v1.14.7 will be released

### ISSUE THREAD

**Issue by phisanti** [Rdatatable/data.table#5550]
Hi,

This is an open question more than a bug report. I was just wondering when the data.table v1.14.7 will be released if there is an estimated release date. I have seen some really useful new features that I would like to use.

Thanks

**Comment by tdhock** [comment]
We are working on a release. One of the things we need to do is minimize number of revdep check issues. If you have time to help, you could look at the list of open issues with revdep tag, https://github.com/Rdatatable/data.table/issues?q=is%3Aissue+is%3Aopen+label%3Arevdep some of which need help (fixing dt issues such as https://github.com/Rdatatable/data.table/pull/5133 ) or contacting revdep maintainers to ask for updates.
