### ISSUE TITLE
[R-Forge #4988] File encoding option

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#556]
Submitted by: Joey Reid; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=4988&group_id=240&atid=978)

I would love to see a file-encoding option to read oddly encoded files (such as files using UTF-16LE) along the lines of scan() or file().

**Comment by bnbwn** [comment]
[R-Forge #4903] set encoding in fread #563

**Comment by arunsrinivasan** [comment]
Duplicate of #563 indeed.
