### ISSUE TITLE
data.table inside R6 class

### ISSUE THREAD

**Issue by AdamKarol** [Rdatatable/data.table#5565]
Hi,
how to use data.table inside object of R6 class?
We have problem to get access to objects (columns) when inside R6 class no matter if it is self / private or local object

**Comment by AdamKarol** [comment]
Hi,
how to use data.table inside object of R6 class?
We have problem to get access to objects (columns) when inside R6 class no matter if it is self / private or local object

**Comment by jangorecki** [comment]
We have problem to get access to your minimal reproducible example.

**Comment by jangorecki** [comment]
Sorry but two weeks passed, we didn't get reproducible example. Myself in the last I used dt in two of my packages with combination to R6 and never had any issues because of that, therefore it is not obvious to me what's your problem is precisely about. Please reach back when you can provide more details.

**Comment by AdamKarol** [comment]
Cześć Jan,

 

(spotkaliśmy się na Pazur’ze w Poznaniu)

 

It is true, we have not prepared the reproducible example yet.

 

We have package with some classes R6 inside which recall each other. So the solution is that we put into DESCRIPTION file following line: 

importFrom(data.table,':=')

 

Based on this

 <https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html> Importing data.table (r-project.org)

 

Does it tells You anything?

 

We would like to prepare reproducible example but we do not know when.

 

Greetings from Poland!

**Comment by jangorecki** [comment]
It doesn't tell me anything. You can find some working examples...
dwtools, data.cube, dtq, and possibly other packages in my repositories, and surely many more non-my repositories, that you can easily query from CRAN's packages metadata looking for data.table and R6 in their dependencies.
Greetings :)
