### ISSUE TITLE
Subsetting data.table using join returns a new data.table with wrong class

### ISSUE THREAD

**Issue by Kamgang-B** [Rdatatable/data.table#5572]
Hi all,
Kindly find a reproducible example below:

	dt = data.table(cat = factor(c("a", "b", "c", "b")),
					val = c(0.2, 1.4, 2.5, 1.4),
					grp = structure(c(1L,1L,2L,3L), class="customed"))

Note that `cat` and `grp` are  `factor` and `customed` class objects

	      cat   val        grp
	   <fctr> <num> <customed>
	1:      a   0.2          1
	2:      b   1.4          1
	3:      c   2.5          2
	4:      b   1.4          3

Subsetting using join: the classes of `cat` and `grp` change to `character` and `integer`.

	dt[.("a", 1:2), on=c("cat", "grp")]
	      cat   val   grp
	   <char> <num> <int>
	1:      a   0.2     1
	2:      a    NA     2

Note that setting the key before subsetting would lead to the same results.

**Comment by ben-schwen** [comment]
For the `factor`/`character` conversion similar to #2592 and duplicate to the regarding NEWS item (although not `verbose` is not directly mentioning the coercion from `factor` to `character`).

The class for the column is `inherited` from the `data.table` in `i`.
