### ISSUE TITLE
Autoprint suppression leads to annoying behaviour

### ISSUE THREAD

**Issue by vpetzel** [Rdatatable/data.table#5578]
Data table has a feature intended to suppress auto print in assign by reference scenarios. The motivation behind this seems to be that we want to avoid quasi assignment statements such as `D[some_i, some_col := some_val]` to autoprint the data table, leading to cluttered output. This internally done by the data.table package storing the memory address of at most one data table, and on printing this specific DT is not printed. This value is then reset by any printing operation or most data table operations. This means we can force printing like this `D[some_i, some_col := some_val][]`.

Now the problem is that this mechanism assumes that auto printing is in fact triggered, which is only the case if the result is not assigned to a variable and the call is made on highest possible level (outside of functions or `{ ... }` blocks).

This means we will easily get to situations like this:

```
d <- data.table::data.table(x = sample(3, 10, TRUE), y = runif(10))

some_summary <- function(dt, by, cols) {
    s <- d[
        by = by,
        j = lapply(.SD, sum, na.rm = TRUE),
        .SDcols = cols
    ]

    s[, s := rowSums(.SD), .SDcols = cols]

    s
}

# does not print
some_summary(d, "x", "y")[]
s <- some_summary(d, "x", "y")
# does not print
print(s)
# does print
print(s)
```

Now, it would of course be totally possible to add `[]` to any such statement, but this would demand for a clear documentation of this mechanism. But then we might also try to recognize if printing should be opressed by analysing the call stack.

If the call is made within a function we can assume it won’t be autoprinted. Afaik we cannot determine if something is assigned, but instead maybe not printing would only be valid if the update by reference is performed on the orignial data.table, and not a new one. So if there are any not by reference calls to j or non assign by reference row filterings on the call stack we can assume that the underlying data table has changes and thus we either want the autoprint, or we are going to assign the value anyway.

I do not know if this would be viable, but I think at the very least it should be clearly documented how to prevent the not printing issue.

**Comment by jangorecki** [comment]
Isn't this behavior documented in FAQ already?
