### ISSUE TITLE
`setDT()` for arrow tables

### ISSUE THREAD

**Issue by DrMaphuse** [Rdatatable/data.table#5584]
As mentioned in #2505 and #2026, setDT is a bottleneck when working with big datasets and parquet / feather files. I'm not sure if this makes sense, architecturally, but maybe optimizing setDT to work directly on arrow tables could be a solution.

**Comment by jangorecki** [comment]
Doesn't make sense because memory layout is not the same, it cannot be made by reference therefore.

**Comment by lucasmation** [comment]
What about data.table syntax/API for arrow (R package)? I naively [added this as a feature request to arrow](https://github.com/apache/arrow/issues/39822)

**Comment by jangorecki** [comment]
then, we had already issue which covers that #1828 - please provide your feedback there.

worth to note that arrow is actually 2 things, one is memory layout specification, and another is engine.
