### ISSUE TITLE
selection with on not correct compared to logical selection

### ISSUE THREAD

**Issue by blset** [Rdatatable/data.table#5585]
in some circumstances,

for a dt with a column field containing text with limited possibilities like value1 and value2 but not value3 for instance

`dt["value3", on = "field"] gives a one row data.table with all columns filled with NA
`
whereas

 `dt[field == "value3"] returns a zero row data.table
`
which is the right answer

**Comment by jangorecki** [comment]
Both are right, first one is right outer join, second is subset (like inner join). Base R behaviour for [ is right outer join.
