### ISSUE TITLE
Confusing `address` behavior

### ISSUE THREAD

**Issue by OfekShilon** [Rdatatable/data.table#5586]
```r
> dt <- data.table(a=1, b=2)
> address(dt$c)
[1] "0x56290516d990"
> address(dt$c) == address(dt$d)
[1] TRUE
```
Etc. etc. The reason seems to be it returns the address of an R `NULL`  object:
```r
> address(NULL)
[1] "0x56290516d990"
```

I suggest a small modification to the current implementation:
```c
SEXP address(SEXP x)
{
  // A better way than : http://stackoverflow.com/a/10913296/403310
  char buffer[32];
  snprintf(buffer, 32, "%p", (void *)x);
  return(mkString(buffer));
}
```

into:
```c
SEXP address(SEXP x)
{
  // A better way than : http://stackoverflow.com/a/10913296/403310
  char buffer[32];
  snprintf(buffer, 32, "%p", isNull(x) ? 0 : (void *)x);
  return(mkString(buffer));
}
```

**Comment by ben-schwen** [comment]
Favoring your idea since I already encountered this behavior myself.

`pryr` behaves like the current implementation:

``` r
x <- NULL
pryr::address(x)
#> [1] "0x5639cc23ab40"
```

**Comment by OfekShilon** [comment]
@ben-schwen  I now think it would be more natural to me to return `R_NilValue`, i.e. `is.null(address(NULL)) == TRUE`

**Comment by tlapak** [comment]
I don't understand. It does exactly what it says on the tin?

**Comment by ben-schwen** [comment]
`tracemem` errors if `R_NilValue` or other things like functions, environments, etc. are passed.

**Comment by MichaelChirico** [comment]
`dt$c` is `NULL`. `dt$d` is `NULL`. There's no way for `address()` to distinguish them. I don't see how your suggested implementation helps, besides maybe to make it visually clearer that `address(....)` being `0` tells you you hit `NULL` somewhere.

But OTOH, each session of R _does_ put a `NULL` object into memory _somewhere_, and I don't see why we'd want to obscure information:

```shell
Rscript -e 'data.table::address(NULL)'
# [1] "0x31f47f2adfb0"
Rscript -e 'data.table::address(NULL)'
# [1] "0x70437f29dfb0"
Rscript -e 'data.table::address(NULL)'
# [1] "0x103a3f2a9fb0"
Rscript -e 'data.table::address(NULL)'
# [1] "0x32be7f2a9fb0"
```
