### ISSUE TITLE
[R-Forge #4938] .SD should not always lose the key

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#559]
Submitted by: Eduard Antonyan; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=4938&group_id=240&atid=978)

In the following scenario .SD has a NULL key, but should instead have key = y:

dt = data.table(x = 1, y = 2, z = 3)

setkey(dt, x, y)

dt[, print(key(.SD)), by = x]

**Comment by MichaelChirico** [comment]
Not sure how useful this is... propose to close unless there's a specific use case for this?

**Comment by jangorecki** [comment]
could be used for joining .SD to another table, or binary search... by group(?)

**Comment by franknarf1** [comment]
Later-posted dupe, right? https://github.com/Rdatatable/data.table/issues/1736 

You could @ the OP @eantonya  if interested in use cases beyond what's there.

**Comment by MichaelChirico** [comment]
thanks Frank. closing this one since the other has more fleshed out examples
