### ISSUE TITLE
[R-Forge #4937] rbindlist(a,b,c) could work rather than needing rbindlist(list(a,b,c))

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#560]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=4937&group_id=240&atid=978)

I thought initially: just use rbind instead.   rbind(a,b,c) calls rbindlist under the hood.  But only if a is type data.table.

People want to use rbindlist for the speed, and use it on data.frame too.  Hence the need for rbindlist(a,b,c) working.  It can be done at C level on ..., without needing list().

See :

http://stackoverflow.com/questions/17411223/r-foreach-with-combine-rbindlist

**Comment by jangorecki** [comment]
Why not export `rbind.data.table` and ask people to use it explicitly if they want to rbind also data.frames? It would be more consistent and verbose.  
`rbindlist` as it's name states is for lists, I prefer not oversimplify api in cost of consistency, voting for close that (or turn to *export rbind.data.table*).

**Comment by jangorecki** [comment]
Re-open if really necessary. Closing now, as no follow-up comment happened for 3 years.
