### ISSUE TITLE
Major speed difference depending on use of `keyby`

### ISSUE THREAD

**Issue by jpanfil** [Rdatatable/data.table#5602]
This isn't a bug per se, but I'm curious why there's such a difference in performance in the following code. The motivation is that I often have to run a function, with varying group-bys. So I was playing around with different ways to do that. The first method is passing in a character vector into the function to use with `keyby` within, versus using a simple function that is wrapped with a data.table and `keyby`.

```
library(data.table)

# method 1
calculate_group_scores <- function(data, by_cols){
  grp <- data[ , .(x = mean(x), 
                   y = weighted.mean(y, w),
                   N = .N),
               keyby = by_cols]
  return(grp[])
}

# method 2
calculate_group_scores2 <- function(data){
  grp <- data[ , .(x = mean(x), 
                   y = weighted.mean(y, w),
                   N = .N)]
  return(grp[])
}

# fake data
n <- 1e7
charn <- paste0('xyz', 1:1e5)
dt <- data.table(by1 = sample(c('a', 'b', 'c'), n, replace = TRUE),
                 by2 = sample(letters, n, replace = TRUE),
                 by3 = sample(charn, n, replace = TRUE),
                 x = runif(n),
                 y = rnorm(n),
                 w = sample(1:12, n, replace = TRUE))
head(dt)

# benchmark
bnch <- rbenchmark::benchmark(test1 <- calculate_group_scores(dt, by_cols = c('by1', 'by2', 'by3')),
                              test2 <- dt[, calculate_group_scores2(data = .SD),
                                          .SDcols = colnames(dt),
                                          keyby = .(by1, by2, by3)],
                              replications = 1)
# confirm results are the same
all.equal(test1, test2)
```

The difference in time to run is staggering:

```
bnch[ , c("test", "elapsed", "relative")] 
test elapsed relative
1 test1    56.31    1.000
2 test2  3792.84   67.356
```

My question is why does method 2 (`test2`) take so much longer?

**Comment by avimallu** [comment]
A few reasons I can think of:

1. `gforce` is enabled and grouping is done in parallel in `test1`, and `data.table` can take full advantage of both operations.
2. `test2` has the added the overhead of calling `[.data.table` every time inside the `data.table` call that you have.

**Comment by ben-schwen** [comment]
If you use dev version then it definitely looks like `gforce` as avimallu already pointed out (`weighted.mean` should only be available as Gforce in dev). 

You can check if `gforce` is used by enabling verbose outputs with `options(datatable.verbose=TRUE)`

**Comment by jangorecki** [comment]
Well explained by others. In future try out verbose=TRUE for instant insight what could be the cause.
