### ISSUE TITLE
apply function to columns selected by names

### ISSUE THREAD

**Issue by amin0511ss** [Rdatatable/data.table#5612]
hi
i am not sure why the first code works but the second one does not:
1st code:
DF1 <- DF[, ..cols]
DF1[,] <- lapply(DF1[,], as.factor)

2nd code:
DF[,..cols] <- lapply(DF[,..cols], as.factor)

the second one throws this error message:
Error in `[<-.data.table`(`*tmp*`, , ..cols, value = list(colname1 = c(1L,  : 
  object '..cols' not found

**Comment by MichaelChirico** [comment]
a more canonical approach here is

```r
for (col in cols) set(DF, , col, as.factor(DF[[col]])
```

as to the failure, note that `..` notation on has meaning within `[.data.table`, and not within `[<-.data.table`. in principle we could support this, but `[<-.data.table` is discouraged -- you should be updating columns with `:=` or with `set()`

**Comment by amin0511ss** [comment]
Thank you
