### ISSUE TITLE
revdep dataverifyr test fails since brackify used more

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#5630]
Using github master data.table, checking CRAN package dataverifyr gives
```

* checking tests ...
  Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
    actual[3, ]                                                                                                    
    actual[4, ]                                                                                                    
  - actual[5, ]   Object 'does_not_exist' not found amongst [mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, ...]
  + expected[5, ] Object 'does_not_exist' not found amongst mpg, cyl, disp, hp, drat and 6 more                    
  
  actual$error[2:5] vs expected$error[2:5]
    ""
    ""
    ""
  - "Object 'does_not_exist' not found amongst [mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, ...]"
  + "Object 'does_not_exist' not found amongst mpg, cyl, disp, hp, drat and 6 more"
  
  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 28 ]
  Error: Test failures
  Execution halted
```
which is not present using data.table from CRAN.
git bisect says this started happening after merging https://github.com/Rdatatable/data.table/pull/4929 which changed several instances of paste(collapse) to brackify.
This suggests the revdep dataverifyr is testing the messages from data.table, so I will send an issue to dataverifyr to request a change on their end.

**Comment by tdhock** [comment]
I filed an issue https://github.com/DavZim/dataverifyr/issues/3 asking them to send an update to CRAN.

**Comment by DavZim** [comment]
dataverifyr has been fixed and uploaded to CRAN.

**Comment by tdhock** [comment]
thanks I can verify that this is no longer an issue since your new CRAN update is available. Thanks.
