### ISSUE TITLE
Inconsistent behaviour of order()

### ISSUE THREAD

**Issue by ja-ortiz-uniandes** [Rdatatable/data.table#5645]
I have noticed inconsistent behaviour when using a data.table and any of the `order()` functions (both `data.table`'s and `base`). Here are my results, but I have thus far, been unable to make a reproducible example without sharing the entire original data. I have determined that the problem appears to be related to the use of backticks **`** inside string values
``` r
library(data.table)

dt[folder == "kwy", .N, .(best)][order(best)]
#>              best    N
#> 1: (`2`) no label  165
#> 2: (`6`) no label  155
#> 3: (`1`) no label   48
#> 4: (`7`) no label   20
#> 5: (`9`) no label   95
#> 6: (`3`) no label   59
#> 7: (`4`) no label    2
#> 8: (`8`) no label    3
#> 9: (`5`) no label    1
#> 10:          <NA> 4979

dt[folder == "kwy", .N, .(best)][base::order(best)]
#>              best    N
#> 1: (`2`) no label  165
#> 2: (`6`) no label  155
#> 3: (`1`) no label   48
#> 4: (`7`) no label   20
#> 5: (`9`) no label   95
#> 6: (`3`) no label   59
#> 7: (`4`) no label    2
#> 8: (`8`) no label    3
#> 9: (`5`) no label    1
#> 10:          <NA> 4979


v <-
  c("(`2`) no label",
    "(`6`) no label",
    "(`1`) no label",
    "(`7`) no label",
    "(`9`) no label",
    "(`3`) no label",
    "(`4`) no label",
    "(`8`) no label",
    "(`5`) no label")


# Expected result
data.table(var = v)[order(var)]
#>               var
#> 1: (`1`) no label
#> 2: (`2`) no label
#> 3: (`3`) no label
#> 4: (`4`) no label
#> 5: (`5`) no label
#> 6: (`6`) no label
#> 7: (`7`) no label
#> 8: (`8`) no label
#> 9: (`9`) no label
```

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jangorecki** [comment]
Expected results misses one column, you need to remove it in your code as well, no? Your expected results sorts by the text field, while your code sorts by best value. It is not clear what you really expect when comparing your code and expected output.

**Comment by ja-ortiz-uniandes** [comment]
@jangorecki thank you for your comment. Yes, the expect result does not include the N column. However, the problem is not in the column but in the rows. The expected result has the rows correctly sorted. That is, 1 is first is followed by 2 followed by 3 followed by 4 and so on (1>2>3>4>5>6>7>8>9). The first data table is also sorted by rows (note that the values are the same as in the expected result) but for some reason 2 is first and is followed by 6 is followed by 1. Which makes no sense. In both cases, the sorted columns are strings.
Hopefully this helps make thing clearer, if not let me know and I'll try to continue to explain further.

**Comment by ben-schwen** [comment]
Without a reproducible example, I fear there is not much we can do. 

Your expected result code demonstrates that ordering strings with backticks should work.

**Comment by ja-ortiz-uniandes** [comment]
You are right on all counts. I have tried to make a reproducible example without using the original data, but so far I'm unable to replicate the issue. I will close this issue because of it and sort by a different method. I am not sure why the backticks **only** affect the sorting in my data.

**Comment by ben-schwen** [comment]
@ja-ortiz-uniandes

Can you share the output of
dt[folder == "kwy", .N, .(best)][base::order(best), verbose = TRUE] with us? This would at least tell us if escaping order to use base ordering work. Afaik base::order should also have an argument about which sorting algorithm it uses.

Last but not least you could try if `setorder(DT, best)` works although that shouldnt make a difference.
