### ISSUE TITLE
Updated H2O benchmark results

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#5647]
According to the updated H2O database benchmark results, duckdb and polars are now much faster than data.table. It seems that duckdb and polars have improved a lot in the past two years. Is there any plan for data.table to catch up?  
https://duckdb.org/2023/04/14/h2oai.html

**Comment by jangorecki** [comment]
Yes and no. There are many issues that are there asking about performance improvement, which ultimately will make DT more competitive to those recent performance leaders. No, that I don't see us to be defining action points particularly trying to address those tasks from benchmark, and finding a person who is willing to work on that. Unless you know someone who would like to make such contribution, I think we can close this issue, as too broad, and now having well defined goals.
