### ISSUE TITLE
setorder function also changes the ordering of another data.table if it is assigned (<-) instead of copied

### ISSUE THREAD

**Issue by oguzozbay** [Rdatatable/data.table#5652]
data.table's setorder function also changes the ordering of another data.table if it is assigned (<-)

```r
library(data.table)
DT_setorder = data.table(name = c("aaaa", "bb", "ccc"), n_character = c(4,2,3))
DT_setorder_ORIGINAL = DT_setorder

#Sort DT_setorder by n_character in descending order
setorder(DT_setorder, -n_character)
DT_setorder
DT_setorder_ORIGINAL

# Here are results:
#>   DT_setorder
# name n_character
# 1: aaaa           4
# 2:  ccc           3
# 3:   bb           2
# > DT_setorder_ORIGINAL
# name n_character
# 1: aaaa           4
# 2:  ccc           3
# 3:   bb           2


# Doing similar in dplyr
library(dplyr)
DT_FRAME = data.table(name = c("aaaa", "bb", "ccc"), n_character = c(4,2,3))
DT_FRAME_ORIGINAL <- DT_FRAME
# Sort DT_FRAME by n_character in descending order
DT_FRAME = DT_FRAME %>% arrange(n_character)
DT_FRAME
DT_FRAME_ORIGINAL

# Here are resuts
# > DT_FRAME
# name n_character
# 1:   bb           2
# 2:  ccc           3
# 3: aaaa           4
# > DT_FRAME_ORIGINAL
# name n_character
# 1: aaaa           4
# 2:   bb           2
# 3:  ccc           3
```

**Comment by msummersgill** [comment]
This is behavior as designed and documented. 

Two excerpts from the function documentation:

>In `data.table` parlance, all `set*` functions change their input by reference. That is, no copy is made at all, other than temporary working memory, which is as large as one column. The only other data.table operator that modifies input by reference is `:=`. Check out the See Also section below for other `set*` function data.table provides.


> The input is modified by reference, and returned (invisibly) so it can be used in compound statements; e.g., `setorder(DT,a,-b)[, cumsum(c), by=list(a,b)`]. If you require a copy, take a copy first (using `DT2 = copy(DT)`). See `copy`.

_If you feel this addresses your question, feel free to close this issue to reduce some load on the maintainers._
