### ISSUE TITLE
Can't select correct columns using variables

### ISSUE THREAD

**Issue by TigerZhao007** [Rdatatable/data.table#5653]
Example:

> DT = data.table(
+     ID = c("b","b","b","a","a","c"),
+     a = 1:6,
+     b = 7:12,
+     c = 13:18
+ )
> DT
   ID a  b  c
1:  b 1  7 13
2:  b 2  8 14
3:  b 3  9 15
4:  a 4 10 16
5:  a 5 11 17
6:  c 6 12 18

> DT[,c(1,2)]   # select NO. 1 and 2 columns using column_Number. Correct
   ID a
1:  b 1
2:  b 2
3:  b 3
4:  a 4
5:  a 5
6:  c 6

# using variables to select the same tast, Failed!
> col_num=2  
> DT[,c(1,col_num)]
[1] 1 2

> sessionInfo()
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default

**Comment by MichaelChirico** [comment]
Yes, this is intentional. See the FAQ and intro materials.

You might like `DT[, c(1, col_num), with=FALSE]` or `DT[, .SD, .SDcols = c(1, col_num)]`.
