### ISSUE TITLE
streaming for out-of-memory data

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#5669]
Polars is adding a streaming workflow for out-of-memory data: https://pola-rs.github.io/polars-book/user-guide/concepts/streaming/. I think this is an important feature to have in data.table because it currently only works with in-memory data.

**Comment by jangorecki** [comment]
Thank you for the request.
I would say it is out of scope, at least in reasonable future. We do have file backed data.table on the roadmap, that will allow to work with data bigger than memory, but it is also unlikely to happen anytime soon.
