### ISSUE TITLE
revdep simDAG example error

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#5680]
new revdep simDAG has the following error when checking using data.table master, which is not present when checking using data.table from CRAN:
```
* checking examples ... ERROR
Running examples in 'simDAG-Ex.R' failed
The error most likely occurred in:

> ### Name: long2start_stop
> ### Title: Transform a 'data.table' in the long-format to a 'data.table' in
> ###   the start-stop format
> ### Aliases: long2start_stop
> 
> ### ** Examples
> 
> library(simDAG)
> library(data.table)
> 
> # generate example data in long format
> long <- data.table(.id=rep(seq_len(10), each=5),
+                    .time=rep(seq_len(5), 10),
+                    A=c(rep(FALSE, 43), TRUE, TRUE, rep(FALSE, 3), TRUE,
+                            TRUE),
+                    B=FALSE)
> setkey(long, .id, .time)
> 
> # transform to start-stop format
> long2start_stop(data=long, id=".id", time=".time", varying=c("A", "B"))
Error: object 'max_t' not found
Execution halted
```
git bisect says this starts happening after merging https://github.com/Rdatatable/data.table/pull/5245 by @ben-schwen so could you please take a look and tell me if you think this should be fixed in simDAG or in data.table?

**Comment by tdhock** [comment]
if necessary we can report an issue to the revdep here, https://github.com/RobinDenz1/siMDAG/issues

**Comment by ben-schwen** [comment]
I don't have a computer with me but will check on Monday. There are already two follow ups to #5245 in particular #5348 and #5404, so one of those might already fix this

**Comment by MichaelChirico** [comment]
@ben-schwen I'll let you close -- if you think it warrants a new regression test please add one

**Comment by ben-schwen** [comment]
Problem in simDAG is covered by test 2243.01, since the evaluation of arguments type and fill both follow is_constantish.
