### ISSUE TITLE
Add a CI check for translation quality

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#5683]
To prevent regression on #5681. It will be easy enough, but waiting to invest while our CI is still broken at HEAD.

**Comment by jangorecki** [comment]
I am not sure if GLCI will keep working. I seen some emails about end of premium hourd subscription, that for public open source project was meant to be free.

**Comment by jangorecki** [comment]
How does the check looks like? We could either keep it in ghcl where we check for codecov or in glci where we keep r cmd checks

**Comment by MichaelChirico** [comment]
It's open-ended (we can start building out quality checks), but to start with, just running `tools::checkPoFiles()`.

**Comment by tdhock** [comment]
hi @MichaelChirico can this be closed now that https://github.com/Rdatatable/data.table/pull/6358 is merged?

**Comment by MichaelChirico** [comment]
Indeed, thanks!
