### ISSUE TITLE
[R-Forge #4690] as.data.table keep.rownames supports naming the new column (in addition to the default 'rn')

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#569]
Submitted by: Malcolm Cook; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=4690&group_id=240&atid=978)

proposed change to documentation for new feature

keep.rownames: If ‘...’ is a ‘matrix’ or ‘data.frame’, TRUE will retain the rownames of that object in a column named ‘rn’; a length 1 character will retain the rownames in a column by that name. Anything else, including the default of FALSE, will discard rownames.

**Comment by and3k** [comment]
(duplicate of #575)

**Comment by arunsrinivasan** [comment]
Yes indeed. Thanks @and3k. Have added #575 to 1.9.6 milestone. Should be quite straightforward to implement that feature.

**Comment by and3k** [comment]
:+1: Thanks!
