### ISSUE TITLE
as_tibble.data.table() method? 

### ISSUE THREAD

**Issue by ccsarapas** [Rdatatable/data.table#5698]
(I originally requested this at tidyverse/tibble/issues/1555, but they suggested requesting here instead.)

Would you consider adding a data.table method to `as_tibble()`? On extremely cursory testing, it may be as simple as adapting `as_tibble.data.frame()` with an extra line to remove the `.internal.selfref` attribute:
``` r
library(tibble)
library(data.table)
data(mpg, package = "ggplot2")

# two identical tibbles
mpg2 <- copy(mpg)
identical(mpg, mpg2)
#> [1] TRUE

# after converting to data.table and back to tibble, no longer identical
setDT(mpg2)
mpg2 <- as_tibble(mpg2)
identical(mpg, mpg2)
#> [1] FALSE

# identical again after removing ".internal.selfref" attribute
attr(mpg2, ".internal.selfref") <- NULL
identical(mpg, mpg2)
#> [1] TRUE
```

<sup>Created on 2023-09-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jangorecki** [comment]
Adding such method means extending dependencies of DT. We rather would like to reduce them, also Suggested dependencies.
Is there a reason why as_tibble.data.frame method doesn't work?
going via data.frame should work after looking at as.data.frame.data.table and what is under https://github.com/Rdatatable/data.table/blob/88039186915028ab3c93ccfd8e22c0d1c3534b1a/R/data.table.R#L2799

**Comment by MichaelChirico** [comment]
Isn't this the `Enhances:` dependency, and isn't the direction reversed, i.e., {data.table} would provide `as.data.table.tibble()` and {tibble} would provide `as_tibble.data.table()`?

**Comment by jangorecki** [comment]
So the problem is that initial dataset to which you want to compare to isn't just data.frame. If we use normal data.frame it works as expected.
```r
iris2 = copy(iris)
identical(iris, iris2)
# [1] TRUE

setDT(iris2)
iris2 = as.data.frame(iris2)
identical(iris, iris2)
# [1] TRUE
```

**Comment by jangorecki** [comment]
Indeed proposed one line change works as expected: https://github.com/Rdatatable/data.table/pull/5700/files

**Comment by AngelFelizR** [comment]
Thanks @TimTaylor

@ccsarapas I think that this issue is ready to be closed.
