### ISSUE TITLE
Take part in the 2023 data.table community survey (open until December 1st)

### ISSUE THREAD

**Issue by sluga** [Rdatatable/data.table#5704]
Hi everyone,

the data.table 2023 community survey is now live! Click on https://tinyurl.com/datatable-survey to fill it out, it will remain open until **December 1st**.

In addition to filling out the survey, it would be great if you could share it with others who might be interested in participating.

Thanks to @jangorecki, @tdhock, @markseeto, @franknarf1, @MichaelChirico, and @ben519 for their help in shaping the survey!

![dt-survey-2023](https://github.com/Rdatatable/data.table/assets/20184267/66c37648-ddc5-495a-8821-1e13bda6d8b0)

**Comment by tdhock** [comment]
hi @sluga thanks for organizing this! what are you plans for sharing the survey results? (raw data and analysis)

**Comment by sluga** [comment]
@tdhock I was thinking of publishing data + code in a GH repo. For a summary of the results, perhaps the new data.table blog would be a good place. What do you think?

**Comment by tdhock** [comment]
sounds great thanks

**Comment by jangorecki** [comment]
@sluga please see #5713

**Comment by jangorecki** [comment]
@sluga please do not publish survey data here. I would like to put it directly on r-datatable.com website and to be accessible only from there.

**Comment by tdhock** [comment]
hi @sluga what is the status of the survey data? can you please write a blog post and send a PR to https://github.com/rdatatable-community/the-raft ?

**Comment by sluga** [comment]
@tdhock Haven't finished it yet due to various obligations/trips, but it'll be done in January for sure. Sorry this is taking so long.

**Comment by sluga** [comment]
Blog post: https://rdatatable-community.github.io/The-Raft/posts/2024-02-25-survey_2023-aljaz_sluga/
Data: https://github.com/sluga/r-datatable-survey-2023

**Comment by MichaelChirico** [comment]
Thanks so much for this @sluga!!

**Comment by kbodwin** [comment]
@sluga , ICYMI, your wonderful blog post made the [RWeekly highlights](https://rweekly.org/) this week!  Thank you again from the bottom of our hearts for all the great work you did on the survey.
