### ISSUE TITLE
2023 Community survey question 9 requires scrolling to see the rightmost answer option

### ISSUE THREAD

**Issue by daniellemccool** [Rdatatable/data.table#5713]
As shown in these images, question 9 requires horizontal scrolling in order to see the rightmost header. This is seemingly resolution independent. Small scrollbar excluded, the grid's design doesn't make it immediately obvious that there is more to the right.  Below an example:

![image](https://github.com/Rdatatable/data.table/assets/5112209/d37bb4b6-ea73-4087-87dd-4103a4892b59)
![image](https://github.com/Rdatatable/data.table/assets/5112209/bbe462b1-4105-4cb0-8143-6b87aeaa42ae)

Checked on an updated version of Windows 10 Chrome (Version 118.0.5993.118 (Official Build) (64-bit)) and an updated instance of Edge on a virtual machine with different resolution settings, and both of them required scrolling to get to the last answer. 

### Minimal reproducible example

1. Display resolution set to 1920 x 1080, scale 100% (unclear impact here)
2. [Open survey](https://tinyurl.com/datatable-survey)
3. Navigate to third page, question 9

### Justification

Since a lot of data.table users are likely to be statisticians, it may not be necessary to point out why this is a bad idea. But since I literally just happened to have this paper open in another tab...

Antoun et. al (2018) have a paragraph on the design principle 'visibility across the page' from a literature review on optimizing questionnaires, which I'll quote to efficiently link the papers they reviewed.

> 3. Visibility across the page
> All content should fit the width of the screen so that it is visible without horizontal scrolling. Response options on the right side of the page that are not initially visible may not be noticed by respondents ([Peytchev & Hill, 2010](https://journals.sagepub.com/doi/abs/10.1177/0894439309353037)) and could skew response distributions in favor of the initially visible options ([Lattery, Park Bartolone, & Saunders, 2013](https://web.archive.org/web/20160328064141/http://www.maritzresearch.com:80/~/media/Files/MaritzResearch/Whitepapers/Optimizing-Surveys-for-Smartphones_April-2013.pdf); [Stapleton, 2013](https://www.surveypractice.org/article/3027-the-smart-phone-way-to-collect-survey-data); [Struminskaya, Weyandt, & Bosnjak, 2015](https://mda.gesis.org/index.php/mda/article/view/2015.014)). Given a minimum font size (heuristic 1) and touch target size (heuristic 2), the more response options in the question, the more likely it will need to be displayed vertically.

Antoun, C., Katz, J., Argueta, J., & Wang, L. (2018). Design Heuristics for Effective Smartphone Questionnaires. Social Science Computer Review, 36(5), 557-574. [https://doi.org/10.1177/0894439317727072](https://doi.org/10.1177/0894439317727072)

**Comment by jangorecki** [comment]
@sluga

**Comment by sluga** [comment]
Thanks @daniellemccool, well spotted. Safari sometimes shows all response options & sometimes not, seemingly unpredictably. Unfortunately, I don't know how to fix this, the Forms app is pretty limited. Modifying the font size didn't seem to help.

**Comment by AngelFelizR** [comment]
@sluga you could reduce the number of levels to 3:

- Dissatisfied
- Neither satisfied nor dissatisfied
- Satisfied

I think that is enough detail to take actions and understand user's position.

**Comment by jangorecki** [comment]
survey is finished already
