### ISSUE TITLE
do we want to keep the gitlab mirror going?

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5717]
@jangorecki / @tdhock do we want to keep the gitlab mirror going? Does GHA subsume what GLCI can offer?

_Originally posted by @MichaelChirico in https://github.com/Rdatatable/data.table/issues/5451#issuecomment-1791765549_

**Comment by jangorecki** [comment]
I don't think if it works due to some subscription expiry.
Change for subscription model that happened in gitlab was very unfriendly from the perspective of open source projects. To be fair I am not sure if open source projects are still eligible for free CI, if so then they may need to renew every year, ultimately I don't precisely know. Gitlab was not responsive when trying to contact about this issue.

So my answer is No.

Does GHCI subsume what GLCI I don't think so, I would not make it a priority now.
If someone wants to play with it then sure. We need generating binaries for each platform and r-devel, r-release and r-oldrel, then putting them together (not sure how easy to pass buld artifacts between jobs in GHCI) into single dir structure. Generating R repo. Adding pkgdown as index and  R html manuals in a subdir.

**Comment by tdhock** [comment]
It definitely is useful to have binary builds of data.table master available.
If it is possible to do that on Github, that would be nice so we can do everything in one place.
@jangorecki are you the one who set up GLCI? You wrote "If someone wants to play with it " so does that mean you no longer want to maintain?
related to new "binary maintainer" role mentioned in #5676

**Comment by jangorecki** [comment]
@tdhock Yes, binaries would be great, but I would prioritize after 1.15.0 release. Yes, I setup GLCI, unfortunately I don't have enough time to handle that. It is possibly a matter of finding out if and how we could have some extra CI minutes to continue running there, and setting that up. Big advantage of GLCI over GHCI is that you can run all locally if required.

**Comment by jangorecki** [comment]
according https://about.gitlab.com/pricing/#is-there-a-different-compute-minutes-limit-for-public-projects it should be doable to keep GLCI, eventually dropping few jobs so it eats less compute minutes.
