### ISSUE TITLE
Improve := error for case when cedta() dispatches [.data.frame

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#5721]
The current error is not very helpful for a package author that forgot to `@import` data.table leading [.data.frame to dispatch as cedta() gives FALSE. So := is used correctly, but still get the error.

Difficult (not impossible) to encounter once the package reaches CRAN caliber, more likely for package under early development.

Alternatively, using := is a pretty good sign the author intended [.data.table, so we could consider changing the cedta() result, but I think that will be non-trivial.

**Comment by tdhock** [comment]
What is the current error, and what do you suggest we change it to?

**Comment by MichaelChirico** [comment]
> What is the current error,

The normal error for when `:=` is invoked directly:

https://github.com/Rdatatable/data.table/blob/e6076b02f746dd05d921ac355291fb42623f6c02/R/data.table.R#L2778

> what do you suggest we change it to?

Not sure yet, but the current message is misleading in this case (emphasis on "ensure `x` is a data.table", but `x` is in fact a data.table!).

**Comment by Nj221102** [comment]
Is this error message good enough to fix this issue ?

```
stopf("It seems that `:=` is being used directly. Make sure that `data.table` is imported and used explicitly in your package. If you are intentionally using `:=` with a data table, ensure that the object being modified is indeed a data table. If you are encountering this error unexpectedly, it may be due to `data.table` methods being dispatched as `data.frame` methods. Check that `is.data.table(DT)` returns `TRUE` for your object `DT`. For more information on using `:=` and data tables, refer to the documentation by running `?`:=``.")
```

**Comment by MichaelChirico** [comment]
> imported and used explicitly in your package

But this error might not come up in a package, or it might be caused by an issue in another package entirely.

I am thinking the best way to address this may be in `[.data.frame` itself, e.g. in this branch:

https://github.com/Rdatatable/data.table/blob/3eefbcaa47a1c2fc28037574aee27992d083750e/R/data.table.R#L146-L155

Quickly scan `j` for `:=` (and `let`), and throw a specific error if needed along the lines "`[ was called on a data.table in an environment that is not data.table-aware (i.e. `cedta()`), but `:=` was used, implying the owner of this call really intended for data.table methods to be called. See vignette("datatable-importing") for details on properly importing data.table".

OTOH, maybe using `:=` in `j` is a sign that `cedta()` should pass. If caller is using `:=`, it should be pretty clear they are data.table-aware. WDYT @jangorecki?

**Comment by jangorecki** [comment]
Isn't / wasn't `:=` operator used in some tidyverse package as well?
I think they used it to substitute LHS of assignment because `:=` is lazy on LHS and RHS, unlike `=` where you cannot catch LHS. I don't follow API changes in tidyverse and that may have been change, because there are better ways to achieve (like we did inside `env` var).

**Comment by TysonStanley** [comment]
> Isn't / wasn't `:=` operator used in some tidyverse package as well?

Yes, it's used within their `mutate()` function for lazy evaluation. Pretty sure it's still implemented.

**Comment by MichaelChirico** [comment]
> I think they used it to substitute LHS of assignment because `:=` is lazy on LHS and RHS, unlike `=` where you cannot catch LHS.

yes that's still surely used where needed. my suggestion is to look for := as root of j though, in same fashion as later in [.data.table, instead of recursive search which might find tidyverse false positives.
