### ISSUE TITLE
Programatically convenient and easily chainable column subset

### ISSUE THREAD

**Issue by sbudai** [Rdatatable/data.table#5734]
I wrote to myself 2 functions which I use intensively since then.     
Probably they would be convenient for the public as well.
<br>
Those are about column subsetting. As such they are special type of replacements of the `DT[, .SD, .SDcols = c("a", "b", "c", ...)]` formula.
<nr>
The first one (`keepcolsv()`) easily works together with the lately introduced forward pipe operator (`|>`).
The second one (`setkeepcolsv()`) is a `set...()` style (inplace) subsetter.
<br>
Both of them
- if strict == FALSE, then leaves out - without warning - each listed column which is not part of the input data.table (This is my preference, but it might be switched on/off by an additional parameter.)
- sets the relative order of remaining columns according to the "cols" parameter

*****
### This functions returns with columnwise subset of the data.table "x" using column names in "cols" vector.
```
keepcolsv = function(x, cols, strict = TRUE) {
  if (strict) {
    excess_cols = base::setdiff(x = cols,
                                y = names(x))
    if (length(excess_cols) > 0L) stop(sprintf(fmt = "'%s' is not a valid column name   ", excess_cols))
  }
  data.table::as.data.table(unclass( x )[cols])
}
```

### This functions <ins>inplace</ins> columnwise subsets the data.table "x" using quoted column names.
```
setkeepcolsv = function(x, cols) {
  remaining_cols = base::intersect(x = cols,
                                   y = names(x))
  remove_cols    = base::setdiff(x = names(x),
                                 y = cols)
  data.table::set(x     = x,
                  j     = remove_cols,
                  value = NULL)
  data.table::setcolorder(x        = x,
                          neworder = remaining_cols)
  return(invisible(x))
}

```

### preparation for the example
```
library(data.table)

invisible(data(mtcars))
setDT(x             = mtcars,
      keep.rownames = TRUE )
```

### forward pipe operator type subsetting
```
mtcars_subset = mtcars |> keepcolsv(cols = c("rn", "carb", "cyl"))
mtcars_subset[]
```
                             rn carb cyl
         1:           Mazda RX4    4   6
         2:       Mazda RX4 Wag    4   6
         3:          Datsun 710    1   4
         4:      Hornet 4 Drive    1   6
         5:   Hornet Sportabout    2   8
         6:             Valiant    1   6
         7:          Duster 360    4   8
         8:           Merc 240D    2   4
         9:            Merc 230    2   4
        10:            Merc 280    4   6
        11:           Merc 280C    4   6
        12:          Merc 450SE    3   8
        13:          Merc 450SL    3   8
        14:         Merc 450SLC    3   8
        15:  Cadillac Fleetwood    4   8
        16: Lincoln Continental    4   8
        17:   Chrysler Imperial    4   8
        18:            Fiat 128    1   4
        19:         Honda Civic    2   4
        20:      Toyota Corolla    1   4
        21:       Toyota Corona    1   4
        22:    Dodge Challenger    2   8
        23:         AMC Javelin    2   8
        24:          Camaro Z28    4   8
        25:    Pontiac Firebird    2   8
        26:           Fiat X1-9    1   4
        27:       Porsche 914-2    2   4
        28:        Lotus Europa    2   4
        29:      Ford Pantera L    4   8
        30:        Ferrari Dino    6   6
        31:       Maserati Bora    8   8
        32:          Volvo 142E    2   4
                             rn carb cyl

### inplace subsetting
```
setkeepcolsv(x    = mtcars,
             cols = c("rn", "carb", "cyl"))
mtcars[]
```
                             rn carb cyl
         1:           Mazda RX4    4   6
         2:       Mazda RX4 Wag    4   6
         3:          Datsun 710    1   4
         4:      Hornet 4 Drive    1   6
         5:   Hornet Sportabout    2   8
         6:             Valiant    1   6
         7:          Duster 360    4   8
         8:           Merc 240D    2   4
         9:            Merc 230    2   4
        10:            Merc 280    4   6
        11:           Merc 280C    4   6
        12:          Merc 450SE    3   8
        13:          Merc 450SL    3   8
        14:         Merc 450SLC    3   8
        15:  Cadillac Fleetwood    4   8
        16: Lincoln Continental    4   8
        17:   Chrysler Imperial    4   8
        18:            Fiat 128    1   4
        19:         Honda Civic    2   4
        20:      Toyota Corolla    1   4
        21:       Toyota Corona    1   4
        22:    Dodge Challenger    2   8
        23:         AMC Javelin    2   8
        24:          Camaro Z28    4   8
        25:    Pontiac Firebird    2   8
        26:           Fiat X1-9    1   4
        27:       Porsche 914-2    2   4
        28:        Lotus Europa    2   4
        29:      Ford Pantera L    4   8
        30:        Ferrari Dino    6   6
        31:       Maserati Bora    8   8
        32:          Volvo 142E    2   4
                             rn carb cyl

*****
## Output of `sessionInfo()`
        R version 4.3.2 (2023-10-31)
        Platform: x86_64-redhat-linux-gnu (64-bit)
        Running under: Fedora Linux 38 (Workstation Edition)
        
        Matrix products: default
        BLAS/LAPACK: FlexiBLAS OPENBLAS-OPENMP;  LAPACK version 3.11.0
        
        locale:
         [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=hu_HU.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=hu_HU.UTF-8   
         [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=hu_HU.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
        [11] LC_MEASUREMENT=hu_HU.UTF-8 LC_IDENTIFICATION=C       
        
        time zone: Europe/Budapest
        tzcode source: system (glibc)
        
        attached base packages:
        [1] stats     graphics  grDevices utils     datasets  methods   base     
        
        other attached packages:
        [1] data.table_1.14.8
        
        loaded via a namespace (and not attached):
         [1] vctrs_0.6.4       svglite_2.1.2     httr_1.4.7        cli_3.6.1         knitr_1.45        rlang_1.1.2       xfun_0.41         stringi_1.7.12   
         [9] processx_3.8.2    purrr_1.0.2       generics_0.1.3    pingr_2.0.2       glue_1.6.2        bit_4.0.5         colorspace_2.1-0  htmltools_0.5.7  
        [17] ps_1.7.5          scales_1.2.1      rmarkdown_2.25    evaluate_0.23     munsell_0.5.0     kableExtra_1.3.4  fastmap_1.1.1     lifecycle_1.0.4  
        [25] stringr_1.5.0     insight_0.19.6    compiler_4.3.2    rvest_1.0.3       timechange_0.2.0  rstudioapi_0.15.0 systemfonts_1.0.5 digest_0.6.33    
        [33] viridisLite_0.4.2 R6_2.5.1          magrittr_2.0.3    webshot_0.5.5     tools_4.3.2       bit64_4.0.5       lubridate_1.9.3   xml2_1.3.5

**Comment by ben-schwen** [comment]
I don't get the advantage of using `keepcolsv` over passing the `cols` argument directly to j. It just introduces another level of silencing the error that some columns passed j do not exist

**Comment by sbudai** [comment]
> I don't get the advantage of using `keepcolsv` over passing the `cols` argument directly to j. It just introduces another level of silencing the error that some columns passed j do not exist

I work with very wide tables oftentimes, which are used for making predictions. The  observation identifiers, the response variable are the same, but the predictor set are somewhat vary from time to time, and the input table along with it as well. But the used script are the same.
I found it more parsimonious way of scripting to at first to list the union set of all possible predictor columns and keep in the table what is available. After that I branch the script and in each branch I check the existence of differentiator predictors only .
The other way around would be to branch the script first, and then select (list) the specifically needed columns as many times as many branch there are.

Still, I accept that it can be dangerous.

A compromise can be using a `strict` argument with TRUE default value, by which it would emit "error" message in case of not existing column name(s). I modified the issue accordingly.

**Comment by jangorecki** [comment]
If columns varies then one option could be to melt then into rows

**Comment by ben-schwen** [comment]
The still doesn't convince me really especially since for that use-case I would not touch the input tables and use a `formula` (combined with `data.matrix` if the estimation packages does not support formulas for models).

In any case I guess that `data.table` idiomatic way would be smth like this
```r
keep = function(x, cols, strict = TRUE) {
  if (strict) {
    excess_cols = base::setdiff(x = cols, y = colnames(x))
    if (length(excess_cols) > 0L) stop(sprintf(fmt = "'%s' is not a valid column name   ", excess_cols))
  }
  sel = data.table:::colnamesInt(x, cols)
  x[, sel, with=FALSE]
}
```

**Comment by sbudai** [comment]
The "strict" clause does not worth to dwell so long, so I'll let that go off. So the streamlined FPO chainable function would look like this:
```
keepcolsv = function(x, cols) {
  excess_cols = base::setdiff(x = cols, y = colnames(x))
  if (length(excess_cols) > 0L) stop(sprintf(fmt = "'%s' is not a valid column name   ", excess_cols))
  sel = data.table:::colnamesInt(x, cols)
  x[, sel, with=FALSE]
}
```
The aforementioned "keep" function name is already used by the **purrr** package ([see here](https://cran.r-project.org/web/packages/purrr/purrr.pdf)).
*****
Other: I read the support and contributing guidelines, but I have not found what would be the sign of that stage when "an idea would be accepted in principle".

**Comment by ben-schwen** [comment]
On second thought, that feature is just `base::subset(x, select=cols)`, isn't it?

In general, requested features make it into the package when multiple people are requesting them, and they follow the basic principles of easy syntax and speed (advantage).

What I find interesting is more the `set` part of the feature. Currently one can delete columns by reference with `set(dt, j="colname", value=NULL)`, but deleting every column except j is something we are really missing, hence, something like `set(dt, j=-"colname", value=NULL)`.

Selecting columns already works in that way:
``` r
library(data.table)
dt = as.data.table(mtcars)
dt[1:5, "mpg"]
#>      mpg
#>    <num>
#> 1:  21.0
#> 2:  21.0
#> 3:  22.8
#> 4:  21.4
#> 5:  18.7
dt[1:5, -"mpg"]
#>      cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <num> <num> <num> <num> <num> <num> <num> <num> <num> <num>
#> 1:     6   160   110  3.90 2.620 16.46     0     1     4     4
#> 2:     6   160   110  3.90 2.875 17.02     0     1     4     4
#> 3:     4   108    93  3.85 2.320 18.61     1     1     4     1
#> 4:     6   258   110  3.08 3.215 19.44     1     0     3     1
#> 5:     8   360   175  3.15 3.440 17.02     0     0     3     2
```

**Comment by sbudai** [comment]
First of all, related to `keepcolsv()` yes, you are right, it is the same as `base::subset(x, select=cols)`. (It is shame that I have not encountered with that function, although I have been using R since 2015.)
<br>
Related to the set part of the feature, in general, I do that in this - somewhat verbose - way:
```
set( x     = dt,
     j     = base::setdiff(x = names(dt), y = c("cyl", "disp", "gear")),
     value = NULL )
```

It is definitely more succinct this way:
```
set( x     = dt,
     j     = -c("cyl", "disp", "gear"),
     value = NULL )
```
But the mental abstraction of this function might be sluggish. "Remove those columns which are not listed here. That is it means that keep those which are listed."
Probably this way would be more intuitive:
```
set( x     = dt,
     j     = c("cyl", "disp", "gear"),
     value = .SD )
```
"Keep those columns which are listed here."

**Comment by tdeenes** [comment]
I think for any non-beginner data.table-user the "succinct" example says "Set the values of the columns of `dt` which are NOT in `j` to `value`". In any R data.frame a column is NULL if and only if it is not present in the data.frame, so setting the value of any column to NULL means you remove it. (NB: you can have a list(!) of NULLs in a data.frame column, but this is a different story.)

Your proposed syntax is meaningless: `.SD` in data.table stands for `subset-of-data` (column-wise, where the default is all columns, but can be modified by providing `.SDcols` explicitly).

**Comment by tdeenes** [comment]
A nicer way to achieve what you are after is to use closures; that is, create a wrapper of `set` which also accepts functions acting as column selectors. E.g.:

**Comment by jangorecki** [comment]
- I would prefer not to introduce NSE into `set` (`-"mpg"`)
- I would expect users to keep using `setdiff` etc.; we could try to cover every possible scenario by providing extra functions or extra arguments to existing functions, and it would make it more convenient, but we will end up with tons of functions and many arguments which adds extra burden for newcomers. I would say, let them learn base R as well, rather than try to solve everything in "datatableverse" way.
- 
Ultimately we need to balance between user convenience and too many funs/args, we could keep the issue open and see how much upvotes and downvotes it will get over time.

**Comment by sbudai** [comment]
As a side note, the `value = .SD` version can be run and has an inplace effect on the table without error message. It removes all the columns listed in `j`, that is same as `value = NULL`.
```
library(data.table)
data(mtcars)
setDT(mtcars, keep.rownames = TRUE)

set(x     = mtcars,
    j     = c("cyl", "disp", "gear"),
    value = .SD )

head(mtcars)
```

                      rn  mpg  hp drat    wt  qsec vs am carb
    1:         Mazda RX4 21.0 110 3.90 2.620 16.46  0  1    4
    2:     Mazda RX4 Wag 21.0 110 3.90 2.875 17.02  0  1    4
    3:        Datsun 710 22.8  93 3.85 2.320 18.61  1  1    1
    4:    Hornet 4 Drive 21.4 110 3.08 3.215 19.44  1  0    1
    5: Hornet Sportabout 18.7 175 3.15 3.440 17.02  0  0    2
    6:           Valiant 18.1 105 2.76 3.460 20.22  1  0    1

**Comment by jangorecki** [comment]
> .SD

this is not just same as `value=NULL` it is `NULL`.

Try typing `.SD` in console alone.
So you can easily write `set(...., value=NULL)` instead and it will be easier for those reading the code

**Comment by franknarf1** [comment]
For the non-set part, there is even `subset.data.table` -- no need for `base::subset`

----

For the `set*` part, I think the FR is met by adding an argument eg `setcolorder(..., select = FALSE)` so it behaves like:

```r
newsetcolorder = function(x, neworder, ..., select = FALSE){
    if (select) n = length(neworder)
    setcolorder(x, neworder, ...)
    if (select) set(x, j = setdiff(seq_along(x), seq_len(n)), value = NULL)
    return(invisible(x))
}
```

@sbudai Btw, `setcolorder` is already chain-able (from the docs: "it can be used in compound statements") and helpfully checks for dupes etc first. 

If my understanding is correct, could edit the title to request the new arg; so people can vote on just that part then -- or maybe open a new PR? (I'm not sure about the best practice in this case)

**Comment by sbudai** [comment]
Let me summarize the current state of this tread.    

1. The main issue stated in the title - as it turned out - was not a real issue, since `subset()` can satisfy the requirement luckily.
2. I also wrote about a "set-style" counterpart, which I mentioned for syntax similarity reason, but - by design - could not be chainable. Although its syntax has been questioned for good reasons, the convenience functionality included in it may or may not be worth developing.

Since the main issue is resolved, the additional issue is about something different than the title, and the whole thread is cumbersome to read, I think - in its current form - it not focused enough. So I thought to close it.   
    
Thank you all for your insights!
