### ISSUE TITLE
manual `\item` must not use braces inside `\itemize` and `\enumerate`

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5747]
> CHANGES IN R-devel UTILITIES
> When checking Rd files, ‘R CMD check --as-cran’ now notes some of the “lost braces” that ‘tools::checkRd()’ finds. Typical problems are Rd macros missing the initial backslash (e.g., ‘code{...}’), in-text set notation (e.g., ‘{1, 2}’, where the braces need escaping), and \itemize lists with _description_-like entries of the form \item{label}{description}.

Fix already submitted (vs master branch) inside #5746, thanks to @mmaechler 

We need to include it in 1.14.10 (branched from 1.14.8) coming patch release as well.

We need to ensure it is included in CI because multiple of pending PRs uses `\item{}` inside `\itemize`

**Comment by mmaechler** [comment]
You are welcome.  I think you should edit the title (and part of the above):
In `Rd`, as in LaTeX, 
- `\item{.}` *must* be used in some cases (in LaTeX inside `\description{ .. }`), in Rd, inside `\arguments{ ..}`  and `\describe{ .. }`  *and* inside `\value{..}` where it has the special meaning for list-like results
- but makes *no* sense  (and may be misleading) inside  `\itemize{..}` and `\enumerate{..}`
