### ISSUE TITLE
[R-Forge #2682] keep.rownames could accept a column name instead of always "rn"

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#575]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2682&group_id=240&atid=978)

Setting keep = "Date" would keep rownames and call the first column "Date" rather than "rn".

**Comment by and3k** [comment]
:+1:
Came here to request the same! :)
Thanks!!
