### ISSUE TITLE
[R-Forge #2657] Ricardo's ListTransform functions

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#576]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2657&group_id=240&atid=978)

Example here :
http://stackoverflow.com/questions/15753091/convert-mixed-length-named-list-to-data-frame

**Comment by MichaelChirico** [comment]
Actually this answer looks quite nice, just uses existing arguments to `rbindlist`:

https://stackoverflow.com/a/34647961/3576984

**Comment by jangorecki** [comment]
agree with @MichaelChirico that `rbindlist` can handle that nicely
```r
library(data.table)
list = list(list(a=1,b=3,c=5),list(c=2,a=3))
rbindlist(list,fill=TRUE)
```
