### ISSUE TITLE
Lehman database in .SD vignette broken

### ISSUE THREAD

**Issue by TysonStanley** [Rdatatable/data.table#5767]
The current link is broken (https://www.seanlahman.com/baseball-archive/statistics/) but there are some alternatives we can use:

1. The GitHub page for the Lehman package: https://github.com/cdalzell/Lahman
2. The link on seanlahman's website: http://seanlahman.com/download-baseball-database/ (but it's not secure)

The README link is also broken (https://www.seanlahman.com/files/database/readme2017.txt). Best bet is probably the GitHub page for the R package at this point.

**Comment by MichaelChirico** [comment]
R package makes most sense to me

**Comment by jangorecki** [comment]
fixed by 0338ed4f5b9839a8de2cc01c90a4673a5d8bbab1
