### ISSUE TITLE
[R-Forge #2644] ITime should be milliseconds from midnight

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#577]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2644&group_id=240&atid=978)

As raised here :

http://r.789695.n4.nabble.com/Suggestion-on-ITime-class-implementing-tp4662281.html

Also,  IDateTime.R needs a revamp to obliterate POSIXlt from it.

As I've written before (but can be difficult to find) I tend to use YYYYMMDDL and HHMMSSMMML i.e. no DateTime class at all.

**Comment by jangorecki** [comment]
covered in #1451, I think it can be closed as duplicate then.
