### ISSUE TITLE
cut off NEWS.md file

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5775]
It is getting too long IMO reaching as back as v1.10.0 (03 Dec 2016).

**Comment by TysonStanley** [comment]
I agree. If someone wants a history lesson on data.table there are other sources ;) Should we keep a five year NEWS.md?

**Comment by MichaelChirico** [comment]
I think the idea is to truncate the current file as (e.g.) NEWS.1.md and continue on, similar to how r-devel does it.

**Comment by TysonStanley** [comment]
Makes sense. So would we keep 1 or 2 years in the NEWS.md while putting the rest into NEWS.1.md? Looks like NEWS.0.md has 8 years of notes so unlikely to be much of a guide that way.

**Comment by MichaelChirico** [comment]
r-devel does a new NEWS for each major version, but we don't look to be
going to 2.0.0+ any time soon. Maybe what makes sense for us is
data.table-0.x.y in NEWS.0, then data.table-1.[0-9].y in NEWS.1.0,
data.table-1.1[0-9].y in NEWS.1.1, data.table-1.2[0-9].y in NEWS.1.2, etc?

**Comment by jangorecki** [comment]
Or just keep all history of 3+ years in NEWS.0.md

**Comment by MichaelChirico** [comment]
> Or just keep all history of 3+ years in NEWS.0.md

GitHub UI struggles with huge files, better to keep a few around IMO.

**Comment by jangorecki** [comment]
but CTRL+F is easier for single file on the other hand, and so old entries are rarely needed
