### ISSUE TITLE
-Wformat-extra-args compiler warning

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5778]
```
sudo docker run -it --rm rocker/r-devel /bin/bash
mkdir -p ~/.R
echo 'CFLAGS=-Wformat -Wformat-extra-args' > ~/.R/Makevars
echo 'CXXFLAGS=-Wformat -Wformat-extra-args' >> ~/.R/Makevars

## optional
wget https://cran.r-project.org/src/contrib/data.table_1.14.8.tar.gz
RD CMD INSTALL data.table_1.14.8.tar.gz
```
```
ijoin.c:323:22: warning: too many arguments for format [-Wformat-extra-args]
  323 |     default: error(_("Internal error: unknown type in mult=ALL in overlaps: %d"), mult, type); // #nocov
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by jangorecki** [comment]
This was already fixed in hotfix branch when fixing other errors.

**Comment by MichaelChirico** [comment]
@jangorecki side note -- since you've already got a good docker flow set up for this, would you mind running `-Wall` and sharing what pops out? While we're in a mood of fixing compiler warnings we might get out ahead of future CRAN warnings if possible.

(we don't have to fix everything under `-Wall`, but can decide case-by-case which are worthwhile checks)

**Comment by jangorecki** [comment]
we won't see much yet because https://github.com/Rdatatable/data.table/issues/5748 is stopping jobs due to the failure from #5748. grep for warnings in installation output is after the package check.

**Comment by jangorecki** [comment]
When looking at the logs (on master) I see
```
Found the following significant warnings:
  assign.c:1200:13: warning: format ‘%p’ expects argument of type ‘void *’, but argument 4 has type ‘struct SEXPREC **’ [-Wformat=]
  assign.c:1200:13: warning: format ‘%p’ expects argument of type ‘void *’, but argument 5 has type ‘R_len_t *’ {aka ‘int *’} [-Wformat=]
```
we should definitely run hotfix branch on CI to ensure if all issues has been caught
