### ISSUE TITLE
vignettes avoid max.print

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5783]
New vignette added in (to be) 1.14.99 uses `options(max.print = ...)`. As a side effect, all vignettes, that are being rendered after that one, are inheriting this options, and it gets messy. See https://jangorecki.github.io/armarkdown/rmarkdown/datatable-reference-semantics.html

**Comment by MichaelChirico** [comment]
> New vignette added in (to be) 1.14.99 uses `options(max.print = ...)`. As a side effect, all vignettes, that are being rendered after that one, are inheriting this options, and it gets messy. See https://jangorecki.github.io/armarkdown/rmarkdown/datatable-reference-semantics.html

is this documented behavior (`options()` persisting across rendering all vignettes)?

(approach in #5784 is preferable anyway, but maybe this is an R bug)

**Comment by jangorecki** [comment]
no idea, I am not digging that deep :D
