### ISSUE TITLE
frollsum/frollmean unexpected behavier of fill argument

### ISSUE THREAD

**Issue by ClaudioHeinrich** [Rdatatable/data.table#5812]
Hey,

not exactly sure whether this is a feature or a bug. 

In the `frollsum`- and `frollmean`-documentation, the `fill`-argument is documented as *numeric, value to pad by. Defaults to NA.*
However, it does not actually seem to pad, but to replace the values for windows overlapping the edges by the fill value.
For example, we have:

``` r
data.table::frollsum(x = 1:3, n = 3, fill = 0)
#> [1] 0 0 6
```

<sup>Created on 2023-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

In my understanding, if we would actually *pad* with zeros, we'd calculate the rolling sum over 0, 0, 1, 2, 3, which would result in 1, 3, 6 instead. So if the current behavior is on purpose, you might consider rephrasing the documentation.

I'd find it actually more useful if the behavior of `fill` would change and it would pad as described above, as calculating such padded sums seems kind of hard to do right now while grouping in by?

**Comment by jangorecki** [comment]
No, padding is meant to be a value to be filled in when window size is incomplete.

Padding is a value to be filled in the answer when window size is incomplete.

Behavior will not change. It was designed after famous and very popular, for a long time already, package `zoo`.
```r
data.table::frollsum(x = 1:3, n = 3, fill = 0)
#[1] 0 0 6
zoo::rollsumr(x = 1:3, k = 3, fill = 0)
#[1] 0 0 6
```
On current master.

----

You may want to check `partial=TRUE` argument. It won't fill missing observations in the window with 0 (or other `fill` value), but it will compute a function using smaller window size (so the `fill` is then ignored). This feature is not yet in master branch, therefore you need to install branch from github. I recommend to use `rollmedian` branch. Easiest way to do it from R is with `remotes` package:
```r
remotes::install_github("Rdatatable/data.table@rollmedian")
data.table::frollsum(x = 1:3, n = 3, partial=TRUE)
#[1] 1 3 6

```
