### ISSUE TITLE
1.14.10 tarball has 1.14.9 version in DESCRIPTION

### ISSUE THREAD

**Issue by barracuda156** [Rdatatable/data.table#5816]
Please fix the version, otherwise it breaks the build. The current tag for 1.14.10 b84dbb051d246aa48a7d8f5dada814830f6e36dc has a wrong version in DESCRIPTION.

**Comment by TysonStanley** [comment]
Was working to match what Matt had done previously but running into annoying tag issues

**Comment by TysonStanley** [comment]
Think I have it solved if we want to commit 1.14.10 in description/init.c for the tag

**Comment by jangorecki** [comment]
Now I see that tags do have even numbers. Which opposes release procedure

>  Bump minor version in DESCRIPTION to next odd number. Note that DESCRIPTION was in edited and uncommitted state so even number never appears in git.

Possibly Matt meant that even numbers are never in master?

**Comment by TysonStanley** [comment]
@jangorecki that's my guess? I can bump the version in hot fix and then tag that commit.

**Comment by barracuda156** [comment]
> What builds does it break? ~Even tags in git never had even numbers in DCF, as opposed to CRAN releases. Do you have the same problem on the previous tags as well?~

@jangorecki In Macports; `R CMD build` uses version number from `DESCRIPTION`, apparently, to make a tarball, and then it mismatches the version in the port, so installation fails due to the right tarball not being found.

**Comment by jangorecki** [comment]
@TysonStanley yes, and ideally update release procedure (in master) to reflect that

**Comment by TysonStanley** [comment]
Fixed tag: https://github.com/Rdatatable/data.table/releases/tag/1.14.10
