### ISSUE TITLE
`value.var` columns are not present in the output of `dcast` even if they are included  in LHS of formula through `...`

### ISSUE THREAD

**Issue by iago-pssjd** [Rdatatable/data.table#5824]
Hi,

**Update**

`dcast` output does not include last column of input data when it is included  in LHS of formula through `...`, `value.var` is missing and `fun.aggregate` is `length`.

This can be generalised, since under these conditions (`value.var` is missing and `fun.aggregate` is `length`), `value.var` becomes the last column. Therefore, the issue is that any `value.var` column will not be included in the output if it is not explicitly mentioned in the formula.

**Issue as initially found:**
I will explain this bug by means of a reproducible example, since I am not sure of its cause (and so, of the title of the issue).

The code
```r
library(data.table)
test <- data.table("index" = rep(letters[1:2],2), "indexU" = rep(letters[11:12],2), "var1" = rnorm(4,0,1), "var2" = rnorm(4,0,1))
#print(test)

test <- dcast(test[, r := .I], r + ... + index ~ index, fun = length)
#print(test)

test <- dcast(test, r + ... + indexU ~ indexU, fun = length)
#print(test)
```
The initial `test` data.table:
```r
   index indexU       var1       var2
1:     a      k -0.6914432 1.06764510
2:     b      l  1.5993563 0.33203747
3:     a      k -1.4733880 0.07003668
4:     b      l -0.2550293 1.67193531
```
`index` are the letters a,b and `indexU` are the letters k,l (where I place letters, it could be any categorical variable; these are character, but they may be factor class).

The first `dcast` works nicely, producing dummy variables for `index` categories as expected (thanks to https://stackoverflow.com/a/18881195/997979), while keeping `index` variable. Its output:
```r
   r indexU       var1       var2 index a b
1: 1      k -0.6914432 1.06764510     a 1 0
2: 2      l  1.5993563 0.33203747     b 0 1
3: 3      k -1.4733880 0.07003668     a 1 0
4: 4      l -0.2550293 1.67193531     b 0 1
```

But when I apply the second `dcast`, it does what expected for `indexU`, but it removes last dummy variable, `b`:
```r
   r       var1       var2 index a indexU k l
1: 1 -0.6914432 1.06764510     a 1      k 1 0
2: 2  1.5993563 0.33203747     b 0      l 0 1
3: 3 -1.4733880 0.07003668     a 1      k 1 0
4: 4 -0.2550293 1.67193531     b 0      l 0 1
```

Why? How can I avoid this behaviour? 

Thanks!

I have just updated to `data.table` 1.14.10, but it happened to me with development version 1.14.9.

```r
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Spanish_Spain.utf8  LC_CTYPE=Spanish_Spain.utf8    LC_MONETARY=Spanish_Spain.utf8 LC_NUMERIC=C                   LC_TIME=Spanish_Spain.utf8    

time zone: Europe/Madrid
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.10

loaded via a namespace (and not attached):
[1] compiler_4.3.2 tools_4.3.2   

```

**Comment by tdhock** [comment]
Seems like an issue with ... in dcast formula
?dcast says
```
There are
     two special variables: '.' represents no variable, while '...'
     represents all variables not otherwise mentioned in 'formula';
```
There is only one example with ...
```r
     DT <- data.table(v1 = rep(1:2, each = 6),
                      v2 = rep(rep(1:3, 2), each = 2),
                      v3 = rep(1:2, 6),
                      v4 = rnorm(6))
     dcast(DT, ... ~ v3, value.var="v4") # same as v1+v2 ~ v3, value.var="v4"
```
There are a couple of tests with dcast and ...
```
  # FR #335 and DOC #332
  set.seed(1L)
  DT = data.table(a=sample(10), b=2013:2014, variable=rep(c("c", "d"), each=10), value=runif(20))
  test(1102.18, names(dcast(DT, a ~ ... + b, value.var="value")), c("a", "c_2013", "c_2014", "d_2013", "d_2014"))

  # dcast.data.table new tests
  # Fix for #1070 (special case of ... on LHS)
  DT = data.table(label= month.abb[1:5], val=0)
  test(1102.28, dcast(DT,... ~ label, value.var="val", sum),
                data.table(`.`=".", Apr=0, Feb=0, Jan=0, Mar=0, May=0, key="."))

```

Below is modification of original code, which shows that ... is not being interpreted as claimed (I manually changed the ... to all the other column names not mentioned in the formula)

```r
> (test <- data.table(index=c("a","b"), indexU=c("k","l"), var1=1:4, var2=5:8))
    index indexU  var1  var2
   <char> <char> <int> <int>
1:      a      k     1     5
2:      b      l     2     6
3:      a      k     3     7
4:      b      l     4     8
> (out1 <- dcast(test[, r := .I], r + ... + index ~ index, fun = length))
Key: <r, indexU, var1, var2, index>
       r indexU  var1  var2  index     a     b
   <int> <char> <int> <int> <char> <int> <int>
1:     1      k     1     5      a     1     0
2:     2      l     2     6      b     0     1
3:     3      k     3     7      a     1     0
4:     4      l     4     8      b     0     1
> (out.dots <- dcast(out1, r + ... + indexU ~ indexU, fun = length))
Key: <r, var1, var2, index, a, indexU>
       r  var1  var2  index     a indexU     k     l
   <int> <int> <int> <char> <int> <char> <int> <int>
1:     1     1     5      a     1      k     1     0
2:     2     2     6      b     0      l     0     1
3:     3     3     7      a     1      k     1     0
4:     4     4     8      b     0      l     0     1
> (out.no.dots <- dcast(out1, r + var1 + var2 + index + a + b + indexU ~ indexU, fun = length))
Key: <r, var1, var2, index, a, b, indexU>
       r  var1  var2  index     a     b indexU     k     l
   <int> <int> <int> <char> <int> <int> <char> <int> <int>
1:     1     1     5      a     1     0      k     1     0
2:     2     2     6      b     0     1      l     0     1
3:     3     3     7      a     1     0      k     1     0
4:     4     4     8      b     0     1      l     0     1
```

**Comment by iago-pssjd** [comment]
The issue seems to be when

https://github.com/Rdatatable/data.table/blob/f1be897218821ffd631bad4443e24fc56c85fd81/R/fcast.R#L119

zooming, in

https://github.com/Rdatatable/data.table/blob/f1be897218821ffd631bad4443e24fc56c85fd81/R/fcast.R#L37

and so in

https://github.com/Rdatatable/data.table/blob/f1be897218821ffd631bad4443e24fc56c85fd81/R/fcast.R#L40-L51

since, debugging `dcast(out1, r + var1 + var2 + index + a + b + indexU ~ indexU, fun = length)`) one gets
```r
varnames
[1] "r"      "indexU" "var1"   "var2"   "index"  "a"      "b"     
> allvars
[1] "r"      "var1"   "var2"   "index"  "a"      "b"      "indexU" "b"     
> deparse_formula(as.list(formula)[-1L], varnames, allvars) |> print()
[[1]]
[[1]][[1]]
r

[[1]][[2]]
var1

[[1]][[3]]
var2

[[1]][[4]]
index

[[1]][[5]]
a

[[1]][[6]]
b

[[1]][[7]]
indexU


[[2]]
[[2]][[1]]
indexU

```
while debugging the problematic `dcast` (`dcast(out1, r + ... + indexU ~ indexU, fun = length)`) `b` is not in the output
```r
> varnames
[1] "r"      "indexU" "var1"   "var2"   "index"  "a"      "b"     
allvars
[1] "r"      "indexU" "b"   
> deparse_formula(as.list(formula)[-1L], varnames, allvars) |> print()
[[1]]
[[1]][[1]]
r

[[1]][[2]]
var1

[[1]][[3]]
var2

[[1]][[4]]
index

[[1]][[5]]
a

[[1]][[6]]
indexU


[[2]]
[[2]][[1]]
indexU
```

**Comment by iago-pssjd** [comment]
cc @MichaelChirico, who has worked this function in its last commits (https://github.com/Rdatatable/data.table/commit/bdc6da98b6dc1276accd906d1ec0f0cd921bbfc4, https://github.com/Rdatatable/data.table/commit/44e20ba434ce5ee4b472b1667fe58132af10f06d)

**Comment by MichaelChirico** [comment]
thanks for reporting and investigating @iago-pssjd, it looks like you're close to understanding the issue, would you like to have a go at a PR? we are happy to help along the way.

**Comment by iago-pssjd** [comment]
Actually I am not sure where the issue is and I do not understand the "function" and "interaction" of the functions `check_formula` and `deparse_formula`.
Could it be also due to the `allvars` argument passed to the function `deparse_formula`?


In the more nested `deparse_formula`, it returns `setdiff(varnames, allvars)`, so `"var1"   "var2"   "index"  "a"`, while `r` and `indexU` are got later, since they appear in the formula. But `"b"` is in `valnames` (in `check_formula` ), and so in `allvars`, not being in the formula it is not returned.

`"b"` in `valnames` comes from `dcast`
```r
if (missing(value.var) && !missing(fun.aggregate) && identical(fun.aggregate, 
    length)) 
    value.var = names(data)[ncol(data)]
  lvals = value_vars(value.var, names(data))
  valnames = unique(unlist(lvals))
```
but what is its function in `allvars`? And why nested `deparse_formula` returns `setdiff(varnames, allvars)`?

**Comment by iago-pssjd** [comment]
BTW, I found the source of these functions in a commit introducing several features: https://github.com/Rdatatable/data.table/commit/25a74dfd8b738e5e5556144d38713b6b003a56f2

**Comment by jangorecki** [comment]
What makes dev easier is to use cc() function. You will find it in .dev dir. Then it's very straightforward to put extra print(); cc(); dcast(). cc() is fast rebuilding package so you don't want for compilation.

**Comment by tdhock** [comment]
> What makes dev easier is to use cc() function. You will find it in .dev dir. Then it's very straightforward to put extra print(); cc(); dcast(). cc() is fast rebuilding package so you don't want for compilation.

great suggestion. where is cc() documented? I have never used it but I would like to. Can you please make a screencast next time you use it, so you could show others how?

**Comment by ben-schwen** [comment]
> > What makes dev easier is to use cc() function. You will find it in .dev dir. Then it's very straightforward to put extra print(); cc(); dcast(). cc() is fast rebuilding package so you don't want for compilation.
> 
> great suggestion. where is cc() documented? I have never used it but I would like to. Can you please make a screencast next time you use it, so you could show others how?

It's mentioned in Contributing wiki and document in [.dev/README.md](https://github.com/Rdatatable/data.table/blob/master/.dev/README.md)

In #5131 Jan and Matt also pointed out how they set their Rprofile to easily source `cc()`

**Comment by MichaelChirico** [comment]
FWIW we definitely see `...` used in LHS of `dcast()` in the wild:

https://github.com/search?q=lang%3AR+%2F%5Cn%5B%5E%23%5Cn%5D*%5B.%5D%5B.%5D%5B.%5D%5B%5E%22%27%7B%7D%5Cn%2C%5D*%5B%7E%5D%2F+%2Fdcast%5B%28%5D%2F+-path%3A.Rd&type=code

e.g.

https://github.com/shahcompbio/signals/blob/73f877382562b0a981e9418f3371163f6bf46a9f/R/combinedata.R#L28
https://github.com/ihmeuw/ihme-modeling/blob/3e97f2c65399178a2f9de5113944a2684c4590a1/gbd_2021/mortality_code/harmonize-implied-em/upload_cc_draws.R#L93
