### ISSUE TITLE
Loading package via `devtools::load_all()` errors

### ISSUE THREAD

**Issue by ben-schwen** [Rdatatable/data.table#5827]
I know that we have `cc()` for recompiling and attaching the package. However, people unfamiliar with `data.table` dev might try to use `devtools::load_all()` which currently errors on loading.

```r
devtools::load_all()
#  Error in gzfile(file, "rb") : cannot open the connection
#  In addition: Warning message:
#  In gzfile(file, "rb") :
#    cannot open compressed file '', probable reason 'No such file or directory'
```

Minimal change to `.onLoad` would enable `devtools::load_all()` to also work.

**Comment by TysonStanley** [comment]
Would definitely make the development easier for a lot of people if we can make `devtools::load_all()` work. If it's a small change, send like a smart move to ease the addition of new contributors.

**Comment by jangorecki** [comment]
> Would definitely make the development easier

As long as it behaves as expected (which unfortunately was not always the case), otherwise wastes many hours of debugging.
Anyway good to have it working for those who prefer.
