### ISSUE TITLE
[R-Forge #2597] Build in Andrie's technique of avoiding `==` in `j`

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#584]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2597&group_id=240&atid=978)

Never realised this before:  `==` in `j` has overhead of course.  Usually we talk about `==` in i.

See technique Andie used to get 10\* improvement :

http://stackoverflow.com/a/15273669/403310

Maybe we can build this into data.table optimization somehow.

**Comment by MichaelChirico** [comment]
Don't really know what this implementation would look like, and doesn't seem like it's piqued any interest in 10 years. Closing.
