### ISSUE TITLE
test() should get an options= argument to transparently & temporarily set options for a test

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#5842]
https://github.com/Rdatatable/data.table/blob/6c1fd839e0e0257d13f07975ead0fe6fdfee2f61/R/test.data.table.R#L252

Now, we set options sporadically in the text, e.g.

https://github.com/Rdatatable/data.table/blob/6c1fd839e0e0257d13f07975ead0fe6fdfee2f61/inst/tests/froll.Rraw#L306
https://github.com/Rdatatable/data.table/blob/6c1fd839e0e0257d13f07975ead0fe6fdfee2f61/inst/tests/froll.Rraw#L343

Having the option set 50, 100, or more lines away from where the value is needed harms readability. It's much better to set the options transparently in the call to `test()`.

Proposed API:

```r
test(..., options = list(key1 = "val1", ..., keyn = "valn"))

# impl
test <- function(..., options = NULL) {
  if (!is.null(options)) {
    old <- do.call("options", options)
    on.exit(options(old), add = TRUE)
  }
  ...
}
```

Possibly `tmp_options=` is a better name so as not to clash with `options()`, then we can do `do.call(options, tmp_options)`.

**Comment by MichaelChirico** [comment]
This would supersede #5429.

**Comment by jangorecki** [comment]
+10!
