### ISSUE TITLE
clarify AI-contributed code in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5847]
In my opinion we should explicitly request contributors not to use AI models for assisting in writing their code contributed to data.table project, as long as they are not able to examine license of the code used for model training.

Taking GitHub Copilot as an example. Microsoft says:

> You are respon­si­ble for ensur­ing the secu­rity and qual­ity of your code. We rec­om­mend you take the same pre­cau­tions when using code gen­er­ated by GitHub Copi­lot that you would when using any code you didn’t write your­self. These pre­cau­tions include rig­or­ous test­ing, IP [(= intel­lec­tual prop­erty)] scan­ning, and track­ing for secu­rity vul­ner­a­bil­i­ties.

Security and quality is something that developer and PR reviewers can easily evaluate. Intellectual properly is not. It seems that Microsoft does not provide any tools to perform mentioned intellectual property "scanning".

This would of course not apply to AI models where developer can "scan" intellectual property for compatibility to our license, and provide proper citation/authorship.

**Comment by tdhock** [comment]
maybe add a note on https://github.com/Rdatatable/data.table/wiki/Contributing ?

**Comment by jangorecki** [comment]
@MichaelChirico @tdhock @ben-schwen @TysonStanley wdyt about moving this guide from wiki to .github dir, where github normally expects it to be?
I was thinking about adding PR template as well, that would use the location in .github.

Currently the file is just pointing to wiki, and both points that tries to justify that are not very correct IMO.

> so it can be revised easily in one place by anyone

I don't think it's a good idea that anyone can edit our contribution guidelines.

> so that revsions do not trigger Continuous Integration checks

GLCI has been changed to run nightly rather than on each commit. So that's not an issue anymore.

**Comment by ben-schwen** [comment]
The only problem about wiki I see is that GitHub could suddenly decide to shut it down (similar to what they did with group member posts). Having everything in one place (the repository itself) is definitely preferred if we ever decide to move.

**Comment by MichaelChirico** [comment]
Agree for consistency with other projects it belongs in the repo itself. Some organizations might even have a policy requiring CONTRIBUTING before their employees could offer PRs -- having it in an "unexpected" place could cause bureaucratic hassle preventing contributions.

**Comment by TysonStanley** [comment]
I agree with the others. Let's put it in the repo, if .github is the expected location for GitHub then let's do that.

**Comment by MichaelChirico** [comment]
Two more points in favor of tracking the file in the repo itself:

 1. Easier for project members to keep up with edits to the contribution rules (I noticed a few small points that had escaped my notice since Wiki edits don't trigger notifications)
 2. Now that project members can commit directly, there's not the overhead of review toil that was imposing previously. I.e., before, trivial Contributing edits required attention from Matt, but now we can just file edits as a PR and merge right away -- members will still get visibility about a change and can request 'revert', but that needn't slow down trivial changes.

**Comment by MichaelChirico** [comment]
Hi @zhiiiyang, I'm not sure if this is something you did intentionally or not, but we got a request for Rdatatable org to set up GitHub Copilot coming from you.

As noted here, use of Copilot would go against our CONTRIBUTING guidelines, so I've rejected the request:

https://github.com/Rdatatable/data.table/blob/3c3baa9277e990df0121b4f5e0287271086502bf/.github/CONTRIBUTING.md?plain=1#L13

Thank you for your understanding & looking forward to future contributions!
