### ISSUE TITLE
[R-Forge #2595] Allow alloc.col accept symbol names as character (to wrap load())

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#585]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2595&group_id=240&atid=978)

As raised here :

http://stackoverflow.com/a/15213807/403310

and add environment argument too perhaps.

**Comment by MichaelChirico** [comment]
Not sure I understand what the advantage is, nor is there much expressed interest here >10 years later. Closing.
