### ISSUE TITLE
Quoted column names in setorder vs setorderv

### ISSUE THREAD

**Issue by nilseling** [Rdatatable/data.table#5854]
Hi Team,

sorry for raising this here as I couldn't find information on this online or in the issues. I was wondering if I can expect different behaviour of the `setorder` function when using quoted or unquoted column names. I understand that for quoted column names the `setorderv` function is in place; a piece of information that I have seen too late. However, the `setorder` function does not throw an error when quoted column names are provided. So the example below produces the same result but I was wondering if there is a setting in which quoted column names in `setorder` are an issue.

```
DT = data.table(test = c(2, 1, 3))
DT2 = copy(DT)

setorder(DT, test)
setorder(DT2, "test")
```

**Comment by ben-schwen** [comment]
There are subtle differences when using quoted names and + and - for ascending and descending order, e.g.

```r
setorder(DT, -test) # works
setorder(DT, "-test") # wont
setorder(DT, +"test") # works too
```

Doc advises to not use quoted column names but I do not see many reasons for that since quoted columns will be converted to character in any case.

**Comment by nilseling** [comment]
That's great, thanks for the explanation. Makes sense. And just to clarify, the type of the column will not be affected, right? E.g., a numeric column will not be converted into a character column before ordering when using quoted column names?

**Comment by ben-schwen** [comment]
> That's great, thanks for the explanation. Makes sense. And just to clarify, the type of the column will not be affected, right? E.g., a numeric column will not be converted into a character column before ordering when using quoted column names?

Setorder, setorderv, forder, etc. do not change column types but only change orderings.

I will consider your question as answered and close the issue but feel free to reopen if something is unclear or if you feel we could improve the documentation of setorder/setorderv.
