### ISSUE TITLE
Argument for fwrite to set the file 'Owner' on Windows

### ISSUE THREAD

**Issue by msgoussi** [Rdatatable/data.table#5858]
Is it possible to add a creator argument in fwrite that controls the owner property in Details Tab in Windows?
![image](https://github.com/Rdatatable/data.table/assets/18138496/0bfa4122-bc51-47b3-af56-63481ca6db72)

**Comment by MichaelChirico** [comment]
AFAICT the way to do so is with a command line utility 'icacls', e.g.

https://github.com/zerland/MAGMA_Celltyping/blob/8cb235fb495a467fb825819a76b2f154d3840146/R/set_permissions.R#L19-L23

Why should {data.table} own this logic? It seems more natural to me that another package/wrapper would simply follow up the `fwrite()`:

```r
fwrite(table, file)
set_acls(file)
```

**Comment by msgoussi** [comment]
when i use openxlsx::write.xlsx, there is a argument called "creator".
Thanks in advance

**Comment by MichaelChirico** [comment]
AFAICT they do so relying on some code in the C++ API. It makes more sense for a package like {openxlsx} to be deeply integrated with Windows. I think {data.table} should be more platform-agnostic.

**Comment by jangorecki** [comment]
Completely agree. A good workaround could be to use wsl in windows and run something like this
```
sudo -u newOwner R
```
