### ISSUE TITLE
set() creates a new column by ref, that disappears right after first accessing it 

### ISSUE THREAD

**Issue by fabiocs8** [Rdatatable/data.table#5865]
I have a data.table dt. Then I create two new columns:
dt[  , id := .I, verbose = TRUE]
Detected that j uses these columns: <none> 
Assigning to all 7103 rows
RHS_list_of_columns == false
RHS for item 1 has been duplicated because NAMED==65535 MAYBE_SHARED==1, but then is being plonked. length(values)==7103; length(cols)==1)

dt[  , dc := descricao_complementar, verbose = TRUE]
Detected that j uses these columns: descricao_complementar 
Assigning to all 7103 rows
RHS_list_of_columns == false
Direct plonk of unnamed RHS, no copy. NAMED==1, MAYBE_SHARED==0

At this point, I am able to see both columns at RStudio command View(dt). Also, dt$dc correctly shows the contents for dc.

However, when I run the next command, I get an error:
> dt[, dc := gsub("G\\,ML\\b", "G/ML", dc, perl=T)]
Error in is.factor(x) : object 'dc' not found
 
And the two following commands also provide errors:
> dt$id
NULL
> dt$dc
NULL

It seems that both columns have both disapeared!

A work around that fixed the problem for dc was: after running dt[  , dc := descrico_complementar, verbose = TRUE]), then run:
dt[grepl(".", dc, perl = T)]   

Now dt[, dc := gsub("G\\,ML\\b", "G/ML", dc, perl=T)] and all following instructions run as before.

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example); please be sure to set `verbose=TRUE` where possible!

I was not able to run a minimal reproducible example.  The ones I tried did not reproduce this behavior.

A have this code working properly for many months, and this problem manifested for the first time only today. 

I have boot my computer and changed the data.table version back to 1.14.8, no success. I reinstalled data.table to the current version 1.14.10.

`#` `Output of sessionInfo()`

> sessionInfo()
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8    LC_MONETARY=Portuguese_Brazil.utf8 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] readxl_1.4.3       fuzzyjoin_0.1.6    memoise_2.0.1      digest_0.6.33      stringdist_0.9.12  gsubfn_0.7         proto_1.0.0        stringi_1.8.3     
 [9] stringr_1.5.1      DBI_1.2.0          magrittr_2.0.3     data.table_1.14.10 RSQLite_2.3.4     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.15.0 tidyselect_1.2.0  bit_4.0.5         R6_2.5.1          rlang_1.1.2       fastmap_1.1.1     fansi_1.0.6       dplyr_1.1.4      
 [9] blob_1.2.4        tcltk_4.2.3       tools_4.2.3       parallel_4.2.3    utf8_1.2.4        cli_3.6.2         bit64_4.0.5       tibble_3.2.1     
[17] lifecycle_1.0.4   vctrs_0.6.5       glue_1.6.2        cachem_1.0.8      pillar_1.9.0      compiler_4.2.3    cellranger_1.1.0  generics_0.1.3   
[25] pkgconfig_2.0.3  

Please let me know if I can be of further help.

**Comment by TysonStanley** [comment]
Thanks for the issue. Can you send us an example data.table that replicates this issue? We can't replicate with the code you have provided. Something like:

```
dt = data.table(...)
dt[, id := .I, verbose = TRUE]
dt[ , dc := descricao_complementar, verbose = TRUE]
...
```

**Comment by TysonStanley** [comment]
Try to make it as similar to your current data as possible (while obviously making it sharable). This includes using the same variable types (and encoding). Often the problem will become clear as you do that. Otherwise, it's very difficult for us to determine where the issue could be happening.

**Comment by fabiocs8** [comment]
Dear Tyson, thank you. I tried to provide a minimal reproduceble example without success, It seems to be related to some internal state of the object. The best I can provide is a sample of the data  sample.RDS inside sample. zip.

This file has the object dt, that when we apply  the following code we get the error:

dt[, dc := descricao_complementar, verbose = T]  >>>>>>>> OK
dt$dc  >>>>>>>>>>>>> OK
dt [, dc := gsub("G\\,ML\\b", "G/ML", dc, perl=T)] >>>>>>>>>>>>> ERROR!
Error in eval(jsub, SDenv, parent.frame()) : objeto 'dc' não encontrado

It is very instable, sometimes the error appears as described, sometimes on further code lines, all of them gsub like the one I provided.



[sample.zip](https://github.com/Rdatatable/data.table/files/13796766/sample.zip)

**Comment by jangorecki** [comment]
Just in case you don't know. Whenever you read data table from RDS file, you should call setDT on it. When trying to reproduce the problem I also suggest to do it in R console, rather RStudio.

**Comment by fabiocs8** [comment]
If you give me the instructions on how to capture the internal state of R session and objetcts, I can gather it and send to you.

**Comment by fabiocs8** [comment]
[sample_env.zip](https://github.com/Rdatatable/data.table/files/13798316/sample_env.zip)
Please find attached the environment of the sample data JUST BEFORE running dt[, dc := descricao_complementar, verbose = T]

**Comment by ben-schwen** [comment]
Maybe I'm missing something here but using your provided regex, the only thing I get is
``` r
library(data.table)
dt = readRDS('~/Downloads/sample.RDS')
setDT(dt)
dt[, dc := descricao_complementar]
gsub('G\,ML\b', "G/ML", dt$dc, perl=TRUE)
# Error: '\,' is an unrecognized escape in character string (<input>:1:9)
```

Even when fixing the regex (using \\ to escape) and running for 100 consecutive times, does not yield a error for me.

Can you provide a sample script, including loading your provided data until you reach the error? My guess would be that a some step your `dt[i,j,by]` evalutes to something like `dt[, dc := NULL]` and thats why the consecutive call does not work.

**Comment by fabiocs8** [comment]
Hi Ben. Thank you.
Regarding regex: actually every \ should be \\, when copying the code into ghithub it droped one of them. So your regex correction  is right, thank you.

The problem is that dt misses dc column unexpectedly. As per your suggestion,  please find below a commented script:

library (data.table)

# at this point please reconstruct the environment I sent today as sample_env.RData, that is inside sample_env.zip.  
# dt data.table will appear
dt[, dc := descricao_complementar, verbose = T] #  executes ok
dt$dc #  just to see if dc was created. Executes ok and I can see dc data
dt [, dc := gsub("G\,ML\b", "G/ML", dc, perl=T)]  # ERROR!!!!!!!!
Error in eval(jsub, SDenv, parent.frame()) : objeto 'dc' não encontrado

**Comment by fabiocs8** [comment]
Regarding you comment "My guess would be that a some step your dt[i,j,by] evalutes to something like dt[, dc := NULL]..." I can assure you that it is not the case, the error happens exactly running the script above.

**Comment by jangorecki** [comment]
We don't need attempt of capturing your environment, don't waste your time on that. Simply provide reproducible example, including randomly generated data, or a flat file storing data required to reproduce the problem. Take your time, learn how to make great reproducible example, consider it as an investment, very good one in R ecosystem actually, and then come back. Otherwise you will be wasting yours and ours time.

**Comment by fabiocs8** [comment]
Dear Ben, I believe that the error is not related to data.table library, but some internal state of RStudio environment. I will open an issue there and let you know any news.  Thank you.

**Comment by fabiocs8** [comment]
The same code runs correctly using Rgui, so the issue is neither a data.table nor an R problem. Thank you.

**Comment by jangorecki** [comment]
It can always be an intersection of multiple things, including data.table, but without reproducible example, or a point in (C) code that is throwing an error, there is nothing for us to do.
We don't lock issues due to inactivity, so whenever in future reproducible example appears, we will simply re-open this issue.
