### ISSUE TITLE
[R-Forge #2582] Add fasttime to fread

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#587]
Submitted by: stat quant; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2582&group_id=240&atid=978)

As discussed in http://r.789695.n4.nabble.com/datatable-help-f2315188.html fread could benefit of a use.fasttime option.

fastmatch on the other hand can already be used together with data.table, iiuc.

**Comment by st-pasha** [comment]
The links are dead
It is unclear what this issue asks for...
