### ISSUE TITLE
interviewing possible data.table users, contributors, financiers

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#5880]
As a part of the NSF POSE project about expanding the open-source ecosystem around data.table, we will be conducting 100 interviews of various stakeholders related to the project (current or possible users, contributors, financiers), in the next few months (Jan-Mar 2024). Each of these interviews is to be short (~15 min) and the goal at the end is to get a better idea of who is using the software, who is interested/available to contribute, and what options there are for long term financing of the project (beyond the NSF project, 2023-2025). 

If you are a current or possible user/contributor/financier, and you would like to be interviewed, please contact @anirban166 who will be scheduling and conducting the interviews. Anirban has also created an editable google doc list of possible people to interview -- Anirban can you please post a link to that?

Related to #5704 which was a survey of community members -- @sluga do you have a list of names/emails of people who filled out your survey, that we could possibly ask to interview?

**Comment by Anirban166** [comment]
Sure! Here is the link to my google doc: [data.table interviewee list](https://docs.google.com/document/d/1pZkBQWzsMzkueRkie5-Aq0br6O4va8pC5hYeWNIvKls/edit?usp=sharing)

Please feel free to go ahead and include your name and email address along with your availability for the short interview!

The ideal candidates for the interviews include, but are not restricted to:
- Current and former contributors
- [Issue](https://github.com/Rdatatable/data.table/issues) authors with no PRs
- Package publishers that depend on data.table
- data.table users from big companies
- Ones mentioned in the [description](https://github.com/Rdatatable/data.table/blob/master/DESCRIPTION) but not actively contributing anymore

[ac4743@nau.edu](mailto:ac4743@nau.edu) is the email address that I can be reached at for communication regarding this.

Note: The interviews are to begin from the 17<sup>th</sup> of January as per the official timeline. I'm also on vacation till the second week of this month or till the 14<sup>th</sup> of Jan, so I'll be on hiatus from checking emails till then.

**Comment by tdhock** [comment]
@kbodwin @TysonStanley please add possible people to interview to the list linked above, https://docs.google.com/document/d/1pZkBQWzsMzkueRkie5-Aq0br6O4va8pC5hYeWNIvKls/edit

**Comment by TysonStanley** [comment]
@MichaelChirico we found out that we need to have several of these completed by the end of this week. Would you have 15 minutes to have a quick chat? Can send the questions ahead of time to make it ultra efficient. Same goes for @jangorecki and @ben-schwen if you have time.

**Comment by Anirban166** [comment]
Just a quick update - the interviews are going well (~40 out of 60<sup>1</sup> done) and the insights I gathered from them will be shared here soon.

Next week, I'll be posting a blog post regarding what I learned, and what we (the project essentially) can improve upon. 

<sup>1</sup>NSF updated the program timeline (initially it was from Jan to March) to instead be 4 weeks, and correspondingly the interview count from 100 to 60.

**Comment by Anirban166** [comment]
Quick update: 
The interviews are going well (40+ out of 60<sup>1 </sup>done) and the insights I gathered from them will be shared soon - Next week (after the interviews have concluded) I'll be sending a PR to [The Raft](https://github.com/rdatatable-community/The-Raft/) for a blog post regarding what I learned and what we (the project and the community essentially) can improve upon.

<sup>1</sup>NSF updated the program timeline (initially it was from January to March) to instead be 4 weeks, and the interview count from 100 to 60.

**Comment by tdhock** [comment]
summary here https://github.com/rdatatable-community/The-Raft/pull/21
