### ISSUE TITLE
[R-Forge #2550] Document that <<- copies

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#589]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2550&group_id=240&atid=978)

Inside functions :

   assign("globDT", DT, .GlobalEnv)

doesn't copy but :

   globDT <<- DT

does. Maybe a new FAQ for this or on wiki.

**Comment by MichaelChirico** [comment]
This doesn't appear to be true anymore?

```
foo = function(x) {
  DT = data.table(x, 1:10)
  print(address(DT))
  assign('globDT', DT, envir = .GlobalEnv)
}

foo(4)
# [1] "0x121704000"
print(address(globDT))
# [1] "0x121704000"

bar = function(x) {
  DT = data.table(x, 1:10)
  print(address(DT))
  globDT <<- DT
}

bar(10)
# [1] "0x118892000"
print(address(globDT))
# [1] "0x118892000"
```

Shall we close?
