### ISSUE TITLE
Clear error message when attempting to read non-excel file

### ISSUE THREAD

**Issue by john-ioannides** [Rdatatable/data.table#5917]
As I understand that this package is an improvement of the openxlsx package, I've recently switched one of my codes from the old one to this one,

When attempting to read non-excel files, `openxlsx::read.xlsx()` gave this clear error: 
```
Error: openxlsx can only read .xlsx or .xlsm files
```

On the contrary, with the same input, `openxlsx2::read_xlsx()` gives this rather misleading error: 
```
Error in basename(sheets$Target) : object 'sheets' not found
In addition: Warning message:
In unzip(file, exdir = xmlDir) : error 1 in extracting from zip file
```

I think a clearer error message would be more suitable.

**Comment by ben-schwen** [comment]
You are at the wrong repository. I think you are looking for [openxlsx2](https://github.com/JanMarvin/openxlsx2)

**Comment by john-ioannides** [comment]
You're completely right! Really sorry about that!
