### ISSUE TITLE
Error: package or namespace load failed for ‘data.table’

### ISSUE THREAD

**Issue by APLevine** [Rdatatable/data.table#5919]
I am getting the below error message. I have seen a previous post about this (https://github.com/Rdatatable/data.table/issues/4175). I do not have administrative rights on the computer. Is there another workaround I can try? Thank you.

```
> library(data.table)
Error: package or namespace load failed for ‘data.table’:
 .onLoad failed in loadNamespace() for 'data.table', details:
  call: NULL
  error: invalid version specification ‘before 1.12.0’
In addition: Warning message:
package ‘data.table’ was built under R version 4.1.3 
```
```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2
```

**Comment by MichaelChirico** [comment]
What is `read.dcf(system.file("DESCRIPTION", package="data.table"), "Version")`?

Note that that error is coming from base R:

https://github.com/r-devel/r-svn/blob/5c231d70b011167ae1b2d50b707d30b5e29f76b8/src/library/base/R/version.R#L73

**Comment by MichaelChirico** [comment]
You're meant to be seeing this error:

https://github.com/Rdatatable/data.table/blob/cde7333938a590a3cddbda1b02103650e2f55d15/R/onLoad.R#L25-L26

If the steps described there don't help, I'm not sure what else to do.
