### ISSUE TITLE
lgb.importance(): Error: R character strings are limited to 2^31-1 bytes

### ISSUE THREAD

**Issue by Chuang1128** [Rdatatable/data.table#5922]
Hello!

when I run this code lgb.importance(), it will show the Error: R character strings are limited to 2^31-1 bytes.

how do I solve this error? Thank you!

**Comment by MichaelChirico** [comment]
lgb.importance() is not a data.table function, and indeed single strings in R character vectors have this limit.

**Comment by MichaelChirico** [comment]
please check on the lightgbm issue tracker

**Comment by Chuang1128** [comment]
What is the lightgbm issue tracker？
I've used the same code before and it worked fine

**Comment by tdeenes** [comment]
As Michael already informed you:

- your issue has nothing to do with the data.table package, and this is an issue tracker for the data.table package (totally unrelated to lightgbm);
- therefore, go to the GitHub issue tracker of the lightgbm package: https://github.com/microsoft/LightGBM/issues
- Michael also confirmed to you what the Error already told you: "R character strings are limited to 2^31-1 bytes."

It is highly likely that you train your lightgbm model an a new data set which has some issues that you will have to debug and probably resolve on your own.

**Comment by Chuang1128** [comment]
ok! thank you
