### ISSUE TITLE
Please roll the main branch to 1.5.99

### ISSUE THREAD

**Issue by eddelbuettel** [Rdatatable/data.table#5924]
Congratulations on getting 1.5.0 shipped to CRAN!  A true milestone.

So now that version is ahead of `master` and eg as a consequence the convenience wrapper `DT` is hiding.  I could re-enable (and another micro-issue is that I didn't immediately find the options ...) or I could just rebuild from source -- but for that source needs to be ahead of release.

```r
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 23.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.11.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Chicago
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.15.0

loaded via a namespace (and not attached):
[1] compiler_4.3.2   parallel_4.3.2   colorout_1.3-0.1 fortunes_1.5-4  
> 
```

**Comment by ben-schwen** [comment]
We have already set up the new dev [branch](https://github.com/Rdatatable/data.table/tree/1-15-99).

AFAIK the only thing left before switching master to the new branch is to tag `1.15.0` accordingly.

**Comment by eddelbuettel** [comment]
Ahhhh. Because I had a fork and the real upstream as `parentrepo` I was only following `master` there. Corrected, and installed from 1-15-99.  (That left the branch in 'detached HEAD' which I don't like so I didn't 'remain' in the branch. I trust 'master' will get update soon.)  Thanks for the hint!

**Comment by TysonStanley** [comment]
Will be tagging the release today.
