### ISSUE TITLE
Incorrect URLs accross the data.table repo

### ISSUE THREAD

**Issue by KyleHaynes** [Rdatatable/data.table#5926]
There are a few incorrect URLs referenced in the data.table repository.

Below is not an exhaustive list that I've found. 

Happy to continue looking if there is interest.

Location | Reference | Incorrect URL | Correct URL???
-- | -- | -- | --
https://github.com/Rdatatable/data.table/wiki/Installation | see [OpenMP below](#openmp-enabled-compiler-for-mac) | [OpenMP below](#openmp-enabled-compiler-for-mac) | [OpenMP below](#enable-openmp-for-macos)
https://github.com/Rdatatable/data.table/wiki/Getting-started | https://github.com/Rdatatable/data.table/wiki/Getting-started#user-reviews | http://crantastic.org/packages/data-table | crantastic no longer exists?
https://github.com/Rdatatable/data.table/wiki/Getting-started | Learn   by doing     data.table course on DataCamp | https://www.datacamp.com/courses/data-analysis-the-data-table-way?referrer=GitHubWiki | No longer on datacamp?
https://github.com/Rdatatable/data.table/wiki/Support | 14. Take the Datacamp course | https://www.datacamp.com/courses/data-analysis-the-data-table-way | No longer on datacamp?
Wiki [right[ Sidebar | data.table URL to rdoc | https://www.rdocumentation.org/packages/data.table/versions/1.15.0/topics/data.table | https://www.rdocumentation.org/packages/data.table
https://github.com/Rdatatable/data.table/blob/master/R/IDateTime.R | https://github.com/Rdatatable/data.table/blob/6f43a96ad478e02a48f61939e0c0d3047e949353/R/IDateTime.R#L317 | http://gist.github.com/10238 | https://gist.github.com/hadley/10238

**Comment by tdhock** [comment]
for the wiki, can you please edit/correct? anybody should be able to I think.
For the IDateTime.R, can you please submit a PR?

**Comment by TysonStanley** [comment]
Hi @KyleHaynes has this been completed? Didn't see an open PR about the link on IDateTime.R so wanted to see.

**Comment by KyleHaynes** [comment]
@TysonStanley, Sorry for the delay. See https://github.com/Rdatatable/data.table/pull/6226

**Comment by TysonStanley** [comment]
No problem, thanks!

**Comment by ben-schwen** [comment]
I've found the course, but AFAICT its only visible to registered users [data-table-data-manipulation-r-tutorial-archived](https://app.datacamp.com/learn/courses/data-table-data-manipulation-r-tutorial-archived)

**Comment by MichaelChirico** [comment]
Is this ready to be closed?
