### ISSUE TITLE
web (https://rdatatable.gitlab.io/data.table/) and github News page not updated

### ISSUE THREAD

**Issue by phisanti** [Rdatatable/data.table#5927]
Currently, the https://rdatatable.gitlab.io/data.table/ web and the NEWs shows 1.14.99 as latest version while CRAN shows 1.15.0. Thus, it needs to be updated.

**Comment by AngelFelizR** [comment]
You're right. The team is working on that in the issue #5724

**Comment by ben-schwen** [comment]
Duplicate to #5924 so closing this one
