### ISSUE TITLE
Feedback about new wiki pages with roles

### ISSUE THREAD

**Issue by Anirban166** [Rdatatable/data.table#5928]
@MichaelChirico Can you please proofread the wiki page I created to document the [Translation](https://github.com/Rdatatable/data.table/wiki/Translations) aspects of data.table and your role?

@jangorecki Can you please proofread the wiki page I created to document the [Triage Management](https://github.com/Rdatatable/data.table/wiki/Triage-Management) aspects of data.table and your role?

If the wiki pages are not an accurate reflection of what you guys are working on, can you please edit or mention what changes are required?

**Comment by Anirban166** [comment]
Note: I created these as per former discussion with @tdhock as he mentioned the creation of such new roles (for e.g., [Performance Testing](https://github.com/Rdatatable/data.table/wiki/Performance-testing) would apply to him) in the agenda going forward.

**Comment by jangorecki** [comment]
Unfortunately not anytime soon

**Comment by Anirban166** [comment]
> Unfortunately not anytime soon

No worries, at your convenience!

**Comment by MichaelChirico** [comment]
Thanks Ani. Would you like me to just edit the Wiki, or give feedback in this issue?

**Comment by Anirban166** [comment]
> Thanks Ani. Would you like me to just edit the Wiki, or give feedback in this issue?

Either way works!

**Comment by MichaelChirico** [comment]
I made some edits, PTAL.

**Comment by tdhock** [comment]
i made some Teams for easy `@mentioning` of people with these roles

**Comment by Anirban166** [comment]
Looks 👌🏻  to me, and I edited it a bit as a square up. Up to you guys to make further edits and decide what to put there in the long run, but I think the translation part is good to go for the first draft. (I'll wait for @jangorecki to review the Triage Management wiki to close this)

**Comment by jangorecki** [comment]
I looked at the doc at it feels very good to me. I don't really have idea how such doc should look like but I don't thinkI would add anything more at the moment.

**Comment by Anirban166** [comment]
Thanks Jan! 
Noted, but please feel free to add or edit whenever needed as things change.
