### ISSUE TITLE
[R-Forge #2489] edit() retaining class of data.table would be nice

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#593]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2489&group_id=240&atid=978)

Currently edit() changes the data.table to data.frame.

**Comment by MichaelChirico** [comment]
Seems solving this would require doing something in C:

```
getAnywhere("edit.default")
A single object matching ‘edit.default’ was found
It was found in the following places
  registered S3 method for edit from namespace utils
  namespace:utils
with value

function (name = NULL, file = "", title = NULL, editor = getOption("editor"), 
    ...) 
{
    if (is.null(title)) 
        title <- deparse(substitute(name))
    if (is.function(editor)) 
        invisible(editor(name = name, file = file, title = title))
    else .External2(C_edit, name, file, title, editor)
}
<bytecode: 0x4cf9e70>
<environment: namespace:utils>
```

I tried doing some stuff with adding `edit.data.table`, running it through `edit.default`, and `setDT`ing the output but that was getting me nowhere.

Perhaps up to r-devel to fix this?
