### ISSUE TITLE
Disagreement between CRAN version and GitHub version

### ISSUE THREAD

**Issue by iago-pssjd** [Rdatatable/data.table#5931]
In CRAN version (https://cran.r-project.org/web/packages/data.table/news/news.html), NEWS appear rightly documented as for version 1.15.0:
# data.table [v1.15.0](https://github.com/Rdatatable/data.table/milestone/29) (14 Jan 2024)

However, in GitHub released version (https://github.com/Rdatatable/data.table/tree/27b0b227384f52c7d035828086e71c41d864558c) NEWS file (https://github.com/Rdatatable/data.table/blob/27b0b227384f52c7d035828086e71c41d864558c/NEWS.md) has as header yet version 1.14.99

# data.table [v1.14.99](https://github.com/Rdatatable/data.table/milestone/29) (in development).

Am I looking at the right place?

Thanks!

**Comment by AngelFelizR** [comment]
Hello @iago-pssjd, The issue have also been reported in issue #5924.

**Comment by iago-pssjd** [comment]
Thanks @AngelFelizR . Actually I think this issue follows to that, as there it is claimed the tagging of the release a couple of days ago (https://github.com/Rdatatable/data.table/issues/5924#issuecomment-1917070336), which is the branch I linked ([release_changes_1.15](https://github.com/Rdatatable/data.table/tree/release_changes_1.15)), beyond that there a distinct branch is referred: [1-15-99](https://github.com/Rdatatable/data.table/tree/1-15-99)
