### ISSUE TITLE
data.table 1.15.0 two failing tests on CRAN

### ISSUE THREAD

**Issue by TysonStanley** [Rdatatable/data.table#5935]
CRAN contacted me today with what looks like two failing tests. 

> Dear maintainer,
> 
> Please see the problems shown on <https://cran.r-project.org/web/checks/check_results_data.table.html>.
> Please correct before 2024-02-27 to safely retain your package on CRAN.
>
> Note that this will be the *final* reminder.
>
> The CRAN Team

**Comment by TysonStanley** [comment]
These look like ones that normally fix themselves with a re-run of the build but could be wrong.

**Comment by tdhock** [comment]
I think he means the M1mac issue,
```
* checking whether package ‘data.table’ can be installed ... [11s/12s] WARNING
Found the following significant warnings:
  fwriteR.c:267:108: warning: format specifies type 'long long' but the argument has type 'R_xlen_t' (aka 'long') [-Wformat]
See ‘/Users/ripley/R/packages/tests-devel/data.table.Rcheck/00install.out’ for details.
```

**Comment by TysonStanley** [comment]
Do we have a branch we are using to create the patch 1.15.2?

**Comment by jangorecki** [comment]
Not yet. Create it branching from 1.15.0 branch.

**Comment by MichaelChirico** [comment]
https://github.com/Rdatatable/data.table/tree/patch-1.15.2

**Comment by TysonStanley** [comment]
1.15.2 has been submitted to CRAN. Will update once I hear back from them.

**Comment by MichaelChirico** [comment]
I see it's been accepted. Thanks @TysonStanley! What do we need to do now on `master`? Just add the exact dates & NEWS items?

**Comment by TysonStanley** [comment]
Yes, will push the tag later today. Did we already move those fixes to master? If not, those should be merged.

**Comment by MichaelChirico** [comment]
> Yes, will push the tag later today. Did we already move those fixes to master? If not, those should be merged.

yes they're included already:

e24a66aa26dbeb3f78394966c8732849dac73829

74db86077d6ffebff795b31ec54d24e2b462eb5e

**Comment by TysonStanley** [comment]
The release is tagged so 1.15.2 is complete. Will be watching the tests this week to see if anything new pops up
