### ISSUE TITLE
dot function not found in function calls on RHS of := in J

### ISSUE THREAD

**Issue by agilly** [Rdatatable/data.table#5949]
Hi!

I am not sure if this is a bug, but I have encountered the following behavior. It seems unintentional, especially since `.()`doesn't seem to be banned from the RHS of `:=` in general, as e.g. `dt[,col2:=.(col1)]` works.

## MRE
```R
# Load the data.table package
library(data.table)

# Create a data.table
dt <- data.table(Col1 = c(25, 30, 35, 40), Col2 = c(20, 25, 30, 35), Col3 = c(170, 175, 180, 185), x = rnorm(4))

# Define the formula
frml <- "genericFunction(x, genericArg=.(Col1,Col1^2))"

# Define a dummy generic function
genericFunction <- function(x, genericArg) {
  print(head(genericArg))
  return(x - mean(x))
}

# This works
print(dt[, eval(parse(text=frml))])

# This does not work and throws an error : could not find function "."
dt[, newcol := eval(parse(text=frml))]

# Also no luck
dt[, newcol := eval(parse(text=frml), envir=.SD)]

```

## Output of sessionInfo()
```
r$> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C        
[11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.15.0 colorout_1.3-0   

loaded via a namespace (and not attached):
[1] compiler_4.3.1 tools_4.3.1 
```

If it is intentional this way, or at least expected, are there any `envir=` values that will make the `eval()` work?

**Comment by MichaelChirico** [comment]
avoid eval(parse()) at all costs. the simplest workaround (minimal refactoring) is to write list(...) instead of .(...).

but I strongly recommend investing in a better programming approach, in particular the new env= argument, see the programming vignette:

https://rdatatable.gitlab.io/data.table/articles/datatable-programming.html

closing as this is WAI.

**Comment by agilly** [comment]
Thanks, I use `eval(parse())` for its versatility, but am open to try new approaches if they are more robust. Is there a concise example of how I could replace my `dt[, newcol:=eval(parse(text=frml))]` to use the new `env` arg?

The only other thing I can think of is to do `.=function(...) list(...)` locally in the function where this is called, which works but is pretty brutal.
