### ISSUE TITLE
[R-Forge #2480] New maintain.key argument

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#595]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2480&group_id=240&atid=978)

As raised here :

http://stackoverflow.com/a/14366007/403310

It would do an extra test to see if the new values would change the sort order. If not, it's an easy update without dropping the key (but user has explicitly asked to maintain the key so that's not the old different-type-depending-on-data issue).  If it would change the sort order, it only needs to binary search the new values,  and then move the rows around  (much faster than a full table resort).

Not a bad idea!

Also a datatable.maintain.key global option, by default FALSE.

Perhaps name should be  update.maintains.sort.order   or something clear. To convey why the default is FALSE.   "maintain.key" sounds like it should be TRUE.

**Comment by MichaelChirico** [comment]
I would put this in the category of "maybe nice to have, but not at the cost of extra `[.data.table` argument clutter" at this point, as the importance of keys in `data.table` has waned substantially in these years. Easy enough to just `setkey` if needed, and more explicit.

If anything, I would add some note to `verbose` output saying that the key was dropped:

```
DT = data.table(
  x = c("a", "a", "a", "c", "c", "c", "z", "z", "z"), 
  y = c(1, 3, 6, 1, 3, 6, 1, 3, 6), 
  v = c(13, 13, 13, 7, 8, 9, 42, 42, 42), 
  v2 = c(84, 84, 84, NA, NA, NA, NA, NA, NA), 
  m = c(5, 5, 5, 8, 8, 8, 42, 42, 42)
)
setkey(DT, x)
DT[J("a"), x := "z", verbose = TRUE]
# Starting bmerge ...done in 0.000sec 
# Detected that j uses these columns: x 
# Assigning to 3 row subset of 9 rows
```

Anyone still think it's worth to add?

**Comment by MichaelChirico** [comment]
> Anyone still think it's worth to add?

Taking as a no :)
