### ISSUE TITLE
1.15.4 release

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#5971]
1.15.2 release is now on CRAN, but we didn't get a fix for #5962 included in time. We should aim to release another patch with this regression fix in maybe another month or so, including any further issues that arise in the meantime.

Filing this issue as an earmark to that end.

The patch release branch is https://github.com/Rdatatable/data.table/tree/patch-1.15.4

**Comment by TysonStanley** [comment]
Works for me.

**Comment by MichaelChirico** [comment]
I think this patch is urgent enough to start getting a release ready next week if you'll have the time @TysonStanley -- the "`shift` in subsets issue" is bad for those affected by it, e.g. https://stackoverflow.com/a/78149204/3576984. Nothing else came up from the CRAN checks so I think the patch is as ready as it will be, anyway.

**Comment by TysonStanley** [comment]
@MichaelChirico Will plan on it!

**Comment by MichaelChirico** [comment]
We're also erroring on CRAN as of about 12 hours ago as the language comparison change is now in R-devel:

https://github.com/r-devel/r-svn/commit/f111326ae1a1200b76e4c74f280fac2673117b6f

https://cran.r-project.org/web/checks/check_results_data.table.html

**Comment by TysonStanley** [comment]
CRAN response

>  Found the following (possibly) invalid URLs: URL: https://csvy.org/ From: man/fread.Rd

I just tried the site and it looks dead at the moment.

**Comment by TysonStanley** [comment]
I haven't been able to find its new home (if there is one). Do we have a recommended approach for dead links like this one?

**Comment by TysonStanley** [comment]
Short-term fix to remove the issue with the dead link in d88fd42 to get patch fixed for CRAN

**Comment by MichaelChirico** [comment]
> I haven't been able to find its new home (if there is one). Do we have a recommended approach for dead links like this one?

checking with the csvy GitHub owner:

https://fosstodon.org/@michaelchirico/112131985274138229

we could also link the associated GitHub repo.

as for general approach, I'd say (1) try and find the same page relocated (2) try and find an equivalent page (3) delete it, possibly temporarily with a TODO if we've reason to expect the page to resurrect later.

**Comment by TysonStanley** [comment]
Thanks, appreciate the feedback. And thanks for reaching out to the owner. I can wait a day or two to see if we get an answer (our patch isn't due until April 1).

**Comment by TysonStanley** [comment]
@MichaelChirico any word on csvy?

**Comment by MichaelChirico** [comment]
> @MichaelChirico any word on csvy?

no, let's just link the GitHub instead

**Comment by TysonStanley** [comment]
IS this the best one? Can't find anything better (other than R/python packages for working with csvy): https://github.com/csvy

**Comment by TysonStanley** [comment]
I'm seeing a new error that I was hoping was a false positive in my checks. I'm away from the computer and haven't looked at this close but it seems to be a consistent issue on Windows for R-Devel. 

```
checking tests ... [10m] ERROR
  Running 'autoprint.R'
  Comparing 'autoprint.Rout' to 'autoprint.Rout.save' ... OK
  Running 'froll.R' [70s]
  Running 'knitr.R'
  Comparing 'knitr.Rout' to 'knitr.Rout.save' ... OK
  Running 'main.R' [416s]
  Running 'nafill.R'
  Running 'other.R' [63s]
  Running 'programming.R' [58s]
  Running 'types.R'
Running the tests in 'tests/froll.R' failed.
Complete output:
  > require(data.table)
  Loading required package: data.table
  > test.data.table(script="froll.Rraw")
  getDTthreads(verbose=TRUE):
    OpenMP version (_OPENMP)       201511
    omp_get_num_procs()            48
    R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
    R_DATATABLE_NUM_THREADS        unset
    R_DATATABLE_THROTTLE           unset (default 1024)
    omp_get_thread_limit()         2
    omp_get_max_threads()          48
    OMP_THREAD_LIMIT               2
    OMP_NUM_THREADS                unset
    RestoreAfterFork               true
    data.table is using 2 threads with throttle==1024. See ?setDTthreads.
  test.data.table() running: D:/RCompile/CRANincoming/R-devel/lib/data.table/tests/froll.Rraw.bz2
  
  Sun Mar 24 22:47:29 2024  endian==little, sizeof(long double)==16, longdouble.digits==64, sizeof(pointer)==8, TZ==unset, Sys.timezone()=='Europe/Berlin', Sys.getlocale()=='LC_COLLATE=C;LC_CTYPE=German_Germany.utf8;LC_MONETARY=C;LC_NUMERIC=C;LC_TIME=C', l10n_info()=='MBCS=TRUE; UTF-8=TRUE; Latin-1=FALSE; codepage=65001; system.codepage=65001', getDTthreads()=='OpenMP version (_OPENMP)==201511; omp_get_num_procs()==48; R_DATATABLE_NUM_PROCS_PERCENT==unset (default 50); R_DATATABLE_NUM_THREADS==unset; R_DATATABLE_THROTTLE==unset (default 1024); omp_get_thread_limit()==2; omp_get_max_threads()==48; OMP_THREAD_LIMIT==2; OMP_NUM_THREADS==unset; RestoreAfterFork==true; data.table is using 2 threads with throttle==1024. See ?setDTthreads.', zlibVersion()==1.3.1 ZLIB_VERSION==1.3.1
  10 longest running tests took 10s (99% of 10s)
       ID time nTest
  1: 6002 8.75   576
  2: 6003 1.39   256
  3: 6001 0.42    64
  4: 6000 0.12   224
  5: 6010 0.00    47
  All 1167 tests (last 6010.606) in tests/froll.Rraw.bz2 completed ok in 11.1s elapsed (10.5s cpu)
  > 
  > proc.time()
     user  system elapsed 
    10.70    0.62   11.31 
Running the tests in 'tests/other.R' failed.
Complete output:
  > require(data.table)
  Loading required package: data.table
  > if (as.logical(Sys.getenv("TEST_DATA_TABLE_WITH_OTHER_PACKAGES","FALSE"))) {
  + 
  +   options(warn=1)
  +   # test.data.table() turns on R's warnPartial* options and currently there
  +   # are partial argument names used in base and other packages. Without the
  +   # options(warn=1), other.Rout just contains "There were 16 warnings (use
  +   # warnings() to see them)". However, a print(warnings()) after test.data.table()
  +   # just results in NULL in other.Rout. Hence options(warn=1) because that
  +   # worked to display the warnings, not because we want them displayed at the
  +   # time per se.
  +     
  +   test.data.table(script="other.Rraw")
  + }
  > 
  > 
  > proc.time()
     user  system elapsed 
     0.18    0.03    0.20 
Running the tests in 'tests/programming.R' failed.
Complete output:
  > require(data.table)
  Loading required package: data.table
  > test.data.table(script="programming.Rraw")
  getDTthreads(verbose=TRUE):
    OpenMP version (_OPENMP)       201511
    omp_get_num_procs()            48
    R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
    R_DATATABLE_NUM_THREADS        unset
    R_DATATABLE_THROTTLE           unset (default 1024)
    omp_get_thread_limit()         2
    omp_get_max_threads()          48
    OMP_THREAD_LIMIT               2
    OMP_NUM_THREADS                unset
    RestoreAfterFork               true
    data.table is using 2 threads with throttle==1024. See ?setDTthreads.
  test.data.table() running: D:/RCompile/CRANincoming/R-devel/lib/data.table/tests/programming.Rraw.bz2
  
  Sun Mar 24 22:56:28 2024  endian==little, sizeof(long double)==16, longdouble.digits==64, sizeof(pointer)==8, TZ==unset, Sys.timezone()=='Europe/Berlin', Sys.getlocale()=='LC_COLLATE=C;LC_CTYPE=German_Germany.utf8;LC_MONETARY=C;LC_NUMERIC=C;LC_TIME=C', l10n_info()=='MBCS=TRUE; UTF-8=TRUE; Latin-1=FALSE; codepage=65001; system.codepage=65001', getDTthreads()=='OpenMP version (_OPENMP)==201511; omp_get_num_procs()==48; R_DATATABLE_NUM_PROCS_PERCENT==unset (default 50); R_DATATABLE_NUM_THREADS==unset; R_DATATABLE_THROTTLE==unset (default 1024); omp_get_thread_limit()==2; omp_get_max_threads()==48; OMP_THREAD_LIMIT==2; OMP_NUM_THREADS==unset; RestoreAfterFork==true; data.table is using 2 threads with throttle==1024. See ?setDTthreads.', zlibVersion()==1.3.1 ZLIB_VERSION==1.3.1
  10 longest running tests took 0s (100% of 0s)
       ID time nTest
   1:  11 0.15    52
   2: 102 0.03     6
   3:   1 0.03    17
   4:  12 0.03    25
   5: 201 0.02     3
   6:   2 0.02    45
   7:   4 0.01    15
   8: 103 0.01     2
   9:   3 0.00     2
  10:   5 0.00    11
  All 218 tests (last 202.3) in tests/programming.Rraw.bz2 completed ok in 0.360s elapsed (0.340s cpu)
  > 
  > proc.time()
     user  system elapsed 
     0.51    0.06    0.56 
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking re-building of vignette outputs ... [20s] OK
* checking PDF version of manual ... [17s] OK
* checking HTML version of manual ... [13s] OK
* DONE
Status: 1 ERROR, 1 NOTE
```

Other than the date in the NEWS and the compression of the large files, everything is the same on `patch_1.15.4` branch. 

I can look into this tonight if no one knows the reason for this.

**Comment by MichaelChirico** [comment]
With #6021 and #6022, we get more output, but I still don't see why it's throwing an error:

https://github.com/Rdatatable/data.table/actions/runs/8415023077/job/23039571689?pr=6022

**Comment by TysonStanley** [comment]
Thanks. It didn't throw an error just a few days ago other than the url and I made no other adjustments. Could be a false positive or something. Error didn't show up on Mac or Linux R-Devel. 

Should I grab those changes and test it on win-builder to see the full output?

**Comment by TysonStanley** [comment]
Oh I see your link to our CI. Sorry, missed that.

**Comment by MichaelChirico** [comment]
I do see some mention of Windows on recent r-devel history, possibly it's an upstream issue? Though I don't really see evidence of other packages affected

**Comment by TysonStanley** [comment]
Yeah, the errors are in strange places. We have a week until it's due so we have time to wait to see if it shows up as an upstream issue

**Comment by eddelbuettel** [comment]
FYI windows r-devel was them, and is fixed now.

**Comment by TysonStanley** [comment]
Thanks, in their response Uwe mentioned on our submission

> Thanks, we see you write

>> \code{setDTthreads(0)} is the same as
>> \code{setDTthreads(percent=100)}; i.e. use all logical CPUs, subject
>> to \code{Sys.getenv("OMP_THREAD_LIMIT")}. Please note again that
>> CRAN's daily test system sets \code{OMP_THREAD_LIMIT} to 2, so
>> developers of CRAN packages should never change
>> \code{OMP_THREAD_LIMIT} inside their package to a value greater than
>> 2.

> But that's simply wrong ... at least neither Kurt nor I ever used 2. data.table should not use more than 2 by default unless the user 
requests more than 2. This is a ganeral matter and shoudl not only apply for CRAN: I have been 
repeatedly bitten by this myself on clusters where packages grap more 
cores than the allocated amount without knowing they may use any 
parallel techniques.

**Comment by TysonStanley** [comment]
@MichaelChirico @jangorecki Do we have a preference for how to deal with Uwe's comment here? Can do a small adjustment for the 1.15.4 branch that changes the wording there in the docs.

**Comment by MichaelChirico** [comment]
Sorry, didn't realize there's an ask here. AIUI the dispute is the claim about how CRAN is enforcing threads<=2, we made an assumption (?) about how it's done but that part doesn't really matter, what matters is "watch out for threads>2 on CRAN". How about

```diff
-  \code{setDTthreads(0)} is the same as \code{setDTthreads(percent=100)}; i.e. use all logical CPUs, subject to \code{Sys.getenv("OMP_THREAD_LIMIT")}. Please note again that CRAN's daily test system sets \code{OMP_THREAD_LIMIT} to 2, so developers of CRAN packages should never change \code{OMP_THREAD_LIMIT} inside their package to a value greater than 2.
+  \code{setDTthreads(0)} is the same as \code{setDTthreads(percent=100)}; i.e. use all logical CPUs, subject to \code{Sys.getenv("OMP_THREAD_LIMIT")}. Please note again that developers of CRAN packages should never change \code{OMP_THREAD_LIMIT} inside their package to a value greater than 2 as CRAN very strictly enforces limits on automated parallelism in packages.
```

**Comment by TysonStanley** [comment]
That may work, hard to tell if they'll push back at all, but if they do it's easy enough to edit again. Will make this change and submit to CRAN tonight

**Comment by TysonStanley** [comment]
Another pushback on the patch, this time on the time it's currently taking to run the tests. We are seeing 30 minutes for their servers for at least Windows for R-devel. I haven't looked deeper yet but in my docker tests for Linux and on my MacOS the testing for R-devel has been much faster.

**Comment by eddelbuettel** [comment]
Windows is know slow esp with file access.  I am for no more than 5 mins. From a glance at

![image](https://github.com/Rdatatable/data.table/assets/673121/6dfdbfe4-7867-4d12-b0d2-afed925409ee)

you guys seem in the ball park ... apart on r-devel for whatever reason, likely theirs.  But reducing the tests for CRAN (while keeping a full batch for CI and local dev etc) may be something to consider.

**Comment by MichaelChirico** [comment]
It's kind of crazy to have such a wide variance among the three Windows checks. Here's the setup of those three machines:

<table border="1">
<tr> <th> Flavor </th> <th> CPU&nbsp;Info </th> <th> Compilers </th> </tr>
<tr> <td> r-devel-windows-x86_64 </td> <td> 2x AMD EPYC 7443 (24 cores) @ 2.85GHz </td> <td> GCC 13.2.0 (built by MXE, MinGW-W64 project) </td> </tr>
<tr> <td> r-release-windows-x86_64 </td> <td> 2x Intel Xeon E5-2680 v4 (14 core) @ 2.4GHz </td> <td> GCC 12.3.0 (built by MXE, MinGW-W64 project) </td> </tr>
<tr> <td> r-oldrel-windows-x86_64 </td> <td> 2x Intel Xeon E5-2680 v4 (14 core) @ 2.4GHz </td> <td> GCC 10.4.0 (built by MXE, MinGW-W64 project) </td> </tr>
</table>

_(irrelevant columns removed)_

So it's either (1) noise (2) AMD or (3) GCC version.

Are they able to share any more details? e.g. the corresponding Rcheck output at least, we should have more specific timing info in there.

**Comment by TysonStanley** [comment]
Uwe just contacted me with two notes:

* for each resubmission we are supposed to increase the version number (he had issues seeing previous submissions with the same version number)
* he's starting the revdep check so I don't think he'll stop based on testing time. Think this is still worth figuring out but doesn't seem like it will stop us for this version.

**Comment by jangorecki** [comment]
Looks like r-devel win configuration issue. Maybe GC step is enabled there. Or a machine runs many jobs in parallel and they fight for resources.

**Comment by TysonStanley** [comment]
"On its way to CRAN" 👍

Will finish this and tag it tonight.

**Comment by TysonStanley** [comment]
Uwe does want a separate version number for each resubmission though. Given our new versioning process, seems like we could do subsequent numbers (eg this one could have been 1.15.5). Thoughts? If we want to change will make issue/PR for it.

**Comment by eddelbuettel** [comment]
My bot says you're done so congratulations!

![image](https://github.com/Rdatatable/data.table/assets/673121/913b435c-ce54-45da-a740-7188219dfdd1)
