### ISSUE TITLE
Make blog accessible via RSS feed

### ISSUE THREAD

**Issue by luca-scr** [Rdatatable/data.table#5972]
It would be great if the blog at https://rdatatable-community.github.io/The-Raft/ could be made accessible via RSS feed.

**Comment by ben-schwen** [comment]
There is already an issue at the [repo](https://github.com/rdatatable-community/The-Raft/issues/5). Closing here but mentioning @tdhock about merging or at least linking organizations

**Comment by tdhock** [comment]
@luca-scr if you know how to set that up, can you please send The raft a PR?
