### ISSUE TITLE
dt_fill raises recycle error all of a sudden

### ISSUE THREAD

**Issue by gernophil** [Rdatatable/data.table#5975]
I have data wrangling script, where I just want to fill all `NA`s with the value above it. I used to do it this way:
```
library(data.table)

col1 <- c("A", "B", "C", "D")
col2 <- c("X", NA, "Z", NA)

dt <- data.table(col1,
                 col2)

dt[, col2 := dt_fill(dt, col2, .direction = 'down')]
```
And this always worked, but now I get the error:
```
Error in `[.data.table`(dt, , `:=`(col2, dt_fill(dt, col2, .direction = "down"))) : 
  Supplied 2 items to be assigned to 4 items of column 'col2'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
```

EDIT: Sorry, I've just now seen this is not part of `data.table`, but `tidyfast`. But maybe anyone still knows the answer.

**Comment by gernophil** [comment]
See https://github.com/TysonStanley/tidyfast/issues/54

**Comment by MichaelChirico** [comment]
@gernophil thanks for the MRE. I get the same error with CRAN {tidyfast} and {data.table} versions 46ee52571214b135b645e367ebacd02de02aff52, `1.14.0`, and `1.13.4` (the minimum {data.table} version required by current {tidyfast}).

It will help to know what versions of {tidyfast}/{data.table} you ran where this code worked.

**Comment by gernophil** [comment]
@MichaelChirico: It does not seem to depend on the `data.table` version. I just installed the previous `tidyfast` version (`0.2.1`) and it worked again:
```
remove.packages("tidyfast")
remotes::install_version("tidyfast", "0.2.1")
```
