### ISSUE TITLE
Comparison operators will not work with language objects in R-devel

### ISSUE THREAD

**Issue by TysonStanley** [Rdatatable/data.table#5977]
Got a message today from Luke Tierney about this change in R-devel.

Comparison operators == and != can be used on language objects
(i.e. call objects and symbols). The == operator in particular often
seems to be used as a shorthand for calling identical(). The current
implementation involves comparing deparsed calls as strings. This has
a number of drawbacks and we would like to transition to a more robust
and efficient implementation. As a first step, R-devel will soon be
modified to signal an error when the ordered comparison operators <,
<=, >, >= are used on language objects. A small number of CRAN and
BIOC packages will fail after this change. If you want to check your
packages or code before the change is committed you can run the
current R-devel with the environment variable setting

`_R_COMPARE_LANG_OBJECTS=eqonly`

where using such a comparison now produces

```r
quote(x + y) > 1
Error in quote(x + y) > 1 :
  comparison (>) is not possible for language types
```

I haven't done a thorough review of where/if this occurs yet. Plant to do that this weekend unless someone beats me to it.

**Comment by jangorecki** [comment]
What are the other values a accepted in _R_COMPARE_LANG_OBJECTS ?
Sounds that we should add something like _R_COMPARE_LANG_OBJECTS=all to CI

**Comment by MichaelChirico** [comment]
Did the e-mail mention what the long-term state will be for comparison of language objects? I see ordered comparisons will be blocked, but are `==` and `!=` slated for blocking as well?

**Comment by MichaelChirico** [comment]
I used the GitHub Code space on `master` (which runs R-devel) to check if we'll be affected, which we will:

```
Running test id 580          Test 580 didn't produce the correct error:
Expected: simply wrap with which(), and take the which() outside the loop if possible for efficiency
Observed: comparison (<) is not possible for language types
```

**Comment by MichaelChirico** [comment]
> What are the other values a accepted in _R_COMPARE_LANG_OBJECTS ? Sounds that we should add something like _R_COMPARE_LANG_OBJECTS=all to CI

Seems they're enumerated here. I don't know the corresponding behaviors.

https://github.com/r-devel/r-svn/blob/31dc4569fe30653b20e8166576d967d486d41a73/src/main/relop.c#L117-L131

**Comment by MichaelChirico** [comment]
All of `_R_COMPARE_LANG_OBJECTS={identical,error_calls,error}` throw a ton of errors for us, since things like `quote(.) == "..."` are blocked, and we use that a lot.

I am not sure yet what the intended migration path is -- using `quote(.) == quote(.)` instead? Would be good to have some guidance here before proceeding with a big fix.
