### ISSUE TITLE
win-dev and win-rel CI jobs failed

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5979]
Root cause not identified but I wasn't looking into it, just noticed they failed. Maybe simply url upgrade to recent R? not sure.

We need additionaly to ensure that jobs are listed in https://rdatatable.gitlab.io/data.table/web/checks/check_results_data.table.html where currently those jobs are missing

**Comment by MichaelChirico** [comment]
It looks like Rtools is failing to download:

```
Start-Process : This command cannot be run due to the error: The file or directory is corrupted and unreadable.
At line:299 char:43
+ ... RTOOLS_BIN; Start-Process -FilePath ..\rtools.exe -ArgumentList "/VER ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

**Comment by jangorecki** [comment]
Thanks, the problem is resolved, yet I am not sure if we are future proof in terms of future failures to be displayed on CI summary page. I will create new issue for that.
