### ISSUE TITLE
[R-Forge #2433] rbindlist support for list of vectors

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#600]
Submitted by: Garrett See; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2433&group_id=240&atid=978)

Currently, the `l` argument to `rbindlist()` should be a list of `data.table`, `data.frame`, or `list` objects (according to the docs).  It would be nice if it could be a list of (non-list) vectors as well.

For example, given this list:

```R
l <- list(c("16:59:20", "100", "143.88"), c("16:59:05", "106", "143.90"), 
          c("16:58:49", "900", "143.92"), c("16:58:49", "100", "143.92"), 
          c("16:58:46", "100", "143.93"), c("16:58:46", "200", "143.93"))

do.call(rbind, l)
#     [,1]       [,2]  [,3]    
#[1,] "16:59:20" "100" "143.88"
#[2,] "16:59:05" "106" "143.90"
#[3,] "16:58:49" "900" "143.92"
#[4,] "16:58:49" "100" "143.92"
#[5,] "16:58:46" "100" "143.93"
#[6,] "16:58:46" "200" "143.93"
```

```R
rbindlist(l)
#Error in rbindlist(l) : 
#  Item 1 of list input is not a data.frame, data.table or list
rbindlist(lapply(l, list)) # try with `l` as a list of lists?
#Error in alloc.col(ans) : 
#  Internal error: length of names (0) is not length of dt (1)
```

**Comment by arunsrinivasan** [comment]
@gsee, just pushed `transpose()` - for a list - #1025 . With that you can do:

```R
setDT(transpose(l))[]
#          V1  V2     V3
# 1: 16:59:20 100 143.88
# 2: 16:59:05 106 143.90
# 3: 16:58:49 900 143.92
# 4: 16:58:49 100 143.92
# 5: 16:58:46 100 143.93
# 6: 16:58:46 200 143.93
```
Although vector names (if named) are ignored. Closing this as solving this issue. Please open another issue for specific improvements if you think of any.

**Comment by boseop** [comment]
hi my name is boseop
