### ISSUE TITLE
[R-Forge #2422] Handle columns with complex numbers

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#602]
Submitted by: Paul Metzner; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2422&group_id=240&atid=978)

Necessary to use data.table for signal processing, especially for the analysis of power spectra.

**Comment by MichaelChirico** [comment]
I suppose this issue is open because `complex` columns are not feature-complete?

E.g, 

```
set.seed(102439)
DT <- data.table(C = c(1+2i, 1+2i, 1-2i, 1-2i), N = runif(4))
DT[ , .N, by = C]
```

> Error in`` `[.data.table`(DT, , .N, by = C)``: 
  column or expression 1 of `by` or `keyby` is type `complex`. Do not quote column names. Usage: `DT[,sum(colC),by=list(colA,month(colB))]`

**Comment by jangorecki** [comment]
The last one `DT[ , base::sum(C), by = I]` looks like a bug. This `sapply(split(DT$C, DT$I), sum)` works.

**Comment by arunsrinivasan** [comment]
dup of #1444.
