### ISSUE TITLE
shift() could auto-name list inputs for give.names=TRUE

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6035]
Follow-up to #2932.

```r
DT = data.table(
  income = rnorm(10)**2,
  hours = rnorm(10)**2
)
names(DT[ , shift(.(income, hours), 0:2, give.names=TRUE)])
# [1] "V1_lag_0" "V1_lag_1" "V1_lag_2" "V2_lag_0" "V2_lag_1" "V2_lag_2"
names(DT[ , shift(.(income = income, hours = hours), 0:2, give.names=TRUE)])
# [1] "income_lag_0" "income_lag_1" "income_lag_2" "hours_lag_0"  "hours_lag_1" 
# [6] "hours_lag_2"
```

The latter looks like a more natural output from reading the code & should better match user intuition for `.(...)` auto-naming.

**Comment by joshhwuu** [comment]
Hi I'd like to work on this!

Just to confirm my understanding, we want to change it so:

```R
names(DT[ , shift(.(income, hours), 0:2, give.names=TRUE)])

# [1] "income_lag_0" "income_lag_1" "income_lag_2" "hours_lag_0"  "hours_lag_1" 
# [6] "hours_lag_2"
```

**Comment by MichaelChirico** [comment]
yes, output should be identical to the more verbose .(income=income, hours=hours)

**Comment by jangorecki** [comment]
I am a bit sceptical.
`list(income=income, hours=hours)` would be good because we can do those names without NSE. Dot alias could work because we can change it to list, and then shift does not need NSE. But unnamed list passed to shift is another thing. There was idea to auto name list in j, then it could possibly work, but that's the breaking change (change proposed here as well is breaking). Therefore I would prefer to focus more on design before we jump into implementation.

**Comment by MichaelChirico** [comment]
To clarify `.`->`list` is happening since it's inside `j`, outside `j` it'd have to be `shift(list(income, hours),...)`.

I think auto-naming `name` -> c(name = name)` is pretty light NSE, doesn't come with all the really tough parts of NSE like where to resolve symbols/conflicts/inheritance etc. Just simple symbol->string replacement.

> change proposed here as well is breaking

yes... mildly... I would want to see if anybody is impacted. I know we didn't have any breaking change warning when we added better auto-naming in `j`. As of now I don't see anyone using `shift(.(...))` with `give.names!=FALSE`, mostly when `give.names=TRUE` is supplied it's with `shift(.SD, ...)` which is already named:

https://github.com/search?q=lang%3AR+%2Fgive%5B.%5Dnames%5Cs*%3D%5Cs*%5B%5E+F%5D%2F+%2Fshift%5B%28%5D%5Cs*%5B.%5D%5B%28%5D%2F+-path%3A.Rd&type=code

https://github.com/search?q=lang%3AR+%2Fgive%5B.%5Dnames%5Cs*%3D%5Cs*%5B%5E+F%5D%2F+%2Fshift%5B%28%5D%5Cs*%2F+-path%3A.Rd&type=code

**Comment by joshhwuu** [comment]
I added the following line to `shift`:
```R
if (give.names && is.list(ans)) {
    if (is.null(names(x))) {
      xsub = substitute(x)
      if (is.atomic(x) && is.name(xsub)) nx = deparse(xsub, 500L)
      else if (is.call(xsub) && xsub[[1]] == as.name("list")) nx = all.vars(xsub) # new line
      else nx = paste0("V", if (is.atomic(x)) 1L else seq_along(x))
    }
...
```
Which checks if `xsub` is a call, and uses the arguments in the call as names for the columns. It passes existing and new tests, could this approach work? I'm not familiar with NSEs (or what they are, actually), so I can't really add anything of value to the previous discussion.

**Comment by MichaelChirico** [comment]
NSE is "non-standard evaluation", see for example [here](http://adv-r.had.co.nz/Computing-on-the-language.html).

> `nx = all.vars(xsub)`

That's not really gonna be the way to go, you're getting lucky in your tests :)

See here for how it's done for `j` inside `[`:

https://github.com/Rdatatable/data.table/blob/096b20f1f1b9788787a826ba3d32177ed9836352/R/data.table.R#L952-L977

We don't need to be as sophisticated for `shift()`, just `if (is.name(x)) name<-as.character(x)` would suffice.

**Comment by joshhwuu** [comment]
Thanks! I'll take a look and start a PR soon.

**Comment by joshhwuu** [comment]
So, I'm not sure if I'm following. Are you saying `if (is.name(x)) name<-as.character(x)` is enough to auto-name the columns based on the `.(income, hours)`? Or should I also keep my condition `if (is.call(xsub) && xsub[[1]] == as.name("list"))` as well but replace `all.vars(xsub)` with `as.character(x)` ? 

I'm under the impression that `(is.name(x)) = FALSE` in this case, and my tests didn't pass when I replaced my modified line with `if (is.name(x)) name<-as.character(x)`. Maybe I'm not putting it in the right place?

**Comment by jangorecki** [comment]
As said before, I am against NSE in shift, better to keep it only in [. That implies no `subsitute`.

**Comment by MichaelChirico** [comment]
OK, I think we should close this issue then if we're not willing to re-use the logic in `data.table()`, i.e. `name_dots()`.
