### ISSUE TITLE
Add a "How to convert your Depends dependency on data.table to Imports" section to datatable-importing vignette?

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6037]
#3076 was long ago but we keep seeing more and more packages with {data.table} in Depends :frowning_face:

I started filing some PRs helping authors change to Imports, but it's hardly scalable:

 - https://github.com/Brauckhoff/biopixR/pull/5
 - https://github.com/entjos/TreeMineR/pull/2
 - https://github.com/immunomind/immunarch/pull/404

Better might be a how-to guide in our docs somewhere. I'm only torn on whether this is better as an addition to the existing vignette, or a new Wiki page that can be more easily edited. Thoughts?

**Comment by Anirban166** [comment]
I think it would be valuable to have notes for that in both places. This fits in the subject matter of the importing vignette, and as you mentioned, a Wiki page would benefit from easy and instant updates by everyone (although I presume it may be less discoverable than a vignette).

**Comment by tdhock** [comment]
other packages are allowed to use Depends, if they want.
I don't think it is our respsonsibility to police Depends vs Imports usage. Do we gain something (less issues filed by users, etc?) by doing this policing?

**Comment by MichaelChirico** [comment]
#3076 cites the advantage to us being cleaning up this ugly code:

https://github.com/Rdatatable/data.table/blob/898dce33c4f115c10c02c6a2e56855bf74dfd441/R/cedta.R#L64

but more broadly speaking, as an important package in the R ecosystem we can play a role in spreading awareness of best practices.

AFAICT 'Depends' is a relic of >10 years ago when that was the only way to do dependencies, but R can't remove it for back-compatibility.

I can also say that R at Google had an infrastructure issue where all Imports were converted to Depends and it caused absolute havoc. It took years to fix. From the experience of working on that I came away detesting Depends.

Anyway, while it's not a great use of dev time to go around fixing 90 other packages, we _can_ offer a simple DIY guide like this and continued encouragement to drop Depends.
