### ISSUE TITLE
[R-Forge #2377] Change keyby to run j by group in sorted order, too, rather than key afterwards.

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#606]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2377&group_id=240&atid=978)

This option would only be useful where j depends on some value from the previous group; as demonstrated here :

http://stackoverflow.com/a/8833899/403310

If you mix up the order of DT there,  so it isn't sorted by TreatmentID:
set.seed(10)
DT2 = DT[sample(1:24)]

then 

r=0; DT2[,{r<<-min(Rank[Rank>r]); .SD[Rank==r]}, keyby=TreatmentID]

returns slightly different (but correct) results because Rank 3 and 4 both appear in both IDs 2 and 3.

Changing by to keyby, returns the same result, just ordered differently.

Perhaps keyby should run the groups in the sorted order, instead.  Or perhaps that should be optional.

To repeat the begining of this FR, it only makes a difference if each group depends on the previous group result, as in that S.O. answer.

**Comment by mattdowle** [comment]
a39897265a84d046c079c8b308c840c86e78ba6a implements this.
