### ISSUE TITLE
Unify %s should be TRUE or FALSE messages

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6066]
This is a pretty common error, better for translation would be `stopf("%s should be TRUE or FALSE", "skip_absent")`, but that's out of scope for this PR.

_Originally posted by @MichaelChirico in https://github.com/Rdatatable/data.table/pull/6044#discussion_r1558485970_

Currently:

```
grep -Fr "should be TRUE or FALSE" po/*.pot
po/data.table.pot:msgid "narm should be TRUE or FALSE"
po/data.table.pot:msgid "fill= should be TRUE or FALSE"
```

**Comment by joshhwuu** [comment]
Should I also include error message:

```
grep -Fr "should be TRUE" po/*.pot
po/data.table.pot:msgid "use.names= should be TRUE, FALSE, or not used (\"check\" by default)"
```

**Comment by MichaelChirico** [comment]
the 'fromLast' one can be included, the other two have subtle differences that mean they can't be easily collapsed. If you think they're identical (or close to it), feel free to include in a PR; worst case we'll just revert those during review.

**Comment by ben-schwen** [comment]
Out of curiosity, what's the advantage of having %s over putting the argument in the string?

**Comment by MichaelChirico** [comment]
> Out of curiosity, what's the advantage of having %s over putting the argument in the string?

DRY principle for translation. different strings might wind up translated differently even though the English is the same.
