### ISSUE TITLE
New argument skip_absent= for colnamesInt() not to error when some columns are not found

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6067]
More general would be an argument `skip_absent=` to `colnamesInt`, then the change can be even easier:

```r
neworder = colnamesInt(x, neworder, check_dups=FALSE, skip_absent=skip_absent)
```

But I think that's better for follow-up.

_Originally posted by @MichaelChirico in https://github.com/Rdatatable/data.table/pull/6044#discussion_r1558493257_

**Comment by Nj221102** [comment]
I am working on this.
