### ISSUE TITLE
test.data.table() needs to initialize/reset setNumericRounding()

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6082]
Fails some tests:

```r
setNumericRounding(2)
test.data.table()
# Error: 2 error(s) out of 11157. Search inst/tests/tests.Rraw for test number(s) 1196.1, 1
```

After #1898 this could be a lot worse. Best to treat numeric rounding as another initial state that we want to control and then restore to user's setting on exit.

**Comment by markseeto** [comment]
@MichaelChirico I'd like to try doing this.

**Comment by MichaelChirico** [comment]
great, thanks for volunteering! assigned you, please reach out if you get stuck.

**Comment by markseeto** [comment]
Thanks @MichaelChirico.
