### ISSUE TITLE
Avoid repetitive calls to print() [default] inside print.data.table()

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6089]
we really shouldn't need all this repetition. but that's not relevant to this PR.

_Originally posted by @MichaelChirico in https://github.com/Rdatatable/data.table/pull/6087#discussion_r1563199703_
            
As illustrated in the linked PR, it's a pain to maintain since we have to remember to update 4 separate call sites to `print.default()`, all with the same signature. This should be unified.

**Comment by joshhwuu** [comment]
What do we think of changing each call to `print.default` into a `do.call` with a list of printing arguments? This way, if we ever need to add additional arguments we can just update the argument list, instead of going to every call and adding the extra argument.

We could also make a function wrapper that calls `print.default`, but we would have to pass in the arguments to this wrapper anyways, which kind of defeats the purpose.

**Comment by MichaelChirico** [comment]
> We could also make a function wrapper that calls `print.default`, but we would have to pass in the arguments to this wrapper anyways, which kind of defeats the purpose.

Not if the wrapper defined within the `print.data.table()` body, e.g.

```r
print.data.table = function(...) {
  # ...
  print_default = function(x) print(x, quote=quote, na.print=na.print, right=right)
  # ...
  if (...) {
    print_default()
  } else {
    print_default()
  }
  # ...
}
```

The third option is if we can refactor the code to avoid needing 4 call sites to begin with, e.g.

https://github.com/Rdatatable/data.table/blob/7268eff60180dac38ecc4b079021a020d3e82db3/R/print.data.table.R#L122-L124

Should we do `if (col.names != "none") cut_colnames=identity`? Then we can run `cut_colnames(print(...))` in both branches.

Can we combine the `printdots` and `!printdots` cases as well? Needs a bit more careful thought.

**Comment by joshhwuu** [comment]
Looking at it now, quite a bit of the code in `printdots` and `!printdots` branches can be factored out:

https://github.com/Rdatatable/data.table/blob/7268eff60180dac38ecc4b079021a020d3e82db3/R/print.data.table.R#L121-L128

and

https://github.com/Rdatatable/data.table/blob/7268eff60180dac38ecc4b079021a020d3e82db3/R/print.data.table.R#L136-L143

Would it be beneficial to factor out these two big chunks and then handle:

> Should we do `if (col.names != "none") cut_colnames=identity`? Then we can run `cut_colnames(print(...))` in both branches.

in the factored code?

**Comment by MichaelChirico** [comment]
It seems reasonable to me to make the `print.data.table()` body simpler / relying on helpers. We have pretty good tests of output already, so I think you can feel comfortable refactoring as long as you pass tests.
