### ISSUE TITLE
[R-Forge #2360] Do list names clobber when list is final value of j={...}, too

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#609]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2360&group_id=240&atid=978)

Should be fairly straightforward, with a good performance gain.

Highlighted by Steve L offlist on 7 Nov 2012,  and with related fix in 1.8.3.

See test 865.

**Comment by MichaelChirico** [comment]
IINM this is also covered by #3802

**Comment by mattdowle** [comment]
Closed by #3802
