### ISSUE TITLE
openMP not detected on alpine linx, with openmp-dev installed

### ISSUE THREAD

**Issue by lpagie** [Rdatatable/data.table#6092]
I'm trying to create a minimal docker container with R/data.table, using alpine as base. I'm installing the alpine packages openmp and openmp-dev.
I can run R and load data.table but get the following message:

```
data.table 1.15.4 using 1 threads (see ?getDTthreads).  Latest news: r-datatable.com
**********
This installation of data.table has not detected OpenMP support. It should still work but in single-threaded mode.
This is Linux. This warning should not normally occur on Windows or Linux where OpenMP is turned on by data.table's configure script by passing -fopenmp to the compiler. If you see this warning on Windows or Linux, please file a GitHub issue.
**********
```

Here is my dockerfile:
```
FROM rhub/r-minimal
RUN apk add --no-cache bash
CMD ["/bin/bash"]
```

and command to install data.table:
`installr -a openmp-dev -a openmp -c data.table`
where option -a installs the alpine packages and keeps them after installation, and option -c installs the C/C++ compilers and keeps them afterwards.

Can anybody help me in finding the reason (and solution?) for data.table not detecting multiple cores?

The message is from https://github.com/Rdatatable/data.table/blob/47a7f52222ee1a7062701d637a346480d838ef37/R/onAttach.R#L36
This goes back to 'hasOpenMP' in init.c (https://github.com/Rdatatable/data.table/blob/47a7f52222ee1a7062701d637a346480d838ef37/src/init.c#L323)
And now I'm lost as it seems to me all is fine ....

**Comment by ben-schwen** [comment]
What is your output of `getDTthreads(verbose=TRUE)`?

We have a working devcontainer with a dockerfile [here](https://github.com/Rdatatable/data.table/blob/master/.devcontainer/r-devel-gcc/Dockerfile)

**Comment by lpagie** [comment]
Thanks for the suggestions! Made some progress, not solved yet

output of getDTthreads(verbose=TRUE):
```
getDTthreads(verbose=TRUE)
This installation of data.table has not been compiled with OpenMP support.
  omp_get_num_procs()            1
  R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
  R_DATATABLE_NUM_THREADS        unset
  R_DATATABLE_THROTTLE           unset (default 1024)
  omp_get_thread_limit()         1
  omp_get_max_threads()          1
  OMP_THREAD_LIMIT               unset
  OMP_NUM_THREADS                unset
  RestoreAfterFork               true
  data.table is using 1 threads with throttle==1024. See ?setDTthreads.
[1] 1
```

But now I've also installed data.table using 'install.packages()'. Here's some output:
```
trying URL 'https://mirror.lyrahosting.com/CRAN/src/contrib/data.table_1.15.4.tar.gz'
Content type 'application/x-gzip' length 5387593 bytes (5.1 MB)
==================================================
downloaded 5.1 MB

* installing *source* package ‘data.table’ ...
** package ‘data.table’ successfully unpacked and MD5 sums checked
** using staged installation
gcc 13.2.1
*** pkg-config is not installed.
*** Compilation will now be attempted and if it works you can ignore this message. In
*** particular, this should be the case on Mac where zlib is built in or pkg-config
*** is not installed. However, if compilation fails, try 'locate zlib.h zconf.h' and
*** ensure the zlib development library is installed :
***   deb: zlib1g-dev (Debian, Ubuntu, ...)
***   rpm: zlib-devel (Fedora, EPEL, ...)
***   There is a zlib in brew for OSX but the built in zlib should work.
*** Note that zlib is required to compile R itself so you may find the advice in the R-admin
*** guide helpful regarding zlib. On Debian/Ubuntu, zlib1g-dev is a dependency of r-base as
*** shown by 'apt-cache showsrc r-base | grep ^Build-Depends | grep zlib', and therefore
*** 'sudo apt-get build-dep r-base' should be sufficient too.
*** To silence this message, please ensure that :
***   1) 'pkg-config --exists zlib' succeeds (i.e. $? -eq 0)
***   2) 'pkg-config --libs zlib' contains -lz
```
... there is an issue with zlib it seems ...
and then:
```
R CMD SHLIB supports OpenMP without any extra hint
*** Compilation without compression support in fwrite
** libs
using C compiler: ‘gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014’
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include    -DNOZLIB -fpic  -D__MUSL__  -c assign.c -o assign.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include    -DNOZLIB -fpic  -D__MUSL__  -c between.c -o between.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include    -DNOZLIB -fpic  -D__MUSL__  -c bmerge.c -o bmerge.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include    -DNOZLIB -fpic  -D__MUSL__  -c chmatch.c -o chmatch.o
...
```
So; OpenMP is detected by 'R CMD SHLIB ...' but it the lib is not linked ( -fopenmp)

Would that be because of the ZLIB issue? Can I force to link (is it linking?) openmp?

Now I also found  a section on not detecting openMP in https://github.com/Rdatatable/data.table/wiki/Installation

But it refers to gcc64, g++, and libgomp. But I can't find packages for these for alpine.

I built the devcontainer you [refered to](https://github.com/Rdatatable/data.table/blob/master/.devcontainer/r-devel-gcc/Dockerfile). It works fine (although to my suprise I had to manually install data.table, but sure there is a good reason for that).  
But, it results in a 1.6Gb image, while I'm hoping for an image size far less

**Comment by jangorecki** [comment]
zlib is independent of openmp, so it is not because of it

**Comment by jangorecki** [comment]
1.6gb doesn't tell much. Please break down for data.table, openmp, openmp-dev, R, C compiler. Otherwise there is not way to optimize.

**Comment by jangorecki** [comment]
You can force any compilation flags using makevars in ~/.R directory

**Comment by jangorecki** [comment]
Mine minimal image for compiling data.table, afair with openmp support, is only 230mb.
https://gitlab.com/jangorecki/dockerfiles/container_registry/5818352
https://gitlab.com/jangorecki/dockerfiles/-/blob/master/r-base/r-base-gcc
If you need lightweight setup you may want to use this one instead

**Comment by lpagie** [comment]
> You can force any compilation flags using makevars in ~/.R directory

I couldn't get this working (with my minimal experience)

> Mine minimal image for compiling data.table, afair with openmp support, is only 230mb. https://gitlab.com/jangorecki/dockerfiles/container_registry/5818352 https://gitlab.com/jangorecki/dockerfiles/-/blob/master/r-base/r-base-gcc If you need lightweight setup you may want to use this one instead
> 
> This is for R release, if you need for R-devel start from here https://gitlab.com/jangorecki/dockerfiles/container_registry/1475961 500mb

Great!!! I will try that

**Comment by lpagie** [comment]
Thanks everyone for quick and useful help

**Comment by lpagie** [comment]
I will go with Jan's container and close this issue. Thanks again!

**Comment by gaborcsardi** [comment]
For the record the r-minimal container is simply Alpine Linux, which certainly supports openmp.

**Comment by MichaelChirico** [comment]
I'm glad OP found a suitable workaround, but as Gabor notes, our `configure` should indeed be picking up OpenMP if it's there. Hence the note:

> If you see this warning on Windows or Linux, please file a GitHub issue.

**Comment by gaborcsardi** [comment]
@lpagie Did you see https://github.com/r-hub/r-minimal/issues/87#issuecomment-2062093159?

The omp library is certainly linked there:
```
bash-5.1# ldd /usr/local/lib/R/library/data.table/libs/data_table.so 2>/dev/null
        /lib/ld-musl-aarch64.so.1 (0xffffbed5e000)
	libz.so.1 => /lib/libz.so.1 (0xffffbec84000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0xffffbec35000)
	libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffffbed5e000)
```

Am I missing something?

**Comment by gaborcsardi** [comment]
> Being a bit naive maybe (and still having some blond hair underneath the grey); why is it necessary to specify this config? Should this not be automatic?

The `-fopenmp` flags are not there by default because most packages do not need openmp, and an important goal of the container is to make it small. But you can still link to openmp if your package needs it.

**Comment by lpagie** [comment]
So, it's the 'OS' which sets the default libraries to link? That sounds strange.
And installing the openmp package would be the point where this setting could by updated, no?
(sorry, sysadmin 010 questions maybe)

**Comment by gaborcsardi** [comment]
> So, it's the 'OS' which sets the default libraries to link?

R has its own default flags when compiling packages. Those flags do not include `-fopenmp` on the r-minimal image.

data.table could still add that flag if openmp is detected, even if the default R flags do not have it.

But you can always add the flags manually if you are sure that the system has openmp.

**Comment by lpagie** [comment]
Cool. I see no more related open issues. I'm closing

Thanks everybody. I give you all 5*'s

**Comment by lpagie** [comment]
Cool. I see no more related open issues. I'm closing

Thanks everybody. I give you all 5*'s
