### ISSUE TITLE
Object containing vector of column names being modified upon data.table object being modified?

### ISSUE THREAD

**Issue by vragh** [Rdatatable/data.table#6093]
Hi,

Thank you so much for the wonderful `data.table` package.

I have run into an issue that I am not sure is a bug or a feature. Namely, if I store the column names of a `data.table` in a vector, the size of this vector (and its contents, I suppose) are being automatically modified upon the `data.table` in question being modified. Below is a MRE demonstrating this phenomenon with columns being dropped (note values of object `newnames`):

```
mydt <- as.data.table(matrix(sample(letters, 16, replace = TRUE), nrow = 4, ncol = 4))
names(mydt) <- sample(LETTERS, 4)

mydt
# V E W B
# 1: f x k a
# 2: o c k q
# 3: a r i m
# 4: k o k b

newnames <- names(mydt)

newnames == names(mydt)
# [1] TRUE TRUE TRUE TRUE
newnames
# [1] "V" "E" "W" "B"

mydt[, (newnames[1]) := NULL]
mydt
# E W B
# 1: x k a
# 2: c k q
# 3: r i m
# 4: o k b

newnames
# [1] "E" "W" "B"
```

Why is this happening, and what can I do to prevent this?

`R`, and `data.table` information:
```
> library(data.table)
data.table 1.14.10 using 16 threads (see ?getDTthreads).  Latest news: r-datatable.com

> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: openSUSE Leap 15.5

Matrix products: default
BLAS:   /usr/lib64/R/lib/libRblas.so 
LAPACK: /usr/lib64/R/lib/libRlapack.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.2    tools_4.3.2       rstudioapi_0.15.0
```

**Comment by MichaelChirico** [comment]
this is very much intentional, because editing names of a table can induce a copy. Please check the FAQ and report back if you don't find this explained well there.

copy() is your friend to get your "expected" behavior, e.g. newnames=copy(names(mydt)).

note that names()<- is also discouraged in favor of setnames()

**Comment by vragh** [comment]
> this looks like a duplicate of #5756

I believe so, yes.



> this is very much intentional, because editing names of a table can induce a copy. Please check the FAQ and report back if you don't find this explained well there.
> 
> copy() is your friend to get your "expected" behavior, e.g. newnames=copy(names(mydt)).
> 
> note that names()<- is also discouraged in favor of setnames()

Thank you for the clarification. I was not even aware that there is a FAQ for `data.table` (I do now). I am not certain where in the FAQ this issue is described. Given that it is, in my limited experience, "un-R-like", I think something like this should get put out as warning messages when performing certain operations and/or get mentioned when the package is loaded and/or plastered somewhere that users (especially casual ones) are likely to visit.



> note that names()<- is also discouraged in favor of setnames()

Sometimes you just need to get a vector of the names; the objective here was not to update the column names for the object.

**Comment by MichaelChirico** [comment]
> Sometimes you just need to get a vector of the names

to clarify I'm referring to this line: 

> names(mydt) <- sample(LETTERS, 4)

**Comment by MichaelChirico** [comment]
@vragh sorry, I pointed to the wrong vignette -- reference-semantics discusses the properties of `names()`:

https://cran.r-project.org/web/packages/data.table/vignettes/datatable-reference-semantics.html

Please feel free to re-open if we can improve that documentation.

> I think something like this should get put out as warning messages when performing certain operations and/or get mentioned when the package is loaded and/or plastered somewhere that users (especially casual ones) are likely to visit.

One example would be a `names.data.table()` method that can tell when the result is being assigned (e.g. in `x <- names(DT)`, but not `print(names(DT))`), but AFAICT it's not possible to recover from inside such a method whether there's an assignment happening up in the evaluation tree. I'm open to PRs trying to improve visibility of this aspect of data.table, but it needs to be balanced against being overly noisy for the larger part of users that are familiar with this behavior & would be annoyed by such a notification.
