### ISSUE TITLE
Overwriting list-column in 1-row data.table drops wrapping `list()`

### ISSUE THREAD

**Issue by sebffischer** [Rdatatable/data.table#6104]
``` r
library(data.table)

d = data.table(x = 1, y = list(NULL))
d$y = list(list(a = 1))
d$y[[1L]]
#> [1] 1

d = data.table(x = 1:2, y = list(NULL))
d$y = list(list(a = 1), list(b = 2))
d$y[[1L]]
#> $a
#> [1] 1
```

<sup>Created on 2024-04-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ben-schwen** [comment]
I'm sorry but I cannot follow your example. What is your intended behavior?

AFAIC this is intended behavior which becomes clear when you turn on verbosity via `options(datatable.verbose=TRUE)`.

``` r
library(data.table)
options(datatable.verbose=TRUE)
data.table(x = 1, y = list(NULL))[, y := list(list(a = 1))]
#> Detected that j uses these columns: [y]
#> Assigning to all 1 rows
#> RHS_list_of_columns == false
#> RHS_list_of_columns revised to true because RHS list has 1 item which is NULL, or whose length 1 is either 1 or targetlen (1). Please unwrap RHS.
#> Direct plonk of unnamed RHS, no copy. NAMED==1, MAYBE_SHARED==0
data.table(x = 1:2, y = list(NULL))[, y := list(list(a = 1), list(b = 2))]
#> Detected that j uses these columns: [y]
#> Assigning to all 2 rows
#> RHS_list_of_columns == false
#> Direct plonk of unnamed RHS, no copy. NAMED==1, MAYBE_SHARED==0
```

**Comment by sebffischer** [comment]
Thanks for the quick response and sorry for not giving a better explanation.

When I do `d$y <- list(x)` I then expect that `d$y` is set to `list(x)`, which is also the case if `nrow(d) > 1`.
The problem is that if `nrow(d) == 1`, `d$y` is set to `x` instead of `list(x)`. 

``` r
library(data.table)

d = data.table(x = 1, y = list(NULL))
d$y = list(list(a = 1))
identical(d$y, list(list(a = 1))) # <--- I expect this to be TRUE, but it is FALSE
#> [1] FALSE
d
#>        x      y
#>    <num> <list>
#> 1:     1      1

d = data.table(x = 1:2, y = list(NULL))
d$y = list(list(a = 1), list(b = 2))
identical(d$y, list(list(a = 1), list(b = 2)))
#> [1] TRUE
d
#>        x         y
#>    <int>    <list>
#> 1:     1 <list[1]>
#> 2:     2 <list[1]>
```

<sup>Created on 2024-04-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I strongly disagree with the message `RHS_list_of_columns revised to true because RHS list has 1 item which is NULL, or whose length 1 is either 1 or targetlen (1). Please unwrap RHS.`, which seems to be guessing what I want instead of trusting me that I know what I want. The current behavior makes it reasonable tricky to insert new list columns into data.tables when the number of rows is unknown, as we always have to handle the special case with 1 row.
I am pretty sure that this causes a lot of bugs in some code-bases.

A similar issue has been reported already at least once: https://github.com/Rdatatable/data.table/issues/4568

**Comment by sebffischer** [comment]
To be more precise and give another example, I think that the first assignment below behaves how I would expect it to, but the second doesn't. 
This is, because I would interpret a `dt[, c(...)] = list(...)` as replacing columns from a data.table, where each column from the lhs is replace by the corresponding list element from the rhs. But when I do`dt$<name> <- list(...)` I replace a single column, where I just don't see why the list should be dropped, as exactly one column is being replaced and I don't need a container object to simultaneously change multiple columns.

``` r
library(data.table)

d = data.table(x = 1)
d[, "z"] = list(list(a = 1))
d
#>        x      z
#>    <num> <list>
#> 1:     1      1

d = data.table(x = 1)
d$z = list(list(a = 1))
d
#>        x      z
#>    <num> <list>
#> 1:     1      1
```

<sup>Created on 2024-04-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ben-schwen** [comment]
Ok then I would say it's a duplicate to #4569

Note that due to this inconsistency you can actually achieve what you are after by using the functional form of `:=` or its alias `let`

``` r
library(data.table)
dt = data.table(x = 1, y = list(NULL))
dt[, let(y = list(list(a=1)))]
str(dt)
#> Classes 'data.table' and 'data.frame':   1 obs. of  2 variables:
#>  $ x: num 1
#>  $ y:List of 1
#>   ..$ :List of 1
#>   .. ..$ a: num 1
#>  - attr(*, ".internal.selfref")=<externalptr>
```

**Comment by sebffischer** [comment]
yes, thanks for the response!
