### ISSUE TITLE
[R-Forge #2330]  Optimize .SD[i] query to keep the elegance but make it faster unchanged.

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#613]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2330&group_id=240&atid=978)

By using .I   See :
http://stackoverflow.com/a/12955084/403310

**Comment by jangorecki** [comment]
isn't it duplicate of  #735 ?

**Comment by mattdowle** [comment]
Raised again here :

**Comment by mattdowle** [comment]
And again here :

**Comment by kslays** [comment]
Here are more related links:
https://github.com/Rdatatable/data.table/issues/735#issuecomment-63198483 and https://github.com/Rdatatable/data.table/issues/735#issuecomment-98836402
https://stackoverflow.com/a/24558696/
https://stackoverflow.com/a/16574176/
https://stackoverflow.com/q/47539186/

**Comment by jangorecki** [comment]
Request in this issue is already resolved. It is documented in #735
