### ISSUE TITLE
coerceAs may be doing factor coercion incorrectly

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6140]
As seen in `r-cmd-check-occasional`:

https://github.com/Rdatatable/data.table/blob/c8c35f3dc23b5d4ad6d6fce7bb624f349486480c/inst/tests/nafill.Rraw#L277

When run in a locale where `y` sorts before `x` we get:

```
> x = coerceAs(1:2, factor(c("x", "y"))) 
First 2 of 2 (type 'integer'): 
[1] y x
Levels: y x
> y = factor(c("x", "y")) 
First 2 of 2 (type 'integer'): 
[1] x y
Levels: y x
2 string mismatches
```

I am not sure the intended behavior in this case, but that output does look potentially off to me. We can fix the test if the behavior is intentional, want to check with Jan first.

**Comment by jangorecki** [comment]
Locale was never considered when implementing this or adding this tests so it is not by design

**Comment by MichaelChirico** [comment]
OK, so is it an error or intended?

I lean towards "data.table always uses C locale to sort, including for generating factor levels automatically" as being the correct behavior, WDYT?

**Comment by jangorecki** [comment]
yes, agree
