### ISSUE TITLE
Request argument "notby" for unique.data.table

### ISSUE THREAD

**Issue by nielshagenbuch** [Rdatatable/data.table#6163]
I would have a wish for the function unique.data.table.

Could there be an argument “notby” that allows for specific exclusion of certain variables? If there are a lot of vars. to be included and only a few to exclude, a reverse selection would be neat.

Example:

```r 
test <- data.table(A = rep(1:3, each=4), B = rep(1:2, 6), T = 1:12)
test   ##  Imagine there were a lot of vars A, B, C, D, E, F, …, T
unique(test, by = c("A", "B", "C", "D", ...))   # T should not be considered.

##  Clumsy way to not test on "T" but have it in the output.
unique(test, by = names(test)[!(names(test) %in% "T")])

##  Wish:
unique(test, notby = "C")
```

Best,
Niels

**Comment by TimothyWillard** [comment]
Maybe slightly less clunky:
```R
identical(
  unique(test, by = names(test)[!(names(test) %in% "T")]),
  unique(test, by = setdiff(names(test), 'T'))
)
```

**Comment by MichaelChirico** [comment]
I think the `setdiff()` approach is the way to go here. I would find `notby=` a bit harder to read & always a bit loath to add new arguments, especially to an S3 method where we don't own the generic (base does).

I'll leave this open in case there is an uproarious response disagreeing with me :)

**Comment by nielshagenbuch** [comment]
All very good arguments (no pun intended).

Consider my wish no longer relevant.

Thanks for the quick and kind answers.
