### ISSUE TITLE
Failed translation of error message

### ISSUE THREAD

**Issue by trafficfan** [Rdatatable/data.table#6172]
When rewriting the BLP code using data.table, it reported an error "Error in sprintf(gettext(fmt, domain = domain, trim = trim), ...) : The format '%1%s' is invalid; the format used for character objects should be %s Called by: sprintf(gettext(fmt, domain = domain, trim = trim), ...)". ，GPT thinks it's a multi-threaded underlying crash that needs to be fed back to the developers. Attached is the refactored code that reported the error
`library(data.table)

data <- fread("G:\\Rspace\\panel_all_test.csv")

I <- 1000
TJ <- nrow(data)

market_share2 <- data[, market_share]
Q1 <- data[, knowledge_oneself]
Q2 <- data[, knowledge_colleague]
Q3 <- data[, knowledge_outside]
Q4 <- data[, social]

Z1 <- data[, iv_knowledge_oneself]
Z2 <- data[, iv_knowledge_colleague]
Z3 <- data[, iv_knowledge_outside]
Z4 <- data[, iv_social]

R <- data[, title]
C <- data[, common]

ksaai <- rnorm(TJ)
data[, ksaai := ksaai] 
Ihtheta <- rnorm(I)

market_fun <- function(subset, theta2) {
  sigma <- sqrt(theta2)
  delta2 <- subset[, delta]
  R2 <- subset[, title]
  D1 <- delta2 + sigma * (Ihtheta %*% t(R2))
  D2 <- exp(D1)
  denom <- rowSums(D2) + 1
  pre_share <- colSums(D2 / denom) / length(Ihtheta)
  return(pre_share)
}

predict_blp <- function(data, theta2) {
  setkeyv(data, 'market_order')
  data[, delta := data[, delta]]  
  data[, pred_share := market_fun(.SD, theta2)]  
  return(data[, pred_share])
}
contraction_blp <- function(data, theta2, theta1 = matrix(c(-1, 0.5, 0.5, 0.5, 0.5, 1), ncol = 1), tol = 1e-8, max_iter = 1000) {
   data[, delta := 0]
  sigma <- sqrt(theta2)
  it <- 0
  data[, delta_in := cbind(
    data[, knowledge_oneself],
    data[, knowledge_colleague],
    data[, knowledge_outside],
    data[, social],
    data[, title],
    1  # Intercept
  ) %*% theta1 + data[, ksaai]]
  
  repeat {
    data[, pred_s := predict_blp(data, theta2)]
    
    data[, delta := data[, delta_in] + log(data[, ..obs_s]) - log(data[, pred_s])]
    
    a <- abs(data[, delta] - data[, delta_in])
    if (max(a, na.rm = TRUE) < tol) {
      break
    }
    data[, delta_in := data[, delta]]
    it <- it + 1
    if (it > max_iter) {
      break
    }
  }
  return(data[, delta])
}
data[, x1 := 1]
data[, x2 := Z1]
data[, x3 := Z2]
data[, x4 := Z3]
data[, x5 := Z4]
data[, x6 := R]

data[, iv1 := 1]
data[, iv2 := Z1]
data[, iv3 := Z1^2]
data[, iv4 := Z2]
data[, iv5 := Z2^2]
data[, iv6 := Z3]
data[, iv7 := Z3^2]
data[, iv8 := Z4]
data[, iv9 := Z4^2]
data[, iv10 := R]

x <- as.matrix(data[, .(x1, x2, x3, x4, x5, x6)])
iv <- as.matrix(data[, .(iv1, iv2, iv3, iv4, iv5, iv6, iv7, iv8, iv9, iv10)])
obs_s <- matrix(market_share2)

t_iv <- t(iv)
t_x <- t(x)
w <- solve(t(iv) %*% iv)
o1 <- t_x %*% iv %*% w %*% t_iv %*% x
s_o1 <- solve(o1)
o2 <- s_o1 %*% t_x %*% iv %*% w

object_blp <- function(data, delta) {
  o3 <- t_iv %*% delta
  theta_1 <- o2 %*% o3
  mean_uti <- x %*% theta_1
  error <- delta - mean_uti
  GMM <- t(error) %*% iv %*% w %*% t_iv %*% error
  obj_list <- list("theta1" = theta_1, "mean.uti" = mean_uti, "error" = error, "GMMvalue" = GMM)
  return(obj_list)
}

optimize_iterations <- 0

gmm_blp <- function(data, theta2) {
  optimize_iterations <<- optimize_iterations + 1
  delta <- contraction_blp(data, theta2)
  ob <- object_blp(data, delta)
  objective <- ob$GMMvalue
  print(optimize_iterations)
  return(objective)
}

theta2 <- 1  
result <- optimize(gmm_blp, c(0, 100), data = data)  `

**Comment by tdhock** [comment]
hi, thanks for the report, but we are not able to help unless you create a minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example
in particular your example is not reproducible because of the first line which depends on a file, `fread("G:\Rspace\panel_all_test.csv")`
can you please create a simplified version of the data set that still raises your issue?
make sure your post answers the following questions:
what are you trying to do? what code did you run? what did you expect? what did you observe?

**Comment by MichaelChirico** [comment]
Found the bug:

https://github.com/Rdatatable/data.table/blob/a5e2bca769d6a30083b639814522b6de0cc77d9c/po/R-zh_CN.po#L374

That needs to be `%1$s`. Turn off Chinese language for now as a workaround (e.g. `Sys.setenv(LANGUAGE='en_US')`)

**Comment by MichaelChirico** [comment]
BTW, here's what the error should be:

```
Both '%1$s' and '..%1$s' exist in calling scope. Please remove the '..%1$s' variable in calling scope for clarity.
```

Might be some ambiguity about this variable `obs_s`? But here is where the MRE part really bites -- you may have to debug that yourself.

FWIW, you might prefer the "new" approach to meta-programming through the `env=` argument in `[` instead, see the new vignette:

https://cran.r-project.org/web/packages/data.table/vignettes/datatable-programming.html

**Comment by trafficfan** [comment]
[panel_all_test1.csv](https://github.com/user-attachments/files/15755469/panel_all_test1.csv)
@MichaelChirico @tdhock here's the orgin csv

**Comment by trafficfan** [comment]
I'm still new to data.table and I don't quite understand... The difference between %1$s and %1$s, does this mean that there are variables in the global environment and internal conflicts within functions?

**Comment by trafficfan** [comment]
I'm still new to data.table and I don't quite understand... The difference between %1$s and %1$s, does this mean that there are variables in the global environment and internal conflicts within functions?

**Comment by trafficfan** [comment]
> [panel_all_test1.csv](https://github.com/user-attachments/files/15755469/panel_all_test1.csv) @MichaelChirico @tdhock here's the orgin csv
I'm wondering if i can solve the report 
![image](https://github.com/Rdatatable/data.table/assets/149685680/0a856ea0-c736-447b-861d-fcce44c8ed65)

**Comment by MichaelChirico** [comment]
> > [panel_all_test1.csv](https://github.com/user-attachments/files/15755469/panel_all_test1.csv) @MichaelChirico @tdhock here's the orgin csv
> > I'm wondering if i can solve the report
> > ![image](https://private-user-images.githubusercontent.com/149685680/338027495-0a856ea0-c736-447b-861d-fcce44c8ed65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzYyMjYsIm5iZiI6MTcxODAzNTkyNiwicGF0aCI6Ii8xNDk2ODU2ODAvMzM4MDI3NDk1LTBhODU2ZWEwLWM3MzYtNDQ3Yi04NjFkLWZjY2U0NGM4ZWQ2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxNjEyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDlhMDU2NTQxNmZjZjBiOTdkZDlhNjlkMjAxZDRmMDM2YzdhYTRlZTQ4NzFkNjk2M2Y5NTc5Y2M2MGZkZGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oVp1OANn9JSCWnt8B-K9rksgGPFGwry1pxCkAiE09Bk)

Here is a different error message than before. I think we'll need to see a more minimal example to help further. Which line produces this error?

**Comment by Anirban166** [comment]
> I'm still new to data.table and I don't quite understand... The difference between %1$s and %1$s, does this mean that there are variables in the global environment and internal conflicts within functions?

You understood mostly correct, or afaik `variableName` refers to a variable within the current scope whereas `..variableName` is used to reference variables from the calling environment (where the `data.table` call was made, and yes that is usually the global environment, unless it is defined inside a function for e.g.) when there is a naming conflict within the `data.table` scope (or within `DT[ ... ]`).

Like Michael already mentioned, it's likely the `obs_s` variable if this is indeed the source of error, as I see it being both assigned within the scope of a `data.table` call and outside it:
```r
obs_s <- matrix(market_share2)
```
```r
data[, delta := data[, delta_in] + log(..obs_s) - log(data[, pred_s])]
```

So you can either rename the variable used inside the scope of `data` above or avoid using `..obs_s` by directly referencing the column name to avoid that issue.

**Comment by trafficfan** [comment]
Thank you for your generous help.the problem was solved!
