### ISSUE TITLE
fread() parameter na.strings does not work as expected

### ISSUE THREAD

**Issue by HMU-WH** [Rdatatable/data.table#6186]
### Example

I have a set of character vectors read from a file, like the following：
```r
text <- c("line1\t\"na\"\t\"a\"", "line2\t\"b\"\t\"na\"")
```
When I run:
```r
data.table::fread(text = text, sep = "\t", header = FALSE, na.strings = "\"na\"")
```
The result is:
```
       V1     V2     V3
   <char> <char> <char>
1:  line1     na      a
2:  line2      b     na
```
It can be seen that the parameter "na.strings" does not work!

But when I only operate on a single element, it works fine:
```r
data.table::fread(text = text[1], sep = "\t", header = FALSE, na.strings = "\"na\"")
```
output:
```
       V1     V2     V3
   <char> <lgcl> <char>
1:  line1     NA      a
```

I think this is a bug in `fread()`！

### SessionInfo

```
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8 LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] HaoUtils_1.0.0

loaded via a namespace (and not attached):
 [1] tidyr_1.3.1        utf8_1.2.4         R6_2.5.1           tidyselect_1.2.1   magrittr_2.0.3    
 [6] glue_1.7.0         stringr_1.5.1      tibble_3.2.1       R.utils_2.12.3     pkgconfig_2.0.3   
[11] dplyr_1.1.4        generics_0.1.3     lifecycle_1.0.4    xml2_1.3.6         cli_3.6.2         
[16] fansi_1.0.6        R.methodsS3_1.8.2  vctrs_0.6.5        data.table_1.15.99 compiler_4.3.3    
[21] R.oo_1.26.0        purrr_1.0.2        rstudioapi_0.16.0  tools_4.3.3        curl_5.2.1        
[26] pillar_1.9.0       rlang_1.1.3        stringi_1.8.3   
```

**Comment by ecoRoland2** [comment]
You obviously consider the quotation marks as part of the strings, in contrast to quotes marking character strings (as is good practice). `fread` seems to get confused with the default `quote="\""` and doesn't do the second pass with quotes disabled. 

If you help `fread` a bit, everything works as expected:

```
data.table::fread(text = text, sep = "\t", header = FALSE, na.strings = "\"na\"", quote = FALSE)
#       V1     V2     V3
#   <char> <char> <char>
#1:  line1   <NA>    "a"
#2:  line2    "b"   <NA>
```
Note how it now considers the quotes part of the string, in contrast to your attempt with only line 1.

I would consider your input an edge case and I'm not sure it's worth the effort of fixing this.

**Comment by HMU-WH** [comment]
Sorry, the first example I gave didn't simulate it clearly.

I don't want to set quote = "", I expect the result to not contain double quotes. As I said at the beginning, `text` are simulated lines read from a file, like this:
```
"line1"	"na"	"a"
"line2"	"a"	"na"
```
Assume the name of the file is `tmp.txt`.

The result I expect is:
```
       V1     V2     V3
   <char> <char> <char>
1:  line1     <NA>      a
2:  line2      a     <NA>
```

But the result of the following code is:
```
data.table::fread(file = "tmp.txt", sep = "\t", header = FALSE, na.strings = c("na", "\"na\""))
       V1     V2     V3
   <char> <char> <char>
1:  line1     na      a
2:  line2      a     na
```

In addition, I think "na.strings" should not be set to the form of `\"...\"`, but in some cases it must be set this way, such as the previous single element operation example.

**Comment by HMU-WH** [comment]
Sorry, the first example I gave didn't simulate it clearly.

I don't want to set quote = "", I expect the result to not contain double quotes. As I said at the beginning, `text` are simulated lines read from a file, like this:
```
"line1"	"na"	"a"
"line2"	"a"	"na"
```
Assume the name of the file is `tmp.txt`.

The result I expect is:
```
       V1     V2     V3
   <char> <char> <char>
1:  line1     <NA>      a
2:  line2      a     <NA>
```

But the result of the following code is:
```
data.table::fread(file = "tmp.txt", sep = "\t", header = FALSE, na.strings = c("na", "\"na\""))
       V1     V2     V3
   <char> <char> <char>
1:  line1     na      a
2:  line2      a     na
```

In addition, I think "na.strings" should not be set to the form of `\"...\"`, but in some cases it must be set this way, such as the previous single element operation example.

**Comment by HMU-WH** [comment]
> So the problem is that files with quoted `na.strings` cannot be read properly?那么问题是带引号 `na.strings` 的文件无法正确读取？
> 
> ```r
> library(data.table)
> dt = data.table(a=c("l1", "l2"), b=c(NA, "a"), c=c("a", NA))
> f = tempfile()
> fwrite(dt, f, col.names=FALSE, na="\"na\"")
> fread(f, header=FALSE, na.strings="\"na\"")
> #>        V1     V2     V3
> #>    <char> <char> <char>
> #> 1:     l1     na      a
> #> 2:     l2      a     na
> ```
> 
> Seems related/duplicate to #2586似乎与 #2586 相关/重复

Yes, `na.strings` does not work as expected for text files with double quotes. This is indeed related/duplicate to [#2586](https://github.com/Rdatatable/data.table/issues/2586)

Methods such as `read.table` can get the expected results, but they are far less efficient than` fread`.I really hope `fread` can enhance support for this function!
