### ISSUE TITLE
[R-Forge #2276] -.data.table could skip over character columns

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#620]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2276&group_id=240&atid=978)

so that B - A[B] could work without [,-1,with=FALSE] shinanigans that would be needed if that approach were used here :

http://stackoverflow.com/a/12399549/403310

**Comment by MichaelChirico** [comment]
@mattdowle I wonder if the `data.frame`-like column selection now available doesn't cover this?

**Comment by MichaelChirico** [comment]
Not sure I see the benefit of this method, workarounds using e.g. `.SDcols=!is.character` seem easy enough. And for the SO Q&A in question (as I've just edited), all the cruft around `with=FALSE` is no longer needed as `[, -1L]` works just fine.
