### ISSUE TITLE
please add members to Chinese team

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#6206]
Hi @MichaelChirico I believe you know the github usernames of the people who worked on the Chinese translation? 
Can you please add them to https://github.com/orgs/Rdatatable/teams/chinese/members ?
I have already invited members to French and Portuguese teams.
All are under a parent team "Translators" which has parent "Project Members"
I created these teams for easy mentioning, for example `@Rdatatable/translators` or `@Rdatatable/chinese`

**Comment by joshhwuu** [comment]
I'm not sure if we need this help but I could also help with future Chinese translations as well :)

**Comment by tdhock** [comment]
Hi Josh, thanks for volunteering. I added you to the team as a maintainer. Please feel free to update the translations, and add new members to the translation team, if you know of others who may be able to help.

**Comment by MichaelChirico** [comment]
I've invited everyone who sent a PR as part of the original effort (PRs with `label:translation`), most importantly @hongyuanjia who has taken charge of updating translations following the initial push. Thanks everyone! Closing this.
