### ISSUE TITLE
Gitlab CI wrong tags for runner

### ISSUE THREAD

**Issue by ben-schwen** [Rdatatable/data.table#6209]
Our nightly builds get stuck daily in their first stage.

AFAIU we use tags in our `.gitlab-ci.yml` file and our runner does not have them listed.

@MichaelChirico If you could add [me](https://gitlab.com/ben-schwen) to the Gitlab repo I would try to fix it.

**Comment by jangorecki** [comment]
I added you to the org there.  Seems that problem is on gitlab side

> This job is stuck because of one of the following problems. There are no active runners online, no runners for the [protected branch](https://docs.gitlab.com/runner/security/index.html#reduce-the-security-risk-of-using-privileged-containers), or no runners that match all of the job's tags: linux

**Comment by jangorecki** [comment]
If there is no easy fix for that we could change update_dev_pkg to point to alternative location

**Comment by ben-schwen** [comment]
For future references, here also the [deprecation post](https://docs.gitlab.com/ee/update/deprecations.html#removal-of-tags-from-small-saas-runners-on-linux)
