### ISSUE TITLE
Update documentation for CJ supporting complex number 

### ISSUE THREAD

**Issue by sandhya-davera** [Rdatatable/data.table#6215]
In the documentation, pg no. 73, it says the function CJ  "support for sorting complex is not yet implemented".
I expected to get a warning, but the sorting looks correct. It looks like it has been added in the pull request https://github.com/Rdatatable/data.table/issues/3690.  If the functionality is implemented, would it be possible to update the documentation to remove this comment: "support for sorting complex is not yet implemented"

**Comment by ben-schwen** [comment]
Good catch. Seems that #3691 added the current example and it wasn't updated when we started to support sorting with #3701

**Comment by MichaelChirico** [comment]
thanks @sandhya-davera ! do you want to have a go at writing the PR?
