### ISSUE TITLE
vignette translations: define the expected translated package vignette file extensions ?

### ISSUE THREAD

**Issue by ChristianWia** [Rdatatable/data.table#6223]
What kind of file should be provided with vignette translations ?

Starting from an .Rmd file i have seen that packages contain sometimes additionally .pdf and .html vignette files generated from the initial file. 

Example:
```
Vignettes in package ‘aplpack’:

sliderfns           Working with Slider Functions (source,
                    pdf)

Vignettes in package ‘argonR’:

getting_started     Getting Started (source, html)
```

This (multiplied by the number of locales) is for easy use but will increase size of the package. 

So as a requirement, which vignette file extensions could we expect for translated data.table  ? Thanks.

This topic is linked with  #6221

**Comment by tdhock** [comment]
I believe you are asking about the format of the built vignettes?
In https://cloud.r-project.org/src/contrib/data.table_1.15.4.tar.gz the inst/doc directory contains html as the built format (not pdf)
But we do not add those files to git / source package. 
instead they are created via R CMD build, before submission of package to CRAN.
Does that answer your question?

**Comment by ChristianWia** [comment]
All is ok What I see in the installed package below comes from   inst/doc  source being the .Rmd and the .html . So at my level we  only need to  provide the viable  XXX-fr.Rmd files and the build will generate via R the derived .html (or other) files present in the .tar.gz.   Thanks. 


```
Vignettes in package ‘data.table’:

datatable-benchmarking
                    Benchmarking data.table (source, html)
datatable-reshape   Efficient reshaping using data.tables
                    (source, html)
datatable-faq       Frequently asked questions (source,
                    html)
datatable-importing
                    Importing data.table (source, html)
datatable-intro     Introduction to data.table (source,
                    html)
datatable-keys-fast-subset
                    Keys and fast binary search based subset
                    (source, html)
datatable-reference-semantics
                    Reference semantics (source, html)
datatable-secondary-indices-and-auto-indexing
                    Secondary indices and auto indexing
                    (source, html)
datatable-sd-usage
                    Using .SD for Data Analysis (source,
                    html)
```

**Comment by tdhock** [comment]
right, if that is ok then please close.
