### ISSUE TITLE
normalise R markdown  ```r

### ISSUE THREAD

**Issue by ChristianWia** [Rdatatable/data.table#6225]
check the vignettes files  for R code chunk inclusions to be compatible with existing tools. include r in braces.: instead ```r  write ```{r}
```
ex: in data table intro Rmd
```r
    flights[origin == "XYZ"]
  # Returns:
  # Empty data.table (0 rows and 19 cols): year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...
  ```
```

**Comment by MichaelChirico** [comment]
Thanks for the report, but sorry, I prefer ```` ```r ```` when `eval=FALSE`, IMO it's a clearer way to express `eval=FALSE`. Some tooling (e.g. {lintr}) is also not (currently) equipped to read & respect chunk attributes (including `eval=FALSE`), leading to false positives in static analysis from analyzing code that is never meant to be evaluated.

If you see any ```` ```{r} ```` usage that should instead be changed to ```` ```r ```` instead for consistency, a PR would be welcome (and then reopen here).
