### ISSUE TITLE
C API isFrame regression

### ISSUE THREAD

**Issue by ben-schwen** [Rdatatable/data.table#6244]
#6235 introduced a new error as shown by our [GitLab CI](https://gitlab.com/Rdatatable/data.table/-/jobs/7324126750)

```
dogroups.c: In function ‘dogroups’:
dogroups.c:279:35: warning: implicit declaration of function ‘isDataFrame’; did you mean ‘isFrame’? [-Wimplicit-function-declaration]
  279 |         if (!isVector(thiscol) || isDataFrame(thiscol))
      |                                   ^~~~~~~~~~~
      |                                   isFrame

Error: package or namespace load failed for ‘data.table’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/builds/Rdatatable/data.table/data.table.Rcheck/00LOCK-data.table/00new/data.table/libs/data_table.so':
  /builds/Rdatatable/data.table/data.table.Rcheck/00LOCK-data.table/00new/data.table/libs/data_table.so: undefined symbol: isDataFrame
```

**Comment by MichaelChirico** [comment]
Hmm, I only see one other package attempting to define `isDataFrame()` and it's done in the same way AFAICT:

https://github.com/cran/QuickJSR/blob/0718dce159a9bdb8aa3abd08679418ebdabfffae/inst/include/quickjsr/SEXP_to_JSValue.hpp#L10-L13

**Comment by ben-schwen** [comment]
<img width="1716" alt="2024-07-13_00-38" src="https://github.com/user-attachments/assets/70779cfe-5fd1-410e-a77f-bac208946466">

You can download the `artifacts.zip` at the right hand side (see screenshot above)
And then inside the `artifacts.zip` at `/bus/test-lin-dev-gcc-strict-cran/data.table.Rcheck/00install.out`

**Comment by MichaelChirico** [comment]
Oh, sorry. I managed to look at 00install.log thinking I was seeing 00install.out 😨

**Comment by MichaelChirico** [comment]
@ben-schwen what's going on here is the GCLI runner is on a slightly old version of r-devel. We see r86945 in the logs, but `isDataFrame()` was added in r86702: https://github.com/r-devel/r-svn/commit/4ef83b9dc3c6874e774195d329cbb6c11a71c414. So the GCLI issue will go away on its own. Still I think we can hold off on #6235 for a while as it's not generating a `NOTE` yet -- I think it makes sense to wait for `isDataFrame()` to make an R release first.
