### ISSUE TITLE
revdep dtts test error after all.equal dispatch

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#6285]
https://github.com/Rdatatable/data.table/pull/4546 broke revdep dtts https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-07-16/
```
* checking tests ...
  Running 'tinytest.R'
 ERROR
Running the tests in 'tests/tinytest.R' failed.
Last 13 lines of output:
   diff| Column 'index': Mean relative difference: 0.01851852
  ----- FAILED[attr]: test_dtts.R<128--128>
   call| expect_equal(align(dt1, t2, start = as.nanoduration(0), end = one_second_duration, 
   call| -->    eopen = FALSE), dt1[seq(5, 50, 5)])
   diff| Column 'index': Mean relative difference: 0.01785714
  ----- FAILED[attr]: test_dtts.R<139--139>
   call| expect_equal(align(dt1, t2, start = -one_second_period, tz = "America/New_York"), 
   call| -->    dt1[seq(4, 49, 5)])
   diff| Column 'index': Mean relative difference: 0.01851852
  ----- FAILED[attr]: test_dtts.R<149--149>
   call| expect_equal(align(dt1, t2, end = one_second_period, eopen = FALSE, 
   call| -->    tz = "America/New_York"), dt1[seq(5, 50, 5)])
   diff| Column 'index': Mean relative difference: 0.01785714
  Error: 4 out of 102 tests failed
  Execution halted
```
@MichaelChirico @ben-schwen can you please investigate?

**Comment by MichaelChirico** [comment]
Sent https://github.com/eddelbuettel/dtts/pull/18

**Comment by eddelbuettel** [comment]
Just to reiterate -- the new `dtts` is at CRAN now so no worries on your end:

![image](https://github.com/user-attachments/assets/e6536a58-491d-4a51-91b6-c4ad79d9dbf8)

**Comment by MichaelChirico** [comment]
Thanks Dirk! Our protocol here is to wait for a :heavy_plus_sign: report from the revdeps server; I see that now:

https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-07-19/

![image](https://github.com/user-attachments/assets/476d16b0-3e0a-4fda-b438-07953894cfef)

So closing.
