### ISSUE TITLE
[R-Forge #2175] Add natural joins i.e. X[Y] when X has no key could use common column names

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#629]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2175&group_id=240&atid=978)

Use matching column names in this case.

As suggested by David Kulp here :

http://lists.r-forge.r-project.org/pipermail/datatable-help/2012-August/001241.html

Or, leave this to merge (since merge.data.table does that)? And if so, document.

**Comment by MichaelChirico** [comment]
This is easy now with `on`, correct? could set default of `on` to `intersect(names(dt1),names(dt2))`, for example.

**Comment by franknarf1** [comment]
@MichaelChirico I would prefer to see a special value for `on` (analogous to `.EACHI`), to keep it explicit/transparent, like `on=.COMMON`. 

While we're at it, I suppose there could be an `onby` (if the logic & code are structured so that that actually makes sense).

**Comment by MichaelChirico** [comment]
This seems like a close relative of the recently-closed #1517

**Comment by MichaelChirico** [comment]
@franknarf1 in keeping with SQL-inspired syntax, I was thinking `on = .NATURAL` would be a very natural (sorry) way to implement this.
