### ISSUE TITLE
[R-Forge #2153] Closures/Functions Column Values

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#631]
Submitted by: Yike Lu; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2153&group_id=240&atid=978)

It would be nice to be able to have closures as column values - I am creating a different function per row,

**Comment by MichaelChirico** [comment]
Seems identical to #518

**Comment by arunsrinivasan** [comment]
Thanks @MichaelChirico.
