### ISSUE TITLE
my_subset() does not actually replicate subset()

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6315]
https://github.com/Rdatatable/data.table/blob/822631e985cfcbd29ddae9e63bb75b30c42c5816/vignettes/datatable-programming.Rmd#L69

subset() also drops NA values, so this helper should to. I think it will emphasize the point that writing with [[ can be very hard to read

**Comment by TysonStanley** [comment]
You thinking something like

```r
my_subset = function(data, col, val) {
  data[data[[col]] == val & !is.na(data[[col]]), ]
}
my_subset(iris, col = "Species", val = "setosa")
```

**Comment by MichaelChirico** [comment]
Yea that would be more faithful to what `subset()` actually does. Besides the simple edit, also think about whether the surrounding text can benefit from pointing out how messy it is / needing to re-invent original logic.
