### ISSUE TITLE
Add an atime performance regression test for forder caching

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6320]
@Anirban166 this is a good candidate for a performance regression test, would you like to take a stab at writing one? I don't think Jan will get to it quickly :)

_Originally posted by @MichaelChirico in https://github.com/Rdatatable/data.table/issues/4386#issuecomment-2224114772_
            
It will be good to have a test in the performance suite showing the improvement + preventing regression.

**Comment by Anirban166** [comment]
Forgot to mention here or link back to this issue but I created a test shortly around the time after you posted this, [GHA test in my fork](https://github.com/Anirban166/data.table/pull/15) - @MichaelChirico @tdhock Could you guys please check if that qualifies?

My code for quick reference:
```r
...

  "forder improved in #4386" = atime::atime_test(
    N = 10^seq(1, 8), # 1e9 probably exceeds the runner's memory (process gets killed)
    setup = {
      dt <- data.table(id = sample(N), value = rnorm(N))
    },
    expr = {
      data.table:::setkey(dt, id)
      dt[order(data.table:::forder(dt, "id"))]
      dt[order(data.table:::forder(dt, "id"))] # Can repeat more but twice is good enough to see the caching in effect.
    },
    Slow = "c152ced0e5799acee1589910c69c1a2c6586b95d", # Parent of the merge commit that fixes the regression
    Fast = "1a84514f6d20ff1f9cc614ea9b92ccdee5541506"), # Merge commit of the PR (https://github.com/Rdatatable/data.table/pull/4386/commits) that fixes the regression

...
```
I was not sure if the test case I wrote above was accurate enough (compared to [this](https://github.com/Rdatatable/data.table/pull/4386#issuecomment-2254259077) say, since I didn't use `datatable.forder.reuse.sorting=TRUE`), but the results look about right to me: (clear spike in memory usage, all version labels seem to make sense)

![image](https://github.com/user-attachments/assets/27147fdb-a76b-44a0-ad0e-a11c9f9f1587)

**Comment by tdhock** [comment]
I dont see any time difference, only memory difference. is that normal?

**Comment by Anirban166** [comment]
Given the purpose of caching, the main improvement should be in time so I think you're right as this shows little difference there (the 'Slow' label is still above compared to the other versions) versus it indicating better use of memory by a higher factor.

**Comment by tdhock** [comment]
then your performance test needs to be revised

**Comment by Anirban166** [comment]
WDYT about the [latest one](https://github.com/Anirban166/data.table/pull/15#issuecomment-2259112776)? (to me, it makes much more sense than the previous results I was getting)

![image](https://github.com/user-attachments/assets/8fc8706b-9e82-437f-ba53-65596bcf006a)

Core differences in this test case compared to my previous version include additional ordering operations, using `setindex` instead of `setkey`, and testing different key combinations to evaluate the performance of reusing the cache better.

**Comment by tdhock** [comment]
this new figure is not conclusive because we only see one N for most versions.
you could increase seconds.limit to debug, but you should revise the test case to get the overall timings for all methods well below 0.01 seconds, so the test case runs fast on CI.

**Comment by Anirban166** [comment]
> this new figure is not conclusive because we only see one N for most versions.

True 

I kept revising my test and played around with the parameters a bit till I found a sweet spot (minimal time ft. correct results) among the results that I'm [observing](https://github.com/Anirban166/data.table/pull/15#issuecomment-2259112776):

![image](https://github.com/user-attachments/assets/07218991-3326-4f3c-9fbe-1c5e340af579)

```r 
  "forder improved in #4386" = atime::atime_test(
    ## 1e9 exceeds the runner's memory (process gets killed) and < 1e8 does not show the most accurate results for memory use.
    N = 10^seq(3, 8),
    seconds.limit = 0.08,
    setup = {
      dt <- data.table(a = sample(letters, N, TRUE), b = rnorm(N))
    },
    expr = {
      data.table:::setindex(dt, a)  
      options(datatable.forder.reuse.sorting = TRUE, datatable.verbose = TRUE)
      dt[order(data.table:::forder(dt, c("a", "b")))]
      dt[order(data.table:::forder(dt, "a"))]
    },
    Slow = "c152ced0e5799acee1589910c69c1a2c6586b95d", # Parent of the merge commit that fixes the regression
    Fast = "1a84514f6d20ff1f9cc614ea9b92ccdee5541506"), # Merge commit of the PR (https://github.com/Rdatatable/data.table/pull/4386/commits) that fixes the regression
```
This runs for all `N` up to 10<sup>8</sup> only when `seconds.limit` is greater than 0.07 seconds (else the computations for the higher `N` will be cut off like the previous plot I shared on this thread), thus 0.08. If I were to reduce computing `N` to 10<sup>7</sup> or lower, we won't get accurate results ('Fast' and 'Slow' labels will be together in terms of memory [for e.g.](https://camo.githubusercontent.com/43495e80b45dc516741f21df4551cd3e91ddaa49f450e8710a47bfd9862c5def/68747470733a2f2f61737365742e636d6c2e6465762f316161646437376237353436636638656462303031343134646630373335663464393331636132633f636d6c3d706e672663616368652d6279706173733d33633866616136622d633161652d343335652d613539622d666362616666343161343562) which I don't think is true, or it should show a difference/improvement in memory usage as well for an amply sized benchmark).

As for CI, the time difference in running this is not too big (~20 seconds more on average) vs the last one I shared here above or the usual time it takes to run this one test. Thoughts? @tdhock

**Comment by Anirban166** [comment]
> this new figure is not conclusive because we only see one N for most versions.

True 

I kept revising my test and played around with the parameters a bit till I found a sweet spot (minimal time ft. correct results) among the results that I'm [observing](https://github.com/Anirban166/data.table/pull/15#issuecomment-2259112776):

![image](https://github.com/user-attachments/assets/07218991-3326-4f3c-9fbe-1c5e340af579)

```r 
...

  "forder improved in #4386" = atime::atime_test(
    ## 1e9 exceeds the runner's memory (process gets killed) and < 1e8 does not show the most accurate results for memory use.
    N = 10^seq(3, 8),
    seconds.limit = 0.08,
    setup = {
      dt <- data.table(a = sample(letters, N, TRUE), b = rnorm(N))
    },
    expr = {
      data.table:::setindex(dt, a)  
      options(datatable.forder.reuse.sorting = TRUE, datatable.verbose = TRUE)
      dt[order(data.table:::forder(dt, "a"))]
      dt[order(data.table:::forder(dt, "a"))]
    },
    Slow = "c152ced0e5799acee1589910c69c1a2c6586b95d", # Parent of the merge commit that fixes the regression
    Fast = "1a84514f6d20ff1f9cc614ea9b92ccdee5541506"), # Merge commit of the PR (https://github.com/Rdatatable/data.table/pull/4386/commits) that fixes the regression

...
```
This runs for all `N` up to 10<sup>8</sup> only when `seconds.limit` is greater than 0.07 seconds (else the computations for the higher `N` will be cut off like the previous plot I shared on this thread), thus 0.08. If I were to reduce computing `N` to 10<sup>7</sup> or lower, we won't get accurate results ('Fast' and 'Slow' labels will be together in terms of memory [for e.g.](https://camo.githubusercontent.com/43495e80b45dc516741f21df4551cd3e91ddaa49f450e8710a47bfd9862c5def/68747470733a2f2f61737365742e636d6c2e6465762f316161646437376237353436636638656462303031343134646630373335663464393331636132633f636d6c3d706e672663616368652d6279706173733d33633866616136622d633161652d343335652d613539622d666362616666343161343562) which I don't think is true, or it should show a difference/improvement in memory usage as well for an amply sized benchmark).

As for CI, the time difference in running this is not too big (~20 seconds more on average) vs the last one I shared here above or the usual time it takes to run this one test. Thoughts? @tdhock

**Comment by Anirban166** [comment]
> this new figure is not conclusive because we only see one N for most versions.

True 

I kept revising my test and played around with the parameters a bit till I found a sweet spot (minimal time ft. correct results) among the results that I'm [observing](https://github.com/Anirban166/data.table/pull/15#issuecomment-2259112776):

![image](https://github.com/user-attachments/assets/07218991-3326-4f3c-9fbe-1c5e340af579)

```r 
...

  "forder improved in #4386" = atime::atime_test(
    ## 1e9 exceeds the runner's memory (process gets killed) and < 1e8 does not show the most accurate results for memory use.
    N = 10^seq(3, 8),
    seconds.limit = 0.08,
    setup = {
      dt <- data.table(a = sample(letters, N, TRUE))
    },
    expr = {
      data.table:::setindex(dt, a)  
      options(datatable.forder.reuse.sorting = TRUE, datatable.verbose = TRUE)
      dt[order(data.table:::forder(dt, "a"))]
      dt[order(data.table:::forder(dt, "a"))]
    },
    Slow = "c152ced0e5799acee1589910c69c1a2c6586b95d", # Parent of the merge commit that fixes the regression
    Fast = "1a84514f6d20ff1f9cc614ea9b92ccdee5541506"), # Merge commit of the PR (https://github.com/Rdatatable/data.table/pull/4386/commits) that fixes the regression

...
```
This runs for all `N` up to 10<sup>8</sup> only when `seconds.limit` is greater than 0.07 seconds (else the computations for the higher `N` will be cut off like the previous plot I shared on this thread), thus 0.08. If I were to reduce computing `N` to 10<sup>7</sup> or lower, we won't get accurate results ('Fast' and 'Slow' labels will be together in terms of memory [for e.g.](https://camo.githubusercontent.com/43495e80b45dc516741f21df4551cd3e91ddaa49f450e8710a47bfd9862c5def/68747470733a2f2f61737365742e636d6c2e6465762f316161646437376237353436636638656462303031343134646630373335663464393331636132633f636d6c3d706e672663616368652d6279706173733d33633866616136622d633161652d343335652d613539622d666362616666343161343562) which I don't think is true, or it should show a difference/improvement in memory usage as well for an amply sized benchmark).

As for CI, the time difference in running this is not too big (~20 seconds more on average) vs the last one I shared here above or the usual time it takes to run this one test. Thoughts? @tdhock

**Comment by tdhock** [comment]
your figure does not make sense. Fast has larger computation time than Slow. Did you mix them up? Why is there such a large difference in the constant overhead? Please double check.

**Comment by tdhock** [comment]
it seems like this is taking too long and you are not making much progress, so maybe try to focus your time on other low hanging fruit? (other tasks which would be easier/faster to get useful results)

**Comment by Anirban166** [comment]
> your figure does not make sense. Fast has larger computation time than Slow. Did you mix them up? Why is there such a large difference in the constant overhead? Please double check.

I thought the label grouping made sense..it's similar to some other test case results that you approved of and we are currently seeing in the plots from PRs. For example, [here](https://camo.githubusercontent.com/e2fbba8c85e5ff6956da747ad7ee929f251ab85e73b3c4e91cb1d50b34a0ea71/68747470733a2f2f61737365742e636d6c2e6465762f616437616662316261646232613137333163393832363636613039633733356532646162623031323f636d6c3d706e672663616368652d6279706173733d35306230633331622d663364342d346261612d613335352d313566393238373963663037) is a recent example where it shows two similar cases: ('Fast' has larger computation time than 'Slow')

<img width="854" alt="image" src="https://github.com/user-attachments/assets/96878179-b4d6-4d09-a8de-cd48ada13d0e">

(and I cross checked, I did not mix the labels; [code](https://github.com/Anirban166/data.table/pull/15/files) for quick reference)

**Comment by Anirban166** [comment]
> it seems like this is taking too long and you are not making much progress, so maybe try to focus your time on other low hanging fruit? (other tasks which would be easier/faster to get useful results)

Sure

**Comment by Anirban166** [comment]
> your figure does not make sense. Fast has larger computation time than Slow. Did you mix them up? Why is there such a large difference in the constant overhead? Please double check.

I thought the label grouping made sense..it's similar to some other test case results that you approved of and we are currently seeing in the plots from PRs. For example, [here](https://camo.githubusercontent.com/e2fbba8c85e5ff6956da747ad7ee929f251ab85e73b3c4e91cb1d50b34a0ea71/68747470733a2f2f61737365742e636d6c2e6465762f616437616662316261646232613137333163393832363636613039633733356532646162623031323f636d6c3d706e672663616368652d6279706173733d35306230633331622d663364342d346261612d613335352d313566393238373963663037) is a recently generated plot where it shows two similar cases: ('Fast' has larger computation time than 'Slow')

<img width="854" alt="image" src="https://github.com/user-attachments/assets/96878179-b4d6-4d09-a8de-cd48ada13d0e">

(and I cross checked, I did not mix the labels; [code](https://github.com/Anirban166/data.table/pull/15/files) for quick reference)

**Comment by Anirban166** [comment]
> it seems like this is taking too long and you are not making much progress, so maybe try to focus your time on other low hanging fruit? (other tasks which would be easier/faster to get useful results)

Sure

**Comment by tdhock** [comment]
> [here](https://camo.githubusercontent.com/e2fbba8c85e5ff6956da747ad7ee929f251ab85e73b3c4e91cb1d50b34a0ea71/68747470733a2f2f61737365742e636d6c2e6465762f616437616662316261646232613137333163393832363636613039633733356532646162623031323f636d6c3d706e672663616368652d6279706173733d35306230633331622d663364342d346261612d613335352d313566393238373963663037) is a recently generated plot where it shows two similar cases: ('Fast' has larger computation time than 'Slow')

actually, in that figure, Fast has smaller computation time, but larger memory usage, for the setDT test (left). Were you mistaken? Please clarify.

**Comment by Anirban166** [comment]
You're right, now I see the trends make sense - I wasn't looking at the points, my bad! (I got confused by the labels being above)

**Comment by Anirban166** [comment]
You're right, now that I see it again, it makes sense - I wasn't looking at the points or the trend curves, my bad! (I got confused by the labels being above)

**Comment by tdhock** [comment]
@Anirban166 what is the status of this test/issue?

**Comment by Anirban166** [comment]
I started revising it this week. Looking at the initial post by Jan made things clear as I had to use `forderv` and then set the `datatable.forder.auto.index` option to cache the index initially created by the first call to it.

Here is my current version:
```r
# Fixed in: https://github.com/Rdatatable/data.table/pull/4386
"forder improved in #4386" = atime::atime_test(
  N = 10^seq(3, 8), # 1e9 exceeds the runner's memory (process gets killed)
  setup = {
    options(datatable.verbose = TRUE, datatable.forder.auto.index = TRUE, datatable.forder.reuse.sorting = TRUE)
    dt <- data.table(index = sample(N), values = sample(N))
    data.table:::forderv(dt, "index") # First ordering call to initialize caching
  },
  expr = {
    data.table:::forderv(dt, "index", retGrp = FALSE) # Reuse the cached index (no group information required)
    data.table:::forderv(dt, "index", retGrp = TRUE) # Reuse the index but compute group info.
  },
  Slow = "c152ced0e5799acee1589910c69c1a2c6586b95d", # Parent of the merge commit of the PR (https://github.com/Rdatatable/data.table/pull/4386/commits) that fixes the regression
  Fast = "1a84514f6d20ff1f9cc614ea9b92ccdee5541506") # Merge commit of the PR (https://github.com/Rdatatable/data.table/pull/4386/commits) that fixes the regression
```
Above, I'm using `index` as the column which is being indexed and sorted (i.e., I'm creating an index for it and reusing it in `expr`, and it's also the column acting as the sorting key). Results:

![image](https://github.com/user-attachments/assets/7fe5433e-219b-46ee-bf6b-cee2bed0c6e1)

I'll send a PR if the improvement/plot looks good to you as well!

**Comment by Anirban166** [comment]
I started revising it this week. Looking at the initial post by Jan made things clear as I had to use `forderv` and then set the `datatable.forder.auto.index` option to cache the index initially created by the first call to it.

Here is my current version:
```r
# Fixed in: https://github.com/Rdatatable/data.table/pull/4386
"forder improved in #4386" = atime::atime_test(
  N = 10^seq(3, 8), # 1e9 exceeds the runner's memory (process gets killed)
  setup = {
    options(datatable.forder.auto.index = TRUE, datatable.forder.reuse.sorting = TRUE)
    dt <- data.table(index = sample(N), values = sample(N))
    data.table:::forderv(dt, "index") # First ordering call to initialize caching
  },
  expr = {
    data.table:::forderv(dt, "index", retGrp = FALSE) # Reuse the cached index (no group information required)
    data.table:::forderv(dt, "index", retGrp = TRUE) # Reuse the index but compute group info.
  },
  Slow = "c152ced0e5799acee1589910c69c1a2c6586b95d", # Parent of the merge commit of the PR (https://github.com/Rdatatable/data.table/pull/4386/commits) that fixes the regression
  Fast = "1a84514f6d20ff1f9cc614ea9b92ccdee5541506") # Merge commit of the PR (https://github.com/Rdatatable/data.table/pull/4386/commits) that fixes the regression
```
Above, I'm using `index` as the column which is being indexed and sorted (i.e., I'm creating an index for it and reusing it in `expr`, and it's also the column acting as the sorting key). Results:

![image](https://github.com/user-attachments/assets/7fe5433e-219b-46ee-bf6b-cee2bed0c6e1)

I'll send a PR if the improvement/plot looks good to you as well!

**Comment by tdhock** [comment]
yes this looks good, please send a PR, thanks
