### ISSUE TITLE
CI complains about -Wvla flag

### ISSUE THREAD

**Issue by ben-schwen** [Rdatatable/data.table#6326]
CI is now complaining about these flags in:
- lin-dev-clang-cran
- lin-dev-gcc-strict-cran
- lin-rel-cran

```
Compilation used the following non-portable flag(s):
  ‘-Wvla’
```

_Originally posted by @ben-schwen in https://github.com/Rdatatable/data.table/issues/6274#issuecomment-2256785586_

**Comment by MichaelChirico** [comment]
Could you link the exact failure? Is that `R CMD check` complaining?

**Comment by ben-schwen** [comment]
Yes it is in `R CMD check`

https://gitlab.com/Rdatatable/data.table/-/jobs/7447310770#L107
https://gitlab.com/Rdatatable/data.table/-/jobs/7447310761#L107
https://gitlab.com/Rdatatable/data.table/-/jobs/7447310746#L100

**Comment by MichaelChirico** [comment]
I think we can suppress this in our CI with `_R_CHECK_COMPILATION_FLAGS_KNOWN_="-Wvla"`:

https://github.com/r-devel/r-svn/blob/83873fe7c1e3e23ef1ff4a986954bf1c8f01ce1d/src/library/tools/R/check.R#L3739C39-L3739C72
