### ISSUE TITLE
feature request: sql-like views

### ISSUE THREAD

**Issue by torbjorn** [Rdatatable/data.table#6359]
I went a bit forth and back about this.

Would it be feasible to implement something like sql's views as data.table objects?

R being a programming language (and functions even being first class citizens), you could just write your own functions instead, combining data or doing whatever. But perhaps having abstract data.table objects continously updated from content in other related data.table objects still could have merrit?

**Comment by MichaelChirico** [comment]
I'm not quite sure what precisely is being requested here, but from what I understand it is well outside the scope of something {data.table} _per se_ would do. If you write a package to support this relying on data.table and there is some associated feature request to better support that, feel free to re-open.

See also our GOVERNANCE doc which tries to delineate what's in/out of scope for the pacakge itself:
