### ISSUE TITLE
How to solve this issue from .() function 

### ISSUE THREAD

**Issue by Longfei2** [Rdatatable/data.table#6365]
When I develop an R function in R package , I encountered the following issue:
![image](https://github.com/user-attachments/assets/6bbb2ed9-2b3a-4f13-bdb4-8611650ccce0)

Is there a solution to it?

**Comment by Longfei2** [comment]
Dear author @TysonStanley,
`data.table` is really an excellent package, but I can't be familiar with its grammer. Could you please see this error?

**Comment by MichaelChirico** [comment]
See https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html
