### ISSUE TITLE
CODEOWNERS has DOS line endings

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#6369]
But it looks like most other files have unix line endings, at least in my clone on ubuntu. Does anybody else notice that?
![image](https://github.com/user-attachments/assets/de0f7774-14b7-4f90-9891-32185966376f)
Notice above (DOS) in mode line bottom left CODEOWNERS buffer, but not other 3 buffers.

I can see the line ending in git diff:
```
(base) tdhock@tdhock-MacBook:~/R/data.table[CODEOWNERS-translation-teams*]$ git diff
diff --git a/CODEOWNERS b/CODEOWNERS
index 61277276..9a360821 100644
--- a/CODEOWNERS
+++ b/CODEOWNERS
@@ -40,6 +40,9 @@
 /po/ @michaelchirico
 /R/translation.R @michaelchirico
 /src/po.h @michaelchirico
+po/*zh_CN.po @Rdatatable/chinese^M
+po/*pt_BR.po @Rdatatable/brazil^M
+po/*es.po @Rdatatable/spanish^M
 
 # printing
 /R/print.data.table.R @michaelchirico
```

**Comment by rikivillalba** [comment]
Yes 🤷
![image](https://github.com/user-attachments/assets/17a665ff-229a-49bb-aa50-6735ada6ea70)
