### ISSUE TITLE
Translating "tl of class is marked"

### ISSUE THREAD

**Issue by aitap** [Rdatatable/data.table#6374]
What does it mean that "tl of class is marked"? Here's the context:

https://github.com/Rdatatable/data.table/blob/6cee825fa1b05a8ccbf674a5ec5659559d674457/src/assign.c#L264-L265

Here, `dt` is the data.table object and `tl` is its `TRUELENGTH(dt)`. At this point in the code, `dt` must be a `data.table` object because it has a non-empty `class` attribute and a valid `.internal.selfref` attribute, but something's wrong with the `TRUELENGTH`. Is the intended meaning "the object you gave me is marked as a `data.table`, but an invariant of that class is violated"?

Not sure whether to tag the translation teams yet. I've tried to infer some more meaning from `po/{es,pt_BR}.po`, but didn't succeed.

**Comment by rikivillalba** [comment]
Some relevant explanation of the issue is in the `truelength` reference. 
https://github.com/Rdatatable/data.table/blob/6cee825fa1b05a8ccbf674a5ec5659559d674457/man/truelength.Rd#L32

> truelength(x) returns the length of the vector allocated in memory. length(x) of those items are in use. Currently, it is just the list vector of column pointers that is over-allocated (i.e. truelength(DT)), not the column vectors themselves, which would in future allow fast row insert(). For tables loaded from disk however, truelength is 0 in R 2.14.0+ (and random in R <= 2.13.2), which is perhaps unexpected. data.table detects this state and over-allocates the loaded data.table when the next column addition occurs. All other operations on data.table (such as fast grouping and joins) do not need truelength.

For these apparently very internals-specific issues I often chose to not to add additional meaning since it was not te attempt of the authors of the original message (unless idiomatic explanation is needed, like in CoW - Copy on Write).

**Comment by aitap** [comment]
This provides useful context, thanks. Still don't entirely understand why "tl of class" and not "tl of dt" and in which sense it's "marked". Maybe we'll keep the original text in brackets to make it easier to report internal errors (should they happen again).

**Comment by MichaelChirico** [comment]
I agree not to spend much effort on translating -- long-standing #4306 will unmark highly internal strings from translation to save the effort.

There's some more relevant comment in the original commit message: https://github.com/Rdatatable/data.table/commit/c4b1186a9d81391c5893903a810872eca49e535f#diff-22b103646a1efab9bbfc374791ccfc3fd1422eefc48918a3e126fc2f30d1f572

**Comment by aitap** [comment]
Thank you! I think I know what to do now.
