### ISSUE TITLE
[R-Forge #2028] Add option "datatable.IKnowHowToBenchmark"

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#638]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2028&group_id=240&atid=978)

By default FALSE

If FALSE and the caller of [.data.table is a for() loop and there's a system.time() above that in the stack,  then issue this warning :

Beware of finding significant differences of insignificant times. Beware of benchmark(,times=100) and microbenchmark(,times=1000). Only useful if the real task really is to loop many independent calls to [.data.table, otherwise you just time overhead and data.table is not designed to be used like that. Time a SINGLE call on LARGE data, not 1000 runs on tiny data. See this link, and this link.  To turn off this warning please put this in your ~/.Rprofile:  options(datatable.IKnowHowToBenchmark=TRUE).

**Comment by jangorecki** [comment]
maybe put it to FAQ instead? much simple and cheaper to maintain.

**Comment by MichaelChirico** [comment]
Agree with Jan.
