### ISSUE TITLE
Can't save patchwork object in a list column in data.table when group

### ISSUE THREAD

**Issue by person-c** [Rdatatable/data.table#6395]
see #5685

Are there any ways to walk around this?

```r
r$> mtDT <- setDT(copy(mtcars))

    mtDT[, .(plot = list(ggplot(data = .SD) + geom_point(aes(x=wt, y=mpg)))), by=.(carb,am)][,
    .(list(patchwork::wrap_plots(plot))), by=am]
Error in `X[[i]]`:
! Index out of bounds
Run `rlang::last_trace()` to see where the error occurred.

r$> rlang::last_trace(drop = FALSE)
<error/rlang_error>
Error in `X[[i]]`:
! Index out of bounds
---
Backtrace:
     x
  1. +-...[]
  2. \-data.table:::`[.data.table`(...)
  3.   \-data.table (local) runlock(ans)
  4.     \-base::lapply(x, runlock, current_depth = current_depth + 1L)
  5.       \-data.table (local) FUN(X[[i]], ...)
  6.         \-base::lapply(x, runlock, current_depth = current_depth + 1L)
  7.           \-data.table (local) FUN(X[[i]], ...)
  8.             \-base::lapply(x, runlock, current_depth = current_depth + 1L)
  9.               +-X[[i]]
 10.               \-patchwork:::`[[.patchwork`(X, i)
 11.                 \-cli::cli_abort("Index out of bounds")
 12.                   \-rlang::abort(...)
```

**Comment by rikivillalba** [comment]
It appears to be a conflict with 'patchwork'::: `[[` and data.table.
`data.table` look at x[[1]] perhaps to print something.
Custom `[[` on "patchwork" [indexes](https://github.com/thomasp85/patchwork/blob/3e549b42a37b1e5063ae4a2d3dc1519a36ef4a62/R/plot_patchwork.R#L71) on the list `x$patches$plots` and throws error if the list is empty. For me that is not expected to happen and might be a patchwork bug (as i think `[[` is not expected to throw an error at least in base R).

A workaround: unclass then reclass
`dt <- mtDT[, .(plot = list(ggplot(data = .SD) + geom_point(aes(x=wt, y=mpg)))), 
     by=.(carb,am)][,.(wp = list(unclass(patchwork::wrap_plots(plot)))), by=.(am)]

dt[ , wp := list(setattr(wp[[1]], "class", c("patchwork", "gg", "ggplot")))]
`

Then: if you run 
`dt[,wp][[1]]`
The plot is displayed

But if you run ... 
`dt[,wp[[1]]]`
> Error in `X[[i]]`:
! Index out of bounds
Run `rlang::last_trace()` to see where the error occurred.

If you agree then fill a bug in https://github.com/thomasp85/patchwork.

**Comment by person-c** [comment]
Thanks, I will.

**Comment by thomasp85** [comment]
`[[` certainly throws an out of bound error in base R (e.g. try running `list()[[1]]`)

The issue revolves around the implementation of `lapply()` and friends which do not seem to honor the dispatching for `[[` and `length()`. I have yet to figure out a way around this but in my opinion it is a bug/constraint of base R
