### ISSUE TITLE
confusion about row name

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#6396]
https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html
According to this vignette, data.table doesn’t set or use row names, ever. Why the code below works?

```
require(data.table)
x <- data.table(col1 = rnorm(5))
rownames(x)
rownames(x) <- c("6", "7", "8", "9", "10")
rownames(x)
```

**Comment by TysonStanley** [comment]
You can force row names onto any data.frame adjacent object (including tibbles although it gives you a warning) as far as I know. `data.table` won't use those row names and it doesn't print them either and they'll be forgotten after any data.table operation (e.g., `rownames(x[col1 < 0])`). Under the hood there are "row names" but they are just the row number. When you force different names it will be saved as an attribute until you perform an operation then it forgets it.

```r
require(data.table)
x <- data.table(col1 = rnorm(5))
rownames(x) <- c("6", "7", "8", "9", "10")
attributes(x)
attributes(x[col1 < 0])
```

**Comment by TysonStanley** [comment]
As such, this does look like it matches expectation so I'll close but if there is something about this behavior that creates unexpected results, please reopen with an example of that.

**Comment by MichaelChirico** [comment]
That's right, thanks Tyson. Adding:

> data.table doesn’t set or use row names, ever.

That's right. In your example, _you_ set & used the row names, not data.table. Setting the row.names attribute is IINM required for compatibility with data.frame, but data.table ignores this -- you can't expect the attribute to be preserved or used.
