### ISSUE TITLE
filter by group 

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#6397]
This could be a bug. My understanding is that x1 and x2 should be identical. 

```
require(data.table)
x <- data.table(col1 = sample(letters, size = 1000, replace = TRUE), col2 = rnorm(1000))
x[, col2_med := median(col2), by = col1]
x1 <- x[col2 <= col2_med]
x2 <- x[col2 <= median(col2), .SD, by = col1]
nrow(x1) == nrow(x2)
```

**Comment by MichaelChirico** [comment]
I guess you want #788. `i` evaluates before `by`; the global median is calculated but it looks like you want to filter by group median.

**Comment by waynelapierre** [comment]
If I use the order function in i, is it still evaluated before by?

**Comment by MichaelChirico** [comment]
yes, `i` is always evaluated first

**Comment by waynelapierre** [comment]
This seems different from SQL, where order by is evaluated much later than where. I am still confused about this. The code below seems to suggest that the order function is evaluated after keyby. Any clarification?

```
require(data.table)
x <- data.table(col1 = sample(letters, size = 1e3, replace = TRUE), col2 = rnorm(1e3))
x1 <- x[order(col2), .SD[1], keyby = col1]
x2 <- x[, .(col2 = min(col2)), keyby = col1]
all.equal(x1, x2)

```

**Comment by MichaelChirico** [comment]
keyby is doing the ordering.

aggregation functions in `i` are perfectly valid; not only is this generally very useful, but also it would be impossible to determine which parts of i do/do not aggregate.

**Comment by waynelapierre** [comment]
Is it possible to print a warning message when using aggregation functions in i when a by clause is also used?

**Comment by MichaelChirico** [comment]
I think that's neither desirable nor possible.
