### ISSUE TITLE
[R-Forge #2002] Test @<- in R3 with data.table

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#640]
Submitted by: Damian Betebenner; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2002&group_id=240&atid=978)

Currently, assignment by reference, :=, isn't supported in slots of S4 classes.

Request is to allow such assignment and to not have the package return a warning
that a copy is being made as all S4 classes, when instantiated, seem to be done so with copying.

**Comment by MichaelChirico** [comment]
S4 support for data.table is pretty limited; interested users are encouraged to explore implementation & open new issues, but for now I'm closing as out-of-scope.
