### ISSUE TITLE
data.table logo not fully vectorized - poor reproduction quality

### ISSUE THREAD

**Issue by jmrung** [Rdatatable/data.table#6402]
The data.table logo appears pixelated in areas and, depending on the format viewed, some cosmetic "blemishes" are present (e.g., vertical lines between shapes that make up the brackets/table legs).

On inspection of the .svg from the .graphics directory it appears that a raster image is embedded in the file, which is used for the lines of the seal. This results in difficulties rescaling the image without loss of quality, and the embedded image itself is not high quality. This explains the apparent pixelation. 

![datatable_embeddedimg](https://github.com/user-attachments/assets/dff39571-0ba8-43b0-a9d9-baee25550ceb)

I have created a fully vectorized version using InkScape that also addresses some of the disconnected shapes. This image should be able to be submitted for things like sticker printing without potential for quality issues--at least on the end of the supplied image. I was nudged to do a PR by @TysonStanley, which I'll be submitting soon. If any changes to the new logo are needed I'll be happy to complete them. Let me know if I should include the updated logo here as well, or if in the PR itself suffices

Thanks!

**Comment by MichaelChirico** [comment]
Excellent! Related: #6222

**Comment by rikivillalba** [comment]
Some improvement on the geometric shapes (@jmrung please compare)
![rdatatable](https://github.com/user-attachments/assets/fa783d62-94c9-492f-921f-d8997f3330c0)

**Comment by jmrung** [comment]
Looks great, @rikivillalba . Are you able to replace the version I have in the pending PR? (New to doing those)
