### ISSUE TITLE
Please roll version to 1.16.99

### ISSUE THREAD

**Issue by eddelbuettel** [Rdatatable/data.table#6416]
I sometimes / frequently build local versions (where I mau re-export `DT`) and prefer for those build to _not_ be overwritten by `update.packages()` but currently the CRAN version is higher than your development version.  Obviously I can do so locally too but as your build may also go to r-universe etc an incrementing of the version seems appropriate.

```
$ git pull --all
Fetching origin
Fetching parentrepo
Already up to date.
$ git merge parentrepo/master
Already up to date.
$ grep Version DESCRIPTION 
Version: 1.15.99
$ 
```

**Comment by MichaelChirico** [comment]
Thanks for flagging & your patience as we grow into the release process :)
