### ISSUE TITLE
[R-Forge #1974] Update wiki for j=lapply(.SD,...) speedup in v1.8.1. Allow .SDcols to accept unquoted names.

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#642]
Submitted by: Yike Lu; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1974&group_id=240&atid=978)

See Dos/Don'ts number 1:

http://rwiki.sciviews.org/doku.php?id=packages:cran:data.table

Essentially, it would be nice for ans2 to be the same as ans1 without colnames(ans2)=colnames(ans1)

**Comment by jaapwalhout** [comment]
I think it would be consistent behavior if `.SDcols` also accepts lists as follows:

    DT[, lapply(.SD, function), by = .(id, group), .SDcols = .(a, b, c)]

Related to [#1257](https://github.com/Rdatatable/data.table/issues/1257)

**Comment by DavidArenburg** [comment]
I agree with @jaapwalhout, never noticed this inconsistency before.

**Comment by franknarf1** [comment]
Re `.SDcols=` accepting unquoted names, if the extension is general enough, maybe it could also be used in other places where `cols=` appear, like `na.omit(x, cols = DC3:DC9)` from SO: https://stackoverflow.com/q/51385594/

**Comment by MichaelChirico** [comment]
I think this is out-of-scope, maintainers don't want to add more NSE to `.SDcols`, though it could support more other features.
