### ISSUE TITLE
Run cc() on windows

### ISSUE THREAD

**Issue by rikivillalba** [Rdatatable/data.table#6423]
I was able to run `cc()` on windows under MinGW after some modifications.
Most important, -c99 compliance is an issue because with -c99 the macro WIN32 is not defined (only _WIN32), and then fread.c and others do not guard against including <sys/mman.h>, which is not provided by MinGW.
 
Previous related: #4189

diff:
https://github.com/Rdatatable/data.table/compare/master...rikivillalba:data.table:dev_cc_R_win32

**Comment by tdhock** [comment]
wow nice hack!
this should affect anybody on windows, right? 
I would suggest submitting a PR.

> I was able to run cc() on windows under MinGW after some modifications.

is your MinGW same as rtools?

**Comment by rikivillalba** [comment]
Yes, I'm using rtools.
