### ISSUE TITLE
[R-Forge #1965] Add stringsAsFactors to data.table()

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#643]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1965&group_id=240&atid=978)

As discussed on list, default FALSE, default option: "datatable.stringsAsFactors".

**Comment by jangorecki** [comment]
This appears to be highly related to #1446 for which I've made PR today.
Instead of handling character to factors I've just made a warning which tells this arg is not supported.
