### ISSUE TITLE
v1.6.0 reported on CRAN news?

### ISSUE THREAD

**Issue by r2evans** [Rdatatable/data.table#6443]
I don't know how better to identify this typo, I can't find it in the repo files nor commits, but it's on CRAN:

https://cran.r-project.org/web/packages/data.table/news/news.html

![image](https://github.com/user-attachments/assets/06f740e5-c14f-40a9-ad67-ee15705e044d)

It correctly links to the 1.16.0 milestone.

**Comment by TysonStanley** [comment]
It's the correct link but it was a typo in the release itself. Unfortunately there aren't any checks for that so I don't see it until it was live. It's been fixed in master and will be fixed in the next patch release.
