### ISSUE TITLE
Release data.table version 1.16.2

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6444]
We've picked up a number of issues we should handle in a patch release already.

I've begun branch [`patch-1.16.2`](https://github.com/Rdatatable/data.table/tree/patch-1.16.2) to keep track of the changes.

So far it includes:

 - b73d4e91271c8ef845011a5039bf4ed9e806cf89
 - b9cab715857b31294389b6b6125cdc9ab6671e29
 - 2b7d3da4c6f0828a1d1664c537caae8ca308d939
 - fc9b328c99f29b99c03e3630885a85ce503f9385
 - 18f4ab610a0124eb3b8aa8162117944ad36c4e38
 - eaa7cd35193c93a2f9b5a69df26383089165ebbe
 - Typo fix of 1.6.0 in NEWS

**Comment by tdhock** [comment]
great thanks!
according to https://github.com/Rdatatable/data.table/blob/master/GOVERNANCE.md#version-numbering "patch/hotfix development should occur on GitHub as z=odd (1.15.1) and release to CRAN as z=even (1.15.2)." but I see 1.15.2 in https://github.com/Rdatatable/data.table/blob/patch-1.16.2/DESCRIPTION so could you please change to 1.15.1?

**Comment by r2evans** [comment]
May I suggest/request that https://github.com/Rdatatable/data.table/pull/6442 be included? That bug is a show-stopper for just about anybody using `options(datatable.prettyprint.char=)`. (I apologize if this comment is out of line.)

**Comment by MichaelChirico** [comment]
> May I suggest/request that #6442 be included? That bug is a show-stopper for just about anybody using `options(datatable.prettyprint.char=)`. (I apologize if this comment is out of line.)

yep it's in the milestone already:

https://github.com/Rdatatable/data.table/milestone/35

**Comment by TysonStanley** [comment]
@MichaelChirico great! Will get this submitted this week.

**Comment by TysonStanley** [comment]
Thanks, been traveling so working on this now. Did most of the checks, which are passing at this point, but I'm still replicating the `NOTE` that we see on CRAN too:

```
    Running ‘knitr.R’ [1s/1s]
    Comparing ‘knitr.Rout’ to ‘knitr.Rout.save’ ...28,38d27
  < 
  < ```
  < ##        x     y     z
  < ##    <int> <int> <int>
  < ## 1:     1     4     7
  < ## 2:     2     5     8
  < ## 3:     3     6     9
  < ```
  < 
  < ``` r
  52,62d40
  < ```
  < 
  < ```
  < ##        x     y     z     a
  < ##    <int> <int> <int> <int>
  < ## 1:     1     4    10     1
  < ## 2:     2     5    11     1
  < ## 3:     3     6    12     1
  ```

**Comment by TysonStanley** [comment]
Looks like the difference is that `DT[, z := 7:9]` is printing in the `knitr` output.

```
  < ##        x     y     z
  < ##    <int> <int> <int>
  < ## 1:     1     4     7
  < ## 2:     2     5     8
  < ## 3:     3     6     9
```

**Comment by MichaelChirico** [comment]
Yea, that shouldn't happen 🙈

**Comment by TysonStanley** [comment]
Not sure why it's not showing up in CI checks at all. It's a note on Linux and windows on CRAN and it showed up on MacOS for me here.

**Comment by tanho63** [comment]
Hi, just wondering if there was an update on expected timeline for release - have been eagerly awaiting Rdatatable/data.table#6452 to be released on CRAN as that intermittent segfault has been annoying to work around in our prod systems (and corp security frowns on github installs)

**Comment by r2evans** [comment]
@tanho63 I suggest you do what I did: downgrade. It's not awesome or desirable, but it's a far-more-stable approach than adding workarounds in production systems.

(I'm not a dev here, I'm also eagerly awaiting 1.16.2. I deliberately tested our prod systems against 1.16.0, found some bugs, and am holding back until our tests come back clean.)

**Comment by MichaelChirico** [comment]
@tanho63 we're having a bit of trouble with #6509 because it only shows up on some systems and happens non-interactively so the usual debugging toolkit is unavailable. 

if you want to expedite release please try your hand at fixing 😁

**Comment by tdhock** [comment]
#6509 should be fixed now so please try a patch release @TysonStanley

**Comment by TysonStanley** [comment]
Great, will submit later today/tomorrow

**Comment by TysonStanley** [comment]
Patch was just accepted but I'm away from my computer until tonight. Will update the branch and release then.
