### ISSUE TITLE
What is the more idiomatic way to select columns in a character vector: `..` or `.SDcols`?

### ISSUE THREAD

**Issue by jpanfil** [Rdatatable/data.table#6461]
What is the preferred or recommended style for selecting columns from a `data.table` using a character vector? `..` or `.SDcols`:

```
library(data.table)

df <- data.table(x = c(1, 2), y = c("asdf", "sd"), z = c("i love", "data.table"))
select_cols <- c("x", "z")

df[ , ..select_cols]
df[ , .SD, .SDcols = select_cols]

# both return
       x          z
   <num>     <char>
1:     1     i love
2:     2 data.table
```

Both return the exact same results. Is one of these methods preferred over the other? Obviously `..` is less typing, but I am wondering if there's other considerations that might make one way superior to the other.

As always, thank you so much!

(Above uses R 4.4.1 and data.table 1.15.4)

**Comment by MichaelChirico** [comment]
I think both are supported just fine. each has its advantages in different situations.

I think the latter approach is more suited to "formal" programming -- the former will generate R CMD check notes in packages, e.g.

I'll close since there's no request or report here.
