### ISSUE TITLE
[R-Forge #1751] Remove use of POSIXlt in IDateTime, and add yearquarter()

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#649]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1751&group_id=240&atid=978)

The coercion to 40 byte POSIXlt will be slowing down month() for example.

**Comment by jangorecki** [comment]
Closed by https://github.com/Rdatatable/data.table/pull/5300
