### ISSUE TITLE
New internal class1 helper

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6522]
We use `function(x) class(x)[1]` a few times, including one new time in #5973:

https://github.com/Rdatatable/data.table/blob/a673460dd83fa499edee71d7eee7fa1f1b5f3fa6/R/print.data.table.R#L106

https://github.com/Rdatatable/data.table/blob/a673460dd83fa499edee71d7eee7fa1f1b5f3fa6/R/test.data.table.R#L293

https://github.com/Rdatatable/data.table/pull/5973/files#diff-8bde12f7775c5541aa8cce5665991eb0f9e0c1cf94ad222a7d6889fcc9101909R79

Better to use a helper to wrap this, e.g. named `class1`.

<details>

Found with {lintr}:

```r
l=lintr::make_linter_from_xpath("//FUNCTION/following-sibling::expr[OP-LEFT-BRACKET]/expr/expr/SYMBOL_FUNCTION_CALL[text() = 'class']", "xxx")
lintr::lint_dir("R", linters=l())
```

</details>

**Comment by jangorecki** [comment]
Or classes1 so we can put in vapply already, possibly adding cols art to subset columns

**Comment by MichaelChirico** [comment]
Good idea! I found other places that just use `class(x)[1L]`, so I added both as helpers: #6525.
