### ISSUE TITLE
[R-Forge #1670] Use NAMED in assign.c to suppress shallow copy warning from := in some cases

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#653]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1670&group_id=240&atid=978)

Linked to commit 411 in v1.7.3 and bug #264

**Comment by jangorecki** [comment]
any idea which cases are the issue referring to?

**Comment by jangorecki** [comment]
closing as it is not clear what the issue asks about
