### ISSUE TITLE
GLCI: failing to install packages in local CRAN mirror (test-win-dev)

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6547]
As seen here:

https://gitlab.com/Rdatatable/data.table/-/jobs/7943818865

```
also installing the dependencies 'R.oo', 'R.methodsS3', 'evaluate', 'highr', 'xfun', 'commonmark'
Error in read.dcf(file = tmpf) : cannot open the connection
Calls: install.packages -> available.packages -> read.dcf
In addition: Warning message:
In read.dcf(file = tmpf) :
  cannot open compressed file 'C:/GitLab-Runner/builds/Rdatatable/data.table/bus/mirror-packages/cran/bin/windows/contrib/4.5/PACKAGES', probable reason 'No such file or directory'
```

Pretty cryptic but it looks like the local CRAN mirror is not set up correctly.

cc @jangorecki

**Comment by ben-schwen** [comment]
The problem is the version mismatch that we have. We are setting `R_DEV_VERSION:  "4.4"` but Windows dev is '4.5'.

Will open a PR for that when I'm back at my computer (next weekend)

**Comment by MichaelChirico** [comment]
Ah, that issue again. OK, easy enough, but it might be nice to have that populate programmatically, WDYT about

```shell
curl -s https://svn.r-project.org/R/trunk/VERSION | awk -F'.' '{print $1 "." $2}'
``

I don't see as trivial a way to get the `r-oldrel` / `r-release` versions updated though, perhaps we should just use the {rversions} package instead:

https://cran.r-project.org/web/packages/rversions/index.html

**Comment by ben-schwen** [comment]
Seems that you fixed this by #6550 

Unfortunately, `rversions` provides only versions for R, but we need versions for Rtools too.
So ultimately, we should probably use https://api.r-hub.io/rversions

**Comment by MichaelChirico** [comment]
Good point; asked https://github.com/r-hub/rversions/issues/38. It might be nice to use {rversions} as an abstraction layer vs. directly hitting that API.

**Comment by ben-schwen** [comment]
AFAIU GLCI documentation we cannot populate our global variables `R_REL_VERSION`, `R_REL_WIN_BIN` with a script
