### ISSUE TITLE
1.16.0 testunit fails

### ISSUE THREAD

**Issue by nunotexbsd** [Rdatatable/data.table#6559]
testunit from previous version 1.15.4 is OK.

```
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: amd64-portbld-freebsd15.0
Running under: FreeBSD 15amd64-main 15.0-CURRENT FreeBSD 15.0-CURRENT 1500023 amd64

Matrix products: default
LAPACK: /usr/local/lib/R/lib/libRlapack.so;  LAPACK version 3.12.0

locale:
[1] C.UTF-8/C.UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8

time zone: Europe/Lisbon
tzcode source: system (FreeBSD)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.4.1
```
```
<snip>
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'S4.R'
  Running 'autoprint.R'
  Comparing 'autoprint.Rout' to 'autoprint.Rout.save' ... OK
  Running 'froll.R'
  Running 'knitr.R'
  Comparing 'knitr.Rout' to 'knitr.Rout.save' ... OK
  Running 'main.R'
 ERROR
Running the tests in 'tests/main.R' failed.
Last 13 lines of output:
     0.000s ( 24%) Rereading 1 columns due to out-of-sample type exceptions
     0.000s        Total
  Column 1 <<A>> bumped from 'int32' to 'int64' due to <<123456789123456>> on row 114
            A           B
  "integer64"   "integer"
  Test 2266 produced 1 errors but expected 0
  Expected:
  Observed: no documentation of type 'a' and topic 'o' (or error in processing help)
  Error in eval(exprs[i], envir) : object 'tmp2' not found

  Mon Oct  7 12:28:45 2024  endian==little, sizeof(long double)==16, longdouble.digits==64, sizeof(pointer)==8, TZ==unset, Sys.timezone()=='Europe/Lisbon', Sys.getlocale()=='C', l10n_info()=='MBCS=FALSE; UTF-8=FALSE; Latin-1=FALSE; codeset=US-ASCII', getDTthreads()=='This installation of data.table has not been compiled with OpenMP support.; omp_get_num_procs()==1; R_DATATABLE_NUM_PROCS_PERCENT==unset (default 50); R_DATATABLE_NUM_THREADS==unset; R_DATATABLE_THROTTLE==unset (default 1024); omp_get_thread_limit()==1; omp_get_max_threads()==1; OMP_THREAD_LIMIT==unset; OMP_NUM_THREADS==unset; RestoreAfterFork==true; data.table is using 1 threads with throttle==1024. See ?setDTthreads.', .libPaths()=='/wrkdirs/usr/ports/devel/R-cran-data.table/work/data.table.Rcheck','/usr/local/lib/R/library', zlibVersion()==1.3.1 ZLIB_VERSION==1.3.1
  Error in test.data.table() :
    Failed in 20.2s elapsed (19.4s cpu) after test 2273.3 before the next test() call in /wrkdirs/usr/ports/devel/R-cran-data.table/work/data.table.Rcheck/data.table/tests/tests.Rraw.bz2
  Calls: test.data.table -> stopf -> raise_condition -> signal
  Execution halted
* checking package vignettes ... NOTE
Package has 'vignettes' subdirectory but apparently no vignettes.
Perhaps the 'VignetteBuilder' information is missing from the
DESCRIPTION file?
* DONE

Status: 1 ERROR, 1 WARNING, 3 NOTEs
See
  '/wrkdirs/usr/ports/devel/R-cran-data.table/work/data.table.Rcheck/00check.log'
for details.

*** Error code 1
```
Any clues?
Thanks

**Comment by ben-schwen** [comment]
Thanks for the report. Could you check whether the error still exists with the dev version? Updating to dev can be done with `data.table::update_dev_pkg()`

**Comment by MichaelChirico** [comment]
Based on this:

> Failed in 20.2s elapsed (19.4s cpu) after test 2273.3 before the next test() call in /wrkdirs/usr/ports/devel/R-cran-data.table/work/data.table.Rcheck/data.table/tests/tests.Rraw.bz2

I guess it's b73d4e91271c8ef845011a5039bf4ed9e806cf89

You _might_ be able to fix it without updating to dev {data.table} by installing {R.utils} and re-trying.

**Comment by nunotexbsd** [comment]
@ben-schwen 
```
> native_ano = iconv("a\U00F1o", "UTF-8", "")
str(native_ano)
.Internal(inspect(native_ano))
 chr "año"
@2160dad18d58 16 STRSXP g0c1 [REF(1)] (len=1, tl=0)
  @2160d9cc5270 09 CHARSXP g0c1 [REF(3),gp=0x28] [UTF8] [cached] "año"
```

**Comment by nunotexbsd** [comment]
@MichaelChirico 

I have added R.utils to test depends but error is same.
I will try devel and put results here.

BTW, I'm maintaining FreeBSD port: https://www.freshports.org/devel/R-cran-data.table/

**Comment by nunotexbsd** [comment]
Ok, I think I found the problem. OpenMP detection not working as in macports:
https://github.com/macports/macports-ports/blob/99af437d1f41eb15874f926020fdcf39356a7ab2/R/R-data.table/Portfile#L23

And only now I did found it on my build logs:

```
<...>
===>   Generating temporary packing list
* installing *source* package 'data.table' ...
** package 'data.table' successfully unpacked and MD5 sums checked
** using staged installation
zlib 1.3.1 is available ok
***
*** OpenMP not supported! data.table uses OpenMP to automatically
***   parallelize operations like sorting, grouping, file reading, etc.
*** For details on how to install the necessary toolchains on your OS see:
***   https://github.com/Rdatatable/data.table/wiki/Installation
*** Continuing installation without OpenMP support...
***
** libs
<...>
```
and included in above unittest log:
`getDTthreads()=='This installation of data.table has not been compiled with OpenMP support.`

I will try to enable OpenMP and check tests.

**Comment by nunotexbsd** [comment]
I will close this PR as problem is deeper that I thought. I will take car of OpenMP support first and the check further tests.

A quick patch shows that I can build package with OpenMP:

```diff
--- configure.orig      2024-10-08 08:42:43 UTC
+++ configure
@@ -144,7 +144,17 @@ detect_openmp () {

   fi # uname=Darwin

-  # No support for OpenMP available
+
+  if [ "$(uname)" = "FreeBSD" ]; then
+
+    export PKG_CFLAGS="${PKG_CFLAGS}"
+    export PKG_LIBS="${PKG_LIBS}"
+    export R_OPENMP_ENABLED=1
+    return
+
+  fi # uname=FreeBSD
+
+ # No support for OpenMP available
   export R_OPENMP_ENABLED=0
 }
```

But it needs better testing.

Thanks all for help.

**Comment by aitap** [comment]
>     locale:
>     [1] C.UTF-8/C.UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8

>     Test 2266 produced 1 errors but expected 0
>       Expected:
>       Observed: no documentation of type 'a' and topic 'o' (or error in processing help)

Is there a chance that your unit test environment is running in `LC_ALL=C` instead of `LC_ALL=C.UTF-8`? It looks like on FreeBSD with `LC_ALL=C` in action, `iconv("a\U00F1o", "UTF-8", "")` returns `"a?o"` (which gets parsed as a help request) instead of `NA`. `iconv()` just silently succeeds and returns `1` ("one character converted in a nonreversible way").

For a quick workaround, skip the test if `identical(native_ano, 'a?o')`. Not sure if R could handle this quirk of FreeBSD's `iconv()` implementation, but they perform incredible gymnastics to accomodate macOS `iconv()`.

**Comment by aitap** [comment]
> Can't find a way to skip this test.
> Any hints?

This is a bug, should be fixed by #6567. Does it help if you apply it locally?

**Comment by nunotexbsd** [comment]
> > Can't find a way to skip this test.
> > Any hints?
> 
> This is a bug, should be fixed by #6567. Does it help if you apply it locally?


I can confirm that it fixes test.
Thanks

**Comment by tdhock** [comment]
hi @nunotexbsd thanks for your detailed analysis.
if I understand correctly, there were two issues on freebsd.

the original was about iconv, which was fixed by #6567 so I wonder if this issue can be closed now?  


the other was about openmp, for which you proposed a fix https://github.com/Rdatatable/data.table/issues/6559#issuecomment-2407642567 if that is right then can you please submit a PR?

**Comment by tdhock** [comment]
related to other openmp pr https://github.com/Rdatatable/data.table/pull/6497

**Comment by nunotexbsd** [comment]
Hello @tdhock 

You can close https://github.com/Rdatatable/data.table/pull/6567 as it fixes problem.

Related to https://github.com/Rdatatable/data.table/issues/6559#issuecomment-2407642567, I will use a local patch for the time being to be sure that it is the better solution for configure phase and the I will open a PR with a patch.

Thanks
