### ISSUE TITLE
cedta() fails for a package orchestrating debugging

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6560]
Pretty involved generating this, but it did come up from real code :)

We have a package that instruments line-by-line debugging of an R script, so we get an arbitrary R script as input and launch `browser()` to allow stepping through its execution.

```r
# CREATE TEST PACKAGE
testPkg <- file.path(tempdir(), "testPkg")
dir.create(testPkg)
write.dcf(list(Package = "testPkg", Version = "0.0.1"), file.path(testPkg, "DESCRIPTION"))
dir.create(file.path(testPkg, "R"))
cat(file = file.path(testPkg, "R", "RUN.R"), "
RUN = function(f) {
  .DebuggedScript(f)()
}

.DebuggedScript <- function(r_script) {
  script_exprs <- parse(r_script, keep.source = TRUE)
  RunScript <- function() {
    browser()
  }
  for (ii in seq_along(script_exprs)) {
    body(RunScript)[[ii + 2L]] <- script_exprs[[ii]]
  }
  return(RunScript)
}
")
writeLines("export(RUN)", file.path(testPkg, "NAMESPACE"))
system(paste("R CMD INSTALL", testPkg))

cat(file = tmp<-tempfile(), "
library(data.table)
DT = data.table(a=1)
DT[a == 1]
")

library(testPkg)
RUN(tmp)
```

That attaches the debugger, `n` 4 times makes the error:

```
Error in .DebuggedScript(f)() : object 'a' not found
```

debugging `cedta()` doesn't really give us much to go on:

```
[[1]]
RUN(tmp)

[[2]]
.DebuggedScript(f)()

[[3]]
DT[a == 1]

[[4]]
`[.data.table`(DT, a == 1)

[[5]]
cedta()
```

**Comment by MichaelChirico** [comment]
I think the answer here is to extend `cedta.pkgEvalsUserCode`. Don't think there's anything else to do. Pretty hard for the user to debug though!

**Comment by MichaelChirico** [comment]
Hmm this is even more complicated, since `cedta.pkgEvalsUserCode` expects `eval()` somewhere in the stack. But the way I've written this is quieter -- there's no trace of `eval()` or `browser()` or anything.

Maybe `.datatable.aware` is the right approach...

**Comment by rikivillalba** [comment]
What if you create a local function in testpkg instead of call it directly?
```
RUN = function(f) {
  .DebuggedScript(function() f())()
}
```
I noted i.e. that `lapply(rmdFiles, knitr::knit)` fails by not cedta. Help of lappli give some warning about.
