### ISSUE TITLE
[R-Forge #1607] Add i. and x. prefixes

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#658]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1607&group_id=240&atid=978)

For self joins and rolling joins.
See post on 4 Oct 2011,  and previous thread somewhere : search for "i. x."

**Comment by jangorecki** [comment]
This was resolved by @arunsrinivasan in 620276b3fef4996d2c377257c1ec49c7be10d783
