### ISSUE TITLE
fread support for differing open and close quotes

### ISSUE THREAD

**Issue by MPagel** [Rdatatable/data.table#6614]
Please allow for paired-but-differing open and close quotes specified for fread.

For example `[` and `]`; `“` and `”`; `«` and `»`; `{` and `}`

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example); please be sure to set `verbose=TRUE` where possible!

csv (or rather log file) contains lines similar to:
`[2024-11-12 17:00:23,573 - ERROR - deidentification.py:311 - _make_single_token] input\input.csv, Line 3, XXX - E00000, Email must be a non-empty string`

I want the comma in the timestamp `17:00:23,573` to be interpreted as lacking a delimiter because it is within the square brackets 

suggested preferred syntax:
`fread("blah.log",quote=c("[","]"))`
alternate syntax
`fread("blah.log",openquote="[",closequote="]")`
 
related:
#1109, #1299

note that in the given example, the quotes do not encompass the entirety of what I consider to be the first field, as that also includes input\input.csv after the closing `]`

meanwhile, I can always glue together the first and second fields after read-in.
e.g.
```
dq <- fread("blah.log",header=FALSE,fill=8,sep=",")
dq[,V1:=paste0(V1,",",V2)][,V2:=NULL]

```
`#` `Output of sessionInfo()`
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 26100)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.16.2

loaded via a namespace (and not attached):
[1] compiler_4.3.3 tools_4.3.3

**Comment by tdhock** [comment]
I understand that your issue is that there is a comma that you would like to ignore in an unquoted "field" when reading data with fread like this:
```r
> text <- "[2024-11-12 17:00:23,573 - ERROR - deidentification.py:311 - _make_single_token] input.csv, Line 3, XXX - E00000, Email must be a non-empty string"
> data.table::fread(text=text,header=FALSE)
                     V1
                 <char>
1: [2024-11-12 17:00:23
                                                                      V2     V3
                                                                  <char> <char>
1: 573 - ERROR - deidentification.py:311 - _make_single_token] input.csv Line 3
             V4                               V5
         <char>                           <char>
1: XXX - E00000 Email must be a non-empty string
```
above is problematic because V1 and V2 are in different columns.

Your proposed fix can be simulated by replacing `[` and `]` with double quotes as below
```r
> (double.quotes <- gsub("[][]", '"', text))
[1] "\"2024-11-12 17:00:23,573 - ERROR - deidentification.py:311 - _make_single_token\" input.csv, Line 3, XXX - E00000, Email must be a non-empty string"
> data.table::fread(text=double.quotes,header=FALSE)
                                                                               V1
                                                                           <char>
1: 2024-11-12 17:00:23,573 - ERROR - deidentification.py:311 - _make_single_token
           V2     V3    V4     V5     V6      V7     V8     V9    V10    V11
       <char> <char> <num> <char> <char>  <char> <char> <char> <char> <char>
1: input.csv,   Line     3    XXX      - E00000,  Email   must     be      a
         V12    V13
      <char> <char>
1: non-empty string
```
so you could do a find and replace as above, maybe with `fread(cmd="cat your_file|sed 's/]/\"/'|sed 's/[/\"/'")`

or you could use regex to parse instead as below
```r
> (parsed.dt <- nc::capture_first_vec(
+ text,
+ "\\[",
+ in_square_brackets=".*?",
+ "\\] ",
+ csv=".*"))
                                                               in_square_brackets
                                                                           <char>
1: 2024-11-12 17:00:23,573 - ERROR - deidentification.py:311 - _make_single_token
                                                                 csv
                                                              <char>
1: input.csv, Line 3, XXX - E00000, Email must be a non-empty string
> data.table::fread(text=parsed.dt$csv,header=FALSE)
          V1     V2           V3                               V4
      <char> <char>       <char>                           <char>
1: input.csv Line 3 XXX - E00000 Email must be a non-empty string
```

**Comment by tdhock** [comment]
I don't believe it should be a priority for fread to support differing open and close quotes, because there are work-arounds.

**Comment by MPagel** [comment]
fair enough.  Coding for too many special cases would likely cause fread to not be as efficient as it is.

**Comment by MichaelChirico** [comment]
> Coding for too many special cases would likely cause fread to not be as efficient as it is.

I'm not totally clear this is true, but agree with Toby on not prioritizing this. Outside contributions welcome :)

**Comment by MPagel** [comment]
In the unlikely event that someone finds this issue thread while searching through closed posts, one possibility is using the `\p{Quote}` perl regular expression class. Extending the fread function to parse with REs may allow us to customize delimiters and quote characters to use either the standard classes or custom groupings.

the `\p{Quote}` character class would not include `[` or `]`, but a custom grouping (e.g. `[\\[\\]\\p{Quote}]` may allow for this.

**Comment by MichaelChirico** [comment]
As `quote=` is not implemented in R & this would add unknown dependencies of `fread()` routine on perl-regex-supporting libraries, it's unlikely the right way forward.

**Comment by tdhock** [comment]
Agree that we can't use regex inside of fread, but you could use regex outside of fread:
```r
> nc::capture_first_vec(text,"\\p{Ps}",in_square_brackets=".*?","\\p{Pe} ",csv=".*")[, fread(text=csv,header=FALSE), by=in_square_brackets]
                                                               in_square_brackets
                                                                           <char>
1: 2024-11-12 17:00:23,573 - ERROR - deidentification.py:311 - _make_single_token
          V1     V2           V3                               V4
      <char> <char>       <char>                           <char>
1: input.csv Line 3 XXX - E00000 Email must be a non-empty string
```
