### ISSUE TITLE
[R-Forge #1253] setkey could save attribute : largest group size

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#663]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1253&group_id=240&atid=978)

this would save dogroups the time of the vector scan needed to find out the size of the largest group needed for the .SD allocation

**Comment by arunsrinivasan** [comment]
Not a huge priority at the moment. Moving to 2.0.0

**Comment by jangorecki** [comment]
I would close it as won't fix, and keep setkey as simple as reorder and set `sorted` attribute.
Largest group is availble from `retGrp=T`, which is about to be default for index, once #4386.
It is easier to set index than key anyway, because setting key sacrifies the original order.
