### ISSUE TITLE
Set a minimum quantity of groups to print progress (2?)

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6668]
Running some very slow grouping operation that happens to be on a one-group table (occurring programmatically):

```r
library(data.table)
DT=data.table(a=1)
DT[, by=a, {Sys.sleep(5); 1}]
# Processed 1 groups out of 1. 100% done. Time elapsed: 5s. ETA: 0s.
#        a    V1
#    <num> <num>
# 1:     1     1
```

Doesn't seem very useful in this case. cc @joshhwuu

**Comment by joshhwuu** [comment]
Thanks for the ping, sounds like a reasonable request to me! I can take a look into this 😄
