### ISSUE TITLE
[R-Forge #1044] Posted example containing repeated cumsum.lag() and pmax(). Revisit.

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#667]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1044&group_id=240&atid=978)

This was posted by Johann Hibschman in May 2010 :

http://r.789695.n4.nabble.com/Access-to-local-variables-in-j-expressions-tp2315330p2315336.html

The example looks strange and can likely be done differently. It repeats unlist(tapply()) many times listed out, similiar repetition of cumsum.lag() and and pmax() too.  Tom answered at the time suggesting multicore. I didn't look at it at the time (on holiday) so it's just to revisit through the eyes of v1.5 and see if it generates a nice example for documentation, at least.

The thread contains a reference that only 2.5 times speedup was achieved.  That needs addressing if it turns out to be be poorly constructed code rather than data.table per se.  We are used to many more times than 2.5 speedup, especially with simple functions such as these it seems.

**Comment by jangorecki** [comment]
We need an example code. Will re-open if _Tom_ is somewhere around to provide one.
