### ISSUE TITLE
[R-Forge #1003] Revisit growVector

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#669]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1003&group_id=240&atid=978)

2 TODO comments in dogroups.c where growVector is called, for further improvement.

**Comment by MichaelChirico** [comment]
Unclear if these TODOs exist anymore (haven't checked), but if so they'll get a new issue later (_a la_ #678).
