### ISSUE TITLE
[R-Forge #1001] REPL print copy, and revisit [[.data.table

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#670]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1001&group_id=240&atid=978)

Currently removed. Reinstate with speedup to .Call directly and skip [[.data.frame.
Issue introduced now data.table inherits from data.frame.

**Comment by MichaelChirico** [comment]
Context here is lost. Closing.
