### ISSUE TITLE
[R-Forge #801] Review all if()s and ifelse()s.  Can they be removed or raised ?

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#673]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=801&group_id=240&atid=978)

Tom removed the version check, gettting an 18 times speedup in some tests.  It was nested far too deep.  Since it could well be the if() (i.e. branching) rather than necessarily the version check itself,  we should review all if()s and ifelse()s.

**Comment by mattdowle** [comment]
[#1598](https://github.com/Rdatatable/data.table/pull/1598) merged.

**Comment by MichaelChirico** [comment]
I guess "reviewing all `if`s" is a pretty daunting task at this point... shall we close this or perhaps make it more specific?
