### ISSUE TITLE
[R-Forge #748] Allow zeros (or any other value) to be used as fill rather than just NA

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#675]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=748&group_id=240&atid=978)

```R
data <- data.table(c(1:2,5:7), c(0.5,0.2,1,1.6,2), key="V1")
data
#      V1  V2
# [1,]  1 0.5
# [2,]  2 0.2
# [3,]  5 1.0
# [4,]  6 1.6
# [5,]  7 2.0

data[J(1:7), fill=0L]
#      V1  V2
# [1,]  1 0.5
# [2,]  2 0.2
# [3,]  3   0
# [4,]  4   0
# [5,]  5 1.0
# [6,]  6 1.6
# [7,]  7 2.0
```
Notice that `fill=0L` automatically changed `keep` to `TRUE`.

**Comment by jangorecki** [comment]
duplicate of #857 - would work after change `nomatch=0L` to `nomatch=NULL` for inner join.

**Comment by arunsrinivasan** [comment]
Dup indeed.
