### ISSUE TITLE
[R-Forge #415] Allow i to be a list of integer vector to invoke chained grouping

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#676]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=415&group_id=240&atid=978)

Currently joins results are flattened so the following doesn't work:

a[a.idx[J(dts),rownum], mean(v)]))

if a.idx[J(dts),rownum] returned a list of the rownum subsets corresponding to the group criteria in the i,  then a.idx[ would know how to group.

**Comment by jangorecki** [comment]
If anyone has a reproducible example for this request, please provide one.
