### ISSUE TITLE
[R-Forge #202] Allow one column to be a matrix [1=Lowest priority]

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#680]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=202&group_id=240&atid=978)

For example an n-column matrix could be 1 'column' in a data.table, subject to a i-column key. Print method would display as as an i+n data.table, but length(DT)==i+1.   Advantage would be the matrix stored contiguously in memory and would be able to run matrix expressions as the j e.g. DT["foo",A%*%B] if 2 matrices were stored in the data.table.

Alternative naming would be data.list or data.list.of.list where the top level is key'd by columns just like a data.table.

**Comment by MichaelChirico** [comment]
My take is if you want a matrix you should use a matrix. Accounting for `data.table` columns with dimensions will cause more headaches than benefits IMO
