### ISSUE TITLE
[R-Forge #2588] New warning needed when items on RHS of := are silently ignored

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#681]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2588&group_id=240&atid=5335)

As raised [here on SO](http://stackoverflow.com/a/15121703/403310).

**Comment by MichaelChirico** [comment]
The "unexpected" version in the So link now returns the "expected" results:

```
dt <- data.table(x=c(1:10))
setkey(dt, x)

k <- data.table(x=c(1:5,10), b=c(letters[1:5], "d"))
setkey(k, x)

dt[,b:=k[.BY, list(b)],by=x][]
        x      b
 1:     1      a
 2:     2      b
 3:     3      c
 4:     4      d
 5:     5      e
 6:     6   <NA>
 7:     7   <NA>
 8:     8   <NA>
 9:     9   <NA>
10:    10      d
```

**Comment by MichaelChirico** [comment]
I think current logic assumes you were trying to build `list` columns if you pass an over-sized list in RHS:

```
DT = data.table(a = 1:3)
DT[ , c := .(2, 3)]
```

> Error in `[.data.table`(DT, , `:=`(c, .(2, 3))) : 
  Supplied 2 items to be assigned to 3 items of column 'c'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.

```
DT[ , c('b', 'c') := .(rep(0, 3), rep(1, 3), rep(2, 3))]
```

> Error in `[.data.table`(DT, , `:=`(c("b", "c"), .(rep(0, 3), rep(1, 3),  : 
  Supplied 2 columns to be assigned 3 items. Please see NEWS for v1.12.2. Try adding/removing a list() or .() wrapper around the RHS.

So I guess this is covered by more recent updates.
