### ISSUE TITLE
[R-Forge #4882] data.table() to drop names on vector inputs

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#683]
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=4882&group_id=240&atid=5335)

As discussed [here](http://r.789695.n4.nabble.com/column-of-named-vectors-in-data-table-and-possible-bug-tp4674435p4675569.html).

**Comment by MichaelChirico** [comment]
This seems to have been closed (not sure when):

```
x <- c(1,1,1,2,2)
y <- 6:10
setattr(y, 'names', letters[1:5])
DT<- data.table(A = x, B = y)

DT$B
# [1]  6  7  8  9 10
```

**Comment by jangorecki** [comment]
yes
