### ISSUE TITLE
Feature request: fwrite for data.table

### ISSUE THREAD

**Issue by robbyjo** [Rdatatable/data.table#690]
It would be nice if we can have fwrite function as a complement of fread. Right now, we can only use R's standard write.csv or write.delim or write.table. For huge tables (> 200GB in size), these standard routines will blow the available memory away. We need a memory-efficient alternative version.

**Comment by mattdowle** [comment]
@robbyjo Just in case you didn't see the update on #580, fwrite is now available in dev.
