### ISSUE TITLE
Consistency in 'i' for integer and logical types

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#697]
Currently, there is one small inconsistency in row-subset using integer and logical types:

``` S
require(data.table)
DT <- data.table(x=1:2, y=c(TRUE, FALSE))
v1 = 1L
```

**`i` as integer:**

``` S
DT[1L]
#    x    y
#1: 1 TRUE
DT[x]
# Error in eval(expr, envir, enclos) : object 'x' not found 
# Corrected the output here.. Thanks to @eddi.
DT[v1]
#    x    y
#1: 1 TRUE
DT[(x)]
#    x     y
#1: 1  TRUE
#2: 2 FALSE
```

The same happens for `logical` type as well. 

The question is, can we get this indexing to work without the need for `(` for cases where `i` is a column in `DT` instead of throwing the error? 

**Edit:** Cleaned up noise and retained just the resolution.

**Comment by MichaelChirico** [comment]
On current master, this is the error:

> x is not found in calling scope and it is not a column of type logical. When the first argument inside DT[...] is a single symbol, data.table looks for it in calling scope.

For `y` we get:

`DT[y]`

> y is not found in calling scope but it is a column of type logical. If you wish to select rows where that column is TRUE, either wrap the symbol with '()' or use ==TRUE to be clearest to readers of your code.

So, it seems we could at least make the error message a bit more consistent:

> x is not found in calling scope but it is a column of type integer...
