### ISSUE TITLE
Document that join is by default right outer join

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#709]
Suggestion from @tucson : 
> I propose to update datatable-intro.pdf with a chapter [4. Join], and a Table of Content in the same doc. [4. Join] could explain that "data.table join is done as follows: [example]. DATA.TABLE JOIN IS A RIGHT OUTER JOIN BY DEFAULT. [4.1 Right outer join (default option)] [4.2 Left outer join] [4.3 Inner join] [4.4 Full outer join] Each paragraph giving a simple example.

Made as a comment here : 
http://stackoverflow.com/questions/12773822/why-does-xy-join-of-data-tables-not-allow-a-full-outer-join-or-a-left-join/12778902#comment36326349_12778902

**Comment by arunsrinivasan** [comment]
Done in ?data.table. Will reflect in vignette after, as this'll change to *inner join* soon enough.
