### ISSUE TITLE
Integration with databases

### ISSUE THREAD

**Issue by hgera000** [Rdatatable/data.table#726]
I couldn't find this information anywhere, but was interested to know if there are any plans for `data.table` to also integrate with databases such as `MySQL` (through `R`) to avoid calling extremely large datasets into memory. I believe `dplyr` has this functionality. Not sure what the hit to performance would be, however.

**Comment by b3nj1** [comment]
@arunsrinivasan I'd be interested in this feature. I have a large code base (4k lines) built around data.table (Thanks!!!). Currently, we use cvs's and fread (again, Thanks!!!), but some of our data sets are uncomfortably large, so this doesn't scale anymore. We'd love to be able to drop in a mysql database without re-writing large amounts of code.

Thanks,
Benjamin

**Comment by cronacronis** [comment]
See [SSDB project](https://github.com/ideawu/ssdb), which has Redis API and is based on LevelDB. Together with [RCppRedis](http://dirk.eddelbuettel.com/code/rcppredis.html) it might be a way to go. Current key limit is 120MB.

**Comment by jangorecki** [comment]
There are no plans for transparent integration to existing databases. I suggest to use DBI package which is battle-tested for that.
Still we do plan transparent integration with off-memory on-disk storage. Data stored in binary files will be able to serves some of the features that databases do, like processing data bigger than available memory, or sharing data between different sessions. Status of file-backed data.table can be tracked in #1336.

**Comment by daroczig** [comment]
Although it's probably not exactly the integration functionality you are looking for, but my `dbr` pkg at https://github.com/daroczig/dbr does something like this:

1. define your preferred data frame format as `data.table`:

```r
options('dbr.output_format' = 'data.table')
``` 

2. set up the connection params in a YAML file
3. query your database via `db_query`, eg

```r
db_query('select 42', db = 'foobar')
```

That will automatically return the results in `data.table`.
