### ISSUE TITLE
I didn't think get() copies, why is fun2()  slowest here?

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#727]
http://stackoverflow.com/a/24668479/403310

**Comment by MichaelChirico** [comment]
I think that without `.SDcols` `get` has to copy. So I'm not sure there's any fix to this besides supplying `.SDcols`... OK to close?

**Comment by jangorecki** [comment]
I think that solution proposed #4304 is a proper way to address this issue. It removes the burden of maintaining `get` optimisation. I think it is is reasonable to advise to use substitution rather than `get`, thus closing. SO should be updated when we will have it in master.
