### ISSUE TITLE
[R-Forge #5115] cannot extend data.table anymore

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#74]
Submitted by: Garrett See; Assigned to: Arun ; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5115&group_id=240&atid=975)

The following works with CRAN version 1.8.10 and worked in earlier versions of 1.8.11, but broke when updating to rev. 1040 (although I don't know what revision I was on before updating to this one, so it could have broken much sooner)
```
x <- as.data.table(BOD)
setattr(x, "class", c("myclass", class(x)))
x[, Time:=as.numeric(Time)]
# Error in `[.data.table`(x, , `:=`(Time, as.numeric(Time))) :
# Input is not a data.table. set() (and `:=`) can add columns by reference only
# on a data.table.
```

**Comment by mattdowle** [comment]
Came across this issue when I found isDatatable in assign.c was not covered.  The comment mentioned this issue. I searched tests.Rraw and found test 1146 thoroughly covers this issue.  So isDatatable can safely be removed.  Will do and link the commit to here.
