### ISSUE TITLE
setDT should have 'key' argument

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#749]
Currently after getting a `data.table` from `data.frame` with `setDT`, if we've to set key, then:

```R
setkey(setDT(dat), ...)
```

It'd be much more convenient to do:

```R
setDT(dat, key=c(...))
```

**Comment by MichaelChirico** [comment]
It seems this FR was duplicated by [#1121](https://github.com/Rdatatable/data.table/issues/1121) and has since been closed.
