### ISSUE TITLE
'by=deparse(substitute(.))' could be caught and dealt with.

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#752]
[This SO post](http://stackoverflow.com/q/20121188/559784) illustrates the problem quite nicely. `by=.` catches most common cases (and rightfully so). And it's rather unusual to use `deparse(substitute(.))` in `by`, when it allows character vectors.

Still, I can't see why we can't include this case as well.. Filed here just so we don't miss it.

**Comment by jangorecki** [comment]
In such a unusual case which doesn't come often (once in 5 years?) I think we can simply follow the error message:
```
Error in `[.data.table`(dt, , list(x = sum(x)), by = deparse(substitute(a))) : 
  'by' appears to evaluate to column names but isn't c() or key(). Use by=list(...) if you can. Otherwise, by=eval(deparse(substitute(a))) should work. This is for efficiency so data.table can detect which columns are needed. 
```
then wrapping ` deparse(substitute(a))` into `c()` solves the problem.
Same is required when providing a function call to `by` which is going to return character vector.
```r
f=function() "a"
data.table(a=1,b=2)[, .N, c(f())]
```
