### ISSUE TITLE
Inconsistent treatment of missing values by 'fread'

### ISSUE THREAD

**Issue by polmath** [Rdatatable/data.table#765]
I read a 2 column file with fread. Both columns are numeric, but one contains a NA, the other contains a NULL. I specify with the 'na.strings' argument that both NA and NULL should be understood as missing values. This is indeed what 'fread' does, but one column is taken as 'character' while the other is taken as 'numeric'; I would expect both columns to be recognized as 'numeric'. 

I have put a minimal reproducible example at the following address : https://gist.github.com/polmath/c6de9c64400efc0ca212 

Thank you. 
Pol

**Comment by arunsrinivasan** [comment]
Fixed in devel with https://github.com/Rdatatable/data.table/commit/226f337b607aa02579ce1ec456b00d17d93df486 and this PR https://github.com/Rdatatable/data.table/commit/6c302f55465e4adfdeb01d47d1f5015284d44742
