### ISSUE TITLE
Add a `copy` argument to `[`

### ISSUE THREAD

**Issue by brodieG** [Rdatatable/data.table#787]
This would allow mimicking of `transform` / `mutate` behavior:

``` r
dt.a <- data.table(a=1:3)
dt.b <- dt.a[, b:=5:7, cp=T]
```

`dt.b` is now a new object with two columns, whereas `dt.a` remains a one column `dt`.  While the reference nature of `data.table` is fantastic most of the times sometimes it can be a little annoying.

Simple work arounds exist so this is not high priority:

``` r
dt.a[][, b:=5:7]
```

Although maybe the ideal solution would be if `data.table` detects it is being used as part of an assignment, not to do the modification by reference (though that will likely break lots of existing code...).

**Comment by jangorecki** [comment]
@brodieG the feature which address the case ["read.only"](https://github.com/jangorecki/data.table/compare/read.only), not very efficient because it do `copy` even when you query data.table with no `:=`. Yet it would be possible to extended to investigate `j` and then decide if `copy` necessary.

**Comment by brodieG** [comment]
@jangorecki , would this become more efficient with a shallow copy that doesn't really copy stuff until it actually is modified?  I think that's an FR, right?

**Comment by jangorecki** [comment]
It would but not in the way how I've implemented it now. Using shallow copy would surely be (a more) correct way to implement such feature.
