### ISSUE TITLE
a better way to set the key in complicated one-liners

### ISSUE THREAD

**Issue by eantonya** [Rdatatable/data.table#794]
If one tries to set the key on an intermediate expression before continuing, the flow breaks down, as the setkey has to be in front and the whole thing becomes a mess. Here's a random example (that doesn't do anything, and can be done differently, but imagine more complex stuff instead, e.g. http://stackoverflow.com/a/25628423/817778) of what I have in mind:

```
dt = data.table(a = 1:6, b = 1:2)

setkey(dt[, a[1], by = b], V1)[, c := 2*V1]
```

For a short period of time someone pointed out (I forget who, sorry) that it can be done like so:

```
dt[, a[1], by = b][, setkey(.SD, V1)][, c := 2*V1]
```

which I actually thought was fairly neat, but then this stopped being an option after .SD bindings got locked down.

I think we need to either allow the above .SD expression or have another alternative that can be written/read in a similar manner, from left to right, without having to skip back to the beginning of the sentence.

**Comment by jangorecki** [comment]
you should still be able to use `setattr(setorderv(.SD,cols),"sorted",cols)`, but I'm not sure how safe it is.

**Comment by MichaelChirico** [comment]
It's not clear to me from the example why we need to set the key here.

I found myself doing the messy mid-line `setkey` much more before `on` was an option; is this still a necessary feature? I'm struggling to think of an example where it's necessary, maybe something like:

    setkey(dt[ , a[1], by = b], V1)[.(V1[1]), sum(a)]

Can't say I've ever needed something like that.

**Comment by eantonya** [comment]
Agreed, `on` solves the issue neatly. Closing.
