### ISSUE TITLE
Error in fread{data.table} when reading txt files

### ISSUE THREAD

**Issue by carlopacioni** [Rdatatable/data.table#801]
I'm trying to read a txt file using `fread{data.table)` but I get an error:

```R
# (Error in fread(filename, h = F, sep = ";", nrows = 81, skip = 168, verbose = T) : 
# ' ends field 1 on line 168 when detecting types: Iteration 27)
```
The file is available [here](https://www.dropbox.com/s/1ybznmh63qjfaij/test.txt?dl=0). The code is:

```R
filename="test.txt"
require(data.table)
tyr <- fread(filename, h=F, sep=";", nrows=81, skip=168, verbose=T)
```

I can read the file fine with:

```R
tyr <- fread(filename, h=F, sep=";", nrows=15, skip=168, verbose=T)
```

and I can read the file fine if I open it in a text editor (`Notepad++`), cut the first 167 lines, re-save it as plain txt and use:

```R
tyr <- fread(filename, h=F, sep=";", nrows=81, skip=1, verbose=T)
```

Lastly, I can read the file fine using the equivalent call with `read.table`. I don't understand what `fread` is looking in line 168 since I said to skip it. The file is a standard output file from a software and each data block is identically formatted, yet I can read the previous data block fine with:

```R
tyr <- fread(filename, h=F, sep=";", nrows=81, skip=86, verbose=T)
```
I'd appreciate any help in understanding what's going on.

Thanks, carlo

**Comment by arunsrinivasan** [comment]
Could you try this again with the development version? Seems to have been fixed as well.

**Comment by carlopacioni** [comment]
sure, I'll need a couple of day to get to this though as I'm out for meetings today and tomorrow and then out in the field until Monday night. I'll get back to you sometime early next week if that's OK.

Thanks,
carlo

**Comment by carlopacioni** [comment]
Hi Arun, 
sorry for the delay.
I have good news, it seems to be working OK with version 1.9.5!

I also tried with two other larger files which were causing me problems before, and they were read in just fine.

I think you can close this issue if you are happy with my testing!

Thanks!

**Comment by arunsrinivasan** [comment]
Great! Thanks for the feedback.

**Comment by carlopacioni** [comment]
no worries, thank you
