### ISSUE TITLE
DT[FALSE,v:=1]

### ISSUE THREAD

**Issue by matthieugomez** [Rdatatable/data.table#820]
There must have been a discussion about this but I can't find it :
````R
require(data.table)
DT <- data.table(id = 1:2)
DT[FALSE,v:=1]
````

  I expected `DT[FALSE,v:=1]`  to return a variable `v` which equals `NA`. but it does not create a variable. In my opinion, it makes it a little bit harder to use it in a program. For instance, the data.table code given in this [SO comment](http://stackoverflow.com/questions/25649056/create-lagged-variable-in-unbalanced-panel-data-in-r#comment40082154_25649056) would not work for lags 6 years ago.

**Comment by arunsrinivasan** [comment]
I am not so sure if we should change the existing behaviour here.

Consider `DT[ x > 5, col := val]` and there were no values in `x`

**Comment by arunsrinivasan** [comment]
Continued...

That is > 5.. We don't want to replace all values with NA... Just occurred to me.

**Comment by matthieugomez** [comment]
I agree, my point only talks about the case where the variable (v in my example, col in yours) is new

**Comment by arunsrinivasan** [comment]
Hm yes, for that case I think this makes sense. I just checked that base R has the same behaviour you describe.

```R
df = data.frame(x=1:5)
df$y[df$x > 5] = 1 # all NA
df$z[df$x > 2] = 1 # first two rows are NA
df$z[df$x > 5] = 1 # no change
```

**Comment by jangorecki** [comment]
Is there any open issue for that? both linked are closed but not resolved.

**Comment by jangorecki** [comment]
This is also fixed by latest Arun's [commit](https://github.com/Rdatatable/data.table/commit/ee7c24716348cc6b51f22b21377530d2df3ba9c7).
```r
library(data.table)
DT <- data.table(id = 1:2)
DT[FALSE,v:=1][]
#   id  v
#1:  1 NA
#2:  2 NA
```

**Comment by arunsrinivasan** [comment]
dup of #759.
