### ISSUE TITLE
Conditional Merge in Data.table

### ISSUE THREAD

**Issue by ywhuofu** [Rdatatable/data.table#829]
As switching from SAS to R, I really enjoy using data.table for the syntax simplicity and efficiency. But I wonder if a conditional join / merge can be implemented. I found a similar issue in package `dplyr`. See 
https://github.com/hadley/dplyr/issues/557. Is there anyway to do this in data.table? 

Thanks

**Comment by ywhuofu** [comment]
@matthieugomez . I am sorry that  wasn't following github constantly. I clicked your link and don't see the function you mentioned? Have you found a nicer solution to this problem? Because of this type of joins (sql inequality join), I now use Postgresql as back-ends to do this type of work, and then pips data back to R for analysis.  

If you have a solution, I am very eager to learn! 

Thank you!

**Comment by ywhuofu** [comment]
@arunsrinivasan, I just noticed your post, and I find `overlaps()` is a great new feature, but lacks some flexibility. 

1. In you example, you have to first add another column that is identical to `datestamp` as `end` because `foverlaps()` requires 2 columns from both data tables. 
2. You also have to modify the start column (minus 1 day) in order to have values that equal to `start` be included in the join. 

**It would be much more flexible if one can specify inequality conditions inside the join statement.**

Above being said, thank you for the work on this new feature, and look forward to see improvements!

**Comment by matthieugomez** [comment]
ywhuofu,

I only wrote a function to roll a given function with respect to a time variable. The function is much slower than foverlaps (just R code), just easier to use for me.

For a real inequality join, foverlaps is your best best. I think Arun plans to incorporate inequality join at some point directly into data.table syntax #830, which would make forverlaps easier to use for time-based joins.

**Comment by arunsrinivasan** [comment]
This'll be automatically taken care of when https://github.com/Rdatatable/data.table/issues/1452 is done.
