### ISSUE TITLE
Adding a new column by reference using := errors with "cannot allocate vector of size .."

### ISSUE THREAD

**Issue by geponce** [Rdatatable/data.table#834]
DT[,Ncol:= (t1 + t2) /2] in 64bit linux system with 124 GB RAM get the error "cannot allocate vector of size" DT ~ 50GB, hint?
Looking at the system monitor memory section, before executing the instruction the memory is in ~ 45%, once I start it the memory reaches 100% usage and that's when start getting the allocation issues... 
Is this making copies of DT ? Is eating over 60GB ram in a single process on a fresh R session... I save/load the DT using saveRDS/readRDS.

**Comment by Ic3fr0g** [comment]
I believe `lapply` is the right way to do it ?

**Comment by jangorecki** [comment]
Not sure it issue is relevant anymore, but after `readRDS` you have to use `setDT`. Otherwise `:=` might try to do a copy. If you are able to provide reproducible example (after using `setDT`) please reopen.
