### ISSUE TITLE
fread:  `nrows = 15` OK. `nrows = 16` FAIL

### ISSUE THREAD

**Issue by rsaporta** [Rdatatable/data.table#849]
I have a file with an incomplete row in line 389.
This file also has two irrelevant text lines at the top of the file.  

Thus, I would use `skip = 2` and `nrow = `385`

Unfortunately, fread is complaining about the incomplete line, when it should stop before then. 
`read.table` succeeds in the identical situation (and `read.table` will complain with `nrows=386`)

    read.table(f, header=TRUE, sep="\t", skip=2, nrows=385, stringsAsFactors=FALSE)
         fread(f, header=TRUE, sep="\t", skip=2, nrows=385, stringsAsFactors=FALSE)

    Error in fread(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE,  :
      Expected sep ('\t') but '\n' ends field 4 on line 3 when detecting types:
      < line of data shown is line 389, which is incomplete >

`fread` complains even with nrow as small as `16`.  
Interestingly, if we shrink nrows down to `nrows=15`, then fread works correctly.

    fread(f, header=TRUE, sep="\t", skip=2, nrows=15, stringsAsFactors=FALSE)
    ## SUCCESS

    fread(f, header=TRUE, sep="\t", skip=2, nrows=16, stringsAsFactors=FALSE)
    ## Same error as with `nrow=385`.  The line of data shown is 389, long after 16. 

I am not familiar with the `fred.c` code, but a simple grep hints that the issue might lay somewhere in the for loop at line 732 
    
    for (j=0; j<(nrow>15?3:1); j++)  {
    ...
    }

**Comment by arunsrinivasan** [comment]
@rsaporta could you share the file? I'd be happy to take a look at it.

**Comment by arunsrinivasan** [comment]
@rsaporta could you please provide an update for this?

**Comment by arunsrinivasan** [comment]
Rick, please re-open this once you've a file link or code with which we can reproduce this.

**Comment by rsaporta** [comment]
Hey Arun,  Unfortunately, I cannot share the file as it is not my data.    If I find some downtime I will try to troubleshoot it further
