### ISSUE TITLE
R CMD check NOTE: No visible binding for global variable

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#850]
Packages using data.table (and I believe dplyr as well) get this NOTE (perhaps many) from R CMD check.  Is there anything we can do?  It is only a NOTE so can be ignored, but even so.

Perhaps provide a function that detects those symbols and creates the `globalVariables()` call automatically for the package author.

http://stackoverflow.com/questions/15409806/r-package-compilation-with-dependency-on-data-table
http://stackoverflow.com/questions/8096313/no-visible-binding-for-global-variable-note-in-r-cmd-check

IIUC, it would need a change to 'R CMD check' to make it aware of "non-standard-evaluation" that both data.table and dplyr use. That is a hard problem (perhaps even impossible without running the code).  So functions `?globalVariables` was added to R in 2.15.1 and lesser known perhaps is that `?dontCheck` was added in R 3.1.0 which can be used to wrap queries using NSE.  These are better than `<-NULL` which has the risk of silencing true errors (or perhaps creating new ones) in other areas of the code, as well as the ones using NSE.

**Comment by cderv** [comment]
Hi, 
it is an old issue but not closed. I was wondering if there is now a new solution ?
Otherwise, what is the good practice to follow ? still `globalVariables` ?

I like the idea of 

>  a function that detects those symbols and creates the `globalVariables()`

Thank you.

**Comment by jangorecki** [comment]
@cderv you can just assign NULL to the variable before using it (not confuse with override it). So you are not defining global variables, but just defining them locally in a function where you are using them. I don't think we need to address that in any special way, this is a matter of R CMD check strictness.

**Comment by jangorecki** [comment]
Proposed way works very good. Another way we could consider supporting can be something similar to the way dplyr deals with it: https://dplyr.tidyverse.org/articles/in-packages.html#data-masking-and-tidy-selection-notes

**Comment by d-morrison** [comment]
> Another way we could consider supporting can be something similar to the way dplyr deals with it: https://dplyr.tidyverse.org/articles/in-packages.html#data-masking-and-tidy-selection-notes

@jangorecki just wanted to add my support for this option; it would be a big help for my team, which is split between data.table and dplyr users, to have a similar solution across both!

**Comment by jangorecki** [comment]
AFAIK there is an ongoing work in base R to address this issue, so we could possibly wait and address it in the base R way instead

**Comment by MichaelChirico** [comment]
Yes: https://bugs.r-project.org/show_bug.cgi?id=14354

I strongly prefer waiting for full `declare()` support in R itself.
