### ISSUE TITLE
Fill in missing data

### ISSUE THREAD

**Issue by matthieugomez** [Rdatatable/data.table#854]
http://stackoverflow.com/questions/26171958/fill-in-missing-values-by-group-in-data-table

IMO, the best syntax  would be  a function `fill_na`

``` R
DT[, value_filled := fill_na(value, roll , rollends), by = id]
```

but it would require some work - I'm not even sure it's feasible. 

An easier solution would be a function `setna` that works depending on the keys of DT

``` R
setna <- function(.data, cols,roll = TRUE ,  rollends = if (roll=="nearest") c(TRUE,TRUE)
  else if (roll>=0) c(FALSE,TRUE)
  else c(TRUE,FALSE)){
  keys <- key(.data)    
  if (length(keys)<1){
    stop(".data must be keyed by at least one variable")
  }   
  for (col in cols){
    eval(substitute(.data[, (col) := .data[!is.na(x)][.data, value, roll = roll, rollends = rollends]], list(x = as.name(col))))
  }
}
setkey(DT, id, date)
setna(DT, "value")
```

**Comment by jangorecki** [comment]
When/if support for character columns will be provided, the following question can be answered: https://stackoverflow.com/q/20535505/2490497
