### ISSUE TITLE
[Request] convert DT to xts efficiently

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#882]
Proposed feature request:

As data.table is used in finance I wonder if we could convert to `xts` by reference?
Assumptions:
 - first column contain `POSIXct` or `Date`
 - because xts is a matrix all other columns needs to be `numeric` or `integer` (others would be dropped)
 - `setDT` should also accept xts object to ensure the following is TRUE: `setXTS(setDT(xts_obj)) == xts_obj`

This may enhance the integration of data.table with already well developed functionalities around `xts`.

**Comment by jangorecki** [comment]
I've pushed it as a new DT branch: https://github.com/jangorecki/data.table/tree/as.xts
Tests are ready (as `testthat` at the moment) but not yet merged into `tests.Rraw`.
Am I correct they should be transformed into `test(num,x,y)` tests?
I will PR it to `1.9.7`.

**Comment by arunsrinivasan** [comment]
@jangorecki looks great! Looks like you've .Rd files now. If they've to be merged to .Rraw, then yes, they have to be converted. I can help with that.

But if you'd like to keep the file as-is, then maybe @lianos can help? He has setup tests for S4-classes using `testthat` framework. 

I'll push a `as.data.table.default` method. `xts` should be in `suggests` and should the examples be wrapped with `\dontrun{}`?

**Comment by lianos** [comment]
Yes, can help w/ tests if you want to keep w/ `testthat` -- I'm not actually sure if these are being run anymore? We can migrate this to the new suggested layout for testthat tests if so ...

**Comment by jangorecki** [comment]
There is not need to use `testthat` if current `test` process is working fine. It should be straight to transfer `expect_equal` calls.
I will do the edits and merge into one commit before PR. Unfortunately I can't make *cran check* to work.

**Comment by arunsrinivasan** [comment]
Great. I can help you with that.. You can go ahead and make the PR...

**Comment by arunsrinivasan** [comment]
@lianos missed your reply before, sorry. I'm not sure if they're being run. I assumed so. What's the new suggested layout you refer to?

**Comment by jangorecki** [comment]
I've pushed PR, `dontrun` and `tests.Rraw`. Let me know if everything ok so I can merge them as single commit (there are two commits at the moment).
