### ISSUE TITLE
funding / donation to data.table project

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#903]
Inspired by #580 I would like to raise a suggestion to setup a funding / donation channel for data.table project.
Personally I couldn't afford donation anytime soon but I can image a serious companies which relies their data processing on data.table therefore they may in fact gain profits by funding and speeding up the bug fixes or improvements in the package.

**Comment by jangorecki** [comment]
closing as there are no real action points for that issue.

**Comment by mattdowle** [comment]
@zachmayer In case you didn't see the update on #580, fwrite() is now available in dev.

**Comment by daroczig** [comment]
I just looked if it's possible to set up a recurring donation for `data.table` using GH's sponsors feature, but I was not able to find a way to do so. Any of the core devs willing to set up a profile at https://github.com/sponsors? :pray:
