### ISSUE TITLE
Add DT[a==1][, b:=1] vs DT[a==1, b:=1] to ?":="

### ISSUE THREAD

**Issue by matthieugomez** [Rdatatable/data.table#905]
I could not find anything in the documentation about how

````R
DT <- data.table (a = 1)
DT[a==1][, b:=1]
````
is actually different from

````R
DT <- data.table (a = 1)
DT1 <- DT[a==1]
DT1[,  b := 1]
````

Maybe the distinction should be written somewhere. This behavior surprised me.

**Comment by arunsrinivasan** [comment]
Added as `Note` to `?":="`.
