### ISSUE TITLE
fread dec=","

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#917]
As raised on S.O. [here](http://stackoverflow.com/questions/19958431/decimal-point-setting-in-fread-data-table) and [here](http://stackoverflow.com/questions/14440661/dec-argument-in-data-tablefread)

The issue is that fread uses C function strtod which retrieves the decimal separator from the current locale. Either we'd need to find another function or set the locale and be careful to set it back again. Knowing the locale name to change to is tricky to do in a portable way, and then we'd need to check it really does provide the desired dec.

**Comment by CarlesCG** [comment]
This feature is awesome! Thank you guys ^^
