### ISSUE TITLE
data.table not printed when it should

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#939]
Following code will not print DT in the first attempt.

```R
library(data.table)
library(jsonlite)
lot.dict.new <- setkeyv(setDT(fromJSON("https://api.hitbtc.com/api/1/public/symbols")[["symbols"]]),"symbol")[,c("step","lot","takeLiquidityRate","provideLiquidityRate") := lapply(.SD, as.numeric), .SDcols=c("step","lot","takeLiquidityRate","provideLiquidityRate")]
lot.dict.new # there is no print here
lot.dict.new # it works when trying for a second time
```
it is reproducible on my machine:

```R
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
data.table 1.9.5 as of 2014-11-02
```

**Comment by arunsrinivasan** [comment]
Moved to 1.9.8

**Comment by franknarf1** [comment]
Same with `merge`: 

    merge(data.table(a=1,b=2),data.table(a=1,d=2), by="a")
    # prints nothing

(I'm assuming this is the same issue based on the title and its still being open.)

**Comment by malcook** [comment]
I find this to be the case using data.table_1.9.6 in R 3.3.1 - but I can not yet characterize it sufficiently to warrant a new issue here.  Just sayin'
