### ISSUE TITLE
In function fread automaticaly detected columnn type! 

### ISSUE THREAD

**Issue by Jureiss** [Rdatatable/data.table#942]
When I read data 
,"x"
1,1
2,1
3,1
4,2
5,3
5,
5,
5,
5,
6,6A
1,
2,
3,
4,
5,
5,
6,6A
5,
5,
5,
7,
8,
9,
10,
11,

with fread function I get error:
Warning message:
In fread("f:/data.csv") :
  Bumped column 2 to type character on data row 6, field contains '6A'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.

May be can something do for fread if function not check not right type of character.

**Comment by arunsrinivasan** [comment]
What you got is a *warning*, not *error*. And with `1.9.5`, it reads fine (even without the warning). Please re-open if you still have trouble with `v1.9.5`.
