### ISSUE TITLE
[Question] what is the most efficient way to persist to disk a data.table?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [Rdatatable/data.table#943]
I am starting on a project dealing with large datasets.  Of course data.table will be at the centre of our architecture, but we will need to quickly save and retrieve possibly millions of rows on disk.
I am sure you are familiar how the data.frame is mapped "directly" onto various DB (e.g. Postgres with PivotalR etc.).
Has anybody done something similar for data.table (beside the great fread of course)? 
Am I right in assuming that the ideal DB for data.table would be a key-value store?
Is anything similar planned?
Thanks!

**Comment by jangorecki** [comment]
The fastest you may get in fact can be SQLite, not R binary files which is a bit strange.
Timing on 1e7 rows in seconds
```
sqlite_memory          15.59166
sqlite                 18.33587
rds                    40.28054
csv               	   167.86923
```

**Comment by smartinsightsfromdata** [comment]
@jangorecki Fine to close and "converge comments on #726

I've got similar results as well (e.g. sqlite as the fastest way to persist on disk etc.).

**Comment by jangorecki** [comment]
If you work in c++ you can take a loot at levelDB, they finally provide some better docs: https://github.com/google/leveldb
and the [performance is stunning](http://highscalability.com/blog/2011/8/10/leveldb-fast-and-lightweight-keyvalue-database-from-the-auth.html) even vs sqlite which is already very fast.
Besides it has [interesting features like](http://highscalability.com/blog/2011/8/10/leveldb-fast-and-lightweight-keyvalue-database-from-the-auth.html).

- Largest tested database: 1 billion entries with 16 byte keys and 100 byte values (roughly 100 GB of raw data, about half that after compression).
- LevelDB has been Open Sourced.
- Data is written in sorted order.

**Comment by cronacronis** [comment]
See [SSDB project](https://github.com/ideawu/ssdb), which has Redis API and is based on LevelDB. Together with [RCppRedis](http://dirk.eddelbuettel.com/code/rcppredis.html) it might be a way to go. Current key limit is 120MB.

**Comment by skanskan** [comment]
Two other options:
fst package:
http://blog.revolutionanalytics.com/2017/02/fst-fast-serialization-of-r-data-frames.html

MonetDB: 
https://www.monetdb.org/blog/monetdblite-r
