### ISSUE TITLE
fread() reads incorrectly when there are double quotes followed by comma

### ISSUE THREAD

**Issue by naruchan** [Rdatatable/data.table#947]
Noticed this today, which had me pulling at my hair for awhile trying to figure out why my data seemed incorrect. It seems like something about a comma after two double quotes within a string confuses fread. 

**GOOD:**
"She said ""have a nice day!"" Then she left the party."

fread() turns this into:
"She said \"\"have a nice day!\"\" Then she left the party." 

**BAD:**
"My examples include ""Exhibit 1"", etc. You would not understand."

fread() turns this into:
"My examples include \"\"Exhibit 1\""

and it splits to the next column with:
" etc. You would not understand.\""

Is there anyway to work around this?

**Comment by and3k** [comment]
Hi!

isn’t this behaviour wrong? According to [Wikipedia](http://en.wikipedia.org/wiki/Comma-separated_values) a pair of quotation marks should be converted into one.

CSV:
"She said ""have a nice day!"" Then she left the party."
Desired results in R:
"She said \"have a nice day!\" Then she left the party." 

Best,
Bela
