### ISSUE TITLE
data.table column creation with `:=` and double indexing

### ISSUE THREAD

**Issue by hraoyama** [Rdatatable/data.table#954]
Refer to : [stackoverflow issue](http://stackoverflow.com/questions/26949827/data-table-column-creation-with-and-double-indexing?noredirect=1#comment42441244_26949827)

I am processing a data.table instance and looking to create an extra column using := this worked fine until I did some double indexing.

To duplicate:

```R
example_data$MONTH = apply(example_data,1, function(x) { strsplit(as.character(x[["V3"]]),"\\.")[[1]][1]})
```
a natural syntax is:

```R
example_data[,MONTH:=strsplit(as.character(V3),"\\.")[[1]][1]]
```

However the double indexing is not being interpreted as I intended, because it is changing all values to the outcome of the first row. Removing the indexing does perform the correct operation (just not extracting and placing the data in the right place)

As Arun says:

> *You need the same apply (or better sapply) to get the first element of each list. But we should provide a function to do this conveniently. Could you please file an issue here? –  Arun 1 hour ago*

**Comment by arunsrinivasan** [comment]
Implemented `transpose()` and `tstrsplit()` in commit d5e49fbd77327968095219a2905ee5be68e56a6b.
Also updated [the relevant SO post](http://stackoverflow.com/a/28183977/559784).
