### ISSUE TITLE
[Request] Please consider defaulting to auto.index=FALSE in 1.9.6

### ISSUE THREAD

**Issue by gsee** [Rdatatable/data.table#960]
If the default for version 1.9.6 were options(datatable.auto.index=FALSE), I believe it would create a more stable CRAN release.  You could turn it right back on in 1.9.7 while you continue to fine-tune it.  I think it's a great feature, but it's not fully mature yet.  Thank you for considering.

**Comment by arunsrinivasan** [comment]
I think we don't need to default to FALSE (even though I understand the concern). The fix, AFAICT, is quite clear / should not be that hard to make.

For the moment, we hook auto indexing (AI) iff `SEXPTYPE(LHS) >= SEXPTYPE(RHS)`. This'd mean:
1. `x == y` where x is an integer and y is a list would *not* use AI
2. `x == y` where x is an integer and y is numeric type would *not* use AI etc..
(not sure how base handles cases where both are lists, I think it converts both to character vectors).

This should make things consistent with base, and later we can improve specific cases.

**Comment by gsee** [comment]
Just to explain where I was coming from...  For a long time (since 1.8.[single digit]) each time we would update data.table, something would break.  I think that every release in recent memory has included new features and there hasn't been a bugfix only release to create a stable version to roll back to (not complaining; most of the new features are awesome and useful).  At work, we usually use a development version of data.table, but we have to replace some files to work around bugs.  So, it is not easy to roll back to a version that works for everything.  Aside from the new auto.index feature, we almost had a stable CRAN release that we could always roll back to, which makes it less scary to update data.table.  

If I were you and I saw a request to set `options(datatable.auto.index=FALSE)`, I would think, "why doesn't this guy just set it in his .Rprofile and not bother us?!"  The reason is that we have over 300 cron jobs that start with either `Rscript --vanilla` or `R --vanilla` because we thought that was a good idea a few years ago.  At this point, we've updated all the scripts to include the option and added it to Rprofile.site.  However, I think it would be good at some point push a version to CRAN with no known issues and with no new features (that may introduce issues since they haven't been tested in the wild).  As always, just my 2 cents.

**Comment by arunsrinivasan** [comment]
Not sure how we can test major features though. It is very likely to have bugs (as it might not be extensively tested on every scenario that many users would come across).

But point taken. We could've default'd to FALSE while testing it. Will keep this in mind for future releases. Can't do much on this feature. However, I'll try and fix the other bugs before this release (at least the ones reported).
