### ISSUE TITLE
Read irregular format text file using data.table

### ISSUE THREAD

**Issue by tungttnguyen** [Rdatatable/data.table#964]
I'm wondering if data.table can be used to read a text file that originally posted here
http://stackoverflow.com/questions/25314749/read-irregular-format-text-file-mixed-of-text-with-without-space-and-numbers

Using read.table or read.zoo is too slow for a 100,000+ line text file.

Any suggestion? Thanks!

P.S: another similar sample text file is below

c("  USAF  WBAN YR--MODAHRMN DIR SPD GUS CLG SKC L M H  VSB MW MW MW MW AW AW AW AW W TEMP DEWP    SLP   ALT    STP MAX MIN PCP01 PCP06 PCP24 PCPXX SD", 
"727857 94129 200601010053 080   8 **\*  47 OVC \* \* \* 10.0 *\* *\* *\* *\* 61 *\* *\* *\* \*   45   40  987.5 29.14  898.6 **\* **\*  0.00T****\* ****\* ****\* *\* ", 
"727857 94129 200601010153 120   8 **\*  39 OVC \* \* \*  3.0 *\* *\* *\* *\* 63 *\* *\* *\* \*   45   40  988.0 29.16  899.3 **\* **\*  0.07 ****\* ****\* ****\* *\* ", 
"727857 94129 200601010253 280   6 **\*  32 OVC \* \* \*  7.0 *\* *\* *\* *\* 61 *\* *\* *\* \*   44   40  988.9 29.19  900.2 **\* **\*  0.13 ****\* ****\*  0.19 *\* ", 
"727857 94129 200601010315 270   8 **\*  32 OVC \* \* \*  5.0 *\* *\* *\* *\* 61 10 *\* *\* \*   43   41 *****\* 29.20  900.5 **\* **\*  0.02 ****\* ****\* ****\* *\* ", 
"727857 94129 200601010329 250  16 **\*   6 OVC \* \* \*  6.0 *\* *\* *\* *\* 61 10 *\* *\* \*   43   41 *****\* 29.22  901.1 **\* **\*  0.02 ****\* ****\* ****\* *\* ", 
"727857 94129 200601010353 240  25  33   6 OVC \* \* \*  6.0 *\* *\* *\* *\* 61 10 *\* *\* \*   40   36  991.5 29.25  902.1 **\* **\*  0.02 ****\* ****\* ****\* *\* ", 
"727857 94129 200601010402 240  30  39  20 OVC \* \* \*  9.1 *\* *\* *\* *\* 61 *\* *\* *\* \*   37   34 *****\* 29.26  902.4 **\* **\*  0.00T****\* ****\* ****\* *\* ", 
"727857 94129 200601010424 240  26  34   8 OVC \* \* \* 10.0 *\* *\* *\* *\* 61 *\* *\* *\* \*   36   34 *****\* 29.27  902.7 **\* **\*  0.00T****\* ****\* ****\* *\* ", 
"727857 94129 200601010453 240  24  32   6 OVC \* \* \*  5.0 *\* *\* *\* *\* 71 10 *\* *\* \*   36   33  993.6 29.31  904.0 **\* **\*  0.00T****\* ****\* ****\* *\* ", 
"727857 94129 200601010526 250  23  38   6 OVC \* \* \*  1.8 *\* *\* *\* *\* 71 10 *\* *\* \*   34   32 *****\* 29.35  905.2 **\* **\*  0.00T****\* ****\* ****\* *\* ", 
"727857 94129 200601010551 250  23  32   6 **\* \* \* \*  2.0 *\* *\* *\* *\* 71 10 *\* *\* \*   36   32 *****\* 29.39  906.5 **\* **\* ****\* ****\* ****\* ****\* *\* ", 
"727857 94129 200601010553 250  23  31   6 OVC \* \* \*  2.0 *\* *\* *\* *\* 71 10 *\* *\* \*   35   32  996.4 29.39  906.5  45  34  0.01  0.23 ****\* ****\* *\* ", 
"727857 94129 200601010605 250  22  33   6 OVC \* \* \*  1.3 *\* *\* *\* *\* 71 10 *\* *\* \*   34   32 *****\* 29.41  907.1 **\* **\*  0.00T****\* ****\* ****\* *\* ", 
"727857 94129 200601010633 250  21  26   4 OVC \* \* \*  1.3 *\* *\* *\* *\* 71 10 *\* *\* \*   34   32 *****\* 29.45  908.4 **\* **\*  0.02 ****\* ****\* ****\* *\* ", 
"727857 94129 200601010653 250  18  25   4 OVC \* \* \*  1.8 *\* *\* *\* *\* 71 10 *\* *\* \*   34   32  999.1 29.47  909.0 **\* **\*  0.03 ****\* ****\* ****\* *\* ", 
"727857 94129 200601010707 250  17  23   4 OVC \* \* \*  2.5 *\* *\* *\* *\* 71 10 *\* *\* \*   34   32 *****\* 29.48  909.3 **\* **\*  0.01 ****\* ****\* ****\* *\* ", 
"727857 94129 200601010716 260  11 **\*   4 OVC \* \* \*  4.0 *\* *\* *\* *\* 71 10 *\* *\* \*   36   32 *****\* 29.49  909.6 **\* **\*  0.01 ****\* ****\* ****\* *\* ", 
"727857 94129 200601010748 250  15 **\*   2 OVC \* \* \*  1.8 *\* *\* *\* *\* 61 10 *\* *\* \*   36   34 *****\* 29.51  910.2  47  34  0.01 ****\* ****\* ****\* *\* "
)

**Comment by mattdowle** [comment]
Not sure why this one was closed. Let's revisit and confirm why.

**Comment by MichaelChirico** [comment]
I think FWF is out of scope for data.table. I could get the vector in the OP read decently well using the new option to specify a number of columns in `fill=` and supplying various lengths of `*` as `na.strings=`:

```
fread(text=x, sep = " ", header=TRUE, fill=length(unlist(strsplit(x[1], " "))), na.strings=strrep("*", 1:6))
      USAF  WBAN YR--MODAHRMN   DIR   SPD   GUS   CLG    SKC      L      M
     <int> <int>        <i64> <int> <int> <int> <int> <char> <lgcl> <lgcl>
 1: 727857 94129 200601010053    80     8    NA    47    OVC     NA     NA
 2: 727857 94129 200601010153   120     8    NA    39    OVC     NA     NA
 3: 727857 94129 200601010253   280     6    NA    32    OVC     NA     NA
 4: 727857 94129 200601010315   270     8    NA    32    OVC     NA     NA
 5: 727857 94129 200601010329   250    16    NA     6    OVC     NA     NA
 6: 727857 94129 200601010353   240    25    33     6    OVC     NA     NA
 7: 727857 94129 200601010402   240    30    39    20    OVC     NA     NA
 8: 727857 94129 200601010424   240    26    34     8    OVC     NA     NA
 9: 727857 94129 200601010453   240    24    32     6    OVC     NA     NA
10: 727857 94129 200601010526   250    23    38     6    OVC     NA     NA
11: 727857 94129 200601010551   250    23    32     6   <NA>     NA     NA
12: 727857 94129 200601010553   250    23    31     6    OVC     NA     NA
13: 727857 94129 200601010605   250    22    33     6    OVC     NA     NA
14: 727857 94129 200601010633   250    21    26     4    OVC     NA     NA
15: 727857 94129 200601010653   250    18    25     4    OVC     NA     NA
16: 727857 94129 200601010707   250    17    23     4    OVC     NA     NA
17: 727857 94129 200601010716   260    11    NA     4    OVC     NA     NA
18: 727857 94129 200601010748   250    15    NA     2    OVC     NA     NA
         H   VSB     MW     MW     MW     MW    AW    AW     AW     AW      W
    <lgcl> <num> <lgcl> <lgcl> <lgcl> <lgcl> <int> <int> <lgcl> <lgcl> <lgcl>
 1:     NA  10.0     NA     NA     NA     NA    61    NA     NA     NA     NA
 2:     NA   3.0     NA     NA     NA     NA    63    NA     NA     NA     NA
 3:     NA   7.0     NA     NA     NA     NA    61    NA     NA     NA     NA
 4:     NA   5.0     NA     NA     NA     NA    61    10     NA     NA     NA
 5:     NA   6.0     NA     NA     NA     NA    61    10     NA     NA     NA
 6:     NA   6.0     NA     NA     NA     NA    61    10     NA     NA     NA
 7:     NA   9.1     NA     NA     NA     NA    61    NA     NA     NA     NA
 8:     NA  10.0     NA     NA     NA     NA    61    NA     NA     NA     NA
 9:     NA   5.0     NA     NA     NA     NA    71    10     NA     NA     NA
10:     NA   1.8     NA     NA     NA     NA    71    10     NA     NA     NA
11:     NA   2.0     NA     NA     NA     NA    71    10     NA     NA     NA
12:     NA   2.0     NA     NA     NA     NA    71    10     NA     NA     NA
13:     NA   1.3     NA     NA     NA     NA    71    10     NA     NA     NA
14:     NA   1.3     NA     NA     NA     NA    71    10     NA     NA     NA
15:     NA   1.8     NA     NA     NA     NA    71    10     NA     NA     NA
16:     NA   2.5     NA     NA     NA     NA    71    10     NA     NA     NA
17:     NA   4.0     NA     NA     NA     NA    71    10     NA     NA     NA
18:     NA   1.8     NA     NA     NA     NA    61    10     NA     NA     NA
     TEMP  DEWP   SLP   ALT   STP   MAX   MIN  PCP01 PCP06  PCP24 PCPXX     SD
    <int> <int> <num> <num> <num> <int> <int> <char> <num> <lgcl> <num> <lgcl>
 1:    45    40 987.5 29.14 898.6    NA    NA 0.00T*    NA     NA    NA     NA
 2:    45    40 988.0 29.16 899.3    NA    NA   0.07    NA     NA    NA     NA
 3:    44    40 988.9 29.19 900.2    NA    NA   0.13    NA     NA  0.19     NA
 4:    43    41    NA 29.20 900.5    NA    NA   0.02    NA     NA    NA     NA
 5:    43    41    NA 29.22 901.1    NA    NA   0.02    NA     NA    NA     NA
 6:    40    36 991.5 29.25 902.1    NA    NA   0.02    NA     NA    NA     NA
 7:    37    34    NA 29.26 902.4    NA    NA 0.00T*    NA     NA    NA     NA
 8:    36    34    NA 29.27 902.7    NA    NA 0.00T*    NA     NA    NA     NA
 9:    36    33 993.6 29.31 904.0    NA    NA 0.00T*    NA     NA    NA     NA
10:    34    32    NA 29.35 905.2    NA    NA 0.00T*    NA     NA    NA     NA
11:    36    32    NA 29.39 906.5    NA    NA   <NA>    NA     NA    NA     NA
12:    35    32 996.4 29.39 906.5    45    34   0.01  0.23     NA    NA     NA
13:    34    32    NA 29.41 907.1    NA    NA 0.00T*    NA     NA    NA     NA
14:    34    32    NA 29.45 908.4    NA    NA   0.02    NA     NA    NA     NA
15:    34    32 999.1 29.47 909.0    NA    NA   0.03    NA     NA    NA     NA
16:    34    32    NA 29.48 909.3    NA    NA   0.01    NA     NA    NA     NA
17:    36    32    NA 29.49 909.6    NA    NA   0.01    NA     NA    NA     NA
18:    36    34    NA 29.51 910.2    47    34   0.01    NA     NA    NA     NA
       V34
    <lgcl>
 1:     NA
 2:     NA
 3:     NA
 4:     NA
 5:     NA
 6:     NA
 7:     NA
 8:     NA
 9:     NA
10:     NA
11:     NA
12:     NA
13:     NA
14:     NA
15:     NA
16:     NA
17:     NA
18:     NA
```
