### ISSUE TITLE
[Question] Autocompletion in RStudio

### ISSUE THREAD

**Issue by larmarange** [Rdatatable/data.table#984]
Would it be possible to have autocompletion in RStudio compatible with data.table to easily select variables within the [] of a data.table?

**Comment by sanjmeh** [comment]
I am having trouble seeing autocompletion but NOT inside `[`.
Autocompletion does not give any parameter names of the function `dcast` e.g. `fun.aggregate` which I have to type out everytime. Is this something tackled on a different thread?

**Comment by MichaelChirico** [comment]
@sanjmeh works fine for me.

![screen shot 2018-07-25 at 9 54 14 am](https://user-images.githubusercontent.com/7606389/43175244-bcdcaee8-8ff0-11e8-906e-efb9ce260862.png)
