### ISSUE TITLE
Unnecessary warning from gmean about sum greater than integer can hold

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#986]
See at 3:01 into this video :
https://www.youtube.com/watch?v=AmE4LXPQErM

**Comment by jangorecki** [comment]
```r
data.table(a=c(1L,1L), v=c(2e9L, 2e9L))[, mean(v), a]
#       a    V1
#   <int> <num>
#1:     1 2e+09
#Warning message:
#In gmean(v) :
#  The sum of an integer column for a group was more than type 'integer' can hold so the result has #been coerced to 'numeric' automatically for convenience.
```
is it fine to add extra argument to `gsum` called `silent` or `ignore_overflow`?

**Comment by HughParsonage** [comment]
Or just suppress the warning altogether? The average of an integer vector isn't an integer anyway, so avoiding coercion is not a concern.

**Comment by MichaelChirico** [comment]
@jangorecki yea it seems like this is the most expedient way in the current API. Problem is that is a registered routine from R so it needs a bit more effort.

What would be easier is if we have access to a `suppressWarnings` function from the C level, and we could just wrap `gmean`'s `gsum` call here:

```
ans = PROTECT(suppressWarnings(gsum(x,narm))); protecti++;
```

I don't think that's possible though? So a new argument is the way to go...
