### ISSUE TITLE
Misleading error when trying to do fread("folder")

### ISSUE THREAD

**Issue by vlsi** [Rdatatable/data.table#989]
If trying to `fread("folder")` a misleading error occurs:
```
>fread("~")
Error in fread("~") : 
  Opened file ok, obtained its size on disk (0.0MB), but couldn't memory map it.
This is a 64bit machine so this is surprising. Please report to datatable-help
```

I guess the error can be improved for such case.

**Comment by arunsrinivasan** [comment]
Thanks for the report. Reproducible. Please make sure you've read the [contribution guidelines](https://github.com/Rdatatable/data.table/blob/master/Contributing.md).

**Comment by scottgrimes** [comment]
I got the same error. Any developments on fixing it?

**Comment by MichaelChirico** [comment]
Is checking this equivalent to finding 0 MB file?

**Comment by jangorecki** [comment]
@MichaelChirico Not sure, but I think they may refer to `fread` on directory.

**Comment by MichaelChirico** [comment]
@jangorecki yes, I'm wondering if we have to do anything more complicated then adding an `if size = 0 print("this is a directory")` approach.

**Comment by jangorecki** [comment]
better then relying of size would be to use `file.info("path")$isdir`

**Comment by MichaelChirico** [comment]
@jangorecki better than going in base would (could?) be to attack this as the [internals of `file.info`](https://github.com/wch/r-source/blob/ce8b7a5499a9243d4af4a81fc8870be325eba84c/src/main/platform.c#L864) do:

    LOGICAL(isdir)[i] = (sb.st_mode & S_IFDIR) > 0;

(though to be honest I don't understand how the RHS of that code works)
