### ISSUE TITLE
Invalid HTML in README.md

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#991]
From Kurt Hornik to many package maintainers : 
- - -
These packages contain README.md files with invalid HTML output created
by pandoc 1.12.4.2 according to W3C-validator.

I attach the HTML errors and warnings found below, and will put copies
of the corresponding HTML files up at
<http://www.r-project.org/nosvn/pandoc>.  

Please investigate the problems and fix as needed.

Afaics, many of the problems are caused by adding "raw" HTML elements in
the README.md files and not realizing that the default output format
"html" is XHTML 1 (and not HTML 5).  E.g., a raw <br> results in an end tag for "br" omitted, but OMITTAG NO was specified error.

data.table.html:
  Valid: FALSE (errors: 2, warnings: 0)
  Errors:
    line  col  message
      30  188  end tag for "br" omitted, but OMITTAG NO was specified
      30  703  invalid comment declaration: found name character outside comment but inside comment declaration

**Comment by arunsrinivasan** [comment]
I'm quite sure this is fixed.
