### ISSUE TITLE
[FR] speed of convert vector into one column data.table

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#997]
Feature Request.
Looks like an easy way to improve performance for turning a single vector into one column data.table (see below).
If you know a way how to convert `x5` into `list(x5)` *by reference* it could be even faster, also it would allow to add `setDT` *method* for vector input, below code still makes a copy on `list()` call.
```R
library(data.table)
library(microbenchmark)
x5 = sample(c(1:100),2e6, replace=TRUE)
microbenchmark(times=10L,
               r1 <- setnames(setDT(list(x5)),as.character(substitute(x5))),
               r2 <- data.table(x5),
               r3 <- as.data.table(x5))
# Unit: microseconds
#                                                           expr      min       lq       mean    median       uq       max neval
#  r1 <- setnames(setDT(list(x5)), as.character(substitute(x5)))  278.039  281.671   350.3037  360.1025  391.740   461.303    10
#                                           r2 <- data.table(x5) 5837.050 5879.731  6860.2088 6611.8420 7851.628  8128.129    10
#                                        r3 <- as.data.table(x5) 5441.409 5550.987 20911.0340 5760.3320 7726.265 81454.149    10
all.equal(r1,r2) && all.equal(r1,r3)
# [1] TRUE
```
If there is no way to `list()` by reference then maybe a `data.table(x5)` could use `setDT(list(x5))` behind the scene?

**Comment by arunsrinivasan** [comment]
Jan, would be nice, yes. The only issue is that operations by reference would also modify the vector. At least until `shallow()` is exported, there's no safe way to implement this.

**Comment by jangorecki** [comment]
Yes, I understand. That's why there can be 2 separate approaches:
- `data.table(x)` computed as `setnames(setDT(list(x)), as.character(substitute(x)))` behind the scene (non be reference).
- `setDT(x)` the same as above but only available if by reference `list(x)` is possible.

**Comment by jangorecki** [comment]
First approach from my previous post appears to builds data.table by from `x` also by reference. Increased timing seems to be related only to that fact. As I understand `shallow` for single column data.table would not change much. As Arun pointed out there is no safe way to implement this. Closing issue.
